### ISSUE TITLE
New Updates

### ISSUE THREAD

**Issue by TheLemmyW** [Cockatrice/Cockatrice#1008]
Today i installed the latest windows8.1 updates using the windows update program, then i downloaded the new cockatrice version, and successfully installed it. The problem is that now the program is not starting, i'm launching it and nothing happens.
![aggiornamenti](https://cloud.githubusercontent.com/assets/12069519/7277070/0aded84c-e90e-11e4-8d98-c6e213dd461a.png)

**Comment by TheLemmyW** [comment]
Another error occured.
![errore](https://cloud.githubusercontent.com/assets/12069519/7277193/ddcfe2aa-e90e-11e4-8c10-dfad148753f5.png)

**Comment by ctrlaltca** [comment]
try running as an administrator.

**Comment by woogerboy21** [comment]
The other thing you may try (caught this the other day).  Check your cockatrice shortcut and see if it has the --debug flag put next to the executable name in the shortcut's start string.  If it does, take it out.

**Comment by TheLemmyW** [comment]
Managed to solve the problem. I think it was a problem in the Shortcut.

**Comment by ctrlaltca** [comment]
Thank you for reporting back the problem
