### ISSUE TITLE
Invisible rooms

### ISSUE THREAD

**Issue by LethalPigeon7** [Cockatrice/Cockatrice#101]
When hosting drafts/normal games, people often tend to just leave the room open for countless hours, letting people join, just to discover that theyve joined a waste of space.

A partial solution to that would be to have a box the creator can tick, which prevents people from joining and hides the room from the Chat Room. And prefferably have it automaticly tick itself once the room is filled up.

**Comment by ZeldaZach** [comment]
See #517
