### ISSUE TITLE
convert remove/add buttons to +/- buttons

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#1012]
Use the `+` and `-` buttons in settings menu as well for adding and removing chat macros:
![add - buttons](https://cloud.githubusercontent.com/assets/9874850/7296539/db65fae2-e9c0-11e4-8a9f-6e4ec0bdb4f8.png)

We have them in deck editor and edit tokens dialog already.

**Comment by poixen** [comment]
Addressed in #1016
