### ISSUE TITLE
hex code for mentions color flashing in settings

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#1013]
If you move your mouse over the hex code and away or click it it starts flashing randomly.

http://screencast-o-matic.com/watch/cof0llfViu

**Comment by ZeldaZach** [comment]
Odd for sure. Didn't we have some kind of color wheel that would pop up?

**Comment by tooomm** [comment]
I'm totally fine with the hex color, a color wheel is overkill maybe.

We could put a link or `?-button` to a site like [this](http://www.w3schools.com/tags/ref_colorpicker.asp), [this](http://www.color-hex.com/color-palettes/popular.php), [this](http://www.color-hex.com/) or [this](http://www.colorpicker.com/) instead.
Even better than a color wheel...

**Comment by ebbit1q** [comment]
can't reproduce
