### ISSUE TITLE
Shutdown timer improvements

### ISSUE THREAD

**Issue by woogerboy21** [Cockatrice/Cockatrice#1015]
The current shutdown timer notifications are inadequate to new users that log in post the timer start and mid the last 10min warning and 5 min remaining.  It could use some improvement.  It would be nice if when a user logs in and there is a shutdown in progress that the user be notified of the time remaining before shutdown so they are aware without being blindsided at the last few minutes prior to shutdown.

**Comment by Daenyth** [comment]
:+1:

**Comment by tooomm** [comment]
The server shutdown message should trigger a desktop notification as well! :+1:

**Comment by ZeldaZach** [comment]
We've made it so alerts are sent out more frequently towards the end, so overall I think I'm fine with how it works at this point
