### ISSUE TITLE
Client Crashes on Shutdown Popup

### ISSUE THREAD

**Issue by woogerboy21** [Cockatrice/Cockatrice#1020]
It appears that after commit 3141fb8 the windows client crashes moments after the server shutdown popup windows are triggered.  Not sure what exactly is causing it nor if there is any other type of popup that could cause the client crashes.

Client version 3141fb8 works as expected.  Tested versions 924dd17 & a16f8e0 which has the crashing issue.

For those running into the issue and want a previous version of the client that does not appear to have the bug they can download 3141fb8 from http://www.woogerworks.com/files/cockatrice_weeklybuilds/old.builds/Cockatrice_win32_git-3141fb8.exe

**Comment by woogerboy21** [comment]
Also, just an FYI.  This error is not caused by the server shutdown timer changes as that code change on the server side is running.  it's most likely something client side that has changed.

**Comment by woogerboy21** [comment]
Also, to the dev guys.  To reproduce you can jump on the testing server with a bugged client version and unlock the admin tools.  Issue a shutdown for 5 min and when the 4 minute popup window happens youll shortly see the crash afterwords.  The server will shutdown and then auto restart shortly after shutdown so you can attempt to reproduce and work on it over and over if you like.

**Comment by ZeldaZach** [comment]
This happens on OS X as well

**Comment by woogerboy21** [comment]
off in the distance is a small yet noticeable sound of a diesel engine starting....
You hear that????  Sounds like the BUS coming for @poixen  :bus:

**Comment by poixen** [comment]
Fixed in #1029
