### ISSUE TITLE
P/T Issue on reconnects/spectate

### ISSUE THREAD

**Issue by 203995014** [Cockatrice/Cockatrice#1021]
This is the first time I'm making a post like this so I apologize in advance if I screwed something up. Basically I'm reporting what the title says.

_____
When you spectate someone or reconnect to a game you disconnected from, every non-creature permanent on the field shows up as a 0/0

**Comment by poixen** [comment]
Sigh. 

#1009 is the culprit

**Comment by tooomm** [comment]
this can be closed
