### ISSUE TITLE
Images will not load after troubleshooting/reinstalling

### ISSUE THREAD

**Issue by Akbaillie** [Cockatrice/Cockatrice#1026]
2015 iMac 27" 5K
I have been using the 2nd most recent client with no issues. Today I had random cards missing images. If I restarted the client it would come back sometimes, however more images started to come up missing so I cleared the image cashe. High Res images is NOT checked. After restarting, no images showed up. I deleted the client, downloaded the current version and installed. Still no images are showing. I also updated the database though Oracle, and nothing has changed. I also tried to adjust the image size database, and nothing made any difference. Any assistance is appreciated 
![screen shot 2015-04-26 at 1 31 09 pm 2](https://cloud.githubusercontent.com/assets/10547571/7339138/94d4789c-ec18-11e4-9a4d-029b34814d1e.png)

**Comment by ctrlaltca** [comment]
Thy these
1. adjust picture cache size up to 2047MB
2. ensure you can access the gatherer from your pc (cockatrice fetches images there)
3. run cockatrice from a terminal and see if you get some hints on what's going on

**Comment by Akbaillie** [comment]
So http://gatherer.wizards.com is not working for me. Maybe that has been my issue all along? My internet works just fine, all other sites work fine. Anyone else having issues with the site?

**Comment by tooomm** [comment]
just performed a search on gatherer. a bit slower maybe, but working for me.

check this for debug mode:
https://github.com/Cockatrice/Cockatrice/wiki/Debug---Logging

**Comment by ctrlaltca** [comment]
If gatherer was not working cockatrice had no place to fetch images from. There used to be a very nice alternative site (http://mtgimage.com/) in the past.

**Comment by Akbaillie** [comment]
So this gets even stranger. None of my computers can access http://gatherer.wizards.com from any computer. When I access on my phone not using my home's network, then I can see the site with no issues. If I try to access the site trough an IP blocker like newIPnow.com, the site comes up fine on my computer. Could Wizards be blocking my home's IP address?

**Comment by ZeldaZach** [comment]
That seems like a personal issue and not something related to the client. Can you try clearing your cache and restarting? Maybe that'll help. 

Gatherer goes down weekly for updates, so maybe wizards was just in a time of updates when you were trying to access the site.

**Comment by Daenyth** [comment]
Gatherer is often unreliable, that would be my first guess. Next I'd guess
you're on a school network and it's being blocked
