### ISSUE TITLE
ascending versioning instead of random hashes

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#1036]
You can never tell, just from viewing the hash in the about dialog, how old a client is.
This makes bug reports etc. more difficult. Users can't easily compare their versions or know when they should upgrade, too.

Did some quick research and found these links, hope they help:
- http://brianmilco.blogspot.de/2012/11/cmake-automatically-use-git-tags-as.html
- http://eatmyrandom.blogspot.de/2010/06/automate-version-numbering-using-git.html
- http://pukkaone.github.io/2010/12/19/build-number-git-repository.html
- http://stackoverflow.com/questions/1435953/how-can-i-pass-git-sha1-to-compiler-as-definition-using-cmake

An alternative/addition would be to add a build date next to/below our actual version hash.

---
- [x] Added **commit date** to `About` dialog next to the commit hash (#1046)
- [ ] implement some kind of version numbering, style could be: www.semver.org

**Comment by ZeldaZach** [comment]
I approve of something like this :smile:

**Comment by poixen** [comment]
Been wanting this for so long.

**Comment by Daenyth** [comment]
`git describe` should help

**Comment by woogerboy21** [comment]
Are you wanting this type of information in the help-about window or were you thinking on just the file name associated with the client installer?  Not sure the scope you intended.

**Comment by Daenyth** [comment]
Both would be best, to aid users in giving us information when they
hit problems.

**Comment by woogerboy21** [comment]
@tooomm So i just glanced at some of the articles you linked.  we currently are using the git hash for the commit and not a random generated hash.  are you thinking we are making some random hash for our releases?  it sounds to me like your wanting us to start using tagging correct?

**Comment by tooomm** [comment]
@woogerboy21 I know that the "random number" is our hashed commit. It just looks random.
You can't make any connection out of two different hashes or set them in order just by looking. That's what I don't like, but that's the nature of a hashed value.

The links I posted are just some potential helpful ideas that I found while googling.
I'm not sure if they help or provide possible solutions. That's up for discussion, and the brains here. ;)

**Comment by tooomm** [comment]
Updated the initial post... 50% done.
The date is a nice help and a great improvement, the beloved feature of real version numbers remains unresolved though.

Reopen please!

**Comment by ZeldaZach** [comment]
Sure :)

**Comment by tooomm** [comment]
Any new input here?

People tend to remember simple version numbers or memorable names way better than random commit numbers. We often run into people that need help but can't remember their last used or last working version because of that for example.

As long as we don't get real incrementing versioning working, what about pushing a commit with the name of the release (or a hardcoded version number) to the about window right before releasing?
Could be a easy workaround and very helpful for us too. ;)
I would prefer to use the nice names that we come up with every time, it wouldn't mess with (maybe different) future version numbers.
