### ISSUE TITLE
Owned/Controlled card manipulation

### ISSUE THREAD

**Issue by LethalPigeon7** [Cockatrice/Cockatrice#104]
Far too often does one accidentaly drag a card to the opponent's side of the table and has to wait for the slow opponent to give it back.(Me usually being slow opponent) I suggest that a player can interact with all cards he owns, not only controls. The only problem I can see from a user's point of view is abuse in MP, which doesnt seem relevant, since people abusing their privileges deserve a kick regardless, resulting in their cards becoming irrelevant.
*Its a minor annoyance and therefore deserves to be ignored if the solution is complicated.

**Comment by Daenyth** [comment]
I recall that Apprentice had a "request control" button; perhaps something similar here would be good.

**Comment by swalters37** [comment]
This has been opened for a while, think there's a chance for implementation ever?

**Comment by ZeldaZach** [comment]
Medium Priority tends to fall after High Priority, but if someone in the community wants to give it a shot I'd be open to a pull request.

I'm not sure how to best approach this situation at the moment, so I'd need to see some design ideas behind it

**Comment by Daenyth** [comment]
This definitely require a protocol change to be implemented.

Proposal:
- command to request control of an entity in a zone
- event to notify all players
- client event handler to prompt the user - this one may be tricky
- command to grant control

The huge problem I see here is that if we make the event handler trigger a popup window then this can be abused really easily to steal focus.
Instead I'd propose we make the handler give a soft pulsing glow to the requested card(s) until the client takes a protocol action
Or perhaps it could draw an arrow from the requested card to the requesting player

**Comment by ebbit1q** [comment]
if the player experience is just seeing an arrow and handing over the card, in what way is it different from the current system? I don't think a specific command for requesting control is needed, you already can simply ask them and they simply might be afk. the alternative is tracking card ownership, which would also be useful when players leave the game in this scenario, taking your misplaced cards to the shadow realm

**Comment by ebbit1q** [comment]
yes, that's another ticket though https://github.com/Cockatrice/Cockatrice/issues/1912

**Comment by ZeldaZach** [comment]
Closing as I feel the work done in #5348 is sufficient to meet the needs
