### ISSUE TITLE
Card images

### ISSUE THREAD

**Issue by Melisandrei** [Cockatrice/Cockatrice#1042]
I have no card images on cockatrice even after following the full FAQ guidelines and troubleshooter

**Comment by Nightfirecat** [comment]
Refer to #869 or #1000, perhaps?

**Comment by Melisandrei** [comment]
Tried but still nothing

**Comment by Melisandrei** [comment]
http://gyazo.com/ef54b3634477674ee3b8041cad343188

**Comment by Daenyth** [comment]
What version do you have? Can you check that your settings have a picture directory set? Are there files in it? Can you create a file there? If it's in program files change it to a location in your user folders

**Comment by Melisandrei** [comment]
Ive managed to fix this by reinstalling the program 4 times. CHeers
