### ISSUE TITLE
Partial Name Mention Bug

### ISSUE THREAD

**Issue by Fizztastic** [Cockatrice/Cockatrice#1050]
If someone makes a mention to a user who's name starts with your username, you'll receive a mention notice even though it's not directed to you.

![MentionBug](http://i.imgur.com/B3l2uKi.jpg)

**Comment by ZeldaZach** [comment]
Interesting for sure; I personally would find this annoying...

@poixen Any ideas?

**Comment by poixen** [comment]
It's a known issue.
