### ISSUE TITLE
Art cards

### ISSUE THREAD

**Issue by ahenaa** [Cockatrice/Cockatrice#1054]
Hi, I don't have any arts for cards on cockatrice, i tried to to the differents steps before opening this ticket, and it still does not work.

**Comment by ZeldaZach** [comment]
You tried unchecking "high quality" and updating your client ?

**Comment by ahenaa** [comment]
what do you mean by updating, i downloaded again cockatrice and installed it

**Comment by ZeldaZach** [comment]
Windows, Mac, or Linux? Can you post a debug log

**Comment by ahenaa** [comment]
Windows
How do i get the debug log ?

**Comment by Daenyth** [comment]
Unfortunately I'm not sure how/if you can get at the debug log on windows right now. @ctrlaltca maybe this can help us get console debug output on windows? http://stackoverflow.com/questions/17331999/qmakes-config-console-in-cmake

So, just to be clear, you have "download high quality pictures" unchecked in your settings? And you have permission to write to your card location you've defined in your settings? Do you have any art at all, or is it missing only for new cards?

**Comment by ahenaa** [comment]
I don't have art for every cards,  i had on some cards, then i followed the setps on the cockatrice faq, and all of them dissapeared

**Comment by ctrlaltca** [comment]
We could get create a debug package of cockatrice for windows up with the --debug-output option enabled by default and a "view debug log" menu. This could help debugging future issues.
Back to this ticket, i didn't see an answer to the first question: do you have "download high quality pictures" unchecked in your settings?

**Comment by ahenaa** [comment]
It is unchecked

**Comment by poixen** [comment]
Can you give a card name you are missing and from what set?

**Comment by ahenaa** [comment]
Every single card :)

**Comment by Daenyth** [comment]
Please attach a screenshot of your settings screen?

**Comment by poixen** [comment]
Can you confirm:
 + what pic cache is set to
 + if your pictures dir is set correctly?
 + If you navigate to the pics dir, is there anything there?

**Comment by ahenaa** [comment]
Hi, 
I changed nothing and restart cockatrice several times, and now all the cards seems to have arts

**Comment by ahenaa** [comment]
thanks a lot everyone for your time
