### ISSUE TITLE
i can't load cards images

### ISSUE THREAD

**Issue by giangi26** [Cockatrice/Cockatrice#1056]
hi im unable to see my magic cards with their properly images,i tried all of the 6 steps in the faq section,but nothing changed,may you help me?

**Comment by tooomm** [comment]
- uncheck `Download high quality pictures`, they don't work at the moment
- if you still get no images after some time check if gatherer is down

what's the version of your client?

**Comment by giangi26** [comment]
its all righthank you

Date: Tue, 5 May 2015 02:26:27 -0700
