### ISSUE TITLE
link to FAQ from somewhere in the client

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#1057]
https://github.com/Cockatrice/Cockatrice/wiki/Frequently-Asked-Questions

- about window
- menu entry
- ...

@woogerboy21 is it in the server description tab as well? (can't test right now)

---

https://github.com/Cockatrice/Cockatrice/wiki/Troubleshooting or the wiki in general are helpful as well to provide help and guide them to our issue tracker.

**Comment by Daenyth** [comment]
:+1:

**Comment by woogerboy21** [comment]
Sorry, totally missed this.  There is no direct link in the server tab for the FAQ but there is this section which references the wiki as well as the github site:
```
Troubleshooting
If you are experiencing issue's, check out the github wiki page.
Report any issue's at the github issue's page.

```
