### ISSUE TITLE
add notification about image source beeing unavailable

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#1058]
While chatting around with @ZeldaZach we had a nice idea:

> Can we look into making a popup notification for when gatherer is down so people don't make tickets asking why their cards don't work
> (If downloading and fails, say gatherer is down and only show one popup per login; if you logout and login it will appear again)

Maybe try 3 times to fetch card art, otherwise show a popup that the card art is not present in the offline database and the online image source is not available right now.
Will prevent users from tinkering around etc. and nobody can help them anyway.

This is a real issue right now and gatherer has quite some downtimes...

**Comment by Daenyth** [comment]
We'll have to have some timing information stored around this so we only
generate one message per launch otherwise we'll speak the user with
hundreds of notifications.

**Comment by tooomm** [comment]
Closing in favor of https://github.com/Cockatrice/Cockatrice/issues/1830
