### ISSUE TITLE
Chatting in local game crashes the client

### ISSUE THREAD

**Issue by RobHammann** [Cockatrice/Cockatrice#1060]
![cockatrice crash](https://cloud.githubusercontent.com/assets/12264967/7486524/36742814-f36c-11e4-8e1e-3c02e0f3ae96.png)

Typing anything in a local game causes the client to immediately crash

**Comment by ZeldaZach** [comment]
Tested on Cockatrice cf24f4a (2015-05-04) and this issue doesn't seem to occur.

Can you try updating your client?

**Comment by poixen** [comment]
I fixed this a while ago. You just need to update to a newer client.
