### ISSUE TITLE
Windows Installer Builds no longer build correctly

### ISSUE THREAD

**Issue by woogerboy21** [Cockatrice/Cockatrice#1063]
Not sure whats changed and wont be home to even begin to troubleshoot for another week but one of the more recent changes is now causing the windows installer file to not be created properly.  The mac seems to build a dmg file ok but windows fails to create the installer files.

Last successful build with installer was Cockatrice_win32_git-53f63e2.exe

**Comment by ctrlaltca** [comment]
Strange, the "package" target compiles fine for me under msvc2010.

**Comment by tooomm** [comment]
is this resolved?

**Comment by ctrlaltca** [comment]
Well, the packages seems to builds correctly here, not not on the server; we need wooger to check out what's going on on weekly releases. Reopening

**Comment by ZeldaZach** [comment]
Currently, the Mac build is not available and a few users are complaining about it. Can we get this fixed asap?

**Comment by woogerboy21** [comment]
@ZeldaZach  the more they complain the less i plan on working on it.

**Comment by woogerboy21** [comment]
@ctrlaltca 
When I attempt to compile "Package" I receive the following:
```
1>------ Build started: Project: ZERO_CHECK, Configuration: Release Win32 ------
2>------ Build started: Project: servatrice, Configuration: Release Win32 ------
2>  serversocketinterface.cpp
2>..\..\servatrice\src\serversocketinterface.cpp(167): error C2065: '__PRETTY_FUNCTION__' : undeclared identifier
2>..\..\servatrice\src\serversocketinterface.cpp(174): error C2065: '__PRETTY_FUNCTION__' : undeclared identifier
3>------ Build started: Project: ALL_BUILD, Configuration: Release Win32 ------
3>  Build all projects
========== Build: 2 succeeded, 1 failed, 4 up-to-date, 0 skipped ==========

```

**Comment by ctrlaltca** [comment]
so, #1048 is the culprit (using a macro not available under msvc). A fix is on the way.
