### ISSUE TITLE
Creating a new game: remembering last options used

### ISSUE THREAD

**Issue by pedro-walter** [Cockatrice/Cockatrice#1069]
Hi,

Usually, when I'm on a server and playtesting many games with a specific deck and format, I need to retype the room details, such as name, format options, spectators can chat, etc. Some way to remember the last options used would be a great help at saving time.

Leaving the room open not always lead to new players coming in, as they usually look for the rooms opened in the last minutes, and ignore rooms open for more than 10 minutes or so.

**Comment by Daenyth** [comment]
:+1:

**Comment by tooomm** [comment]
i think there is a ticket already?
