### ISSUE TITLE
make servatrice support correct user detail reporting for offline users and enable it again

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#107]
Steps to reproduce

1. Friend someone
1. Have them go offline
1. From user tab right click and hit user details
1. Info box shows them as unreg with no info

**Comment by tooomm** [comment]
you might want to rename this?
the issue is now "make servatrice support correct user detail reporting for offline users and enable it again"

**Comment by Daenyth** [comment]
Has the behavior changed?

**Comment by poixen** [comment]
It's always been like this from what I remember. If there was no db entry it meant you were unregistered. Also happens if a user goes offline.

**Comment by Daenyth** [comment]
It's simple to fix, the server just needs to read the user's row from the database if the user isn't online
