### ISSUE TITLE
Human vs. computer suggestion

### ISSUE THREAD

**Issue by MichaelEscott** [Cockatrice/Cockatrice#1077]
Yes, it is quite fun to play against other players online, but what if someone wants to play against a AL? There should be a single player mode so that players can test themselves in different ways. What if someone doesn't have a wifi connection and can't connect to Cockatrice Magic the gathering? Guess what single player mode is there for offline play. There could be different levels of difficulty so that the player can test his skills against the computer. Yes there is different software out there that do have Magic the gathering solo play but some people don't have to money for those or just don't want to pay for them. Cockatrice is a free software that has only multiplayer, why not have solo?

**Comment by poixen** [comment]
This would require a rules engine. The AI would need to know what the cards do and perform those actions. Cockatrice wasn't built with a rules engine in mind. 

It's a nice idea but I don't think we can do it.

**Comment by ctrlaltca** [comment]
You maybe want to try https://github.com/magefree/mage instead.
