### ISSUE TITLE
Clicking bug

### ISSUE THREAD

**Issue by deckplate** [Cockatrice/Cockatrice#1080]
The game works and launches fine, but as soon as a right-click the game seems to think my cursor stays in the same spot, where I clicked, although I am still able to move my mouse, and I am not able to do anything else. For example, if I right click the deck and click view library I am unable to close the library or move any cards because the game thinks my mouse is still over the library. Even if i use F3 to close the library window or right-click anywhere else the game still thinks the mouse is where I originally right-clicked. I have tried reintalling multiple times, running as administrator, and restarting my computer, but I still have the same problem. I have also downloaded with windows version as i have windows, and it is not a hardware problem as I do not have any other problems in other programs. I can provide pictures if needed.

**Comment by deckplate** [comment]
http://imgur.com/a/cltZa
Here is an example of me playing cards then looking all ability to move cards or click anywhere else.

**Comment by Daenyth** [comment]
Is this a new problem after upgrading? Do you have an old installer handy
to try?

**Comment by ZeldaZach** [comment]
I've never heard of something like this before.

@deckplate Have you tried restarting your computer and upgrading Cockatrice to the latest version? If not, can you try that :smile: 

If that doesn't work, we'll keep brainstorming!

**Comment by ZeldaZach** [comment]
If this is still an issue, please feel free to reopen
