### ISSUE TITLE
CIPT Flag - Shocklands enter battlefield tapped. Hideaway lands don't.

### ISSUE THREAD

**Issue by Psithief** [Cockatrice/Cockatrice#1082]
Version: 18da49d (2015-05-11)

### Should enter tapped
* [Hideaway lands](http://gatherer.wizards.com/Pages/Search/Default.aspx?action=advanced&output=spoiler&method=visual&text=+[hideaway]).
  Easy fix: `cardText.contains("Hideaway")`

### Enters tapped based on player choice.
* [Vesuva](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=287332). Leave as-is?

### Enters tapped based on player choice.

These lands now enter tapped, where previously they were untapped. Do we want this behaviour to change in this way or stay as-is?

* [Tribal lands](http://gatherer.wizards.com/Pages/Search/Default.aspx?action=advanced&output=spoiler&method=visual&type=+[%22Land%22]&text=+[tapped]+[%22don%27t%22]&block=|[%22Lorwyn%20Block%22]) (Ancient Amphitheater, Auntie's Hovel, [Flamekin Village](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=389518), Gilt-Leaf Palace, Murmuring Bosk, Primal Beyond, Rustic Clachan, Secluded Glen, Wanderwine Hub)
* Shocklands

Previously there must have been a bug where shocklands weren't caught as matching `" enters the battlefield tapped"`, but now that bug has been fixed, inadvertently changing the behaviour we expect.

The logic below needs another conditional statement to match the ravnica dual land template.

oracle/src/oracleimporter.cpp:
```c++
bool cipt = cardText.contains(cardName + " enters the battlefield tapped") &&
            !cardText.contains(cardName + " enters the battlefield tapped unless");
```

The template text is:

> ({T}: Add {?} or {?} to your mana pool)
> As CARDNAME enters the battlefield, you may pay 2 life. If you don't, CARDNAME enters the battlefield tapped.

- - -

Issue possibly introduced in fix for #670 ?

**Comment by Daenyth** [comment]
I actually like it like this. Either way we do it is technically wrong but
this way makes it a little harder to forget about the life

**Comment by Psithief** [comment]
I think you'd want to consider if the average user was a fan of the change. 

Barely anything that's been done recently has changed the expected behaviour of cards. The old behaviour is what they're used to, and leaving this is going to produce asymmetric expectations because one person has a more recent oracleimporter and their opponent has an older one.
- - -
Not changing this also means that it doesn't match the behaviour of similar cards like all the [checklands](http://gatherer.wizards.com/Pages/Search/Default.aspx?action=advanced&output=spoiler&method=visual&text=+%5Bm/::name::.enters.the.battlefield.tapped%5Csunless/%5D). 
Then there's a land like Vesuva, that has a slightly different wording (`enter` vs. `enters`) that is also a choice.

**Comment by Psithief** [comment]
I just noticed the hideaway lands (the cycle starting with Windbrisk Heights) don't enter tapped either.

I'm not sure it warrants a separate issue, this issue is more a list of "outstanding issues with CIPT flag".

Easy fix: `cardText.contains("Hideaway")`

**Comment by ZeldaZach** [comment]
I'll add that to the oracle script @Psithief

**Comment by ZeldaZach** [comment]
Fixed in #1091

**Comment by Psithief** [comment]
The issue has not been fully addressed, can it be reopened plz?

**Comment by ZeldaZach** [comment]
What's wrong?

**Comment by ZeldaZach** [comment]
@Psithief Can I have more information on what needs to be addressed here?

**Comment by Psithief** [comment]
@ZeldaZach 

1. *Shockland behaviour has changed, they now enter tapped.*
The issue was originally opened for this reason. In the end:
  * I failed to convince Daenyth to revert the behaviour
  * nor did I capture any other opinions from any other developer

2. *Hideaway lands were not entering tapped.*
This was added as an afterthought after I reviewed all lands that could enter tapped while reformatting the issue's first post. That's fixed now, but this issue was intended to focus on 1.

I'd prefer this issue left open until it gets closed and labelled "Won't Fix", because it really is just about this question:

> ## What should be the default for shocklands entering the battlefield, tapped or untapped?

**Comment by jimivyas** [comment]
Hey, I haven't really contributed to this project yet, (i do use cockatrice tho lol) but I'm fairly certain the default should be tapped. It makes sense that the default action should be based on a player *not* taking any actions.

**Comment by Daenyth** [comment]
I tend to agree (that the default is tapped)

**Comment by Psithief** [comment]
Alright.
That's probably good enough for anyone that comes looking to complain about the change.
