### ISSUE TITLE
[IDEA] Mask server latency

### ISSUE THREAD

**Issue by poixen** [Cockatrice/Cockatrice#1085]
Currently EU players are having a slower time playing. If an action is performed, there is a delay between click and the action performing. This is due to the client waiting on a server resp before performing the action requested.

Was thinking that the client could update WHILST the message is sent to the server. This would make the game feel like it should.

Issues?
- Players could be "racing" with requests and there could be some server disruption/errors
- Could make only the active player have this option available (like MTGO) but that would feel inconsistent when its not your turn. Mtgo can get away with this as they are turn based, rather than real  time.

Thoughts?

**Comment by ctrlaltca** [comment]
Misc thoughts:
 * the server can deny a command request from an user; you could get the side effect that a lagged user is convinced to have done an action and then, when the server replies, you need to rewind it;
 * some commands can't be executed until the server provides the needed information (eg: draw a card);
 * two lagged users could execute an action almost at the same time, each one being sure and arguing with the opponent that he did it first, so the stack should resolve different, etc..

**Comment by Daenyth** [comment]
The last one is nastiest. There's already a ton of opportunity for bad
interactions with people without the software appearing like game actions
are unreliable

**Comment by woogerboy21** [comment]
Personally I like the idea of having some built in mechanism to manage priority.  This would allow for a few possibilities for later development.  I haven't really thought the negatives through though.  Though the first thing that comes to mind if you want to eliminate the lag, get the multi-server code working :smile:

**Comment by ZeldaZach** [comment]
This has been dead for a while and doesn't seem relevant imo
