### ISSUE TITLE
Filter wipes textbox when the filter is changed

### ISSUE THREAD

**Issue by doombringer777** [Cockatrice/Cockatrice#1093]
In the deckbuilder changing the filter wipes the filter text box.

Here the user has some text in the filter textbox
![screenshot 2015-05-22 00 39 47](https://cloud.githubusercontent.com/assets/1956705/7751217/1f978368-001c-11e5-9bf2-9bd03b50fb92.png)
But the user realizes they want to filter by name not text
![screenshot 2015-05-22 00 39 57](https://cloud.githubusercontent.com/assets/1956705/7751225/23200bcc-001c-11e5-8f90-3bd3663814cb.png)
and now the textbox has been wiped when the user wanted to use that search term. Forcing them to retype it.
![screenshot 2015-05-22 00 40 04](https://cloud.githubusercontent.com/assets/1956705/7751228/25f1e69a-001c-11e5-9d97-b00173c3395d.png)

**Comment by Daenyth** [comment]
Seems reasonable to change the behavior here :+1:

**Comment by ZeldaZach** [comment]
I fixed this in https://github.com/ctrlaltca/Cockatrice/pull/5
