### ISSUE TITLE
Shutdown Timer Limitation

### ISSUE THREAD

**Issue by woogerboy21** [Cockatrice/Cockatrice#1097]
Apparently when going to create an extended shutdown time period on the main woogerworks cockatrice server it appears the GUI only allows you to make a maximum timer of 99 minutes.  Is there a way we can get that extended so it can do triple digits?  It would be nice to be able to schedule shutdown for like 12 hours in advance.

@ctrlaltca or @poixen

**Comment by poixen** [comment]
#1098
