### ISSUE TITLE
problem with first-run detection / welcome msg

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#1102]
i got the dialog that tells me that i might run this cockatrice version for the first time 3-4 times today.
if i go on there will pop up the edit sets dialog as supposed to, but with my old settings with just a few sets enabled...

- first time happened randomly today when i first started cockatrice (installed+used this version yesterday)
- second time was when i was clicking around the tray icon and had an unused (no login, no nothing) cockatrice in the background + jumped to the front again

Edit:
- just got the msg again... after experiencing a "Cockatrice stopped working" crash.

(all on win 8 - build from 2015-05-20)

@ctrlaltca

**Comment by ctrlaltca** [comment]
> second time was when i was clicking around the tray icon and had an unused (no login, no nothing) cockatrice in the background + jumped to the front again

The CardDatabase::checkUnknownSets() is made when the card database gets reloaded, and this typically happens on start or when the cardDatabasePathChanged() signal gets emitted.

The only way the message could be displayed more than once that comes to my mind are:
 * more than one cockatrice instance was running, so they were racing over the config file
 * cockatrice crashed without writing its config file, so it doesn't remember it already knew those sets.

**Comment by tooomm** [comment]
> more than one cockatrice instance was running, so they were racing over the config file

Nope. I never run more than one. Didn't know that it's possible at all. :)
Just tested it. I can't even start Cockatrice for a second time. Maybe needs a second install.


> cockatrice crashed without writing its config file, so it doesn't remember it already knew those sets.

That's highly likely due to the recent server shutdown crashes in the last hours.
Not sure about the tray icon thing though.

**Comment by ctrlaltca** [comment]
> That's highly likely due to the recent server shutdown crashes in the last hours.

#1105 

> Not sure about the tray icon thing though.

Let's see if it happens more times, i'll give it a look

**Comment by tooomm** [comment]
**But** yesterday when we tinkered around with the crash none of us (@woogerboy21 & @poixen)
experienced the repeating welcome message after crashes. At least they don't mentioned it. I can't remember that I saw it there after several crashes+restarts.

**Comment by camaroman86v6** [comment]
I am having this problem after updating today. I'm running Linux Mint and re-built Cockatrice after a git clone earlier today. I'm on Version 411fc38 (2015-05-23).
