### ISSUE TITLE
Centralized crash report database?

### ISSUE THREAD

**Issue by anoda9** [Cockatrice/Cockatrice#1104]
Is there an established place to submit crash reports to? 

Cockatrice has been crashing a lot since I updated to the latest (5/22 - 43c9f4e) version. Here are a few crash logs:

http://pastebin.com/qvAvdgWT
~~http://pastebin.com/E2RdZKDX~~ EDIT: moved to #1105

**Comment by Daenyth** [comment]
This is the place

**Comment by anoda9** [comment]
Yeah, it just feels bad to open a new issue every time.

**Comment by poixen** [comment]
Looks like it's to do with my new tab name formatting. Will have a look in a bit.

**Comment by poixen** [comment]
Fixed in #1107

**Comment by ctrlaltca** [comment]
Thank you for the report, fixed for both crashes have been committed, and the next weekly packages will contain the fixes.
