### ISSUE TITLE
no icon next to settings menu entry

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#1108]
![settings-wheel](https://cloud.githubusercontent.com/assets/9874850/7786265/164c7128-01c1-11e5-8573-7c3eec2b611d.png)
Shit happens...
To make it easier to find the settings page to change back the language for example, there should be a symbol next to the `Settings...` menu entry.

We have such an icon already next to the `Card database` --> `Clear search` menu:
![clear-search](https://cloud.githubusercontent.com/assets/9874850/7786269/6c394836-01c1-11e5-904e-db1aa1017dec.png)

We could use the same cogwheel we have next to main chat already (to clear the chat and go to chat settings) - it could look like this:
![settings-wheel2](https://cloud.githubusercontent.com/assets/9874850/7786294/f95731b4-01c2-11e5-8e95-0af2a99fcbd8.png)

---

this is the icon for settings:
https://github.com/Cockatrice/Cockatrice/blob/master/cockatrice/resources/icon_settings.svg

**Comment by ZeldaZach** [comment]
I'm very confused what's happening here...

**Comment by Nightfirecat** [comment]
He's suggesting that screenshot 1 look like screenshot 3, by modifying the "Settings" entry to have a cog next to it, to make it more clear how to reset your language if you accidentally change that setting.

**Comment by woogerboy21** [comment]
Can't say its happened to me before but those situations always suck ....
