### ISSUE TITLE
@cockatrice down ?

### ISSUE THREAD

**Issue by ahenaa** [Cockatrice/Cockatrice#1109]
Is cockatrice down ?
When I try to connect as usual,  can't connect, the software sent me a message:
"This server requires users registration"

**Comment by Nightfirecat** [comment]
Sounds like the normal server might have been in a restart process, redirecting traffic to the backup server, which requires user registration. I was able to connect just fine now.

P.S. This isn't a Cockatrice issue, it's a Woogerworks server issue - that's unrelated to any application features...

**Comment by ahenaa** [comment]
I still can't

**Comment by Nightfirecat** [comment]
If you visit woogerworks.com, you'll see this message. I think that may be related to the cause. @woogerboy21 

> We are performing routine maintenance ...
