### ISSUE TITLE
Select all text after adding card in deck editor

### ISSUE THREAD

**Issue by poixen** [Cockatrice/Cockatrice#1112]
This is more of a self reminder than anything as I will do it at some point.

After you have searched for and selected a card and press [ENTER], I want the entire text to be highlighted. This will mean any [CHAR] keypress will remove the old text and start typing the new search.

This will speed up deck construction as you do not need to remove the previous search manually.

**Comment by Nightfirecat** [comment]
:+1:

**Comment by ctrlaltca** [comment]
Implemented in #1115
