### ISSUE TITLE
[Bug] Context menu options for cards from opponent's library are incorrect, possible regression of #297.

### ISSUE THREAD

**Issue by Nightfirecat** [Cockatrice/Cockatrice#1113]
When viewing an opponent's library in an online game, I found that the context menu items for the cards shown was similar to those available for cards in your own library ("Play", "Play&nbsp;Face&nbsp;Down", "Move&nbsp;to...&nbsp;>"), but the options did not do anything.

Furthermore, if this dialog is left open, the opponent drawing cards will cause the display to update as well, similar to #297. I haven't had time to test this extensively, but I imagine that the test cases will perform similarly - removing the view's top card, rather than removing the actual top card.

**Environment info:** 43c9f4e on Windows 7, reproduced on 5/27/2015.

**Comment by Daenyth** [comment]
This might be related/dupe #625

**Comment by ebbit1q** [comment]
I can no longer reproduce this issue
