### ISSUE TITLE
Quickly switching between phases causes phase icons to fade to black

### ISSUE THREAD

**Issue by Nightfirecat** [Cockatrice/Cockatrice#1114]
See title. This can be reproduced by switching between phases in a local game using the F-key hotkeys at a high rate. ex: using F5 and F6 to switch between Untap and Draw phases.

This doesn't appear to manifest itself by switching between phases at a constant rate (that is, even at >10x/second, the icons look normal) but by staggering the switches, the effect can be seen more prominently. (eg. hitting F6 immediately after F5, repeatedly)
It's a pretty abnormal case, and one that's especially unlikely to occur online because of latency, so this may be too narrow to warrant fixing.

**Comment by Daenyth** [comment]
I'm guessing race condition. Maybe related to sending phase change 2 before the server's reply to change 1 has been received.

**Comment by Nightfirecat** [comment]
Just commenting on this to say it still repros; gif below was created by spamming between F6, F7, and F8 until the "Beginning of Combat" step indicator faded fully to black.

![phase-fading-to-black](https://cloud.githubusercontent.com/assets/2199511/25840180/a5f4247a-344f-11e7-9f64-d9ba6a4ff66b.gif)

**Comment by ctrlaltca** [comment]
I think i've just understood the meaning of the original bug report.

**Comment by ZeldaZach** [comment]
Imo this is no longer an issue as when I try to reproduce I get the "You are flooding the game. Please wait a couple of seconds." alert. That should prevent the rapid movement.
