### ISSUE TITLE
Gametypes sql table has a wrong primary key

### ISSUE THREAD

**Issue by ctrlaltca** [Cockatrice/Cockatrice#1119]
```
CREATE TABLE IF NOT EXISTS `cockatrice_rooms_gametypes` (
`id_room` int(7) unsigned NOT NULL,
`name` varchar(50) NOT NULL,
PRIMARY KEY (`name`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
```
Since the primary key is on "name", you can't use the same gametype name in two different rooms.
Also, having a primary key is quite useless, since the only query accessing the table is:
```
select name from cockatrice_rooms_gametypes where id_room = :id_room
```

I propose to drop the primary key and add an index on the id_room column.
The issue has been spotted by @poixen

**Comment by poixen** [comment]
Awesome. I agree with dropping the primary key.

**Comment by woogerboy21** [comment]
One other thing to note about the cockatrice_rooms and cockatrice_rooms_gametypes tables.  They both have no table row value to distinguish the server id that should use the game information.  So there is no way to stand up multiple servers using the multi server code and have them allow different game types based on the server itself

**Comment by woogerboy21** [comment]
My suggestion would be keep the "id" field but drop it as the primary key and then updated the servers code that reads the game type information from these two DB tables to identify the "id" that matches the servers id placed in the servers ini file.

**Comment by poixen** [comment]
I dropped the primary key and it worked. I was able to specify different game types in different rooms.
