### ISSUE TITLE
Servatrices Replay tables missing Date / Time Stamp

### ISSUE THREAD

**Issue by woogerboy21** [Cockatrice/Cockatrice#1122]
```
| cockatrice_replays          |
| cockatrice_replays_access   |
```
Both tables do not contain any type of date and time stamp as to when the replay data was inserted into the database.  This makes it very troublesome for cleanup and management of the replays.  Currently the only method I have to allow cleanup of the replays is to set a truncate of the tables at a specific time period (say every other sunday) resulting in replays for players that made one on monday be  available for 6 days but players that had a replay created on that sunday only available for less than a day.  With a date and time stamp there could be queries created to calculate cleanup based on X number of days and allow for replays to be available to players for multiple days regardless of when they were created in the database based on a non-date/time stamped method of removal.

**Comment by ctrlaltca** [comment]
When investigating this issue, i noticed that you could just join the ```cockatrice_games table``` on the ```id_game``` field to use ```time_started``` and ```time_finished``` from that table.

**Comment by woogerboy21** [comment]
Hmm... now to find out how to make a join statement in sql.

**Comment by woogerboy21** [comment]
Closing this issue, an alternate method ended up being worked out. :+1:  to @ctrlaltca
