### ISSUE TITLE
Window Focus

### ISSUE THREAD

**Issue by camaroman86v6** [Cockatrice/Cockatrice#1125]
I updated today to Version 2de9947 (2015-05-31). I previously had an issue due to compiling against qt4, but I'm now using qt5 via the repositories in Mint for version 5.2. Since I switched to Qt5, every time I open a new window via a shortcut like Ctrl+L for life or Ctrl+I to roll a die, this new window doesn't have focus. I used to be able to "Ctrl+I -> Enter" to roll a die, now I have to click the ok button in the dialog box. The life window pops up behind Cockatrice's main window, so I have to go to the task bar to find it and change my life by more than 1 at a time. I also seem to have a new issue where if I click my life total 3 times quickly, I end up with a net change of 4 life because it's double triggering somehow. I've not changed how quickly I click there since updating to qt5 and I did not have this issue before.

Is this some setting in Qt5 that should fix this?

**Comment by ZeldaZach** [comment]
I haven't heard of this issue before, but maybe because you're compiling against 5.2 instead of 5.4.1 might be the issue.

**Comment by Daenyth** [comment]
Iirc 5.2 is buggy, use something more recent.
