### ISSUE TITLE
P/T of face-down creature is coloured based on actual P/T of face-down card

### ISSUE THREAD

**Issue by david-in-perth** [Cockatrice/Cockatrice#1126]
I observed the following behaviour in a 1-player game:
- Put any creature card face-down on the battlefield (e.g. Ire Shaman)
- Set its P/T to the face-down card's P/T (e.g. 2/1)
  - Outcome: P/T numbers show in white.
- Set its P/T to something else (e.g. 2/2)
  - Outcome: P/T numbers show in red.

I haven't been had a chance to check whether opponents see the same thing in a 2-or-more-player game. If only the controller sees the difference in P/T colour, then it's a pretty minor bug. Otherwise, it has the potential to reveal hidden information to the opponent.

Git snapshot: 2de99475b03ccaa8b4eea397aa26e305d30fccdb

**Comment by ZeldaZach** [comment]
Tested and was able to replicate. This isn't good as people can guess what the face down card is based on it's P/T.

Should be that if a card is face down, the P/T will always be colored.
