### ISSUE TITLE
Game creator can't kick users after leaving the game and rejoining

### ISSUE THREAD

**Issue by LestatTheDarkPrince** [Cockatrice/Cockatrice#1127]
I noticed something, It used to be that the maker of a room had kicking powers when he or she came back to a room. Example i make a room and the game ends to i kick people to close the room but as i leave someone else enters randomly. Instead of allowing that person to "take over" my room i would enter and kick them and resume closing. Now it seems that if i reneter behind that person, they now have the "kicking" powers.

**Comment by ZeldaZach** [comment]
I don't see an issue with the highest person in the room (i.e. usually the room creator, but if they leave then the next person in the room) being re-assigned as the "room creator." 

Is there something in your issue that I'm missing?

**Comment by LestatTheDarkPrince** [comment]
I mainly noticed its different now. it used to be the creator automatically
had kick powers no matter what order they were. so if i left and came back
an hour later to find my room still active i could go into it and close it
in seconds. Now i have to hope that the other people close it.

**Comment by Daenyth** [comment]
I'm not sure when this would have changed. Were you registered?

**Comment by LestatTheDarkPrince** [comment]
I have always been. I just like to close my rooms when i leave them.
instead of having random people in a room that I created.

**Comment by ZeldaZach** [comment]
Dupe #2727
