### ISSUE TITLE
Server provider should be able to set username / password 

### ISSUE THREAD

**Issue by poixen** [Cockatrice/Cockatrice#1128]
It should be possible for:
+ [x] Server providers to set the rules for usernames outside of the server (like the ini). The should include chat sets, length, allow uppercase, punctuation...
+ [ ] The same for passwords. Server provider should be able to set a min and max length for password. 
+ [x] If there is a failure to meet with the external rules, the client should show the correct message. 

I feel that this would be good as a milestone before the roll out if a new version  

Thoughts?

**Comment by Daenyth** [comment]
Point 3 is #1173

**Comment by woogerboy21** [comment]
Is point 2 in this issue wise?  It sounds to me like your allowing operators to require users to have weak / strong passwords.  I guess I could see forcing length requirements as a minimum.  But as a max?

**Comment by Daenyth** [comment]
Setting max password length is insane. There's no good reason to do that.

**Comment by ZeldaZach** [comment]
Based on your logics, this ticket is complete.
