### ISSUE TITLE
Cockatrice update

### ISSUE THREAD

**Issue by casey002** [Cockatrice/Cockatrice#1131]

**Comment by Nightfirecat** [comment]
It looks like you forgot to add a description... :-1:

What are you trying to say?

**Comment by casey002** [comment]
I am an idiot. I'm sitting here struggling to update my card database on cockatrice. Although I think I might just have too old of a version and need to update.

**Comment by casey002** [comment]
"Database loads but no cards."

**Comment by Daenyth** [comment]
Try with the latest version of cockatrice

**Comment by casey002** [comment]
Tried that. Deleted all the old stuff and downloaded the latest version. Still getting the same error message. I can't find a copy of the .xml file so instead I tried using the .json and cockatrice wouldn't recognize the file when I searched for it.

**Comment by Daenyth** [comment]
What xml file can you not find? sets.xml? If so you are on a *very* old version.

If you're trying to use a sets.xml you need to back up your deck files and then upgrade to the latest version from woogerworks.com client downloads page.

For future updates you won't have to backup decks but the version you have installed has a bug where it can delete them on uninstall or upgrade if you store them in program files.

**Comment by ctrlaltca** [comment]
Closing; please reopen if you have more feedback.
