### ISSUE TITLE
Error 0xc000007b on loadup attempt

### ISSUE THREAD

**Issue by LetsGoHome** [Cockatrice/Cockatrice#1133]
Hi folks. I posted this over on the subreddit but I was directed here. Whenever I try to run Cockatrice (even as an administrator) it gives me the error 0xc000007b, saying it failed to start. Before you start posting, I have already done the following.

Downloaded and installed the latest .NET framework (multiple times)

Downloaded and installed the C++ visual studio x86 and x64 to see if either worked

Installed any missing .dlls that previous errors were giving me

Ran in safe mode and replaced some .dlls that I already have.

So yeah. Any advice? This all started when I reinstalled windows. It was working perfectly fine before that. Thanks for your help.

**Comment by ctrlaltca** [comment]
Can you try to download this: http://www.dependencywalker.com/ , run it, file -> open "cockatrice.exe" (you'll find it in c:\ program files (x86)\Cockatrice\).
Then, in the left pane you should be able to see if cockatrice still misses any dlls.

**Comment by LetsGoHome** [comment]
Thanks for the response. It gave me an error and said this.

Error: At least one module has an unresolved import due to a missing export function in an implicitly dependent module.
Error: Modules with different CPU types were found.
Warning: At least one delay-load dependency module was not found.
Warning: At least one module has an unresolved import due to a missing export function in a delay-load dependent module.

**Comment by ctrlaltca** [comment]
So, it seems that some dlls being picked up are not compatible one eachother (wrong version, maybe?).
I can't be really helpful here, i can just suggest you to have a look at the left pane in the software, expand the subtrees and search for dll names with a red icon. Those are probably the problem.

**Comment by ctrlaltca** [comment]
Closing; please reopen if you have more feedback.
