### ISSUE TITLE
AutoLink Error

### ISSUE THREAD

**Issue by ZeldaZach** [Cockatrice/Cockatrice#1135]
When people type messages that contain three (3) www's in a row, the system thinks they're trying to link to something and makes the incorrect conversion.

A simple fix should just be instead of searching for "www" it should search for "www." but maybe there's something more intuitive to prevent false linking.

![screen shot 2015-06-11 at 11 49 17 pm](https://cloud.githubusercontent.com/assets/7460172/8123294/947dff94-1094-11e5-9efe-2bb29838feed.png)
![screen shot 2015-06-11 at 11 49 27 pm](https://cloud.githubusercontent.com/assets/7460172/8123295/94819866-1094-11e5-9edc-3b5c505f4715.png)

**Comment by Daenyth** [comment]
\bwww\.
