### ISSUE TITLE
New Deck Editor UI jitters

### ISSUE THREAD

**Issue by Fizztastic** [Cockatrice/Cockatrice#1143]
The jittering is about 5 times faster than the gif crappy framerate and only on the card in the image tab.  Observed on 48c3e64.

![DeckEditor](http://i.imgur.com/QRRITUs.gif)

**Comment by ZeldaZach** [comment]
I observed this as well earlier. I believe it has something to do with the frame size not being a constant

**Comment by ctrlaltca** [comment]
Does this happen when browsing cards on the list, or even if you're not clicking/moving anything?

**Comment by ZeldaZach** [comment]
This happens no matter what's going on. Whether you're clicking on a card or doing nothing, it will "jitter"
