### ISSUE TITLE
Maximizing screen

### ISSUE THREAD

**Issue by LestatTheDarkPrince** [Cockatrice/Cockatrice#1144]
This is still an issue and it keeps putting the chat box under my taskbar it does this whenever i Sideboard for a game or when ever i check the "Account" tab.i have to minimize athen remax each time, and when i am done side boarding it does it again when the game starts.

**Comment by ZeldaZach** [comment]
Can you include some pics please?

**Comment by LestatTheDarkPrince** [comment]
I would not know how.

**Comment by LestatTheDarkPrince** [comment]
ok i think i have an idea on how to do this. When I log in the screen is like this. 
![image](https://cloud.githubusercontent.com/assets/12475361/8196971/19a95078-1460-11e5-870d-56063803f09f.png)  and i have to maximize the screen to get the box to be above the taskbar like so :
![image](https://cloud.githubusercontent.com/assets/12475361/8196979/3e751dce-1460-11e5-95a4-3d538c99b4a1.png) Everytime I sideboard or check the account screen it reverts back to the first image with the "say" box hidden.

**Comment by ZeldaZach** [comment]
I think it has something to do with your start bar menu being larger then normal. Cockatrice, to my knowledge, takes your screen size when it starts and it assumed you had a normal start bar. Why don't you try shrinking it and see if that fixes the issue?

**Comment by LestatTheDarkPrince** [comment]
because that would mess up everything else. i would not be able to see it
even. It did not do that before I had it the same size and before the
update there was No problem at all.

**Comment by ctrlaltca** [comment]
Your screen resolution is 1440x900 and the taskbar takes up 120px, the window titlebar 20px and the menubar 20px, so cockatrice is left with 740pixels. I suppose that the tabs you mentioned (account and sideboard) needs a vertical size > 740 pixel, so when they are shown they force the window to resize.
We can try to look at those windows and lower their minimum required height.

**Comment by LestatTheDarkPrince** [comment]
I am sorry none of that made any sense. All I know is it did not do it
before the update. After the update it does it.

**Comment by woogerboy21** [comment]
Im getting it as well.

**Comment by woogerboy21** [comment]
@ctrlaltca I run a res of 1920x1080 and no matter what I do I cant reproduce this issue.  are you suggesting the odd sized resolution (900) is the issue?  I can start the app and drag the size of my start bar to any different size and have yet to get the chat box to fall behind the start bar.

**Comment by ctrlaltca** [comment]
I tested a little bit and 700pixels seems enough.
About the "account" tab, maybe you have a very big avatar that forces the window to grow in order to show it? If yes, can you try a smaller one and see if this solves the problem? If no, can we see that tab to understand what's taking up the space?
Abut the "sideboard" tab, the card preview on the right is in "Show full info" mode? If yes, can you try to temporary change it to another mode and see if this solves the problem? If it doesn't solve the problem, can we see that tab to understand what's taking up the space?

**Comment by LestatTheDarkPrince** [comment]
my avatar i assume mean pic is kinda smal its just a book cover does not
even take up the whole slot you offer. about my sideboard i have show full
info. on yes. i showed pics of the tab bar issue already. for sideboard its
the same thing just a sideboard screen is up..

**Comment by LestatTheDarkPrince** [comment]
screen normally: 
![image](https://cloud.githubusercontent.com/assets/12475361/8251385/2ea53c62-164a-11e5-8974-355bfc492138.png)

Screen after hitting account tab.: 
![image](https://cloud.githubusercontent.com/assets/12475361/8251394/3dbb7982-164a-11e5-8120-d620bbaefba7.png)

screen for side boarding. the second i unlock board.  
![image](https://cloud.githubusercontent.com/assets/12475361/8251420/6959b95a-164a-11e5-8f05-e4920f90209b.png)

**Comment by LestatTheDarkPrince** [comment]
on side board you cannot even see board until i resize screen, and then when starting t reverts back to hidden voice box.

**Comment by ctrlaltca** [comment]
Thank you for the screenshots.
In the account screen the problem is definitely caused by the avatar image, we need to constrain its maximum height.
I need to check the sideboard screen, but the problem could be caused by the background image.

**Comment by LestatTheDarkPrince** [comment]
never had that issus with background and i have used that pic for about a
month.

**Comment by LestatTheDarkPrince** [comment]
Just installed newest download. Problem is NOT fixed.   same issue
