### ISSUE TITLE
Ability to ignore messages that @ people you have ignored

### ISSUE THREAD

**Issue by isleep2late** [Cockatrice/Cockatrice#1147]
This was suggested by user And.rew a few days ago, and it seems like something that a few of the users on the main chat have expressed interest in. I would have a discussion with someone on the chat that another user has on ignore, and to that user the chat looks one-sided.

**Comment by ZeldaZach** [comment]
I'm assuming this refers to how if you were to block "foo" and he tried messaging you, "fighters", the message wouldn't highlight. 

I.e. "Hey @fighters why did you block me!!?!?" Would not highlight and/or send a notification. 

:+1:

**Comment by isleep2late** [comment]
Well, here's an example of what I mean... I was talking to @Lunchbox3 on the main chat (using that tag) and @And.rew couldn't see what Lunch was saying because he had him on ignore, but he could see all of my messages whenever i would @ Lunch, so Drew suggested that we somehow implement a feature where, anytime I say @Lunchbox3 in the main chat, those particular messages would be ignored by him, only because he has that particular user on ignore.

If anything, it could be something users could have the option to use. A "super-ignore" or "meta-ignore" so to speak. lol

**Comment by Fizztastic** [comment]
I had already experienced similar issue in #1050 most likely due to https://github.com/Cockatrice/Cockatrice/blob/master/cockatrice/src/chatview.cpp#L265 only checking if the message starts by @YourUserName and not if its actually your complete username...

**Comment by ZeldaZach** [comment]
@Fizztastic Yeah, I was working on that last night. I'll continue to see if I can get it to work properly
