### ISSUE TITLE
Popup window on reveal hand in a spec friendly game.

### ISSUE THREAD

**Issue by dsolstad** [Cockatrice/Cockatrice#1154]
When spectating a game where you can see both players hands, it would be nice to not get the popup window showing their hands when a player reveals.

**Comment by Nightfirecat** [comment]
From a spectator's standpoint, I can see why that would be annoying. That said, the same view is used for replays (correct me if I'm wrong), and it's useful to see the revealed cards window at that point, as a number of players - myself included - use this window ingame to determine known information about players' hands, so having the same dialogs available during replays can be extremely useful for game reviews.

I wouldn't be opposed to this feature being implemented, so long as it was toggleable.

**Comment by dsolstad** [comment]
Isn't it possible to disable it with a simple check whether or not you are viewing a replay or a live game?

**Comment by ZeldaZach** [comment]
Potentially @dsolstad I'll mark this ticket and try to look into it

**Comment by radioactivehazards** [comment]
Why is that? why is it when we are watching replays we get to see the opponents hand? that seems like a waste. I personally see no point to seeing your opponents hand during a replay, or period i see no reason to ever have "specs may see hands". I think this opens up the possibility for multiple users to just troll people.

**Comment by Daenyth** [comment]
I think this would be more work to implement than it's worth. Reveals are handled the same from hand as from the deck and other areas, so it would require extra logic to not break those.

**Comment by radioactivehazards** [comment]
no i meant why would i ever want to see their hand?  i would not want to see it. in replay or anywhere

**Comment by tooomm** [comment]
a replay is more of a review and why-did-he-this-and-not-that thing than just a tv show.
you need to have all information available to understand why someone played this card over that card or to discover a missplay. without seeing their hands there is just very little use of replays - except for entertaining purpose.
