### ISSUE TITLE
question

### ISSUE THREAD

**Issue by LestatTheDarkPrince** [Cockatrice/Cockatrice#1157]
why was the deck editor area changed?  example:
![image](https://cloud.githubusercontent.com/assets/12475361/8265259/8dd0bada-16c3-11e5-9723-55a0da3096c8.png)  thespot where i see my card info the resizing of the box and the options seem uneened. just have the 3rd option as automatic. when you pull up a card you should see the pic and have description of info. the other 2 options seem pointless as you would just be simpler and save space with both. Some people, My self included use CUSTOM pics that cover up the wordings so i understand having a details box also.  I also do not think it helps that you cannot type anything except under the 3rd option.

**Comment by ZeldaZach** [comment]
You seem to be one in a minority then. A lot of users have requested us adding the option to view the image, description, and/or both in the deck editor in a quick and easily manageable way.

**Comment by LestatTheDarkPrince** [comment]
really i just seems like it would always be opyion 4 all day everyday. I
cannot imaging wanting to only see image or only see info.

**Comment by LestatTheDarkPrince** [comment]
Option*

**Comment by ctrlaltca** [comment]
So is this a feature request for removing a feature because you don't need it?

**Comment by LestatTheDarkPrince** [comment]
i just do not see why anyone would need it

**Comment by Daenyth** [comment]
What is your actual objection? Is it that we take up a few pixels with the tabs?
