### ISSUE TITLE
Cant get card promo images

### ISSUE THREAD

**Issue by poixen** [Cockatrice/Cockatrice#1158]
If a card has the promo version there can be complications downloading as gatherer do not host these images.

It needs to be a fall through to see if there are any other images in the sets that can be used instead.

![a](https://cloud.githubusercontent.com/assets/2134793/8266903/79d0a5ca-1747-11e5-8ce3-e9b2283bbe1c.png)

Also it shows an official card back, which I am not comfortable with.

This never used to happen, only when I updated my master recently. Maybe @ZeldaZach  or @ctrlaltca know more.

**Comment by ctrlaltca** [comment]
The problem here is that gatherer, instead of returning a 404 (so that cockatrice can move on to the next set image), returns a card back image. We could include a "blacklist" of card images based on their hash.

**Comment by ZeldaZach** [comment]
I figured it had something to do with gatherer. Good idea @ctrlaltca for checking on a hash :)

**Comment by Daenyth** [comment]
I was thinking of this blacklisting as well. I'm not sure we have any other
option.
