### ISSUE TITLE
Downloading Cardsets

### ISSUE THREAD

**Issue by Pyroice12** [Cockatrice/Cockatrice#1161]
So I've had some help through Woogerworks from everything from Uninstalling to manually downloading the AllSets.zip files. I have entered the current AllSets.json file into Oracle, and several others as well which all respond "The File was retrieved but contains no cardsets data", I converted one to a text file and it doesn't look corrupted, however in addition, the first time I downloaded the file it was as a JSON, now they all appear as ZIPs, which is it supposed to be?
I also tired manually downloading and oracle downloading the file after disabling my firewall and turning my internet security down temporarily with no results. 
Is there an updated version of oracle or something?
I'm not a tech savvy person and I just want to play MTG XD

**Comment by ZeldaZach** [comment]
Can you try updating your client to the newest one found on WoogerWorks' weekly build page? After that, try opening the new oracle tool and follow the steps through.

If it doesn't work, can you report back the errors again? :smile:

**Comment by Pyroice12** [comment]
I did update the cockatrice client from Woogerworks, but Oracle didn't seem to change, and there was no option to just update Oracle, at least not that I saw.

**Comment by ZeldaZach** [comment]
Can you try using the URL `http://mtgjson.com/json/AllSets.json` inside of Oracle?

Also, when you download the ZIP from Woogerworks, you get two programs: Cockatrice and Oracle

**Comment by Pyroice12** [comment]
"The file was retrieved successfully, but it does not contain any cardsets data"

**Comment by ZeldaZach** [comment]
Why don't you hope on [gitter](http://gitter.im/cockatrice/cockatrice) and we can try to troubleshoot this further?

**Comment by ctrlaltca** [comment]
Fixed by reinstalling.
