### ISSUE TITLE
talking to judge

### ISSUE THREAD

**Issue by LestatTheDarkPrince** [Cockatrice/Cockatrice#1163]
This post is only directed at Zelda, i do not understand my banning as i was in the process of pming you and saying very plainly that what i had typed would be all i would type. I wanted to get my point across. You stated your reason for banning me. You should then ban Several other people. You are hlping them walk all over a fellow user and showing them that it is ok to bully said user. I explained my side and they chose to mock me. So i chose to defend myself. Anyone would have. Would you allow people to just walk all over you. i am sorry if you would but i cannot. Especially when they are openly calling me retarded and such. its disrespectful. I was done posting and was about to start an EDH game. I have no other way to communicate this with you so i am forced to turn to this Reddit page which is probably the wrong place. If you had been monitoring the eariler discussion correctly you would have seen Various members Asking me to write my post to their forums, and they ban its quite funny. "Go ahead and complain about our awful site, We will just Ban you." Maybe if you know a more priave way we can discuss this and maybe come a better conclusion than just punishing half the people involved. Like i said i assume and hope you banned Them also. If you did not is unfit for you to continue being a mod. (not trying to insult your or your duties nor tell you how to do your job.) Further more i do not see what an issue between me and Magic league has to do with cockatrice.

**Comment by ZeldaZach** [comment]
Please note that the GitHub repo has nothing to do with any active servers in the community and we only build the software.

If you had a banning issue, I suggest you try emailing/talking to the server admin to get assistance.
