### ISSUE TITLE
Cockatrice deletes config on update

### ISSUE THREAD

**Issue by Psithief** [Cockatrice/Cockatrice#1164]
I just installed 8533424 over 18da49d (windows)
Cockatrice demanded the existing install be uninstalled first, so did as instructed.

On install, I unchecked "Update Configuration" because *I don't want my configuration changed*. I already have my paths set up the way I like them.

It turns out that unchecking this box does *not* allow me to preserve my previous configuration.

* Why not? That is what the box did previously.
* Why does it demand I uninstall Cockatrice in the first place? Isn't that the reason the configuration is being deleted?
* What's wrong with just one Cockatrice? `%localappdata%\Cockatrice\Cockatrice` is nesting madness.

**Comment by ctrlaltca** [comment]
> Why not? That is what the box did previously.

Unchecking "Update Configuration" still works

> Why does it demand I uninstall Cockatrice in the first place? Isn't that the reason the configuration is being deleted?

Yes, this is the reason and is a known bug. The long term solution would be to move the config to an ini file inside the user profile (this would lead to the creation of a portable version, too), but by now we'd better at least fix the NSIS script not to delete the old configuration.

> What's wrong with just one Cockatrice? %localappdata%\Cockatrice\Cockatrice is nesting madness.

The first "Cockatrice" is the vendor, the second is the product. Eg. servatrice would save data in %localappdata%\Cockatrice\Servatrice, oracle in %localappdata%\Cockatrice\Oracle

**Comment by Psithief** [comment]
This answers all my questions.
