### ISSUE TITLE
Card image redraw issue

### ISSUE THREAD

**Issue by Psithief** [Cockatrice/Cockatrice#1165]
## Steps to reproduce (Windows)
1. Open Cockatrice, single player game.
2. Put some cards on the table.
3. Change to another application / do other things for a few minutes.
4. Refocus Cockatrice
5. Hover over a card.
## Result

Card is redrawn as a completely white box. The card display in the right sidebar also shows a default card back instead of the card.

**Before Hover**
![image_draw_bug_0](https://cloud.githubusercontent.com/assets/1124846/8321781/e00dde70-1a5d-11e5-91a0-c423f7c93b41.png)
**After Hover**
![image_draw_bug_1](https://cloud.githubusercontent.com/assets/1124846/8321782/e01088e6-1a5d-11e5-89ea-8cc7cfb812a3.png)
## Prevalence

I believe this was happening ever since the cache was "fixed" so it would not balloon to enormous size. If related, is this some sort of cache miss? The hover redraw might need to ensure the image is still cached.

**Comment by ctrlaltca** [comment]
It's probably related. When you hovered the card, you forced a repaint: https://github.com/Cockatrice/Cockatrice/blob/master/cockatrice/src/abstractcarditem.cpp#L96
The paint method tries to load the image back from the CardInfo item:
https://github.com/Cockatrice/Cockatrice/blob/master/cockatrice/src/carddatabase.cpp#L625
First the cache is queried, if that fails an empty image is returned and the async reload-the-image routine gets called.
When dealing with an empty image, the card item will paint the card main color (in this case #E6E6E6), while the card preview will paint a card back.

What happened here? Either the cache unloaded the image in the meanwhile, or failed at returning the previously loaded image, so the default "empty" images got paint; then, the system used to reload the picture failed to actually do it.

**Comment by Psithief** [comment]
This appears to have become worse. Nothing I can do will make Cockatrice to recover from this cache fail.

I suspect the team removed some unnecessary cache refreshes that would otherwise have been useful for getting the card to display after this.

**Comment by Psithief** [comment]
This might be related to my application not having a card back to display, breaking the entire process.

**Comment by ZeldaZach** [comment]
We can't reproduce this, and seems super rare to happen. As such, I'm gonna close for now. If we get better directions in the future, we might have some way to solve it.

We think it might be the image cache dying and rebuilding incorrectly, but it's only a guess.

**Comment by ebbit1q** [comment]
if reproduction steps for this can be made we can reopen this ticket.

**Comment by tooomm** [comment]
Realized the same issue a few days ago when testing #2771!

Following the reproduction steps above now, it "only" makes the token flash and you shortly see a colored background. Then the correct token art is shown right after.
