### ISSUE TITLE
Invalid Username is hard to debug.

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#1173]
I propose that we add a new error string field onto the response to the client.

The new field should contain details of exactly why the validation failed, based on the dynamic server configuration at the time.

eg:
```ini
[users]
minnamelength=6
maxnamelength=12
allowlowercase=true
allowuppercase=true
allownumerics=false
allowedpunctuation=_.-
allowpunctuationprefix=false
```

Username | Error Message
------------ | -------------
joe | Minimum permitted username length is 6, "joe" is 3
abc123 | Numbers in usernames are not permitted
jack/! | Permitted punctutation is `_.-`, "jack/!" contains "/", "!"
22!! | Minimum permitted username length is 6, "22!!" is 4, Numbers in usernames are not permitted, Permitted punctutation is `_.-`, "22!!" contains "!"

The goal of these messages is to help guide users to be able to resolve issues by themselves. Right now users can't tell why the name is invalid, leading to reddit threads and github issues.

**Comment by ZeldaZach** [comment]
:+1: all the way

**Comment by poixen** [comment]
:+1: should be In before release.

**Comment by ZeldaZach** [comment]
It's a server fix, so there's no reason not to release the client when we can implement this at any point directly to all users. @poixen

**Comment by poixen** [comment]
It's client side. The server only sends an error state, not an error message.

**Comment by poixen** [comment]
Currently the client would not know what to do if sent a message.

**Comment by ZeldaZach** [comment]
Do you think you can potentially implement it client sided today, and we can do the server sided part at a later date?

**Comment by Daenyth** [comment]
I think that's risky because it locks us into a protocol version. Let's
just write it all at once.

**Comment by ZeldaZach** [comment]
Fair enough, but I'm not certain how we should go about this to begin
