### ISSUE TITLE
Segmentation Fault When Searching for Cards

### ISSUE THREAD

**Issue by pallados** [Cockatrice/Cockatrice#1174]
If I use the card search for the Cockatrice deck builder, I can usually get a few searches in before the program unexpectedly quits.  This number is higher when I run the program from terminal for some reason.  The only error I get is a segmentation fault.  The error happens when I change a search query while in the deck builder tab, either by adding a character or deleting what is inside.

I have not gotten the program to function normally in this regard, although playing a local game does not trigger this error in any way.

My OS is Ubuntu 14.04 LTS, and I installed the program a couple days ago by downloading the source and using cmake and make.

**Comment by Daenyth** [comment]
Can you install `gdb` and run `gdb cockatrice`, then when it segfaults put in `bt` and paste the stack trace it prints?

**Comment by pallados** [comment]
Program received signal SIGSEGV, Segmentation fault.
0x00007fffeb341cbb in ?? ()
   from /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so
(gdb) bt
#0  0x00007fffeb341cbb in ?? ()
   from /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so
#1  0x00007fffeb327b0d in ?? ()
   from /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so
#2  0x00007fffeb328b6b in ?? ()
   from /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so
#3  0x00007ffff5d7e22e in QObject::event(QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007ffff76ebc8c in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#5  0x00007ffff76f0e56 in QApplication::notify(QObject*, QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#6  0x00007ffff5d55c2d in QCoreApplication::notifyInternal(QObject*, QEvent*)
    () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007ffff5d57e07 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007ffff5da2cd3 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00007ffff47dae04 in g_main_context_dispatch ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#10 0x00007ffff47db048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#11 0x00007ffff47db0ec in g_main_context_iteration ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#12 0x00007ffff5da298c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop:---Type <return> to continue, or q <return> to quit---
:ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#13 0x00007ffff5d5496b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#14 0x00007ffff5d5b0e1 in QCoreApplication::exec() ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#15 0x0000000000503614 in main ()

**Comment by ctrlaltca** [comment]
Can you tell us your Qt and libxcbversion? i suspect https://bugreports.qt.io/browse/QTBUG-34748

**Comment by pallados** [comment]
Qt is version 5.2.1 (QMake version 3.0)

libxcb is version 1.10 if Synaptic Package Manager is correct

**Comment by ctrlaltca** [comment]
Ok, so it's not the issue i cited in the previous comment.

**Comment by ZeldaZach** [comment]
QT 5.2 has been known to have issues. Can you try upgrading to 5.4.2?

**Comment by Daenyth** [comment]
@ctrlaltca is it possible/easy to produce a warning/error/are-you-sure-confirmation when cmake detects qt 5.2?

**Comment by pallados** [comment]
When I run cmake .. in the build folder, I get this

-- Found Qt 5.2.1
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pala/Desktop/cct/Cockatrice/build

**Comment by Daenyth** [comment]
Can you try installing a Qt version newer than 5.2?

I found this PPA but I don't know the owner or whether it's trustworthy https://launchpad.net/~beineri/+archive/ubuntu/opt-qt541-trusty

**Comment by pallados** [comment]
I've been trying to install 5.4.2, but I keep on getting stuck because it can't find lpoly2tri
The issue is pretty much this one
http://forum.odroid.com/viewtopic.php?f=52&t=12306

I wouldn't be posting about it here, but it takes a nontrivial amount of time to download/run configurations and make for qt5.

**Comment by ZeldaZach** [comment]
@pallados Were you able to try this again and see if you still were experiencing a SEGFAULT?

**Comment by ctrlaltca** [comment]
Closing. Please reopen if more feedback is available,

**Comment by Daenyth** [comment]
@ctrlaltca Might this be the same as #1967
