### ISSUE TITLE
Players added out of order in local game

### ISSUE THREAD

**Issue by mildmongrel** [Cockatrice/Cockatrice#1176]
During testing of gamescene changes I found that when creating a 4-player local game the players were added to the game in the order ("Player 2", "Player 1", "Player 3", "Player 4").

This is likely a very minor issue.

**Comment by ZeldaZach** [comment]
Dupe #3795

**Comment by ebbit1q** [comment]
this is actually a duplicate of https://github.com/Cockatrice/Cockatrice/issues/2491 instead
