### ISSUE TITLE
No Funciona

### ISSUE THREAD

**Issue by JineteDV** [Cockatrice/Cockatrice#1182]
I downloaded the latest build on June 25th and randomly the program will stop functioning even without me being in/spectating a game. Has been triggered at least once by me posting a link with url tags in a private chat. Haven't found a method to the madness yet. OSX 10.10.3

**Comment by Daenyth** [comment]
What does "stop functioning" mean? Does it crash? Does it freeze and stop responding? Describe exactly what happens.

**Comment by JineteDV** [comment]
It doesn't crash, it'll stop responding and my loading pinwheel will come up whenever I mouseover the cockatrice window and it'll stay like that for hours unless I close cockatrice.

**Comment by Daenyth** [comment]
Can you follow this and upload the log to gist.github.com? 
https://github.com/Cockatrice/Cockatrice/wiki/Debug---Logging#mac-osx

**Comment by JineteDV** [comment]
https://gist.github.com/JineteDV/62fa368e1269dedb3632

**Comment by Daenyth** [comment]
Unfortunately that doesn't give me any insight for why it might be stalling. I'm at a bit of a loss.

If you compile your own update from the instructions on the wiki can you try with that?

**Comment by JineteDV** [comment]
https://gist.github.com/JineteDV/45b6b9ee4f38416bac0d another odd crash report

**Comment by JineteDV** [comment]
https://gist.github.com/JineteDV/03d599391f15ca535b78 crash report, this and the above crash reports happened when I tried to send a message in the chat.

**Comment by Daenyth** [comment]
cc @ctrlaltca ?

**Comment by ctrlaltca** [comment]
It sounds like an infinite loop due to #1151

**Comment by JineteDV** [comment]
I played a game where a player cast a card and then the program stalled. Even when watching the replay the program will stall at the exact same point every time. How can I share the replay file?

**Comment by JineteDV** [comment]
https://www.dropbox.com/s/gi0acuxfb3mu2ve/replay_35932.cor?dl=0 A replay file. When I played the game and whenever I watch the replay cockatrice will always stall when time vault enters the stack.
Here's the crash report for it https://gist.github.com/JineteDV/8567d0b6fc5b62d71699
