### ISSUE TITLE
Face-down ETB-tapped lands will ETB tapped, face-down

### ISSUE THREAD

**Issue by Nightfirecat** [Cockatrice/Cockatrice#1183]
As seen in [this screenshot of a spectated game](https://i.imgur.com/xhjlKLw.png), the lower player played a Raging Ravine, added a counter to his Liliana of the Veil, and placed another Raging Ravine onto the battlefield face-down, which entered the battlefield tapped. IMO, all face-down cards should ETB untapped to prevent information being given away.

Observed on June 30, 2015 using 43c9f4e on Win7.

**Comment by Daenyth** [comment]
Thanks for the report, should be straightforward to fix.

**Comment by Daenyth** [comment]
We should enforce on the server side that all cards played face down have no marked pt, annotations, tapped/flipped state, etc.

**Comment by ZeldaZach** [comment]
Client side, easy. Server side, hard as can be. :frowning:

**Comment by Fizztastic** [comment]
Tested this on the current version and if you hold shift and drag the card into play or use the "play face-down" option in the card menu, the card doesn't enter the battlefield tapped.

**Comment by ZeldaZach** [comment]
Tested on 43c9f4e (Build in question) &rarr; Can't reproduce
Tested on 680332a (Newest build) &rarr; Can't reproduce

If you're able to get a video/game replay that shows there's an issue, please feel free to include and reopen
