### ISSUE TITLE
Add "Forgot password" functionality

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#1184]
We can register users but we can't reset passwords without outside intervention.
- [x] Cockatrice presents "forgot password" option with two modes. It accepts a username. If user has reset token, they can input it
- [x] Servatrice handles "forgot password" protocol action.
  - Reply to user with "Password reset request received. If the user has an activated email, they will be sent recovery instructions"
  - Check user exists, activated, has email.
  - Insert a row into password_reset table. It has a random token (like activation) and an expiry time set 24hrs after request. It records the requestor's ip address and time of request.
  - Send an email with "if you requested reset, paste this token to forgot password screen"
- [x] Servatrice handles forgot+token protocol action
  - Check username + token, generic error on failure
  - Check expiry time, if current time is after expiry time, reply with message saying it expired and to start over to get a new token
  - Set a randomized password and email it to the user.

**Comment by woogerboy21** [comment]
This would be the last real item I could see needed to making the woogerworks server registration only based.

**Comment by tooomm** [comment]
:+1: 

(servers are reg only in the meantime, but still no forgot password functionality)

**Comment by woogerboy21** [comment]
So what do you do if the user has no email associated with there account?

**Comment by tooomm** [comment]
How can that be? Email is a required information as far as I know?

**Comment by woogerboy21** [comment]
Sure but nothing stops some one from misspelling there own email address.
The server has no way to even check that ;)

**Comment by Daenyth** [comment]
The server can check that by the user not having an activation token.

Regardless we don't enforce emails so we need to figure a way

**Comment by ZeldaZach** [comment]
Security questions are always possible @Daenyth

**Comment by Daenyth** [comment]
They're also typically a great way to totally bypass password security. I'd have to look into how to do it right

**Comment by realityfabric** [comment]
You could just have a notice during the registration process that emails are required for password resets, and that it is the registrant's responsibility to ensure that their email is on file and correct

**Comment by tooomm** [comment]
>Regardless we don't enforce emails so we need to figure a way

We require a "valid" email address at registration: (if you enter nothing, you'll receive the same)
![mail needed](https://cloud.githubusercontent.com/assets/9874850/10367896/2d9bf230-6dd3-11e5-812a-30d8f112607b.png)
You even need to enter it wrong two times to get it send to the server at all...

If you manage that, you won't receive a token and can't activate your account.
So you need to contact the server owner which can help your with your wrong email to receive your token.
Or you just register again with a new nickname.

So no problem here...

---

BUT you can actually delete or change your email address within the `Account` tab. I think that's a issue...
There should be the same verification and support with changing email addresses as we have in the registration process.

What do I miss @Daenyth ?

**Comment by Daenyth** [comment]
@tooomm It's configurable. The server admin doesn't have to require them

**Comment by tooomm** [comment]
@Daenyth Hmm. What happens then if the admin doesn't require email addresses? The user can never activate their account because they can't receive a token via email.
The only other option I can think of right now are `Unregistered users`, but they don't have an account and can't forget their passwords.

**Comment by Daenyth** [comment]
If email addresses aren't required, the account is activated immediately.

**Comment by Daenyth** [comment]
OK, let's revisit this.

We should agree on some high-level points first. The way I see this is that there's multiple layers of "reset password" functionality we can implement.

- Password value changed to explicit value given by moderator; zero self service. I believe we already have this in the "change password" functionality.
- With email (or another out of band authenticated mechanism) - using nonce values shipped over a secure channel. 
- Without email; I think the right approach here is a moderated one. This is the more complex case.

I'll write more on this later, I need to watch the little one now. We should aim at the email case first then do the case without email after

**Comment by ZeldaZach** [comment]
We don't currently have a way for mods to change a user password in client

An idea that woods implemented is we can do it with server configs and the owner can determine how they want to go about resetting

1: `sendEmailWithNew` -- This will reset the password to a random string of characters and email this string to the user

2: `requireEmail` -- This will require the user to input the email associated with the account in the password reset form

3: `requireClientID` -- This will require the user to be on a computer they've used in the past to login to Cockatrice (successfully) for the reset form to work

4: `requireSecurityQuestion` -- We can add a new field when registering that users answer a security question so if they forget their password they can reset it with a security question

And we can probably come up with a lot more ideas, but here are just some I've thought of quickly. Server owners can choose how strict they want to be with users resetting their passwords.

**Comment by realityfabric** [comment]
I think it is important to have a password reset system that does not rely on moderators, especially not if the moderators will at any time be able to read the password in plain text.

I also don't think sending the password in plain text over email is a good idea. At the most there should be a one-time use password sent over email, with a limited time frame in which the password can be reset with that temporary password, and which the user is forced to change once they have logged in with it.

If security questions are implemented, they should be custom questions, not preset.

**Comment by Daenyth** [comment]
> especially not if the moderators will at any time be able to read the password in plain text.

This isn't possible; the server doesn't store any plain text passwords.

**Comment by Daenyth** [comment]
> If security questions are implemented, they should be custom questions, not preset.

Security questions might be a decent idea, but I think they can be added on after the fact in a backwards-compatible way. People on older clients just wouldn't see the option. I agree custom questions are better

**Comment by Daenyth** [comment]
> We don't currently have a way for mods to change a user password in client

Ok, my mistake, I thought we had this. Let's ticket it if it's not already there, it should be simple to implement.

**Comment by Daenyth** [comment]
On the subject of email-less resets, let's examine the information we have to work with.

- requester-supplied username
- requester-supplied email
- requester ip
- requester client id
- (maybe) security question

I think that we can take incoming reset requests and record all of the above data points in a table. Then, we can make some comparisons.

- Does the username match the email address?
- Does the requester ip match any known user ips?
- Does the requester client id match any known user client ids?
- Does the security question match?

The answers to those questions can be used to drive either fully automatic or moderator-driven resets.

Of the options available I think a security question provides the strongest verification for automatic resets. It does have some migration problems as users will need to provide questions. We can enforce it for new users but we'll also have to expand the "modify account" protocol to permit changing security questions (which definitely must be logged)

**Comment by woogerboy21** [comment]
So I am interested in re-exploring the implementation of the self service password reset.  At least to the point for users that have valid email address's and notifying them via it.  @Daenyth would you accept a PR that would allow people to self service forgot password functionality  with the following process:

* client side menu option for "forgot password"
* protocol component that sends information to/from client as a command/response
* checks for email address and emails user a token (probably generated during the interaction)

The only step that is still up for some thought would be how to handle the users account when the reset password request has been made.  My initial thought was to set there account to  inactive and then re-activate it during the set new password interaction.  But doing so may cause some one with malicious intent to simply spam the server with the information for account password resets and de-activate accounts.

**Comment by Daenyth** [comment]
Yes that sounds like appropriate handling. When I'm at a computer I'll go
into some more details for the security portion of the workflow. We also
need to consider how server settings impact this, like if email is turned
off etc
