### ISSUE TITLE
The mystery of the ghostly sessions and pool utilization

### ISSUE THREAD

**Issue by woogerboy21** [Cockatrice/Cockatrice#1186]
So I noticed over the last server time out that results in a mass number of users getting booted that there is not a crash of the server so no debug data is captured but in the servers log file you see things like this:

Wed Jul 1 17:02:05 2015 Pool utilisation: ("1785")
(Even though there was only 952 users on.)

Wed Jul 1 17:02:10 2015 Server::removeClient: removed 0x6ec29b0 ; 357 clients;  0 users left
(How is there 0 users left but 357 clients?)

So any idea's on why there would be such a massive pool utilisation increase?  Maybe a loop in the code?

**Comment by woogerboy21** [comment]
Im also seeing entries around the same time like:
```
Wed Jul 1 17:02:05 2015 3539730 Incoming connection: 108.53.84.65
Wed Jul 1 17:02:05 2015 Pool utilisation: ("1783")
Wed Jul 1 17:02:05 2015 QIODevice::write: device not open
Wed Jul 1 17:02:05 2015 QIODevice::write: device not open
```

Its almost like the listener for the socket died but then came back?

**Comment by Daenyth** [comment]
Maybe failed logins leak threads?

**Comment by woogerboy21** [comment]
Not that this is to much help but further investigation shows that there is points in time in the log that things just are not written.  For example @ 17:01:34 I see entries but at 17:01:35 there are none.   As if the process thread was derped in some fashion.

**Comment by ZeldaZach** [comment]
Fabio and I fixed this a few months back
