### ISSUE TITLE
documentation on custom sets?

### ISSUE THREAD

**Issue by aeosynth** [Cockatrice/Cockatrice#1196]
is there any documentation on creating custom cards/sets? i'm thinking of extracting my spoiler scraper, and generating cockatrice custom sets.

**Comment by ctrlaltca** [comment]
Recent cockatrice builds can load additional xml sets files (see #1088 for details); this did not make it in the documentation yet.
Basic documentation on the xml format is available at https://github.com/Cockatrice/Cockatrice/wiki/Custom-Card-Images, including an xsd schema definition.
If you need any clarification, i'll be glad to help.

**Comment by ZeldaZach** [comment]
I've worked on updating the github wiki about the customsets folder. You can have up to 25 databases in the customsets folder, from what I recall, and they are loaded in numerical/alphabetical order.

**Comment by aeosynth** [comment]
cool. i was able to make [my app](https://github.com/aeosynth/spoiler) using the info from the wiki, so this issue is resolved for me.
