### ISSUE TITLE
Compile for windows on Travis using mingw

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#1198]
http://stackoverflow.com/questions/28155308/how-to-cross-compile-with-mingw-on-linux-for-windows
http://stackoverflow.com/questions/18720773/qt5-cmake-and-mingw

We'll need general instructions for this as well.

**Comment by woogerboy21** [comment]
Are you wanting to move back to using minigw to compile in the windows environment as well or is this an effort to get travis to test compiling the client for windows compatibility?

**Comment by Daenyth** [comment]
The latter gives us the former.

**Comment by woogerboy21** [comment]
Is this needed any longer since appveyor is setup/configured?
