### ISSUE TITLE
Clicking private message notification resizes the cockatrice window

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#1199]
Reproduce:
- Be on OSX
- Get a PM
- Click the notification
- Window resizes

compiled from 8ed9d35724d44702aea066c21150b2434ee5a2fd (very recent)

**Comment by poixen** [comment]
This happens in all clients. If you have maximized window and you click a message it will resize. It can be fixed in window_main line 571.

**Comment by ZeldaZach** [comment]
Fixed in #1485
