### ISSUE TITLE
can't register account in linux version

### ISSUE THREAD

**Issue by kd8eeh** [Cockatrice/Cockatrice#1200]
I followed the instructions on the website, except qt5 didn't work for some reason so I forced it to use qt4.

**Comment by woogerboy21** [comment]
What version of 5 did you use ? The windows clients use 5.4.1 and I seem to
recall requiring something like 5.2 as a minimum when using 5.

**Comment by ZeldaZach** [comment]
We're updating requirements for QT5 with the new build to use 5.4 or newer. Try updating your QT5 and see if that works.

**Comment by Daenyth** [comment]
What happens when you try to register?
How did qt5 fail?

**Comment by Walsen** [comment]
Hi,

I'm having the same problem, my servatrice is running under centos 6.5 with qt 5.4, the error displayed in the logs is:

```shell
Tue Jul 7 19:03:25 2015 12aa0e0 Incoming connection: 11.107.217.116
Tue Jul 7 19:03:26 2015 12aa0e0 [Command_Register.ext] { user_name: "amiel" email: "amiel@gmail.com" gender: Male country: "bo" real_name: "Adiel" }
Tue Jul 7 19:03:26 2015 Got register command:  "amiel"
Tue Jul 7 19:03:26 2015 "[pool 0] Error executing query: Column 'token' cannot be null QMYSQL3: Unable to execute statement"
Tue Jul 7 19:03:26 2015 Failed to insert user:  QSqlError("1048", "QMYSQL3: Unable to execute statement", "Column 'token' cannot be null")  sql:  "insert into cockatrice_users (name, realname, gender, password_sha512, email, country, registrationDate, active, token) values (:userName, :realName, :gender, :password_sha512, :email, :country, UTC_TIMESTAMP(), :active, :token)"
Tue Jul 7 19:03:26 2015 Socket error: QAbstractSocket::RemoteHostClosedError
Tue Jul 7 19:03:26 2015 Server::removeClient: removed 0x12aa0e0 ; 0 clients;  0 users left                                                                                     
Tue Jul 7 19:03:26 2015 12aa0e0 ServerSocketInterface destructor 
```

**Comment by Daenyth** [comment]
This is related to #865 I think. Try setting your servatrice mysql schema to non-strict mode

**Comment by kd8eeh** [comment]
I looked through and it appears I have qt 4.8.6 installed.  I'll try to force that to update, and see if it works then.

**Comment by ctrlaltca** [comment]
I bet this happens on a server where user activation is disabled. There's a quick workaround for this in #1234, if you want to test it.

**Comment by kd8eeh** [comment]
It's not that I am getting an error when I try to register.  The client does not appear to have any functionality to register an account (i.e. there is no button for it).  I can't register from a browser or other means until dns issues are fixed.

**Comment by kd8eeh** [comment]
it's the woogerworks server, so it should have all necessary functionality

**Comment by ZeldaZach** [comment]
Sounds like your client is out of date then... Try updating [here](https://github.com/Cockatrice/Cockatrice/releases/)

**Comment by woogerboy21** [comment]
If you dont have the register to server option from the cockatrice menu, then your client is out of date and will need rebuilt.

**Comment by woogerboy21** [comment]
So was this issue ever resolved?  Sounds like @kd8eeh was running an out of date client if the menu option was the only thing missing.

**Comment by ctrlaltca** [comment]
Closing
