### ISSUE TITLE
Cards.xml manual update

### ISSUE THREAD

**Issue by gthomson0201** [Cockatrice/Cockatrice#1201]
I'm on a mac and I want to play the new origins cards and I downloaded the updated cards.xml and none of the origins cards are showing up

**Comment by ZeldaZach** [comment]
Are you using the `customsets` folder, manually replacing your `cards.xml` or doing something else I don't know of? Just saying that an XML file, that *might* not be following the appropriate format, that you downloaded doesn't work really isn't giving us much to work with.

Can you provide some more insight please? :smile_cat:

**Comment by gthomson0201** [comment]
Thanks for the reply I was using a faulty cards.xml 🙈
