### ISSUE TITLE
Expand "Create related card" function to nonflip cards like Bitterblossom?

### ISSUE THREAD

**Issue by azas9s4d9** [Cockatrice/Cockatrice#1203]
Would be nice if this worked on Permanents that created the same types of permanents over and over again

**Comment by woogerboy21** [comment]
Could you give an example of a card that does this that your referring to?

**Comment by azas9s4d9** [comment]
On Delver of Secrets, you can right click it, click "make related card," and you get Insectile Aberration—the other side of Delver. So I was thinking you could right click something like Bitterblossom and make the correct token. Another example is Awakening Zone. It would be great if you could use that feature to create   0/1 colorless Eldrazi Spawn creature token with "Sacrifice this creature: Add {1} to your mana pool." instead of creating it manually.

**Comment by ZeldaZach** [comment]
We discussed this a few weeks ago and hope to bring it to Cockatrice in the near future 😇

**Comment by Daenyth** [comment]
Yup, this is planned.

**Comment by tooomm** [comment]
This got implemented with #1722?

**Comment by ZeldaZach** [comment]
Yes @tooomm
