### ISSUE TITLE
Export/import block list or friends list?

### ISSUE THREAD

**Issue by azas9s4d9** [Cockatrice/Cockatrice#1204]
I proactively block people who are uncooperative, slow, don't understand the rules, etc. and I add responsive, fast players who know the rules to my friends list.  I think it would be useful to be able to share block lists and friends lists. Lots of the criticism of Cockatrice is bad users, and I think this could help. People could share lists of users who have proven that they are good to play with and you can avoid undesirable players who will waste your time.

**Comment by Daenyth** [comment]
This would be partially covered by #622 since the room could have a block list independent of players.
