### ISSUE TITLE
validate custom sets

### ISSUE THREAD

**Issue by aeosynth** [Cockatrice/Cockatrice#1207]
custom sets should be validated to prevent problems such as https://github.com/aeosynth/spoiler/issues/1

**Comment by ZeldaZach** [comment]
We have an [XSD validation file](https://github.com/Cockatrice/Cockatrice/wiki/Custom-Card-Images#i-modified-my-cardsxml-how-can-i-ensure-it-wont-create-problems) with Cockatrice, but it seems to be out of date. I'll work on getting that up to date.

**Comment by tooomm** [comment]
@ZeldaZach here is the correct link: [cards.xsd](https://github.com/Cockatrice/Cockatrice/blob/master/doc/cards.xsd)
Is it still outdated?

There is also a deck.xsd file...


I highly support a validation of the custom sets files. Just tested the `BFZ.xml` file provided [on reddit](https://www.reddit.com/r/Cockatrice/comments/3kg2bv/bfz_xml_file/).

The file is "working", but the result looks aweful:
![custom sets bfz](https://cloud.githubusercontent.com/assets/9874850/9826450/b510eb16-58da-11e5-8e0f-0a8557c4e5fc.png)

The xml file has stuff like this inside which might cause the issue:
```
<card>
      <name>~Awaken Cancel</name>
      <type>Instant</type>
      <text>Counter target spell.&#xD;Awaken 3&#xE2;&#x80;&#x94;4UU (If you cast this spell for 4UU, also put three +1/+1 counters on target land you control and it becomes a 0/0 Elemental creature with haste. It's still a land.)</text>
      <manacost>1&#xD;
                &#xD;
                    U&#xD;
                &#xD;
                    U</manacost>
      <tablerow>3</tablerow>
      <set picURL="">BFZ</set>
</card>
```

Not sure though if it could be detected with a validation against the xsd.

**Comment by aeosynth** [comment]
@tooomm i updated my spoiler generator, here's my xml: https://gist.github.com/aeosynth/9c23d2d6de733a0ec118

i did have an issue with an `&bull;` nuking everything past that point. also i had to check the wiki to see that custom sets are required to have a `.xml` extension; a warning dialog would have been nice (eg 'unsupported file format')

**Comment by ebbit1q** [comment]
dupe #2065
