### ISSUE TITLE
Token text created a different card

### ISSUE THREAD

**Issue by Nightfirecat** [Cockatrice/Cockatrice#1209]
It could be because the tokens had a P/T set when the defined Human token does not have a P/T, but when creating a Human token, [the art for "Human Frailty" was displayed instead](http://i.imgur.com/ejHpkHs.png). Possibly related to #915?

Above screenshot was produced using Windows 7 on 816c01e.

**Comment by Psithief** [comment]
I can't reproduce this using 3189045.
Do you have *any* working tokens?

**Comment by Nightfirecat** [comment]
Yes, other tokens seem to look fine - I can confirm "Elemental" and "Spirit" off the top of my head.

**Comment by ZeldaZach** [comment]
Tested with 3189045 &rarr; No Issues
Tested with 816c01e &rarr; No Issues

<img width="336" alt="screenshot 2015-07-05 19 07 52" src="https://cloud.githubusercontent.com/assets/7460172/8513844/2944be8a-2349-11e5-8e37-03aad5496245.png">

Tested on Mac OS X 10.10.4

@Nightfirecat Do you have a replay of the game where this token appeared with the wrong image? That would be helpful to identify the problem. In addition, try updating your `tokens.xml` file as that might fix the issue too.

**Comment by ZeldaZach** [comment]
Looking back at past tickets, this seems to be a dupe of #370, which seems to have been fixed... Odd

**Comment by Nightfirecat** [comment]
Yeah, looks like it was an old `tokens.xml` that caused it. Can't repro - I'll reopen if I notice anything else, but it seems to be working now.
