### ISSUE TITLE
Error building on Debian SID amd64

### ISSUE THREAD

**Issue by GuillaumeSeren** [Cockatrice/Cockatrice#1211]
Hi there,
I get an error while trying to build the code on Debian SID amd64,
I followed the guide here (https://github.com/Cockatrice/Cockatrice/wiki/Installing-Cockatrice#debian-linux), it went well, but when I do make it return me an error:
```
make[2]: *** No rule to make target '/usr/lib/i386-linux-gnu/libprotobuf.so', needed by 'cockatrice/cockatrice'. Arrêt.
CMakeFiles/Makefile2:245: recipe for target 'cockatrice/CMakeFiles/cockatrice.dir/all' failed
make[1]: *** [cockatrice/CMakeFiles/cockatrice.dir/all] Error 2
Makefile:136: recipe for target 'all' failed
make: *** [all] Error 2
```

I installed all listed dependencies such as protobuf, but I find it weird that it use protobuf from i386.

Guillaume.

**Comment by GuillaumeSeren** [comment]
After checking in my setup I got not i386 protobuf (since I am on amd64): 
sudo dpkg -l | grep 'protobuf'
ii  libprotobuf-dev:amd64                                       2.6.1-1                                        amd64        protocol buffers C++ library (development files)
ii  libprotobuf-lite9:amd64                                     2.6.1-1                                        amd64        protocol buffers C++ library (lite version)
ii  libprotobuf9:amd64                                          2.6.1-1                                        amd64        protocol buffers C++ library
ii  protobuf-compiler                                           2.6.1-1                                        amd64        compiler for protocol buffer definition files

**Comment by ctrlaltca** [comment]
It seems like cmake is guessing the wrong directory for protobuf. I'd start checking the contents of the generated file "CMakeCache.txt" looking for "protobuf" entries.
Is it normal that the "protobuf-compiler" package is not listed as amd64?

**Comment by GuillaumeSeren** [comment]
@ctrlaltca thank you for reply,
Here is my CMakeCache.txt content:
```
PROTOBUF_INCLUDE_DIR:PATH=/usr/include
PROTOBUF_LIBRARY:FILEPATH=/usr/lib/i386-linux-gnu/libprotobuf.so
PROTOBUF_LIBRARY_DEBUG:FILEPATH=/usr/lib/i386-linux-gnu/libprotobuf.so
PROTOBUF_LITE_LIBRARY:FILEPATH=/usr/lib/i386-linux-gnu/libprotobuf-lite.so
PROTOBUF_LITE_LIBRARY_DEBUG:FILEPATH=/usr/lib/i386-linux-gnu/libprotobuf-lite.so
PROTOBUF_PROTOC_EXECUTABLE:FILEPATH=/usr/bin/protoc
PROTOBUF_PROTOC_LIBRARY:FILEPATH=PROTOBUF_PROTOC_LIBRARY-NOTFOUND
PROTOBUF_PROTOC_LIBRARY_DEBUG:FILEPATH=PROTOBUF_PROTOC_LIBRARY_DEBUG-NOTFOUND
cockatrice_protocol_LIB_DEPENDS:STATIC=optimized;/usr/lib/i386-linux-gnu/libprotobuf.so;debug;/usr/lib/i386-linux-gnu/libprotobuf.so;general;-lpthread;general;-lpthread;
//Details about finding PROTOBUF
FIND_PACKAGE_MESSAGE_DETAILS_PROTOBUF:INTERNAL=[/usr/lib/i386-linux-gnu/libprotobuf.so][/usr/include][v()]
//ADVANCED property for variable: PROTOBUF_INCLUDE_DIR
PROTOBUF_INCLUDE_DIR-ADVANCED:INTERNAL=1
//ADVANCED property for variable: PROTOBUF_LIBRARY
PROTOBUF_LIBRARY-ADVANCED:INTERNAL=1
//ADVANCED property for variable: PROTOBUF_LIBRARY_DEBUG
PROTOBUF_LIBRARY_DEBUG-ADVANCED:INTERNAL=1
//ADVANCED property for variable: PROTOBUF_LITE_LIBRARY
PROTOBUF_LITE_LIBRARY-ADVANCED:INTERNAL=1
//ADVANCED property for variable: PROTOBUF_LITE_LIBRARY_DEBUG
PROTOBUF_LITE_LIBRARY_DEBUG-ADVANCED:INTERNAL=1
//ADVANCED property for variable: PROTOBUF_PROTOC_EXECUTABLE
PROTOBUF_PROTOC_EXECUTABLE-ADVANCED:INTERNAL=1
//ADVANCED property for variable: PROTOBUF_PROTOC_LIBRARY
PROTOBUF_PROTOC_LIBRARY-ADVANCED:INTERNAL=1
//ADVANCED property for variable: PROTOBUF_PROTOC_LIBRARY_DEBUG
PROTOBUF_PROTOC_LIBRARY_DEBUG-ADVANCED:INTERNAL=1
```

About 'protobuf-compiler' it is marked amd64 in the architecture section on the left.

I can do additional tests if you see something.

Guillaume.

**Comment by ctrlaltca** [comment]
So, when cmake ran it detected a "/usr/lib/i386-linux-gnu/libprotobuf.so" file that gcc can't find anymore when compiling.. did you try wiping out che compilation directory and starting from scratch?

**Comment by GuillaumeSeren** [comment]
Maybe it comes from an other attemps on an other machine, I'll test it.

@ctrlaltca thank's for you reply.

Guillaume.

**Comment by GuillaumeSeren** [comment]
Damn it !
Since the build directory was in the in the .gitignore I didn't see it in the 'git status'.

It worked out by cleaning the build directory, then rebuilding it.

Thank @ctrlaltca for your help !

Guillaume.

**Comment by ctrlaltca** [comment]
You are welcome! closing
