### ISSUE TITLE
Connection

### ISSUE THREAD

**Issue by Bigdogdch** [Cockatrice/Cockatrice#1212]
Trying to connect and i get this message

"Socket Error.  Host not found"

Please help
Thanks

**Comment by Nightfirecat** [comment]
This isn't a Cockatrice issue, it's a server issue. See below:

* https://twitter.com/woogerworks/status/617595627556470784
* https://twitter.com/woogerworks/status/617596628485173248
* https://twitter.com/woogerworks/status/617747872717623296
