### ISSUE TITLE
Client Version Check

### ISSUE THREAD

**Issue by woogerboy21** [Cockatrice/Cockatrice#1214]
Any idea how we could implement a client version check?  It would be nice to notify a user when they connect to a server if they are running an older client and to consider upgrading.  The first thing I thought was to have a DB entry (maybe in the schema table) and have the client pass a number to the server and compare it against. 

This may not be the best idea and am open to hearing other idea's.

**Comment by ZeldaZach** [comment]
inside of the servatrice.ini file we should add a "min_requirement" and a "suggested_min" so the server can say "hey if you don't have a client that was made on date1 then you can't connect" and "hey you should update to this client as we're going to discontinue yours in the near future!"

**Comment by woogerboy21** [comment]
ini might be better, i wasnt thinking they would be denied but i guess that could be an option.  i wonder if you can pull the commit date of the version being compiled and place it in the client some were as the commit date would work well as a check

**Comment by Daenyth** [comment]
I'd support what @ZeldaZach says if we use it sparingly. If it's a weekly message people will ignore it.

**Comment by woogerboy21** [comment]
@Daenyth well if its a .ini configuration option it would be at the server operators discretion .  Personally as an operator I would use it when I found major feature improvements were available.  Such as the in client account management. functionality that @ctrlaltca has created.  But thats not to say other server operators wouldnt choose to change there config on a more aggressive time frame.

**Comment by ZeldaZach** [comment]
Nothing wrong with a server owner being more aggressive @woogerboy21. They want their players to have the best experience possible

**Comment by woogerboy21** [comment]
@ZeldaZach Nope there isn't.  Just wanted to point out that it would be at the operators discretion since @Daenyth seemed hesitant

**Comment by Daenyth** [comment]
I was imagining this would be hardcoded.

There's a question of whether to use build data or protocol version.

For this feature I think build date (read: date stamp of the git commit) is most appropriate.

**Comment by ZeldaZach** [comment]
I was thinking of parsing the build date from the version we include in client, but I'd like to see this done in the INI over being hardcoded. We can always include a "github operator suggested min version" which is hardcoded, but allow server operators to make the requirements more strict
 + i.e. if we hardcode that clients made on `Jan 1, 2015` are still usable, the server operator can make the requirements `Jan 2, 2015` or newer from the INI

**Comment by woogerboy21** [comment]
@ZeldaZach - 'I was thinking of parsing the build date from the version we include in client
Your not suggesting we have it hard coded some were a date that has to be constantly updated are you?

**Comment by ZeldaZach** [comment]
I really don't know what @Daenyth wants specifically, so I was considering hard-coding for a bit.

@woogerboy21 There should be a developer set version, that probably uses the protobuf API, saying "you can't use clients older then X" and then we allow server operators to set their own suggested & min requirements

**Comment by Daenyth** [comment]
The client at build time would get an autogenerated hardcoded date, just like it does for git commit hash right now. We extend the existing gitversion header to include the date.

Servatrice ini could accept a date string like `recommended_build_date=2015-07-01` which would message users with a build date lower than that.

**Comment by Daenyth** [comment]
Like https://github.com/Cockatrice/Cockatrice/blob/master/cmake/createversionfile.cmake

**Comment by woogerboy21** [comment]
Just as long as the date pulled in is the date of the commit and not the date on the machine at the time of compiling.

**Comment by ctrlaltca** [comment]
The date coming from cmake is the date of the last included commit: https://github.com/Cockatrice/Cockatrice/blob/master/cmake/getversion.cmake#L4

**Comment by woogerboy21** [comment]
So there has been a couple of proposed solutions put towards this and I am curious on people's thoughts on the direction it should go.  Both are discussed in #1419 .  The first was a client update notification based on commit number with date and time checking and another by @Daenyth that was proposed to implement a feature list that is compared and user notification occurring (https://github.com/Cockatrice/Cockatrice/pull/1419#issuecomment-134771855) .

My over all goal was to keep the current methodology of keeping a feature list to commit level requiring a simple check to be done for client updates.  Were as the goal presented with the solution provided by @Daenyth allows for more.

What is everyone's opinions?  

Personally I like the idea @Daenyth has but fear that having to either manually maintain a listing of feature or expecting some one to add a function call to append to the feature list could be troublesome down the road.

**Comment by Daenyth** [comment]
I think if we store the feature list as constants it will be easy to catch during code review when someone forgets to add one.

I see the two aspects as orthogonal, which is why I propose that approach. One aspect is, can the client and server communicate with each other effectively, and does the client support actions the server admin considers mandatory. It's about compatibility. The other aspect is client being up to date - this is a workflow primarily about keeping user experience improving. It's not a concern for the server if the client has a UI update to do highlight notification, for example. I think we can arrive at an architecture that's easier for us to extend and maintain if we compartmentalize responsibility as much as possible.

I have a workflow in my head for client-side only update checking; it requires some infrastructure we don't have yet, I'll write up the list as soon as I can - I think it will help make this more clear, because it relates to the feature negotiation that I was proposing.

**Comment by woogerboy21** [comment]
> it requires some infrastructure we don't have yet,

You had me till this statement.  When you say things like this it makes me question the direction of things.  IMO the code shouldn't rely on any type of external infrastructure.  I believe what your expecting to put in place is something for consistency checking which may not be a bad thing, but once again it shouldn't be relied on.

**Comment by Daenyth** [comment]
I'll try to make a detailed post as soon as I can with the info for it. It's totally doable and each step by itself shouldn't be large.

**Comment by woogerboy21** [comment]
It isn't a matter of doable.  Its a matter of future dependency.  As an example, say in the not so distant future we get bored with the code ( or simply loose the time to maintain it) and some one else decides to take up maintaining it.  They shouldn't be forced to put some type of infrastructure component in place to make sure things are maintained.  The solution should be simple enough to be independent on external expectations.  Especially if the external expectation is a human based one as it sounds like what your proposing is a list of features to be maintained and with out some type of infrastructure to maintain it , the maintenance will fall back to faulty humans (us) which is a bad design IMO.

The DB schema table get's close in the same aspect as this concern but it's justifiable as being a dependency for the application to operate properly period.  This is slightly different as the app doesn't rely on it to operate, its just a notification functionality addition.

**Comment by woogerboy21** [comment]
The other thing to mention (that was briefly discussed or stated) was neither solution really solves the potential for multiple servers running different revisions of the code.  Both falter on notifying the user definitively of an update as there is no one main source for code that users are required to go to and I don't believe there ever should be.  The best that can occur is that a user is notified if a server is running a different version of code than what the client is using.  If you want to pass feature functionality back and forth that may be good for troubleshooting what a client is missing.  But the goal of the issue wasn't to create a single trusted source for product code.  It was to notify the user if the version they are running is older than the version that the server they are connecting to is older suggesting that there is a product update available.

**Comment by woogerboy21** [comment]
Closing as #1439 implements what is needed.
