### ISSUE TITLE
Set up Windows automated builds on Appveyor

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#1218]
Like travis but for windows

**Comment by woogerboy21** [comment]
Would this replace #1198 ?

**Comment by Daenyth** [comment]
I think we should do both. Potentially this will require implementing 1198

**Comment by ZeldaZach** [comment]
Seems like Appveyor is causing all PRs to fail atm

**Comment by Daenyth** [comment]
I reconfigured it to skip branches lacking appveyor.yml

**Comment by woogerboy21** [comment]
@Daenyth I added the VS2013 compile instructions on the wiki if it will help out with this in any way.

**Comment by Daenyth** [comment]
It probably does

**Comment by Daenyth** [comment]
ref: https://github.com/kvirc/KVIrc/
