### ISSUE TITLE
no card images showing up in cockatrice, except my custom ones.

### ISSUE THREAD

**Issue by RYANoceros92** [Cockatrice/Cockatrice#1229]
My friend and I are experiencing the same problem yesterday we were playing fine and now we both cannot see any card images.

**Comment by ZeldaZach** [comment]
Please read [our FAQ wiki page](https://github.com/Cockatrice/Cockatrice/wiki/Frequently-Asked-Questions#some-of-my-cards-dont-have-art) and see if that helps.

**Comment by woogerboy21** [comment]
Also can you give a bit more information about the OS your on, did you custom build and if so he build details as to version?

**Comment by ZeldaZach** [comment]
Please reopen if this is still an issue for you.
