### ISSUE TITLE
Deck editor does not respect disabled sets

### ISSUE THREAD

**Issue by dstinct** [Cockatrice/Cockatrice#1231]
It's really frustrating to have disabled sets load images before enabled ones. Can you have a button or function in the sets editor that moves all disabled sets to the bottom of the set editor. Unfortunately the set editor cannot filter by enabled/disabled right now. It just reverses the current order of the sets.

**Comment by ZeldaZach** [comment]
If a set is disabled, the client should skip over that image (whether it has to download it or it's already saved on the harddrive) when attempting to load in set-order.

cc: @ctrlaltca

**Comment by dstinct** [comment]
I just noticed the text that said it will still load pics. I guess the only way to fix it is to have an ability to move all disabled sets to the bottom.

**Comment by ZeldaZach** [comment]
While it does say it will still load pics, @dstinct, I think I'd like to potentially see the feature changed as you disabled the set for a reason.

I think at this point it should internally change how it handles the sets.
If ORI and MM2 are disabled, then it should attempt to load the pic in this order
`M2015 -> KTK -> ... other sets ... -> ORI -> MM2`

This is to allow the card to potentially be downloaded & allow being disabled to mean something more.

**Comment by ctrlaltca** [comment]
This has already been discussed, please read #1072.

**Comment by Daenyth** [comment]
See #1235
