### ISSUE TITLE
Disabled sets should be lowest priority for image downloads

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#1235]
This should be automatic without user intervention

ref #1072 #1231

**Comment by ZeldaZach** [comment]
This needs to be done in two places:
```
void PictureLoader::processLoadQueue()
void PictureLoader::startNextPicDownload()
```
(both in `cockatrice/src/carddatabase.cpp`)

**Comment by ctrlaltca** [comment]
Poll on this: you would prefer disables sets:
 1. not to be used for card download at all (possible cause of missing images if you have no set defining a card at all);
2. used for card image download only _after_ all the enabled sets have been checked and failed; the sets order in the "sets window" stays the same;
3. same as 2, but in the "sets window" disabled sets are immediately moved to the bottom.

I suppose option 3 sounds as the most reasonable, but it's problematic from an UI PoV:
 * if you uncheck a set by mistake you'll have an hard time finding it again;
 * if you check a previously unchecked set, when will it end up? at the beginning of checked sets? at the end?
 * it breaks sorting of the table; you can't sort eg. by date anymore (possible solution: split the table into 2 tables with enabled and disabled sets)

**Comment by MassCraziness** [comment]
I like Option 1 the most @ctrlaltca mostly because then I can keep sets ordered from newest to oldest, but simply turn off the ones I don't want to use for images. Anything else just feels awkward to me (especially moving them, where it would mess with my ability to see things from newest to oldest).

**Comment by Daenyth** [comment]
You guys are making this too complicated.

A disabled set can preserve its position in the order of sets in the window. There's no issue with moving it or losing it.

When constructing the pic download url we simply sort the sets differently. All disabled sets sort lower than enabled sets. Then if enabled flag is the same, we fall back to sorting by configured position.

**Comment by ctrlaltca** [comment]
Got it, will implement it this way.
