### ISSUE TITLE
Missing .ini settings aren't added on update

### ISSUE THREAD

**Issue by skwerlman** [Cockatrice/Cockatrice#1237]
When I updated my server to the current head from a build without registration, none of the [registration], [smtp], or [users] settings were added to my ini.

This is an easy fix on my end, though it would be preferable if were automatic.

**Comment by ctrlaltca** [comment]
I don't think it's a good idea for us to edit your ini configuration file. You could have changed it, moved options around, added and removed comments. How to be sure to update it without disrupting it?
Anyway, all the new (missing) options will default to the same default value defined in the ini.

**Comment by poixen** [comment]
maybe we could have a better way to use the inis. Maybe some form of schema to confirm the min values are there?

Anywho the server does have hard coded defaults should you be missing values.

**Comment by ctrlaltca** [comment]
Yes, this is definitely improvable.

**Comment by Daenyth** [comment]
Perhaps servatrice could warn on missing settings?

**Comment by woogerboy21** [comment]
@Daenyth  (and others)
Thinking about this, I would have to agree I don't like the idea's of the actual modification of an ini even if it were additions.  How ever for the notifications, were you thinking a console output?  In the logs?  Both for that matter?

**Comment by FluxIX** [comment]
When I have had to implement things like this in the past, I have kept the data which was present and then appended the new values to the end of the file. These may be actual seen key-value pairs or commented-out examples of how to add the key-value pairs.

Another option might be offering to merge the data, but that would be more confusing to the user.

**Comment by woogerboy21** [comment]
Im just not a fan of overwriting or manipulating the .ini file as I can not predict the future as to the need for custom .ini files and manipulation involved.  I would have to agree with @Daenyth though a warning at the very least would be nice.

**Comment by ctrlaltca** [comment]
We can't just append the new options at the end of the file, since the options are structured inside ```[groups]```. Using QSettings we could write the missing options back to the file, but this would mean wiping away all the comments.

**Comment by Daenyth** [comment]
After you `make install`, diff the new config.

We can probably try to be better about giving notification for new
features and flags

**Comment by woogerboy21** [comment]
FYI, the winders equiv to diff is the command FC
stackoverflow.com/questions/6877238/what-is-the-windows-equivalent-of-the-diff-command

**Comment by woogerboy21** [comment]
The two options I see is either we write a function that verifies the ini sanity or we write a check in when the settings cache is called that tests if value(s) are default and warn when they are.The former is the fix but will require some maintaining that I think everyone tries to avoid, the latter can produce false positives but does not require those maintenance steps.

**Comment by Daenyth** [comment]
I think it's sufficient to provide a good changelog with migration guide
for servatrice settings.

**Comment by ZeldaZach** [comment]
When we do changes, we can write them in on the release notes

**Comment by ZeldaZach** [comment]
I'm not sold on this
