### ISSUE TITLE
Sidebar no longer auto-adjusts size.

### ISSUE THREAD

**Issue by Psithief** [Cockatrice/Cockatrice#1239]
![both_space_waste](https://cloud.githubusercontent.com/assets/1124846/8633934/814675a2-2816-11e5-962c-81342e8a9b7a.png)

(v. 3189045)

The sidebar on the right of the screen no longer adjusts size to show as much as it can.

The options are now:
- Image, nearly twice as high as it needs to be.
- Descrption, there has never been a card printed that needs this much text space
- Both, where the image displayed is no bigger than the card hovered.

What happened?

**Comment by Daenyth** [comment]
I wonder if this is related to #1189

**Comment by Daenyth** [comment]
Maybe try reverting that and then compiling?

**Comment by Psithief** [comment]
I can't compile.

**Comment by Fizztastic** [comment]
As far as I know, those changes all happened with  https://github.com/Cockatrice/Cockatrice/commit/d6ce1852a1fdcac3bbe33a6d20b155d5b7abccc3

**Comment by Psithief** [comment]
I'm going to be honest, I have no interest in ever compiling Cockatrice myself. You'll have to weigh the issue on its own merits rather than my willingness to investigate.

**Comment by Daenyth** [comment]
I'm sure we'll get around to fixing it.

**Comment by ZeldaZach** [comment]
Resize should be working now
