### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by JineteDV** [Cockatrice/Cockatrice#124]
Was spectating two games when it crashed...From the console

6/24/14 8:19:34.351 AM com.apple.launchd.peruser.501[164]: ([0x0-0xae0ae].cockatrice[2689]) Job appears to have crashed: Segmentation fault: 11
6/24/14 8:19:34.427 AM ReportCrash[2827]: Saved crash report for cockatrice[2689] version ??? (???) to /Users/azix_zan/Library/Logs/DiagnosticReports/cockatrice_2014-06-24-081934_Jinetes-MacBook-Pro.crash
6/24/14 8:19:39.798 AM SIMBL Agent[289]: warning: failed to get scripting definition from /Users/azix_zan/Desktop/Cockatrice-master 2/cockatrice.app; it may not be scriptable.
6/24/14 8:19:39.996 AM cockatrice[2834]: Performance: Please update this scripting addition to supply a value for ThreadSafe for each event handler: "/Library/ScriptingAdditions/SIMBL.osax"
6/24/14 8:19:52.231 AM WindowServer[94]: _CGXRemoveWindowFromWindowMovementGroup: Window not in group
6/24/14 8:19:52.275 AM cockatrice[2834]: modalSession has been exited prematurely - check for a reentrant call to endModalSession:
6/24/14 8:20:15.237 AM cockatrice[2834]: modalSession has been exited prematurely - check for a reentrant call to endModalSession:

https://www.dropbox.com/s/ekgo3xxkz0xoavy/CrashReport6%3A24%3A14.rtf

**Comment by Daenyth** [comment]
dupe #29
