### ISSUE TITLE
about the text area

### ISSUE THREAD

**Issue by FrozenSlave** [Cockatrice/Cockatrice#1242]
Can we move the room clock somewhere else?  the bottom right of the screen has very little room for the text areas. can we give the text area maybe 3-4 more lines? i have it set to small but i only get about 4-5 lines of text in it and it can be cumbersome. A few more lines would make less scrolling to find out what just happened, or how my opponents turn progress in a mutiplayer game. also helps when hands get discarded and what not.  On this note can we make the "show card" area size adjustable? where me the user can make it smaller. this would also free up some lines in that area. just suggestions.

**Comment by poixen** [comment]
Could you post a screen shot of how it looks for you? You can drag and drop images in here when you are writing messages.

**Comment by FrozenSlave** [comment]
I am on a new Machine and its windows 8  tried to take a screenshot but its not allowing me to. sorry it looks like a normal screen

**Comment by ctrlaltca** [comment]
The "show card" area size is already adjustable, you just need to drag its bottom border up to make its size smaller.

**Comment by FrozenSlave** [comment]
the only box that moves is the "player box"  the one with the player's
names in it. the "card description" box does not move.  (i mean in game)

**Comment by ctrlaltca** [comment]
So, i made some tests.
This s the old behavior:
![old](https://cloud.githubusercontent.com/assets/1631111/8787425/4e191944-2f34-11e5-901d-ffea2a3159e8.gif)
This is the new behavior:
![new](https://cloud.githubusercontent.com/assets/1631111/8787432/582b4ab0-2f34-11e5-8f76-340d456688d8.gif)

I still don't fully understand the problem.

**Comment by Daenyth** [comment]
I think most people used it in card only mode and never ran into the bug that prevented you from shrinking it further. I think we should permit users to shrink it down quite small.

**Comment by ctrlaltca** [comment]
I think this is superated now that all elements can be resized, grouped and detached.
