### ISSUE TITLE
Socket error

### ISSUE THREAD

**Issue by Bigdogdch** [Cockatrice/Cockatrice#1245]
Keep getting a socket error again. this time it's connection timed out
Please advise
Thanks

**Comment by woogerboy21** [comment]
What address are you using for your host?

**Comment by Bigdogdch** [comment]
Using the connection for the IP address as Host:  198.199.69.27
Port 4747

**Comment by woogerboy21** [comment]
try using the name instead of that ip.  either:
cockatrice.woogerworks.com
cockatrice.woogerworks.info

**Comment by Bigdogdch** [comment]
OK.
Tried the 1st one before and didn't work.  Now it does
Thanks

**Comment by ZeldaZach** [comment]
This is related to a server, not the code base. Closing

**Comment by woogerboy21** [comment]
Yeah, the .com is actually functional.  Its still replicating out to the world so people will start to show it as usable over the next 2 days depending on were you are in the world.
