### ISSUE TITLE
In-client registration should confirm users email and password

### ISSUE THREAD

**Issue by poixen** [Cockatrice/Cockatrice#1248]
When trying to register from the client, there should be an additional "confirm password" and "confirm email" line. We should compare the two before submitting. I have had a bunch of issues where users enter `blah@gmal.com` and then have to register again.

**Comment by woogerboy21** [comment]
:+1: I like the idea.  Not certain it will fix the human factor but should help.

**Comment by ZeldaZach** [comment]
Maybe the field should prevent copypasta so they have to type it out
