### ISSUE TITLE
Uninstalled and reinstalled to get newest client. Now cant run program at all (Cockatrice)

### ISSUE THREAD

**Issue by bmoorman05** [Cockatrice/Cockatrice#1251]
I wanted to register an account for cockatrice and the website told me that I had to do it in the client. I didn't have the latest client so the option wasn't there. I went back to the website and it told me to download the newest client to get the option to register. I uninstalled the current version I had and downloaded the latest. Now when after I install it asks if I want Oracle to update the cards. I say yes and the application closes and nothing happens. Now when I go to launch the application it says:

"The program can't start because MSVCP120.dll is missing from your computer. Try reinstalling the program to fix the problem"

I uninstalled and reinstalled multiple times restarting in between uninstall and reinstall also. 

Nothing works.

Please help.

Thank you,

Brian

**Comment by bmoorman05** [comment]
I am using Windows 7 64 bit.

**Comment by ZeldaZach** [comment]
Please check our wiki troubleshooting section as this has been solved numerous times for others already.

**Comment by bmoorman05** [comment]
Can you please link me,  I was  looking for a FAQ and couldn't find one.

**Comment by bmoorman05** [comment]
I found it, thanks

**Comment by ZeldaZach** [comment]
Yeah, sure. Click [here to get to the wiki](http://github.com/Cockatrice/Cockatrice/wiki)
