### ISSUE TITLE
Liliana of the Veil

### ISSUE THREAD

**Issue by Thoughtseizes** [Cockatrice/Cockatrice#1255]
I just got Cockatrice to do some theorycrafting, the first card I typed into the list is: Liliana of the Veil.

It isn't in the list... You have all the other ones, even the Origins Liliana but the Modern staple is MIA.

Seems odd?

**Comment by ZeldaZach** [comment]
Seems to be there for me
<img width="1082" alt="screenshot 2015-07-13 21 05 23" src="https://cloud.githubusercontent.com/assets/7460172/8664270/e36044e2-29a2-11e5-95bb-e1ec6d3c3750.png">

Can you try re-running Oracle and make sure you have no filters on?

**Comment by Thoughtseizes** [comment]
How weird this is what it looks like for me:

![lil](https://cloud.githubusercontent.com/assets/13323922/8664308/506cad5a-298a-11e5-99ff-06f580dfa758.png)



I'll try what you suggested. Thanks!

**Comment by Thoughtseizes** [comment]
Yup that did the trick! Thank you. Sorry for being such a nubnub >_<

**Comment by ZeldaZach** [comment]
Glad I could help!
