### ISSUE TITLE
Server PM Messages

### ISSUE THREAD

**Issue by woogerboy21** [Cockatrice/Cockatrice#1265]
It would be nice to have the ability for the server to send private messages.  WHAT you say?  Here is my thoughts on it.  If the server has the functional ability to send a PM to a user we could implement things like announcements to the moderation staff when a ban occurs and what for.

**Comment by ZeldaZach** [comment]
:+1: for sure, just the implementation will be annoying. Maybe have an account, "Server" that's reserved by the system to send these messages? Also what happens when a user responds, if they have the option? Where will the info go?

**Comment by woogerboy21** [comment]
I never anticipated the idea of some one trying to send a message to a user named "Server".  Though that idea is kind of funny cause we could implement some interesting responses.

**Comment by ZeldaZach** [comment]
This is accomplished in #1522
