### ISSUE TITLE
Temporarily Saving PMs (as well as, perhaps, main room chat and game room messages/chat)

### ISSUE THREAD

**Issue by MassCraziness** [Cockatrice/Cockatrice#1268]
This is both a suggestion to solve #982 as well as help any people who may DC and lose all the lines of chat they may have wanted/needed.

With this, these lines would be saved in some "log" file(s), which will then place the text back in their appropriate window, with appropriate timestamps. These should, ideally, be able to be:

* Size/length/time limited
* Cleared on command
* A toggle option
* Able to place game move commands as well as spoken words (if in game rooms)

**Comment by ZeldaZach** [comment]
I feel like this is accomplished by #1474
