### ISSUE TITLE
Account Settings

### ISSUE THREAD

**Issue by JineteDV** [Cockatrice/Cockatrice#1269]
Just updated cockatrice yesterday and no matter what I do I cannot set my country/flag. On OSX 10.10.4.....It seems like I can only set the flag if I also set my gender pronouns to something other than neutral.

**Comment by MassCraziness** [comment]
This issue is also on Windows 8, I just tested it.

**Comment by ctrlaltca** [comment]
Ive just committed a fix for this problem. Nice catch, it was quite hard to notice while testing.
