### ISSUE TITLE
PM contents should not be shown in alert bubble

### ISSUE THREAD

**Issue by poixen** [Cockatrice/Cockatrice#1273]
If you leave a game and get pm'd hate from a user, rather than just closing the pm tab, you have to see the content they write to you. Also if you have the window minimized and someone sends you hate whilst someone else is looking at your comp.. it looks bad.

**Comment by LestatTheDarkPrince** [comment]
as far as i know you can turn that feature off in the settings.

**Comment by poixen** [comment]
You can disable the popup. I don't think you can disable the bubble message though. I don't remember adding that feature.

**Comment by Daenyth** [comment]
I also don't remember that.

**Comment by ZeldaZach** [comment]
You can just block the user if you don't want msgs from them.
