### ISSUE TITLE
Servatrice failing to start with to new of a schema version

### ISSUE THREAD

**Issue by woogerboy21** [Cockatrice/Cockatrice#1275]
If you attempt to start the server with a schema version number in the database newer than the version number compiled in the app you get a message saying the schema version is to old and to run the migration tool to update it from version {newnumber} to {oldnumber} (ie: version 2 to 1.).

We probably should either update the warning message saying something more like "fix your schema versions so they match" or allow the newer version schema to run with the older application numbers.

Thoughts?

**Comment by woogerboy21** [comment]
![capture](https://cloud.githubusercontent.com/assets/1361287/8767494/a9335104-2e2c-11e5-8a57-5b191cdc974f.PNG)

**Comment by ctrlaltca** [comment]
I agree that the message should be fixed in the case the db version is higher than the servatrice version.

**Comment by ctrlaltca** [comment]
Running an old servatrice with an newer schema version is possibly as problematic as the opposite, so i suppose it's a good behavior to avoid it from starting and report an error.
