### ISSUE TITLE
Bad UI Changes (aka stop screwing with things poixen!) -Or- If it ain't broke, DON'T FIX IT

### ISSUE THREAD

**Issue by gigapow** [Cockatrice/Cockatrice#1276]
Several UI chnages were made which are terrible for useability. They appear to have been made by poixen sometime in early May. 

1: The "View Library" pop up window, which looks to be created by viewzonewidget.cpp, was messed up. First, for no reason, a darker gray background was put in the interior of the window. In zoneviewzone.cpp this code was added for NO reason

void ZoneViewZone::paint(QPainter * painter, const QStyleOptionGraphicsItem * /*option*/, QWidget * /*widget*/)
{
    QBrush windowBrush(QColor(240,240,240));
    windowBrush.setColor(windowBrush.color().darker(150));
    painter->fillRect(boundingRect(), windowBrush);
}

This makes grey next to dark gray next to text meant to be read, which is a TERRIBLE for eye strain. It also fixes no usability issues and looks like it was added just because the developer individually thought it looked cool. This should NEVER be a reason to change a UI. EVER. EVER. 

2: The window title and close button on that pop up window were also changed. Previously, the title bar was the standard size (dark gray on gray as well, but that's beside the point) and the "Close" button was a reasonable size, somewhere around 30x70 px. The new window cuts the title bar to less than HALF the height of the old one, making the level of accuracy the user needs to use to move the window double what it used to be. Also, for some completely inexplicable reason. the normally easy to click Close button was replaced by a button that's roughly 2px x 2 px in size, making it WAY harder to click than it used to be. Once again, neither of these things were broken in any way, they appear to have been changed to meet the developers personal preference for small screen elements. This should not be how community development happens

3: You can no longer resize the top third of the right sidebar in the game room/during a game. The smallest you can make it is the size of the card preview, even if you have the txt only preview selected. This seems to have coincided with a change from a drop down box to radio buttons for selected the preview mode, a change that wasn't needed, didn't fix anything that was broken, and broke something new. Once again, nothing about the way it was done was broken, not working, or causing any problems. It seems to have been changed for no reason other than some developers personal preference. 

I had to go back to a May 1 version of the code and build that from source to get rid of these "enhancements". It reeks of the change in table color from blue to gray. I don't know who this poixen guy is, but he should keep his affinity for tiny window elements, monochrome gray screen colors, and trying to code in his personal "design" choices out of Cockatrice.

**Comment by woogerboy21** [comment]
Thanks for your feedback.  There is a number of client side settings that are being worked into the client to allow customization.  Other things you mention are in fact bugs introduced with the advancements we are making in the code.

**Comment by gigapow** [comment]
What "advancements"? You are breaking things that aren't broken!

Although I can see that there is no interest in hearing feedback, just silencing anything you disagree with. I guess we are just a few versions away from hardcoded anime chicks, full monochrome layout, and text only input, cause poixen LIKES IT THAT WAY!!

**Comment by ctrlaltca** [comment]
Please, don't put it personally against a single developer. He's offering his time and skills for free, trying to improve this project. If you don't like a change, let's talk about the change, not the one who did it. 

Moreover, you stated your opinion but, being just your opinion, you should try to be polite and don't offend people just because they see thing different from you.

Last, shouting on a bugtracker because you think somebody broke "your" game and attacking this individual is really childish, because it won't surely help getting your problems solved; instead, you will only attract people's dislikes.

If you want to build up a serious discussion about these changes, please start over.

**Comment by ctrlaltca** [comment]
> Although I can see that there is no interest in hearing feedback, just silencing anything you disagree with.

Please check the previous thousand bug tickets, you will see this is not actually true. Don't you really understand the reason why this ticket has been trashed? Hint: your behavior.

> I guess we are just a few versions away from hardcoded anime chicks, full monochrome layout, and text only input, cause poixen LIKES IT THAT WAY!!

Thank you for these further suggestions, we'll see what we can do about them.

**Comment by Daenyth** [comment]
@ghost if you have specific complaints about specific changes please ticket them individually with screenshots.

Here's an example that would be productive:

> The foobar was changed to look like quoz and it used to look like quif. This makes the user experience worse because baz. Here's a screenshot showing the problem

**Comment by poixen** [comment]
Guys, right, but off topic, but listen, just had an awesome idea. 

Do any of you like anime...?

**Comment by woogerboy21** [comment]
:facepunch:
