### ISSUE TITLE
The procedure entry point_except1 could not be located in the dynamic link library C:/Program Files\Cockatrice/servatrice.exe 

### ISSUE THREAD

**Issue by azas9s4d9** [Cockatrice/Cockatrice#1279]
Sorry if this doesn't belong here, but I am trying to run Cockatrice for the first time on a new ASUS notebook with Windows 8 and I get this error:

The procedure entry point_except1 could not be located in the dynamic link library C:/Program Files\Cockatrice/servatrice.exe 

I tried uninstalling and reinstalling but I can't get it to work.

**Comment by woogerboy21** [comment]
First thing I would check is that you have the required redistributables installed.  Check out the github wiki troubleshooting page for the 120.dll error and download / install that requirement.  Also MS site states this:

For Windows 8.1 and Windows Server 2012 R2, KB2883200 (available through Windows Update) is required.


Start there.






From: azas9s4d9
Sent: ‎Tuesday‎, ‎July‎ ‎21‎, ‎2015 ‎12‎:‎18‎ ‎AM
To: Cockatrice/Cockatrice





Sorry if this doesn't belong here, but I am trying to run Cockatrice for the first time on a new ASUS notebook with Windows 8 and I get this error:

The procedure entry point_except1 could not be located in the dynamic link library C:/Program Files\Cockatrice/servatrice.exe 

I tried uninstalling and reinstalling but I can't get it to work.

**Comment by MassCraziness** [comment]
Are you trying to run the client or a server? The client is "cockatrice.exe"

**Comment by azas9s4d9** [comment]
Thank you, I got it.
