### ISSUE TITLE
problem starting cockatrice :(

### ISSUE THREAD

**Issue by willskate15** [Cockatrice/Cockatrice#1280]
When i try to start cockatrice I get an error that because MSVCPL20.dll is missing. I installed the missing dll file but it still isn't working and now says "The application was unable to start correctly (0xc0000022)". Help please?

**Comment by ZeldaZach** [comment]
Check out our troubleshooting wiki

**Comment by ctrlaltca** [comment]
https://github.com/Cockatrice/Cockatrice/wiki/Troubleshooting#failed-start-because-msvcp120dll-was-not-found

**Comment by willskate15** [comment]
It says I'll have to download an older version of cockatrice for my computer because I don't have modern software. Is there a version I can download that will still work with oracle to get all the cards? Anyone have the download handy?

**Comment by Daenyth** [comment]
What says that? Screenshot? What version of windows are you using?

**Comment by willskate15** [comment]
The troubleshooting wiki explaining my problem says that.
https://github.com/Cockatrice/Cockatrice/wiki/Troubleshooting#failed-start-because-msvcp120dll-was-not-found
I'm using windows 7

**Comment by ctrlaltca** [comment]
Please try following the instructions we linked for "Failed start because MSVCP120.dll was not found", aka installing the x86 installer from Microsoft (MSVC2013).
