### ISSUE TITLE
Questions and comments

### ISSUE THREAD

**Issue by jjo2997** [Cockatrice/Cockatrice#1282]
1) **Edit sets dialog writes to an defined, editable file**

For reference, the edit sets dialog

![edit sets](https://cloud.githubusercontent.com/assets/7950979/8804604/12a73faa-2f9b-11e5-9e1d-1ad664b8aa09.png)

which controls how art looks in the program. Currently it writes to a registry file (on Windows) or god knows where (on Mac). I can't read registry files and I haven't been able to find the file on Mac. Would it be too difficult to have the order of the sets as defined by the edit sets dialog write to a (for example .txt) file defined by the program that a user could clearly see by going into Settings / Preferences? That way it could be copied and manipulated and didn't get overwritten every time you updated the client, and you could move it between computers instead of having to manually rearrange it every time.

2) **Add functionality for moderators to close rooms without having to enter them / ability to right click rooms in the 'Games' box**

I, at least, would be far less loath to close old rooms if I didn't have to physically enter them and kick everyone in the room. The process doesn't take long, but it's tedious, and the minute (or so) that it does take adds up when you're closing multiple rooms. Is right-click functionality feasible?

3) **That horrible forced Oracle**

There is no benefit to an Oracle that forces you to download all sets over the old one with the checkboxes...where you still have the option to download every set, but you can also manually do it and not get all the reprint sets and the silver-bordered sets and the sets with fake cards that clutter up the deck and sets editor.

**Comment by Daenyth** [comment]
1 - Semi related to #424 in that ini-writing would solve it (kind of)

2 - I'm not sure this is useful. Moderators should generally speak to the people in a room before closing it. If it's just old, then the sort by room age feature generally takes care of those. Can you elaborate here?

3 - I think all of your complaints would be addressed by solving #1235

**Comment by ctrlaltca** [comment]
> As for clutter in the deck editor, maybe we can make disabled sets not show up - I thought this was already the behavior.

It's the current behavior.

**Comment by jjo2997** [comment]
2 - Speaking to a room owner before you close a room _is_ the default behavior, but if the room is 5+ hours old, passworded, and buddies only, it's safe to bet there's no one in there, and the ability to not have to join the room, wait some amount of time for no one to respond, kick the head of the table, and then leave the room would be a breath of fresh air. Alternatively (or in addition to), would it be possible to add a bubble that displays a snapshot of the room info in greater detail if you hover your mouse over it for a couple of seconds?

3 - It is true that disabled sets don't show up in the deck editor...but they show up here:

![fuck](https://cloud.githubusercontent.com/assets/7950979/8911055/1b6aa2fa-3458-11e5-867f-267b6c334a2f.png)

If you want to arrange your sets in a specific manner, a process which already takes a long time, suddenly you have dozens of useless sets to sort through. And since you can't select and manipulate multiple sets at the same time, an already tedious affair just becomes a vortex in which hours cease to have meaning. Reading #1235, it seems that option 3 as argued by @ctrlaltca would make the most sense...but in that case, why have Oracle behave like this at all? What was wrong with the old Oracle? Especially since Oracle is more tied to client functionality than ever with the 'create related card' function in Lightning Angel.

**Comment by ctrlaltca** [comment]
About 3:
That's the window where you disable/enable sets, if we hide them from there you won't be able to enable them from anywhere.

> What was wrong with the old Oracle?

 1. It forced everyone to check their preferred sets at every update;
 2. there was no good "default" list of default checked sets, because everyone play/likes in different ways (we got tickets to add some sets, then people complaining because those new sets added some reprints, then people complaining because we removed those sets.. and so on);
 3. if you missed a set in oracle, you could play without some cards and when noticing you had to re-run oracle, recheck all sets again, etc..

> but in that case, why have Oracle behave like this at all?

Now oracle imports all cards and sets. Sets are sorted by default by release date (newer to older), and all sets are enabled.
 * you surely won't miss a card
 * don't you like reprints from a set? just disable it
 * when the next update is out, just rerun oracle; cockatrice will ask you if you want to enable the new set; all the old settings (enabled sets, sets order) are kept as you previously defined.

By the way, #1235 got fixed.

**Comment by jjo2997** [comment]
Then offer Oracle as a stand-alone program or split 'trice repositories so individual people can have an solution that works for them.

**Comment by ZeldaZach** [comment]
I don't see a reason to split oracle from the main repo as it does its job. All of the past settings of Oracle can now be found in client.

**Comment by Daenyth** [comment]
We should split the remaining addressable issues into their own tickets (your no. 1 and maybe no. 2)

**Comment by ZeldaZach** [comment]
Feel free to open the tickets @Daenyth and I'll shut this

**Comment by ZeldaZach** [comment]
1 was solved already with a change over to ini files
2 still needs to be looked into

**Comment by ctrlaltca** [comment]
Splitted issue number 2 to #2063. Closing
