### ISSUE TITLE
Cant start cockatrice after new download

### ISSUE THREAD

**Issue by willskate15** [Cockatrice/Cockatrice#1285]
I tried to update and install the new version of cockatrice with oracle and I first got a pop-up saying: "Failed start because MSVCP120.dll was not found" so I downloaded the needed file and trhen got another message saying "Application failed to initiate correctly (0xc000001d)".
The troubleshooting page says: "Your computer processor is missing some instructions needed to run modern software: you should stick with a Cockatrice version built with older libraries, still compatible with your computer's processor.

Technical details: since version 5.3, the Qt libraries used by Cockatrice are compiled by default with SSE2 support enabled. More details if needed: #219"
Is there an older version I can find that will still be compatible with oracle? Anyone have another download that will work for my computer? :(

**Comment by Daenyth** [comment]
https://github.com/Cockatrice/Cockatrice/wiki/Troubleshooting#failed-start-because-msvcp120dll-was-not-found

**Comment by willskate15** [comment]
I've already looked at that but it says I need an older version of cockatrice compatible with my computer?

**Comment by willskate15** [comment]
Where would I be able to find that.

**Comment by ctrlaltca** [comment]
We should probably create a qt4 version of cockatrice, at least for official releases.

**Comment by willskate15** [comment]
That would be so awesome I really need to able to use cockatrice again to test for Grand Prix San Diego in two weeks.

**Comment by ctrlaltca** [comment]
Can you test this version and report if it works for you: https://drive.google.com/file/d/0B2e-_UrI3ByvOFNWSS1jdHVVVzA/view?usp=sharing . It's an unofficial build msvc10 + qt4.8.7.

**Comment by willskate15** [comment]
it worked thank you so much :)

**Comment by willskate15** [comment]
I'm still running the mscv10 + qt4.8.7 version you made me for me stopped working when I downloaded the new battle for zendikar set from oracle. It now says "Unknown login error: -1" every time I try to connect with one of my accounts. Any help with this issue? Is this version I'm running too old now?
