### ISSUE TITLE
Deck list is hard to read with dark UI theme

### ISSUE THREAD

**Issue by skwerlman** [Cockatrice/Cockatrice#1289]
I use a GTK theme which has a dark background and light text. This, combined with the white, green, and gray coloring in the deck editor makes the deck list extremely hard to read.

One possible solution would be to ensure that the text in the deck list is always black, rather than just assuming that the default will be readable.

Another option would be to make the deck list colors change with the theme.

Screenshot:
![4_037](https://cloud.githubusercontent.com/assets/6954107/8862081/048c35fc-315c-11e5-9a8a-e11b5b0c202f.png)

**Comment by woogerboy21** [comment]
@ctrlaltca how is #1081 coming along?

**Comment by ctrlaltca** [comment]
#1081 permits e customization of the client (images and style). It's quite ready for a test, but it still lacks any UI configuration.
I'd take the easy route suggested by @skwerlman to fix this.
