### ISSUE TITLE
Cockatrice exits soon after starting

### ISSUE THREAD

**Issue by MotherofRuins** [Cockatrice/Cockatrice#1290]
Windows 7 Pro SP1, Cockatrice Lightning Angel R1

Cockatrice worked great before upgrade to Lightning Angel and C++ 2013 redistributable.  Now when running Cockatrice, the pointer changes to hourglass for a few seconds, then nothing.  While this is happening, cockatrice process shows up in Task Manager:

cockatrice.exe *32    28,800 k

It stays there for 20 to 30 seconds, then it disappears.  This behavior is consistent on two different computers, both running Win 7 Pro SP1.

No amount of rebooting or reinstalling fixes this.  If someone builds a DEBUG version for me I'd be happy to post the logs.

**Comment by ctrlaltca** [comment]
Can you test this version and report if it works for you: https://drive.google.com/file/d/0B2e-_UrI3ByvOFNWSS1jdHVVVzA/view?usp=sharing . It's an unofficial build msvc10 + qt4.8.7.

**Comment by MotherofRuins** [comment]
That works.  Is that a version of Lightning Angel?

**Comment by ctrlaltca** [comment]
> That works. Is that a version of Lightning Angel?
Yes, with some more fixes in.
