### ISSUE TITLE
Cockatrice Problem (0xc000007b)

### ISSUE THREAD

**Issue by Rip-In-Peace** [Cockatrice/Cockatrice#1291]
tried a lot of things but still having this issue please help

**Comment by ctrlaltca** [comment]
Can you test this version and report if it works for you: https://drive.google.com/file/d/0B2e-_UrI3ByvOFNWSS1jdHVVVzA/view?usp=sharing . It's an unofficial build msvc10 + qt4.8.7.

**Comment by woogerboy21** [comment]
I have posted this build to http://www.woogerworks.com/files/cockatrice_weeklybuilds/Cockatrice-WindowsClient_Qt4_0d5e169.exe  for any other user interested or having this issue.

**Comment by ctrlaltca** [comment]
Thank you @woogerboy21

**Comment by Rip-In-Peace** [comment]
thank you this has seem to have fixed this

**Comment by ctrlaltca** [comment]
Thank you for your feedback.
