### ISSUE TITLE
Mod was unable to join MAIN room

### ISSUE THREAD

**Issue by poixen** [Cockatrice/Cockatrice#1297]
User @breakbriker was unable to join the MAIN chat room today. He had to log in and out 3 times for it to let him in.

He reported that he could see himself online in the room, but unable to join.

@woogerboy21 could this have something to do with his last logout session?

**Comment by woogerboy21** [comment]
Doubtful.  How was he able to see himself in the room when he wasn't in the room?

**Comment by ZeldaZach** [comment]
Doesn't make sense to me... does this have something to do with the server cap maybe?

**Comment by Daenyth** [comment]
Did it not autojoin or did it not let him manually join? I've seen failure to autojoin under network latency

**Comment by woogerboy21** [comment]
Is it safe to close this?  I for one dont have logs that go this far back and I haven't seen any responses really.
