### ISSUE TITLE
Unable to see the new planeswalkers Flip cards in Deck editor!!!!!

### ISSUE THREAD

**Issue by Dymitr33** [Cockatrice/Cockatrice#1298]
So I have done everything! Checked Oracle for updates, Im using Lightning angel client, Reset my downloaded pictures, downloaded Tokens.xml file and none of these actions have fixed the problem.

I can get any token I want but when I type in Any of the flip planeswalkers I get a blank card with the name of the card. 

I also have images of all the cards from Origins except for the 5 planeswalkers. I dont understand how this has happened. I have all the latest files. I know if I change the card database to an older xml file I will fix this issues but then I wont have images of THS and FRF cards. 

Please Help me.

**Comment by poixen** [comment]
I think this issue has now been solved. By deleting cards.xml and reusing oracle.

**Comment by ctrlaltca** [comment]
Maybe he was using one of the unofficial spoiler sets for ORI and still had the file in customsets/ ?

**Comment by ZeldaZach** [comment]
I was thinking that @ctrlaltca 

Based on @poixen comment closing
