### ISSUE TITLE
Game selection does not de-select if highlighted room becomes unavailable

### ISSUE THREAD

**Issue by Nightfirecat** [Cockatrice/Cockatrice#1299]
To be more clear - here's a use case which I've encountered multiple times, and been frustrated by:
1. Join a server room
2. Select a game (for instance, a Standard game with 2 players) which you intend to join
3. Wait for the game to become unavailable (second player joins game before you do)

In this instance, I'd expect that the game selection highlight would un-highlight, leaving _no_ game selected.  
What actually happens is the game below it in the server listing is highlighted instead.

**Comment by ZeldaZach** [comment]
Nice catch. If you have "show unavailable games" ticked, then the full game would remain highlighted.

A fix could be if "show unavailable games" was not ticked, then it deselects.

**Comment by Nightfirecat** [comment]
That's true - this is only an issue when using that setting.

**Comment by ZeldaZach** [comment]
Feels very minor and probably not a big issue
