### ISSUE TITLE
Wildcard Matching for Highlight Words

### ISSUE THREAD

**Issue by ZeldaZach** [Cockatrice/Cockatrice#1300]
When you have highlight words, you should have the option to include a wildcard `*` so you're notified when the word is said in a certain way.

Example: If you have the word `judge` in your highlight words, you can have the option to change it to `judg*` and then receive an alert whenever `judge`, `judging` or something that starts with `judg` appears.

**Comment by Daenyth** [comment]
I'm not sure the added complexity is worth the feature. Why not just add each word?

**Comment by ZeldaZach** [comment]
Fair enough, just throwing an idea out there
