### ISSUE TITLE
Cards not loading

### ISSUE THREAD

**Issue by j0wsh** [Cockatrice/Cockatrice#1304]
Hi, I am new to cockatrice and when I tried to work with oracle it didn't work. It loaded some of the cards but it didn't load any of the other cards. I have tried numerous times following the steps you have provided, but I have still not been able to solve the issue. It's probably because I am bad with computers.

**Comment by j0wsh** [comment]
Let me clarify that I have all the cards information but I do not have most of the pictures of the cards in my decks.

**Comment by ZeldaZach** [comment]
Do you have the "Download from a custom URL" checkbox ticked? Also, make sure "Download cards on the fly" is ticked off

**Comment by j0wsh** [comment]
Yeah, I just noticed that! Thanks man, I unclicked it and worked now
