### ISSUE TITLE
Moderators can't modify adminNotes in client

### ISSUE THREAD

**Issue by MassCraziness** [Cockatrice/Cockatrice#1306]
There are currently several things that, if in-client, would make moderation and administrating simpler. Things I'd like to see added:
- [ ] Moderator-only visibile user note system
- [x] Ability to elevate/de-elevate user-levels in-client in real-time (without having to log out and in)
- [x] Ability to view chat logs in-client
- [x] Ability to see game action logs (in cases of cheating or something) (low priority)
- [ ] In-client ban reviews for additional comments/remarks about specific bans that can be made by other moderators

With these tools, moderation will not only be easier, but possibly more effective and more thorough. With the ability to have notes, comments, and reviews of different users/bans, the mod team can be more informed and make better decisions.

**Comment by Daenyth** [comment]
See also https://github.com/Cockatrice/Cockatrice/milestones/Moderation%20Tools

**Comment by MassCraziness** [comment]
Yes, I saw that, but I didn't notice any of these things there, which is why I made this post. I could add them to the checklist, but wouldn't that kind of defeat the point of the milestone?

**Comment by Daenyth** [comment]
just cross referencing

**Comment by ZeldaZach** [comment]
2nd bullet point accomplished by #1391

**Comment by tooomm** [comment]
for reference: 3rd bullet point is filed under #1397 as separate issue

**Comment by tooomm** [comment]
update: #1541 should address 3rd bullet point

**Comment by woogerboy21** [comment]
I know this is slowly coming along but was curious about this one:

> In-client ban reviews for additional comments/remarks about specific bans that can be made by other moderators

Any chance you remember the specifics about this and can describe some scenarios explaining what you had in mind?

**Comment by MassCraziness** [comment]
My initial idea with that was that moderators would be able to add more
stuff to a ban that wouldn't normally be reasonable under the old system.
Mostly, I wanted an in-client ban log, simply making
viewing/editing/removing bans easier. Perhaps notes for screenshots/mod
comments on the situation?

**Comment by ZeldaZach** [comment]
Updated the name of the ticket. Would like mods to be able to have access to adminNotes
