### ISSUE TITLE
Server / Servatrice Performance (Context Switching)

### ISSUE THREAD

**Issue by woogerboy21** [Cockatrice/Cockatrice#1309]
So over the last who knows how long I have been investigating the reason for what appears to be a pretty high load average on a system when you approach the 1000 user mark but the processor's them selves show a fairly low amount of single core utilization.

From some early research what it appears to be is a pretty large amount of context switching that is happening at the higher user counts.  Early theory is that due to the fact that were spinning off a new thread per user log in that as we approach the magic 1000 user mark the amount of resources required for keeping track of simple context switching that has to occur is causing some problems.

Im looking for some one else to validate my theory in the since that I am understanding how the threading is written on the servatrice side and if so , is there any better method that could be used to reduce the amount of context switching that is occurring?

**Comment by woogerboy21** [comment]
To give an example, the current user load on the woogerworks server is ~950 users and I am seeing context switching counts of:
```
voluntary_ctxt_switches:        204959
nonvoluntary_ctxt_switches:     44545
```

```
03:18:08 PM   UID       PID   cswch/s nvcswch/s  Command
03:18:08 PM  1000      3663      8.13      1.77  servatrice.reg
```

**Comment by woogerboy21** [comment]
![htop performance snapshot](https://cloud.githubusercontent.com/assets/1361287/9028791/5a555b64-3952-11e5-9642-5eec634d0d00.png)



Taking another look at performance under ~1000 users today using a newer tool take a look at the color indicators on the bars.  With HTOP you can see that out of the 4 processors, 2 of the processors are functionally doing something and of what they are doing the RED parts of line indicate kernel time that is consuming the majority of the work due to the multitude of context switching that is occurring.  We really need to figure out what is causing this on the server side.  My guess is 2 factors.  1 is the client keep alive that has to be processed every second per client and the other is the server side timer that rolls through and calculates things like client time outs and flood calculations (but its just a guess).

**Comment by Daenyth** [comment]
Tricky.

I'd kind of like to rewrite servatrice using an actor model which should really help this out, I think.

There's this, which I haven't evaluated: http://actor-framework.org/

I'm super familiar with Akka for scala but going there means we have to rewrite all the logic. I think the end app would end up cleaner designed but it's a ton of work that I can't pretend I have time to do, plus I don't want to just throw away every else's knowledge of how the system operates now.

Erlang obviously has the best actors and could trivially handle our scale, but it's also the largest departure - it's not a C style language *at all*. I also don't know it even at a syntax level yet

**Comment by ZeldaZach** [comment]
We don't really hit these user caps anymore, so I'm not sure what more we can do
