### ISSUE TITLE
Export sideboard to .txt differently?

### ISSUE THREAD

**Issue by azas9s4d9** [Cockatrice/Cockatrice#1311]
I don't know any sites or tools that use the "SB: X card, SB: X card" format aside from Cocaktrice. I think you should at least have the option to export it as the more commonly compatible "Sideboard:X card, X card"

**Comment by Nightfirecat** [comment]
http://www.magicworkstation.com/

**Comment by ctrlaltca** [comment]
We should be able to load both formats ("SB: X card, SB: X card" and "Sideboard:X card, X card"), but when exporting a deck we use the SB: format for better compatibility with MWS.
You say that the other format is more commonly compatible, can you give us some example of app/websites that doesn't accept our format, so that we can test and fix it?

**Comment by azas9s4d9** [comment]
Tappedout.net

**Comment by ctrlaltca** [comment]
I tested tappedout and it has two different textboxes to put mainboard and sideboard cards. How do you load deck files anyway?

**Comment by ZeldaZach** [comment]
@ctrlaltca You have to copypasta it in. http://tappedout.net/mtg-decks/paste/

**Comment by Nightfirecat** [comment]
> it has two different textboxes to put mainboard and sideboard cards

Regardless of format, it's not a "Paste everything into this (one) box" thing is what he was saying, if I'm understanding correctly.

**Comment by ZeldaZach** [comment]
They don't have an upload form, so I see no reason why we need to have a way to export the sideboard differently...

**Comment by ctrlaltca** [comment]
> They don't have an upload form, so I see no reason why we need to have a way to export the sideboard differently...

That was my point.

**Comment by ZeldaZach** [comment]
I don't really see any relevance to this feature, but feel free to open if you disagree.

**Comment by ctrlaltca** [comment]
@azas9s4d9 : "analyze on tappedout" feature is currently in the works in #2126
