### ISSUE TITLE
[Recommendation] Admin/Moderator name in private chat deliniation

### ISSUE THREAD

**Issue by woogerboy21** [Cockatrice/Cockatrice#1315]
It has been mentioned to me that it would be nice when a user is private messaged by another user that if the user is of a higher level than registered/unregistered user (moderator or admin as an example) that beside there name there is some type of indicator that they are a mod or admin would come in handy so that when they are contacted by a moderator due to a complaint they are aware immediately that they are talking to some one other than a complete stranger attempting to possibly start some type of harassing message.

My thoughts were maybe a [mod] or [admin] next to there name but I have not dug into the code to see how difficult that would be to add.

**Comment by MassCraziness** [comment]
I like this idea, but only if it's something the moderator/admin can turn on just for that PM/Chat Room message sent, and not permanent. I want it to be, say, "Official Use Only", not something always present.

**Comment by woogerboy21** [comment]
Any particular reason why? (just curious)

**Comment by MassCraziness** [comment]
From your suggestion, it seems like you want it to be "so they know it's a warning". If it's permanent, how will they know?

Also, if we can use it in chat rooms, we can say "[Mod] Stop doing that." So they know it's a real warning.

**Comment by woogerboy21** [comment]
Well the original goal was to make sure the user is aware they are talking to some one of a higher privilege level than a regular user.  Does that equate to "this means business", not necessarily, just so the users are aware when a random PM comes in and doesn't immediately choose to ignore a moderator unknowingly.

The indicator isn't meant to be some type of indicator that the message being sent is of greater importance, just the person stating what ever message it may be is of a higher user privilege level.

**Comment by woogerboy21** [comment]
Not sure I fully think there is a good reason to turn it on and off.

**Comment by MassCraziness** [comment]
I suppose that's also a fine way to think of it, I just feel like I'd rather only have it for "business" messages, not just chatting with my buds.

**Comment by woogerboy21** [comment]
I think what your looking to do is more directed towards one of the PRs (ill have to look it up) were a moderator can send a user a canned warning and that canned warning would PM with special notice of the importance of the message.

**Comment by MassCraziness** [comment]
I suppose I may have misinterpreted the intent of this, then.

**Comment by woogerboy21** [comment]
#175 was the PR btw.

**Comment by MassCraziness** [comment]
Yeah, this felt to me like it was something similar to that, where we could attach our special tag so they know when we say something it's business (which is kind of why I wanted it to be in the main chat). If that wasn't the intent then well, I guess toggling it is kind of pointless.

**Comment by ZeldaZach** [comment]
I'm a fan of having something like this, but have it say "**staff**" (in bold) and not allow it to be disabled.

**Comment by Daenyth** [comment]
How about using the icon?

**Comment by ZeldaZach** [comment]
I like that better @Daenyth
