### ISSUE TITLE
[Suggestion] Additional Higher Level User Ranks + Permissions Granted

### ISSUE THREAD

**Issue by MassCraziness** [Cockatrice/Cockatrice#1316]
Currently, for user ranks, we have Unreg, Reg, Mod, and Admin. With this, I feel servers could create better moderator teams, with different tiers for each moderator, each getting new permissions as you climb the ranks (or different sets of permissions, if the owner set it that way).

Currently, my idea for this is this (and this can be changed, it's not final, and just a suggestion (more stuff could even be added if user-creatable rooms ever get done), the titles are also just fill-in titles):

**New Mod**
- Ability to ban for 24 hours maximum.
- Ability to join any room, but not kick.

**Older Mod**
- Ability to ban for up to a week.
- Ability to kick from any room.
- Ability to review and undo any mod decision made by someone of lower rank.
- Ability to edit ban-lengths to last up to a week (but cannot edit anything higher than a week)

**Old Mod**
- Perma-ban capability
- Ability to edit any ban-length
- Ability to change passwords for other users
- All lower-ranked moderator permissions

**Mod's Mod**
- Ability to elevate/de-elevate user ranks on command, up to Old Mod
- All lower-ranked moderator permissions

**Admin**
- Ability to elevate/de-elevate user ranks on command, up to Mod's Mod
- Ability to change Server Tab
- Ability to send Server Messages
- Ability to restart server
- All lower-ranked permissions

**Owner**
- Can do whatever he wants, he's the owner.

Of course, this is just a suggestion, and the permissions should be able to be swapped around as the owner wishes (as well as the ability to have more/less ranks), as well as any permissions I may have missed. Some of these suggestions will, of course, need other things done first (like the ability to elevate users on command in-client in real-time). This is just a suggestion list, nothing totally final.

EDIT: "Ban length maximum" shoudl also be definable by the server owner. I can't believe I failed to realize that I didn't say that.

EDIT 2: Server owner should be able to define the names of these ranks, as well as assign each rank the permissions they want. I may have stated some of this but I just want to clarify that.

**Comment by skwerlman** [comment]
What if instead of fixed tiers, you had a set of permissions which could be
individually granted to a series of administrator-defined ranks? (I.e. the
way ts3 does it)

**Comment by MassCraziness** [comment]
Well, that was the idea @skwerlman though I'm not sure where I failed to mention that the server owner could define how many ranks to use. Maybe the fact that I missed the "name them" part. I should add that.

**Comment by ZeldaZach** [comment]
Maybe instead of rank names it can be like reddit. You can assign each power on a yes/no basis and leave it like that

**Comment by skwerlman** [comment]
Configuring the permissions per-user sounds like it would get tiring
quickly.

**Comment by ZeldaZach** [comment]
Seems like a simple checkbox list to me, not that bad.

**Comment by MassCraziness** [comment]
I think having a list of permissions to toggle per-user would be fine if there were some sort of way to distinguish between the ranks (instead of just one icon for all of them). That's why I'd much rather have groups (wish an SVG assigned).

That is, of course, my opinion.

**Comment by FrozenSlave** [comment]
well some mods do abuse their powers. also some mods are more likely to ban certain users that they have a history with.

**Comment by Nightfirecat** [comment]
@FrozenSlave Please do not spam unrelated issues with separate concerns. We have already addressed the issue you raised - please follow up with the advice there.

**Comment by Daenyth** [comment]
It sounds like what we really want is dynamic *role-based permissions*

All actions would be tied to permissions.

As a server operator, you could use a preset model (we'd present what we use now), or you could flexibly define your own ranks with the set of permissions you'd like to have the rank use. Then as the admin you'd add users to groups where the group is set to ranks. Inheritance among ranks would be nice. IE, rank unreg = talk, create game; rank user = $unreg + foo.

I can think of some UI workflows that would support this. The database structure wouldn't be terrible. It would require a lot of code changes (basically wherever we check permissions now)

I'd support moving in that direction.

If the rest of the team like the idea I will write an RFC spec for it.

**Comment by MassCraziness** [comment]
@Daenyth My intent was that there would be some additional defaults offered, with the ability to instead create your own ranks with your own permissions assigned to them.

**Comment by Daenyth** [comment]
Yeah, I think we're talking about the same thing. I'll try to get some time to make a concrete spec proposal

**Comment by MassCraziness** [comment]
@Daenyth Would we offer more default ranks than just the 4 (unreg, reg, mod, admin) we have now? Also, if we allow server operators to create more ranks, would we give them the ability to have their own SVGs for those ranks (so we can differentiate between them)?

**Comment by Daenyth** [comment]
By default I don't see a strong reason to support the extra levels - it's
more confusion. We could provide some guides on setting up the model you
mention as an alternative.

**Comment by MassCraziness** [comment]
That sounds reasonable.

**Comment by ZeldaZach** [comment]
Based on how things have evolved over the past 5 years, I don't see a need for such a change
