### ISSUE TITLE
Probleme for connect

### ISSUE THREAD

**Issue by Crovax58** [Cockatrice/Cockatrice#1317]
I would like to connect to play cockatrice but it requires user registration.
What should I do? Thank you.

**Comment by ZeldaZach** [comment]
You register...?

In client you can register now. If you don't see the option then update your client.

**Comment by Nightfirecat** [comment]
You should register an account. [This has been required on Woogerworks since July 23rd.](https://twitter.com/woogerworks/status/624429509765398528)
