### ISSUE TITLE
Disable a user from sending PMs

### ISSUE THREAD

**Issue by poixen** [Cockatrice/Cockatrice#1322]
As an alternative form of punishment, we should be able to ban a user from sending PMs for some time. Similar to how we handle bans.

Thoughts?

**Comment by MassCraziness** [comment]
I dislike this, it just feels like a weak version of a pure mute, which is a weak shadow ban. I don't see why we can't just ban someone if they're spamming/harassing multiple users by PM. If it's just one, then I don't see why we should do anything, the ignore-list is an amazing self-moderation tool.

I'd rather not have this. That's my opinion on the matter.

**Comment by Daenyth** [comment]
I'd rather just ban them from the server completely

**Comment by ZeldaZach** [comment]
I don't see a purpose for this really, but it was a nice idea

**Comment by FrozenSlave** [comment]
no reason to ban a person for 1 on 1 harassing just use the ignore tool.

**Comment by Nightfirecat** [comment]
@FrozenSlave Please do not spam unrelated issues with separate concerns. We have already addressed the issue you raised - please follow up with the advice there.

**Comment by FrozenSlave** [comment]
was nothing related to anyone else.
