### ISSUE TITLE
trolling

### ISSUE THREAD

**Issue by FrozenSlave** [Cockatrice/Cockatrice#1323]
Excuse me but that was a very rude banning as I did not troll i was having a conversation with people. I have never trolled in my life. So now you are saying that we (your users) have no write to freedom of speech. I already know what mod banned me. Thats an abuse of power and should not be allowed.

**Comment by FrozenSlave** [comment]
Further more if a mod is going to ban you for typing anything, they need to issue a warning. to just ban someone for No reason at all, except as a abuse of power is wrong.

**Comment by Nightfirecat** [comment]
This issues bulletin should be used for bugs or features for the software itself. You should take up issues with moderation or bannings with the server owner. (Presumably the mods/admins at Woogerworks)

**Comment by FrozenSlave** [comment]
so basically run around. ok i get it

**Comment by woogerboy21** [comment]
No run around.  Its a pretty simple concept.  The development group doesnt host servers.  If you have a complaint about a specific server take it up with the server owner / operators.  Woogerworks is one of a few servers out there.

**Comment by FrozenSlave** [comment]
a link to this place would be helpful instead of telling me where to
go....but not giving me any way to get there.

**Comment by woogerboy21** [comment]
http://www.woogerworks.com

**Comment by Daenyth** [comment]
This isn't the place for any one server-specific issues. Most of the team here is not involved in running servers. This is the place you go if the software is crashing or if you have an idea that can make it better.
