### ISSUE TITLE
"Both" deck editor display mode has a very small image

### ISSUE THREAD

**Issue by doombringer777** [Cockatrice/Cockatrice#1329]
Card images when using the "Both" display mode on the deck editor are far too small and are wasting lots of space. I want to have both the card text and the image visible if possible.
![screenshot 2015-08-04 12 29 00](https://cloud.githubusercontent.com/assets/1956705/9053473/ca208fd8-3ab8-11e5-894e-9325947639fd.png)

I can understand that if the window is reduced in size then having the small image makes sense but when the program is full screened it seems very un-intuitive.

**Comment by tooomm** [comment]
For me it looks like this on small laptop resolution:
![untitled](https://cloud.githubusercontent.com/assets/9874850/9056837/0d6dfcda-3a96-11e5-8807-99ff5906df50.png)
Even cards with much text don't eat up all the space.

But image and **especially the filter area** is very very small!

Maybe use a movable separator between card info/picture box and the filter box to adjust the space as needed to get rid of the "wasted space" and make the filter area usable even for smaller resolutions (like between Chat and Games lists when connected in the "Main" tab).
Plus make the image in "Both" view somehow scalable or 3 adjustable size options if you right click?

**Comment by poixen** [comment]
We should add logic to not add employ labels. In the above image, pt and mana cost. That would add some more vertical space.

**Comment by marcofernandezheras** [comment]
What about moving the filters panel to a tab, letting the tabs fill all the vertical space?

**Comment by Daenyth** [comment]
@poixen I tried that a while ago, iirc it's complicated because the same widget is reused for different cards which may or may not have fields as it's changed between them, so I don't think it's as straightforward as one would hope. Still doable, just might take some more works.

@marcofernandezheras personally I wouldn't like that, I tend to use the filters a lot for exploratory deck building and I need to examine the card details. Tabbing back and forth would really hinder that workflow.

**Comment by doombringer777** [comment]
@Daenyth yeh I think changing the filters would do more harm than good.

I'm more wondering if on larger resolutions like my screenshot the text and details can be moved further down to allow for a larger picture. Note how the area in red is wasted currently.
![screenshot 2015-08-04 12 29 00](https://cloud.githubusercontent.com/assets/1956705/9062528/532b45dc-3b06-11e5-8ec3-2e0dc226704b.png)

**Comment by tooomm** [comment]
@Daenyth That's true. if you use the filter you are working with a decklist... and in that case you want to see what you are working with and check rulings/wordings.

In general I liked the idea. Maybe just not practical in use.

**Comment by marcofernandezheras** [comment]
What about moving the filter to the left column? Maybe adding them on a split layout so it can be hidden?
![Layout](https://hostr.co/file/970/EF6Mw0xd9g6O/layout.png)

**Comment by Daenyth** [comment]
That's not a bad idea. We could lay it out a little differently.

Ideally the whole thing would have ecah component be draggable and
resizeable but that's a bit far off.
