### ISSUE TITLE
sets selection: group sets by type

### ISSUE THREAD

**Issue by aeosynth** [Cockatrice/Cockatrice#133]
http://mtgjson.com/#sets

> Each individual set is a JSON object like this:

```
// Type of set. One of: "core", "expansion", "reprint", "box", "un",
//                      "from the vault", "premium deck", "duel deck",
//                      "starter", "commander", "planechase", "archenemy",
//                      "promo", "vanguard", "masters"
```

this could be reduced to core, expansion, other

**Comment by tooomm** [comment]
@Cerxi are you requesting to have a separate column for info like `Game` that one could sort for?

**Comment by Cerxi** [comment]
No, when I posted this you couldn't just click "Set type" or "Release date" or whatever to sort ascending/descending, you had to drag sets into order one by one. The "Edit sets" dialogue has improved drastically in the intervening _four years_.

**Comment by Daenyth** [comment]
>  four years.

Thanks for sticking with us! :p

**Comment by tooomm** [comment]
What's this issue about then actually? 😄 
I'm not sure if it's still relevant? It's also just referencing mtgjson...

Does anybody recall?

**Comment by Cerxi** [comment]
>Thanks
Well, it's a good program!

>What's this issue about
It was about adding properties beyond just names to Edit Sets, and automating sorting, both of which happened, so no, it's not really relevant anymore

**Comment by tooomm** [comment]
Thanks @Cerxi 
Feel free to let us know about any other issues or improvements.

For more years to come, hehe.
