### ISSUE TITLE
No shortcut for copying card text

### ISSUE THREAD

**Issue by doombringer777** [Cockatrice/Cockatrice#1330]
I often use Cockatrice on Windows when offline as a type of Gatherer to find exact rules text. However something that constantly annoys me is the inability to use Ctrl + C or some other shortcut to copy rules text to the clipboard that I have selected in the deck editor.

![screenshot 2015-08-04 15 02 17](https://cloud.githubusercontent.com/assets/1956705/9053588/3a4b5c60-3aba-11e5-970c-56d17aaa212b.png)

Instead as shown in the screenshot I have to right click on the text then select Copy.

Is it possible to have the program detect if you are highlighting text and allow you t then use Ctrl + C to copy the highlighted text.

**Comment by marcofernandezheras** [comment]
The problem is that ctrl+c is bound to "Save deck to clipboard"...

**Comment by Daenyth** [comment]
@poixen do you think it would be hard to modify the ctrl+c handler so that it checks for highlighted text before doing deck copy?

**Comment by ZeldaZach** [comment]
@Daenyth You can use `qtextcursor` potentially (See: [qt forum](https://forum.qt.io/topic/24525/how-to-check-if-the-selected-word-is-bold-or-not))

**Comment by doombringer777** [comment]
Any progress on this?

**Comment by Daenyth** [comment]
No.

**Comment by ctrlaltca** [comment]
With the new configurable shortcuts, you can just remove the ctrl+c shortcut from "copy deck to clipboard" and it will start working.
