### ISSUE TITLE
missing flag in "edit account" dialog

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#1331]
If you want to adjust your account settings out of the client and you look into the country flags,
there is no flag shown for AM (should be Armenia).

edit account dialog:
![am flag missing](https://cloud.githubusercontent.com/assets/9874850/9057109/dea628a8-3a97-11e5-94f8-93d6817c058c.png)

user information in account tab:
![am flag](https://cloud.githubusercontent.com/assets/9874850/11762702/de0131ea-a0ef-11e5-92fe-b061ab498705.png)

---

btw... why are the letters small? Looks weird, and if you look at someones account details they are displayed big.

**Comment by Nightfirecat** [comment]
I imagine because the image is incorrect (that small sliver of red), meaning that the text doesn't get pushed as far to the right as it would if the image were full-sized.

Certainly not a definitive conclusion, but just theorizing.

**Comment by tooomm** [comment]
The flag itself seems to be ok:
https://github.com/Cockatrice/Cockatrice/blob/master/cockatrice/resources/countries/am.svg

**Comment by Daenyth** [comment]
The letters are lowercased because that's how they're transmitted; the uppercasing happens in the account display panel just to look nicer. #623

**Comment by tooomm** [comment]
Maybe they should look nice in the selection drop-down menu as well? ;)

**Comment by ZeldaZach** [comment]
This flag seems to be a vertical rectangle instead of horizontal one, like the others... hmm

**Comment by tooomm** [comment]
![am flag](https://user-images.githubusercontent.com/9874850/33081698-3676362a-cedb-11e7-975d-c4b8ade7a07e.png)

This is no issue anymore. Realized in 2.4.0 release.
Maybe my flag update or newer qt version fixed things!?

**Comment by Nightfirecat** [comment]
🤔

**Comment by tooomm** [comment]
Do you still see issues @Nightfirecat?

**Comment by Nightfirecat** [comment]
No, I was just commenting on how odd it is that this issue just went away on its own.

**Comment by tooomm** [comment]
Haha, ok :)

I didn't keep track of it all the time, just randomly realized it today. But I guess it's about Qt.
Same for this one: https://github.com/Cockatrice/Cockatrice/issues/1673
