### ISSUE TITLE
Banned?

### ISSUE THREAD

**Issue by Frodo12** [Cockatrice/Cockatrice#1333]
I kicked a player for simply not following the rules of the game. NO MLD or INF and he went inf t4 during a commander game. He reports me and I get banned? I am not allowed to kick a player to keep them from enjoying their game? He did not follow the preset rules!

**Comment by Daenyth** [comment]
This isn't the place to go. Go to the people who run the server you were on when this happened. This is the place you should go if the software is crashing or if you have an idea for a feature that would make it better.

**Comment by Toddy111** [comment]
hi

i was banned on cockatrice duing some time . i made some mistake in the past and i would change it and other time enjoying on cockatrice.

thanks very much
