### ISSUE TITLE
Banning Hierarchy

### ISSUE THREAD

**Issue by poixen** [Cockatrice/Cockatrice#1335]
We should add a server side check to see what the userlevel is of the user a ban is being applied to.

Mods should only be able to ban reg/unreg users.
Admins should be able to ban mods.

This will help if a mod goes postal. 

This needs to be done in the server code, and also in @woogerboy21 php banning mgmt.

**Comment by Daenyth** [comment]
This is reasonable.

**Comment by MassCraziness** [comment]
@poixen How does this help? Currently there is only one level of power. This means if a mod goes postal there is nothing to stop them at all until an admin shows up. I'm all for restricting who can ban who, but only if there are more user levels to stop the issue if need be.

**Comment by poixen** [comment]
I wouldn't have noticed unless I hadn't been checking the logs. Seems some mods ban one another for "fun". This is confusing to read. 

Think of it this way. Currently postal mod can ban all staff. Meaning only woog can solve it. With the checks in place any admin can intervene, currently woog, dae and myself.

**Comment by MassCraziness** [comment]
I understand the concern, and I agree that having some check in place is good, but not with the current system. It just allows room for a mod to abuse while we sit on our hands and wait for an admin to show up. If we can ban them we can temporarily stop them.

"Fun" bans are just us messing with friends, enjoying ourselves. They're not harmful, they're a separate issue from this entirely.

**Comment by poixen** [comment]
It's actually the reason I created this ticket. Had I not seen it, I wouldn't have made it. this fun clutters the data base, makes more work for someone interpreting the data, slows the loading of the already clogged ban page and is unprofessional.

**Comment by ZeldaZach** [comment]
I don't find this too relevant based on how the client has evolved over the past 5 years.
