### ISSUE TITLE
origins cards not appearing in the deckbuilder

### ISSUE THREAD

**Issue by potatoZMaster** [Cockatrice/Cockatrice#1337]
i don't know if this is happening to other people but i am on a mac, i have redownloaded the latest client of cockatrice, have fully updated everything, and yet magic origins card (that i have found in the cards.xml file) don't appear in the deck builder. they DO APPEAR in the xml file. if i save the deck to clipboard and edit it i can type in exact names and still get card art and text but ONLY ON CARDS THAT HAVE NO PUNCTUATION. for example, i can get "Fiery Impulse" but i can't get "Day's Undoing" because day's undoing has an apostrophe. help?

**Comment by woogerboy21** [comment]
Hmm.. thats odd.  I see the data in a linux client. @ZeldaZach , do you have issues with your mac client?

**Comment by Daenyth** [comment]
Is the set enabled?

**Comment by potatoZMaster** [comment]
the set is enabled but on that enable set screen "ORI" and "MM2" have no long name (there is one in the xml however, it just doesn't appear.)

**Comment by ZeldaZach** [comment]
I have no issues @woogerboy21. The issue sounds like @potatoZMaster is using a downloaded XML and not one generated by the Oracle tool

**Comment by Daenyth** [comment]
Can you run oracle again; it will tell you the file path where it saved the
file -- please upload that file to gist.github.com and link it here.

**Comment by Daenyth** [comment]
And make sure your card db settings point to the location used by oracle

**Comment by potatoZMaster** [comment]
/Users/student/Library/Application Support/Cockatrice/Cockatrice/cards.xml is the path it was saved to. what are card db settings?

**Comment by potatoZMaster** [comment]
i am pretty sure it is an oracle xml file. if it isn't (i wouldn't be able to tell) how would i get the oracle one? just run oracle i assume? (which i did just now and still have the problem)

**Comment by Daenyth** [comment]
It could have been a hand made one that someone gave you which was made
incorrectly.

Can you upload screenshots of your settings page and the editor?

**Comment by potatoZMaster** [comment]
sure. these are pictures of cards with apostrophes, cards without apostrophes, and general settings along with a generic view of the deck builder.
![screen shot 2015-08-05 at 9 15 32 pm](https://cloud.githubusercontent.com/assets/13654079/9101651/869e0b1e-3bb7-11e5-8e6e-411a2ae0b9f0.png)
![screen shot 2015-08-05 at 9 16 41 pm](https://cloud.githubusercontent.com/assets/13654079/9101649/8698983c-3bb7-11e5-8671-a6de9279f725.png)
![screen shot 2015-08-05 at 9 17 08 pm](https://cloud.githubusercontent.com/assets/13654079/9101652/86a5688c-3bb7-11e5-9a21-9a16415e9836.png)
![screen shot 2015-08-05 at 9 16 50 pm](https://cloud.githubusercontent.com/assets/13654079/9101650/869d6bd2-3bb7-11e5-9a2d-aab3ff3adbaf.png)

**Comment by ZeldaZach** [comment]
@potatoZMaster Your `Card database:` link is wrong. It's linked to a downloaded XML file. Change it to `/Users/student/Library/Application Support/Cockatrice/Cockatrice/cards.xml`

That should solve your issues.

**Comment by potatoZMaster** [comment]
YES
thank you thank you thank you! this worked like a charm. i vaguely remember now changing that for some reason and changing it back worked immediately. thank you all so much!
