### ISSUE TITLE
Improvements to "Register to server" dialog

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#1339]
- [ ] Use `*` (Asterix) next to the required fields and add a bottom note explaining the `*`
- [ ] I like @ZeldaZach `s suggestion [here](https://github.com/Cockatrice/Cockatrice/issues/1248#issuecomment-120769814): <br>
"Password and eMail fields should have a copy/paste protection to narrow down incorrect registrations due to human fault because people copy their slightly wrong pw/mail without noticing the typo"

**Comment by ZeldaZach** [comment]
It's not possible to easily get them copypasta protection as if you make one field gluten free, the rest follow the same path.

**Comment by tooomm** [comment]
Well, if there is just no copy/paste functionality for this complete single dialog that's perfectly fine... broken copy/paste in all client is no option for sure!

The only problematic thing would be the server adress.
But when the history/profiles (#1307) gets introduced, there should be the same drop down with some *correctly* preconfigured servers in the "Register to server" dialog as in the "Connect" dialog.

**Comment by Daenyth** [comment]
The required fields thing is a little tricky - some are required at the server's discretion - like email. It's not always required and not always optional. The client doesn't have a way to tell right now without asking the server.

**Comment by Nightfirecat** [comment]
I'm heavily against the second point, particularly because I make use of a password manager, which all but requires me to copy+paste to work at peak efficiency.

**Comment by ZeldaZach** [comment]
Personally, I don't see the use for either bullet point on this ticket due to both @Daenyth  and @Nightfirecat's comments... It was a good idea, but the benefits don't out way the losses

**Comment by MassCraziness** [comment]
@Daenyth Perhaps have registration be in two parts, then? First you input the server you wish to register to, where it asks what things are required, then it pops up a second dialog box where things are marked as required or not for when you register. That would solve the "needing to ask the server" part,

**Comment by Daenyth** [comment]
I wouldn't like it in two parts, it increases friction.

I also really dislike the copy/paste thing - I use a password manager and forbidding me from pasting makes me *more* likely to make a mistake entering the password

**Comment by ZeldaZach** [comment]
Sounds like we're all in agreement here about not going forward with either option
