### ISSUE TITLE
launch oracle from cockatrice

### ISSUE THREAD

**Issue by aeosynth** [Cockatrice/Cockatrice#135]
instead of telling a user to launch oracle, launch it for them

**Comment by ZeldaZach** [comment]
With the recent update, cockatrice now tells you when you need to run oracle. I consider this good enough

**Comment by ctrlaltca** [comment]
With the recent update, cockatrice now tells you when you need to run oracle <= not really; it will only tell you if oracle added new sets to your cards.xml, but you still have to run it manually

**Comment by tooomm** [comment]
@poixen is it possible to start Oracle out of the `Card Database` menu the same way we open the custom card folder?

**Comment by Daenyth** [comment]
There's a way to launch apps with qt
