### ISSUE TITLE
Due to user registration, it isn't possible to set up a server without a database

### ISSUE THREAD

**Issue by shblythe** [Cockatrice/Cockatrice#1351]
If a server is set up without a database, there is not such thing as a registered user.
The client only allows registered users to set up games which can be joined by non-registered users, therefore it's impossible to ever set up a game which another user can join.
Setting up a server without a database is useful for a quick home server which won't be exposed to the outside world.

**Comment by woogerboy21** [comment]
So your saying that a server with out a database will not allow a non-registered user to create a game?

**Comment by shblythe** [comment]
No, user can create a game, but the "onlyRegisteredCheckBox" is ticked and greyed out, which means only registered users can join the created game, but there are no registered users.

**Comment by woogerboy21** [comment]
Let me fire up a test server.  If this is the case its a whoops on a default UI setting.

**Comment by shblythe** [comment]
Looking at the source myself, but haven't found the culprit yet.

**Comment by woogerboy21** [comment]
Just curious, are you compiling with Qt4 or 5 ?  It shouldnt matter but just want to make sure im replicating the environment properly.

**Comment by shblythe** [comment]
Actually, maybe I have:
    onlyRegisteredCheckBox->setChecked(true);

in DlgCreateGame::actReset()

**Comment by shblythe** [comment]
Qt4

**Comment by Daenyth** [comment]
The server should ignore the game setting if it's in unreg mode.

The client won't necessarily know what the server setting is

**Comment by shblythe** [comment]
Looking at the code, I suspect it's a client issue now, rather than a server issue.

**Comment by woogerboy21** [comment]
LoL.  Yeah its a client side setting.

**Comment by shblythe** [comment]
DlgCreateGame::sharedCtor disables the control if the user isn't registered, but DlgCreateGame::actReset() defaults the control to enabled.

**Comment by shblythe** [comment]
Sorry, I mean "ticked" rather than enabled.

**Comment by woogerboy21** [comment]
@shblythe Would you like to make a PR for it or would you like some one else to?

**Comment by shblythe** [comment]
I can do it if you like, is the correct fix to change actReset to default it to false?

**Comment by shblythe** [comment]
If so, I'll do that and test it here.

**Comment by woogerboy21** [comment]
Thats all I would do assuming that it tests out ok

**Comment by shblythe** [comment]
OK, I'll give it a go.

**Comment by woogerboy21** [comment]
I found the issue , its the settingscache value defaulting to true for the checkbox.

**Comment by shblythe** [comment]
Ah, OK, thanks.  I've been away from my computer for a bit.  Are you planning to PR it then?

**Comment by woogerboy21** [comment]
Yup :)

**Comment by shblythe** [comment]
Great - thanks for that!

**Comment by woogerboy21** [comment]
Fixed with #1352

**Comment by Daenyth** [comment]
This isn't about the client side setting, this should be fixed on the server - the setting is nonsensical and your approach doesn't actually fix it, it just changes the default - if the user checks the setting, then the problem still happens
