### ISSUE TITLE
Large spike in CPU usage when saving set order

### ISSUE THREAD

**Issue by A4G** [Cockatrice/Cockatrice#1355]
Cockatrice's CPU usage goes up by 20% on my mid-range laptop when saving any changes to the set order. I'd imagine the lag is a lot worse on lower end systems, which a lot of people have.
It shouldn't take as much processing as it's doing to just rewrite the config file, so something else is probably going on.
![247b1d9e8d90d25eb0ff7c7a053c76ae](https://cloud.githubusercontent.com/assets/6441353/9159269/48f59324-3ef3-11e5-9cc5-e820accb30b1.png)

**Comment by ZeldaZach** [comment]
I notice this issue on OS X as well, but it's not as severe. Still, it's a problem that should be looked into.

**Comment by ZeldaZach** [comment]
A quick look reveals two things happen:
```
model->save(db); // Rewrite config with new info
db->clearPixmapCache(); // Clear image cache
```

The clearing of the image cache is what's probably doing it, as that can be up to 2GB of information that has to be dumped quickly.

**Comment by A4G** [comment]
After minor testing, reducing the default image cache size to 500 and then 64 mb showed no change. 
Could be an isolated incident, hopefully someone can reproduce it.

**Comment by ctrlaltca** [comment]
When the sets windows gets closed confirming changes, the card database gets reloaded. That causes the CPU spike.

**Comment by Daenyth** [comment]
We probably don't need to do that

**Comment by ctrlaltca** [comment]
> We probably don't need to do that

If the user just enabled a previously disabled set, we want to do that.

**Comment by Daenyth** [comment]
Why do we need to rescan the database? We could just keep the db in memory and filter as-needed. I really dislike the db loading code structure in general.

Obviously under the current model we need to do this but there's no reason we have to always

**Comment by ZeldaZach** [comment]
Im a fan of maybe using a smarter technology and only reloading/dropping the sets that were modified from memory instead of everything

**Comment by marcofernandezheras** [comment]
If we dig on SetsModel::save, we can see multiples calls to CardSet::setSortKey & CardSet::setEnabled, those both metods make a QSettings stack instance what means that each invocation of each open & close a hdd file... maybe that the lag spike.
We can try to pass the QSettings object by reference or (better) move that setting to settings cache (or even better) move that set enable/disable logic to a new class.

**Comment by Daenyth** [comment]
I like the latter option

**Comment by ZeldaZach** [comment]
We can't do much about the reload process and it's a quick spike to load up so I'm not too concerned
