### ISSUE TITLE
Migrate Travis from Legacy

### ISSUE THREAD

**Issue by ZeldaZach** [Cockatrice/Cockatrice#1357]
http://docs.travis-ci.com/user/migrating-from-legacy/

**Comment by Daenyth** [comment]
Thanks for the heads up

**Comment by Daenyth** [comment]
> If you require sudo, for instance to install Ubuntu packages, a workaround is to use precompiled binaries, uploading them to S3 and downloading them as part of your build,then installing them into a non-root directory.

So, that's fucking obnoxious. I don't think we should do that. Let's revisit this when they have a better story about dependency management.

**Comment by ctrlaltca** [comment]
@Daenyth http://docs.travis-ci.com/user/migrating-from-legacy/#How-do-I-install-APT-sources-and-packages%3F i think we could be fine using this

**Comment by Daenyth** [comment]
There's no mention if it works for homebrew; I can ask their support

**Comment by Daenyth** [comment]
See also: 

https://github.com/travis-ci/apt-package-whitelist/pull/881
https://github.com/travis-ci/apt-package-whitelist/issues/857

https://github.com/travis-ci/apt-source-whitelist/issues/110

**Comment by ctrlaltca** [comment]
Fixed in #3037
