### ISSUE TITLE
bugs with #1342 (dockable elements)

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#1359]
@marcofernandezheras related PR #1342

**Bugs:**

- [x] Filters "dock"
  Buttons for `delete selected filter` & `delete all filters` are gone (introduced in https://github.com/Cockatrice/Cockatrice/pull/1137)
  fixed in  #1483
- [ ] Card Info "dock"
  - swapping several times between `description` and `both` tab will make the picture shrink more and more in the `both` tab<br>going to `image` and back to `both` will reset the size
  - going from `both` to `image` and back will make the description part in `both` be displayed way more down than initially set<br>won't change until you hit the `description` tab and go back to `both`<br>interestingly if you hit `description` and then `image` before going back to `both` the separator won't be that close at the bottom anymore, but still not at his initial position.
- [ ] wideness of "docks"
  If you play around with enabling/disabling different "docks" with custom wideness settings they won't remember correctly and get displayed with different wideness, one "dock" eats up the wideness of former 2 "docks" or they split-share it evenly (even when set to 1/3 and 2/3 before for example)

**Improvements:**

- [ ] Buttons to show/hide elements next to the search field... it's very difficult to distinguish between both states of the button. It's ok on my very old monitor, but on the laptop it's really difficult!
- [ ] If you add a card to the decklist or sideboard (when deck "dock" is hidden), it should automatically show the deck "dock" again to visualize that you are doing something.
  - You added a card by mistake, so you will get informed about your mistake (double clicking in the list for example) and don't need to wonder about "do you want to save deck changes?" confirmation when you quit cockatrice for example
  - You added a card intentionally, so you see what you are doing, can interact with it and it's actually what you expect to happen I guess.

<br>
Tried to attach a video... but screen-o-matic is not working for me right now.
I hope you can follow my description and reproduce for your own!

---

**Maybe there should be more than one person doing _serious testing_ (plus commenting on the pr that they did) before merging...!?**

**Comment by ZeldaZach** [comment]
Thanks for the list of points. Let me try to address some of them quickly.

____

> Buttons for `delete selected filter` & `delete all filters` are gone

Those are still found in the menu options.
<img width="253" alt="screenshot 2015-08-10 20 18 29" src="https://cloud.githubusercontent.com/assets/7460172/9187308/ff8d051e-3f9c-11e5-88b4-c4eee16b5a7f.png">

______

> Should ask for confirmation after applying/changing. In case someone plays around or tries this option or hit it by mistake all of his customization and adjustment are gone...
What I like to happen here:

I'm a fan of how it currently works. Having a popup would be a nuance, as we've experimented with in the past, and resetting the layout isn't the end of the world. The advantage of the popup I don't find worth it.

____

Your bug reports are valuable and we were really excited to get the initial feature in. Since we're an open source project, it's hard to find people to stick around and join proper roles. I'm the only one who does the serious testing at this point, but I'm open to others joining in if they'd like.

**Comment by Daenyth** [comment]
We shouldn't rely on menus and remove the buttons. People don't read the
menus. We added the buttons in the first place because the menu was
insufficient

**Comment by marcofernandezheras** [comment]
I've missed to add `filterDelOne` `filterDelAll` QToolButtons back to the UI again on the dockify process...
I'll add them back & i'll made a PR later, or, What about adding contextual menus there instead buttons to some space saving?

**Comment by tooomm** [comment]
I liked your picture [here](https://github.com/Cockatrice/Cockatrice/issues/1329#issuecomment-127627007)... the layout with the filters placed beneath the card list looks very nice, clean and useful - just well placed. (same width for sure)

Couldn't reproduce it with your recent PR.
It's not possible to interact with the card list. You can't group elements with it to get a tab below or place things (relatively to the width of the card list) above or below it.
You can just place things at the very top or bottom of the layout (over the width of all client).
The thing is that the card list is not a dockable element at all and you can just place other things around it. I kinda like that because it's the core of the deck list and other things just relate to it...
Still it would be nice to interact a bite more flexible with the card list.
Possible at all or some workaround you can think of?

**Comment by Daenyth** [comment]
bump

**Comment by Daenyth** [comment]
We need to re-triage this:
- Any remaining issues from this should get new tickets (one per issue)

And then close this
