### ISSUE TITLE
[Regression] Cockatrice now opens in a maximized window at all times, even when the last-closed instance was not a maximized window.

### ISSUE THREAD

**Issue by MassCraziness** [Cockatrice/Cockatrice#1360]
Before, Cockatrice would start with the exact window size I had it last when I closed it. As of the August 9, 2015 update, Cockatrice now starts maximized no matter what. I am unsure of whether or not this is simply an issue for me, however all I did was update the program, so that shouldn't be the case.

**Comment by tooomm** [comment]
same behavior here with build from 9th august

**Comment by ZeldaZach** [comment]
I believe it has something to do with the updated deck editor as I believe it sets the screen to full size when its first initiated.

**Comment by Daenyth** [comment]
That's probably not ideal

**Comment by ZeldaZach** [comment]
**./cockatrice/src/main.cpp:225:10**
`ui.showMaximized();`

Should be changed back to
`ui.show();`
