### ISSUE TITLE
Oracle - skip card downloading

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#1364]
Add a `Skip` button
Next / Skip / Cancel

Ability to skip the card data downloading if you just want to refresh the token file for example.
It takes quite some time on low speed internet to download the 3mb or you just don't want to overwrite it because you use a custom file etc...

( @ctrlaltca )

**Comment by Daenyth** [comment]
We could have checkbooks for both portions

**Comment by ZeldaZach** [comment]
I have a feeling people will be complaining now that "I ran Oracle and my files are still broken!" if this is done... Maybe another way instead of a Skip button?

**Comment by Daenyth** [comment]
I'm imagining an option on the first screen that looks like:

- [X] Download card data
- [X] Download token data

And then they can uncheck options.

**Comment by tooomm** [comment]
@ZeldaZach we can't fix stupid. If people hit a <kbd>Skip</kbd> button and expect the program to do anything except skipping something (=doing nothing), well...
The button shouldn't have the activate-this-button-if-you-hit-enter focus for sure!

But I like Dae's suggestion, too!
@Daenyth do you think your suggestion will interfere with future multi game support when there might be a dropdown list or something to select the card data for your game?
People might even don't know what tokens are because you don't need them for their game etc. (Hearthstone for example? just assuming, don't know this game)
Maybe there should be a token checkbox on the mtg related sup part. And if you select `Heartstone` there is no checkbox for tokens because you don't need them or there are none yet.
For now it works for sure and is easy to understand!

@ctrlaltca Oracle guru... what do you think?

**Comment by Daenyth** [comment]
I'm not sure if multi game support will happen in oracle out another app

**Comment by tooomm** [comment]
This is closely related to #2571

<br>

>I'm not sure if multi game support will happen in oracle out another app

@Daenyth Do you think Oracle is something like a mtg-importer?
And there should be other importer for different games?

The multi-game support idea seems to be very vague in general and needs to be thought trough well,  there is this ticket for example: https://github.com/Cockatrice/Cockatrice/issues/1740

**Comment by Daenyth** [comment]
> @Daenyth Do you think Oracle is something like a mtg-importer?
> And there should be other importer for different games?

Yes, that's how I feel.

> multi-game support idea seems to be very vague

I agree. I had a pretty detailed write up in the past but it was on the old cockatrice.de github repo and was lost after the Hasbrocalypse

**Comment by tooomm** [comment]
>I had a pretty detailed write up in the past but it was on the old cockatrice.de github repo and was lost after the Hasbrocalypse

And @mbruker has no copy left I assume...

**Comment by Daenyth** [comment]
Long long gone. He sent me all his notes he had but the issue tracker
wasn't among them

**Comment by mbruker** [comment]
I'm not sure what you're talking about exactly, but it's safe to assume that I don't have any files or notes left that I haven't shared already. I might remember some scattered thoughts on a couple of subjects, but presumably (hopefully!) the code has changed so much since the event Daenyth is referring to (thanks for the brillant neologism there) that my ideas from the past won't be of much use...

**Comment by ZeldaZach** [comment]
I'm still not sold on this ticket
