### ISSUE TITLE
Misconfiguration Causes Unnecessary Crash

### ISSUE THREAD

**Issue by Lachee** [Cockatrice/Cockatrice#1370]
Well, hey all

I just discovered my server hasn't been working for a while, which would explain why everyone was asking questions about chickatrice.net.

What caused the error was a crash that occurred at every runtime (I have it set to a cron). 

It crashed because I had authentication=none and registered=1, meaning that it wanted only registered users, but no authentication is necessary.

Yes, this seems like a legitimate reason to error, but to crash all together? Maybe you could make it just display the error, and assume registered=0 when authentication is none.

Cheers

**Comment by Daenyth** [comment]
I think the right behavior here is to show an informative error message and ignore it as you said.

**Comment by woogerboy21** [comment]
@Daenyth 
The server states this on startup when the configuration described is in place:
```
Servatrice 8bf58af (2015-08-12) starting.
-------------------------
Registration only server enabled but no authentication method defined: Error.
```

**Comment by ZeldaZach** [comment]
Was this solved? i can't remember

**Comment by Daenyth** [comment]
I agree. We should not transparently degrade configured security settings when ambiguous. Testing the server configuration would have caught this.
