### ISSUE TITLE
Add an admin-level command to change user level.

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#1377]
Admins should be able to +mod registered users and -mod moderators.

**Comment by woogerboy21** [comment]
As in right click menu options on the user from the user list?

**Comment by ZeldaZach** [comment]
@woogerboy21 Sounds fine to me

**Comment by Daenyth** [comment]
For right now we can set it to admin level. Later it can be an action tied to a role.

**Comment by woogerboy21** [comment]
@Daenyth 
I've been working on this (https://github.com/woogerboy21/Cockatrice/tree/admin_adjustmods)  but just curious on your $0.02.  What would you expect (if any) response notifications?  Right now it just doesnt do anything but show the response code in the debug data.

**Comment by Daenyth** [comment]
I'll look at that when I can. In general the server should just send the
user their own userinfo rather than disconnecting or pm
