### ISSUE TITLE
Power/Toughness when tagging a creature name?

### ISSUE THREAD

**Issue by isleep2late** [Cockatrice/Cockatrice#1383]
I noticed that we don't have yet the viewing of a creature's Power/Toughness when someone tags a creature name. For example, if I type in the chat [[Dark Confidant]], besides the image itself you can't really tell what the power/toughness is on the creature (2/1). This would be useful because if gatherer or whatever database we use goes down, we won't see the card image but we will at least see all the characteristics of the card.

**Comment by Fizztastic** [comment]
The P/T of cards is displayed when you tag cards in chat. 
![untitled-1](https://cloud.githubusercontent.com/assets/11285250/9294740/51326432-4424-11e5-85ea-a82351f29d41.jpg)

**Comment by poixen** [comment]
Awesome alt.

**Comment by isleep2late** [comment]
That's odd... it doesn't do that for me when I tag a card in chat, and I just updated to the latest cockatrice build (though I'm pretty sure I was on it before I reinstalled). I am noticing that the P/T section is displayed under Card Info for everything else though, just not when a creature card is tagged in the chatroom. Could you be on the Mac version of Cockatrice? And yes, awesome alt

**Comment by isleep2late** [comment]
Can anyone else confirm whether they are seeing the Power / Toughness under creature card descriptions for when they get tagged in the chat? I just asked the main chat and nobody else seems to have the power/toughness displayed either.

**Comment by Fizztastic** [comment]
@isleep2late I'm on Windows.

**Comment by isleep2late** [comment]
@Fizztastic Are you on the latest build? Older ones might not have had this issue.

**Comment by Fizztastic** [comment]
@isleep2late I'm on a custom build but I just downloaded the latest woogerworks build and it displays the same thing as the screenshot i posted earlier.

**Comment by isleep2late** [comment]
Okay because it seems everyone else I've talked to is having the same issue I'm having...

**Comment by isleep2late** [comment]
I'm on the latest build, and this is currently what I'm seeing, and also since the card image isn't loading I'll never know the Power/Toughness on Kor Firewalker lol.
![11911891_1153474801334939_1841156643_n](https://cloud.githubusercontent.com/assets/7435598/9295026/bf915150-442d-11e5-9699-d008b2e7b5cb.jpg)

**Comment by Fizztastic** [comment]
@isleep2late Looking at the code, there's definitely something fishy going on here. I'll delve into this issue tonight.
