### ISSUE TITLE
Have a way to add a comment to a player in the buddy list

### ISSUE THREAD

**Issue by dlight** [Cockatrice/Cockatrice#1384]
I'm not sure if this was suggested already, but it would make the buddy list much more useful. I can add which kinds of decks or formats they play, or whether they are receptive to give feedback to new decks, whether they enjoy long games with well-thought moves (a rare quality it seems) or prefer quick games, etc.

Another way to approach this problem is arranging the buddy list in groups, but it's less flexible and don't allow writing specific information about a buddy (it would also require changing the buddy list to a treeview or something like it)

**Comment by Daenyth** [comment]
I like tags or notes. This might be a duplicate ticket

**Comment by tooomm** [comment]
It's in this one issue with the very long list/many things.
I really like to see this and would keep it as separate issue therefore!

Notes or tags. :+1:

**Comment by Daenyth** [comment]
See also #1957 about user list tags.

**Comment by tooomm** [comment]
See https://github.com/Cockatrice/Cockatrice/issues/1957
