### ISSUE TITLE
Can't 'make'  fix-1351

### ISSUE THREAD

**Issue by HearMeWhisper** [Cockatrice/Cockatrice#1390]
[ 64%] Building CXX object common/CMakeFiles/cockatrice_common.dir/server_player.cpp.o
[ 64%] Building CXX object common/CMakeFiles/cockatrice_common.dir/server_protocolhandler.cpp.o
/home/chrisserver/Cockatrice/common/server_protocolhandler.cpp: In member function Response::ResponseCode Server_ProtocolHandler::cmdCreateGame(const Command_CreateGame&, Server_Room*, ResponseContainer&):
/home/chrisserver/Cockatrice/common/server_protocolhandler.cpp:640:66: error: class Server has no member named getAuthenticationMethod
     bool onlyRegisteredUsers = cmd.only_registered() && (server->getAuthenticationMethod() != Servatrice::AuthenticationNone);
                                                                  ^
/home/chrisserver/Cockatrice/common/server_protocolhandler.cpp:640:95: error: Servatrice has not been declared
     bool onlyRegisteredUsers = cmd.only_registered() && (server->getAuthenticationMethod() != Servatrice::AuthenticationNone);
           ^
make[2]: *** [common/CMakeFiles/cockatrice_common.dir/server_protocolhandler.cpp.o] Error 1
make[1]: *** [common/CMakeFiles/cockatrice_common.dir/all] Error 2
make: *** [all] Error 2

**Comment by woogerboy21** [comment]
#1351 PR isnt working (as indicated by the PR travis failure).

**Comment by HearMeWhisper** [comment]
So is this something I can fix on my side?

**Comment by woogerboy21** [comment]
There needs to be a completely new member added to pass the authentication method configured in the servatrice.ini .  Currently one work around for the code base as it sits on the current commit would be change the value of this line: https://github.com/Cockatrice/Cockatrice/blob/master/cockatrice/src/settingscache.cpp#L115   from true to false and recompile.

So basically, remove your clone and reclone (don't pull in #1351) and then change that line from true to false.

**Comment by woogerboy21** [comment]
Keep in mind that the value I mention is a client side value so anyone wanting to use that fix will need the updated client you change.  The actual underlying issue (server side problem) still needs fixed.

**Comment by HearMeWhisper** [comment]
Hmm, i've tried that.  Is there any way to remove any settings in other directories?  The option is still grayed out after multiple tries.

**Comment by woogerboy21** [comment]
You could force the server to always set the value to false regardless of client setting.  That would probably be better if you have friends trying to connect.

**Comment by HearMeWhisper** [comment]
I'm guessing its the same setting, but under servatrice/src/?

**Comment by woogerboy21** [comment]
Nope, let me get you the line

**Comment by woogerboy21** [comment]
Change this line:
https://github.com/Cockatrice/Cockatrice/blob/master/common/server_protocolhandler.cpp#L655
Change cmd.only_registered() to false

Then recompile.

What that is doing is passing a value of "false" regardless of the checkbox setting in the client.  The reason I didnt recommend this at first is you will see that in the client the checkbox is checked and things are grayed out but the server will ignore that setting when creating the game.


Just curious, when you recompile are you making sure your client / server is shutdown and that you also are running the updated executable created?  If you aren't closing the client/server and running a make install chances are its not overwriting the old client / server executable as they are in use.

**Comment by woogerboy21** [comment]
You can also see on that line the other options that are being passed.  Its passing just true/false in those fields and you can flip which values you want passed by replacing the cmd.XXXX with true false.  but keep in mind that if you dont have a DB connected having some options set to true could cause problems with people connecting

**Comment by HearMeWhisper** [comment]
Servatrice was running on my server while I was compiling on my client, but I closed the program out in my client.

**Comment by woogerboy21** [comment]
If its a client side change than you should have been ok (weird).

**Comment by woogerboy21** [comment]
If the change above is used, you should see that after the game is created, under the game listing in the room the field that indicates if it has any restrictions will be blank.
