### ISSUE TITLE
Server Messages don't alert on taskbar

### ISSUE THREAD

**Issue by ZeldaZach** [Cockatrice/Cockatrice#1392]

**Comment by Nightfirecat** [comment]
Like what, `@/all This is a server message` doesn't cause a taskbar alert?
I saw an alert bubble for one of those earlier today on de1b9252, so if that's the issue you're describing, I didn't reproduce it from my end.

**Comment by ZeldaZach** [comment]
MassCraziness reported that the server shutdown message didn't alert his taskbar and apparently made itself focused, even when the client wasn't...

On OS X that isn't how it happens, so maybe a windows bug?
