### ISSUE TITLE
Extend login protocol to include ability to force close sessions

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#1393]
Add a new boolean flag to the protocol when logging in which will inform the server to kill existing sessions for that user.

**Comment by woogerboy21** [comment]
Whats the idea around the flag?  Is there some were some one could enable/disable the functionality in mind?

**Comment by Daenyth** [comment]
I haven't decided whether to just always enable it or to let the user check
a box.

We could make the server just do it always and skip the protocol.

**Comment by woogerboy21** [comment]
yeah, my thought was to just have it done.  if your worried about some troll kicking you off then you have bigger problems cause your account is compromised at that point

**Comment by woogerboy21** [comment]
Let me know if you want the protocol handler extended. Or feel free to piggy back on the PR like you did with #1391.

**Comment by Daenyth** [comment]
Server side handling is fine.
