### ISSUE TITLE
Moderation -- In Client Chat Logs

### ISSUE THREAD

**Issue by ZeldaZach** [Cockatrice/Cockatrice#1397]
Currently, moderators can only review chat logs via an external program. We should look into a way to incorporate something similar to this external program into the client in some way.

**Comment by woogerboy21** [comment]
I've been thinking through this and could use some direction when it comes to handling how the data is sent back to the client.  The first idea I had was to create a couple dialogues.  One for the moderator to select the options they want to narrow the data down.  And the second was a response dialogue that should present the data to the moderator.  How ever, the response data it self is not translated in any fashion (and will probably never be) so having a dialogue for presentation of the data to the requesting moderator doesn't necessarily have to be a dialogue.  It could be something like a PM from the server.

What are people thoughts about how the data should be presented to the mod/admin requesting the data?

**Comment by ZeldaZach** [comment]
@woogerboy21 I'd like to see the return results be in a popup `<textarea>` field in some format like the following:

```
HH:MM:SS username: %message
HH:MM:SS username: %message
HH:MM:SS username: %message
HH:MM:SS username: %message
```

**Comment by Daenyth** [comment]
I think it should definitely be presented in its own pane; possible even a whole new Tab launched from the admin tab. It's complex enough that we shouldn't limit interactions to just text dumps or anything else. Individual items should be clickable with actions. For example, if I am viewing the most recent bans and see one, I should be able to click the username to filter down to that user's bans; similarly for ip address, etc. Back buttons for the filtering that respond quickly would be fairly important. There's some complex UX workflow I think we should include.

I think the bare minimum we need to include is view all bans sorted by time, *with pagination*
