### ISSUE TITLE
Allow users to opt-out of @/all mentions without disabling mentions totally

### ISSUE THREAD

**Issue by azas9s4d9** [Cockatrice/Cockatrice#1398]
So, @myusername will still ping me, but @/all won't. Could this be implemented?

**Comment by ZeldaZach** [comment]
You're free to opt out of mentions all together, but if you're opted in then we should be able to contact you as a group. 

I don't think we should change the functionality of this feature at this time, but I'll see what others think

**Comment by Nightfirecat** [comment]
Given that only mods/admins can use `@/all`, I don't see a need for this.

**Comment by LestatTheDarkPrince** [comment]
I posted itin the AMA area but ill post it here also as it relates, Can there be a Sound for this? Like a tone that plays when the you are mentioned in the Main chat?

**Comment by radioactivehazards** [comment]
I post this in the AMA section on reddit, but it has Relevance so ill add it here. Can we get like a sound to play when we are mentioned instead of the box? this way other people in area do not get to read part of the post.

**Comment by Daenyth** [comment]
Please open a new ticket for sounds

**Comment by Daenyth** [comment]
I'll probably implement this

**Comment by tooomm** [comment]
So something like:
- [ ] Enable '@/all' chat mentions
- [x] Enable chat mentions for your username

?

**Comment by Daenyth** [comment]
Yes

**Comment by ZeldaZach** [comment]
I'd like it to say

- [x] Enable staff alerts
- [x] Enable chat mentions
