### ISSUE TITLE
Banning dialog pops up twice

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#1402]
Taken out of gitter:

> a banned user gets a double pop up

**Comment by woogerboy21** [comment]
According to @ZeldaZach , this has happened for a while.  I wasn't aware just thought I would mention it.

**Comment by Daenyth** [comment]
Maybe we have a signal connected twice

**Comment by ZeldaZach** [comment]
This doesn't appear to happen anymore, but if you see it again feel free to reopen.

I tested with the latest master build.

**Comment by woogerboy21** [comment]
I was able to reproduce this.  This happens when the user being banned is banned by ip and name.  Its fixed now in #1527.

**Comment by Daenyth** [comment]
Derp, I knew that was the cause a long time ago. I must have said it in gitter but not posted it in here.
