### ISSUE TITLE
UNKNOWN ERROR

### ISSUE THREAD

**Issue by jon120283** [Cockatrice/Cockatrice#1406]
Currently I have been getting disconnected from my matches however currently I am now able to connect to the room to join a match.  Please assist. It says "Failed to join room due to an unknown error"

**Comment by woogerboy21** [comment]
Hello!

First thing I would say is check to make sure you have updated your client
to the most recent version to see if there is an actual error displayed.

Second , can you tell me the OS your running?

Thanks.

**Comment by ZeldaZach** [comment]
No response and unintuitive ticket. Feel free to reopen if something pops up
