### ISSUE TITLE
Increate power Shortcut doesn't work.

### ISSUE THREAD

**Issue by alfchaval** [Cockatrice/Cockatrice#1408]
The shorcut for increase power (ctrl + +) doesn't work for me and for any other spanish players I asked, but players of other countries said that works, so probably is because of keyboard language.

When I use the shorcut, the position of my cards and my opponent's cards change, the power of the selected creature doesn't change.
The shorcut worked fine before I updated the client.

**Comment by ZeldaZach** [comment]
I'm closing this because of #1382. You'll be able to set your own shortcuts in the next official release of Cockatrice (or now if you'd like to compile one yourself!)

**Comment by tooomm** [comment]
Zach, that is not fixing the problem... I highly suggest to look into that!
If people can change shortcuts that's an other thing. Right now we deliver a *broken client* and you're basically saying: Deal with it, you can fix it for your own?! Except they can never use the nice (& well placed) default shortcut for P/T increase everyone is used to.

<br>
We removed all shortcuts from being translatable, so I don't see a problem with transifex etc.
Even checked it, there is no `ctrl` string.

@alfchaval 
which client version did you use before?
which client version do you use now?
which operating system are you on?
does all spanish speaking people you've asked use the client in spanish language?

**Comment by Daenyth** [comment]
I wonder about Spanish layout keyboards too

**Comment by marcofernandezheras** [comment]
I don't know which version of the client are you using, but ctr++ works fine for me (Spanish lang & spanish keyboard)

**Comment by alfchaval** [comment]
Client version: 903292a
Don't remember the last version I used.
OS: Windows 7 Proffesional
I'm using the client in english.

**Comment by tooomm** [comment]
Your client is 4 weeks old, you might want to update to the latest version:
http://www.woogerworks.com/?option=com_content&view=article&id=91

Does this fix your problem?

**Comment by alfchaval** [comment]
Updated to 1ef9041, the problem persist.

**Comment by marcofernandezheras** [comment]
Why you didn't update to https://github.com/Cockatrice/Cockatrice/commit/432c856f0d5ed7580bda0a1a6d06dec492868cea ? You're even behind customizable shortcuts... check [network graph](https://github.com/Cockatrice/Cockatrice/network)

**Comment by ZeldaZach** [comment]
@marcofernandezheras The client on WoogerWorks is updated weekly, not daily. Also, I see what you mean about trying to locate a fix for this and I agree after reading your points. 

The ctrl++ never worked on OS X, but with the custom shortcuts I felt as it was 'patched', per say.

**Comment by tooomm** [comment]
Yep it's broken for me on 1ef9041, too!
Was wondering because I had a bigger break without playing.
**100% sure it worked before on Windows and I used it ~3-4 month ago!**

**Comment by Daenyth** [comment]
How far back do builds go on woogers? Can he download a version that's a
few months old?

**Comment by woogerboy21** [comment]
http://www.woogerworks.com/files/cockatrice.weeklybuilds/

**Comment by tooomm** [comment]
@alfchaval Does this persist with recent versions? Can you let us know, please?

I tend to close this because this is really old and there have been no news.
The default shortcut for increase power <kbd>Ctrl</kbd>+<kbd>+</kbd> works for me on Windows 10 and the most recent 2.5.0-beta.
If I change my keyboard layout to spanish it still works.

Can somebody with a mac test a recent version as well and close if it's working for them?
@ZeldaZach @Daenyth @ctrlaltca

**Comment by ZeldaZach** [comment]
I'm having no problems with shortcuts on Mac, but if this persists please do let us know!

**Comment by alfchaval** [comment]
The error was solved with an update long time ago.

**Comment by tooomm** [comment]
Awesome, thanks for reporting back!

You can close issues once they are solved by the way - it always helps if you keep us updated 😉
