### ISSUE TITLE
Change focus in 'Create token' dialog box

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#1410]
See old conversation: (regarding to @poixen this is a simple one line fix)
https://github.com/Cockatrice/Cockatrice/pull/937#issuecomment-91288780

Since we now have token support build in I would like to see the focus be set to the `token list` rather than the `Token data`. People barely need to create a custom token nowadays if they open this window.

This change would allow to immediately start typing and search for the token you need.

**Comment by Daenyth** [comment]
Seems good.

**Comment by tooomm** [comment]
I feel like this is no longer needed with the related cards feature in place...

**Comment by tooomm** [comment]
Reopening. This is still awkward during spoiler season and the focus on the list instead of the token name helps with creating that token which you are looking for smoother and faster.

**Comment by ctrlaltca** [comment]
It looks like in the meanwhile #1981 got merged, adding the possibility of filtering the tokens list directly from the token name field. So if you open the "create token" dialog and just start typing the token name, it works.

**Comment by tooomm** [comment]
This is indeed correct. Forgot about that.
Anyway, his pr was a feature addition, while this is just a focus change to influence the workflow.
With the name field being focused you still need to use your mouse and it's generally more difficult/slower as what I request here.
You can't use `Ctrl+T` + type `wa` + `Enter` to get your warrior token. Worst case (if you have more sets enabled) you hit 1-2 times the arrow key.

With the search you have to hit 6x tab in between + using arrow keys, or switch from the keyboard and use your mouse. You can't even double click a token to create it.

Is it bad to have both?
Maybe I'm wrong and it's a mess if you've a lot of sets with many tokens enabled? For me it's the other way around so the search isn't benefiting me too much since i just have fewer sets enabled. Plus having the described disadvantages in the workflow.
I don't know... do most players have like 10-20 sets enabled or 50?

**Comment by ctrlaltca** [comment]
If the list is focused when the dialog opens, then you won't be able to use the search, making #1981 less effective.

**Comment by tooomm** [comment]
Correct. But in a normal game (especially talking about spoiler season... since besides spoiler season without related-card info for token available, or custom token creation you don't use the `Create token` dialog too much in the first place) you just use the reverse-related feature.
So in the spoiler season you know what you are going to create, you don't need to properly search for it. You just want to jump to the token in the list. And exactly that happens if you focus the list and start typing.

The search in comparison also finds `Llanowar Elves (token)` if you type "war". It really helps you find stuff if you're not sure or want to check something. Different approach I guess.
But generally you want to `create` a special token from that dialog, not `search` for one. You more likely do that in the deck editor...
I'm not saying the search is bad, I'm questioning if it's the best default option here.

**Comment by tooomm** [comment]
Things might have changed in between and the search is indeed a nice feature. Also, in spoiler season the tokens file might get updated faster now and it's less of a problem.
