### ISSUE TITLE
DB Country Code Issue

### ISSUE THREAD

**Issue by woogerboy21** [Cockatrice/Cockatrice#1412]
So there looks to be n issue with the way that the data in the database for the country code is being written.   I haven't tracked down if its with the registration process or the edit dialogue but when I user has the definition for "Undefined" (the blank box) translated, the insert that is being done is "Un".  I also see it for a couple of other countries like the following:

```
Un
미지
```

Im not to familiar with the country codes, but my guess is that the country code shouldnt be translated.  The countries name in the drop down box should be.

**Comment by tooomm** [comment]
We don't translate country names at all as far as I know!
I couldn't find any country string in transifex as well.

@ideocl4st can you please translate the two Korean signs that appear in the db. :)

**Comment by woogerboy21** [comment]
```
./cockatrice/src/dlg_edit_user.cpp:    countryEdit->insertItem(0, tr("Undefined"));
./cockatrice/src/dlg_register.cpp:    countryEdit->insertItem(0, tr("Undefined"));
```
These lines say otherwises.

**Comment by tooomm** [comment]
Well. `Undefined` is not a country.

**Comment by ctrlaltca** [comment]
Somehow cockatrice is sending "Undefined" as the country name if the country has not been chosen by the user. Then the db truncates the string to 2 characters, and we end up with a "Un" in the database.

**Comment by woogerboy21** [comment]
@ctrlaltca that explains the  Un.  But not the funny other sign.

**Comment by ideocl4st** [comment]
That word means 'Unknown' in Korean, but I don't remember using that word anywhere...

Where is the database that we are talking about here?

**Comment by ctrlaltca** [comment]
An user running a korean-translated cockatrice will see this: https://www.transifex.com/cockatrice/cockatrice/translate/#ko/cockatrice/53593469?q=undefined
Cockatrice will send that korean word, then truncated and inserted in the db.

**Comment by woogerboy21** [comment]
that happens to be the only one in the db, would this happen with other languages?

**Comment by ideocl4st** [comment]
Ah, that's why...The last letter of my translation has been cut off. So it should be 미지정 instead of 미지. However, based on how Cockatrice should be handling that information it should be sending 'Undefined' in English to the user DB, right?

**Comment by woogerboy21** [comment]
@ideocl4st correct, and is why the translation for character codes should not be occuring

**Comment by ideocl4st** [comment]
Hm, I wonder why it didn't happen to other languages (especially Unicode ones like Japanese) though. 

Is there a way to exclude certain strings from being translated in Transifex?

**Comment by ZeldaZach** [comment]
I'm going to do an update for this in a moment.

**Comment by tooomm** [comment]
@ideocl4st 
We can lock certain strings in transifex and mark them for `no translation`.
But that is not fixing the initial problem. Therefore it doesn't matter if you translate `Undefined` to `미지정` or not.
It will just prevent the korean signs in the db, but we will get an `Un` instead, which is also wrong and not wanted. We need `un` in all lowercase instead. ;)

Let's see what @ZeldaZach comes up with. :+1:
