### ISSUE TITLE
Filter games for buddies-only. Suggestion.

### ISSUE THREAD

**Issue by Eosed** [Cockatrice/Cockatrice#1420]
One can filter games by registered users or not. Password-protected or not.
Why not buddies-only or not?
When I apply the last filter I fall from those games for buddies-only.

**Comment by Daenyth** [comment]
We could remove them all but we can't filter it to just ones you can join;
you don't know who has you on their buddy list.

I haven't added an option because it would confuse many players

**Comment by ZeldaZach** [comment]
@Daenyth The option to have buddy "requests" over direct buddy adding one way?

**Comment by Daenyth** [comment]
I don't think that's a net benefit

**Comment by Daenyth** [comment]
dupe #1823
