### ISSUE TITLE
Printing out decklists based on the official deck registration sheet

### ISSUE THREAD

**Issue by ideocl4st** [Cockatrice/Cockatrice#1422]
http://wpn.wizards.com/sites/wpn/files/attachements/mtg_constructed_deck_registration_sheet_pdf11.pdf

Currently, Cockatrice can only print decklists in its own format, which is slightly different from the official deck registration sheet.

It would be very nice if we are able to print them out in the official format.

**Comment by Nightfirecat** [comment]
You can just use a service like http://decklist.org to print it out -- it accepts all common list formats (including Cockatrice).

**Comment by ideocl4st** [comment]
@Nightfirecat True - there are alternative ways to do it. 
I just think it would be nice if we can do it without leaving Cockatrice especially when we already have a way to print out the list of cards.

**Comment by Nightfirecat** [comment]
Seems like in this case, it may be a bit much to reinvent the wheel.

On the other hand, decklist *does* have an API, so it wouldn't be hard to link directly to a deck sheet with all of the cards pre-filled.

**Comment by ideocl4st** [comment]
@Nightfirecat 
http://www.decklist.org/html/directlinking.html

and indeed it does. I think this is the better idea.

**Comment by Daenyth** [comment]
Interesting. I think the exact form is probably copyrighted implicitly so
I'm not sure of the implications of including something like that.. Would
have to look at it.

How important is the form layout vs just having the information?

**Comment by ideocl4st** [comment]
@Daenyth 
Well, The reason is rather personal...A certain Level 2 judge in my play area explicitly forbids any other form of decklist when participating in any Comp-REL tournament he head-judges.

I wouldn't mind if this is considered to be something unnecessary, but there's no harm in suggesting it, right?

**Comment by Daenyth** [comment]
That sounds like some bs. At the events I've been to the L2 judges have
been happy enough to get something with legible handwriting. Sounds like
yours is power tripping or something

That said it's a reasonable feature. We can look at the api

**Comment by tooomm** [comment]
This should be solved by https://github.com/Cockatrice/Cockatrice/pull/2938 some time ago.
