### ISSUE TITLE
4k resolution causes cards and chat box to be too small.

### ISSUE THREAD

**Issue by JettJengaGod** [Cockatrice/Cockatrice#1425]
![image](https://cloud.githubusercontent.com/assets/8456683/9506166/46cd87b8-4bfb-11e5-8369-8be160709385.png)
![image](https://cloud.githubusercontent.com/assets/8456683/9506170/4c78e0f4-4bfb-11e5-958f-e5ceb41df4f8.png)
I got a new laptop and I have been unable to resize the chat boxes or the cards making it very difficult to play on.

**Comment by JettDota** [comment]
Ignore the skype window, that was on accident.

**Comment by woogerboy21** [comment]
Are the images your using pulled from the slightly magic group or some were else?

**Comment by JettDota** [comment]
The card images or the pictures I posted?

**Comment by woogerboy21** [comment]
The card images.

**Comment by JettDota** [comment]
I got the card images from whatever the default is for cockatrice, http://mtgjson.com/json/AllSets.json.zip.

**Comment by JettDota** [comment]
Through oracle.

**Comment by woogerboy21** [comment]
Ah ok, For whatever reason I was thinking the resolution was the card images not the display (completly my fault).  I thought the actual card images were higher resolution.  That's what puzzled me.  Im pretty sure the dockable feature through out the client would help with this.  Does the version of client your running have the dockable features on the deck editor screen and if so does that functionality work well at that high of a resolution?

**Comment by JettDota** [comment]
![deck editor](https://cloud.githubusercontent.com/assets/8456683/9506799/0a5e63a2-4bff-11e5-95cf-806210e8ce0e.PNG)
I don't see any options for that.

**Comment by woogerboy21** [comment]
what version of the client are you running?  (you can find the version number in the help about screen)

**Comment by woogerboy21** [comment]
Also its not an option under the settings.  You can see it in action if your client supports it here:
https://vid.me/z4Ra

**Comment by JettDota** [comment]
Version 903292a and I don't think it supports docking.

**Comment by woogerboy21** [comment]
Looks like thats LA-Rev1.  Not that the Rev 2 will fix the display issue's in the game tab, the new release will have dockable support for the deck editor tab so if you decide to upgrade let us know if you can adjust things on the deck editor tab and if it helps out there at all.  I know there was some discussion about higher res monitor support for mac's but not sure how far that went.

**Comment by tooomm** [comment]
Push
https://www.reddit.com/r/Cockatrice/comments/8vx31n/recently_upgraded_my_pc_and_i_have_a_1st_world/

High screen resolution seems to be a general problem which the app can't properly handle.

**Comment by Daenyth** [comment]
I'd like to see a screenshot of a 2 player game

**Comment by tooomm** [comment]
Linking https://github.com/Cockatrice/Cockatrice/issues/1937
