### ISSUE TITLE
HQ card images blurry/grainy

### ISSUE THREAD

**Issue by kuhruby** [Cockatrice/Cockatrice#1426]
I've downloaded the M15 image set from slightly magic. The images in cockatrice look grainy compared to the originals. The ones pulled from gatherer look even worse. Here is an image viewed in Preview, on the left, and the same image (custom image folder) renderd in cockatrice, on the right:

<img width="657" alt="screen shot 2015-08-27 at 12 32 27 am" src="https://cloud.githubusercontent.com/assets/7840943/9513272/8fafed74-4c53-11e5-94b4-f70ac074acb1.png">

The images seem to look worse as I shrink the card view in cockatrice.

Cockatrice version 1ef9041
MacBook Pro (Retina, 13-inch, Late 2013)
OS X Yosemite 10.10.5

**Comment by Nightfirecat** [comment]
My hunch is that it's related to the image upscaling algorithm used, but I can hardly say for sure.

**Comment by ctrlaltca** [comment]
The problem here is that we're using QPixmap::scaled() http://doc.qt.io/qt-4.8/qpixmap.html#scaled to create a version of the image of the correct size, but we don't take in consideration the more pixels needed in order to display properly on a hi-dpi display.
Related doc (qt5 only) here: http://doc.qt.io/qt-5/qpainter.html#drawing-high-resolution-versions-of-pixmaps-and-images

**Comment by adlersantos** [comment]
+1 on a fix for this issue. 👍

**Comment by KarasuGamma** [comment]
Only tangentially related to this, but is there any way the images of the Plane cards from Planechase can be rotated so they take up the full card window?

**Comment by Daenyth** [comment]
Not right now

**Comment by ZeldaZach** [comment]
This shouldn't be a problem anymore

**Comment by johtso** [comment]
I just started using Cockatrice and it seems to still be an issue?

<img width="628" alt="image" src="https://user-images.githubusercontent.com/830800/140626759-6baa1111-a1fc-4339-881b-f8b437ecc14b.png">

**Comment by ebbit1q** [comment]
the option mentioned here HQ card images no longer exists at all, if you are not satisfied with the amount of pixels cockatrice downloads by default the url used is fully customizable, see our wiki https://github.com/Cockatrice/Cockatrice/wiki/Custom-Picture-Download-URLs#example-urls

to use the highest, non lossy format provided by scryfall you'll want to use the following template: `https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!&version=png`
this will use a lot more disk space but is the highest quality scans available, it's not going to get less blurry than the png version unless you were to scan the images yourself.

**Comment by johtso** [comment]
Thanks for the info! The thing is, the images are pixelated even when you scale them down, so it doesn't seem to be to do with the resolution of the source image. Actually now that I think about it, it might be to do with the down-sampling algorithm..

<img width="491" alt="image" src="https://user-images.githubusercontent.com/830800/140629152-8f017315-5ce8-48e7-8f2a-50813cd996b8.png">

<img width="265" alt="image" src="https://user-images.githubusercontent.com/830800/140629155-5232df05-9166-4a34-907b-c28fb1a2b5b7.png">

**Comment by johtso** [comment]
Sounds like Qt5 should sort high dpi fine.

This stackoverflow question might be useful https://stackoverflow.com/q/34465506/311220

It may just be that the Info.plist is missing
```<key>NSPrincipalClass</key>
<string>NSApplication</string>```

Might also need to do
```QApplication::setAttribute(Qt::AA_UseHighDpiPixmaps)```

**Comment by Ignell** [comment]
Hi, i just installed the beta version (2.8.1-beta.12), and i noticed that the stable version (2021-01-26 Cockatrice v2.8.0) have no problem whith the pics but the beta have all the card grainy. 
I run both on the same PC on the same monitor at the same time, the beta is blurry and the stable is not. 
I tried to serch for other people that have my same problem but i cannot find them, what did i do wrong?

How can i fix the beta version?

**Comment by ebbit1q** [comment]
this is more likely to be a different issue, possibly a new one, please provide more details, including the cockatrice logs and preferably some screenshots, in a new ticket https://github.com/Cockatrice/Cockatrice/issues/new
