### ISSUE TITLE
cleanup usermanual + pictures

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#1427]
- https://github.com/Cockatrice/Cockatrice/tree/master/doc/usermanual
 - `usermanual.md`
 - `usermanual.tex` --> `usermanual.pdf`

Very old and mostly outdated. For example with old unavailable cockatrice URL.
Many things like compiling are covered (and updated more frequently) in the wiki.
The files are not provided with the binaries wooger delivers.

The general idea to have a manual with pictures for the starters is not bad. :+1: 
But difficult to maintain.
<br>
- https://github.com/Cockatrice/Cockatrice/tree/master/doc/usermanual/pics
  - nearly all pictures contain critical material and the ui is outdated

<br>
**Include some kind of manual in the wiki for easier maintenance instead?**

**Comment by ZeldaZach** [comment]
If you'd like to re-write it, you're free to make a PR.
Personally, I think these docs should be removed and we should solely rely on the wiki.
We can make new wiki pages, when needed, to satisfy that.

**Comment by Daenyth** [comment]
The user manual files should be deleted completely and moved to the wiki.

**Comment by ZeldaZach** [comment]
I'll work with Tom to do transition over the next few days. When we're done, I'll PR the removal of the docs

**Comment by Daenyth** [comment]
That would be awesome!
