### ISSUE TITLE
Runs at lower resolution than Apple Retina display

### ISSUE THREAD

**Issue by SomeoneElse37** [Cockatrice/Cockatrice#143]
Cockatrice seems to run at a resolution significantly lower than Apple's extra-high-resolution displays. The result is a lot of jagged, pixellates edges on card pictures and- more importantly- text. I find it quite annoying.

Shown below is a screenshot of the low-resolution Cockatrice window below the high-res OSX menu bar.

![lowrescockatricescreenshot](https://cloud.githubusercontent.com/assets/3794890/3419789/80bdd758-fe7b-11e3-90b5-346b844f0571.png)

Oracle does it, too, but the icons for both programs in the dock, Finder, etc. are just fine.

**Comment by Daenyth** [comment]
We should revisit this with a qt5 build

**Comment by ctrlaltca** [comment]
moved development of this feature to #799
