### ISSUE TITLE
Add search in replay list

### ISSUE THREAD

**Issue by radioactivehazards** [Cockatrice/Cockatrice#1430]
Can we put a "search user" function in the replay area? I sometimes have a hard time remembering people who i played against and it would help to see Certain games over without having to scour the list trying to find 1.

**Comment by Daenyth** [comment]
That's a great idea

**Comment by tooomm** [comment]
Such a "filter" could be handy not only for `Game replays`, but in the `Deck storage` tab as well.

**Comment by ZeldaZach** [comment]
Dupe of #1526
