### ISSUE TITLE
Server drop down list for easier registrations

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#1433]
Provide a predefined list of servers to register with in the `Register to server...` dialog box.

Similar, but different to #1307 
Should be a list with fixed entries. Right now I can imagine wooger and poixen server, since chickatrice doesn't support normal signup. You need to be member of their community (register on their site for a forum account), then you'll automatically get access to the server.

**Comment by Daenyth** [comment]
:boom: done.

**Comment by tooomm** [comment]
Register with server dialog /= Connect to server dialog

But as stated, this will be done when both will merge into one.

**Comment by Daenyth** [comment]
At this point this is dup https://github.com/Cockatrice/Cockatrice/issues/742#issuecomment-268402235
