### ISSUE TITLE
Extend ban table to include moderator doing the ban

### ISSUE THREAD

**Issue by woogerboy21** [Cockatrice/Cockatrice#1436]
Currently there is no documented event when a ban occurs on who is doing the bans.  It would be nice to have the moderator putting the ban in place recorded in the ban table.

**Comment by Daenyth** [comment]
What about the `id_admin` field? I'll check the code.

**Comment by Daenyth** [comment]
Definitely `id_admin`: https://github.com/Cockatrice/Cockatrice/blob/e9156ecd62914adef8def4da6b59938622147138/servatrice/src/serversocketinterface.cpp#L765

**Comment by woogerboy21** [comment]
ok cool :+1:
