### ISSUE TITLE
Protocol extension to support in-client registration

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#144]
I thought I already noted this all down but maybe it was on the old github

New message
Command_Register
- username
- hashed password value
- email address

New responses
- User already registered
- Email required and not sent
- New username accepted & Activation email sent to $email
- Server does not use authentication

New response to login as unregistered
~~Server requires registered accounts to connect~~

Cockatrice needs a new UI pane for it and UI for when the server doesn't support registration

Servatrice needs to handle the message

**Comment by ZeldaZach** [comment]
Gonna get started now @Daenyth ? :smile:

**Comment by Daenyth** [comment]
I'm gonna call this one done.
