### ISSUE TITLE
Active Session

### ISSUE THREAD

**Issue by Eosed** [Cockatrice/Cockatrice#1440]
I lose connection and I can't log in again. This stays for a while. Of course I got kicked from the game by the time I log.

![sin titulo](https://cloud.githubusercontent.com/assets/13790334/9568241/2f87abfc-4f1a-11e5-8646-b0c8967b6a2f.jpg)

Is there any way to disconnect an "active session" if you can't log in?

**Comment by ZeldaZach** [comment]
Yes,  #1438

**Comment by woogerboy21** [comment]
Right now the code we have is causing stability issues with the server when
old sessions are closed and until the bug is fixed there is no real way
around this till the old session times out.
