### ISSUE TITLE
Ban messages with quotation marks are erased.

### ISSUE THREAD

**Issue by MassCraziness** [Cockatrice/Cockatrice#1443]
When typing in the ban reason boxes, anything you place in quotation marks will be removed.

EX: `This user was banned for saying "BAD WORD"` would appear as `This user was banned for saying`

**Comment by Daenyth** [comment]
@masscraziness did you mean to close this?

**Comment by MassCraziness** [comment]
No, sorry.

**Comment by woogerboy21** [comment]
This is most likely due to the line:
https://github.com/Cockatrice/Cockatrice/blob/master/servatrice/src/serversocketinterface.cpp#L767

My guess would be that were converting to standard string and then into qstring. Probably should test converting to utf8 and then working with the content to store all characters.  (Just a note and a guess)

**Comment by ctrlaltca** [comment]
I'm testing current trunk:
 * the command is sent correctly
```
OUT 70 "cmd_id: 20 moderator_command { [Command_BanFromServer.ext] { user_name: "fabio2" address: "127.0.0.1" minutes: 5 reason: "Test \"test\" test" visible_reason: "Test2 \"test2\" test2" clientid: "" } }"
```

The server is inserting the row correctly:
```
		 1954 Execute	insert into cockatrice_bans (user_name, ip_address, id_admin, time_from, minutes, reason, visible_reason, clientid) values('fabio2', '', 1, NOW(), 5, 'Test \"test\" test', 'Test2 \"test2\" test2', '')
```

The user gets notified of the ban reason correctly (italian, sorry):
![banish me mucho](https://cloud.githubusercontent.com/assets/1631111/9588051/426f7d5a-5026-11e5-8dcd-2a27932ca764.png)

Looking at the database, the row is fine:
```
MariaDB [servatrice]> select * from cockatrice_bans where user_name='fabio2';
+-----------+------------+----------+---------------------+---------+------------------+---------------------+----------+
| user_name | ip_address | id_admin | time_from           | minutes | reason           | visible_reason      | clientid |
+-----------+------------+----------+---------------------+---------+------------------+---------------------+----------+
| fabio2    |            |  0000001 | 2015-08-31 21:18:49 |       5 | Test "test" test | Test2 "test2" test2 |          |
+-----------+------------+----------+---------------------+---------+------------------+---------------------+----------+
1 row in set (0.00 sec)
```

I think the real cause of the problem has not been detected yet.

**Comment by ZeldaZach** [comment]
Just occurred to me to check the PHP side of things. It seems like things weren't escaped properly and thus it doesn't show the message in full.

```
<input type="text" name="reason" value="Testing "go away". Ding 123" size="255" readonly>
```

Will show
```
Testing
```

and then just report the rest as HTML error. This is not a cockatrice thing at all.
