### ISSUE TITLE
Enable create related card to create cards from the stack.

### ISSUE THREAD

**Issue by Psithief** [Cockatrice/Cockatrice#1447]
Expanding on #1203.

Instants and Sorceries that create tokens go to the stack when played. The context-menu for cards on the stack needs to have a 'created related card' option.

Currently, `<related>` has no functionality unless the card is on the battlefield.

**Comment by Daenyth** [comment]
:+1:

Pretty sure some spells do it on cast too.

Needs to handle attach also
