### ISSUE TITLE
Enable / Disable sounds per room

### ISSUE THREAD

**Issue by poixen** [Cockatrice/Cockatrice#1452]
It might be nice to have a switch in each room to enable or disable sound.

**Comment by Daenyth** [comment]
I suppose a menu entry wouldn't be much of a UI burden for it.

**Comment by radioactivehazards** [comment]
What if some users in said room want sounds?

**Comment by Daenyth** [comment]
Sounds are a client side setting. The server doesn't know or care, and
so no one else in the room would either.
