### ISSUE TITLE
Shaman of the pack bug? With database code

### ISSUE THREAD

**Issue by DanieLegend** [Cockatrice/Cockatrice#1455]
Hi, well, my problem is that Shaman of the pack don't appear in "Creatures", appear in a new section called "Shaman", as you can see in the images.

When you load the deck on a match:

![shaman](https://cloud.githubusercontent.com/assets/14105756/9652908/e0591bca-521f-11e5-83cf-fb4997c8590d.png)

When you are editing the deck:

![shaman2](https://cloud.githubusercontent.com/assets/14105756/9652909/e05c6c8a-521f-11e5-82ac-3cc50244965d.png)

I don't know why this is happening, also I play other Shamans like Deathrite shaman, but deathrite appears in the right section.

This is the code of Shaman of the Pack in my database:

< card>
            < name>Shaman of the Pack< /name>
            < set picURL="http://magiccards.info/scans/en/ori/217.jpg" picURLHq="" picURLSt="">ORI< /set>
            < color>B< /color>
            < color>G< /color>
            < manacost>1BG< /manacost>
            < type>Creature — Elf Shaman< /type>
            < pt>3/2< /pt>
            < tablerow>2< /tablerow>
            < text>When Shaman of the Pack enters the battlefield, target opponent loses life equal to the number of Elves you control.< /text>
< /card>

(I put a space after each "<" just in case the page don't show it correctly, but in the database those spaces don't exist)

If you know how to fix that please tell me, also if not, I would appreciate the code of Shaman of the Pack of your database just to replace mine to see if it would work.

Regards, Dani.

**Comment by Daenyth** [comment]
Update your client and run oracle, this is an old bug

**Comment by Daenyth** [comment]
Dupe #105 -- this bug is from summer 2014...

Update more often. We have new features every week.
