### ISSUE TITLE
"Socket Error:  Connection Refused"

### ISSUE THREAD

**Issue by methodicalmike** [Cockatrice/Cockatrice#1460]
I keep getting the error "Socket Error:  Connection Refused" when trying to connect to the server.  I have not been able to get on all day long.

Woogerworks is usually very punctual with reporting server downtimes on their twitter and everything seems to be fine there.

Just trying to find out what is wrong and make sure that I am not doing anything wrong.  I know last week some users were getting banned as part of a glitch.  I hope that is not happening again.

Thanks for the help!

**Comment by ZeldaZach** [comment]
The issue seems to be linked to users connecting to `cockatrice.woogerworks.info` instead of `cockatrice.woogerworks.com`. Try changing that and see if it works!

**Comment by methodicalmike** [comment]
Thanks so much.  That did work.  Im curious though, what is the difference between the .com and .info?

**Comment by Daenyth** [comment]
@woogerboy21 mentioned some DNS changes - maybe he was dropping the old domain.

Either way this is an issue with a specific server and not the software itself.
