### ISSUE TITLE
Can't override old shortcuts even after removing them

### ISSUE THREAD

**Issue by anoda9** [Cockatrice/Cockatrice#1461]
I'm trying to set crtl-P to "set counters - green" on a card. Even after removing the "print deck" shortcut, the client still gives the "shortcut already in use" message.

**Comment by ZeldaZach** [comment]
You'll need to remove the old shortcut before you can assign it again

**Comment by anoda9** [comment]
>Even after removing the "print deck" shortcut

Yea... isn't that exactly what I wrote?

**Comment by anoda9** [comment]
Nevermind, the problem was I forgot crtl-P was still mapped to set p/t.

**Comment by anoda9** [comment]
It might be helpful to have the "shortcut already in use" message also tell the user where the conflict is. If the client already has to read the shortcut database to see what is in use or not, it shouldn't be too much more effort to tell the user what conflicts.

**Comment by Daenyth** [comment]
That would be a good feature.
