### ISSUE TITLE
Put "edit sets" and "edit tokens" windows into preferences?

### ISSUE THREAD

**Issue by anoda9** [Cockatrice/Cockatrice#1462]
They are preferences in every sense of the word, so it seems like it'd make more sense to have them be accessible through the preferences window. (This would also mean there is a keyboard shortcut to easily access them, which would be nice.)

**Comment by tooomm** [comment]
Have you tried the <kbd>Alt</kbd> accelerators?

<kbd>Alt+A+E</kbd>: Edit Sets
<kbd>Alt+A+T</kbd>: Edit Tokens
*(they are depended on your language settings)*

**Comment by Daenyth** [comment]
This seems reasonable

**Comment by ZeldaZach** [comment]
I think I'm fine with it as-is, but if I'm wrong and the majority wants this change we can reevaluate it.
