### ISSUE TITLE
Preference to change default text size?

### ISSUE THREAD

**Issue by anoda9** [Cockatrice/Cockatrice#1463]
Yes, you can use crtl+scroll to change the size of the chat and game log, but that doesn't work for the game list, player list, replays and buddy list, card list in the deckbuilder and a whole host of other things. On a laptop it's not an issue, but if you have a larger screen it is. It'd be good if there were a preference to change the default text size.

**Comment by Daenyth** [comment]
:+1: we should have some font selection.

**Comment by ctrlaltca** [comment]
Note: this can be actually achieved using themes; eg. inside a theme folder, create a file named style.css with content:
```
* {
	font: bold 14px;
}
```
Result:
![schermata 2015-09-08 alle 16 57 47](https://cloud.githubusercontent.com/assets/1631111/9738270/06a4d9f2-564b-11e5-801b-623a89542df4.png)

More info here: http://doc.qt.io/qt-4.8/stylesheet-examples.html

We's really need to create some GUI for themes...

**Comment by ZeldaZach** [comment]
a GUI would be nice... like how we have the avatar upload GUI, maybe we can base one off of that?

**Comment by ZeldaZach** [comment]
@tooomm can you document this on the wiki? It's more a wiki good to know for theming than a ticket.

**Comment by tooomm** [comment]
It's there already: https://github.com/Cockatrice/Cockatrice/wiki/Themes#the-style-sheet-file-advanced
