### ISSUE TITLE
Viewing replays causes a crash

### ISSUE THREAD

**Issue by anoda9** [Cockatrice/Cockatrice#1464]
On 60ed9fd, OSX 10.10.5
Open a replay, click the play button --> crash.

**Comment by ZeldaZach** [comment]
Confirmed. Debugging log didn't show much, but I'm going to see what I can find.

**Comment by poixen** [comment]
Are you on the latest client. I fixed something like this a long time ago.

**Comment by ZeldaZach** [comment]
This is the latest client @poixen something went wrong somewhere

**Comment by woogerboy21** [comment]
Does anyone know what the last version of the client that didnt crash was?

**Comment by poixen** [comment]
When does the replay crash? The last time it happened due to a string trying to print in the chat.

**Comment by JineteDV** [comment]
https://www.dropbox.com/s/zqd5ha5z4a34v37/CrashReport.rtf?dl=0

**Comment by ZeldaZach** [comment]
Caused by: https://github.com/Cockatrice/Cockatrice/commit/a64ea1735734b4af48df2f05a3082463f6901fb0
