### ISSUE TITLE
Auto-connect function broken

### ISSUE THREAD

**Issue by anoda9** [Cockatrice/Cockatrice#1465]
On 60ed9fd, OSX 10.10.5
It worked before, but for some reason it doesn't now. 

Edit: "before" as in - in previous builds. It has never worked for me on 60ed9fd.

**Comment by ZeldaZach** [comment]
The auto connect feature works as expected for me on the same build & OS.

**Comment by Daenyth** [comment]
You're going to have to say a bit more than "broken" - what happens exactly? Try using the debugging steps in the wiki and get the console output.

**Comment by woogerboy21** [comment]
I can tell you on my linux boxes if I select the save password and also select the auto connect the client does not log in.  When the client is re-opened there is no authentication box that pops up (as if it was going to auto connect) but no connection is made and when you choose to connect the previous hos radio button shows checked and the user information is stored but there is no name in the hostname box and the client does not auto connect..

**Comment by anoda9** [comment]
log:

Theme changed: "Default" 
15353 cards in 183 sets loaded 
loadCardDatabase(): Path =  "~/Library/Application Support/Cockatrice/Cockatrice/cards.xml"  Status =  0 
15646 cards in 183 sets loaded 
main(): starting main program
main(): SoundEngine constructor finished
main(): MainWindow constructor finished
ClientID In Cache:  "63e0e39713b1c90" 
main(): ui.show() finished
Event loop finished, terminating...
