### ISSUE TITLE
Cockatrice on MAC OS : 

### ISSUE THREAD

**Issue by lloic** [Cockatrice/Cockatrice#1466]
Hi,

Once connected on the server cockatrice.woogerworks.com (Port 4747) with the client downloaded here:
http://www.woogerworks.com/?option=com_content&view=article&id=91

I cannot connect to the room "Main". When I try to do it, I have the following error:
"Failed to join the room due to an unknown error."

Surprisingly, I can connect to the Room "Magic-League.com". 

Any idea of what to do ?

Lo.

**Comment by Daenyth** [comment]
Can you run with the debugging steps in here https://github.com/Cockatrice/Cockatrice/wiki/Debugging#mac-osx

And then post that console output?

**Comment by lloic** [comment]
Sure, with pleasure. Can you give me the procedure step by step ?

**Comment by lloic** [comment]
here it is:

[1] 18933
ruby:~ lbarthe$ 15359 cards in 186 sets loaded 
loadCardDatabase(): Path =  "/Users/lbarthe/Library/Application Support/Cockatrice/Cockatrice/cards.xml"  Status =  0 
15652 cards in 186 sets loaded 
main(): starting main program
main(): SoundEngine constructor finished
main(): MainWindow constructor finished
ClientID In Cache:  "26c9b4542e1a1b4" 
main(): ui.show() finished
2015-09-05 22:58:06.763 cockatrice[18933:984386] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
Cannot open file ':/resources/countries/un.svg', because: Unknown error
2015-09-05 22:58:15.823 cockatrice[18933:984386] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
Event loop finished, terminating...

[1]+  Done                    /Applications/cockatrice.app/Contents/MacOS/cockatrice ~/Desktop/Cockatrice.log

**Comment by ctrlaltca** [comment]
Just tested and it works here. Is it still broken for you?
This could be related to #1379.

**Comment by lloic** [comment]
Yes, still broken … A configuration problem ? 

Lo.

> Le 6 sept. 2015 à 11:53, ctrlaltca <notifications@github.com> a écrit :
> 
> Just tested and it works here. Is it still broken for you?
> This could be related to #1379 <https://github.com/Cockatrice/Cockatrice/pull/1379>.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/Cockatrice/Cockatrice/issues/1466#issuecomment-138061461>.
> 

--
Loïc Barthe
Professor
Co-head of the VORTEX Group - IRIT - Université de Toulouse
http://www.irit.fr/~Loic.Barthe <http://www.irit.fr/~Loic.Barthe>
00 33 (0)5 61 55 63 12

**Comment by ctrlaltca** [comment]
@woogerboy21 care to check server logs?

**Comment by lloic** [comment]
it works now ... Many thanks and let's play !!!!!!
