### ISSUE TITLE
Settings not being saved between client closure / reopen

### ISSUE THREAD

**Issue by woogerboy21** [Cockatrice/Cockatrice#1467]
Looks like with the introduction of the portable builds that in the linux client the default behavior has been changed to act like a portable build.  Sadly though, the settings are not being saved in the .ini file upon change.  If I were to guess, the startup code logic is pointing to one place to look for settings but the saving logic is pointing to another to save upon change.

**Comment by Daenyth** [comment]
Did you mean to close?

**Comment by woogerboy21** [comment]
Yea , I believe this was caused by the pre-def issue that was found and
fixed.  If I find otherwise I'll either reopen or create a new issue.
