### ISSUE TITLE
After updating Cockatrice, have to click Clear Filter to see any matches

### ISSUE THREAD

**Issue by catmanjan** [Cockatrice/Cockatrice#1476]
May be a mismatch between filter logic from a previous version - I assumed it was only me but another user experienced the same issue.

**Comment by Nightfirecat** [comment]
I just updated my build from a weekly (~2 weeks ago) to the current build and did not experience this issue. How old was the previous client you updated from?

**Comment by catmanjan** [comment]
A few months at least - quite confusing as when I logged in it appeared that there were no games available, in addition to the bug may need an enhancement request to make it more obvious (in the games list area) that there is a filter being applied.

**Comment by Daenyth** [comment]
We could add some label text next to filter buttons, something like
"Showing X of Y games"

**Comment by tooomm** [comment]
@Daenyth a game counter related to filters was also requested here: #583

**Comment by ZeldaZach** [comment]
It's possible your filters were set to only show one format with at most 1 player or something. This doesn't seem to be an issue on any versions that I've tested in the last month.

**Comment by catmanjan** [comment]
@Daenyth I think there needs to be something shown in the grid itself - especially in the case where no games are visible due to filtering. 

@ZeldaZach The other user nor I had ever actually used filtering. In your testing did you upgrade directly from an older version to the latest version?

**Comment by catmanjan** [comment]
Just had 3 other users have this problem, they had to ask in chat how to fix it... One of them was updating from a year old version.

**Comment by demern** [comment]
Can confirm that this was also an issue for me (on Linux Mint) and a friend (on Mac) when updating from an older version to the current one today. Pretty easy to fix, but a bit confusing at first when you log in and there aren't any games in the list. In our case, the reason no games appeared was because both the min. and max. number of players was set to "1", so only games for 1 player would show up. It also would not show password-protected games or full games by default.

**Comment by tooomm** [comment]
this should be no longer an issue?

**Comment by ZeldaZach** [comment]
i still hear about it  sometimes

**Comment by tooomm** [comment]
but it's nothing that we are fixing, isn't it?
it's a one time issue when you update in some cases on some older clients.
it should go to the faq instead maybe?

**Comment by ZeldaZach** [comment]
Yeah I think it's better in the Faq as we can't do much for this

**Comment by catmanjan** [comment]
It would be better to reset filters every time rather than leave it as is,
people not seeing games is a bit of a showstopper

**Comment by tooomm** [comment]
Fate... :)

Actually I just run into the same issue when testing with a clean install (with no leftovers of former installations)... used the newest dev build. So this issue is not fixed and it isn't a problem of some older clients! :cry:

**Comment by Daenyth** [comment]
@tooomm Thanks for the test, that helps narrow things down!
