### ISSUE TITLE
"Show all tokens from this deck" feature does not work

### ISSUE THREAD

**Issue by Nightfirecat** [Cockatrice/Cockatrice#1481]
Selecting the "Show all tokens from this deck" option in the tokens window does not change the available tokens in the pre-populated list. This is true both of offline and online games.

Image: http://i.imgur.com/23zDdR1.png
Build: 60ed9fd on Windows 7

**Comment by ctrlaltca** [comment]
Do you actually have at least one token card added to the deck? Because if the deck doesn't contain at least one token, he list will always show all the available tokens  from the card database.

**Comment by ZeldaZach** [comment]
Tested on 60ed9fd and it seems that as long as you have at least 1 token in the deck, the "show all tokens from this deck" will function as it should.

No changes I feel are necessary at this point in the code logic, unless the <kbd>reverse-related</kbd> action is coming into play soon.

**Comment by tooomm** [comment]
>Do you actually have at least one token card added to the deck? Because if the deck doesn't contain at least one token, the list will always show all the available tokens from the card database.

It should maybe just show an empty list (with a hint maybe) to avoid confusion and to work as it's described. :)

**Comment by Nightfirecat** [comment]
Ah, so this feature only works if you specifically have tokens in your deck? (as opposed to token-producing cards)

**Comment by ctrlaltca** [comment]
Maybe you're confusing this with the newly added support for "related" cards? that's avaiable only for split/flip cards by now; token support is in the works.

**Comment by Nightfirecat** [comment]
I suppose so. It just doesn't seem totally intuitive to me for that to be the behavior here. I guess I'll revisit this after related token support gets finished.
