### ISSUE TITLE
Clicking a chat notification bubble causes Cockatrice to resize itself

### ISSUE THREAD

**Issue by Nightfirecat** [Cockatrice/Cockatrice#1482]
See title.

When Cockatrice is maximized in Windows (on my monitor, 1920x1080), clicking on any chat notification bubbles from the tray cause it to resize to [this size](http://i.imgur.com/pB0aQAF.png). This has been occurring for a month or so -- though I don't remember if there were any notable issue fixes that preceded it -- and occurs up to the latest weekly, 60ed9fd.

**Comment by ctrlaltca** [comment]
Caused by #923

**Comment by ctrlaltca** [comment]
Tested and confirmed. This is due to this line https://github.com/Cockatrice/Cockatrice/blob/master/cockatrice/src/window_main.cpp#L707
calling http://doc.qt.io/qt-4.8/qwidget.html#showNormal . If the window was previously maximized, showNormal() will de-maximize it, causing it to resize.
