### ISSUE TITLE
Hide top card when "Always reveal top card" is disabled.

### ISSUE THREAD

**Issue by anoda9** [Cockatrice/Cockatrice#1486]
Currently, there is no easy way to tell if the top card of your library is set to "always reveal". It would be good if were some visual indicator for this. Maybe having the library/top card have an blue outline/border?

**Comment by ZeldaZach** [comment]
If it's set to "always reveal" you'll see the top card instead of the card back... unless I'm mistaken

**Comment by Nightfirecat** [comment]
He may mean that the top card remains revealed if you previously had the "Always reveal the top card" set, then turn it off, until you draw a card.

**Comment by anoda9** [comment]
Yes, the top card stays revealed, even after you unset "always reveal top card". 

On second though, the most obvious solution is just to hide the top card when "always reveal top card" gets turned off.

**Comment by Daenyth** [comment]
> hide the top card when "always reveal top card" gets turned off.

If that isn't the current behavior, I consider the current behavior a bug.

**Comment by anoda9** [comment]
Unfortunately that is the current behavior.


Akio

**Comment by catmanjan** [comment]
Actually it is fine the way it is, once you've revealed the card it is public information, no harm in it remaining visible. Once you stop revealing and shuffle or draw or otherwise change the top card of your library you can no longer see what the top card is.

This is how revealing hands works, the window remains visible to your opponent even after the turn ends.

**Comment by anoda9** [comment]
@catmanjan the harm is that if the card stays revealed, it isn't obvious if the "always reveal top card" function is enabled or not, leading to cards accidentally being revealed when they shouldn't be. The public information is always preserved in the chat (it will say "Player 1 reveals [cardname] from the top of his library." after each card draw), so there's no need for it to remain visible in the library.

>This is how revealing hands works, the window remains visible to your opponent even after the turn ends.

It's not really right to compare these, since revealing hands is a one-time event, whereas "always reveal top card" is a continuous stream of information (snapshot vs. video). The behavior you described is how the "reveal top card" (once) function works, and it's appropriate for that one, but not for this one imo.

**Comment by catmanjan** [comment]
Okay, so revealing top card once should spawn a window then, which is possible through the "Reveal top cards to..." menu item.

**Comment by ZeldaZach** [comment]
this should be solved now with the checkbox feature

**Comment by tooomm** [comment]
Nothing changed, this is still an issue.

**Comment by ebbit1q** [comment]
you can see if the top of library is revealed by right clicking it and noticing if reveal top of library is checked

**Comment by tooomm** [comment]
https://github.com/Cockatrice/Cockatrice/issues/1486#issuecomment-138665387
