### ISSUE TITLE
Ability to set shortcuts for reveal hand, reveal top card of library once

### ISSUE THREAD

**Issue by anoda9** [Cockatrice/Cockatrice#1487]
The shortcut setting preference is awesome and a huge improvement to the client. It's missing a few things that I think would be useful, though. The ability to:
1. Set a shortcut to reveal your hand (thoughtseize, etc.)
2. Set a shortcut for reveal the top card of your library once (counterbalance, lurking predators, dark confindant)

**Comment by ZeldaZach** [comment]
cc: @marcofernandezheras

**Comment by ZeldaZach** [comment]
i did this fairly recently
