### ISSUE TITLE
Automatic counters for modular or other effects

### ISSUE THREAD

**Issue by catmanjan** [Cockatrice/Cockatrice#1490]
While I know this is an enhancement that would take a lot of work unless it is provided by the data source, it would be nice.

Just like tap lands automatically come into play tapped, modular should automatically get triggered (i.e. Arcbound Ravager, and other similar non-modular cards like Tendo Ice Bridge).

**Comment by ZeldaZach** [comment]
I feel this is getting to into the rules aspect, but it's a possibility we can add to the XML like

```
<red-counters>3</red-counters>
<green-counters></green-counters>
<yellow-counters></yellow-counters>
```

to allow cards put into play to have certain types of counters already on them.

**Comment by Daenyth** [comment]
I think something like Zach's suggestion is maybe the most reasonable; that being said, I don't think we're going to implement this. I don't think it's in line with our goals right now, and it would be a fairly high amount of work for a small feature.

**Comment by tooomm** [comment]
It would be handy to have planeswalkers or other cards enter the battlefield with some counters as well for example...

But I see the concerns.
