### ISSUE TITLE
Floating windows can become obscured by the interface making them immovable

### ISSUE THREAD

**Issue by catmanjan** [Cockatrice/Cockatrice#1491]
Windows should be locked inside the game windows viewport or floating outside of the interface.

![untitled](https://cloud.githubusercontent.com/assets/137350/9752664/48437a8e-56f6-11e5-81e1-7cdebdbfe8e7.png)

**Comment by ZeldaZach** [comment]
I've observed this too. We really need to create better boundaries for external popups, or just have them similar to the deck editor and have the popups come outside of the main client

**Comment by Daenyth** [comment]
All overlays like that should have esc bound to remove them.

**Comment by catmanjan** [comment]
Being able to remove the window is not enough, when you are shown an opponents hand you may want to keep the window active for future reference. If you remove the window there is no easy way to reinstate it.

**Comment by Daenyth** [comment]
I agree. It's just an additional facet.

**Comment by Daenyth** [comment]
@ZeldaZach "Gameplay problem" label is for when the client makes it impossible/onerous to follow the game rules correctly.

**Comment by ctrlaltca** [comment]
This is a regression: #754
