### ISSUE TITLE
Keyboards not working at all (Mac)

### ISSUE THREAD

**Issue by Johan86** [Cockatrice/Cockatrice#1494]
Since yesterday my keyboard isn't working at all in Cockatrice. I can't even type in the textfields, is there any settings that might have been changed without my knowledge or is it something else? The keyboard is working fine everywhere else, it's just when I'm trying to type or do anything in Cockatrice. 

BR Johan

**Comment by ctrlaltca** [comment]
Reboot maybe?

**Comment by ZeldaZach** [comment]
Computer keyboard daemon sometimes crashes. Try rebooting your computer

**Comment by Daenyth** [comment]
> Computer keyboard daemon sometimes crashes

Huh?

@Johan86 If you haven't upgraded in that timespan I have no idea what might cause something like this. Try closing and opening the app, and rebooting the computer.

**Comment by ctrlaltca** [comment]
Closing as "need feedback".
