### ISSUE TITLE
Group Kicking, Feature

### ISSUE THREAD

**Issue by MrAAA264** [Cockatrice/Cockatrice#1500]
A problem that i've been seeing in game of 3 players or more, is that the host has all of the power. But what if the host tried to cheat, or plays by different rules. Could there be a way to kick the host as a group vote. But i would'nt want this kind of feature in a 1v1 game, it just wouldnt work. 

If all players(but the host) vote on him, being kicked. Could this be a real thing that can be implemented in the client?

**Comment by ZeldaZach** [comment]
I don't see us implementing something like that at this time, but I am curious what others think.

**Comment by MrAAA264** [comment]
this was the thing i was asking for your help earlier, the host shuffled in his eldrazi, which has indestructible, into his deck with his grave, in res to a player casting damnation. Stuff like this, where the host player does thing he isnt suppose to do but does it anyway. It would take too long to undo the effects

**Comment by ctrlaltca** [comment]
What if you go to play in a store and notice that the owner is cheating? Do you change store or try to kick the owner out of his own store and overtake it? :)

**Comment by Daenyth** [comment]
This is by design. Ignore list bad players and move on. You could also run your own game. #622 would help too.
