### ISSUE TITLE
Crash viewing library or graveyard

### ISSUE THREAD

**Issue by oscscull** [Cockatrice/Cockatrice#1505]
When viewing library, grave or exile cockatrice crashes.

 Windows error message:
Problem signature: Problem Event Name: APPCRASH Application Name: cockatrice.exe Application Version: 0.0.0.0 Application Timestamp: 55f43364 Fault Module Name: Qt5Gui.dll Fault Module Version: 5.5.0.0 Fault Module Timestamp: 55911d00 Exception Code: c0000005 Exception Offset: 000768f0 OS Version: 6.1.7601.2.1.0.256.48 Locale ID: 2057 Additional Information 1: 0a9e Additional Information 2: 0a9e372d3b4ad19135b953a78882e789 Additional Information 3: 0a9e Additional Information 4: 0a9e372d3b4ad19135b953a78882e789

This is on the latest version of cockatrice, running on windows 7.

**Comment by Fizztastic** [comment]
https://github.com/Cockatrice/Cockatrice/blob/master/cockatrice/src/zoneviewwidget.cpp#L148

First-chance exception at 0x572D97BD (Qt5Guid.dll) in cockatrice.exe: 0xC0000005: Access violation writing location 0x0000000B.
Unhandled exception at 0x572D97BD (Qt5Guid.dll) in cockatrice.exe: 0xC0000005: Access violation writing location 0x0000000B.

**Comment by ctrlaltca** [comment]
@Fizztastic do you have a full backtrace? how did you find out the problem is at line 148?

**Comment by Fizztastic** [comment]
@ctrlaltca I'll try and get a full backtrace. It's where Visual Studio tells me it's breaking.

**Comment by ctrlaltca** [comment]
Ok if msvc it's reporting that as the problem it's enough, thank you.

**Comment by ctrlaltca** [comment]
Can you try removing lines 144-149 and just adding a ```    int titleBarHeight = 24;``` and see it that works?

**Comment by Fizztastic** [comment]
@ctrlaltca It fixes the bug. I was able to open the library/graveyard/exile without crashing.

**Comment by ctrlaltca** [comment]
wanna open a PR?
