### ISSUE TITLE
Custom Set Selections

### ISSUE THREAD

**Issue by joca-bt** [Cockatrice/Cockatrice#1506]
Would it be possible, or is it possible, to create custom set selections?

What do I mean with this? For example, I am building a Legacy deck, I have to edit the available sets and select only the ones allowed in Legacy. Then I switch to Modern, I have to do the same. If there could be a way to save and load custom selections of sets, the switching between types when building decks would be greatly improved.

EDIT: If it were possible to attach each set selection to the deck it would be even better! This way the user would only needs to select the sets when creating the deck. Then, when switching between decks, changing the set selection would not be necessary.

Currently, I do this by keeping a cardDatabase.ini.legacy, cardDatabase.ini.modern, and so on and restarting the application after changing the file.

**Comment by Daenyth** [comment]
You can make a filter, OR all the valid sets together. Right now that's the
best option. This is probably a duplicate ticket but I'm on phone at the
moment so it's hard to look up

**Comment by joca-bt** [comment]
Ok, but then I need to save the filter somewhere else as well, or do you mean something else?

**Comment by Daenyth** [comment]
No, that's what I meant.

Tappedout has a good deck builder too and can export until we do something
for this

**Comment by tooomm** [comment]
Linking #215

**Comment by ZeldaZach** [comment]
We have a filter on format now, that should solve this
