### ISSUE TITLE
Card Backs Missing

### ISSUE THREAD

**Issue by ZeldaZach** [Cockatrice/Cockatrice#1507]
This has come about due to the theme manager, #1081.

Card backs are loaded from the first sub-directory down in each theme folder and is not acceptable in a .svg format, which is what we've used in the past.
    Ex: (OS X) `~/Library/Application Support/Cockatrice/Cockatrice/themes/Fabric/cardback.*`

Allowing the use of .svg in loading images for themes would be the best fix, but converting it into a QImage is also a possibility (I've experimented with this myself earlier).

**Comment by lOEILl** [comment]
Is there a fix to this yet ?

**Comment by Nightfirecat** [comment]
@lOEILl Check ctrlaltca's pull request at #1511. It sounds like that fixes the issue.
