### ISSUE TITLE
No sound on Linux, build 59da62d (2015-09-13)

### ISSUE THREAD

**Issue by wsky0csky** [Cockatrice/Cockatrice#1514]
Host: Debian 8 x64, QT4, XFCE 4.10

No sound after upgrading cockatrice to the version mentioned.

**Comment by ctrlaltca** [comment]
Can we see a debug log? run cockatrice from a terminal and try to have it play a sound.

**Comment by wsky0csky** [comment]
Nothing shown in the log while trying to use the "test sond" settings button:

wsky@deb01silver:~$ cockatrice 
Theme name not set, setting default value 
Theme changed: "Default" 
15359 cards in 186 sets loaded 
loadCardDatabase(): Path =  "/home/wsky/.local/share/data/Cockatrice/Cockatrice/cards.xml"  Status =  0 
main(): starting main program
SoundEngine: sound not available
main(): SoundEngine constructor finished
main(): MainWindow constructor finished
main(): ui.show() finished
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap

**Comment by wsky0csky** [comment]
Ah, it shows "SoundEngine: sound not available"... but, firefox for instance normally plays sounds.

**Comment by ctrlaltca** [comment]
Yep. I suppose qt is missing a plugin (debian package) un order to play sound. Are you using alsa and/or pulseaudio?

**Comment by wsky0csky** [comment]
Of course I'm using PulseAudio:
wsky      1588  0.0  0.9 367676 10060 ?        S<l  14:42   0:00 /usr/bin/pulseaudio --start
wsky      1620  0.0  0.0   4328   108 ?        S    14:42   0:00 /bin/sh /usr/bin/start-pulseaudio-x11

As i said, it worked before I've updated Cockatrice, also I haven't made any system changes in beteen.

**Comment by ctrlaltca** [comment]
I suppose that https://github.com/ctrlaltca/Cockatrice/commit/0b072e2d60b467b34bf5a0ab05312e82ca8697d2 is the culprit. Probably under qt4 linking against qtmultimedia is still needed.
I think qt5 should work, instead.

**Comment by wsky0csky** [comment]
No idea how to compile it against QT5 on Debian 8.

**Comment by ctrlaltca** [comment]
Don't worry, i'll fix this.

**Comment by wsky0csky** [comment]
Thanks!
It would be perfect if you would say when can i do another pull.

**Comment by Daenyth** [comment]
Is pulse audio installed? Do you have the same issue on qt5?

**Comment by ctrlaltca** [comment]
@Daenyth this is due to QSound being shitty under qt4, since it only supports nas under x11 (an obscure network sound service). I'm reverting to using QAudioOutput, at least it works.

**Comment by ctrlaltca** [comment]
@wsky0csky pull request #1512 should fix your issue. You can wait for it to get merged or try it beforehand.

**Comment by wsky0csky** [comment]
Negative:
Build f2864ce

wsky@deb01silver:~$ cockatrice 
Theme name not set, setting default value 
Theme changed: "Default" 
15359 cards in 186 sets loaded 
loadCardDatabase(): Path =  "/home/wsky/.local/share/data/Cockatrice/Cockatrice/cards.xml"  Status =  0 
main(): starting main program
SoundEngine: sound not available
main(): SoundEngine constructor finished
main(): MainWindow constructor finished
main(): ui.show() finished

**Comment by ctrlaltca** [comment]
#1512 has not been merged yet so, in order to test it, you should run some specific commands (https://help.github.com/articles/checking-out-pull-requests-locally/). Or you can just wait until we'll review the change and merge it.

**Comment by wsky0csky** [comment]
Ok I'll waitm thanks.

**Comment by wsky0csky** [comment]
I've just upgraded, works now.

Cheers

Have in mind that you have to place the sound files in $HOME/.local/share/data/Cockatrice/Cockatrice because it's impossible to manually specify the path.

**Comment by ctrlaltca** [comment]
We could add an "open profile folder" as we already did for cards.. thank you for the reminder.

**Comment by Daenyth** [comment]
Maybe we should make a custom widget class that encapsulates the "set path with button to open folder" behavior?

**Comment by ctrlaltca** [comment]
Or just a single "open user profile" button, then the user can navigate to the specific folder

**Comment by woogerboy21** [comment]
So does this mean all Qt4 clients wont have sound or was it strictly just something with the Qt4 package in that repo?

**Comment by ctrlaltca** [comment]
Sound stopped working due to a recent change. The change has been partially reverted to reenable working sound functionality.

**Comment by Daenyth** [comment]
> Or just a single "open user profile" button, then the user can navigate to the specific folder

Various settings may not share a parent folder. I put my decks folder in dropbox for example

**Comment by ZeldaZach** [comment]
@Daenyth What if we bind the open deck folder and such to the location set in the settings page?

**Comment by Daenyth** [comment]
I'm not sure what you mean

**Comment by ZeldaZach** [comment]
We can use 
<img width="138" alt="screenshot 2015-09-14 16 19 47" src="https://cloud.githubusercontent.com/assets/7460172/9860833/75d85a5a-5afc-11e5-91a9-9c3c96254b5c.png">
to determine locations on the "Open user profile" option.
