### ISSUE TITLE
Add a "Reset all shortcuts to default" button

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#1517]

**Comment by tooomm** [comment]
I would like to see a Link to https://github.com/Cockatrice/Cockatrice/wiki/Custom-Keyboard-Shortcuts as well somewhere in the relating settings page.

Like the link to FAQ for example.

**Comment by Daenyth** [comment]
:+1:

**Comment by ZeldaZach** [comment]
@tooomm I thought I had that link put onto the settings page... blah
