### ISSUE TITLE
Left-click or right-click on life total in Ubuntu triggers multiple loss/gain of life

### ISSUE THREAD

**Issue by catmanjan** [Cockatrice/Cockatrice#1518]
It is intermittent but repeatable, seems to happen more often when moving the mouse, may be a drag trigger?

**Comment by Daenyth** [comment]
I bet it's related to your mouse sensitivity and repeat threshold. Iirc
xset -q? See what it says

**Comment by catmanjan** [comment]
This is a fresh install...

jan@u31sd:~$ xset -q
Keyboard Control:
  auto repeat:  on    key click percent:  0    LED mask:  00000000
  XKB indicators:
    00: Caps Lock:   off    01: Num Lock:    off    02: Scroll Lock: off
    03: Compose:     off    04: Kana:        off    05: Sleep:       off
    06: Suspend:     off    07: Mute:        off    08: Misc:        off
    09: Mail:        off    10: Charging:    off    11: Shift Lock:  off
    12: Group 2:     off    13: Mouse Keys:  off
  auto repeat delay:  500    repeat rate:  33
  auto repeating keys:  00ffffffdffffbbf
                        fadfffefffedffff
                        9fffffffffffffff
                        fff7ffffffffffff
  bell percent:  50    bell pitch:  400    bell duration:  100
Pointer Control:
  acceleration:  2/1    threshold:  4
Screen Saver:
  prefer blanking:  yes    allow exposures:  yes
  timeout:  0    cycle:  0
Colors:
  default colormap:  0x45    BlackPixel:  0x0    WhitePixel:  0xffffff
Font Path:
  /usr/share/fonts/X11/misc,/usr/share/fonts/X11/Type1,built-ins
DPMS (Energy Star):
  Standby: 0    Suspend: 0    Off: 0
  DPMS is Enabled
  Monitor is On

**Comment by Daenyth** [comment]
Weird... I have no clue what might cause this.

**Comment by ZeldaZach** [comment]
Sounds like a mouse issue, not a Cockatrice issue
