### ISSUE TITLE
Issue with 'Open custom sets folder' menu entry

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#1520]
related #1376 & #955

Before you click the `Open custom sets folder` it looks like this:
![custom sets1](https://cloud.githubusercontent.com/assets/9874850/9878357/88fb5bc0-5bc2-11e5-93c0-2bd232372b30.png)

The entry turns into the path on your file system afterwards:
![custom sets](https://cloud.githubusercontent.com/assets/9874850/9878327/609a9d8a-5bc2-11e5-8dd4-59cbd54e6d5c.png)

This is not happening with the `Open custom image folder` menu entry.
The os x code for both entries looks similar, but the win code doesn't...

Win 8.1 / 1ef9041

**Comment by ZeldaZach** [comment]
Does not occur on Mac or Linux

**Comment by ctrlaltca** [comment]
This is due to some debug code that made it into master:
https://github.com/Cockatrice/Cockatrice/blob/f2864ce569fa9c42b024c7225c374d8d1f3a6e49/cockatrice/src/tab_deck_editor.cpp#L834
