### ISSUE TITLE
Clicking in play area causes chat box to lose focus

### ISSUE THREAD

**Issue by Nightfirecat** [Cockatrice/Cockatrice#1529]
Using ead6ab3 on Windows 7 (latest weekly), clicking anywhere in the play area (on game objects or otherwise) causes the room's chat window to lose focus where this behavior did not occur previously.

**Comment by woogerboy21** [comment]
What was the last build you were on?

**Comment by Nightfirecat** [comment]
According to the [last issue I submitted](https://github.com/Cockatrice/Cockatrice/issues/1499) (which I believe to be accurate), 60ed9fd.

**Comment by Nightfirecat** [comment]
To be clear, I've just been using the weekly builds for a while - I haven't been compiling from source. This week was the first one that I noticed the option for Windows XP vs. Win7+ clients.

**Comment by Psithief** [comment]
I can't reproduce this from last week's weekly 59da62d, so it must be new.

Previously, the only way to get the chat input to lose focus was to click the chat history.

**Comment by Psithief** [comment]
I think I found it in 4c6b543.

**Comment by woogerboy21** [comment]
>This week was the first one that I noticed the option for Windows XP vs. Win7+ clients.

The client for XP compared to 7+ has actually been around for a while.  The woogerworks download page simply didnt have the options to get to the WinXP client through its navigation style layout.  It was added to help older OS users up front.  The difference is simply the XP client use QT4 and does not have the servatrice app compiled with it.  The 7+ client uses QT5 and does contain the server side binary.

**Comment by Nightfirecat** [comment]
Ah, that explains why I only noticed it now.
