### ISSUE TITLE
Private message log

### ISSUE THREAD

**Issue by radioactivehazards** [Cockatrice/Cockatrice#1532]
Would there be a Way to make pms Able to read offline? I often will discuss deck building ideas with people in pm but when I go home to build the decks, I cannot view those notes that I discussed earlier. Would we be able to implement a pm log or have the a way to reread previous pms after the box has closed? Also would we be able to see old pms between the same person. For example if I pmed a user about some things and then 3 days later he pmed me back, I would like to have the ability to read the previous pms to not re talk about the same stuff over and over.

**Comment by ZeldaZach** [comment]
This would require multiple changes to how messages are done.

We could store them in a local sqlite database and have them pulled up whenever a private chat is opened. In addition, we could also have it be server dependent. Servers could keep this information for their users.

I'm not the hugest fan of this idea, but I'm curious what others think.

**Comment by radioactivehazards** [comment]
I just do not see the point to the messages if you cannot review them later.

**Comment by woogerboy21** [comment]
With the most recent client changes the PM tabs are not closed on disconnect.  You should be able to copy the content out I believe.

**Comment by ZeldaZach** [comment]
That too ^

**Comment by woogerboy21** [comment]
We could prob add the ability for PMs to save to local files?  Just a thought

**Comment by radioactivehazards** [comment]
When disconnect happens, you get a box "host has lost connection" or what not and when you click that box off all the Tabs close. so the pms are lost to the Nether verse.

**Comment by woogerboy21** [comment]
Your running an old client.  it doesnt do that any longer.

**Comment by radioactivehazards** [comment]
My client is only a month old is there another one?

**Comment by ZeldaZach** [comment]
We update the clients weekly @radioactivehazards

**Comment by radioactivehazards** [comment]
too many updates...you are Scrambling my brain.....Can I get  link please.

**Comment by woogerboy21** [comment]
http://www.woogerworks.com/index.php/client-downloads

Yeah were working on getting a better notification system in place for client updates.

**Comment by radioactivehazards** [comment]
cool thx maybe my problem was already solved :)

**Comment by woogerboy21** [comment]
Well it doesnt store the information so if you close the client or it crashes the chat is lost  but it does save users from disconnects loosing the chat information.

**Comment by radioactivehazards** [comment]
Normally i only close from losing wfi connection

**Comment by radioactivehazards** [comment]
ok i just installed the new update....Can i speak to someone as a feature I had and used allot now appears to be Gone.

**Comment by woogerboy21** [comment]
Looks like you have opened another issue for discussion.  Is it ok to close this issue?

**Comment by radioactivehazards** [comment]
well the other issue has nothing to do with this one and I have not checked to see if this is resolved yet

**Comment by Daenyth** [comment]
Offline PMs could be handled without any change to protocol. This is a reasonable addition.

To be clear, are you talking about persistent chat history or sending pm to offline users?

**Comment by Daenyth** [comment]
Offline PMs could be handled without any change to protocol. This is a reasonable addition.

To be clear, are you talking about persistent chat history or sending pm to offline users?

**Comment by radioactivehazards** [comment]
Both. as I have discussed dick ideas with a user and we literay built a deck Via pm..but after I went offline because i had to go home, all those notes we exchanged were gone. I had to rebuild from scratch.  Also sending offline users pms would be cool but I could see you making so you could only send pms to buddies who are offline, this way users do not troll offline users.

**Comment by Daenyth** [comment]
I think that we can start with local history and then do offline pm later.
They're two separate features

**Comment by isleep2late** [comment]
Sorry, didn't mean to necro this thread, but I brought this up on gitter that having this feature would be great for moderators. So even if it's not something that can be done with regular users, it would at least be good for mods to contact users when they get back online, possibly informing them or updating them on a report they made about another user, etc

**Comment by Daenyth** [comment]
We do want to add this, and for all users. Currently it's waiting for someone to do the work

**Comment by tooomm** [comment]
All issues spoken about here have their own separate issues now.
