### ISSUE TITLE
Newest update Issues

### ISSUE THREAD

**Issue by radioactivehazards** [Cockatrice/Cockatrice#1533]
What happened to the appearance? I had A custom art to my background, my card back, my hand area, my player area and I forget the other area..That all seems gone now.

**Comment by ZeldaZach** [comment]
We've updated how themes are done and have a beginner wiki page up. It will be added to over time.

**Comment by radioactivehazards** [comment]
but you took away the ability to have images?? so now we have to revert to
the ugly backgroundish looks.

**Comment by ZeldaZach** [comment]
Nope, you can add your own custom themes. Read the wiki

**Comment by radioactivehazards** [comment]
where is this wiki?

**Comment by radioactivehazards** [comment]
ok i found the wiki and am reading it...it says to find a custom theme folder...no folder exists well done
