### ISSUE TITLE
Themes are confusing

### ISSUE THREAD

**Issue by radioactivehazards** [Cockatrice/Cockatrice#1534]
I am sorry but this is an Issue no matter how many times you close it.   You had a way for us to set up pictures to view for our hand area, play area, stack, player area, and Card backing. it was very simple and easy.   Now this feature is gone. and you want us to read a whole ton of information and learn ow to program a whole lot of stuff?? Why did you complicate this? It was easy as pie before now its advanced physics.  Please Revert back to the old system. or at least give us a choice. We are not all programming wizards nor have time to learn how to do this stuff. I understand maybe going from advanced to simple but from simple to rocket science?

**Comment by radioactivehazards** [comment]
I read the wiki and i am confused as heck as i am totally lost now, why did you have to make it into an impossible task now? This wiki is not even in English

**Comment by Nightfirecat** [comment]
:-1:

I'm sorry, but I get the impression that you're not really taking the time to understand how the "Themes" feature works.

As you can see [in the Cockatrice resources directory](https://github.com/Cockatrice/Cockatrice/tree/master/cockatrice/resources), there are a number of images and folders. These images define how the application and all of its bits and pieces look. [As described in the "How to create a theme?" section](https://github.com/Cockatrice/Cockatrice/wiki/Themes#how-to-create-a-theme) of the Themes wiki page, all you need to do to replace any of these images is to create a folder in your user profile directory:

* Windows: `c:\Users\<username>\AppData\Local\Cockatrice\Cockatrice\themes`
* Linux: `/home/<username>/.local/share/data/Cockatrice/Cockatrice/themes`
* Mac OSX: `/Users/<username>/Library/Application\ Support/Cockatrice/Cockatrice/themes`

Once you've created this folder, you merely have to put images in it (or in the appropriate sub-folder, according to [how Cockatrice organizes it](https://github.com/Cockatrice/Cockatrice/tree/master/cockatrice/resources) for them to take precedence over the default images. If you're looking to replace a specific image, [you can check the 'long list' of images, which describes nearly every image that's used](https://github.com/Cockatrice/Cockatrice/wiki/Themes#the-long-list-of-all-images).

**Comment by Nightfirecat** [comment]
While this feature is different than it used to be, it provides a comprehensive method through which ***all*** of the application images can be replaced and customized, as well as a method to add further customization using CSS files, if a user has the technical knowledge. This is a drastic improvement over the previous functionality, where only a very small portion of the application could be customized.

**Comment by radioactivehazards** [comment]
none of this makes sense, the older method was Very easy. I would like to understand this but I am not a rocket scientist

**Comment by woogerboy21** [comment]
Prior to the theme configuration there was a very limited amount of configuration that could be done.  Theme's are designed to extend the capabilities of the customization and will be used going forward.

**Comment by radioactivehazards** [comment]
so must i have a folder for each image? i only want the ones I had before.I have the themes folder (had to create it) i have a sub folder (my theme) and in that folder are the images, according to the wiki i need a txt document in some foreign computer langauage

**Comment by woogerboy21** [comment]
Foreign computer language?  The use CSS.  Its been around for a very long time at this point.  If your looking to do basics you should be able to simply copy a theme that exists and change the few components that you wish to change.

**Comment by radioactivehazards** [comment]
You seem to want us, (users) to have Full freedom over how Everything looks. why? you expect us all to be programmers? some of us are not that tech Savy. Nor do we want to be. You teased us with an easy feature and then made it Extremely complicated. I may sound mad here and I kinda am as i have to do a whole lot of work to get back where i was. I updated for 1 feature and lost others.

**Comment by woogerboy21** [comment]
One of the main reasons for theme's is the direction that the application is moving.  There is a push to make the application more game agnostic .  With the previous forms of customization this would not be possible.

**Comment by radioactivehazards** [comment]
I am sorry if I seem mad. but all i see here is I had something nice and simple..now its gone. in order to get it back i have to jump through several hoops. I have the theme folder, i have a folder in there named "my theme" i have now 5 folders in there of the areas that I used to have pics. i have in those folders the images that used to be where they were. yet nothing is working. I have no idea what CSS is nor Do i have time to learn it as I am not into computer programming. I am normally very calm just not fond of having a system set up and then having the rug pulled out from under me. I would greatly prefer someone log into cockatrice and walk me through this as its blasted confusing.

**Comment by Nightfirecat** [comment]
I understand that this change is frustrating to you, but there's really no "programming magic" that you need to do to re-apply your theme. I'll lay it out as simply as I can:

1. Create a folder at the location specified for your operating system. (see my original comment or the wiki page)
2. Put your card back image in this folder, and name it `cardback`.
3. That's it. Your card back should be updated for the next time you run Cockatrice.

*That said*, it looks like a past update may have removed the ability to add background images to the play, hand, and stack areas. @ctrlaltca, would you know anything about that?

**Comment by radioactivehazards** [comment]
I did all of that...it did not work

**Comment by Nightfirecat** [comment]
What operating system are you using, and what does the folder you moved images into look like? The more detail you can provide for troubleshooting, the better assistance we'll be able to provide.

**Comment by radioactivehazards** [comment]
I am on Windows. I created the "Themes" folder. Then i created a folder "My theme" in there. I put all the images in there in there own folders. For example i found the image and i named it "Cardback" and put it in its own folder with the same name. I did this for the following areas.  Cardback, Player info area, Play area, Stack, Hand area. None show up.   On cockatrice go to setting and I see in the themes "My theme" so i got that part right but i select that theme and nothing changes.

**Comment by Nightfirecat** [comment]
Ok, thank you. I'm not going to have access to my Windows computer until later tonight to try to test/assist with this, but I'll look into this once I'm there.

Like I said before, I seem to remember play area image support being removed when background colors were added to the configuration options, so that may need to be re-added. The card backs should definitely be able to work for now though.

**Comment by radioactivehazards** [comment]
Well nightfirecat, It is night where I am at and ill be offline in a few hours 1-2. So can we meet up tomorrow on cockatrice and maybe you "hold my hand". I am sorry but this is very foreign to me and yes i am quite frustrated. i may like this after I understand it but until then I am Captain frustrated and angry at changes.

**Comment by radioactivehazards** [comment]
Ok with some help from a user on cockatrice, Computersarehard I was able to change a few zones, not sure how. the card back is still awful, and so is the Stack. I think the way he did was to rewrite one of ur themes. I rewrote the Fabric theme as pngs and the Stack worked there but nothing else did. Then i tried again with the Velvet marble folder and i rewrote them as Jpgs and all but stack worked. Card back Never worked

**Comment by ctrlaltca** [comment]
@Nightfirecat zones background should end up in the "zones" subdirectory of the theme. I still need to find the time to add that info to the wiki.

**Comment by tooomm** [comment]
Some sort of multiple theme support and managment with add/edit feature to themes and different zones in the settings would be very handy here.

The advanced customizing of all further images and CSS usage could be covered in the wiki.

**Comment by Nightfirecat** [comment]
Interesting, while setting up my demo theme, I noticed that the card back didn't actually update the first time I switched to the theme &mdash; I had to exit Cockatrice, then restart it for that image to be applied. @ctrlaltca this might be a bug?

Anyways, @radioactivehazards, [here is a download for a ~~very crappy~~ sample theme](https://dl.dropboxusercontent.com/u/32033415/sanic-theme.zip) that modifies all of the images you mentioned (card back, player zone, stack zone, hand zone, table zone). [(sample image of crappy theme)](https://i.imgur.com/z9aag7i.png)

Below are screenshots of my folders and images within the folders for this theme. You should try to make your folder structure look the same to achieve the same effect.

![sanic theme base directory](http://i.imgur.com/KuL186Y.png)  
![sanic theme zones directory](http://i.imgur.com/PkStSu0.png)

**Comment by Daenyth** [comment]
This ties back to where I was saying we should provide a complete clone of the default theme with all images in place for people to modify.

@radioactivehazards the wiki page was just added within this week, it'll become more polished as time goes on.

**Comment by Daenyth** [comment]
@radioactivehazards please see my suggestion in #1539 - would that address your concerns?

**Comment by radioactivehazards** [comment]
Yes with help from Computersarehard I was able to set up my original theme
except for Card back

**Comment by Nightfirecat** [comment]
@radioactivehazards Have you tried following my latest comment? I was able to modify all of the images you described, including card back.

**Comment by radioactivehazards** [comment]
Yes and no as the back did change but it only took up half the card. I
think its a sizing issue though
