### ISSUE TITLE
Better use of wasted space in deck editor card list

### ISSUE THREAD

**Issue by Psithief** [Cockatrice/Cockatrice#1535]
The reason I suggest a change is because each time I open the deck editor, the Card type column is not wide enough to show subtypes. Yet the P/T column is at the end and takes up half the list space.

I would like to make better use of the highlighted area in the image below.
![wastespace](https://cloud.githubusercontent.com/assets/1124846/9974637/d4715b66-5ecb-11e5-8865-2adb4cee7642.png)

Having the deck editor remember the minimum width of a column or the order of the columns would be nice.

Version 59da62d

**Comment by ZeldaZach** [comment]
cc @marcofernandezheras

**Comment by tooomm** [comment]
:+1: :+1: :+1:

**Comment by ZeldaZach** [comment]
You can resize the columns now to avoid this issue
