### ISSUE TITLE
Phase descriptions based on game

### ISSUE THREAD

**Issue by woogerboy21** [Cockatrice/Cockatrice#1538]
How difficult would it be to update the client so that the phase names are generic (like phaseone,phasetwo ... whatver) and then allow the definition of the phase to be applied in the theme so that when the phase change occur's and the chat box is populated with the phase name its linked to the theme's definition and not hard set into the clients code?

**Comment by woogerboy21** [comment]
@ctrlaltca

**Comment by Daenyth** [comment]
For translation to happen the string must be hard coded into the source.

**Comment by woogerboy21** [comment]
>For translation to happen the string must be hard coded into the source.

I thought phase change comments were are they not?  So when a user goes from phase combat to phase damage the client adds a line in the chat window of the game tab that says so.

**Comment by woogerboy21** [comment]
Looks like the names are hard set and passed in here:
https://github.com/Cockatrice/Cockatrice/blob/master/cockatrice/src/phasestoolbar.cpp#L110

**Comment by tooomm** [comment]
>Im not referring to translatable in the since of spoken language. im referring to translatable between different games. So MtG may have a phase named "combat" but another game might call it "battle". 

This should be linked to https://github.com/Cockatrice/Cockatrice/issues/1740

**Comment by ebbit1q** [comment]
tracked in #1740
