### ISSUE TITLE
Theme gui editor

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#1539]
See #1534 

Settings should have a "Create theme" button. When clicked it should create a new directory inside the user themes folder and populate it with the default theme images. Then it can open the directory, and the user can replace images in there with the new ones they want. This should simplify theme setup greatly.

cc @ctrlaltca 

---

Upon creating a new theme, it should load you into a theme editor. The editor should have tabbed views for each subdirectory in the theme. Each image should have a "load from disk" button. The load button should present the user a file explorer, and when a file is selected, cockatrice should copy the selected file and overwrite the new theme's matching file.

**Comment by tooomm** [comment]
Could this go hand in hand with a complete theme management integration in the settings with its own sub page `Themes` or `Customization`?
https://github.com/Cockatrice/Cockatrice/issues/1534#issuecomment-141654206

But maybe your suggested `Create Theme` button, a `Open Theme folder` button and a dropdown menu for theme selection in the settings is sufficient.

The newly created theme could also include a linked how-to file to our wiki.

**Comment by Daenyth** [comment]
Those are all good suggestions

**Comment by radioactivehazards** [comment]
personally the wiki is horrid and does not help at all with this.

**Comment by Daenyth** [comment]
@radioactivehazards if you have specific examples of ways that it's bad we can act on those. Saying that it's bad without any detail doesn't help us make it better.

**Comment by zebington** [comment]
I'm currently working on this.

**Comment by Daenyth** [comment]
Awesome!

**Comment by ZeldaZach** [comment]
I don't think we're gonna be supporting a custom editor, but we have details in the works to improve theming
