### ISSUE TITLE
Cards database > Edit sets... BUG : cards images won't get downloaded according to sets order

### ISSUE THREAD

**Issue by gil01280** [Cockatrice/Cockatrice#1543]
Since last update, i cannot get the program to download cards images according to the order i setup in Cards database > Edit sets...
I used to have it working properly until 2 days ago and last update.
Even though my sets are sorted by date , i keep getting random arts for cards, and not the oldest one each time, which is weird and new.
I did fresh install on win7 64, and never had such problem before with previous versions of cocka.
I uploaded screenshot to show you guys the problem (in this case, having new KTK fetches art instead of ONSLAUGHT ones), and i hope a quick fix.
I did try to manually put ONSLAUGHT on top of the list, and in this case i had correct picture for my strand. But if i have to do this for each card which had reprints, there is a problem. Also, it was working perfectly with previous versions : i would just sort sets by date, click ok and get images in chronological order for every one and each card i clicked after this.
I also tried Reset/clear downloaded pictures button before saving new database, still was not getting proper images.
![untitled](https://cloud.githubusercontent.com/assets/14471982/9983660/281a9ce8-6005-11e5-9b6e-0dec557a0ffe.jpg)

**Comment by woogerboy21** [comment]
FYI for the others that are more familiar with the card database and downloading.  This is the results I get from a debug run trying to reproduce:

```
Trying to load picture (set:  "pJGP"  card:  "Flooded Strand" )
Picture NOT found, trying to download (set:  "pJGP"  card:  "Flooded Strand" )
Trying to load picture (set:  "pJGP"  card:  "Flooded Strand" )
Picture NOT found, trying to download (set:  "pJGP"  card:  "Flooded Strand" )
Trying to load picture (set:  "pJGP"  card:  "Flooded Strand" )
Picture NOT found, trying to download (set:  "pJGP"  card:  "Flooded Strand" )
starting picture download: "Flooded Strand" Url:  QUrl( "http://gatherer.wizards.com/Handlers/Image.ashx?name=Flooded Strand&type=card" ) 
starting picture download: "Flooded Strand" Url:  QUrl( "http://gatherer.wizards.com/Handlers/Image.ashx?name=Flooded Strand&type=card" ) 
starting picture download: "Flooded Strand" Url:  QUrl( "http://gatherer.wizards.com/Handlers/Image.ashx?name=Flooded Strand&type=card" )
```

Does the downloader even understand how to pull the correct set picture from the LQ sources?

**Comment by Psithief** [comment]
@gil01280 Uncheck all the promo sets. They are at fault and can't be displayed anyway.

---

@woogerboy21 Here's the problem: 
1. Flooded Strand was printed in Onslaught, Khans of Tarkir, and as a Judge promo.
2. Despite being printed as a promo after Onslaught, the date of the promo set is from the first promo ever: `1998-06-01`. This is well before Onslaught's release date.
3. If the downloader doesn't have a multiverse ID to work with, it will just download by card name.

This is incorrect behaviour. Cards without a multiverse ID should always be downloaded at a lower priority than cards that have one.

Additionally, I suggest all those promo sets should be unchecked by default.

Card entry for reference:
```xml
<card>
    <name>Flooded Strand</name>
    <set muId="0">pJGP</set>
    <set muId="386537">KTK</set>
    <set muId="39503">ONS</set>
    <manacost></manacost>
    <cmc>0</cmc>
    <type>Land</type>
    <tablerow>0</tablerow>
    <text>{T}, Pay 1 life, Sacrifice Flooded Strand: Search your library for a Plains or Island card and put it onto the battlefield. Then shuffle your library.</text>
</card>
```

**Comment by Psithief** [comment]
**too long; didn't read:**
Why do we still import promo sets now that mtgimage.com is gone? It only causes problems and we should stop doing it.

**Comment by woogerboy21** [comment]
Oh cool :+1:

**Comment by Daenyth** [comment]
Some cards are only in promo, like mana crypt

**Comment by gil01280** [comment]
Hello there, so i tried disabling all promo sets, then i ordered my sets by date like i always did, and still i CANNOT have old images over the new ones.
This problem is new and i believe is linked to the new update because prior to that, i had all sets checked and never encountered this problem, program was able to fetch images according to my set list...
I cleared all images before. Thing is, i also have BFZ basic lands, even with BFZ unticked in my list...
I can swear it was working perfectly before update and it was a welcomed change, because with older versions i had to get a file on forums to have my sets sorted...
![asdasd](https://cloud.githubusercontent.com/assets/14471982/9990515/597f54ec-6062-11e5-9e97-92acc3190a51.jpg)

**Comment by Daenyth** [comment]
What version did you update from? Did it not have the sorting built in?

**Comment by woogerboy21** [comment]
When I do as @Psithief suggested I am getting the older card images as expected.  I can't reproduce the issue after promo sets are disabled.  I will say though, it would be nice to have a "Disable Promo" button along with "disable all sets".

**Comment by woogerboy21** [comment]
@gil01280 
Have you tried to reset/clear your downloaded card images just to make sure things are sane?

**Comment by gil01280** [comment]
I updated from a version that didnt have the custom sets, cant remember which but it was working the old way for skins for example. It did have the built in sort feature , and it was working flawlessly till new update. I did fresh install, deleted folders in program files and appdata, cleared image cache in settings. I have new arts even though its sorted by date , with promos sets disabled. I have old art for swords to plowshares, but new art for fetches, sword of fire and ice or meddling mage for example. I just had my brother reproduce the bug on its fresh updated version of cocka : he has new fetches from KTK...

**Comment by gil01280** [comment]
Ok so after toyin around with all options, i achieved my goal. Here's how i solved the problem : 
- first i deleted manually cards.xml, then launched oracle from desktop and updated cards and tokens xmls
- went to settings and deleted all images
- went to card database > edit sets and disabled all promo sets, then ordered by date, then  put BFZ at the end and then i saved
for now i have images in chronological order, but i never had to do all those steps before the update, so i maintain there is something odd here
before that i just had to click date and ok :)
thanks for replies anyway and keep up the good work with cocka !

**Comment by Daenyth** [comment]
I think the bug here is that we're not doing fallback order correctly.

**Comment by Daenyth** [comment]
dupe #1984
