### ISSUE TITLE
Disable promo sets by default.

### ISSUE THREAD

**Issue by Psithief** [Cockatrice/Cockatrice#1545]
Cards without multiverse IDs should not be available to download by default. 
mtgimage.com is not coming back. 

Please change Cockatrice so promo sets are not enabled by default. Ideally they should not even be imported because promo sets are just a setting to the application that will **secretly break things** with no explanation to the user.

Fixing this prevents new users reporting issues like #1543.

Unfortunately, it's not as simple as just disabling `set type promo` there are more dodgy sets in the data, but it's a good start.

**Comment by Psithief** [comment]
You'll also need to change this:

> Hi! It seems like you're running this version of Cockatrice for the first time. **All the sets in the card database have been enabled.** Read more about changing the set order or disabling specific sets and consequent effects in the "Edit Sets" window.

:unamused:

**Comment by Daenyth** [comment]
The problem isn't that they're enabled the problem is that we don't
correctly fall back to the next lowest set.

**Comment by Psithief** [comment]
Closing in favour of #1554.
