### ISSUE TITLE
compiled with cmake's flag -DUPDATE_TRANSLATIONS=1 but I only have english language available

### ISSUE THREAD

**Issue by shackra** [Cockatrice/Cockatrice#1549]
As the title says, I compiled with the following command:

```
cd build
cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -DWITH_SERVER=0 -DWITH_CLIENT=1 -DWITH_ORACLE=1 -DUPDATE_TRANSLATIONS=1 ..
make
make install
```

And I find out I have only one language available, english, how am I supposed to get the Spanish translation for `oracle` and `cockatrice`?

This is the content of the package I built for my system:

```
cockatrice-client /usr/
cockatrice-client /usr/bin/
cockatrice-client /usr/bin/cockatrice
cockatrice-client /usr/bin/oracle
cockatrice-client /usr/share/
cockatrice-client /usr/share/applications/
cockatrice-client /usr/share/applications/cockatrice.desktop
cockatrice-client /usr/share/applications/oracle.desktop
cockatrice-client /usr/share/cockatrice/
cockatrice-client /usr/share/cockatrice/sounds/
cockatrice-client /usr/share/cockatrice/sounds/attack.raw
cockatrice-client /usr/share/cockatrice/sounds/end_step.raw
cockatrice-client /usr/share/cockatrice/sounds/player_joined.raw
cockatrice-client /usr/share/cockatrice/sounds/start_combat.raw
cockatrice-client /usr/share/cockatrice/sounds/tap.raw
cockatrice-client /usr/share/cockatrice/translations/
cockatrice-client /usr/share/cockatrice/translations/cockatrice_en.qm
cockatrice-client /usr/share/cockatrice/zonebg/
cockatrice-client /usr/share/cockatrice/zonebg/VelvetMarble_HorizontalHand_Hand.jpg
cockatrice-client /usr/share/cockatrice/zonebg/VelvetMarble_HorizontalHand_Player.jpg
cockatrice-client /usr/share/cockatrice/zonebg/VelvetMarble_Stack.jpg
cockatrice-client /usr/share/cockatrice/zonebg/VelvetMarble_Table.jpg
cockatrice-client /usr/share/cockatrice/zonebg/VelvetMarble_VerticalHand_Hand.jpg
cockatrice-client /usr/share/cockatrice/zonebg/VelvetMarble_VerticalHand_Player.jpg
cockatrice-client /usr/share/cockatrice/zonebg/fabric_blue.png
cockatrice-client /usr/share/cockatrice/zonebg/fabric_gray.png
cockatrice-client /usr/share/cockatrice/zonebg/fabric_green.png
cockatrice-client /usr/share/cockatrice/zonebg/fabric_red.png
cockatrice-client /usr/share/cockatrice/zonebg/leather_blue.png
cockatrice-client /usr/share/cockatrice/zonebg/leather_gray.png
cockatrice-client /usr/share/cockatrice/zonebg/leather_green.png
cockatrice-client /usr/share/cockatrice/zonebg/leather_red.png
cockatrice-client /usr/share/cockatrice/zonebg/plasma_blue.png
cockatrice-client /usr/share/cockatrice/zonebg/plasma_gray.png
cockatrice-client /usr/share/cockatrice/zonebg/plasma_green.png
cockatrice-client /usr/share/cockatrice/zonebg/plasma_red.png
cockatrice-client /usr/share/icons/
cockatrice-client /usr/share/icons/hicolor/
cockatrice-client /usr/share/icons/hicolor/48x48/
cockatrice-client /usr/share/icons/hicolor/48x48/apps/
cockatrice-client /usr/share/icons/hicolor/48x48/apps/cockatrice.png
cockatrice-client /usr/share/icons/hicolor/48x48/apps/oracle.png
cockatrice-client /usr/share/icons/hicolor/scalable/
cockatrice-client /usr/share/icons/hicolor/scalable/apps/
cockatrice-client /usr/share/icons/hicolor/scalable/apps/cockatrice.svg
cockatrice-client /usr/share/icons/hicolor/scalable/apps/oracle.svg
cockatrice-client /usr/share/oracle/
cockatrice-client /usr/share/oracle/translations/
cockatrice-client /usr/share/oracle/translations/oracle_en.qm
```

**Comment by ctrlaltca** [comment]
You don't need to enable the -DUPDATE_TRANSLATIONS=1 option order to get translations; this option is something internally used by developers only when they make some change to the code.

**Comment by Daenyth** [comment]
Translations should be available when launching after make install

**Comment by tooomm** [comment]
After starting cockatrice you should be able to adjust the displayed language in `Settings --> General`.

If you want to contribute to translations, and help us to finish Spanish for example you can do so [here](https://www.transifex.com/cockatrice/cockatrice/). It's pretty simple and highly appreciated! :+1: 
We provide further information in the [Translation FAQ](https://github.com/Cockatrice/Cockatrice/wiki/Translation-FAQ).

**Comment by shackra** [comment]
But that's my point, I only have English available...

Why `make install` isn't doing what's supposed to do? how can I give debug
information on this issue?

> El 22 de septiembre de 2015 a las 5:29 tooomm <notifications@github.com>
> escribió:
> 
> 
> After starting cockatrice you should be able to adjust the displayed language
> in `Settings --> General`.
> 
> If you want to contribute to translations, and help us to finish Spanish for
> example you can do so
> [here](https://www.transifex.com/cockatrice/cockatrice/). It's pretty simple
> and highly appreciated! :+1: 
> We provide further information in the [Translation
> FAQ](https://github.com/Cockatrice/Cockatrice/wiki/Translation-FAQ).
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/Cockatrice/Cockatrice/issues/1549#issuecomment-142259639

--
Pax et bonum.
Jorge Araya Navarro.
ES: Diseñador Publicitario, Programador Python y colaborador en Parabola
GNU/Linux-libre
EN: Ads Designer, Python programmer and contributor Parabola GNU/Linux-libre
EO: Anonco grafikisto, Pitino programalingvo programisto kai kontribuanto en
Parabola GNU/Linux-libre
https://es.gravatar.com/shackra

**Comment by ctrlaltca** [comment]
Please attach the output of cmake, make and make install steps.

**Comment by shackra** [comment]
The issue resolved by itself after removing the flag -DUPDATE_TRANSLATIONS=1

**Comment by Daenyth** [comment]
I think I know what happened. By running with update turned on, when your setup couldn't find the translation tools, it excluded the translation files from the build. Maybe. We'd have to have the full log to say.
