### ISSUE TITLE
any user can click pass regardless of turn

### ISSUE THREAD

**Issue by ashak** [Cockatrice/Cockatrice#1551]
Hi,

I just built the latest cockatrice on Debian Jessie. I started servatrice with no config. I connected two (different named) users to the server on localhost. I started a game with one of them, I joined the game with the other user. I loaded a different deck for each of them. I then clicked pass... and again... and again... as one of the users and it just continually changed the turn of the user, despite it always being the same user that's passing.

That seems a bit broken to me :)

**Comment by Daenyth** [comment]
This is by design. We don't enforce any specific workflow or rules.
