### ISSUE TITLE
Deck editor crashes when viewing lots of cards in a row

### ISSUE THREAD

**Issue by alvaro-cuesta** [Cockatrice/Cockatrice#1552]
**Reproducing:** Focus the card list in the deck editor (left pane) and hold down up/down cursor keys to visit a lot of cards in a row. At some point card images stop being shown and, a few seconds later, Cockatrice crashes.

**Build:** Windows 7 x64 ead6ab3

**Comment by Daenyth** [comment]
I don't suppose it offers you any debugging info or stack traces?

We can look into this.

**Comment by alvaro-cuesta** [comment]
Just a plain old Windows crash. The only detail I get is it's an unhandled exception. Can I turn debug logging somehow? I can't seem to find a log file anywhere and running Cockatrice from the command-line doesn't seem to log either.

**Comment by Daenyth** [comment]
I haven't been able to figure out how to preserve the log output on windows, unfortunately. You can probably run it through a debugger if you set up a full developer environment, but that's a pain in the ass on windows.

Regardless, this probably gives enough info to go on.

What's your image cache size setting, and how much memory does your computer have?

**Comment by ctrlaltca** [comment]
> What's your image cache size setting, and how much memory does your computer have?

I think you nailed it. I'd try lowering the image cache setting size and see if this avoids the crash.

**Comment by Daenyth** [comment]
If it's image cache issues we should do something other than crash...

**Comment by woogerboy21** [comment]
Maybe a check on startup to make sure there is that much memory before allowing the client to try and use the amount would be something at the very least?

**Comment by Daenyth** [comment]
I thought we did that. But I'll have to look into it

**Comment by ctrlaltca** [comment]
Qt offers no way to get that info. Workarounds exists: http://stackoverflow.com/questions/8122277/getting-memory-information-with-qt

**Comment by Daenyth** [comment]
@ctrlaltca do we actually `malloc` anywhere though? I think we just instantiate objects typically.

**Comment by ctrlaltca** [comment]
You are right, mine was just a bad example.

**Comment by Daenyth** [comment]
@alvaro-cuesta Does a more recent version also have this problem for you? Please reopen this issue if so.
