### ISSUE TITLE
Crash when loading cards.xml with outdated version number

### ISSUE THREAD

**Issue by Desruprot** [Cockatrice/Cockatrice#1553]
https://drive.google.com/file/d/0B8XgYkguCQ0nczlIOGJzQ1otXzA/view?usp=sharing

is the custom set file, that cockatrice is not working with. I had a topic on reddit and this is the follow up.

Cockatrice crashes (I do get an error I think). It as not completely seeing the image method for me (this is a set attempted to be ported from MSE2.

**Comment by Daenyth** [comment]
What OS are you, and what build of cockatrice (From the about/help menu)

Does the crash produce any detail messages? When does the crash happen?

**Comment by Desruprot** [comment]
Windows 7, I am using the latest build, no messages were shown, the crash happens shortly after opening (it shows up as a process then immediately terminates). I'm using the 09/17/2015 build. Either method (the card pictures using the CUSTOM folder dont appear so I can enable them in the set area).

**Comment by Daenyth** [comment]
Can you post the build info from the about menu? It will have a random-looking sequence of letters.

Did it work in the past and break in this version, or is this the first time you've tried it?

**Comment by ZeldaZach** [comment]
So I looked through the file and figured out the issue:
FFV.xml:2 `<cockatrice_carddatabase version='2'>`

This should be set to **version 3**. Version 2 is no longer supported and causes the client to crash with the following:
```
loadFromFile(): Version too old:  2
loadCardDatabase(): Path =  "/Users/zeldazach/Library/Application Support/Cockatrice/Cockatrice/customsets/FFV.xml"  Status =  1
main(): invalid settings or load status
```

**Comment by ctrlaltca** [comment]
Just fix the header of your file, from:
```
<?xml version='1.0' encoding='UTF-8'?>
<cockatrice_carddatabase version='2'>
```
to:
```
<?xml version="1.0" encoding="UTF-8"?>
<cockatrice_carddatabase version="3">
```

The crash is partially unrelated, and due to the settings dialog appearing before the sound engine object is created.

**Comment by Daenyth** [comment]
We shouldn't crash on old-version files. When did that happen?
