### ISSUE TITLE
[Expeditions] Creating improperly named tokens crashes the client

### ISSUE THREAD

**Issue by Imponaut** [Cockatrice/Cockatrice#1560]
Boardstate does not appear to matter. Issue is 100% consistent, using latest (Expeditions) build and running Windows 7, Creating a token with a name that is not the same as a known card immediately crashes the client, and appears to crash the client for anyone else joined or spectating the match. Issue also presents offline.

**Comment by ZeldaZach** [comment]
I reverted the PR that caused this issue. If you can build your own client from master, you're free to. If not, updated clients will be available tomorrow.

**Comment by Daenyth** [comment]
Updated clients are out now.
