### ISSUE TITLE
Proposal: PRs need two signoffs before merge

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#1562]
I propose that new PRs need :shipit: from two people other than the author before merge, given after the most recent commit. If the PR is security related or a fix for a severe crash, then it doesn't require any signoff and is instead merged at the author or first reviewer's discretion.

If the author has merge rights, they should merge it themselves.

If the author doesn't have merge rights, anyone on the project should feel free to merge it.

Person doing the merge should update the changelog. (For now; later I'd like to get changelogs auto-generated for the most part).

@Cockatrice/developers please :+1: or :-1: and leave comments.

**Comment by poixen** [comment]
Love this idea. Though it can sometimes slow down prs as not everyone checks the prs. Pros and cons.

**Comment by ctrlaltca** [comment]
I agree with this; i'd just province an exception for security PRs and hard crashes, especially if they're trivial patches (like oneliners).

**Comment by Daenyth** [comment]
> I agree with this; i'd just province an exception for security PRs and hard crashes, especially if they're trivial patches (like oneliners).

Good point, I'll say that security and crash fixes get merged at author/reviewer's discretion.

**Comment by woogerboy21** [comment]
Ill throw my $0.02 in here and mention that something like this sounds great, but with volunteered time things could potentially stay out for a very long time.  But even with that Im willing to try it with the understanding that it can always be changed in the future.  Obviously there is something that needs changed and with out finding out what it would be like any other way we will never know what way works best.

**Comment by ZeldaZach** [comment]
I'm fine with trying this out. The only real issue is when things sit open for long period of time (4+ days) without any interactions

**Comment by Daenyth** [comment]
Given the nature of recent support requests and general community response, I'm also going to add that new client/server features (as in ones listed in `featureset.cpp`) must be tested for at least 2 weeks prior to merge and public release.

Let's go with this strategy for now.
