### ISSUE TITLE
Theme documentation doesn't make clear that you should not modify Program Files/Themes

### ISSUE THREAD

**Issue by radioactivehazards** [Cockatrice/Cockatrice#1565]
Yeah the title explains it all. I finally fixed those annoying themes. and upgraded to the newer client. I made a back up of the themes just in case.  When i started the new client they were wiped. so i copied the back-up. that changed NOTHING. so i made a new folder in there and moved the images into that in the same places.. NOTHING. so i went into that fold into the "Fabric" and changed all the pictures...NOTHING. did it to plasma changing all the files to png, and jpg formats. Still nothing. the only thing I got to work was the card back and then that also died and now its not even the Default anymore its just a white Space,  So I am very frustrated. Please explain why you went from simple to Rocket Science.

**Comment by Daenyth** [comment]
Where did you store your custom theme? Inside your user's appdata directory, or program files? Program files theme folders aren't intended to be modified.

If the installer deleted your appdata themes directory, that's a severe bug.

**Comment by Daenyth** [comment]
cc @ctrlaltca

**Comment by radioactivehazards** [comment]
in the program area,

**Comment by woogerboy21** [comment]
@Daenyth and this is why i wouldnt remove any theme folder :smile:

**Comment by radioactivehazards** [comment]
I had them in the area marked "Velvetmarble" and they are there but they no longer work. i deleted them all and put what I had before back in there and it still did not work. I am convinced the themes are just broken.

**Comment by Daenyth** [comment]
That's why then - you shouldn't be touching anything inside program files.

We need better documentation for this. Sorry you're hitting so many rough edges.

@woogerboy21 if we don't do that, we can never update any bundled themes, only create new ones. AFAIK it only removes the default bundled ones, and any new theme directories inside there shouldn't be touched, even though it's program files.

**Comment by radioactivehazards** [comment]
well i was told that i had to tamper with the program files to fix them in the 1st place.

**Comment by Daenyth** [comment]
related: #1534 and #1539

**Comment by radioactivehazards** [comment]
how about a better fix...revert back to old way of handling themes

**Comment by Daenyth** [comment]
The wiki section on [How to create a new theme](https://github.com/Cockatrice/Cockatrice/wiki/Themes#how-to-create-a-theme) tells you to use your user folders, and right above that there's a link to the paths for it.

I'll work on the wiki page to make the instructions more clear.

**Comment by Daenyth** [comment]
Rather than reverting we should be making changes so that the new theme system is as easy to configure as the old one was.

I think I'll expand the proposal in #1539 to include a full theme editor gui that will let you select individual images the same way the old one did.

**Comment by radioactivehazards** [comment]
thankyou, because i read that wiki 4 times. i have no idea what a cascading style sheet file is nor how to create one. I read that are also 4-5 times and my head is now hurting and i need some Aspirin.

**Comment by radioactivehazards** [comment]
Lmk When you finish that set up.

**Comment by Daenyth** [comment]
You don't need to create a css file, it's strictly for advanced users to do extreme customizations. If you just want to change images you replace the existing file with a new file.

**Comment by Daenyth** [comment]
I've just made changes, please let me know what you think. Feedback on areas which are confusing is especially helpful.

**Comment by radioactivehazards** [comment]
tried that...it did not work

**Comment by radioactivehazards** [comment]
must I reinstall for the changes?

**Comment by radioactivehazards** [comment]
ok I reinstalled...where are these changes?

**Comment by Daenyth** [comment]
I don't quite understand what you're asking.

Once you've created a user theme folder, it should show up as one you can select from settings.

**Comment by radioactivehazards** [comment]
i assumed you put the changes in "cocka, settings" but then i tried to make my own folder in the app area and that Did work partially, the card back is still not working its back on default. I used a different theme than my usual so i have to change the images over but They did change from You're defaults so we are moving up in direction

**Comment by radioactivehazards** [comment]
ok, I cannot seem to change the pictures, as i have moved new ones into the folder but it still uses the ones from the theme I downloaded. here is what I have:
![image](https://cloud.githubusercontent.com/assets/13910327/10048814/b1c579e8-61e2-11e5-87c2-632a65355d02.png)

I am attempting to change them to other images on my machine. i renamed the images with same exact names and moved them into the fold but it still comes up with those images i showed.

**Comment by Daenyth** [comment]
Try restarting the app after changing the files?

**Comment by radioactivehazards** [comment]
I tried that....the image i tried to change went blank, then i found a youtube Video for themes and am following that so ill let you know what happens

**Comment by radioactivehazards** [comment]
The Videon was dated and used the old simple method so yeah it did nothing. I tried to change the "player area" image and when i restarted the client with "my image" in place i was presented with this:
![image](https://cloud.githubusercontent.com/assets/13910327/10049303/eddb32a4-61e4-11e5-8473-827f9d79d6e0.png)

I mistakenly  deleted the original image I had there, but yes now its blank

**Comment by Daenyth** [comment]
cc @ctrlaltca on that. 

It's supposed to fall back to default theme I believe.

**Comment by radioactivehazards** [comment]
ok I went into the program area again... and all looks fixed. i had to move each file 1 by 1 and rename them correctly. I have the wrong image for card back but i am pretty sure I can fix it now it works fine

**Comment by Daenyth** [comment]
Excellent.

We'll keep working on the documentation and configuration.

**Comment by ZeldaZach** [comment]
I have time today, so I'll look into rewriting the docs

**Comment by radioactivehazards** [comment]
Thankyou very much. its not too hard once you get your hand held some and I
am showing anyone who asks on cocka now
