### ISSUE TITLE
Can't set card back image in theme

### ISSUE THREAD

**Issue by MrAAA264** [Cockatrice/Cockatrice#1567]
So in the new update the setting for adding custom artwork, front and back side of the card have remove, is there another way to add custom artwork?

**Comment by Nightfirecat** [comment]
See the comment threads for #1534 and #1565 for some information, and try reading [the Wiki page on Themes](https://github.com/Cockatrice/Cockatrice/wiki/Themes) for more information

**Comment by MrAAA264** [comment]
i just found out the problem, i opened the Card Database>Open Custom Image Folder. which i dragged all the my saved images to this folder

**Comment by Daenyth** [comment]
Is this about custom card images or custom pictures inside the app, like the game play background?

**Comment by MrAAA264** [comment]
i still havnt found a way to change the art of the back of the card

**Comment by MrAAA264** [comment]
@Daenyth the custom card images

**Comment by Daenyth** [comment]
Card back and custom card images are different things. The first one is part of a theme, the card images are done separately.

**Comment by MrAAA264** [comment]
the only thing on the Theme tab, is the changing and of the background. On that note, how can i set the background to a custom art work?

**Comment by ZeldaZach** [comment]
You can check the themes wiki. I added a [tree log](https://gist.github.com/ZeldaZach/68c4f5e7db06efb45729) which shows where everything goes. If you'd like to change the card back, I highly recommend you use a svg file, but you simply add `cardback.svg` to your theme folder in the appropriate location (as seen in the tree log) :)

**Comment by MrAAA264** [comment]
where is the Theme folder i cant find it?

**Comment by ZeldaZach** [comment]
https://github.com/Cockatrice/Cockatrice/wiki/Themes#what-is-a-theme

**Comment by MrAAA264** [comment]
i made the Theme Folder, and it still didnt work

**Comment by MrAAA264** [comment]
i made the folder and it didnt work

**Comment by MrAAA264** [comment]
Is it possible that you guys can make a youtube video explaining this?

**Comment by Daenyth** [comment]
That would be helpful

**Comment by MrAAA264** [comment]
So i just found out that the card database set order doesn't work, i have the Media Insert set on the very top of the set order and it isnt working

**Comment by MrAAA264** [comment]
http://imgur.com/wBwCbh6   here is my example

**Comment by ZeldaZach** [comment]
What source are you trying to download cards from? It's possible they don't have some of these promo sets and they are therefore skipped over.

**Comment by MrAAA264** [comment]
its being downloaded form mtgjson.com

**Comment by ZeldaZach** [comment]
MTGJSON provides the database, I'm asking where you get the physical images from. Gatherer? Another source?

**Comment by MrAAA264** [comment]
i wouldn't know, it coming form Oracle

**Comment by ZeldaZach** [comment]
Based on how you're uncertain, I'm assuming you're downloading from gatherer. (Which is the default. You can check on this in your settings.) Gatherer does not have most of the promos for the sets, so when the client tries to download them, it fails and goes on to the next set in the list until it hits something that is valid.

**Comment by MrAAA264** [comment]
ah, yes its coming form gatherer, is there another source i can use?

**Comment by ZeldaZach** [comment]
I'm not certain of any other sources at this time, but if you find any you're free to try them out. We have a guide on the Wiki for how to make them work. I'm assuming this issue is resolved as of now, but you're free to open it again if you feel the need to. :)
