### ISSUE TITLE
Socket error: Unknown error

### ISSUE THREAD

**Issue by Scuta04** [Cockatrice/Cockatrice#1568]
I have installed latest update of expeditions and still get the message "socket error: Unknown error" when I try to connect to the server.. any suggestions?

**Comment by ZeldaZach** [comment]
What OS are you on?

**Comment by Scuta04** [comment]
Windows 7

**Comment by Daenyth** [comment]
Screenshot?

**Comment by Scuta04** [comment]
http://imgur.com/xwtZO5w

**Comment by Scuta04** [comment]
I have tried the newest update, an older version, as well as what prompted me attempt an update: "login error: -1".  Upgrade turned that to the socket error but still cannot connect to any server.

**Comment by Bigdogdch** [comment]
I am having the same issues.  Have the same OS windows 7
Please advise
Thanks

**Comment by catmanjan** [comment]
just did a fresh install and noticed that the port number doesn't autopopulate to 4747 - may be related

**Comment by Scuta04** [comment]
Yes my port was blank, thanks!

**Comment by Bigdogdch** [comment]
Mine is not.  When it comes up, the Port is already defaulted to 4747
I have tried using both hosts, cockatrice.woogerworks.com and 198.199.69.27

**Comment by woogerboy21** [comment]
What is 198.199.69.27?

**Comment by Bigdogdch** [comment]
I don't know.  An IP address?  The last time this same situation happened I was told to use this as the host address until the issue was resolved

**Comment by woogerboy21** [comment]
The IP address of the cockatrice.woogerworks.com server currently is 158.69.223.150
This changes as the server grows and is moved to new providers/hardware.

**Comment by Bigdogdch** [comment]
when cockatrice come up it already has the host of cockatrice.woogerworks.com with a port of 4747
