### ISSUE TITLE
CLient crash - cockatrice

### ISSUE THREAD

**Issue by HUngasaur** [Cockatrice/Cockatrice#1570]
Hi experiencing an odd crash every time i start a game.
can load it up and as people join its fine.. but once everyone  hits ready,
 client crashes and despite multiple log ins.. i cannot re connect tot he server without the client instantly crashing.
until that game has been abandoned.

problem details
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	cockatrice.exe
  Application Version:	0.0.0.0
  Application Timestamp:	5602407f
  Fault Module Name:	cockatrice.exe
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	5602407f
  Exception Code:	c0000005
  Exception Offset:	00009d63
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	5129
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by HUngasaur** [comment]
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	cockatrice.exe
  Application Version:	0.0.0.0
  Application Timestamp:	5602407f
  Fault Module Name:	cockatrice.exe
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	5602407f
  Exception Code:	c0000005
  Exception Offset:	00009d63
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	5129
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by Daenyth** [comment]
What version is your client? If your version is 064c89b, this is #1560 and you can fix it by upgrading to rev1

**Comment by HUngasaur** [comment]
Thanks for getting back to me, I updated the client , a few times doing an Uninstaller each time.  3rd time was the charm seems to be OK now.



-------- Original message --------

**Comment by Daenyth** [comment]
dupe #1560
