### ISSUE TITLE
Socket error

### ISSUE THREAD

**Issue by Bigdogdch** [Cockatrice/Cockatrice#1571]
Having the same issue as Scuta04 
Socket error: Unknown error #1568
https://github.com/Cockatrice/Cockatrice/issues/1568

Please read my last comment

**Comment by Bigdogdch** [comment]
https://github.com/Cockatrice/Cockatrice/issues/1568

**Comment by Daenyth** [comment]
Screenshot?

From the about menu, what version are you using?

**Comment by Bigdogdch** [comment]
version 3189045 (2015-07-04)

**Comment by woogerboy21** [comment]
You dont have something like a host file setup with the wrong IP in it do you?

**Comment by Daenyth** [comment]
Perhaps a firewall?

Are you on a school network? Sometimes they have crazy network rules which might be hijacking the connection.

**Comment by Bigdogdch** [comment]
Nope. It my home laptop

Chris.

**Comment by Daenyth** [comment]
Any firewall or antivirus setups?

**Comment by Bigdogdch** [comment]
The only thing I have is malwarebytes anti-malware scanner
Had this before the problem came up

**Comment by Daenyth** [comment]
Can you post a screenshot?

**Comment by Bigdogdch** [comment]
![screen shot](https://cloud.githubusercontent.com/assets/12568532/10108795/1ee40cd8-6391-11e5-9db7-08b17e35ddc6.png)

**Comment by Daenyth** [comment]
You definitely aren't on a recent version. Uninstall the app, download the latest installer from woogerworks, and run it to install.

**Comment by Bigdogdch** [comment]
OK Thanks 
That seemed to do the trick
