### ISSUE TITLE
Cockatrice login error -1

### ISSUE THREAD

**Issue by chazwazer97** [Cockatrice/Cockatrice#1572]
Ive been on cockatrice daily for at least a month. all of a sudden it gives me an error no matter what I do, ive tried reinstalling cockatrice, updating the card database. nothing seems to work. please help?

**Comment by Nightfirecat** [comment]
Read #1561.

**Comment by Daenyth** [comment]
The woogerworks server is requiring you to have a client that is more up to date, but your client is old enough that it doesn't understand what the server is saying.

Upgrade your client.
