### ISSUE TITLE
Client crashes when opening deck on game room (064c89b)

### ISSUE THREAD

**Issue by RASMiranda** [Cockatrice/Cockatrice#1573]
Cockatrice client version 064c89b

I've copied this deck from clipboard: https://goo.gl/cGcvTJ
Deck saves and loads fine on deck editor, but on game room when I load the deck the client crashes

**Comment by RASMiranda** [comment]
Ok, problem is Prarie Stream is misspelled, should be Prairie Stream

**Comment by Daenyth** [comment]
Upgrade your client, the crash is #1560
