### ISSUE TITLE
No "Close" button on deck view window

### ISSUE THREAD

**Issue by joshuabengal** [Cockatrice/Cockatrice#1575]
The little "x" is there in the corner, but the larger Close button was much more functional and easier to click. Small click boxes are much harder to target for users with accessibility issues (which includes me). 

Can we bring the close button back?

**Comment by Daenyth** [comment]
:+1:

**Comment by ctrlaltca** [comment]
The aspect of the "deck view window" titlebar is currently drawn after the aspect defined by your operating system. What o.s. are you running?

**Comment by Daenyth** [comment]
Screenshots pointing out the issue also help

**Comment by joshuabengal** [comment]
Windows 7
On Sep 24, 2015 3:29 PM, ctrlaltca <notifications@github.com> wrote:The aspect of the "deck view window" titlebar is currently drawn after the aspect defined by your operating system. What o.s. are you running?

**Comment by joshuabengal** [comment]
I will try to get some later
On Sep 24, 2015 3:55 PM, Gavin Bisesi <notifications@github.com> wrote:Screenshots pointing out the issue also help

**Comment by joshuabengal** [comment]
Screenshot

![noclosebutton](https://cloud.githubusercontent.com/assets/13399585/10098422/2cd4deb8-634f-11e5-9d02-ad42f9c837de.jpg)

**Comment by joshuabengal** [comment]
It looks like this is the commit that made the change
The  May 5 commit by poixen in Cockatrice/cockatrice/src/zoneviewzone.cpp. The notes say: 


WIP Remade reveal zone

+ darkened card area to eaisily see boundries
+ reverted back to using a window
+ window can be resized
+ removed fake title bar and "X"
+ moved all cards revealed slightly to the right, makes it easier to
drag-select from the left

**Comment by ctrlaltca** [comment]
That commit changed the "deck view zone" from being a gray, unresizable rectangle with a dummy close button to be a real windows with os-themed window decorations.
The titlebar is so small because that's how it's defined in windows xp (and win7 with classic theme); we could tune the window's flags to make it appear like a top level window, with a bigger close button.
Also, you should be able to close the view pressing "Esc".

**Comment by tooomm** [comment]
But it's not working correctly @ctrlaltca 
>to be a real windows with os-themed window decorations

![view library win](https://cloud.githubusercontent.com/assets/9874850/10099118/ed3a0e08-6386-11e5-907a-32becd2e280b.png)
The decoration is different than the windows theme.
Same for `Reveal Hand` etc.

(running win 8.1)

**Comment by Daenyth** [comment]
I think there's a ticket about that already tooomm

**Comment by ctrlaltca** [comment]
Let's try to clarify:
 * Qt tries to match the current os's theme; it's not perfect, but it typically does a good job;
 * A "Classic window" theme exists (http://doc.qt.io/qt-5/gallery-windows.html)
 * A "Windows Vista" (read: windows 7) theme exists (http://doc.qt.io/qt-5/gallery-windowsvista.html)
 * No "Windows Metro" theme is shipped yet with qt. I Know old digia's qt-commercial version had such a theme, but it was far from being complete.
 * Since no windows metro theme exists, qt is rendering the window using the best match: windows 7 theme. We won't be able to draw that window decorations differently, this must be fixed in qt.

Apart of this:
 * i suppose that @joshuabengal is running Windows 7 with the classic theme;
 * all of this is unrelated to this ticket.

**Comment by tooomm** [comment]
*OT:
Thanks for the clarification about the background! :heart_eyes: 
In this case it must be really difficult to create a normal window which fits the os style for this actions!?
Otherwise we would use it...*

**Comment by ctrlaltca** [comment]
Real windows and dialogs's decorations (like preferences, edit sets, ..) are drawn by the operating system, so their aspect is correct. The "view zone" window is not really a window, it is drawn by qt to match the aspect of the os; we could make it a real window, but this could cause problems, like it going behind the game window

**Comment by joshuabengal** [comment]
I'm not going to pretend to fully understand whats being discussed, but I did manage to fix the problem on my local copy of cockatrice by splicing in some of the older code and compiling locally. I added this to zoneviewwidget.cpp at line 45 and it seems to do the trick

		//Reinstate Close Button
		closeButton = new QPushButton("Close");
		closeButton->setFixedSize(70, 30);

		connect(closeButton, SIGNAL(clicked()), this, SLOT(close()));
		closeButton->setSizePolicy(QSizePolicy::Fixed, QSizePolicy::Fixed);
		QGraphicsProxyWidget *closeButtonProxy = new QGraphicsProxyWidget;
		closeButtonProxy->setWidget(closeButton);

		hFilterbox->addItem(closeButtonProxy);


> That commit changed the "deck view zone" from being a gray, unresizable rectangle with a dummy close button to be a real windows with os-themed window decorations.

While I do understand the desire to do things the "right" way, that small x button does present real world accessibility issues. I suffer from fairly severe RSI's in my right arm, hand, and wrist, and any movement that require precision tracking to small points on the screen aggravates those and causes a painful reaction.

**Comment by joshuabengal** [comment]
Thought I would bump this now that I cockatrice going again. Is there any reason a close button was not added back to the zone views? There's no reason they cannot be "real" windows AND have a close button

**Comment by ZeldaZach** [comment]
Doesn't look like something I was involved in; This "issue" has been annoying for sure, but I'm not sure how we can make it better right now

**Comment by Daenyth** [comment]
I'm pretty sure the zone views aren't real windows from qt's perspective

**Comment by joshuabengal** [comment]
I posted code above that adds back in the Close button. It needs to be tweaked a  bit but I don't see why it couldn't be added.

**Comment by joshuabengal** [comment]
Ok, adding the above code to zoneviewwidget.cpp gives the following result (Screenshots)

If a zone is displayed that has more than 2 columns of cards, say a full library, it works fine and you get a close button where it should be

![viewlibrary](https://cloud.githubusercontent.com/assets/13399585/18237629/e9a907a4-7301-11e6-92f6-a04abb431721.png)


If you view a zone with a single column of cards, like a hand, or a graveyard with only a few cards in it, you get a working close button, but the background of the panel does not resize correctly and you get some transparency in the panel

![viewsinglecol](https://cloud.githubusercontent.com/assets/13399585/18237652/1e1cc822-7302-11e6-8e54-60e03e4b1811.png)

If you right click a zone to "View top X cards ..." then the close button does not show at all

![viewtop](https://cloud.githubusercontent.com/assets/13399585/18237661/2caf0abc-7302-11e6-8e17-f26549428c53.png)

I'm not all that familiar with QT, anyone know how these quirks can be addressed?

**Comment by joshuabengal** [comment]
This is confusing. When you view the graveyard, the first view is messed up as in the screenshot,. However, if you take any action in that view, the window fixes itself. From what I can tell that should be a result of reorganizeCards(); getting called after something changes, however, if I put zone->reorganizeCards(); as the last line in the ZoneViewWidget::ZoneViewWidget definition, it is never run, the same behavior is exhibited (messed up display when opened, display fixes itself after any change)

Any ideas?

**Comment by joshuabengal** [comment]
Well I got a workaround in place. In zoneviewzone.cpp, I added the following code to reorganizeCards

After qreal awidth = (pileView && sortByType) ? qMax(typeColumn + 1, 3) * CARD_WIDTH + (CARD_WIDTH/2) : qMax(cols, 1) * CARD_WIDTH + (CARD_WIDTH/2);

I added 
	
	if (awidth < 246) {
		awidth = 246;
	}


The Close button now appears and all window sizes work. I will close this issue
