### ISSUE TITLE
Crashing up ending of the game OSX

### ISSUE THREAD

**Issue by JineteDV** [Cockatrice/Cockatrice#1579]
OSX 10.10.5

Upon conceding a game cockatrice crashed for me.
https://www.dropbox.com/s/ncpdl8wi1ek2l0q/replay_79082.cor?dl=0 Game replay
https://www.dropbox.com/s/bn2evcxdyggz0a3/Crash%20Report%209%3A24%3A15.rtf?dl=0 Crash report

**Comment by Daenyth** [comment]
Maybe related to #1701

**Comment by ebbit1q** [comment]
if this still happens feel free to reopen
