### ISSUE TITLE
Unknown login error HELP

### ISSUE THREAD

**Issue by willskate15** [Cockatrice/Cockatrice#1583]
Whenever I log into the server with my account it says "Unknown login error:-1" so I made another account thinking there was something wrong with mine and it's still giving me the error. Any help? :(

**Comment by Daenyth** [comment]
Did making the new account work?

Either way update your client.

**Comment by willskate15** [comment]
I have to run the mscv10 + qt4.8.7 version someone made me awhile ago because my old computer wasn't working with the newest versions. Could that be the issue? It still says this on the new client.

**Comment by willskate15** [comment]
Im still having this error and cant run the new client, any help?

**Comment by Daenyth** [comment]
If you're still having this error you aren't running the latest version - the error doesn't exist in the project any more.

Try uninstalling completely, and then run the newest installer from http://cockatrice.github.io
