### ISSUE TITLE
errore login -1 cokatrice

### ISSUE THREAD

**Issue by djsp** [Cockatrice/Cockatrice#1585]
errore login -1 cokatrice non riesco a collegarmi su cokatrice

**Comment by ctrlaltca** [comment]
https://translate.google.it/translate?sl=en&tl=it&js=y&prev=_t&hl=it&ie=UTF-8&u=https%3A%2F%2Fwww.reddit.com%2Fr%2FCockatrice%2Fcomments%2F3m1cwr%2Fthe_expeditions_have_arrived%2F&edit-text=&act=url

Aggiorna cockatrice.
