### ISSUE TITLE
[Solved] Unknown login error: -1

### ISSUE THREAD

**Issue by aitor46** [Cockatrice/Cockatrice#1586]
I can´t connect to the server due to this error

**Comment by woogerboy21** [comment]
Please see the troubleshooting section or do a search.  This has been asked many times over.

https://github.com/Cockatrice/Cockatrice/wiki/Troubleshooting#i-keep-getting-a-error--1-message-upon-login

If you have attempted to install the updated client and still receive this message the install was not completed successfully.  Close all clients, backup your deck files, and reboot the PC your on, remove the current client.  Verify all the files in the install directory are gone. Then re-run the new client installer.

**Comment by tooomm** [comment]
leave this open to help others with the same problems over the next days?

**Comment by ctrlaltca** [comment]
Closing.
