### ISSUE TITLE
Main

### ISSUE THREAD

**Issue by Bigdogdch** [Cockatrice/Cockatrice#1587]
I am now able to get back logged on but now I am not able to see the the main room

Can see the chat but nothing else

![screen shot 2](https://cloud.githubusercontent.com/assets/12568532/10110321/6fb34c9c-639a-11e5-8379-c5b0b170e3ca.png)

**Comment by woogerboy21** [comment]
Clear your filters using the clear filter button

**Comment by Daenyth** [comment]
Hit "Clear filter"
