### ISSUE TITLE
Socket Error: Connection Refused

### ISSUE THREAD

**Issue by NateTheArtificer** [Cockatrice/Cockatrice#1590]
I haven't used Cockatrice in about a week or so, and when I tried logging on today I get the error "Socket Error: Connection Refused" no matter what host or port I try. Wht is the problem and how do I fix it? Thank you in advance.

**Comment by woogerboy21** [comment]
The woogerworks server is down for maintenance at the moment.  Should be up shortly.  You can try others if you like they may be up.

**Comment by NateTheArtificer** [comment]
Thank you much. I'm not sure where to find other servers to try, though.

**Comment by woogerboy21** [comment]
If you have auto login enabled you probably dont see it, but there is a drop down list on the login screen that you can select from a couple of others that host servers.

**Comment by woogerboy21** [comment]
The server is back up (and has been for a bit now).  Were you able to connect?
