### ISSUE TITLE
Change default "play card" action to use stack instead of board.

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#1594]

**Comment by Psithief** [comment]
Nice, getting rid of those legacy oddities in the code. :+1:

**Comment by Daenyth** [comment]
I think we'll still have the config option, just change the default

**Comment by anoda9** [comment]
Why is this a good change? It seems much more convenient to play cards to the battlefield.

**Comment by Daenyth** [comment]
You still can, but many people have asked for this
