### ISSUE TITLE
Server room list width isn't dynamic

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#1596]
Not sure when this happened, fairly sure it's a regression.

Built from 9c4bd8e

<img width="1432" alt="screen shot 2015-09-27 at 9 00 12 am" src="https://cloud.githubusercontent.com/assets/14644/10122903/4e09a020-64f6-11e5-865b-ac019237fe32.png">

**Comment by ctrlaltca** [comment]
Dup #1687, fixed in #1699
