### ISSUE TITLE
Possible race condition in chat display

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#1597]
I saw this on chat:

<img width="498" alt="screen shot 2015-09-27 at 9 03 20 am" src="https://cloud.githubusercontent.com/assets/14644/10122916/dfefd91e-64f6-11e5-9b7e-5ef522773b52.png">

Since unreg users aren't enabled, I suspect there's some race condition where I receive the "user disconnected" event before the "user chat" event.

We could reproduce that series of events using the python scripts to act like a servatrice

**Comment by ZeldaZach** [comment]
Do we still want to deal with this?

**Comment by Daenyth** [comment]
I haven't seen it since
