### ISSUE TITLE
Make "Manage sets" more keyboard friendly by capturing space / return

### ISSUE THREAD

**Issue by Psithief** [Cockatrice/Cockatrice#1602]
Can we have the "Edit sets" window capture space and/or return to toggle the enabled checkbox?

**Comment by Daenyth** [comment]
:+1:

**Comment by BrandonGriffin** [comment]
@Daenyth the space bar appears to do this in the current master branch.

**Comment by Psithief** [comment]
It does! Now we just need `Enter`/`return` to do the same, and `Escape` to close the window. :)

**Comment by ZeldaZach** [comment]
Can we get more context on what to do here? I don't seem to understand the issue.

**Comment by tooomm** [comment]
>Can we get more context on what to do here?

The issue asks that a user can hit `Space` or `Enter` on his keyboard in order to enable/disable a selected set in the "Manage sets..." dialog. That would allow to navigate with keys only.
`Space` works for me again in 2.7.5, but `Enter` still doesn't.
