### ISSUE TITLE
Client Auto Update Function

### ISSUE THREAD

**Issue by TMiguelT** [Cockatrice/Cockatrice#1607]
I'd like to preface this by saying that I'd really like to have a go at implementing this, so leaving this to me would be fantastic. Of course if you don't hear from me for a while then feel free to look into this.

What I'm referring to is simply an option (maybe About->Update Client) in the toolbar that opens a dialog that pulls the latest version of cockatrice from woogerworks, replaces the current client, and restarts. This isn't hugely needed feature, but it would be nice, and I believe it's up to my skill level.

My first question is, is there any reason this hasn't been implemented yet? Has anyone decided this is a bad idea?

Secondly, how should I go about downloading the newest client? I can of course make an HTTP request to the right URL (for example `http://www.woogerworks.com/files/cockatrice.weeklybuilds/Cockatrice-WindowsClient.exe` for newer versions of Windows). Is this the most future proof method of finding the client?

Any other advice is welcome.

**Comment by Daenyth** [comment]
We're actively working on release process at the moment; effort right now would be slightly wasted. Let's visit this once our automated deployments are in place and stable.

It hasn't been implemented so far due to lack of infrastructure.

Builds will be hosted on bintray in the future.

**Comment by TMiguelT** [comment]
Ah so there is a reason this hasn't been attempted!


How is this automated deployment going to work?

**Comment by ctrlaltca** [comment]
Update: we currently have official builds released from bintray, so work on this can be started.

**Comment by TMiguelT** [comment]
So no-one else is working on this? I'll give it a go in that case

**Comment by ZeldaZach** [comment]
Thanks for the help @TMiguelT

**Comment by TMiguelT** [comment]
So I should be using https://bintray.com/cockatrice/Cockatrice/Cockatrice/_latestVersion as the download URL. Correct?

**Comment by ctrlaltca** [comment]
You can leverage bintray's API to get the "latest version" information and download urls, eg: https://api.bintray.com/packages/cockatrice/Cockatrice/Cockatrice/files

API doc is here: https://bintray.com/docs/api/

**Comment by TMiguelT** [comment]
Okay so the versions endpoint is authenticated (https://api.bintray.com/packages/cockatrice/Cockatrice/Cockatrice/versions/_latest). Should I just use the files endpoint you linked and determine the version from the 'created' date?

**Comment by TMiguelT** [comment]
Okay it's going well, but how do I get the build date of the current version? I need this to determine if the client needs an update. I realise there's a `VERSION_STRING = "c917a6c (2015-12-27)";` but I'd rather not have to parse out the date from that.

**Comment by ZeldaZach** [comment]
Why don't you come on gitter? We'll try to help

**Comment by Daenyth** [comment]
@TMiguelT can you have a look at #210? There was some discussion on this in the past.

**Comment by TMiguelT** [comment]
I read that issue but I'm not sure I see the connection. What were you referring to?

**Comment by TMiguelT** [comment]
Other than the json/qt4 issue, does anyone know why the builds are failing with qt5 Linux?

**Comment by Daenyth** [comment]
Nothing specific, just mentioning it for hour info.

**Comment by ctrlaltca** [comment]
fixed in #1727
