### ISSUE TITLE
Oracle and Cockatrice should produce xml schema tags in produced xml files

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#1610]
They can have `xsi:schemaLocation` link to `https://github.com/Cockatrice/Cockatrice/blob/<git_version_hash>/doc/cards.xsd` and `deck.xsd` respectively. This should help with tool validation.

**Comment by Psithief** [comment]
Oracle would also need to open `tokens.xml` and add the attribute.

**Comment by tooomm** [comment]
do we need a special token.xml with the schema tags in the doc folder on github then as well?

**Comment by Daenyth** [comment]
Tokens is awkward. It's not generated by a version of the code, so I'm not sure what to link to

**Comment by Psithief** [comment]
It still needs to follow the same format as cards but that schemaLocation has a variable in it.

**Comment by Daenyth** [comment]
Right but what version? If you write a token file, and we update cockatrice, now there's a new version, and we might have added changes that you didn't correct for - and now it lists a schema in the xml file that doesn't validate against itself

**Comment by Psithief** [comment]
Leave it then. The only test it needs to pass is whether Cockatrice loads it successfully or not.
