### ISSUE TITLE
Cockatrice stops working upon connection.

### ISSUE THREAD

**Issue by Irdilavice** [Cockatrice/Cockatrice#1613]
Latest release, redownloaded somewhere between 15 to 18 times. It runs fine if I can rush to hit disconnect within the short period of time. Upon connection to a server (any) it will immediately stop responding.

**Comment by Daenyth** [comment]
What version from the about menu? What OS? Any error messages? Screenshots?

**Comment by ctrlaltca** [comment]
Depending on your os/version, you could try to disable autoconnect modifying the configuration file. Alternatively, you could try starting cockatrice while not connected to the internet to see if it still crashes.

**Comment by Irdilavice** [comment]
Version: d55e44e
OS: Windows 7 home pro
No error messages other than the default "Cockatrice has stopped responding." 
No screenshots I'm afraid. I backed up my decks, completely wiped it and all traces, and reinstalled and that fixed it. But it simply gave the default Windows "(Program) has stopped responding." message the moment it tried to connect to any server. Thank you both very much, though.
