### ISSUE TITLE
f2 to concede doesn't work on mac

### ISSUE THREAD

**Issue by anoda9** [Cockatrice/Cockatrice#1614]
It worked a few versions ago, but does not currently work on d55e44e.

**Comment by ZeldaZach** [comment]
On mac, <kbd>fn + f2</kbd> doesn't work?

**Comment by anoda9** [comment]
Correct. It used to work previously.

**Comment by Daenyth** [comment]
If you go to the keybind settings and map concede to f2 manually, does it then work?

**Comment by anoda9** [comment]
Nevermind, this is was just an issue with my keyboard/remappings. I had remapped f2 to something else... -_-
