### ISSUE TITLE
include portable option in NSIS win installer

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#1616]
Right now we have a normal installer file and a portable option that is more or less _unused_.

I would like to see them included as an option into the normal win installer (like other programs do), that would finally utilize the great option we have.
Even more with automated building and central hosting of the NSIS created file in the future.

https://gist.github.com/kevinhikaruevans/a46be6ad593e9fa3f7d2
http://stackoverflow.com/questions/13777988/use-nsis-to-create-both-normal-install-and-portable-install
http://stackoverflow.com/questions/23389007/nsis-install-like-in-teamviewer-portable-mode-option

example from [foobar2000](http://www.foobar2000.org) (sadly no open source):
![nsis portable integration](https://cloud.githubusercontent.com/assets/9874850/10216809/089fc44a-682c-11e5-9ade-96f8d9ea2cd2.png)
_The "admin-rights-needed-shield" on the `Next` button will disappear if you select `Portable installation`_

**Comment by ctrlaltca** [comment]
This is not possible by now, since being "portable" is hardcoded inside the executable at compilation time. We'd need to change this from being a compile-time #define to a runtime check, e.g. checking if a "portable" dummy file exists in the same directory of the executable.
