### ISSUE TITLE
Buddies only games

### ISSUE THREAD

**Issue by Philip61978** [Cockatrice/Cockatrice#1617]
Hey i was wondering if any developers have thoughts on making a filter on the games created tab that will make it where buddies only games dont show up kinda like password protected and occupied games. Just a thought. Thx

**Comment by tooomm** [comment]
that would just makes sense if buddy games that one of your buddies create would be displayed, no?

maybe a generic filter: `Just show games that I can join?`

**Comment by Philip61978** [comment]
^^^ Yes exactly plz

**Comment by Daenyth** [comment]
The reason that isn't there is that you don't have access to other player's lists; you only know whether you can join at the time you try.

We could make the default to be "hide buddy only games", but the problem there is that people *already* get confused by filters - we get questions all the time about "I made a game and my friend can't see it" - they use a password and it doesn't show up.

**Comment by poixen** [comment]
Bump.
Would really something like this.

**Comment by tooomm** [comment]
merging with #1823
