### ISSUE TITLE
Problem with reinstalling client

### ISSUE THREAD

**Issue by whrinko** [Cockatrice/Cockatrice#1622]
Hello. I am having problems with my cockatrice client. After reinstalling it, it is saying MSVP120.dll is missing. I noticed a lnik to this in the FAQ. After exploring this solution, I found it was to a link on Microsoft's page where I was not able to download the files the FAQ was suggesting

**Comment by woogerboy21** [comment]
What was the issue when downloading the files from Microsoft? I've been
told by some certain browsers have problems so you may want to try a
different browser on there page of possible.

**Comment by Fizztastic** [comment]
@whrinko [Direct Link.](http://download.microsoft.com/download/2/E/6/2E61CFA4-993B-4DD4-91DA-3737CD5CD6E3/vcredist_x86.exe)

**Comment by whrinko** [comment]
Thank you very much

**Comment by woogerboy21** [comment]
So did that fix things for you?
