### ISSUE TITLE
Bigger or resizable create token dialog

### ISSUE THREAD

**Issue by joca-bt** [Cockatrice/Cockatrice#1623]
The create token dialog is too small and not resizable. It's a pain to search for tokens.

**Comment by tooomm** [comment]
Same for `Edit tokens` dialog...

I would suggest to include a card picture like in the `Deck Editor` in both as well.

**Comment by Psithief** [comment]
While this is true, implementing #1445, #1446 and #1447 would mean most of the time nobody needs to search for tokens.

**Comment by joca-bt** [comment]
That would be cool. Still, even then searching should be more friendly.

**Comment by tooomm** [comment]
Did #2480 did solve the problem for you @joca-bt ?

For me it looks like this with the change:
![tokencreate](https://cloud.githubusercontent.com/assets/9874850/24076070/fe789aee-0c28-11e7-93f0-f178036d9d07.png)

**Comment by joca-bt** [comment]
Well, it's still not resizable, however, this is no longer a problem due to create-related card.

**Comment by tooomm** [comment]
Jep, same for me. No idea what should have changed... 😆 

Maybe @ZeldaZach or @ctrlaltca can bring some light in the dark?
<br>

>however, this is no longer a problem due to the create-related card functionality.

This is not exactly true... during spoiler season the related tags are missing and you are forced to use the `Create Token` dialog, to name an example!
