### ISSUE TITLE
Cannot use arrows to navigate modal popups (OSX)

### ISSUE THREAD

**Issue by poixen** [Cockatrice/Cockatrice#1624]
You are unable to use the arrow keys to select yes/no from popups.

**Comment by ctrlaltca** [comment]
It's a default option in osx. You need to:
```
System Preferences > Keyboard > Keyboard Shortcuts, enable Full Keyboard Access for "All controls".
```
then you can use TAB to move the focus and space to press the buttons.

**Comment by Daenyth** [comment]
I don't think we can really do much about this given that, reopen if I'm wrong.
