### ISSUE TITLE
Assign hotkey to "draw arrow" option

### ISSUE THREAD

**Issue by poixen** [Cockatrice/Cockatrice#1625]
Please tell me there is a key to hold for drawing arrows?
The way I found (click and drag with 2 fingers on trackpad) is horrible. You can't pick up your fingers to drag further. There needs to be a hot key in case there isn't one already.

**Comment by ctrlaltca** [comment]
Yep, the 2 fingers click is hard to be used. I typically "right click -> draw arrow" and then use the touchpad.

**Comment by Daenyth** [comment]
Configure your pad so lower right corner is right click

**Comment by Daenyth** [comment]
And install better touch tool

**Comment by Daenyth** [comment]
Is this something we want to do something about? Personally I find it to be pretty acceptable to have the right click menu action + the option to configure your touchpad to work better with this. Two-finger right click is an abomination anyway :P

**Comment by ctrlaltca** [comment]
The only different way to workaround this is to assign an hotkey to the "draw arrow" action. This way you can click the source card to focus it, press the hotkey, and then point the target.

**Comment by ctrlaltca** [comment]
> Two-finger right click is an abomination anyway :P

Imho two finger click is not that bad, because you can right-click without the need of move the fingers around the trackpad. Instead, the two-finger drag-n-drop like gesture needed to draw an arrow is unusable.

**Comment by ZeldaZach** [comment]
Looking at this issue, I see no problems. I use the trackpad for arrows often. There's no reason to put time into a fix of this caliber.

**Comment by tooomm** [comment]
The one thing to consider might be this from @ctrlaltca:
>The only different way to workaround this is to assign an hotkey to the "draw arrow" action. This way you can click the source card to focus it, press the hotkey, and then point the target.

**Comment by leestran1995** [comment]
There is a setting in Cockatrice -> Settings -> Shortcuts, under the "Draw | Move | View | Gameplay" tab to set a shortcut for drawing an arrow.

**Comment by Daenyth** [comment]
Thanks @leestran1995 !
