### ISSUE TITLE
Add game creation limit?

### ISSUE THREAD

**Issue by poixen** [Cockatrice/Cockatrice#1626]
What is currently in place to stop a user from creating 100s of games that can only be closed by a mod?

**Comment by ctrlaltca** [comment]
Afaik user can't create rooms (yet). They can only be defined in servatrice.ini or in the sql database.

**Comment by poixen** [comment]
Sorry, I meant games :P Will update title.

**Comment by ctrlaltca** [comment]
From servatrice.ini:
```
; Maximum number of games a single user can create; default is 5
max_games_per_user=5
```
