### ISSUE TITLE
Can't join the Main room! "Failed to join the room due to an unknown error."

### ISSUE THREAD

**Issue by VikkuViral** [Cockatrice/Cockatrice#1628]
I just installed, got the C++ install for Win 7, updated the card database, and registered to server: cockatrice.woogerworks.com, with port: 4747. Version d55e44e

Been trying to troubleshoot this and just can't figure it out. Am I just an idiot? I see about 1,000 people in the server so I know it's on my side!

Thanks and cheers!

**Comment by woogerboy21** [comment]
This error has been mentioned before and we have yet to reproduce it. From
what we have seen the error is thrown when your username is already joined
to the room and is most likely caused by the client. It properly
disconnecting.  Let's start troubleshooting by making sure your client is
closed and you reboot your PC. This will ensure the client is completely
disconnected from the server.

Allow at least 15 minutes to pass before attempting to reopen and rejoin
the server and see if you can log in and join the room.

Also, is VikkiViral your username or are you using a different username? I
can see if there is anything on our side I. The logs that would give more
insight.

Thanks.

**Comment by Daenyth** [comment]
So there's 3+ people so far who have reported this, very likely many more.

Anyone affected, please list:
- Version from "about" menu
- Does it happen 100% of the time or only sometimes?
- Any other details you've noticed about the behavior.

**Comment by TFIN678123** [comment]
I have Version d55e44e.  This has happened only after I updated the version, and it has happened 100% of the times I tried to join a room.

**Comment by Daenyth** [comment]
What's your username on the server?

**Comment by TFIN678123** [comment]
TFIN

**Comment by Daenyth** [comment]
Can you try right now? If you're on any version that isn't windows, [collecting debug output](https://github.com/Cockatrice/Cockatrice/wiki/Debugging#mac-osx) would help

**Comment by TFIN678123** [comment]
Just tried and the same error occurred.  Should I try restarting?

I am using the Windows version.

**Comment by Daenyth** [comment]
I don't see you online at all. Can you stay connected and PM me from the Account tab?

**Comment by ctrlaltca** [comment]
I see him both online and inside the Main room now.

**Comment by Daenyth** [comment]
Same

**Comment by Daenyth** [comment]
@ctrlaltca Did anything server side change? I'm wondering if there's some odd condition that might make it not send the "you joined room x" message

**Comment by TFIN678123** [comment]
thanks for the help!

**Comment by Daenyth** [comment]
@VikkuViral When you get this, is the Main tab visible? @TFIN678123's issue was that the game list was empty.

**Comment by ctrlaltca** [comment]
We had a related change in: https://github.com/Cockatrice/Cockatrice/pull/1379;
anyway, an issue ticket predates that PR: https://github.com/Cockatrice/Cockatrice/issues/1297

**Comment by woogerboy21** [comment]
Just curious, when the condition occurs , have you tried going to the server tab and selecting the Main room and clicking the join button?

**Comment by woogerboy21** [comment]
So something interesting to note.  If I am already in the room and I goto the server tab and click the join button the error displayed is the one described.  Are the users already in the room and just over looking the room tab?

**Comment by ctrlaltca** [comment]
#1637 implements different error messages for the "you already joined the room" and "the room doesn't exists on the server".

**Comment by Daenyth** [comment]
> Are the users already in the room and just over looking the room tab?

I think this is the issue

**Comment by VikkuViral** [comment]
@Daenyth Yes, I believe I see the Main tab. I think @woogerboy21 got it right on. Thanks for solving my stupidity! I think the issue is that because you automatically join a room, you aren't notified, so for us new users it's a bit confusing to see a tab called "Main" and we don't initially assume it's a game room - especially because the Server tab is the 2nd on the list, while the primary "Room" tab to actually play is the last one. I think, most intuitively, that I look for the settings and 'extra' stuff in the far tabs.  Thanks so much for your help! Excited to start playing!

**Comment by jgod** [comment]
I don't think that the proper closure to this issue is that it's a user error. I'm on the same version as him and haven't looked into later versions, but when I ran into this there were no indicators that I was already in the room.
It's a UI/UX error.
The proper fix is to not display any errors at all, and just switch focus to that tab.

**Comment by tooomm** [comment]
But that's what happens now @jgod...
You should really upgrade your client from https://cockatrice.github.com. ;)

The errors are just shown if Cockatrice isn't able to switch to the room for several reasons.

**Comment by ctrlaltca** [comment]
> The proper fix is to not display any errors at all, and just switch focus to that tab.

That you for pointing out something that we already fixed 6 months ago :)

**Comment by jgod** [comment]
Oh, now I look dumb :) Couldn't ascertain that from just this issue. Thanks for letting me know!
