### ISSUE TITLE
Help! starting cockatrice :(

### ISSUE THREAD

**Issue by willskate15** [Cockatrice/Cockatrice#1629]
I'm running an old mscv10 + qt4.8.7 version of cockatrice on my computer that runs with Oracle but when I downloaded Battle for Zendikar I haven't been able to login. I keep getting the popup that says "Unknown login error: -1". I cannot download and run the newest clients because they haven't been working with my old computer and If I do run the new client it gives me a popup that says "The application was unable to start correctly (0xc0000022)" whenever I try to login. I've been running this older version for a long time and it was working perfectly up until BFZ. Is it my computer or the program? Help?

**Comment by woogerboy21** [comment]
Hello!

The error -1 issue is an out dated client and you will need to upgrade.
Which client have you tried using when you update? You should be able to
download the windows XP/Vista client if you want to continue to use the
msvc10+qt 4.8 build.

The error you indicate about unable to start sounds like your trying to use
the qt5 client and you have an incompatible processor for Qt5.

Thanks

**Comment by Daenyth** [comment]
https://github.com/Cockatrice/Cockatrice/wiki/Troubleshooting#application-failed-to-initiate-correctly-0xc000001d
