### ISSUE TITLE
BFZ Set cards missing from deck editor

### ISSUE THREAD

**Issue by Bigdogdch** [Cockatrice/Cockatrice#1630]
I am updating my card sets and when finished it list Battle for Zendikar as one of the sets downloaded/added/updated, but when I attempt to look for those cards, nothing comes up.
Please advise
Thanks

**Comment by Daenyth** [comment]
Do you have any customsets added? Make sure the cards.xml generated by oracle is at the same path as the one cockatrice is reading.

**Comment by Bigdogdch** [comment]
I have some files in the custom folder.  Do I need to delete those?
And how do I check on the path?

**Comment by Daenyth** [comment]
Try moving the files to another location and restarting the app. If that fixes the problem, add them back one by one until you find the one that breaks it again. Once you find one that breaks it, please upload it to gist.github.com and include the link here
