### ISSUE TITLE
[Fedora linux] Saving decks defaults to plain text, not cod

### ISSUE THREAD

**Issue by GV14982** [Cockatrice/Cockatrice#1631]
I get this error in the terminal when I save a new deck, but no file gets created: 

```
(cockatrice:13355): 
Gtk-CRITICAL **: gtk_file_chooser_default_set_current_name: assertion 'impl->action == GTK_FILE_CHOOSER_ACTION_SAVE || impl->action == GTK_FILE_CHOOSER_ACTION_CREATE_FOLDER' failed
```

**Comment by Daenyth** [comment]
What's your deck storage location?

Can you include the output from running `cmake` with the same arguments you compiled?

**Comment by GV14982** [comment]
My decks storage location is: /home/username/.local/share/Cockatrice/Cockatrice/decks/decks

And this is the output of `cmake ..`: 
-- The C compiler identification is GNU 5.1.1
-- The CXX compiler identification is GNU 5.1.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test CXX_HAS_WARNING_-Wno-error=extra
-- Performing Test CXX_HAS_WARNING_-Wno-error=extra - Success
-- Performing Test CXX_HAS_WARNING_-Wno-error=delete-non-virtual-dtor
-- Performing Test CXX_HAS_WARNING_-Wno-error=delete-non-virtual-dtor - Success
-- Performing Test CXX_HAS_WARNING_-Wno-error=sign-compare
-- Performing Test CXX_HAS_WARNING_-Wno-error=sign-compare - Success
-- Performing Test CXX_HAS_WARNING_-Wno-error=missing-declarations
-- Performing Test CXX_HAS_WARNING_-Wno-error=missing-declarations - Success
UPDATE TRANSLATIONS: OFF
-- Found Qt 5.5.0
-- Configuring done
-- Generating done
-- Build files have been written to: /home/username/Cockatrice/build
 
Also, something else I noticed, is that it is saving the decks, but it's just saving them as text files?

**Comment by Daenyth** [comment]
Is it actually saving them though? The error doesn't prevent it?

**Comment by GV14982** [comment]
No, it seems as though it creates a text file, just not the .cod

**Comment by Daenyth** [comment]
Can the file be loaded as a deck though?

**Comment by GV14982** [comment]
Nope

**Comment by Daenyth** [comment]
Can you upload the file to gist?

Is there other console output when you launch the app, create new deck,
save it?

**Comment by GV14982** [comment]
I will when I get home, but there is no other console output.

**Comment by woogerboy21** [comment]
i'd be willing to bed its actually formatted in the file correctly there just is no .cod file extension.  Might try adding .cod to the file name when you save the deck and see if you can load it later.

**Comment by GV14982** [comment]
So adding the .cod seemed to work, but it doesn't import the name or anything. Is there anything I can do to make it save correctly? If not I'm cool with the workaround, at least for now.

**Comment by Daenyth** [comment]
Can you please try:

- Restart the app
- Open deck editor tab
- Create new deck (menu)
- Add cards and save, make sure the "file type" selector is on cod
- The file on disk should be a .cod file with xml inside.

Does that work?

**Comment by GV14982** [comment]
It is still saving it as just a text document, without any XML. If I type .cod in the file name as I'm saving, it saves it correctly, but otherwise it doesn't. The file type selector is on Common Deck Format, but that is the only option besides all file types.

**Comment by Daenyth** [comment]
Ok, sounds like it might be an issue on that platform.

**Comment by GV14982** [comment]
Oh, okay! I'll just use the workaround for now!

**Comment by emidln** [comment]
For me, this manifests as a plain ascii .dec file but without any file extension. If I make the filename end with .dec, they appear and can be loaded.

I use the following to fix my decks in bash (seems safe to me, but I don't name my files with spaces or non-ascii characters, YMMV):

```bash
pushd ~/.local/share/Cockatrice/Cockatrice/decks && for x in `ls -1 -I '*.dec'`; do mv $x $x; done; popd
```

**Comment by emidln** [comment]
Also, if I add an extension of `.cod` to the end of a deck when saving, it does properly create the XML. It seems as though the save mimetypes list is supposed to be applied to generate a filename prior to figuring out which format to serialize to, this isn't happening, and it defaults no extension to just ascii .dec.

**Comment by tooomm** [comment]
Can somebody confirm that this is fixed with https://github.com/Cockatrice/Cockatrice/pull/2910?
@emidln? @GV14982?

**Comment by emidln** [comment]
It seems fixed for me. When I go to save a deck, there is a `.cod` prepopulated in the filename field. I'm on Fedora 27 now. 

It would be nice if there was a warning for saving the file without changing anything (i.e. tell me "Hey Dummy! You didn't type a filename!" or maybe something a little nicer). That said, the core issue is fixed.

**Comment by tooomm** [comment]
Which version did you tested with? The most recent release is v2.4.0.

**Comment by emidln** [comment]
I tested with `4d641eb0` which is tagged `2017-11-19-Release-2.4.0`.

**Comment by tooomm** [comment]
Jep, that's the right commit! The main problem seems to be fixed then.
