### ISSUE TITLE
Super glitchy chat/deck editor (OSX)

### ISSUE THREAD

**Issue by ktpolanski** [Cockatrice/Cockatrice#1632]
Hello,

When something appears in the chat of a game, it seems to sluggishly shift the lines up one by one to make room for itself, resulting in a weird seasickness-inducing effect that makes the game just about unplayable. The chat glitches like mad when attempts are made to scroll it. The deck editor is similarly glitchy when trying to scroll through a deck list, with parts of it freezing up randomly, making deck edition close to impossible.

I've had this issue ever since your forced update, the most recent version on your site does not solve this.

**Comment by woogerboy21** [comment]
Hello!

Can you post the specs of your PC and what OS your running?

Thanks.

**Comment by ktpolanski** [comment]
10.7.5

Processor  2.5 GHz Intel Core i5
Memory  8 GB 1600 MHz DDR3

**Comment by woogerboy21** [comment]
Those specs should be sufficient . Any of the OSX guys have any ideas? This
is the first I've heard of this and know win/Lin users with less hardware
specs don't have this sort of issue.

**Comment by ZeldaZach** [comment]
I haven't experienced this myself. @ktpolanski Can you possibly record a video so I can have a better understanding?

**Comment by Daenyth** [comment]
> 10.7.5

That's pretty old; I wonder if there's some library issue here.

Can you try following the instructions to compile your own version using homebrew? You should be able to paste what I've put below once homebrew is installed, I think.

```
brew install qt5 cmake protobuf git
git clone https://github.com/Cockatrice/Cockatrice.git
cd Cockatrice
mkdir build
cd build
QT5_DIR=$(brew info --installed qt5 | grep "^$(brew --cellar qt5)" | cut -d' ' -f1)
cmake .. -DWITH_SERVER=0 -DWITH_CLIENT=1 -DCMAKE_PREFIX_PATH=$QT5_DIR/
make
make package
open Cockatrice*.dmg
```

**Comment by ktpolanski** [comment]
Sorry about the delay. I tried the thing you suggested, I think that brew sees the leftovers of an unfortunate failed fink installation that I didn't quite manage to purge and refuses to work correctly in the first line. Naturally, this leads to the script ultimately failing.

**Comment by ZeldaZach** [comment]
old OS, so unless this is still buggy on 10.10 or 10.11 i'm closing
