### ISSUE TITLE
"Failed to join the room due to an unknown error"

### ISSUE THREAD

**Issue by BiffBifferson** [Cockatrice/Cockatrice#1633]
Hello,

Brand new user here.  Completed the install, joined the server, built a deck and now trying to join the main room.  When I click join I get a pop-up with "Failed to join the room due to an unknown error".

Running version d55e44e, port 4747

Thank you for your help!

**Comment by woogerboy21** [comment]
What is the username you are using on the server?
Thanks.

**Comment by BiffBifferson** [comment]
My user name is BiffBifferson. 

Thank you for the quick response!

**Comment by Daenyth** [comment]
Please use #1628 from here so we can keep things in one place
