### ISSUE TITLE
Failed to join the room due to an unknown error.

### ISSUE THREAD

**Issue by TFIN678123** [Cockatrice/Cockatrice#1634]
I am new to Cockatrice and just updated the client.  When I went to log in, it said I couldn't join the room.  I tried disconnecting and reconnecting, as well as restarting my PC.  I still get the error.
I have seen a couple of these issues posted.  Is there any easy solution?

My username on the server is TFIN.

Thanks!

**Comment by Daenyth** [comment]
There's some other open tickets about this; Please use #1628
