### ISSUE TITLE
windows 10 connection error

### ISSUE THREAD

**Issue by maniac3001** [Cockatrice/Cockatrice#1643]
Version d55e44e
Immer wenn ich mich zum Server verbinden will erscheint folgende Meldung:
Socket Error: unknown error
Muss ich einen best. Host auswählen?
Und was muss ich bei Port eingeben?
Oder hat es nichts damit zu tun?

**Comment by Daenyth** [comment]
Bitte einen Screenshot hochladen.

**Comment by Daenyth** [comment]
Der Port ist 4747

**Comment by tooomm** [comment]
Zu welchem Server versuchst du dich zu verbinden?
Du musst dich natürlich schon für einen Server aus der Liste entscheiden oder einen eigenen neu anlegen (dann benötigst du aber dessen Host und Port Angaben etc.).

Die Portangabe die Daenyth gemacht hat bezieht sich auf den wohl am weitesten verbreiteten Server unter www.woogerworks.com .

Bitte melde dich kurz zurück wenn alles geklappt hat oder weitehrin Probleme bestehen!

**Comment by maniac3001** [comment]
Hey, danke für den Support.
Also so geb ich's ein:
![image](https://cloud.githubusercontent.com/assets/15074483/10419006/4f1cd930-706a-11e5-9ed6-d911a3a16b7e.png)
Das ist das Ergebnis:
![image](https://cloud.githubusercontent.com/assets/15074483/10419009/63e969a0-706a-11e5-931b-27694b2123bd.png)
Wenn ich bei Port 4747 eingebe, kommt das:
![image](https://cloud.githubusercontent.com/assets/15074483/10419013/8b4a0a22-706a-11e5-8d1f-d5e936ffe61d.png)

**Comment by tooomm** [comment]
Es ist kein Port eingetragen...

**Comment by maniac3001** [comment]
Was meinst du damit?

**Comment by tooomm** [comment]
Ich habe übersehen, dass du zwischen den Bildern noch etwsa geschrieben hast... :)

Bist du schon auf dem Server registriert?

**Comment by maniac3001** [comment]
nein, habe es ausprobiert, darauf folgender Screen:
![image](https://cloud.githubusercontent.com/assets/15074483/10440734/1ec7aeb2-7142-11e5-932e-5ce6aa79925b.png)

**Comment by maniac3001** [comment]
Ah es funktioniert! Danke nochmal. Habe bei der Registration zuerst unter Host was falsches angegeben. Wenn man es so macht funktionierte: http://www.woogerworks.com/index.php/11-howto-documentation/107-how-to-register-a-cockatrice-account

**Comment by tooomm** [comment]
Ich kann immernoch nicht nachvollziehen was du genau (falsch) gemacht hast oder wie du die Fehlermeldungen produziert hast. :)
Die Registrierung ist doch eigentlich im Client bzw. auf der Seite des Servers gut formuliert und dargestellt?!
