### ISSUE TITLE
Can't get cockatrice to compile on windows

### ISSUE THREAD

**Issue by BrandonGriffin** [Cockatrice/Cockatrice#1647]
I am trying to compile cockatrice on Windows 10 x64 based. I am using visual studio 2013 premium and Qt5.5, though I am not sure what it is used for??
Every command has ran without issue for protobuf anf cockatrice until I actually try to build Cockatrice with this command

    msbuild C:\Cockatrice\build\PACKAGE.vcxproj /p:Configuration=Release /p:PlatformToolset=v120_xp
I get an error that you can't build more than one project. When I just open visual studio and try to build the solution in there, I get build errors "machine module "x64" conflicts with target machine type "x86""

**Comment by ctrlaltca** [comment]
You are mixing up 32-bit and 64-bit binaries. It seems like you are targeting to create a 32-bit package, but some library is 64-bit (Qt maybe?). I can't tell you more without viewing the log.

**Comment by Daenyth** [comment]
@BrandonGriffin If you're just looking to install it, you can also download pre-compiled binaries from woogerworks.

**Comment by BrandonGriffin** [comment]
@Daenyth I am looking to actually contribute to the codebase. 
@ctrlaltca I will look into the QT libraries right after work, that may very well be the issue. I have never used Qt before, so I am just kind of feeling my way around.

**Comment by Daenyth** [comment]
Excellent, thank you!

We usually also chat on gitter, so feel free to hop in there and hang around.

**Comment by BrandonGriffin** [comment]
After working on this for a little bit over the weekend, I have made some progress, but it seems as though the Qt library was compiled with VS 2012, and I am trying to build cockatrice with VS2013. Any pointers on what I can do there? I will also hop on gitter later if need be.

**Comment by ctrlaltca** [comment]
Just download the correct version of qt from here: http://www.qt.io/download-open-source/#section-5
Qt actually supports VS 2010, 2012 and 2013.

**Comment by BrandonGriffin** [comment]
@ctrlaltca I was able to get it to build last night. I had the correct version of Qt installed, but the proj files were pointing to a 2012 version in their paths. I changed the path to the correct folder and it builds fine now. The only issue I am having now is running the software in release mode I get an error about QtNetwork.dll and a couple of others not being on the computer, although they are definitely in the folder I put in the include path. It was too late last night for me to dig into it any though, so I will likely get around to figuring that out a little later.

**Comment by Daenyth** [comment]
@woogerboy21 Is it possible for us to provide a project definition file and say "download qt installer, run it and install to C:\whatever and then use our project file"?

Or does VS not provide a way to share config like that?

**Comment by woogerboy21** [comment]
Not sure, would have to look. As far as the missing DLLs mention when trying to run it out of the compiler. I didn't dig into things to deep for that and gave up simply copying the needed DLLs into folder that the exe gets built in.

**Comment by BrandonGriffin** [comment]
I moved the DLLs into the folder and that worked to get it up and running. I am pretty new to most of the stuff used in this project(Qt, C++, etc.), but figured now is as good of time as any to branch out. I can't get it to build in debug mode, but release mode seems to be working fine for everything I have set up, so all is well.

**Comment by woogerboy21** [comment]
You probably  don't have a copy of protobuf compiled in debug mode be my
guess.

**Comment by BrandonGriffin** [comment]
I did compile libprotobuf in debug mode, but when I tried to compile cockatrice, I got a bunch of errors about the linking and all. I fixed the errors in release mode, so I just have to do the same things in debug mode. 

When I try to check for card updates after building in release mode, it says it is unable to run the updater in C:/Cockatrice/build/Cockatrice/release/oracle.exe, which is because there is no oracle.exe there. oracle.exe gets put in the build/oracle/release folder. Is there a path I need to update, or am I doing something wrong with my build?

**Comment by ctrlaltca** [comment]
When checkin for card updates, Cockatrice assumes that oracle.exe exists in its same directory.
This is true when you install it from a package, but not inside the compilation tree.

**Comment by BrandonGriffin** [comment]
I was just looking at the code for that. So I moved the oracle.exe into the same folder as cockatrice, but the updater crashes. Probably something small I am doing wrong on my side. fun stuff haha.

**Comment by Daenyth** [comment]
It seems like this is solved - please reopen or make a new issue if your need more help.

We're also on the gitter chat if your want to talk dev stuff and the like
