### ISSUE TITLE
How do I make cards larger?

### ISSUE THREAD

**Issue by egervari** [Cockatrice/Cockatrice#1649]
In the deck editor, how can I make the picture of the card larger? At max resolution, the text is small. And because I can't resize it manually, there's actually a lot of wasted screen real-estate. Help?

**Comment by ctrlaltca** [comment]
Sorry, this ticket got lost. Anyway, the card picture in deck editor is now resizable, or you can even make it pop out the cockatrice window and make it fullscreen.
