### ISSUE TITLE
Morph card issue

### ISSUE THREAD

**Issue by ctrlaltca** [Cockatrice/Cockatrice#1652]
From #1651:
When you have a morph creature in play and you double-click a creature card from your hand that is the same as the face-down creature, it enters the battlefield on top of the morph, telling your opponent, that the morph is the same creature as the one you played from your hand.

**Comment by Nightfirecat** [comment]
Also from https://github.com/Cockatrice/Cockatrice/issues/1651#issuecomment-149111611, I'm able to reproduce the issue.

**Comment by Psithief** [comment]
This probably has the same cause as #467.
