### ISSUE TITLE
Protobuf compile error 

### ISSUE THREAD

**Issue by marcofernandezheras** [Cockatrice/Cockatrice#1653]
Just installed fedora 22 and tried to compile following compiling guide:

CMake output:
>[marco@marco build]$ cmake ..
-- The C compiler identification is GNU 5.1.1
-- The CXX compiler identification is GNU 5.1.1
-- Check for working C compiler: /bin/cc
-- Check for working C compiler: /bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /bin/c++
-- Check for working CXX compiler: /bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /bin/git (found version "2.4.3") 
-- Performing Test CXX_HAS_WARNING_-Wcast-align
-- Performing Test CXX_HAS_WARNING_-Wcast-align - Success
-- Performing Test CXX_HAS_WARNING_-Wmissing-declarations
-- Performing Test CXX_HAS_WARNING_-Wmissing-declarations - Success
-- Performing Test CXX_HAS_WARNING_-Wno-long-long
-- Performing Test CXX_HAS_WARNING_-Wno-long-long - Success                                                                                                             
-- Performing Test CXX_HAS_WARNING_-Wno-error=extra                                                                                                                     
-- Performing Test CXX_HAS_WARNING_-Wno-error=extra - Success                                                                                                           
-- Performing Test CXX_HAS_WARNING_-Wno-error=delete-non-virtual-dtor                                                                                                   
-- Performing Test CXX_HAS_WARNING_-Wno-error=delete-non-virtual-dtor - Success                                                                                         
-- Performing Test CXX_HAS_WARNING_-Wno-error=sign-compare                                                                                                              
-- Performing Test CXX_HAS_WARNING_-Wno-error=sign-compare - Success                                                                                                    
-- Performing Test CXX_HAS_WARNING_-Wno-error=missing-declarations                                                                                                      
-- Performing Test CXX_HAS_WARNING_-Wno-error=missing-declarations - Success                                                                                            
-- UPDATE TRANSLATIONS: OFF                                                                                                                                             
-- Found Qt 5.5.0                                                                                                                                                       
-- Looking for include file pthread.h                                                                                                                                   
-- Looking for include file pthread.h - found                                                                                                                           
-- Looking for pthread_create                                                                                                                                           
-- Looking for pthread_create - not found                                                                                                                               
-- Looking for pthread_create in pthreads                                                                                                                               
-- Looking for pthread_create in pthreads - not found                                                                                                                   
-- Looking for pthread_create in pthread                                                                                                                                
-- Looking for pthread_create in pthread - found                                                                                                                        
-- Found Threads: TRUE                                                                                                                                                  
-- Found PROTOBUF: /usr/local/lib/libprotobuf.so  
-- Found ZLIB: /lib64/libz.so (found version "1.2.8") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/marco/Proyectos/Qt/cockatrice/build

make error output:
>[ 30%] Building CXX object common/pb/CMakeFiles/cockatrice_protocol.dir/admin_commands.pb.cc.o
In file included from /home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.cc:5:0:
/home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
 #error This file was generated by an older version of protoc which is
  ^
/home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.h:18:2: error: #error incompatible with your Protocol Buffer headers. Please
 #error incompatible with your Protocol Buffer headers.  Please
  ^
/home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.h:19:2: error: #error regenerate this file with a newer version of protoc.
 #error regenerate this file with a newer version of protoc.
  ^
In file included from /home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.cc:5:0:
/home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.h: En la función miembro ‘void Command_ShutdownServer::clear_reason()’:
/home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.h:543:19: error: ‘kEmptyString’ no es un miembro de ‘google::protobuf::internal’
   if (reason_ != &::google::protobuf::internal::kEmptyString) {
                   ^
/home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.h: En la función miembro ‘void Command_ShutdownServer::set_reason(const string&)’:
/home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.h:553:19: error: ‘kEmptyString’ no es un miembro de ‘google::protobuf::internal’
   if (reason_ == &::google::protobuf::internal::kEmptyString) {
                   ^
/home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.h: En la función miembro ‘void Command_ShutdownServer::set_reason(const char*)’:
/home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.h:560:19: error: ‘kEmptyString’ no es un miembro de ‘google::protobuf::internal’
   if (reason_ == &::google::protobuf::internal::kEmptyString) {
                   ^
/home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.h: En la función miembro ‘void Command_ShutdownServer::set_reason(const char*, size_t)’:
/home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.h:567:19: error: ‘kEmptyString’ no es un miembro de ‘google::protobuf::internal’
   if (reason_ == &::google::protobuf::internal::kEmptyString) {
                   ^
/home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.h: En la función miembro ‘std::string* Command_ShutdownServer::mutable_reason()’:
/home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.h:574:19: error: ‘kEmptyString’ no es un miembro de ‘google::protobuf::internal’
   if (reason_ == &::google::protobuf::internal::kEmptyString) {
                   ^
/home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.h: En la función miembro ‘std::string* Command_ShutdownServer::release_reason()’:
/home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.h:581:19: error: ‘kEmptyString’ no es un miembro de ‘google::protobuf::internal’
   if (reason_ == &::google::protobuf::internal::kEmptyString) {
                   ^
/home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.h:585:44: error: ‘kEmptyString’ no es un miembro de ‘google::protobuf::internal’
     reason_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
                                            ^
/home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.h: En la función miembro ‘void Command_ShutdownServer::set_allocated_reason(std::string*)’:
/home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.h:590:19: error: ‘kEmptyString’ no es un miembro de ‘google::protobuf::internal’
   if (reason_ != &::google::protobuf::internal::kEmptyString) {
                   ^
/home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.h:598:44: error: ‘kEmptyString’ no es un miembro de ‘google::protobuf::internal’
     reason_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
                                            ^
/home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.h: En la función miembro ‘void Command_AdjustMod::clear_user_name()’:
/home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.h:643:22: error: ‘kEmptyString’ no es un miembro de ‘google::protobuf::internal’
   if (user_name_ != &::google::protobuf::internal::kEmptyString) {
                      ^
/home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.h: En la función miembro ‘void Command_AdjustMod::set_user_name(const string&)’:
/home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.h:653:22: error: ‘kEmptyString’ no es un miembro de ‘google::protobuf::internal’
   if (user_name_ == &::google::protobuf::internal::kEmptyString) {
                      ^
/home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.h: En la función miembro ‘void Command_AdjustMod::set_user_name(const char*)’:
/home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.h:660:22: error: ‘kEmptyString’ no es un miembro de ‘google::protobuf::internal’
   if (user_name_ == &::google::protobuf::internal::kEmptyString) {
                      ^
/home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.h: En la función miembro ‘void Command_AdjustMod::set_user_name(const char*, size_t)’:
/home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.h:667:22: error: ‘kEmptyString’ no es un miembro de ‘google::protobuf::internal’
   if (user_name_ == &::google::protobuf::internal::kEmptyString) {
                      ^
/home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.h: En la función miembro ‘std::string* Command_AdjustMod::mutable_user_name()’:
/home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.h:674:22: error: ‘kEmptyString’ no es un miembro de ‘google::protobuf::internal’
   if (user_name_ == &::google::protobuf::internal::kEmptyString) {
                      ^
/home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.h: En la función miembro ‘std::string* Command_AdjustMod::release_user_name()’:
/home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.h:681:22: error: ‘kEmptyString’ no es un miembro de ‘google::protobuf::internal’
   if (user_name_ == &::google::protobuf::internal::kEmptyString) {
                      ^
/home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.h:685:47: error: ‘kEmptyString’ no es un miembro de ‘google::protobuf::internal’
     user_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
                                               ^
/home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.h: En la función miembro ‘void Command_AdjustMod::set_allocated_user_name(std::string*)’:
/home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.h:690:22: error: ‘kEmptyString’ no es un miembro de ‘google::protobuf::internal’
   if (user_name_ != &::google::protobuf::internal::kEmptyString) {
                      ^
/home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.h:698:47: error: ‘kEmptyString’ no es un miembro de ‘google::protobuf::internal’
     user_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
                                               ^
/home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.cc: En la función ‘void protobuf_AssignDesc_admin_5fcommands_2eproto()’:
/home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.cc:60:27: error: no se encontró una función coincidente para la llamada a ‘google::protobuf::internal::GeneratedMessageReflection::GeneratedMessageReflection(const google::protobuf::Descriptor*&, AdminCommand*&, const int [1], int, int, int, const google::protobuf::DescriptorPool*, google::protobuf::MessageFactory*, long unsigned int)’
       sizeof(AdminCommand));
                           ^
In file included from /usr/local/include/google/protobuf/stubs/common.h:41:0,
                 from /home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.h:9,
                 from /home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.cc:5:
/usr/local/include/google/protobuf/generated_message_reflection.h:574:3: nota: candidate: google::protobuf::internal::GeneratedMessageReflection::GeneratedMessageReflection(const google::protobuf::internal::GeneratedMessageReflection&)
   GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(GeneratedMessageReflection);
   ^
/usr/local/include/google/protobuf/generated_message_reflection.h:574:3: nota:   el candidato espera 1 argumento, se proporcionaron 9
In file included from /home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.cc:14:0:
/usr/local/include/google/protobuf/generated_message_reflection.h:169:3: nota: candidate: google::protobuf::internal::GeneratedMessageReflection::GeneratedMessageReflection(const google::protobuf::Descriptor*, const google::protobuf::Message*, const int*, int, int, int, const void*, int, const google::protobuf::DescriptorPool*, google::protobuf::MessageFactory*, int, int, int)
   GeneratedMessageReflection(const Descriptor* descriptor,
   ^
/usr/local/include/google/protobuf/generated_message_reflection.h:169:3: nota:   el candidato espera 13 argumentos, se proporcionaron 9
/usr/local/include/google/protobuf/generated_message_reflection.h:133:3: nota: candidate: google::protobuf::internal::GeneratedMessageReflection::GeneratedMessageReflection(const google::protobuf::Descriptor*, const google::protobuf::Message*, const int*, int, int, int, const google::protobuf::DescriptorPool*, google::protobuf::MessageFactory*, int, int, int)
   GeneratedMessageReflection(const Descriptor* descriptor,
   ^
/usr/local/include/google/protobuf/generated_message_reflection.h:133:3: nota:   el candidato espera 11 argumentos, se proporcionaron 9
/home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.cc:75:42: error: no se encontró una función coincidente para la llamada a ‘google::protobuf::internal::GeneratedMessageReflection::GeneratedMessageReflection(const google::protobuf::Descriptor*&, Command_UpdateServerMessage*&, const int [1], int, int, int, const google::protobuf::DescriptorPool*, google::protobuf::MessageFactory*, long unsigned int)’
       sizeof(Command_UpdateServerMessage));
                                          ^
In file included from /usr/local/include/google/protobuf/stubs/common.h:41:0,
                 from /home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.h:9,
                 from /home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.cc:5:
/usr/local/include/google/protobuf/generated_message_reflection.h:574:3: nota: candidate: google::protobuf::internal::GeneratedMessageReflection::GeneratedMessageReflection(const google::protobuf::internal::GeneratedMessageReflection&)
   GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(GeneratedMessageReflection);
   ^
/usr/local/include/google/protobuf/generated_message_reflection.h:574:3: nota:   el candidato espera 1 argumento, se proporcionaron 9
In file included from /home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.cc:14:0:
/usr/local/include/google/protobuf/generated_message_reflection.h:169:3: nota: candidate: google::protobuf::internal::GeneratedMessageReflection::GeneratedMessageReflection(const google::protobuf::Descriptor*, const google::protobuf::Message*, const int*, int, int, int, const void*, int, const google::protobuf::DescriptorPool*, google::protobuf::MessageFactory*, int, int, int)
   GeneratedMessageReflection(const Descriptor* descriptor,
   ^
/usr/local/include/google/protobuf/generated_message_reflection.h:169:3: nota:   el candidato espera 13 argumentos, se proporcionaron 9
/usr/local/include/google/protobuf/generated_message_reflection.h:133:3: nota: candidate: google::protobuf::internal::GeneratedMessageReflection::GeneratedMessageReflection(const google::protobuf::Descriptor*, const google::protobuf::Message*, const int*, int, int, int, const google::protobuf::DescriptorPool*, google::protobuf::MessageFactory*, int, int, int)
   GeneratedMessageReflection(const Descriptor* descriptor,
   ^
/usr/local/include/google/protobuf/generated_message_reflection.h:133:3: nota:   el candidato espera 11 argumentos, se proporcionaron 9
/home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.cc:91:37: error: no se encontró una función coincidente para la llamada a ‘google::protobuf::internal::GeneratedMessageReflection::GeneratedMessageReflection(const google::protobuf::Descriptor*&, Command_ShutdownServer*&, const int [2], int, int, int, const google::protobuf::DescriptorPool*, google::protobuf::MessageFactory*, long unsigned int)’
       sizeof(Command_ShutdownServer));
                                     ^
In file included from /usr/local/include/google/protobuf/stubs/common.h:41:0,
                 from /home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.h:9,
                 from /home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.cc:5:
/usr/local/include/google/protobuf/generated_message_reflection.h:574:3: nota: candidate: google::protobuf::internal::GeneratedMessageReflection::GeneratedMessageReflection(const google::protobuf::internal::GeneratedMessageReflection&)
   GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(GeneratedMessageReflection);
   ^
/usr/local/include/google/protobuf/generated_message_reflection.h:574:3: nota:   el candidato espera 1 argumento, se proporcionaron 9
In file included from /home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.cc:14:0:
/usr/local/include/google/protobuf/generated_message_reflection.h:169:3: nota: candidate: google::protobuf::internal::GeneratedMessageReflection::GeneratedMessageReflection(const google::protobuf::Descriptor*, const google::protobuf::Message*, const int*, int, int, int, const void*, int, const google::protobuf::DescriptorPool*, google::protobuf::MessageFactory*, int, int, int)
   GeneratedMessageReflection(const Descriptor* descriptor,
   ^
/usr/local/include/google/protobuf/generated_message_reflection.h:169:3: nota:   el candidato espera 13 argumentos, se proporcionaron 9
/usr/local/include/google/protobuf/generated_message_reflection.h:133:3: nota: candidate: google::protobuf::internal::GeneratedMessageReflection::GeneratedMessageReflection(const google::protobuf::Descriptor*, const google::protobuf::Message*, const int*, int, int, int, const google::protobuf::DescriptorPool*, google::protobuf::MessageFactory*, int, int, int)
   GeneratedMessageReflection(const Descriptor* descriptor,
   ^
/usr/local/include/google/protobuf/generated_message_reflection.h:133:3: nota:   el candidato espera 11 argumentos, se proporcionaron 9
/home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.cc:105:35: error: no se encontró una función coincidente para la llamada a ‘google::protobuf::internal::GeneratedMessageReflection::GeneratedMessageReflection(const google::protobuf::Descriptor*&, Command_ReloadConfig*&, const int [1], int, int, int, const google::protobuf::DescriptorPool*, google::protobuf::MessageFactory*, long unsigned int)’
       sizeof(Command_ReloadConfig));
                                   ^
In file included from /usr/local/include/google/protobuf/stubs/common.h:41:0,
                 from /home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.h:9,
                 from /home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.cc:5:
/usr/local/include/google/protobuf/generated_message_reflection.h:574:3: nota: candidate: google::protobuf::internal::GeneratedMessageReflection::GeneratedMessageReflection(const google::protobuf::internal::GeneratedMessageReflection&)
   GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(GeneratedMessageReflection);
   ^
/usr/local/include/google/protobuf/generated_message_reflection.h:574:3: nota:   el candidato espera 1 argumento, se proporcionaron 9
In file included from /home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.cc:14:0:
/usr/local/include/google/protobuf/generated_message_reflection.h:169:3: nota: candidate: google::protobuf::internal::GeneratedMessageReflection::GeneratedMessageReflection(const google::protobuf::Descriptor*, const google::protobuf::Message*, const int*, int, int, int, const void*, int, const google::protobuf::DescriptorPool*, google::protobuf::MessageFactory*, int, int, int)
   GeneratedMessageReflection(const Descriptor* descriptor,
   ^
/usr/local/include/google/protobuf/generated_message_reflection.h:169:3: nota:   el candidato espera 13 argumentos, se proporcionaron 9
/usr/local/include/google/protobuf/generated_message_reflection.h:133:3: nota: candidate: google::protobuf::internal::GeneratedMessageReflection::GeneratedMessageReflection(const google::protobuf::Descriptor*, const google::protobuf::Message*, const int*, int, int, int, const google::protobuf::DescriptorPool*, google::protobuf::MessageFactory*, int, int, int)
   GeneratedMessageReflection(const Descriptor* descriptor,
   ^
/usr/local/include/google/protobuf/generated_message_reflection.h:133:3: nota:   el candidato espera 11 argumentos, se proporcionaron 9
/home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.cc:121:32: error: no se encontró una función coincidente para la llamada a ‘google::protobuf::internal::GeneratedMessageReflection::GeneratedMessageReflection(const google::protobuf::Descriptor*&, Command_AdjustMod*&, const int [2], int, int, int, const google::protobuf::DescriptorPool*, google::protobuf::MessageFactory*, long unsigned int)’
       sizeof(Command_AdjustMod));
                                ^
In file included from /usr/local/include/google/protobuf/stubs/common.h:41:0,
                 from /home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.h:9,
                 from /home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.cc:5:
/usr/local/include/google/protobuf/generated_message_reflection.h:574:3: nota: candidate: google::protobuf::internal::GeneratedMessageReflection::GeneratedMessageReflection(const google::protobuf::internal::GeneratedMessageReflection&)
   GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(GeneratedMessageReflection);
   ^
/usr/local/include/google/protobuf/generated_message_reflection.h:574:3: nota:   el candidato espera 1 argumento, se proporcionaron 9
In file included from /home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.cc:14:0:
/usr/local/include/google/protobuf/generated_message_reflection.h:169:3: nota: candidate: google::protobuf::internal::GeneratedMessageReflection::GeneratedMessageReflection(const google::protobuf::Descriptor*, const google::protobuf::Message*, const int*, int, int, int, const void*, int, const google::protobuf::DescriptorPool*, google::protobuf::MessageFactory*, int, int, int)
   GeneratedMessageReflection(const Descriptor* descriptor,
   ^
/usr/local/include/google/protobuf/generated_message_reflection.h:169:3: nota:   el candidato espera 13 argumentos, se proporcionaron 9
/usr/local/include/google/protobuf/generated_message_reflection.h:133:3: nota: candidate: google::protobuf::internal::GeneratedMessageReflection::GeneratedMessageReflection(const google::protobuf::Descriptor*, const google::protobuf::Message*, const int*, int, int, int, const google::protobuf::DescriptorPool*, google::protobuf::MessageFactory*, int, int, int)
   GeneratedMessageReflection(const Descriptor* descriptor,
   ^
/usr/local/include/google/protobuf/generated_message_reflection.h:133:3: nota:   el candidato espera 11 argumentos, se proporcionaron 9
/home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.cc: En la función miembro ‘void Command_ShutdownServer::SharedCtor()’:
/home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.cc:611:42: error: ‘kEmptyString’ no es un miembro de ‘google::protobuf::internal’
   reason_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
                                          ^
/home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.cc: En la función miembro ‘void Command_ShutdownServer::SharedDtor()’:
/home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.cc:621:19: error: ‘kEmptyString’ no es un miembro de ‘google::protobuf::internal’
   if (reason_ != &::google::protobuf::internal::kEmptyString) {
                   ^
/home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.cc: En la función miembro ‘virtual void Command_ShutdownServer::Clear()’:
/home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.cc:652:23: error: ‘kEmptyString’ no es un miembro de ‘google::protobuf::internal’
       if (reason_ != &::google::protobuf::internal::kEmptyString) {
                       ^
/home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.cc: En la función miembro ‘void Command_AdjustMod::SharedCtor()’:
/home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.cc:1044:45: error: ‘kEmptyString’ no es un miembro de ‘google::protobuf::internal’
   user_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
                                             ^
/home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.cc: En la función miembro ‘void Command_AdjustMod::SharedDtor()’:
/home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.cc:1054:22: error: ‘kEmptyString’ no es un miembro de ‘google::protobuf::internal’
   if (user_name_ != &::google::protobuf::internal::kEmptyString) {
                      ^
/home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.cc: En la función miembro ‘virtual void Command_AdjustMod::Clear()’:
/home/marco/Proyectos/Qt/cockatrice/build/common/pb/admin_commands.pb.cc:1085:26: error: ‘kEmptyString’ no es un miembro de ‘google::protobuf::internal’
       if (user_name_ != &::google::protobuf::internal::kEmptyString) {
                          ^
common/pb/CMakeFiles/cockatrice_protocol.dir/build.make:1278: recipe for target 'common/pb/CMakeFiles/cockatrice_protocol.dir/admin_commands.pb.cc.o' failed
make[2]: *** [common/pb/CMakeFiles/cockatrice_protocol.dir/admin_commands.pb.cc.o] Error 1
CMakeFiles/Makefile2:177: recipe for target 'common/pb/CMakeFiles/cockatrice_protocol.dir/all' failed
make[1]: *** [common/pb/CMakeFiles/cockatrice_protocol.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ctrlaltca** [comment]
As the error states:
```
This file was generated by an older version of protoc which is incompatible with your Protocol Buffer headers. Please regenerate this file with a newer version of protoc.
```
Protoc is creating files that are not compatible with the installer protobuf library version.
Can you ``` yum list installed | grep proto```?

**Comment by ctrlaltca** [comment]
Closing. This was quite surely a case of mismatching version between protoc and libprotobuf.
