### ISSUE TITLE
In-game Macros

### ISSUE THREAD

**Issue by Kyzaru** [Cockatrice/Cockatrice#1659]
Hi there!
Could someone explain me how in-game macros work?
Thank you

**Comment by tooomm** [comment]
Dou you mean the shortcuts?
https://github.com/Cockatrice/Cockatrice/wiki/Custom-Keyboard-Shortcuts

**Comment by Daenyth** [comment]
The chat macros aren't well documented ATM. I'll try to get something when
I can

**Comment by Daenyth** [comment]
Dup #267
