### ISSUE TITLE
Consolidate play/pause buttons in replays

### ISSUE THREAD

**Issue by anoda9** [Cockatrice/Cockatrice#1661]
Since a replay can never being playing and paused at the same time, the Play and Pause buttons should be consolidated into one button (Play/Pause) whose image changes depending on the state. 
This also might make it easier to implement #1536?

**Comment by Nightfirecat** [comment]
Definitely would be a big UI (and possibly UX) improvement. :+1:

**Comment by Daenyth** [comment]
:+1:

**Comment by tooomm** [comment]
Very good suggestion!
