### ISSUE TITLE
problem with token downloading

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#1663]
![token ssl](https://cloud.githubusercontent.com/assets/9874850/10757256/fe592a48-7ca9-11e5-980b-d50c87c8ec70.png)

When I try to download the token file I get this error message.
If I copy the link from Oracle to my browser it opens without any problems.

**Comment by Daenyth** [comment]
Have you compiled before? Could you run the app inside VS and capture any log output?

**Comment by tooomm** [comment]
I use Cockatrice  version 5db338c (2015-10-02) from [appveyor](https://ci.appveyor.com/project/Daenyth/cockatrice/build/0.0.0.0.1-branch-master-build-31/job/5k108mo0hf1wfiqy).

**Comment by ctrlaltca** [comment]
Quick tested under Windows7, seems to work here. The typical case of that error is missing openssl libraries in the app folder (libssl, libeay), but this doesn't seems the case.

**Comment by tooomm** [comment]
The only `ssl` related file I can find in the Cockatrice install folder is `ssleay32.dll`.
(same for the portable app folder)

Win 8.1 64bit here.

**Comment by ctrlaltca** [comment]
No ```libeay32.dll```?

**Comment by tooomm** [comment]
![token ssl](https://cloud.githubusercontent.com/assets/9874850/10765627/fcf300dc-7cd3-11e5-92ce-25223ddaada9.png)

Newest build on the same PR has the same problem. (Cockatrice_git-d85fcfc_2015-10-05-x86_64_qt5)
https://ci.appveyor.com/project/Daenyth/cockatrice/build/0.0.0.0.1-branch-master-build-38/job/1j204juo7ru6mxgi

<br>


>No libeay32.dll?

Yes. I don't have a `libeay32.dll` file in the installation folder or the portable build. The portable build is updating though... (I also checked for hidden files!)

**Comment by tooomm** [comment]
Build f35c047 (downloaded from the gh page) is working for me!
I don't get it...

@Psithief If I remember correctly you had some similar problems and run into this error as well at some point?!

**Comment by Psithief** [comment]
I don't know any more than you, you guys told me it was appveyor at fault.

**Comment by tooomm** [comment]
At least I'm having a `libeay32.dll` now in my `C:\Program Files (x86)\Cockatrice` folder... which might caused this. I don't know why it was missing before, I can't think of any Oracle/appveyor changes recently!

Are card + token downloads working for you with recent builds as well @Psithief ?

**Comment by Psithief** [comment]
Works fine in the build 2016-01-11 (5350302), but I don't uninstall when I install a new one so I'm not a good data point.

**Comment by tooomm** [comment]
Ok. I'll close for now...
