### ISSUE TITLE
Don't ask me again box when closing

### ISSUE THREAD

**Issue by poixen** [Cockatrice/Cockatrice#1664]
When I exit the client I would rather not have a popup preventing me from doing so. 
Can we have a "Don't ask me again" check box to this can be optional?

**Comment by Nightfirecat** [comment]
:+1:

**Comment by Daenyth** [comment]
I think this depends.

Currently, which ones do we show?
- You have games open, are you sure you want to exit (this is ok to skip)
- You haven't saved this deck, are you sure? (Not ok to skip)

**Comment by tooomm** [comment]
If the game is active I'm not sure if skipping is a good behavior...
It's ok for game rooms where you just idle in the game lobby maybe.

**Comment by Daenyth** [comment]
Well, for the game, you can rejoin. The deck you can't recover.

We shouldn't be prompting at all if you're spectating.

**Comment by tooomm** [comment]
Good point. :+1:

**Comment by ZeldaZach** [comment]
I don't find this too relevant
