### ISSUE TITLE
Propper scaling of tabletop in 3 player mode

### ISSUE THREAD

**Issue by derpman123** [Cockatrice/Cockatrice#1666]
The wasted space in a 3 player game would be awesome if the whole bottom row was that play'ers portion of the battlefield/tabletop.

instead of https://i.imgur.com/PxMeabb.jpg it would be nice to be able to stretch the field to cover the whole space giving you more room instead of a big black box.

![img](https://i.imgur.com/PxMeabb.jpg)

**Comment by ZeldaZach** [comment]
The only option is to play with the full bar view instead of the small rectangles. It's a limitation of such a layout as we can't expand one player's board and not the others.
