### ISSUE TITLE
Resize limits with "Card Info" widget

### ISSUE THREAD

**Issue by LethalPigeon7** [Cockatrice/Cockatrice#1667]
~~tl;dr: Please make card info in-game optional.(leaving only the list of players and chat) 
Card info in game. Why is it there. Why. I can always middleclick to get the same information. The existance of this feature: a) spares me of the physical work required to press down on my mouse b) saves me time, the time it takes for my brain to process the information, my finger to press down, and my computer to process that information. Miliseconds. 
While I can't relate, I can understand this for mac users. Or people whose middle mouse button is broken. Still, these are niche markets, so it should be off by default. And why in spagetti's name would this not be optional? Even if one hates optimalization, and people with small screens so much, please, let it be resizable at least.~~
~~Here I present a picture of me using this feature to its fullest:
![image](https://cloud.githubusercontent.com/assets/7950438/10829963/57a58464-7e7d-11e5-8c8f-e83f98d63171.png)~~

<br>

**Edit:** Initial issue is fixed.
This issue is now about limits with resizing the `Card Info` widget: https://github.com/Cockatrice/Cockatrice/issues/1667#issuecomment-173484929

**Comment by ctrlaltca** [comment]
Yep, i suppose https://github.com/Cockatrice/Cockatrice/pull/1544 could be a nice solution for your needs.

**Comment by Daenyth** [comment]
Can you not just drag the chat all the way to the top any more? The separator should be a draggable handle unless something changed

**Comment by LethalPigeon7** [comment]
EDIT: Forgot laptops. Laptop users are a big demographic that needs this feature. I was using one when I wrote this for spagetti's sake. Still doesn't mean there's any reason for it to be on by default, or even mandatory.

**Comment by Daenyth** [comment]
> Can you not just drag the chat all the way to the top any more? The separator should be a draggable handle unless something changed

I'd like to know if this is broken, I haven't been on the app lately.

**Comment by LethalPigeon7** [comment]
Well the user list is very flexible(its size is very adjustable), the chat is somewhat flexible, and the card info(which mind you I still consider completely useless for my personal usage in-game) can not shrink past a certain size. This is a problem only relating to small screens, personally I have the card info consuming about 2/3 of the "chat/userlist/card info" area, leaving very little to the other ones. Removing minimum sizes or even allowing windows to be dragged and/or closed like deck editor parts would fix this perfectly.

**Comment by tooomm** [comment]
@LethalPigeon7 Did you even check out the link ctrlaltca posted above? ;)
Please test this version and report back if that's helping you:
https://bintray.com/cockatrice/Cockatrice/Cockatrice-git/0.0.1~git20160111.5350302/view#files

**Comment by LethalPigeon7** [comment]
I've downloaded the version linked, uninstalled the old one, installed the new one, and nothing has changed.

**Comment by Daenyth** [comment]
Can you confirm the full version string from the `About` menu?

**Comment by LethalPigeon7** [comment]
![image](https://cloud.githubusercontent.com/assets/7950438/12249153/3966b308-b8be-11e5-941c-02425191c84d.png)

**Comment by tooomm** [comment]
My bad... I realized the link was not correct. Sorry for that. ;)
You can get the correct 57434a7a win build here:
https://ci.appveyor.com/project/Daenyth/cockatrice-8k7y5/build/0.0.1-branch-master-build-48

preview on 1366x768: (card info behind messages widget + custom right bar width)
![lowres](https://cloud.githubusercontent.com/assets/9874850/12259430/14bf93fa-b916-11e5-8683-ae06ff9221eb.png)

**Comment by LethalPigeon7** [comment]
No change, still the same, d0bed02 (2016-01-14). Did fix oracle which is nice. (W7, 32, shitty laptop)
Also I cant copy from the "about" menu. It'd be nice if this bug were to be resolved.

**Comment by tooomm** [comment]
You don't wonder that your version is not 57434a7 as I pointed you to?
You simply downloaded the wrong version because you clicked on `Latest Build` or something that was not part of my instructions... ;)

>You can get the correct 57434a7 win build here:
https://ci.appveyor.com/project/Daenyth/cockatrice-8k7y5/build/0.0.1-branch-master-build-48
Choose 32 or 64 bit and then click on Artifacts to download the .exe installer.

1. choose 32bit in your case
2. click on `Artifacts` 
3. download the `.exe` file

1)
![untitled](https://cloud.githubusercontent.com/assets/9874850/12352191/22b459ee-bb84-11e5-8872-4dbf299b855a.png)
<br>
2)
![untitled](https://cloud.githubusercontent.com/assets/9874850/12360841/9b5ed4a6-bbba-11e5-8d6b-1cd0cd708383.png)

**Comment by Daenyth** [comment]
@tooomm to be fair, the meaning of those details aren't obvious to non-developers

**Comment by tooomm** [comment]
Yes, you're right. Hope my comment did not sound too harsh... ;)

We still don't know what went wrong on his side, though.
I just guessed that he clicked on `Latest Build` in the upper left corner by fault.

@LethalPigeon7 Did the details and pictures I included in my last comment help you to get the correct version running?

I'm looking forward to seeing it in a release, such a great feature! :+1:

**Comment by LethalPigeon7** [comment]
Oh yes you guessed everything correctly, I just didnt have the time to sit at my pc and update for some time. After I did it worked. And you were correct in assuming I clicked latesst build. To someone with zero real developement knowledge the idea of the latest build not including everything was counterintuitive at the time. Only thing you got wrong was not noting the politeness you approached this with. Did not respond because life. Definitely not offended, the opposite if anything.

**Comment by Daenyth** [comment]
Glad we got it working for you :+1: 

>  the latest build not including everything 

"Latest build" isn't quite, it's the latest merged version. The one we linked you to was for an in-development feature not completely finished yet.

**Comment by LethalPigeon7** [comment]
The card info can still not be shrunk past a certain limit. That limit is "half my screen". While I can use cockatrice just fine since I can close the window completely, I don't understand why it has this limit, and why it's so big.

**Comment by ZeldaZach** [comment]
I'm closing this again because we have n made the game have tabs similar to deck editor. It will be live in next official release.

**Comment by LethalPigeon7** [comment]
Why close this? The deck editor has the identical issue as far as I'm concerned. There is a limit to how small a window can be, that is the issue.

**Comment by Daenyth** [comment]
We can look at changing that especially with the docking changes

**Comment by tooomm** [comment]
I experience a limit as well, but it's there for a reason I think.
If I lower the width to the narrowest possible position the `Info`, `Description` and `Both` Buttons are not completely visible and some `<` `>` buttons appear to make me cycle trough the buttons.
If you could narrow it down even more the buttons wouldn't be properly usable anymore I guess.
But the narrowest part is just like 10-15% of my screen... (13xx * 7xx resolution)
![widgetwidth](https://cloud.githubusercontent.com/assets/9874850/12483612/413af3b0-c056-11e5-9b9b-3db615949b93.png)

Are you playing on a netbook?
That's the only hardware I can imagine right now which is around 5 years old AND does use resolutions smaller than mine...

**Comment by LethalPigeon7** [comment]
10xx/6xx here. I can plug in a monitor when at home, but its annoying on the go.  The reason I push the option of increasing the limit close to the point of no limits is that if you dont like how it looks, you can always go back, I dont see the downside. Even if it did require a client restart to be fixed for example id feel its in the spirit of the beautifully massive ammount of control you get over things when using cockatrice.

**Comment by ZeldaZach** [comment]
This ticket has gone nowhere due to confusions on the issue. Please feel free to open a new ticket with any issue you might be experiencing
