### ISSUE TITLE
Deck Editor should remember changes to column order

### ISSUE THREAD

**Issue by Psithief** [Cockatrice/Cockatrice#1671]
The deck editor layout doesn't persist through different resolutions, and some items don't persist at all.

Many examples:
- Resizing Cockatrice to a different size and back resets the layout. Maximising a smaller window leads to this waste of space:  
  ![editor_default](https://cloud.githubusercontent.com/assets/1124846/11054899/262611dc-87ac-11e5-9e05-2919d3c4759c.png)  Related: #1535
- The horizontal divider between the picture and the rules text (`Card Info -> Both`) doesn't save at all. (mentioned in #1359)
  - It resets when closing/opening Cockatrice
  - It doesn't persist when opening a new Deck Editor
  - It doesn't even persist when switching to `Card Info -> Image`/`Card Info -> Description` and back.  
    ![editor_divider](https://cloud.githubusercontent.com/assets/1124846/11054851/c2109ed8-87ab-11e5-9d8b-0ae1007eb552.png)
- Order, sort and widths of columns don't persist, for both card search and deck list.

**Comment by ctrlaltca** [comment]
About the first issue, what's the best behavior?
 * resizing the 3 columns (carddb | info+filters | decklist ) proportionally, instead of just expanding the first column?
 * resizing the table columns of the carddb?

**Comment by Psithief** [comment]
Perhaps the solution is a mix of better defaults, better interpolation and keeping track of a layout for different widths.

## Better defaults
The font size doesn't change, so the card db columns only need a certain width each.
On mine (Win7) @ 1920px screen size:
* **Name** is at most 163px (in black-border)
* **Sets** will take up as must room as it can (e.g. basics lands). If we pick something like 5 sets, that's 150px
* **Mana Cost** is at most 103px (in black-border: Reaper King's 2/W2/U2/B2/R2/G)
* **P/T** is at most 49px (1+*/1+*)
* **Card type** is at most 242px (in black-border)

Column width Sub-total: 707px  
Default card db width: 1,320px

The Card db should never expand past that smaller width unless the user drags it.

## Better interpolation

The card db columns don't react when their container gets narrower, but they should. And not linearly, because the useful width of a column is different depending on the column.
*E.g.:*
* **Name** ~140px
* **Sets** 65px is enough to show 2 sets (most of the time)
* **Mana cost** 52px is enough for most cards (though the column title is cut off)
* **P/T** 26px shows single digit power / toughness stats
* **Card type** 136px is enough to show any single type, single subtype combination, e.g. `Enchantment — Aura`.

Again, based on my Win7 machine.

## Track different layouts

I often use the deck editor at half-width (960px window size) but play/watch games at full size. Every time I resize Cockatrice the deck editor messes up its layout.

What if, any time the user adjusts a divider or column in the Deck Editor, the layout should be saved for that window size?

**Comment by Daenyth** [comment]
Maybe we should look at how hard it would be to rewrite the deck editor layout in qml with css for this. Hardcoding it is a pain. Websites have solved this screen size and layout problem, so ideally we can use css to fix it.

**Comment by tooomm** [comment]
I see the need for some improvements in the deck editor as well, and things like the column not saving annoys me all the time. I also swap between different resolutions for Cockatrice (internal+external monitor) a lot...
I mentioned the `horizontal divider between the picture and the rules text` issue in #1359, too.
Good illustration of and involvement with the problem @Psithief! :+1:  

Anyone here experienced with QML?
Rewrite always sounds like a lot of work...

**Comment by Psithief** [comment]
Is [Qt Creator](https://en.wikipedia.org/wiki/Qt_Creator) the tool of choice for QML?

**Comment by ctrlaltca** [comment]
QML files are just javascript files; Qt Creator can create and edit them. Take care that two version of the Qt Quick "language" exists:
 * version 1 has been introduced in qt4.7, deprecated in qt5.5 and removed in qt5.6
 * version 2 has been introduced in qt5.0, and it doesn't exists in qt4; it requires an OpenGL2.0 video card or compiling Qt with ANGLE (a library that converts OpenGL calls to Direct3D calls).

Imho, since Qt Quick 1 has gone the way of the dodo, Qt Quick 2 would be the only choice, but it could cut out users with old/uncommon hardware.

**Comment by ray73neo** [comment]
I would like to bump this thread as it seems the issue has not been fully addressed.

It is rather frustrating to have to readjust the column size, column order, and sub-window sizes to my preferences every time I launch Cockatrice. I also suggest columns to remember order, as posted in #2152.

**Comment by tooomm** [comment]
@ray73neo which version of cockatrice are you using?

**Comment by ray73neo** [comment]
@tooomm I am using version 277d7e2. I didn't realize I was using an older version, but even after updating, only the column order in editor seems to be working. The column order when searching for games resets.

The sub-window sizes in editor do remember their sizes when I move the lines between the art+filter (2) and art+decklist (3). However, the line between art+card list (1) resets when dragged too far left but not right.

![image](https://cloud.githubusercontent.com/assets/10788499/18478240/81e9a198-799e-11e6-9156-1bfde90bb96b.png)

**Comment by tooomm** [comment]
@ray73neo Sorry for coming back to you that late. Yes, that's the newest version as of now.
The columns for games are not saved yet, this issue is ticketed already as you correctly mentioned. So we are aware of the problem and will fix it as soon as somebody finds time to look into it. It shouldn't be too difficult. But don't expect a time frame.^^

Thanks for clarifying and describing the problem with the vertical divider!

**Comment by ZeldaZach** [comment]
Covered by the linked ticket

**Comment by tooomm** [comment]
>Covered by the linked ticket

Note to clarify because this ticket is linked to in several places...
This ticket is about deck editor columns, the linked ticket is about game list columns, hence the issue occurs in various places.
