### ISSUE TITLE
another flag issue

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#1673]
In the user list the flag of "United Arab Emirates" (AE) is displayed with a wrong aspect ratio:
![ae flag](https://cloud.githubusercontent.com/assets/9874850/11068278/defd2abe-87d0-11e5-970f-0fd91b8071c2.png)
Seems to be 2x2 instead 3x2...
(Same for AF)

another picture showing that the flag is displayed wrong compared to others and the resource seems to be ok:
![ae flag](https://cloud.githubusercontent.com/assets/9874850/11691562/d9918700-9e9b-11e5-9cd7-88c57754f6af.png)

But in the edit account dialog box everything is correct:
![ae edit](https://cloud.githubusercontent.com/assets/9874850/11068352/32c8d67a-87d1-11e5-902d-87255b140d67.png)

The flag source seems fine:
https://github.com/Cockatrice/Cockatrice/blob/master/cockatrice/resources/countries/ae.svg
Compared to the working Belgium flag:
https://github.com/Cockatrice/Cockatrice/blob/master/cockatrice/resources/countries/be.svg

(linking #1331)

**Comment by ctrlaltca** [comment]
Looking at the svg, it's declaing a wrong viewport size of 512x512. I noticed the same in the "aq" flag.

**Comment by tooomm** [comment]
Yes. There are several (17) flags with a `viewBox` attribute.
Including the problematic ones mentioned here and the AM flag from issue 1331.
That might be the reason for the problems. I don't have any experience with `viewBox` though....

Detailed information about the attribute: http://sarasoueidan.com/blog/svg-art-direction-using-viewbox/

**Comment by tooomm** [comment]
![ae flag](https://user-images.githubusercontent.com/9874850/33082067-26d0761c-cedc-11e7-821f-c90155186487.png)

This is no issue anymore. Realized in 2.4.0 release.
Maybe my flag update or newer qt version fixed things!?
