### ISSUE TITLE
Client freezes on right click, please add hot key!

### ISSUE THREAD

**Issue by poixen** [Cockatrice/Cockatrice#1676]
Hardware: Macbook Pro
OS: Newest OSX

Issue:
During play I "right click" by using 2 fingers on the trackpad. Occasionally (More often that I like) the client will lock down, not allowing me to interact. The client still renders and updates as I can see users performing actions. This only happens with cockatrice. This mainly happens when right clicking to drag an arrow (a pain, with 2 finger click I might add), or when reducing life/counters.

Solution:
Add some form of clicking hotkey to make it easier to create arrows or mutate counters? Or something, I dunno.

**Comment by ctrlaltca** [comment]
Right click => menu => draw arrow, point the target, or just set an hotkey in the preferences.
Also, duplicate #1625

**Comment by poixen** [comment]
@ctrlaltca Thanks for the idea. Will look into the hotkey in prefs. Though I don't think right clicking will help when that creates the issue :D

**Comment by Daenyth** [comment]
This is bizarre. Have you seen any other app do that? It shouldn't lock up.

Can you run it from the console as described in the debugging wiki page?

**Comment by poixen** [comment]
Its also worth noting that this does not happen with a mouse connected. The freeze is only momentary, usually around 20-30 seconds.

**Comment by Daenyth** [comment]
Which macbook? From system information. I can try to reproduce it.

**Comment by poixen** [comment]
Macbook pro early 2015, with force touch.

**Comment by ZeldaZach** [comment]
This issue doesn't seem to be relevant anymore. I have not seen nor heard from anyone of this type of issue with the last few renditions of macOS
