### ISSUE TITLE
Have custom URLs return the newest rather than oldest set

### ISSUE THREAD

**Issue by ShadowDrakken** [Cockatrice/Cockatrice#1677]
I know this is a rather trivial request, but maybe it can be added as an option to have !cardid!, !setcode!, !setcode_lower!, !setname! and !setname_lower! return the most recent version, rather than the oldest version of a given card.

Much as I'm all for the nostalgia factor, the newer cards almost always just look better to me. But keeping it as a user configurable option would be good for people who prefer the older art.

**Comment by ZeldaZach** [comment]
It returns the info in your preference order, going one at a time from the top of your list down

**Comment by ctrlaltca** [comment]
From the "Card database" menu open the "Edit sets" dialog.
Click on the header of the "Release date" column so that sets will be sorted from the newest to the oldest.
Just to be sure, close and reopen cockatrice, check if sets are still sorted right, and then you're done.
