### ISSUE TITLE
Spectator cheat?

### ISSUE THREAD

**Issue by poixen** [Cockatrice/Cockatrice#1678]
Just a thought.
If I create a room and allow spectators. Am I allowed, from the same IP, you open a new client and spectate the game to get perfect hand information?

**Comment by Fizztastic** [comment]
Yes you can, although you need a second account.

**Comment by JineteDV** [comment]
What he said.

**Comment by woogerboy21** [comment]
If people do this , that's just dumb.

**Comment by Fizztastic** [comment]
It's also not limited to hand information. If "spectators can see everything" is enabled, you can see what card are rearranged on top/bottom of the library in the chat log.

**Comment by Psithief** [comment]
There's no reason to deny it, it's not like IP matters. You could get a friend at another location to spectate and tell you everything you want to know.

**Comment by ctrlaltca** [comment]
There is a specific option to enable spectators to see hands, that is disabled by default.
In the "games" table there's a "spectator" column where you can see if this option is enabled.
If the option is enabled, a malicious user could join twice the game both as a player and as a spectator, and see cards in your hand. This is similar to the way bots are used to cheat in online FPS games.

**Comment by Daenyth** [comment]
Yes, you definitely can cheat this way. I recommend that anyone concerned not enable spec view
