### ISSUE TITLE
What about implementing a lisp-based scripting language to bring card effects into the software?

### ISSUE THREAD

**Issue by shackra** [Cockatrice/Cockatrice#1679]
Just an idea for making Cockatrice a better experience. I read many complains about Cockatrice of players claiming that other players are *cheaters* and leaving the game when the so-called cheaters were doing valid and legal movements, I would bet this happens because the other player missed something or he simply somehow got confused. Having the rules of *Magic: The Gathering* enforced by the software and also the effects of each card would create a better experience for the entire Cockatrice community in the long term.

My suggestion for a lisp-based scripting language comes from the fact that what makes a text editor like [Emacs](https://en.wikipedia.org/wiki/Emacs) so flexible and extensible is because of [Emacs Lisp](https://en.wikipedia.org/wiki/Emacs_Lisp), so, being *Magic* a game with fix rules that are changed or extended by the variety of effects from the cards it makes sense, at least to me, that if such thing as bringing the cards effects into the software is ever attempted, it should be made using a lisp-based language.

What are your thoughts about the idea?

**Comment by berserkingyadis** [comment]
For me, having to enforce the rules myself is part of the charm of Cockatrice. It almost feels like playing kitchen magic when you have to do everything yourself. 

I have tried the several Magic Duels of the Planeswalkers games on Steam where enforcing of the rules and effects is in the software and got bored pretty quick because there is not as much to do as in Cockatrice.

**Comment by shackra** [comment]
It almost feels, but is hard to not acknowledge that the mode in which player interacts and play is not face-to-face like playing in a kitchen table.

But some consensus could be reach in the middle between automation and players-doing-everything...

**Comment by Nightfirecat** [comment]
Cockatrice is meant to be a general game engine, not necessarily MtG-specific. Thus, it aims intentionally not to implement card mechanics. If you're looking to play Magic with a game engine, I'd recommend [XMage](http://xmage.de/) instead.

**Comment by shackra** [comment]
Oh, is true, I forgot.

But this feature isn't necessarily restricted to Magic cards either.

El sábado 14 de noviembre del 2015 a las 1845 horas, Jordan escribió:

> Cockatrice is meant to be a general game engine, not necessarily MtG-specific. Thus, it aims intentionally not to implement card mechanics. If you're looking to play Magic with a game engine, I'd recommend [XMage](http://xmage.de/) instead.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/Cockatrice/Cockatrice/issues/1679#issuecomment-156765944

-- 
👋 Pax et bonum.
Jorge Araya Navarro
https://es.gravatar.com/shackra

**Comment by Daenyth** [comment]
This goes directly against the project's intentions. I suggest you look into xmage if you'd like rules enforcement
