### ISSUE TITLE
.txt should be added to list of common deck file types

### ISSUE THREAD

**Issue by anoda9** [Cockatrice/Cockatrice#1683]
When using "load local deck", the file type always defaults to ".cod, .dec, .mwdeck". However, a lot of my decks are in the .txt format, and it's very annoying to have to keep changing the file type every time you want to load a deck. The load local deck function should remember the last selection - if the user changed it to "All files", this should be remembered. Alternatively, we could just add .txt to the list of common deck file types. 

![github file type](https://cloud.githubusercontent.com/assets/3486897/11374381/a6eb28fa-928a-11e5-92d8-219708fa59d5.png)

**Comment by ctrlaltca** [comment]
Is this something that could affect other users? I mean, if there's some other software used to create decks that saves them with a .txt extension?
if this is the case, i agree of adding this common extension to the list of the common deck extensions.
If no other software is saving decks as .txt, i see no point in adding the extension, but only the downside that people trying to load a deck from a shared folder (eg: Downloads) will have to look for deck files between a possibly lot of txt files that are not decks.

**Comment by anoda9** [comment]
> I mean, if there's some other software used to create decks that saves them with a .txt extension?

Uh, every text editor?   

If a user copies a decklist from the internet to their clipboard and then saves it in a text editor, the default format will be .txt. Obviously users can change the extension, or save the deck through cockatrice's deck editor, but that's an extra hassle that seems unnecessary.

The vast majority of mtg deck sites let you download decks files in the .txt format (though some also have the option to download decks in the .dec format). For example, if you wanted to test out this deck: http://www.mtggoldfish.com/archetype/legacy-shardless-bug-21812#paper you'd download it as a .txt file, then have to manually change the extension to .dec for it to show up in the initial window. 

I think the .txt format is ubiquitous enough for deck files that including it in the list of common files types would be an improvement. But at the very least, the other suggestion would help - 
>the load local deck function could remember the last selection - if the user changed it to "All files", this should be remembered. 

It's just incredibly tedious to either have to manually change the extension on every deck file you have, or change the file type selector to "all files" *every single time* you load a deck. Whenever you run into a workflow/pattern of actions that is "tedious" when using a piece of software, that seems like a flaw - one of the main purposes of technology seems to be to eliminate/reduce tasks that are tedious or repetitive.

**Comment by ctrlaltca** [comment]
> The vast majority of mtg deck sites let you download decks files in the .txt format

This is what i wanted to hear. I'm :+1: for this change, @Daenyth ?

**Comment by Daenyth** [comment]
I can't find a good reason to object so I suppose I'm in favor
