### ISSUE TITLE
Socket error: Connection timed out

### ISSUE THREAD

**Issue by nubbyforce** [Cockatrice/Cockatrice#1685]
Can't register. Unable to do anything because I can't. Whenever I try it pops up with a dialog box that asks for password, email, country, all that. I fill it all in and click connect and it comes back with this. Tried it about a dozen times. Running on Windows Vista 32bit, home built system with pretty insane specs. Only firewall enabled at all is Windows Firewall and both Cockatrice and Oracle are set as exceptions.

**Comment by tooomm** [comment]
You might want to tell us what went wrong?
Or how you managed to fix it?

**Comment by Daenyth** [comment]
Connection timeout is usually a transient network issue; either on his
end or the server end. There's not much to really debug here.
