### ISSUE TITLE
Shortcuts Key don't work

### ISSUE THREAD

**Issue by zeno182** [Cockatrice/Cockatrice#1686]
hi, at the moment i'm using Ubuntu 15.10, and i've recently installed Cockatrice, so by default i didn't change anything in cockatrice > settings > shortcuts , but they all don't work. (dice: ctrl+i doesn't work, mulligan: ctrl+M doesn' work, library: F3 doesn't work, graveyard: F4 doesn't work, shuffle: ctrl+S doesn't work, etc.)

i checked in cockatrice > settings > shortcuts : shortcut keys are setted normally.

inside a game the menu shows me anyway the shortcuts but they don't work.

at the moment i'm forced to use mouse... and i do slow play...

why does this happens? what can i do to fix it? thank you...

**Comment by unaszplodrmann** [comment]
https://github.com/Cockatrice/Cockatrice/wiki/Compiling-Cockatrice#ubuntu-14xx

**Comment by Daenyth** [comment]
@unaszplodrmann Aha! Are you referring to

> At last, install the package. Currently the appmenu-qt5 package is broken on ubuntu (https://bugs.launchpad.net/appmenu-qt5/+bug/1380702), so you want to remove it in order to get working hotkeys.

I didn't realize that was an issue - I'll add that to the troubleshooting faq on the wiki

**Comment by zeno182** [comment]
actually i don't understand very much... ehm, may i trust in you that it will be fixed in the following version of Cockatrice? i can wait... (in reasonable times...)

**Comment by Daenyth** [comment]
It's not a problem with Cockatrice, it's a problem with other software that cockatrice uses - and you should be able to fix it yourself by running this: `sudo apt-get remove appmenu-qt5`

**Comment by zeno182** [comment]
done... ...perfect! it seems the problem is solved... now all shortcuts work how they should... graphics layout is changed (now it has something like "old style"), but it's ok... thank you!

**Comment by Daenyth** [comment]
Let us know if you have any other issues.
