### ISSUE TITLE
save custom set of filters

### ISSUE THREAD

**Issue by belenkaya** [Cockatrice/Cockatrice#1689]
When i start programm i have to make up all filters again. Can it be saved in layout?

**Comment by tooomm** [comment]
You are talking about the filter options for the shown card list in the deck editor tab?
Because the filters for the games list on the server are saved...

**Comment by belenkaya** [comment]
If i am asking for filters to be saved, i mean that they are not saved now. Of course, i am talking about deck editor tab. Why would i ask something already done?

**Comment by belenkaya** [comment]
Any news on this?

**Comment by Daenyth** [comment]
No one is working on it at the moment

**Comment by Forblaze** [comment]
I'd really like to see this implemented. I only just started playing magic and the amount of cards is really overwhelming. Using filters makes everything a lot more approachable, but needing to recreate them constantly gets tedious.

**Comment by KarasuGamma** [comment]
I know this is slightly off-topic, and I realize that supporting too many formats is undesirable, but would it be possible to have a specific filter for Standard, rather than having to manually enable each of "or set DTK, ORI, BFZ, OGW, SOI"?

**Comment by Daenyth** [comment]
@Forblaze That's covered in #215

**Comment by Daenyth** [comment]
Dupe #722
