### ISSUE TITLE
No images in cockatrice on ubuntu.

### ISSUE THREAD

**Issue by thedoctor818** [Cockatrice/Cockatrice#1690]
I am running cockatrice on ubuntu 15.04 and the interface opens but I see no card images. I "see" the cards listed on the left but when I click on them nothing happens no images are shown. I tried twice to download the oracle and it seemed to download fine but no images. Please help. Thanks!

**Comment by Daenyth** [comment]
Can you run `cockatrice` from the command line and paste the output from a session here?

**Comment by thedoctor818** [comment]
That was for my friends computer. He currently has no internet access and at the moment it will be tomorrow before I can easily get you the feedback from cockatrice in the terminal. My other query is: I am running Ubuntu 15,10 and would like to know if I follow the same instructions as the 14.xx or are there new instructions to follow to compile under 15.10 for cockatrice. Thanks!!!

**Comment by Daenyth** [comment]
If you have no internet connection it can't download images. Make sure when
it's being run you have a connection.

**Comment by Daenyth** [comment]
And the instructions should be the same I believe

**Comment by ctrlaltca** [comment]
Closing.

**Comment by thedoctor818** [comment]
Upon compiling and running cockatrice in a terminal, I get the following:

File error loading your card database.
Would you like to change your card database location? Yes/No.

What do I do from there/where do I change the card database location to???

Thanks!

**Comment by ctrlaltca** [comment]
Close cockatrice and run oracle, let it download cards.
When cards are saved, it will tell you the exact path where the "cards.xml" file has been saved.
Oracle will also tell you the path of the tokens database, if you need to fix that one, too.

**Comment by thedoctor818** [comment]
Thanks, that seemed to work!
