### ISSUE TITLE
Card animations slow/general gameplay lag

### ISSUE THREAD

**Issue by litzinger** [Cockatrice/Cockatrice#1691]
Hello, since upgrading to El Capitan the card tap animations, dragging a card to the graveyard or exile, or any other animation is incredibly slow. It can take up to a second or two for a card to turn sideways. A local game appears to be slightly faster when turning cards sideways, but it still feels much slower than before I had El Capitan. Its consistent and has happened every time I've played since upgrading to El Capitan over the course of several weeks. I would record a video of it happening but I'm unable to connect to the server.

OSX 10.11.1
Cockatrice build d55e44e (2015-09-23)

**Comment by litzinger** [comment]
Just an update, this suddenly doesn't appear to be an issue anymore.

**Comment by Daenyth** [comment]
Anything that prompted it? Did you update the OS? Change anything on the system? Rebooted?

**Comment by litzinger** [comment]
Not a thing has changed. Same OS and Cockatrice versions. I just fired it up to play expecting lag and low and behold it was fine.

**Comment by brianthehuman** [comment]
This issue has been happening to me for a while - I don't play super frequently, but it was happening on my old client and is still happening after just downloading and installing the newest version.
