### ISSUE TITLE
Activation Token

### ISSUE THREAD

**Issue by Frapounette** [Cockatrice/Cockatrice#1692]
Hello, I installed Cockatrice to play Magic.
I cliked on "Connection"  and write the good server and port.
Then they ask me my email for send the activation token, that i do.
Then they ask me the token activation but i never recieved it and i'm sure the email i wrote (2 times) is good because i just have this one.
How can i do? Thanks

**Comment by Daenyth** [comment]
You need to speak to the people administrating the server.

cc @woogerboy21

**Comment by Frapounette** [comment]
i'm so bad with informatic... How i do this?

**Comment by tooomm** [comment]
So you are connecting to the woogerworks server?
You might want to try the official homepage of the server... :+1: 

www.woogerworks.com

**Comment by JineteDV** [comment]
Tell me your Cockatrice name and I'll resend the email.

**Comment by Frapounette** [comment]
Thank you. 
Frapounette

**Comment by Frapounette** [comment]
i try to "Locate activation token" but didn't work

**Comment by JineteDV** [comment]
I resent it, check your spam folder as well. If this doesn't work we can try changing your email address. For which I'd like for you to give me through the github chat privately.

**Comment by Frapounette** [comment]
It's ok thank you.

**Comment by ctrlaltca** [comment]
Closing.
