### ISSUE TITLE
An internal error has occurred, please try closing and reopening your client

### ISSUE THREAD

**Issue by isochron88** [Cockatrice/Cockatrice#1693]
On trying to connect to any server, I get an error:

"An internal error has occurred, please try closing and reopening your client and try again. If the error persists try updating your client to the most recent build and if need be contact your software provider."

I'm using Windows Vista, Cockatrice is the client from http://www.woogerworks.com the XP/Vista version.

**Comment by Daenyth** [comment]
What's the version from the About menu? Try downloading from the website again and installing, there may be a newer version. What were you doing when it happened?

**Comment by isochron88** [comment]
Version in About Menu is d55e44e (2015-09-23)
What I was doing.  Started the application, from the pull down menu "Cockatrice" selected "Connect"
In pop-up window labelled "Connect to server" the radio button "previous host" was selected with "cockatrice.woogerworks.com" as the host.  Port is "4747".  Player name and Password were left blank.  Pressed "ok" button. Error ""An internal error has occurred, please try closing and reopening your client and try again..." appeared. I tried closing and restarted Cockatrice as directed.  Problem still occurs.

**Comment by Nightfirecat** [comment]
That version is several months out of date from the current version. I'd recommend downloading and installing the latest weekly build and trying again.

**Comment by woogerboy21** [comment]
Wait, why is the username and password left blank? (just curious)

**Comment by isochron88** [comment]
The user name and password were left blank because I have never used the application before and was trying to have a look at it before I signed up. Do I have to complile from source?  or can you supply a link to the latest build?

**Comment by Daenyth** [comment]
Try using register to server from the main menu. We should make sure the
username field is there...

**Comment by isochron88** [comment]
I successfully registered an account by using register to server.  After that the "Connect" pull down menu option works.  I no longer get "An internal error has occurred...", I connect as expected.  Maybe change the error message to inform new players that they need to create an account before attempting to connect.  Thank you for help.
