### ISSUE TITLE
Velvet Marble Theme broken

### ISSUE THREAD

**Issue by Cerxi** [Cockatrice/Cockatrice#1695]
It's been like this for a few months now, but I was too lazy to file an issue; Under the VelvetMarble theme, playerzone.jpg and tablezone.jpg have swapped filenames, leading to the table using the player information zone background, and vice-versa.

**Comment by Daenyth** [comment]
Thanks, should be easy to fix

**Comment by ZeldaZach** [comment]
I just tested VelvetMarble and Leather (as a control), and both look fine to me. Can you possibly explain what went wrong?

<img width="1067" alt="screenshot 2015-12-10 12 30 20" src="https://cloud.githubusercontent.com/assets/7460172/11722943/ccf7aaa8-9f39-11e5-8c68-97aa83338c99.png">
<img width="1015" alt="screenshot 2015-12-10 12 29 23" src="https://cloud.githubusercontent.com/assets/7460172/11722945/cfa757b2-9f39-11e5-8d00-0f2c589c22c0.png">

**Comment by Cerxi** [comment]
Look at the table again on Velvet Marble. That's not the table background, you can tell by the poor tiling. Meanwhile the player background image is incredibly wide. Those two images are backwards; the table is supposed to be the wide white image and the player zone is supposed to be the narrow blue one. It was like that up until themes were added, but they were reversed at some point during the theme update.

**Comment by ctrlaltca** [comment]
I can confirm this, my mistake when moving images from the old "zonebg" to the new "themes".
Here's the old files:
 * table: https://github.com/Cockatrice/Cockatrice/blob/70296dde9a4237ec07adbffae2a4acf40fc8bf6a/zonebg/VelvetMarble_Table.jpg
* player: https://github.com/Cockatrice/Cockatrice/blob/70296dde9a4237ec07adbffae2a4acf40fc8bf6a/zonebg/VelvetMarble_VerticalHand_Player.jpg

i've created a PR fixing this: #1697
