### ISSUE TITLE
Font colors

### ISSUE THREAD

**Issue by wsky0csky** [Cockatrice/Cockatrice#1696]
I'd suggest starting using system QT functions to set the font colors rather than static color numbers.
I'm saying that because i like to use dark desktop themes on Linux and black or dark blue text does not look good on dark grey. Basically it's barely readable.

**Comment by Daenyth** [comment]
If you have any specific references that would be useful

**Comment by ctrlaltca** [comment]
Qt should follow the look and feel defined by your desktop environment, unless you manually install a cockatrice theme that modifies the colors.
Can you tell us your os and de versions, so that we can test it out?

**Comment by wsky0csky** [comment]
@ctrlaltca 
It follows the theme only in some areas, some text on chat and text on user lists are static.

**Comment by ebbit1q** [comment]
dupe https://github.com/Cockatrice/Cockatrice/issues/3948
