### ISSUE TITLE
Add user suspicion level for moderators

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#170]
With large numbers of connected users, it's sometimes hard to figure out who is worth paying attention to.

Users are usually not suspicious when
- They registered a long time ago
- Their sessions tend tower less frequent but longer sessions (rather than constantly reconnecting)
- There aren't other users on the server sharing their ip address
- They have had few or no bans in the past
- They have lots of people who added them as a buddy
- They have few people who ignore them
- They are moderators or server admins

Servatrice should send back an extra field in the user info when talking to a moderator giving a number summarizing this.

Cockatrice can then take this number and apply a gradient to people in the user list, giving a quick visual indication when users are worth watching.

Moderators should also have the ability to manually tweak this number up and down.

cc @woogerboy21 @Beusapu

**Comment by woogerboy21** [comment]
@Daenyth While working through some of the more recent idea's in the client additions I try and keep this in mind as it plays into a number of things I have in mind.  One question that has recently come up would be "At what point does the user suspicion level start to go down?".  Are we concerned about a users behavior forever?  Is after a period of time things start to drop?  Or think about it this way.  If a user starts to act out and the moderators get informed by the color change.  Then the user stops acting out and the suspicion level never drops.  Will that be a bad thing?  Would mods be constantly be notified of a user that is not really needing monitored?

**Comment by ZeldaZach** [comment]
@woogerboy21 Maybe set an `expiration_date` field for each thing added to the `userSuspicion` table? Leave them there for reference, but stop counting them against the player after X time.

**Comment by woogerboy21** [comment]
@Daenyth how often were you thinking this number should be calculated?

**Comment by Daenyth** [comment]
On user login at most once per day should be plenty.
