### ISSUE TITLE
Problems after compiling and running cockatrice on Ubuntu 15.10

### ISSUE THREAD

**Issue by thedoctor818** [Cockatrice/Cockatrice#1706]
Upon compiling and running cockatrice in a terminal, I get the following:

File error loading your card database.
Would you like to change your card database location? Yes/No.

What do I do from there/where do I change the card database location to???

Thanks!

**Comment by berserkingyadis** [comment]
Did you run "oracle" first? You have to download the cards before you can play.

**Comment by ctrlaltca** [comment]
Close cockatrice and run oracle, let it download cards.
When cards are saved, it will tell you the exact path where the "cards.xml" file has been saved.
Oracle will also tell you the path of the tokens database, if you need to fix that one, too.

**Comment by ctrlaltca** [comment]
Closing as: whatever happened we'll never know.
