### ISSUE TITLE
Locking rooms

### ISSUE THREAD

**Issue by Beusapu** [Cockatrice/Cockatrice#171]
This has been mentioned many times before, but I didn't see an issue open. It would be great to "lock" rooms so no people can join, even if there's free space. That would make it much easier for drafters who keep joining dead draft rooms that have already started. it should also let the game start if the room is locked, even if there aren't "enough" players in (like for example, in an EDH room for 4 people, if they decide to start with only 3, they should be able to).

**Comment by ZeldaZach** [comment]
See #517
