### ISSUE TITLE
Special case 2-sided dice as coin flips

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#1710]
Include heads or tails

> PlayerTwo flipped a coin - tails (0)
> PlayerOne flipped a coin - heads (1)

Purely cosmetic, still done via the existing roll system.

**Comment by ZeldaZach** [comment]
Sounds cool to me. I might try doing this

**Comment by Daenyth** [comment]
I believe you'll want to look at messagelogwidget.cpp

**Comment by Nightfirecat** [comment]
So long as the messages still provide numbers, I'm in favor of this change.
