### ISSUE TITLE
Server Crash Report: 12202015

### ISSUE THREAD

**Issue by woogerboy21** [Cockatrice/Cockatrice#1718]
This is an odd one?
```
Error: signal 11:
/usr/local/bin/servatrice.reg(_ZN13SignalHandler14sigSegvHandlerEi+0x26)[0x59a974]
/lib64/libpthread.so.0(+0xf130)[0x7f2d3d41a130]
```

Feel free to close this if its useless.  As I don't see anything from it but maybe some one else does.

**Comment by ctrlaltca** [comment]
Yep, that's almost no information in there. It could be due to a corrupted stack, but that's not how corrupted stacks usually manifest. Do you have a core file?

**Comment by woogerboy21** [comment]
It does not look like it.  And the best I can tell the actual crash log seems partially written which is very odd.
