### ISSUE TITLE
Verification email not recieved

### ISSUE THREAD

**Issue by velocity0602** [Cockatrice/Cockatrice#1719]
I've waited a day for a verification email to be sent to my account but it has never come.

**Comment by ZeldaZach** [comment]
There was a server issue with the email account being overloaded. Message @woogerboy21 for assistance.

**Comment by woogerboy21** [comment]
@velocity0602 If you have not already done so, use the contact us link off the main woogerworks site and I will manually activate your account.  I have been working through a number of account activation's already.
