### ISSUE TITLE
Merge Challenge Cards into Oracle

### ISSUE THREAD

**Issue by ZeldaZach** [Cockatrice/Cockatrice#1725]
The cards from Theros block challenge decks are "considered cards and not tokens" based on @Psithief so is there a way we can get Oracle to import them separately from the XML found at https://github.com/Cockatrice/Magic-Token/blob/master/challenge_tokens.xml?

**Comment by Psithief** [comment]
Maybe we want a repository full of extra XML files and Oracle just downloads the entire repo ZIP archive?

**Comment by ZeldaZach** [comment]
What other XMLs would we need exactly? This seems to be the only thing it doesn't parse

**Comment by Psithief** [comment]
Actually, I don't know if those game-day event decks were well-received enough for WotC to do them again. :+1: Let's not over-engineer.

**Comment by Daenyth** [comment]
Yeah, honestly I don't think this is important enough for us to redesign
our db system

**Comment by ebbit1q** [comment]
would be fixed by #1739 4109
