### ISSUE TITLE
Connection on Woogerworks server via the old Version ca60a46 of Cockatrice

### ISSUE THREAD

**Issue by raouldouglas** [Cockatrice/Cockatrice#1729]
Hello, I'm trying to connect to woogerworks server via the Version ca60a46 of Cockatrice (on MAC OS X 10.7.4), where the card image on the right of the battlefield is way more bigger and much pleasant to play for the confort of the eyes. Unfortunatly, it seems I cannot connect anymore. Is this possible to re-authorize the connections to the servers from the old software, or make the possibility on the new one to have the illustration of the cards on the right bigger, like on the old software ?
Thank by advance and thank you for your work.

**Comment by Daenyth** [comment]
The woogerworks server admin requires you to have a newer client to connect.

If you open a new issue on here specifically for the image issue, with screenshots, we can help fix that.
