### ISSUE TITLE
Windows: Some Cards Still not Loading Images

### ISSUE THREAD

**Issue by Varjo1** [Cockatrice/Cockatrice#173]
Confirmed on three different windows machines (windows 8.1 and 7, all x64). Broken cards include swamp, mountain, and dark ritual. Not sure exactly what's breaking but I've done multiple clean installs on three machines and all have had the issue. Is any more info needed from me?

**Comment by JazzMaster** [comment]
HMMM...seems this bug still exists in the latest builds for windows.Cant say for Linux, it was complaining about missing CXX files and Fedora21 has none.
