### ISSUE TITLE
Multiplayer games and Card Info

### ISSUE THREAD

**Issue by Ledge-And-Dairy** [Cockatrice/Cockatrice#1731]
I understand that we still need to follow the platform but is there a way that for multiplayer games we could do a:
 [] [] 
 [] [] 
pattern instead of 4 stacked on top of each other. secondly for the Card Info section in deck builder and in game can they be seperate? personnaly i prefer to have the both option in the deck builder and the image/ info version in game as both congests my screen and i cant read them

**Comment by ZeldaZach** [comment]
Here are the two options that we currently have. Can you elaborate on what you're talking about a little further?

<img width="1049" alt="screenshot 2015-12-29 14 52 53" src="https://cloud.githubusercontent.com/assets/7460172/12041045/ea796308-ae3b-11e5-9214-04cc43b1f39c.png">
<img width="1114" alt="screenshot 2015-12-29 14 53 07" src="https://cloud.githubusercontent.com/assets/7460172/12041044/ea766fea-ae3b-11e5-9769-ed5244f6e611.png">

Also, are you talking about two different things in this ticket?

**Comment by Ledge-And-Dairy** [comment]
yes and how do you turn on the second option in game?

**Comment by Daenyth** [comment]
>  secondly for the Card Info section in deck builder and in game can they be seperate? personnaly i prefer to have the both option in the deck builder and the image/ info version in game as both congests my screen and i cant read them

Would you please create a new issue for this concern so that we can address them specifically?

**Comment by ZeldaZach** [comment]
<img width="974" alt="screenshot 2015-12-29 14 56 45" src="https://cloud.githubusercontent.com/assets/7460172/12041107/663cbe04-ae3c-11e5-9fde-61ec67e976ab.png">

Last option

**Comment by Ledge-And-Dairy** [comment]
thank you and as for the second option here:
https://gyazo.com/3f3d51e086c821227627e61a9efbdbae and
https://gyazo.com/e4ed8ed4417e5be6109cd17d3863f6b8

**Comment by Daenyth** [comment]
Please open a second ticket about that issue so that we can keep it organized.
