### ISSUE TITLE
Deck Editor visual deck layout option

### ISSUE THREAD

**Issue by radioactivehazards** [Cockatrice/Cockatrice#1732]
I understand some people like building decks via "list" set up where it lists cards by name as it does currently. What I would like is a way to tweak this to list in a "table view" so instead of building by adding cards from 1 column to another you can build like you would real cards. Laying them out to sort via curve, color, or even type as some people like to lay out draft decks in 2 rows. creatures and spells. Now if this cannot be done by the deck editor for what ever reason, Could we make A different game room. Example: Create game. Have another function, "Create Table". This would open a Black Canvas that players could use to lay out cards, either by making tokens or loading a list and laying them out. They could sort them as they see fit. Kinda like a 1 player game but have the ability to turn off the Zoom feature because for edh decks that feature makes it very hard as the cards keep getting smaller. Another idea here is this. You know how you can only have 3 cards on top of each other....Turn that off. Attaching cards over and over and over is stressful and tiresome. You could even use the same layout for a 1 player game and instead use the "mana bubbles" as "add lands" so that you can fully build on a table.

**Comment by ZeldaZach** [comment]
Sounds like you'd like something similar to the MTGO way when drafting and such.

**Comment by Ledge-And-Dairy** [comment]
If im correct this is easily accessable with the deckstats.net link in deck editor

**Comment by Daenyth** [comment]
This is doable but because of the level of effort that would be involved, I think it's best if an outside tool does this. As @Ledge-And-Dairy says, there are websites that give a UI like this, and they can export decks in cockatrice-ready formats.

There's also the question of how to drag cards *into* such an area - it's not even possible to render all cards in the game to be dragged in, so there'd be some kind of weirdness.

We *could* potentially offer an extra tab which displays a deck using the same view as the game ready screen.

**Comment by ZeldaZach** [comment]
If this is done by an outside tool that we export to in ready format already, I see no reason to spend time on something like this (at this time) if we can do something a little more productive

**Comment by Ledge-And-Dairy** [comment]
we could alos put a quick link right below the deck list that brings you too the deckstats.net it would probably be pretty convenient

**Comment by tooomm** [comment]
>If im correct this is easily accessable with the deckstats.net link in deck editor

Deckstats just offer stats and so, no "table" to sort out visual cards (aka build) a deck like commonly done when building limited decks out of a fixed pool or finalizing-reviewing-adjusting constructed decks with real cards.

I don't know any service or tool offering this. Am I wrong?

**Comment by Ledge-And-Dairy** [comment]
there could be a sort button that puts it in order of mana cost and such

**Comment by tooomm** [comment]
**If** there is going to be a "Create Table" option or something similar that could be used to drag cards around and organize them in piles to simulate a structured deck building process with real cards... then there should be some sort/filter options as well for sure.

**Comment by radioactivehazards** [comment]
never used other sites to build on as i normally just build via cockatrice.

**Comment by Daenyth** [comment]
tappedout.net's editor is pretty nice.

**Comment by radioactivehazards** [comment]
I just signed up for an account there and such...their deck builder is worse than cockatrice. unless i did something wrong I saw Nothing like i stated at all.

**Comment by Ledge-And-Dairy** [comment]
you dont need an account just make a deck on cockatrice then go to deck editor at the top right and click analysis deck on deckstats.net and it auto loads the deck there and gives you curve and mana/mana source distrbution and such

**Comment by Daenyth** [comment]
He's talking about a visual layout to create the deck, not view it.

I'm not sure there is one right now

**Comment by tooomm** [comment]
This is very similar to https://github.com/Cockatrice/Cockatrice/issues/2883 which has a mockup too.

#1368 is also related...
