### ISSUE TITLE
sachabon@hotmail.com

### ISSUE THREAD

**Issue by sachm** [Cockatrice/Cockatrice#1738]
Hi,
when i connect, there are 700+ people in the room but when i start a game, nobody joins and i can't join a game either (i don't see any people in the "games" rectanle, only 700+ people in the "users in this room" list.

What am i doing wrong?
thanks for the reply

kind regards,
Sachabon

**Comment by ZeldaZach** [comment]
This isn't a development issue, but if you use the game options (standard, modern, etc) then you should have people playing.

**Comment by Daenyth** [comment]
Make sure you're not checking buddy only or password.

**Comment by tooomm** [comment]
Yes, maybe you just need to hit `Clear Filters` below the "Games" rectangle once. There was a known problem for some people.
