### ISSUE TITLE
Custom Download URLs - !setnr

### ISSUE THREAD

**Issue by nshcat** [Cockatrice/Cockatrice#1741]
For some image repositories, the index of a card in its set is part of the static image URL.

This, for example, is the case with `magiccards.info`. The URL "http://magiccards.info/scans/en/v13/12.jpg" links to the card `"Gilded Lotus"` in the Set `"From the Vault: Twenty"` and has the set index `12`.

A token for that index is not yet implemented. Something like `"!setnr"` or `"!setindex"` could do well.

**Comment by ZeldaZach** [comment]
I believe we spoke about this before and it's still in the works to get more fields

**Comment by Daenyth** [comment]
There's no reason we can't do this.

**Comment by ZeldaZach** [comment]
So MTGJSON added a field, `mciNumber` which contains this exact option of `!setnumber`. An update to Oracle to add a new field to the database and this should be doable.

**Comment by tooomm** [comment]
> https://github.com/Cockatrice/Cockatrice/issues/1845#issuecomment-192962601
> @skwerlman wrote:
> although i don't see any documentation for the `mciNumber` mentioned there, just `number`.

Same for me. No hint about `mciNumber` in the documentation.
