### ISSUE TITLE
Socket error... Can't connect

### ISSUE THREAD

**Issue by Untranslated** [Cockatrice/Cockatrice#1742]
"Socket error: Connection timed out" or, upon startup, "Socket error: Host not found" are the messages I'm getting.  I have the latest version for Mac (as of Jan 1st 2016).  The previous version I had couldn't connect either.

I've tried both "cockatrice.woogerworks.com" and "cockatrice.woogerworks.info" many times yesterday and today. I've also tried "vps.poixen.com" and "chickatrice.net" today. None of them seem to work. 

Maybe it's my location. I could connect from the eastern U.S. fine.  I'm now in Sweden.  But I'm able to get a response from the servers with a ping so I don't know.

 Thanks and happy new year.

**Comment by woogerboy21** [comment]
Is there a reason your leaving the periods out of all the host names?

**Comment by Untranslated** [comment]
In what I wrote above, I can see the periods between the subdomain, domain, and TLD.  Are you seeing something else?

**Comment by Daenyth** [comment]
The email notification was missing them for some reason. I can see them on the site but not the email.

The fact that poixen and woogerworks both fail leads me to think it's a problem on your side - the two servers are totally unrelated.

Are you by any chance on a university network? They often have strict network rules that might break the app's connection.

Can you try using port 443 for the woogerworks host?

**Comment by Untranslated** [comment]
I am on a sort of "campus" but haven't had an issue with anything else.  In any case, port 443 now works.    Interesting...I tried it yesterday and nothing.  Thanks so much!

**Comment by Untranslated** [comment]
I guess we can close this issue now.  Cheers
