### ISSUE TITLE
Sending offline message

### ISSUE THREAD

**Issue by radioactivehazards** [Cockatrice/Cockatrice#1744]
I know someone somewhere brought this up, Can we set up a way to message people via p.m when they are NOT on and have them receive it when they sign on next?

**Comment by Nightfirecat** [comment]
Yes, you've already raised an issue about this: #1532.

**Comment by ctrlaltca** [comment]
Closing as duplicate

**Comment by tooomm** [comment]
1532 is about
- pm chat history (not done)
- and offline reading of messages (we have that i guess because the tabs don't close anymore?)

but NOT about sending pm's to other offline users

**Comment by ctrlaltca** [comment]
Ouch, sorry for the misunderstanding. Reopening.

**Comment by Nightfirecat** [comment]
My apologies; they are in fact different, though related, issues.

**Comment by tooomm** [comment]
can someone rename the issues please? (especially this one is badly named :P )

**Comment by radioactivehazards** [comment]
That better name? I have the new client for the other issue

**Comment by radioactivehazards** [comment]
so yeah..any ideas on this???

**Comment by Daenyth** [comment]
On the surface this seems like a reasonable change. I don't think it would require any protocol changes, though maybe we might need to include a "message sent time" field on chat messages. It might already be there with the room history, actually.

**Comment by Sir-Binks** [comment]
I would welcome a feature like this.
Leaving someone a message when they are not online is something I am sure people are missing.

**Comment by ZeldaZach** [comment]
If I read this correct, this is about sending a PM to another user who happens to be offline. They shall receive said message upon logging in the next time. If this is the case, I will look into this in the next few days or so!

**Comment by ebbit1q** [comment]
this would require #2146 to be implemented first, then we can consider this
