### ISSUE TITLE
Game wont start in particular cases

### ISSUE THREAD

**Issue by Ledge-And-Dairy** [Cockatrice/Cockatrice#1745]
@ZeldaZach 

There were two attempts yesterday to start a game between two people that I was viewing and with no such luck did the game start: 
[Game 1](https://gyazo.com/3410dc4157431cfe8005b4eb7a0e4128)
[Game 2](https://gyazo.com/2df43241e80dfe282472356c4e410cbf)

Potential causes: 
1. Password game
2. Time inwhich spectator joined

In the third room made I waited until they both probably started playing before I joined and it ended up working. I believe this is a problem in the **spectators** coding, but as I dont actually have the coding I cant guarantee this.

**Comment by Daenyth** [comment]
How many people was the room set to? If it was a 3-player room it would need 3 ready players to start. I've never seen games fail to start before so I'd suspect a user problem first (though it's possibly a code problem)

**Comment by Ledge-And-Dairy** [comment]
i personnaly didnt make the room so that might have been the problem ill ask the people who were in the room

**Comment by ZeldaZach** [comment]
Any updates on this?

**Comment by Ledge-And-Dairy** [comment]
i believe the problem was the set room size sorry for the inconvenience
