### ISSUE TITLE
Sort userlist

### ISSUE THREAD

**Issue by dsolstad** [Cockatrice/Cockatrice#1748]
Is it possible to get an option to sort the online user list after country?

**Comment by Daenyth** [comment]
Possibly but I don't think it's a great idea. What are you trying to
accomplish by having it sorted?

**Comment by dsolstad** [comment]
Find fellow country men

**Comment by Daenyth** [comment]
I think I'd rather work on #622 for that. I think having sorting on the userlist is unnecessary
