### ISSUE TITLE
Official warnings

### ISSUE THREAD

**Issue by Beusapu** [Cockatrice/Cockatrice#175]
Right now, to warn someone you have to either send them a private message, tell them in the main chat, or create a 1-minute warning ban. None of those remain permanently, so if another mod sees the same user doing the same offense, he can't know if he had been warned before.

Some kind of warning list that could be seen in user details (only for mods, of course) would make it easier to know if someone is a repeated ofender. For example, you could look at someone's user details and see:
-(1) Spam warning.
-(2) Foul language warnings.

Or something like that. Warnings/infractions could expire in something like a month. If someone gets banned without a warning, that should create a warning for him too.

Users should also be able to see their active warnings when they log on, because right now, if someone logs off before you can talk to them, you have to create a long ban to make sure they get the message.

**Comment by woogerboy21** [comment]
This is on my to-do list next once #1469 is merged so if you guys have any idea's for more than the couple of warnings listed above let me know.  I'll start to work the code up prior to #1469 being merged but dont want to submit anything as I don't like to work through merge conflicts.
