### ISSUE TITLE
[RFC] Remove the local offline mode

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#1750]
This would simplify the codebase and make it possible to split the server/client/protocol into their own repos.

http://strawpoll.me/6464431

**Comment by Nightfirecat** [comment]
Alternative&mdash;would refactoring it to be a local temporary server, or something of the like, still allow for a better codebase while maintaining the ability to play/test locally?

**Comment by radioactivehazards** [comment]
would this mean that you could not use cockatrice unless online?

**Comment by ZeldaZach** [comment]
I'm fine with scrapping it as it's just a mess, but it's up to everyone I guess

**Comment by Psithief** [comment]
It's about the only reason I use Cockatrice. :-1:

**Comment by ctrlaltca** [comment]
I use local games a lot, too :-1:

**Comment by radioactivehazards** [comment]
I use it offline a lot myself and do not favor the idea of scrapping offline

**Comment by Daenyth** [comment]
> would this mean that you could not use cockatrice unless online?

You could run a servatrice on your local computer.

I think the general feedback for this has been negative enough that until/unless we come up with a more cohesive way of locally playing, we won't do this.
