### ISSUE TITLE
extend branches for different releases/development

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#1751]
As talked on gitter:
Have more/different branches for latest release(s) and development.

> Daenyth
> hmm, can appveyor and travis build automatically when we make a "release" tag on github? Would be sweet
> 
> tooomm 
> we could setup a release branch maybe that gets build^^
> 
> TMiguelT
> That might be easier actually
> 
> tooomm
> so master = development/beta, release = latest stable
> 
> TMiguelT
> I think the ordinary way is to have master = release and dev = dev
> 
> Daenyth
> Probably each release should have a maint branch so we can backport hotfixes easily
> master ~= RC for us

**Comment by TMiguelT** [comment]
Perhaps we could have a dev branch that we all PR/commit to, then when we're ready for release we rename that dev branch to the release number and then merge to master. Then we create a new dev branch and start over. 

Although personally I don't think we need release branches. I think a dev branch we periodically merge is fine. If we hotfix then everyone can just update to the latest version. It's not like we need a Cockatrice LTS. And we can us CIs to build the master and also github's release feature to mark where in the master we made releases (each merge from the dev branch)

**Comment by ZeldaZach** [comment]
I see no real reason to have branching like described above. I think we can work on our release schedule internally to have it publish a little more frequently (Such as monthly)

**Comment by ZeldaZach** [comment]
Done?
