### ISSUE TITLE
sign up

### ISSUE THREAD

**Issue by Echo-ult** [Cockatrice/Cockatrice#1754]
During sign up and sign in the servers are not found or do not exist and will have me attempt to reregister time and time again.

**Comment by ctrlaltca** [comment]
This misses some basic data:
 * the cockatrice version you are using, and the OS version
 * what server you are trying to connect on ("the servers" means all and nothing)
 * the exact error message ("are not found or do not exist" means nothing)
 * "and will have me attempt to reregister time and time again." makes me think you are getting some precise error message explaining what's going on, can you tell us?
