### ISSUE TITLE
Some parts of the app doesn't allow to highlight text on Windows

### ISSUE THREAD

**Issue by LethalPigeon7** [Cockatrice/Cockatrice#1762]
I can't copy the text from in-game windows, such as the "about" menu or the "card info" tab both in game or in deck editor (both card text and other qualities like name or card type). Especially confusing with card text since it can randomly be selected unlike the others, but trying to copy it doesn't work.  
This bug isn't the end of the world, since it's simply a matter of inconvenience but it comes up a few times a day, it'd be swell if it were to be fixed.

**Comment by ZeldaZach** [comment]
Can you show with pictures what the exact issue is?

**Comment by LethalPigeon7** [comment]
No, all I can do is perfectly describe it like I have. This isn't a matter of laziness, this is a matter of screenshots just being an inferior way of describing this specific problem, not sure how I could use them. When I select things and press ctrl+c, they do not get loaded into clipboard. Some things cannot even be drag selected. I noted the 2 biggest and only examples I know, the "about" window, and the "card info",,, subwindow or whatever its called in game and in deck editor.

**Comment by LethalPigeon7** [comment]
Actually I tested it and it seems it does try to load it into clipboard, since it deletes whatever was in there previously, so when I press ctrl+V it pastes nothing.

**Comment by ctrlaltca** [comment]
The default action for ctrl+c in the deck editor is to copy the actual content of your deck into clipboard (the same as ```Deck Editor Menu → Save deck to clipboard```). You can override this from the settings: ```Shortcuts → Main Window | Deck Editor → Save deck (clipboard)``` (last one bottom right)

**Comment by ctrlaltca** [comment]
I agree it's strange (let's say counter-productive) to overwrite such common key combinations with different actions. This problem has been already reported in another issue, and a fix was postponed for when we had configurable shortcuts working.
Now that they are working, we could change the default shortcuts for load / save deck to clipboard to something better, like ctrl+shift+c / v.

**Comment by Daenyth** [comment]
> change the default shortcuts for load / save deck to clipboard to something better, like ctrl+shift+c / v.

:+1:

**Comment by LethalPigeon7** [comment]
This isn't limited to the deck editor... the problem is in-game as well.

**Comment by tooomm** [comment]
But why is it not possible to highlight text in some parts of the program at all?
(e.g. from the `About Cockatrice` dialog to get that commit number...)

**Comment by Daenyth** [comment]
@tooomm I select text in `About Cockatrice` to copy (osx/qt5)

**Comment by Daenyth** [comment]
> This isn't limited to the deck editor... the problem is mid-match as well.

What's the specific in-game behavior?

**Comment by LethalPigeon7** [comment]
While it's nice knowing that you can copy from the info menu, and it therefore isn't a "global" problem, I can't, and neither can toomm. It would also be handy to be able to highlight from the card info window. Currently the only part I can highlight and therefore copy is "text", but not "name" (or "card type", "color(s)" etc.).
By mid-match problem i was reffering to not being able to copy from "text" in "card info" while in a room. This is no longer a problem on the current version, I may have made a mistake. Still, the problem with the help section and anything but text from card info prevails.

**Comment by Daenyth** [comment]
I wonder if it's a qt thing

**Comment by tooomm** [comment]
@ctrlaltca had some more knowledge and even two potential ways to fix it... we talked about it on gitter, but we missed to left the notes here:

>ctrlaltca
http://stackoverflow.com/questions/32589776/qmessagebox-you-can-select-text-from
i suppose this is "default off" on windows
or, we could use http://doc.qt.io/qt-4.8/qmessagebox.html#detailedText-prop
>
>tooomm 
ok great, at least we know the problem and what to look at for #1762
which one do you think is more viable? the TextSelectableByMouse flag or the detailedText ?
>
>ctrlaltca
the one that works 
the first is easier, but i'm not sure it will work
the second is a bit more intrusive, but should be safer
