### ISSUE TITLE
Card pictures don't load.

### ISSUE THREAD

**Issue by Reriiru** [Cockatrice/Cockatrice#1765]
I'll provide pictures to better illustrate.
0st: http://i.imgur.com/jpwWUM2.png - System in question.
1st: http://i.imgur.com/wNptxwD.png - Freshly reset card database and picture folder. Cockatrice just rebuilt after the problem occurred. As you can clearly see the "Download card pictures on the fly" option works perfectly well - there is a picture in the folder, and the software can't recognize that there is. After reseting the software problem persists. 
2nd: http://i.imgur.com/FxM5pqV.png - Everything reset yet again, same cockatrice build, restarted the software in this exact order:
- Toggle download off.
- Reset folders.
- Turn Cockatrice off.
- Extracted pics.rar
- Run Oracle.
- Run Cockatrice.
(Pics folder from my friends client.)

So it does not matter what I do, Cockatrie fails to recognize pictures, I've tried various combinations of the order above. If there is something I did wrong - please do tell.

**Comment by skwerlman** [comment]
What version of cockatrice are you using?

Does 2789e0df1917ead988ee1f83ed200f3c72556a5d work?

Seems related to #1721

**Comment by Reriiru** [comment]
I am using the latest (I think) 36c3536 (2016-01-15).

I will try using the older one and see how it works. Any other versions you would recommend to test?

**Comment by Reriiru** [comment]
Okay, 2789e0d didn't work. Has the same issue. Didn't make a screenshot, but it's exactly the same - cards are there, but no images.

What worked perfectly is the latest release version. 
Here is the screenshot: http://i.imgur.com/3J8MtbO.png
Also, the version display broke after installing 2789e0d don't know where that came from. Possibly something with make install, pretty sure that correctly uninstalling the software would fix this. Note to self: never use make install again.

Please give me another good version-candidate to test, so we can pinpoint the problem.

**Comment by ctrlaltca** [comment]
If you already succeeded in compiling and installing cockatrice, can i ask you to compile in debug mode (``` cmake .. -DCMAKE_BUILD_TYPE=Debug ;; make ;; make install```) and run cockatrice from a terminal? You will see a lot of debug messages related to card loading from disk / download that could help in troubleshooting the issue.

**Comment by Reriiru** [comment]
So I did. The result: http://pastebin.com/L4b3iCUJ
Gotta be installing the working version now.

**Comment by Daenyth** [comment]
@Reriiru Are you familiar with using `git bisect`? It's a tool in git for exactly this - pinpoint which commit introduced/fixed a problem. We can walk you through using it on our gitter chat https://gitter.im/Cockatrice/Cockatrice

**Comment by kdoomsday** [comment]
I'm experiencing the same situation. According to git bisect, the first bad commit is 4d7795ca3af041c3deaf6119eaea90bab0bdc1c4

**Comment by Daenyth** [comment]
cc @ctrlaltca, it looks like it's related to the picture loading changes.

**Comment by ctrlaltca** [comment]
So, i investigated the issue and will come back with a patch shortly.

**Comment by ctrlaltca** [comment]
I've opened a PR with a fix; @Reriiru and @kdoomsday can you please test https://github.com/Cockatrice/Cockatrice/commit/133693d9ce8a4a7ad0dad27253b1d902e6fcc59d and see if it fixes the problem for you?

**Comment by grickit** [comment]
Been following this issue since Wednesday. This pull request fixed it for me.

**Comment by kdoomsday** [comment]
That fix works for me too.
