### ISSUE TITLE
"custom" tokens do not work

### ISSUE THREAD

**Issue by LethalPigeon7** [Cockatrice/Cockatrice#1768]
Poor wording, can't think of a better one, what I mean is when I create a token of a card that doesn't exist (examples: "lol", "take 1 dmg", "19") it looks like a morph, I can see the card back, and shows nothing (not even the name) in the card info window when I mouse over it.
This is relevant (mainly, not only) in MP EDH games, where players create a token named after their dice roll to make the beginning of the game smoother. The tokens other people make look like morphs to me as well.

**Comment by Daenyth** [comment]
This sounds like a regression. Normally tokens are just color blocks like a card missing an image. Can you include a screenshot?

**Comment by LethalPigeon7** [comment]
![image](https://cloud.githubusercontent.com/assets/7950438/12530492/21dbe128-c1e1-11e5-8c47-2f3ae48d1fb6.png)
![image](https://cloud.githubusercontent.com/assets/7950438/12530497/43006dd8-c1e1-11e5-9f97-e8fd4af132a7.png)
![image](https://cloud.githubusercontent.com/assets/7950438/12530503/6fb243ec-c1e1-11e5-8f18-aa7aa7b5a10b.png)
Probably a mistake somewhere on my side, but I can't assume that, also it'd be swell to know how to fix it.

**Comment by ctrlaltca** [comment]
Sounds related to the "pixmap loader" change i merged recently. I will investigate it asap.

**Comment by tooomm** [comment]
Yes, same for me... it used to be just a plain colored areas instead the card background!
![token](https://cloud.githubusercontent.com/assets/9874850/12686411/c88c3df0-c6c9-11e5-8195-710125b77729.png)

**Comment by ctrlaltca** [comment]
Tagging this as "solve before january release"

**Comment by radioactivehazards** [comment]
Hey pigeon, where did you get that theme? i like it

**Comment by camaroman86v6** [comment]
I'm on version 49c22f3 and I am still experiencing this problem. Any custom named token I make is generated with no name and goes in the lands section by default.

**Comment by Daenyth** [comment]
I ran a git bisect and came up with this commit as the probable cause: e721280bc096d0dda705246b5caa2f8ec727d3d1

```
# bad: [c917a6c27204dd473dd9baaaa0ef0f23c83df91a] Merge pull request #1722 from ctrlaltca/rev-related
# good: [d55e44ea602973f4fb2f58a27dc7d8f17da1abef] Merge pull request #1558 from Cockatrice/revert-1556-carddatabase_changes
git bisect start 'master@{2015-12-31 00:00:00}' '2015-09-24-Release'
# good: [a07b72a0315a0dd0d3f0895805c2620f0392079f] Merge pull request #1699 from ctrlaltca/fix_1687
git bisect good a07b72a0315a0dd0d3f0895805c2620f0392079f
# good: [db8548521c3ec128f56eab74b283bf15e847977c] Merge pull request #1707 from ctrlaltca/fix_1703
git bisect good db8548521c3ec128f56eab74b283bf15e847977c
# good: [4e17014ebf7f69f586f843f736a4b41fe30062e0] Merge pull request #1714 from ctrlaltca/fix_1598
git bisect good 4e17014ebf7f69f586f843f736a4b41fe30062e0
# bad: [f03051b6cfad75c4065b33ed1647dc9b19582efa] Merge pull request #1642 from ctrlaltca/dont_merge_this_yet
git bisect bad f03051b6cfad75c4065b33ed1647dc9b19582efa
# good: [aebc18fc3f2043a4bd47076a0bd2a9c030e7705b] Merge pull request #1717 from ctrlaltca/fix_1716
git bisect good aebc18fc3f2043a4bd47076a0bd2a9c030e7705b
```

**Comment by Daenyth** [comment]
cc @ctrlaltca ^

**Comment by Daenyth** [comment]
But given that it was a PR merge I'd be suspicious of any commits on that branch
