### ISSUE TITLE
Face Down Exile

### ISSUE THREAD

**Issue by dev-id** [Cockatrice/Cockatrice#1769]
Having your exile face down should be an option for a few cards including Inverter of Truth.  Would also help with other non-mtg games to have a second face-down pile.

**Comment by Daenyth** [comment]
Unfortunately this is going to need some fairly wide-ranging changes to the codebase and it might not happen until we get more generic game support.

**Comment by Q3CPMA** [comment]
Hello, I might add that Scroll Rack also needs this.

**Comment by ebbit1q** [comment]
this should be implemented in #1740
