### ISSUE TITLE
Filter cards by format legality

### ISSUE THREAD

**Issue by LethalPigeon7** [Cockatrice/Cockatrice#1771]
When wanting to brew EDH I can do "and not color X; Y; Z;" + "and not text {X}; {Y}; {Z};", and as tedius as that is, it works, and is still less annoying than going over to gatherer and having to look up each card twice. There is no such workaround for pauper. In a vague effort to be helpful I can think of 2 solutions:
A) Add a rarity filter, which is really useless 99.9% of the time unless one is brewing pauper, but could be easier to implement.
B) Add a format filter, which is generally insanely useful for everyone everywhere, but sounds a lot harder to implement.

**Comment by Daenyth** [comment]
I'm not sure we store rarity information right now, but we could.

How are cards printed at multiple rarities handled? I could just do "and rarity = common" would include a card if any printing was common, and then "and not rare" would exclude cards ever printed at rare

**Comment by Psithief** [comment]
This has been discussed quite a bit already. In short, a rarity filter is the **wrong** method for searching for cards valid in Pauper.

#215
#492
#1644

Some of my earlier thoughts:

> Perhaps we wait for a generalised 'format' support solution, where Cockatrice can just download prepared format lists such as these; assuming that looking up a list is quicker than recreating it from the raw data each keystroke.

> Actually adding that kind of quirky format support to the application directly doesn't seem efficient enough to me.

**Comment by Psithief** [comment]
Colour identity is just a field in mtgjson now. Just needs:
* updating Oracle to parse it 
* updating the cards database format to allow it
* adding the filter

**Comment by LethalPigeon7** [comment]
I did try to offer 2 solutions, and from a user standpoint a terrible and messy short-term implementation of either would be a million times better than nothing. Just to answer the question, Daeynyth, what you said is precisely what I had in mind, if one of the prints would count for a filter the card would show up. One card would have multiple rarities stapled to it, or if that was a lot easier, just the lowest one.

**Comment by Daenyth** [comment]
That's something we would have to do

**Comment by tooomm** [comment]
There is a `Legality` field in mtgjson as well... just in the extended version though!
And it doesn't include Pauper or other common formats as far as I know.

In general I understand and follow @LethalPigeon7 point in 
"filter for rarity (combined with others) let's you find most stuff needed for a special environment". 

Legalities are just a special case or preset of filters which needs to get maintained (frequently!) and kept up to date to be useful. Which sounds problematic to me.
If you know the given rules/restrictions you could easily create a set of filter for a special legality by yourself.

Color Identity would be an important addition for the EDH legality.
While rarity is one for Pauper (and maybe others?)
I see the problem with changed/multiple rarities though... but nothing that can't be handled!?

Filters > Legalities :+1:

**Comment by Daenyth** [comment]
I think it's not unreasonable to include legalities in the cards.xml format.

Honestly at some point it'll probably make sense to just switch to using the json format directly, perhaps with augmentations, instead of using the xml

**Comment by LethalPigeon7** [comment]
Oooh, possibly stupid question, but could we have user created formats? Where someone makes a set of filters and then saves it for himself (and ideally for anyone) to get back to. This would still not solve formats which care for rarity, but Id happily go through and filter out all the sets (il)legal in modern and then filter out all the bans,  and definitely wouldnt mind updating it every X years it gets changed. And that's the most problematic format when using this theoretical messy method. Not to mention that it would allow for easy sharing and building of very uncommon formats. Say I want to play a format few people know, or even make one up, this gives me an easy way of letting me (and ideally people I want to get involved) make decks easily.

**Comment by Daenyth** [comment]
> Oooh, possibly stupid question, but could we have user created formats?

This is the design I've had in my head, but as I started writing this out I realized that maintaining a format as a first-level entity kind of sucks because you either need to restrict the power (and be unable to express things like tiny leaders or pauper), or you end up just having filters by a different name. I think stored filters are a better approach since they should be able to fully express any format, we just need a way to serialize the filter tree and read it back out (not too hard).

We can certainly maintain a pre-set of stored filters on github like we do with tokens.

**Comment by LethalPigeon7** [comment]
Thats pretty much what i had in mind. Formats are really just a preset of filters after all. The question is how hard is it for me to make one, get to the established oes, and get to one a friend made.

**Comment by Daenyth** [comment]
Actually, dup #215 at this point now that rarity filter is implemented.

**Comment by Scapegoat-Tom** [comment]
IS anyone working on making this work?

**Comment by tooomm** [comment]
@Scapegoat-Tom you might want to go to the referenced open issue: #215
But I don't think anybody is working on this, our card database doesn't know about format `legalities` yet because we only utilize normal data (no extra fields) from mtgjson.
Check the documentation of our card data source: https://mtgjson.com/documentation.html

Extras are also needed for https://github.com/Cockatrice/Cockatrice/issues/528 or https://github.com/Cockatrice/Cockatrice/issues/1876

**Comment by Scapegoat-Tom** [comment]
@tooomm fair enough, maybe an ability to save filters (i filter only the standard sets for deck building) would be a good work around since the mtgjson doesn't support formats. any thoughts?

**Comment by tooomm** [comment]
>since the mtgjson doesn't support formats

mtgjson does know about formats and have a special `legalities´ field as mentioned (and linked) above.
We just don't use that information yet...

Anyway, this closed ticket is not the right place for discussions, suggestions or other requests.

**Comment by Daenyth** [comment]
> Anyway, this closed ticket is not the right place for discussions, suggestions or other requests.

To be more clear, discussion is welcome, but let's put it into the open ticket: #215
