### ISSUE TITLE
Duplicate server log entries

### ISSUE THREAD

**Issue by woogerboy21** [Cockatrice/Cockatrice#1773]
So im seeing something very odd in the server logging. Did someone put something in that would cause a rewriting of something that some one said in a room to the logs over and over with in the actual server.log file that is written? What I mean by this is I see a user say this in the room:
```
dSJFIBdl;s
```
But in the logs this is written:
```
Sun Jan 24 05:04:12 2016 247ebd0 [Command_RoomSay.ext] { message: "dSJFIBdl;s" }
Sun Jan 24 05:04:12 2016 "dSJFIBdl;s"
Sun Jan 24 05:04:25 2016 "dSJFIBdl;s"
Sun Jan 24 05:04:31 2016 "dSJFIBdl;s"
Sun Jan 24 05:04:31 2016 "dSJFIBdl;s"
Sun Jan 24 05:04:32 2016 "dSJFIBdl;s"
Sun Jan 24 05:04:52 2016 "dSJFIBdl;s"
Sun Jan 24 05:04:53 2016 "dSJFIBdl;s"
Sun Jan 24 05:05:06 2016 "dSJFIBdl;s"
```
The logs stored in the db are correct listing only the user saying it a single time

I cant say I have looked at the actual physical log in a long time so I dont know when started happening but noticed it while reviewing the logs post a recent server crash.

**Comment by ctrlaltca** [comment]
There's definitely something fishy going on here, the strangest part being the time between the logged messages.
I've tried to reproduce this on current master, but i've not been able to. Did you compile from clean master or added any PR / commit in?

**Comment by woogerboy21** [comment]
The server is running the dec 20th build (https://github.com/Cockatrice/Cockatrice/commit/4e17014ebf7f69f586f843f736a4b41fe30062e0) with #1717 rolled in prior to it being committed to master.  Other than that I have no custom branches pulled in the base nor am I doing anything crazy like log filtering.

**Comment by woogerboy21** [comment]
Looking at the logs, the only time chat conversations seem to be repeated is post a RoomSay event.
GameSays are not repeating.
