### ISSUE TITLE
Don't have pictures

### ISSUE THREAD

**Issue by Kalso12** [Cockatrice/Cockatrice#1781]
I don't have a single picture of any card just see the back of every card and i can't play like that
please help me i drove crazy over that allready.

**Comment by Daenyth** [comment]
What OS are you on, and what version from "About Cockatrice" in the help menu?

**Comment by Kalso12** [comment]
Win 10 d55e44e (2015-09-23)

**Comment by ZeldaZach** [comment]
Do you have "download cards on the fly" ticked?

**Comment by Kalso12** [comment]
picture cache size: 64mb
"download card pictures on the fly" V
"download card pictures from custom URL: 
http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!cardid!&type=card"  V

**Comment by ZeldaZach** [comment]
Increase from 64 to 2047

**Comment by Daenyth** [comment]
We should add a log statement at least when picture loading fails from low cache size. Maybe an alert once per app run.

**Comment by ctrlaltca** [comment]
The "64MB cache size problem" has been resolved in #763. 
Anyway, 64MBs are enough to cache at least an hundred card images, so i'm afraid this was not the original problem that @Kalso12 experienced.
Maybe gatherer was down? We'll never know.

**Comment by Daenyth** [comment]
The new log viewer will help us debug issues like this in the future.
