### ISSUE TITLE
Old Database Version?

### ISSUE THREAD

**Issue by KOnki99** [Cockatrice/Cockatrice#1782]
Hello

Due to the fact that dataversion 3.0 makes it impossible to export custom sets from magis set editor I would like to ask if abyone has older client version that operates using oldder database version?

Thank you.

**Comment by Daenyth** [comment]
Can you explain more about what makes it impossible to export custom sets? The format hasn't changed greatly, there shouldn't be a problem.

**Comment by KOnki99** [comment]
Im' sorry my bad, I didn't mean it's impossible to export them from MSE. Export option in MSE works fine, however when I try make cockatrice "read" the exported xml file (database version 1 or 2) it keeps saying that my "database is too old" and opens oracle every time making me change xml. It can't read it.

I don't know what do you mean when you say it hasn't changed greatly, cause I don't have a clue when it comes to programming but when opening xml files the 3.0 version looks whole lot dofferent, like continous text without any spaces, like, whereas older database-related xml files looked organized when opened.

**Comment by ctrlaltca** [comment]
can you please attach a file created with MSE that's not loading in cockatrice?

**Comment by KOnki99** [comment]
There
 
 
W dniu 2016-01-30 09:36:43 użytkownik ctrlaltca <notifications@github.com> napisał:
can you please attach a file created with MSE that's not loading in cockatrice?
—
Reply to this email directly or view it on GitHub.
 
 
 
 
--
Regards Krzysztof Domaszewski

**Comment by KOnki99** [comment]
I sent it via e-mail, can't attach it here.

**Comment by Daenyth** [comment]
You can upload it to gist.github.com and put the link here

**Comment by KOnki99** [comment]
File attached 
 
 
W dniu 2016-01-30 00:05:32 użytkownik Gavin Bisesi <notifications@github.com> napisał:
Can you explain more about what makes it impossible to export custom sets? The format hasn't changed greatly, there shouldn't be a problem.
—
Reply to this email directly or view it on GitHub.
 
 
 
 
--
Regards Krzysztof Domaszewski

**Comment by KOnki99** [comment]
I sent it to you too Daenyth

**Comment by Daenyth** [comment]
I didn't get it. Regardless, everyone will be able to see it and help if
you upload it to gist

**Comment by KOnki99** [comment]
https://gist.github.com/KOnki99/d7e3c5f14e9c7a6c711f

**Comment by KOnki99** [comment]
Is that fine?

**Comment by Psithief** [comment]
> continous text without any spaces

`cards.xml` has unix-style end of line characters, but most Windows applications expect something different.
Most of the format is still the same. You should try changing the second line from `<cockatrice_carddatabase version='2'>` to `<cockatrice_carddatabase version='3'>` and see what happens.

According to the database format rules [`cards.xsd`](/Cockatrice/Cockatrice/blob/master/doc/cards.xsd), you must have a name & longname for each set and must have a name, manacost, type, tablerow and text for each card. Your file has all those things, so it should be fine.

**Comment by KOnki99** [comment]
omfg it works, feel damn stupid for not trying this myself....thanks man

**Comment by Daenyth** [comment]
If you know who made the MSE plugin to export it, tell the it needs to be updated
