### ISSUE TITLE
Ubuntu .debs and git compilations assume Unity environment

### ISSUE THREAD

**Issue by daryltucker** [Cockatrice/Cockatrice#1783]
I ran into an issue where the .debs provided at https://cockatrice.github.io/, and the compilation of the source both gave me a UI without any main menu (Cockatrice, Game, View, Help).  I was forced to login with Unity, which is not my preferred environment, as the menu was only accessible via it.

Is it possible to detect this automatically or give users a keyboard shortcut to bring up the main menu somewhere else within the UI?
On my Archlinux install, I see the menu, so I'm wondering if there is a configuration option at compilation time that I can take advantage of to see the menus?

Thanks for your help with getting Cockatrice running with an in-window menu on Ubuntu systems that chose not to run Unity.

**Comment by ctrlaltca** [comment]
I'm not sure if this is related, but if you have a package named ```appmenu-qt5```, i'd try removing it.

**Comment by Daenyth** [comment]
@ctrlaltca Can we mark the built package as conflicting with appmenu so it suggests removal?

**Comment by ctrlaltca** [comment]
Closing since the longstanding problems affecting appmenu-qt5 seems to be resolved in latest LTS 16.04

**Comment by Daenyth** [comment]
🎉
