### ISSUE TITLE
Missing information in the client updater

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#1784]
Addition to #1727 

Tell the user **which version he is about to download** and **better describe what the tool is actually doing**.
Otherwise he might get confused when he reads the information about different versions on the download site. (if he clicks on the `Go to download page` button for example)

**Comment by Daenyth** [comment]
:+1:

**Comment by Daenyth** [comment]
This is probably easy, I'll have a look after I finish #2002

**Comment by tooomm** [comment]
There should be a link to the github changelog as well:
https://github.com/Cockatrice/Cockatrice/releases/latest

Or a dialog popup containing with that information.

**Comment by tooomm** [comment]
With https://github.com/Cockatrice/Cockatrice/pull/2362 we now have more information on the downloaded file:
![dl-info](https://cloud.githubusercontent.com/assets/9874850/23833648/e0bb1b88-0748-11e7-99da-7ec1137e064e.png)
