### ISSUE TITLE
Putting cards on the bottom of your library in a random order (Cascade)

### ISSUE THREAD

**Issue by Sir-Binks** [Cockatrice/Cockatrice#1785]
I think this is a "Defect - Game Rules Compliance".

At the moment it is not possible to accurately resolve a Cascade trigger.
The cards revealed and not cast can not be put on the bottom of your library in random order.
Especially relevent if higher numbers of cards are flipped and you would be almost stacking your deck.

702.84. Cascade

702.84a Cascade is a triggered ability that functions only while the spell with cascade is on the stack. “Cascade” means “When you cast this spell, exile cards from the top of your library until you exile a nonland card whose converted mana cost is less than this spell’s converted mana cost. You may cast that card without paying its mana cost. Then put all cards exiled this way that weren’t cast on the bottom of your library in a random order.”

**Comment by ZeldaZach** [comment]
The random order aspect seems to be the problem here. It's an interesting discussion

**Comment by Sir-Binks** [comment]
Also anything else making resolving a cascade trigger more enjoyable than repeatingly dragging single cards onto the table would be nice, but is not the primary issue here.

**Comment by Daenyth** [comment]
I swear there's already a ticket for this exact issue.

**Comment by Daenyth** [comment]
Dupe #673

**Comment by Sir-Binks** [comment]
@Daenyth It's about a missing function in the game. Putting the cards back on the bottom in random order. That's not what the referenced issue was about and it is nowhere mentioned in the title or the first posts. Therefore I (respectfully) suggest keeping this one open, as it is clearer and focused on that.

**Comment by Daenyth** [comment]
@Sir-Binks That issue isn't as nicely worded perhaps, but it's still about not being able to cascade. It has more discussion which is why I'm closing this one
