### ISSUE TITLE
[Gatewatchers]  application was unable to start correctly (0xc000007b)

### ISSUE THREAD

**Issue by radioactivehazards** [Cockatrice/Cockatrice#1788]
Downloaded client, and now cockatrice no longer works????   i keep getting a box that says:

The application was unable to start correctly (0xc000007b). Click ok to close.

I have installed it 6 times. no change. HELP?!

**Comment by zebington** [comment]
See if any of these suggestions will help: http://www.tomshardware.co.uk/answers/id-1991597/windows-bit-error-0xc000007b.html
It's probably an issue with .NET Framework or C++ redist.

**Comment by Daenyth** [comment]
We might need to point people at a new redist now that builds happen on appveyor instead of wooger's box. Might be using a different version than he was.

**Comment by Daenyth** [comment]
@radioactivehazards Which installer did you run?

**Comment by radioactivehazards** [comment]
cocktatrice-gatewatchers-win-qt5.exe   and when i got to .net they keep directing me to windows 10 downloads. I am not sure my machine can do win 10. i am used to win 8 atm so i rather stay with what works.

**Comment by radioactivehazards** [comment]
found the .net link i need, doing that now

**Comment by Daenyth** [comment]
Yes, please let us know if that works. @ZeldaZach We may need a new troubleshooting wiki entry and a note in the release notes

**Comment by radioactivehazards** [comment]
Will update as soon as it installs, and ill reinstall cockatrice after the .net framework is done.

**Comment by radioactivehazards** [comment]
did the .netframe   had to restart machine, started machine, reinstalled cockatrice...No change

**Comment by radioactivehazards** [comment]
.net framework 4.6.1   did not help

**Comment by radioactivehazards** [comment]
useless.

**Comment by Daenyth** [comment]
cc @ctrlaltca

**Comment by radioactivehazards** [comment]
Well i am glad that i was able to give other people cool features. when you get one that works for me ill try it. until then i guess ill stick to expeditions

**Comment by radioactivehazards** [comment]
I swear this always happens every time you guys get a new build.

**Comment by woogerboy21** [comment]
So far I can't reproduce the problem.  Sounds like a dependency on that particular machine that isnt correct.  I would try uninstalling and reinstalling the MSVC2013 runtime files.
MS Link: https://www.microsoft.com/en-us/download/details.aspx?id=40784
WW-Link: http://www.woogerworks.com/files/vcredist_x86_2013.exe (x86)

Is appveyor building 32bit or 64bit clients?

**Comment by radioactivehazards** [comment]
i do not understand your post even bro. ms or ww?   i am on the 86 client i think not sure which that falls under.

**Comment by woogerboy21** [comment]
MS = the direct link to the microsoft runtime files off microsofts site.
WW is a copy of the runtime installer i make available for users if they have trouble pulling it from microsoft.  You will need to have the appropriate runtime files installed for the client to operate properly  If you are running a 32bit client, you will need the x86 runtime files.  If you try and run the 64bit client you will need to have the x64 bit runtime files installed for it to work.

**Comment by radioactivehazards** [comment]
i am downloading the vcredist_x86_2013 and ill do that then reinstall the gatewatchers see if it works

**Comment by woogerboy21** [comment]
I only make the x86 (32bit) version of the runtime files available from the woogerworks site.  If you need the 64bit youll have to get it from the MS site.  Im not 100% certain if the appveyor builds are 32bit or 64bit.  I would guess that the qt4 is 32bit, but qt5 could be either.

**Comment by radioactivehazards** [comment]
tried the link you did, the ww one and i had no install option i had repair and uninstall, i repaired and restarted machine then redownloaded gatecrashers and nothing still.

**Comment by woogerboy21** [comment]
Odd.  So nothing meaning its throwing the same error.  Or nothing as in there is no more error but it doesnt run?

**Comment by woogerboy21** [comment]
Wait wait wait, what OS are you on?

**Comment by radioactivehazards** [comment]
nothing as in nothing new changed, i am os windows 8.

**Comment by woogerboy21** [comment]
Just 8 or 8.1?  If you just on 8 there is a good likelyhood you will need to run the qt4 version of the client.  Happen to try that version yet?

**Comment by radioactivehazards** [comment]
not sure where to check, that and no i have not tried the qt4 version at all

**Comment by woogerboy21** [comment]
If you wouldnt mind trying it and let us know that would be helpful

**Comment by radioactivehazards** [comment]
windows 8, does not say . anything so i assume 8 would be correct, just checked control panel

**Comment by radioactivehazards** [comment]
doing so now. installing it and then ill see if anything changes.

**Comment by radioactivehazards** [comment]
ok did so and i think it worked, is there a sure fire way to know?

**Comment by woogerboy21** [comment]
The rule of thumb i basically go by is windows 8 and older = qt4 .  Win 8.1 + qt5.
Around windows 8 is when qt dropped support for various proc support and microsoft seems to have used older runtimes in the OS.  8.1 went with newer runtime components which also caused some of the older hardware tech to loose support.  Thats why you probably can't run win 10.  AMD based proc's are showing there core technology age at this point sadly.  If you own one of those you may want to consider jumping over to a more modern intel.  Thats usually the component that has the most trouble with the more modern software.

**Comment by radioactivehazards** [comment]
Pretty sure we good now, i loaded a game and made a walker emblem of the "create related card" toy so thats good. now to figure how to set these custom sounds

**Comment by woogerboy21** [comment]
:+1: Good to hear.

**Comment by Daenyth** [comment]
Instructions for custom sounds are on [Sounds Themes](https://github.com/Cockatrice/Cockatrice/wiki/Sound-themes) wiki page

**Comment by Daenyth** [comment]
@radioactivehazards Just to be clear, did it finally work for you with the -qt4 installer or the -qt5 installer?

**Comment by radioactivehazards** [comment]
the qt4 worked finally

**Comment by Daenyth** [comment]
ok, there was some confusion on our side - we mislabeled them. The -qt4 was 32bit and -qt5 was 64bit, but both were built with Qt5
