### ISSUE TITLE
Numbered tokens

### ISSUE THREAD

**Issue by radioactivehazards** [Cockatrice/Cockatrice#1789]
Maybe it is something wrong with the token xml but now when i go to make number tokens for my dice rolles in edh all i get are blank tokens.

**Comment by ctrlaltca** [comment]
Do you maybe mean the same thing as #1768 ?

**Comment by radioactivehazards** [comment]
yes exact same thing

**Comment by ctrlaltca** [comment]
Ok, i'll merge the tickets then; i'm already working on this issue, expect a fix in a few days.
