### ISSUE TITLE
where do i input activation token?

### ISSUE THREAD

**Issue by KingMax87** [Cockatrice/Cockatrice#1791]
I looked everywhere and it doesnt prompt me or give a like to input this,  thank you

**Comment by ctrlaltca** [comment]
The activation token is not used to "activate" cockatrice itself, but to enable your user to connect to a specific server. Just try to connect to the server with the username you just registered, and if it needs activation cockatrice will ask for the token. If you are already able to connect to the server with your username, there's no need for the activation token anymore.

**Comment by KingMax87** [comment]
I tried that and got an unknown error -1 message

**Comment by ctrlaltca** [comment]
What version of cockatrice are you using, and what server are you connecting to?
You can see the version from the "about cockatrice" menu.
I suppose you are using an old version. You can get an updated one from https://github.com/Cockatrice/Cockatrice/releases

**Comment by KingMax87** [comment]
I just downloaded the new one from the site today but ill try that one and see what happens

**Comment by Daenyth** [comment]
@KingMax87 `unknown error -1` means you are on an old version, not the new one.

https://github.com/Cockatrice/Cockatrice/wiki/Troubleshooting#unknown-error--1-message-upon-login

**Comment by Daenyth** [comment]
If you need further help after running the updated version please reopen this
