### ISSUE TITLE
Game Tab Doesn't Save Configuration

### ISSUE THREAD

**Issue by ZeldaZach** [Cockatrice/Cockatrice#1792]
When you  move elements around in a game tab, they don't store that config when you open a new game up. This gets annoying as the default isn't even "default" because if you hit reset layout it'll change.

**Comment by ctrlaltca** [comment]
IIRC the layout gets saved only when you close a game, so it will be applied on new games from that moment on. This can be surely improved.

**Comment by ZeldaZach** [comment]
Not even, it doesn't save period.

**Comment by JineteDV** [comment]
Same problem

**Comment by ctrlaltca** [comment]
@ZeldaZach can you test https://github.com/ctrlaltca/Cockatrice/commit/058b913455b33d11960beaaa0a363847e40dcb95 ?

**Comment by ZeldaZach** [comment]
@ctrlaltca Tested and it's pretty much working, except a few small issues.

1) When you reset the layout, it does put everything back in the correct location and height, but the widths will remain whatever the user edited them to be.
<img width="940" alt="screenshot 2016-02-09 21 36 37" src="https://cloud.githubusercontent.com/assets/7460172/12937291/44095572-cf75-11e5-9785-04a9a3292dc7.png">

2) The deck editor (yes, maybe unrelated) seems to change the widths of the columns whenever opened to some kind of minimum that's not enforced (Ex: I can make the column width very small and then it bumps back up to a set width). This does not happen when you make the columns very large.

<img width="498" alt="screenshot 2016-02-09 21 39 48" src="https://cloud.githubusercontent.com/assets/7460172/12937341/b4b6f0ea-cf75-11e5-890c-9355f869c9c8.png">
-Closed then reopened-
<img width="464" alt="screenshot 2016-02-09 21 39 59" src="https://cloud.githubusercontent.com/assets/7460172/12937339/aeec9b10-cf75-11e5-8a33-d1a4163b25a5.png">



3) The settings are based on the last action taken. (Ex: If you have two games open and close the chat in a game, whenever you join another game the chat will be closed by default.) Nothing wrong with this method (I like it), just pointing it out.

**Comment by ctrlaltca** [comment]
@ZeldaZach i've opened #1807, let's continue the discussion there.
Point 1 (widths on reset layout) should be fixed.
I've not been able to fully reproduce point 2; only when i move 2 dock in the same place (eg. in your pic, the "filters" and "deck" docks are in the same place), then Qt will grow the dock size to make room for the bigger of the docks.
Point 3: i know this is suboptimal, but the only other way i can think of is to require users to manually press a "save this layout as the default layout for new games" button, and i'm not sure if this would be considered easier or harder for users.
