### ISSUE TITLE
Theme Updation

### ISSUE THREAD

**Issue by radioactivehazards** [Cockatrice/Cockatrice#1795]
I do not know about you but i know me, I get bored looking at the same sleeves and table mats. so i change them around at times. I do the same with cockatrice themes.  This brings me to my issue.

If you want to update your theme you must find the image, nameit the theme you want, open cockatrice, start a local game, and you get to see what it looks like... say you hate it. Then you must close cock down, and do all that again for every image. This is a long process. Could we we kind merge the old theme process with this one?  So you can preview them easier, Maybe make it so you only have to close the game to see the new themes.

**Comment by Nightfirecat** [comment]
Having a theme editor of sorts would certainly make the process smoother and less error-prone, I agree.

**Comment by Fizztastic** [comment]
Switching to another theme and back in the options should refresh it.

**Comment by LethalPigeon7** [comment]
I think the pictures as of now are a piece of cake. What we need is a better way to edit more complicated things, like the colors of the UI and chat, I looked through the folder, and even the css file and I could not for the love of me find anything that does that.

**Comment by zebington** [comment]
@LethalPigeon7 what would you want to see in a style.css wizard? What options do you thing are needed?

**Comment by LethalPigeon7** [comment]
Colors of everything.

**Comment by Daenyth** [comment]
Dupe #1539
