### ISSUE TITLE
Downloaded new update problem

### ISSUE THREAD

**Issue by LograGx** [Cockatrice/Cockatrice#1797]
I get this message when i download gatewatchers i go to mtgjson site download the file and make it a local file go to the next screen and cant proceed past token part gets the same error message. Also if I press cancel i can open up cockatrice I just cant log on or see cards.
![error](https://cloud.githubusercontent.com/assets/17057924/12864370/9ef3306a-cc56-11e5-8476-47a85f55c12e.jpg)

**Comment by ctrlaltca** [comment]
Somehow oracle is not able to connect to the http://mtgjson.com/ website. You can trying go to that site using a browser, download the "All Sets 3.7MB" and feed it to Oracle using the "Local file" option.

**Comment by LograGx** [comment]
I don't know if you read what i said but i already done what you suggested and when I get to the token part this what happens.
,![error 2](https://cloud.githubusercontent.com/assets/17057924/12867220/b3c4fd84-ccb5-11e5-809c-6f4476a9850e.jpg)

**Comment by LograGx** [comment]
And if i click cancel and open up cockatrice this what happens I dont see cards or tokens and I cant log in either.
![error 3](https://cloud.githubusercontent.com/assets/17057924/12867286/93669000-ccb7-11e5-898f-6d93e70257d3.jpg)

**Comment by woogerboy21** [comment]
Sounds to me like your unable to connect to either the sites that host the XML data that oracle uses.  Check your network connectivity between you and the two hosts.

**Comment by LograGx** [comment]
How would I do that and i have the old install file but it wont show the tokens either I reinstalled after this didnt work the 1st time and token database wasnt working.

**Comment by tooomm** [comment]
you find the token file at this locatiokn:
https://github.com/Cockatrice/Magic-Token

**Comment by LograGx** [comment]
,I'll let you know here n a few tooomm

**Comment by LograGx** [comment]
There names show up but no images still and no network connection
![error 5](https://cloud.githubusercontent.com/assets/17057924/12867726/481404be-ccc3-11e5-9238-72748e59999d.jpg)
![error 6](https://cloud.githubusercontent.com/assets/17057924/12867748/e18d91aa-ccc3-11e5-9ae6-5dfff4ef5523.jpg)

**Comment by woogerboy21** [comment]
Once again, host not found indicates something is blocking your connection.  I would first try rebooting your pc (if its windows).  From there you will have to work your way back from your pc to what is providing you internet connectivity.  If your not the one that handles the network I would recommend talking to the person that does as there is a good likelyhood that if it was working before and is not working now either something network wise isnt functioning correctly (and needs a reboot of whatever device) or some one has put something up to prevent the connections.

**Comment by LograGx** [comment]
I understand im on my house network but I'll try rebooting and so forth but what about the images.

**Comment by woogerboy21** [comment]
The only other thing that I can think of would be DNS.  Make sure you can resolve all the names correctly.

**Comment by LograGx** [comment]
ty ill update in a few im about to leave

**Comment by tooomm** [comment]
>what about the images.


Images gets pulled from your local hard drive (if you downloaded some/all of them before manually or automatically) otherwise Cockatrice tries to download them.
If you're having trouble with your internet connection and Cockatrice/Oracle can't properly access the internet they can't work as they are supposed to and Oracle can't download card information, nor does Cockatrice can connect to a server or download images missing on your hard drive.

**Comment by Daenyth** [comment]
@LograGx Is your windows computer running a personal firewall app? Sometimes that or an antivirus might block the network connections of an app. If you just updated you might have to reset the permission, I'm not sure.

**Comment by woogerboy21** [comment]
So was this ever fixed?

**Comment by Daenyth** [comment]
Reopen if you still have the problem

**Comment by LograGx** [comment]
I apologize I never got it to work i'll just play it as is maybe the next update will work.

**Comment by Daenyth** [comment]
Try setting your DNS server to google dns (8.8.8.8 and 4.4.4.4) and see if it works then.

Also try changing the url to mtgjson.net instead of mtgjson.com (the rest stays the same)

**Comment by LograGx** [comment]
alright i will
