### ISSUE TITLE
Issue loading card images.

### ISSUE THREAD

**Issue by ifrit49** [Cockatrice/Cockatrice#1800]
Working on os x El capitan with cockatrice version cdr 40 (2016-02-07) and card images will not load. I've;
moved sets ath, dkm, dpa, hho, itp, rqs tp the bottom of the set list. 
And reset/clear download picture url. 
As per trouble shooting recommendations but no luck.  :-(

**Comment by ifrit49** [comment]
Version cddb450

**Comment by ctrlaltca** [comment]
Can you try running cockatrice from a terminal window and show us the log?

**Comment by Daenyth** [comment]
I feel like this might be a duplicate ticket but I can't find what other one it might be off the top of my head.

**Comment by Daenyth** [comment]
> Can you try running cockatrice from a terminal window and show us the log?

There's instructions for doing this on the wiki if you don't know how: 
https://github.com/Cockatrice/Cockatrice/wiki/Debugging#mac-osx

**Comment by ifrit49** [comment]
Hey Gavin,

I was about to get the log for you but when I opened tried opening cockatrice one last time it started loading the pictures. I downloaded everything while on wifi, but then went somewhere afterwards where I didn't have wifi. I thought the images where loaded when i downloaded oracle. Is this not the case? Either way now that I'm on wifi again the images are loading it seems.


________________________________

**Comment by skwerlman** [comment]
Images are downloaded on the fly, not when running Oracle

**Comment by ctrlaltca** [comment]
You need an internet connection to download images from the internet. The 30-sec download happening in oracle only downloads card names and informations, but not images.
