### ISSUE TITLE
Card animations slow/general gameplay lag 

### ISSUE THREAD

**Issue by leb0x** [Cockatrice/Cockatrice#1802]
I updated to El Capitain and since then cockatrice has been slow with animations, card response, etc. general phase changes. It started immediately after I upgraded. I tried reinstalling the software to no help.

**Comment by ctrlaltca** [comment]
What version are you using? You can get this info from the "About cockatrice" menu.
What hardware are you working on (eg: MacBook Pro 13 late 2011)? You can get this info from the Apple menu => info on this mac
Did you try reinstalling the last version from http://cockatrice.github.io/?

**Comment by leb0x** [comment]
Version d55e44e (2015-09-23) of Cockatrice I have a newer Macbook I bought
the Macbook Pro Last November.

MacBook Pro (Retina, 15-inch, Mid 2014)

2.2 GHz Intel Core i7

16 GB 1600 MHz DDR3

Intel Iris Pro 1536 MB


I have tried re downloading Cock and reinstalling the software.

**Comment by ctrlaltca** [comment]
> I have tried re downloading Cock and reinstalling the software.

So are you running the last version now?

**Comment by leb0x** [comment]
Yes.

**Comment by ZeldaZach** [comment]
Haven't heard anything on this nor have I heard this from anyone else. If still an issue pleas reopen!
