### ISSUE TITLE
Change DB to innodb, use constraints for replays

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#1805]
> Imho:
 1. move the schema to use innodb tables (better locking, more resource usage but better scalability)
 2. add the necessary constraints (read : foreign keys on cascade delete) so that we can't have eg. a "replay player access" without a "replay"
 3. implement a migration script

>  At this point we only need to delete the row in the "games" table to get everything cleaned up by mysql automatically.
We can then thinking on implementing a scheduled, configurable purge of games data older than "x" days directly from inside servatrice.

[~ ctrlaltca](https://github.com/Cockatrice/Cockatrice/pull/1803#discussion_r52504123)

**Comment by ZeldaZach** [comment]
I've discussed this with @woogerboy21 before and felt it was the right move. I highly suggest we look into this
