### ISSUE TITLE
Drop Qt4

### ISSUE THREAD

**Issue by ctrlaltca** [Cockatrice/Cockatrice#1809]
Qt4 support by Qt ended on december 2014, but was extended for another year to get a 4.8.7 version out (http://blog.qt.io/blog/2014/11/27/qt-4-8-x-support-to-be-extended-for-another-year/).
All the windows packages built by Appveyor and the Osx, Linux "release" packages built by TravisCI are already qt5 only.
Removing qt4 we could
 * clean up a lot of dead code in ```#if QT_VERSION < 0x050000```
 * remove some dirty code (like servarice's own command line parser, see #1405)
 * remove the dependency on libgcrypt
 * (eventually) remove out bundled qt-json library and move to use qt5's own library

**Comment by Daenyth** [comment]
Once the bintray builds (as qt5-only) have been out a while and we haven't seen problems, then let's go ahead on this.

Let's revisit in May.

**Comment by tooomm** [comment]
We mostly still support it due to very very old processors that not support SSE2, correct?

I found this while doing some reading with another issue on gitter:
https://github.com/Cockatrice/Cockatrice/issues/219#issuecomment-51491792
So we could move to Qt5 and even keep these old machines compatible or provide special builds on demand...

**Comment by ctrlaltca** [comment]
> We mostly still support it due to very very old processors that don't support SSE2, correct?

Reasons to still support qt4:
 * linux distros running Kde4: Qt5-based software is usable without any conflict, and they will eventually migrate to Kde5 (based on Qt5) soon;
 * Users with old, non-SSE2 processors: we could add to Appveyor a version using Qt5.2.1, the last Qt version not requiring a SSE2-based processor.

**Comment by leematos** [comment]
If I'm understanding correctly, SSE2 came out circa 2003. I'm super curious how many users are using machines from pre-2003. Going QT5, does that help to simplify the dev process? Make us faster/leaner?

**Comment by ctrlaltca** [comment]
SSE2 came out with the first Intel Pentium 4, so late 2000. AMD caught up only 2003 with their 64-bit processors.

> Going QT5, does that help to simplify the dev process? Make us faster/leaner?

We'll only avoid to maintain some dead and manually crafted code to support Qt4, and all the related dependencies, like taking care that travis builds fine with Qt4.
Going qt5 we'll also be able to use new features, like Qt5's new signal/slot syntax, which allows for compile-time checking and the usage of lambdas, or QMessageLogger.

**Comment by Daenyth** [comment]
Once we hear that >50% of the player base is on new builds I'm happy to
drop it

**Comment by leematos** [comment]
On that front @Daenyth, I don't remember, do clients report builds? (I have to assume so) And do we have that number handy?

**Comment by Daenyth** [comment]
They report the build number. Anything from this year is pretty much qt5 so once most people are on that we'll have a good indication.

**Comment by woogerboy21** [comment]
I think this is what your looking for:
Query -
```
select distinct(client_ver),count(client_ver) from cockatrice_user_analytics where last_login like '2016%' group by client_ver;
```

Results -
```
+--------------------------+-------------------+
|                          |                42 |
| ()                       |                17 |
| 0286cd3 (2015-12-11)     |                 1 |
| 064c89b (2015-09-23)     |                24 |
| 084b5c5 (2015-12-14)     |                17 |
| 0b8f52e (2016-02-28)     |               930 |
| 0c137e8 (2015-12-12)     |                 1 |
| 0c67cb6 (2015-10-09)     |                 1 |
| 0e1c26a (2015-12-19)     |                 3 |
| 0e229ad (2015-12-13)     |                 1 |
| 108ec14 (2016-02-22)     |                 8 |
| 17925ce (2016-03-05)     |               621 |
| 2789e0d (2016-01-16)     |                17 |
| 291b262 (2015-09-25)     |                 3 |
| 2b138cc (2016-04-05)     |                 5 |
| 2bf998b (2015-12-28)     |                 2 |
| 2d2958e (2016-03-21)     |                 1 |
| 2d43ab9 (2016-02-17)     |               359 |
| 323fc06 (2016-02-02)     |              1925 |
| 36c3536 (2016-01-15)     |                15 |
| 36f1536 (2016-02-14)     |               317 |
| 3ba3f1e (2016-02-27)     |               273 |
| 3c58003 (2016-03-22)     |              2542 |
| 41494b4 (2016-03-18)     |                22 |
| 43262b2 (2015-10-02)     |                 5 |
| 4691f3e (2016-04-05)     |                83 |
| 49c22f3 (2016-02-25)     |               601 |
| 4e17014 (2015-12-20)     |                 5 |
| 4e3e31c (2015-11-04)     |                 1 |
| 4f1d3c3 (2016-02-20)     |                 7 |
| 521559a (2016-03-03)     |               119 |
| 5350302 (2016-01-11)     |                10 |
| 535e19f (2016-03-18)     |               819 |
| 5577d61 (2016-01-28)     |                 2 |
| 586d580 (2015-12-13)     |                 1 |
| 5b22187 (2016-02-16)     |               121 |
| 5fcd8a7 (2016-01-28)     |                 1 |
| 613f712 (2015-10-17)     |                 5 |
| 66634c9 (2016-02-22)     |               358 |
| 696ae7e (2015-12-19)     |                 1 |
| 6a86990 (2015-09-30)     |                 3 |
| 77b9aa7 (2015-10-24)     |                24 |
| 7e6972a (2015-12-15)     |                 2 |
| 7ec3968 (2016-01-23)     |                 9 |
| 830a4c2 (2016-03-30)     |                17 |
| 8f819df (2016-02-10)     |                35 |
| 924bbb2 (2015-12-30)     |                13 |
| 93d4f78 (2016-02-10)     |               591 |
| 948a5c6 (2016-04-05)     |               577 |
| 9c4bd8e (2015-09-26)     |                 7 |
| a6ff54a (2015-11-22)     |                18 |
| b6f3630 (2016-01-24)     |                17 |
| bc79d9e (2016-02-24)     |                74 |
| bf42319 (2016-02-20)     |               386 |
| c1663d5 (2015-09-25)     |                 5 |
| c917a6c (2015-12-27)     |                 3 |
| cbea432 (2016-03-08)     |              2093 |
| cc2effb (2016-03-03)     |                19 |
| cd02df7 (2015-10-05)     |                 5 |
| cddb450 (2016-02-07)     |               495 |
| d09b75a (2015-10-01)     |                 1 |
| d16fab9 (2016-03-03)     |               245 |
| d2e731b (2016-01-20)     |                13 |
| d55e44e (2015-09-23)     |             23353 |
| d6c6b94 (2016-01-14)     |                 1 |
| d85fcfc (2015-10-05)     |                 1 |
| e68b8b3 (2015-09-22)     |                 1 |
| e94f59d (2016-03-22)     |                 2 |
| ef62261 (2016-04-05)     |                90 |
| f03051b (2015-12-26)     |                 2 |
| f217551 (2016-03-30)     |              1696 |
| f2b6285 (2015-09-23)     |                 3 |
| f31a89e (2016-02-24)     |                31 |
| f35c047 (2016-01-29)     |                33 |
| f7f9827 (2016-01-15)     |                 1 |
| fc59a33 (2016-01-14)     |                 1 |
| Guardian Turbo           |                 1 |
| unknown (git not found!) |                 5 |
| unknown (unknown)        |                 5 |
+--------------------------+-------------------+
```

**Comment by woogerboy21** [comment]
Oldest client login from version  d55e44e (2015-09-23)
```
| d55e44e (2015-09-23) | 2016-02-24 08:45:21 |
```

Newest client login from that version:
```
| d55e44e (2015-09-23) | 2016-04-07 12:13:24 |
```

**Comment by leematos** [comment]
@Daenyth @woogerboy21 What release is a "new build" as per Dae's 50% of users on new builds number? If 2015-09-23 is the oldest that's 6 months ago. Is that a "new build"?

**Comment by woogerboy21** [comment]
@leematos 
I doubt a 6 month old client is a new build.  But im not completely certain what the goal of the data is.  I was just putting in here per a request for data of client versions users have used this year.  As I mentioned to @tooomm , The numbers listed next to each build only indicates that a user has logged in some time in 2016 with that client version and has not logged in since with a different client version.  So if a user logged in back in Jan using a client and then stopped playing all together the data posted above may skew ones desired expectation to understand what "new" is.

**Comment by Daenyth** [comment]
What I mean by "new build" is a build that we know for sure never had qt4 downloads offered

I'm pretty sure the 9/23 build had a qt4 version offered; so that leaves gatewatchers as the mark to pass

**Comment by leematos** [comment]
Analyzing the data above:

39164 total logins

15532 with clients who's date string is 2/2/16 or greater.

If that's correct, ~40% of log ins this year came from a "new build". Is that a correct use of the datestrings?

**Comment by ZeldaZach** [comment]
Can we get new data numbers @woogerboy21 ? I think with the new release it might be time to look into bumping QT4 out
