### ISSUE TITLE
Who/What/When/Where/Why parses wrong

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#181]
My card entry is named `Who // Where` and only has those two rules sections, not all of them.

**Comment by ZeldaZach** [comment]
I looked into this quickly, and it seems as if `oracle/src/oracleimporter.cpp` is hard coded to only allow split cards to have two options. The un-sets really screw up with parsing in a lot of ways, unfortunately.

**Comment by Daenyth** [comment]
We can probably start using the json data to fix this at this point. Instead of inferring based on the name

**Comment by ZeldaZach** [comment]
Are you suggesting a hacky method to just force this card to be added or a more permanent solution that can allow for > 2 cards on one card?

**Comment by Daenyth** [comment]
The latter. I'd like to avoid special cases. I think using the extra
json fields would substantially improve oracle.
