### ISSUE TITLE
Installation error on MAC

### ISSUE THREAD

**Issue by Trons63** [Cockatrice/Cockatrice#1812]
Hi, 
This message come when i want to install cockatrice or oracle :
Process: launchd [2488]
Path: /Volumes/VOLUME/cockatrice.app/Contents/MacOS/cockatrice
Identifier: com.cockatrice.cockatrice
Version: ??? (???)
Code Type: X86-64 (Native)
Parent Process: launchd [120]

Date/Time: 2016-02-08 22:36:54.487 +0100
OS Version: Mac OS X 10.7.5 (11G63)
Report Version: 9

Interval Since Last Report: 180548 sec
Crashes Since Last Report: 74
Per-App Crashes Since Last Report: 46
Anonymous UUID: 29577BFE-8169-434E-963A-AF7556D95EB5

Crashed Thread: Unknown

Exception Type: EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0x00007fff5fc01028

Backtrace not available

Unknown thread crashed with X86 Thread State (64-bit):
rax: 0x0000000000000055 rbx: 0x0000000000000000 rcx: 0x0000000000000000 rdx: 0x0000000000000000
rdi: 0x0000000000000000 rsi: 0x0000000000000000 rbp: 0x0000000000000000 rsp: 0x0000000000000000
r8: 0x0000000000000000 r9: 0x0000000000000000 r10: 0x0000000000000000 r11: 0x0000000000000000
r12: 0x0000000000000000 r13: 0x0000000000000000 r14: 0x0000000000000000 r15: 0x0000000000000000
rip: 0x00007fff5fc01028 rfl: 0x0000000000010203 cr2: 0x00007fff5fc01028
Logical CPU: 2

Binary images description not available

External Modification Summary:
Calls made by other processes targeting this process:
task_for_pid: 1
thread_create: 0
thread_set_state: 0
Calls made by this process:
task_for_pid: 0
thread_create: 0
thread_set_state: 0
Calls made by all processes on this machine:
task_for_pid: 2294
thread_create: 0
thread_set_state: 0

Model: MacBookPro8,1, BootROM MBP81.0047.B27, 2 processors, Intel Core i5, 2.4 GHz, 4 GB, SMC 1.68f99
Graphics: Intel HD Graphics 3000, Intel HD Graphics 3000, Built-In, 384 MB
Memory Module: BANK 0/DIMM0, 2 GB, DDR3, 1333 MHz, 0x802C, 0x384A53463235363634485A2D314734443120
Memory Module: BANK 1/DIMM0, 2 GB, DDR3, 1333 MHz, 0x802C, 0x384A53463235363634485A2D314734443120
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0xD6), Broadcom BCM43xx 1.0 (5.106.198.19.22)
Bluetooth: Version 4.0.8f17, 2 service, 11 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: ST9500325ASG, 500,11 GB
Serial ATA Device: MATSHITADVD-R UJ-8A8
USB Device: hub_device, 0x0424 (SMSC), 0x2513, 0xfa100000 / 3
USB Device: BRCM2070 Hub, 0x0a5c (Broadcom Corp.), 0x4500, 0xfa110000 / 5
USB Device: Bluetooth USB Host Controller, apple_vendor_id, 0x821a, 0xfa113000 / 7
USB Device: Apple Internal Keyboard / Trackpad, apple_vendor_id, 0x0253, 0xfa120000 / 4
USB Device: FaceTime HD Camera (Built-in), apple_vendor_id, 0x8509, 0xfa200000 / 2
USB Device: hub_device, 0x0424 (SMSC), 0x2513, 0xfd100000 / 2
USB Device: USB Optical Mouse, 0x046d (Logitech Inc.), 0xc077, 0xfd120000 / 4
USB Device: IR Receiver, apple_vendor_id, 0x8242, 0xfd110000 / 3

Before the cockatrice was ok but when i do an update this message is arrived.
I don't arrive to install cockatrice so if you know this problem i want the solution please.

Thanks.
Best regards
(sorry for my bad english)

**Comment by ZeldaZach** [comment]
Cockatrice bundles that we provide are built on OS X 10.9. This means you must be on 10.9 or newer to use a pre-compiled bundle.

Since you're on 10.7, I can only recommend two things: either a) Compile a binary yourself (which you can learn how to do quickly using homebrew on our wiki) or b) Update your computer to a newer OS

**Comment by Trons63** [comment]
Thanks for this information :-)

Envoyé de mon iPhone

**Comment by tooomm** [comment]
Just in case you can't immediately find it in the wiki...
https://github.com/Cockatrice/Cockatrice/wiki/Compiling-Cockatrice#on-os-x

Come back with any problems you might run into... or step by at [Gitter](https://github.com/Cockatrice/Cockatrice#get-involved-)

**Comment by Trons63** [comment]
It's ok with the new OS!

Thank you.

Envoyé de mon iPhone
