### ISSUE TITLE
Skype-like statuses

### ISSUE THREAD

**Issue by LethalPigeon7** [Cockatrice/Cockatrice#1813]
"Online" "Do not Disturb" "Offline"(Makes you appear offline even though you are not), or the only one that I actually badly need in cockatrice, possibly as a standalone feature, "Away". A different color or something next to peoples' names if they have been offline for a set ammount of time (30 minutes seem ideal).

**Comment by Daenyth** [comment]
I don't see us adding this. I don't think it adds much value to community building aspects, and it doesn't help gameplay at all.
