### ISSUE TITLE
Group chat

### ISSUE THREAD

**Issue by LethalPigeon7** [Cockatrice/Cockatrice#1816]
Is it a possibility? Inspired by skype. Adding users to a personal chat. Possibly falls under making new chatrooms (I think I saw that here), but I have a quick to make, simple, short-term conversation of 3-5 people in mind, not a big community

**Comment by Daenyth** [comment]
For now you can use a game lobby for this. I'll have to think about whether we should add this feature at all, and if so the best way to integrate it.

**Comment by ZeldaZach** [comment]
I don't see a real reason to add this as it becomes a pain to watch them efficiently from a moderator's stand point. I find game lobbies the best

**Comment by LethalPigeon7** [comment]
Youre not *supposed* to watch them. You have no reason to watch them. Why would you? Its a group of friends talking, no differrnt than 2 buddies talking.

**Comment by Daenyth** [comment]
Yeah Zach I disagree on that point. There's server side logging if
moderation becomes needed.
