### ISSUE TITLE
Cockatrice failing to start

### ISSUE THREAD

**Issue by maloy8920** [Cockatrice/Cockatrice#1817]
I cant run cockatrice on my windows vista computer. When i run the program it tells me to first uninstall the older version of cockatrice. The uninstaller runs and tells me everything is uninstalled and then i reinstall the new version and it still gives me the error. I manually go to the C:/ drive and delete the cockatrice folder and i also delete the folder in app data but it still gives me the same error. This PC does have 2 profiles on it but i made sure it was deleted on both profiles. I also tried to install it on both profiles but no luck. Running as an administrator doesnt help either. I'm not sure but i may have installed cockatrice a very long time ago. I'm not sure if maybe a really old version had different file paths or something. any ideas?

**Comment by Daenyth** [comment]
> gives me the error

Please give us more detail about the error you're seeing. Can you take a screenshot?

**Comment by ZeldaZach** [comment]
As far as I recall, we no longer support the windows xp and vista platforms... maybe i'm mistaken?

**Comment by Daenyth** [comment]
I think it should still work on vista with the appropriate 32/64bit build
as appropriate. If we have the error message we can help more

**Comment by ctrlaltca** [comment]
> we no longer support the windows xp and vista platforms.

Vista should work just fine, as long as you're running the correct version (32 or 64 bit)
About windows xp, #1819 fixes the appveyor package adding windows xp compatibility.

**Comment by ctrlaltca** [comment]
@maloy8920 have you been able to solve your problem?

**Comment by Daenyth** [comment]
@maloy8920 Please reopen this issue if you are still having problems.
