### ISSUE TITLE
Socket Error: Host not found

### ISSUE THREAD

**Issue by Snipemare** [Cockatrice/Cockatrice#1818]
I am getting the "Socket Error: Host not found" message when I attempt to register on  cockatrice.woogerworks.com or  cockatrice.woogerworks.info. I have tried using sockets 4747 and 443 for them both. I have disabled all firewalls. I have attempted multiple usernames and passwords. I have checked for updates and it says I am running the latest version. I really have no idea what else it could be. I can connect to chickatrice.net just fine. Any suggestions or ideas?

Running: Windows 7 on your typical Cox broadband connection. Modem and router with no special security settings. 

Thanks!

**Comment by Daenyth** [comment]
Can you visit those websites in your browser? Host not found is a network error. 

Are you on a managed network like a university?

Try changing your computer's DNS settings to resolve with Google DNS, 8.8.8.8 and 8.8.4.4

**Comment by Snipemare** [comment]
I can go to those websites from my browser. They are just a simple text box with a few options like register, account log-in, etc.

I am on my own private home network.

Changed DNS settings to the Google ones you provided. Ran ipconfig /all in cmd prompt to be sure I was running from those now. Still getting the same error.

**Comment by woogerboy21** [comment]
You could try the IP to find out if its something with name resolution.  The IP of the server is 62.210.169.149 .  May give that a shot.  The only other things I could suggest is rebooting your networking equipment like modem / router maybe?

**Comment by Snipemare** [comment]
Wow the IP address worked. Could you explain why it worked? Having a hard rapping my head around what the actual problem is.

**Comment by Daenyth** [comment]
Maybe you had a bad IP address cached somehow? I think you need to
explicitly flush the dns cache separately from setting the name server

**Comment by woogerboy21** [comment]
I would suggest opening a command prompt and running the following command:
```
ipconfig /flushdns
```
That should flush your local machines resolution cache.  If you still cant get there by name chances are there is something else down the network path that has an incorrect ip cache'd some were.

**Comment by ctrlaltca** [comment]
Maybe his cox provider is just transparently re-routing all DNS queries to its own DNS server.
Anyway this definitely not a cockatrice issue, and not even a woggerworks server issue.
