### ISSUE TITLE
"show buddies only games" toggle

### ISSUE THREAD

**Issue by LethalPigeon7** [Cockatrice/Cockatrice#1823]
> Daenyth commented on 18 Nov 2015
I don't see a compelling reason to set a limit of games you can create so low.
I could see hiding buddy games under "unavailable", or perhaps having an extra toggle specifically for it.
Maybe if we created a relevancy rating that was the default game sort. A combination of password, buddy only, game age, open slots._ - from a somewhat related post that was rightfuly closed

I think the last feature is far too complicated and ultimately useless, all I wish for is a "show buddies only games" toggle.  Seems like an extremely effective and simple fix for a pretty annoying problem.
Assuming this is already being considered I do apologize, but I can't assume that since there's no open issue to remind of this that I know of

**Comment by Daenyth** [comment]
Don't worry about opening issues. If there's none existing it's fine and if there is we'll point it out.

Anyway I'm fine adding a "show games restricted to creator's buddies" filter

**Comment by tooomm** [comment]
What are we talking about here exactly?

a feature/option
- to hide/show all games with the tag `buddy only`?
- to hide/show games that you can't join because you're not a buddy of that games creator

<br>
If I remember correctly the second would be best and very helpful, but is not possible right now.

**Comment by LethalPigeon7** [comment]
The former. I suggested the latter previously and was told just that. Not possible right now. But I couldn't humanly care less, about the advatages of the only hiding games of people I haven't buddied personally, I'd be upset if time was wasted on implementing this pointless feature if anything. I have been playing for 3 years and I have not once looked in main to join a buddies only game. I just right click people's names.

**Comment by tooomm** [comment]
I put some more thoughts into such a toggle and how it could look like...

What do you guys think about new filter buttons for the most simple and basic thinks... quickly accessible and visually easy to check:
![filter buttons](https://cloud.githubusercontent.com/assets/9874850/14348227/5c4fedda-fcbb-11e5-8ac3-a83301a5c92a.png)
- Password protected games `show = yellow lock` / `hide = grey or open lock`
- only Buddy games `show = colored budy icon` / `hide = grey or x'ed budy icon`

More advanced and custom stuff would still go to the `Filter games` dialog box.

There could also be a toggle for spectating (![spec](https://cloud.githubusercontent.com/assets/9874850/14348299/df5a12c8-fcbb-11e5-8d78-4fc1cb316d24.png)) or reg only games...


@poixen you're our button and icon specialist ;)

**Comment by LethalPigeon7** [comment]
Its literally irelevant how features are implemented as long as they work.

**Comment by leematos** [comment]
@LethalPigeon7, I'm not sure if you intended to be snarky, but your last comment sounds pretty mean. Does @tooomm's suggestion look reasonable to how you think this could work?

**Comment by LethalPigeon7** [comment]
Snaky might be the right word for it? But it was 100% honest, and it was the most important comment I could make. His way of doing things seemed flawless, yes ^^. But in this case(and many more) the difference between a completely half-arsed solution, and the best one possibly imaginable would probably be so neglegable I wouldn't notice.

**Comment by Nightfirecat** [comment]
@LethalPigeon7 On the other hand, the design and interface behind such a feature will make a huge difference as far as acceptance to the general userbase. Were it put together poorly, it might work for you, but not work as others would need it to. Integration is key in a feature-rich application like this; it's certainly not a trivial effort to choose how such a feature is exposed.

**Comment by ZeldaZach** [comment]
I'm a fan of the design @tooomm we should look into something like that

**Comment by tooomm** [comment]
>Its literally irelevant how features are implemented as long as they work.

It's still necessary. And by no means trivial or unimportant!
<br>
We all agreed already in this ticket that this feature is a nice addition in theory and might be very helpful...

**Comment by tooomm** [comment]
stumbled upon an older duplicate: #1420

**Comment by samgc3** [comment]
Came here to contribute this request. Just chiming in that I also think it would be useful to filter out 'buddies only' games. These are games that are often old and clutter the view, but still might be a relevant room for the creator.

**Comment by poixen** [comment]
fixed in #2049
