### ISSUE TITLE
Broken tokens.xml file

### ISSUE THREAD

**Issue by MrAAA264** [Cockatrice/Cockatrice#1824]
After trying to update my Oracle, i can no longer create tokens with art, but other player can make them and i can see the art? I've toogled the TK set in the database, im not sure what else to do

**Comment by Daenyth** [comment]
Can you be more specific? Screenshots of the issue?

**Comment by MrAAA264** [comment]
i fixed the problem mostly, i had a corrupted file in the client, so i uninstalled of it, and downloaded the newest version
