### ISSUE TITLE
[gh pages] exchange php script in favor of js/ajax code to provide download links

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#1825]
_(just a reminder to keep track)_
<br>

Right now we use this [php script](https://github.com/Cockatrice/cockatrice.github.io/blob/master/scripts/cockatrice_bin.php) hosted on a external site because github pages are just static and don't allow for server executable code.
The best solution would be to use JS/AJAX for that instead, implemented into the site.
Unfortunately this isn't supported by the Bintray API yet.

TMiguelT even wrote the support about that:
![bintray ajax](https://files.gitter.im/Cockatrice/Cockatrice/Jh2f/bintray-ajax.png)
Gitter Source: :point_up: [January 7, 2016 4:20 AM](https://gitter.im/Cockatrice/Cockatrice?at=568dd98084fa46770b25014a)

@TMiguelT Any news on that?

<br>
They might announce new features on their blog: http://blog.bintray.com/

**Comment by TMiguelT** [comment]
No news from me, but I'm sure I can help fix this once they implement CORS. Feel free to email them yourself or watch the blog until then.

**Comment by tooomm** [comment]
Update from support:

> The ETA for this is Q2 2016.

**Comment by ZeldaZach** [comment]
Awesome!

**Comment by ZeldaZach** [comment]
Any word on this?

**Comment by tooomm** [comment]
Not yet. I'll ask them in a few weeks for an update.

**Comment by tooomm** [comment]
At the moment we don't use the php script anymore, we use static links that we need to update every release instead.

It seems like there are options to query the github api to somehow accomplish the same and dynamically link to the newest release files on github instead of bintray on our gh webpage:
http://stackoverflow.com/questions/24987542/is-there-a-link-to-github-for-downloading-a-file-in-the-latest-release-of-a-repo
http://stackoverflow.com/questions/28236859/download-link-for-latest-release-of-github-project?rq=1

Is something pretending us from using this instead for the download links on the webpage?

**Comment by tooomm** [comment]
@TMiguelT Calling for help here.
We switched to host our releases on github instead of bintray... and their API supports CORS!

Do you want to have a look?? 😃

**Comment by tooomm** [comment]
There is a pretty cool page to check the download count of releases:
http://www.somsubhra.com/github-release-stats/

It uses js to query the github api as well, source code available here:
https://github.com/Somsubhra/github-release-stats/blob/master/js/main.js
We just need to adapt it to get the information that we are looking for. 👍
