### ISSUE TITLE
Misleading CMake DB Error

### ISSUE THREAD

**Issue by woogerboy21** [Cockatrice/Cockatrice#1827]
When compiling from source using CentOS 7 and Qt5.5.1 users are presented with the following error message during the cmake command using the -DWITH_SERVER=1 option.

```
-- Mysql connector NOT FOUND: servatrice won't be able to connect to a mysql server
```

Even though the server compiles and DB connectivity to the mysql/mariadb app is available and functions correctly.

I noticed this as well when trying to compile using ubuntu but didnt get to testing if DB connectivity worked using that build/test.

**Comment by skwerlman** [comment]
I had this issue as well, but managed to solve it. I'll try and find my solution...

**Comment by woogerboy21** [comment]
In the case of CentOS the required packages are there, the cmake file looks for the plugins in a couple of paths that are listed in the .cmake file under the servatrice folder but are not the correct paths by the looks of things.  Im thinking there is something with the newer versions of either Qt or MariaDB that have moved things from were they were located at one time.  Cant speak for ubuntu though, i dont typically use that distribution and had loaded it to play with but that never really went any were since I ran out of time to play.

**Comment by ctrlaltca** [comment]
```
SET(MYSQLCLIENT_DEFAULT_PATHS "/usr/lib" "/usr/local/lib")
find_library(MYSQLCLIENT_LIBRARIES NAMES mysqlclient PATHS ${MYSQLCLIENT_DEFAULT_PATHS} PATH_SUFFIXES mysql mariadb)
```

It's searching for a library named "libmysqlclient" in either "/usr/lib", "/usr/local/lib" or a subdirectory of those directories named after "mysql" or "mariadb".
I had a centos7 box handy to test this and it seems that we miss to search in the 64-bit libraries directories. The correct path for me was ```/usr/lib64/mysql/libmysqlclient.so```
