### ISSUE TITLE
Update of the Wiki: building Cockatrice on Debian Jessie 8

### ISSUE THREAD

**Issue by alexmehdi** [Cockatrice/Cockatrice#1829]
<b>OS:</b>
GNU/Linux 8.3 (jessie)
<br>
Hi,

I tried to install build Cockatrice with the instructions of the Wiki. Unfortunately the instructions given in the Debian Linux section does not work for Debian GNU/Linux 8.3 (jessie). I found the solution. Thus, I suggest to add the following instructions which work for me:

_For Debian GNU/Linux 8.3 (jessie), you can run the following commands:_
```
# apt-get install -y build-essential g++ cmake \
    qtmobility-dev libprotobuf-dev protobuf-compiler
$ cd
$ git clone git://github.com/Cockatrice/Cockatrice
$ cd Cockatrice
$ mkdir build
$ cd build
$ cmake ..
$ make
# make install
```

Only the first instruction is different. 

Have a good day !

**Comment by tooomm** [comment]
Thanks for the hint!

https://github.com/Cockatrice/Cockatrice/wiki/Compiling-Cockatrice#debian-linux
