### ISSUE TITLE
Show a warning the first time we get strange image download errors

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#1830]
If gatherer is offline and returning 500s or connection refused, the UX is that images appear to be broken with no indication as to why.

The image download code should emit a signal saying how the download failed.

The app should connect that signal to a one-time listener and show a warning the first time a non-404 download failure is reached.

**Comment by ZeldaZach** [comment]
SF is the default nowadays, this isn't as much of a concern
