### ISSUE TITLE
remove numbers from the dice roll translatable strings

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#1833]
https://github.com/Cockatrice/Cockatrice/blob/master/cockatrice/src/messagelogwidget.cpp#L148

To prevent mistakes or make translators mix things up...
Basic dice functionality should be there in any case, and properly working!

**Comment by Daenyth** [comment]
I don't think we should do this, it's unexpected behavior. Users on older clients would see numbers and users on newer clients would see the flip. The intent of the flip stuff is for it to be both. If necessary, we should add comments to the tr call so the translator has the context

**Comment by tooomm** [comment]
You got me wrong. :)

Users should **always** see both..
They should just not able to translate `Heads (1)`, it should just be `Heads` in transifex. The shown message in the client needs to be `Heads (1)` for sure.
Or `Kopf (1)` if translated to german for example!

The idea is that someone can't change numbers in the translation string and the confusion will be there...

**Comment by Daenyth** [comment]
Aha! I understand now. You're exactly right.
