### ISSUE TITLE
Replay data not being stored in replay table

### ISSUE THREAD

**Issue by woogerboy21** [Cockatrice/Cockatrice#1835]
Looks like with the most recent build of the server the data that typically gets written to the cockatrice_replays table isnt being properly written.  The data written to the cockatrice_replays_access table is recorded correctly.

So far this seems to happen from a cleanly built database using the most recent .sql scripts.

@ctrlaltca 
Maybe related to the DB constraints put in place?

**Comment by woogerboy21** [comment]
This turned out to be a problem on my server.  Had to drop and recreate the replay table for whatever reason.

**Comment by ctrlaltca** [comment]
I suppose this was the cause: https://github.com/Cockatrice/Cockatrice/blob/master/servatrice/migrations/servatrice_0012_to_0013.sql#L30
The old tables had wrong signedness

**Comment by Daenyth** [comment]
Do we need to patch that script?
