### ISSUE TITLE
Receiving no token/activation mail for Registration.

### ISSUE THREAD

**Issue by sembroglio** [Cockatrice/Cockatrice#1837]
<b>OS:</b>
OS X 10.10.5

<b>Cockatrice version:</b>
Version 49c22f3 (2016-02-25)

___
<br>

Hi, after registration I'm not receiving any token mails to complete registration (same problem as Issue #1692). Registration seems to work up until i need to verify with the token from the mail. Tried two different mails and checked Spam folders.
Thx in advance!

**Comment by tooomm** [comment]
Which server did you register for?

Woogerworks? Did you try to use the contact form on his page as written in the issue you linked?

**Comment by woogerboy21** [comment]
@sembroglio Ever get this resolved?

**Comment by woogerboy21** [comment]
Closing this issue.  If the user needs an activation token still they can contact the server owner (which chances are might be me).
