### ISSUE TITLE
Unable to compile on Sabayon

### ISSUE THREAD

**Issue by skwerlman** [Cockatrice/Cockatrice#1838]
<b>OS:</b>
Sabayon Linux 16.02

<b>Cockatrice version:</b>
0b8f52e

___
<br>

Compilation fails with the error:
```
/home/skw/Code/cockatrice/cockatrice/src/soundengine.cpp:5:24: fatal error: QAudioOutput: No such file or directory
 #include <QAudioOutput>
                         ^
compilation terminated.
```

I'm building against QT 5.5.1-r1:
```
skw@sabayon-pc ~/cockatrice/build $ equo s --installed qtcore:5
╠  @@ Searching...
╠      @@ Package: dev-qt/qtcore-5.5.1-r1 branch: 5, [__system__] 
╠          Installed:     version: 5.5.1-r1 ~ tag: NoTag ~ revision: 0
╠          Slot:          5
╠          Homepage:      https://www.qt.io/ 
╠          Description:   Cross-platform application development 
╠                         framework 
╠          License:       FDL-1.3 LGPL-2.1 LGPL-3
╠   Keywords:  qtcore:5
╠   Found:     1 entry
```

**Comment by Daenyth** [comment]
Is there any qt multimedia package? What is sabayon based on?

**Comment by skwerlman** [comment]
The qt packages don't install `qtmultimedia:5` by default. However, after installing it, compilation still fails at the same place.

Sabayon is based on Gentoo, but uses a separate (and largely incompatible) package manager.

**Comment by skwerlman** [comment]
I'm gonna add a section for compiling on Sabayon to the wiki, if that's all right with you guys.

**Comment by Daenyth** [comment]
Thanks for the contribution!
