### ISSUE TITLE
unknown login error: -1 

### ISSUE THREAD

**Issue by Longshot101** [Cockatrice/Cockatrice#1842]
ok so i had some trouble with my client and after getting my old one to work and when i try to get online and i get this.
![capture](https://cloud.githubusercontent.com/assets/12321502/13508638/d94329aa-e155-11e5-8450-e2787265e2c6.PNG)
now if i update my client to the most up-to-date i get this lovely thing.
 
![capture1](https://cloud.githubusercontent.com/assets/12321502/13508758/5671daf2-e156-11e5-92c7-810aa52d3b7d.PNG)
is their a way to fix this headache?

**Comment by Longshot101** [comment]
and yes i have try to reinstall it many of time

**Comment by woogerboy21** [comment]
Just curious what your OS version is?

**Comment by Longshot101** [comment]
where would i locate that?

**Comment by Longshot101** [comment]
windows 7

**Comment by woogerboy21** [comment]
Any service packs?

**Comment by Longshot101** [comment]
as in like an update or something, I'm not sure? cause I've gone though all the updates i could find and also had to download msvcp120.dll to get past that problem.   if i helps my pc is  Windows 7 Alienware.

**Comment by Longshot101** [comment]
i do know when i download the new client i'm missing a few files. un like my old one like. icudt53.dll icuin53.dll   icuuc53.dll

**Comment by Longshot101** [comment]
the old client i have will run, but not go online how every the new client just gives me that error in the 2nd pic. (i'm not computer wiz i just try my best)

**Comment by woogerboy21** [comment]
Yeah im trying to reproduce the error you have to figure out the exact problem.  If I were to guess you need a client using Qt4 or an earlier version of Qt5 (but its just a guess)

**Comment by Longshot101** [comment]
well on the left is all the old stuff and on the right is the new one
![capture3](https://cloud.githubusercontent.com/assets/12321502/13543639/fd785116-e23a-11e5-814b-d95adcf30cf0.PNG)

**Comment by woogerboy21** [comment]
Yes, the newer client does not have those files nor does it need it.  So far all my research leads back to one of 2 issue's.  Either your VC++ runtimes are not configured properly OR you have some type of antivirus anti-malware app preventing the execution of the application.  Ill see if I can reproduce the issue on a windows 7 box.

**Comment by Longshot101** [comment]
ok so i went though my antivirus anti-malware stuff and could not find anything that would cause the issuse

**Comment by snowpl** [comment]
We'll im having the same issue as shown in the first picture "Unknow login error: -1", tried to reinstall, nothing helped, same on win 7

**Comment by Daenyth** [comment]
@snowpl download a more recent version of the client.

**Comment by woogerboy21** [comment]
I'm wondering if it's the cmake issue that was causing problems on XP
machines ctrlaltca fixed post the most recent full release .  Downloading a
more recent development release would be a good test. (As Daenyrh mentioned)

**Comment by snowpl** [comment]
yup, changing the version to the most recent help ;)

**Comment by woogerboy21** [comment]
@Longshot101 By chance have you tried the most recent dev build as well or are you working with the stable release?

**Comment by Longshot101** [comment]
I'm not totally sure by what you mean but i use this link to download the client https://cockatrice.github.io/   sry

**Comment by woogerboy21** [comment]
@Longshot101 Lets first start by trying this version of the app and let us know if it still comes up with the error starting:

**Comment by Longshot101** [comment]
yes this most up to date version give me this 
![capture1](https://cloud.githubusercontent.com/assets/12321502/13549610/74c0423c-e2d7-11e5-9863-78fc2df59c4c.PNG)

**Comment by woogerboy21** [comment]
@Longshot101 
For the version that does work but throws the -1 error, what version number does it say in the help->about window?

**Comment by Longshot101** [comment]
![capture](https://cloud.githubusercontent.com/assets/12321502/13549858/7e66a2b2-e2dd-11e5-875e-d306272a12ec.PNG)

**Comment by woogerboy21** [comment]
One more screenshot to help troubleshoot.  With the version that throws the -1 error.  Can you right click on the Qt5Core.dll file under the installation path.  Choose properties and then send a screenshot of the details tab?  Im looking for the File version number on the Qt5Core.dll file.

**Comment by Longshot101** [comment]
![capture](https://cloud.githubusercontent.com/assets/12321502/13549884/2c1fea08-e2de-11e5-8acf-d9ec450d7f0c.PNG)

**Comment by Longshot101** [comment]
and the up to date one is Product version 5.5.1.0

**Comment by Longshot101** [comment]
hold up your link you gave me worked after redownloading it 3 times     x.x
  https://bintray.com/artifact/download/cockatrice/Cockatrice/Win32/Cockatrice-0.0.1~git20160305.17925ce-x86_qt5.exe

**Comment by woogerboy21** [comment]
Hmm.. thats odd.  Im pretty sure the issue was that cmake option i mentioned.  But it could have been the VS runtimes as well.  But if its working for you great!

**Comment by Longshot101** [comment]
i just wiped all the files for it off my pc the third time then tried to download and it seems to work rather then the uninstall and reinstall? i don't know why/if/or how it worked.
