### ISSUE TITLE
Ubuntu installer client failures

### ISSUE THREAD

**Issue by woogerboy21** [Cockatrice/Cockatrice#1843]
Reporting this on behalf of a user that emailed me about it.  Not sure if its been fixed or not. @ctrlaltca 

so I just downloaded cockatrice for linux (ubuntu 14.04) and the software center told me it didn't meet quality standards and to send you guys this:

Lintian check results for /home/piper/Downloads/Cockatrice-0.0.1-git20160228.0b8f52e.deb:
E: cockatrice: control-file-has-bad-permissions md5sums 0664 != 0644
E: cockatrice: maintainer-name-missing Daenyth+github@gmail.com
Use of uninitialized value $name in pattern match (m//) at /usr/share/perl5/Lintian/Check.pm line 203.

**Comment by ctrlaltca** [comment]
> E: cockatrice: control-file-has-bad-permissions md5sums 0664 != 0644

This is a known cpack (cmake) bug, fixed in cmake 3.3. Unfortunately that version of cmake is currently not available on the ubuntu version used by travis..

> E: cockatrice: maintainer-name-missing Daenyth+github@gmail.com

This is easily fixable.

> Use of uninitialized value $name in pattern match (m//) at /usr/share/perl5/Lintian/Check.pm line 203.

Lol this is an error of the script checking our package for errors. Sounds recursive.

**Comment by Daenyth** [comment]
Can we use a PPA for cmake 3.3?

**Comment by ctrlaltca** [comment]
https://launchpad.net/~george-edison55/+archive/ubuntu/cmake-3.x could be fine for trusty, 'm still searching for something offering 3.3 for precise.

**Comment by ctrlaltca** [comment]
#1859 adds the usage of https://code.launchpad.net/~smspillaz/+archive/ubuntu/cmake-master , that currently includes cmake 3.3, fixing half of this problem.

**Comment by ctrlaltca** [comment]
Added oneliner fix in #1859
