### ISSUE TITLE
~3s delay opening "Register to server" dialog the first time

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#1844]
<b>OS:</b>
Seen on OSX + Windows

<b>Cockatrice version:</b>
Since at least `Version ad6de1c (2015-11-03)`, I also see it on `Version d16fab9 (2016-03-03)`
___
<br>

The first time you open the "register to server" dialog, there's a ~3 second delay. Opening it again is seamless.

Seen in #1841

**Comment by ctrlaltca** [comment]
It's loading 252 svg images (countries and genders icons) and rendering them to a bitmap representation suitable to be used on the dropdowns. Once loaded the pixmaps are cached, so the following times the dialog takes no time to reopen.

**Comment by Daenyth** [comment]
I think probably we don't care enough about this then.

**Comment by tooomm** [comment]
Is there a way to store the generated bitmap and reuse it until it gets forcefully updated somehow?

**Comment by ctrlaltca** [comment]
Loading pre-resized bitmapsfiles would take a bit less time than loading .svgs and resizing them.
Unfortunately creating a caching mechanism on the disk is something a bit too complicated to be worth the effort.
We could try to avoid the problem bundling bitmaps of the correct size, or implementing a lazy loading mechanism in the dropdownlist.

**Comment by tooomm** [comment]
Such a long waiting time for a dialog to open (on recent hardware!) is unexpected and destroying the UX.

>We could try to avoid the problem bundling bitmaps of the correct size, or implementing a lazy loading mechanism in the dropdownlist.

Sure! Why not just load+create them on demand if you open the drop-down list?
Maybe not needed for the gender icons.
Would it take 3s to open the country dropdownlist then? Or would the dropdownlist with the country names open immediately and the flags show up next to the names after scrolling/viewing at the list for 3s?

**Comment by Daenyth** [comment]
>  unexpected and destroying the UX.

This is for registering to a server. If it was the connect dialog I'd be more bothered, but this is for most people a one-time action.
