### ISSUE TITLE
Add support for card number in custom image URLs

### ISSUE THREAD

**Issue by skwerlman** [Cockatrice/Cockatrice#1845]
<b>OS:</b>
Win 10

<b>Cockatrice version:</b>
17925ce

___
<br>

MTGJSON provides a `number` field in each card array. It would be useful to have access to that for use in custom image URLs since some sites use that for image sorting/naming.

**Comment by ctrlaltca** [comment]
Is this the same as #1741?

**Comment by skwerlman** [comment]
whoops, my bad, this is a duplicate; although i don't see any documentation for the `mciNumber` mentioned there, just `number`.
