### ISSUE TITLE
CTRL + TAB to scroll through server tabs

### ISSUE THREAD

**Issue by anoda9** [Cockatrice/Cockatrice#1846]
<b>OS: OS X 10.11.3</b>

<b>Cockatrice version: Version 323fc06 (2016-02-02)</b>

---

<br>

In the previous version (before gatewatchers), hovering the mouse over the tab bar and scrolling would switch tabs. In the latest build, this doesn't work. Scrolling to switch tabs was very convenient and useful. Can we get this back?

**Comment by Daenyth** [comment]
Sounds reasonable

**Comment by woogerboy21** [comment]
FYI, this functionality still works in the windows build.  Could it be an OSX issue?

**Comment by ctrlaltca** [comment]
Relevant info here: https://bugreports.qt.io/browse/QTBUG-8428

**Comment by anoda9** [comment]
I guess this was due to a change in the QT framework/code, but man was scrolling to change tabs useful. It just seems strictly worse to not have the option to do that.

**Comment by Daenyth** [comment]
I'd like ctrl+tab to work in the expected way in all tabs at least

**Comment by tooomm** [comment]
<kbd>Ctrl</kbd> + <kbd>Tab</kbd> is used for that in many applications like Firefox and others... :+1:
