### ISSUE TITLE
Does Cockatrice handle alternative pictures for the same card ?

### ISSUE THREAD

**Issue by Graffity2199** [Cockatrice/Cockatrice#1847]
Some cards have alternative pictures in a set directory, such as :
<b>Homelands</b>
*\* Abbey Matron1.full.jpg
*\* Abbey Matron2.full.jpg
*\* Aliban's Tower1.full.jpg
*\* Aliban's Tower2.full.jpg
<b>Antiquities</b>
*\* Urza's Power Plant1.full.jpg
*\* Urza's Power Plant2.full.jpg
*\* Urza's Power Plant3.full.jpg
*\* Urza's Power Plant4.full.jpg

Is there any way to choose which one we want in our deck ?
In addition, it seems that the HQ pictures can't be read in that case, I have the feeling that it is the downloaded version of the pictures which is taken into account...

Thanks for your help.

![handle alternative pictures](https://cloud.githubusercontent.com/assets/17712224/13585077/00a29a8c-e4ba-11e5-9899-5be4028a4cbe.png)

**Comment by Fizztastic** [comment]
Those are not handled by cockatrice. It will only load the image if it matches the cardname in the database. The only way to "choose" which image you see is by removing the number at the end of the one you want to see. In this case, the image name would be "Abbey Matron.full.jpg".

**Comment by Daenyth** [comment]
I plan to have us support this eventually. It won't be soon because the card database code is difficult to change and crosses a lot of parts of the app.

**Comment by Graffity2199** [comment]
Ok no problem, thank you for your answer.

**Comment by radioactivehazards** [comment]
You can use the Custom images Function to choose which version you see.

**Comment by tooomm** [comment]
Linking #2022
