### ISSUE TITLE
Cant load or upload deck

### ISSUE THREAD

**Issue by thekaratekid97** [Cockatrice/Cockatrice#1849]
<b>OS:</b>
win 8

<b>Cockatrice version:</b>
17925ce (2016-03-05)
___
<br>

when ever i hit load or save deck it opens the location where my files are saved and then i get the notification cockatrice has stopped working and windows shuts it down. this is a new problem i have tried restarting my computer and reinstalling

**Comment by Daenyth** [comment]
Can you screenshot the error message?

**Comment by thekaratekid97** [comment]
there is no error message

**Comment by thekaratekid97** [comment]
![cockatrice issue](https://cloud.githubusercontent.com/assets/17713774/13588886/930212e0-e4a1-11e5-8d7d-9e22a88414bf.PNG)

**Comment by ctrlaltca** [comment]
Can you try to temporary rename your cockatrice's profile folder?
First ensure that cockatrice is not running.
Search for the folder ```C:\Users\Your Name\AppData\Local\Cockatrice``` and move/rename it to force cockatrice to re-create it.
Then, run oracle to re-downloads cads and tokens.
Now you can try to run cockatrice again and see if it still crashes at the on the "load deck" dialog.

If it still crashes, it could be a libraries problem, and we'll have to investigate that further.
Instead, if recreating the profile solves your problem, you can close cockatrice again and move back some selected data from the old profile into the new one; you probably want to get at least pictures and decks from the old profile.

**Comment by Daenyth** [comment]
If moving the files fixes it we'd also appreciate if you can zip then and
upload so we can find the root problem

**Comment by thekaratekid97** [comment]
i tried what you suggested and it still crashed. i went to settings and i clicked on all of the paths for tokens images decks etc and it crashes on all of them

**Comment by thekaratekid97** [comment]
it was working for me before the new update

**Comment by woogerboy21** [comment]
I attempted to recreate this and have yet to be successful doing so on the d3447b3 (2016-03-09) build under windows 10.  Do you happen to know the version number of the client you had before you updated?

**Comment by ctrlaltca** [comment]
It could be due to some old qt libraries leftovers somewhere in cockatrice or windows directory.

**Comment by thekaratekid97** [comment]
ok ill try that.

**Comment by thekaratekid97** [comment]
it still doesnt work I tried shutting off firewall to make sure it wasnt that and that didnt work either

**Comment by rangicus** [comment]
I'm getting the same problem, have tried all of the recommended steps. Have also tried installing different versions of the program found on the downloads. The issue has occurred at every step of the way.

**Comment by Daenyth** [comment]
@rangicus Are you also on windows?

**Comment by Daenyth** [comment]
@thekaratekid97 @rangicus What's your deck storage location? Where on disk are they? I wonder if it's possibly related to the location.

**Comment by Daenyth** [comment]
And does it crash when the window to select your deck comes up? When you select a deck? When you hit ok/load after selecting a deck?

**Comment by Daenyth** [comment]
Does it crash opening decks in the deck editor, or does it crash opening them in a game? Or both?

**Comment by rangicus** [comment]
@Daenyth I am on Windows 10. Deck storage is default Cockatrice folder. On `C:\Users\#\AppData\Local\Cockatrice\Cockatrice\decks`. It crashes when the window for selecting a deck appears. It does crashes when the open deck window is open, regardless of the context.

**Comment by Daenyth** [comment]
Thanks, that info helps narrow it down.

**Comment by woogerboy21** [comment]
Is this happening in the deck editor or some were else when you attempt to load a deck?

**Comment by rangicus** [comment]
@woogerboy21 The crash occurs any time the load deck window is opened. From any source.

**Comment by Daenyth** [comment]
@rangicus What is your computer language set to? And what is cockatrice's language set to?

**Comment by rangicus** [comment]
@Daenyth They are both set to English.

**Comment by Daenyth** [comment]
@rangicus if you don't mind, could try moving aside your appdata files as mentioned earlier in the thread, and then running the uninstaller, selecting the "remove everything" option (remove your stored configuration). Then reinstall and let me know if the problem persists?

I'm trying to figure out if this could be related to some kind of old incompatible settings being stored which it's breaking on.

**Comment by Daenyth** [comment]
Do you see the file select dialog on screen and then crash, or does it crash before you see it?

**Comment by woogerboy21** [comment]
it also would be handy to know if anyone knew there previous client version that they came from

**Comment by rangicus** [comment]
@Daenyth I have already tried moving/deleting the folder within appdata and reinstalling. I see the file select screen, then I have about two seconds before the crash happens. I do not know what version I've come from, but this is the first one to have done this.

**Comment by Daenyth** [comment]
@rangicus with the reinstall, did you check the box that says delete everything when uninstalling though? Or did you keep any settings?

**Comment by rangicus** [comment]
@Daenyth I have tried both.

**Comment by Daenyth** [comment]
Thanks

**Comment by tooomm** [comment]
I can load and save (+save as) different decks without problems in the deck editor! :+1: 

Loading a deck on the server (game room) also works like a charm...

(Win 8.1 - Cockatrice version: ec7e375 04.03.16)

**Comment by tooomm** [comment]
**Update:**
newest 64bit version cbea432 from 2016-03-08 is also perfectly working for me

---

Let's start from scratch...
- Did anything on your PC recently changed? Hardware upgrades? New drivers? Other Firewall etc...
- When did you do your last Cockatrice update before this one? <br>Give us a rough timeframe pls... 3month? 6month? 2 weeks?
- From which site did you download the client from?<br>Can you give us a screenshot or detailed description?
- What kind of windows do you run (32/64bit?) <br>
--> check this: https://support.microsoft.com/en-us/kb/827218
- Does the crash happen just in the deck editor or also in a game lobby on the server?
- What kind of deck files do you try to open? How old are they and how many cards are inside? Did you try different deck files? What kind of file type do your decks have?

**Comment by rangicus** [comment]
64 bit windows 10. This is the first installation of cockatrice on this PC. They are cod files. Never tried compiling myself. Crash happens regardless of location.

**Comment by Daenyth** [comment]
> This is the first installation of cockatrice on this PC

Is this true for everyone? I wonder if clean installs are what's broken and upgrading existing installs works.

**Comment by ctrlaltca** [comment]
To everyone experiencing the problem, here's two possible causes.
First: are you using a DELL pc or have the "Dell Backup and Recovery" software installed? If yes, that could be the problem (source: https://bugreports.qt.io/browse/QTBUG-41416 ).

Second: can you try to:
 * close cockatrice
 * browse to the cockatrice's installation folder (Usually ```c:\program files\Cockatrice``` or ```c:\program files (x86)\Cockatrice```)
 * rename cockatrice.exe to cockatrice2.exe
 * double click on it in order to run it
 * test if deck loading is working?
If this fixes your problem, it's due to some internal windows vodoo (source: https://bugreports.qt.io/browse/QTBUG-33119 ).

**Comment by rangicus** [comment]
@ctrlaltca I just have "Dell Backup and Recovery" on my computer. That could be the issue. I will try renaming the Cockatrice.exe

**Comment by rangicus** [comment]
@ctrlaltca Renaming cockatrice does nothing. I will see if I can disable the dell program.

**Comment by rangicus** [comment]
@ctrlaltca Uninstalling `Dell Backup and Recovery' has solved the problem! Thank you.

**Comment by thekaratekid97** [comment]
@ctrlaltca the same worked for me thanks for the help!

**Comment by Daenyth** [comment]
OK, I think at this point it's resolved.

Thanks @ctrlaltca, I saw that ticket but thought it wasn't related due to the reported details.

**Comment by Nightfirecat** [comment]
Maybe this should be added to the wiki? I didn't see a page/section for it yet, and it sounds like we've got a pretty straightforward set of steps to fix it based on @ctrlaltca's comment.

**Comment by tooomm** [comment]
What did you guys actually do to solve it? Just uninstall the program? Both of you?

Is there maybe a workaround that still allow people to use the Dell app... some might really need it.
Renaming doesn't seem to do the trick for @rangicus ?!

**Comment by Daenyth** [comment]
> Maybe this should be added to the wiki?

Yes, I mentioned this in gitter. If you'd like to update the troubleshooting page, go ahead :)

**Comment by Nightfirecat** [comment]
If I remember after work, I'll try to get to this tonight.

**Comment by ZeldaZach** [comment]
Did you remember? @Nightfirecat

**Comment by Nightfirecat** [comment]
[I did.](https://github.com/Cockatrice/Cockatrice/wiki/Troubleshooting#cockatrice-crashes-when-i-try-to-save-or-load-a-deck)
