### ISSUE TITLE
Cannot Load Deck from File or Clipboard

### ISSUE THREAD

**Issue by tourachsdoorbell** [Cockatrice/Cockatrice#1851]
<b>OS:</b>
Windows 8, current SP
<b>Cockatrice version:</b>
Version cbea432 (2016-03-08)

___
<br>

When loading from file or clipboard, after you confirm the load no decklist shows up on right. It appears to register that there is something there, however, as you are prompted to save before closing if you load from clipboard.

**Comment by tooomm** [comment]
Can you show us a screenshot about your Cockatrice window after loading the deck?

**Comment by tourachsdoorbell** [comment]
Thanks for following up. I reinstalled a second time and had no issue, so
no screenshot. Sorry for the goose chase.

On Fri, Mar 11, 2016 at 8:38 AM, tooomm <notifications@github.com> wrote:

> Can you show us a screenshot about your Cockatrice window after loading
> the deck?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Cockatrice/Cockatrice/issues/1851#issuecomment-195393088>
> .
>



-- 
Chris Miller

chrismikemiller@gmail.com
612.840.7620
