### ISSUE TITLE
client Death

### ISSUE THREAD

**Issue by radioactivehazards** [Cockatrice/Cockatrice#1853]
Tried to install latest Client from weekly build....Failed to do so and it deleted current client now unable to use either one.

**Comment by radioactivehazards** [comment]
tried Re-installing the newest build and now i get "The application was unable to start correctly (0xc000007b) click ok to close."

**Comment by Daenyth** [comment]
Did you use the 32bit or the 64bit installer? I think this is the same error from #1788 and you need to make sure to use the 32bit version.

**Comment by Daenyth** [comment]
Also https://github.com/Cockatrice/Cockatrice/issues?q=is%3Aissue+0xc000007b+is%3Aclosed

**Comment by woogerboy21** [comment]
Didnt you post this in the past? :smile:

**Comment by radioactivehazards** [comment]
well it did not even ask me to select one and it said weekly builds. what are you looking for...and then it uninstalled my other client. i no longer have the "link" to the qt4 that Did work so yeah.....trying to update i got smacked with an issue which is Normally the case :) hence why I dislike updating

**Comment by Daenyth** [comment]
oh hm, @woogerboy21 the weekly build aren't on bintray are they?

**Comment by Daenyth** [comment]
@radioactivehazards You can get the latest full release here: https://bintray.com/cockatrice/Cockatrice/Cockatrice/view#files ; use the win-x86 one.

**Comment by Daenyth** [comment]
aha, separate issue; the download link on the github.io page needs to point to the right arch version. @ZeldaZach

**Comment by radioactivehazards** [comment]
attempting now.....and yeah i know it was the same issue i just dislike how many times i get slapped in the face for updating :)

**Comment by ZeldaZach** [comment]
I'll get on fixing that

**Comment by Daenyth** [comment]
@radioactivehazards where did you get the build from? woogerworks or the .io site? I think it just wasn't hosting the right version.

**Comment by radioactivehazards** [comment]
i went to the place that cockatrice directed me to in the Server tab for weekly builds

**Comment by Daenyth** [comment]
That's the io site; Zach will be fixing the links there. For the moment stick with the latest release.
