### ISSUE TITLE
Cockatrice client crashes anytime either player draws arrows.

### ISSUE THREAD

**Issue by dopestX** [Cockatrice/Cockatrice#1857]
<b>OS:</b>
mac OS X 10.8.5

<b>Cockatrice version:</b>
Version 323fc06 (2016-02-02)

___
<br>

The issue I am having is anytime either my opponent or myself draws an arrow to indicate targets my game client crashes. i have uninstalled and reinstalled about 6 times to no avail. I also tried downloading the version i found through the link that said "stable, main release version" (or something similar) and that still had no affect. This has been an issue since the first time that i downloaded the program. thanks for any help

**Comment by ctrlaltca** [comment]
I'm afraid that currently the OSX packages that we provide are only compatible from OSX 10.9.5 onwards.
We either need to find someone able t provide you a 10.8-compatible package, or we can help you in creating a package yourself. This involves writing some commands in a terminal, that's not so user friendly, but not even that hard.
Do you happen t use [homebrew](http://brew.sh/)? If you do, you can follow these instructions:
https://github.com/Cockatrice/Cockatrice/wiki/Compiling-Cockatrice#compiling-with-homebrew

**Comment by krayola** [comment]
Hi ctrlatca. I am having the same trouble than dopestX with the same OS X 10.8.5. Sadly I was unable (though I tried to) understand how to solve the problem, could you give me a hand please?

**Comment by Daenyth** [comment]
@krayola [Install homebrew](http://brew.sh/) and then follow the instructions for qt5 from the wiki linked above. If you get stuck with that, please open a new ticket for it

**Comment by Daenyth** [comment]
@dopestX Is this fixed for you when you compile your own client?

**Comment by krayola** [comment]
Ok I installed homebrew, but then when I try to install cockatrice it says

Error: The following formula:
  qt5
cannot be installed as a a binary package and must be built from source.
To continue, you must install Xcode or the CLT from:
  https://developer.apple.com/downloads/

do I need to download and install that Xcode 7.3 beta 5? It's almost 5GB size

**Comment by ctrlaltca** [comment]
You don-t need to install the whole XCode, but only the "command line tools". Try running: ```xcode-select --install```

**Comment by krayola** [comment]
xcode-select: Error: unknown command option '--install'.

xcode-select: Report or change the path to the active
              Xcode installation for this machine.

Usage: xcode-select --print-path
           Prints the path of the active Xcode folder
   or: xcode-select --switch <xcode_path>
           Sets the path for the active Xcode folder
   or: xcode-select --version
           Prints the version of xcode-select

**Comment by ctrlaltca** [comment]
Hum.. it seems that ```xcode-select --install``` didn't exist yet on 10.8; at that time you needed an apple account to login to the "apple developers" portal, download and install them manually. Of course apple doesn't provide that download anymore.
Also, even homebrew doesn't officially support anything below 10.9 anymore.
I'm afraid that no userfriendly way to compile on 10.8 exists anymore.

**Comment by Daenyth** [comment]
@krayola You should be able to upgrade your OSX to 10.9 via the App Store app. Can you try that?

**Comment by krayola** [comment]
I know this might not be the best solution, but so far is the arrow thing the only inconvenient with the software you've heard of in 10.8.5? Because if that is so, I can just avoid it. I am just playing with friends and I can tell them to not arrow.

**Comment by Daenyth** [comment]
@krayola I'm surprised it runs at all.

**Comment by krayola** [comment]
Jesus christ... well I'll try it anyway, I hope it's the only crash reason

**Comment by Daenyth** [comment]
@krayola Is there a reason you can't upgrade your OS? I'm not asking as a rebuke, I just want to know if there's situations where people can't do it so we can improve our documentation/guidelines for troubleshooting

**Comment by krayola** [comment]
I'm scared of Apple upgrades and their planned obsolescence strategy, and even of upgrades in general. Last time I updated my Itunes I lost a lot of my cover / albums information. Somehow I feel I am ok and lucky with the one I have because it works fine so I wouldn't do that unless it was strictly necessary.  So as you see it's just a voluntary decision. Thanks again for your attention and have a good day.

**Comment by ctrlaltca** [comment]
Partial backtrace extracted from @BENJIMON95's issue #1890:
```
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   dyld                            0x00007fff6b28509d dyld_fatal_error + 1
1   dyld                            0x00007fff6b288048 dyld::fastBindLazySymbol(ImageLoader**, unsigned long) + 139
2   libdyld.dylib                   0x00007fff96f938ee dyld_stub_binder_ + 13
3   ???                             0x000000010bd116f0 0 + 4493219568
4   com.cockatrice.cockatrice       0x000000010b76817b ArrowDragItem::mouseMoveEvent(QGraphicsSceneMouseEvent*) + 779
5   org.qt-project.QtWidgets        0x000000010c63522f QGraphicsItem::sceneEvent(QEvent*) + 271
6   org.qt-project.QtWidgets        0x000000010c65ca93 QGraphicsScenePrivate::sendEvent(QGraphicsItem*, QEvent*) + 339
7   org.qt-project.QtWidgets        0x000000010c65e52a QGraphicsScenePrivate::sendMouseEvent(QGraphicsSceneMouseEvent*) + 698
8   org.qt-project.QtWidgets        0x000000010c6691d0 QGraphicsScene::mouseMoveEvent(QGraphicsSceneMouseEvent*) + 128
9   org.qt-project.QtWidgets        0x000000010c663fbe QGraphicsScene::event(QEvent*) + 1950
10  com.cockatrice.cockatrice       0x000000010b7657a5 GameScene::event(QEvent*) + 69
11  org.qt-project.QtWidgets        0x000000010c32dfa6 QApplicationPrivate::notify_helper(QObject*, QEvent*) + 294
12  org.qt-project.QtWidgets        0x000000010c331294 QApplication::notify(QObject*, QEvent*) + 7956
13  org.qt-project.QtCore           0x000000010d20e5d7 QCoreApplication::notifyInternal2(QObject*, QEvent*) + 167
14  org.qt-project.QtWidgets        0x000000010c682a7b QGraphicsViewPrivate::mouseMoveEventHandler(QMouseEvent*) + 939
15  org.qt-project.QtWidgets        0x000000010c36e5e1 QWidget::event(QEvent*) + 1633
16  org.qt-project.QtWidgets        0x000000010c46447d QFrame::event(QEvent*) + 45
17  org.qt-project.QtWidgets        0x000000010c4efe6a QAbstractScrollArea::viewportEvent(QEvent*) + 170
18  org.qt-project.QtWidgets        0x000000010c68ad75 QGraphicsView::viewportEvent(QEvent*) + 1941
19  org.qt-project.QtWidgets        0x000000010c4f0af5 QAbstractScrollAreaFilter::eventFilter(QObject*, QEvent*) + 37
20  org.qt-project.QtCore           0x000000010d20e8de QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) + 222
21  org.qt-project.QtWidgets        0x000000010c32df91 QApplicationPrivate::notify_helper(QObject*, QEvent*) + 273
22  org.qt-project.QtWidgets        0x000000010c3317f3 QApplication::notify(QObject*, QEvent*) + 9331
23  org.qt-project.QtCore           0x000000010d20e5d7 QCoreApplication::notifyInternal2(QObject*, QEvent*) + 167
24  org.qt-project.QtWidgets        0x000000010c32e980 QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) + 1072
25  org.qt-project.QtWidgets        0x000000010c38fdc2 QWidgetWindow::handleMouseEvent(QMouseEvent*) + 1298
26  org.qt-project.QtWidgets        0x000000010c38ef16 QWidgetWindow::event(QEvent*) + 118
27  org.qt-project.QtWidgets        0x000000010c32dfa6 QApplicationPrivate::notify_helper(QObject*, QEvent*) + 294
28  org.qt-project.QtWidgets        0x000000010c331294 QApplication::notify(QObject*, QEvent*) + 7956
29  org.qt-project.QtCore           0x000000010d20e5d7 QCoreApplication::notifyInternal2(QObject*, QEvent*) + 167
30  org.qt-project.QtGui            0x000000010ca27545 QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) + 2581
31  org.qt-project.QtGui            0x000000010ca263ae QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) + 126
32  org.qt-project.QtGui            0x000000010ca1088b QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 411

```
