### ISSUE TITLE
Cockatrice tokens and user custom tokens

### ISSUE THREAD

**Issue by ctrlaltca** [Cockatrice/Cockatrice#1858]
In recent cockatrice versions, oracle fetches a file containing up to date tokens courtesy of @Psithief, and saves it to tokens.xml.
While this has been an huge improvement in casual user's gameplay, every time a tokens.xml gets saved it will overwrite (= delete) any custom token manually created by the user from the "edit tokens" dialog.
I'd like to know your opinion on a few questions:
 1. do you think that is is a problem?
 2. is there any reason left for us to still need the ability to create custom, user-defined tokens?
 3. A possible solution would be to save user-created tokens (identified by the special "TK" set they are created in) and save them to a different file, e.g. "customsets/TK.xml". Do you think this is a viable solution? If you have any better idea, please explain it.

FYI, my answers are all yes.

**Comment by Daenyth** [comment]
1. Yes, we should never negate work users have done unless it's now invalid.
2. Yes, the token list is just for magic - people can use it for all sorts of things, like commander damage, etc.
3. I think using another file is quite reasonable

**Comment by ZeldaZach** [comment]
I like the idea of making the Oracle file downloaded a read-only file and we have a comment inside such as

```<!-- NOTE: DO NOT EDIT THIS FILE. PLACE CUSTOM TOKENS IN custom_tokens.xml --->```

**Comment by Psithief** [comment]
:+1: Isn't it weird that Cockatrice doesn't allow the `customsets` path to be customised in settings?

### Aside

> Yes, the token list is just for magic - people can use it for all sorts of things, like commander damage, etc.

I thought this would be more useful for counting the number of times a commander has been cast from the command zone. Commander damage is often just a clone of the commander in question.

**Comment by Daenyth** [comment]
I use storm for commander cast, but yes, people do tokens too

**Comment by tooomm** [comment]
I thought about that custom token stuff yesterday as well and was about to talk to you! :grinning: :+1: 

1. Yes
2. Yes
3. Yes, but we should think about that `TK` label and its filename... it fits nicely in the set name scheme used by mtg, but for exactly that reason it's confusing and misleading. Should be more general and helpful. As I see ctrlaltca uses two token files in parallel for now (a new tk.xml next to the old tokens.xml) --> more in the pr.

<br>
@ZeldaZach once mtgjson integrates tokens we could have them all in the cards.xml and just the `custom token file` would be left, or we decide to keep them separate... then I would like to see something like that (well, cards.xml should have something like that, too!!)

**Comment by ctrlaltca** [comment]
Another possible solution for 3:
Oracle downloads both cards data from mtgjson and tokens data from our repo, then merges them in cards.xml. Tokens.xml is reserverd for user-created tokens.

**Comment by Psithief** [comment]
> @ZeldaZach once mtgjson integrates tokens we could have them all in the cards.xml and just the custom token file would be left, or we decide to keep them separate... then I would like to see something like that (well, cards.xml should have something like that, too!!)

> Another possible solution for 3:
Oracle downloads both cards data from mtgjson and tokens data from our repo, then merges them in cards.xml. Tokens.xml is reserverd for user-created tokens.

That doesn't sound like a good solution, if I don't have a place to test the tokens.xml then how will mtgjson be able to copy my work without producing errors? :grinning:

**Comment by tooomm** [comment]
>Another possible solution for 3:
Oracle downloads both cards data from mtgjson and tokens data from our repo, then merges them in cards.xml. 

It should still be two separate processes which are followed one by one (keeping #1364 in mind).
The end result could still be one single cards.xml file, but filled first with cards and gets expanded for tokens in the next step for example.

>Tokens.xml is reserverd for **user-created tokens**.

It doesn't matter if we go with a all-included cards.xml + user token file or cards-only cards.xml + two different token files. Either way, we should call a spade a spade.
~`custom_tokens.xml` > `tokens.xml`

Especially in your scenario it would also prevent users with two different tokens.xml files (one with just custom ones and the other user with the old mix of pre-configuired plus custom ones) talking about a problem with their token files and which content they have.

<br>
>That doesn't sound like a good solution, if I don't have a place to test the tokens.xml then how will mtgjson be able to copy my work without producing errors?

Hmm, I can't follow you right now. Why would you loose your place for testing?

**Comment by ctrlaltca** [comment]
I'm quite reluctant on adding another hardcoded filename for a card database. My secret dream is to remove cards.xml and tokens.xml, and make the "customsets" folder the only place where to look for cards. Then, have a "customsets" folder for mtg, another for another game, etc, and switch between them as different "profiles". The code needed to switch the entire card database on the fly is already in place in #1859.

**Comment by Psithief** [comment]
> Hmm, I can't follow you right now. Why would you lose your place for testing?

I use Oracle too. If the files are merged, I have to push to public or change the download path in Oracle just to test. That's ridiculous. :sob:
