### ISSUE TITLE
Cockatrice crashes when trying to show popup notifications

### ISSUE THREAD

**Issue by tm512** [Cockatrice/Cockatrice#1860]
<b>OS:</b>
FreeBSD 10.2-STABLE

<b>Cockatrice version:</b>
cbea432 (2016-03-08)

___
<br>

I noticed that Cockatrice would segfault any time someone tried to PM me. Running it in a debugger, I found out that trayIcon is NULL in TabMessage::showSystemPopup, but the code assumes that it is valid. It looks like TabRoom::actShowMentionPopup would cause the same problem as well.

**Comment by Daenyth** [comment]
Thanks for the detailed report, should be a fairly easy fix.

**Comment by ZeldaZach** [comment]
Lets see what I can do
