### ISSUE TITLE
Can't receive email to confirm registration on server.

### ISSUE THREAD

**Issue by seFv2** [Cockatrice/Cockatrice#1864]
<b>OS:</b>  Intel (R) Core (TM) i7 CPU  860 @ 2.80 GHz 2.80 GHz
<b>Cockatrice version:</b> cbea432 (2016-03-08)
<br>

Dear Cockatrice Team;
I can't complete the registration on server because i can't receive the confirmation mail on my mail address (alucard-box@live.it)
Waiting for your help, greetings;
Luca.

**Comment by woogerboy21** [comment]
This issue isnt a coding issue.  You should contact the server owner/operator to get your account activated.  FYI.  Microsoft accounts are pretty notorious for having emails held.  If you have registered on the woogerworks server use the "contact us" link from the main site and it will get the process going.

**Comment by woogerboy21** [comment]
```
Mar 14 12:48:37 email sendmail[26171]: u2EGmYeA026169: to=<alucard-box@live.it>, delay=00:00:03, xdelay=00:00:03, mailer=esmtp, pri=120327, relay=mx2.hotmail.com. [207.46.8.167], dsn=2.0.0, stat=Sent ( <201603141648.u2EGmYeA026169@email.where.secureserver.net> Queued mail for delivery)
Mar 14 13:14:22 email sendmail[26375]: u2EHEJQU026373: to=<alucard-box@live.it>, delay=00:00:03, xdelay=00:00:03, mailer=esmtp, pri=120329, relay=mx3.hotmail.com. [65.55.92.136], dsn=2.0.0, stat=Sent ( <201603141714.u2EHEJQU026373@email.where.secureserver.net> Queued mail for delivery)

```
