### ISSUE TITLE
In-app way to view debug/warning/info logs

### ISSUE THREAD

**Issue by ctrlaltca** [Cockatrice/Cockatrice#1867]
By now if a non-fatal error happens when loading a custom card database or downloading a card's image, the error is logged in the console using ```qDebug()```. It would be nice if the user could see these messages, preferably in a non-blocking way (no modal messagebox), so that any issue is more easily debuggable.

Split from https://github.com/Cockatrice/Cockatrice/pull/1859#discussion_r56013944

**Comment by Daenyth** [comment]
I'd like ALL qDebug (qInfo qWarning etc) to be logged to a file explicitly with an option in the program for the user to open the file.

**Comment by Daenyth** [comment]
Implemented with #2025
