### ISSUE TITLE
Multiple Decks Function

### ISSUE THREAD

**Issue by ZenthF** [Cockatrice/Cockatrice#1868]
Wondering if it were possible to add multiple decks for use with things like Planechase so you don't have to load another game for just PC cards.

**Comment by ZeldaZach** [comment]
Not do-able yet, but you can always add it to the sideboard then mash it into facedown exile in client. This should be a feature still. Maybe when the plugins come about? Cc: @ctrlaltca

**Comment by ZenthF** [comment]
I'll try that. I'm a huge fan of the Force of Will card game and I really want to be able to play it in cockatrice, The problem is that they use two decks (Main deck and a resource deck) much like L5R.

**Comment by Daenyth** [comment]
I'd like this but it's not anywhere close for us. There's a lot of infrastructure we need to be able to support this

**Comment by Cerxi** [comment]
Would it be possible to, as a stopgap, add the ability to reveal a random card from your sideboard? This would work passably for the Force of Will game; keep your Stone deck in your sideboard and randomly reveal one as the one you're playing.

@ZeldaZach How do you put things into facedown exile? I can't seem to figure out a way to do that.

**Comment by Daenyth** [comment]
The exile zone can't have facedown cards as the app currently works. Shift+drag to the tabletop

**Comment by skwerlman** [comment]
it appears that the new un-set will require this functionality for a lot of its cards, since contraptions will use their own deck

![image](https://user-images.githubusercontent.com/6954107/32783938-656d2e9a-c91b-11e7-8317-c83037125b01.png)

**Comment by Daenyth** [comment]
Unless someone funds a developer to work on this full time from here until then, there's no way at all this will happen. This is a *major* overhaul to the card engine and will probably take months of work to fully roll out, especially if people are just working on it nights and weekends.

**Comment by Cerxi** [comment]
Any odds of my previous suggestion being workable? The ability to reveal 1 random card from sideboard as a stopgap, so you could put your contraptions in the sideboard and revealing 1 randomly? Then you could assemble that as normal. It's not quite perfect, but it seems like it'd take way less dev time than implementing a second deck.

**Comment by ZeldaZach** [comment]
Dupe #1740
