### ISSUE TITLE
Application crashed on start

### ISSUE THREAD

**Issue by TyTy03** [Cockatrice/Cockatrice#1869]
<b>OS:</b>
*Windows 7 64 bits x86*

<b>Cockatrice version:</b>
*It's the last one : Cockatrice-0.0.1~git20160308.cbea432-x86_64_qt5.exe (I can't exactly tell what is the number as I can't even launch the app*
___
<br>

I had an old version for like 8 months, unfortunatly I'm not able to say you which one it is, as I don't have the .exe anymore :(

Recently I tryed to play online with a friend, and I had an error, saying I have to update my Cockatrice ("Error : -1", if I remember well !).
So I donwload the lastest version (the .exe upper), it installs properly. At the end, it asks me to update the DB Cards (using Oracle.exe), I accept and the app crash. I tryed to launch "Cockatrice.exe", same result. I tryed to uninstall, reboot computer many time, app always crash on start.

I looked a bit there, if someone already have this issue. It seems like this one #1570 except that is not a card problem...

Any suggestions ?

Thank you

**Comment by ctrlaltca** [comment]
Can you try to:
 * uninstall cockatrice
 * check if the ```c:\program files (x86)\cockatrice``` and / or ```c:\program files\cockatrice``` still exists and delete them
 * install the last stable release: [download](https://bintray.com/artifact/download/cockatrice/Cockatrice/Cockatrice-Gatewatchers-win-x86_64.exe)

**Comment by TyTy03** [comment]
I deleted all files in `c:\program files (x86)\cockatrice` before trying to install the new version.

I tryed with the stable release, same issue :(

**Comment by woogerboy21** [comment]
Does the app present any type of error when it crashes or does it just not
show anything?  If it's not showing anything I would reinstall your VC
runtime files.  The wiki should have a link under the troubleshooting
section for MSVC120.dll .

Thanks

**Comment by ctrlaltca** [comment]
Relevant wiki section: https://github.com/Cockatrice/Cockatrice/wiki/Troubleshooting#failed-start-because-msvcpxxxdll-was-not-found

**Comment by TyTy03** [comment]
I'll check the exact error to copy/paste there when I'm home.

But, I'm pretty sure it's not a MSVC120.dll error, anyway I'll check this out later.

Thanks for your answers btw !

**Comment by tooomm** [comment]
Are you on 64 or 32 bit? In your starting post you wrote both... (x86 is 32bit)^^

This might also help: https://github.com/Cockatrice/Cockatrice/wiki/Troubleshooting#not-a-valid-win32-application

**Comment by TyTy03** [comment]
I'm ont 64 bit yes, sorry for misunderstood ^^'

**Comment by TyTy03** [comment]
Back with the detailed error :

```
Nom d’événement de problème:	APPCRASH
  Nom de l’application:	cockatrice.exe
  Version de l’application:	0.0.0.0
  Horodatage de l’application:	56b11d6a
  Nom du module par défaut:	MSVCR120.dll
  Version du module par défaut:	12.0.21005.1
  Horodateur du module par défaut:	524f83ff
  Code de l’exception:	c000001d
  Décalage de l’exception:	0000000000095c01
  Version du système:	6.1.7600.2.0.0.768.3
  Identificateur de paramètres régionaux:	1036
  Information supplémentaire n° 1:	01ed
  Information supplémentaire n° 2:	01ed35689bde779d2f9ef04f4650da99
  Information supplémentaire n° 3:	a36c
  Information supplémentaire n° 4:	a36c4312e2967399ba7f1d24743a1244
```

It's in french sorry about that :(

I noticed the `MSVCR120.dll`was mentioned, so I download the `vcredist_x64.exe` and execute it, still the problem persist...

**Comment by ctrlaltca** [comment]
This is a "common" but hard to solve problem that typically involves a previously installed version of the same library that has been installed and is now being picked up instead of the correct one.
A possible workaround is to try running the 32-bit version of cockatrice, hoping that it will pick up the correct version of the library. You can find it here: https://bintray.com/artifact/download/cockatrice/Cockatrice/Cockatrice-Gatewatchers-win-x86.exe

The long solution is to inspect all the library dependencies of cockatrice with something like [this](http://www.dependencywalker.com/) in order to find out which library is causing the wrong version of ```MSVCR120.dll``` to be loaded and try to uninstall the related software until you get cockatrice to load the correct version. Not exactly an easy and advised procedure, since it could break other software running on your pc.

**Comment by TyTy03** [comment]
Downloading the 32-bit version worked perfectly well :D

Anyway, thank you !

**Comment by Daenyth** [comment]
@ctrlaltca We should add what you just said to the troubleshooting wiki for the dll problem under "I installed vc redist and still get the same error" (also advising people to open a ticket)

**Comment by ctrlaltca** [comment]
Added
