### ISSUE TITLE
Cockatrice doesn't start in full screen on first run

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#1871]
<b>OS:</b>
Win 8.1

<b>Cockatrice version:</b>
6d85b79 (2016-03-15) (experimental build from pr)

---

<br>

While doing some testing and reinstalling the app a dozen times (including complete deletion of all leftover files) I realized that Cockatrice starts in a weird small window size **on first run** instead of full screen.
Unless you switch to full screen once Cockatrice always opens in this size and at this position.

![no fullscreen on first start](https://cloud.githubusercontent.com/assets/9874850/13817949/6f731492-eb94-11e5-9607-9f49200a2c1a.png)

**Comment by woogerboy21** [comment]
I thought we originally had it open in full screen and the functionality was changed per request to start in windowed mode?

**Comment by tooomm** [comment]
Oh really? Why would you not open an app in full screen? The interface already needs quite some space... I can't think of any benefit of using windowed mode. Especially for the default behavior.

For Oracle it makes sense. But Cockatrice?

**Comment by ZeldaZach** [comment]
It was requested to have it not in full screen mode as i recall

**Comment by tooomm** [comment]
I found what you both are talking about... 
But #1360 is different. The user was reporting that his client no longer remembers the last used window state (position and size) and therefore is not reusing that on the next start.

@ZeldaZach removed the forced "always start in full screen" in #1369, which is good.

So right now we are back to the nice feature that Cockatrice remembers its position and size. 
We just have that little bug that if there is no known former state it starts not in full screen but in this central smaller window mode.

Maybe add a pre configured window size to the ini (or wherever that last known window state is stored).
If no former setting is known (e.g. because it's the first start) it would be in full screen as expected by almost all users.
This setting would still get overwritten by user changes and remembers and reopens with that new setting if someone needs it.

**Comment by tooomm** [comment]
@Daenyth mentioned in https://github.com/Cockatrice/Cockatrice/issues/3063#issuecomment-362113439
>we also have a hardcoded launch size

<br>

Should it be like this?
 - On app close, update resolution + position values in settings.ini
 - On launch, check settings for resolution + position value from settings.ini
    - If found: take them and launch Cockatrice with this values
    - If not found: launch in max size/full screen
