### ISSUE TITLE
Add ability to add custom set from url (download it)

### ISSUE THREAD

**Issue by dev-id** [Cockatrice/Cockatrice#1874]
Would it be possible to have Cockatrice use a web-based XML file for its custom set?  

Use case: during spoiler season, it's possible to generate a new XML periodically for the newly-spoiled cards, but it has to be downloaded each time.

**Comment by ctrlaltca** [comment]
I get your point, and we could expand the recently added feature "add custom set to cockatrice", that by now permits only to load local files, to also download remote files.
This way you'll have to
 * click on a menu: card database → add custom set
 * paste the XML url in there (only the first time, we can remember the last used url) and press Ok
 * have cockatrice download the file, add it to the custom sets and reload the card db on the fly

Bonus: if a custom set with the same name already exists, cockatrice should ask the user if he wants to overwrite the old file or create another.

**Comment by radioactivehazards** [comment]
This is bad I think as most of those custom xlmls are bugged with errors. It's easier to test with Custom images and "writing cards" into your decks. A function that is Now glitched and NEEDS immediate Fixing!!!!!!!  People who do as you are suggesting and load a new xmls every day basically get viruses and many spelling errored cards and such.

**Comment by ctrlaltca** [comment]
> most of those custom xlmls are bugged with errors

agreed

> A function that is Now glitched and NEEDS immediate Fixing!!!!!!!

This feature currently doesn't exists at all !!1!!eleven!

> load a new xmls every day basically get viruses

I'm not aware of any example of this,

> nd many spelling errored cards and such.

but i understand what you mean and somewhat agree that making people load files from untrusted sources could be troublesome. How to prevent such problems is an hard matter, but we could start a discussion right here.

**Comment by radioactivehazards** [comment]
The Feature that you say does not exist Used to. I could make SOi cards into my decks without xmls very easily. Now its not possible.    Before I could find the card I want to test with and "Save image" to Custom ad then when i use the Save to clipboard/load from clipboard Features I can add in SOi card names. and when the deck is testing i get Soi cards with pictures Voila!. Now I am forced to use blank cards and use the spoiler to "refresh" what they all do.  Fixing the glitch with tokens would stop the need for Xmls every day as people would just do it the Same way that i used to as it's much easier and has less chance of errors

**Comment by Daenyth** [comment]
You should be able to use custom images for cards not in the database in the way you described. If that doesn't work, it's a bug we need to fix. It's probably the same root problem as #1768

**Comment by radioactivehazards** [comment]
i know it is a bug, thats why i posted about it 2-3 times and was told
that "my issue" was already being addressed.......and fixed...but the Fix
was a lie

**Comment by Daenyth** [comment]
I'd be happy to clear up any confusion about bugs, if there's another ticket that's been closed and we said it was solved, please reopen it and we can discuss it there. Let's keep this ticket on topic please.

**Comment by Daenyth** [comment]
> most of those custom xlmls are bugged with errors

We should make a wiki page aimed at spoiler authors showing them how to validate their xmls.

http://when-others-then-null.blogspot.co.uk/2012/12/Validate-XML-against-an-XSD-using-npp.html

And `xmllint` instructions are there already for linux/osx

**Comment by radioactivehazards** [comment]
its cool, Find another Patsy to play with i am done suggesting and "testing
new toys just to be yelled at constantly and ignored.

**Comment by woogerboy21** [comment]
So is the issue described that you can put a custom card image in the custom folder and if you create a token with that name it doesnt show a card image?

**Comment by Daenyth** [comment]
@radioactivehazards I'm sorry, I've tried to be patient with you, but I'm not going to allow you to keep attacking and ranting at us when we try to help you. If you'd like the software to be customized for your use case exactly the way you'd like, please contact me personally and we can arrange payment for me to do it.

**Comment by Daenyth** [comment]
> So is the issue described that you can put a custom card image in the custom folder and if you create a token with that name it doesnt show a card image?

I believe that's what he described, it should be easy enough to test.

**Comment by woogerboy21** [comment]
I dont recall that ever working.  You always had to have a card in the card database in order for the token to display an image.  So for example, you could create a token named "Demonic Tutor" and it will show the image.  Otherwise how would the program have the slightest idea how to link a particular image to a card object in game?

**Comment by radioactivehazards** [comment]
its cool Daeynth i just wish that when you ask for suggestions you actually wanted them. I got the wrong idea here as things that were good were being destroyed. I try to help people get off xml usage but instead you Rather them do it?? it seems to me a long winded way to do what I was Already doing with Custom images and such. but alas I understand now and i will not try to help anymore. 
I do not see how i have tried your patience by reporting any errors I see As i see them, which is Exactly what was asked of me. This is exactly what i mean. 

The Method i described is this. Go to the spoiler and save an image into Custom images. (name it correctly.) Then when you build the deck leave spots for new cards and Save the deck to the clipboard. Now load the deck from the clipboard and Type in the text box all the "New" cards out. Once done save deck and enjoy as when you draw a new card you will have a picture and be able to refresh yourself on its effects.     I have shown Several users how to do this in my spare time and ALL agree that its much easier and better than the XML method.

**Comment by radioactivehazards** [comment]
On a Seperate not Daenyth, i think i figured out the 32 bit 64 bit error...ill get back at you but i think for some reason i had 2 folders in my "program data" area and cockatrice was in the wrong one. So i am Combining both folders right now, its copying all the data and will take time.

**Comment by radioactivehazards** [comment]
Yeah that did Not work. Still no idea why my 64 bit machine is Forced to run 32bit cockatrice

**Comment by Daenyth** [comment]
I've deleted about all the off topic posts

**Comment by Jinxstands4Jinx** [comment]
xmls are cumbersome and I find it a drag to have to keep asking people for new ones. is there another way?

**Comment by Daenyth** [comment]
Yes, but it would involve rewriting portions of the app and invalidating existing tooling like MSE's export scripts

**Comment by leematos** [comment]
@Daenyth, in theory could a "Helper app" just replace the custom XML file? What I'm asking is, will trice freak out if the xml was changed without _it_ changing it? 

Possible solution:

"spoiler season app" -> when you launch it, it looks for an updated xml from "some trusted source", downloads it, puts it in the right folder for trice, done.

**Comment by Jinxstands4Jinx** [comment]
Well, I heard about a method with the Custom folder. I am shy on details but it was a better method. I dunno maybe it can help?

**Comment by Daenyth** [comment]
@leematos someone could write such a thing. So far no one has. Custom sets are easy to use when people know they exist.

**Comment by ZeldaZach** [comment]
I'm a bit concerned on the security side of things. We've made it so users can open their custom location via settings and put files in manually.

**Comment by ebbit1q** [comment]
dupe https://github.com/Cockatrice/Cockatrice/issues/4109
