### ISSUE TITLE
Oracle Doesn't Download Foreign Data

### ISSUE THREAD

**Issue by ZeldaZach** [Cockatrice/Cockatrice#1876]
Some users may want to have information in a foreign language. When you change it in client, it asks the cards.xml file to provide the translations for the cards/desc if possible.

Oracle, when trying to download the AllSets-x file (the one with foreign data), doesn't seem to parse the foreign data and discards it as junk. This is not expected and needs to be re-evaluated.

**Comment by tooomm** [comment]
Are you talking about card name + card text?

The `AllSets-x` file with extras just has `foreignNames` of the card:
"Foreign language names for the card, if this card in this set was printed in another language. An array of objects, each object having 'language', 'name' and 'multiverseid' keys. Not available for all sets."
So there are no information about card texts right now. But lsmoura is working on it, at least he started at one point.

**Comment by ZeldaZach** [comment]
Related to #3406
