### ISSUE TITLE
Cockatrice should create an empty customsets folder on launch

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#1884]
Users get confused by customsets because they have to manually create the folder. Cockatrice should create it on launch to make it easier for them

**Comment by ctrlaltca** [comment]
Cockatrice already creates it, if it's able to:
https://github.com/Cockatrice/Cockatrice/blob/36c3536e0cfc8a2031911a150995f1fc0cb7f518/cockatrice/src/main.cpp#L198
