### ISSUE TITLE
This app can't run on your PC

### ISSUE THREAD

**Issue by Baneshe** [Cockatrice/Cockatrice#1885]
<b>OS:</b>
Win 10
<b>Cockatrice version:</b>
Most recent / unknown installer name is "Cockatrice-0.0.1-git20160322.3c58003-x86_64_qt5"

___
<br>

I get the error "This app can't run on your pc" even when ran as administrator (tried reinstalling several times)

![image](https://cloud.githubusercontent.com/assets/18059800/14033161/86b52f04-f1ee-11e5-9572-c0a7cd951b84.png)

**Comment by Daenyth** [comment]
From what I can find on google it seems like that error might be related to 64bit vs 32bit installs. Does the 32bit installer work for you?

https://bintray.com/artifact/download/cockatrice/Cockatrice/Cockatrice-Gatewatchers-win-x86.exe

**Comment by tooomm** [comment]
The 32bit installer solved the issue for you @Baneshe ?

Next time leave a short message and let us know, please (+ you can even close the issue for yourself!). ;)

**Comment by Daenyth** [comment]
@tooomm Looks like they left a :+1: on my link, so I'm assuming it worked.

**Comment by Daenyth** [comment]
@tooomm Maybe we should add a `This app can't run on your PC` entry to the troubleshooting wiki?

**Comment by tooomm** [comment]
I did? It just links to the same entry. Check the ToC. :P
