### ISSUE TITLE
Socket error: Connection Timed Out

### ISSUE THREAD

**Issue by mp009** [Cockatrice/Cockatrice#1886]
<b>OS:</b>
*Win 8.1*

<b>Cockatrice version:</b>
cbea432 (2016-03-08)
___
<br>

I can never connect to a sever, if it's not a whole other problem like Chickatrice's forum bridge problem right now, it's the fact that anything that might work will time out, like registering to woodgerworks. I seem to be doing everything right with the port of 7474.

**Comment by woogerboy21** [comment]
Hello!

Do you mean woogerworks?  And the port is either 4747 (not 7474) or you can use port 443.

Thanks

**Comment by ZeldaZach** [comment]
This doesn't seem to be related to the main project
