### ISSUE TITLE
Add color column in deck editor.

### ISSUE THREAD

**Issue by Jinxstands4Jinx** [Cockatrice/Cockatrice#1888]
In the Deck editor section where we can sort cards would it be hard to add "Color" to the list?

We currently have name/set/CMC/type/ and p.t   could we add Color here?

Also for DFC could we have a way to check the second side?

**Comment by Daenyth** [comment]
That's reasonable.

**Comment by tooomm** [comment]
Could you update the issue name with a description that brings it to the point, please?

**Comment by ZeldaZach** [comment]
I have no problem doing this, just is color necessary?

**Comment by Jinxstands4Jinx** [comment]
It helps when trying to sort cards for brewing purposes. Also when New sets come out this would list the cards in Numerical order making rating of cards easier and able to analyze better.

**Comment by tooomm** [comment]
>We currently have name/set/CMC/type/ and p.t could we add Color here?

We don't have `CMC` there, we have `Mana cost` which include color as well.
Converted mana cost would be different.

<br>
>It helps when trying to sort cards for brewing purposes.

We have the filters for that - and they accomplish that way better and more flexible?

<br>
>Also when New sets come out this would list the cards in Numerical order making rating of cards easier and able to analyze better.

Numerical order? I don't understand what you mean there and how the color column would help. Explain yourself please. :)

**Comment by Jinxstands4Jinx** [comment]
When new sets come out some people like to read the cards in their own colors to get a better idea of how they will flow for limited. This way plays can sort the cards out in color/numerical order and get a feel for how strong or weak each color will be for draft and or sealed formats. sorting by any other means that we already have does not allow this as the set gets scrambled up.  
About numerical order. the sets have numbers on each card in the order it is printed. those numbers would auto be sorted by simply doing a color/name sort. similar to when you sort by type then by name to find certain cards for your brews.
