### ISSUE TITLE
Windows DB Debug DLLs

### ISSUE THREAD

**Issue by woogerboy21** [Cockatrice/Cockatrice#1889]
When compiling the source in windows using Debug the QT database driver debug DLL's are not copied into the plugins/sqldrivers folder.  This prevents running servatrice in debug mode.  If anyone is curious the fix should be that the qsqlmysqld.dll could use copied into the folder along with the regular qsqlmysql.dll (non-debug) file.

**Comment by ctrlaltca** [comment]
Even if you compile cockatrice in "Debug" mode, you should link to the "Release" version of Qt (and thus need the non-debug plugins), unless you are willing to debug Qt itself.

Before https://github.com/Cockatrice/Cockatrice/commit/54ce135e0cb8f4e91f1b6dd8b59e7181af2f37a1 the CMake scripts used to copy the "Debug" version of the plugins if Cockatrice was compiled in "Debug" mode. While testing compilation windows package creation, i found out that Cockatrice would default link to the "Release" version of Qt anyway, unless you manually changed the Qt libraries in CMake.

**Comment by woogerboy21** [comment]
You can't start the applications within the VS interface in debug mode when trying to cross link like you mention.  Atleast I have yet to be able to.  The debugger looks for the d.dll's when executing the compiled forms of the applications and simply throws an error.
