### ISSUE TITLE
Cockatrice doesn't launch anymore

### ISSUE THREAD

**Issue by amaury-guy** [Cockatrice/Cockatrice#1891]
I run cockatrice on <b>Ubuntu 14.04</b>

I think I have the lastest version: <b>535e19f 9f3b500  2016 mar 22</b>
___
<br>

Well, I installed cockatrice yesterday and it worked perfectly fine, great work by the way !!
Today, I opened it again and worked fine.
Then, I remember having unistalled the default video player with its packages and having it replaced by VLC (don't know if it can be useful), closing Cockatrice, and then, being unable to launch it again.

I see the icon on the launching panel, but the interface doesn't show.

Here is what I get when I launch it on my terminal:

```
amaury@amaury-K53SD:~/Cockatrice/build/cockatrice$ ./cockatrice
Theme name not set, setting default value 
Theme changed: "Default" 
Sounds theme name not set, setting default value 
SoundEngine: disabling sound
Sound theme changed: "Default" 
SoundEngine: disabling sound
15823 cards in 191 sets loaded 
loadCardDatabase(): Path = "/home/amaury/.local/share/Cockatrice/Cockatrice/cards.xml" Tokens = false Status = 0 
16143 cards in 192 sets loaded 
loadCardDatabase(): Path = "/home/amaury/.local/share/Cockatrice/Cockatrice/tokens.xml" Tokens = true Status = 0 
main(): starting main program
QSystemTrayIcon::setVisible: No Icon set
main(): MainWindow constructor finished
main(): ui.show() finished
cache fail for "_trice_card_back_356252" 
cache fail for "_trice_card_back_356249" 
```

Thank you for your help
Amaury from France

**Comment by amaury-guy** [comment]
Hi,
It appears that Cockatrice worked fine on Linux 4.2.0-27, and that these bugs appeared with Linux 4.2.0-34
Is there a way ton get it working on the later linux ?

**Comment by Daenyth** [comment]
I wonder if this could somehow be related to #1895 ?

> It appears that Cockatrice worked fine on Linux 4.2.0-27, and that these bugs appeared with Linux 4.2.0-34

Just to be clear; cockatrice worked, then you upgraded your kernel, and then it stopped working?

Can you try recompiling it?

**Comment by amaury-guy** [comment]
Hi Daenyth !

> I wonder if this could somehow be related to #1895 ?

Well, the symptoms seem identical, even if the OS is different. I can provide a snapshot of what occurs when Trix fails to launch.

> Just to be clear; cockatrice worked, then you upgraded your kernel, and then it stopped working?

I think so. I don't remember quite well. I have the felling I updated the kernel, restarted my computer, and that cokatrice worked fine for half an hour, then issue #1891 appeared.

But in the GRUB, when I launch the older kernel version, it works fine ! So for the moment, I can use Trix asking the older kernel in the grub.

> Can you try recompiling it?

I followed again all the steps on git hub wiki:
[https://github.com/Cockatrice/Cockatrice/wiki/Compiling-Cockatrice#ubuntu-14xx](url)
and I got the same problem. Do I have to do something else?

Thank you very much for your help

**Comment by ctrlaltca** [comment]
> So for the moment, I can use Trix asking the older kernel in the grub.

When i read this statement a shiver runs down my spine.
I have a 14.04 vm, i'll try to update it and check if i can reproduce the problem

**Comment by amaury-guy** [comment]
Hi folks,

I had another problem.

Trix doesn't launch anymore after I deleted the audio software "rhythmbox" and its dependency packages. Cockatrix's icon, as oracle, wasn't visible anymore when I searched for these programs.
I tried recompiling from the latest version, updating cmake, as said in #1899 
But an error occured while executing `make package -j2` :

`/home/amaury/Cockatrice/cockatrice/src/soundengine.cpp:5:24: 
fatal error: 
QAudioOutput: no such file or directory 
 #include <QAudioOutput> 
                        ^
compilation terminated.
make[2]: *** [cockatrice/CMakeFiles/cockatrice.dir/src/soundengine.cpp.o] Erreur 1
make[2]: *** Waiting for untermined tasks....
make[1]: *** [cockatrice/CMakeFiles/cockatrice.dir/all] Erreur 2
make: *** [all] Erreur 2
`
I tried to install rhythmbox again, but got the same message.

I assume an audio package is missing, but I'm a little bit lost with kernel updates and dependencies right now ...

Thanks for your help !

**Comment by ctrlaltca** [comment]
For that specific error try running ```sudo apt-get install qtmultimedia5-dev libqt5multimedia5-plugins```

**Comment by amaury-guy** [comment]
Hi ctrlaltca, thanks for the fast answer,

I already tried this, and wasn't able to install them. The terminal told me (approximative translation from my french terminal):
`Following packages contain non satisfactory dependencies :
 libqt5multimedia5-plugins : Dépend: libqt5multimedia5 (= 5.2.1-0ubuntu5) but won't be installed
                             Dépend: libqgsttools-p1 (>= 5.2.1-0ubuntu5) but won't be installed
 qtmultimedia5-dev : Dépend: libqgsttools-p1 (= 5.2.1-0ubuntu5) but won't be installed
                     Dépend: libqt5multimedia5 (= 5.2.1-0ubuntu5) but won't be installed
                     Dépend: libqt5multimediawidgets5 (= 5.2.1-0ubuntu5) but won't be installed
E: Impossible to solve problems, bad packages are in mode « keep it as it is ».
`
Thank you for your enlightenment !

**Comment by ctrlaltca** [comment]
Wait, did you previously compile Cockatrice using Qt4 or Qt5?
If you used Qt4: ```sudo apt-get install -y qtmobility-dev libqt4-dev```
If you used Qt5, my previous advice was correct, but somehow apt-get is unable to re-install the missing packages. I'd try to
```
sudo apt-get clean
sudo apt-get update
sudo apt-get -f install
```
and see if it fixes the package cache.
Please be careful, playing wth packages could compromise your system.

**Comment by amaury-guy** [comment]
Thanks for your help, but I got exactly the same message. 
I will take time to understand better the terminal language before trying anything again.
See you soon.

**Comment by Daenyth** [comment]
Please open a new issue for unrelated problems
