### ISSUE TITLE
Qt5 versions of Cockatrice don't open on my Windows 7 systems

### ISSUE THREAD

**Issue by MotherofRuins** [Cockatrice/Cockatrice#1895]
<b>OS:</b>
Windows 7 Home Premium SP1 64-bit (2010 HP tower)
Windows 7 Professional SP1 64-bit (2010 HP tower)
Windows 7 Professional SP1 64-bit (2014 Lenovo laptop)

<b>Cockatrice version:</b>
Any version of Cockatrice since June 2015 built with Qt5, including the latest, will not open its main window.  Can't tell you the build because it won't open.

Have been running version d55e44e since 9/23/2015 (special Qt4 build).  It works on all three of those systems.  But the new tokens don't work now, e.g., so I need to upgrade.
___
<br>

Very willing to assist, including running debugging or verbose logging versions.  

32-bit version of Gatewatchers also does not open the window.

**Comment by ctrlaltca** [comment]
If i understand correctly the problem installs fine but when trying to start cockatrice nothing happens, no error at all?

Im quite confident that your PCs are recent enough to support a Qt5 build of Cockatrice.

**Comment by Daenyth** [comment]
Until we get a new version working I believe you can fix the tokens by editing the XML file and deleting the reverse-related elements.

**Comment by MotherofRuins** [comment]
@ctrlaltca: You are correct.  A process appears in Task manager for about 20 seconds, then it just goes away.  Nothing ever shows in the applications tab.

@Daenyth: Thanks for the workaround.  That worked.

**Comment by Daenyth** [comment]
Have you tried both 32bit and 64bit versions of cockatrice?

**Comment by MotherofRuins** [comment]
Yes

**Comment by Daenyth** [comment]
@woogerboy21 If you run trice in VS in debug mode can you get the console output that way?

**Comment by MotherofRuins** [comment]
I don't have Visual Studio, just the runtimes.

**Comment by MotherofRuins** [comment]
Is that something you want me to do?

**Comment by Daenyth** [comment]
I was trying to ask one of the people using windows if running in VS would allow you to get debug output.

If you'd like to give it a try, there's instructions on the wiki for setting it up (warning: PITA).

Could you be running some kind of antivirus or something which automatically kills the app? I know some of them have false positives on us because of a compression library that we use.

**Comment by woogerboy21** [comment]
> @woogerboy21 If you run trice in VS in debug mode can you get the console output that way?

Yes you can.  I wish in windows it was as easy as linux.

**Comment by MotherofRuins** [comment]
I tried it with my antivirus disabled - same result.

To run it in VS debug mode I have to compile Cockatrice.  I tried that once a few years ago but ran into roadblocks with the dependencies before I could even make.  I'll try again, but it will take some calendar time, so don't close this thread.  I'll respond one way or another.

**Comment by tooomm** [comment]
Maybe [this](https://github.com/Cockatrice/Cockatrice/wiki/Debugging#windows) is helping you!

**Comment by tooomm** [comment]
[New official Cockatrice version out!](https://github.com/Cockatrice/Cockatrice/releases/tag/2016-05-06-Release)
Can you please try this one and report back?

Or did you managed to solve the problem by your own in the meantime @MotherofRuins?

**Comment by Daenyth** [comment]
Please reopen if this is still a problem.
