### ISSUE TITLE
Token Cards in customsets/*.xml are not Listed/Available

### ISSUE THREAD

**Issue by vjjft** [Cockatrice/Cockatrice#1896]
<b>OS:</b>
Windows 7 Ultimate 6.1.7601 SP 1 Build 7601

<b>Cockatrice version:</b>
535e19f  (2016-03-18)
___

Token Cards in customsets/*.xml are not listed/available

Having customsets/custom_tokens.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<cockatrice_carddatabase version="3">
<cards>
  <card>
    <name>_Test Token</name>
    <set>TEST</set>
    <type>TEST TOKEN</type>
    <text>This is a test token in customsets/custom_tokens.xml</text>
    <token>1</token>
  </card>
</cards>
</cockatrice_carddatabase>
```
does not result in a token card '_Test Token'

Same behavior exhibited when token card is included in a file containing non token cards (which are listed properly)

[customsets.zip](https://github.com/Cockatrice/Cockatrice/files/195789/customsets.zip)

**Comment by ctrlaltca** [comment]
This problem never made it into an issue here, but i encountered it while working on #1859, that already contains a fix for it.
