### ISSUE TITLE
Name column way too big, can't resize normally

### ISSUE THREAD

**Issue by Psithief** [Cockatrice/Cockatrice#1897]
f217551

![deck_editor_name_column](https://cloud.githubusercontent.com/assets/1124846/14166562/2affc56c-f747-11e5-9a5d-4f492980fb03.png)

The name column automatically expands to ridiculous size on 1920x1080 and the other columns are just one size. I can't modify the name column width, except by dragging the right-hand edge of the last column to the right (out of the table). That's a very obscure solution, one I don't think most users will understand.

The name text is way too far from the other text in the grid, so it's hard to read. It almost makes more sense to just have the name column as the far-right one now, bringing us back to the original problem.

I don't know the best solution, but the current one isn't a positive change for legibility.

In a portrait view, all the other columns are suddenly hidden. It becomes even more difficult to understand how to shrink the columns with name locked when the user has to scroll horizontally. The minimum name length in this situation is still much too wide.

![deck_editor_name_column_portrait](https://cloud.githubusercontent.com/assets/1124846/14166564/2e6194ba-f747-11e5-8565-7ebef2793654.png)

**Comment by ZeldaZach** [comment]
I can confirm this is an issue, we should see about setting fixed max-widths potentially

**Comment by ctrlaltca** [comment]
I'll have a took at this, than you for pointing out the problem.
