### ISSUE TITLE
Westvale Abbey image flipped

### ISSUE THREAD

**Issue by professionalecho** [Cockatrice/Cockatrice#1898]
<b>OS:</b> Windows 10

<b>Cockatrice version:</b> cbea432 (2016-03-08)
___
<br>

The card Westvale Abbey, which transforms into Ormendahl, Profane Prince, is actually showing Ormendahl on the front face and Westvale Abbey on the back. The descriptions are correct, but the images are flipped.

**Comment by tritoch** [comment]
Issue with mtgjson / gatherer, see https://github.com/lsmoura/mtgjson/issues/138

**Comment by ctrlaltca** [comment]
Yep, unfortunately we can't fix wrong images on Gatherer. Thank you for reporting anyway.
