### ISSUE TITLE
Unable to compile on Ubuntu 14.04.4

### ISSUE THREAD

**Issue by skwerlman** [Cockatrice/Cockatrice#1899]
<b>OS:</b>
Ubuntu 14.04.4

<b>Cockatrice version:</b>
2d2958e931b9facd3642b6a8e2e39e34f322bc08 and later

___
<br>

```
Welcome to Ubuntu 14.04.4 LTS (GNU/Linux 3.13.0-45-generic x86_64)

* Documentation:  https://help.ubuntu.com/

0 packages can be updated.
0 updates are security updates.

You have new mail.
Last login: Thu Mar 31 18:47:02 2016 from [removed]
wheeler@bfs:~$ cmake --version
cmake version 2.8.12.2
wheeler@bfs:~$ sudo apt-get upgrade
[cut for brevity]
wheeler@bfs:~$ sudo apt-get install cmake
Reading package lists... Done
Building dependency tree
Reading state information... Done
cmake is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
wheeler@bfs:~$
```

As you can see from the above log, `cmake` will not update past 2.8, though Cockatrice requires version 3.1 to compile. The compilation instructions on the wiki don't mention doing anything special to update `cmake`, but I'm wondering if it was an accidental omission, or if I'm an idiot with a misconfigured `apt`.

**Comment by ctrlaltca** [comment]
The last stable version of Cockatrice (https://github.com/Cockatrice/Cockatrice/releases/tag/2016-02-03-Release) works fine with cmake 2.8. The current development branch requires cmake >= 3.1 in order to have full c++11 support on all platforms. You can get it on 14.04 from an external ppa:
```
  sudo add-apt-repository -y ppa:smspillaz/cmake-master
  sudo apt-get update -qq
  sudo apt-get -y purge cmake
  sudo apt-get install -y cmake
```

**Comment by ctrlaltca** [comment]
Also, you can get a precompiled package of the latest Cockatrice development version for 14.04 here: https://bintray.com/package/files/cockatrice/Cockatrice/Cockatrice-git?order=asc&sort=name&basePath=Ubuntu%2Ftrusty&tab=files

**Comment by skwerlman** [comment]
Thanks; might want to make a note about the new dependency, since its mentioned anywhere I could find.

**Comment by Daenyth** [comment]
> Thanks; might want to make a note about the new dependency, since its mentioned anywhere I could find.

You're right, we should update the wiki

**Comment by tooomm** [comment]
Could someone of the linux guys update our [Compiling Instructions](https://github.com/Cockatrice/Cockatrice/wiki/Compiling-Cockatrice#ubuntu-14xx), please? Same for 12.02?

**Comment by ctrlaltca** [comment]
Done
