### ISSUE TITLE
Can no longer click on a token in the token list and start typing a name to find it quicker.

### ISSUE THREAD

**Issue by chtref** [Cockatrice/Cockatrice#1903]
<b>OS:</b>
Windows 7 Service Pack 1

<b>Cockatrice version:</b>
f217551

___
<br>

In prior versions, it was possible to click on a token from the list (example: Ape) and start typing the name of the token you wanted to create (example: "Spir" for Spirit) in order to select it faster, but this feature no longer works consistently.

**Comment by ctrlaltca** [comment]
I just tested and it seems to work as usual:
```Ctrl+T, click on the list, write "Goblin", press ok```
Can you please elaborate on the problem?
![new](https://cloud.githubusercontent.com/assets/1631111/14231519/d6b38ae2-f986-11e5-9cda-563039910702.gif)

**Comment by Lechek** [comment]
I have got a similar problem. My token list contains of 1 token: Angel, white, 4/4 flying

No other tokens are shown in the list. I updated the list today, the xml file is 212kb.

I also checked on the link in settings, it is correct.

Any ideas?

**Comment by ctrlaltca** [comment]
@Lechek : have a look at #1810, or just install a more recent version of cockatrice.

**Comment by Lechek** [comment]
thx

**Comment by chtref** [comment]
I have done the same thing as you did, and I have noticed "Goblin" works more consistently than Spirit. Here is what happens when I try to type Goblin. Please disregard quality issues.
![cockatrice_goblin](https://cloud.githubusercontent.com/assets/10520926/14233306/b77d0124-f992-11e5-8684-bf403bf9fcec.gif)

Here is what happens when I try to type Spirit.
![cockatrice_spirit](https://cloud.githubusercontent.com/assets/10520926/14233310/c129aef2-f992-11e5-9a14-0e4efefc4785.gif)

As you can see, the Spirit demo doesn't work. I have found one workaround, but it is very poor. You need to scroll down all the way to the bottom of the tokens list and THEN search for Spirit.
![cockatrice_spirit_2](https://cloud.githubusercontent.com/assets/10520926/14233318/08d262bc-f993-11e5-9a68-df8d61c55dc9.gif)

Perhaps the new token parser is the cause of this?

**Comment by ctrlaltca** [comment]
Thank you for the details on the problem, i've been able to reproduce the problem and the fix is in https://github.com/Cockatrice/Cockatrice/pull/1905
