### ISSUE TITLE
Default Layout displayed wrong (but resize button on Windows fixes it)

### ISSUE THREAD

**Issue by chtref** [Cockatrice/Cockatrice#1904]
<b>OS:</b>
Windows 7 Service Pack 1

<b>Cockatrice version:</b>
f217551

---

<br>

When entering any room (and sometimes the deckbuilder), the layout is displayed wrong. Resetting the default layout also shows this particular layout. Screen is 1368x768.
![cockatrice_defaultlayout](https://cloud.githubusercontent.com/assets/10520926/14233390/fdfb2ba6-f994-11e5-8bdf-f9215ff29b07.png)

Do note that clicking on the resize button twice (make smaller, then bring back to screen size) makes the layout perfect.
![image](https://cloud.githubusercontent.com/assets/10520926/14233431/1f6afa2c-f996-11e5-8924-badaa5ed6262.png).

I have also noticed that every time you create a new room, the chat will become lower than previously. Same for the game panel.

**Comment by ctrlaltca** [comment]
I suppose the sum of the default heights for all the elements is more than your screen's available space.
I've experienced this problem, too in the past.

**Comment by tooomm** [comment]
Just guessing here... you're complaining that the typing field in the message dock is hidden behind your taskbar?

Trice should run fine on 1368x768, which is a small but very basic and common resolution on a bit older hardware or smaller devices.

But I have the same problem as you on Win 8.1:
![smallscreen1](https://cloud.githubusercontent.com/assets/9874850/14327099/30c9f6ae-fc31-11e5-9bcf-d0a7d6c61fb9.png)
<br>
As you said, after resizing the window once (hitting "restore down" & apply "full screen/maximize" again) I see everything.
Plus it will stay like this for every other game I create afterwards, even when closing/restating the app in between. But just as long as I don't change the monitor resolution in between.
If I connect my external monitor with bigger resolution and go back to internal small resolution I run into the same problem again.

So this should be an issue about handling different resolutions and converting/adjusting saved positions in settings?

**Comment by Daenyth** [comment]
> So this should be an issue about handling different resolutions and converting/adjusting saved positions in settings?

Good call. On start, we should clamp the stored settings to the available screen space (if possible)

**Comment by chtref** [comment]
> Just guessing here... you're complaining that the typing field in the message dock is hidden behind your taskbar?

Correct. It does have a few other issues related to it though. GIF below.

> Plus it will stay like this for every other game I create afterwards, even when closing/restating the app in between.
Not quite. It will always try to hide more and more every time.
![cockatrice_baddims](https://cloud.githubusercontent.com/assets/10520926/14340693/f5591646-fc57-11e5-93b5-97fe107c6415.gif)

Best seen when comparing the last frame of this gif with the first frame of this gif. Viewing this gif a few times should help identify what's going on.

>If I connect my external monitor with bigger resolution and go back to internal small resolution I run into the same problem again.
Is this the same for you @chtref ?
I believe so.

**Comment by chtref** [comment]
Would like to bump this issue because it is labeled as Easy Change and has been in every releases afterwards. I am now using Windows 10 instead of Windows 7 and my screen resolution is now 1920x1080.

**Comment by tooomm** [comment]
Linking https://github.com/Cockatrice/Cockatrice/issues/2621

**Comment by ebbit1q** [comment]
I merged these tickets into https://github.com/Cockatrice/Cockatrice/issues/4114
