### ISSUE TITLE
Hotkey ctrl+e not working, the rest fine.

### ISSUE THREAD

**Issue by martok22** [Cockatrice/Cockatrice#1907]
<b>OS:</b>
"Xubuntu 14.04.4 LTS Trusty" x64bit (where cockatrice is installed).
Dual boot: Windows 7 Ultimate x64bit.

<b>Cockatrice version:</b>
Version 2d43ab9 (2016-02-17)*

---

<br>
Since i've installed cockatrice, i've had this problem. The hotkey ctrl+e (draw x cards) doesn't work, but the other hotkeys work fine. 

I've just tested that in a single player game, ctrl+e works fine, yet when playing a 2 player game, the binding doesn't work. The other shorcuts work ok.

Drawing cards with right click-> draw cards works. 

I've removed app-qt5menu during installation, and followed this guide for that: https://github.com/Cockatrice/Cockatrice/wiki/Compiling-Cockatrice#ubuntu-14xx

**Comment by Daenyth** [comment]
Do you mean a single player game in local mode, or a game on the server with max players set to 1?

**Comment by someKindOfGenius** [comment]
I also have this issue, but ctrl+u also does not work. In local games it works fine, but doesn't work at all on the server.

**Comment by martok22** [comment]
Sorry for the delay.

> Do you mean a single player game in local mode, or a game on the server with max players set to 1?

Both. 

I've managed to avoid the problem by changing the binding to another hotkey.

**Comment by ebbit1q** [comment]
duplicate: https://github.com/Cockatrice/Cockatrice/issues/2219
