### ISSUE TITLE
Expose card number on the set for Custom download URL

### ISSUE THREAD

**Issue by L4D15** [Cockatrice/Cockatrice#1908]
Would be possible to insert a new field to get the card number into the custom image download URL?

With that, it would be possible to download the images from magiccards.info, who are of better quality than the gatherer ones.

**Comment by ctrlaltca** [comment]
Sure, it's a good idea, and it has already been proposed here: https://github.com/Cockatrice/Cockatrice/issues/1741
Closing this as a duplicate, please refer to the other ticket.
