### ISSUE TITLE
Cockatrice Server registrieren

### ISSUE THREAD

**Issue by maniac3001** [Cockatrice/Cockatrice#1909]
Windows XP
323fc06 (2016-02-02)
___
Ich kann mich nicht zum Server verbinden.
Denke, Ich muss mich erst beim Server registrieren, weiss aber nicht wie.
Was muss ich eingeben bei Host und Port?

**Comment by Daenyth** [comment]
You can register with a server using the "register to server" action from main "Actions" menu. It should have a list of known servers and you can select which server you want to register to.

Please let me know if you need further help.

**Comment by tooomm** [comment]
Falls du dich für den Woogerworks Server registrieren möchtest schau mal auf deren Seite:
http://woogerworks.com/?option=com_content&view=article&id=107
