### ISSUE TITLE
Recovering cards from dead players.

### ISSUE THREAD

**Issue by Jinxstands4Jinx** [Cockatrice/Cockatrice#1912]
Can we input a way to recover a card from a player who has "left" a game. When a player concedes all they own is "taken" off the battlefeild. Is there a way to fix this? so cards taken by effects like Act of treason or Gilded drake can be returned to the owner.

**Comment by Daenyth** [comment]
Cards they own should be removed.

I think you're saying that cards they control but do not own are removed from the game and can't be recovered, right?

I forget the rules for this situation. Can you point to the comp rules about non-owned cards from a player leaving a multiplayer game?

**Comment by Jinxstands4Jinx** [comment]
Your second statement is what I am pertaining to.
"I think you're saying that cards they control but do not own are removed from the game and can't be recovered, right?"

800.4a. When a player leaves the game, all objects (see rule 109) owned by that player leave the game, any effects which give that player control of any objects or players end, and all spells and abilities controlled by that player on the stack cease to exist. Then, if there are any objects still controlled by that player, those objects are exiled. This is not a state-based action. It happens as soon as the player leaves the game. If the player who left the game had priority at the time he or she left, priority passes to the next player in turn order who’s still in the game.

I understand the card stays exiled. But for effects like Rift Sweeper. The player could get the card back. Also for effects that "Process" cards another player could get the card or cards back. According to this rule the objects controlled but NOT owned would just be exiled. 

Players leave games for a variety of reasons, but they should not be allowed to perma-exile things just to mess the game up for those who remain.

**Comment by Daenyth** [comment]
Agreed. This is tricky.

Let's see - in a tabletop game this would be handled by the leaving player physically sorting out cards back to owners and the owners putting them in the appropriate zones.

I think the nearest solution for us is to take non-owned cards in play and return them to the owner's play zone. Then non-owned cards in non-play zones can be sent to the owner's exile. There should be chat messages for every such card returned (depending how we implement this may happen automatically without needed change).

Does that sound like the appropriate measure?

**Comment by Jinxstands4Jinx** [comment]
That sounds about what I was thinking we could do. Yes.

**Comment by Daenyth** [comment]
@ctrlaltca Do you think we can do this without modification to the protocol?

**Comment by ctrlaltca** [comment]
Adding some "cleaning" procedure when a player concedes should be quite easy.
I'm afraid that IIRC the server is not tracking card ownership, but only the current zone position. Saving the original owner player for each card will require some more changes.

**Comment by Daenyth** [comment]
> the server is not tracking card ownership

Ugh, really? I'll have to double check this. If so that's not great.
