### ISSUE TITLE
no card images and i cant join chat room help!

### ISSUE THREAD

**Issue by Revanchrist** [Cockatrice/Cockatrice#1913]
<b>OS:</b>
Win 7 SP1

<b>Cockatrice version:</b>
d55e44e 20150923

___
<br>

**Comment by ctrlaltca** [comment]
I'm afraid we can't really help you on such a generic description of the problem. if you care to elaborate on that, i'll be glad to assist you.

**Comment by Daenyth** [comment]
If you have a specific error message or screenshot, that would help.
