### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by nathanmo** [Cockatrice/Cockatrice#1916]
![screenshot_3](https://cloud.githubusercontent.com/assets/18338396/14370655/7b9c7528-fced-11e5-9646-c2de20e6d4bf.png)
<b>OS:</b>
Windows 10.1

<b>Cockatrice version:</b>
(Cant find out due to problem)

___
<br>

I am unable to use Cockatrice because of a missing file, which does not seem to come with the program.

**Comment by ZeldaZach** [comment]
Look on the wiki. this is a common troubleshooting problem.

**Comment by Daenyth** [comment]
https://github.com/Cockatrice/Cockatrice/wiki/Troubleshooting#failed-start-because-msvcpxxxdll-was-not-found

**Comment by nathanmo** [comment]
It says something about improper windows, how would I download the nessesary requirements to run this program?

**Comment by Daenyth** [comment]
If you downloaded the 32bit version of cockatrice you need to get the 32bit version of the VC redist files. If you got the 64bit version, then you need the 64bit redist files.

We aren't allowed to install these for you automatically because of microsoft's licensing rules.
