### ISSUE TITLE
Menu Layout

### ISSUE THREAD

**Issue by JineteDV** [Cockatrice/Cockatrice#1923]
http://imgur.com/RNii2wc

The Windows menu layout at the top should match what it looks like on OSX. Having it be cockatrice, actions, room, help is less confusing that cockatrice, cockatrice, room, help when we're trying to help people navigate through the menus.

**Comment by ctrlaltca** [comment]
Unfortunately we can't mess with the first "cockatrice" menu: it's created by OSX and we can't change its contents out of some specific items, eg. providing an entry for "preferences"

**Comment by ctrlaltca** [comment]
oh sorry, do you mean we should change the windows one to match the osx one?

**Comment by JineteDV** [comment]
Yea, should change the windows layout to match what it looks like on osx

**Comment by tooomm** [comment]
I don't get what this is about, no mac guy though.

OT: you can also drag and drop images from your pc into the github comment field to properly host+include them. Makes reviewing easier and files won't suddenly disappear for some reason.

**Comment by ancestral** [comment]
The Imgur link is broken, but it sounds like this issue has been more-or-less resolved. The original issue seems to suggest there were two Cockatrice menus at one time; I don’t see two of them. The other menus look fine. I would say maybe I would consider moving the View menu more towards the left, as View typically comes before many other menus.

The only thing I would say is, an Edit menu might be nice to have; this might be a trivial thing to add, as the Edit menu commands are there and active already.

**Comment by Daenyth** [comment]
I think this got fixed along the way
