### ISSUE TITLE
Tokens get wiped out. This prevents me from playing SOI

### ISSUE THREAD

**Issue by Gooseboxicus** [Cockatrice/Cockatrice#1924]
Everytime I launch a game my tokens.xml file gets wiped out and goes from a 226kb file to 1kb file. Tokens unfortunately are the only way to test with SOI.

Please help

<b>OS:</b>
*Override this line with the exact operating system you are running! (e.g. "Win 7 SP1", "OS X 10.8.5", "Ubuntu 15.10" ...)*

<b>Cockatrice version:</b>
*Put your Cockatrice version number & build date here! You find them inside the app: `Help` --> `About Cockatrice` (e.g. "2d53ce9 (2016-02-18)")*

___
<br>

*Explain your Issue/Request/Suggestion in detail here!*

**Comment by Daenyth** [comment]
Can you include the tokens.xml that gets removed?

Can you also include your OS and Cockatrice version as the template says?

> Tokens unfortunately are the only way to test with SOI.

That's confusing; what about custom sets? That seems to work for everyone else.

**Comment by tooomm** [comment]
>Tokens unfortunately are the only way to test with SOI.

SOI is already fetched by Oracle since 10+ days... what do you need a token.xml for?

**Comment by KarasuGamma** [comment]
I'm having a similar problem - the only token the deck editor recognizes is the 4/4 Angel. They were all working (mostly) normally a few days ago.

Additionally, even while they were working, I couldn't access any of the actual SOI tokens (Clues, Devils, and Emblems).

**Comment by tooomm** [comment]
@KarasuGamma Please try to install the newest version of Cockatrice from https://cockatrice.github.io and rerun Oracle afterwards. You should be fine then.

**Comment by KarasuGamma** [comment]
Everything seems to be working now.

**Comment by tooomm** [comment]
That's something for @Psithief

**Comment by Psithief** [comment]
@KarasuGamma I suppose you can have both.
