### ISSUE TITLE
info/warning in tokens and cards.xml

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#1927]
Add comments to cards.xml and tokens.xml that these files should **not** be edited. There could also be a short information or link to our wiki about how to use custom sets and tokens instead.
- [ ] `cards.xml`
- [x] `tokens.xml`
- [x] `spoiler.xml`

See https://github.com/Cockatrice/Cockatrice/issues/1858#issuecomment-196078594 by @ZeldaZach

**Comment by ZeldaZach** [comment]
I think we can just manually add this to the tokens file on that repo and I can write a quick script to insert it into the cards xml

**Comment by tooomm** [comment]
@ZeldaZach edited the tokens.xml so that we have some info in there now:
https://github.com/Cockatrice/Magic-Token/pull/12

I think we could improve the wording - feel free to discuss it here.
Input @Psithief ?

**Comment by Psithief** [comment]
Uh oh. I've now realised it isn't making much sense to have the `Edit tokens` functionality under `Card Database` _not_ point at a custom tokens file.

Until that window stops modifying `tokens.xml` there's not much point putting the warning in.

**Comment by Psithief** [comment]
Actually, testing that window now, it _kind of_ doesn't actually work.

Try adding a token. It doesn't appear in that list.

**Comment by tooomm** [comment]
Yep. There is definitely a problem and the `Edit tokens` dialog should stop displaying tokens.xml cards. It's not able to edit them anyway.

It should be able to properly display & modify `TK.xml` cards though...
