### ISSUE TITLE
Missing English option in language selection menu

### ISSUE THREAD

**Issue by JineteDV** [Cockatrice/Cockatrice#1928]
![screen shot 2016-04-10 at 3 47 59 pm](https://cloud.githubusercontent.com/assets/6514656/14412596/f55a2548-ff33-11e5-8b1d-15ecb4b525b4.jpg)
<b>OS:</b>
OSX 10.11.3

<b>Cockatrice version:</b>
8d67c75 4/8/16

___
<br>

Both of the blanks in the language list happen to be (regular) English.

**Comment by skwerlman** [comment]
i think this is already fixed in #1919, though it still needs to be merged
