### ISSUE TITLE
Card information popout off screen

### ISSUE THREAD

**Issue by JineteDV** [Cockatrice/Cockatrice#1929]
![screen shot 2016-04-10 at 4 00 55 pm](https://cloud.githubusercontent.com/assets/6514656/14412679/e42c3886-ff35-11e5-94cb-5b6897b5a3a0.jpg)
<b>OS:</b>
OSX 10.11.3

<b>Cockatrice version:</b>
8d67c75 (2016-04-08)

___
<br>
If the linked card is too low in the window then the pop out will be off screen.

**Comment by Fizztastic** [comment]
Possibly a Mac only issue?
![ss](https://cloud.githubusercontent.com/assets/11285250/14412929/5a15ed68-ff3a-11e5-9ea4-6cbb14a1dcd8.jpg)

**Comment by tooomm** [comment]
Nope, same for me on Win 8.1. I run into it earlier today, thanks for the report!

![card preview on click](https://cloud.githubusercontent.com/assets/9874850/14413489/217a6668-ff7c-11e5-8fd5-8a457a6d975e.png)

**Comment by Daenyth** [comment]
@Fizztastic and @tooomm What versions are you running there

**Comment by Fizztastic** [comment]
@Daenyth self compiled 8d67c75 with tweak to make the card in the infobox even bigger.
https://github.com/Cockatrice/Cockatrice/blob/master/cockatrice/src/cardinfowidget.cpp#L31-L35
`int pixmapHeight = desktopWidget.screenGeometry().height() / 1.6;
    int pixmapWidth = pixmapHeight / aspectRatio;
    pic->setFixedWidth(pixmapWidth);
    pic->setFixedHeight(pixmapHeight);
    setFixedWidth(pixmapWidth + 25);`
