### ISSUE TITLE
Card Display in Chat Cut Off

### ISSUE THREAD

**Issue by tritoch** [Cockatrice/Cockatrice#1932]
<b>OS:</b>
Win7

<b>Cockatrice version:</b>
b4d5721

___
<br>

Card info box gets cut off if link is near bottom of screen.  I think this is a regression from gatewatchers?

![cut off](http://i.imgur.com/gWUe7LB.png)

**Comment by ctrlaltca** [comment]
You are right; we already noticed this problem #1929 and the fix has just been included #1930. The next development version will be fine.

**Comment by tooomm** [comment]
Thanks for the report though! ;)
