### ISSUE TITLE
include QT_VERSION data in the about menu version

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#1934]
from gitter:

>**@Daenyth**
so it's like `<gitsha> (date Qt vXXYYZZ)`
it's also like a 5 minute code change
getting qt ver in bug reports would help us
since qt is buggy as hell especially on ubuntu
since ubuntu is always outdated

<br>
(adjust the issue template accordingly, too)

**Comment by Daenyth** [comment]
We removed Qt4
