### ISSUE TITLE
Leaving rooms upon exit

### ISSUE THREAD

**Issue by LethalPigeon7** [Cockatrice/Cockatrice#1938]
<b>OS:</b>Win 7 SP1
<b>Cockatrice version:</b> can't be loaded into clipboard

---

<br>
[SUGGESTION]
When someone closes cockatrice whilst in room he should exit those rooms, not have a black dot and stay in as disconnected. The simplest way of doing this seems to change the popup window of "leave? some games are open" options from "close cockatrice" // "don't close cockatrice" to "close cockatrice and leave all rooms" // don't close cockatrice".  
This way when someone ragequits, noone would have to wait for him not knowing he isn't an unfortunate soul with a poor connection, but rather left intentionally based on NaCl levels alone and simply isn't coming back. And even in a world of only reasonable players, it would mean that after a nice match the players would be spared a few needless clicks - leaving the room / kicking the black-dot player.  
And at the same time if someone's app actually crashed on its own he could still get back into the games perfectly fine. The only downside of this feature I can think of (aside from arguable irrelevance) is when someone wants to close the program, and then get back into the games he left. This has never happened to me, but I can imagine it theoretically happening, someone needs to move his laptop, restart his computer, etc, at which point he can just kill cockatrice via task manager. The popup with the "leave and close rooms" could mention this way out.

**Comment by tritoch** [comment]
Could it be a third (and default) option?  Close Cockatrice and exit all rooms // Close Cockatrice // Don't close Cockatrice

I've occasionally needed to leave a room with intent to come back (run card update, restart PC) and I'd rather not have to kill the process to avoid having my games close.

**Comment by LethalPigeon7** [comment]
Seems good. If anyone really wanted to be a pain he'd gladly go through task manager anyway.

**Comment by Daenyth** [comment]
I'm not sure how I feel with this. I don't want to add another toggle because it's another largely unimportant (to the user) choice, which degrades UX. At the same time, I don't want to make leaving games the default behavior, for the reasons @tritoch stated. Taking those two together arrives at leaving the behavior the same as it currently is, which is problematic as well.

I'm not sure the right path here. I'll think about it
