### ISSUE TITLE
socket error: host cannot be found

### ISSUE THREAD

**Issue by KhanMan2** [Cockatrice/Cockatrice#1940]
<b>OS: Windows 7 64bit</b>

<b>Cockatrice version:b4d5721 (2016-4-09)</b>

___
<br>

I am trying to register for the cockatrice.woogerworks.com server using either the 443 or 4747 port and every time I do i get the Socket error: Host cannot be found. I have tried using the 62.210.169.149 IP and i get timed out everytime i do that. I have flushed my DNS, I'm using the 8.8.8.8 and 8.8.4.4 dns servers. If there is anything else I can do to fix this issue I'd appreciate the help.

**Comment by ctrlaltca** [comment]
The current ip that i see for that server is 62.210.10.127, can you try it?
The nice part is that i'm using google's DNS 8.8.8.8, too.

**Comment by KhanMan2** [comment]
That did it thanks man

**Comment by ctrlaltca** [comment]
You are welcome. @woogerboy21 maybe it can be an useful info for you to know that some DNS is reporting a wrong address for your server?

**Comment by KhanMan2** [comment]
I'm not going to pretend to know what that means.

**Comment by ctrlaltca** [comment]
Nevermind, i was just informing the server administrator to have a look at this problem.

**Comment by KhanMan2** [comment]
OK, thanks again buddy.
