### ISSUE TITLE
"new sets found" dialog box bugged

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#1942]
<b>OS:</b>
Win 8.1

<b>Cockatrice version:</b>
768a1c5 (2016-04-12)

___
<br>

When you run Oracle and a new set is found (or more...) you see a dialog box telling you something like:
`"~1 new set has been found"` and it asks you to enable it --> `yes / no / ~view sets`

On every launch of Cockatrice the dialog pops up again and ask you what you want to do **unless** you hit `yes` or `no`. If you decide to `view sets` every time to review for yourself what the new set is or if you want to enable/disable it, the database gets correctly updated.... BUT you'll see the same dialog on the next start again.
Just if you decide to go for `yes` or `no`, it'll stop the loop of launching a pop up after several seconds after you started the app.

I thought about two improvements:
- treat a hit on `~view sets` in the dialog the same as a hit on `yes` or `no` and don't show the dialog again
- list all newly found sets (like the [required featues](https://github.com/Cockatrice/Cockatrice/pull/1439#issuecomment-136877493)) in a "detail" box maybe?

**Comment by ZeldaZach** [comment]
Confirmed glitch on OS X. I've noticed it too, but it's not that big of a deal. Should still be fixed.
