### ISSUE TITLE
Sounds Stop Working

### ISSUE THREAD

**Issue by someKindOfGenius** [Cockatrice/Cockatrice#1943]
<b>OS:</b>
Ubuntu 14.04

<b>Cockatrice version:</b>
Version 323fc06 (2016-02-02)

---

<br>

At times, the sounds simply stop playing for any actions at all. It starts off fine, but after a while they just stop. It isn't always the same length either, or game type, or anything I can think of.

**Comment by Daenyth** [comment]
If you run it from the console does it print anything?

**Comment by someKindOfGenius** [comment]
No, nothing mentioned in the terminal about the sound engine or anything, just loading card images. One thing that I'm not sure if it's relevant is it kept saying something about a buffer underflow, usually after a new phase was entered.

**Comment by ctrlaltca** [comment]
> it kept saying something
It would be nice to know the exact message

**Comment by someKindOfGenius** [comment]
> It would be nice to know the exact message
```
playing "end_step" 
Got a buffer underflow!
```

**Comment by ctrlaltca** [comment]
Did you build by yourself using qt4? If you did, it could be caused by a known qt bug: https://bugreports.qt.io/browse/QTMOBILITY-1948

**Comment by someKindOfGenius** [comment]
I didn't build it myself, I downloaded the 'Trusty' package from the Cockatrice website.

**Comment by Daenyth** [comment]
Is this still a problem with the latest version?

**Comment by someKindOfGenius** [comment]
Yes, this is still happening.

**Comment by ZeldaZach** [comment]
@someKindOfGenius If this is still an issue as of now, pleas reopen!
