### ISSUE TITLE
Suggestion: Ability to change color options in chat

### ISSUE THREAD

**Issue by TheMasterpass** [Cockatrice/Cockatrice#1945]
<b>OS:</b>
Windows 10

<b>Cockatrice version:</b>
Version 323fc06 (2016-02-02)

---

<br>

It might be beneficial to have a wider selection of colors to work with, both for the in-game chat as well as the join messages that are presented when using custom Servatrice servers.  Currently, the roomlist\x\joinmessage function can only output a dark green text that is visually difficult to read using some of the themes that are found on the wiki.

**Comment by ctrlaltca** [comment]
We should remove the hardcoded colors and add classes to meke it possible to style them using css from a theme.

**Comment by leematos** [comment]
@ctrlaltca this is near and dear to my heart as a theme designer, but looking at the chatview code, I'm not sure of the right way to add classes to these elements? https://github.com/Cockatrice/Cockatrice/blob/master/cockatrice/src/chatview.cpp#L173

Is it as simple as defaultFormat.setObjectName('ServerChatMessage') and then I'm set to grab it in a theme? if so, this is great! I can make that happen.

**Comment by Daenyth** [comment]
It should be pretty easy to just try; change the switch there to apply a style instead of hardcoding the aspects, then just grab that class in css and make it stand out

**Comment by ZeldaZach** [comment]
Dupe #3948
