### ISSUE TITLE
OSX - crash moving top cards of library

### ISSUE THREAD

**Issue by JineteDV** [Cockatrice/Cockatrice#1947]
<b>OS:</b>
OSX 10.11.4

<b>Cockatrice version:</b>
8d67c75 (2016-04-08)

---

<br>
https://gist.github.com/JineteDV/86e6c79697e739bb61ac3cbf868ca4f1
Crashed while trying to move a card in the top 3 cards of my library.

**Comment by JineteDV** [comment]
![screen shot 2016-04-14 at 9 35 27 pm](https://cloud.githubusercontent.com/assets/6514656/14549399/855b1a06-028d-11e6-895f-91336ae7a2d4.jpg)
Then after getting back in the game, most of the card images wouldn't load, it was only specifically in that game though.

**Comment by Daenyth** [comment]
```
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   org.qt-project.QtWidgets      	0x000000010706e1f5 QGraphicsItem::setCursor(QCursor const&) + 85
1   com.cockatrice.cockatrice     	0x0000000106163715 CardItem::mouseReleaseEvent(QGraphicsSceneMouseEvent*) + 341
```

ping @ctrlaltca, if you feel like looking at the code to see what's up. It might be an obvious issue. I'll try to check on it if I have time this week.

**Comment by ZeldaZach** [comment]
Is this still a problem?

**Comment by JineteDV** [comment]
Don't think so, can't remember the last time this happened.

**Comment by tooomm** [comment]
Let us know once it pops up again, hopefully it won't happen again. :)
