### ISSUE TITLE
Prevent user from joining a game if any user in the game is ignoring them.

### ISSUE THREAD

**Issue by Jinxstands4Jinx** [Cockatrice/Cockatrice#1950]
I just hosted an EDH game and had 2 people enter who apparently were on each other's ignore list. Neither realized this until midway into the game. They started Arguing and both expressed later that if they had noticed the other person's name sooner they could have avoided the room. I started thinking about this. Is there any way we can implement a "Players in room" Column in the main room? Maybe between "Players" and "Spectators".

**Comment by Daenyth** [comment]
Hmm, tricky problem. The server should probably just block them from joining saying "One of the players in this game is ignoring you"

**Comment by Jinxstands4Jinx** [comment]
I was thinking just since we can show "room creators" why not show occupants?

**Comment by Daenyth** [comment]
There's nothing preventing it but it's more work (server change, protocol change, ui change) vs just rejecting the join, which is a server-side only change (and maybe a tiny client change to update the message wording)

**Comment by Daenyth** [comment]
Also showing the list doesn't actually prevent the problem from happening. They would have to proactively check

**Comment by Jinxstands4Jinx** [comment]
True.

**Comment by Jinxstands4Jinx** [comment]
Still having the ability to check would be helpful.

**Comment by tritoch** [comment]
Preventing join is also problematic, namely for draft rooms.  If someone has a lot of ignores, people won't be able to join your room and you won't know why.  You're absorbing an ignore list(s) and you don't have any information about it.

**Comment by Jinxstands4Jinx** [comment]
That is a good point, hence i think we should just be able to check,  Also,  i do not mind running into people that have ignored me  or vis versa in a draft as sometimes that forces you to unignore them and they do end up redeeming themselves, or you redeem yourselve.

**Comment by ZeldaZach** [comment]
I don't think I'd want this implemented imo. Like said above, it can cause draft rooms to remain empty for "no apparent reason" and i'd rather just let them work out their problems on their own.

**Comment by tooomm** [comment]
>Hmm, tricky problem. The server should probably just block them from joining saying "One of the players in this game is ignoring you"

```
One of the players in this game is ignoring you.
Do you still want to join?

Yes/No
```

**Comment by ZeldaZach** [comment]
Tracking #2448
