### ISSUE TITLE
Request to give replay access to mods

### ISSUE THREAD

**Issue by isleep2late** [Cockatrice/Cockatrice#1953]
<b>OS:</b>
_Windows 10 Bootcamp_

<b>Cockatrice version:</b>
_3c58003 (2016-3-22)_

---

<br>

I spoke with @Daenyth and @tooomm about this. Recently a user reported cheating by a player who created a token of a spell to pass it off as a real spell. To verify this, I had to give the user my personal e-mail address so they could send me their replay file. I then had to figure out how to read the file and find the local directory on my computer, which was cumbersome but essential.

I was wondering if there would be a way in a future update for moderators to have access to the replay files stored on the server. I think this would save a lot of headache such as in the example above. Users also commonly report being kicked for no reason, which itself is also a difficult task without the evidence of a replay.

Any thoughts or ideas?

Thanks for reading!

**Comment by ZeldaZach** [comment]
I'm a fan of a way from the admin tab to enter a game number and it will then download the replay file for you

**Comment by Daenyth** [comment]
I'm actually a little uncertain of this. I have reservations about overstepping bounds. Perhaps this could be added but restricted to admin level. My reasoning is that many users use cockatrice for tournament practice, and it's entirely reasonable to think that they would want their brews kept private. Adding the ability to download replays with no restriction means that a rogue moderator could get information they shouldn't have access to. I've definitely seen a few PT-level players talk about testing on cockatrice.

The reasoning about keeping it at admin level is basically that the admin has access to it already via the file system, so it's not really any risk over what's already present.

**Comment by Daenyth** [comment]
Also it goes into what the role of a moderator should be; access to replays is only useful if banning players for cheating is part of the moderator's job. If they are there to help control troll population and users abusing the server, then the functionality is not needed. I know woods and I disagree on this front.

**Comment by ZeldaZach** [comment]
I'm a fan of giving replay access to mods as it's mostly irrelevant and if mods want to view replays and inspect for cheating. It's a minor thing, so I don't really see a reason to hold it back

**Comment by ctrlaltca** [comment]
Dup #146 . Keeping this one open since it contains a bit of discussion on the topic.

**Comment by D0nV170** [comment]
Just wanted to confirm and add to the discussion since the this one is close enough to the other but I would also like a way to view the in-game log without waiting until the game is over and the lobby is closed, even once it's easier to access a replay, with the current system, mods have to wait until the game is closed until we can get any replay.
