### ISSUE TITLE
0xc000007b error message

### ISSUE THREAD

**Issue by potatoZMaster** [Cockatrice/Cockatrice#1954]
Windows 7

d55e44e

I keep getting the error message: "The application was unable to start correctly (0xc000007b). Click ok to close the application." And then i press ok and the application closes. Is there any way to fix this?

**Comment by leematos** [comment]
Do you know if you are on 32 or 64 bit windows? I believe that's what this is about. Using the wrong version of cockatrice for your platform.

**Comment by potatoZMaster** [comment]
never mind me and my friend figured it out. thank you though!

**Comment by Nightfirecat** [comment]
If you wouldn't mind, could you post a short description of what you did, or what the problem was?

**Comment by tooomm** [comment]
If you provide some details about the problem and your solution we are more than happy to add it to our [troubleshooting section in the wiki](https://github.com/Cockatrice/Cockatrice/wiki/Troubleshooting). Would be nice if you help others solve this too!

**Comment by leematos** [comment]
I'm 99% sure this is the 64bit app on a 32bit OS problem: https://github.com/Cockatrice/Cockatrice/issues/1854

**Comment by tooomm** [comment]
added the error code to the wiki:
https://github.com/Cockatrice/Cockatrice/wiki/Troubleshooting#not-a-valid-win32-application-0xc000007b
