### ISSUE TITLE
Problem w/ tokens/trnasforming cards

### ISSUE THREAD

**Issue by Bigdogdch** [Cockatrice/Cockatrice#1956]
Simply put, when I used to "create token" it provided a listing of all the tokens that were I assume pre loaded by cockatrice.  Now there are no tokens listed.  Please help
Also, with Shadows over Innistrad and transforming cards, how do I transform cards?

Thanks

**Comment by leematos** [comment]
As for tokens your tokens issue, I'm not sure, but for the transform cards, if you right click on a card, you should see a "related cards" option and then you can choose the related card you'd like to flip:

![fqhmdrgwas](https://cloud.githubusercontent.com/assets/359140/14744922/d2173692-0876-11e6-8ddc-d51292f7f2f0.gif)

**Comment by Jinxstands4Jinx** [comment]
that example is nothing like it looks, not sure why. For the tokens you have to reload the token xml.

**Comment by leematos** [comment]
@Jinxstands4Jinx can you clarify? I'm thinking maybe you are on an older version or getting confused by my theme?

**Comment by Jinxstands4Jinx** [comment]
well the background is weird. wonder how you set that up. I also did not recall the flip option but yeah it is there. I just never used it.

**Comment by Jinxstands4Jinx** [comment]
Could you please tell me how you got the menu to pop like that with the blackened background, and the text? mine is the dull white.

**Comment by Daenyth** [comment]
Please keep this on topic, it's a bug report

**Comment by ctrlaltca** [comment]
@Bigdogdch you are probably running an old cockatrice version. Please, try to download the latest version from http://cockatrice.github.io/ , install it, run oracle and try again.

@Jinxstands4Jinx 

> well the background is weird. wonder how you set that up
> Could you please tell me how you got the menu to pop like that with the blackened background, and the text? mine is the dull white

Themes, have a look here:
https://github.com/Cockatrice/Cockatrice/wiki/Themes

> Also when I use abby I only get the flip side for related I do not get the cleric choice. That may be the updated version and if it is I wonder if they finally fixed the Custom cards issue. As I know the newer client cannot handle Custom tokens.

I don't get the question, if is there a question at all.

**Comment by ZeldaZach** [comment]
If there is an actual issue, please reopen and provide us more info
