### ISSUE TITLE
Request: record reason for departure and initiator of kickings in chatlog

### ISSUE THREAD

**Issue by aeschenkarnos** [Cockatrice/Cockatrice#1958]
Normally the creator of a room has kick privileges. If the creator leaves, the first player in the list gets the kick privileges. If the creator returns as a spectator, the creator gets kick privileges again.

This has the potential to create or exacerbate drama, if the creator kicks someone and the first player in the list is blamed.

The fix is easy - just have the chatlog say "XxXRudeGuyXxX left the game voluntarily" or "XxXRudeGuyXxX was kicked by XxXSomeJerkXxX" instead of ""XxXRudeGuyXxX left the game".

**Comment by Daenyth** [comment]
The message change is reasonable but probably requires a protocol change which means a required client update.

**Comment by ZeldaZach** [comment]
The client already says, when a user leaves, if they were kicked by gamehost or moderator...?
