### ISSUE TITLE
Request: Custom layout for Cardfight!! Vanguard

### ISSUE THREAD

**Issue by rishabhkalra** [Cockatrice/Cockatrice#1960]
I want to add support for Cardfight!! Vanguard but it uses a board layout that is difficult to replicate given the current layout of the board.  Maybe we can possibly add support for free-form layout? Or just have a custom layout for the game, not sure but it's a suggestion.  

The board board layout in CFV is all fixed.  Not sure exactly how to describe it but I'll leave a link for the layout.  ![Playmat Layout](http://vignette3.wikia.nocookie.net/cardfight/images/3/30/1026998.jpg/revision/latest?cb=20130825060958)

That shows all the zones, the only "special" one that has a special case is the red one in the middle, the vanguard circle, certain decks have a mechanic called legion where you can have 2 cards next to each other in the middle.  Other than that all other circles only have one card.

**Comment by Daenyth** [comment]
Is that 6 spaces or 7? What's the green section?

You might be able to do this already by putting things in the lands row and others in the middle row

**Comment by rishabhkalra** [comment]
The green space is also a zone, it's the guard zone, so when you want to block an attack you would put a card there to signify a blocking action, so it's 7 spaces I guess

**Comment by Daenyth** [comment]
Images of the layout mid-game with cards would be helpful here

**Comment by rishabhkalra** [comment]
This is the only image I could find but I think it'll do ![in-game layout](https://s-media-cache-ak0.pinimg.com/564x/c0/a0/00/c0a000f31e908c2a2154d8fee568548a.jpg)

**Comment by Jinxstands4Jinx** [comment]
If we do this Why not do other games like Ascension.

**Comment by skwerlman** [comment]
I see two ways of solving this:
 * server-side layout system
 * cockatrice providing support for every game

There are issues with each fix.

A server-side custom layout system would be nice, but hard to implement and theme, and it'd probably require a protocol change whenever it needs a new feature.

Cockatrice providing support for all games is impractical for obvious reasons.

**Comment by Daenyth** [comment]
@Jinxstands4Jinx I want to support Ascension. It's difficult because we currently have no ability for a shared-ownership deck.

**Comment by Jinxstands4Jinx** [comment]
Well Why would it be a shared ownership?  I played ascension when it first started and have lost touch with it now but this is what I am thinking. Bear with me this may be rough.

Ok this is my Table on cocka with nothing on it. 
https://cloud.githubusercontent.com/assets/18018938/15902468/0c7d7fa2-2d76-11e6-803a-8f8efc00caca.png

Now The set up for ascension is as follows.

You need 1 spot for mystics, 1 for heavy, 1 for the Cultist, 1 for the Void, 1 for the Pool deck.  6 community piles and then you need 1 deck for Each player. 

The easiest Way I can see doing this is to have the Host of the table make a separate game like they would for Planeshift. They control 1 deck and they lay out the 6 community piles like so.

The host would supply the community deck. Then they make a token on the game for the Cultist, Heavy and the mystics. Each player who Wants to play would bring their own deck of the Basic cards the 2 militias and the 8 apprentices.  As players Buy cards they are put into exile (void) by the host and then the players can Make tokens or the host can have The entire deck in his Sideboard and he can just View his board and slide cards out as needed to hand to players. The main table set up though would look like this.

https://cloud.githubusercontent.com/assets/18018938/15902893/35c94e98-2d78-11e6-8b0a-81d638269538.png

They could use the Life meter as the total Honor in the game to be determined by the host. If I left anything out Let me know.

**Comment by Jinxstands4Jinx** [comment]
If someone would show me how to write up a Custom set I would be willing to make a Ascension Decklist.

**Comment by rishabhkalra** [comment]
Custom set is really easy to make, make an XML file called whatever and put it into the custom sets folder, populate it with all the card data using the predefined syntax of MTG cards, if you look at the docs it shows you what XML tags mean what in context of MTG, for ascension just decide what tags you're going to use for what and that's pretty much it

**Comment by Jinxstands4Jinx** [comment]
Rishabhkarla. I have never done an Xml file before and Right now I am Gathering all the images of Every Ascension card so I can have them ready for people to download. Can I have your Cocka name so we can discuss on cocka how to set that up?

**Comment by rishabhkalra** [comment]
Its iWyze on cockatrice, or at least it should be, I'll confirm when I get home from work

**Comment by rishabhkalra** [comment]
Also if the images of the cards are available online, I'd recommend just not bothering with the download because in the XML file you're going to have to specify a card URL, or at least that's the way I've done it before, not sure if there's a different way to do it but I'd say that's probably the easist

**Comment by Jinxstands4Jinx** [comment]
Well i need the images so that Other people who want to play will be able
to see card pics. So they would have to put the "Folder" into their Custom
folder and then all the cards images would work.

**Comment by rishabhkalra** [comment]
If they're available online, you just have to specify a link and it works just fine

**Comment by rishabhkalra** [comment]
I've already done this for 2000+ vanguard cards so trust me, it works lol

**Comment by Daenyth** [comment]
I'd appreciate if we can keep the ticket on-topic. If you two don't mind I'd like to remove those comments so the main meat of the discussion here is easier to follow.

**Comment by rishabhkalra** [comment]
Sure, sorry about that Daenyth

**Comment by Daenyth** [comment]
@Jinxstands4Jinx What you describe about having the host make a second game for the shared deck - yes that's how it can be done today. But that's a very inconvenient workaround. I'm talking about making shared decks a feature that the game engine supports natively (when a game's rules support such things).

**Comment by Jinxstands4Jinx** [comment]
hmm, Well Let me finish gathering all these pictures and ill make a
Downloadable file that gives people a Ascension XML and images of All the
cards so that they can just add the "Ascension Set" to their card pool and
let them go from there.

**Comment by Jinxstands4Jinx** [comment]
Sorry Daenyth, That is why i asked for his cocka name.

**Comment by tooomm** [comment]
I couldn't catch you on the server @rishabhkalra.

We introduced a category in the wiki for other games besides Magic, do you mind putting your
`Cardfight!! Vanguard` work up there for everybody to use? At best with some link to a reddit post etc.
https://github.com/Cockatrice/Cockatrice/wiki/Custom-Cards-&-Sets#custom-card-databases-by-the-community

**Comment by ZeldaZach** [comment]
Dupe #1740
