### ISSUE TITLE
app window misplaced on launch (win 10)

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#1961]
<b>OS:</b>
Win 10

<b>Cockatrice version:</b>
c213b67 (2016-04-25)

---

<br>

On every launch of Cockatrice the app window is wrongly placed. I didn't experience this on Win 8.1!

For example at the right part of the screen and cut off a bit on the top and half on the right:
![win10start](https://cloud.githubusercontent.com/assets/9874850/14826652/277c1312-0bdf-11e6-8e2b-d9c6061639f9.png)

This just happens if the app was in full screen when you close it. Position is randomized a bit too on start. It's not always the same as in the picture.

(might be connected to #1871, or at least a 2-for-1 fix :laughing:)

**Comment by tooomm** [comment]
Debug Error log print right after start:
<pre>
QWindowsWindow::setGeometry: Unable to set geometry 1920x1018+869+20 on QWidgetWindow/'MainWindowClassWindow'. Resulting geometry:  1916x1018+869+20 (frame: 8, 31, 8, 8, custom margin: 0, 0, 0, 0, minimum size: 861x1018, maximum size: 16777215x16777215).
</pre>

**Comment by ZeldaZach** [comment]
There's a resizing issue on mac too depending on what you do. It sometimes goes below the Dock randomly and if you move the window it resizes correctly.

**Comment by tooomm** [comment]
Try to catch the error msg. Maybe the causing issue is the same.

**Comment by tooomm** [comment]
>There's a resizing issue on mac too depending on what you do. It sometimes goes below the Dock randomly and if you move the window it resizes correctly.

@ZeldaZach Is this still the case on mac with the newest changes @Vafthrudnir introduced?

My issues on windows seem to be fixed. 👍
