### ISSUE TITLE
“Gatewaterchers” typo

### ISSUE THREAD

**Issue by vitorgalvao** [Cockatrice/Cockatrice#1964]
<b>OS:</b>
OS X (specific version irrelevant)

<b>Cockatrice version:</b>
2016-02-03 Gatewatchers

___

On the releases page, you have a `zip` that contains a `dmg`, for the OS X version (`Cockatrice-Gatewatchers-osx.dmg.zip`). The `dmg` is wrongly named, though, and has `Gatewaterchers` instead of `Gatewatchers` in the name.

Irrelevant in most cases, but relevant when trying to automate the installation (which is what [homebrew-cask](https://github.com/caskroom/homebrew-cask) is for, and [how I found the issue](https://github.com/caskroom/homebrew-cask/commit/ea415766d754addfec7349aaf383f299046c8481)).

**Comment by tooomm** [comment]
Can you provide a link, please? Just to be sure...

**Comment by ctrlaltca** [comment]
@vitorgalvao thank you, i've updated the release with a new, corrected package: https://github.com/Cockatrice/Cockatrice/releases/download/2016-02-03-Release/Cockatrice-Gatewatchers-osx.dmg
The old zip is still there just in case someone hotlinked it.

**Comment by vitorgalvao** [comment]
Thank you @ctrlaltca. Confirmed as working correctly.
