### ISSUE TITLE
Warning Users needs better feature set

### ISSUE THREAD

**Issue by samgc3** [Cockatrice/Cockatrice#1965]
Warns should have a text field where mods can explain the warn for other mods to reference. It should also be able to be updated or added to after issuance. Warns should also be able to be lifted by the issuing mod (though being able to make a text update would likely suffice.)

**Comment by woogerboy21** [comment]
So one of the original idea's for warnings was that there is a unified set of warnings used by the moderation staff. This list is defined by the owner/operator and any understanding of such warnings should be communicated by the owner/operator to the moderation staff.  This limits the possibility for confusion between moderators and the users being warned.  I for one want to avoid a situation were a user is being warned by moderator A for something and moderator B warns them with the same thing (possibly at different times) with a different understanding or pretense as to what the warning means. 

Now does that mean there isn't room for improvement?  No, we definitely want to be able to remove things like warnings if the user is improperly warned (as well as banned) which there is currently no real method in client to do so.  But can you give an example of were having some type of note or reference would be beneficial between moderators if a user is continuously being warned for a common understanding of a violation?  Take for instance one of the more extreme conditions harassment.  If a user is being warned for harassment and not banned, the user isn't causing to much of a problem but enough.  I'm not sure knowing details about the users historical warning for harassment matters much when at a later time the user is making harassing behavior.  In fact if anything having details about the situation may lead to a more prejudice approach towards the user.  To me, if I log in and see a user doing something like harassment and I look at his historic warnings and they have 10 previous warnings for the behavior I'm not really concerned about the specifics of the historic harassing behavior, nor do I really care. At that point there should be a more stern disciplinary action taken.  Which in our case is banning and you can type in the information you mention.

**Comment by Daenyth** [comment]
Closing since the main ask here is in opposition to the way the warning system is intended to work (namely that available warnings are consistent and translatable instead of ad-hoc)
