### ISSUE TITLE
Add shortcut to set life

### ISSUE THREAD

**Issue by Graffity2199** [Cockatrice/Cockatrice#1966]
After playing a while with Cockatrice, I would like a shortcut menu to set players' life, just by clicking right over the life panel, instead of going into the "Game > Player > Counters > Life > +X".

It would be really nice to have the same menu just with a right click, it would save time ;-)
I've added a screenshot to illustrate my request.

![set life shortcut](https://cloud.githubusercontent.com/assets/17712224/14936193/448c741c-0ee9-11e6-8804-542d95adc2f7.jpg)

Thanks a lot for your work.

**Comment by tooomm** [comment]
Did you tried <kbd>middle mouse click</kbd> on your life total? ;)

**Comment by Nightfirecat** [comment]
Also, have you tried using <kbd>Ctrl</kbd> + <kbd>L</kbd>?

**Comment by skwerlman** [comment]
Those both work, but a menu option would still be nice

**Comment by Graffity2199** [comment]
The `middle mouse` click doesn't work (Cockatrice Version 535e19f (2016-03-18) on Ubuntu 14.04 32 bits)
`Ctrl` + `L` works, and will help me before having a menu ;-)
Thanks a lot
