### ISSUE TITLE
Unauthenticated proxy causes card art to not load until application restart.

### ISSUE THREAD

**Issue by Dippyskoodlez** [Cockatrice/Cockatrice#1975]
<b>OS:</b>
Mac OS X 10.11.4 (15E65)

<b>Cockatrice version:</b>
e3fb308

---

<br>

If the device you open Cockatrice on is not authenticated to the proxy for network access (I have to pull up a page, click okay and then have internet) or simply does not have access at the time of opening, any cards that were attempted to be loaded art will not reload once internet connectivity is restored.

Reproduction:
Load Cockatrice with empty cache.
Disconnect from internet.
Attempt to pull up card.
Connect to internet.
New cards will retrieve image, but old card will not until application is restarted.

**Comment by ctrlaltca** [comment]
I think you have a point here: currently when cockatrice fails to download a picture from an url, it marks that url as "not to be used anymore". It doesn't make any difference is the download failed for a 404 or because connectivity is not present. We could improve that.

**Comment by Daenyth** [comment]
That probably also means that transient failures like DNS going down or network timeouts will also cause a card to not be loaded in that session again.

**Comment by ZeldaZach** [comment]
If this is still an issue, please let us know. I believe we've fixed how we load URLs in this regard
