### ISSUE TITLE
Players should not be able to ignore moderators

### ISSUE THREAD

**Issue by samgc3** [Cockatrice/Cockatrice#1976]
On a couple occasions when I message a player to address rude behavior they ignore me then sometimes flame me. They shouldn't be able to ignore moderators.

**Comment by Daenyth** [comment]
A player ignoring a mod is perfectly acceptable 99% of the time - it's only an issue if the user is abusive. In that case, it's appropriate to remove the user. Given that most users are not abusive, it's unreasonable to add a restriction affecting them just for this case.
