### ISSUE TITLE
auto-updater - determine if the os is win32 or win64

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#1977]
The auto-updater should determine if the os is win32 or win64 to download correct file from bintray and doesn't force users on old 32bit windows to download (and break!) their Cockatrice installations with 64bit binaries.
The important information here really is the OS, not which version of Cockatrice is installed/running.

Interesting reading:
https://msdn.microsoft.com/en-us/library/windows/desktop/ms724340.aspx
https://msdn.microsoft.com/en-us/library/windows/desktop/ms684139%28v=vs.85%29.aspx
Source: http://stackoverflow.com/questions/10529772/qt-get-system-32bit-or-64-bit-info

**Comment by Daenyth** [comment]
I think it's simplest if the 32bit client gets 32, etc. We will know they
can run it from that

**Comment by ctrlaltca** [comment]
> I think it's simplest if the 32bit client gets 32, etc. We will know they
> can run it from that

Agreed. Automatically updating 32-bit users to 64-bit could lead to missing vcredist.
Actually there's no good reason to choose the 64bit over the 32bit anyway.

**Comment by ZeldaZach** [comment]
@ctrlaltca What does the 64-bit version provide (feature wise) that the 32-bit doesn't? If nothing, then I think we can just pull the 64 bit down and work with what we have

**Comment by tooomm** [comment]
feature wise it should be the same, it might not be requirements, dependencies & performance wise

interesting idea though...

**Comment by ctrlaltca** [comment]
> What does the 64-bit version provide (feature wise) that the 32-bit doesn't?

Nothing. The only good reason to use the 64bit version is that if your OS is 64 and all of your software is 64bit, you don't need to install the 32bit vcredist just for using Cockatrice.

**Comment by tooomm** [comment]
I assume you did close this **un**intentionally @ctrlaltca ?
Otherwise explain yourself please. :)

**Comment by tooomm** [comment]
Thanks!
I think this is kinda important since we have different updater versions already floating around and none of them offers a real rock-solid solution for everybody!
<br>

>>What does the 64-bit version provide (feature wise) that the 32-bit doesn't?

>Nothing. The only good reason to use the 64bit version is that if your OS is 64 and all of your software is 64bit, you don't need to install the 32bit vcredist just for using Cockatrice.

I just tried 32bit Cockatrice on a 64bit win 10. I'm pretty sure I never installed 32bit `vcredist` and it worked flawlessly. Maybe the windows updater brought it to me at one point?

Can somebody confirm and retest my observation?

So is dropping the 64bit windows build for now something we should really consider?
There seems to be no change in the environment anytime soon that would require to have it?

This would help with the updater a bit. But it's not required.
Anyway we need to rethink and rework how the updater queries bintray and make sure there is a consistency (and ruleset) for the filenames we host on bintray.
Weird workarounds with .zip files and changing appendices don't provide the careless solution we want to bring to the user for updating their clients!
https://github.com/Cockatrice/Cockatrice/pull/1974 is just a small (and temporary) "fix" to make it work again, no real solution.

**Comment by ctrlaltca** [comment]
> I'm pretty sure I never installed 32bit vcredist and it worked flawlessly.
Any other software that you installed could have silenty installed the vcredist. 

> Maybe the windows updater brought it to me at one point?
That's possible. You should be able to check it from the "installed updates" section in the controls panel (that i'm sure had been renamed to something else in windows 10, to ensure nobody is able to find it anymore).

> Can somebody confirm and retest my observation?
I currently have no access to any windows 10 pc, i'll see if i can get one.

> So is dropping the 64bit windows build for now something we should really consider?
There is no reason in this. Probably keeping 64bit building but offering to users only 32-bits download is a better idea.

> Anyway we need to rethink and rework how the updater queries bintray and make sure there is a consistency (and ruleset) for the filenames we host on bintray.
I saw there's been a change just before the new release to fix something (#1974), but i had no chance to have a look at it and investigate further.

**Comment by tooomm** [comment]
Summing things up after talking with @Daenyth :
We want to check what the user is running at the moment and download the same version.
(e.g. 32 bit gets 32bit, and 64 bit sticks to 64bit binaries)
