### ISSUE TITLE
[Solved] Cockatrice won't load gtk theme

### ISSUE THREAD

**Issue by pjimenez1080** [Cockatrice/Cockatrice#1978]
<b>OS:</b>
Debian GNU/Linux

<b>Cockatrice version:</b>
e3fb308 (2016-05-08)

___
<br>
I've had this issue on every Debian system I've installed Cockatrice into. I recently tried it on Debian (8.4, 64 bits) running LXDE desktop enviroment and Openbox, I've tried it with every theme I had and Cockatrice can't load any. However, I wanted to test if that worked on lastest version of Lubuntu (16.04, 64 bits), also running LXDE desktop enviroment and Openbox, and for some reason Cockatrice does load every gtk theme here. I can't figure out why this is happening.

It's not an issue with gtk versions, either 2.0 or 3.0, because in Lubuntu, Cockatrice could load gtk themes of both versions.

Here I upload two screeshots, first one is from Lubuntu loading Clearlooks gtk theme and second one is from Debian not loading any gtk, but instead loading the default grey and ugly theme.
![lubuntu_cocka](https://cloud.githubusercontent.com/assets/2736100/15130380/4116841a-1648-11e6-8063-20b1256df906.png)
![debian_cocka](https://cloud.githubusercontent.com/assets/2736100/15130383/46dc03c0-1648-11e6-943c-2c1f09a37b17.png)

**Comment by Daenyth** [comment]
Cockatrice is written in qt, not gtk, so that might be why

**Comment by pjimenez1080** [comment]
Well, but in Lubuntu Cockatrice does load gtk themes. Also, applications like Skype which are written in qt do load gtk theme on Debian.

**Comment by pjimenez1080** [comment]
Ok, I just found the solution to this issue here
https://wiki.archlinux.org/index.php/Uniform_look_for_Qt_and_GTK_applications

I just needed to edit ~/.config/Trolltech.conf and add this
`[Qt]
style=GTK+`
 
It worked for me, Cockatrice can now load gtk theme on Debian.

**Comment by ZeldaZach** [comment]
Great! Feel free to add that to the wiki :)
