### ISSUE TITLE
Cannot compile or use the 14.04 binaries

### ISSUE THREAD

**Issue by ambivalentduck** [Cockatrice/Cockatrice#1980]
<b>OS:</b>
Ubuntu 16.04

<b>Cockatrice version:</b>
Sun May 8th commit by Zach, pulled from git
___
<br>

Cannot compile Cockatrice or use the provided binary on Ubuntu 16.04, Xenial.

Compilation fails as cmake does not appear to detect that Qt5Widgets is propertly present. If the cmake file is quickly edited to ignore that failure to find, the proper include and linker paths are not present. Qt4 detection fails as qmake will report its version as 5.5.1. This qualifies as an error in Ubuntu itself, but it's still annoying.

Provided binary fails since libQtMultimediaKit.so.1 is not found. Yes, my Qt5 is completely and properly installed. Other Qt5 dependent programs (such as TexMaker) work without issues.

**Comment by Daenyth** [comment]
You won't be able to use the 14.04 binaries on a 16.04 system because they're dynamically linked.

Can you paste the output from your `cmake` run with no source modifications? Finding qt5 is probably a matter of providing the right `-DCMAKE_PREFIX_PATH`

**Comment by ambivalentduck** [comment]
It's not especially useful: 

-- Performing Test CXX_HAS_WARNING_-Wno-error=extra
-- Performing Test CXX_HAS_WARNING_-Wno-error=extra - Success
-- Performing Test CXX_HAS_WARNING_-Wno-error=delete-non-virtual-dtor
-- Performing Test CXX_HAS_WARNING_-Wno-error=delete-non-virtual-dtor - Success
-- Performing Test CXX_HAS_WARNING_-Wno-error=sign-compare
-- Performing Test CXX_HAS_WARNING_-Wno-error=sign-compare - Success
-- Performing Test CXX_HAS_WARNING_-Wno-error=missing-declarations
-- Performing Test CXX_HAS_WARNING_-Wno-error=missing-declarations - Success
-- UPDATE TRANSLATIONS: OFF
CMake Error at /usr/share/cmake-3.5/Modules/FindQt4.cmake:1326 (message):
  Found unsuitable Qt version "5.5.1" from /usr/bin/qmake, this code requires
  Qt 4.x
Call Stack (most recent call first):
  CMakeLists.txt:144 (FIND_PACKAGE)


-- Configuring incomplete, errors occurred!

**Comment by Daenyth** [comment]
> Found unsuitable Qt version "5.5.1" from /usr/bin/qmake, this code requires
Qt 4.x

Add  `-DWITH_QT4=0` to your `cmake` call.

**Comment by ambivalentduck** [comment]
Fixed!

**Comment by Daenyth** [comment]
Awesome!
