### ISSUE TITLE
Revealed Top Card of Library, Hideaway, Face Down

### ISSUE THREAD

**Issue by dev-id** [Cockatrice/Cockatrice#1983]
<b>Cockatrice version:</b>
e3fb308

---

<br>

Setup: Top card of library revealed, using hideaway, look at top 4 cards, shift+drag one of them on to battlefield, attach to hideaway land. For purposes of the below example, Archetype of Endurance = Hiddenaway card.  Forest = top card of library.

What controller of hideaway land sees:
tritoch puts Archetype of Endurance into play from library.
tritoch attaches Archetype of Endurance to tritoch's Spinerock Knoll.
tritoch stops looking at his library.
tritoch unattaches Archetype of Endurance.

What opponent sees:
tritoch puts Forest into play from their library.
tritoch attaches Forest to tritoch's Spinerock Knoll.
tritoch stops looking at their library.
tritoch unattaches Forest.

**Comment by Daenyth** [comment]
Thanks.

**Comment by ZeldaZach** [comment]
This is a real problem with how we handle revealed text. Kinda related to #2048

**Comment by ebbit1q** [comment]
this is still an issue

**Comment by ebbit1q** [comment]
actually, the setup is a little different now, just reveal top card, stop reveal, shuffle, place top card on field face down, if you then flip it it will retain the false information, only when you move the card between zones will it correct
