### ISSUE TITLE
Card images not falling back correctly

### ISSUE THREAD

**Issue by skwerlman** [Cockatrice/Cockatrice#1984]
<b>OS:</b>
Windows 10, OSX 10.10

<b>Cockatrice version:</b>
e3fb308 (Shadows)

---

<br>

Now that `!setnumber!` is available, I updated my download url to `http://magiccards.info/scans/en/!setcode_lower!/!setnumber!.jpg`

However, it appears magiccards.info does not use the standard set code for several sets (i.e. `7e` for `7ED`). Because of this, some cards can't be grabbed from there. The issue, however, is that Cockatrice is seemingly not falling back to the secondary download url; and is instead displaying nothing at all:
![image](https://cloud.githubusercontent.com/assets/6954107/15234046/8ac54058-187b-11e6-9a7a-62914012d940.png)

My secondary URL is set to the default primary url: `http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!cardid!&type=card`

When loading the card that cockatrice is trying to get (with the incorrect first url) I do get a 404 error, so I'm not sure why it isn't trying the second.

The primary url (404): http://magiccards.info/scans/en/7ed/172.jpg
The secondary url (200): http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=25678&type=card

**Comment by Daenyth** [comment]
Sounds like it should be an easy fix

**Comment by ctrlaltca** [comment]
The default url is used when the card has a muid (that identifies the specific card, in the specific set, in the specific language and variation).
The fallback url is used when the card has no muid, so it can only be referred by name and set name.
I see this is not explained well in the UI, so you ended up setting:
 * a default url non sing muid, that won't work for cards in specific sets;
 * a fallback url using muid, that will only be used when the muid is invalid :)

**Comment by Daenyth** [comment]
We should probably just make the url patterns an ordered sequence. If the first one fails permanently then use the next one

**Comment by tooomm** [comment]
I run into the same problem (see #2192 for debug log).

<br>
My conclusion is:
>The fallback url is used when the card has no muid. I see this is not explained well in the UI

Jep, bad interface right now.

>We should probably just make the url patterns an ordered sequence. If the first one fails permanently then use the next one

There could still be a hidden 3rd one that just checks for name (same as fallback right now) in case people mess around and break both.

**Comment by tooomm** [comment]
Having no fallback working is especially bad when new sets are freshly out and pics not yet on certain sites available...
>Trying to load picture (set:  "AER"  card:  "Aegis Automaton" )
Picture NOT found, trying to download (set:  "AER"  card:  "Aegis Automaton" )
starting picture download: "Aegis Automaton" Url: QUrl("http://magiccards.info/scans/en/aer/141.jpg")
Download failed: "Error transferring http://magiccards.info/scans/en/aer/141.jpg - server replied: Not Found"
Picture NOT found, download failed, no more sets to try: BAILING OUT (oldset:  "AER"  card:  "Aegis Automaton" )

**Comment by Daenyth** [comment]
#2479
