### ISSUE TITLE
Art for custom cards and custom art not showing

### ISSUE THREAD

**Issue by thorks23** [Cockatrice/Cockatrice#1986]
<b>OS:</b>
Win 10

<b>Cockatrice version:</b>
version 2e3966a
___
<br>

I have added the art in all the correct places and I believe I have done everything right and yet the art still doesn't show. Please help

**Comment by ctrlaltca** [comment]
1. Close trice
2. Read carefully and follow: https://github.com/Cockatrice/Cockatrice/wiki/Custom-Cards-&-Sets#to-add-custom-art-for-cards-the-easiest-way-is-to-use-the-custom-folder
3. Start trice

If it still doesn't work, please start adding some more informations, like the full path where you're trying to put images (eg: c:\Users\whetever\AppData\Local\Cockatrice\Cockatrice\pics\CUSTOM\SET\) and the name of the image you are using (eg: Meow.jpg).

**Comment by thorks23** [comment]
ok thanks. Apperently if you don't go through that whole path it doesn't work. I had the folder for cockatrice on my desktop and I just noticed when I put them in that one it didn't show up in the one that was there when I followed that path. Thanks you've helped a lot :)
