### ISSUE TITLE
bad name choice for !setnumber!

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#1992]
see: https://github.com/Cockatrice/Cockatrice/pull/1921#issuecomment-220785141

>I don't like the naming at all... it's very confusing!
Why don't we use cardnumber?
All placeholders with "set" are related to actual sets... this isn't. It's not a number of a set, it's a number of a card in a set.

**Comment by ctrlaltca** [comment]
I agree the current name could be improved. The correct wording would be something like "alphanumeric code identifying the specific card inside the set it has been published", but we'd better keep the name short so "cardnumber" is a good candidate.
I'd keep the old name working, too to avoid breaking people using it.

**Comment by Daenyth** [comment]
I agree with @ctrlaltca on all counts.

**Comment by ZeldaZach** [comment]
I agree with what @ctrlaltca is stating, but why have two tags that do the same thing? As i mentioned in my other comment on the other thread... I don't see a reason to change it as the wiki clearly documents how to use it

**Comment by Daenyth** [comment]
We key the old one because we're trying not to jerk people around who have
already made settings with the old tag.

Maybe we could make an automatic migration for the settings? Call replace
in the setting handler

**Comment by Psithief** [comment]
I'm pretty sure it's collector number.

**Comment by tooomm** [comment]
Since this change is not in the newest official release (https://github.com/Cockatrice/Cockatrice/releases/tag/2016-06-30-Release), nor is a version containing this linked on our site, it's definitely worth changing before the next release. Just very few people have a client with this feature and way less should be using it.

Therefor the transition could be a bit more abrupt as well?
Otherwise I like to see a solution like we handle the "Picture cach size". On start we check once if it's set to 2048, if not we change it accordingly. If people lower it later, it stays.
In this case, we would check for `cardnumber` and change it to `collectornumber` once.
(btw: Why don't we use CamelCase here as well for better readability? :) )
