### ISSUE TITLE
Reverse Side of Dual Face Card (DFC) name to xml

### ISSUE THREAD

**Issue by dev-id** [Cockatrice/Cockatrice#1993]
Currently, unless a card is on the battlefield/stack, there's no way to know what the name of the back side of the card is.  Add the name of the back/front of DFC to cards.xml. (eg Huntmaster says somewhere in the card Description in deck editor/chat/hand "Ravager of the Fells" and ravager says in the description "Huntmaster of the Fells"

**Comment by ctrlaltca** [comment]
We already have that info in cards.xml, we just need to expose the related cards somewhere in the UI

**Comment by Daenyth** [comment]
Until we present the information better, for now you can use the "Create related card" context menu action as an indication of the name of the back side.

**Comment by ctrlaltca** [comment]
Related: #2013

**Comment by tooomm** [comment]
Maybe we should have a `Show related card` option next to `Create related card` and make it popup a window with the image (and maybe plus oracle text etc. similar to the "Card info" Widget)

**Comment by tooomm** [comment]
>We already have that info in cards.xml, we just need to expose the related cards somewhere in the UI

Do we also have info about meld cards in the `cards.xml` @ctrlaltca ?

**Comment by tooomm** [comment]
>We already have that info in cards.xml, we just need to expose the related cards somewhere in the UI

Looking at https://github.com/Cockatrice/Cockatrice/pull/1232 this should not be too difficult.

But how can we filter DFC's from Tokens or other related cards?
