### ISSUE TITLE
"unable to start correctly (0xc0000022)" error on Windows

### ISSUE THREAD

**Issue by willskate15** [Cockatrice/Cockatrice#1996]
<b>OS:</b>
Windows 10

<b>Cockatrice version:</b>
Cannot open cockatrice program, I am using the download from this link: https://cockatrice.github.io/
---

<br>

Whenever I try to run the program I get a popup that says "The application was unable to start correctly (0xc0000022). Click okay to close the application." This has happened to me many times before and I had an old Qt4 build that worked for awhile but not anymore. I can get cockatrice to open once after I uninstall and reinstall, but oracle will not open and I get this error and as soon as I close cockatrice, it won't open again. Any help?

**Comment by Daenyth** [comment]
Are you running some antivirus? Some of them flag oracle because it contains code for interacting with zip files, and some viruses do that as well (stupid...)

**Comment by Daenyth** [comment]
I'm finding references to "CA Internet Suite" causing this specific error for some people (in other programs)

**Comment by willskate15** [comment]
I had malwarebytes as my only antivirus software and I uninstalled it, but I'm still getting the same popup every time I try to run cockatrice and oracle. Whenever I uninstall and reinstall cockatrice it will open up after re-installation and work for me, but if I close it and try to open it anywhere else I get that popup. I can still run it now I guess, it just kinda sucks that I have to uninstall and reinstall every time I want to play lol.

**Comment by Daenyth** [comment]
It almost sounds like something is corrupting the app every time you try to
use it. I've never heard of this problem before. I'll keep looking into it

**Comment by willskate15** [comment]
Thank you please get back to me soon.

**Comment by ZeldaZach** [comment]
@willskate15 Is this still an issue for you?

**Comment by ctrlaltca** [comment]
Closing.
