### ISSUE TITLE
Significant lag while dealing with full card list.

### ISSUE THREAD

**Issue by blythe703** [Cockatrice/Cockatrice#2004]
<b>OS: Linux Mint 17.1 Cinnamon 64-bit</b>

<b>0baccd3 (2016-06-04):</b>

___
<br>

Any time I search starting with no filters or searches, or remove text from the search bar in the deck editor, Cockatrice locks up. The lag is most noticeable after clearing the card search bar, Cockatrice locks up for ~5 seconds. Cockatrice seems to jump to 100% CPU core usage during this lag. Before this update there was next to zero lag while using the card name search bar.

**Comment by Daenyth** [comment]
How much ram do you have? SSD or spinning disk drive? How many cores does your cpu have?

**Comment by Daenyth** [comment]
Also if you know the specific version you used before, that's potentially helpful. The commit you mention is from today, not the latest published release, so I'm guessing you self-compiled rather than using the deb, so I'm not sure what you might have had before.

Can you post the full output from cmake as well?

**Comment by Daenyth** [comment]
Maybe related to #1981 or #1900 or #1859

**Comment by blythe703** [comment]
Apologizes, I was away and I am a bit of a scub, so I will do my best to get what info I can.
I have 6gigs of ram, the images and Cockatrice files are on an SSD, and my computer has 4 cores.

I tried to find the version I was using before, but I do not remember it and I don't know how to check. Is there a way to find this in the .git file? It has been a while since I last updated, so it would be difficult to be specific.
If there is no way to find the previous version, I remember not having !setnumber! as an option, and I believe movable and re-sizable in game card information was new. Hopefully that narrows it down some.

I don't know if it is helpful at all, but I did load up a single player game and the token list seemed to work fine.

I did self compile, when that did not work I tired using the deb file, it had the same problem.

[Here is a the CMakeOutput.log from CMakeFiles](http://pastebin.com/cndTihtt). As a warning if there are  good practices in dealing with make files, I have not been following them.

Thank you for your help.

**Comment by blythe703** [comment]
I've noticed on the versions that didn't work the text looked different, slightly thicker and far more aliasing.

I am not entierly sure how git works, but I tried several different versions and fffc3e7 worked, but 089acfd did not. It also seems that bb5292a has the same text and lag issues. I tired going chronologically to see what commit had problems, but bb5292a is listed as before fffc3e7 and I don't know what I am doing.

Another possible problem is Qt5, I had to install it for this most recent update and I might not have installed it properly.

[Here is a CMakeOutput.log with fffc3e7 then bb5292a complied.](http://pastebin.com/3ZZfjFRJ)

**Comment by Daenyth** [comment]
Since it looks like this is definitely a regression I think it would be
good to try running a git bisect to track down exactly which commit
introduced the problem. Can you hop on the gitter chat at some point and we
can walk you though it? Basically git will keep cutting the commit history
in half between a known good and known bad version, and you compile at each
step, tell it if it's good or bad, and it will find the specific place it
changed

**Comment by blythe703** [comment]
Git Bisect Log

# bad: [0baccd3c00f84c85e744a842e891c39c05fb0c71] Merge pull request #2000 from ZeldaZach/fix_1946
# good: [fffc3e7e0089ded84d4c6cbdbd38cef36e25fdb0] Merge pull request #1982 from Cockatrice/mention-bot-config
git bisect start 'HEAD' 'fffc3e7e0089ded84d4c6cbdbd38cef36e25fdb0'
# bad: [4ffec331dcc7abad4a2502cd6e95caa771f336a0] Merge pull request #1995 from tooomm/tx_logo
git bisect bad 4ffec331dcc7abad4a2502cd6e95caa771f336a0
# bad: [575376403fa3d793e2c78510bad08b904adf9f16] Merge pull request #1985 from ctrlaltca/p_1405
git bisect bad 575376403fa3d793e2c78510bad08b904adf9f16
# bad: [36470c50619f8a7999afe3b55b8fe7a64e942e55] Merge pull request #1979 from ctrlaltca/make_qt5_great_again
git bisect bad 36470c50619f8a7999afe3b55b8fe7a64e942e55
# bad: [bb5292aa8de3755db4855154b713ae117ac84573] Drop Qt4, libgcrypt, qtmobility dependencies
git bisect bad bb5292aa8de3755db4855154b713ae117ac84573
# first bad commit: [bb5292aa8de3755db4855154b713ae117ac84573] Drop Qt4, libgcrypt, qtmobility dependencies
# bad: [bb5292aa8de3755db4855154b713ae117ac84573] Drop Qt4, libgcrypt, qtmobility dependencies
git bisect bad bb5292aa8de3755db4855154b713ae117ac84573
# first bad commit: [bb5292aa8de3755db4855154b713ae117ac84573] Drop Qt4, libgcrypt, qtmobility dependencies

The computer was using a AMD Phenom(tm) II X4 925 Processor

**Comment by Daenyth** [comment]
I'm looking for an issue on the qt5 bug tracker that might be related

**Comment by blythe703** [comment]
After installing Qt 5.6 and running with cmake -DCMAKE_PREFIX_PATH=/opt/Qt/5.6/gcc_64/ ..
I get 
```
cockatrice: /usr/lib/x86_64-linux-gnu/libQt5Multimedia.so.5: no version information available (required by cockatrice)
cockatrice: /usr/lib/x86_64-linux-gnu/libQt5Network.so.5: no version information available (required by cockatrice)
cockatrice: /usr/lib/x86_64-linux-gnu/libQt5PrintSupport.so.5: no version information available (required by cockatrice)
cockatrice: /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5: no version information available (required by cockatrice)
cockatrice: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: no version information available (required by cockatrice)
cockatrice: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: no version information available (required by cockatrice)
cockatrice: /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5: no version information available (required by cockatrice)
cockatrice: relocation error: cockatrice: symbol _ZTI9QRunnable, version Qt_5 not defined in file libQt5Core.so.5 with link time reference
```

**Comment by ctrlaltca** [comment]
Linux Mint installs Qt in /opt providing no configuration for `ld.so.conf? That's uncool :(

**Comment by Daenyth** [comment]
Mint installs 5.2 in the normal way. The opt install was with qt's installer
