### ISSUE TITLE
Version not shown in "About"

### ISSUE THREAD

**Issue by poixen** [Cockatrice/Cockatrice#2005]
OSX: 10.11.5
Installation method: `brew install homebrew/games/cockatrice`
Installation version: `stable 2016-05-06`

The version number should be shown in the about section of the application.

<img width="405" alt="screen shot 2016-06-06 at 11 42 26" src="https://cloud.githubusercontent.com/assets/2134793/15818175/1c81cc5a-2bdc-11e6-9dd5-4b3f9a976fcb.png">

**Comment by ctrlaltca** [comment]
We are using the git hash and date of the commit as version number. If the homebrew formula is not providing that info at compilation time, it won't appear in the dialog.
CMake could check for the presence of a specific file containing the "version to report in the client" and use that info in place of the data coming from git if unavailable.
Then, we should include such a file inside the table version's tarballs and/or ask the homebrew guys to create such a file when the formula is built.

**Comment by Daenyth** [comment]
We don't control the file, this should be filled as a bug against the brew package

**Comment by ctrlaltca** [comment]
Fixed in homebrew as of today.
