### ISSUE TITLE
Changing tab keeps chat entry contents 

### ISSUE THREAD

**Issue by dsolstad** [Cockatrice/Cockatrice#2007]
<b>OS:</b>
Win 7 SP1

<b>Cockatrice version:</b>
2016-06-04

---

<br>

When writing PM's to people and then a game you are spectating or playing in gets focus, the text you are currently writing gets written in the chat on the game instead. This often leads to awkwardness.

I have not found a setting for this and I think it's very useful.

**Comment by Daenyth** [comment]
How does the game get focus over the PM though? You need to click on the tab to switch over and focus it. Are you saying that the text you were typing in the pm window is in the game window's text entry for the chat?

**Comment by dsolstad** [comment]
Yes, exactly this.

**Comment by Daenyth** [comment]
Bizarre. Thanks

**Comment by dsolstad** [comment]
A scenario: I'm writing a PM to a player and right before I hit enter, the focus, or rather the cursor is automatically switched to the input field in another tab, where there is a game open and the text gets written in the chat there instead. I don't know what triggers it. Maybe a game starting or something.

**Comment by Daenyth** [comment]
I'm fairly sure the tabs shouldn't be automatically switching either.

**Comment by JineteDV** [comment]
![screen shot 2016-06-12 at 6 38 24 pm](https://cloud.githubusercontent.com/assets/6514656/15994262/806976f0-30cd-11e6-8844-0c06e612bd35.jpg)

**Comment by ZeldaZach** [comment]
Can't seem to reproduce on our end. If it's still a problem, let us know how we can reproduce
