### ISSUE TITLE
Shift-clicking in `Edit Sets`

### ISSUE THREAD

**Issue by skwerlman** [Cockatrice/Cockatrice#2009]
<b>OS:</b>
Sabayon 16.05 Cinnamon/MDM

<b>Cockatrice version:</b>
0baccd3

---

<br>

Currently when installing Cockatrice for the first time, you are presented with an 'Edit Sets' window. When I am setting up my sets, I find myself disabling entire types of sets (e.g. Reprint sets).

It would be nice if I could shift-click to select multiple sets in this window, since clicking individually to disable each and every set I don't want gets tiring fast, especially since I reinstall my OS fairly often.

**Comment by Daenyth** [comment]
:+1:

**Comment by ZeldaZach** [comment]
Do we / if we don't : Lets store the disabled set types in the user configuration file

**Comment by tooomm** [comment]
If you update your client (aka deinstall + install) just the same sets show up.
So we somehow save that already.

@skwerlman can you save and reuse your `settings.ini` the next time and check?

**Comment by skwerlman** [comment]
When I get home, I'll do a fresh VM install and see how it goes.

**Comment by tooomm** [comment]
Before this issue gets closed... how did your test go @skwerlman ?

**Comment by skwerlman** [comment]
well, it didn't go, because i completely forgot about this issue...

Looking at it now, I don't see the mentioned `settings.ini` in `~/.local/share/Cockatrice/Cockatrice/settings`, however `cardDatabase.ini` seems to have what we're looking for:
```ini
[sets]
10E\enabled=true
10E\isknown=true
10E\sortkey=91
2ED\enabled=true
2ED\isknown=true
2ED\sortkey=178
3ED\enabled=true
3ED\isknown=true
3ED\sortkey=174
(and so on)
```

And, yes, moving `cardDatabase.ini` is sufficient to restore the set ordering. Maybe a settings export/import feature could further reduce the cost of setting up on a new box?

As a side note, why is the path `~/.local/share/Cockatrice/Cockatrice/` and not `~/.local/share/Cockatrice/`? The current one seems redundant...

**Comment by ctrlaltca** [comment]
> As a side note, why is the path ~/.local/share/Cockatrice/Cockatrice/ and not ~/.local/share/Cockatrice/? The current one seems redundant...

First is vendor, second is product. We use Cockatrice/Cockatrice, Cockatrice/Servatrice, etc..

**Comment by skwerlman** [comment]
> First is vendor, second is product. We use Cockatrice/Cockatrice, Cockatrice/Servatrice, etc..

Ah, that makes sense. It just looks/feels weird when only Cockatrice is installed.
