### ISSUE TITLE
missing translations on transifex

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2010]
Froom Gitter: :point_up: [June 8, 2016 12:18 PM](https://gitter.im/Cockatrice/Cockatrice?at=5757f0df662b042b7e597f43)

>tooomm @tooomm Jun 08 12:18
https://github.com/Cockatrice/Cockatrice/blob/master/common/decklist.cpp#L96-L105
https://github.com/Cockatrice/Cockatrice/blob/master/common/server_protocolhandler.cpp#L406
these strings are missing completely in transifex. i guess it's because we just ship strings from the `oracle/` and `cockatrice/` directory (but not from files inside `common/`)
that's something for you, mr. transifex? @ctrlaltca 

>https://github.com/Cockatrice/Cockatrice/blob/master/common/server.cpp#L130
however exists (but just because it's there in cockatrice/src/window_main.cpp:104 as well i guess...)

**Comment by ctrlaltca** [comment]
> https://github.com/Cockatrice/Cockatrice/blob/master/common/decklist.cpp#L96-L105

Fixed in #2011, string extraction from the `common/` directory was broken due to a cmake script error.

> https://github.com/Cockatrice/Cockatrice/blob/master/common/server_protocolhandler.cpp#L406
> https://github.com/Cockatrice/Cockatrice/blob/master/common/server.cpp#L130

These strings are only used in the server. The server sends them alongside the error code, that is used by the client to show a correctly translated version of the error message.
