### ISSUE TITLE
hardcoded strings in the updater

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2012]
<b>OS:</b>
Win 10

<b>Cockatrice version:</b>
f6a3551 (2016-06-15)

___
<br>

Update Anyway
https://github.com/TMiguelT/Cockatrice/blob/66fda086c39b353708cab77e8e5607fdc506fc9e/cockatrice/src/dlg_update.cpp#L29

Open Download Page
https://github.com/TMiguelT/Cockatrice/blob/66fda086c39b353708cab77e8e5607fdc506fc9e/cockatrice/src/dlg_update.cpp#L31

Downloading Update...
https://github.com/TMiguelT/Cockatrice/blob/66fda086c39b353708cab77e8e5607fdc506fc9e/cockatrice/src/dlg_update.cpp#L87

Checking for Updates...
https://github.com/TMiguelT/Cockatrice/blob/66fda086c39b353708cab77e8e5607fdc506fc9e/cockatrice/src/dlg_update.cpp#L94

Finished Checking for Updates.
https://github.com/TMiguelT/Cockatrice/blob/66fda086c39b353708cab77e8e5607fdc506fc9e/cockatrice/src/dlg_update.cpp#L104

Update Available msg box
https://github.com/TMiguelT/Cockatrice/blob/66fda086c39b353708cab77e8e5607fdc506fc9e/cockatrice/src/dlg_update.cpp#L122-L124

Cockatrice Update
https://github.com/TMiguelT/Cockatrice/blob/66fda086c39b353708cab77e8e5607fdc506fc9e/cockatrice/src/dlg_update.cpp#L130

An Error occored (...)
https://github.com/TMiguelT/Cockatrice/blob/66fda086c39b353708cab77e8e5607fdc506fc9e/cockatrice/src/dlg_update.cpp#L154

An Error occored (...) /2
https://github.com/TMiguelT/Cockatrice/blob/66fda086c39b353708cab77e8e5607fdc506fc9e/cockatrice/src/dlg_update.cpp#L159

Installing...
https://github.com/TMiguelT/Cockatrice/blob/66fda086c39b353708cab77e8e5607fdc506fc9e/cockatrice/src/dlg_update.cpp#L163

Error
https://github.com/TMiguelT/Cockatrice/blob/66fda086c39b353708cab77e8e5607fdc506fc9e/cockatrice/src/dlg_update.cpp#L170

Unable to open (...)
https://github.com/TMiguelT/Cockatrice/blob/66fda086c39b353708cab77e8e5607fdc506fc9e/cockatrice/src/dlg_update.cpp#L171-L172

Could not open (...)
https://github.com/TMiguelT/Cockatrice/blob/66fda086c39b353708cab77e8e5607fdc506fc9e/cockatrice/src/update_downloader.cpp#L52

I hope this covers all strings regarding the updater! :)

**Comment by Daenyth** [comment]
Nice catch :)
