### ISSUE TITLE
Link to related card in deck editor

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2013]
I would like to see a right click menu in the deck editor list.
![related](https://cloud.githubusercontent.com/assets/9874850/16152989/a308f8ea-34a4-11e6-881b-df6aadccb529.png)

If you right click on a card you could choose to `Show related card` which jumps to and highlights it in the list. If there is a `related` tag.
Could also jump to tokens, emblems etc. for example and helps a lot with building decks.
But the most use would come from double faced cards since you don't necessarily know their name!

`Ancient of the Equinox` should be able to link to his "main" side:
`<related>Autumnal Gloom</related>`

**Comment by Jinxstands4Jinx** [comment]
I like this, but can we add something for tokens that have Multiple pictures. maybe make a way to only have 1 picture (a custom picture you like) and have the cards link right to that.

**Comment by ZeldaZach** [comment]
That's a completely different idea @Jinxstands4Jinx So i suggest you ticket it in itself. I'll see if I can look into this for you

**Comment by tooomm** [comment]
I don't understand what your idea is about @Jinxstands4Jinx 
But it seems to be different than mine, you should open a new issue and explain more in detail. Examples and/or pictures always help! :+1: 

Would be awesome @ZeldaZach !

**Comment by ZeldaZach** [comment]
Another thought on this: If we add a "flip" button below the image if we detect a double faced card, that could load the other side?

**Comment by ctrlaltca** [comment]
We currently don't have the concept of DFC in the card database, but only of "related" cards.

**Comment by tooomm** [comment]
The context menu should list all `<related>` cards, yes... :+1: 
Not just flip sides! Also tokens/emblems, meld cards etc.

**Comment by tooomm** [comment]
>Another thought on this: If we add a "flip" button below the image if we detect a double faced card, that could load the other side?

Now with meld and flip it would be nice to have something in the ui at the card picture as well... yes.
![flip-meld](https://cloud.githubusercontent.com/assets/9874850/16891557/ea580aac-4afb-11e6-8a35-7d8f284d4732.png)
