### ISSUE TITLE
Custom cards broken?

### ISSUE THREAD

**Issue by Jinxstands4Jinx** [Cockatrice/Cockatrice#2019]
I am on latest version of client and the Custom Card feature is NOT working. I am attempting to make proxies of the EMN cards that were just revealed. Normally the process is to Save an image in the Custom folder, then save a decklist from clipboard with the New card(s) typed in. I did that but the picture is coming up blank.

**Comment by ctrlaltca** [comment]
So much for issue templates, what OS and exact version of cockatrice are you on?

**Comment by Jinxstands4Jinx** [comment]
Version 2ab3209 (5-16-16) I am on windows 8, as I like the set up it has. This is the Same set up I had during Soi and there was No issue there.

**Comment by Daenyth** [comment]
Can you provide a screenshot?

**Comment by Jinxstands4Jinx** [comment]
This is related to "When a card name isn't in card database, still check for CUSTOM/ picture #2023 " and is basically the same issue

**Comment by ctrlaltca** [comment]
Closing as a duplicate of #2023, let's continue the discussion there.
