### ISSUE TITLE
Add the ability to select which art to use for specific tokens.

### ISSUE THREAD

**Issue by Jinxstands4Jinx** [Cockatrice/Cockatrice#2022]
I was told to make this a New issue or suggestion so here goes.

What I am talking about here is things that make tokens. Example the eldrazi scion tokens from the bfz/ogw sets. there are 3 different pictures of them. most people make the token of the original which would be [[Eldrazi Scion]](I no longer have this picture). Other cards make the Same token name but many different versions example number 2. Chandra's elemental tokens are different from young pyromancers. I think we should link EVERY token maker to is correct token. so that players do not have to bring up the long list of tokens and hunt for the picture that is correct. most players actually use the wrong pictures and just adjust power and toughness. Which works in most cases. but my 3rd example is Forbidden orchard. the spirit token made by this land does not fly. many people forget that. and when you make a [[Spirit]] token most of the time you get the 1/1 white flying creature token. Not only is this token the wrong color but it should not fly.

**Comment by tooomm** [comment]
Did you check out our newly introduced feature called `Create related card`?
![spirit](https://cloud.githubusercontent.com/assets/9874850/16279746/b632a24c-38bc-11e6-8bb7-de9639379299.png)

It immediately creates the correct version of the spirit, as seen in the example.

*It could have the keyword abilities next to the name as well maybe, well.*

**Comment by Jinxstands4Jinx** [comment]
Yes. Also that feature is not on token makers.  it is on the flip cards. not sure how you got it on the token makers as I do not.

**Comment by tooomm** [comment]
It is available for all cards that create tokens.
Planeswalkers, Instants, Creatures etc. as well as double faced cards.

You should make sure that you run the most recent client version AND update your card + token database!

**Comment by Jinxstands4Jinx** [comment]
I am updating now, hopefully the Bugs that prevented me from updating are
also fixed. Those bugs do not pertain to this issue so I will not mention
them.

**Comment by Jinxstands4Jinx** [comment]
Just updated to the shadows client....do not see the related card feature on forbidden orchard....

**Comment by tooomm** [comment]
Did you run `Oracle` as well to update your cards.xml and tokens.xml databases...

**Comment by Jinxstands4Jinx** [comment]
all is set up. thankyou. Sadly those other features are not fixed (will handle in other issues) this fixs kinda solves most of the issue I listed so the only other part would be to make users able to Set Custome images for tokens example they could change Chandra's elemental picture but leave the elemental picture for omnath.

**Comment by Daenyth** [comment]
> make users able to Set Custome images for tokens

The way the app is currently written this is really hard to add. We'll get there eventually but it's going to have to be after we rewrite how we handle tokens. The issue is that we don't really have a "true" source of tokens outside of the one maintained by Psithief. Everything in it is written by hand. The cockatrice card db treats card name as the unique identifier, and tokens can have the same name but different abilities, that's the core issue. We get around that by making the actual name include extra spaces right now like `"Spirit"` vs `"Spirit "`

**Comment by tooomm** [comment]
Linking #1847

**Comment by ToMuchNeverEnuf** [comment]
I was just wondering if this was going to be able to be used to have multiple arts for a single type of card? Could the code be modified to ignore trailing spaces when looking for coding, ability, and card info "So 'Naturalize' 'Naturalize ' and 'Naturalize  ' would all be linked to the same card (for meta date and related tokens) but could be linked to separate images (so you could have a set of custom images for one card). I've been loving all the updates and would find this to be AMAZING! Thanks and keep up the awesome work!

**Comment by ZeldaZach** [comment]
Dupe #2545
