### ISSUE TITLE
When a card name isn't in card database, still check for CUSTOM/ picture

### ISSUE THREAD

**Issue by Jinxstands4Jinx** [Cockatrice/Cockatrice#2023]
Since the Custom card saving trick no longer is being supported. (no idea why as its a much better feature) I feel we should have a you-tube link explaining to people how to create xmls and how to make Workable proxies for when new sets come out.  This would help because no one likes ot play games with unreadable blank cards when trying to play cards from the newest set before the Full blow xml is released.

**Comment by Daenyth** [comment]
I'm not sure what you mean by `Custom card saving trick no longer is being supported`

What was the trick? I don't recall us removing support for anything like custom cards before.

**Comment by Daenyth** [comment]
We should still document the custom sets.xml though.

**Comment by Jinxstands4Jinx** [comment]
well for a while you could Save a picture into your custom card folder. then build a deck and copy the name via the clipboard and you would get proxies with pictures of the actual cards.....For some reason this no longer works.  That was the trick.  

The main thing was though some users, myself included do not know how to create an xml at all and would like to learn via a you-tube video.

**Comment by Daenyth** [comment]
Hmm, I think I might know what broke that. The fact that it ever worked at all was a bug which we fixed.

We can add it back in as an actual feature though.

cc @ctrlaltca 

I think the feature to add in here is when a card name can't be found in the card database, we still check for CUSTOM/ picture with that name.

**Comment by Jinxstands4Jinx** [comment]
That would probably work. and make "new set" times much easier.

**Comment by ctrlaltca** [comment]
A bit of history about how this worked in the past:
When the card database got a request for a not-existing card, it would create an empty token named after the requested card name.
This caused problems: since the token database was filled by a lot of "dummy" tokens named after real cards, once those cards ended up officially in the card database they would get overwritten by the dummy tokens.

Unfortunately i was not aware of your use case when trying to fix this problem, so i accidentally broke it, sorry for that.

**Comment by Jinxstands4Jinx** [comment]
No problem, You cannot control breaking something you did not know even existed at the time. And to be honest it sounds like when we get it back it will be a Better feature than before. so technically I should thankyou for breaking it, lol :)

**Comment by ZeldaZach** [comment]
@ctrlaltca Wanna do anything with this?

**Comment by ctrlaltca** [comment]
I'll look into it this weekend, if i have enough time.

**Comment by ctrlaltca** [comment]
Fixed in  #3589
