### ISSUE TITLE
Kiora, the Crashing Wave token issue

### ISSUE THREAD

**Issue by KarasuGamma** [Cockatrice/Cockatrice#2026]
Currently, the Kraken token Kiora's emblem creates is tied to Kiora rather than the emblem. This is moderately inconvenient in situations where Kiora isn't in play and you don't have another Kraken to clone. Can this be reassigned to the emblem?

I doubt this is worth posting as a new issue, but I wasn't sure where else to make a small suggestion like this. I was tempted to post this in #655 but that didn't feel right.

**Comment by ctrlaltca** [comment]
Thank you for the hint, i've created an issue at the Magic-Token repo: https://github.com/Cockatrice/Magic-Token/issues/11

Closing this one, please continue the discussion on the other ticket.
