### ISSUE TITLE
Clicking opponents life modifies your own

### ISSUE THREAD

**Issue by poixen** [Cockatrice/Cockatrice#2027]
Title says it all.

**Comment by KarasuGamma** [comment]
The same applies to the mana and storm counters, though I don't know if any of this is intentional.

**Comment by Daenyth** [comment]
Surprised no one has come across this before.

**Comment by tooomm** [comment]
Indeed. I can confirm this false behavior on windows.
Middle click on life or mana/storm of your opponent doesn't work though. Just right/left mouse clicks are working.

You shouldn't be able to modify this information. You don't own it.

**Comment by Psithief** [comment]
Isn't this from local game support?

**Comment by tooomm** [comment]
Yes, maybe shared code without proper checks causes the issue.
In local games it should edit your opponents data, while it shouldn't modify anything in a normal game.

**Comment by jjcard** [comment]
Happens with the Mana and the storm counters as well
