### ISSUE TITLE
Can't update

### ISSUE THREAD

**Issue by Milosz006** [Cockatrice/Cockatrice#2028]
<b>OS:</b>
Windows 7 64-bit

<b>Cockatrice version:</b>
c19f225 (2016-06-26)

___
<br>

Automatic updating doesn't work, where can I get the newest cards.xml? The latest set I have is Zendikar vs Eldrazi.

**Comment by Daenyth** [comment]
Run the Oracle program

**Comment by ctrlaltca** [comment]
![error message](https://cloud.githubusercontent.com/assets/1631111/16370710/2fe6453e-3c42-11e6-92a7-c11a15be0257.png)

Please, try to be a little more specific the next time, like telling what you tried, what you expected to happen, and what happened instead. "Doesn't work" is so generic we can't really help you a lot.

**Comment by ctrlaltca** [comment]
I suppose this was related to #2031.
