### ISSUE TITLE
"Meld" Cards

### ISSUE THREAD

**Issue by ZeldaZach** [Cockatrice/Cockatrice#2030]
My suggestion for how we should handle the new Meld Cards:

We add a new optional tag, <kbd>merge</kbd> which (for now) allows you to input the name of one card. Then, we use the standard <kbd>reverse-related</kbd> tag for the "back" sides of the melded cards, linking it to the card that has the clause for melding. Finally, when you create the meld token, all cards that have the merge tag that are in play on your side of the battlefield will become attached to the new token. Note that we are not necessarily checking that they have the required creatures in play, but that if the creature IS in play, we are to combine them.

Example:
**Cards.xml**

```
<card>
<name>Bruna, the fading light</name>
</card>

<card>
<name>Gisela, the broken blade</name>
<merge>Bruna, the fading light</merge>
</card>
```

**Tokens.xml**

```
<card>
<name>Brisela, voice of nightmares</name>
<reverse-related>Gisela, the broken blade</reverse-related>
</card>
```

(Some tags omitted as they aren't necessary to portray my example)

Example 1: You have both cards that can be melded together in play
<img width="341" alt="screenshot 2016-06-27 15 54 51" src="https://cloud.githubusercontent.com/assets/7460172/16393649/91c5909c-3c7f-11e6-8f65-2f4c3aa11c6e.png">

Now, when you meld this is the result:
<img width="269" alt="screenshot 2016-06-27 15 54 41" src="https://cloud.githubusercontent.com/assets/7460172/16393648/91c53336-3c7f-11e6-975f-8edb1c15f979.png">

<hr>

Example 2: You have only the one card that has the clause for melding in play (while this may not be correct rules wise, we still have to support this just in case)
<img width="148" alt="screenshot 2016-06-27 15 56 49" src="https://cloud.githubusercontent.com/assets/7460172/16393708/c854b00c-3c7f-11e6-9d8f-6982601df389.png">

Now, when you meld this one card by itself:
<img width="295" alt="screenshot 2016-06-27 15 55 14" src="https://cloud.githubusercontent.com/assets/7460172/16393647/91c42554-3c7f-11e6-970b-605dc2df5a68.png">

We do have to be careful, however, if a person has multiple copies of a card in play. If somebody has two copies of Bruna, lets say (I know this can't happen, but there might be instances where the cards that meld may not be legendary), and one copy of Gisela, that only one copy of Bruna is "melded" and the other is left alone.

I'd like to see what everybody thinks of my proposed idea and what they think should be done to support this new card type.

**Comment by JineteDV** [comment]
Idea: Right click on X select 'meld' from the menu, the menu goes away and has you already draw an arrow from X, you click on Y, and then cockatrice makes the appriopriate token and attaches X and Y to Z.

**Comment by Daenyth** [comment]
Do you have a link to the new rules announcement?

**Comment by skwerlman** [comment]
imo, leaving the individual cards (bruna, gisela) would make the board feel cluttered.

**Comment by ZeldaZach** [comment]
Related ticket: https://github.com/lsmoura/mtgjson/issues/187
Rules: http://magic.wizards.com/en/articles/archive/feature/eldritch-moon-mechanics-2016-06-27

**Comment by Jinxstands4Jinx** [comment]
The "melded" cards should be exiled or Taken off the field because you can only stack 3 cards in a row.  For sure we should have the Correct meld named in the selection so people do not misspell them or have to type out the Name each time.

**Comment by ZeldaZach** [comment]
@Jinxstands4Jinx They're not "stacked", they're attached. There's a difference.

<img width="362" alt="screenshot 2016-06-27 16 32 28" src="https://cloud.githubusercontent.com/assets/7460172/16394747/c0675386-3c84-11e6-95c9-28726c6c87b9.png">

**Comment by Jinxstands4Jinx** [comment]
yes but that looks terrible and it would be unreadable.

**Comment by Daenyth** [comment]
We don't really have a better option right this moment

**Comment by Jinxstands4Jinx** [comment]
We cannot link them to a Token or a 3rd card and put the other 2 copies into sideboards? This seems like a very easy fix.

**Comment by ZeldaZach** [comment]
That seems excessive and not worth the haggle to me

**Comment by Jinxstands4Jinx** [comment]
so you rather have the attached and 2 cards unable to be read correctly without using the details feature. because if you try reading the pictures it seems impossible.

**Comment by ZeldaZach** [comment]
You have no real reason to see the attached cards. they're just there in case you need them... And you can always scroll over. If you'd like to develop a different method, feel free to

**Comment by Jinxstands4Jinx** [comment]
You asked for suggestions... i gave some. you shoot them down and told me to go to hell...... really zack??  I think attaching the cards is not going to be clean and look very good but alas I am 1 user among many.

**Comment by KarasuGamma** [comment]
It's no different from how dual-faced cards are handled already - it creates a token of the other face, and attaches the real card to the token. The real card has to exist somewhere, and the most reasonable place is the battlefield, since it's not destroyed or exiled.

I think @JineteDV offered the cleanest way of doing it; the game shouldn't be making an assumption of which other creature to use.

**Comment by Jinxstands4Jinx** [comment]
and when you have a dfc normally some users, myself included remove the front face from the field unless it can be "reflipped" in the case of something like Arlinn kord your idea works but in the face of something like Chalice of life/death once it flips the front is usually exiled in a player's sideboard. also in both cases the front side is 1 card in this case the front side is actually 2 cards.

**Comment by ZeldaZach** [comment]
@KarasuGamma His idea seems pretty good to me, just I'd like to see an example (maybe w/ pictures?)

**Comment by Jinxstands4Jinx** [comment]
I like his idea except that having 2 cards "sideways" and unreadable seems cumbersome

**Comment by KarasuGamma** [comment]
@ZeldaZach I presume it'd look something like this:
![brisela](https://cloud.githubusercontent.com/assets/18459787/16398281/8cf2146a-3c97-11e6-9898-976a4fd17cb1.png)

**Comment by Jinxstands4Jinx** [comment]
That will be cumbersome with aura's, equips, and what not. I seriously think we should consider a "meld zone" or something as this will only look worse as more cards are attached to the initial card.

**Comment by KarasuGamma** [comment]
I have never seen or heard of anyone removing the real card when transforming it, and I would personally ask an opponent who does it not to do it when playing with me.

**Comment by ZeldaZach** [comment]
The goal of Cockatrice is to work with numerous games, so exiling the cards really doesn't fit with that motto. Attaching them to the creating object is the best way imo

**Comment by Jinxstands4Jinx** [comment]
karasu, I am only pertaining to cards that do not flip back. as in a Real life game the card is no longer on the field. For example Chalice of life/death. When death is on my field you cannot see life as its on the other side of the card. in cockatrice I just exile the front to my sideboard as it is not there anymore. This makes perfect sense.  In the case of Arlinn kord who flips back and forth as turns go by I do as normal and attach the cards together always making sure the current state is always on top. In the case of these, I guess I'll have to exile them to sideboards as the field is only so big.

**Comment by KarasuGamma** [comment]
That's flawed logic since that has actual gameplay implications regarding where the card actually is, but this is off-topic.

I think there is another significant issue with compliance with the meld rules brought up in #1912 in that
> the server is not tracking card ownership
The meld cards state that you must both own and control the cards for the ability to create the melded card.

**Comment by JineteDV** [comment]
@KarasuGamma That picture is exactly what I was describing.

**Comment by KarasuGamma** [comment]
Any updates, now that the prerelease is over and the set is closer to release?

**Comment by ctrlaltca** [comment]
The cards are in mtgjson, and the "create related card" feature works. The only problem is that only one of the original cards (eg. bruna or gisela) gets attached to the melded card.

I'm starting to thing that maybe the easiest implementation is to attach all the currently selected card to the "related card" when using that feature.

**Comment by Jinxstands4Jinx** [comment]
I still like the idea of exiling both halves to the sideboard and just
using 1 token without the other 2 attachments because too many attachments
on 1 creature is annoying to look at.

**Comment by tooomm** [comment]
Linking #3033

**Comment by ZeldaZach** [comment]
Dupe #4081
