### ISSUE TITLE
Custom Formats

### ISSUE THREAD

**Issue by LethalPigeon7** [Cockatrice/Cockatrice#2033]
Would it be possible to have the "Custom" format have a text box? It would ideally allow a user to write in whatever they want to appear in the "Game Type" characteristic much like they do with the Description.  
This would be immensely helpful for filtering out the smaller (or bigger) formats not recognised by cockatrice, and shouldn't disrupt anyone else.  
The worst outcome I can imagine is people using custom names for already existing formats, leading to a more hectic game list when sorted by game type. Aside from a large amount of time being spent on a feature of not so large significance to the community as a whole that is.

**Comment by woogerboy21** [comment]
> The worst outcome I can imagine is people using custom names for already existing formats...

Best line of the day :+1:

**Comment by LethalPigeon7** [comment]
Is it just entertaining or also a valid reason not to do this. The amount of people willing to bother with that is minimal and so is the damage.

**Comment by tooomm** [comment]
In theory this sounds reasonable. But I doubt it would work...

**Comment by ZeldaZach** [comment]
People can also write inappropriate things which is slightly annoying, but overall I'd be fine with this.

**Comment by skwerlman** [comment]
Could they be listed as `Custom (<game type here>)`? This would eliminate (or at least reduce) the sorting issue @LethalPigeon7 mentioned.

**Comment by LethalPigeon7** [comment]
you can still put vulgar things in the room name, so that is not an argument unless theres some horrid censorship feature with room names that couldnt be tranfered to format names

**Comment by ZeldaZach** [comment]
If users are vulgur, mods can just ban them. We can include that in the TOS easily (up to each server owner)

**Comment by ZeldaZach** [comment]
You can use the Description field. We filter on Formats, and this would just add more chaos to the mix
