### ISSUE TITLE
Cockatrice-x64 installs on the wrong folder on Win64

### ISSUE THREAD

**Issue by ctrlaltca** [Cockatrice/Cockatrice#2035]
Currently the NSIS script only supports installation on 32bit systems.
As a result, even if cockatrice is compiled as a 64bit app, it's installed in `c:\program files (x86)\Cockatrice` and the installer is using the 32bit registry.

**Comment by tooomm** [comment]
Some related links:
- https://stackoverflow.com/questions/21822044/merge-32bit-and-64bit-installer-into-one-installer-using-nsis
- https://stackoverflow.com/questions/19374453/nsis-installer-define-installer-and-system-x32-x64
- https://stackoverflow.com/questions/14089647/install-to-program-files-x86-on-64bit-host
- http://forums.winamp.com/showthread.php?threadid=301724
- https://github.com/qbittorrent/qBittorrent/issues/6079
- http://www.bojankomazec.com/2011/10/nsis-installer-for-64-bit-windows.html
