### ISSUE TITLE
Link to new-player quick start guide in the application / installer

### ISSUE THREAD

**Issue by Jinxstands4Jinx** [Cockatrice/Cockatrice#2040]
Quite recently I have been pming newer players and giving them a little "intro to cockatrice" guide that I wrote up. I think we should attach this to the install area or put it somewhere easy to find so that new players can grasp the game easier and become Familiar with controls better.  I have included the guide and if anyone wants to add to it, please feel free. I notice new players in the main all the time and I remember not long ago when I had to wear the "I'm New" shoes and it is not always fun. 

Ctrl L= Set life total
Ctrl M= Mulligan
Crtl D= draw card
Crtl T= make token
Ctrl W= Scry
Ctrl I= Dice roll
Ctrl R= Remove arrows
Ctrl F3= look at sideboard during game. (useful for edh)
Ctrl f2= Concede.

Most players prefer you go to end and Do Not pass the turn as it messes up EOT plays and can jeopardize game flow causing arguments.

Right click cards does most functions.

Drafting/Sealed

enter a draft/sealed room and the host will give you a link once you reach correct number of players (most cases 8) that link will be to DR4ft.com draft site and they allow you to draft by picking cards and building a deck, they even provide lands. It is good practice to include some lands in your sidebaord as adding them later becomes impossible. Once you build the deck you will download it You and your opponent will move to a separate room to play best of 3 games. you lose then good luck in next draft. You win then report back to the main draft lobby and inform players remaining that you are "ready for Round 2". 

Arrow Drawing

When drawing an arrow (normally with mouse to show what you are targeting and such)  You can draw multiple colored arrows.

For a red arrow, do nothing (default)
For a green arrow, hold shift while drawing
For a blue arrow, Hold Alt while drawing
For a yellow arrow, hold CTRL while drawing

**Comment by ZeldaZach** [comment]
Related: #652

**Comment by tooomm** [comment]
It would also nicely fit to our wiki that players could link to it!
The `Get Started` is well... not so helpful right now. hehe

**Comment by Jinxstands4Jinx** [comment]
Thankyou tooomm.

**Comment by ctrlaltca** [comment]
Thank you @Jinxstands4Jinx !
I've moved the guide to a wiki page: https://github.com/Cockatrice/Cockatrice/wiki/One-minute-game-guide and linked it on the top of the wiki menu, so that people will find it easily.
The next step could be linking the guide somewhere in the UI

**Comment by Daenyth** [comment]
This is a great contribution! Thanks so much :)

@Jinxstands4Jinx I believe our wiki is open to public edits, so if you have more ideas for documentation feel free to just add the page - we can review it pretty easily there and then make direct edits as well.

**Comment by Daenyth** [comment]
@ZeldaZach a link to that wiki page with a summary would be a great first "tip" for that ticket

**Comment by tooomm** [comment]
Also linking https://github.com/Cockatrice/Cockatrice/issues/3063
