### ISSUE TITLE
Prevent/warn when joining games of users that I have ignored

### ISSUE THREAD

**Issue by poixen** [Cockatrice/Cockatrice#2041]
As a user, I would like to avoid all contact with an ignored player.
Currently this extends to in game communications, but not to player games.
## Current Behaviour

If I ignore a user, and they have not ignored me, then I am still able to join the game.
## Expected Behaviour

I would like to have a pop up that tells me I can not enter the game as the user is on my ignore list.

**Comment by LethalPigeon7** [comment]
What's the expected behavior for multiplayer? Be it 4mans or limited rooms. It's obviously equally as bad as joining a 2-man.

**Comment by ctrlaltca** [comment]
What happens when you are playing with someone and you ignore him or viceversa? One of you gets kicked out of the room?

**Comment by poixen** [comment]
If you ignore a user during a game you will continue as normal. The user may not PM you though. 

Best Regards
Matthew Lowe

**Comment by tooomm** [comment]
Clarification:
#724 is about hiding games from people that you ignore in the list of games. It would be a new filter option.

This issue is about preventing to join games created by ignored users (or at least show a warning/confirmation before).

**Comment by ZeldaZach** [comment]
Tracking on #2448
