### ISSUE TITLE
Error Opening File for Writing

### ISSUE THREAD

**Issue by LethalPigeon7** [Cockatrice/Cockatrice#2042]
<b>OS:</b>
Win 7 SP1
<b>Cockatrice version:</b>
Archivist Madness

___
<br>

So for the first time I can remember I encountered a problem installing.
![image](https://cloud.githubusercontent.com/assets/7950438/16505853/48532e22-3f1f-11e6-9d25-3acea8ae8757.png)

**Comment by ZeldaZach** [comment]
Try reinstalling again. Might be a file mod issue

**Comment by LethalPigeon7** [comment]
Nope. Still dead.

**Comment by ctrlaltca** [comment]
Possible causes:
 * Something is locking that file, possibly a running process (like a crashed cockatrice), a reboot could solve the problem
 * You installed as an administrator and now don't have the permission to write to that folder anymore, try to run the setup with right click -> run as administrator

**Comment by ctrlaltca** [comment]
Merging with #1574
