### ISSUE TITLE
"Edit Tokens" causes issues

### ISSUE THREAD

**Issue by Nahiri** [Cockatrice/Cockatrice#2043]
<b>OS:</b>
_64-bit Windows 8.1_

<b>Cockatrice version:</b>
_Version e81a6d4 (2016-06-21)_

---

<br>

For a while now (since SOI release, I believe), I haven't been able to successfully retain a custom collection of tokens. I know you've changed how tokens work around that time, so it may be related.

I do not wish to use the default Oracle tokens.xml - I'd rather use my own. I don't really play cockatrice online with random people, only with friends who have the exact same .xmls that I do, and thus we much prefer having strictly only the tokens that we use in our decks available, so that the list we have to sift through when ctrl-T'ing is only as big as it needs to be.

Problem is, for some time now, I haven't been able to go Card Database > Edit Tokens to add tokens or even edit the .xml directly to add tokens as I've done in the past, as the list of tokens keeps getting partially erased, seemingly at random, everytime I run the program.

While perhaps unconventional for a ticket (I wouldn't know), I see no reason why I can't [Show and Tell](https://www.youtube.com/watch?v=svw-8qv3aUw&feature=youtu.be).

Quality isn't stellar, but it's what I could whip up on short notice. Image should be sharp enough to see and read in 720/1080p.

Although I added notes to the video, here's what I do in it:

I first show that I have my tokens.xml correctly pathed, and then proceed to open it. It has a bunch of tokens in it - this isn't the full list I normally use, but it works for the purposes of demonstration

When I first open Cockatrice, all is well: all the tokens are there. Close it, run the binary again, and it's clear to see some tokens are gone. Rinse and repeat, they're still gone (if I were to continue, more might disappear).

I also demonstrated something odd: if I am to try to manually add a Token named 'Clue', it won't allow me to do so, despite the 'Clue' token having gone missing from the list. Probably because in spite of that, it's still in the .xml. They're effectively only missing from the list - their disappearance doesn't affect the actual .xml in any way.

Any help would be appreciated. If there's any other additional relevant information you need, let me know.

**Edit:** Unrelated but I've just sent you some 200+ (PT)Portuguese translations on transifex. May take care of the remaining 300 later.

**Comment by tooomm** [comment]
Congratz on the first video ticket ever. Not a bad idea, hehe. :laughing: 

First things first:
There is a new version in case you want to check that out:
https://github.com/Cockatrice/Cockatrice/releases/tag/2016-06-30-Release
<br>
>so that the list we have to sift through when ctrl-T'ing is only as big as it needs to be.

We have a nice little feature for that for a while now, called "Create predefined token".
Well, I'm kidding. It has been around forever I think. :)
It just lists tokens that you've added to your decklist and you can use shortcuts to create them.

But we have a real nice little new feature for that, called "Related cards"
You just need to rightclick any card that has related other cards or tokens (dfc cards work for example, or any emblem, enchantment, sorcery, planeswalker, creature etc. that creates tokens) and you can simply chose which of the ones, linked to that card, you want to create. It's awesome. But stuff like that just works with token files that contain special information. 
Serious, you should give the normal intended use a try, you never ever need to use `Ctrl+T` again for example if you don't want to. (for normal Tokens at least)

<br>
>as the list of tokens keeps getting partially erased, seemingly at random, everytime I run the program

@ctrlaltca can tell you for sure

But we have two types of token files now. The **`tokens.xml`** (same as `cards.xml`) **are not intended for user modification now** (see https://github.com/Cockatrice/Cockatrice/issues/1927). If you use `Edit tokens...` and hit `+` to create a new token, it'll create a special file in your `customsets` folder which you could freely modify (`TK.xml`), but it just contains new tokens.
If you modify exisiting tokens which are in the tokens.xml file the app shows the new value but the file is not edited (that's actually a good behavior, but the Edit tokens dialog should just dispaly custom tokens, especially if you can't modify others (which i like!)), so if you restart a 99/99 spirit is 1/1 again!

That's actually a displaying issue and a matter of not displaying content from the tokens.xml file in the edit tokens dialog i think.

<br>
I suggest you test if the custom `TK.xml` works for you, and/or you update your card database+tokens and you check out that nice&shiny new `Create related card` feature.

**Comment by ctrlaltca** [comment]
The specific issue of user-created tokens being overwritten by oracle has already been reported as #1858 and solved in #1859, so the recently released versions should not be affected anymore.

**Comment by tooomm** [comment]
The client he is using has that fix already in^^

**Comment by Nahiri** [comment]
Thank you both for your replies and time, I've just tested tooomm's solution and it seems to work well enough:

[Token example in my deck](http://i.imgur.com/JBkQfMV.png)
[Token in play](http://i.imgur.com/MKL1fF1.png)

Nothing seems to be getting swiped after restarting the program, thus everything seems to be in order. I rather like the 'display only tokens from this deck' functionality, but I still wish that the edit tokens section wasn't cluttered by all these additional unnecessary (for me & my friends) tokens, but that's alright.

I apologize for not having found those two previous issues ctrlaltca mentioned, I glossed over r/cockatrice to find an identical problem and found nothing - Daenyth told me to post the issue here instead and I didn't think to scour previous issues for the same problem first.

**Comment by tooomm** [comment]
I don't know what you actually tried and what your "solution" was... :)
Anyway, I don't understand why you don't want to use the `Create realted card` feature?
![untitled](https://cloud.githubusercontent.com/assets/9874850/16540364/a3a51580-4062-11e6-90a3-ac87811747eb.png)


<br>
>I see that the oracle token list allows for multiple tokens with the exact same name. Is there any way to do this with custom tokens?

We use spaces as a workaround.


>I rather like the 'display only tokens from this deck' functionality

It doesn't work for me either. There is some problem with that I guess. Maybe https://github.com/Cockatrice/Cockatrice/pull/1981?

>but I still wish that the edit tokens section wasn't cluttered by all these additional unnecessary (for me & my friends) tokens

Have you tried just deleting the tokens.xml? As long as you don't tell Oracle to download cards AND tokens. You should be fine.

**Comment by Nahiri** [comment]
The "solution" was no longer trying to edit the tokens.xml file. Prior to you having informed me of it no longer being possible, it's what I was doing, since it used to work fine in the past. 

I missed the memo when it was changed because I was busy around OGW/SOI release times and didn't make any token changes in the first half of 2016.

Incidentally, I did rename the tokens.xml just before reading your latest reply to see if I could do away with it and keep the custom TK.xml working fine, and it does.

Additionally, thank you for the "spaces" workaround tip, it works wonders:

![example](https://cloud.githubusercontent.com/assets/20253640/16540549/929f3952-4060-11e6-8214-f0988b13368a.png)

I may turn to using the related card feature at a later point in time, but for now I'm satisfied with my non-cluttered and most importantly **working** token list. Thank you very much for your help.

**Comment by tooomm** [comment]
Your welcome. As far as I know we can't deal with different pictures at the moment. So this would be a workaround. :)

Can you please test and confirm https://github.com/Cockatrice/Cockatrice/issues/2044?
I stumbled upon in while testing some stuff with your issue.

**Comment by Nahiri** [comment]
My previous reply has links to two pictures hosted on imgur where you can see that the create tokens from deck functionality works for me.

I added an "Angel #1" Token to my test decklist and it then appeared when I toggled "Show tokens from this deck" while in-game.

**Comment by Daenyth** [comment]
I think the remaining item here is that "Edit Tokens" should work cleanly.

Does it? If not, we should fix it.

**Comment by tooomm** [comment]
Our token handling within the app and also with the new custom tokens is not clear right now and we should explain better how to use both files and clarify what the `Edit tokens` dialog is doing.
But we also need to rethink what `Edit tokens` should be doing in the first place.

If users should be able to editing tokens there, then it should just be custom tokens since we don't want people to change and break the `tokens.xml` file (same as they should not modify `cards.xml`). They still could if they feel the need.
But since we list all available tokens from both files in the `Edit tokens` dialog it suggest they can edit them. Which is actually not true, tokens from the token.xml can't be edited. You can't edit tokens from our `tokens.xml` file from within the `Edit tokens` dialog, see my first post here:
>If you modify exisiting tokens which are in the tokens.xml file, the app shows the new value but the file is not edited (that's actually a good behavior, but the Edit tokens dialog should just dispaly custom tokens, especially if you can't modify others (which i like!)), so if you restart, a 99/99 spirit is 1/1 again!

So I suggest that we just display tokens from the custom `TK.xml` set in the `Edit tokens` dialog. Easy for the user to use and understand. Plus unexperienced users are not messing with our file and braking basic functionality. The menu item should be renamed to `Edit custom tokens`, too.
Advanced users could still modify both files if they like to. For example, like @Nahiri did to add custom pictures to tokens, which you can't do with the `Edit tokens` dialog.

**Comment by Nahiri** [comment]
I'd like to correct my previous statement that said one can delete the tokens.xml file and work with only the custom TK.xml.

Did some more stress testing just now and I'm still having tokens getting randomly deleted while only making changes to TK.xml while **not** having tokens.xml.

**Comment by tooomm** [comment]
But if you keep the `tokens.xml` file it's working?

There is definitely something going wrong at one point. :/

**Comment by Nahiri** [comment]
The plot thickens. Here are my findings:

I tried a different approach from what I said - I created Tokens named Test1,Test2(...)Test9 with both tokens,xml **AND** TK.xml active to see if they could co-exist. 

At this time the tokens had nothing but a name. I restarted the program 10 times and never lost a token.

I proceeded to add an annotation to every 2nd card and restarted the program 10 times to see if that would make a difference, and no cards were lost.

I then made a third experiment and started attributing colours aswell as P/T to these tokens, and the very next time I re-opened the program, some of the "Test" tokens were missing.

I will try to pinpoint whether the colour **or** the P/T attribute was the underlying cause (since I altered both in the same step), but I now know that one way or another, even with both .xmls active, custom tokens still get deleted.

**Comment by Daenyth** [comment]
This is bizarre...

**Comment by Nahiri** [comment]
Yes, it is... 

I should also add that I also started experiencing this problem on my 64-bit Windows 7 laptop around the same time (OGW || SOI release time), so it's happened across two different machines with different operative systems.

I haven't yet tested if the problem is ocurring there at the moment, nor do I have the laptop handy right now. Can anyone reproduce this problem?

**Comment by Psithief** [comment]
I can't even manage to add a new token on that screen and have it appear in the list, but it won't let me add a token with the same name again because it already exists.

This screen needs to be redone with a new purpose in mind.

**Comment by ZeldaZach** [comment]
When we add tokens they should be added to another custom file, similar to the cards... hmm

**Comment by Nahiri** [comment]
They **do** get added to a custom file, the TK.xml

The problem is the fact that they get deleted for no good reason =/

**Comment by ZeldaZach** [comment]
So they get deleted from the TK file? now that shouldn't be happening

**Comment by Nahiri** [comment]
If you refer to one of my previous posts (I have no idea how to link to specific post on Github, but it was my last post from 3 days ago), they don't get deleted if all you do is name them. That is, create <insertnamehere> token on the edit tokens menu. It's when you start fiddling with the attributes that they start to disappear.

Also, they only disappear on program startup, I assume that might be relevant.

**Comment by tooomm** [comment]
>If you refer to one of my previous posts (I have no idea how to link to specific post on Github

You can click on the timestamp of a post, e.g. `2 days ago` to get a link to a single post

<br>
The `Edit sets` dialog should stop displaying cards from tokens.xml first.
Then we could start tracking more details down, maybe it's all good then. Even if people edit the `tokens.xml` manually (in any combination with `tk.xml`)...

**Comment by tooomm** [comment]
Is this still an issue @Nahiri?

>I do not wish to use the default Oracle tokens.xml - I'd rather use my own. I don't really play cockatrice online with random people, only with friends who have the exact same .xmls that I do, and thus we much prefer having strictly only the tokens that we use in our decks available, so that the list we have to sift through when ctrl-T'ing is only as big as it needs to be.

Besides that there is the new `related cards` feature which quickly+easily lets you create e.g. an `Energy Reserve` token off any card which creates energy just by right clicking that card...
There was a change, so that tokens that you added to your deck files are shown on default in the ctrl-T dialog for `Create tokens...`:
![untitled](https://user-images.githubusercontent.com/9874850/35826701-c8389778-0ab9-11e8-9660-ceeea62fa844.png)

<br>

About the issues with creating tokens and the `TK.xml` and `tokens.xml` file etc.
Can you give us an update if things changed with more recent versions?

**Comment by Nahiri** [comment]
> Is this still an issue @Nahiri?

I regret to say that I can't really give you an update on the issue because as there were no further replies to this topic back then, I simply defaulted to using the tokens.xml, and have never since tried to use custom tokens.

Since the 'create related card' feature was added, it also rendered my need for custom token xmls obsolete as my only issue with using the default list was the clutter.

For whatever it's worth, I did some **quick** testing just now by adding a few different custom test tokens and restarted Cockatrice a couple of times. They all seemed to stick.

**Comment by tooomm** [comment]
Thanks for coming back to us that quickly @Nahiri!

>For whatever it's worth, I did some quick testing just now by adding a few different custom test tokens and restarted Cockatrice a couple of times. They all seemed to stick.

Ok, sounds not too bad 😛 
Most likely something else changed in the background in between.

If you ever encounter the same or other problems - please let us know!
