### ISSUE TITLE
`Show tokens from this deck` just displays tokens from enabled sets

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2044]
<b>OS:</b>
Win 10 64bit

<b>Cockatrice version:</b>
277d7e2 (2016-06-30)

---

<br>

No matter if you have tokens in your deck or not. The `Create Token` dialog won't show you any.

![tokenindeck](https://cloud.githubusercontent.com/assets/9874850/16540458/d9430c30-4065-11e6-8393-a7087b73a5a4.png)

**Comment by Daenyth** [comment]
Can you attack the .cod file you were using?

That screen doesn't use the "related card" feature since it was created before that existed. You need token entries in the decklist itself. I'm not sure how well the deck editor UI exposes this.

**Comment by tooomm** [comment]
I'm not speaking of the "related card" feature and I don't expect any interaction with it here.

This is the .cod deck file that I created in Cockatrice and which I used for testing something else while stumbling upon this:
```
<?xml version="1.0" encoding="UTF-8"?>
<cockatrice_deck version="1">
    <deckname></deckname>
    <comments></comments>
    <zone name="main">
        <card number="1" price="0" name="Kiora, the Crashing Wave"/>
    </zone>
    <zone name="tokens">
        <card number="1" price="0" name="Kraken"/>
        <card number="1" price="0" name="Kiora, the Crashing Wave (emblem)"/>
    </zone>
</cockatrice_deck>
```


Also... why do we still have prices in there?

**Comment by tooomm** [comment]
Ha, I had an idea... and there we go! :+1: 

`Show token from this deck` should not care about which sets are enabled and just display **all** tokens that are present in the deck.
The problem for me was that I just had recent sets enabeld and not the set which contained the tokens that were in my deck. This behavior is perfectly fine for the card list.
But the `Create token` dialog, especially the `Show token from this deck` list needs to display all tokens, not just ones from sets that you've enabled. Otherwise you always run into this problem when you play an old deck!
(Not sure if the `Show all tokens` list should do the same... maybe you need to create a different token or help your opponent out or sth, or you gain control of a card etc.pp.)

Would it be reasonable to add a 3rd bullet point?
- Show all tokens
- Show tokens from enabled sets
- Show tokens from this deck

**Comment by Psithief** [comment]
I wouldn't like another radio button stealing vertical space from the list of tokens so much.

Of course, I'm also of the opinion that **enabled sets** should not be relevant in games anyway. Even in the Edit Sets window itself it says "Enable the sets that you want to have available in the deck editor". There's no indication anywhere that the setting would have an effect on a game.

**Comment by tooomm** [comment]
@Psithief 
>I wouldn't like another radio button stealing vertical space from the list of tokens so much.

It could be horizontal as well for sure:

| Show Tokens
|----------------------------------------------- |
|    o All    /    o Only from enabled sets     /    o Only from this deck
|    Token list...

<br>
>I'm also of the opinion that enabled sets should not be relevant in games anyway. 

100% agree. So the best might be to make the `Create Token` dialog independent from other restrictions like set selection etc.
You might want to play that legacy deck which happen to have no recent cards, or an old standard deck with a friend while you are building your new t1 deck or testing for limited with just relevant sets enabled... :+1: 

3rd pulled point (horizonally) with `Show only tokens from enabled sets` might still be valid to narrow the list down by a lot.

**Comment by ZeldaZach** [comment]
Is this still a bug? I"m not sure

**Comment by tooomm** [comment]
Yes! Running aec1ae9 (2017-03-18) right now on Win 10 64bit.
