### ISSUE TITLE
FindQt5 not provided for cmake

### ISSUE THREAD

**Issue by ZeldaZach** [Cockatrice/Cockatrice#205]
I used Homebrew to install qt4 in the past.
I uninstalled qt4, installed qt5 and tried building with cmake; Error posted below:

```
CMake Warning at CMakeLists.txt:97 (FIND_PACKAGE):
  By not providing "FindQt5Widgets.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Qt5Widgets", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5Widgets" with
  any of the following names:

    Qt5WidgetsConfig.cmake
    qt5widgets-config.cmake

  Add the installation prefix of "Qt5Widgets" to CMAKE_PREFIX_PATH or set
  "Qt5Widgets_DIR" to a directory containing one of the above files.  If
  "Qt5Widgets" provides a separate development package or SDK, be sure it has
  been installed.


CMake Error at /usr/local/Cellar/cmake/3.0.0/share/cmake/Modules/FindQt4.cmake:1316 (message):
  Found unsuitable Qt version "" from NOTFOUND, this code requires Qt 4.x
Call Stack (most recent call first):
  CMakeLists.txt:108 (FIND_PACKAGE)


-- Configuring incomplete, errors occurred!
```

**Comment by Daenyth** [comment]
I added a note to the wiki under the homebrew section

**Comment by DavidEGrayson** [comment]
I am not a Cockatrice user, but I found this thread because I encountered the same problem on my own project, and this thread was very useful.  My solution is to tell the user to run this command in the documentation:

    cmake . -DCMAKE_PREFIX_PATH=`brew --prefix qt5`

This works for me, and it's simpler than the [solution on the Cockatrice wiki](https://github.com/Cockatrice/Cockatrice/wiki/Compiling-Cockatrice#compiling-with-homebrew), which says:

    QT5_DIR=$(brew info --installed qt5 | grep "^$(brew --cellar qt5)" | cut -d' ' -f1)
    cmake .. -DWITH_SERVER=0 -DWITH_CLIENT=1 -DCMAKE_PREFIX_PATH=$QT5_DIR/

**Comment by Daenyth** [comment]
Derp, yeah `--prefix` makes sense. Please feel free to update the wiki

**Comment by CoalaJoe** [comment]
It workes when installed `qt5-default`

**Comment by mtalo** [comment]
HI My Name is Elifuraha Mtalo (mtalo@uob.ac.tz)

I am trying to configure CloudCompare using the cmake-gui on Linux - 4.13.0-43-generic - x86_64 (Ubuntu 16.04) and I am unable to clear all the issues raised by the configuration program as shown in the attachment: [Problens Configuring CloudCompare.pdf](https://github.com/Cockatrice/Cockatrice/files/2109375/Problens.Configuring.CloudCompare.pdf)

For clarity I installed Qt5.9.1 successfully under /usr/local  
After installing all the required libraries as shown here:

cmake-qt-gui installation

$ sudo apt-get install cmake-qt-gui


OpenGL Installation:

 $  sudo apt-get update
 $  sudo apt-get install freeglut3
 $  sudo apt-get install freeglut3-dev
 $  sudo apt-get install binutils-gold


Qt5.9.1 Installation

$ wget http://download.qt.io/official_releases/qt/5.9/5.9.1/qt-opensource-linux-x64-5.9.1.run
$ chmod +x qt-opensource-linux-x64-5.9.1.run
$ sudo ./qt-opensource-linux-x64-5.9.1.run


CloudCompare Installation:

$ cd CloudCompare
$ sudo cmake-gui

Configuration Issues Raised:
QT5_ROOT_PATH  NOT FOUND
At5Widgets_DIR  NOT COUND
Qt5PrintSupport_DIR  NOT FOUND
Qt5Concurrent_DIR  NOT FOUND
Qt5OpenGL_DIR    NOT FOUND
...

I browsed the Qt5.9.1  installation directory tree  and set the problematic parameters as follows:

QT5_ROOT_PATH = /usr/local/Qt5.9.1
Qt5Widgets_DIR = /usr/local/Qt5.9.1/5.9.1/gcc_64/lib/cmake/Qt5Widgets
Qt5PrintSupport_DIR = /usr/local/Qt5.9.1/5.9.1/gcc_64/lib/cmake/Qt5PrintSupport
Qt5Concurrent_DIR = /usr/local/Qt5.9.1/5.9.1/gcc_64/lib/cmake/Qt5Concurrent
Qt5OpenGL_DIR = /usr/local/Qt5.9.1/5.9.1/gcc_64/lib/cmake/Qt5OpenGL
Qt5OpenGLExtensions  = /usr/local/Qt5.9.1/5.9.1/gcc_64/lib/cmake/Qt5OpenGLExtensions
Qt5Svg_DIR = /usr/local/Qt5.9.1/5.9.1/gcc_64/lib/cmake/Qt5Svg

After this the configuration program displayed a number of options and after checking the options
the configuration raised the following exceptions:
CGAL_DIR NOT FOUND
PDAL_DIR NOT FOUND


I unchecked the CGAL and PDAL plugins options but I still get the same issues raised.

Can any one help resolve this issue?

**Comment by Daenyth** [comment]
@mtalo This bug tracker is for the Cockatrice software, please ask the CloudCompare people for support

**Comment by troyesivanyh** [comment]
CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "stg_msgs" with any
  of the following names:

    stg_msgsConfig.cmake
    stg_msgs-config.cmake

 I am a freshman to learn ros ,i don't know what means and how to solve this problem? can some graet man help me?

**Comment by troyesivanyh** [comment]
CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
Could not find a package configuration file provided by "stg_msgs" with any
of the following names:
stg_msgsConfig.cmake
stg_msgs-config.cmake
I am a freshman to learn ros ,i don't know what means and how to solve this problem? can some graet man help me? @ctrlaltca @ @DavidEGrayson

**Comment by ctrlaltca** [comment]
@troyesivanyh this is the support page for a tabletop card game. You may want to ask for support in the correct place for the software you are trying to compile.
