### ISSUE TITLE
No hosted ubuntu build for 16.04

### ISSUE THREAD

**Issue by pfirpfel** [Cockatrice/Cockatrice#2051]
<b>OS:</b>
Ubuntu 16.04 LTS

<b>Cockatrice version:</b>
Cockatrice-0.0.1-git20160703.066aff9.deb

---

<br>

The installation fails under Ubuntu 16.04 LTS due to the libprotobuf8 dependency. libprotobuf8 is not available under Ubuntu 16.04, libprotobuf9v5 is (if that is any help).

Although I was able to compile Cocaktrice myself and create my own packages, supplying working packages for the current LTS-release of Ubuntu seems important.

Console output: (Sorry for german)

```
$ sudo dpkg -i Cockatrice-0.0.1-git20160703.066aff9.deb 
Vormals nicht ausgewähltes Paket cockatrice wird gewählt.
(Lese Datenbank ... 206401 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von Cockatrice-0.0.1-git20160703.066aff9.deb ...
Entpacken von cockatrice (0.0.1~git20160703.066aff9) ...
dpkg: Abhängigkeitsprobleme verhindern Konfiguration von cockatrice:
 cockatrice hängt ab von libprotobuf8; aber:
  Paket libprotobuf8 ist nicht installiert.

dpkg: Fehler beim Bearbeiten des Paketes cockatrice (--install):
 Abhängigkeitsprobleme - verbleibt unkonfiguriert
Trigger für gnome-menus (3.13.3-6ubuntu3) werden verarbeitet ...
Trigger für desktop-file-utils (0.22-1ubuntu5) werden verarbeitet ...
Trigger für mime-support (3.59ubuntu1) werden verarbeitet ...
Trigger für hicolor-icon-theme (0.15-0ubuntu1) werden verarbeitet ...
Fehler traten auf beim Bearbeiten von:
 cockatrice
```

**Comment by ctrlaltca** [comment]
Where did you download the package from? I suppose it was stated that it was for a specific ubuntu version.
Anyway, i agree with you that we should provide a working package for Ubuntu 16.x, to avoid forcing users to compile.

**Comment by pfirpfel** [comment]
I downloaded it from bintray: https://bintray.com/cockatrice/Cockatrice/Cockatrice-git (and here as well https://cockatrice.github.io/)
I'm aware that is sasys "trusty" which is the previous LTS-release.

**Comment by Daenyth** [comment]
Precise builds should also be uploaded. I'll have to check the config.

In the mean time it's not too hard to compile it using the instructions on the wiki

**Comment by tooomm** [comment]
Travis doesn't offer 16.04 LTS builds at the moment.
<br>
> Precise builds should also be uploaded. I'll have to check the config.

You mean Xenial?
We do still upload 12.04 (Precise), but we could think about stopping that maybe... :)


<br>
Is the auto updater working for ubuntu (linux in general?) btw?

**Comment by Daenyth** [comment]
Got it, my mistake. 

We should see if travis offers 16.04 build boxes yet.

Auto updater doesn't work on linux at the moment.

**Comment by Daenyth** [comment]
Travis won't be supporting 16.04 soon, *but* we could compile with docker. I have servatrice compiling so it shouldn't be too hard to get the client compilation working.

https://github.com/travis-ci/travis-ci/issues/5821

**Comment by tooomm** [comment]
Since 16.10 is already out for a while, we might really want to look into that docker thing to get away with our incompatible version nobody is using anyway. We have the instructions in the wiki to compile on 16.04 LTS, sure...
But the target group for our Ubuntu build are inexperienced users, and they most likely run 16.04 LTS (or 16.10), not 14.04.

Did you look further into that docker option @Daenyth ?

**Comment by ZeldaZach** [comment]
I think we should look into getting a LTS build up for 16.04 onto BinTray...

**Comment by tooomm** [comment]
That would work pretty well for the moment. Can somebody spin up a vm or is running 16.04?! :shipit:

**Comment by skwerlman** [comment]
I have a GitLab instance with CI running on 16.04, if 80% guaranteed uptime is acceptable until travis gets support.

**Comment by tooomm** [comment]
We are mostly looking to get the main releases up to offer an up to date download on the page sooner than later. So we would manually upload a pre-compiled .deb file. 
To be able to offer all dev builds in the recent lts as well is just a plus. But we want it all automated again at one point, sure.

**Comment by tooomm** [comment]
@skwerlman You should definitely check out our gitter! I didn't even find a mail address to contact you...
Maybe you can help us with that .deb file compiled on 16.04. ;)

**Comment by fguilhaumon** [comment]
Hello,

just compiled it for myself. If it can help : https://github.com/fguilhaumon/cockatrice0.0.1_ubuntu16.04_deb

Cheers !

**Comment by ZeldaZach** [comment]
Travis still doesn't support 16.04+, so if we want this to be done we'll have to manually host build boxes with docker or something similar for the time being. If anyone wants to undertake this, please feel free to and let us know in the gitter chat!

**Comment by Daenyth** [comment]
Correct me if I'm wrong, but if we convert the build scripts so that the building happens in a docker container, we could build in a 16.04 docker container, no?

So this is possible if obnoxious currently

**Comment by skwerlman** [comment]
Unofficial builds for 16.04 are now available: https://github.com/Cockatrice/Cockatrice/wiki/Unofficial-Developer-Builds

**Comment by tritoch** [comment]
> Unofficial builds for 16.04 are now available: https://github.com/Cockatrice/Cockatrice/wiki/Unofficial-Developer-Builds

Can you add version numbers and maybe checksums?

**Comment by skwerlman** [comment]
Currently, the download links are setup to always point at the newest artifacts built from master, so version numbers are hard. I could make it so they point to artifacts from a specific commit, but then I'd have to update the wiki page after each commit

**Comment by tritoch** [comment]
Is there a log that can be viewed showing the commit they're using?

**Comment by skwerlman** [comment]
I'm not sure; I'll look for a way to link to the newest pipeline.

**Comment by skwerlman** [comment]
From what I can find, there's no way to link to the latest pipeline directly without knowing its ID.

However, it should be possible for me to set up a a small page which could be automatically rebuilt whenever a pipeline completes that would have all the info your looking for. I'll try and get that set up this month.

**Comment by tooomm** [comment]
Should we try to use Docker to provide at least a up-to-date basic version for Linux/Debian users?
Would be the latest LTS (16.04) from last year right now.

Travis won't get support anytime soon, they just made 14.04 the default.
I found this search link in one of the issues at travis: https://github.com/search?utf8=%E2%9C%93&q=docker%20pull%2016.04+filename%3A.travis.yml
It looks pretty easy to include a docker image actually. But never tried.
