### ISSUE TITLE
cockatrice.exe has stopped working

### ISSUE THREAD

**Issue by BeaverCleaner** [Cockatrice/Cockatrice#2055]
<b>Windows 10</b>

<b>b4dec04(2016-07-05)</b>

___
<br>

Anytime I join a game or shortly after joining a game the app crashes, I get the standard windows dialog box popup telling me "A problem caused the program to stop working correctly. Windows will close the program and notify you if a solution is available"

**Comment by ZeldaZach** [comment]
You seem to be on a test version of Cockatrice that was not released to the public yet. Can you possibly go to the log section and report what it says? Also, why don't you try the latest release to see if that helps.

**Comment by BeaverCleaner** [comment]
How do I get to the log section? I'm a first time user here and just was giving this a shot today. I downloaded the program here "https://cockatrice.github.io/"

**Comment by BeaverCleaner** [comment]
I found the old version, it works flawlessly

**Comment by ZeldaZach** [comment]
Ok, so this appears to be an issue with the new build. I"ll mark a note on that.

**Comment by Daenyth** [comment]
@BeaverCleaner I believe the website is linking to development builds, you can get the latest release from here: https://bintray.com/cockatrice/Cockatrice/Cockatrice/2016-06-30_Archivist_Madness#files

**Comment by tooomm** [comment]
We fixed our webpage. It now properly links to full releases!
