### ISSUE TITLE
Trying to import schema into Servatrice

### ISSUE THREAD

**Issue by chairborne33** [Cockatrice/Cockatrice#2056]
<b>OS:</b>
*Server 2012 R2 (e.g. "Win 7 SP1", "OS X 10.8.5", "Ubuntu 15.10" ...)*

<b>Cockatrice version:</b>
*f7d1802` (e.g. "2d53ce9 (2016-02-18)"). If you can't access this menu for any reason, please include the full filename of the installer you used.*

___
<br>

When trying to configure servatrice, at the step where I would import the tables into the database I get an error. (shown below) Can anyone help?
```
C:\Program Files\MySQL\MySQL Server 5.7\bin\mysql.exe  Ver 14.14 Distrib 5.7.13,
 for Win64 (x86_64)

Connection id:          6
Current database:
Current user:           root@localhost
SSL:                    Not in use
Using delimiter:        ;
Server version:         5.7.13-log MySQL Community Server (GPL)
Protocol version:       10
Connection:             localhost via TCP/IP
Server characterset:    utf8
Db     characterset:    utf8
Client characterset:    utf8
Conn.  characterset:    utf8
TCP port:               3306
Uptime:                 11 min 21 sec

Threads: 1  Questions: 6532  Slow queries: 0  Opens: 155  Flush tables: 1  Open
tables: 139  Queries per second avg: 9.591
--------------

ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that
corresponds to your MySQL server version for the right syntax to use near 'mysql
 -u servatrice =pfoobar servatrice < c:ervatrice.sql' at line 1
```

**Comment by ctrlaltca** [comment]
The command
```
mysql -u servatrice =pfoobar servatrice < c:ervatrice.sql
```
is meant to be run from a shell, not from inside mysql. Also, since windows' command prompt is so wonderful, you'll have to call the full path to mysql.exe:

```
c:\path\to\mysql.exe -u servatrice -pfoobar servatrice < c:\servatrice.sql
```

As an alternative, from inside the mysql prompt you can use the `source` command.

More info here: https://dev.mysql.com/doc/refman/5.7/en/mysql-batch-commands.html

**Comment by Daenyth** [comment]
Please reopen if that doesn't get you unstuck
