### ISSUE TITLE
Error message "Socket error: Connection Timed Out"

### ISSUE THREAD

**Issue by shawstafarian** [Cockatrice/Cockatrice#2057]
<b>OS:</b>
OS X 10.8.5

<b>Cockatrice version:</b>
d55e44e (2015-09-23)

___
<br>

Every time I try to connect I get an error message saying "socket error: connection timed out"

All other functionality seems fine

using host: cockatrice.woogerworks.com
Port: 4747

**Comment by Daenyth** [comment]
Can you open Terminal.app and copy/paste the result of running `nslookup cockatrice.woogerworks.com` ?

**Comment by Daenyth** [comment]
Also, are you on a managed network like a university/school/business? They may have network rules in place which are dropping the traffic.

**Comment by ctrlaltca** [comment]
> OS:
> OS X 10.8.5

I see more issues here. We can't support OSX < 10.9 because of Apple and the ay they handle updates. Sorry for that.
