### ISSUE TITLE
Constant Cockatrice Crashes

### ISSUE THREAD

**Issue by DuRiechstSoGut** [Cockatrice/Cockatrice#2058]
<b>OS:</b>
*Windows 8.1*

<b>Cockatrice version:</b>
*b4dec04 (2016-07-05)*

___
<br>

*Cockatrice crashes randomly upon joining the server, and if it doesn't then it crashes upon trying to perform any action within a game. It also sometimes crashes when attempting to host a game. Simply comes up with the windows 'Cockatrice.exe has stopped working' message.*

**Comment by ZeldaZach** [comment]
For some reason you're on a build that we haven't released to the public yet and is in beta testing. Please download the newest stable build from http://cockatrice.github.io and you should be good to go.

**Comment by Daenyth** [comment]
I believe the website is linking to our development builds instead of the releases. 

@DuRiechstSoGut you can get the latest release build here: https://bintray.com/cockatrice/Cockatrice/Cockatrice/2016-06-30_Archivist_Madness#files
