### ISSUE TITLE
Support text search with word boundaries in deck editor

### ISSUE THREAD

**Issue by helios25** [Cockatrice/Cockatrice#2059]
<b>OS:</b>
_Override this line with the exact operating system you are running! (e.g. "Win 7 SP1", "OS X 10.8.5", "Ubuntu 15.10" ...)_

<b>Cockatrice version:</b>
323fc06 (2016/02/02)

---

<br>
Would like to be able to search with word boundaries ( ie being able to seach for text containing X without getting results from all texts with x word box)

**Comment by ZeldaZach** [comment]
What do you mean?

**Comment by Nightfirecat** [comment]
I think he means being able to search for terms that appear on word boundaries, but not just within some other word.

For example, [searching for the term `red` returns many results, with most not actually using the word **"red"**](http://magiccards.info/query?q=red), whereas [a word-bounded search for `red` (think of the regex `\bred\b`) narrows that result significantly](http://magiccards.info/query?q=%22red+%22+and+%22+red%22).

**Comment by ZeldaZach** [comment]
Are we referring to searching in the deck editor?

**Comment by Nightfirecat** [comment]
I'd assume so.

**Comment by Daenyth** [comment]
Yes, this was about the deck editor

**Comment by ctrlaltca** [comment]
Poor man's solution: ` red ` (space r e d space).
I know this won't work in many cases, (first or last word in the name, punctuation, etc..)

**Comment by tooomm** [comment]
Is this still an issue with the new search in deck editor?

**Comment by ZeldaZach** [comment]
Dupe of #4108
