### ISSUE TITLE
Color filter not properly removing certain cards

### ISSUE THREAD

**Issue by scootalewis** [Cockatrice/Cockatrice#2060]
See title.

http://i.imgur.com/bHbkVNn.png

Current behaviour:

Filter "AND NOT white" plus "AND NOT" blue" does not remove blue cards with Devoid. The same is true for "AND NOT white" plus "OR NOT blue", as well as simply "AND NOT blue".

Expected behaviour:

Attempting to filter "NOT blue" in the Color category removes all cards with U in their casting cost from the list.

**Comment by skwerlman** [comment]
This seems like correct behavior to me. There should still be a way to filter by full mana cost, however.

**Comment by scootalewis** [comment]
I just checked; the same is true for white. Eldrazi Displacer is not removed from the list while all other white cards are. Eldrazi Discplacer should count as white by its mana cost; the filter does not take card efects or color identity into consideration, or so I'm told.

It seems that NOT filters will not remove Devoid cards that otherwise fit the criteria, while still removing other cards that do. I fail to see how this is correct behaviour.

**Comment by skwerlman** [comment]
It seems correct because cards with devoid have no color, so filtering by color should treat them as colorless.

That said, I do agree that `colorIdentity` should be filterable, though that would mean that Oracle would have to start saving this data, as it's currently discarded.

**Comment by Nightfirecat** [comment]
> It seems correct because cards with devoid have no color, so filtering by color should treat them as colorless.

This is correct. These cards are colorless, despite their mana costs.

**Comment by KarasuGamma** [comment]
One similar suggestion would be to improve the filter options under "mana cost", since "and/or/and not/or not" aren't particularly intuitive when applied to a value like this. It doesn't even look like "or not" does anything no matter what is entered. I realize this would cause a disjunction with the rest of the filters, but maybe switching to something based on "is" or "contains" would be more helpful.

**Comment by tooomm** [comment]
the technical terms are really not easy to use for the average user :)
