### ISSUE TITLE
No qtwebsockets on Sabayon

### ISSUE THREAD

**Issue by skwerlman** [Cockatrice/Cockatrice#2061]
<b>OS:</b>
Sabayon 16.07

<b>Cockatrice version:</b>
6a152ff

___
<br>

With the addition of websockets to Servatrice, a dependency on `qtwebsockets` was added. This package is not provided by Sabayon in the Entropy repos.

The package can be installed from Portage:
```
equo up
equo i -av dev-qt/qtcore:5 dev-qt/qtnetwork:5
emerge --sync
emerge dev-qt/qtwebsockets --nodeps
equo rescue spmsync
equo dt
```

Note that mixing Portage with Entropy is not recommended. See https://wiki.sabayon.org/?title=HOWTO:_Safely_mix_Entropy_and_Portage

(This isn't so much a bug, as a note to others who encounter problems on Sabayon)

**Comment by ctrlaltca** [comment]
This would better fit in this wiki page: https://github.com/Cockatrice/Cockatrice/wiki/Compiling-Cockatrice

**Comment by Daenyth** [comment]
@ctrlaltca we should probably make websockets conditional at compile time
so people can omit it.

**Comment by skwerlman** [comment]
`qtwebsockets` has been added to entropy in a recent update.
