### ISSUE TITLE
Cockatrice crashing upon attempting to start a game

### ISSUE THREAD

**Issue by DwarfWoot** [Cockatrice/Cockatrice#2062]
<b>OS:</b>
* Windows 10 Home *

<b>Cockatrice version:</b>
* b4dec04 (2016-07-05)*

___
<br>

Installed Cockatrice onto this computer a few days ago (new computer, fresh OS install and everything within the last few days). Today I opened it up, built a deck with no issue (other than images taking seemingly longer than usual to update), connected to the server with no issue. I joined a buddy's game, and loaded my deck, all still problem free- until the game actually started. Upon the game starting, Cockatrice stopped responding and crashed. I was able to re-open it fine, but any further attempts to connect to the server have immediately resulted in the same crash.

Not that it should matter, but I do have Cockatrice installed in this directory: C:\MtgPrograms\Cockatrice instead of the default directory, because of some past issues with some programs not running correctly in Program Files in Win10
![cock2](https://cloud.githubusercontent.com/assets/1775272/16678201/b1e69de8-4491-11e6-9496-a62c505d1db6.PNG)
![specs](https://cloud.githubusercontent.com/assets/1775272/16678202/b1ea2ae4-4491-11e6-8cba-e6e94496b2ab.PNG)

**Comment by ctrlaltca** [comment]
Please redownload a fresh copy of cockatrice from http://cockatrice.github.io/
The version you are using is an internal development version containing a known problem.
Sorry for the trouble.
