### ISSUE TITLE
ability to `attach to` from stack

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2068]
<b>OS:</b>
Win 10

<b>Cockatrice version:</b>
641fd4a (2016-07-09)

---

<br>

While playing an enchantment you put it on the stack and point to your target creature for example.
It should be possible to immediately right click and choose `Attach to card...` (while the card is on the stack) instead of putting it to the battlefield first and right click then.

![attachstack](https://cloud.githubusercontent.com/assets/9874850/16707736/7aa71440-45d9-11e6-8753-d1c6cb1b6c69.png)

**Comment by ZeldaZach** [comment]
I started preliminary working on this, you can check my branch (https://github.com/ZeldaZach/Cockatrice/tree/fix_2068). it seems to glitch out sometimes, though so I'm not 100% certain what's up.

**Comment by ZeldaZach** [comment]
This should be doable with the current protocol. I'd like this added
