### ISSUE TITLE
`Open custom image folder` broken!

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2069]
<b>OS:</b>
Win 10 (64 bit)

<b>Cockatrice version:</b>
641fd4a (2016-07-09)

---

<br>

It opens `This PC - Documents` on Windows 10. Don't know when this changed...

Can somebody confirm on same/different OS?

<br>
Edit: Still valid as of 28th february 2017 on f8623f3 (2017-02-22)

**Comment by Nightfirecat** [comment]
I'm on 11dfee4 (2016-04-15) on Windows 7 (64-bit) and not seeing this issue. Could be newer than that, or not present on Win7.

**Comment by ctrlaltca** [comment]
When you ask windows' `explorer.exe` to open a non/existing folder, it will open the user's `Document` folder instead. So the issue here is to understand why the folder that trice thinks should be used for custom images doesn't exist.
Can you try to manually browse into trice's settings folder (usually `c:\Users\tooomm\AppData\Local\Cockatrice\Cockatrice\settings\`), open the `global.ini` file with a text editor, search for the `pics` definition in the `[paths]` section and see if it actually exists and contains a subfolder named `CUSTOM`?

**Comment by tooomm** [comment]
In the `global.ini` I realized a difference. While the path was more or less correct it said
`...\\AppData\\Local\\Cockatrice\\pics` which seems fine. But Cockatrice placed the files in
`...\\AppData\\Local\\Cockatrice\\Cockatrice\\pics` instead.
I tested with adding correct path to the ini and it worked again. Even though it just points to `\pics` and not `\pics\CUSTOM`

I did a complete deletion with all settings and reinstalled the latest *Archives* full release this time.
But the same problem persists. Opening the folder from within the app doesn't work and the path in the settings are the same as before. Cockatrice also stored stuff again in 
`...\AppData\Local\Cockatrice\Cockatrice`

<br>
**Open custom sets** properly opens to `...\AppData\Local\Cockatrice\Cockatrice\customsets` though...
BUT there is no entry for `customsets path` in the `global.ini` at all.

**Comment by ctrlaltca** [comment]
> I did a complete deletion with all settings and reinstalled the latest Archives full release this time.
> But the same problem persists.

I double checked the code that initializes that value and i'm quite confident it's producing the correct value, since the same code is shared between pics and other folders (decks, replays, customsets, etc..)
I suppose that the function that translates the old settings from the registry to the ini files is getting some old, wrong value from the registry and pushing it into the ini files.

**Comment by tooomm** [comment]
The question still is why Cockatrice puts all the stuff to
`...\\AppData\\Local\\Cockatrice\\Cockatrice\` during installation.
Why is there the double Cockatrice\Cockatrice??

Settings are fine. There it says `...\\AppData\\Local\\Cockatrice\...`

**Comment by ctrlaltca** [comment]
> Why is there the double Cockatrice\Cockatrice??

The first Cockatrice is the "vendor", the second is the "program name". Eg. Servatrice stores its config in "Cockatrice\Servatrice"

> And why is there no ~customsets value in [paths] in the global.ini as well?

The "custom sets" folder has never been exposed to the user as a configurable option, and it defaults at `<cockatrice config path>/customsets`.

The sample applies for the "custom pictures" folder, that defaults at `<pics path>/CUSTOM`.


> Cockatrice it'll create a new double Cockatrice\Cockatrice subfolder

Again, this is the correct behavior.

**Comment by tooomm** [comment]
>>Cockatrice (will) create a new double Cockatrice\Cockatrice subfolder

>this is the correct behavior.
>The first Cockatrice is the "vendor", the second is the "program name". Eg. Servatrice stores its config in "Cockatrice\Servatrice"


Ok, but then the `global.ini` has to respect that too and shouldn't store paths without the second part for "program name":
```
(copied from global.ini)

[paths]
decks=C:\\Users\\xyz\\AppData\\Local\\Cockatrice\\decks
pics=C:\\Users\\xyz\\AppData\\Local\\Cockatrice\\pics


[replays]
pics=C:\\Users\\xyz\\AppData\\Local\\Cockatrice\\replays
```

Card- & Tokendatabases are fine, since they aren't stored in the subfolders:
(but which is weird again since they belong to the "programm name" Cockatrice and not the vendor!?)
```
carddatabase=C:\\Users\\xyz\\AppData\\Local\\Cockatrice\\cards.xml
tokendatabase=C:\\Users\\xyz\\AppData\\Local\\Cockatrice\\tokens.xml
```

<br>
>The "custom sets" folder has never been exposed to the user as a configurable option, and it defaults at `<cockatrice config path>/customsets`.

>The same applies for the "custom pictures" folder, that defaults at `<pics path>/CUSTOM`.

Makes sense.
`<cockatrice config path>` has to be 
...\\AppData\\Local\\Cockatrice\\Cockatrice then?

But `<pics path>` is obviously wrongly pointing to 
...\\AppData\\Local\\Cockatrice\\pics.

**Comment by ZeldaZach** [comment]
Any news on this?

**Comment by tooomm** [comment]
I updated the starting post a few days ago:
`Still valid as of 28th february 2017 on f8623f3 (2017-02-22)`

**Comment by tooomm** [comment]
New report on reddit regarding this:
https://www.reddit.com/r/Cockatrice/comments/6e642q/custom_images_folder_missing/

**Comment by JoshuaLamusga** [comment]
I changed
`customPicsPath = getSafeConfigPath("paths/custompics", picsPath + "/CUSTOM/");`
to
`customPicsPath = getSafeConfigPath("paths/pics", picsPath + "/CUSTOM/");`
twice in the settingscache file. Seems to be the solution for installations. The portable version ends up with `<cockatrice path>//redundant//slashes`, which should be `<cockatrice path>/redundant/slashes`, so replacing `//` with `/` might work. Can't test on other operating systems, but this should be enough for somebody to tackle.

**Comment by Baccanno** [comment]
I'm having some issue with path too. a double slash is added and an error occurs
![image](https://user-images.githubusercontent.com/3664080/36340453-7616a188-13dd-11e8-91f2-fbaaf0258828.png)


![image](https://user-images.githubusercontent.com/3664080/36340456-8a7fee2c-13dd-11e8-8db7-fc1926eae04d.png)
![image](https://user-images.githubusercontent.com/3664080/36340466-a75cc646-13dd-11e8-9f70-39af4349081f.png)
