### ISSUE TITLE
"connect to server" list misses ports

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2070]
<b>OS:</b>
win 10

<b>Cockatrice version:</b>
archives full release

---

<br>

On first fresh start the `Connect...` dialog looks like this:
![firststart_connect](https://cloud.githubusercontent.com/assets/9874850/16713072/1c6daefc-469c-11e6-9140-da87c4b81591.png)

If you try to use one of the pre-made servers it won't have the info on `port` and you can't use it:
![firststart_connect2](https://cloud.githubusercontent.com/assets/9874850/16713073/1e4cce88-469c-11e6-9c26-44259f5205a1.png)
<br>
We should store a default & working port number next to the host address!
(People can still adjust it if they run into trouble because they are on managed networks etc. - the server needs to allow connections on different ports first anyway - poixen doesn't for example)

for woogerworks it's: 4747
for poixen it's: 4747
for chickatrice it's: 4747

**Comment by tooomm** [comment]
@Lachee Do you still run chickatrice.net? The url just throws an error!

**Comment by Daenyth** [comment]
I'll address this in #1841

**Comment by Lachee** [comment]
Yea, I still run chickatrice.net. I need to rebuild the server as there is something wrong with the mysql. It crashes often. I need to remove the work I have on it first though, so I have been putting it off. I will begin tomorrow actually.

**Comment by tooomm** [comment]
Thanks for coming back to us @Lachee!
We thought you might have abandoned it. :)

Hope you figure it out. Otherwise we can help you maybe. Let us know and join our Gitter chat.
