### ISSUE TITLE
MoveCard_ToZone Protobuf Errors

### ISSUE THREAD

**Issue by woogerboy21** [Cockatrice/Cockatrice#2074]
<b>OS:</b>
CentOS 7 x64

<b>Cockatrice version:</b>
Servatrice 3c58003 (2016-03-22)

---

I see the following error on rare occasions in the debug log's.  It doesn't seem to crash the server but thought I would report it.

```
[libprotobuf ERROR google/protobuf/wire_format_lite.cc:532] String field 'MoveCard_ToZone.card_name' contains invalid UTF-8 data when parsing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes.
```

**Comment by ctrlaltca** [comment]
I suppose it's caused by an user using a customset file that's not correctly encoded using UTF8.

**Comment by Daenyth** [comment]
We should be able to validate that on load

**Comment by Daenyth** [comment]
Since the server seems to handle this fine I think the task is

- Cockatrice should validate the encoding of customset files.
- Cockatrice shouldn't send invalidly-encoded data via protobuf

**Comment by ZeldaZach** [comment]
I haven't seen this issue so I'm gonna close it
