### ISSUE TITLE
`clear filter` not working correctly

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2079]
The `Clear filter` button is not correctly working.

The clear button is intended to remove all restrictions on the viewable games in the room and show as many open games as possible.
Therefore it should show buddy only games as well as password protected ones.

Instead it leaves the buddy only option unchecked:
![filterreset](https://cloud.githubusercontent.com/assets/9874850/16854088/c4ce9022-4a0f-11e6-8dfd-fcfe3e641073.png)

related / introduced by https://github.com/Cockatrice/Cockatrice/pull/2049
cc @poixen

**Comment by ZeldaZach** [comment]
I'll check this out
