### ISSUE TITLE
Layout bug when pasting deck

### ISSUE THREAD

**Issue by poixen** [Cockatrice/Cockatrice#2081]
Running the latest master branch (81006d5342c95e3aa25e6bfce790875e9aebf9c7).

When opening the program, have a decklist in your clipboard and press the paste key combination (ctrl/cmd + V) without clicking on anything else.

<img width="1680" alt="screen shot 2016-07-15 at 10 42 33" src="https://cloud.githubusercontent.com/assets/2134793/16868659/32a44e2a-4a79-11e6-923a-9b9f4f8134e9.png">

Here was the deck I used. Looks like all of the items went into the `Deck Name` edit.

```
2 Abrupt Decay
2 Blood Crypt
2 Bloodstained Mire
1 Clifftop Retreat
1 Damnation
1 Elesh Norn, Grand Cenobite
4 Faithless Looting
1 Forest
1 Godless Shrine
1 Grave Titan
3 Kitchen Finks
3 Lingering Souls
2 Marsh Flats
1 Mountain
2 Murderous Cut
1 Overgrown Tomb
3 Path to Exile
1 Plains
2 Rootbound Crag
1 Sacred Foundry
2 Satyr Wayfinder
2 Siege Rhino
1 Stomping Ground
1 Sunpetal Grove
1 Swamp
4 Tarmogoyf
2 Temple Garden
2 Thoughtseize
2 Thragtusk
3 Unburial Rites
1 Vault of the Archangel
2 Wooded Foothills
1 Woodland Cemetery
1 Wurmcoil Engine
sideboard
1 Ancient Grudge
1 Anger of the Gods
1 Elesh Norn, Grand Cenobite
1 Golgari Charm
2 Inquisition of Kozilek
1 Iona, Shield of Emeria
1 Maelstrom Pulse
1 Rakdos Charm
1 Ruric Thar, the Unbowed
1 Sigarda, Host of Herons
2 Slaughter Games
2 Timely Reinforcements

```

**Comment by ctrlaltca** [comment]
Note: the big blue button shown in the image is actually the tab caption. It seems that Qt elides the text, but doesn't filter out EOL characters.

**Comment by poixen** [comment]
This works normally if you click on the deck list area and then paste.
