### ISSUE TITLE
Current Web Client does not pass any feature set information

### ISSUE THREAD

**Issue by woogerboy21** [Cockatrice/Cockatrice#2086]
If a server admin wishes to restrict access to feature set requirement the current web client passes no featureset information.  I also noticed that the current featureset list does not list the webclient or websockets as a feature set.  Not sure if that needs added or not since a server admin can restrict access to the server by config.

@Daenyth should a new label be created for the webclient stuff?

**Comment by woogerboy21** [comment]
@ctrlaltca Might be something easily added since your more familiar with the current web client functionality.

**Comment by Daenyth** [comment]
Websockets isn't really a useful feature to send.

**Comment by Daenyth** [comment]
Making the js client send the other list will be easy though

**Comment by woogerboy21** [comment]
@Daenyth  
What about a label for use on the issue's page here?

**Comment by woogerboy21** [comment]
Oh snap, this is already happening.  I just cant read JS !  Yippeee...
