### ISSUE TITLE
Current web client server message formating problems

### ISSUE THREAD

**Issue by woogerboy21** [Cockatrice/Cockatrice#2088]
Looks like the current web client pulls the server message in but doesnt format the messages similar to how the actual client does.  If the server message contains html code structure (might be others as well) the web client simply puts the data in the field and doesnt follow formating rules.

![image](https://cloud.githubusercontent.com/assets/1361287/16901267/7739e4b6-4c0c-11e6-93a0-a4b67f8c6c5a.png)

**Comment by Daenyth** [comment]
When we add that we need to make sure we don't eval it, we don't want to open an ability for a server to inject javascript into the browser unexpectedly.
