### ISSUE TITLE
No keyboard shortcut for "Move cards to graveyard"

### ISSUE THREAD

**Issue by chtref** [Cockatrice/Cockatrice#2089]
<b>OS:</b>
Win 7 SP1

<b>Cockatrice version:</b>
277d7e2 (2016-06-30)

---

<br>

There is currently no possible shortcut for moving the top X cards from the top of the library to the graveyard. This would be very useful for mechanics such as Dredge, or playing against Mill decks.

**Comment by Daenyth** [comment]
You can right click deck -> "Move cards to graveyard..." to move the top X. There's also an option for exile.

There is no keyboard shortcut for it at the moment though.

**Comment by ZeldaZach** [comment]
I added this shortcut a while back
