### ISSUE TITLE
CrashLog from Single Player Game

### ISSUE THREAD

**Issue by ZeldaZach** [Cockatrice/Cockatrice#2091]
Crashlog location: https://gist.github.com/ZeldaZach/04ff77d4e0f68ce221fe159e950b21ce

**Comment by tooomm** [comment]
We talked about it in Gitter... @poixen run into it first!

I got the same error on win once I want to start a single player game yesterday.
Running 96c501a (2016-07-05)

**Today I also realized that it crashes when I want to create a game on the server or try to join a game. 
This might be  a serious bug!**

cc: @ctrlaltca

**Comment by ctrlaltca** [comment]
```
5b21dc8cdeda64f202610352956d674fd6b9d124 is the first bad commit
commit 5b21dc8cdeda64f202610352956d674fd6b9d124
Author: Fabio Bas <ctrlaltca@gmail.com>
Date:   Thu Dec 24 17:40:49 2015 +0100

    Implementation of websockets in servatrice and test js client
```

**Comment by ctrlaltca** [comment]
> Today I also realized that it crashes when I want to create a game on the server or try to join a game.

This is not related to this ticket.

**Comment by tooomm** [comment]
>Today I also realized that it crashes when I want to create a game on the server or try to join a game.

This is working in f87f677 (2016-07-22) again.
