### ISSUE TITLE
Win64 version crashes on windows

### ISSUE THREAD

**Issue by peripheryy** [Cockatrice/Cockatrice#2092]
<b>OS:</b>
Windows 7

<b>Cockatrice version:</b>
Cockatrice-0.0.1-git20160617.bfbbedd-x86_64_qt5
(Can't open but that's the file name I installed/downloaded)

---

<br>

I've tried reinstalling a bunch of times, same problem. I just got this PC a few months ago and haven't been able to use cockatrice on it yet. The version I'm using is straight from the website.
This is what shows up when I try to open it:

http://imgur.com/a/Fh8nf

**Comment by ctrlaltca** [comment]
You are running a development version. Try to run the last stable version, get it from here: http://cockatrice.github.io/

**Comment by peripheryy** [comment]
I downloaded it from that link and it's doing the same thing :/

**Comment by Daenyth** [comment]
For a few days we had the wrong download link on the site. It's fixed now

**Comment by tooomm** [comment]
>I downloaded it from that link and it's doing the same thing :/

Did you actually test again with the link from the webpage?

**Comment by peripheryy** [comment]
Yes, I uninstalled my previous version, downloaded that from the site, and reinstalled. Same problem. Uninstalled and tried it again, same thing.

**Comment by peripheryy** [comment]
I'm clicking the windows 64 bit download on the left side.

**Comment by tooomm** [comment]
So you get the **Archivist Madness** installer in 64bit? I guess your CPU is 64bit as well?

**Comment by peripheryy** [comment]
I'm 100% sure this computer is 64 bit, but installing the 32 bit version seemed to work. Strange.

**Comment by tooomm** [comment]
Just open `System` on your win 7 machine and check for
`System / System Type`. It should have something like: "64-bit Operating Sytem, x64-based processor"

**Comment by peripheryy** [comment]
Yup, 64-bit operating system. I'd hope so, I just built this PC a few months ago.

**Comment by peripheryy** [comment]
Thank you all for your help! Apparently my PC just wants to run the 32 bit version.

**Comment by tooomm** [comment]
That's not perfect news though... Anybody has any ideas what might caused this?
Do we have problems with our 64bit build? Regarding all this reports and crashes lately...

**Comment by Daenyth** [comment]
I'm going to guess it's something about the vc redist files? @ctrlaltca ?

**Comment by ctrlaltca** [comment]
Yep, definitely some incompatible version of a dll is loaded. Maybe it's the vcredist, maybe an incompatible version of Qt (see similar issue: https://github.com/Cockatrice/Cockatrice/wiki/Troubleshooting#cockatrice-crashes-when-i-try-to-save-or-load-a-deck )

**Comment by tooomm** [comment]
Which 32bit version are you actually running now @peripheryy ?

Since you never replied to that question... maybe you somehow ran into a wrong version because your browser cached an old link.
Do you mind testing this link just to make sure?
https://bintray.com/cockatrice/Cockatrice/download_file?file_path=Cockatrice_Archivist_Madness_win64.exe
I used to run this version perfectly fine on my windows 10 (64bit)...

**Comment by peripheryy** [comment]
I tried this one and it didn't work. Same problem, auto crashes. Sorry for
the late response, haven't checked this email in a while. I'm using windows
7, btw.

**Comment by tooomm** [comment]
Did you try to test the troubleshooting suggestions from ctrlatlca?
You can also try to check this: https://github.com/Cockatrice/Cockatrice/wiki/Troubleshooting#failed-start-because-msvcpxxxdll-was-not-found
