### ISSUE TITLE
Private discussion losing focus when a game starts

### ISSUE THREAD

**Issue by chtref** [Cockatrice/Cockatrice#2093]
<b>OS:</b>
Win 7 SP1

<b>Cockatrice version:</b>
277d7e2 (2016-06-30)

___
<br>

There are probably more cases, but I will describe one:

I am chatting with Alpha in a Private Conversation while spectating a game between Alpha and Bravo.

Let's say Alpha and Bravo are currently sideboarding. Alpha is ready to start the game, but Bravo isn't. While Alpha waits, Alpha and I discuss in the Private Conversation. I type and send messages and all goes well. As I type a message to Alpha, Bravo becomes ready to start the game. The game between Alpha and Bravo starts and thus... the focus moves straight from the Private Conversation to the game between Alpha and Bravo.

The issue here is that we can start writing a message and it will cut midway in the Private Conversation, only for the other half of the message to appear in the game.

This leads to situations like this

In Private Conversation: "I don't think you should b"
In game: "e sideboarding out Bolt..."

All in all, the problem is probably because starting a game moves the focus to the game's chat input automatically, no matter which tab you're on. I wouldn't be surprised if this happened in your own room and it wasn't exclusively a problem for spectators.

Sorry for the lack of demonstrating GIF for the moment, it is fairly tough to replicate the exact situation even though it happens often.

**Comment by Daenyth** [comment]
Pretty sure there's an existing ticket for this, I'll find it later

**Comment by Daenyth** [comment]
Dup #2007
