### ISSUE TITLE
Can't find cockatrice.exe on disk after installing.

### ISSUE THREAD

**Issue by Demoneyz87** [Cockatrice/Cockatrice#2094]
<b>OS:</b>
Windows 7 64-bit

<b>Cockatrice version:</b>
Cockatrice Version 277d7e2 (2016-06-30)

___
<br>
I downloaded this program originally on 7/17/2016 and when I booted my computer today 7/18/2016 I went to open the program and it's nowhere to be found. I found the original downloaded file in the my downloads folder and re-installed the program. It is now open, and still not showing up in my installed programs or in the install location. I've double and triple checked the location to make sure I'm not missing anything.. I don't understand how it's an open program on my computer.. yet it doesn't exist? I'm including a screenshot of the exact same location open in two separate windows, one I opened through the Cockatrice Application, the other opened from my start menu. 
![cockatrice2](https://cloud.githubusercontent.com/assets/20526375/16933875/077ae6d2-4d17-11e6-880d-ba08c7ce6eb8.PNG)
![cockatrice](https://cloud.githubusercontent.com/assets/20526375/16933876/08b93968-4d17-11e6-8a0d-42496466821f.PNG)

**Comment by ZeldaZach** [comment]
Maybe it installed to `Program Files` and not the `x86

**Comment by Demoneyz87** [comment]
Tried that too, no such luck.

**Comment by ZeldaZach** [comment]
Open the command line and type `dir Cockatrice /AD /s`

**Comment by Demoneyz87** [comment]
I'll try tomorrow and update this thread with results. For now, sleep! Thanks for the reply, I'll let you know.

**Comment by Demoneyz87** [comment]
Again, it's like it's gone.. I don't understand what is happening..
![cmd](https://cloud.githubusercontent.com/assets/20526375/16969175/a6ff7684-4dd8-11e6-837a-db3348395ffa.PNG)

**Comment by Daenyth** [comment]
Is the uninstaller present? Try uninstalling it, and then rerun the installer. Double check the install location when you do that

**Comment by Demoneyz87** [comment]
I wish it was that easy.. Nope.. No uninstall. The original download file is in my downloads folder. It just doesn't make sense that it's not *really* installing. Color me very very confused.

**Comment by ctrlaltca** [comment]
While installing you should be able to see where files are being copied to:

![co](https://cloud.githubusercontent.com/assets/1631111/16985846/6e7f1598-4e83-11e6-94b8-e1a11f2134e2.png)
![cooo](https://cloud.githubusercontent.com/assets/1631111/16985845/6e7c575e-4e83-11e6-8129-96044eba8ae0.png)

**Comment by Demoneyz87** [comment]
No custom install, I paid very close attention to the install location. I'll re-install and screenshot the entire process.

**Comment by Demoneyz87** [comment]
![cockatrice dl](https://cloud.githubusercontent.com/assets/20526375/17006559/5e6fa3d8-4ea7-11e6-86df-c1c063deea06.PNG)
Here's the download... and since it's again disappeared I'm going to try installing again...
![uninstall-install](https://cloud.githubusercontent.com/assets/20526375/17006567/713e7980-4ea7-11e6-8ea9-d27c34d702fb.PNG)
double click...oh hey... it's installed...somewhere...or so it thinks...
![uninstall all](https://cloud.githubusercontent.com/assets/20526375/17006579/83e6137c-4ea7-11e6-8b58-51cf15542f2b.PNG)
uninstall previous...
![uninstalled](https://cloud.githubusercontent.com/assets/20526375/17006582/86e71e40-4ea7-11e6-9c62-6b2fdb17846f.PNG)
uninstall complete...
![agree](https://cloud.githubusercontent.com/assets/20526375/17006591/8d1add24-4ea7-11e6-91f4-baf2db295716.PNG)
agree to terms...
![components](https://cloud.githubusercontent.com/assets/20526375/17006596/9196b65c-4ea7-11e6-9658-ae615c3a2ae4.PNG)
install all components...
![programfilesx86](https://cloud.githubusercontent.com/assets/20526375/17006602/98a1bad2-4ea7-11e6-9b37-86381773810b.PNG)
Nope... no custom install here... C:\Program Files (x86)
![extracting](https://cloud.githubusercontent.com/assets/20526375/17006618/afc3013a-4ea7-11e6-9219-5a9347efb3c8.PNG)
extracting...
![where did it install](https://cloud.githubusercontent.com/assets/20526375/17006621/b34002e0-4ea7-11e6-83b2-176d901fdd8b.PNG)
installed...right...right?... *refresh* ... huh... not there... go figure.

**Comment by Demoneyz87** [comment]
Well...MFer...
![foundit](https://cloud.githubusercontent.com/assets/20526375/17006779/faf19986-4ea8-11e6-9c30-aea23eb66ff7.PNG)

**Comment by Daenyth** [comment]
Glad you got it figured out! Let us know if you need any more help with it.
