### ISSUE TITLE
Archenemy cards do not shuffle in the library

### ISSUE THREAD

**Issue by digitalmayhemx** [Cockatrice/Cockatrice#2095]
<b>OS:</b>
Win 7 SP1

<b>Cockatrice version:</b>
c095daa (2016-06-30)

___
<br>

Archenemy cards do not shuffle in the library. When given the shuffle command, the draw order remains unchanged.

**Comment by ZeldaZach** [comment]
So you have a deck with archenemy cards in it, and when you attempt to shuffle, the chat says "USER shuffled their library." and it didn't actually shuffle?

**Comment by ctrlaltca** [comment]
I suppose that he means "archenemy cards should not be shuffled in the library"?
Afaik one player has a secondary deck of "scheme" cards, but i'm not into archenemy so i could be wrong.
If so, this is just a feature request to add support for exotic game formats, similar to #478

**Comment by Daenyth** [comment]
If there's a problem it's vastly unlikely that it's as described, because the server has no idea what a card is, it just know what the name of the card is.

**Comment by tooomm** [comment]
@digitalmayhemx feel free to come back to us with more details and we'll try to help you!

**Comment by digitalmayhemx** [comment]
> So you have a deck with archenemy cards in it, and when you attempt to shuffle, the chat says "USER shuffled their library." and it didn't actually shuffle?

This is correct.
