### ISSUE TITLE
[Critical] Delete from BinTray

### ISSUE THREAD

**Issue by ZeldaZach** [Cockatrice/Cockatrice#2102]
We received a notice about overusage on bintray. Find an API call to delete prior versions in the `cockatrice-git` repo on BinTray

**Comment by tooomm** [comment]
From Gitter: [July 21, 2016 1:43 PM](https://gitter.im/Cockatrice/Cockatrice?at=5790b5589f35137e67f61d0f)

**Comment by Daenyth** [comment]
normal limits

> 1. 10GB of storage quota per account
> 2. 2TB of monthly downloads

**Comment by tooomm** [comment]
Which limit do we hit?

But generally deleting old git builds >3-6 month should be fine.
We could even delete older main releases, since we still have them here at github releases!

**Comment by ctrlaltca** [comment]
In the meanwhile, i've manually deleted all the old development builds dated before may, 2016.

**Comment by ZeldaZach** [comment]
Have we found any other way to deal with this yet?

**Comment by Daenyth** [comment]
No, we should check this again

**Comment by ctrlaltca** [comment]
Bingo:
```


Hi Cockatrice,

Your Bintray account is currently rate-limited due to overuse.

Customer Support should contact you at the earliest to remove the limits from your account. You may also contact them directly at support@jfrog.com.

Regards,
The Bintray Team

```

**Comment by ctrlaltca** [comment]
No longer using bintray, closing.

**Comment by tooomm** [comment]
I think we should delete our account there completely to minimize confusion.
https://bintray.com/cockatrice/Cockatrice

We aren't hosting builds there anyway:
![nodl](https://cloud.githubusercontent.com/assets/9874850/25949076/9b51cf8c-3656-11e7-8255-6022eac9c323.png)
https://bintray.com/cockatrice/Cockatrice/Cockatrice#files
(I guess @ctrlaltca mentioned that they somehow just show up if you're logged in as admin or someting, so bintray really hates us...)

**Comment by ctrlaltca** [comment]
> I think we should delete our account there completely to minimize confusion

I've just deleted both the project and the organization. It would have been nice to keep it open to host at least one package to provide a smooth upgrade path from old versions, but since it looks like they like to mess up with our packages, maybe it's better to just drop them.
So long, and thanks for all the fish!

**Comment by Nightfirecat** [comment]
Might be handy to write something in the Wiki about that hiccup in the upgrade process for users on older versions. I'd be happy to do that if I can find an installer for an older version which would have that issue, so I can repro myself.

**Comment by tooomm** [comment]
@Nightfirecat you can basically pick any older one from gh releases. The first thopter release should be old enough, but still not too old.

**Comment by Nightfirecat** [comment]
Done! Turns out releases before that one just caused the client to crash, and releases before the GitHub release approach open a dead link to Bintray.

https://github.com/Cockatrice/Cockatrice/wiki/Troubleshooting#cockatrice-fails-to-update
