### ISSUE TITLE
Crashing only during Games, but every time

### ISSUE THREAD

**Issue by 7onething1** [Cockatrice/Cockatrice#2104]
<b>OS:</b>
OS X 10.8.5

<b>Cockatrice version:</b>
*Put your Cockatrice version number & build date here:  "277d7e2 (2016-06-30). 

___
<br>

Here is the crash log
http://pastebin.com/LeQFS0rZ

**Comment by Daenyth** [comment]
> OS X 10.8.5

We're unable to support versions of OSX older than 10.9 because Apple removed the tools needed to make builds for it.

You can either upgrade your OS, or if you're able to install virtualbox, you can install a linux virtual machine and use cockatrice from that.
