### ISSUE TITLE
Allow just one game room type at a time

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2112]
[Idea taken from Gitter](https://gitter.im/Cockatrice/Cockatrice?at=579531ce32bd01d843ba67ab)

It's confusing to allow different types at a time, e.g. `standard, commander` or `commander, limited`.

check boxes --> radio buttons

CC: @poixen

**Comment by poixen** [comment]
This is super easy to do client side. I'm not sure if we NEED to fix this server side, that will take more time and would require everyone update. 

I can have a look into this tomorrow. 

Best Regards

**Comment by Jinxstands4Jinx** [comment]
This does make some sense as having people make modern,standard rooms makes no sense and for people like myself who only show certain formats it messes up our settings.

**Comment by Daenyth** [comment]
I'd prefer a client side only fix; this keep the proto more flexible. Another game or client might want to use those fields for something where combinations do make sense.

**Comment by tooomm** [comment]
One thing that just came to my mind... with radio buttons there needs to be one selection as default, right?
So we should make `Others` the pre-selection or introduce a new `None` field (a bit separated from the list maybe).
Once people start using it, it should remember the last selection though.

**Comment by poixen** [comment]
You can lock down the `create` button until a selection has been made and have nothing selected to start with.

**Comment by ZeldaZach** [comment]
I like that idea @poixen

**Comment by ctrlaltca** [comment]
fixed by #2115

**Comment by tritoch** [comment]
I'd like to see this be server managed.  There is a use case for allowing game with multiple types.  Pauper cube is Pauper & Limited and should be able to be advertised to players of both.

**Comment by Daenyth** [comment]
There's no need to have it be server-managed. The motivating reason for this is streamlining the UI. If we can make a better UI for the games list I'd be very happy to re-add this. I used multi-format stuff in the same way you mention.
