### ISSUE TITLE
Interface keeps freezing.

### ISSUE THREAD

**Issue by SinfireTitan** [Cockatrice/Cockatrice#2113]
<b>OS:</b>
Windows 7 64-bit Service Pack 1

<b>Cockatrice version:</b>
d55e44e (2015/09/23)

___
<br>

The problem started sometime after downloading Eldritch Moon to the Oracle. Repeatedly, Cockatrice will stop allowing me to interact with it as if the program were frozen, but the program is most certainly not frozen (the program still changes images and allows me to highlight the battlefield).
When this happens in the Deck Editor it can be temporarily solved by minimizing the window and restoring it, but the problem will immediately occur again if I change text boxes, IE: while editing a deck I was forced to minimize the window in order to type into the filter, and then forced to do so again to go back to the search window, and again when I removed an extra card from the deck.
During an actual game, however, it just can't be resolved regardless of my actions. I have no clue what is wrong with it, but I can't even complete a full mulligan before the glitch occurs.

**Comment by tooomm** [comment]
Is there some interesting output in the debug log?
`Help --> View Debug Log`

Oh I see your version is pretty old... maybe you want to update your client first?
(otherwise you don't have a debug log anyway, hehe)
https://cockatrice.github.io/

**Comment by Daenyth** [comment]
Good catch on the version; we definitely should check whether this remains a problem with recent versions.

**Comment by tooomm** [comment]
Let us know in case this problem still persists!
