### ISSUE TITLE
server

### ISSUE THREAD

**Issue by darksorrows** [Cockatrice/Cockatrice#2116]
<b>OS:</b>
*Override this line with the exact operating system you are running! (e.g. "Win 7 SP1", "OS X 10.8.5", "Ubuntu 15.10" ...)*

<b>Cockatrice version:</b>
*Put your Cockatrice version number & build date here! You find them inside the app: `Help` --> `About Cockatrice` (e.g. "2d53ce9 (2016-02-18)"). If you can't access this menu for any reason, please include the full filename of the installer you used.*

___im having issues connecting to the server on cockatrice  but can sign on in the web client any help would be appreciated
<br>

*Explain your Issue/Request/Suggestion in detail here!*

**Comment by Daenyth** [comment]
Can you include your OS and cockatrice version as the template suggested? Also any specific errors messages that you might be seeing, screenshots, etc.

**Comment by darksorrows** [comment]
os is windows 10 version: 277d7e2 and the error says socket error: the remote host closed the connection

**Comment by woogerboy21** [comment]
What port by chance are you using?  And do you have any firewall or anti malware software running?  And are you on any type of school or business network or is this from your home network?

Thanks

**Comment by darksorrows** [comment]
home network no firewall or malware and port is 4748

**Comment by woogerboy21** [comment]
the regular client should use either port 4747 or 443, the webclient uses port 4748.  If your putting port 4748 in the pc client replace the number with either 4747 or 443 and try again.

**Comment by darksorrows** [comment]
thanks it works now
