### ISSUE TITLE
Ignore list glitching

### ISSUE THREAD

**Issue by Jinxstands4Jinx** [Cockatrice/Cockatrice#2121]
This may be an isolated incident but i have noticed 4 times now that users I have on my ignore list refresh for some reason, example. I had a user on my ignore list for a very long time, long as in several months and without explanation I find myself in a game with this exact same person, they have somehow come off my ignore. I chalked up the first time to maybe I unignored as I'Il do that at times, but after the 5th or so I just wonder if there would be a method or a reason why this would happen? I would state names but that seems extra rude.

**Comment by Daenyth** [comment]
I have no idea what might cause this. @woogerboy21 maybe some weird cleanup script?

**Comment by Jinxstands4Jinx** [comment]
I know this is Completely off topic here, but i just now noticed and found the Wiki and saw that my Primer for new players was on there and wanted to give a Shoutout to Toomm For that as it looks Great. I recognize my writing :)

**Comment by tooomm** [comment]
You mean this? https://github.com/Cockatrice/Cockatrice/wiki/One-minute-game-guide
You also find it on our main page as `Quickstart Guide for Gaming`: https://cockatrice.github.io/ 

Thanks for the input and write up on this! ;)

**Comment by Jinxstands4Jinx** [comment]
Yeah tooomm, Good to see my writing put to use. :)  I also did not mind that you took the credit ;)  but alas I have noticed this ignoring issue. Not sure how it is happening. I think it's a refresh as I only notice that its users I have ignored ages ago and more or less forgotten why I ignored them in the 1st place

**Comment by tooomm** [comment]
OT:
Well, it wasn't me actually. I just added one or two things. :P
https://github.com/Cockatrice/Cockatrice/issues/2040#issuecomment-229872264

**Comment by woogerboy21** [comment]
@Daenyth There is no cleanup script for ignore lists on the woogerworks server.  I do have flushing of replays due to storage limitations as well as cleanup of registered inactive accounts after so many days.

**Comment by woogerboy21** [comment]
If I could get some actual username examples such as playerA is ignoring playerB for users that experience what is described here I could try and see if there is anything odd in the DB occurring.
