### ISSUE TITLE
Spectating options

### ISSUE THREAD

**Issue by Jinxstands4Jinx** [Cockatrice/Cockatrice#2124]
Would it be hard to put an extra button somewhere 2 actually, For players in a game and for spectators out of the game. Let me explain both.

Players in game would get a button "Move to spectator" and if Specs are allowed in the room they would slide right over.

Spectators would get the same button but it would be "Move to game" and if there was an empty chair they could slide to game.   

These buttons would be helpful when people are testing in groups, or when a person dies but wants to watch next game while they improve deck. When you try to leave and come back sometimes the host has to "kick" people who enter oddly or who inadvertently steal seats.  Also for specs to come over faster when they were watching and the game has ended but a new one is starting.

**Comment by tooomm** [comment]
Instead of buttons, it could also be a right click option on your name in the `Player List`

**Comment by Daenyth** [comment]
I like that a bit better

**Comment by Jinxstands4Jinx** [comment]
Options are perfectly fine I just did not think of it that way.

**Comment by ZeldaZach** [comment]
Not really worth the effort of changing the game logic to support this when a player can leave and rejoin on their own
