### ISSUE TITLE
Clearing the chat

### ISSUE THREAD

**Issue by Jinxstands4Jinx** [Cockatrice/Cockatrice#2127]
I know we can clear the main chat. Is there a Reason we cannot clear in game chat?

**Comment by Daenyth** [comment]
You'd lose the ability to see what happened before in the game. I don't
really see much purpose to it honestly

**Comment by Jinxstands4Jinx** [comment]
Well I brought it up because I was involved in a EDH Kingdoms game and the Host put his entire deck in the graveyard so that they could shuffle the lands and pass them out fairly.  But it listed his deck in the chat... It would have been convenient to just erase the chat. instead of everyone flooding the chat to get rid of it.

**Comment by Nightfirecat** [comment]
Perhaps this would add blank space enough to clear your view of the chat, rather than removing the previous game chat entries?

**Comment by Jinxstands4Jinx** [comment]
it would be like it is in the main room, you could just push f12 to clear the chat. The replay would be unaffected but your chat would be cleared. It was a thought.

**Comment by ZeldaZach** [comment]
I personally don't agree with a feature like this as we should keep game chats fully viewable in case of dispute. Any other opinions?
