### ISSUE TITLE
Possibility to hide specific games on user choice

### ISSUE THREAD

**Issue by LethalPigeon7** [Cockatrice/Cockatrice#2128]
<b>OS:</b>
Win 7 SP1
<b>Cockatrice version:</b>
Version 1c78598 (2016-08-09)

---

I've been pondering how to clean the main with complicated additions such as timing out and auto-closing rooms, and I've never thought of this as the obvious and (hopefully) simple solution.
Ideally one would right click on a room in main and hide it. Or have a "Hide" button somewhere in the room-related actions, on the right to "Join as spectator" for example. This would mostly be useful for hiding old rooms, but could just be used to filter out rooms which don't appeal to me for any reason.
This is the polar opposite of a pressing matter, just something I'd appreciate feedback on.

**Comment by Jinxstands4Jinx** [comment]
well there are options to filter rooms so you only see certain formats, So I would guess this would be an extension on that and I would be for it, i hate seeing so many buddy rooms, and password protected rooms.

**Comment by LethalPigeon7** [comment]
There's actually filters for both of those. It's mostly a dead rooms fix with additional user freedom because murica.

**Comment by Jinxstands4Jinx** [comment]
hmm, was unaware.

**Comment by ZeldaZach** [comment]
a potential (but I disagree with) filter could be "Filter by Time" so older rooms are auto filtered out.

**Comment by tooomm** [comment]
Auto closing rooms is already tracked: https://github.com/Cockatrice/Cockatrice/issues/783
Filtering them out (client side) could be done the same as with players: `max. game age: xy`

**Comment by LethalPigeon7** [comment]
Would this be difficult to implement? The added bonus of giving control to the user so he can filter out new rooms he doesn't care for seems worth a bit of work, but not a lot.

**Comment by Daenyth** [comment]
I think this is relatively easy.

@poixen I think you're most familiar with this code area currently. Does this sound reasonable to you?
- User right clicks on a game, selects 'ignore this game'
- app records the game_id into a QSet and applies a filter to the game list model with that set.
- When the app gets a game closed event for that game id remove the id from the filter list so it doesn't grow.
- When fully refreshing the game list (does this happen?) also prune ignored game_ids from the ignore set.
- on launch the set is empty.

**Comment by ray73neo** [comment]
I would like to add to this the ability to hide "buddies only" games. I don't like seeing games that I am unable to join (similar to hiding passworded games).

**Comment by poixen** [comment]
@ray73neo I added that feature. It should be in the next release.

**Comment by tooomm** [comment]
>User right clicks on a game, selects 'ignore this game'

Wouldn't that just temporary help you with a single specific game?
The approach should be more broad and general, like with a real filter.

If you want to avoid old games, you want to avoid all old games. (--> "room age" filter)

People will hide games on mistake as well and can't undo it easily etc. pp.

**Comment by ZeldaZach** [comment]
This has been solved by our advanced filtering
