### ISSUE TITLE
Smoother sideboard <-> main movement

### ISSUE THREAD

**Issue by LethalPigeon7** [Cockatrice/Cockatrice#2129]
<b>OS:</b>
Win 7 SP1
<b>Cockatrice version:</b>
1c78598 (2016-08-09)
___
When I press "S" in the deck editor to move a card to or from the sideboard, the deckbuilder highlights the card in the new area (the deck when moving from the sideboard and vice versa).
This has been massively annoying any time I've ever wanted to use it (mostly constructed deckbuilding), and has lately been especially painful when I started building sealed decks in cockatrice. When I want to move multiple copies of a card I have to press S, scroll down to where I was, click the card and repeat for every copy. Same goes for single copies of multiple cards. 
Ideally when a card is moved from one part to the other, the original location would stay highlighted, and should all copies be used the card above/below the original card would be highlighted now.

**Comment by tooomm** [comment]
You should name your proposal/enhancement... not just the issue. :P

**Comment by LethalPigeon7** [comment]
That's what the last line is... Have you read the post?

**Comment by tooomm** [comment]
Well, you edited your post... so. ;)
I'm pretty sure I read that for the first time. Doesn't matter anyway. ^^
<br>
>Ideally when a card is moved from one part to the other, the original location would stay highlighted, and **should all copies be used** the card above/below the original card would be highlighted now.

Even then you think it's best to not follow the card?
The first makes sense I would say. :+1:

**Comment by LethalPigeon7** [comment]
Oh, you commented 4 hours after I posted and I was pretty sure I edited it within minutes of posting it. Anyway yes, even then, because I still genuenly can not fathom a situation where you finish moving one card from one zone to another and want to go something in the new zone. Generally you want to side in/out other cards. Or are done with using the function.
I may be overlooking something, because I've yet to come up with a counter-argument, so I'm very much looking for feedback.

**Comment by tooomm** [comment]
>EDIT: I guess you could side in your cards for game 2 and then want to side cards out without using the mouse, but having to click once or press up 10 more cards in that situation seems like an opurtunity cost worth taking, even when I don't consider how rare I think it is.

We are talking about deck editor, right? You wouldn't use that for sideboarding between games.
While playing a game (in a game room) you can't sideboard while using shortcuts or mouse clicks - you need to drag and drop cards between "zones". At least that's the only way it works for me on windows.

But the first seems more and more valid:
In the deck list view in deck editor while changing cards zones, the focus shouldn't follow individual cards. But stay in the "card group" as long as there are cards left.
With the last card the focus should switch to the **next card in the list** in my opinion. Following the last card seems bad. Using the former card in the list is unusual as well.
