### ISSUE TITLE
Pics Not Appearing on New decks

### ISSUE THREAD

**Issue by tobenamed** [Cockatrice/Cockatrice#2130]
<b>OS:</b>
Win 7 SP1
<b>Cockatrice version:</b>
Version 277d7e2(2016-06-30)
___
<br>

My card data base is not updating its pictures, when i create a new deck none of the images show up, but the description card, type, etc. all are still known.  The decks i have previously made still have all of thier images for their cards.  I cannot make any new decs due to this problem.  Can u please try to fix this problem. I really enjoy using this program.

**Comment by Grelwing** [comment]
I don't have a fix, but I am having the same issue. I tried reinstalling the client and re-downloading card images. Now even old decks fail to display card images. I posted over on the subreddit -- and was going to post a ticket here; but it's probably a better idea to just piggyback on yours to help find a solution.

**Comment by tooomm** [comment]
Gatherer is down at the moment, so you can't download new images not already present in your picture folder...
Try again in a few hours or tomorrow and double check if you can access http://gatherer.wizards.com/
You should also check and post your error log: `Help --> View debug log`
