### ISSUE TITLE
keep getting a socket error (woogerworks)

### ISSUE THREAD

**Issue by Grimshade** [Cockatrice/Cockatrice#2131]
ive tried everything including updating my client to the latest version and using different server addresses

**Comment by tooomm** [comment]
**Please don't mess around with your postings!**
We have a template for a reason, please use it and provide information accordingly and in full detail.
There is no way to provide any help while we're just speculating...
<br>
for example:
>latest version

Which?

>different server addresses

Which?

...

**Comment by Grimshade** [comment]
ok if you must know i reinstalled to version 277d7e2  and the adreses i was trying were both cockatrice.woogerworks.info and cockatrice.woogerworks.com

**Comment by ctrlaltca** [comment]
Try `cockatrice.woogerworks.com`, ensure the port number is 4747. If it still doesn't work, try to use `62.210.10.127` as the server address, still port 4747.

**Comment by Grimshade** [comment]
ok that seems to have resolved the issue thanks man

**Comment by ctrlaltca** [comment]
So the issue was the port number being incorrect? Ws it empty or set to a wrong value?

**Comment by Grimshade** [comment]
It was not the port number just using that up seemed to allow me to connect

**Comment by ctrlaltca** [comment]
Ok, thank you @Grimshade!
@woogerboy21 possibly some DNS issues?

**Comment by woogerboy21** [comment]
I checked the domain info on the hosting company and the address's appear
correct on there side. I havent heard of anyone else reporting the issue
but Ill keep an eye out.
Thanks

**Comment by tooomm** [comment]
Thanks for reporting back @Grimshade!
