### ISSUE TITLE
No Menu on Ubuntu Trusty 14.04

### ISSUE THREAD

**Issue by jeffmendoza** [Cockatrice/Cockatrice#2133]
<b>OS:</b>
Ubuntu Trusty 14.04

<b>Cockatrice version:</b>
Cockatrice_Archivist_Madness_trusty.deb
ii  cockatrice                                      0.0.1~git20160630.277d7e2    amd64                        Cockatrice
___
<br>

Tried in GNOME and Cinnamon, can't see the menu:
![cockatrice-no-menu](https://cloud.githubusercontent.com/assets/771387/17761476/483ee51c-64bc-11e6-82c6-ff2e32e8612f.png)

**Comment by ctrlaltca** [comment]
I suppose this is a duplicate of #1783. Try to follow the advice on the first comment:

> I'm not sure if this is related, but if you have a package named ```appmenu-qt5```, i'd try removing it.
> It's a package that tried to make qt5 apps feel "native" by integrating them in the unity's menubar, but it's known to be broken.

**Comment by jeffmendoza** [comment]
`sudo apt-get remove appmenu-qt5` Worked, thanks so much. It would be good to get that here https://github.com/Cockatrice/Cockatrice/wiki/Troubleshooting for those of us on old 14.04

**Comment by jeffmendoza** [comment]
Just updated the wiki

**Comment by Daenyth** [comment]
Thank you for the help!
