### ISSUE TITLE
As a server operator I would like user registration name filtering

### ISSUE THREAD

**Issue by poixen** [Cockatrice/Cockatrice#2135]
## Description
As a server operator I would like to prevent the use of certain words in username by adding a filter. This filter can include words or special characters. This will prevent the creation of usernames not deemed appropriate for the server operator.

## Notes
A similar feature is already in place. Usernames can not have special chars that have been disallowed in the server conf.

**Comment by LethalPigeon7** [comment]
Cockatrice: Club Penguin edition.

**Comment by Nightfirecat** [comment]
On the contrary, if I were a server op, I'd appreciate such a feature, even if I didn't end up using it.

**Comment by Daenyth** [comment]
@LethalPigeon7 If you have objections or concerns about the feature on its own merits please bring them up. I know you've mentioned that this won't solve a problem totally. That's fine. It doesn't have to. What it *can* do is give operators more flexibility.

Otherwise I'd appreciate it if you refrain from comments that don't add substance to the conversation.

**Comment by LethalPigeon7** [comment]
Good point, albeit a strong move in the direction of that program (neutral statement), simply pointing that out is somewhat pointless. My bad.

**Comment by poixen** [comment]
This is not a constructive feature?

**Comment by LethalPigeon7** [comment]
Not "simply pointing out that it is somewhat pointless and not constrictive".
"simply pointing out that it is reminiscent of club penguin is pointless and not constructive"

**Comment by Daenyth** [comment]
I don't see it as pointless; for woogerworks, I think it's enough that usernames with "admin" are restricted. We know from experience that many users don't understand the shirts, and there's potential for confusion by malicious users. I can also see it being useful for public servers in the future who might make more of an effort to be kid-friendly. We all know it's no substitute for moderation but it's very low hanging fruit and doesn't really harm anything.

**Comment by Daenyth** [comment]
Aha, I misunderstood your comment.

**Comment by wincinderith** [comment]
I'm working on the feature here: #2200
