### ISSUE TITLE
File could not be saved to /Applications/Cockatrice.app

### ISSUE THREAD

**Issue by BladeMasta220** [Cockatrice/Cockatrice#2136]
<b>OS:</b>
OS X 10.9.5

newest version

---

<br>

Whenever I try to update the card database for cockatrice using oracle it says what the title of the ticket says. It won't let me update the card database.

**Comment by Daenyth** [comment]
Can you post what's in Help > View Debug Log?

Try changing your settings so that your card database location is in another location - Documents, or maybe `~/Library/Application Support/Cockatrice/Cockatrice`

**Comment by ctrlaltca** [comment]
We should add some buttons to reset the user-modifiable paths to their default.

**Comment by ZeldaZach** [comment]
I haven't been able to reproduce this. @BladeMasta220 Is this still an issue for you?
