### ISSUE TITLE
Error connection refused

### ISSUE THREAD

**Issue by philipcliang** [Cockatrice/Cockatrice#2137]
<b>OS:</b>
Windows 10
<b>Cockatrice version:</b>
323fc06

___
<br>

I am getting error connection refused when I try to log in.

**Comment by Daenyth** [comment]
I'm assuming you're connecting to the woogerworks server right now; it's down at the moment. Try again later.

**Comment by Daenyth** [comment]
You can get updates for them here: https://twitter.com/@woogerworks
