### ISSUE TITLE
Ubuntu : error while loading shared libraries: libprotobuf.so.8

### ISSUE THREAD

**Issue by AnthonyJacob** [Cockatrice/Cockatrice#2140]
<b>OS:</b>
*Ubuntu 16.04.1 LTS \n \l*

<b>Cockatrice version:</b>
*Cockatrice_Archivist_Madness_trusty.deb*

___
<br>

I downloaded the .deb file, installed it trough shell `dpkg -f Cockatrice_Archivist_Madness_trusty.deb`. Then I ran the `Cockatrice Oracle downloader` followed the installation steps. Finally I ran command `cockatrice` in shell but I have got following error: <br><br>

> **cockatrice: error while loading shared libraries: libprotobuf.so.8: cannot open shared object file: No such file or directory**

**Comment by ctrlaltca** [comment]
If you force the installation of a package using `dpkg -f`, it will install even if not all its dependencies are satisfied. In your case you are installing a package made for a previous Ubuntu version, and the missing library doesn't exists anymore in the newer Ubuntu, bcause it has been renamed (to be precise, renumbered).

I'm afraid that you'll have to compile by hand using the [instructions](https://github.com/Cockatrice/Cockatrice/wiki/Compiling-Cockatrice#ubuntu-16xx)

**Comment by AnthonyJacob** [comment]
Thanks for such a fast reply! Problem solved.

**Comment by ctrlaltca** [comment]
You are welcome, and sorry if we are not able to provide a precompiled package (yet)
