### ISSUE TITLE
i cant enter in cockatrice since friday. why?? what can i do??

### ISSUE THREAD

**Issue by VforVraki** [Cockatrice/Cockatrice#2141]
<b>OS:</b>
*Override this line with the exact operating system you are running! (e.g. "Win 7 SP1", "OS X 10.8.5", "Ubuntu 15.10" ...)*

<b>Cockatrice version:</b>
*Put your Cockatrice version number & build date here! You find them inside the app: `Help` --> `About Cockatrice` (e.g. "2d53ce9 (2016-02-18)"). If you can't access this menu for any reason, please include the full filename of the installer you used.*

___
<br>

*Explain your Issue/Request/Suggestion in detail here!*

**Comment by ctrlaltca** [comment]
Fill the field with the information required and explain your problem in detail, so that we can understand what's going on and assist you in fixing the problem.

**Comment by Daenyth** [comment]
If you're having problems connecting to a specific server, please use that server's website to contact the administrator
