### ISSUE TITLE
Bug with "new set found" dialogue.

### ISSUE THREAD

**Issue by Psithief** [Cockatrice/Cockatrice#2144]
Version 277d7e2 (June 2016)
## Steps to reproduce
1. Update tokens.xml
2. Open Cockatrice
3. Cockatrice prompts "New set CN2 found, do you want to load"
4. Click yes.
5. Add a set filter in the Deck Editor named 'CN2'
## Result

Only cards that are already in existing sets are shown. The 'Sets' column does not include 'CN2'.
In this example, "Beast, Dragon, Construct, Soldier, Spirit, Zombie and Insect" were all shown because they are not new to the game.
## Expected result

Show all the new cards from the set.

This does not persist after closing and re-opening Cockatrice.

**Comment by tooomm** [comment]
So the issue is that that the `´New set(s) found` dialog (more precisely its `Yes` button) doesn't enable the set as expected?

**Comment by Psithief** [comment]
I haven't actually checked to see what happens if I said 'No' to that dialog. I don't get that many chances to check.

**Comment by ZeldaZach** [comment]
I fixed this a while ago with spoilers
