### ISSUE TITLE
Cannot get Cockatrice to compile

### ISSUE THREAD

**Issue by joshuabengal** [Cockatrice/Cockatrice#2148]
<b>OS:</b>
Windows 7SP1 clean install on a Virtual Machine
___
<br>

So I've been struggling for a few days with this and hit a roadblock. I had previously gotten cockatrice to compile under the old VS 2013 setup. But this new setup does not want to cooperate. 

I have everything done except the final build command. I execute

msbuild C:\Cockatrice\build\PACKAGE.vcxproj /p:Configuration=Release..

And get the following error:

"C:\Cockatrice\build\PACKAGE.vcxproj" (default target) (1) ->
"C:\Cockatrice\build\ZERO_CHECK.vcxproj" (default target) (2) ->
(PlatformPrepareForBuild target) ->
  C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targe
ts(55,5): error MSB8020: The build tools for Visual Studio 2010 (Platform Tools
et = 'v100') cannot be found. To build using the v100 build tools, please insta
ll Visual Studio 2010 build tools.  Alternatively, you may upgrade to the curre
nt Visual Studio tools by selecting the Project menu or right-click the solutio
n, and then selecting "Retarget solution". [C:\Cockatrice\build\ZERO_CHECK.vcxp
roj]

I tried retargeting both those individual solutions and the entire solution, but the only option I have to retarget is to 8.1. I downloaded and installed the Windows 7 SDK, and I still only have 8.1 as a retarget option. And retargeting to 8.1 doesnt seem to do anything, I get the same errors. 

Any ideas?

Thanks

**Comment by ctrlaltca** [comment]
Check my comment: https://github.com/Cockatrice/Cockatrice/issues/2147#issuecomment-242844487

**Comment by joshuabengal** [comment]
I commented out that line, still won't compile, throws same error. 

I found a site saying you needed to make sure "Common Tools for Visual C++ 2015" was checked on the VS Install, I checked and mine wasn't, so I checked it, installed those, rebooted, and still, no dice. build crashes with the same error

Any other ideas?

**Comment by ctrlaltca** [comment]
> error MSB8020: The build tools for Visual Studio 2010 (Platform Tools
> et = 'v100') cannot be found. To build using the v100 build tools, please insta
> ll Visual Studio 2010 build tools. Alternatively, you may upgrade to the curre
> nt Visual Studio tools by selecting the Project menu or right-click the solutio
> n, and then selecting "Retarget solution"

Googling up this error brought up [this](http://stackoverflow.com/questions/33380128/visual-studio-2015-command-line-retarget-solution) and [this](http://stackoverflow.com/questions/19801072/the-builds-tools-for-v120-platform-toolset-v120-cannot-be-found).
If i understand correctly, cmake created project files for the wrong version of MSVC. Why? Probably because it found more than a version installed, or because the version you are using doesn't support MSVC2015 yet.
You need to retarget the project to use MSVC2015

> I tried retargeting both those individual solutions and the entire solution, but the only option I have to retarget is to 8.1

This makes no sense: windows versions are not what the error is talking about. When you retarget a project you can choose between different MSVC toolset versions, line v110, v120, etc.. 
Learn how to change the platform toolset here: https://msdn.microsoft.com/en-us/library/ff770576.aspx (around the end of the page)

> I downloaded and installed the Windows 7 SDK, and I still only have 8.1 as a retarget option

The SDK is not needed to compile Cockatrice.

**Comment by joshuabengal** [comment]
I followed that link, and checked the platform toolset for every project in the solution. All were set to Visual Studio 2015 (v14). I tried to build and got the exact same error. 

I only have one version of Visual Studio installed (Community 2015), and the machine is a fresh Win 7 install. Any other ideas?

**Comment by joshuabengal** [comment]
I tried uninstalling the latest version of CMake and installing 3.1, the lowest version that will still work with the solution, but no dice. Same build error

**Comment by joshuabengal** [comment]
I also tried the "Build via GUI" instructions since they contain an extra step that seemd to be related to versioning, and those instructions don't even get past the cmake install

I am giving in one more go, I set up a brand new VM, brand new OS install, I'm installing all the tools fresh right now, if this doesn't work then I'm calling it un-doable. If another dev on the project could go through a new build environment setup and get it working and them update the instructions so they are accurate, it would be much appreciated

**Comment by Daenyth** [comment]
It's certainly possible to compile on Windows otherwise our appveyor builds
wouldn't work. Can you try manually running the commands that script uses?

**Comment by woogerboy21** [comment]
Sounds to me like you passed the wrong version of your VC in your cmake command.  What is the version you passed when you were running cmake?

**Comment by joshuabengal** [comment]
Well, I managed some success. I followed the instructions to build via the GUI, and combining what I learned from the previous exercise with the additional protobuf conversion step, I eventually got it to build. However, that documentation needs to be updated as well, it does not reference the need to select VC++ on the Visual Studio install, it links to an old version of cMake, and it intimates that you can build the project without installing MySQL, which is incorrect. 

I'd be happy to update the directions, but when I click on the Edit button it brings up the original page in the editor, not the GUI page. Any tips on how to edit the GUI instructions?

**Comment by Daenyth** [comment]
I'm not sure what you mean. What do you mean by original page and GUI page?

**Comment by joshuabengal** [comment]
On the page "Compiling Cockatrice" (https://github.com/Cockatrice/Cockatrice/wiki/Compiling-Cockatrice) I can click the Edit button and edit the document. Under the windows sentence, there is a link (Use **this** guide if you wish to compile from source using the IDE (GUI).) that when clicked takes you to a different set of instructions at https://github.com/Cockatrice/Cockatrice/wiki/Compiling-Cockatrice/e4d3d6217cd3683c0e28ff2adbae792af24a630f#on-windows. If I click the edit button on that page, however, it does not load that page in the editor, it loads the original page (https://github.com/Cockatrice/Cockatrice/wiki/Compiling-Cockatrice). So I cannot update the directions on the GUI instruction page.

**Comment by tooomm** [comment]
>I'm not sure what you mean. What do you mean by original page and GUI page?

see: https://github.com/Cockatrice/Cockatrice/issues/2147#issuecomment-243417555

**Comment by joshuabengal** [comment]
Well it seems my celebration was short lived I'm trying to compile some alternate versions and now it fails. It seems VC can't see my MySQL install since it keeps crashing on libMySql,dll and LibPQ.dll. Any ideas how to fix that?

**Comment by ctrlaltca** [comment]
> VC can't see my MySQL install

I'm perplexed, because we don't link to mysql at all. We just link to Qt's database abstraction library, and it contains a mysql-specific plugin that loads mysql's client library dinamically at runtime. The needed library is present in the mysql/mariadb connector package.

> since it keeps crashing on libMySql,dll and LibPQ.dll. Any ideas how to fix that?

Do you really mean it's crashing or is it just throwing an error? Then, what's the precise error message?
I suppose that compilation went well, and it's now failing at building the "package" target because it's looking for files that are not available on the $PATH.

Building software on Windows is such a pain nowadays...

**Comment by joshuabengal** [comment]
HEre's the output of the failed build. This is with MariaDB, and latest version of code from Git. I can compile prootbuf fine. and cmake completes with no errors. When I run Visual Studio, set the output to Release, and Build PACKAGE, it runs for a while, then generates this: 

------ Build started: Project: PACKAGE, Configuration: Release Win32 ------
  CPack: Create package using NSIS
  CPack: Install projects
  CPack: - Install project: Cockatrice
EXEC : warning : target 'libmysql.dll' is not absolute...
EXEC : warning : target 'libmysql.dll' does not exist...
  CMake Error at C:/Program Files/CMake/share/cmake-3.6/Modules/GetPrerequisites.cmake:818 (message):
    C:/Program Files/Microsoft Visual Studio 14.0/VC/bin/dumpbin.exe failed:
    1181



    Microsoft (R) COFF/PE Dumper Version 14.00.24213.1

    Copyright (C) Microsoft Corporation.  All rights reserved.





    Dump of file libmysql.dll

LINK : fatal error LNK1181: cannot open input file 'libmysql.dll'

  Call Stack (most recent call first):
    C:/Program Files/CMake/share/cmake-3.6/Modules/GetPrerequisites.cmake:945 (get_prerequisites)
    C:/Program Files/CMake/share/cmake-3.6/Modules/BundleUtilities.cmake:585 (get_prerequisites)
    C:/Program Files/CMake/share/cmake-3.6/Modules/BundleUtilities.cmake:858 (get_bundle_keys)
    C:/Cockatrice/build/servatrice/cmake_install.cmake:68 (fixup_bundle)
    C:/Cockatrice/build/cmake_install.cmake:33 (include)


EXEC : CPack error : Error when generating package: Cockatrice
C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: The command "setlocal
C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: cd C:\Cockatrice\build
C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd
C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: C:
C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd
C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: "C:\Program Files\CMake\bin\cpack.exe" -C Release --config ./CPackConfig.cmake
C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd
C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: :cmEnd
C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: :cmErrorLevel
C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: exit /b %1
C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: :cmDone
C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd
C:\Program Files\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: :VCEnd" exited with code 1.
========== Build: 0 succeeded, 1 failed, 7 up-to-date, 0 skipped ==========

**Comment by ctrlaltca** [comment]
The good news is that all the compilation steps completed successfully.
There's only 1 job left, the "package" target that actually runs NSIS to create the setup package.

> EXEC : warning : target 'libmysql.dll' does not exist...

Cmake is lookinf for all the needed dlls to be included in the setup package, but it can't find 'libmysql.dll'. Add it to the PATH and it should be fine.

You should be able to find an already compiled and runnable executable of cockatrice in the "release"directory. Once the "package" step is completed successfully, it will create a cockatrice-setup-xxx.exe installer in the mail directory.

**Comment by joshuabengal** [comment]
I added the path to MariaDB, and I got past the libmysql.dll, but now I am getting the libPQ.dll issue. Oddly enough I do not see that dll file on my PC at all.  If it's not used as you indicated, can it be removed from that package instructions?

**Comment by joshuabengal** [comment]
Well, even with the path updated it still fails on that DLL. Really odd. Any ideas on how to fix it? Or how to remove servatrice from the project and still get it to compile?

**Comment by Daenyth** [comment]
You can skip compiling servatrice with `-DWITH_SERVER=0` to cmake

**Comment by joshuabengal** [comment]
Thanks, modifying that switch solved a lot of issues! I can now compile older versions no problem. 

As an aside anyone know when the lgin code changed? I'm getting an "Unknown login error: -1" on the older version login attempts

**Comment by Daenyth** [comment]
From the wiki; https://github.com/Cockatrice/Cockatrice/wiki/Troubleshooting#unknown-error--1-message-upon-login

> 
> The server you are trying to connect with is requiring you to have a newer Cockatrice client, but your client is too old to understand that, and instead displays the Error: -1 message.
> 
> You need to upgrade your client.
> 
> If you have attempted to install the updated client and still receive this message the install was not completed successfully. Close all clients, backup your deck files, and reboot the PC you're on. Remove the current client and verify all the files in the install directory are gone. Finally re-run the new client installer.

**Comment by joshuabengal** [comment]
Right, I knew that was the source of the error, I was just wondering if anyone knew when that code was added to the codebase. Basically how far back could you go to in history and still be able to build a client that could connect

I'm also going to work on modifying the instructions to add a note about the `-DWITH_SERVER=0` switch, besides fixing my error it also greatly speeds up cmake and the build process. Thanks for pointing that out!

**Comment by Daenyth** [comment]
Hmm, I'm not sure. I expect it's somewhere around the time client id was added, and the featureset code.

**Comment by Daenyth** [comment]
Maybe summer 2015, ish. @woogerboy21 Do you remember when we did the forced upgrade?

**Comment by woogerboy21** [comment]
According to the commits it should be some were around Sept (fall) time period.  Its definitely when we implemented the clientid code change.  Though I believe if your referring to what feature's are required and trying to compile the very oldest possible client you probably want to look for the client_warnings feature as I believe it is more recent of a feature and is required on the woogerworks server.

**Comment by woogerboy21** [comment]
I believe this is it:
https://github.com/Cockatrice/Cockatrice/commit/6ad2a5936749cddc0464b0d1777dec8797c2765b#diff-87f6a7fb7b62866521bbd624bb919fb7

Though do keep in mind features are developed and will be set to required in good time so this will always be a moving target.

**Comment by Daenyth** [comment]
Is there anything left for us to do on this? If so, please reopen and let us know
