### ISSUE TITLE
Connection timed out

### ISSUE THREAD

**Issue by halo7** [Cockatrice/Cockatrice#2149]
<b>OS:</b>
Windows 7 Prof
<b>Cockatrice version:</b>
d55e44e 2015 09 23
___
<br>

Everytime I try to connect to cockatrice.woogerworks.info (with the port 4747) it just takes long time "connecting to cockatrice.woogerworks.info" and then says "Socket error: connection timed out"
so I cant connect and play.

**Comment by ctrlaltca** [comment]
cockatrice.woogerworks.info is not a valid address for woogerworks' server. Have a look at their website for the correct address: http://www.woogerworks.com/offered-services.html

**Comment by halo7** [comment]
None of them work!

**Comment by ctrlaltca** [comment]
It would be nice to know what you tried. The correct address should be cockatrice.woogerworks.com or the equivalent IP address 163.172.169.152

**Comment by halo7** [comment]
I always have the same problem connection timed out. I tried all the servers (Cockatrice Mumble XMage)

**Comment by ctrlaltca** [comment]
Please try like this:

![schermata 2016-08-27 alle 10 25 05](https://cloud.githubusercontent.com/assets/1631111/18026239/9bf11000-6c40-11e6-9df0-677b97c0b398.png)

**Comment by halo7** [comment]
I think I have an older version. Maybe that is the problem?

**Comment by ctrlaltca** [comment]
You can try to update, head to https://cockatrice.github.io/ and download the most recent version

**Comment by halo7** [comment]
I just needed to update. anyways thanks for your support

**Comment by ctrlaltca** [comment]
You are welcome.
