### ISSUE TITLE
New Feature: Sort and filter by Format

### ISSUE THREAD

**Issue by ZeldaZach** [Cockatrice/Cockatrice#215]
In the new Deck Editor, it allows you to have filters. Instead of having to type to say, lets go with standard, "RTR, GTC, DGM, THS, BTG, JOU, M14, M15," you should be able to click on the 2nd dropdown option "legality" and you can either then type "Modern, Standard, Legacy, Vintage, etc." to filter the cards accordingly.

**Comment by ZeldaZach** [comment]
Seems that there's a field on MTGJSON-extra: `legalities` that contains what formats the cards are legal in. This could be parsed by Oracle and then we could add filters to support it.

**Comment by Daenyth** [comment]
:+1:

**Comment by ZeldaZach** [comment]
I'm going to look into this, but it'll require people to download the extended MTGJSON Oracle version

**Comment by Daenyth** [comment]
Ah that's a good note. That's a fair difference in size isn't it?

**Comment by tooomm** [comment]
3.8 (all sets) vs 9.3 MB (all sets + extras) according to the webpage

**Comment by Daenyth** [comment]
eh not awful. I was thinking it was more.

**Comment by tritoch** [comment]
>To make it easy for people to define custom formats without having to edit every card.

This will still require editing the cards.xml and re-editing it every time Oracle is run?

**Comment by skwerlman** [comment]
> This will still require editing the cards.xml and re-editing it every time Oracle is run?

IMO exclusions should be contained in the `<format>` instead of on the card itself. That way, you can have a format defined in a customSet which can have exceptions for cards in cards.xml.

**Comment by gabrielfgularte** [comment]
Any thoughts on this? It's a very good feature!

**Comment by tooomm** [comment]
First, we would need to switch to the extended AllSets.json file @gabrielfgularte.

As initiated by @Daenyth here: https://github.com/Cockatrice/Cockatrice/issues/528#issuecomment-352259616
