### ISSUE TITLE
Description sidebar width and flickering with long card types

### ISSUE THREAD

**Issue by Kishibe** [Cockatrice/Cockatrice#2150]
<b>OS: Win 10 64bit</b>

<b>Build: d55e44e(20150923):</b>
277d7e2 (2016-06-30)

---

<br>

In a MTG game, the width of the sidebar changes if the "description" or "both" mode is selected and I hover with the mouse in over the card "xenagos, gods of revels". Probably due to Xenagos' card type being "legendary enchantment creature - god", and the standard width of the sidebar is just a bit too thin.

This causes an annoying flickering if the mouse is hovering just on the right of the card, since the card moves its position to the left and the mouse automatically starts hovering to the card to the left of xenagos. This rescales the sidebar and the mouse goes back to hovering on top of xenagos... and back again

**Comment by Psithief** [comment]
A build from 2015? Could you download a more recent build and test if it is still relevant?

**Comment by Kishibe** [comment]
Just tested with build 277d7e2 (2016-06-30) with the same result. Should I open a new issue with the current version?

**Comment by Daenyth** [comment]
No, this ticket is fine

**Comment by Psithief** [comment]
On mine (Windows 7), the type just expands to multiple lines, even if I drag the sidebar to its narrowest width. What resolution are you using?

![image](https://cloud.githubusercontent.com/assets/1124846/18097873/5f80be34-6f12-11e6-8c14-3fcfe5c7a02b.png)

**Comment by Kishibe** [comment]
I tried again to reproduce the issue and today I'm not able to anymore.

It occurs to me that in my previous check (the previous post of mine) I hadn't rebooted my pc between uninstalling the previous Cockatrice version and installing the latest, can that matter?

I'll try again some other day - I notice today that the card info sidebar doesn't autostretch horizontally anymore - that was the feature of the previous build that probably caused the issue.... The bizarre thing is that I'm sure I noticed it again when I wrote the previous post...

BTW, my desktop resolution is 2650x1440 on Win 10, and I set up Windows to enlarge text and app dimensions to 150%.
