### ISSUE TITLE
Split compiling wiki page by OS

### ISSUE THREAD

**Issue by skwerlman** [Cockatrice/Cockatrice#2154]
The "Compiling Cockatrice" page is enormous, and very difficult to navigate. On top of that, the section for each OS is formatted differently from the other sections (different header sizes, use of horizontal rules, etc), making it easy to get lost when scrolling through.

I propose splitting it into four separate pages, to reduce complexity.

The pages would be one per OS type, plus one for linking to the new pages from old links.
    - Compiling Cockatrice
    - Compiling Cockatrice (Windows)
    - Compiling Cockatrice (OSX)
    - Compiling Cockatrice (Linux)

This is a pretty big change in format, so I wanted to get opinions from everyone before doing it.

**Comment by Daenyth** [comment]
Go for it 👍

**Comment by skwerlman** [comment]
Done! I'm not sure if adding direct links to the new pages would clutter the sidebar too much, so I haven't done that yet. Lemme know if I should

**Comment by Daenyth** [comment]
I think one link to the index page on the sidebar is fine for now.

**Comment by Daenyth** [comment]
Nice work!

**Comment by tooomm** [comment]
Regarding the general name change from `OS X` to `macOS` the page should reflect that imo.
The name will stay for a long time and will be what people use and know in the future soon. SEO wise we should have the old names `Mac OS` and `OS X` in the text as well.
