### ISSUE TITLE
Can't Open Cockatrice

### ISSUE THREAD

**Issue by Kammodo** [Cockatrice/Cockatrice#2155]
<b>OS:</b>
*Override this line with the exact operating system you are running! (e.g. "Win 7 SP1", "OS X 10.8.5", "Ubuntu 15.10" ...)*

<b>Cockatrice version:</b>
*Put your Cockatrice version number & build date here! You find them inside the app: `Help` --> `About Cockatrice` (e.g. "2d53ce9 (2016-02-18)"). If you can't access this menu for any reason, please include the full filename of the installer you used.* "C:\Program Files (x86)\Cockatrice\cockatrice.exe"
___
<br>

*Explain your Issue/Request/Suggestion in detail here!*
I have tried opening the program but it never seems to open and i just get an error message telling me to uninstall it then install it. I have windows 10 Home but i can download and run the 32 bit version but it wont let me sign in. i get a message saying "log in error -1"

**Comment by tooomm** [comment]
>>OS:
>>Override this line with the exact operating system you are running! (e.g. "Win 7 SP1", "OS X 10.8.5", >>"Ubuntu 15.10" ...)

>*I have windows 10 Home...*

<br>
>>Cockatrice version:
>>Put your Cockatrice version number & build date here! You find them inside the app: Help --> About Cockatrice (e.g. "2d53ce9 (2016-02-18)"). If you can't access this menu for any reason, please include the full filename of the installer you used

> "C:\Program Files (x86)\Cockatrice\cockatrice.exe"

:+1: 

<br>
Regarding your issue...
>but it wont let me sign in. i get a message saying "log in **error -1**"

..see the troubleshooting section in our [wiki](https://github.com/Cockatrice/Cockatrice/wiki):
https://github.com/Cockatrice/Cockatrice/wiki/Troubleshooting#unknown-error--1-message-upon-login
<br>
Long solution short:
**Your client is out of date and no longer supported by the server you try to use. You need to update your client from our site https://cockatrice.github.io - that's it. :P**

**Comment by Daenyth** [comment]
Reopen this issue if you're still having trouble after upgrading.
