### ISSUE TITLE
Conflict with golang-golang-x-tools /usr/bin/oracle binary

### ISSUE THREAD

**Issue by islander** [Cockatrice/Cockatrice#2158]
<b>OS:</b> Ubuntu 15.10
<b>Cockatrice version:</b> 0.0.1~git20160630.277d7e2

---

<br>

Hello, when I try to install cockatrice, I get this error:

```
$ sudo dpkg -i Cockatrice_Archivist_Madness_trusty.deb 
(Reading database ... 1275596 files and directories currently installed.)
Preparing to unpack Cockatrice_Archivist_Madness_trusty.deb ...
Unpacking cockatrice (0.0.1~git20160630.277d7e2) ...
dpkg: error processing archive Cockatrice_Archivist_Madness_trusty.deb (--install):
 trying to overwrite '/usr/bin/oracle', which is also in package golang-golang-x-tools 1:0.0~git20150902.0.1330b28+dfsg1-0ubuntu1
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Processing triggers for desktop-file-utils (0.22-1ubuntu3) ...
Processing triggers for mime-support (3.58ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.15-0ubuntu1) ...
Errors were encountered while processing:
 Cockatrice_Archivist_Madness_trusty.deb
```

I don't want to remove golang package. Is it posible to rename `/usr/bin/oracle` binary?

**Comment by Daenyth** [comment]
Well that's obnoxious. It's probably possible.

As a workaround, try uninstalling that package, installing cockatrice, renaming `oracle` to `cockatrice-oracle` and then reinstall the golang package.

**Comment by Daenyth** [comment]
cc @ctrlaltca I'm sure we can resolve this with cmake? Maybe we can add a flag like `-DORACLE_BINARY_NAME=cocktrice-oracle` ?

**Comment by islander** [comment]
@Daenyth workaround not working, same error when reinstalling golang:
```
$ sudo mv /usr/bin/oracle /usr/bin/cockatrice-oracle
$ sudo apt-get install golang-go.tools golang-golang-x-tools
...
trying to overwrite '/usr/bin/oracle', which is also in package cockatrice 0.0.1~git20160630.277d7e2
```

**Comment by skwerlman** [comment]
@islander you might be able to get around it by installing golang like this: http://askubuntu.com/a/316653/195840

**Comment by Daenyth** [comment]
That seems like the best way to handle it for the moment.

@islander Another option would be to not use the cockatrice deb but instead compile it yourself and run it out of the compiled directory instead of installing it system wide, at least until we can include an option for the binary name

**Comment by tooomm** [comment]
The name also leads to confusions with other software by `Oracle` for example.

**Comment by Daenyth** [comment]
I'm not concerned with anyone getting us confused with them
