### ISSUE TITLE
Buddies only filter buggy

### ISSUE THREAD

**Issue by LethalPigeon7** [Cockatrice/Cockatrice#2159]
<b>OS:</b>Win 7 SP1
<b>Cockatrice version:</b>a3a6065 (2016-08-20)

---

If I restart cockatrice it remembers that I had buddies only games filtered out last time I was logged on, and it shows the tickbox as unticked, but still shows buddies only games. Fixed by re-ticking the box twice.
This is a very minor issue that hasn't really affected me in any notable way, but I thought I might as well report it.
In case my point got lost in poor choice of words (happens too often, really), here's [overly specific screenshots](http://imgur.com/a/9LnH2)

**Comment by tooomm** [comment]
I can't check or verify your detection at the moment.
But yes, these small UI/UX things might confuse people a lot and are mostly easy to fix as well.

Thanks for every tiny report! ;)

(I remember some people here used http://recordit.co/ to generate gifs or
http://screencast-o-matic.com for real videos for best explanations)
