### ISSUE TITLE
Split Card picture download without MUID

### ISSUE THREAD

**Issue by tritoch** [Cockatrice/Cockatrice#2160]
If a split card does not have a muid, it will attempt to download as "LeftRight" instead of "Left // Right"

Debug follows

Trying to load picture (set:  "DGM"  card:  "WearTear" )
Picture NOT found, trying to download (set:  "DGM"  card:  "WearTear" )
starting picture download: "Wear // Tear" Url: QUrl("http://gatherer.wizards.com/Handlers/Image.ashx?name=WearTear&type=card")
Picture downloaded, but blacklisted, will consider it as not found
Picture NOT found, download failed, no more sets to try: BAILING OUT (oldset:  "DGM"  card:  "WearTear" )

**Comment by skwerlman** [comment]
Correct URL is http://gatherer.wizards.com/Handlers/Image.ashx?name=Wear%20//%20Tear&type=card

**Comment by tritoch** [comment]
" // " (and if // were to survive, "/") are being removed here:
https://github.com/Cockatrice/Cockatrice/blob/8571815cbd1906c17ccf9f67f6d3acd0f6897b37/cockatrice/src/carddatabase.cpp#L261

If you remove those strips, the image loader appears to process the correct URL, but then it hangs, won't download your split card or any thereafter until Cockatrice is restarted.

`Picture NOT found, trying to download (set:  "DDJ"  card:  "Fire // Ice" )
starting picture download: "Fire // Ice" Url: QUrl("http://gatherer.wizards.com/Handlers/Image.ashx?name=Fire %2F%2F Ice&type=card")`

No further debug is logged, if another card without image is selected, debug is as follows:
`Picture NOT found, trying to download (set:  "DRK"  card:  "Fire and Brimstone" )`
Again, no further debug indefinitely.

**Comment by tritoch** [comment]
Also, this affects all cards with any of these symbols currently (they're all stripped, and gatherer wants them all left alone): 
`return result.remove(" // ").remove(':').remove('"').remove('?').replace('/', ' ');`
aka
`[" // ",':','"','?','/']`

To test this, simply put the Fallback URL from settings (`http://gatherer.wizards.com/Handlers/Image.ashx?name=!name!&type=card`) as the primary, you won't be able to download any images for cards with that symbol set in them (`Circle of Protection: Black`,`Kongming, "Sleeping Dragon"`, `Far // Away`,`Who/What/When/Where/Why`,`Question Elemental?`)

**Comment by ctrlaltca** [comment]
> If you remove those strips, the image loader appears to process the correct URL, but then it hangs, won't download your split card or any thereafter until Cockatrice is restarted.

The card name is cleaned of some characters to avoid problematic filenames when saving the file to disk. It is wrongy used also when downloading those cards, and this needs to be fixed.
