### ISSUE TITLE
Kaladesh Aether card images not functioning

### ISSUE THREAD

**Issue by samgc3** [Cockatrice/Cockatrice#2161]
<b>OS:</b>
Win 10

<b>Cockatrice version:</b>
2e3966a (2016-04-16)

---

<br>

I noticed while using custom set XML for Kaladesh that cards having Aether in their name aren't functioning properly. It converts the name from Aether to AEther and won't return the card image. I believe this is due to Wizards changing Æ to Ae and the former having been specially coded into Cockatrice.

Here is sample XML:

```
    <card>
      <name>Aether Hub</name>
      <set picURL="http://media-dominaria.cursecdn.com/avatars/126/947/636089260525055620.png">KLD</set>
      <color></color>
      <manacost></manacost>
      <cmc>0</cmc>
      <type>Land</type>
      <pt></pt>
      <tablerow>2</tablerow>
      <text>When Aether Hub enters the battlefield, you get e (an energy counter).

t: Add C to your mana pool.

t, Pay e: Add one mana of any color to your mana pool.</text>
    </card>
```

**Comment by Daenyth** [comment]
Did oracle generate this xml or did you get it from somewhere? Oracle doesn't attach `picURL` any more, so I'm not clear.

Can you also attach the debug log from a session with the failure you're seeing?

**Comment by samgc3** [comment]
I found that the cards function properly when you magnify them, but you cannot see the image in deck editor, hand, or on the battlefield. 

Someone created the XML, found here: http://www.mtgsalvation.com/forums/magic-fundamentals/magic-software/third-party-programs/754885-kaladesh-patch-for-cockatrice

**Comment by samgc3** [comment]
Here's a sample of what I'm seeing. I'm not sure how to get the debug log.

http://imgur.com/a/SPJam

**Comment by Daenyth** [comment]
From the application menu `Help > View debug log`

**Comment by samgc3** [comment]
The issue seems to be that when loading a deck from a text file names with Aether are brought in as AEther. I can work around the issue by loading from a .cod instead.

**Comment by Daenyth** [comment]
Generally speaking, .dec/.txt imports are for compatibility only and won't always be 100%. This is one thing it does for compatibility with some older cards, but we can probably remove it at this point.

If you have a deck in txt format, you can use the "load deck from clipboard" feature and save as .cod.

**Comment by Jinxstands4Jinx** [comment]
You could use the Custom images Folder to overwrite this by saving the correct picture in there named Aether.

**Comment by woogerboy21** [comment]
Can this issue be closed?  Sounds like there is a fix for the Ae/AE issue already merged and the user defined file may have been the original reasoning for the issue?
