### ISSUE TITLE
Add custom sets/cards duplicates existing sets

### ISSUE THREAD

**Issue by dev-id** [Cockatrice/Cockatrice#2162]
When using Card Database > Add custom sets/cards, importing an existing set will create a duplicate.  Cockatrice should prompt for overwrite or duplication.

Users are continuously working on a custom set or updating spoilers periodically.

**Comment by tooomm** [comment]
while copying the file to the custom set folder it get's renamed and a number is added.
we could still compare the files by name and ask to overwrite the existing version.

as long as people don't add dates or incrementing numbers to their spoilers it should work.

**Comment by ZeldaZach** [comment]
We don't have a good way of knowing if your set's a dupe or not. Would require a lot of extra information from the user.

**Comment by tooomm** [comment]
Ticket only asks to have a `File with that name exists already` dialog instead automatically renaming and adding that file as a new instance which leaves the former old version silently behind.
