### ISSUE TITLE
Client is not responding until I reconnect, happens often

### ISSUE THREAD

**Issue by robcards** [Cockatrice/Cockatrice#2168]
<b>OS:</b>
Win 7

<b>Cockatrice version:</b>
c095daa (2016-06-30)

---

<br>

When I'm playing a game on cockatrice, sometimes what I do goes through on my opponent's end but I can't see it and I can't see anything they do and the only way to fix it is to disconnect and reconnect. Usually this would happen once every 5 minutes or so, but today it happened every 5 seconds. I also noticed that in the Server tab the color of the circle next to Server would turn red and then black when this happened (aside from shuffling deck or tapping a permanent its the only way I notice it's happened). This has been going on for months, and through several versions of Cockatrice. My internet connection is very strong so I know it isn't that.

**Comment by woogerboy21** [comment]
This sounds like a poor network connection.  Could you open a command
window on whatever operating system you are using and try issueing a ping
command to the server you are connecting to and post the results?

Thanks

**Comment by robcards** [comment]
Packets: Sent = 4, Received = 4, Lost = 0
Approximate round trip times in milli-seconds:
Minimum = 175ms, Maximum = 182ms, Average = 177ms

**Comment by robcards** [comment]
Ok I did a ping when I experienced one of the issues and the first request timed out

**Comment by woogerboy21** [comment]
@robcards Ever get this worked out?  Sounds like you were loosing network communication.
