### ISSUE TITLE
Ability to choose which "print" to add to the deck

### ISSUE THREAD

**Issue by Alekiel** [Cockatrice/Cockatrice#217]
Choosing which version of a card you want to add to your deck would be wonderful, rather than defaulting to just "set order", since it'd be far more flexible. This is specially true for lands, which get "replaced" every time a new set gets added to oracle.

**Comment by Fenrirthviti** [comment]
This looks to be the same issue as #486, but #486 has significantly more discussion, despite this being this older issue.

**Comment by ebbit1q** [comment]
duplicate
