### ISSUE TITLE
webclient autologin after server selection (autocomplete) for no reason

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2170]
<b>OS:</b>
Win 10 with Firefox 48.0.2

<b>Cockatrice version:</b>
Webclient @ woogerworks (19th september 2016)

___
<br>

![autologin](https://cloud.githubusercontent.com/assets/9874850/18641439/e7217cd6-7e9c-11e6-8b62-7d83aa275395.png)
If you select a server in the host field it'll automatically try to connect you to that server. Even if you haven't entered any user information yet.
Same if you change from one server to another it'll instantly try to connect to the new host without letting you adjust your credentials accordingly.

I highly prefer to generally disable this autologin behavior and just login if the user hits the `Connect` button.

**Comment by ctrlaltca** [comment]
I can only reproduce this behavior navigating the autocompleter using arrow keys and pressing enter/return to confirm the selection. In this case the browser interprets the enter/return as "send the form" causing the connect to occur.
When choosing an option from the completer using the mouse, i never got the webclient to  connect.
Can you confirm if it works the same for you?

**Comment by tooomm** [comment]
Can confirm, if you select the entry with your mouse it does not connect automatically.
