### ISSUE TITLE
Cannot Connect

### ISSUE THREAD

**Issue by 7onething1** [Cockatrice/Cockatrice#2171]
<b>OS:</b>
*Override this line with the exact operating system you are running! ("OS X 10.9.5")

<b>Cockatrice version:</b>
*Put your Cockatrice version number & build date here!   277d7e2  2016-06-30. .*

___
<br>

Me and my friends cannot connect.  booted off and "socket error:connection refused"

**Comment by tooomm** [comment]
I'm just guessing that you are connected to the woogerworks server. You should let us know, there are other servers that you could be using as well...
You might want to follow his twitter, there is a known issue with the server right now:
https://twitter.com/woogerworks/status/777990674050408448

You need to hang on.

**Comment by 7onething1** [comment]
The other two servers didn't work, could you advise one for me here in the us

**Comment by Daenyth** [comment]
"Connection refused" means that your client was able to communicate with the server address you listed but that the server was not accepting connections on that port. Usually this means that the server address is correct but the server is down.

What problem did you have with the other servers?

All public servers that we are aware of, we put into the default list.
