### ISSUE TITLE
Cannot connect

### ISSUE THREAD

**Issue by philipcliang** [Cockatrice/Cockatrice#2172]
<b>OS:</b>
Windows 10

<b>Cockatrice version:</b>
323fc06

___
<br>

I cannot connect to the server.

**Comment by tooomm** [comment]
I'm just guessing that you are connected to the woogerworks server. You should let us know, there are other servers that you could be using as well...
You might want to follow his twitter, there is a known issue with the server right now:
https://twitter.com/woogerworks/status/777990674050408448

You need to hang on.
