### ISSUE TITLE
New public server; separate page for public servers?

### ISSUE THREAD

**Issue by skwerlman** [Cockatrice/Cockatrice#2173]
I've got two (related) requests regarding cockatrice.github.io.

---

- [x] I've recently decided to make my (very small) personal server open to the public. Could it please be added to the website?

website: none yet (update: skwerlman.github.io)
host: mtg.tetrarch.co
port: 4747
no webclient support (waiting for it to mature a bit before allowing it)
in-client registration only

---

- [x] Add my server to the in-client list

---

- [x] Maybe have a separate page for the server list? The current list only works for servers which have their own websites attached, and does not really provide much info about where each server is, or info about the communities they support. I think there's a lot of room for improvement there.

I suggest having a table with info on each public server, like so:

| Server (+ link to website) | Location | Language | Aprox. Users | Hostname | Port | Webclient Port | Allows Unreg |
| --- | --- | --- | --- | --- | --- | --- | --- |
| Tetrarch | US East | English | 10 | mtg.tetrarch.co | 4747 | N/A | No |
| [Woogerworks](http://www.woogerworks.com/) | Somewhere (EU?) | English | A bunch | cockatrice.woogerworks.com | 4747 | 4748 | ?? |

**Comment by tooomm** [comment]
We could have a wiki page and link to it from the io page :+1: 
So server admins could adjust and add servers on their own. We just need to watch out for mistakes!

**Comment by skwerlman** [comment]
That's a good solution. 

I'd be happy to get the page started, though I don't know much about the servers currently listed.

**Comment by tooomm** [comment]
Start with a temp page again maybe. We'll bring @woogerboy21, @poixen and @Lachee on board as well.

Not sure which information are really needed and which should be thought over. We can figure that out later. I've some design ideas that i'll work into once you set the page up! :+1:

**Comment by skwerlman** [comment]
Here's the list with all the info I have: https://github.com/Cockatrice/Cockatrice/wiki/Public-Servers

**Comment by woogerboy21** [comment]
Is there a link to this off the main wiki page side?

**Comment by tooomm** [comment]
Not yet, we are gathering information and ideas at the moment.
Does everybody likes the idea of having a link on the github pages site to such a server wiki side? (instead of having a long list there and the subscribed downsides by skwerlman in his starting post here)

@skwerlman Do you request to get added with your server to the client as well?

**Comment by Daenyth** [comment]
I like the wiki idea.

I think if we list a server on there we should put it in the client also

**Comment by skwerlman** [comment]
Ye, it'd be nice to get in the client.

**Comment by Lachee** [comment]
I added my server details to the table to. Confused by the User and Auth though. Is Users the maxium users I can support or the approximate active players day to day? And what is auth? Is that saying people have to have an account to login? Because Allow Unregister will signify that instead.

**Comment by skwerlman** [comment]
Users is the approximate number of people you see at any one time.
Auth is whether users are allowed to create accounts from the client (authentication.method is sql, not none)

**Comment by Lachee** [comment]
Thank you. I have updated the information.

**Comment by Daenyth** [comment]
@skwerlman Your SSL certs need fixing btw, if I go to mtg.tetrarch.co I get `NET::ERR_CERT_COMMON_NAME_INVALID`

**Comment by skwerlman** [comment]
@Daenyth mtg.tetrarch.co doesn't have anything running on port 80 (or it shouldn't, at least)

**Comment by skwerlman** [comment]
@tooomm I like the idea of relative indicators, but they look odd for me (I'm using a dark theme for GH)

I could _try_ to make some indicator svgs, unless someone with more inkscape experience wants to give it a try

**Comment by Daenyth** [comment]
@skwerlman it does have things running, go to the url and tell your browser to bypass the ssl error; it appears to be a status/uptime page

**Comment by Daenyth** [comment]
@tooomm what do you think about changing the .io page to point to the wiki list of servers instead of listing them directly? Adding tetrarch to the list would be awkward since the existing lines are all links to the server's website.

@skwerlman If you could stand up a static page (gh-pages?) with info about your server that would help, so we can direct people there

**Comment by skwerlman** [comment]
@daenyth it looks like my nginx is redirecting to status.tetrarch.co, instead of doing nothing. I'll have to look into it.

As for a page, I have no experience writing anything for the web, so help here would be appreciated: skwerlman.github.io

**Comment by tooomm** [comment]
@Daenyth That was the idea from the beginning. :P 
Changes to the io page done. It's now also on the wiki sidebar.

<br>
@skwerlman Their are themes and setup help for gh pages, check these out: https://pages.github.com/ and https://github.com/blog/1081-instantly-beautiful-project-pages

I was also wondering about the server info (port) here: https://tetrarch.co/
Is it correct? Or the one on our wiki page?
<br>
>Auth is whether users are allowed to create accounts from the client (`authentication.method` is sql, not none)

That sounds like a bad name choice!? If it's really that, it should obviously be named<br> `In-Client Registration` in the table?
(and it should be explained better in the servatrice config... if even server admins don't know)

**Comment by skwerlman** [comment]
> I was also wondering about the server info (port) here: https://tetrarch.co/

The port on my website is wrong. :flushed: 

> That sounds like a bad name choice!?

I based that name off the config section, which is:
```ini
[authentication]

; Servatrice can authenticate users connecting. It currently supports 3 different authentication methods:
; * none: no authentication, accept every user;
; * password: require users to specify a common password to log in;
; * sql: authenticate users against the "users" table of the database;
; Please note that only the "sql" method permits to have registered users and store their data on the server.
method=none
```

There's probably a better/clearer/more correct wording for it.

**Comment by Daenyth** [comment]
I'll mark this closed since all the todo items are done, anything remaining is just tweaks.

**Comment by skwerlman** [comment]
Should the public servers list be in the Servatrice section? I feel like it'd make more sense in the Welcome to Cockatrice section, since new players will be looking for it.

**Comment by poixen** [comment]
@skwerlman Im not sure Im for the idea of hard coding this in. Some operators may not want to promote others?

**Comment by skwerlman** [comment]
I meant in the sidebar of the wiki. I prob shouldve been more specific...

**Comment by Daenyth** [comment]
@skwerlman do whatever wiki edits you think makes it better, just keep in mind that changing page urls may break links
