### ISSUE TITLE
Cockatrice not loading my GTK theme

### ISSUE THREAD

**Issue by skwerlman** [Cockatrice/Cockatrice#2174]
<b>OS:</b>
Sabayon 16.10

<b>Cockatrice version:</b>
7f28a7e

---

<br>

I'm unable to get Cockatrice to use my GTK theme.

I've followed the steps listed in the troubleshooting section of the wiki (install libgnome, add `style=GTK+` to Trolltech.conf), but cockatrice remains unthemed.

![image](https://cloud.githubusercontent.com/assets/6954107/19372710/6a34fe5c-918c-11e6-800f-40d3df346bf0.png)

Other QT apps (like qtconfig) are themed correctly.

There's nothing in the debug log that indicates a problem.

(edit: after updating to git HEAD, problem remains)

**Comment by Daenyth** [comment]
This is likely us doing something wrong

**Comment by skwerlman** [comment]
If it helps with debugging, here are the versions I'm using:
- Cinnamon 3.0.6
- QT 5.6.1
- gtk+ 3.20.8
- gtk-engines-murrine 0.98.2-r1
- gtk-engines-equinox 1.50
- libgnomeui 2.24.5-r1
- Adapta Nocto f05f9e9 (git head)

**Comment by ctrlaltca** [comment]
> I've followed the steps listed in the troubleshooting section of the wiki (install libgnome, add style=GTK+ to Trolltech.conf)

Those informations are relevant only for Qt4, and we should probably remove them from the Wiki now that Cockatrice is Qt5-only.

> Other QT apps (like qtconfig) are themed correctly.

`qtconfig` is a Qt4 app, and doesn't exists anymore on Qt5.
Can you check if you have any other Qt5-based app and if it's themed correctly?

Can you please try to:
 * run cockatrice from a terminal: `XDG_CURRENT_DESKTOP=gnome cockatrice`;
 * run cockatrice from a terminal: `QT_QPA_PLATFORMTHEME='gtk2' cockatrice`;
 * run cockatrice from a terminal: `cockatrice -style=gtk+`;

**Comment by skwerlman** [comment]
I do not think I have any other qt5 apps at the moment.
None of the three commands provided had any effect.
After running `unset QT_STYLE_OVERRIDE` (found here: http://unix.stackexchange.com/questions/176696/qt5-applications-dont-use-gtk-style-on-liux-mint) I was able to get it to use the default GTK theme, but not my current one.

**Comment by skwerlman** [comment]
I have _finally_ figured this out!

In order to get any theme to work for all qt5 apps, you have to add it as a custom .qss file in `qt5ct`. Unfortunately, my GTK theme doesn't support qss yet, but I was able to find a (sorta) passable alternative, although it has a few problems: http://imgur.com/a/dJV11

I know very little about creating themes with qss, so pointers would be appreciated.

**Comment by ZeldaZach** [comment]
@skwerlman Thanks for letting us know! If you'd like to update the wiki with this knowledge, please feel free to :)
