### ISSUE TITLE
installation on ubuntu 16.04

### ISSUE THREAD

**Issue by menph** [Cockatrice/Cockatrice#2177]
<b>OS:</b>
ubuntu 16.04 LTS

<b>Cockatrice version:</b>
Version 7f28a7e (2016-09-02)

___
<br>
installated with no problem at all. i add my shell session here per Daenyth (Cockatice Lead Developer) request

    menph@menph:~/Cockatrice/build$ cmake .. -DWITH_SERVER=1
    -- Performing Test CXX_HAS_WARNING_-Wno-error=extra
    -- Performing Test CXX_HAS_WARNING_-Wno-error=extra - Success
    -- Performing Test CXX_HAS_WARNING_-Wno-error=delete-non-virtual-dtor
    -- Performing Test CXX_HAS_WARNING_-Wno-error=delete-non-virtual-dtor - Success
    -- Performing Test CXX_HAS_WARNING_-Wno-error=sign-compare
    -- Performing Test CXX_HAS_WARNING_-Wno-error=sign-compare - Success
    -- Performing Test CXX_HAS_WARNING_-Wno-error=missing-declarations
    -- Performing Test CXX_HAS_WARNING_-Wno-error=missing-declarations - Success
    -- UPDATE TRANSLATIONS: OFF
    -- Found Qt 5.5.1
    -- Mysql connector NOT FOUND: servatrice won't be able to connect to a mysql server
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /home/menph/Cockatrice/build
    menph@menph:~/Cockatrice/build$ make package -j2
    [  0%] Automatic moc for target cockatrice_common
    [  0%] Automatic moc for target cockatrice_protocol
    [  0%] Built target cockatrice_protocol_automoc
    [  0%] Built target cockatrice_common_automoc
    Scanning dependencies of target servatrice_automoc
    [  1%] Automatic moc for target servatrice
    [  1%] Automatic moc for target cockatrice
    Generating moc_isl_interface.cpp
    [  1%] Built target cockatrice_automoc
    Generating moc_servatrice.cpp
    [  1%] Automatic moc for target oracle
    [  1%] Built target oracle_automoc
    Generating moc_servatrice_connection_pool.cpp
    Generating moc_servatrice_database_interface.cpp
    [ 60%] Built target cockatrice_protocol
    Generating moc_server_logger.cpp
    Generating moc_serversocketinterface.cpp
    [ 67%] Built target oracle
    Generating moc_settingscache.cpp
    Generating moc_signalhandler.cpp
    [ 71%] Built target cockatrice_common
    Generating moc_qxtsmtp.cpp
    Generating moc_qxtsmtp_p.cpp
    Generating moc_smtpclient.cpp
    [ 71%] Built target servatrice_automoc
    [ 72%] Generating qrc_servatrice.cpp
    Scanning dependencies of target servatrice
    [ 97%] Built target cockatrice
    [ 97%] Building CXX object servatrice/CMakeFiles/servatrice.dir/src/passwordhasher.cpp.o
    [ 97%] Building CXX object servatrice/CMakeFiles/servatrice.dir/src/main.cpp.o
    [ 97%] Building CXX object servatrice/CMakeFiles/servatrice.dir/src/servatrice.cpp.o
    [ 97%] Building CXX object servatrice/CMakeFiles/servatrice.dir/src/servatrice_connection_pool.cpp.o
    [ 98%] Building CXX object servatrice/CMakeFiles/servatrice.dir/src/servatrice_database_interface.cpp.o
    [ 98%] Building CXX object servatrice/CMakeFiles/servatrice.dir/src/server_logger.cpp.o
    [ 98%] Building CXX object servatrice/CMakeFiles/servatrice.dir/src/serversocketinterface.cpp.o
    [ 98%] Building CXX object servatrice/CMakeFiles/servatrice.dir/src/settingscache.cpp.o
    [ 98%] Building CXX object servatrice/CMakeFiles/servatrice.dir/src/isl_interface.cpp.o
    [ 99%] Building CXX object servatrice/CMakeFiles/servatrice.dir/src/signalhandler.cpp.o
    [ 99%] Building CXX object servatrice/CMakeFiles/servatrice.dir/__/version_string.cpp.o
    [ 99%] Building CXX object servatrice/CMakeFiles/servatrice.dir/src/smtpclient.cpp.o
    [ 99%] Building CXX object servatrice/CMakeFiles/servatrice.dir/src/smtp/qxthmac.cpp.o
    [ 99%] Building CXX object servatrice/CMakeFiles/servatrice.dir/src/smtp/qxtmailattachment.cpp.o
    [100%] Building CXX object servatrice/CMakeFiles/servatrice.dir/src/smtp/qxtmailmessage.cpp.o
    [100%] Building CXX object servatrice/CMakeFiles/servatrice.dir/src/smtp/qxtsmtp.cpp.o
    [100%] Building CXX object servatrice/CMakeFiles/servatrice.dir/qrc_servatrice.cpp.o
    [100%] Building CXX object servatrice/CMakeFiles/servatrice.dir/servatrice_automoc.cpp.o
    [100%] Linking CXX executable servatrice
    [100%] Built target servatrice
    Run CPack packaging tool...
    CPack: Create package using DEB
    CPack: Install projects
    CPack: - Run preinstall target for: Cockatrice
    CPack: - Install project: Cockatrice
    CPack: Create package
    CPackDeb: - Generating dependency list
    CPack: - package: /home/menph/Cockatrice/build/Cockatrice-0.0.1~git20160902.7f28a7e.deb generated.
    menph@menph:~/Cockatrice/build$ sudo dpkg -i Cockatrice*.deb
    Selezionato il pacchetto cockatrice non precedentemente selezionato.
    (Lettura del database... 217095 file e directory attualmente installati.)
    Preparativi per estrarre Cockatrice-0.0.1~git20160902.7f28a7e.deb...
    Estrazione di cockatrice (0.0.1~git20160902.7f28a7e)...
    Configurazione di cockatrice (0.0.1~git20160902.7f28a7e)...
    Elaborazione dei trigger per gnome-menus (3.13.3-6ubuntu3.1)...
    Elaborazione dei trigger per desktop-file-utils (0.22-1ubuntu5)...
    Elaborazione dei trigger per bamfdaemon (0.5.3~bzr0+16.04.20160701-0ubuntu1)...
    Rebuilding /usr/share/applications/bamf-2.index...
    Elaborazione dei trigger per mime-support (3.59ubuntu1)...
    Elaborazione dei trigger per hicolor-icon-theme (0.15-0ubuntu1)...

**Comment by Daenyth** [comment]
Sorry, I thought from your post you had an error installing it
