### ISSUE TITLE
Wrong image for card: Westvale Abbey

### ISSUE THREAD

**Issue by baddestwheel** [Cockatrice/Cockatrice#2180]
<b>OS:</b>
Window 10

<b>Cockatrice version:</b>
version: cbea432 (2016-03-08)

___
<br>

The card Westvale Abbey (legendary land) uses the image for Ormendahl, Profane Prince (which is the card it transforms into).

Here is a link to the official card on the MTG gatherer: 
http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=410049

side note: If you get an image of Westvale Abbey, you can save it as a custom card image as a .jpg with the name "Westvale Abbey" (minus the "") and it will display correctly (for your screen only or anyone else who has used this fix).

**Comment by ZeldaZach** [comment]
Please update your oracle database. This issue has been fixed already.
