### ISSUE TITLE
Zendikar Expeditions should have set type "Masterpiece"

### ISSUE THREAD

**Issue by GatesDA** [Cockatrice/Cockatrice#2181]
With the addition of the Masterpiece set type for Kaladesh Inventions, Zendikar Expeditions should be updated to match it.

**Comment by Daenyth** [comment]
I think this is a bug for @lsmoura

**Comment by lsmoura** [comment]
Can we get any confirmation as that BFZ is an Masterpiece? Something on WOTC website?

**Comment by Daenyth** [comment]
@lsmoura https://magic.wizards.com/en/articles/archive/feature/kaladesh-release-notes-2016-09-16

> The Masterpiece Series that began with Zendikar Expeditions continues with Kaladesh Inventions!

**Comment by lsmoura** [comment]
I'm fixing it! Once KLD is standard, it will be all good.

**Comment by Daenyth** [comment]
Thanks! :D
