### ISSUE TITLE
E counters

### ISSUE THREAD

**Issue by Jinxstands4Jinx** [Cockatrice/Cockatrice#2184]
This is more a suggestion than Anything. The cards that make tokens are linked to their token. I think the E makers of KLD and possibly future sets should be linked to the E counter. like the EXp guys are linked to their Exp counter.

**Comment by ZeldaZach** [comment]
I think this is related to @Psithief

**Comment by Psithief** [comment]
Hmm. Yeah, this is true.

**Comment by Psithief** [comment]
This is now done. 204925eaa37137c05b5e3ba73d2b605a2d86a99f

Thanks @Jinxstands4Jinx , I had forgotten about this. It is one day later than the earliest I could have delivered it.
