### ISSUE TITLE
Registered users only

### ISSUE THREAD

**Issue by Jinxstands4Jinx** [Cockatrice/Cockatrice#2186]
in efforts to make sorting games easier,  I try to not look at "buddies only" or "password" games I think we should eliminate the option of "registered users only" as every person fits this already. If we cannot remove it then allow the sorter to change the order as showing the "blank" games and the user only ones are the same thing.

**Comment by tooomm** [comment]
duplicate https://github.com/Cockatrice/Cockatrice/issues/1702?

**Comment by Jinxstands4Jinx** [comment]
well yes but for different reason as sorting the games is not very well sorted with both options. hence why i think we should eliminate one.

**Comment by Daenyth** [comment]
This will be easier once I can get some time to add a way for the
server to tell the client what options are set. If the server can tell
the client that it's reg only the client will be able to know to hide
the reg only flag

**Comment by Daenyth** [comment]
Also not all servers are reg only; I believe chickatrice allows unreg

**Comment by woogerboy21** [comment]
Yes, the option is there for operators that wish to offer unreg server access along with reg server access.  It just so happens the woogerworks server that most people use is registered users only.

**Comment by tooomm** [comment]
I'm pretty sure this is covered in #1702:

>For "registered users only" servers
>
>    - Check + grey out the `Only registered users can join` option in the "Create game" dialog

<br>

Removing the option in the interface completely won't happen because
>not all servers are reg only

<br>

`If we cannot remove it then allow the sorter to change the order as showing the "blank" games and the user only ones are the same thing.` --> also covered in #1702:
>Hide `reg. users only` tags in the "Restriction" column of the game list
