### ISSUE TITLE
Randomizer Deck Option?

### ISSUE THREAD

**Issue by Maycus** [Cockatrice/Cockatrice#2187]
<b>OS:</b>
*Override this line with the exact operating system you are running! (e.g. "Win 7 SP1", "OS X 10.8.5", "Ubuntu 15.10" ...)*

<b>Cockatrice version:</b>
*Put your Cockatrice version number & build date here! You find them inside the app: `Help` --> `About Cockatrice` (e.g. "2d53ce9 (2016-02-18)"). If you can't access this menu for any reason, please include the full filename of the installer you used.*

___
<br>

*Explain your Issue/Request/Suggestion in detail here!*
Could I suggest that there's a randomizer option in Cockatrice, where we can go in a game, and have the program randomly generate a deck based on EDH or other formats? (excluding casual "Anything goes")

For example, I create a game, and there's a button that says "Random Deck" and it generates a random deck that we do not know is in it, until the game starts. If it's in for example, Standard format, it will only pick cards that are allowed in Standard, and adds the right amount of lands for whatever colors it chooses.

**Comment by Daenyth** [comment]
This is pretty far out of scope for us. We're aiming to be a digital kitchen tabletop, and I don't think this serves that goal.

I think the best thing for this would be an external site which could generate a .cod deck file for you to download. That would be pretty easy to make
