### ISSUE TITLE
cockatrice not working after sys update

### ISSUE THREAD

**Issue by bakkoiq** [Cockatrice/Cockatrice#2191]
<b>OS:Ubuntu 15.04 vivid</b>
<b>Version:277d7e2 (not sure)</b>

---

<br>
hi,
cockatrice was working correctly till i updated my system (not realy sure about important parts so i'll paste all):
<br>
`
Start-Date: 2016-09-26  13:56:59
Commandline: aptdaemon role='role-commit-packages' sender=':1.74'
Install: linux-headers-3.19.0-69:amd64 (3.19.0-69.77), linux-image-extra-3.19.0-69-generic:amd64 (3.19.0-69.77), linux-image-3.19.0-69-generic:amd64 (3.19.0-69.77), linux-headers-3.19.0-69-generic:amd64 (3.19.0-69.77), linux-signed-image-3.19.0-69-generic:amd64 (3.19.0-69.77)
Upgrade: wine-devel-i386:i386 (1.9.18~ubuntu15.04.1, 1.9.19~ubuntu15.04.1), linux-headers-generic:amd64 (3.19.0.68.66, 3.19.0.69.67), wine-devel-amd64:amd64 (1.9.18~ubuntu15.04.1, 1.9.19~ubuntu15.04.1), wine-devel:amd64 (1.9.18~ubuntu15.04.1, 1.9.19~ubuntu15.04.1), linux-signed-generic:amd64 (3.19.0.68.66, 3.19.0.69.67), linux-signed-image-generic:amd64 (3.19.0.68.66, 3.19.0.69.67), winehq-devel:amd64 (1.9.18~ubuntu15.04.1, 1.9.19~ubuntu15.04.1), linux-libc-dev:amd64 (3.19.0-68.76, 3.19.0-69.77), linux-image-generic:amd64 (3.19.0.68.66, 3.19.0.69.67), linux-generic:amd64 (3.19.0.68.66, 3.19.0.69.67)
 End-Date: 2016-09-26  14:00:42
`
<br>
now after typing cockatrice new empty window (without menus etc.) named Cockatrice-disconnected appears and goes grey.  
cockatrice>>tracker.log     gives blank file 
i removed and recompiled cockatrice but without improvement 
please help

**Comment by Daenyth** [comment]
Does oracle work?

Can you paste the full output of `cmake` and `make`?

**Comment by bakkoiq** [comment]
oracle is working correctly

**Comment by Daenyth** [comment]
So when you open cockatrice, it stays there but grey? Can you see any menus? Can you get to `Help > View Debug Log` ?

**Comment by bakkoiq** [comment]
when i open cockatrice new window appears with header Cocaktrice-disconnected.  Inside there is only frozen screen (showing terminal from which i started cockatrice). This window goes grey (not responding) after a few seconds.

**Comment by Daenyth** [comment]
Are you familiar with `gdb`? If you could get a backtrace that might help.

**Comment by bakkoiq** [comment]
(gdb) run
Starting program: /usr/bin/cockatrice 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

that's all

**Comment by Daenyth** [comment]
If you use `bt` in gdb after it freezes, what does that say?

**Comment by bakkoiq** [comment]
should i stop it to send bt?

^Z[New Thread 0x7fffcffff700 (LWP 1810)]
[New Thread 0x7fffddef7700 (LWP 1807)]
[New Thread 0x7fffdf289700 (LWP 1806)]
[New Thread 0x7fffea146700 (LWP 1804)]

Program received signal SIGTSTP, Stopped (user).
0x00007ffff5ce8c4d in nanosleep () at ../sysdeps/unix/syscall-template.S:81
81	../sysdeps/unix/syscall-template.S: No such file or directory.
(gdb)backtrace
#0  0x00007ffff5ce8c4d in nanosleep () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007ffff696ed2d in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#2  0x00007ffff68b7ef8 in QThread::msleep(unsigned long) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#3  0x00007ffff6a1a6c0 in QLockFile::tryLock(int) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007ffff6a66b91 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007ffff6a66f3c in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007ffff6a66161 in QSettings::event(QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007ffff7400b2c in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#8  0x00007ffff7406000 in QApplication::notify(QObject*, QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#9  0x00007ffff6af6c2b in QCoreApplication::notifyInternal(QObject*, QEvent*)
    () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x00007ffff6af8c9b in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#11 0x00007ffff6b4f843 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#12 0x00007ffff507ec3d in g_main_context_dispatch ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#13 0x00007ffff507ef20 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#14 0x00007ffff507efcc in g_main_context_iteration ()

**Comment by ctrlaltca** [comment]
Probably https://bugreports.qt.io/browse/QTBUG-45631
QSettings is unable to write in the settings folder (probably due to some permissione problems), and fails to report it, freezing the application. Affects Qt 5.4, fixed in Qt5.5.

**Comment by Daenyth** [comment]
I believe Ubuntu 15.04 is end of life and you should probably upgrade to
get security fixes.
