### ISSUE TITLE
Picture fallback URL not working?

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2192]
<b>OS:</b>
Win 10

<b>Cockatrice version:</b>
Archivist Madness Release

___
<br>

I'm trying to download the card art for "Accomplished Automation" from new Kaladesh set.

Default URL in settings is:
`http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!cardid!&type=card`
--> translates to http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417764&type=card

Fallback URL is:
`http://gatherer.wizards.com/Handlers/Image.ashx?name=!name!&type=card`
--> translates to http://gatherer.wizards.com/Handlers/Image.ashx?name=Accomplished%20Automaton&type=card

Both are working with the same result!

Once I change the default URL to use the new scheme introduced in #1921 (respective #2134) to get better pictures from magiccards info it's not working anymore.
Because mci doesn't have the pictures yet it should use the fallback URL...

From Debug Log window:
```
Card Database load status:  0
Trying to load picture (set:  "KLD"  card:  "Accomplished Automaton" )
Picture NOT found, trying to download (set:  "KLD"  card:  "Accomplished Automaton" )
starting picture download: "Accomplished Automaton" Url: QUrl("http://magiccards.info/scans/en/kld/!collectornumber!.jpg")
Download failed: "Error transferring http://magiccards.info/scans/en/kld/!collectornumber!.jpg - server replied: Not Found"
Picture NOT found, download failed, no more sets to try: BAILING OUT (oldset:  "KLD"  card:  "Accomplished Automaton" )
QPixmap::scaled: Pixmap is a null pixmap
```

(Don't be confused because it shows `!collectornumber!` instead of `191`. That's because I'm running a version without that fix in. If I change it accordingly the log will be the same except it has the number.)

**Comment by Daenyth** [comment]
This is probably because fallback URL is only used it the card has no muid,
it's not currently a priority system. There's an open ticket for that I
think

**Comment by tooomm** [comment]
--> #1984
