### ISSUE TITLE
MSVCP120.dll is missing from your computer.

### ISSUE THREAD

**Issue by tylerme14** [Cockatrice/Cockatrice#2193]
<b>OS: Windows 10 Pro v1607 (64 bit)</b>

<b>Cockatrice version: Cockatrice_Archivist_Madness_win64</b>

___
<br>

I downloaded/installed a fresh version of Cockatrice today on my laptop. The installer downloaded fine, and the installation went smoothly. I tried to run Oracle to download the newest cards database, but received an error message telling me that the file MSVCP120.dll was missing from my computer, and to try reinstalling. I fully uninstalled cockatrice and reinstalled using a freshly downloaded installer, but received the same message. Cockatrice, Oracle, and Servatrice all try to use that same file, and give me the same error message. I didn't see any documentation of this error on the forum or on the subreddit, but as of now I plan to retry the download/install in a few hours on a different wifi network to make sure it's not an issue on my end(I'll go to McDonalds or something :>).

![error message](https://cloud.githubusercontent.com/assets/22499938/18916846/6dbe88be-855b-11e6-8b10-c46b264213a0.png)

**Comment by tooomm** [comment]
You can stay in your place... haha.

Just check out our wiki with the troublehooting as you can find it on our website: https://cockatrice.github.io

**Comment by Daenyth** [comment]
Specifically https://github.com/Cockatrice/Cockatrice/wiki/Troubleshooting#failed-start-because-msvcpxxxdll-was-not-found
