### ISSUE TITLE
add verbose debug logging

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2196]
From Gitter:

> Gavin Bisesi @Daenyth Sep 16 19:28
> we should add verbose debug logging to (the debug log)
> so people can examine it
> **log input params**, **dns resolution**, etc

Conversation was about users reporting connection issues.

**Comment by woogerboy21** [comment]
Any chance a list of expectations for what this is looking for could be built?

**Comment by tooomm** [comment]
There is no single log entry for connections. It should help with troubleshooting to include some important info.

It could say something like:

```
establishing connection to server "host domain name" at "port number"
domain name got resolved to "ip" address
connecting as "username"
connected successful
```

**Comment by tooomm** [comment]
https://github.com/Cockatrice/Cockatrice/pull/2275#issuecomment-260163205

>Or are you wanting the ability to see what those **missing features** might be? If so I wouldnt suggest it be in some buried popup window but possibly in the **debug log**. Maybe on startup?

**Comment by ZeldaZach** [comment]
We don't have a good idea of what we'd want, so I don't see a reason for this rn
