### ISSUE TITLE
Feature suggestion: Notification on Endstep

### ISSUE THREAD

**Issue by ThomasDautzenberg** [Cockatrice/Cockatrice#2198]
For the purpose of remembering EoT triggers, I suggest a feature like: Player->'Name'->"Get notified on endstep."
This could be a chat message (even a public one, since it might not be your turn next), a popup or a sound, making sure you remember there was something yout wanted to do on this endstep.

**Comment by Daenyth** [comment]
That sounds like a nicely ergonomic suggestion. My one hesitation with it
is that it relies on your opponent using phases correctly. Do you see most
people using them?

**Comment by ThomasDautzenberg** [comment]
In my experience, most players go to their endstep when they are ready to pass the turn. Correct usage for things like 'start of combat' is mixed.
One possible solution to that, though maybe too clunky, would be to let the game jump to the marked phase if it would be skipped.
For starters, I think a feature exclusively for the endstep would suffice.

**Comment by Daenyth** [comment]
I agree it would be best placed for just the end step

**Comment by tooomm** [comment]
linking https://github.com/Cockatrice/Cockatrice/issues/2008

**Comment by ZeldaZach** [comment]
Closing as #2008 is more relevant
