### ISSUE TITLE
Remove "Registered Users Only" if the server is registered users only

### ISSUE THREAD

**Issue by poixen** [Cockatrice/Cockatrice#2201]
If a server requires registration to join, then we should remove the option in client to create a `Registered Users Only Game`. It creates clutter.

**Comment by Daenyth** [comment]
This also relies on the server telling the client its settings. Once that
happens this is reasonable enough

**Comment by tooomm** [comment]
linking https://github.com/Cockatrice/Cockatrice/issues/1702

**Comment by ZeldaZach** [comment]
Dupe #1702
