### ISSUE TITLE
Missing window decorations

### ISSUE THREAD

**Issue by skwerlman** [Cockatrice/Cockatrice#2203]
<b>OS:</b>
Sabayon 16.11

<b>Cockatrice version:</b>
Version a7a0ea2 (2016-09-25)

---

<br>

(Might be related to #2174?)

When I open user information or the debug log, the window that pops up has no decorations.
In the case of the debug log, I cannot interact with any other cockatrice windows _(not sure if intentional? seems counterintuitive to me, at least)_, but I can close the window by hitting ESC.
The user information window can only be closed by right clicking on the title bar and selecting 'Close'.

**Comment by ZeldaZach** [comment]
Same problem on mac that you cannot interact w/ the client when debug is open. I really don't agree with it currently and may consider a reversion. cc @ctrlaltca @Daenyth

**Comment by tooomm** [comment]
@ZeldaZach It has always been like that, on windows as well. Same for many other windows like about or settings.

For debug though it would be very helpful!

**Comment by ctrlaltca** [comment]
> (Might be related to #2174?)
Window decorations are drawn by the theme Qt is currently using.
Maybe the theme you are using doesn't support window decorations on those special kind of dialogs.

In #2221 i moved the debug log from a dialog to a tab, this should fix part of the problem.

**Comment by ctrlaltca** [comment]
Can you check if the bug is caused by https://github.com/adapta-project/adapta-gtk-theme/issues/236 ?

**Comment by skwerlman** [comment]
It's not quite the same, since their issue allowed them to click in the correct spot to close the window. I just tried that with no luck.
Trying again with a different theme, the 'X' _does_ appear for the user details window and log. I suppose its a bug in Adapta, then.

**Comment by ctrlaltca** [comment]
Probably we are creating the dialog in a way that Adapta is not able to handle correctly.
Do you see the same problem in other dialogs, too? This could help us undestand what causes the problem and try to avoit it:
 * Debug log => YES
 * User information => YES
 * Connect dialog => ?
 * Register dialog => ?
 * Create token => ?
 * Create game => ?
 * Edit avatar => ?
 * Edit Password => ?
 * Edit token => ?
 * Edit user => ?
 * Game filters => ?
 * Load deck from clipboard => ?

**Comment by skwerlman** [comment]
All dialogs listed are missing the close button.

**Comment by ctrlaltca** [comment]
Ouch, i suppose we can't really workaround this if no dialog works..

**Comment by skwerlman** [comment]
Well, right now, I'm switching to QT5.7 to get theming to work; maybe once that's set up I'll be able to provide more helpful info

**Comment by tooomm** [comment]
Is this still an issue?

<br>

>I'm switching to QT5.7 to get themeing to work

@skwerlman which Qt did you use before?

**Comment by skwerlman** [comment]
> Is this still an issue?

i have no idea if this is still an issue, as i haven't used sabayon or cinnamon de in a while.

> which Qt did you use before?

iirc, it was 5.5.

**Comment by ctrlaltca** [comment]
It's not nice to say it, but:
* i don't think we have a lot of user running that specific distro (sabayon) with that specific theme (adapta); to be honest, i never heard about the theme once outside this ticket.
* since any qt dialog was affected by this problem, i'm not sure it's something that we can really fix from our side.

**Comment by tooomm** [comment]
People can let us know if this is still worth looking into...
