### ISSUE TITLE
Deck editor/card list filter: Add "Greater than / Less than" filters

### ISSUE THREAD

**Issue by dev-id** [Cockatrice/Cockatrice#2205]
Feature request: Allow greater than / less than in deck editor filters (for CMC, Loyalty, Power, and Toughness... and maybe rarity, if we're ambitious.)

I think the easiest way to implement is to allow and translate the characters > < and = in the data entry box, rather than adding new selectors.

**Comment by ZeldaZach** [comment]
I always considered this, but it looks like we'd have to rewrite the filters.

**Comment by tooomm** [comment]
>Feature request: Allow greater than / less than in deck editor filters (for CMC, **Loyalty**, Power, and Toughness

We don't even allow to filter for `Loyalty` right now. Would it be reasonable to have that?

**Comment by Daenyth** [comment]
Yes
