### ISSUE TITLE
Flip cards (Ascendant/Essence) from SOK not working as intended

### ISSUE THREAD

**Issue by aeschenkarnos** [Cockatrice/Cockatrice#2207]
Homura, Human Ascendant and its fellows in SOK (Kuon, Erayo, Rune-Tail and Sasaya), the "flip cards", now show up in decklists as "unknown" cards, and the Essence versions instead appear in the database.

This is unlikely to be a MTGJSON problem as the iOS app Decked Builder also uses MTGJSON, and does not have this problem.

The workaround is to create the Essence card as a token, eg Ctrl-T "Homura's Essence" however the cards have also lost the "Create Related Card" ability. I suspect that the bug will be found in the code having to do with the "Create Related Card" function.

This is also the case for the CHK and BOK cards eg Bushi Tenderfoot, Budoka Gardener, Budoka Pupil etc.

![essence_problems](https://cloud.githubusercontent.com/assets/15379324/19148812/de861790-8c01-11e6-93d1-5346a588ea68.png)

**Comment by skwerlman** [comment]
This is a known issue with MTGJSON: https://github.com/mtgjson/mtgjson/issues/240

**Comment by tritoch** [comment]
mtgjson has fixed the issue.
