### ISSUE TITLE
Log Search Function

### ISSUE THREAD

**Issue by JineteDV** [Cockatrice/Cockatrice#2211]
<b>OSX 10.11.6</b>

<b>Version 277d7e2 (2016-06-30)</b>

---

<br>
![screen shot 2016-10-10 at 9 48 10 am](https://cloud.githubusercontent.com/assets/6514656/19250649/7d6011e0-8f09-11e6-951d-a30e0e0a9b72.png)

Just searching for a word yields no results but putting percent signs around it (%asshole%) let me find what I was looking for.

**Comment by ZeldaZach** [comment]
I feel this is correct as this is a direct SQL query you're executing and it is searching for messages that are exactly "asshole" vs containing it.

<img width="171" alt="screenshot 2016-10-10 17 42 48" src="https://cloud.githubusercontent.com/assets/7460172/19252117/faab08f6-8f10-11e6-9b11-32e66bfe63dc.png">

If you think we should change it to default <kbd>%$MESSAGE%</kbd> I wouldn't oppose, but I don't this to be "broken"

**Comment by JineteDV** [comment]
Sure, that'd be more clear

**Comment by Daenyth** [comment]
Wait they can put in raw data to the query? We need to check this for
injection attacks to make sure they can't take over a server.

**Comment by tooomm** [comment]
An explanation to the user should be added as well, what they can input and how to work with different queries.

**Comment by woogerboy21** [comment]
> Wait they can put in raw data to the query? We need to check this for injection attacks to make sure they can't take over a server.

The code uses PDO prepared statements.  It should be safe.

**Comment by skwerlman** [comment]
> The code uses prepared statements. It should be safe.

Probably still worth a check...

**Comment by ctrlaltca** [comment]
> Wait they can put in raw data to the query?

A '%' is a normal character, but has a special meaning when the mySQL query is comparing items using the `LIKE` operator:

```
With LIKE you can use the following two wildcard characters in the pattern:
% matches any number of characters, even zero characters.
_ matches exactly one character.
```
(source: http://dev.mysql.com/doc/refman/5.7/en/string-comparison-functions.html)

> Probably still worth a check...

The code uses prepared statements. It *is* safe against sql injections.

**Comment by Daenyth** [comment]
Yep, that's all I wanted to check. This is still fairly awful since they
can do a crappy query that can't be indexed

**Comment by Daenyth** [comment]
Ideally we could split the code so that the db query portion could be
replaced with a lucene search over logs or something. I think the log
search stuff wasn't really designed all that much

**Comment by woogerboy21** [comment]
@Daenyth Log searching is a terrible idea.  Not to mention logging most the time is disabled since there is no real logging level implemented and it puts a considerable strain on the disks to write out every game event / action and server level message that happens.

**Comment by ZeldaZach** [comment]
Related to #2487
