### ISSUE TITLE
Linux install- won't read .xml path

### ISSUE THREAD

**Issue by zoomzilla** [Cockatrice/Cockatrice#2212]
<b>OS:</b>
linux peppermint 7

<b>Cockatrice version:</b>
unknown(most recent download from cockatrice website)

___
<br>

After downloading cockatrice(via the debian package for i386 from here:  http://packages.bodhilinux.com/bodhi/pool/stable/c/cockatrice/?C=S;O=A
I've successfully installed the program.  Upon opening, it takes me the settings screen where i can choose the paths for decks, tokens, xml, etc.  The default path for the xml is blank.  All others have paths listed.  No matter what path I set for my working xml file(i'm currently using it on windows) it gives a message stating that my card database is invalid:  "Your card database is invalid. Would you like to go back and set the correct path?"
If i choose yes I can stay there and try to browse for another path, but none work, even if I put it as the same path as one of the others.  If I choose no it closes.  I  can't actually get to the chat screen or deck builder.  
When I try running oracle there is no set data. Even if I choose a local file and choose my working xml it goes through the motions and tells me 0 cards imported.  
In the windows version I've always been able to show cockatrice where my xml is located, even if its on the desktop, and it will find it.  
I'm a newb at linux and can't compile without copying and pasting others instructions which is why i am forced to use the debian package.  Its entirely possible I've not even correctly 
installed the package but i've never got this far before and a native linux install is just out of reach so I'd appreciate any advice.  Thanks so much for your time, I'll gladly answer any other questions.

**Comment by ctrlaltca** [comment]
You downloaded a package dated 2013 from the website of the "Bodhi Linux" distribution.
A lot of things changed since 2013, my hairs went gray and oracle is not able to fetch card data from the gatherer like it did back in those years.
I suggest you to uninstall that old package and try downloading one from the official cockatrice website: https://cockatrice.github.io/
Since Peppermint is based on Lubuntu, you should be fine using the Ubuntu package we provide.

**Comment by Daenyth** [comment]
@zoomzilla please let us know if that doesn't fix your problems
