### ISSUE TITLE
"Aether" cards bug

### ISSUE THREAD

**Issue by MrAAA264** [Cockatrice/Cockatrice#2216]
OS
Windows 7
Cockatrice version
Version 2d43ab9 (2016-02-17)

After the KLD orical update all of my Aether cards have been turned to blank cards. i cant pull them out and put them back in with out having this problem.

i made a video explaining this more in detail 

https://www.youtube.com/watch?v=1umfD-k2lww&feature=youtu.be

Becuz of this bug, all of my decks that use aether cards are now unusable

**Comment by Psithief** [comment]
This has been fixed in the latest development versions.

Alternatively, you can change the type of deck format using the "Save As" option and adding the `.cod` extension. The issue won't occur for that deck file format.

**Comment by tooomm** [comment]
@MrAAA264 Psithief is talking about a development version you can download here: https://bintray.com/cockatrice/Cockatrice/Cockatrice-git/0.0.1%7Egit20161011.a4b1a79#files

Keep in mind that this version might cause other problems.

**Comment by woogerboy21** [comment]
Should this issue be closed then?

**Comment by Psithief** [comment]
Yes
