### ISSUE TITLE
Use `utf8mb4`, not `utf8` in Servatrice

### ISSUE THREAD

**Issue by skwerlman** [Cockatrice/Cockatrice#2218]
I haven't had a chance to test how this affects the server yet, but it looks to me like Servatrice is using the wrong Unicode encoding in MySQL.

Basically, MySQL's `utf8` encoding supports all Unicode code points which are 3 bytes or smaller. Unicode, however, has a number of 4-byte code points which cause problems here.
To fix this, MySQL added the `utf8mb4` encoding in version 5.5.3, which allows for 4-byte code points, and is backwards compatible with the older `utf8` encoding.

More info on this: https://mathiasbynens.be/notes/mysql-utf8mb4

**Comment by ctrlaltca** [comment]
Yay for emoticons in usernames! 💣

**Comment by ZeldaZach** [comment]
Do you think that's a good idea @ctrlaltca ? 😛 

Otherwise, I see no reason why we don't add the 4 byte options

**Comment by skwerlman** [comment]
I just checked, and astral plane chars (including emoji) are already disallowed in names (maybe we can enable them:question:)

**Comment by ctrlaltca** [comment]
> Do you think that's a good idea @ctrlaltca ?

I think it's a good idea, users could copypaste emoticons or text containing other uncommon chars from a webpage directly inside cockatrice, and the server must be able to handle them correctly.
