### ISSUE TITLE
Untap Hotkey doesn't work in multiplayer games

### ISSUE THREAD

**Issue by diversivolent** [Cockatrice/Cockatrice#2219]
<b>OS:</b>
_LInux Mint 18 'Sarah'_

<b>Cockatrice version:</b>
_a7a0ea2 (2016-09-25)_

---

<br>

Hello, for some reason my untap hotkey will not work properly in multiplayer games. Cockatrice was installed using the Ubuntu 16 instructions.

If I'm in a local game, hotkey works. I can hit Ctrl+U and all of my stuff untaps.

All other hotkeys work fine all the time.

If I'm in a solo game on an online server, the hotkey works.

If I play a game with an online opponent, the hotkey does not work.

The above symptoms are the same regardless of which hotkey I bind for untap.

Using the menu untap option, or clicking the untap button on the left pane untaps all of my permanents just fine.

I do not have the appmenu-qt5 package installed.

**Comment by Daenyth** [comment]
That is incredibly weird. I'll see if we can reproduce it.

**Comment by skwerlman** [comment]
I'll try to test this on my copy of Sabayon to see if it's a Cinnamon-specific thing.|

@diversivolent What version of Cinnamon do you have?

**Comment by diversivolent** [comment]
Installed: 3.0.7+sarah

**Comment by chrisacheson** [comment]
I have the same issue on Kubuntu 16.04

**Comment by skwerlman** [comment]
Cannot replicate using cinnamon 3.0.7 from `sabayon-weekly`.

Have you taken a look at "Cinnamon Settings">"Keyboard">"Shortcuts"? It's possible that you have a shortcut in there bound to Ctrl+U.

**Comment by diversivolent** [comment]
@skwerlman Yes I have checked, I do not have a shortcut bound to Ctrl+U. This also wouldn't explain why the issue only occurs in multiplayer games.

**Comment by pjimenez1080** [comment]
Same problem. I had this issue in previous versions. Just updated to Version a85b0dc (2017-01-07) and it persists. I'm running Debian 8.6.

**Comment by MachFour** [comment]
I have the problem as well. I am running Arch Linux, and built cockatrice from Git sources yesterday, using 
`cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -DWITH_CLIENT=1 -DWITH_ORACLE=1 -DWITH_SERVER=0 `.
With default settings, I noticed ctrl-D works to draw, but ctrl-u does not work. Haven't tested other ones.

**Comment by Erotemic** [comment]
Same issue. Built myself on 16.04 with Qt5.

**Comment by Docheinstein** [comment]
I have the same issue on Debian 9.
However bind the "Untap all" action to a different shortcut (in my case Ctrl + O) makes it work even on multiplayer.

**Comment by fearphage** [comment]
Confirming this bug for Ubuntu 18.04.

**Comment by ebbit1q** [comment]
Ubuntu 18.04 cannot reproduce.

**Comment by captflint** [comment]
I've run into the same issue. I built from git sources on Arch Linux. My playtesting partner is running the prebuilt Ubuntu deb package and also is having the same issue. Other shortcut keys seem to be working for both of us.

**Comment by ebbit1q** [comment]
I've spent a long time on this, it'll randomly work again if you shuffle the shortcuts around, restart etc. It's plain weird.

**Comment by Grimblee** [comment]
I've had this issue on Linux for years, across multiple Linux and Cockatrice version (my account is 5+ years old).

This happened both when using a .deb or when compiling. Never had the same issue on windows though. Ctrl + U works when goldfishing though.

**Comment by ebbit1q** [comment]
If only someone could actually figure out what's causing this.

**Comment by Grimblee** [comment]
As I have no C skillz I might not be of use I guess ?

Is there some kind of debug logging were you can see everything happening and so can spot if the input is actually taken into account or not ?

There are also tools like strace I believe ?

**Comment by ebbit1q** [comment]
The debug log is always accessible in the client, and no the only way I really see this changing is when I dig really deep into the input layer of qt itself.

**Comment by Grimblee** [comment]
Mmmh, since it only happens on online game maybe it has something to do with server communication ? Maybe it would be interesting to setup a local server and tcpdump incoming paquets from the client to see if you see the untap all command passing by ?

**Comment by ebbit1q** [comment]
Ctrl e (draw multiple) has the exact same issue.

**Comment by fearphage** [comment]
> Ubuntu 18.04 found the issue, I'll see what I can do.

@ebbit1q Can you leave some details here for others? Maybe point to some files you believe the errors are in or some breadcrumbs so others can catch up to where you are?

I'm a developer but very unfamiliar with the code base. If you could provide this shortcut, maybe I or someone else could assist in some way.

**Comment by ebbit1q** [comment]
The truth is I have no clue and my deepest fear is that it's a problem in qt that I don't want to know about. For the rest I'd be happy to help you find your way in any of the codebase even though I'm unfamiliar with half of it.

**Comment by ebbit1q** [comment]
this problem is solved by #3898 you can now unfocus the chat using esc and keep the functionality of using these shortcuts in the lineedit widget, however ctrl u wouldn't do anything if there is no chat message of course.
