### ISSUE TITLE
Discuss: Fetch server list from online

### ISSUE THREAD

**Issue by ctrlaltca** [Cockatrice/Cockatrice#2226]
Currently cockatrice (and the webclient) bundles an hardcoded list of servers.
We could serialize the info present at https://github.com/Cockatrice/Cockatrice/wiki/Public-Servers into a downloadable file and publish it into a new repository (cockatrice-servers).

When cockatrice's connect dialog opens, it will:
- fetch the server list from a predetermined url;
- try to ping each server name, and display the result;
- (advanced, needs proper design): connect without logging in and ask the server for basic informations (requires registration / accepts new registrations / has free slots for new users / current num of users and games / planned shutdown / whatever )

**Comment by woogerboy21** [comment]
What idea's did you have on who would maintain the list and were would it be stored?

**Comment by Daenyth** [comment]
We should maintain the official list as a json on github.

I'd like to wrap this into a more general login panel that introduces a protocol update which allows a client to (without a session) ask a server about itself - online status, user count, registration rules, etc.

**Comment by Daenyth** [comment]
That would be #742 I believe

**Comment by woogerboy21** [comment]
It should prob also include #2189 as well.

**Comment by skwerlman** [comment]
> who would maintain the list

I would be fine maintaining the list of public servers as a separate repo on here.


> Should the "pre-determiined url" be client side editable?

I can see this becoming a source of very confusing problems for users

**Comment by Daenyth** [comment]
I'll write up what I picture for this tonight (hopefully). at work atm so I can't get into detail. But we should store server info as a whole unit and let users add/remove, rather than individual unconnected text fields

**Comment by woogerboy21** [comment]
I actually started to think about this in regards to implementing the protocol adjustments and code to make the requests and almost out the git-go (see what i did there) came up with some questions.  Seeing as ping is not something built in to any library (like qt libraries) we would have to write a custom set of functions to make it happen.  Is ping really something we want to do?   What is the thought process behind using ping?  I am assuming you want to test to see if a server is responding on the IP that the name resolves to and if it does yet the connection to the server isnt made we could say something like "server is up but not accepting connections? 

If this is the case how do we even know if the IP address resolved from the name is even a cockatrice server? Some one could easily fat finger a server name and this result could occur and the user would simply think "oh woogerworks is down" when in fact they had made the error by a bad copy/paste or mis-spelling.

Or are we simply interested in making a connection and if it succeeds request the data we are looking for and if it fails assume the server is offline/old?

Also there is a few issue's about this open now with various amounts of discussion going on in them.  Maybe we should consolidate the issue's and stick to a single issue case for discussion?

**Comment by ctrlaltca** [comment]
> Is ping really something we want to do? What is the thought process behind using ping?

I agree that ping is suboptimal, and we should avoid using it. I don't remember if when i first opened the issue i meant an ICMP ping or some other "sort of", but i see all the cons of forcing people to keep their server open to ICMPs.

> If this is the case how do we even know if the IP address resolved from the name is even a cockatrice server?

You are right on this point, too. @skwerlman proposed (https://github.com/Cockatrice/Cockatrice/issues/2189) to use a specific dns entry for cockatrice in order to achieve autodiscover (like https://tools.ietf.org/html/rfc6764). This could work to solve the problem, but it will also probably cut out any amateur server not having control over a dns domain.

> Or are we simply interested in making a connection and if it succeeds request the data we are looking for and if it fails assume the server is offline/old?

That's probably the best we can do, alongside adding a way to refresh the server list from github from inside cockatrice ("update server list" button, that's it).

Then, we should be able to determine why the server is not working and try to inform the user.
Let me try to figure out the possible states:

We first try to resolve the server's hostname to a valid IP address; if that doesn't return a valid result, we should inform the user that "the server name is not valid (doesn't exist? anymore?)".
We can then try to connect to server_ip:port with a short timeout (10 secs?). We have two possible failures here: connection timeout or connection rejected: in both cases either the server or servatrice are down, or the user entered a inexistent but valid server name (eg. google.com), or an invalid port. I'd tell the user that "no server is currently available at server:port" or that "the server is not currently accepting connections".
If we have a connection, we can send a request for informations and get an answer.
We can create a new ping-like command that can be issued only before logging in, and only once per session. Since the request will hit all the servers almost every time a new cockatrice is opened, the server reply should only contain informations that can be easily cached in RAM, to avoid any easy way to DOS a server.

> Also there is a few issue's about this open now with various amounts of discussion going on in them. Maybe we should consolidate the issue's and stick to a single issue case for discussion?

So, possible linked issues i've found out by now: 
 * DNS Autodiscover: https://github.com/Cockatrice/Cockatrice/issues/2189
 * Connection dialog port problems: https://github.com/Cockatrice/Cockatrice/issues/2070 (not really related, but reworking the whole thing would affect it)

Shall we merge the register and connect dialog in order to have a single list of servers? If yes:
* Propose users to register to a server: https://github.com/Cockatrice/Cockatrice/issues/1672
* Server dropdown in reg diag: https://github.com/Cockatrice/Cockatrice/issues/1433
* Per-server creds: https://github.com/Cockatrice/Cockatrice/issues/1371

**Comment by tooomm** [comment]
also linking https://github.com/Cockatrice/Cockatrice/issues/742

**Comment by ZeldaZach** [comment]
Based on my new implementation, it should be fairly easy to import numerous servers using the `addNewServer()` function... might need a protocol update to do it though

**Comment by Daenyth** [comment]
I think the next action on this is to spec a json file we can maintain (on the .io website?) that cockatrice knows to check for. Probably for now a suggested menu name, host, port is enough

**Comment by skwerlman** [comment]
I think it might make more sense to have a dedicated repo so it's more clear where to go if you want your server advertised.

**Comment by tooomm** [comment]
>For the json file, it should only need a server's address/port, since we'll have the server advertise the other information on its own.

In the current draft of the server status protocol in https://github.com/Cockatrice/Cockatrice/issues/2474 there is no `server name` included.

So i would go with @Daenyth here
>Probably for now a suggested menu name, host, port is enough

**Comment by skwerlman** [comment]
> In the current draft of the server status protocol in #2474 there is no server name included.

Ah, I didn't realize that wasn't in there. Is there a reason why not?

**Comment by Daenyth** [comment]
Because I didn't think of it. It's reasonable though, I think there's already a server-side config for server name

**Comment by tooomm** [comment]
Some more thoughts by @skwerlman about how the client could handle such a list:
https://github.com/Cockatrice/Cockatrice/pull/3163#issuecomment-378220433

**Comment by ZeldaZach** [comment]
I'ma play around with this today for fun. Lets see what I can come up with
