### ISSUE TITLE
Shortcuts stop working until device restart

### ISSUE THREAD

**Issue by Shiaulis** [Cockatrice/Cockatrice#2229]
<b>OS:</b>
MacOS 10.12 (16A323)

<b>Cockatrice version:</b>
Version 277d7e2 (2016-06-30)

---

<br>

_Actual behavior_
In some situations shortcuts stop to work. Only restart helps to restore correct work of all shortcuts

**Comment by Daenyth** [comment]
Can you give us anything else to on here? I haven't seen this personally.

Did you use an older version and not have the problem? Older version of OSX? Always had it? What situations make it stop working? Anything in the debug log?
