### ISSUE TITLE
Typing \@ in chat causes Cockatrice crash

### ISSUE THREAD

**Issue by MotherofRuins** [Cockatrice/Cockatrice#2232]
<b>OS:</b>
Windows 7 Home Premium SP1

<b>Cockatrice version:</b>
d55e44e (2015-09-23)

___
<br>

Typing \@ in chat and hitting enter causes Cockatrice to crash.  Any other char other than @ after a \ seems fine.  Sometimes chars before or after \@ in the chat line inhibit this behavior.

**Comment by woogerboy21** [comment]
OH I am so trying this!

**Comment by woogerboy21** [comment]
I think this has been fixed.  Im running buil 277d7e2 (2016-06-30) and it doesnt cause a crash.

**Comment by ZeldaZach** [comment]
I just tested this on OS X 10.12 d55e44e and 2dd7158. Neither version experienced a crash when I typed `\@` in the main chat and then hit enter.

Maybe this bug was fixed at some point?

**Comment by Psithief** [comment]
@ZeldaZach Try on an account with only regular user permissions?

**Comment by woogerboy21** [comment]
@Psithief my regular account doesn't crash when i try and do this.

**Comment by Daenyth** [comment]
@MotherofRuins please reopen if this is a problem on recent versions
