### ISSUE TITLE
create repo for themes?

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2233]
After reading this reddit post:
https://www.reddit.com/r/Cockatrice/comments/58lmjz/themes_by_kimchi_no_longer_available/

And checking our linked themes in the wiki:
https://github.com/Cockatrice/Cockatrice/wiki/Themes#custom-user-created-themes

I realized that it might be better to have a central place for themes and ensure availability and quality.
Thoughts?

(some of the themes contain maybe problematic image content, can we held responsible for that if we link to it from the wiki?)

**Comment by ZeldaZach** [comment]
Unfortunately it's not our responsibility to host themes as they are 3rd party and may or may not follow all copyright laws. (This is my opinion on the subject, so I don't think we should be involved)

**Comment by woogerboy21** [comment]
if this were to occur, our repository would only have pretty generic content (as @ZeldaZach mentioned).  Im not against the idea, but it would have to be monitored and maintained fairly strict.

**Comment by tooomm** [comment]
Monitoring and maintaining shouldn't be a big deal, it's a few PR's (+checking them once) for new themes from time to time. And it would allow for many new options.
But since we need to look twice about the content it would probably not result in as demanded themes.
I'm fine with throwing that idea away. 🗑 

<br>
>Unfortunately it's not our responsibility to host themes as they are 3rd party and may or may not follow all copyright laws.

Question still stands for me: It still might be problematic to link to such content.
Maybe it's just europe, but in my county we need to put special disclaimers on basically all normal webpages about links etc. ...

**Comment by Daenyth** [comment]
I'd rather not keep it in the repo since it's a lot of binary files. I also
don't like the idea of hosting the actual files since people are going to
end up using copyrighted images

**Comment by Daenyth** [comment]
Linking to it shouldn't be a problem

**Comment by tooomm** [comment]
Ok, all said I guess. :)
