### ISSUE TITLE
Reconnecting to rooms breaks them

### ISSUE THREAD

**Issue by LethalPigeon7** [Cockatrice/Cockatrice#2234]
<b>OS:</b>Win 7 SP1
<b>Cockatrice version:</b>c3ef53d (2016-10-18)

---

This has happened to me at some point before, just thought it was a lone bug back then, whenever I connect and am already in a room, the screen shrinks and then card art stops working.
<b>Pics: </b>http://imgur.com/a/jDLnV

**Comment by ZeldaZach** [comment]
I don't know much about this, but if you come across it again let us know!

**Comment by LethalPigeon7** [comment]
This is still a problem in exactly the same way it was when I made the ticket. If you dont know whats causing it I understand not looking into it much, but there's no need to close the ticket.

**Comment by tooomm** [comment]
Can you try to record a gif maybe?

Which monitor size do you use?

**Comment by LethalPigeon7** [comment]
No, because I would need someone else to be in the room for it not to autoclose, and gif recording slows me down to one frame a couple seconds, not sure I could make a gif even if I found someone who had patience and time to kill.  
I'm on a 1024x600 notebook plugged into a 1280x1024 monitor.

**Comment by LethalPigeon7** [comment]
H...uh. The battlefield still shrinks to a handful of pixels for a couple seconds before expanding, but the pictures load afterwards. Close this I suppose? Weiiiiiiiird.

**Comment by tooomm** [comment]
Well, as long as it's gone somehow. :)
If this is no longer an issue for you (and you seemed to be the only one), just go ahead and close the issue. You always have the power to close issues that you created by yourself.

But make sure to let us know what changed or what fixed it while closing!
(you did that in this case already, so 👍 )

**Comment by LethalPigeon7** [comment]
Well I didn't do anything. For a long time, on the rare occasion where the server crashed or my internet connection flat out died, I just saw that the screen shrunk and left the room saltily. Somewhere along the line, something about my setup or the code changed in a way that accidentally made it recover after it weirds out, and I just never found out because I assumed it was broken and didn't bother to check. Welp if it works it works, thank you for reopening it for the short while regardless.
