### ISSUE TITLE
connection issue

### ISSUE THREAD

**Issue by Jinxstands4Jinx** [Cockatrice/Cockatrice#2235]
I am unable to connect.  I start like normal and go to connect and i get "unknown login error -1. This sally means that your client is out of date, and the server sent you a reply your client does not understand.  I check for updates and is syas I am up to date.  What am I missing? I am watching this post so please reply soon as cockatrice is not working.

**Comment by Jinxstands4Jinx** [comment]
finally worked an hour later

**Comment by tooomm** [comment]
The problem was most likely due to the server being full. We are about to release a new version which will let you know about this case. The current release just can't tell you what's going on. Stay tuned.
