### ISSUE TITLE
Unknown login error 1

### ISSUE THREAD

**Issue by philipcliang** [Cockatrice/Cockatrice#2238]
OS:
Windows 10

Cockatrice version:
323fc06 2016-02-02

I get unknown login error 1 even though update says I'm up to date.

**Comment by skwerlman** [comment]
Dupe #2231

This cause of this message was explained in the comments on that issue.

Also, if you need further clarification, please comment on your existing issues that have been closed instead of recreating the same ticket repeatedly.

**Comment by Daenyth** [comment]
Just to make it clear since there's been a bit of unfortunate information sharing: this is because the server is full right now. We're releasing an update shortly that will produce a more friendly error message.
