### ISSUE TITLE
Investigate using the Scryfall API for HQ card images

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#2240]
Scryfall is an auth-free api for card searching, and its api endpoints can provide images

https://scryfall.com/docs/api-methods

**Comment by tooomm** [comment]
What's about using this pic link? Did not test it yet

>https://img.scryfall.com/cards/en/!setcode_lower!/!collectornumber!.jpg

**Comment by ZeldaZach** [comment]
I tested that link earlier I think, but it didn't work

**Comment by tooomm** [comment]
`https://img.scryfall.com/cards/en/!setcode_lower!/!collectornumber!.jpg` works like a charm:
>Trying to load picture (set:  "KLD"  card:  "Accomplished Automaton" )
Picture NOT found, trying to download (set:  "KLD"  card:  "Accomplished Automaton" )
starting picture download: "Accomplished Automaton" Url: QUrl("https://img.scryfall.com/cards/en/kld/191.jpg")

<br>
The same as `https://s3-us-west-2.amazonaws.com/echomage/cards/!setcode!/!cardid!.hq.jpg` is working perfectly: (found it on [reddit](https://www.reddit.com/r/Cockatrice/comments/59lp7g/for_all_the_highresolution_junkies_out_there/))
>Trying to load picture (set:  "GTC"  card:  "Act of Treason" )
Picture NOT found, trying to download (set:  "GTC"  card:  "Act of Treason" )
starting picture download: "Act of Treason" Url: QUrl("https://s3-us-west-2.amazonaws.com/echomage/cards/GTC/366305.hq.jpg")

<br>
There might be variances in availability or quality. The last one is supposed to not be as up to date.

**Comment by Daenyth** [comment]
I'd like to redo pic URLs to just be a list we try in order

**Comment by joca-bt** [comment]
For some reason it's not working for me. I've also set the fallback URL to the default primary but it's not fetching anything.

**Comment by Daenyth** [comment]
Got a debug log?

**Comment by joca-bt** [comment]
It appears !collectornumber! is not being expanded.

```
Trying to load picture (set:  "ORI"  card:  "Abbot of Keral Keep" )
Picture NOT found, trying to download (set:  "ORI"  card:  "Abbot of Keral Keep" )
starting picture download: "Abbot of Keral Keep" Url: QUrl("https://img.scryfall.com/cards/en/ori/!collectornumber!.jpg")
Download failed: "Error transferring https://img.scryfall.com/cards/en/ori/!collectornumber!.jpg - server replied: Forbidden"
Picture NOT found, download failed, moving to next set (newset:  "pPRE"  card:  "Abbot of Keral Keep" )
Trying to load picture (set:  "pPRE"  card:  "Abbot of Keral Keep" )
Picture NOT found, trying to download (set:  "pPRE"  card:  "Abbot of Keral Keep" )
starting picture download: "Abbot of Keral Keep" Url: QUrl("http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=0&type=card")
Picture downloaded, but blacklisted, will consider it as not found
Picture NOT found, download failed, no more sets to try: BAILING OUT (oldset:  "pPRE"  card:  "Abbot of Keral Keep" )
QPixmap::scaled: Pixmap is a null pixmap
```

**Comment by joca-bt** [comment]
So I updated Cockatrice to 3498b16 (2016-10-30) and it is now working.

**Comment by tooomm** [comment]
>It's not finding the Alliances version and it is downloading the Masters Edition version instead, however I have MED disabled in my Sets.

Did you check the hints in the `Edit sets...` dialog?
Disabling sets doesn't always prevent pics from downloading.

**Comment by joca-bt** [comment]
Thanks, I had forgotten about it. It makes sense now. But shouldn't the fallback URL be tried before going to other sets? In the second example I posted it seems to jump between URLs and sets.

Wouldn't
Set 1 URL 1
Set 1 URL 2
Set 2 URL 1
Set 2 URL 2
make more sense?

**Comment by Daenyth** [comment]
#2479
