### ISSUE TITLE
Cockatrice won't start after reinstalling

### ISSUE THREAD

**Issue by SlomoSapien** [Cockatrice/Cockatrice#2241]
<b>OS:</b>
Windows 7 Pro

<b>Cockatrice version:</b>

Installed the win32 exe from https://bintray.com/cockatrice/Cockatrice/Cockatrice/2016-06-30_Archivist_Madness#files

Now this message comes up.
![err](http://i66.tinypic.com/2nteiw9.png)

___
<br>

**Comment by Daenyth** [comment]
(for anyone watching)

via gitter:
> i don't know how or why... but i just ran the installer again and now it's running
