### ISSUE TITLE
Wrong commit number in "new update available" dialog

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2247]
<b>OS:</b>
Win 10 64bit

<b>Cockatrice version:</b>
4f5c2c3 (2016-10-29)

---

<br>

While the commit number of "All Hallow's Eve" is supposed to be 3498b16 ([Check release page](https://github.com/Cockatrice/Cockatrice/releases/tag/2016-10-30-Release)).
Cockatrice displays a different one:
![updatemsg](https://cloud.githubusercontent.com/assets/9874850/19835721/f99b61e4-9e8e-11e6-82e5-678b59b143e9.png)

**Comment by ctrlaltca** [comment]
I don't understand why are we showing the commit hash to users, since it's not supposed to be meaningful to them.
Showing the release name could be a nicer alternative, along with adding a debug message containing the commit hash that can be helpful for developers/testers.

**Comment by ctrlaltca** [comment]
Back to the original issue, i can't find commit `29a642b` anywhere.
Looking at https://api.bintray.com/packages/cockatrice/Cockatrice/Cockatrice/files it seems that "sha1" is the hash of the file being downloaded, not the hash of the commit / release.

**Comment by tooomm** [comment]
>Showing the release name could be a nicer alternative, along with adding a debug message containing the commit hash that can be helpful for developers/testers.

Nice proposal!

**Comment by Daenyth** [comment]
We should keep the commit id in the about window though since it's really
useful for tickets
