### ISSUE TITLE
Add link to release notes to "update dialog"

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2248]
<b>OS:</b>
Win 10 64bit

<b>Cockatrice version:</b>
3498b16 (2016-10-30) "All Hallow's Eve"

---

<br>

The download updates dialog looks like this atm:
![releasebutton](https://cloud.githubusercontent.com/assets/9874850/19835817/fa42d3b4-9e90-11e6-95f9-8894ae126b9c.png)

I like to see a new button there that links to: 
`https://github.com/Cockatrice/Cockatrice/releases/latest`

It will bring users to the last main release and they can check changes. Right now they don't know what changed etc. until they read here or see the link on reddit for example.

But since Cockatrice immediately closes all windows once the download is done and launches the installer it might be even better to have the button on the notification before you actually download:
![updatemsg](https://cloud.githubusercontent.com/assets/9874850/19835721/f99b61e4-9e8e-11e6-82e5-678b59b143e9.png)
This would allow for a pre-download check, or at least it would open a new browser window and you could read it later, no matter if Cockatrice closes in between.
<br>
It would also be an idea to make the "Yes, I want to download the new version" button make two things:
- open release notes in browser (foreground)
- start downloading in the background
  So the user could read them while trice is getting downloaded and closed, until the installer starts (and pops up in the front) again

Or the "(commit xxyyzz)" text could be clickable and linking to the release notes.
Or the message could be expanded with a link "You can find the release notes here: ..."
To have a clickable link (same as in the about dialog) might be the easiest way of doing it.

Thoughts?

**Comment by Daenyth** [comment]
I really like the idea of adding release notes

**Comment by tooomm** [comment]
fixed with #2362
The `new version available` dialog now includes a link to the release notes on github!
