### ISSUE TITLE
Don't show optional features info msg for EVERY login

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2249]
<b>OS:</b>
Win 10 64bit

<b>Cockatrice version:</b>
3498b16 (2016-10-30) "All Hallow's Eve"

---

<br>

This is a follow up issue ticket from another PR, check there first for information and history:
https://github.com/Cockatrice/Cockatrice/pull/2242#issuecomment-257087739

We decided to get the wording change in quickly and postpone the proper settings handling to annoy users less. Other, a bit more complex, changes like e.g. a custom message window are kept track of here.

**Comment by Daenyth** [comment]
Cockatrice should remember the specific feature names and over to not warn
for them. Additionally it should tell the user the name of the feature

**Comment by tooomm** [comment]
>tell the user the name of the feature

Exactly. Same as for required features with the `Hide Details` button for example.
