### ISSUE TITLE
Allow Subfolders in the CUSTOM image folder

### ISSUE THREAD

**Issue by doombringer777** [Cockatrice/Cockatrice#2250]
<b>OS:</b>
Win 7 SP1

<b>Cockatrice version:</b>
Cockatrice d55e44e

---

<br>

When attempting to add a folder full of custom art for a custom set playtest I had all the images within a subdirectory (Cockatrice\pics\CUSTOM\Dreamscape), however the images within the Dreamscape folder are not detected, meaning I have to place them directly in CUSTOM. 

This is means if I want to have multiple groups of custom images I cannot easily delete or update a single group as all the images end up in a single directory.

I want to propose that sub-directories be supported by the CUSTOM image directory, allowing for easier management of custom content.

**Comment by ZeldaZach** [comment]
I didn't know this wasn't a feature already... weird.

**Comment by Daenyth** [comment]
Solid proposal :+1:
