### ISSUE TITLE
Load Deck causes Crash

### ISSUE THREAD

**Issue by Ansem717** [Cockatrice/Cockatrice#2253]
<b>OS:</b> Windows 10

<b>Cockatrice version:</b>ersion 3498b16 (2016-10-30)
___
<br>

It's as simple as the title says. Once I downloaded the new client (All Hallow's Eve) and now whenever I try to load a deck (Ctrl+O), the "Choose the deck you wish to load" pop-up window appears, and I can see my decks, but the program immediately crashes. I've reinstalled the software four times now. Help?

EDIT: I cannot recall which Cockatrice I was using before this. I was hoping I could fall back to a previous installment, but the three latest installments (Archivist's Madness; The Shadows; Gatewatchers) all seem to be crashing the client when I try to load a deck. Strange.

**Comment by ctrlaltca** [comment]
Please have a look at https://github.com/Cockatrice/Cockatrice/issues/1849#issuecomment-196015331 and see if you find a solution there.
As an alternative, you can try to download the "_win32.exe" version from here and see is it works: https://bintray.com/cockatrice/Cockatrice/Cockatrice/2016-10-30_All_Hallows_Eve#files

**Comment by Daenyth** [comment]
Does it crash immediately or when you select a deck? Can you paste a list
of filenames, or the deck files, respectively?

**Comment by Ansem717** [comment]
Thank you ctrlaltca so much. Sorry for not searching in advance.

I've fully uninstalled Dell Backup and Recovery (after double checking the necessary precautions, apparently it's not an important piece of software) and that solved it!

**Comment by Daenyth** [comment]
I forgot about it too!

At some point it got added to the troubleshooting page: https://github.com/Cockatrice/Cockatrice/wiki/Troubleshooting#cockatrice-crashes-when-i-try-to-save-or-load-a-deck

If anyone else comes across that, point them there
