### ISSUE TITLE
Trying to open oracle through client

### ISSUE THREAD

**Issue by JineteDV** [Cockatrice/Cockatrice#2254]
<b>OS: macOS 10.12</b>

<b>Cockatrice version: 3498b16</b>
___
<br>

![screen shot 2016-10-31 at 1 59 51 pm](https://cloud.githubusercontent.com/assets/6514656/19865483/cef5a974-9f72-11e6-868f-ddaff3269351.png)

I hit the update card database button from the menu and get the above.

![screen shot 2016-10-31 at 2 00 29 pm](https://cloud.githubusercontent.com/assets/6514656/19865498/e4bc2e18-9f72-11e6-9051-2837960b2301.png)
If I try it again I get that. :(

**Comment by ctrlaltca** [comment]
Where are you running cockatrice from? A new security feature introduced in macOS Sierra 10.12 called "App Translocation" is causing the issue, but it should trigger only when cockatrice is run from inside an archive (dmg, zip, iso, a cdrom ...).
Background info here: https://eclecticlight.co/2016/06/16/macos-sierra-will-break-many-installers-and-updaters/

**Comment by ZeldaZach** [comment]
I just tested the updater feature and it works as expected, when the cockatrice.app and oracle.app applications are moved into the same directory (i.e. /Applications).

Looking at the popup message, it seems like it was run from the boot disk dmg download, which is usually troubling. Ctrlalt's comment also further reassures that this could be a problem.

Recommended approach to fix for users: Copy the two apps into your Applications folder.

**Comment by JineteDV** [comment]
I copied from from the installer into a folder on my desktop, this is good to know thanks.

**Comment by Daenyth** [comment]
In general with OSX, you're never supposed to run apps from inside a DMG. Maybe we can have trice detect this and give a preemptive error on launch

**Comment by tooomm** [comment]
>In general with OSX, you're never supposed to run apps from inside a DMG. Maybe we can have trice detect this and give a preemptive error on launch

Ticket?

---
Can somebody explain to me what you are supposed to do with the .dmg download then?
I try to understand to help new players and tell them how to properly install trice on mac.

**Comment by Daenyth** [comment]
You drag the applications to the applications folder, same as any other
dmg. Maybe we can get cpack to make a graphic with drag like some others
have

**Comment by tooomm** [comment]
>You drag the applications to the applications folder, same as any other dmg.

So you drag the single .dmg which contains cockatrice and oracle?

I'm a bit confused because of zach's comments:
>when the cockatrice.app and oracle.app applications are moved into the same directory
...
> Copy the two apps into your Applications folder.

**Comment by Daenyth** [comment]
http://apple.stackexchange.com/questions/64845/how-do-i-install-applications-from-a-dmg-file
