### ISSUE TITLE
Forgot Password =(

### ISSUE THREAD

**Issue by redcrow87** [Cockatrice/Cockatrice#2258]
<b>OS:</b>
WINDOWS 10

<b>Cockatrice version:</b>
3498b16 (2016-10-30)

___
<br>

So I feel silly for asking but is there a way to recover your password when logging into Cockatrice? (on the woogerworks server, if that makes a difference)

I saved all my deck only online and now that I update versions I can't remember the login. Though I think i know the username correctly.

Thanks

**Comment by ZeldaZach** [comment]
You'll need to email the server operator for help with that.

**Comment by redcrow87** [comment]
Does that "Contact Us"even work? I just tried using it and nothing really happens when I click submit. =/

**Comment by Daenyth** [comment]
cc @woogerboy21 

In-client password recovery doesn't exist yet, but it's planned when we can get to it
