### ISSUE TITLE
Create Multiple Tokens

### ISSUE THREAD

**Issue by tritoch** [Cockatrice/Cockatrice#2262]
I would like to be able to create multiple tokens in the create token dialog.  Then a future enhancement would allow 'Create Related' to store the number of tokens a card usually creates (IE Lingering Souls would have 'Create 2 1/1 Spirits')

**Comment by tooomm** [comment]
Interesting idea! 👍

**Comment by Jinxstands4Jinx** [comment]
Would save time, without the need for "cloning" but how would this work for "create X tokens"

**Comment by Nightfirecat** [comment]
Maybe this could be a field in the "Create Token" dialog? (the dialog should probably be changed to read "Create token(s)" or something similar if that's how it is implemented)

**Comment by Jinxstands4Jinx** [comment]
maybe something along the lines of this.   player goes to create related card tab, instead of it saying what token to make it gives 2 options, create a Token, then it has create a set number of tokens, when you click the second option it gives us an option to enter a umber much like setting life total.

**Comment by tooomm** [comment]
Is there a strict pattern for quantities in the card text for token creation that we could parse for? @Psithief ?

The non-smart version could look like this
```
(right click on card)
 - create related card(s)
     - create 1/1 soldier
     - create 2/2 spirit
            -------
     - create X 1/1 soldiers
     - create X 2/2 spirits
```

Where the X-version brings up the dialog which asks for the quantity (like card draw or type of dice)
<br>
To have an additional quantity field in the `Create token` dialog sounds very reasonable in any case!

**Comment by Psithief** [comment]
Tell me where I can put it in the xml and I will take care of it.

The last time I tried putting something new in the xml it was backwards incompatible.

**Comment by skwerlman** [comment]
Unless you're taking about something else, the backwards-incompatible bit was a problem with oracle failing to handle XMLs with unknown tags, and that got fixed. See #1810 and #1901

**Comment by Psithief** [comment]
This would most likely be a new attribute on an existing tag.

**Comment by skwerlman** [comment]
I tested this by changing `<reverse-related>Devout Invocation</reverse-related>` to `<reverse-related count=6>Devout Invocation</reverse-related>`, and as @Psithief suspected, the remainder of the token DB fails to load. I'll open a new issue and link it here.

**Comment by tritoch** [comment]
I like the thoughts so far.

How should cards like Bestial Menace that create 3 different kinds of tokens be handled? No special handling?  It's not covered by the original issue (doesn't create multiple of the same type)

**Comment by Psithief** [comment]
If it is getting into "create a set of cards", it can't be done from the `tokens.xml`, it would have to be a tag of a collection of tags in `cards.xml`, and I don't edit that.

**Comment by Daenyth** [comment]
I don't think that's very high impact of a change right now. Let's table
that for later

**Comment by Psithief** [comment]
> Is there a strict pattern for quantities in the card text for token creation that we could parse for? @Psithief ?
>
> The non-smart version could look like this
>
>``` (right click on card)
> - create related card(s)
>     - create 1/1 soldier
>     - create 2/2 spirit
>            -------
>     - create X 1/1 soldiers
>     - create X 2/2 spirits
> ```
> Where the X-version brings up the dialog which asks for the quantity (like card draw or type of dice)
> To have an additional quantity field in the Create token dialog sounds very reasonable in any case!

How does this work in the new paradigm?

Let's take examples with as many edge cases as we can:

From Under the Floorboards |
----------------------------- |
Madness {X}{B}{B} (If you discard this card, discard it into exile. When you do, cast it for its madness cost or put it into your graveyard.)
Create three tapped 2/2 black Zombie creature tokens and you gain 3 life. If From Under the Floorboards's madness cost was paid, instead create X of those tokens and you gain X life. |

This card creates 3, or X tokens, but we don't want to take away the ability to create a singular token if a player makes a mistake or is under the effects of `Leyline of Singularity`.

Elspeth, Sun's Champion | 
----------------------------- |
+1: Create three 1/1 white Soldier creature tokens.
−3: Destroy all creatures with power 4 or greater.
−7: You get an emblem with "Creatures you control get +2/+2 and have flying."

The keyboard shortcut is creating 'all tokens' on an Elspeth, Sun's Champion. That's is just incorrect; the tokens and emblem can't be created on the same turn.

**Comment by skwerlman** [comment]
> the tokens and emblem can't be created on the same turn

yes, they can: http://gatherer.wizards.com/Pages/Card/Details.aspx?name=The+Chain+Veil

**Comment by tritoch** [comment]
>- Create 3 1/1 Soldier tokens
>- Create Emblem token
>- Create all tokens (3 1/1 + 1 emblem)

I think we should retain the current `Create 1/1 Soldier token` option (singular) in addition to anything we might do with this issue.

>yes, they can

Can't be created at the same *time* by the same *action*

**Comment by skwerlman** [comment]
> by the same action

fair point

**Comment by tooomm** [comment]
>I don't think we should have separate "create x"

Why?
I like to see `Token: 1 2/2 Goblin`, `Tokens: 3 1/1 Soldiers` and also `Tokens: X 4/4 Angel...` right click options based on the reverse related extension with numbers.
For most cards there are no difficult edge cases. And I'm sure we can find a way to deal with them.

>I think we should retain the current `Create 1/1 Soldier` token option (singular) in addition to anything we might do with this issue.

I'm not sure the create a single token is needed.
There is still the create token dialog if there is the rare edge case that something is not working as intended or a card is wrongly tagged. If a card is just creating 3 1/1 soldiers for example, why would you clutter the menu with an additional create 1 soldier option?
If you have a  "Create x token" option, e.g. for [Entreat the Angels](http://gatherer.wizards.com/Pages/Card/Details.aspx?name=entreat+the+angels), a separate option for x=1 is also not needed.
Since `Create x 4/4 Angels...` would just open a dialog where you put the number - you just put a 1 there.

**Comment by Psithief** [comment]
I've just realised I didn't answer this question:

> Is there a strict pattern for quantities in the card text for token creation that we could parse for? @Psithief ?

There are a small number of different ways this is templated on a card. Most are very simple, but there are always edge cases.

Cockatrice needs a separate create X (that doubles as a create 1), but how can it be squeezed to not take up too much space in the context menu?

**Comment by tooomm** [comment]
>Cockatrice needs a separate create X (that doubles as a create 1), but how can it be squeezed to not take up too much space in the context menu?

Since we have already several cards right now with like 3 options this isn't making things worse.

Mostly it's just exchanging `Token: 1/1 Solder` for `Token: 3 1/1 Soldiers`, which isn't expanding the list either. So I guess in general the support to quickly create several token (related to card) will add no entries, or only one to the context menu, no? Also depends on X replacing the create 1 on cards with a variable number.

**Comment by Daenyth** [comment]
> Mostly it's just exchanging Token: 1/1 Solder for Token: 3 1/1 Soldiers, which isn't expanding the list either

This is the behavior I want. I think it's the best balance of compactness + features

**Comment by Daenyth** [comment]
But if the general consensus is that you'd rather have a menu like:

- Create a 1/1 Soldier token
- Create 3 1/1 Soldier tokens
- Create a Whatsit Emblem token
- Create all tokens (3 1/1 Soldier, 1 Whatsit Emblem)

I'm alright with that.

**Comment by ZeldaZach** [comment]
So you'd rather have 4 options then 3 options w/ a dialog?
- Create X 1/1 Solder tokens
- Create an emblem
- Create all

**Comment by Daenyth** [comment]
Yes, dialogs are awful and should be used as minimally as possible

**Comment by tooomm** [comment]
We just need the dialog for the `x` option (like for dice rolls...), I don't think it's needed for any other token option.

**Comment by tooomm** [comment]
We just need the dialog for the `x` option (like for dice rolls...), I don't think it's needed for any other token option.

I would focus on something like this:
>exchanging `Token: 1/1 Solder` for `Token: 3 1/1 Soldiers`
Or `Token: 4/4 Angel` for `Tokens: X 4/4 Angels...`
