### ISSUE TITLE
Invalid  attributes on tags cause the rest of the database to be silently discarded

### ISSUE THREAD

**Issue by skwerlman** [Cockatrice/Cockatrice#2263]
<b>OS:</b>
Sabayon 16.11

<b>Cockatrice version:</b>
~~Version dfc4d99 (2016-10-28)~~
Version 1cebe03 (2016-11-02) (just updated and tested again, issue persists)

___
<br>

~~When doing some testing relating to how #2262 might get implemented, I tried adding an attribute to a `reverse-related` tag. All cards which came after that tag failed to load in a similar fashion to #1810.~~

~~Cockatrice should, IMO, discard unknown attributes and attempt to load tags without them.~~

Turns out I forgot quotes around the attribute's value.

Still, _silently discarding everything_ after the first invalid line is less than preferable.

**Comment by ZeldaZach** [comment]
I can agree with this ticket for sure. Maybe throw a warning that unsupported tags were found and list them?

**Comment by skwerlman** [comment]
(changed the issue, because the problem was different than I thought)

**Comment by Daenyth** [comment]
Cockatrice should detect and warn when a card db file it tries to load fails to parse. Detailed info in the debug log and a modal including the file path at hand

**Comment by ZeldaZach** [comment]
No longer an issue b/c we have a new database version that solves this problem
