### ISSUE TITLE
Hand popout window vs chat feed

### ISSUE THREAD

**Issue by JineteDV** [Cockatrice/Cockatrice#2264]
<b>macOS 10.12.1</b>

<b>Cockatrice version: 3498b16 (2016-10-30)</b>
___
<br>

![show](https://cloud.githubusercontent.com/assets/6514656/20032146/d1adc034-a35a-11e6-92d5-baf90fc4910b.jpg)

If I move the hand popout window over to the right enough so that it's been partly hidden by the chat feed then the next time the chat feed gains an entry and scrolls down, that grayed out block appears. Scrolling up enough to get away from the gray box then scrolling back down will remove it until the chat feed gains another entry and the box appears again.

**Comment by woogerboy21** [comment]
Odd.... do you have a windows box to test this out on?  Sort of sounds like a display manager issue but not sure if I understand the steps to try and reproduce it.

**Comment by ZeldaZach** [comment]
This is no longer an issue
