### ISSUE TITLE
Possibly adding a few features in the future

### ISSUE THREAD

**Issue by LograGx** [Cockatrice/Cockatrice#2266]
<b>OS:</b>
*Win 10.1
Version 632a2db (2016-10-17)

___
<br>

*Explain your Issue/Request/Suggestion in detail here!*
Like-->
- Mass attach to card (highlighted cards) 
- Reveal random card from graveyard (ex. Deadbridge chant etc..)
- A stack timer for those who wait til after a spell has resolved and off the stack to counter.

**Comment by Daenyth** [comment]
You can already mass attach to card: drag around the cards you want to select, right click any of them, attach to, select the target.

random reveal would be good 👍 

I don't see us doing a stack timer, you'll need to actually communicate with your opponent. Any value we pick would be too short for some and too long for others. I don't think it would enhance the experience.
