### ISSUE TITLE
The help / about did not show the version number only '()'

### ISSUE THREAD

**Issue by GuillaumeSeren** [Cockatrice/Cockatrice#2268]
<b>OS:</b>
Gentoo GNU/Linux

<b>Cockatrice version:</b>
games-board/cockatrice-20160506
___
<br>
When you open the help / about menu to show the version it display 'Version ()'.
<br>
I upgraded to last version the problem still occur, any idea ?
<br><br>
Guillaume

**Comment by Daenyth** [comment]
Did you `git clone` the repo before compiling or did you download a zip? The bit inside the `()` is the git sha of the commit, so if you used the zip you won't have it

**Comment by GuillaumeSeren** [comment]
@Daenyth it comes from the zip of each release packaged (20160506, or 20161030), here a screenshot of the last release:

![Image of the menu](https://framapic.org/gallery#tbtVA6d3lRQU/l8KHp1KFcIZd.jpeg)

**Comment by Daenyth** [comment]
Compile from the git repo rather than downloading a source zip and compiling from that.

**Comment by GuillaumeSeren** [comment]
@Daenyth Ah so with the tarball 'official' version there is no more information in the help / about menu ?

Ok I'll compille it from the tree, and report my feedback here.

**Comment by Daenyth** [comment]
I don't think we create any special tarballs. Github does automatic ones
but we don't really use them

**Comment by ZeldaZach** [comment]
They're automatically made and can't be removed, but compiling from source is always better

**Comment by GuillaumeSeren** [comment]
@ZeldaZach These tarball are the one when you make a tag so there quite official and i use them to package cockatrice in several system (gentoo), but despite the sha1 when i compile from the tree I doubt there is more information in the (help/about), so my misunderstanding come from that despite the possible sha1 I hoped for a tag name like 20161030.

Hope it is a bit clearer ;)

**Comment by Daenyth** [comment]
You can manually create a version header before compiling and it will get the version of whatever you put in there - check `cmake/createversionfile.cmake` for how the file should be structured.

**Comment by GuillaumeSeren** [comment]
@Daenyth Yes I will test that.

To summarize my issue, I was hoping to find the version information like 
> "All Hallow's Eve"  2016-10-30-Release 3498b16

Because this information is already on the releases page, but it is not a big problem and could probably be easily fixed by adding those into the help/about menu, not mandatory but nice to have.

And having the 'Version ()' look strange anyway, are you agree ?

**Comment by Daenyth** [comment]
Generally codenames aren't included in the version string - we have git sha and build date.

It looks strange, but that's not how we distribute builds - we build them from git. Both for our precompiled releases as well as our compiling instructions

**Comment by GuillaumeSeren** [comment]
@Daenyth Thank you for taking time to help on my issue.

It is not a usage problem at all, just an idea about what can be displayed on that help/about menu, for those who follow the tags to upgrade.
I just try to help making more people able to use the last version of cockatrice (including myself) to play some legacy magic ;)

**Comment by Daenyth** [comment]
Feel free also to update our compiling instructions on the wiki if they could be more clear or up to date

**Comment by GuillaumeSeren** [comment]
> Feel free also to update our compiling instructions on the wiki if they could be more clear or up to date
Ok I will.

I found a way to inject the 'CodeName Date' in place (./cmake/getversion.cmake) so it will be probably do the trick.

**Comment by GuillaumeSeren** [comment]
So I find a way to add the date in the menu, it is simple but it works.

![Image of the help/about menu with the date](https://framapic.org/80ClS0Y2Lzzm/RKW6gDzd2RBO.jpeg)

I will check the wiki tomorrow.

**Comment by Daenyth** [comment]
Please include the git sha1 or tag you build from. We ask people for the version string when they submit tickets here

**Comment by GuillaumeSeren** [comment]
@Daenyth Fixed !

![Image of the help/about menu with the sha1](https://framapic.org/QUxYKNSI1SQn/LzA8n1D5tQer.jpeg)

I didn't have time to take a look at the wiki but it is on my list.

**Comment by Daenyth** [comment]
Thanks!

**Comment by GuillaumeSeren** [comment]
I've checked the 'Compiling On Linux/Gentoo' section it seems fine as it is, so I did not add anything.
