### ISSUE TITLE
Card back not showing on deck field after adding a custom set.

### ISSUE THREAD

**Issue by yaminoryuu** [Cockatrice/Cockatrice#2269]
<b>OS:</b>
WINDOWS 10

<b>Cockatrice version:</b>
3498b16 (2016-10-30)

___
<br>

Whenever there's a custom set active, the cardback won't show on the deck field. It displays only a as grey background.
The face down cards shows normally.

Theme used: https://www.reddit.com/r/Cockatrice/comments/5azzfe/just_made_a_wooden_based_theme/
Custom set used: https://www.reddit.com/r/Cockatrice/comments/59k126/commander_2016_xml_files/

![5oxal2t](https://cloud.githubusercontent.com/assets/23249408/20118706/ae95f726-a5ec-11e6-8872-696577c43801.jpg)

**Comment by tooomm** [comment]
Is there anything in debug log? (help --> debug log)

**Comment by yaminoryuu** [comment]
here: http://pastebin.com/5XbKJxes

**Comment by ZeldaZach** [comment]
If still an issue, let us know!
