### ISSUE TITLE
Server crash on register

### ISSUE THREAD

**Issue by skwerlman** [Cockatrice/Cockatrice#2270]
<b>OS:</b>
Ubuntu 16.04

<b>Servatrice version:</b>
6962777

___
<br>

https://gist.github.com/skwerlman/eeaf79a9c89b7cc8c887c2aa126a920c

This seems to be caused by #2259

**Comment by ctrlaltca** [comment]
In `Server_ProtocolHandler::pingClockTimeout()`, we need to check if `userInfo` is a valid pointer before calling `userInfo->privlevel()`, eg:

```
if (!userInfo || QString::fromStdString(userInfo->privlevel()).toLower() == "none") {
```

**Comment by woogerboy21** [comment]
Thats odd, this must be a race condition then?

**Comment by ctrlaltca** [comment]
> Thats odd, this must be a timing condition then?
`userInfo` is null until the user has successfully logged in
