### ISSUE TITLE
User count is cut off in account tab

### ISSUE THREAD

**Issue by skwerlman** [Cockatrice/Cockatrice#2272]
<b>OS:</b>
Sabayon 16.11

<b>Cockatrice version:</b>
Version 6962777 (2016-11-08)

___
<br>

![screenshot from 2016-11-09 08-28-34](https://cloud.githubusercontent.com/assets/6954107/20139948/891eb9be-a656-11e6-9be6-31588dbae6fb.png)

**Comment by woogerboy21** [comment]
I think its something odd with your setup....

![image](https://cloud.githubusercontent.com/assets/1361287/20158421/2473a946-a6a8-11e6-9aa2-69b32876508d.png)

**Comment by skwerlman** [comment]
it could be a theme issue. i've been unable to apply any themeing to qt5 apps for as-yet-unknown reasons, so maybe this is an effect of that problem.

**Comment by tooomm** [comment]
It works fine for me on Windows, never realized a problem actually.
Could you localize the themes as the problem in the meantime?

**Comment by skwerlman** [comment]
Looking for this now, I cannot reproduce. It was almost certainly an issue caused by my broken themeing setup.
