### ISSUE TITLE
Feature Suggestion: Filter Import

### ISSUE THREAD

**Issue by ThomasDautzenberg** [Cockatrice/Cockatrice#2273]
When building Standard, you basically filter for the same sets every time. The same happens when you're building Pauper with MTGO rules.

This is why I suggest a feature for importing (and maybe saving) filters.

**Comment by Daenyth** [comment]
There's existing tickets for:
- Persistent savable filters
- Format-based filters

Don't have them handy; when I do I'll link and close this as dupe

**Comment by tooomm** [comment]
>Format-based filters

https://github.com/Cockatrice/Cockatrice/issues/215

>Persistent savable filters

https://github.com/Cockatrice/Cockatrice/issues/722

<br>
Thanks for requesting @ThomasDautzenberg.
Make sure to check out the other tickets to share your ideas and join the discussion.
