### ISSUE TITLE
Unable to compile on debian 8

### ISSUE THREAD

**Issue by TheNofx68** [Cockatrice/Cockatrice#2274]
## Cockatrice Version: f6e4ee9 (2016-11-09) (`cat version_string.cpp | grep STR`)

I first tried the ubuntu .deb package, which is outdated (requiring libprotobuf8, but libprotobuf9 only is available on debian 8).
Then I tried following the guide to compile Cockatrice on debian systems.
Cmake version (`cmake --version`): version 3.7.0-rc3
Qt version 5.7.0/gcc_64

Following the wiki guide, it failed at *all* and *each* steps (outdated guide here too ?).
To resolve every error to this point, I did these steps which were not specified in the wiki:
```bash
export CMAKE_PREFIX_PATH=/etc/Qt/5.7/gcc_64/lib/cmake/
```
Then, in `~/Cockatrice` (and not in `~/Cockatrice/build`) I did cmake .
Then I was able to do make, which now produces the following error I'm unable to solve:
```bash
#( 11/10/16@10:41pm )( artemis@artemis-pc ):~/softwares/Cockatrice@master✗✗✗
   make -j2
[ 63%] Automatic moc for target cockatrice_protocol
[ 63%] Automatic moc for target cockatrice_common
[ 63%] Built target cockatrice_protocol_automoc
[ 63%] Built target cockatrice_common_automoc
[ 63%] Automatic moc for target cockatrice
[ 63%] Automatic moc for target oracle
[ 63%] Built target oracle_automoc
[ 63%] Built target cockatrice_automoc
[ 63%] Generating oracle_cs.qm
/bin/sh: 1: /home/artemis/softwares/Qt5.7.0/5.7/gcc_64/bin/lrelease: Permission denied
oracle/CMakeFiles/oracle.dir/build.make:61: recipe for target 'oracle/oracle_cs.qm' failed
make[2]: *** [oracle/oracle_cs.qm] Error 126
CMakeFiles/Makefile2:396: recipe for target 'oracle/CMakeFiles/oracle.dir/all' failed
make[1]: *** [oracle/CMakeFiles/oracle.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 63%] Built target cockatrice_protocol
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
#( 11/10/16@10:41pm )( artemis@artemis-pc ):~/softwares/Cockatrice@master✗✗✗
   make
[ 63%] Automatic moc for target cockatrice_common
[ 63%] Built target cockatrice_common_automoc
[ 63%] Automatic moc for target cockatrice_protocol
[ 63%] Built target cockatrice_protocol_automoc
[ 63%] Built target cockatrice_protocol
[ 63%] Built target cockatrice_common
[ 63%] Automatic moc for target cockatrice
[ 63%] Built target cockatrice_automoc
[ 63%] Generating cockatrice_cs.qm
/bin/sh: 1: /home/artemis/softwares/Qt5.7.0/5.7/gcc_64/bin/lrelease: Permission denied
cockatrice/CMakeFiles/cockatrice.dir/build.make:61: recipe for target 'cockatrice/cockatrice_cs.qm' failed
make[2]: *** [cockatrice/cockatrice_cs.qm] Error 126
CMakeFiles/Makefile2:272: recipe for target 'cockatrice/CMakeFiles/cockatrice.dir/all' failed
make[1]: *** [cockatrice/CMakeFiles/cockatrice.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```

Did any of you solve these problems ?

**Comment by skwerlman** [comment]
It looks like you need to fix permissions for ` /home/artemis/softwares/Qt5.7.0/5.7/gcc_64/bin/lrelease`. Try chmodding it to 755 and see if that helps.

**Comment by TheNofx68** [comment]
Welp, for all I've tried, I totally forgot to check that, as I never needed that software.

**Comment by skwerlman** [comment]
I'm not certain the wiki is wrong, since it looks like you've installed a few things in non-standard places, unless that's just how it is on debian (i'm not a debian user)

**Comment by TheNofx68** [comment]
Installing Qt5 through the debian repos don't work.
Using the stretch repos provoke conflicts everywhere.
So I installed Qt5 from the Qt website in my software folder (where I install most of my non-packaged softwares). But for the other things, it shouldn't actually act like that
