### ISSUE TITLE
"Socket Error: Host not found" for all public servers

### ISSUE THREAD

**Issue by strideling** [Cockatrice/Cockatrice#2279]
Mac OSX 10.9.5

3498b16 (2016-10-30)
___

Hi there,

Cockatrice won't connect to any of the public servers listed here: https://github.com/Cockatrice/Cockatrice/wiki/Public-Servers (I've tried them all.) I keep getting a "Socket Error: Host not found" for each one.

I'm currently in Chiang Mai, Thailand trying to connect using public wifi. I successfully connected using the same wifi yesterday, and I've tried two different locations, so it seems like it must be something on my end. Any help would be greatly appreciated! Thank you!

**Comment by skwerlman** [comment]
Can you try running `dig mtg.tetrarch.co` in Terminal?

**Comment by strideling** [comment]
![screen shot 2016-11-14 at 4 39 30 am](https://cloud.githubusercontent.com/assets/23449187/20259732/6cd04cec-aa24-11e6-9f18-eb32ea47c62e.png)

**Comment by skwerlman** [comment]
That A-record looks right, so I'm not sure what's going wrong...

**Comment by strideling** [comment]
username: strideling

**Comment by strideling** [comment]
I've tried a few times - both "Register to server" and just "Connect."

**Comment by ctrlaltca** [comment]
CAn you try to connect using `98.114.135.91` (mtg.tetrarch.co) or `158.69.208.38` (woogerworks) as the server address?

**Comment by strideling** [comment]
Oh, hoorah! The 98.114.135.91 worked!

**Comment by skwerlman** [comment]
I wonder why dns failed for cockatrice when dig found the correct record...

**Comment by ctrlaltca** [comment]
OSX Dns cache maybe? Try to reset it: https://support.apple.com/en-qa/HT202516

**Comment by ctrlaltca** [comment]
Anyway, we definitely needs to log this on the debug log.

**Comment by ZeldaZach** [comment]
Seems like a dead ticket at this point.
