### ISSUE TITLE
Fallback download URL not being tried

### ISSUE THREAD

**Issue by joca-bt** [Cockatrice/Cockatrice#2280]
It appears that whenever the primary download URL fails the fallback URL is not tried. Example:

Primary download URL: `https://img.scryfall.com/cards/en/!setcode_lower!/!collectornumber!.jpg`
Fallback download URL: `http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!cardid!&type=card`

Log (trying Mirri's Guile):
```
Trying to load picture (set:  "TMP"  card:  "Mirri's Guile" )
Picture NOT found, trying to download (set:  "TMP"  card:  "Mirri's Guile" )
starting picture download: "Mirri's Guile" Url: QUrl("https://img.scryfall.com/cards/en/tmp/.jpg")
Download failed: "Error transferring https://img.scryfall.com/cards/en/tmp/.jpg - server replied: Forbidden"
Picture NOT found, download failed, no more sets to try: BAILING OUT (oldset:  "TMP"  card:  "Mirri's Guile" )
```

This is specially relevant for older sets. If the download URLs use different methods of identifying cards, e.g. collector number vs card id, bailing out and skipping the fallback URL does not make much sense, as it may find the card.

**Comment by ctrlaltca** [comment]
Please have a look at #1984.
Another dupe: #2192
