### ISSUE TITLE
Mac, hard crash when using (some?) keyboard shortcuts

### ISSUE THREAD

**Issue by arloft** [Cockatrice/Cockatrice#2281]
<b>OS:</b>
*Mac OSX El Capitan, 10.11.6*

<b>Cockatrice version:</b>
*0.0.1~git20161030.3498b16*

___
<br>
I've experienced several crashes (Mac, 10.11.6, Cockatrice version 0.0.1~git20161030.3498b16, latest as of 11/14/16) when using keyboard shortcuts. I was using a previous version of Cockatrice two days ago, experienced the crash when pressing Cmd+P (set P/T), and today (latest version) when duplicating a token (Cmd+J). Pasted the Console logs and attached the 3 crash logs to this Google Doc: https://docs.google.com/document/d/1yoB_SEhmOLm5KvA1hl4XBepDzbjO61fTs6Ey0C9-U7U/edit?usp=sharing.
Attached all 4 files to this ticket as well.

[cockatrice_2016-11-15-132334_BiOnyx.txt](https://github.com/Cockatrice/Cockatrice/files/592829/cockatrice_2016-11-15-132334_BiOnyx.txt)
[Cockatrice-log-111416-111516.txt](https://github.com/Cockatrice/Cockatrice/files/592832/Cockatrice-log-111416-111516.txt)
[cockatrice_2016-11-14-150716_BiOnyx.txt](https://github.com/Cockatrice/Cockatrice/files/592831/cockatrice_2016-11-14-150716_BiOnyx.txt)
[cockatrice_2016-11-14-151546_BiOnyx.txt](https://github.com/Cockatrice/Cockatrice/files/592830/cockatrice_2016-11-14-151546_BiOnyx.txt)

**Comment by Daenyth** [comment]
Can you attach a screenshot of your keymap configuration in your settings?

**Comment by arloft** [comment]
Mine are default as far as I know, pretty sure I've never changed them, but here's a composite screenshot of all the pref tabs:
![mac-cockatrice-shortcuts-prefs](https://cloud.githubusercontent.com/assets/2423302/20331580/42b48df0-ab74-11e6-8847-c75a98ea963c.png)

**Comment by ctrlaltca** [comment]
Closing this issue. A lot of new Cockatrice versions has been released since 2016, and we didn't receive more reports of this crash. Thank you for the original report, and fell free to reopen if it still crashes for you in the last version.
