### ISSUE TITLE
Continuously asking me to register my account?

### ISSUE THREAD

**Issue by IrateHope** [Cockatrice/Cockatrice#2282]
I reinstalled Cockatrice. Could not remember my old account so I made a new one. Registered and such. Went to my email to make sure it worked. I clicked on the link and did what I needed to.

Whenever I try to log in, it asks me to register my account.

Help?

**Comment by Daenyth** [comment]
Is your account activated? You might have better luck contacting the admin
for the server you're having a problem with

**Comment by woogerboy21** [comment]
@Daenyth 
If an account is registered but not active you will be prompted asking for the activation token.  You shouldn't receive the message popup indicating that you need to register.

@IrateHope 
Who did you actually register an account with (what server)?

**Comment by Daenyth** [comment]
Reopen if it's still an issue
