### ISSUE TITLE
Not connecting

### ISSUE THREAD

**Issue by philipcliang** [Cockatrice/Cockatrice#2284]
<b>OS:</b>
*Override this line with the exact operating system you are running! (e.g. "Win 10")

<b>Cockatrice version:</b>
3498b16
2016-10-30

___
<br>

I try to connect but it doesn't connect.

**Comment by Daenyth** [comment]
We can't help you unless you give us more information. A screenshot of the error you're seeing would help

**Comment by Daenyth** [comment]
I'm guessing you're talking about woogerworks. It's down. https://www.reddit.com/r/Cockatrice/comments/5ekhxr/anybody_having_trouble_connecting_to_the/
