### ISSUE TITLE
Slow query

### ISSUE THREAD

**Issue by woogerboy21** [Cockatrice/Cockatrice#2285]
So I've noticed that while reviewing the "mysql_slow.log" there is a continuous slow query happening.  The query is:

```
select count(*) from cockatrice_sessions where id_server = 1 AND end_time is NULL AND connection_type = 'tcp';
```

While locating were this query happens it appears that it is performed at every single login were each socket interface session that gets created queries the database the a count of the existing users that are using the connection type (either tcp or websocket) and checks to see if the count is greater than the maximum number of users that is allowed for that connection type (defined in the servers ini file and defaults to 500 users).

I am curious, is there a way to see when this particular line of code was added / updated?  I don't recall if I added the query to the DB or if it was added when the websocket server was pulled in.  There is a way to query the server for a user count that could eliminate the need for the constant hitting of the database but it doesn't maintain the connection type and was thinking about dropping the connection type limitation code blocks (or possibly commenting them out) as I'm not sure at this point if that functionality is really gaining us anything or causing more of a resource burden.

@ctrlaltca thoughts?

**Comment by Daenyth** [comment]
Git blame the source file to see when it was added. We should be able to
just hold an int in memory and increment or decrement on connection events.
No query needed

**Comment by woogerboy21** [comment]
That was my idea as well .  But wasn't sure if there was a reason I couldn't think of or find that would warrant the current implementation.
