### ISSUE TITLE
.cod files with arbitrary zones

### ISSUE THREAD

**Issue by skwerlman** [Cockatrice/Cockatrice#2286]
As an experiment, I created a .cod file with a `Commander` zone to see how much support there was for arbitrary zone fields in decks. Doing so, I came across a few issues:

- There is no way to get a new zone into the .cod aside from editing the file manually
- The deck hash always reads `INVALID`
- There is no way to access cards in unknown zones, in either the deck editor or in game

Currently, there is already partial support for these zones:

- The deck editor correctly shows new zones and the cards in them
- The deck preview (before a game) correctly shows new zones and the cards in them

Having access to new zones would make certain formats like Commander/EDH a bit easier. It would also make deck building easier for any card game that has more than two parts to a deck (I am sure some exist).
Additionally, being able to define a maybeboard could make deck prototyping easier, since it would allow a player to keep cards they'd like to experiment with separate from their sideboard.

In game, this would require a dropdown (probably repurposing the unnecessary "Sideboard" dropdown) where all zones of the deck would be listed.
In the deck editor, this would require a "Create new deck zone..." function, and a way to move cards directly to the new zones.

The zone i used for testing:
```xml
<zone name="Commander">
    <card number="1" price="0" name="Child of Alara"/>
</zone>
```

**Comment by ZeldaZach** [comment]
The deck hash reads INVALID because there was a flaw in the way the file was generated, and this prevented manipulation (in tournaments) Check #1217 for more on that.

We could always officially "add" new layers into the file for additional zones, but I don't think that will happen until we modify the program to allow users to load in their own mods... 

I'm curious what others thing on this issue though

**Comment by Daenyth** [comment]
As a roadmap item, this should just work. The problem is that specific zone names are hardcoded into the application and there's no way to tell the server what kind of zone they are, and no way to tell the game view how to display them.

**Comment by ZeldaZach** [comment]
Related to #1740
