### ISSUE TITLE
Typing fast in the search box in the deck editor causes Cockatrice to crash hard.

### ISSUE THREAD

**Issue by mpalmujoki** [Cockatrice/Cockatrice#2287]
<b>OS:</b>
OS X 10.11.6

<b>Cockatrice version:</b>
Version 3498b16 (2016-10-30)

___
<br>

While having a deck loaded in the deck editor, and wanting to search a card to add to the deck: When quickly typing a cards name in the search box, it crashes hard. This is clearly related to the amount of cards it needs to look through. If I quickly type a name, it crashes hard. If I type one letter a time rather slowly, it does not crash.

Also, if I type the first few letters slowly, say `Lion's E` I can then type quickly and finish `Lion's Eye Diamond' without crashing hard.

I created a Gist for you with the crash output: https://gist.github.com/mpalmujoki/47cf8ad0c3a1d10b077732d341b94f1a

**Comment by Daenyth** [comment]
This is definitely a dupe but the info about typing speed is a nice clue.
@zeldazach I'm suspecting the filter model code. Maybe it's got some race
condition?

**Comment by tooomm** [comment]
Found the duplicates: #1967 and #2167
Check these issues for crash logs and other infos!

**Comment by greerrrr** [comment]
Hi there, I'm encountering a bug which may be the same or similar to this, it is a program crash when trying to search.

My desktop is Linux Mint 18 Cinnamon 64-bit
My version of cockatrice is Cockatrice (64-bit) Version 2.5.0-custom(cc2a0fa) (2018-04-10)

When I open cockatrice to the deck editor and attempt to search the library by card name, it will crash after the second typed character. This occurs even if I delete the first character that I typed. If I type very slowly (~10 seconds between characters) I can get a second character in without a crash. The time between characters required to not crash seems to go up, but I haven't totally narrowed it down. I safely got "a [10 seconds] a [30 seconds] z" when "a [10 seconds] a [10 seconds] z" resulted in a crash.

This is the terminal output of a crash after typing "aa" at a normal pace:

https://gist.github.com/greerrrr/1c94f844e4ae4d735dd525305e94657c

**Comment by skwerlman** [comment]
@greerrrr do you have a core dump from the crash? if you do, can you post the stacktrace from it?

**Comment by greerrrr** [comment]
I just learned how to generate a core dump and a stacktrace, so I think this is what you are asking for:

#0  0x00007fc77a3e5eec in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#1  0x00007fc77a3e653e in QSortFilterProxyModel::flags(QModelIndex const&) const () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#2  0x00007fc77a3d109c in QItemSelectionModel::isSelected(QModelIndex const&) const () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#3  0x00007fc77af58b33 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#4  0x00007fc76feda9d9 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#5  0x00007fc76fedaf49 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#6  0x00007fc76fee03ac in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#7  0x00007fc76dcb5abe in ?? () from /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5
#8  0x00007fc76dcb726e in ?? () from /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5
#9  0x00007fc77a44ec01 in QObject::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x00007fc77ad1405c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#11 0x00007fc77ad19516 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#12 0x00007fc77a41f38b in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#13 0x00007fc77a421786 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#14 0x00007fc77a4753c3 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#15 0x00007fc77873b197 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#16 0x00007fc77873b3f0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#17 0x00007fc77873b49c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#18 0x00007fc77a4757cf in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#19 0x00007fc77a41cb4a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#20 0x00007fc77a424bec in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#21 0x000000000054d404 in main ()

The [page that told me what to type in gdb](https://stackoverflow.com/questions/5745215/getting-stacktrace-from-core-dump) had a bunch of options which had more output, let me know if you want one of those instead.

**Comment by Daenyth** [comment]
@greerrrr which version did you use to generate that stack trace?

**Comment by greerrrr** [comment]
Same one I still have installed, a locally compiled Client Version: 2.5.0-custom(cc2a0fa) (2018-04-10)

**Comment by ctrlaltca** [comment]
Turns out this specific crash was caused by a Qt bug: https://bugreports.qt.io/browse/QTBUG-54570
On mac we stuck to the vulnerable Qt version 5.6 for a while, since the next versions had worst problems (see #2647).
Not-vulnerable versions od Qt are 5.8.0 and 5.6.3 (LTS).
The crash is reported by @greerrrr is probably unrelated to the original one.

**Comment by tooomm** [comment]
@greerrrr which version of Qt did you compile against?
Can you paste the first lines from `Help --> View Debog Log` here, please?
Do you still experience the same problem with the newest 2.6.1 release?

**Comment by ctrlaltca** [comment]
Closing this issue. A lot of new Cockatrice versions has been released since 2016, and we didn't receive more reports of this crash. Thank you for the original report, and fell free to reopen if it still crashes for you in the last version.
