### ISSUE TITLE
Error beep when hitting return in any text field

### ISSUE THREAD

**Issue by institute** [Cockatrice/Cockatrice#2289]
<b>OS: OSX 10.11.6</b>
<b>Cockatrice version: 3498b16 (2016-10-30)</b>

___
<br>

*I get an error beep every time i hit enter in a text field, in all chats. So if I type text in a text field and hit enter to submit that text I get a system error beep. Is that normal?*

**Comment by Daenyth** [comment]
Well that's a new one...

**Comment by Daenyth** [comment]
No, it's not normal.

Do you have any uncommon window management software installed? Did you get cockatrice from DMG or manual compile?

**Comment by institute** [comment]
No window management stuff and I downloaded the DMG.

**Comment by ZeldaZach** [comment]
I noticed this happening on mac builds too a while ago when I updated to OS X 10.12, so I just turned alerts off on the mac and didn't have the issue.

None the less, this is still a problem that we should look into.

**Comment by Daenyth** [comment]
Hmm, I'm still on 10.11 and I don't see this.

**Comment by institute** [comment]
Update: Fixed with Version f7c8651 (2016-12-30)
