### ISSUE TITLE
Custom tokens randomly get deleted

### ISSUE THREAD

**Issue by Xelsia** [Cockatrice/Cockatrice#2290]
<b>OS:</b>
WIndows 10 Home*

<b>Cockatrice version:</b>
3498b19 (2016-10-30).*

___
<br>

I'm not entirely sure what causes it or when it happens, but I've noticed my custom tokens randomly get culled over a period of time, forcing me to renter them in the Edit Tokens dropdown list. I used to have this problem ages back (maybe a year ago?), it went away for a very long time, and it's come back since this new build.
I've got a screenshot that demonstrates it perfectly. (Among other things), I have a token for every number between 1 and 20 to make the dice rolls at the start of EDH games look nicer and easier to read. Every-now and then, some numbers will come up as a blank card and will no longer be in the tokens list
![c5357946d5e34c859a6af8a04e4aec08](https://cloud.githubusercontent.com/assets/13385016/20855305/dd005fca-b960-11e6-8991-3789cd2a0d69.png)
![c29654063df94ea8bad2aa3bfc2ccad7](https://cloud.githubusercontent.com/assets/13385016/20855360/4243d678-b961-11e6-8832-d8de0350d8e0.png)

It's also not just tokens that are numbers. I have to recreate tokens I use for indicators such as Black Nightmare, Black Zombie, Arjun Trigger and Mindmoil Trigger.

**Comment by Daenyth** [comment]
Hmm, I suspect "edit tokens" is adding data to tokens.xml which oracle overwrites.

**Comment by Jinxstands4Jinx** [comment]
You can Also use the Custom images area to do this as i also have many token pictures. and i just chuck them in there and i have yet to encounter this issue.

**Comment by Xelsia** [comment]
I've found that I have to make a token for every non-card I want a custom image for, otherwise it just uses the card back. Is there a way around that?

**Comment by Jinxstands4Jinx** [comment]
not sure about that as the ones I have in the Custom folder are Already tokens. I.e the Thopter tokens i have different images for as with most elementals and cats. I have yet to make Customs for cards that are not real. like you're numbers

**Comment by ZeldaZach** [comment]
>Hmm, I suspect "edit tokens" is adding data to tokens.xml which oracle overwrites.

@Daenyth Didn't we make it so when you edit tokens it goes to a new file in the customsets directory, "tk"? I recall we did something like that.

**Comment by ZeldaZach** [comment]
The token dialog had an overhaul a while ago and this shouldn't be a problem now
