### ISSUE TITLE
Error connection refused

### ISSUE THREAD

**Issue by philipcliang** [Cockatrice/Cockatrice#2291]
<b>OS:</b>
Windows 10

<b>Cockatrice version:</b>
3498b16 2016-10-30

___
<br>

I'm getting error connection refused and it taking forever to connect

**Comment by philipcliang** [comment]
Also host not found

**Comment by skwerlman** [comment]
Which server are you trying to connect to?

**Comment by philipcliang** [comment]
woogerworks

**Comment by ZeldaZach** [comment]
Server seems to be up... try again? :)
