### ISSUE TITLE
OSX Sierra, Load Deck loads empty list.. Not previous folder.

### ISSUE THREAD

**Issue by mpalmujoki** [Cockatrice/Cockatrice#2292]
<b>OS:</b>
OSX 10.12.1 (Sierra)
<b>Cockatrice version:</b>
Version 3498b16 (2016-10-30)

___
<br>

I recently upgraded from El Capitan to Sierra on my mac. Previously, opening a deck opened up the graphical window where you select the deck. When I did this, it loaded the last folder I opened a deck from. This made selecting decks easy, both in Local Game, and in Deck Editor. 

However now in Sierra, I've noticed that when I want to open a deck, the list of file is empty. This is essentially what it looks like:

https://www.dropbox.com/s/onq2jw0sx0jp5pa/Screenshot%202016-12-03%2014.37.54.png?dl=0

I can workaround this by clicking the top part and selecting a location from the last used locations, so the bug is rather minor, but impacts usability.

https://www.dropbox.com/s/as923vd2od25sc4/Screenshot%202016-12-03%2014.39.19.png?dl=0

**Comment by ZeldaZach** [comment]
Just tested on **10.12.1 @ 3498b16** and did not experience this bug. Can you try possibly reinstalling the client and seeing if that fixes it?

<img width="766" alt="screenshot 2016-12-06 02 59 01" src="https://cloud.githubusercontent.com/assets/7460172/20917514/f8510512-bb5f-11e6-9192-505eeaabf558.png">

**Comment by mpalmujoki** [comment]
I redownloaded the .dmg from https://cockatrice.github.io/, and copied the Cockatrice over my previous installed app. 

I must have something funky on my end, since I can still replicate the issue. Guess I'll have to live with it for now. This is the only app I've noticed that on so far.

**Comment by mpalmujoki** [comment]
Ah now I get it. It defaults to this location: https://www.dropbox.com/s/czaaydlsnxmirgs/Screenshot%202016-12-07%2010.57.46.png?dl=0

However, I keep my decks at `~/Cockatrice/decks/`.

Turned out that I hadn't changed the default decks directory path since reinstalling. My bad. Now I set it to where I keep my decks and the Open Deck thing works just perfectly.

**Comment by ZeldaZach** [comment]
@mpalmujoki Glad we could figure this out!
