### ISSUE TITLE
Error Connecting

### ISSUE THREAD

**Issue by Vuryal** [Cockatrice/Cockatrice#2293]
<b>OS:</b>
Windows 10

<b>Cockatrice version:</b>
Version 3498b16 (2016-10-30)

___
<br>

I cannot connect to Cockatrice. I tried the Woogerworks .com and .info and am unsuccessful at either. I uninstalled and reinstalled the program but no success.

**Comment by Jinxstands4Jinx** [comment]
Same, and cannot connect to backup either.

**Comment by Nightfirecat** [comment]
This isn't a Cockatrice software problem: https://twitter.com/woogerworks/status/805192886514028544

**Comment by woogerboy21** [comment]
Have you retried at this point?  And were you able to successfully connect?
