### ISSUE TITLE
Crash on server close

### ISSUE THREAD

**Issue by skwerlman** [Cockatrice/Cockatrice#2295]
<b>OS:</b>
Ubuntu 16.04

<b>Cockatrice version:</b>
d039c9b

___
<br>

```
Tue Dec 6 01:53:34 2016 d12490 [Command_ShutdownServer.ext] { reason: "" minutes: 0 }
Tue Dec 6 01:53:34 2016 Server::removeClient: name= "skwerlman"
Tue Dec 6 01:53:34 2016 closed session id: 2389
Tue Dec 6 01:53:34 2016 Server::removeClient: removed 0xd12490 ; 0 clients;  0 users left
Tue Dec 6 01:53:34 2016 d12490 TcpServerSocketInterface destructor
Tue Dec 6 01:53:34 2016 Server_Room destructor
Tue Dec 6 01:53:35 2016 Server_Game destructor: gameId= 848
Tue Dec 6 01:53:35 2016 QObject::killTimer: Timers cannot be stopped from another thread
Tue Dec 6 01:53:35 2016 QObject::~QObject: Timers cannot be stopped from another thread
Tue Dec 6 01:53:35 2016 Server_Room destructor
Tue Dec 6 01:53:35 2016 Server_Room destructor
Tue Dec 6 01:53:35 2016 Server_Room destructor
Tue Dec 6 01:53:35 2016 Server_Room destructor
Tue Dec 6 01:53:35 2016 Closing pool 0...
Tue Dec 6 01:53:35 2016 CRASH: SIGSEGV
```

**Comment by ZeldaZach** [comment]
Was there any additional logs generated by chance?

**Comment by skwerlman** [comment]
Not that I'm aware of. If servatrice generated a file on crashing, where would it be located?

**Comment by ZeldaZach** [comment]
I'm not 100% sure as I have not looked too much into the servatrice portion of the project, but maybe in `/var/log`?

**Comment by skwerlman** [comment]
I don't see anything relevant there, or the folder where `servatrice.log` gets written (realizing i forgot to mention it, the above is taken from `servatrice.log`, and starts with me sending the shutdown command)

**Comment by woogerboy21** [comment]
you would need to compile the server in debug mode and then execute the the servatrice command outputing the shell output to a log.  Something like this:

```
servatrice --config servatrice.ini &> crash.log 
```

**Comment by skwerlman** [comment]
Why doesn't servatrice just write the stacktraces to the normal log? It seems counter-intuitive that important info like that would be discarded by default.

**Comment by ctrlaltca** [comment]
The logger is optimized to use Qt classes, eg. to buffer the text and flush it every now and then to be easy on the disk.
When you are in the middle of a crash you don't want to create new objects or allocate memory, because it will probably fail.
One of the few things that will probably still work are the basic file descriptors, stdout, stderr, etc..

**Comment by skwerlman** [comment]
That makes sense. I've modified my start script so if I spot this crash again (or any other one) I'll be able to provide a trace.

**Comment by ZeldaZach** [comment]
Let us know if there's any additionals you'd like to provide!
