### ISSUE TITLE
Ban DB Query Improvements

### ISSUE THREAD

**Issue by woogerboy21** [Cockatrice/Cockatrice#2303]
So lacking the awesome skills that others more familiar with DB queries have, can anyone give recommendations on how to improve the DB queries involved in locating if a user is banned?  There are multiple queries that are performed at each and every login and I would like to see it improved on (if possible).

You can find the queries staring at:
https://github.com/Cockatrice/Cockatrice/blob/master/servatrice/src/servatrice_database_interface.cpp#L298

ID: https://github.com/Cockatrice/Cockatrice/blob/master/servatrice/src/servatrice_database_interface.cpp#L313

UserName:
https://github.com/Cockatrice/Cockatrice/blob/master/servatrice/src/servatrice_database_interface.cpp#L351

IP:
https://github.com/Cockatrice/Cockatrice/blob/master/servatrice/src/servatrice_database_interface.cpp#L374

The one particular query that seems to always show up in the mysql_slow.log is the one for client id.  There is probably room for impovement on that query at the very least.

**Comment by woogerboy21** [comment]
Infact the more I look into the queries, im not sure why they are the way that they are.  Why would you need a timediff query (or such a complicated query) to simply return true or false?

**Comment by ZeldaZach** [comment]
A thought:

"
Maybe we have a switch go on
A table "cockatrice_bans_older"
and we run a job that after X days/months, the result is moved tables (maybe after the ban is already lifted?)
and we only have to query bans_older when a mod looks up a user's past ban info
that way we keep the login ban table only checking for bans that are still active
and still have the results for mods to look up
"

**Comment by Daenyth** [comment]
I don't think that kind of caching will really be helpful. We just need better indexes.

**Comment by woogerboy21** [comment]
@Daenyth Any suggestions on this, im brainstorming and potentially may write up something like @ZeldaZach suggest just for a test branch .

@ctrlaltca Any idea's?

**Comment by Daenyth** [comment]
Can you post the specific queries that get run on login?

Depending how large the ban table is, we could make the server slurp the ban table into memory and just hold it there, and any updates that need to happen go through that first, but it's a little bit more code than we have right now.

**Comment by woogerboy21** [comment]
```
select timestampdiff(second, now(), date_add(b.time_from, interval b.minutes minute)), b.minutes <=> 0, b.visible_reason from cockatrice_bans b where b.time_from = (select max(c.time_from) from cockatrice_bans c where c.clientid = '{clientidremoved}') and b.clientid = '{clientidremoved}';
```

But specifically the ban lookups that are performed at login (in general) are specifically what I want to refactor.  You can find the code block that is performed when a user log's in at https://github.com/Cockatrice/Cockatrice/blob/master/common/server_protocolhandler.cpp#L415 and track down where the queries are performed.  There are a few lookups done at each login.

**Comment by ZeldaZach** [comment]
@Daenyth Why is my idea not ideal? It seems to fit pretty well in what we want and it limits hits on the database.

@woogerboy21 I'm not sure what the idea is right now, wanna chat?

**Comment by Daenyth** [comment]
Reading it again, I think you and I are proposing the same thing.

I'd like to solve it in sql if we can because it's less code, which means fewer places for bugs to live.

**Comment by Daenyth** [comment]
OK so yeah, this is awful.
https://github.com/Cockatrice/Cockatrice/blob/f86b9e0be73d249e50a4d9ae33d4fd09faa8ae3d/common/server.cpp#L81

Without digging through the whole call stack, it looks to me like a user login can result in *at least* 10 db queries!! This is insane. It should only take 2-3. @ZeldaZach this is the thing to solve before we do more.

We can start here:
```
checkUserIsIpBanned(ipAddress, banReason, banSecondsRemaining) || checkUserIsNameBanned(userName, banReason, banSecondsRemaining) || checkUserIsIdBanned(clientId, banReason, banSecondsRemaining);
```

This can be a single query.

Currently:
```sql
select
  timestampdiff(second, now(), date_add(b.time_from, interval b.minutes minute)),
  b.minutes <=> 0,
  b.visible_reason
from {prefix}_bans b
 where b.time_from = (
    select max(c.time_from)
    from {prefix}_bans c
    where c.user_name = :name2
) and b.user_name = :name1
;
select
  timestampdiff(second, now(), date_add(b.time_from, interval b.minutes minute)),
  b.minutes <=> 1,
  b.visible_reason
from {prefix}_bans b
where b.time_from = (
  select max(c.time_from)
  from {prefix}_bans c
  where c.ip_address = :address
) and b.ip_address = :address2
;
select
  timestampdiff(second, now(), date_add(b.time_from, interval b.minutes minute)),
  b.minutes <=> 1,
  b.visible_reason
from {prefix}_bans b
where b.time_from = (
  select max(c.time_from)
  from {prefix}_bans c
  where c.clientid = :id
) and b.clientid = :id2
```

So that's awful. The first thing that jumps out at me is that the subquery probably isn't needed. We could instead `ORDER BY time_from DESC` and pick the row we want code-side. There's other approaches but that's likely the simplest.

I think there's 2 main ways we can structure this query, and it'll depend on whether the query plan is better.

I have to run afk, but I'll come up with a query for you to EXPLAIN and see how it is

**Comment by woogerboy21** [comment]
@Daenyth My original thought was to update the ban table with a column that something like "end_time" and then when a ban is placed the server calculates when the ban would end and place the date/time in the new column.  Then on login we could do a much simpler query like check for current banlist of user that is newer than end_time = now() and if results return then user is still banned.  Of course the code would have to also include the extracting of reasoning to pass back to the client (assuming we still wanted to do so) but I think you get the idea.

**Comment by Daenyth** [comment]
Yes, we could do that. It would allow easier index usage

**Comment by woogerboy21** [comment]
@Daenyth Did you want to come up with a query (as described above) or should I start with a code branch that calculates the end time as mentioned?

**Comment by Daenyth** [comment]
I didn't have time yesterday but the two I was thinking of would basically
order by the subquery field to remove the subquery and then I'd either do
one query with OR on all the criteria, or if that doesn't do well then
still 3 queries but UNION them so it's done in one operation and pg can
take advantage of indexes. What indexes are on the table right now?

**Comment by Daenyth** [comment]
Either way doing end time will be good

**Comment by woogerboy21** [comment]
@Daenyth Here is the current table structure:
```
MariaDB [servatrice]> describe cockatrice_bans;
+----------------+--------------------------+------+-----+---------+-------+
| Field          | Type                     | Null | Key | Default | Extra |
+----------------+--------------------------+------+-----+---------+-------+
| user_name      | varchar(255)             | NO   | PRI | NULL    |       |
| ip_address     | varchar(255)             | NO   | MUL | NULL    |       |
| id_admin       | int(7) unsigned zerofill | NO   |     | NULL    |       |
| time_from      | datetime                 | NO   | PRI | NULL    |       |
| minutes        | int(6)                   | NO   |     | NULL    |       |
| reason         | text                     | NO   |     | NULL    |       |
| visible_reason | text                     | NO   |     | NULL    |       |
| clientid       | varchar(15)              | NO   |     | NULL    |       |
+----------------+--------------------------+------+-----+---------+-------+
8 rows in set (0.00 sec)
```
