### ISSUE TITLE
User List incomplete on Web Client

### ISSUE THREAD

**Issue by tritoch** [Cockatrice/Cockatrice#2307]
On the web client currently live on woogerworks, people are messaging in chat that are not listed in the userlist.

**Comment by ZeldaZach** [comment]
The userlist, on webatrice, is currently sorter (0-9, A-Z, a-z) so if they have a lowercase name look towards the bottom of the list.

**Comment by tritoch** [comment]
Due to a server issue, there are only about 3 of us on the web client.  One of whom is chatting but not listed in user list.
