### ISSUE TITLE
Extraneous / Debug fields on Web Client Account Tab

### ISSUE THREAD

**Issue by tritoch** [Cockatrice/Cockatrice#2310]
The following fields appear on the Account tab of web client (current version @ woogerworks, Windows 7 / Chrome):

Gender: GenderUnknown
id: -1
serverId: -1

Missing features
mod_log_lookup
user_ban_history

**Comment by ctrlaltca** [comment]
PR #2363 should make these fields more user friendly:

> Gender: GenderUnknown
Well, you didn't set a gender for your account, thus the GenderUnknown value

> id: -1
> serverId: -1
Hidden by #2363

> Missing features
> mod_log_lookup
> user_ban_history

Those are features not yet supported by the web client; just ignore them.

**Comment by Daenyth** [comment]
Gender field is probably going to be removed since it triples translating
work and adds only small value for some people

**Comment by tooomm** [comment]
@Daenyth we did so already in-client. No more gender field for server registration and no displayed information within `User details`!

**Comment by woogerboy21** [comment]
I can tell you that the DB schema still contains the gender column for the users table (https://github.com/Cockatrice/Cockatrice/blob/master/servatrice/servatrice.sql#L31) .  I would have to comb through the code and see what (if anything) still uses the information.

**Comment by Daenyth** [comment]
It's still all over the code, we just removed from ui
