### ISSUE TITLE
My username contains "admin" in it, how to change it ?

### ISSUE THREAD

**Issue by HMgruul** [Cockatrice/Cockatrice#2315]
<b>Windows 7 SP1</b>
<b>3498b16 (2016-10-30)</b>

Hello !
My username on cockatrice is headminerve and I never encountered any problem to connect on servers until several days ago. I guess it has something to do with the latest updates. I get this message :
"Nom d'utilisateur non valide
Votre nom d'utilisateur doit respecter ces règles:
- est 3 - long de 30 caractères
[...]
- can not contain any of the following words: admin"

That last line wasn't there when I encountered my issue the first time because I was on a previous version of Cockatrice. Once I updated the software today, I finally understood what was wrong with my username !

I'm open to change my username but I can't find a valid link on internet or an option in Cockatrice to do it. This is why I'm coming here. How can I change my username please ? And if I can't, what are my options ?
Thanks !
___
<br>

*Explain your Issue/Request/Suggestion in detail here!*

**Comment by skwerlman** [comment]
@HMgruul Assuming you're talking about the woogerworks server, the easiest way would be to ask @woogerboy21 to change it for you, since there is no way currently to do it yourself.

---

Sounds like maybe the username filtering should only be applied to registration, and not logins. That way people can still log in if they registered before the filters got added.

**Comment by Daenyth** [comment]
@skwerlman that would be complicated for servers that allow unregistered users to connect.

**Comment by Daenyth** [comment]
Also I know wooger is on vacation for a few weeks. @ZeldaZach do you have the ability to change usernames on woogerworks?

**Comment by skwerlman** [comment]
@Daenyth Could the server skip the check on login if registration is required or if the user is already registered? It shouldn't require any additional queries since the server has to make sure the user exists anyway.

**Comment by ZeldaZach** [comment]
Yes i have the authority to change names. @HMgruul what new name would you like?

**Comment by HMgruul** [comment]
Thanks for your quick replies, all of you. ;)
And yes, I speak of Woogerworks servers.
@ZeldaZach I'd be fine with "head_minerve" (just add an underscore between the 2 words), that would be the simplest for my friends and myself. Thanks in advance for your help on this one. :)

**Comment by ZeldaZach** [comment]
@HMgruul Done. You should be able to login now.

**Comment by HMgruul** [comment]
It works, you rock !

**Comment by Daenyth** [comment]
'clbuttic' strikes again :P

**Comment by Nightfirecat** [comment]
@skwerlman brings up a good point though. Should the username filter prevent login for users whose usernames happen to go against the op's newly-established filters? Obviously, they can contact the operator to have their name changed (like here), but that feels like asking a lot of the user.

**Comment by Daenyth** [comment]
It's reasonable to allow that
