### ISSUE TITLE
remove submenu "create related card"

### ISSUE THREAD

**Issue by TaZi-loh** [Cockatrice/Cockatrice#2317]
Suggestion:

It's nice to see the "create related card"-feature implemented. It saved quite some of my lifetime already =). However I think it would be reasonable to optimize the menu a bit with a simple step.

I suggest, to remove the menuitem "create related card...". That means instead of a Menu looking like:

... 
Flip
Create related card
 - 1/1 Soldier Token
 - Elspeth Emblem
attach to a card...
...

The Menu should look like

... 
Flip
1/1 Soldier Token
Elspeth Emblem
attach to a card...
...

as most of these Menu have only one entry. Some have two. But only very few cards have more than that. This would be quite appropriate, as this menu entry is probably one of the most used ones.

**Comment by Daenyth** [comment]
This is reasonable. I'd change the wording to `Token: 1/1 Soldier` and so on so they visually collect together when a card has multiple, and also I'd like separators before and after the create block, if related cards are available.
