### ISSUE TITLE
Register to Server not passed current Server name

### ISSUE THREAD

**Issue by dev-id** [Cockatrice/Cockatrice#2318]
When you connect to a server that requires registration, it prompts you to register.  This opens the registration window, but the current server's host is not in the `Host` field.

**Comment by Daenyth** [comment]
I have a branch with some reg and login UI rewrites. I don't know when I will have time to finish it. I might just draw a mockup and ticket it for someone else to finish. The UI I have in mind would make this issue impossible

**Comment by ZeldaZach** [comment]
This appears to be working as expected now
