### ISSUE TITLE
Immediately after login, Idle timeout Pop Up appears

### ISSUE THREAD

**Issue by tritoch** [Cockatrice/Cockatrice#2319]
Immediately after registering to a new server, 2 pop ups appear.

1) the correct "Registration Accepted. Will now login."
2) an incorrect "You are about to be logged out due to inactivity."

Edit: I am now getting this pop up every time I connect.  Idle on this server is set to 0 (disabled, supposedly).

**Comment by Daenyth** [comment]
@ZeldaZach I'd appreciate if you have time to take a look at this.

**Comment by woogerboy21** [comment]
https://github.com/Cockatrice/Cockatrice/blob/master/common/server_protocolhandler.cpp#L397

That line needs updated to include a check to make sure the idle client timer is set to something higher than 0.

**Comment by woogerboy21** [comment]
@tritoch 
Can you check out #2322 and see if that fixes your issue.

**Comment by woogerboy21** [comment]
So I tested out #2322 on a new server connected to the DB, time out value set to 0 and registered a new account.  It registered successfully, logged me in and no warning about idle client popups occurred.  @tritoch was this the condition you explained that you noticed the popup message?
