### ISSUE TITLE
Recursively search customsets folder for xml set files

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2324]
see #2251 

Support for sub directories is now included for the custom picture folder, but not yet for custom sets.

**Comment by Nightfirecat** [comment]
Are there any other cases where we search a directory, but could search through subdirectories as well? Seems like this is generally a good pattern to follow for user-defined files.

**Comment by ZeldaZach** [comment]
See my comment @ https://github.com/Cockatrice/Cockatrice/pull/2251#issuecomment-257367225 I disagree with the search option personally, but I'm open to hearing ways to avoid having problems.

**Comment by tooomm** [comment]
@ZeldaZach what kind of problems do we need to avoid?
Did you see my reply to yours @ https://github.com/Cockatrice/Cockatrice/pull/2251#issuecomment-257520781? Since you never replied to it...

Just because you don't see a use case right now we don't have to limit somehow expected basic behavior for no reason. Or introduce different behaviors for similar things on different places inside the app.
(here: one custom folder vs. another - one works with subfolders while another doesn't)

**Comment by ZeldaZach** [comment]
Any other opinions on this?

**Comment by ctrlaltca** [comment]
This can be useful and is probably safe to implement.

**Comment by tritoch** [comment]
While I could learn to live with this, I currently keep a 'backup' folder with all my old spoiler files and any custom sets I've installed to help people test them. I would need to move them from a subfolder to somewhere else (unless a special exception for certain folder names was added...)

**Comment by ZeldaZach** [comment]
This seems super easy. I'll make an exception folder, but this seems like a solid idea
