### ISSUE TITLE
App crashes randomly

### ISSUE THREAD

**Issue by JesterHoperpot** [Cockatrice/Cockatrice#2326]
<b>OS:</b>
Windows 10 MSI laptop 8gb ram 64-bit OS, x64-based processor.

<b>Cockatrice version:</b>
Version 3498b16 (2016-10-30)

___
<br>
The app freezes at seemingly random times. One moment it'll crash when trying to click on cards, then next time that will be fine but if you open deck editor it will freeze. It never crashes the same way twice in a row but say opening the deck editor makes it crash, then settings makes it crash after reloading while deck editor works fine, then deck editor will crash again next instance. I have tried uninstalling and reinstalling, tried renaming the .exe file, none of that solved the issue. Can anybody help me figure out what to do?

**Comment by woogerboy21** [comment]
Can you document what steps your performing when the crash's are occurring?  I have had a Windows 10 client run for days connected to the server with out crashing but I can't say that I am performing the same tasks / reproducing the same behavior you may be doing.

**Comment by JesterHoperpot** [comment]
Sure thing

It'll be simple things such as opening the app and clicking on settings will cause it to freeze. After force closing the app and bringing it back up going to settings won't cause a thing wrong to happen. However then clicking on a card on the left sidebar will cause it to freeze. Rinse and repeat closing and opening settings and clicking cards will be fine but opening deck editor will crash it. So on and so forth at different points on the app causing it to crash with seemingly no rhyme or reason.

I hope this is enough, thanks in advance!

**Comment by woogerboy21** [comment]
Hmm... that's very odd, I definitely have not heard of that issue.  That sounds pretty annoying and would have definitely been reported by users.  What model of laptop is it (model number)?  And did you compile the app yourself or install it from a downloaded pre-compiled version?  And were you able to see if there was any windows event log entries?

**Comment by JesterHoperpot** [comment]
It most certainly is. It's an MS-16J5 and I downloaded it pre-compiled and there weren't any log entries about it. I'm baffled as to what's wrong.

**Comment by woogerboy21** [comment]
Just curious, when you say it freezes, does the app say its not responding and kind of dim or does the app simply hang with no indication from windows that there is a problem other than not being able to interact with it?

**Comment by JesterHoperpot** [comment]
It hangs, sorry I should have been more clear. It hadn't been doing it for a couple days but yesterday it started up again. Now it's just the deck editor that's making it hang and nothing else. Used to be any sort of thing, now just deck editor.

**Comment by JesterHoperpot** [comment]
No the search bar hasn't been an issue. It used to randomly hang when trying to do virtually anything, now it seems to just be doing it for deck editor.

**Comment by tooomm** [comment]
Did you check this? https://github.com/Cockatrice/Cockatrice/issues/2331
He had problems on his MSI laptop as well and solved it. A MSI tool was causing the problems.

**Comment by JesterHoperpot** [comment]
Wow it was that app the whole time. Well thanks for directing me to that, seems to have solved it.

**Comment by tooomm** [comment]
You're welcome! Enjoy your games. :)

**Comment by ZeldaZach** [comment]
@tooomm Maybe we should Troubleshoot wiki this issue?

**Comment by tooomm** [comment]
@ZeldaZach I can't look into the exact details of the problem or a proper wording right now to update the wiki.
