### ISSUE TITLE
Random Application Freezing on New Laptop

### ISSUE THREAD

**Issue by picclo200** [Cockatrice/Cockatrice#2331]
<b>OS:</b>
Windows 10 Home

<b>Cockatrice version:</b>
Version f7c8651d (2016-12-30)

___
<br>

I have recently purchased a new laptop. It is an  MSI GT72 Dominator Pro G-034. I have found that the application will randomly freeze a few minutes after starting it when I do almost anything. It sometimes freezes while making a deck, sometimes while searching cards, sometimes while loading a deck, and sometimes just when hitting on of the menus on the top of the application. I have checked and I have no windows updates left to do, so I am not sure what may be causing this issue. It has not been happening on my Desktop, but has happened every time I have tried on this laptop. I have done multiple uninstall and reinstalls of the application. Deleted all files and folders that may have contained remnants of cockatrice in between, ran the program as administrator, turned off all antimalware programs, and it is still happening. When the application freezes I have to turn it off through the task manager because it doesn't usually come back, or when it does, it just freezes again a few seconds afterward.

**Comment by picclo200** [comment]
I have figured out what is causing the freezes. There is an application that came pre-installed on the machine called Nahimic for MSI. I have found that if I exit this application I have no problems with Cockatrice (or any other applications as I found more freezing while this was on).

**Comment by Daenyth** [comment]
Would you add that to the wiki troubleshooting section?
