### ISSUE TITLE
Add "Do not remind me again" to client out of date

### ISSUE THREAD

**Issue by poixen** [Cockatrice/Cockatrice#2333]
Add a check box to avoid seeing this popup.
If I can still login, then I do not need to update yet.
Only remind again when I can not login due to my client version.

**Comment by woogerboy21** [comment]
And https://github.com/Cockatrice/Cockatrice/pull/2275 isn't good enough?

**Comment by ctrlaltca** [comment]
Looks like #2275 addressed this, please reopen if something still needs to be fixed.
