### ISSUE TITLE
Playing replays crashes cockatrice.

### ISSUE THREAD

**Issue by GaelTadh** [Cockatrice/Cockatrice#2334]
<b>OS:</b>
OSX El Capitan 10.11.6

<b>Cockatrice version:</b>
Version f7c8651 (2016-12-30)
___
<br>

Fast forwarding in recorded games seems to be broken and crashes the app. 

1. Open a recorded game.
2. Click the fast forward button.
3. Game goes into overdrive speed for a second.
4. Cockatrice crashes.

**Comment by GaelTadh** [comment]
So it looks like replays crash for me even without fast forwarding.

**Comment by woogerboy21** [comment]
This is caused by an access violation right here:  https://github.com/Cockatrice/Cockatrice/blob/master/cockatrice/src/chatview.cpp#L162

**Comment by woogerboy21** [comment]
Have I ever mentioned how much I dislike the current replay system? :)
