### ISSUE TITLE
Keyboard Shortcuts not working in Unity (Ubuntu 16.10)

### ISSUE THREAD

**Issue by ambivalentduck** [Cockatrice/Cockatrice#2335]
<b>OS:</b>
Ubuntu 16.10

<b>Cockatrice version:</b>
Version f7c8651 (2016-12-30)
___
<br>

Adding/removing appmenu-qt5 does not fix broken keyboard shortcuts. Rebuilt several times with and without as well as using _make clean_ between builds. Used the most recent available code using _git pull origin master_.

Downloading and installing from <url>https://bintray.com/cockatrice/Cockatrice/Cockatrice-git/#files/Ubuntu/trusty</url> also does not resolve the problem.

**Comment by tooomm** [comment]
I'm not a linux guy...

The hosted trusty build is for 14.04 and most likely won't work on 16.10.

Did you check our compiling instructions for ubuntu 16.xx?
https://github.com/Cockatrice/Cockatrice/wiki/Compiling-Cockatrice-(Linux)#ubuntu-16xx

**Comment by Daenyth** [comment]
@tooomm He said he compiled from git, so he wouldn't be using the hosted build.

**Comment by tooomm** [comment]
@Daenyth he also tried the hosted trusty build ;)

>Downloading and installing from **https://bintray.com/cockatrice/Cockatrice/Cockatrice-git/#files/Ubuntu/trusty** also does not resolve the problem.

**Comment by ZeldaZach** [comment]
@ambivalentduck Were you able to get this working?

**Comment by TigerMonarchy** [comment]
I am also having this problem as I recently updated to 16.10 and I'm not able to use my keyboard shortcuts now as well. I installed from Git onto Ubuntu 16.04 as per instructions and got it compiled and ran without any issues, save the time it took. But after upgrading, I can't use my shortcuts at all now either.

**Comment by ambivalentduck** [comment]
Shortcuts work just fine in GDM, but not in Unity. I got fed up and switched to GDM, but ideally this should work in Unity without issues.

**Comment by TigerMonarchy** [comment]
@ambivalentduck Thanks for the heads up but I'm not really all that keen to switch over to GDM just to enable functionality in one program, albeit the program I play MtG on. I'd need some other reasons to make that switch as I'm still a relative novice to Ubuntu and Linux in general.

**Comment by ctrlaltca** [comment]
Ubuntu 16 is not supported anymore, and Unity is not even the default UI for ubuntu anymore. Closing this issue.
