### ISSUE TITLE
Suboptimal order of image fetching between the two specified sites (Suggestion)

### ISSUE THREAD

**Issue by Shomotion** [Cockatrice/Cockatrice#2346]
<b>OS:</b>
Windows 10

<b>Cockatrice version:</b>
Version f7c8651d (2016-12-30)

___
<br>

I'm changing the image download links in the Settings > General menu and it seems that when Cockatrice can't find a card's image from my desired edition (specified in the card database list) from the primary site, it grabs a different edition's image from the primary site. This happens even when I have all the other editions disabled (unchecked) in the card database list. For example, I wanted Tropical Island from LEA, which my primary site didn't have. Cockatrice grabbed the image from Collector's Edition, even though my secondary link has the image from LEA. I had every set Tropical Island was printed except LEA disabled in the card database, but it still got the Collector's Edition image anyway. My secondary link is the default primary link, and I know Cockatrice can fetch the LEA Tropical Island image fine from it because I tested it. I think it would be better if Cockatrice tried to get the correct image from the first link, then tried to get the correct image from the second, and then fetched images from disabled sets after looking at both sites. Right now it seems that it doesn't even look at the second link even if the second link has the image I want and that feels suboptimal. Thank you for everything you do!

**Comment by tooomm** [comment]
Linking https://github.com/Cockatrice/Cockatrice/issues/1984, https://github.com/Cockatrice/Cockatrice/issues/1543, https://github.com/Cockatrice/Cockatrice/issues/2240#issuecomment-256885690

**Comment by ZeldaZach** [comment]
I do agree with this idea... I'll try and look into it at some point

**Comment by Daenyth** [comment]
#2479
