### ISSUE TITLE
[Discussion] Kamban board for tasks?

### ISSUE THREAD

**Issue by poixen** [Cockatrice/Cockatrice#2347]
Currently there are over 400 issues and its hard to know the prio of each task (unless you look at tags). 
I think a kamban board would be great for devs to prio issues, maintain backlogs, and know what is being worked on.

https://waffle.io/ looks pretty good, though there are other solutions too.

Discuss below!

**Comment by ZeldaZach** [comment]
I'd love to have a management board of some kind. We can discuss options in the next few days.

**Comment by tooomm** [comment]
Tags are not perfectly set for each and every issue, too!
The idea of a visual support tool for management and planning sounds interesting. Or even just keeping track...

**Comment by skwerlman** [comment]
Why not use github's built-in boards? (It's the projects tab, between wiki and prs)

https://github.com/blog/2256-a-whole-new-github-universe-announcing-new-tools-forums-and-features
https://github.com/blog/2272-introducing-projects-for-organizations

**Comment by Daenyth** [comment]
I've used zenhub which is similar to waffle, and I really prefer the idea of keeping it all in github. So yes, let's think about how best to use projects
