### ISSUE TITLE
Program crash during replay

### ISSUE THREAD

**Issue by Mikefon** [Cockatrice/Cockatrice#2357]
<b>OS:</b>
Win 10 Home 64bit

<b>Cockatrice version:</b>
f7c8651d (2016-12-30)

___
<br>

When I try to view a replay (both on the server and downloaded) the program crashes just before the first card is drawn. 

Here I post the detailed application error report:

> - System 
> 
>   - Provider 
> 
>    [ Name]  Application Error 
>  
>   - EventID 1000 
> 
>    [ Qualifiers]  0 
>  
>    Level 2 
>  
>    Task 100 
>  
>    Keywords 0x80000000000000 
>  
>   - TimeCreated 
> 
>    [ SystemTime]  2017-01-11T08:52:12.917968900Z 
>  
>    EventRecordID 17353 
>  
>    Channel Application 
>  
>    Computer PC22 
>  
>    Security 
>  
> 
> - EventData 
> 
>    cockatrice.exe 
>    0.0.0.0 
>    586700ef 
>    cockatrice.exe 
>    0.0.0.0 
>    586700ef 
>    c0000005 
>    00000000000afc6e 
>    1a4c 
>    01d26be7570546d7 
>    C:\Program Files (x86)\Cockatrice\cockatrice.exe 
>    C:\Program Files (x86)\Cockatrice\cockatrice.exe 
>    1f343483-7eff-48c0-8069-c749ed57b267

**Comment by tooomm** [comment]
Did you check https://github.com/Cockatrice/Cockatrice/issues/2353#issuecomment-271494412?
You can download the most recent development build for Windows [here](https://bintray.com/cockatrice/Cockatrice/Cockatrice-git/0.0.1%7Egit20170108.be8c85b7#files).
Let us know how it goes!

**Comment by Mikefon** [comment]
Didn't check. I tried to use the "search button" but didn't find anything. I'm sorry.
Anyway, now it seems to work fine. 
Thanks.

**Comment by tooomm** [comment]
You're welcome! The other topic is mixing issues a bit and the description is general too due to the unknown problem, don't worry.
