### ISSUE TITLE
Crash on replay view.

### ISSUE THREAD

**Issue by Pablez94** [Cockatrice/Cockatrice#2360]
<b>OS:</b>
Windows 10 Home version 1607 build 14393.576

<b>Cockatrice version:</b>
f7c8651d (30-12-2016)

___
<br>

Upon playing a replay of a previous match played on the woogerworks server, the application crashes after a few seconds, rending myself unable to watch the game, and forcing me to restart the app.

**Comment by skwerlman** [comment]
This issue is already fixed in source: #2340

**Comment by tooomm** [comment]
Check https://github.com/Cockatrice/Cockatrice/issues/2357 for more information and a link to a fixed development build!

Enjoy :)
