### ISSUE TITLE
Mac user Replay Forward crashes cockatrice

### ISSUE THREAD

**Issue by derflippi** [Cockatrice/Cockatrice#2365]
Forwarding an issue from user mitic0ale on woogerworks server

<b>OS:</b>
macOS Sierra Version 10.12.2 (16C67)

<b>Cockatrice version:</b>
Versione f7c8651 (2016-12-30)

___
<br>

Whenever the Mac user presses "Forward" in a replay, cockatrice crashes on them. 
This issue happens for every replay they try to forward, so the problem is easy to recreate.

**Comment by skwerlman** [comment]
This is fixed in source: #2340
You can download a fixed development build here: https://bintray.com/cockatrice/Cockatrice/Cockatrice-git/0.0.1~git20170115.d452934#files
