### ISSUE TITLE
Power/Toughness font size too small on HiDPI screens

### ISSUE THREAD

**Issue by Steven--** [Cockatrice/Cockatrice#2368]
<b>OS:</b>
```
$ uname -a
Linux phantom 4.8.0-2-amd64 #1 SMP Debian 4.8.11-1 (2016-12-02) x86_64 GNU/Linux
```
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux testing (stretch)
Release:	testing
Codename:	stretch
```

<b>Cockatrice version:</b>
Version 784a75db (2017-01-11)
___
<br>

The Power/Toughness displayed on the bottom right of creatures is too small and almost unreadable on HiDPI screens. The font size should scale or there should be some options to set it in the preferences.

**Comment by Steven--** [comment]
After wildly grep-ing through the code I found the method transformPainter in abstractcarditem.cpp that has some hardcoded font sizes in it. Commenting the lines that cap the font sizes to 10pts works for me.
Here is the diff:

```
diff --git a/cockatrice/src/abstractcarditem.cpp b/cockatrice/src/abstractcarditem.cpp
index 5197f906..e24a1f9d 100644
--- a/cockatrice/src/abstractcarditem.cpp
+++ b/cockatrice/src/abstractcarditem.cpp
@@ -80,8 +80,8 @@ void AbstractCardItem::transformPainter(QPainter *painter, const QSizeF &transla
     int fontSize = round(translatedSize.height() / 8);
     if (fontSize < 9)
         fontSize = 9;
-    if (fontSize > 10)
-        fontSize = 10;
+    //if (fontSize > 10)
+    //    fontSize = 10;
     f.setPixelSize(fontSize);
 
     painter->setFont(f);
```

Since I'm in now way confident that this is the proper way to fix this, and I don't know how it interacts with the rest of the  code I'm refraining from submitting a pull request. Maybe someone that knows the code better than be can comment on this :)

**Comment by ZeldaZach** [comment]
Thanks for pointing this out to us. I'll see what we can do.
cc: @Daenyth

**Comment by Daenyth** [comment]
I have no idea why it's locked to those font sizes. @Steven-- if that change doesn't break anything else, would you put in a pull request with it (delete the lines instead of commenting.)

@ZeldaZach we should test the change on a small screen and see if it's an issue. It's unlikely to really hurt anything

**Comment by Steven--** [comment]
Sure, I will be able to test it this weekend.

**Comment by Daenyth** [comment]
Thanks
