### ISSUE TITLE
Registration Dialog Server Hardcoded

### ISSUE THREAD

**Issue by tritoch** [Cockatrice/Cockatrice#2369]
The `host` data in the registration dialog is hardcoded.

https://github.com/Cockatrice/Cockatrice/blob/c01d526161576988f05464a2e763a34f16c057e5/cockatrice/src/dlg_register.cpp#L17

It should pass `host` from the `connect` window (the most common way of reaching the `register` dialog is connecting to a server that does not have your username) and/or have a dropdown for approved servers.

**Comment by ctrlaltca** [comment]
What you see in the code just the default value; it should get the current server hostname from the config, but i suppose that could be broken. You already reported this in #2318.
I agree with you that the hardcoded value should be removed.
The work on this has already been started: see #1841, and a more generic discussion is happening on #2226.
