### ISSUE TITLE
Hebrew Characters in names

### ISSUE THREAD

**Issue by woogerboy21** [Cockatrice/Cockatrice#237]
So it has been pointed out to me that if the name of an account begins with a hebrew character that the text in the chat box (either main or private) is displayed on the right side of the chat window.  And no matter how the account is configured it never shows as elevated beyond an unregistered user account.

See:
http://i.imgur.com/nFbbuik.png

**Comment by ctrlaltca** [comment]
There's been a lot of work in the limiting the username accepted by the server (see #956 #963 #964 #965 #970 #972 #1159); as a result, RTL characters are no more possible in usernames.
