### ISSUE TITLE
Keyboard shortcuts not working since upgrading to Version f7c8651

### ISSUE THREAD

**Issue by robtandy** [Cockatrice/Cockatrice#2371]
<b>OS:</b>
Mac OS 10.10.3

<b>Cockatrice version:</b>
f7c8651

___
<br>

Since upgrading to this version, some keyboard shortcuts no longer work.  For example, pressing - in the deck editor decrements the number of that card, but pressing + no longer increments it.

Similarly, in the game power and toughness increment/decrement shortcuts no longer work.

**Comment by Daenyth** [comment]
What was your old version? Check the keybindings, I think some changed their defaults. You should be able to set the bindings to whatever you want, I think

**Comment by tooomm** [comment]
Check this in case you're not yet familiar with custom keyboard shortcuts:
https://github.com/Cockatrice/Cockatrice/wiki/Custom-Keyboard-Shortcuts

**Comment by ZeldaZach** [comment]
If you're still having issues on the latest version, let us know!
