### ISSUE TITLE
macOS Sierra, some replays regularly crash when viewing them while connected to a server.

### ISSUE THREAD

**Issue by mpalmujoki** [Cockatrice/Cockatrice#2375]
<b>OS:</b>
macOS Sierra, v 10.12.2

<b>Cockatrice version:</b>
Version f7c8651 (2016-12-30)

___
<br>

I noticed that I quite often have crashes when trying to view replays of online games, and the crashes occur at the same spot. Usually I have turned on the fastest replay speed when that occurs.

The same replay, when downloaded locally, does not crash. I wonder what might be causing the macOS crashes.

**Comment by Daenyth** [comment]
The replay crash will be fixed I'm the next release.

@zeldazach can we wrap a release soon? This issue is affecting a lot of
people

**Comment by mpalmujoki** [comment]
Perfect! I will happily be waiting for that release. I like when you support the Mac client.

Are you still researching the bug where the mac client crashes if you try to edit a loaded deck, that occurs in a few different scenarios (typing too fast, seems to crash for sure when I'm connected to a server)?

**Comment by skwerlman** [comment]
@mpalmujoki The version with the replay fix is out: https://github.com/Cockatrice/Cockatrice/releases/tag/2017-01-20-Release

**Comment by Daenyth** [comment]
Haven't figured out the other one yet
