### ISSUE TITLE
randomize system

### ISSUE THREAD

**Issue by micomicoa** [Cockatrice/Cockatrice#2379]
hi! this is just a question
since cocka is open source I would like, if possible, to see how the randomize algorithm is used, since some people are arguing on if it works or not.
A link is fine too! :) i found nothing on the net

thank you!

**Comment by ctrlaltca** [comment]
Hi!
Here's the random number generator we're using: https://github.com/Cockatrice/Cockatrice/tree/master/common/sfmt
You can (chi^2) test the RNG running servatrice with the "--test-random" parameter.

Some previous related discussion: #837 #475 #59 #58

If you are comfortable with algs, here's the short version: https://github.com/Cockatrice/Cockatrice/issues/475#issuecomment-65662556

**Comment by skwerlman** [comment]
(this is off-topic, but where can I find a list of servatrice's command-line args? they don't seem to be documented anywhere...)

**Comment by tritoch** [comment]
> (this is off-topic, but where can I find a list of servatrice's command-line args? they don't seem to be documented anywhere...)

https://github.com/Cockatrice/Cockatrice/blob/7f28a7e8441b9c8361d9d9c3757d8c4964242cfb/servatrice/src/main.cpp#L128-L138

--test-random
--test-hash
--log-to-console
--config

**Comment by tooomm** [comment]
Still OT:
We don't have it in the wiki regarding servatrice or the information for server operators? We should add it!

**Comment by skwerlman** [comment]
documented: https://github.com/Cockatrice/Cockatrice/wiki/Servatrice-Command-Line-Reference
