### ISSUE TITLE
looking top cards spectating future

### ISSUE THREAD

**Issue by micomicoa** [Cockatrice/Cockatrice#2380]
hi! it's just a feedback

win8
last version cocka

there are no future that let us to see top cards while spectating
this wouls be huge to spectate some kind of mtg matchups, i mean that you need to see what's the players seeing
please add this future :)

thank you

**Comment by Daenyth** [comment]
"last version" isn't a version, it changes depending on when someone reads this. 

Anyway you should be able to see what each player sees when the game is set to allow specs to view hands and other hidden info. If the game creator hasn't set spec view on then you see only public info.

**Comment by Daenyth** [comment]
Dupe #2384. Please don't file multiple tickets for the same thing, just update the existing one with the extra information

**Comment by micomicoa** [comment]
win 10

dab7316 (2017-01-19)

is the right system and cocka.
no. i tryed now just to be sure. we can't. 

i repeat, i mean while spectating, i can see hands, i can't see top 3 cards of a ponder even if a player can.
there is an option to allow to see hands, none to see top cards while seeing.
