### ISSUE TITLE
Can't "Show this user's games" on myself

### ISSUE THREAD

**Issue by LethalPigeon7** [Cockatrice/Cockatrice#2381]
<b>OS:</b>Win 7 SP 1
<b>Cockatrice version:</b> f7c8651d (2016-12-30)
___
The option to RMB myself and show the list of my games is disabled, why? Some things such as whether the room is buddies only, registered only, password protected or spectator rights aren't visible from inside the room. Sometimes, when no one is joining for a long time for example, I want to check that I didn't leave the room as buddies only on accident, and finding it in main is often much slower and less convenient than checking my own games.

**Comment by Daenyth** [comment]
Yeah this is reasonable to change

**Comment by ZeldaZach** [comment]
Can you possibly explain this issue a little further? I don't really understand

**Comment by LethalPigeon7** [comment]
You can right click any user and a dropdown menu will pop up.  When you click yourself, everything except "user details" is greyed out, clicking it does nothing. It makes sense for "add to buddy list/ignore list and private chat", but there's not for "show this user's games" as it works the same way as with anyone else. I gave an example of when this could be useful too.
