### ISSUE TITLE
UI somewhat freezes ingame.

### ISSUE THREAD

**Issue by ShawnMichaels** [Cockatrice/Cockatrice#2383]
WS8.1 

dab7316 (2017-01-19

___
Hello,

my User Interface ingame somewhat freezes no matter what I do. I can still use some hotkeys for phase changing for example (but only very limited), other inputs or commands evoke no reactions at all and most of my inputs are ignored by the UI. I can't even drag cards from hand to the field anymore. Sometimes my commands for changing phases only let me draw more cards for some reason, I have no idea why. This malfunction started to appear last summer hence I abstained from Cockatrice but right now I would very much like to play again so I seek help with you.

Thanks in advance.

**Comment by ZeldaZach** [comment]
Hmm, can you try uninstalling completely then installing the newest version from our website/bintray?

**Comment by ShawnMichaels** [comment]
I deleted pretty much everything that was associated with cockatrice on my PC and reinstalled again but didnt change anything.

**Comment by ShawnMichaels** [comment]
Also, if try to use that update function i will receive that infinite update loop that doesnt change anything effectively...

**Comment by Nightfirecat** [comment]
Does this happen only in online games, or does this affect local games as well?

**Comment by ShawnMichaels** [comment]
It also happens with local games it seeems :(

**Comment by Daenyth** [comment]
Hmm, that suggests it has something to do with the game view. @zeldazach
did anything there change recently?

**Comment by ShawnMichaels** [comment]
So I guess I wont get any more help on this unfortunately, right?

**Comment by ZeldaZach** [comment]
I haven't seen any changes to the UI service, so I'm not 100% sure. Can you possibly run trice in a debug state and see what happens?

**Comment by ShawnMichaels** [comment]
Is this what you mean?


Theme changed: "Fabric"
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
main(): starting main program
main(): MainWindow constructor finished
CardDatabase::loadCardDatabases start
main(): ui.show() finished
QWindowsWindow::setGeometry: Unable to set geometry 1366x731+0+20 on QWidgetWindow/'MainWindowClassWindow'. Resulting geometry:  1366x705+0+23 (frame: 8, 31, 8, 8, custom margin: 0, 0, 0, 0, minimum size: 861x731, maximum size: 16777215x16777215).
cache fail for "_trice_card_back_226292"
cache fail for "_trice_card_back_226290"
Trying to load picture (set:  "DTK"  card:  "Acid-Spewer Dragon" )
Picture NOT found, trying to download (set:  "DTK"  card:  "Acid-Spewer Dragon" )
starting picture download: "Acid-Spewer Dragon" Url: QUrl("http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=394485&type=card")
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Dari/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 16904 Sets= 203
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Dari/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 17238 Sets= 203
CardDatabase::loadCardDatabases success

**Comment by Daenyth** [comment]
Without knowing what the cause of this is I'm not sure how much we can
help.

**Comment by Bulldacious** [comment]
Has a fix been discovered for this yet?

**Comment by ZeldaZach** [comment]
Unfortunately, as Daenyth has said, we don't have enough information to attempt at working on a fix. If you're experiencing this issue, @Bulldacious , we'd really appreciate it if you could post some debugging /crash logs :)

**Comment by Bulldacious** [comment]
I have not noticed any connection problems for anything else, but it could be.
