### ISSUE TITLE
Specview should reveal "view top cards"

### ISSUE THREAD

**Issue by micomicoa** [Cockatrice/Cockatrice#2384]
<b>win 10</b>

<b>dab7316 (2017-01-19)</b>
___
<br>
hi
while spectating a game, if a player look at top cards, even if i can see his hand, i can't see those cards that he's looking at.
i just see in chat log if he moves them. can you implement this operation? we would be able to see what a player sees at least :)

thank you

**Comment by Jinxstands4Jinx** [comment]
honestly i think spectators should not be able to see hands even and it baffles me as to why anyone would want to.

**Comment by Daenyth** [comment]
By default they can't. You have to enable it. Personally I like playing with it on, because frequently after the game is over people discuss things.

**Comment by Jinxstands4Jinx** [comment]
I have never had the experience more often specs pm the players and give hints and such.

**Comment by Daenyth** [comment]
If that's your experience don't use it. I find vintage specs very
respectful and haven't had an issue

**Comment by Jinxstands4Jinx** [comment]
Personally it makes no sense, as in real life they could not see hands, so why would they here? not to mention in real life you do not spectate...unless you want free info which I personally never want nor do i want to give hence i never even use the spectators in rooms I make. They Also would not see top cards.  What you are thinking of is "coaching"

**Comment by Nightfirecat** [comment]
So are you saying that it should never be possible to use a "coaching" feature? I can see a lot of cases where people would like that to be possible.

**Comment by Jinxstands4Jinx** [comment]
I think it should be possible to coach. But i think the Table creator and The spectator should have a say. For example the Table creator Could check an option to allow specs to decide. Then when Specs come in, they can chose an option that would allow them to see any hidden cards (scys included) Or they could decline. At this point in time the Soul Power is Only in the Table creator. Not everyone wants help, and not everyone wants to see it all. Normally when I am able to see hands and watch a game, I cannot watch as the person playing is making so many Bonehead choices that I want to punch them and take over. I cannot be the only person who refuses to watch a Trainwreck.
Now, After a game I do not mind a lil discussion here or there, especially in a format like limited. I do not play vintage so I am not familiar with any need to discuss there.

**Comment by Daenyth** [comment]
I'm not removing spec view. Making it toggleable on the client would be more work than it's worth. If you don't like it, don't use it. Let's please leave this ticket to be on topic, which is to allow specview to see top card data.

**Comment by tooomm** [comment]
Good suggestion.
Do spectators see a reveal library action right now? I would extend that request to cover this and similar actions as well, not just "reveal top cards"!

On a site note:
I generally like the idea jinx has in place.
It would be quite cool to change the spectator approach a bit and even make it player dependent (next to the general approach maybe). So any player can decide if he wants that particular spectator to give more "viewing power" over his own cards. I'm speaking of a view `view hidden information` on a per player + per spectator basis. This allows for coaching and such while the other player don't need to worry about cheating! 👍

**Comment by Jinxstands4Jinx** [comment]
exactly.

**Comment by ZeldaZach** [comment]
Related heavily to #2983
