### ISSUE TITLE
Downloading Cockatrice on Mac OS

### ISSUE THREAD

**Issue by adunne09** [Cockatrice/Cockatrice#2385]
<b>OS:</b>
OS X 10.9.5

<b>Cockatrice version: 10.10+ MacOS</b>
> 

___
<br>

I just learned about Cockatrice and tried to download it on the Mac OS. When I opened it the Cockatrice application was always "disconnected", even when I tried to connect it, and the Servatrice app didn't work either. When I deleted one of the windows that is used to build decks, there didn't seem to be any way to get them back up and I also couldn't find where my "decks" were stored on the computer. Please help!

**Comment by ZeldaZach** [comment]
As you can tell by your OS and what you put as your client version... your OS is too outdated to use the pre-compiled binary files. You'll either have to a) Update your OS or b) Compile trice yourself.

We can walk you through either a or b if you'd like

**Comment by adunne09** [comment]
Yes could you help me compile trice I updated my computer to the most recent update but cockatrice still had the same problems as before.

**Comment by Daenyth** [comment]
When you go to "About this Mac" What version of OSX does it say now?

**Comment by adunne09** [comment]
10.12.3

**Comment by tooomm** [comment]
So you are good to go and can just download and install the macOS file from our website: https:/cockatrice.github.io

After doing so let us know which problems still persist for you!

**Comment by adunne09** [comment]
> On Jan 26, 2017, at 8:15 PM, tooomm <notifications@github.com> wrote:
> 

This is what comes up after tried to download it again. For the first picture, that is the only option I have and I still can’t see the deck I’m building. Cockatrice always says disconnected and for the second pic, servatrice doesn’t seem to do anything.

**Comment by tooomm** [comment]
>This is what comes up after tried to download it again. For the first picture, that is the only option I have

I have no idea what you are talking about. Can you try to explain with different words, please?


>and I still can’t see the deck I’m building.

What can't you see? The list of cards in your deck?
Card art of the selected card?
...

>Cockatrice always says disconnected

It will do so for sure - until you register (in menu, go to `Cockatrice --> Register to server...`) and `Connect...` yourself afterwards to the same server.

> and for the second pic, servatrice doesn’t seem to do anything.

Servatrice is the server part of the application and is not needed at all to build decks, play games offline or online.
Just ignore it, it is just needed if you want to run your own server that other people can connect to. (Advanced)
Mostly all people use public servers from [this list](https://github.com/Cockatrice/Cockatrice/wiki/Public-Servers) to connect to and play there. Woogerworks is the biggest and most famous one right now.

By the way, which "pictues" or "pic" are you speaking about all the time? I have no clue what you mean.

**Comment by adunne09** [comment]
Don’t worry about it I just wanted to get the application on the mac but I have a windows laptop and it works very well there. thanks for the help though.

**Comment by adunne09** [comment]
Btw, the “pics” i mean are the ones I put in the email. The biggest problem is that there doesn’t seem to be any menu available.

**Comment by Daenyth** [comment]
@adunne09 Email replies to issues do not attach images. Can you attach them manually via dragging them into the text box on the website?

**Comment by ctrlaltca** [comment]
Closed: no news is good news.
