### ISSUE TITLE
Gummy Privlevel in PM transposed

### ISSUE THREAD

**Issue by tritoch** [Cockatrice/Cockatrice#2386]
<b>Cockatrice version:</b>
dab7316 2017-01-19

___
<br>

When PMing a user with elevated PrivLevel (Donator, VIP), the Gummy colors/flair are swapped between users.

If VIP_USER and DONATOR_USER are engaged in a private message, VIP_USER will have a purple gummy and DONATOR_USER will have an orange/gold gummy.  This is reverse of what their icons appear in chat and in the user list.

If VIP_USER and DONATOR_MOD are engaged, VIP_USER will have a purple gummy, and DONATOR_MOD will have a white/black with star (VIP mod) gummy.

**Comment by ZeldaZach** [comment]
Haha I find this funny. I'll take a look as it's probably just a small issue in the code from a copy/paste or something. Can you include pics possibly so I can confirm?

**Comment by tritoch** [comment]
![bug-vipvip](https://cloud.githubusercontent.com/assets/3866018/22357824/6096c56c-e400-11e6-9c45-9ae88633c243.png)
![bug-vipdonor](https://cloud.githubusercontent.com/assets/3866018/22357825/60a546d2-e400-11e6-8f27-b9203b71cbee.png)
![bug-vipreg](https://cloud.githubusercontent.com/assets/3866018/22357826/60a7892e-e400-11e6-9301-526073903baf.png)

**Comment by ZeldaZach** [comment]
Maybe you see something I dont, but it looks right to me...?

**Comment by woogerboy21** [comment]
> Maybe you see something I dont, but it looks right to me...?

Take a look at tritoch's gummy in each picture....

**Comment by woogerboy21** [comment]
@tritoch Was each of the posted image conversations in PM or else were throughout the client?
