### ISSUE TITLE
"Error Opening File For Writing" error (Attached Screenshot)

### ISSUE THREAD

**Issue by Swaguu** [Cockatrice/Cockatrice#2387]
<b>OS:</b>
Win 10
<b>Cockatrice version:</b>

Cockatrice_All_Hallows_Eve_Revision2_win64

___
<br>

![erroropeningfileforwriting](https://cloud.githubusercontent.com/assets/25379602/22359570/69be8d30-e416-11e6-9eaf-1785ab9b82f8.png)

**Comment by skwerlman** [comment]
It looks like cockatrice is still open in the background. Can you try again after closing it?

**Comment by woogerboy21** [comment]
Yup, this generally happens when either you a) dont have access to write something to the destination or in most cases with the installer you leave the old version running while trying to install a newer version.
