### ISSUE TITLE
Error 0xc000007b

### ISSUE THREAD

**Issue by owerbart** [Cockatrice/Cockatrice#2389]
<b>OS: Windows 10</b>
*Windows 10 Home Edition*

<b>Cockatrice version: Cockatrice All Hollows Eve Revision2 (both 64 and 32 bit)</b>
*Cockatrice_All_Hallows_Eve_Revision2_win32 AND Cockatrice_All_Hallows_Eve_Revision2_win64*

Everytime I Try to access the program, an error window comes up saying "Error 0xc000007b", I have never updated my previous cockatrice program before, which was "Cockatrice-WindowsClientQT4" and didn't have any issues. But now that I require the new version it doesn't seem to work. I tried installing the Gatewatchers version and I'm getting the same mistake.
___
<br>

*I can't start the program due to error 0xc000007b*

**Comment by skwerlman** [comment]
https://github.com/Cockatrice/Cockatrice/wiki/Troubleshooting#not-a-valid-win32-application-0xc000007b

**Comment by Daenyth** [comment]
If the link above doesn't fix your problem please let us know

**Comment by seska588** [comment]
Hello, I'm getting this error out of the blue . i tried reinstalling, nothing seems to work. Can anybody help?

**Comment by tooomm** [comment]
What‘s your version and system?
When does the error appear?

Please provide some information...

Did you read and follow the help found above?!

**Comment by seska588** [comment]
> What‘s your version and system?
> When does the error appear?
> 
> Please provide some information...
> 
> Did you read and follow the help found above?!

I tried everything i could find. Did not work. I have windows 10, 64 bit. 

It happens right away when i try to open cockatrice. I tried reinstalling. didn't work either.

**Comment by tooomm** [comment]
Cockatrice version? Where did you download it?

**Comment by seska588** [comment]
I tried the one on https://cockatrice.github.io/ for windows and the new blessed sanctuary one for windows 64 bit.

**Comment by ebbit1q** [comment]
Can you follow the steps here to make sure your computer is running the 64 bit version? https://support.microsoft.com/en-us/help/15056/windows-32-64-bit-faq
This page is linked in faq linked above, if you have a 64 bit cpu it doesn't neccesarily mean the os is 64 bit as well.

**Comment by seska588** [comment]
I just did. 64-bit operating system, x64-based processor .

**Comment by seska588** [comment]
can anybody else help? This issue really doesn't make any sense. I've had cockatrice on my computer for years, it's always worked fine, but then the other day, when i tried to open it, this happened.

**Comment by tooomm** [comment]
What did you do with your computer in between?
Which apps or drivers did you install or remove? Or did you update your windows system in between etc.?
Do you use a Firewall by the way?

The error is very generic and used to pop up when users tried to install the 64bit version on 32bit systems which is not the case for you it seems. No clue what is casing it here, sorry.

**Comment by ebbit1q** [comment]
Have you tried reinstalling it?

**Comment by seska588** [comment]
I remember uninstalling a few things i wasn't using anymore. and i have tried reinstalling numerous times.

**Comment by tooomm** [comment]
Did you uninstalled a variant of `Microsoft Visual C++ Redistributable` maybe? Cockatrice needs that to work.

But during setup, Cockatrice normally installs it... maybe try properly uninstalling Cockatrice and then install fresh from scratch. Save your decks and themes etc. before!

**Comment by seska588** [comment]
I currently have :
Microsoft Visual C++ 2013 Redistributable (x64) - 12.0.21005
Microsoft Visual C++ 2013 Redistributable (x86) - 12.0.21005
Microsoft Visual C++ 2015-2019 Redistributable (x86) - 14.25.28508

**Comment by tooomm** [comment]
I think Cockatrice needs 2017 v15 (x64 on your PC).

Please uninstall Cockatrice completly, restart and do a full install. At the end the correct vcredist should install automatically.

**Comment by seska588** [comment]
Just did exactly what you said, same error.

**Comment by tooomm** [comment]
Do you have a new/different `Microsoft Visual C++ Redistributable` entry in your list of installed software now?

I'm sorry, but I can't do more than reopen the issue...

The smartscreen warning is normal and happens for all setup files that are not signed with a charged microsoft key.

**Comment by seska588** [comment]
I know that there was one that got installed during the Cockatrice installation. Everything went just fine.
