### ISSUE TITLE
[Linux Mint 17] Partial loss of sound [Custom Sounds]

### ISSUE THREAD

**Issue by AWebb3701** [Cockatrice/Cockatrice#239]
I've replaced my sounds with ones CONFIRMED working previously on my windows install. The files are not damaged in any way. I am currently running Summer Magic (compiled from source) natively on linux, no WINE or other shenanigans.

I can hear my shuffle and my card play sounds, but I can't hear tap, untap, phase changes, or notifications. Quite vexing.

**Comment by ZeldaZach** [comment]
Is this still a problem? If so, please reopen
