### ISSUE TITLE
Unlawful Ban / Discrimination 

### ISSUE THREAD

**Issue by Usumari95** [Cockatrice/Cockatrice#2390]
<b>OS:</b>
Windows 7

<b> f7c8651d (2016-12-30)</b>

___
<br>

My username is Usumari
Recently i was banned from the main server unlawfully with reason "Way to win like a fag"
This is discrimination, and harassment. 
I would like the username and info of the admin in question and him removed from the service.

**Comment by skwerlman** [comment]
This repo is for the cockatrice application, not for any of the servers, which are all independent. Your best bet is to get in touch with the owner of the server you were banned from.

**Comment by Daenyth** [comment]
To make it more clear; this site is for the people creating the software itself. We don't actually run any official servers.
