### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by nikisix** [Cockatrice/Cockatrice#2391]
A year ago one could select background images in the appearance dialog. Is there any plan to bring that back?
Additionally, how hard would it be to to make a dark theme where the whole client was darker and had light text? I'm a software-dev, so I'm fine with making some code changes and recompiling myself if you could just give me a few pointers of where to look.
I live in the terminal and only use Chrome and Cockatrice gui's, so a dark-themed Cockatrice would be like Christmas to me.
Thanks!

**Comment by Daenyth** [comment]
We replaced the image selection with a full theme system. You can control *almost* everything (some stuff is hardcoded right now) with CSS.

See the themes page on the wiki: https://github.com/Cockatrice/Cockatrice/wiki/Themes

**Comment by Daenyth** [comment]
You can switch themes in Settings > Appearance. There's also a list of user-created themes on that wiki page; there's some dark ones. Sometimes people post themes on reddit /r/cockatrice as well
