### ISSUE TITLE
problems with the sideboard.

### ISSUE THREAD

**Issue by Oskarb20** [Cockatrice/Cockatrice#2394]
Window 10 
Versión dab7316 (2017-01-19)

I have problems with the sideboard.
I can not add letters to the sideboard.

https://github.com/Cockatrice/Cockatrice/issues/2139

It is somewhat similary to this problem but I have no results.

Please help

**Comment by Daenyth** [comment]
Can you try to explain what you mean by problems and by letters? I don't understand.

Maybe add screenshots?

Also if English is not your native language, try describing the problem in the language that you do speak; some people around here can help translate.
