### ISSUE TITLE
missing features

### ISSUE THREAD

**Issue by 123farfetch** [Cockatrice/Cockatrice#2396]
<b>OS:</b>
*Windows 8*

<b>Cockatrice version:</b>
*hallows eve revised 2*

___
<br>

*So I reinstalled cockatrice multiple times, but it still says that my client has missing features (idle_client) and need to update, is there any simple solution? Just wanting to play here. Also while installing, it notifys a series of .dll problems, and I just force it to ignore and continue instalation*

**Comment by skwerlman** [comment]
what 'dll problems' are you seeing, exactly? if it's related to permissions, make sure you quit out of cockatrice _before_ updating.

**Comment by 123farfetch** [comment]
Error opening file for writing:
qt5core.dll
qt5gui.dll
qt5multimedia.dll
qt5network.dll
qt5printsupport.dll
qt5svg.dll
qt5widgets.dll
even cockatrice.exe
qdds.dll
qgif.dll
qicns.dll
qico.dll
qjpeg.dll
and goes on one five more files.

So after this issue I tried to update it inside the software, but it crashes.
Already unninstalled and installed multiple times.
But the only thing that accuses is missing feature (idle_client)

**Comment by skwerlman** [comment]
Did you try reinstalling while cockatrice was closed? Those DLLs would only have problems if cockatrice is still open during the install.

**Comment by 123farfetch** [comment]
I closed it on the task manager and it worked! Thank you!

**Comment by skwerlman** [comment]
Awesome! If you arent having any further issues, feel free to close this.
