### ISSUE TITLE
Filter Games option forgets "Show Buddies Only Games" status

### ISSUE THREAD

**Issue by Xelsia** [Cockatrice/Cockatrice#2399]
<b>OS:</b>
Windows 10

<b>Cockatrice version:</b>
F7C8651D
___
<br>

I find that Cockatrice occasionally forgets what I have selected for "Show 'buddies only' games". I always have it turned off because I'm a crusty hate filled individual who never plays in buddies only games, but sometimes it turns back on. I've even had it on a few rare occasions show me buddies only games when it's been unchecked.
Can't offer any steps to reproduce sorry, just thought I'd mention it to document it.

**Comment by woogerboy21** [comment]
> because I'm a crusty hate filled individual who never plays in buddies only games 

This gave me a chuckle...

**Comment by LethalPigeon7** [comment]
Mentioned this (or something similar) earlier (#2159),

**Comment by Daenyth** [comment]
This should be easy to fix
