### ISSUE TITLE
Power and Toughness Hotkey not working for increase

### ISSUE THREAD

**Issue by tjhunter59** [Cockatrice/Cockatrice#2400]
<b>OS:</b>
OS X 10.11.6

<b>Cockatrice version:</b>
Version dab7316 (2017-01-19)

___
<br>

I reinstalled Cockatrice a few days ago and noticed that all the other hot keys seem to work but I can not get the Power and Toughness to increase. I have even changed from standard settings to try to make it work, and I still can not hot key. I can manually switch it, but when adding several +1/+1 counters to each creature every turn...it gets extremely time consuming to try to play. Thanks for the help!

**Comment by timdonovanuk** [comment]
Same on the latest Windows client.
