### ISSUE TITLE
Revert new nested counter menu

### ISSUE THREAD

**Issue by Jinxstands4Jinx** [Cockatrice/Cockatrice#2402]
Ok this may not be explained correctly, Bear with me. Recently there was a build with the Token creation process changed. Specifically counters. You would select your token, and then put counters on.  Now you have to select color and counters seperately adding a 3rd step to this process... This is not an improvement more like a step backwards. because of this people are using tokens less actually and its very annoying and rude to not use the Actual tokens. We should revert this back to the way it was.

**Comment by Nightfirecat** [comment]
I'm not really clear what you mean&mdash;below is how I see it. What are you seeing?
![token creation process](http://i.imgur.com/BdU7xdu.gif)

**Comment by Jinxstands4Jinx** [comment]
yeah ur on the new set up. the old set up was much quicker. The area where you go to add counters used to be quicker. like minus a step.  Now its 1 more additional step and takes slightly longer to make counters for things. Also the cards From AER are STILL not linked to their correct tokens

**Comment by Nightfirecat** [comment]
Oh, so this issue is specifically with the counter entries in the right-click menu? (doesn't have anything to do with tokens)
That was implemented in #2348 to save space. I don't see it as "an additional step", since it doesn't take more clicks to achieve the same effect. If you're using those often, it would save more time to assign keyboard shortcuts to them and use those instead.

**Comment by Jinxstands4Jinx** [comment]
the token part was mainly the issue with AER tokens not be assigned to their cards yet. but yeah the counters need to be reverted back. it saves space now but is hell in the process now. such a pain in the ass and now people have more reasons to NOT use them and its been creating a ton of hassles since people do not want to waste time making the Correct tokens or using the correct counters even.

**Comment by woogerboy21** [comment]
@Jinxstands4Jinx Are you saying the sub menu is causing issue's with adding counters due to additional time it takes ? (in a nut shell)

**Comment by Jinxstands4Jinx** [comment]
yes wooger, that is my issue. That and the fact that it takes so long for the AER cards to be linked to their proper tokens.

**Comment by Daenyth** [comment]
If it really is causing users to avoid using counters at all we should probably revert it.

**Comment by woogerboy21** [comment]
> yes wooger, that is my issue. That and the fact that it takes so long for the AER cards to be linked to their proper tokens.

I didnt mean any negativity with the question, just clarity on my part.  I dont really work with the UI much so experience wise I am disconnected in that aspect.  The next question I would have is, being a user that does this particular action often, is there a short cut available for such an action?

**Comment by Jinxstands4Jinx** [comment]
Thats fine wooger I did not see your response as negative. I was not aware that I had the ability to rewrite the buttons sequence and make my own shortcut, I am trying that now, hopefully i find it easier. I just noticed this and I have an issue, I like the table to Always be correct. maybe its ADhd or just a compulsion but when my opponents do not use the correct tokens, or counters (because it now takes longer) it messes up my focus and just puts me off the game in general.  I apologize if you do not see as a huge issue I just foresee future frustrations and am attempting to nip this in the butt.

**Comment by woogerboy21** [comment]
Looks like there is a way to add shortcuts.....  (honestly i wasnt sure if there was or not).

![image](https://cloud.githubusercontent.com/assets/1361287/22562171/71dad522-e949-11e6-828a-66b770824261.png)

**Comment by woogerboy21** [comment]
@Nightfirecat How did you do the animated image post?

**Comment by Jinxstands4Jinx** [comment]
he probably recorded it and is playing it on a loop. but yeah i found that wooger hopefully it helps will report back if not

**Comment by Nightfirecat** [comment]
[GifCam](http://blog.bahraniapps.com/gifcam/). It's the easiest GIF recorder I've used thus far.

**Comment by Jinxstands4Jinx** [comment]
the shortcuts did not work at all. I tried to set them and instead it became a shortcut to include the stuff i have in my "auto text" area which i use for notes.  I attempted to set the "add green counters button to CTRL+1 and red to ctrl2 and yellow to Ctrl3. that did not work.

**Comment by Daenyth** [comment]
Can you file that as a new issue?

**Comment by LethalPigeon7** [comment]
I'm not sure if it's too late to chime in, but I was in the middle of making a dupe when I realised it could be fixed with shortcuts. But yes, it makes it take about 3 times as long as it did before for me and it saves a minimal amount of screen space, even if shortcuts didn't work I probably wouldn't stop using them but it's safe to say it's made the experience worse for me.

**Comment by KarasuGamma** [comment]
I'm also going to add a voice for disliking the new system. @LethalPigeon7 summarized it perfectly, regarding time added compared to space saved, and I have also encountered players who don't use counters now.

**Comment by Daenyth** [comment]
@ZeldaZach If you have time would you please revert the change?
