### ISSUE TITLE
Connection Issues, Missing Idle Client

### ISSUE THREAD

**Issue by legendofme** [Cockatrice/Cockatrice#2403]
<b>OS: Windows 10 Home</b>

<b>Cockatrice version: d55e44e</b>

___
<br>

When I try to Connect and login, I get the following error:
"Your client does not support features that the server requires, please update your client and try again."
When I click "show details," it says that it's missing "idle_client."

I redownload the newest version and I'm able to connect normally, but if I close Cockatrice or shut down my computer, I get the same error when I try to connect later. How can I fix this? Thanks!

**Comment by Daenyth** [comment]
Very strange. If you get that error message it means you're running an old version of the client. Try running any and all cockatrice uninstallers you can find, then run the installer for the new version again

**Comment by legendofme** [comment]
Good advice! I found that I had Cockatrice installed on both my C: and D: drives, and I had been just uninstalling/reinstalling the C: drive version. Uninstalled both and reinstalled the latest version and everything appears to be working! Thank you, Daenyth!

**Comment by Daenyth** [comment]
Glad it's working for you now!
