### ISSUE TITLE
Not working on Manjaro 16 (Arch Linux)

### ISSUE THREAD

**Issue by fjsaezm** [Cockatrice/Cockatrice#2404]
I have installed Cockatrice from the AUR repository and it worked for me for some time.
Now , it says that I have to update the client to be able to play in woogerworks (server), but i can't update the client because there is no version for Arch.

Has anybody solved that?

**Comment by skwerlman** [comment]
You can compile it for yourself while waiting for the AUR to update. I know there aren't instructions for arch for whatever reason, but the process is the same as it would be for any other nix:

```bash
git clone https://github.com/Cockatrice/Cockatrice
cd Cockatrice
mkdir build && cd build
cmake ..
make
sudo make install
```

**Comment by fjsaezm** [comment]
It worked perfectly, thank you so much @skwerlman !!!

**Comment by Daenyth** [comment]
I recommend using the `cockatrice-git` aur package anyway
