### ISSUE TITLE
Related cards with AER

### ISSUE THREAD

**Issue by Jinxstands4Jinx** [Cockatrice/Cockatrice#2405]
I know this may be just me being dumb. but the AER cards do Not have their related tokens linked to them. Example [[Aether harvester]] Does not link to the energy reserve token.

**Comment by Daenyth** [comment]
Run Oracle again?

**Comment by Jinxstands4Jinx** [comment]
will attempt

**Comment by Jinxstands4Jinx** [comment]
ok had to run the token half also which i normally do not run as it erases custom tokens
