### ISSUE TITLE
Forced update after missing "idle_client", new version shows 0xc000007b error

### ISSUE THREAD

**Issue by joanthedark** [Cockatrice/Cockatrice#2409]
<b>OS:</b>
*Win 7 Ultimate SP1*

<b>Cockatrice version:</b>
*d55e44e (2015-09-23).*

___
<br>

*I used to play normally on that old client (d55e44e 2015-09-23), a few months ago it started giving me a message saying that there are some features not supported by my client, yet I could still play. Now it is not letting me login to cockatrice.woogerworks.com and tells me to update. After I do so (Cockatrice_All_Hallows_Eve_Revision2_win64) it gives me the 0xc000007b error in both oracle/cockatrice, tried development builds and they do the same thing. I still have the old client executable and when I try to reinstall that one I can open both oracle/cockatrice without problems.

My take on it is that at some point in development they made some files necessary in order to make them run. There are two possible solutions in order to fix my problem:

- Which dll files were added in newer versions? So I can just find those specific ones instead of reinstalling Visual C++ all over again (which in some cases doesn't even help people resolve their issue).
- How do I add this "idle_client" to the old client that works like a charm for me?

Thank you in advance.*

**Comment by skwerlman** [comment]
Are you running 32- or 64-bit windows?

**Comment by joanthedark** [comment]
Win 7 Ultimate SP1 64 bits

**Comment by Nightfirecat** [comment]
https://github.com/Cockatrice/Cockatrice/wiki/Troubleshooting#not-a-valid-win32-application-0xc000007b

**Comment by woogerboy21** [comment]
You should consider getting your run time environment fixed and not attempt to "hack" an older client to make it work.  Doing so would require you to recompile the "older" client most likely resulting in you fixing your runtime issue's in the end anyways 😄

**Comment by Daenyth** [comment]
Have you checked https://github.com/Cockatrice/Cockatrice/wiki/Troubleshooting#not-a-valid-win32-application-0xc000007b ?

**Comment by ctrlaltca** [comment]
Closed: no news is good news.
