### ISSUE TITLE
Don't automatically annotate tokens from text tag.

### ISSUE THREAD

**Issue by Psithief** [Cockatrice/Cockatrice#241]
Requires the functionality of  *#233 Add back support for custom picture urls in cards.xml* or equivalent.

Assuming there's uptake of this version of [`tokens.xml`](https://github.com/Psithief/Cockatrice-tokens/blob/master/tokens.xml) there's no benefit in copying the `<text>` field contents to the annotation by default because there's an image for each token with the required text already.

It's a hack that was useful when there were many holes in the tokens database but should be scrapped now.
![token_annotation](https://cloud.githubusercontent.com/assets/1124846/3748691/efd7b32e-17e0-11e4-827f-678ba7485acf.png)

**Edit (2014-08-05)** Making this a *client-side only* suppression of the annotation text without affecting the game state would probably be the ideal solution.

**Comment by ZeldaZach** [comment]
I'd like to bump this post to see if anyone can possibly look into this

**Comment by Psithief** [comment]
I think adding more conditions to skip the annotation drawing is the way to go. [(carditem.cpp line 117)](//github.com/Cockatrice/Cockatrice/blob/master/cockatrice/src/carditem.cpp#L117)

Something like:
* if annotation isn't empty and annotation text does not exactly equal card text

**Reason:** If the local player has the matching text in their card database then it will be shown when the token is hovered (to the right) / middle-clicked (popup), regardless of image availability.

But I don't know c++, not even how to do string comparisons.

**Comment by ColinHebert** [comment]
Any news on this one? That would be a fantastic feature!

**Comment by arxanas** [comment]
@ColinHebert: How does this aid the linked commit? This is purely about the display of tokens, which is a personal preference; it wouldn't make it possible to omit card text in the tokens file. (For example, with me being the sort of person who prefers annotations over images, I would like to have the card annotations displayed regardless of whether or have an image. That requires the tokens file to have the annotation text.)

**Comment by ColinHebert** [comment]
In the case above, I was trying to use Tokens for flip cards. Cards such as [[Garruk, The Veil-Cursed]] can be extremely verbose and makes the card very hard to read.

On top of that, the annotation stays above the counters, which is not ideal when using a flipped planeswalker with a ton of text.

I know there is a part of personal preferences, but objectively having the entire text written in the annotation is not going to work with every card.

Another example would be [[Huntmaster of the Fells]]//[[Ravager of the Fells]] which has a fair bit of text with the card:

> Trample
>Whenever this creature transforms into Ravager of the Fells, it deals 2 damage to target opponent and 2 damage to up to one target creature that player controls.
>At the beginning of each upkeep, if a player cast two or more spells last turn, transform Ravager of the Fells.

Obviously when the only text is "Flying" it's less of a problem, but it isn't always the case.

This doesn't apply to flipcards only, some tokens can be verbose themselves (an example would be the elemental from [[Voice of Resurgence]]).

**Comment by ZeldaZach** [comment]
When you create the token, if you leave the annotation field blank, it shouldn't annotate the cards

**Comment by ColinHebert** [comment]
@ZeldaZach unfortunately that also means that the abilities won't show up in the right hand side panel ether, which is still something that should always be there IMHO.

**Comment by ctrlaltca** [comment]
Now that we have a nice token source (thank you @Psithief ), i agree we could avoid annotating card text on tokens by default.

**Comment by ZeldaZach** [comment]
I'd be fine with that @ctrlaltca. Let me see what I can do

**Comment by Psithief** [comment]
You'll probably want to implement #915 with this one as well then.

**Comment by ZeldaZach** [comment]
Yeah, for sure
