### ISSUE TITLE
Intro amend

### ISSUE THREAD

**Issue by Jinxstands4Jinx** [Cockatrice/Cockatrice#2410]
A while ago I wrote a "intro" to cockatrice for newer players. In fact you guys amended it and put it on the main site ( i cannot find a link but yeah) I would like to add to that intro.  I will not supply the original but here is the AMENDED intro.

Ctrl L= Set life total
Ctrl M= Mulligan
Crtl D= draw card
Crtl T= make token
Ctrl W= Scry
Ctrl I= Dice roll
Ctrl R= Remove arrows
Ctrl F3= look at sideboard during game. (useful for edh)
Ctrl f2= Concede.
CTrl S = Shuffle

Most players prefer you go to end and Do Not pass the turn as it messes up EOT plays and can jeopardize game flow causing arguments.

Right click cards does most functions.

Drafting/Sealed

enter a draft/sealed room and the host will give you a link once you reach correct number of players (most cases 8) that link wil be to DR4ft.com draft site and they allow you to draft by picking cards and building a deck, they even provide lands. It is good practie to include some lands in your sidebaord as adding them later becomes impossible. Once you build the deck you will download it an you and your opponent will move to a seperate room to play best of 3 games. you ose then good luck in next draft. You win then report back to the main draft lobby and inform players remaining that you are "ready for Round 2". 

Edh Kingdoms

Players Only:
This is a Format of edh that many people play. It has a few rules, https://www.reddit.com/r/EDH/comments/1plyyj/kingdoms_edh_variant/
For this format make sure you know how to open your Sideboard. ( Ctrl f3 )
When You enter a room set up for edh Kingdoms, (normally 5 or 6 players) You will start like a normal edh game, get your commander out, and shuffle, but Do not roll a dice. Instead open your sideboard and wait for the host to place 6 face down cards on their board. When the host does this, you should draw an arrow from your name to 1 of the cards. Wait patiently and your host will hand you your card. WHILE HOLDING SHIFT move that card into your sideboard. Do Not reval this card to anyone, except yourself. If you are the plains, then take it out and place it in the stack with your commander(s). If you die, Do not reveal your role until the game ends. If you leave the game before that time, make sure you apolgize and hopefully you do not make a habit or the people who host kingdoms may ignore you. 

Host:
Your job is to assign the roles. you do this by 2 methods. you can have the lands already in your board or you can make tokens for them. (if you chose method 2, you have to uncheck the box labeled (( Destroy token when it leaves the battlefield)) Draw ur entire deck into your hand. Then place the 5 or 6 lands out and move them to your library, Shuffle atleast twice. then While Holding Shift Drag the cards to the table area in front of you. Your players will pick roles, You get the one no one picked. Once that is done, make sure to move ur hand back to your library (all at once PLZ). For best results use the right click mouse option as you do not want to reveal the contents of your library to your opponents. The King will reveal himself, and the game should proceed like normal. No one reveals roles until the game has ended.

Arrow Drawing

When drawing an arrow (normally with mouse to show what you are targeting and such)  You can draw multiple colored arrows.

For a red arrow, do nothing (default)
For a green arrow, hold shift while drawing
For a blue arrow, Hold Alt while drawing
For a yellow arrow, hold CTRL while drawing

----------------------
I added the Kingdom section because i see so many kingdom games messed up for so many reasons. Any input would be appreciated

**Comment by Daenyth** [comment]
That page lives here: https://github.com/Cockatrice/Cockatrice/wiki/One-minute-game-guide

It's free to edit

**Comment by Nightfirecat** [comment]
If you want to make edits to the main cockatrice.github.io site, you could make a pull request here: https://github.com/Cockatrice/cockatrice.github.io

**Comment by Jinxstands4Jinx** [comment]
well i never noticed it was free to edit, then I will do so.

**Comment by Jinxstands4Jinx** [comment]
I edited the intro thx Gavin for the help

**Comment by Daenyth** [comment]
Thanks! It's a huge help to the community to have good docs
