### ISSUE TITLE
Show card back instead of nothing in deck editor

### ISSUE THREAD

**Issue by skwerlman** [Cockatrice/Cockatrice#2411]
<b>OS:</b>
Arch Linux

<b>Cockatrice version:</b>
3498b16e

___
<br>

If memory serves, in the deck editor, when you selected a card without an image (either custom or downloaded), cockatrice used to show the the card back instead of the card. For a while now (going back to at least #1984), cockatrice has been displaying nothing instead of the missing card image, which is worse IMO.

**Comment by ZeldaZach** [comment]
If you see nothing it usually means the card is either downloading (which can take a long time in some cases) or the page returned an error that wasn't 404

**Comment by skwerlman** [comment]
```
Theme changed: "Default"
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
main(): starting main program
main(): MainWindow constructor finished
CardDatabase::loadCardDatabases start
main(): ui.show() finished
cache fail for "_trice_card_back_299198"
cache fail for "_trice_card_back_299100"
[CardDatabase] loadCardDatabase(): Path = "/home/arch/.local/share/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 16904 Sets= 203
[CardDatabase] loadCardDatabase(): Path = "/home/arch/.local/share/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 17238 Sets= 203
CardDatabase::loadCardDatabases success
cache fail for "_trice_card_back_299524"
Trying to load picture (set:  "pCEL"  card:  "1996 World Champion" )
Picture NOT found, trying to download (set:  "pCEL"  card:  "1996 World Champion" )
starting picture download: "1996 World Champion" Url: QUrl("http://gatherer.wizards.com/Handlers/Image.ashx?name=1996 World Champion&type=card")
Picture downloaded, but blacklisted, will consider it as not found
Picture NOT found, download failed, no more sets to try: BAILING OUT (oldset:  "pCEL"  card:  "1996 World Champion" )
QPixmap::scaled: Pixmap is a null pixmap
```
Looking at the logs, this might be a different issue than I thought it was.

The card back appears when I open the deck editor, but after clicking on `1996 World Champion`, it disappears...

**Comment by Daenyth** [comment]
It's reasonable to show our internal card back image in the deck editor specifically.

**Comment by ZeldaZach** [comment]
Note this also happens in-game, because it's the same component re-used
