### ISSUE TITLE
Lowercase 'cockatrice' in mac menus

### ISSUE THREAD

**Issue by tritoch** [Cockatrice/Cockatrice#2412]
<b>OS:</b>
macOS Sierra 10.12

<b>Cockatrice version:</b>
2017-01-30
___
<br>

`cockatrice` lowercase in mac menu.
![macmenu](https://cloud.githubusercontent.com/assets/3866018/22953447/e225f42e-f2d6-11e6-9cc9-c83588178c32.png)

**Comment by ZeldaZach** [comment]
I've thought about making it uppercase for a long time, never got around to it. Might do that later

**Comment by Daenyth** [comment]
Might be related to the dmg having lowercase
