### ISSUE TITLE
while in-game no way to tell the player count

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2417]
*Especially relevant for draft or other bigger multiplayer games*

While you're in a game lobby and you're waiting for enough other players to join, you can't tell how much players are in the game or how many are missing.
You have to either
(1) switch to the main tab and find your game to check (must fit filter settings for sure),
(2) right click a player in your game lobby and check `show this users games`
(3) manually count the players in the player list

For like 4 player EDH you immediately know just by looking, but for drafts, other big games or people with eye restraints this might be an issue.
All options are suboptimal in this case, especially for draft games which need 8 people.

In a draft lobby you have to wait quite some time to find enough people because others also leave in between for example.
So what do you do while waiting? You're either chatting with the other players or you tab out and randomly check how it's going. But you always want to quickly+easily know how much people are missing.

The player count information, which we track already, just needs to be displayed somewhere in the game room, for example in the name of the `player list` widget.
It could also be in the name of the tab for the game, but it's already low on space and might lead to more truncation of other information there.

Maybe I even suggested something similar earlier, not sure
It just immediately popped to my face while I did a first draft game in a long while... really annoying.

**Comment by LethalPigeon7** [comment]
In a draft lobby you also generally immediately find out by looking once...  
Nevertheless this doesn't hurt anyone and _probably isn't that hard to implement?_

**Comment by tooomm** [comment]
>In a draft lobby you also generally immediately find out by looking...

Obviously, I'm not as smart as you... :P
If I'm in the main chat or on the desktop for some time and check back I can't tell just by quickly looking if it's 5/6, 6/7, 7/8 or even 6/7/8 people for sure.

But yes, I also think it's a good general improvement and doesn't hurt anybody to provide that information.
