### ISSUE TITLE
Trying to connect error message

### ISSUE THREAD

**Issue by Bigdogdch** [Cockatrice/Cockatrice#2420]
<b>OS:</b>
*Override this line with the exact operating system you are running! (e.g. "Win 7 SP1", "OS X 10.8.5", "Ubuntu 15.10" ...)*

<b>Cockatrice version:</b>
*Put your Cockatrice version number & build date here! You find them inside the app: `Help` --> `About Cockatrice` (e.g. "2d53ce9 (2016-02-18)"). If you can't access this menu for any reason, please include the full filename of the installer you used.*

___
Message reads
Your client does not support features that the server requested. Please update client and try again
Please advise
Thanks

**Comment by skwerlman** [comment]
You need to update your client. You can get an installer for the current version [here](https://cockatrice.github.io/)
