### ISSUE TITLE
Adding a keyboard shortcut for creating related tokens

### ISSUE THREAD

**Issue by MarkyMarkMcDonald** [Cockatrice/Cockatrice#2425]
### Feature Suggestion
A keyboard shortcut for creating all related cards of the selected card.

For cards with one related card, the shortcut text would be added to the single related card.
For cards with more than one related card, another menu item would be added saying "Create all related cards <shortcut-text>"

I think the default shortcut could be Cmd + Shift + T (Cmd + T being create token on OSX).

------
### Development
I'm working on a PR for this. My plan is to add a new method to Player.cpp that sends a create token command to the server for each related card (extracting a re-useable method from the create related card action).

One thing that has come up is that `relatedCards` and `reverseRelatedCards2Me` are both present in the related cards menu. Is it ok to create a token for every item in both lists? 

Cheers

**Comment by Daenyth** [comment]
Is "Create all related cards" something you ever really want to do though? Maybe it should do nothing, or prompt?

**Comment by MarkyMarkMcDonald** [comment]
Good point. I was thinking of cards like `Wurmcoil Engine` that always generate multiple kinds of tokens, but not cards like `One Dozen Eyes` which give the player a decision between different kinds of tokens.

I was curious about how many cards created different kinds of tokens and how many created a subset of different kinds so I created a quick search for card texts that create multiple tokens and scanned the list:

`cat AllCards.json | jq '.[].text | strings' | egrep "(create|put).*token.*(create|put|and|or).*token"`

Here are cards that give multiple kinds of tokens:
- Wurmcoil Engine
- Trostani's Summoner
- Sylvan Offering

Cards that produce multiple kinds at different times or produce a subset:
- One Dozen Eyes
- Hold the Perimeter

Cards that sometimes put all into play, but other times produce a subset:
 - Fable of Wolf and Owl

It seems like there is a mix of both. I think it's better to give power users a hotkey that creates both and then select + remove the one you don't want than to prompt or do nothing. If users find creating all of them when they only need one annoying they can still open up the card menu and choose the one they need.

**Comment by tritoch** [comment]
Your search missed a few cards that have multiple related because of flip, transform, or multiple abilities.
ex:
- Huntmater of the Fells
- Garruk, Primal Hunter
- Bestial Menace

That said, I think a shortcut would be a great option for 99% of cards.  I agree it's easier to destroy a token than go back in to the menus and make the ones you haven't made.

**Comment by Daenyth** [comment]
That's a solid argument. I'm sold

**Comment by ctrlaltca** [comment]
Fixed in #2426
