### ISSUE TITLE
[Bug] OnlineDeck Storage names with '/' are unusable

### ISSUE THREAD

**Issue by carlosmuller** [Cockatrice/Cockatrice#2429]
<b>OS:</b>
Linux arch , widnows 10
<b>Cockatrice version:</b>
on Arch b9cd942(compiled from master)
on windows dab7316

___
<br>
OnlineDeck Storage names with '/' are unusable

![Folder with this name can't be deleted](http://i.imgur.com/5uOwEGH.png)

The folder 'legacy/modern' is unusable, can't add deck to it neither delete it. No message of error or anything

**Comment by Daenyth** [comment]
Nice find, this is a total fuckup on our side :P

It should be easy to prevent adding this sort of name. Fixing that entry on whatever server will probably require the admin to do something.

**Comment by Daenyth** [comment]
cc @woogerboy21

**Comment by woogerboy21** [comment]
Yea I could fix the entry in the DB if a user sends me a contact us message from the site so I can follow up through email.  We should add a filter in the code to prevent this 😄

**Comment by ZeldaZach** [comment]
I'll probably look into this at some point this week
