### ISSUE TITLE
shared stack for both players

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2444]
It would make stack handling and resolving order of complex situations way easier!

Your spells and ones from your opponent need to be easily distinguishable - your cards could have green borders and others red ones for example.

I see a problem here for multiplayer games because of the way the table looks.
**But even if it's just in two-player games it would be a huge improvement with no downsides I can think of.**

**Comment by Daenyth** [comment]
This is reasonable but unfortunately really hard. There's no such thing as a shared zone right now at all - every zone is owned by a player and you can't touch stuff in other players zones. This should be able to happen once we figure out how to model shared zones.

**Comment by ZeldaZach** [comment]
Related to #1740
