### ISSUE TITLE
login / forgot pw dialog bug (since #2393)

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2445]
(Since #2393)

Reproduce:
- open `connect...` dialog
- hit `forgot password`
- type a wrong host
- `ok`
- wait until the `Socket error: host not found` message appear
- `ok`
- now you've two `connect...` dialog windows opened on top of each other

![bug-forgot-pw](https://cloud.githubusercontent.com/assets/9874850/23582699/3d8c9f18-0130-11e7-8d7f-810afc6a4902.png)

This happens because the socket error dialog box automatically opens the connect windows again.
In general this is really cool, but creates this issue while typing a wrong host info/port during the forgot password process.

Why don't we have the same dropdown or saved recent server info in the forgot password dialog?
Would basically prevent this.

cc: @woogerboy21

**Comment by Daenyth** [comment]
I really should get on the connect dialog rewrite
