### ISSUE TITLE
Make cockatrice notifications compatible with win8+ "toast" notifications

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2446]
Starting with Windows 8 (extended in Win 10) there are now system wide new native notifications in a so-called "Toast" style. Cockatrice isn't compatible right now.

We even just introduced a special tray icon to show some kind of notifications. The icon has no other function. With the new toast notifications there is no need for the tray icon anymore!

As a reference, the open source messenger Telegram (also on github, see linked issue below) is also built with Qt and supports these notifications for new messages.

More information and interesting related reading:
- http://stackoverflow.com/questions/28609521/windows-10-toast-notifications-desktop-application
- https://github.com/telegramdesktop/tdesktop/issues/249

---

Edit: seems like windows somehow transforms old bubble notifications to new ones:
![msg](https://cloud.githubusercontent.com/assets/9874850/23583664/81c74d20-014b-11e7-88e7-0b6f73e4ad71.png)
Funny that I realize it today after opening the issue, haha. 👍 

Anyway, there should be a correct app icon in the notification.
I think windows just automatically catches the old native win notifications and transforms them. So right now we still can't remove the tray icon on new win versions because it's the source of the notification message!

<br>

Clicking the notification will do nothing btw, Cockatrice won't open and display the related pm tab in the app.

---

Edit2:
>"Toast notifications allows your app to inform the users about relevant information and timely events that they should see and take action upon inside your app, such as a new instant message, a new friend request, breaking news, or a calendar event. When the user “chases” the notification (by tapping or clicking on the toast to activate the app), the app should navigate the user to the page with the right context." When I click the notification it will bring me to the right tab in cockatrice when i tab into cockatrice, but wont make cockatrice the active program

>The notifications on windows  10 do show in toast style. But they have no cockatrice icon displayed and clicking them with the app minimized has no effect (it should open cockatrice and focus the tab with the pm).
However, when cockatrice is open and you are following main chat for example while the private message arrives, clicking the notification opens the correct pm tab.

**Comment by ZeldaZach** [comment]
It works.

**Comment by tooomm** [comment]
There are still some issues with the toast notifications on windows!

- There is no app icon to easily connect the notification with its source visually
- Notifications are not correctly linked with the app as clicking them doesn't open Cockatrice and jumps to the corresponding chat etc.
