### ISSUE TITLE
Change ignored message

### ISSUE THREAD

**Issue by LethalPigeon7** [Cockatrice/Cockatrice#2449]
from "This user is ignoring you." to "This user is ignoring you, they cannot see your messages in main chat and you cannot join their games." (both when trying to PM them and join their game)  
At least a couple times a day someone will go complain about someone else in main because they tried PMing them, couldn't, and don't understand that they are blocked in main chat as well. Now, granted, sometimes they specifically want to tell everyone, but that's not a majority of the cases in my experience. Raising awareness of how ignore lists function could be done in a multitude of different ways, but this one seems simplest and most elegant considering it takes up space not being used by anything else and sounds easy to implement.

**Comment by tooomm** [comment]
Check also this out: https://github.com/Cockatrice/Cockatrice/issues/2072

**Comment by LethalPigeon7** [comment]
Implementing both would be ideal, time spent aside.
