### ISSUE TITLE
Friendliness Rating System Ideas

### ISSUE THREAD

**Issue by JineteDV** [Cockatrice/Cockatrice#2450]
Why I think it'd be a beneficial addition: We can't force users to report everything to the mods and they never will, I find that so many users who're getting reported for breaking a rule for the first time should've been reported for other things weeks ago. Weekly I'll see 1-2 users who've been on the server for months or years ask "who's a mod/what's a mod/where are the mods?" They just think that mods are judges or some other special user with no real powers. Letting them +1 or -1 their opponent in 3-4 clicks simplifies the process of reporting and gives them that instant feeling of vindication (talking specifically about -1 because we're negative biased people and there will be more -1ing than +1ing) that they want, without the more arduous and seemingly fruitless attempt at them reporting that person to a mod.

These would be restrictions or rules about the system:

1. An account has to be X (2 months) old to be able to upvote or downvote another player.

2. Voting on mods/admins should be disabled. Mostly because they’ll get downvoted whenever they ban/warn a player.

3. Votes should be saved to a player’s name to hopefully deter players from making multiple account from which to be behave negatively through. 

4. Information about who’s voted on who should be saved.

5. Votes should have a time to live (1 year). People do change over time.

5. Add a filter for games and also in Create a game window, to allow the filtering out and the prevention of people joining who have a rating lower than a variable and/or preset threshold. Rating only matters when trying to join a game or make one.

6. Takes 2 downvotes and 1 upvote (or maybe raise it to 3 and 2 respectively) to actually add -1 and +1 to a player’s rating respectively. We as a people are more apt lash out and comment on negativity rather than praise someone for being a good person.

7. This would all probably be helped by Wooger’s idea of new accounts needed to be reviewed before they’re given an account activation token.

8. Players rating should be on display somewhere in their ‘User Details’. Or…

9. Hide the rating from everyone except mods, if it seems like having the number display is causing problems in and of itself.

I choose those numbers because I thought they'd make sense, otherwise they're arbitrary.

**Comment by Jinxstands4Jinx** [comment]
I see this creating more problems that it fixs. as if you hate a user you just keep "voting them down" and they suffer greatly. Also having the votes last a year is too long, maybe 4 months.  Only the mods should see these numbers. the user can see their own number sure but no one elses. Also when you up vote or down vote a player, there should be a "box or checklist of" "why" like +1 very helpful. or a -1 rude, disrespectful. Kina like how league of legends lets you report but you must actually voice a reason. Also maybe put a cap, let me explain. User A can only vote on user B once per month. they can give that as many ups or downs at one time but once they press enter, They are done reporting said user for 1 month. this may help get rid of players just -1 people do be trolls.

**Comment by woogerboy21** [comment]
Just spit-balling some idea's in this thread as well....

1.) I see no reason why a user should be ever able to have more than 1 vote against another user.  They should only be able to give a + or - to the user.  So in @Jinxstands4Jinx  post, the user shouldn't be able to repetitively give -'s to the same user.  Which brings up the question, can a user change the vote at some later time?  

2.) Im not sold on the idea of a time to live on the vote (5 in the original post) or the once a month concept.  The TTL for the vote IMO should be the life of the account.  But this goes back to my first post, users could be allowed to change the vote they once put in previously.  Maybe after a room is closed and the user has cast a previous vote prompt them asking if they want to change the vote they previously cast?

3.) If you want a mod only view-able rating system why wouldn't we implement a true reporting system?  OR  why couldn't there be a user view-able rating and a mod view-able rating that is adjusted accordingly if you didn't want a full on user reporting system?

4.) I like the idea of having short / to the point reasons, though this might be more focused towards a reporting system but could be beneficial for calculating the rating (in a weight type concept)

5.) a tiered system for rating adjustment is an interesting idea, would be interested in hearing opinions on how much of an impact people think it would deter potential negativity

6.) account age restrictions for casting a vote as well as keeping track of who voted for who (audit) of votes cast would with out a doubt be required.  the question I would then ask would be what happens to the votes if an account is removed?  should the votes be removed as well?  my initial thought is yes... but not to much thought about if they are removed how that would effect things.


I may end up with more thoughts/idea's on the subject but its late and im going to bed for now 😄

**Comment by Daenyth** [comment]
> Only the mods should see these numbers.

Now that's an interesting suggestion that no previously proposed rating system has had. That might be a tipping point to make it actually useful. If people can't use it as a vanity metric, it might actually have a chance at helping the server. I could see letting people see their own number too.

> Information about who’s voted on who should be saved.

Definitely agreed, if this has any hope of working we need the ability for a mod/admin to revoke a troll's voting history

> Add a filter for games and also in Create a game window,

No way - not without a track record of ratings being useful indicators. I'm not convinced that this would work out in practice the way you want. Doing this means that if we get anything wrong, we allow trolls to take away the ability of good users to join games

> if you hate a user you just keep "voting them down" and they suffer greatly.

We'd want some restrictions on how often you can vote in total and how often against a player

> Also when you up vote or down vote a player, there should be a "box or checklist of" "why" like +1 very helpful. or a -1 rude, disrespectful

Reasonable. Maybe even be able to do score per category, +1 friendly -1 rules knowledge or something. But that's more complicated

**Comment by Daenyth** [comment]
> If you want a mod only view-able rating system why wouldn't we implement a true reporting system

This would be a better use of time than a rating system imo.

**Comment by JineteDV** [comment]
Too answer Wooger's question about why I think it should be hidden and users should only be able to specifically see their own and mods should be able to see everyone's is because of people putting too much stake into it for vanity reasons. We don't know if this will happen, I'd prefer it to be visible to everyone, but elsewhere on the internet other similar systems have hid some of this information from the public for this reason.

**Comment by Daenyth** [comment]
It's also easier to experiment if it's hidden. If we add it and then it
sucks people will get annoyed or confused when we remove it

**Comment by woogerboy21** [comment]
> Doing this means that if we get anything wrong, we allow trolls to take away the ability of good users to join games

Wait, so the trolls would be preventing good users from joining games created by the trolls?  Not sure this is a bad thing.

> I'd prefer it to be visible to everyone, but elsewhere on the internet other similar systems have hid some of this information from the public for this reason.

I can see hiding some information such as the reasoning, but I don't get why you would hide the rating of a user from another user.  Vanity you say?  So some one goes and gloats about why they have a 100+ thumbsup rating?  So what?

**Comment by JineteDV** [comment]
Some gloating about that is fine and is to be expected, but I think there is a point where it could be just detrimental for the chat environment, I don't know what this'd look like.

**Comment by Daenyth** [comment]
> Wait, so the trolls would be preventing good users from joining games created by the trolls? Not sure this is a bad thing.

No. Consider:
- Community starts using rating feature. Many games are created with "required rating >x" to join.
- A troll creates a bot to swarm downvote your account from many alts
- Your personal rating is now trashed and you can't join the games created by the community

**Comment by woogerboy21** [comment]
> A troll creates a bot to swarm downvote your account from many alts

I think this is were your wrong.  Im not convinced with the proper constraints in place this could happen as easily as your envisioning and is probably were the difference of opinions come in.

In your vision there is an easy method to create accounts and an even easier method to cast votes with them.  Im picturing a difficult way of creating accounts along with an even more restrictive nature on when an account can cast votes.  

So what, the "troll" has to create sub accounts, wait for extended periods of time to even let those accounts have functionality to hurt some ones account.  Only to attack a user and cause a minor disruption for them till the team terminates said swarm accounts and roles back those votes?  Im questioning if your trolls would even put the effort up.  Considering the way I'm seeing things they would have to wait months only for a single attack?

**Comment by Daenyth** [comment]
More restrictions on new accounts is a possible mitigation, yes. But we don't currently have that. If you can enumerate some of your ideas that would help

**Comment by woogerboy21** [comment]
We don't have built in functionality for new account identification/approval if that is what your asking.  I've been slowly working towards that piece by piece.  As of right now the state of the server is you can configure it to require registered users only, require account registration, and not automatically send email account activation tokens.  Its left open to the server operator to incorporate whatever external functionality they wish to review/approve accounts and send the activation token information.  I'm not so sure we should work the code into the server for any type of an approval process and leave it up to the operators to determine the method(s) they wish to do such a task.

Do you think we should incorporate that functionality in some fashion?

My idea's on what could use reviewed and required for account approval may not necessarily meet with other operators.  Some of the basic's probably do.  Like making sure the user doesnt have multiple alts (from what data we have), make sure they aren't banned in any form etc.

We do have functionality for things like black listing email accounts that you may not want to allow during registration, or placing restrictions on names to prevent unwanted / questionably flavorful user name registrations, or even restricting the number of accounts that can be registered under a single email address.

**Comment by ZeldaZach** [comment]
The feasibility of this is limited, but the report system is a high priority of mine. See #190
