### ISSUE TITLE
Operator Poll / Discussion: User Behavior Type Statistics

### ISSUE THREAD

**Issue by woogerboy21** [Cockatrice/Cockatrice#2451]
So personally after operating a server over how ever long it's been I am interested in hearing on the idea of keeping track of user statistical information.  Would it be beneficial in any way to maintain historical data for actions users have taken.  And I'm not so much referring to only tracking something like kick counts.  Im thinking more like coming up with a list of things players typically do that would be interesting to track and maintain for statistical analysts.  Kicks could be one, but what about number of draws (etc) ?  Since I have not played in a number of years can do you think this type of information would be beneficial and if so what type of information would you like to see?

Im picturing something like being able to give users statistics on how they have historically played.  Though I am at a loss to what that might be as well as what information people may like to see.

**Comment by LethalPigeon7** [comment]
So the goal is to provide users with fun, perhaps even useful trivia about themselves? As a user I would not be interested in this much, but some people would, why not.  
I'm assuming you can't track card-related things like colours and card types server-side for legal reasons, but if you can, seeing how much green I play and how creature-centric I am would be neat. 
Keeping a total win / loss ratio and a win / loss ratio specific to each deck, for all of an account's age, and in the last [arbitrary amount of time]. 
Average time/ammount of turns before winning/losing with a deck/in general.
Also I'm not sure how you would detect draws, as such situations are resolved by one person conceding software-wise.

**Comment by Daenyth** [comment]
I'd definitely like to start logging server-level interesting metrics with statsd - I have an idea of how I want to implement this at the code level. Things like user connections, timeouts, game creations, etc - anything really that we might want to chart over time.

**Comment by tritoch** [comment]
I would be VERY interested in seeing a chart of concessions between opponents vs game leaves (+kicks) in non-edh/other game modes.

i.e. How often do you play a second (or third) game vs leaving after game one.

Main chat has a lot of complaints about people leaving their games labeled 2/3 (best of 3) or 'with sideboard' after game one.

**Comment by woogerboy21** [comment]
> I'd definitely like to start logging server-level interesting metrics with statsd - I have an idea of how I want to implement this at the code level. Things like user connections, timeouts, game creations, etc - anything really that we might want to chart over time.

I think the foundation for what im looking to implement may encompass this kind of information, but the original goal was more of a way to inform users of statistical data based on their past play.  Collecting system information would be good for finding out were in the user base interst in certain application functionality could use improvements but it wouldn't give the user real information on specifics to themselves.

@tritoch I think has a clearer idea of what i'm talking about.  Though certain aspects I'm not so sure we would be able to collect (like a win/loss ratio) since we have very little game understanding.  It's not to say we couldn't use what metrics we have to create those type of statistics, just they may not be as accurate as one may like.

**Comment by skwerlman** [comment]
I really like the idea of tracking this sort of stuff. I've actually been wanting to write a `netdata` module for Servatrice, and these sorts of stats would be really cool to see in it.

**Comment by ZeldaZach** [comment]
This doesn't feel worth the hassle it'll take to get it implemented, and I fear users would just cheat to get stats anyway.
