### ISSUE TITLE
Tokens created through reverse-related interface are not created again with "Create another token"

### ISSUE THREAD

**Issue by Nightfirecat** [Cockatrice/Cockatrice#2453]
<b>OS:</b>
*Windows 7 SP1*

<b>Cockatrice version:</b>
*dab7316 (2017-01-19)*

___
<br>

The "Create another token" cannot create tokens created through the reverse-related token production menu item. Two possible reproduce cases:

Greyed out menu item:

1. Place a card with reverse-related token(s) in play (Voice of Resurgence used in this example)
2. Create one of its tokens (create an Elemental)
3. Right-click the battlefield; the "Create another token" menu item is greyed out&mdash;*expected behavior is for this menu item to be available*

Incorect token produced:

1. Create any token (Thopter used in this example)
2. Place a card with reverse-related token(s) in play (Voice of resurgence used in this example
3. Create one of its tokens (create an Elemental)
4. Right-click the battlefield and click "Create another token". This creates a Thopter token instead of an Elemental token. *expected behavior is for the created token to be a second Elemental token*

!["Create another token" bug demonstration](http://i.imgur.com/JduazyS.gif)

**Comment by ZeldaZach** [comment]
Ahh, a simple miss on the creation. I'll check this out soon

**Comment by Psithief** [comment]
We argued over this previously, I'm glad @Daenyth didn't get a chance to argue against it this time.

See and close #1726.

**Comment by Psithief** [comment]
The keyboard shortcut (Ctrl+G) doesn't work unless the token is created via the token dialog. Please review.

**Comment by ZeldaZach** [comment]
@Psithief best to make a new ticket
