### ISSUE TITLE
Clicking "OK" on anti-idle message does not make you not-idle.

### ISSUE THREAD

**Issue by A4G** [Cockatrice/Cockatrice#2454]
Title, I have to assume this is a bug. Likewise, typing and sending messages in direct chat also does not make the server consider you "not-idle".

**Comment by ZeldaZach** [comment]
I consider pressing the "OK" button not taking an action, so not necessarily a bug. Sending a message in private chat, however, should count towards not being idle.

**Comment by A4G** [comment]
> I consider pressing the "OK" button not taking an action, so not necessarily a bug.

I'm wondering why you wouldn't, clicking "OK" requires you to be viewing the client and, physically, not-idle. Is there a reason to not consider it an action?

> Sending a message in private chat, however, should count towards not being idle.

I can speak from experience this is not the case, I've tested it with Jinete before.

**Comment by tooomm** [comment]
But using main chat is considered an action @A4G  ?

**Comment by A4G** [comment]
@tooomm Correct.
