### ISSUE TITLE
Allow Server Rooms to be based on user permissionLevels

### ISSUE THREAD

**Issue by ZeldaZach** [Cockatrice/Cockatrice#2463]
The idea is we currently can set a room to be "open for all", "moderators only", "admin only".

We'd like to add a way to make a room "VIP only", "Donator only", "VIP/Donator only". These rooms would be an interesting addition. These rooms would be accessible by VIPs and/or Donators & Moderators/Admins of the server.

Areas to look at `tab_server.*`, Protocol

**Comment by Daenyth** [comment]
I really like this idea
