### ISSUE TITLE
Alphabetically sort cards on deck-load screen (cosmetic)

### ISSUE THREAD

**Issue by Psithief** [Cockatrice/Cockatrice#247]
Currently, cards are shown in the reverse order that they were added to the deck.

Example:
![token_preview](https://cloud.githubusercontent.com/assets/1124846/3781060/157b7202-1992-11e4-9c2d-0d6e0465b351.png)
Those were added to the deck in alphabetical order.

Alphabetically sorting this display won't do much but sorted output is just nicer to look at. It would, at minimum, be quicker to check for cards in *"Is this the right deck?"* situations.

**Comment by ZeldaZach** [comment]
This seems to only be an issue with `.dec` files. `.cod` files don't exhibit this issue.

**Comment by Psithief** [comment]
I'm only using `.cod` files and get this every time I load a deck. Maybe this is a OS issue.
