### ISSUE TITLE
Auto-join Server Room without Permissions Results in Message

### ISSUE THREAD

**Issue by dev-id** [Cockatrice/Cockatrice#2470]
If a room is set to auto-join and has elevated permission requirements, when a non-elevated user connects to the server, they will receive an Error message "You do not have the required permission to join this room"

Expected behavior would be to only attempt to join rooms you have permissions on when using auto-join or suppress the error message for auto-join.  User should still receive error when attempting to join elevated room manually.

Some discussion in #2464

**Comment by tritoch** [comment]
If you couldn't see rooms you don't have permissions to, you wouldn't be able to click on them, and we could remove the error message.  Any reason regular users need to see there's a Moderators room?

**Comment by ZeldaZach** [comment]
I like having the rooms all public knowledge personally. For example, having the donator room shown might encourage people to donate if they can join an exclusive room.

**Comment by Daenyth** [comment]
I don't see a reason for hidden rooms to exist.

**Comment by skwerlman** [comment]
I understand having the Donator room visible to people who can't access it, but there's absolutely no reason for a mod/admin-only room to be visible to everyone

**Comment by Daenyth** [comment]
It doesn't hurt anything that they know it exists, honestly

**Comment by tooomm** [comment]
>It doesn't hurt anything that they know it exists, honestly

In terms of a as clean as possible UI it would be useful to hide the said Admin/Mod only room for example.
For Donator/VIP room that might be different. Not like very important though...

**Comment by skwerlman** [comment]
Actually, I think it'd be nice to have the option to hide _any_ room via a flag, but that's for another PR.

**Comment by Daenyth** [comment]
I'd really rather keep it simple and just let them be shown. There's no harm caused from showing them.

**Comment by Daenyth** [comment]
Did we fix this?

**Comment by Daenyth** [comment]
Specifically did we fix

> If a room is set to auto-join and has elevated permission requirements, when a non-elevated user connects to the server, they will receive an Error message "You do not have the required permission to join this room"

**Comment by Daenyth** [comment]
Specifically specifically that the server should not auto-join you to rooms which you aren't allowed to enter

**Comment by ZeldaZach** [comment]
This is probably not too relevant in all likelihood.
