### ISSUE TITLE
Problem with preferences window resizing

### ISSUE THREAD

**Issue by JineteDV** [Cockatrice/Cockatrice#2471]
<b>OS: macOS 10.12.2</b>

<b>Cockatrice version: 6e723b2 (2017-03-14)</b>

After opening the preferences window it's already oversized and goes beneath the screen boundaries. I'm not able to resize the height of the window when I mouse over the edge of it. I can move the window left or right, but when I try to lower it when the left click is released it jumps back up to the top of the screen.
___
<br>

![screen shot 2017-03-14 at 9 31 28 am](https://cloud.githubusercontent.com/assets/6514656/23902905/165a5c58-0899-11e7-8d55-0f7a5d891423.png)

**Comment by tooomm** [comment]
Which resolution do you use?
I guess this is because the biggest sub-windows require that much space?

**Comment by JineteDV** [comment]
1280x800

**Comment by ZeldaZach** [comment]
Maybe we can set a max-height / max-width of the QDialogs. I'll take a quick look

**Comment by Nightfirecat** [comment]
Scrollbars (disabled if not needed) might be nice here. I can also try testing on my 1280x640 resolution netbook to see if this is an issue at lower res as well.

**Comment by ZeldaZach** [comment]
I opened a PR for this, check it out

**Comment by tooomm** [comment]
>1280x800

How can this be a problem?! I run on 1366x768 just fine...
So my display height is even lower than yours! No problem here:
![1366x768](https://cloud.githubusercontent.com/assets/9874850/23920850/9b28c3b2-08fc-11e7-9f6c-c1da79c035ab.png)

**Comment by Nightfirecat** [comment]
From what I know, QT renders differently on different OSes; notably larger on Macs than on Windows.

**Comment by tooomm** [comment]
Is the new version working for you @JineteDV ?
Since I'm having huge issues!

Check my post in the PR (https://github.com/Cockatrice/Cockatrice/pull/2480#issuecomment-287470498)
