### ISSUE TITLE
Write a wiki page about update channels

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#2473]
- What are update channels?
- Which one should I use? Pros/cons?
- How often are updates?

**Comment by skwerlman** [comment]
I'm currently starting this wiki page.

Questions:
How often is there a `Stable` release (not counting hotfixes)? Every 6 months, like before, or is that changing? Should I write as though #2341 is implemented, or leave that for later?

How often is there a development snapshot? Every commit? Or is there some manual intervention required?

**Comment by skwerlman** [comment]
https://github.com/Cockatrice/Cockatrice/wiki/WIP-Release-Channels

**Comment by ZeldaZach** [comment]
I made changed to it @skwerlman Nice job!

**Comment by Daenyth** [comment]
Thanks for jumping on this @skwerlman
