### ISSUE TITLE
How do the protocols work?

### ISSUE THREAD

**Issue by ZeldaZach** [Cockatrice/Cockatrice#2475]
We should get a wiki page made that explains:
- What our protocol is
- How to use the protocol
- How to extend current aspects of the protocol
- How to add new "classes" to the protocol
- How to keep changes from causing a forced update on the users (optional ?)

Some starting info:
You can see examples of how to create pb command container objects in the remote_client.cpp file . you basicly create a container, set the pb value(s) and send it. then on the other side you do the same thing by declairing the protobuf definition to use to understand how to interpret the data
and get the value(S) https://github.com/Cockatrice/Cockatrice/blob/master/cockatrice/src/remoteclient.cpp#L86 in a nutshell. rules for types apply to the information your setting the values for like int etc.

We open a long-lived TCP connection from the client to the server
On that connection we send binary messages, encoded with protocol buffers
You have types of `Command`, `Response`, and `Event`
command is when the client asks the server to do something
response is the server answering that command
event is the server informing the client that something happened

+ basics of communicating and sending data between the client and server
+ how do i extend the current protocols and/or make new protocols
+ how to ensure backwards compatibility
+ some examples of how it's done currently in the code

**Comment by Daenyth** [comment]
(untagging since that tag is for code changes to the protocol)

**Comment by skwerlman** [comment]
Has anyone started work on this?

**Comment by ZeldaZach** [comment]
Tag @ctrlaltca

**Comment by tooomm** [comment]
>Has anyone started work on this?

@ctrlaltca is working on it! https://github.com/Cockatrice/Cockatrice/wiki/Client-server-protocol 👍

**Comment by tooomm** [comment]
I'm not so sure if @ctrlaltca finished the wiki article back then...
It misses at least part 2 and 3 with details about responses and events if I understand his structure correctly while looking at the commits and the page.

Some of your entry questions are also not covered I guess.
