### ISSUE TITLE
Dockable elements width size change issues

### ISSUE THREAD

**Issue by ZeldaZach** [Cockatrice/Cockatrice#2477]
Related #1359 

> If you play around with enabling/disabling different "docks" with custom wideness settings they won't remember correctly and get displayed with different wideness, one "dock" eats up the wideness of former 2 "docks" or they split-share it evenly (even when set to 1/3 and 2/3 before for example)

**Comment by Daenyth** [comment]
Do you understand what @marcofernandezheras meant there? I don't understand

**Comment by tooomm** [comment]
@Daenyth are you talking about this?
>I've missed to add filterDelOne filterDelAll QToolButtons back to the UI again on the dockify process...

he fixed it in #1483

**Comment by tooomm** [comment]
Probably related #2762
