### ISSUE TITLE
Add FreeBSD to "unsupported but it works" releases

### ISSUE THREAD

**Issue by seanbruno** [Cockatrice/Cockatrice#2482]
<b>OS:</b>
FreeBSD 12-CURRENT

<b>Cockatrice version:</b>
2017-03-14-Release
<br>

Just a note that I've added this to FreeBSD Ports and the Package for this is being built by the FreeBSD packaging system. Works great and does all the things.

**Comment by Daenyth** [comment]
The wiki page is publicly editable - you can leave this as a note on the install/compile page for linux. Similarly, the Arch Linux section references the AUR package
