### ISSUE TITLE
Closed room function

### ISSUE THREAD

**Issue by Jinxstands4Jinx** [Cockatrice/Cockatrice#2483]
I think the host of a table should get a second tab like the "kick" tab, that would allow them to "close" the room from new users joining. This would eliminate draft issues somewhat where a person leaves after round 1 and people keep popping in asking "did this fire?" or something similar. the host would have the ability to toggle this feature if for example a person disconnected during the draft by accident the host could toggle it to let the correct player in, then "close" the room again.  This feature like the "kick" feature would travel to the next person on the list if the host leaves the room. (that way hosts do not close and just leave)

**Comment by Daenyth** [comment]
I'm not sure this is useful outside the draft case, and I'd rather put effort toward getting an event management subsystem in place before adding this.

If there's no use case for this outside of event management I think we should not do this.

**Comment by woogerboy21** [comment]
For once I think I agree with @Daenyth , unless some one can come up with a reason outside the draft scenario putting efforts up to implementing proper external drafting support would be my vote.

**Comment by Jinxstands4Jinx** [comment]
well if you want to skip this and just figure out a better Draft management system I can see that. Outside of draft usage the only thing i can see is people making rooms for "certain" users and thats covered via passwords.
