### ISSUE TITLE
Getting replays

### ISSUE THREAD

**Issue by Jinxstands4Jinx** [Cockatrice/Cockatrice#2486]
Currently as far as i know the only way to get a replay for a game is to be involved in said game and to wait until the host closes the room. Is there a way we could maybe check a box and have the system inform us that the replay for the game is up? I recently was involved an 4 person edh game and was killed second. The method of my death though was a long combo and I actually liked the combo set up. So i sat there for a hour (until the game was over) and waited and waited. i kept checking the game to make sure they were still playing and when the host died he disconnected....leaving the room open until a mod or the system closed it down. the other player left. I never got the replay. I think we should either change how replays are gathered or have a system set up so players can get the replays without having to rely solely on the host. like all players in the room would get an option to "save" or to "delete" the replay once the game finishes and it would be stored on the server for like 2 hours after room close for the player(s) to go retrieve it if they so desire.

**Comment by ZeldaZach** [comment]
Once you simply join a room, you will be involved in the replay hash. (If you join a room then leave, whenever that game ends, you will see the replay in your Game Replays tab).

**Comment by Jinxstands4Jinx** [comment]
it did not happen at the time in question. because the host disconnected.

**Comment by ZeldaZach** [comment]
Related to #1953 (pretty much a dupe)
