### ISSUE TITLE
Can't edit host/port for saved servers

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2492]
<b>OS:</b>
Win 10 64bit

<b>Cockatrice version:</b>
a8a4557 (2017-03-16)

___
<br>

Introduced with #2452

I encounter this issues:
- ~~Passwords are always saved, even if you don't check the corresponding option~~ fixed in #2503

- You can't change the name of a server profile<br>
As @ZeldaZach told me you're not able to edit the Profile name from within the UI right now
~~**possible workaround:** grey out the `Name` field if `previous host` is selected~~ done in #2503
**possible solution:** make profile names editable as well, the same way as `Host` and `Port`<br>
I think the name change is a nice way to allow people to customize things and prevent users from adding new profile duplicates. Especially since they can't delete the old ones from within the interface right now. <br>
*Another related problem here is, that if you try to change the name in the name field (which is possible right now) you can properly connect, but any changes you do to the profile like a new port won't be saved. Everything will reset and you're presented with the default view in the connect dialog for the next time!*

<br>

CC: @ZeldaZach

**Comment by Daenyth** [comment]
I was thinking I prefer making server names editable but that's a little annoying to handle because it's the settings key. I'm ok with disabling the edit field on name for now and making it more flexible later

**Comment by ZeldaZach** [comment]
Kinda related #3617

**Comment by ZeldaZach** [comment]
With #5368 you can now delete and re-create the server profile. Not sure how often one will actually edit a live server, so gonna close for now.
