### ISSUE TITLE
Issues with settings window

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2494]
<b>OS:</b>
Win 10 64bit (1366x768)

<b>Cockatrice version:</b>
a8a4557 (2017-03-16)

___
<br>

Related PR: #2472

As posted in https://github.com/Cockatrice/Cockatrice/pull/2472#issuecomment-287470961, I experience issues with changes in this PR.

My settings windows has shrunk too much and you can't properly read all information now.

**Comment by Daenyth** [comment]
It's odd - the code change in there sets a *minimum* size on the window. Zach can you check the qt docs? It shouldn't affect the window like this I'd think...

**Comment by ZeldaZach** [comment]
I'm really not sure why this is happening, maybe someone else can check this out? The docs say it _should_ work correctly....

**Comment by Daenyth** [comment]
Could it actually be related to font size somehow?
