### ISSUE TITLE
OSX - every line in chat makes audible "bel" even with sounds disabled

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#2496]
<b>OS:</b>
OSX 10.11.5

<b>Cockatrice version:</b>
piday

___
<br>
make it stop

**Comment by ZeldaZach** [comment]
I've noticed this too, and this started on OS X 10.12. I disabled systemwide alert sounds to make it stop personally. We need to see why this is happening...

**Comment by Daenyth** [comment]
I don't think this started in 10.12 because I'm on 10.11. I think this started in cockatrice.

**Comment by ZeldaZach** [comment]
I noticed it randomly one day after updating my OS, but it might've been to 10.11. Yeah, i think it was 10.11 actually

**Comment by ZeldaZach** [comment]
I just turned my alert sounds back on and this is no longer an issue... Maybe it's a problem with 10.11?
