### ISSUE TITLE
"Check for updates" thinks piday release is a new release when running piday

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#2497]
Running piday release on osx.

<img width="406" alt="screen shot 2017-03-17 at 8 37 13 pm" src="https://cloud.githubusercontent.com/assets/14644/24067341/97e0306c-0b51-11e7-9360-d90319226c3d.png">

Then if I hit the close button on that dialog:
<img width="393" alt="screen shot 2017-03-17 at 8 38 06 pm" src="https://cloud.githubusercontent.com/assets/14644/24067345/a5af3da0-0b51-11e7-8f17-efc5f172eeeb.png">

- Ok is ambiguous. Does it get the update? Close without doing anything? Need better wording.
- "Update anyway" - What does "anyway" refer to?

------

Expected behavior:
- "You are already running the latest $channel release - $version"

**Comment by ZeldaZach** [comment]
This was fixed
