### ISSUE TITLE
All download links are broken as "forbidden"

### ISSUE THREAD

**Issue by jimivyas** [Cockatrice/Cockatrice#2502]
<b>OS:</b>
*running windows 10 pro build 14393.953 but it doesn't really matter.*

<b>browser version: </b>
*Chrome Version 56.0.2924.87 (64-bit)*

___
<br>

All three download links on https://cockatrice.github.io/ are currently broken with the error "Forbidden!"

___
<br>

**Comment by Daenyth** [comment]
We should hopefully have this fixed by tomorrow

**Comment by Daenyth** [comment]
Scratch that - bigger issue at hand. Apparantly bintray (what we use to host downloads) forbids uploading development builds. We'll have to change our CI system to not automatically upload, and delete them. Then we'll also have to do some code changes on the "development" auto update channel for the new storage location.

@ZeldaZach s3 might work.

cc @ctrlaltca

**Comment by ZeldaZach** [comment]
@Daenyth We can probably still go on the upload path, just we need to only have X versions available at once and delete the rest. They have a REST API available to do such actions

**Comment by Daenyth** [comment]
https://bintray.com/docs/terms_of_service.html

> 4. Use Restrictions
> ...
> You may not [...]  (xxvii) in connection with Contributions, upload and/or store on the Site continuous integration artifacts or nightly builds, **(i.e. you may only upload and store content in direct connection to official software releases).**

We can't host dev builds on bintray, period.

**Comment by ZeldaZach** [comment]
Ok, so this brings back the question of going back to hosting locally, which used to be done on WoogerWorks servers... is that still an option, or should we now have to set up our own host services?

If we do it our own way, we can establish our own ways for the auto-updater to work better

**Comment by Daenyth** [comment]
We can still build on CI, we don't need to build locally, we just need to upload the results elsewhere. I'll come up with a plan tomorrow

**Comment by Daenyth** [comment]
Got this automated email

> Hi Cockatrice,
> Your Bintray account is currently rate-limited due to overuse.
> Customer Support should contact you at the earliest to remove the limits from your account. You may also contact them directly at support@jfrog.com.
> Regards,
> The Bintray Team

**Comment by woogerboy21** [comment]
If you guys need a box I can host builds for a bit.

**Comment by Daenyth** [comment]
I think we can just put them in S3 automatically

**Comment by Daenyth** [comment]
Travis even has built in support for this https://docs.travis-ci.com/user/deployment/s3/

**Comment by Daenyth** [comment]
For now I changed the links on the website to use the github files instead of bintray

**Comment by Daenyth** [comment]
https://www.appveyor.com/docs/deployment/amazon-s3/

**Comment by Daenyth** [comment]
I deleted the Cockatrice-git bintray project. At this point I'm now not sure that bintray is getting us anything useful, and it may be more convenient to just drop it. We can already push manual release files on the github release, and we already need to manually update the website with links, so without automatic uploading I don't think bintray gets us anywhere any more

**Comment by Daenyth** [comment]
It looks like stable releases have predictable urls: `https://github.com/Cockatrice/Cockatrice/releases/download/<release-tag>/<filename>`

And github has a really nice API we should be able to use

**Comment by Daenyth** [comment]
We can get uploaded files with https://developer.github.com/v3/repos/releases/#get-a-single-release

**Comment by Daenyth** [comment]
The "latest" release thing we use already returns the same structure

**Comment by tooomm** [comment]
Any news from bintray support?
@ctrlaltca received the same info. Maybe he has some news?

**Comment by Daenyth** [comment]
Making a new ticket to track dev channel updates - I'll leave this ticket to be closed as stable channel is fixed
