### ISSUE TITLE
Cockatrice keeps crashing when I try to make certain tokens

### ISSUE THREAD

**Issue by The-DJ-Pon3** [Cockatrice/Cockatrice#2512]
<b>OS:</b>
*Windows 7 Professional*

<b>Cockatrice version:</b>
*6e723b2*

___
<br>

I've had this issue ever since the most recent client update where my game will crash whenever I try to create specific tokens. So far the ones that cause the crash are Gideon, Ally of Zendikar's emblem, and using either Gisela or Bruna to make Brisela, Voice of Nightmares.

I'm by no means a programmer or anything of the sort, so if anyone has a fix for me, please have patience if I'm not understanding. I'll include images of a test game I ran specifically to make the two tokens and the crash it gave me. I'm not able to find any crash logs, though I don't exactly know how to acquire those either.

Thank you!
- The DJ Pon3
![gideon crash](https://cloud.githubusercontent.com/assets/26513307/24077365/3f1f8de4-0c08-11e7-9fc3-f3ef7e76fce5.PNG)
![bruna crash](https://cloud.githubusercontent.com/assets/26513307/24077366/3f211d6c-0c08-11e7-83dc-95b99867820a.PNG)

**Comment by ZeldaZach** [comment]
This has been fixed in #2506
