### ISSUE TITLE
Download of update installer can't be cancelled once started

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#2518]
<b>Cockatrice version:</b>
piday+some commits
<img width="395" alt="screen shot 2017-03-19 at 9 27 13 am" src="https://cloud.githubusercontent.com/assets/14644/24081236/4673636c-0c86-11e7-88b8-e4c7897a838b.png">

There should be a "Cancel download" button

**Comment by ZeldaZach** [comment]
I'll work on this after other PRs are merged
