### ISSUE TITLE
Dev channel builds broken post-bintray

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#2519]
follow up #2502

Need to decide where to host builds from CI - probably S3 since it's cheap and integration is easy.

Need to decide how we will manage an index file so the client can tell what dev release is the latest. Hopefully this doesn't require code but if needed we could make something like an AWS lambda that's triggered on S3 upload which can update a static json file

**Comment by ZeldaZach** [comment]
I'm personally looking at DigitalOcean for hosting as I think it would be cheaper then S3...

And I'm all for a JSON file that contains the necessary information (build name, release time, commit hash, download URL)

**Comment by Daenyth** [comment]
I'd rather not manage a full server if we can avoid it. That's why I like s3+lambda, there's 0 management involved. Nothing to keep up to date. And I really do think money cost will be tiny

**Comment by Daenyth** [comment]
I made an s3 bucket. Just need to get travis config in order now

**Comment by tooomm** [comment]
Interesting read:
http://mediagoom.com/blog/How-to-automate-a-@GitHub-release-using-@travisci-and-@appveyor
