### ISSUE TITLE
Set up coverity scan with travis

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#2520]
https://docs.travis-ci.com/user/coverity-scan/

Source code static analyzer

**Comment by Daenyth** [comment]
ref for later https://scan.coverity.com/projects/cockatrice-cockatrice/builds/new?tab=travis_ci

**Comment by tooomm** [comment]
Interesting 👍

**Comment by Daenyth** [comment]
Coverity was a pain, I set up codacy instead. Might come back to this later but closing for now
