### ISSUE TITLE
Website Redesign Proposal

### ISSUE THREAD

**Issue by jetthill** [Cockatrice/Cockatrice#2525]
<b>OS:</b>
macOS 10.10+

<b>Cockatrice version:</b>
N/A

___
<br>
Hello,

I am proposing a redesign of the cockatrice.github.io website. I will build this site to be mobile friendly, based on this first page template. All of the original information is there, just moved around. When viewing this mockup, be sure to view in 100% to get the best resolution. 

![cockatricewebsite](https://cloud.githubusercontent.com/assets/23219238/24123662/6cdc3d0e-0d8e-11e7-853d-69a8cbdfc799.png)

Questions and comments are always welcome.

Thanks,
Drew Hill
UN: jetthill

**Comment by ZeldaZach** [comment]
This should be done @ the other repo: https://github.com/cockatrice/cockatrice.github.io

**Comment by Daenyth** [comment]
Overall I like the proposal. I'd accept a PR changing the website along these lines. As Zach mentions, you can fork that repo to change the website code.

cc @Cockatrice/website-managers

**Comment by tooomm** [comment]
@ZeldaZach at the other repo we don't have issues enabled and redirect people here to better respond to and faster catch issues^^
