### ISSUE TITLE
Deck editor not showing up. Unable to create new decks or load old ones

### ISSUE THREAD

**Issue by dvsmaster** [Cockatrice/Cockatrice#2526]
OS Name	Microsoft Windows 10 Home
Version	10.0.14393 Build 14393

Version 6e723b2 (2017-03-14)

___
<br>

Whenver I start up Cockatrice the deck editor does not show up and I'm unable to create new decks or load any previous decks that I have made. I tried to uninstall and reinstall cockatrice and it worked the first time I used it but when I exited the program and came back, the same problem happened again. It seems  that the decks are registering since the buttons seem to be working its just that I can't see the deck editor popup. I just want to make sure I am not doing something wrong since I am new to the program.

![deck editor not showing up](https://cloud.githubusercontent.com/assets/26559843/24129274/e5c5bb68-0db7-11e7-987d-8d4839689176.GIF)

**Comment by ZeldaZach** [comment]
If you reset your layout, you should be able to see the entire deck editor
