### ISSUE TITLE
It's too easy to close/hide important dockable elements

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#2528]
View > reset layout fixes the problem but it's not intuitive or discoverable. Universally people just think cockatrice is broken.

Let's brainstorm a UX solution here that will let users discover on their own what happened and how to fix it. Maybe little minimized tabs instead of fully closed areas?

**Comment by tooomm** [comment]
The initial implementation had some nice little buttons which showed the status (displayed/hidden) and would allow to change the state on click: #1342 
I really liked that. But he removed it later in favour of the menu - maybe for some other reasons as well, don't remember in detail.

While it's easy to use and not offending or annoying in the UI (speaking about deck editor), it might be difficult to find a good location for them within game rooms. But totally up for something like that!

**Comment by ZeldaZach** [comment]
@ebbit1q and I both think it's fine as-is currently. Having a popup confirming close would be annoying. And most users ask for help if that happens anyway

**Comment by tooomm** [comment]
>Having a popup confirming close would be annoying. 

Not necessarily.

A simple `[ ] Don't show this again` check box in the dialog does the trick.
The popup can not only be a warning, but also makes sure the users knows about the "View" menu options.
