### ISSUE TITLE
Tezzeret the schemer bugs out when +1 token spawn is used!

### ISSUE THREAD

**Issue by DrRyger** [Cockatrice/Cockatrice#2530]
Easy to reproduce, start a match 1 v 1 and activate his +1 ability and game crashes

**Comment by ZeldaZach** [comment]
Sounds like a bug I fixed last week #2506

**Comment by Daenyth** [comment]
@ZeldaZach What do you think about trying to push the stable channel auto update PR through and then cutting a new release? Seems like 2506 is affecting a lot of people, I'd like to get the fix out

**Comment by ZeldaZach** [comment]
I'm fine with that. We can also upload to bintray so people can manually download still for that instead of having to go to the site. Then they'll be on a perm switch to the github releases.

**Comment by Daenyth** [comment]
Yeah we should keep uploading to bintray for now at least.
