### ISSUE TITLE
add links about custom themes to settings

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2533]
Taken from Gitter:

>JineteDV @JineteDV Mar 22 20:52
To get to Package Contents where the themes were stored, I had to right click on the program itself.
Package Contents/Contents/Resources/themes is where they were.
>
>Zach H @ZeldaZach Mar 22 20:54
>Those are where the default themes we package are stored
>they are not really to be edited
>
>JineteDV @JineteDV Mar 22 20:54
>That's what I've been editing xD
>
>Gavin Bisesi @Daenyth Mar 22 20:54
>@JineteDV that's not the right place to put custom themes
>
>Zach H @ZeldaZach Mar 22 20:54
>You're supposed to use the themes in the app support folder
>
>Gavin Bisesi @Daenyth Mar 22 20:54
we could probably make the documentation clearer
**also maybe a "open custom theme folder" button in settings
which creates the directory if missing**
>
>tooomm @tooomm Mar 22 21:13
pretty simple and straight forward to have a link in settings. right next to a wiki link "how to create a theme" https://github.com/Cockatrice/Cockatrice/wiki/Themes

**Comment by ZeldaZach** [comment]
I'm fine with adding it, just the question is where. We have the "Deck Editor" tab with the other custom open buttons, but i don't feel it fits there... maybe?

**Comment by tooomm** [comment]
>just the question is where. We have the "Deck Editor" tab with the other custom open buttons, but i don't feel it fits there... 

You mean this?
![cdb](https://cloud.githubusercontent.com/assets/9874850/24284817/76632a86-106d-11e7-8389-2a603d9e318d.png)

The `Card Database` menu is actually also available in games etc.

But as @Daenyth said: "a `open custom theme folder` button **in settings**" is the best place i guess.
We have other explaining links already in settings:
![example](https://cloud.githubusercontent.com/assets/9874850/24284876/be0643dc-106d-11e7-8d16-ae4c35392cca.png)

The explaining link to the wiki should be placed the same:
![location](https://cloud.githubusercontent.com/assets/9874850/24284894/ceaf7f46-106d-11e7-93a3-4204a43530ad.png)

I just don't know if a link to a folder location can be created the same (especially if it maybe needs to create the folder if not present). Maybe it needs to be a button with a function instead?
But placing the check-if-exist-and-create-folder-plus-open-location button right next to the other two in `card database` isn't too bad either... or move all of them to the main menu, or view?

**Comment by ZeldaZach** [comment]
Ahh, gotcha. I'll figure it out from here!

**Comment by Jinxstands4Jinx** [comment]
TBH i would prefer if we did NOT have a "how to set up video"  more of a "click here to set up" because a user may not always be online and able to watch a video

**Comment by tooomm** [comment]
>TBH i would prefer if we did NOT have a "how to set up video" more of a "click here to set up" because a user may not always be online and able to watch a video

Who wants a video?! I think a video would be bad...

**Comment by skwerlman** [comment]
I agree w/ Jinx that in-client documentation and tips should not depend on an internet connection. GitHub wikis are actually git repositories, so it should be possible to include ours as a submodule which could be built into offline documentation (like html files) and then bundled with the installer.

**Comment by tooomm** [comment]
Great idea @skwerlman !
But since it would affect all other links to the wiki as well... it seems to be a bigger change and not 100% related here. I think it's better off in its own issue? 👍

**Comment by Jinxstands4Jinx** [comment]
2 things. 1) saying it's a link often means its a video. 2) that was my idea !

**Comment by Jinxstands4Jinx** [comment]
Also the idea of a "click here to learn" how to set up sounds bad as When i was setting up my theme i had no clue how to do it and reading the wiki did nothing to help, i had to learn by trail and error and i Still have no idea how to Change/fix my theme

**Comment by skwerlman** [comment]
@tooomm I don't think it'd affect any links to the wiki at all; rather, we'd tell just tell git to download it too when cloning cockarice. It'd still be in the same place.

https://git-scm.com/docs/git-submodule

**Comment by ZeldaZach** [comment]
@skwerlman Would it auto update then or is it a bundle thing?

**Comment by skwerlman** [comment]
It'd be updated by the command `git submodule update wiki` where `wiki` is the subdirectory the docs would be downloaded to (it can be named something else if desired). The conversion to offline docs would have to be added to `make`, but that's literally the hardest part of setting it up.

**Comment by tooomm** [comment]
So you need to change all links to like `\cockatrice\wiki\wiki-pagename` to make them access the bundled offline html files?

**Comment by Jinxstands4Jinx** [comment]
or just include text documents in the download package

**Comment by Daenyth** [comment]
While offline docs would be useful I think it's still going to be easiest
for most people if it's a link to the wiki so they get instant updates.
Bundling in git doesn't make much sense for us.

**Comment by ZeldaZach** [comment]
Gonna close in favor of #4087 as I'd like themes to come from a centralized source
