### ISSUE TITLE
App crashes with the planeswalkers emblems

### ISSUE THREAD

**Issue by serrano65** [Cockatrice/Cockatrice#2535]
<b>OS:</b>
*Mac Os Sierra 10.12.3*

<b>Cockatrice version:</b>
*6e723b2 (2017-03-14)*

The app crashes when you try to put the emblem of  the walkers that have both modes( put a token and also put emblem). like liliana, the last hope or Gideon, ally of zendikar.

Is there any way to fix it by myself? thank you so much

**Comment by ZeldaZach** [comment]
This bug was fixed, will have another release next week with the fix
