### ISSUE TITLE
Re-enable "scale cards on mouse over" doesn't work

### ISSUE THREAD

**Issue by ReggieFourmyle** [Cockatrice/Cockatrice#2539]
<b>OS:</b>
*Override this line with the exact operating system you are running! (e.g. "Win 7 SP1", "OS X 10.8.5", "Ubuntu 15.10" ...)*

<b>Cockatrice version:</b>
*Put your Cockatrice version number & build date here! You find them inside the app: `Help` --> `About Cockatrice` (e.g. "2d53ce9 (2016-02-18)"). If you can't access this menu for any reason, please include the full filename of the installer you used.*

**Version 6e723b2 (2017-03-14)**

___
<br>

*Explain your Issue/Request/Suggestion in detail here!*

- [x] **Bug 1:**  Right clicking on Huntmaster of the Fells and selecting "Token: Ravager of the fells" now crashes the app 100% of the time.  If you select "Create all tokens" it does not crash though.

- [ ] **Bug 2:**  In the preferences under the Appearance tab if you disable the option "Scale cards on mouse over" then hit okay.  Then re-enable the option, it does not work, you can check the box, but the cards no longer scale on mouse over.

**Comment by Nightfirecat** [comment]
(1) is fixed already, and there's an upcoming release which will address that for everyone on the stable release channel, just FYI

**Comment by ZeldaZach** [comment]
I just tested for this and this doesn't appear to be an issue on Mac or Linux, @tooomm Is this a problem on Windows?

**Comment by tooomm** [comment]
Works for me on Win with Version 2.3.18-custom_45b5853 (2017-06-01) in a local game.

**Comment by ZeldaZach** [comment]
Sounds good. If this is still an issue, pleas reopen!
