### ISSUE TITLE
change the behavior of saving settings (win)

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2543]
taken from gitter:
>tooomm @tooomm 21:36
>but sooo weird for windows user that changes get reflected immediatly without hitting ok :confused: (#1334)
>
>Zach H @ZeldaZach 21:37
>The changes aren't based on OK
>It's standard across the board
>it's auto-updated based on your selection
>
>tritoch @tritoch 21:37
>i think he wants cancel to do something
>
>tooomm @tooomm 21:37
>it's not standard at all on windows in general, just trice
>
>Zach H @ZeldaZach 21:37
>Well... idk what to say about it
>
>tooomm @tooomm 21:37
>jep, or hitting x... especially since they intend to do something :smiley:
>
>tritoch @tritoch 21:37
>hitting cancel in windows reverts any changes
>
>Zach H @ZeldaZach 21:37
>What would you like me to do?
>I can probably make a change so it only updates on "Ok"
>If that would make things better
>but everything on trice is auto-updating
>the "Ok" is a simple "Close dialog i'm done now"
>
>tooomm @tooomm 21:38
>no, set changes not for example
>
>tritoch @tritoch 21:38
>maybe OK should say Save ?
>
>tooomm @tooomm 21:38
>you get a special dialog and reload on ok for example
>
>Zach H @ZeldaZach 21:39
>What do you think we should do then
>
>tritoch @tritoch 21:39
>i made wooger change the 'ok' in the connect dialog to say 'connect'
>
>tooomm @tooomm 21:40
>save seems also fine, but anyway it's weird for windows users the way it's right now... they are used to be able to play around with stuff (e.g. messing up your picture link) and simply revert any changes made
>
>Zach H @ZeldaZach 21:40
>Well how about this
>
>tooomm @tooomm 21:40
>in trice you're somehow fucked if you made a faulty high impact change, because it's immediately saved and you need to figure out how to revert it on your own
>
>Zach H @ZeldaZach 21:40
>for the next release
>we will fix all dialogs
>to confirm to one method, "Ok" == Save
>
>tooomm @tooomm 21:41
>sure sure
>
>Zach H @ZeldaZach 21:41
>otherwise, revert everything
>Sound good ?
>
>tritoch @tritoch 21:41
>:thumbsup:

cc: @ZeldaZach @tritoch

**Comment by ctrlaltca** [comment]
Closing in favor of #1334
