### ISSUE TITLE
tr() string with only a reference inside

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2544]
https://github.com/Cockatrice/Cockatrice/blob/master/cockatrice/src/userinfobox.cpp#L115
Shouldn't have a tr tag at all. Just confused translators at transifex and might introduce mistakes.

No layman knows what to do with a translation string which shows up as `%1`, it just shouldn't be there. ;)

**Comment by ZeldaZach** [comment]
You can make a PR to make it just a QString("%1")

**Comment by tooomm** [comment]
Will do! Wasn't exactly sure how to transform it correctly. Thanks. 👍
