### ISSUE TITLE
Improve filter for split cards

### ISSUE THREAD

**Issue by dev-id** [Cockatrice/Cockatrice#2546]
When using filters in deck editor, split cards are difficult to locate.  Here is an example split card entry from cards.xml:

```
        <card>
            <name>Far // Away</name>
            <set rarity="" muId="369042" num="127a">DGM</set>
            <color>U</color>
            <color>B</color>
            <manacost>1U // 2B</manacost>
            <cmc>2 // 3</cmc>
            <type>Instant // Instant</type>
            <tablerow>3</tablerow>
            <text>Return target creature to its owner's hand.
Fuse (You may cast one or both halves of this card from your hand.)

---

Target player sacrifices a creature.
Fuse (You may cast one or both halves of this card from your hand.)</text>
        </card>
```

- [x] Filtering for CMC 2, 3 or 5 will not find the split card
- [ ] nor will manacost `1U` or `2B` (or `3UB` though that would not be expected.) 

`type` and `text` may not be well handled, and using `num` in image downloader url may not work as expected.

**Comment by tooomm** [comment]
With amonkhet the rules even change and (all!) split cards have a different cmc now:
http://magic.wizards.com/en/articles/archive/news/amonkhet-split-card-rules-changes-2017-04-04

So as long as the card isn't played on the stack (well, one half of it) the cmc of the card are the combined costs of both.

So Oracle should account for that and properly display `cmc 5` in the example card above as well.
Or even `5 (2 // 3)`

**Comment by tooomm** [comment]
#3090 fixes the first part, and improves the second...

But searching for `Mana Cost = 1U AND 2B` still won't find Far // Away.

For mana cost each "sub-card" should be treated on its on, no combination of all single values needed as with cmc I think.
