### ISSUE TITLE
Crash Creating Certain Tokens

### ISSUE THREAD

**Issue by jabaldwin** [Cockatrice/Cockatrice#2548]
<b>OS:</b>
Win 10 Home x64

<b>Cockatrice version:</b>
Version 6e723b2 (2017-03-14)

___
<br>

When I try to create certain tokens, the game instantly crashes. I've noticed this with the emblem for Liliana, the Last Hope, as well as the meld Brisela, Voice of Nightmares from either Bruna or Gisela. Many other tokens work fine.

**Comment by Nightfirecat** [comment]
This is a known issue for cards that produce multiple types of tokens and has already been fixed; the fix should be released in a new version in the near future.
