### ISSUE TITLE
Tones for buddies

### ISSUE THREAD

**Issue by Jinxstands4Jinx** [Cockatrice/Cockatrice#2552]
Would there be a way you could set a specific sound to play when a Certain user comes in. like instead of checking the list every hour when you are looking for someone. you could just set it to alert you when they enter

**Comment by ZeldaZach** [comment]
This seems like it could get annoying fast...

**Comment by Jinxstands4Jinx** [comment]
really? the user could set the ton and if annoyed just turn it off. not sure i get why it would be annoying?

**Comment by ZeldaZach** [comment]
If I have 50 buddies and they pop on and off, it'll be annoying. I don't think I'm going to look into this at the moment, but if someone wants to they're free to

**Comment by Jinxstands4Jinx** [comment]
no no thats not what i meant. you would only be able to set a tone for 1 persona nd only 1 tone at a time.

**Comment by ZeldaZach** [comment]
If that's what you mean then I don't see a point to this... setting a tone for one buddy only? Seems like a waste of dev time tbh. If you'd like to make it go for it, but I'm not sure we'd accept it.

**Comment by Jinxstands4Jinx** [comment]
like example say you wanted to talk to me, instead of checking the list repeatedly. i just noticed as i was looking for someone and was tired of checking, if its not a good idea my bad. it just seemed like it owuld be easier to check a box so i would be alerted when they came, much like i am alerted when people mention me.

**Comment by Daenyth** [comment]
I think it would be reasonable to have a 'got pm' sound and a 'got pm from buddy' sound. We could even have the latter default to the same sound as the former, but just be aware of it so that a sound theme can override it

**Comment by Jinxstands4Jinx** [comment]
well i guess... but i was thinking more of a tone when a Certain user came
on. so incase you were trying to meet up with someone for deck tech

**Comment by LethalPigeon7** [comment]
I feel like some *visual* indication of buddies going online could still be handy and not at all annoying. Maybe just the "account" tab getting the blue (I). Not sure if worth dev time, but then again when am I.

**Comment by ZeldaZach** [comment]
We have a way to get notified if a buddy goes online.
