### ISSUE TITLE
Change "About Cockatrice" Menu to show SemVar

### ISSUE THREAD

**Issue by ZeldaZach** [Cockatrice/Cockatrice#2556]
Current: (The version in the "about" window is git sha1 + date of build)
```
Version 54911ee (2017-03-24)
```

Future:
```
Version 2.3.15 (xxxx-xx-xx)
Version 2.3.16-betaXXX (xxxx-xx-xx)
```

**Comment by tooomm** [comment]
I assume the dates should be the release (or pre-release) dates then?
Which mostly matches the build date with the automation in place. But well, actually it could be build a day later if we're unlucky or there are some other problems. Or we need to manually upload binaries for some reason etc.

Recommendation from Github:
>**Tagging suggestions**
>It’s common practice to prefix your version names with the letter v. Some good tag names might be v1.0 or v2.3.4.
>
>If the tag isn’t meant for production use, add a pre-release version after the version name. Some good pre-release versions might be v0.2-alpha or v5.9-beta.3.
>
>**Semantic versioning**
>If you’re new to releasing software, we highly recommend reading about [semantic versioning](http://semver.org/).

So do we favor `v2.3.15` instead?

**Comment by Daenyth** [comment]
I don't feel strongly. Slight preference to keeping the tags similar to our previous system as zach and I discussed
