### ISSUE TITLE
Cannot add/delete buddies

### ISSUE THREAD

**Issue by ZeldaZach** [Cockatrice/Cockatrice#2560]
This issue was unfortunately caused by #2501.

This is a bad regression that causes the "Add/remove buddylist/ignorelist" buttons to not populate.

Build before merge:
<img width="227" alt="screenshot 2017-04-01 01 44 13" src="https://cloud.githubusercontent.com/assets/7460172/24575759/b782025c-167c-11e7-9c6d-68ed3acf47fd.png">
Build after merge:
<img width="233" alt="screenshot 2017-04-01 01 43 28" src="https://cloud.githubusercontent.com/assets/7460172/24575757/b06ab1bc-167c-11e7-9fb0-9b091cc1f59c.png">

**Comment by Daenyth** [comment]
Well that's annoying. I'll see what I can do, but I'm a bit busy this weekend.

Can you still add/remove from the lists on the buddy list tab?

**Comment by Daenyth** [comment]
First guess is here https://github.com/Cockatrice/Cockatrice/pull/2501/files#diff-fb76ae8a58fcb9e9bf4ce06e132fe969R270 `    if (userLevel.testFlag(ServerInfo_User::IsRegistered) && tabSupervisor->isOwnUserRegistered()) {`

**Comment by Daenyth** [comment]
```
+bool TabSupervisor::isOwnUserRegistered() const
 +{
 +    return (bool) getUserInfo()->user_level() & ServerInfo_User::IsRegistered;
 +}
```

I'm guessing the cast is on the wrong thing here - I think it's casting `user_level` to bool and doing `bool & int` or something.

@ZeldaZach try changing it to `return (bool) (getUserInfo()->user_level() & ServerInfo_User::IsRegistered);`
