### ISSUE TITLE
Feature request: macros

### ISSUE THREAD

**Issue by ddevault** [Cockatrice/Cockatrice#2563]
<b>OS:</b>
*Arch Linux*

<b>Cockatrice version:</b>
*20150924.1-1*

__________

I would like to be able to make macros to streamline gameplay with lightweight rules implementations. You'd record yourself doing something, then you could activate the macro to play the recording back later. For example, I could make a macro for [Ponder](http://magiccards.info/m12/en/73.html) that pulls up the top 3 cards of my library. Another macro might draw a card and lose a life for [Phyrexian Arena](http://magiccards.info/cn2/en/144.html). [Grave Titan](http://magiccards.info/c14/en/145.html) creates two zombie tokens.

Triggering macros could be bound to keys, keys+clicks, or specific events. I could trigger the Ponder macro by alt+clicking it. I could trigger the Phyrexian Arena macro automatically on upkeep so long as it's in play. Grave Titan when tapped during the attack phase. [Geist of Saint Traft](http://magiccards.info/ddq/en/1.html) macro could activate under similar conditions and create and tap a token that's automatically removed at the end step.

I think this strikes a good balance between not enforcing rules and convenience.

**Comment by ZeldaZach** [comment]
This seems feasible. Can probably extend on the "Custom Shortcuts" way of doing things to add additional actions. Maybe these actions are stored in an XML keyset

```
<special-action>
	<key-action>SHIFT+CLICK</key-action>
	<card>
		<name>Ponder</name>
		<action>Trigger {CTRL+W, 3}</action>
	</card>
	<card>
    	<name>Brainstorm</name>
		<action>Trigger{CTRL+E, 3}</action>
	</card>
</special-action>
```

**Comment by Jinxstands4Jinx** [comment]
I would Advize a "macros on" or "macros off" check box before these as to me, they sound too confusing to care about and i would not want to accidentally trigger one in game

**Comment by Daenyth** [comment]
I'm not sure if this makes a ton of sense for us. I think the majority of users would find these confusing. By comparison, this is more complicated than chat macros, and most users do not use those at all, or know how to configure them

**Comment by Jinxstands4Jinx** [comment]
that was my thought.

**Comment by SirCmpwn** [comment]
I think the majority of users will probably not be making these, but if at some point they were made sharable then a lot of people would get on board. Some of them would be pretty intuitive, i.e. Grave Titan.

I also think that no one uses chat macros because they aren't useful, not because they're complicated.

**Comment by tooomm** [comment]
Jep, having a chat makro for saying "resolves" doesn't give you too much benefit and can be typed in the same amount of time more or less (e.g. "k").
Maybe that's why most people don't use them or don't know/talk about them.

**Comment by Daenyth** [comment]
I'd be open to removing the chat macro feature honestly, just to slim the app down a bit.

**Comment by tooomm** [comment]
Regarding the macros, would something like autohotkey work?
You can do some really powerful stuff with it!

**Comment by SirCmpwn** [comment]
Nope, I'm afraid not.

**Comment by skwerlman** [comment]
AHK wouldnt be able to access the board state in the way that a built-in macro system would. Still, I don't think that this feature would be useful to very many people.

**Comment by LethalPigeon7** [comment]
I'm currently happily making use of a couple chat macros, and have a couple lines saved in a text file to use as main chat macros, this feature sounds great.

**Comment by ricott1** [comment]
Is there any update on this? I think this feature would greatly improve the gameplay, and as @ddevault mentioned, if made sharable a lot of people could start using them. I really wish I could fetch in one command :)

**Comment by ZeldaZach** [comment]
Hey @ricott1 unfortunately I think I'm gonna be closing this ticket as there's not a ton of interest and it seems like a lot of work for a fairly niche/hidden feature. If you'd like to contribute a bit of code to help bring this to reality, I'd gladly review it and see if it makes sense :)
