### ISSUE TITLE
Database and code for my uni project

### ISSUE THREAD

**Issue by Ares37901** [Cockatrice/Cockatrice#2567]
<b>OS:</b>
*Win10*

Using cockatrice database (.xml) with my project for uni.
Sorting through it to discard non-standard cards, takes 3 minutes.
Talked to Gavin Bisesi on Gitter and he said to put the code up here, using C#.

```c#
        XmlDataDocument xmldoc = new XmlDataDocument();
        XmlNodeList xmlnode;
        FileStream fs = new FileStream("E:/Local/Cockatrice/Cockatrice/cards.xml", FileMode.Open, 
        FileAccess.Read);
            xmldoc.Load(fs);
            xmlnode = xmldoc.GetElementsByTagName("card");
            //Standard
            //AER KLD EMN SOI OGW BFZ
            string[] standard = new string[] { "AER", "BFZ", "EMN", "KLD", "OGW", "SOI" };

                for (int num = xmlnode.Count - 1; num >= 0; num--)
                {
                    bool toDel = false;
                    //xmlnode[num].SelectNodes("set").Count
                    if (xmlnode[num].SelectNodes("set").Count >= 1)
                    {
                        for (int i = 0; i < standard.Length; i++)
                        {
                            for (int j = 1; j <= xmlnode[num].SelectNodes("set").Count; j++)
                            {
                                if (toDel == true)
                                { continue; }
                                else if (xmlnode[num].ChildNodes[j].InnerText.ToString() == standard[i].ToString())
                                { toDel = true; }
                            }
                        }
                    }

                    if (toDel == false)
                    { xmlnode[num].ParentNode.RemoveChild(xmlnode[num]); }
```

Returns and xmlnode List with only standard cards. Similar code used to get rid of extra colors as program allows decks with maximum 2 colors.
Would appreciate any advice guys just go easy on me lol, not that good in c# after all but the tutors want complexity based on my knowledge.

**Comment by Nightfirecat** [comment]
Firstly, this isn't an issue with Cockatrice's software&mdash;I don't think this is the right place to post a general programming question.

Secondly, is there any reason you're attached to using Cockatrice's cards.xml format? I'd recommend you use [MTGJson](https://github.com/mtgjson/mtgjson) (from which it's derived) instead since it's the actual source of this data.

**Comment by Ares37901** [comment]
Gavin Bisesi sent me this way, secondly it's because at the time I didn't realize where cockatrice grabs its database so I used what I had, and lastly I have looked at the mtgjson website and apart from allsets and separate sets there are no links that I can see.

**Comment by Nightfirecat** [comment]
If there's no requirement to maintain the full-sets version, why not supply your project with a trimmed-down version that only contains the sets you need?

**Comment by Ares37901** [comment]
Because the 6 sets required are all throughout the database, I will need to delete around 15,000 record by hand

**Comment by Daenyth** [comment]
So, it is as I suspected doing O(n^2) work.

Deleting entries from an array is O(n) because it needs to re-index every element after it. I bet it you added debug output you'd see this going slower the longer it runs, since you walk the array backwards.

So, a few approaches:

Start with mtgjson, filter in a 5-line python script or so, and emit a trimmed json that you feed to oracle to get your xml

Leave the code as is, and instead of running it every time, store the output it produces and then use it as input for every run afterwards

Redo this to instead make a second target array of cards and append entries into it onto the end, instead of starting with everything and removing entries.

**Comment by ctrlaltca** [comment]
See attached comments
```
        XmlDataDocument xmldoc = new XmlDataDocument();
        XmlNodeList xmlnode;
        FileStream fs = new FileStream("E:/Local/Cockatrice/Cockatrice/cards.xml", FileMode.Open, 
        FileAccess.Read);
        // Why did indentation level change?
            xmldoc.Load(fs);
            xmlnode = xmldoc.GetElementsByTagName("card");
            //Standard
            //AER KLD EMN SOI OGW BFZ
            string[] standard = new string[] { "AER", "BFZ", "EMN", "KLD", "OGW", "SOI" };
                 // Why did indentation level change again?
                for (int num = xmlnode.Count - 1; num >= 0; num--)
                {
                    bool toDel = false;
                    //no need to check this here, you're gonna use it in a loop, if it has no items it will just loop zero times.
                    if (xmlnode[num].SelectNodes("set").Count >= 1)
                    {
                        for (int i = 0; i < standard.Length; i++)
                        {
                            // avoid the overhead of extracting the number of "set" child nodes at each loop
                            // by saving the value to a variable here and using the variable in the loop
                            for (int j = 1; j <= xmlnode[num].SelectNodes("set").Count; j++)
                            {
                                // use "break" instead of "continue" to avoid unneeded cycles
                                if (toDel == true)
                                { continue; }
                                else if (xmlnode[num].ChildNodes[j].InnerText.ToString() == standard[i].ToString())
                                { toDel = true; }
                            }
                        }
                    }

                    // Why does "toDel" means "not to be deleted"? logic inversion, fix var name
                    if (toDel == false)
                    { xmlnode[num].ParentNode.RemoveChild(xmlnode[num]); }
```

Another optimisation could be to first extracting the set name from `xmlnode[num].ChildNodes[j].InnerText.ToString()`, saving it to a variable and then using Array.IndexOf or similar on the "standard" array

**Comment by Daenyth** [comment]
ctrl's suggestions are good but are micro-optimizations or style related in this case. To avoid this taking 3.5 minutes you need to change your algorithm.

**Comment by ZeldaZach** [comment]
@Nightfirecat I'm fine with a question like this here, lets work on a solution :)
