### ISSUE TITLE
Add custom rules for games, specifically EDH

### ISSUE THREAD

**Issue by possiblyanowl** [Cockatrice/Cockatrice#2569]
<b>OS:</b>
*Put your operating system here! For example: "Win 7 SP2", "macOS 10.12.3", "Ubuntu 16.10" etc.*
Antergos
<b>Cockatrice version:</b>
*Put your Cockatrice version number & build date here! For example: "2d53ce9 (2016-02-18)"
You find them inside the app under `Help → About Cockatrice` (Windows & Linux), or `Cockatrice → About Cockatrice` (macOS).*
3498b16e
__________

*Explain your issue/request/suggestion in detail here!*

Allow users or server administrators to do custom rules for games, examples being starting life total, or maybe automatically fetching a card from sideboard. As an EDH only player, It'd be cool for Cockatrice to fetch the only card in sideboard(the commander) and put it in hand or on field.

**Comment by skwerlman** [comment]
starting parameters for things like starting life total sound easy to add. stuff like how the commander is handled would be (mostly) covered by #2286.

auto-fetching the commander could be accomplished by allowing cards to have properties like this:
```xml
<card number="1" price="0" name="Child of Alara" autocast="True"/>
```

**Comment by EntropiaFox** [comment]
This sounds relevant for me as well as I've been working on adapting Shadowverse for Cockatrice. In my case, the "Commander" is merely the card that represents the leader and thus the "class" of your deck, keeping a reminder of your passive ability.

**Comment by Daenyth** [comment]
This will probably come along with generic game support - subtypes where you take the base game rules and layer on tweaks, like starting life total, and adding an extra zone, like commander.

The deck editor could be extended to expose the commander zone (cod supports arbitrary named zones but the editor and maybe server treat main and sideboard specially)

Not a near-term goal but this is all valid stuff in line with the long term roadmap

**Comment by ZeldaZach** [comment]
This feels like an extension of #1740
