### ISSUE TITLE
Cockatrice Custom set file

### ISSUE THREAD

**Issue by N1c0lB0l4s** [Cockatrice/Cockatrice#2573]
Win 10

Cockatrice version: dab7316

__________

Recently I have been designing a custom set with others on Magic Set Editor, and wanted to upload to Cockatrice. I used the Cockatrice export here:
http://magicseteditor.sourceforge.net/node/7812

And imported this custom set file:
https://drive.google.com/drive/folders/0B1BQpLagm2_4OW1ZOXN1WkhET2c

Unfortuantely, the images wouldn't show up in Cockatrice. The card names did just not the cards. Does anybody know how to fix this? I'm not much of a tech person and didn't really understand the README in the exporter, maybe I missed something. Thanks!
Just writing this now too. With that file, now its not letting me upload to cockatrice; it doesn't appear in edit sets. I got it to do that before, any clue whats wrong?

**Comment by Daenyth** [comment]
If you go to Help > View debug log, does it say anything about card image downloading? Paste it here.

**Comment by N1c0lB0l4s** [comment]
Theme changed: "Default"
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
main(): starting main program
main(): MainWindow constructor finished
CardDatabase::loadCardDatabases start
main(): ui.show() finished
Attempting auto-connect...
cache fail for "_trice_card_back_226359"
link path1214 hasn't been detected!
link path1563 hasn't been detected!
link path1563 hasn't been detected!
[CardDatabase] loadCardDatabase(): Path = "C:/Users/nosam/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 16904 Sets= 203
[CardDatabase] loadCardDatabase(): Path = "C:/Users/nosam/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 17238 Sets= 203
[CardDatabase] loadCardDatabase(): Path = "C:/Users/nosam/AppData/Local/Cockatrice/Cockatrice/customsets/01.Fannlaug.xml" Status = 0 Cards = 17238 Sets= 203
CardDatabase::loadCardDatabases success
QObject::connect: No such slot TabSupervisor::resetIdleTimer()
CardDatabase::loadCardDatabases start
[CardDatabase] loadCardDatabase(): Path = "C:/Users/nosam/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 16904 Sets= 203
[CardDatabase] loadCardDatabase(): Path = "C:/Users/nosam/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 17238 Sets= 203
[CardDatabase] loadCardDatabase(): Path = "C:/Users/nosam/AppData/Local/Cockatrice/Cockatrice/customsets/01.Fannlaug.xml" Status = 0 Cards = 17238 Sets= 203
CardDatabase::loadCardDatabases success
CardDatabase::loadCardDatabases start
[CardDatabase] loadCardDatabase(): Path = "C:/Users/nosam/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 16904 Sets= 203
[CardDatabase] loadCardDatabase(): Path = "C:/Users/nosam/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 17238 Sets= 203
[CardDatabase] loadCardDatabase(): Path = "C:/Users/nosam/AppData/Local/Cockatrice/Cockatrice/customsets/01.Fannlaug.xml" Status = 0 Cards = 17238 Sets= 203
CardDatabase::loadCardDatabases success
cache fail for "_trice_card_back_226349"
Trying to load picture (set:  "EMN"  card:  "Abandon Reason" )
Picture found on disk (set:  "EMN"  file:  "Abandon Reason" )
Trying to load picture (set:  "TMP"  card:  "Abandon Hope" )
Picture found on disk (set:  "TMP"  file:  "Abandon Hope" )
Trying to load picture (set:  "pCEL"  card:  "1996 World Champion" )
Picture NOT found, trying to download (set:  "pCEL"  card:  "1996 World Champion" )
starting picture download: "1996 World Champion" Url: QUrl("http://gatherer.wizards.com/Handlers/Image.ashx?name=1996 World Champion&type=card")
Trying to load picture (set:  "UNH"  card:  "_____" )
Picture NOT found, trying to download (set:  "UNH"  card:  "_____" )
Trying to load picture (set:  "UNH"  card:  "\"Ach! Hans, Run!\"" )
Picture found on disk (set:  "UNH"  file:  "Ach! Hans, Run!" )
Trying to load picture (set:  "DDQ"  card:  "Abattoir Ghoul" )
Picture found on disk (set:  "DDQ"  file:  "Abattoir Ghoul" )
Picture downloaded, but blacklisted, will consider it as not found
Picture NOT found, download failed, no more sets to try: BAILING OUT (oldset:  "pCEL"  card:  "1996 World Champion" )
starting picture download: "_____" Url: QUrl("http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=74252&type=card")

**Comment by ctrlaltca** [comment]
Your custom set is named "FNG" and the first card "Angel of Warcraft", but i don't see any of those in the log you posted.
Anyway, i see in your custom set:
```xml
<set picURL="/Angel of Warcraft.full.jpg" picURLHq="" picURLSt="">FNG</set>
```
picURL needs to be a full url, like http://whatever.com/path/to/image.jpg in order to work.
Instead, if the images are already in your pc, just put them in the "custom images folder": https://github.com/Cockatrice/Cockatrice/wiki/Custom-Cards-&-Sets#to-add-custom-art-for-cards-the-easiest-way-is-to-use-the-custom-folder

**Comment by N1c0lB0l4s** [comment]
Where do I put the card image link within that file? Do I have to do each image individually? There is a place to put a link when I am automatically creating the cockatrice file but I tried that once with a public google drive folder but I tried that once and it didn't work.
I was hoping to make this usable with other custom sets and downloadable for others also.

I tried once again to upload the set in using this file:
https://drive.google.com/drive/folders/0B1BQpLagm2_4OW1ZOXN1WkhET2c

But when searching it didn't show any of the cards still. I checked the sets and Fannlaug wasn't there. Here is the debug:
Theme changed: "Default"
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
main(): starting main program
main(): MainWindow constructor finished
CardDatabase::loadCardDatabases start
main(): ui.show() finished
Attempting auto-connect...
cache fail for "_trice_card_back_226343"
cache fail for "_trice_card_back_226101"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/nosam/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 16904 Sets= 203
[CardDatabase] loadCardDatabase(): Path = "C:/Users/nosam/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 17238 Sets= 203
CardDatabase::loadCardDatabases success
QObject::connect: No such slot TabSupervisor::resetIdleTimer()
CardDatabase::loadCardDatabases start
[CardDatabase] loadCardDatabase(): Path = "C:/Users/nosam/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 16904 Sets= 203
[CardDatabase] loadCardDatabase(): Path = "C:/Users/nosam/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 17238 Sets= 203
[CardDatabase] loadCardDatabase(): Path = "C:/Users/nosam/AppData/Local/Cockatrice/Cockatrice/customsets/01.Fannlaug.xml" Status = 0 Cards = 17238 Sets= 203
CardDatabase::loadCardDatabases success
Trying to load picture (set:  "PLC"  card:  "Fa'adiyah Seer" )
Picture found on disk (set:  "PLC"  file:  "Fa'adiyah Seer" )
Trying to load picture (set:  "PLC"  card:  "Ana Battlemage" )
Picture found on disk (set:  "PLC"  file:  "Ana Battlemage" )
Trying to load picture (set:  "AVR"  card:  "Angel" )
Picture found on disk (set:  "AVR"  file:  "Angel" )
Trying to load picture (set:  "APC"  card:  "Angel " )
Picture found on disk (set:  "APC"  file:  "Angel " )
Trying to load picture (set:  "SOI"  card:  "Angel of Deliverance" )
Picture found on disk (set:  "SOI"  file:  "Angel of Deliverance" )
Trying to load picture (set:  "DD3_DVD"  card:  "Akroma, Angel of Wrath" )
Picture found on disk (set:  "DD3_DVD"  file:  "Akroma, Angel of Wrath" )

**Comment by Daenyth** [comment]
`picURL` is the right attribute for loading an image from the internet.

If you want them just on your own hard drive then you don't need to put anything in the xml at all - just make sure the image file is named after the card, as described on the wiki page ctrl linked you to

**Comment by N1c0lB0l4s** [comment]
With the uploader, can I just upload a link where all card images are contained? Meaning each link would be to the public file where all the card images are. Or, do I have to do it manually where I put a specific link for each individual card?

**Comment by N1c0lB0l4s** [comment]
So?

**Comment by skwerlman** [comment]
You have to include a specific link for each card.

**Comment by Daenyth** [comment]
That's the best way to handle it if you want anyone else to get the pictures.

**Comment by N1c0lB0l4s** [comment]
Well, I tried again using that and only one card before I went all out for hours, and it didn't work.
https://drive.google.com/drive/folders/0B1BQpLagm2_4dkNnY2staVY4Q3M

"\x00\x00\x00\x14\b\x01\x1A\x10\x82?\r\n\x0BMaximiliano"
""
""
""
"\x00\x00\x00\x10\b\x01\x1A\f\xE2>\t\n\x07\b\x02 i(\xCC\x02"
""
""
"\x00\x00\x00\x12\b\x01\x1A\x0E\x82?\x0B\n\tn0comment"
""
""
""
""
""
""
""
""
""
""
"\x00\x00\x00\x12\b\x01\x1A\x0E\x82?\x0B\n\tluke21234\x00\x00\x00\b\b\x00\x12\x04\b$\x10\x01"
"\x00\x00\x00\b\b\x00\x12\x04\b$\x10\x01"
""
""
""
""
"\x00\x00\x00\x10\b\x01\x1A\f\xE2>\t\n\x07\b\x02 h(\xCC\x02"
""
""
"\x00\x00\x00\x10\b\x01\x1A\f\xE2>\t\n\x07\b\x02 h(\xCB\x02"
""
""
""
""
""
""
"\x00\x00\x00\x15\b\x01\x1A\x11\x82?\x0E\n\funwisedragon"
""
""
""
"\x00\x00\x00\x10\b\x01\x1A\f\xE2>\t\n\x07\b\x02 f(\xCA\x02"
""
""
"\x00\x00\x00\b\b\x00\x12\x04\b*\x10\x01"
""
""
""
""
""
""
""
"\x00\x00\x00\x10\b\x01\x1A\f\xE2>\t\n\x07\b\x02 i(\xCA\x02"
""
""
""
CardDatabase::loadCardDatabases start
[CardDatabase] loadCardDatabase(): Path = "C:/Users/nosam/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 16904 Sets= 203
[CardDatabase] loadCardDatabase(): Path = "C:/Users/nosam/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 17238 Sets= 203
[CardDatabase] loadCardDatabase(): Path = "C:/Users/nosam/AppData/Local/Cockatrice/Cockatrice/customsets/01.Fannlaug.xml" Status = 0 Cards = 17238 Sets= 203
CardDatabase::loadCardDatabases success
""
""
""
"\x00\x00\x00\x0E\b\x01\x1A\n\x82?\x07\n\x05Zok72"
""
"\x00\x00\x00\x10\b\x01\x1A\f\xE2>\t\n\x07\b\x02 k(\xC8\x02"
""
""
"\x00\x00\x00\x18\b\x01\x1A\x14\x82?\x11\n\x0F""akira_ryuunoske"
""
"\x00\x00\x00\x10\b\x01\x1A\f\xE2>\t\n\x07\b\x02 k(\xC6\x02"
""
"\x00\x00\x00\x10\b\x01\x1A\f\xE2>\t\n\x07\b\x02 k(\xC5\x02"
""
""
""
""

I don't even see the name Fannlaug in the debug file or custom set. Every time I go to add custom sets, wait, then view the view sets and its not there.

**Comment by Daenyth** [comment]
Probably you broke the formatting. There's not a good error message right
now, the file just gets ignored. Run it through an XML validator. The wiki
page has a specific guide on this, on the customizing cards images page

**Comment by N1c0lB0l4s** [comment]
Can I have a link?

**Comment by ctrlaltca** [comment]
I already linked the page 3 days ago: https://github.com/Cockatrice/Cockatrice/issues/2573#issuecomment-292581704
@Daenyth referred to this paragraph: https://github.com/Cockatrice/Cockatrice/wiki/Custom-Cards-&-Sets#i-modified-my-cardsxml-and-it-isnt-working-properly

**Comment by N1c0lB0l4s** [comment]
Where do I find the "cards.xsd"? Or a better question, where do you find the Cockatrice installation directory?
Grab the "cards.xsd" schema file from the "doc" subdirectory of your Cockatrice installation directory. An updated copy is also available here.

**Comment by Daenyth** [comment]
Wherever you installed it to. On windows this is probably c:\program files\cockatrice, I think. Or `program files (x86)`, not sure. One of the two

**Comment by N1c0lB0l4s** [comment]
Where do I find xmlint? I swear i searched everywhere on the page. I am a windows user.
http://xmlsoft.org/downloads.html
Is it libxml? If so which one? Sorry that I'm clueless about all of this.

**Comment by ctrlaltca** [comment]
Download ftp://ftp.zlatkovic.com/libxml/libxml2-2.7.8.win32.zip
Unzip it, you'll find xmlint.exe inside the bin/ directory

**Comment by N1c0lB0l4s** [comment]
It says "iconv.dll" and "zlib1.dll" is missing from my computer when trying to download xmllint. How do I fix this? I have tried redownloading the program multiple times, as it says I should do.

**Comment by N1c0lB0l4s** [comment]
Is there any way to fix this?

**Comment by ctrlaltca** [comment]
You need a bit more curiosity. If you just try to read the page where you downloaded libxml from, you'll find references to both iconv and zlib and downloadable zips containing the files you are missing.

**Comment by N1c0lB0l4s** [comment]
So I apparently do not have cards.xsd on my computer. i went to the updated copy via the link, and it gave me a bunch of commands or something. Do I make this into something? If so, what and how?

**Comment by Nightfirecat** [comment]
You can download that here: https://github.com/Cockatrice/Cockatrice/blob/master/doc/cards.xsd

**Comment by N1c0lB0l4s** [comment]
I know that, but I just see lines of code, not any file. Is there any way to download it for I don't see one

**Comment by Nightfirecat** [comment]
Right-click this link and select "Save as...": https://raw.githubusercontent.com/Cockatrice/Cockatrice/master/doc/cards.xsd

**Comment by Nightfirecat** [comment]
![image](https://cloud.githubusercontent.com/assets/2199511/25062111/6f119420-217a-11e7-96e4-11b7945d7ee5.png)

**Comment by tooomm** [comment]
As I understand it, this is solved?

Please come back to us and reopen the issue if still persistent @N1c0lB0l4s !
