### ISSUE TITLE
Cannot add buddy or ignore

### ISSUE THREAD

**Issue by fbroma** [Cockatrice/Cockatrice#2574]
<b>OS:</b>
OSX 10.11.6

<b>Cockatrice version:</b>
2017/3/31

__________

I noticed that when I right click on a user's name, I can no longer add them to a buddy list or ignore list. This is also true in the main tab or anywhere else. Happens at all times.

**Comment by Nightfirecat** [comment]
This is fixed in the codebase, and you should be able to use a new development channel update to fix this. See #2572.
