### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by Jinxstands4Jinx** [Cockatrice/Cockatrice#2577]
I need help. my computer took a huge dump and i lost EVERYTHING. I cannot even install cockatrice right now. i am missing the dumb file and it refuses to open. Can some one help me get it back?

**Comment by Nightfirecat** [comment]
I think the [Troubleshooting wiki page](https://github.com/Cockatrice/Cockatrice/wiki/Troubleshooting) should help. If your message is "Failed to start because MSVCP100.dll was not found" (or 120/140), then it has steps to follow to resolve that.

**Comment by Jinxstands4Jinx** [comment]
yep 120... which i have like 8 copies of on my machine just not sure where
exactly they need to go.. and i think i lost all my Custom arts.. holy cow
i hope not.

**Comment by Daenyth** [comment]
There's nothing here for us to help with. If you have a specific error and you can't fix it by following the troubleshooting guide, please reopen and include the exact error.
