### ISSUE TITLE
Proposal: add a field to the card db for colloquial names of cards and cycles

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#2579]
A user should be able to search the deck editor for "checkland" or "shockland" for example, and find results.

This data would have to be done manually, but in general it represents a one-time cost per set which could be done over time by volunteer effort

Thoughts?

**Comment by ZeldaZach** [comment]
Can be problematic <=> users put BS data in. If people don't know the name of cards, they should either Google or ask others. Not our job to babysit them to finding the card they want. You have to have _some_ knowledge of MTG to use the MTG aspects of trice

**Comment by Daenyth** [comment]
> users put BS data in

I imagine we'd control it with github like we do with the tokens file.

**Comment by Jinxstands4Jinx** [comment]
also this may not work since not everyone calls them Tango lands. or what ever.

**Comment by tooomm** [comment]
There might be conflicts within different languages as well.
Sure, we could have several names for one card and try to cover it this way...

**Comment by Daenyth** [comment]
I'm starting to wonder if this is worth the effort, given that the card db is already complex code.

**Comment by ZeldaZach** [comment]
I don't find this worth it anymore honestly. We support regex searching now, so I trust users can follow that approach.

**Comment by ebbit1q** [comment]
except that we don't have regex searching implemented right now https://github.com/Cockatrice/Cockatrice/issues/4108
