### ISSUE TITLE
Edit Sets > sort by enabled does nothing

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#2580]
version snapshot-april-8

**Comment by ZeldaZach** [comment]
Well that's a pointless thing that just happens to be broken now... Blahh

**Comment by tooomm** [comment]
Pointless?
I think it's very useful (and the only practical way) if you want to check which single sets you've enabled without scrolling through all list.

You would sort all enabled sets to the top, quickly check the 20 enabled and then resort for date for example to get the newest pictures.

**Comment by Daenyth** [comment]
Not pointless.

In my case I had 8 sets enabled for RFT. I wanted to enable everything, but I wanted to keep those sets handy to switch back to enabling only them. I tried sorting them to the top by enabled. Ended up doing it manually, it worked well.
