### ISSUE TITLE
Changing the text size on card titles.

### ISSUE THREAD

**Issue by Jinxstands4Jinx** [Cockatrice/Cockatrice#2582]
I got my machine fixed, (in case anyone cared :) )  but I noticed something. The text on my machine is perfect and it works for everything except cockatrice. Could we include a method of changing the text size of the card titles?  I do not mean the text on the actual cards. I mean the text box that we see when a card is in our hand or the mosue scrolls over it. normally long worded card titles, like walkers block out most of the  "what this card does" text.

**Comment by ZeldaZach** [comment]
It should be the same size as when the card is in play, so as such you can already change it now.

**Comment by Jinxstands4Jinx** [comment]
how? the name text is huge and blockish and i looked all over setting and could not mind a "text size" box

**Comment by tooomm** [comment]
@Jinxstands4Jinx did you try this?
![size](https://cloud.githubusercontent.com/assets/9874850/25042824/619c690a-211b-11e7-802f-37e802a1c62b.png)

@ZeldaZach why does it say `maximum size` btw? isn't it the actual size?
Another thing: if you set a higher value the text gets bigger, but if you put a smaller value it resets to 12 somehow!?

**Comment by Jinxstands4Jinx** [comment]
thx zelda that was the box i could not find.
