### ISSUE TITLE
Flip linking In deck constructon

### ISSUE THREAD

**Issue by Jinxstands4Jinx** [Cockatrice/Cockatrice#2586]
Title kinda explains the issue. When you are constructing a deck there should be a note on the flip cards to the name of the other half. was trying to brew other day and had no idea what the other have of a flip card was... also put the note on BOTH sides.

**Comment by Daenyth** [comment]
I think you mean transform, not flip, but yes - I agree. We should have a quick way to jump to any related/reverse-related cards in the deck editor.

**Comment by tooomm** [comment]
dupe? https://github.com/Cockatrice/Cockatrice/issues/2013

**Comment by Daenyth** [comment]
Thanks
