### ISSUE TITLE
Custom Images Split cards

### ISSUE THREAD

**Issue by Jinxstands4Jinx** [Cockatrice/Cockatrice#2588]
I was trying to "foil" out my ahk cards and wanted a foil Heaven // Earth. but apparently the file names cannot have // in them so how exactly would you Custom an image for them? I think all the cards with // will have this Same exact issue. Is there a way to fix this?

**Comment by tritoch** [comment]
Call it HeavenEarth.jpg

**Comment by Jinxstands4Jinx** [comment]
but will it show up?

**Comment by Jinxstands4Jinx** [comment]
I am trying that and the Card does not show up the Custom picture nor does heavenEarth find heaven // earth.

**Comment by Nightfirecat** [comment]
![image](https://cloud.githubusercontent.com/assets/2199511/25055764/ab50496a-2119-11e7-9031-2cfd02a7a872.png)

**Comment by Daenyth** [comment]
Would be handy if someone adds a note on the `/` handling to the custom card image page on the wiki

**Comment by Nightfirecat** [comment]
⬆️ Done.
