### ISSUE TITLE
Create Token dialog should preview card art

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#2591]
To help distinguish between different versions of the same token name

**Comment by Jinxstands4Jinx** [comment]
Would be nice yes especially when several colors have the same name.

**Comment by tooomm** [comment]
Yep, with the new vigilance warriors people always get confused... and put the old normal KTK ones.

Additionally we can display keywords from tokens in the list (mtgjson is planning to add support for that, so it might be handy to carry that field over to tokens)

**Comment by Daenyth** [comment]
Yes, you're right. We should display keywords too for people who disable on-the-fly image downloading

**Comment by tooomm** [comment]
Not done yet though... but tagged for the upcoming milestone: https://github.com/mtgjson/mtgjson/issues/285

But since @Psithief is maintaining the token manually and apart from mtgjson, he would need to extend his script. What do you think Psithief?

**Comment by Daenyth** [comment]
I don't think so. Cockatrice already knows what image file to use when you
create the token. We just need to preview it. You'd shouldn't require any
changes on his side

**Comment by tooomm** [comment]
I was referring to:
>We should display **keywords** too for people who disable on-the-fly image downloading

mtgjson is adding an array for abilities^^

**Comment by Daenyth** [comment]
I don't think we need it much. Doesn't the token xml have card text?

**Comment by ZeldaZach** [comment]
> I don't think we need it much. Doesn't the token xml have card text?

some of them do i believe

**Comment by tooomm** [comment]
The token.xml has text for all tokens I guess, yes @Daenyth.
But token text might also mean not just abilities, think about the new embalm tokens!

I was pointing to that mtgjson change because the information (once included) could be used to include it in the tokens file as new tag. Same as Psi has his script which checks for related-cards from within allcards.json.

**Comment by backendr** [comment]
@Daenyth Having tried to create the correct `snake` token recently I can see this being an excellent idea.

**Comment by ctrlaltca** [comment]
Dupe #1665 ?

**Comment by tooomm** [comment]
I looked for that ticket and couldn't find it! I started to doubt it even exist... haha :D
Thanks for linking @ctrlaltca
