### ISSUE TITLE
Viewing replays causes program to crash

### ISSUE THREAD

**Issue by k5t77** [Cockatrice/Cockatrice#2593]
<b>OS: Win10 Home (x64) - inc. all updates</b>

<b>Cockatrice version: dc6c375 (2017-04-15)</b>

__________

Cockatrice crashes (with notification box) soon after starting to view a game replay. Without exception (so to speak ;)). I am not familiar with this issue at all from previous versions, but I might in fact have missed a few of those...

Otherwise, the program seems stable. And all other programs I use (many) seem fine, fwiw.

**Comment by Daenyth** [comment]
Does the crash box contain any detail information?

**Comment by Daenyth** [comment]
I can't reproduce this yet. Can you send us the .cor replay file that triggers the crash for you?

**Comment by k5t77** [comment]
Update: It will crash almost immediately after an actual game starts to be replayed, regardless of the replay file. Literally every single one will do this.

And here is an image showing both the debug log at that point, the game that just began (to be replayed), and the notification box, moved over to the right some.

I hope that is sufficient. Appreciate all your great work, guys. <3

**Comment by Daenyth** [comment]
I wonder if this is windows specific. I haven't had it crash on osx so far

**Comment by tooomm** [comment]
Jep, crashes for me as well on windows with rev2!

But only when the game starts. If I have a sealed room with chat nothing happens.
When I load a replay with an actual game it crashes immediately.

**Comment by Daenyth** [comment]
I watched one with a game on osx without crashing. Either I got lucky or
this is only in Windows

**Comment by Daenyth** [comment]
Actually let me confirm tonight that I'm on the very latest. It's possible
I'm a few commits behind and it's a regression very recently, in which case
it should be very easy to pinpoint the cause

**Comment by skwerlman** [comment]
Can confirm, this crashes on linux too.

Version dd36187 (2017-04-16)

**Comment by Daenyth** [comment]
```
#0  0x00007ffff65039d0 in QWidget::hasFocus() const () at /usr/lib/libQt5Widgets.so.5
#1  0x00007ffff65153ae in QWidget::clearFocus() () at /usr/lib/libQt5Widgets.so.5
```


@ZeldaZach #2583 ?

Add `if (sayEdit)`

**Comment by Daenyth** [comment]
Have I mentioned lately how much I loath our replay system

**Comment by skwerlman** [comment]
off-topic, but how _does_ the replay system work?

**Comment by Daenyth** [comment]
All of the GameEvent protocol messages get stored as a big array. The client basically loads up a non-interactive in-game UI and plays the messages forwards. This design choice is why we can't currently do seeking, only reset and forward. I have ideas for how to improve the cockatrice side while keeping the wire format the same, but the cockatrice code is not in great shape so making wide changes like that is hard
