### ISSUE TITLE
[sideboarding] double clicking a card should swap between main+side

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2594]
<b>OS:</b>
Win 10

<b>Cockatrice version:</b>
dc6c375 (2017-04-15)

__________

Once you join a game room, loaded a deck and unlock your sideboard between games to sideboard...

You need to drag and drop cards to make them change zones, which is not ideal. I would like to be able to double click cards to swap them to the sideboad and vice versa.

**Comment by ZeldaZach** [comment]
Not a bad idea, I'll look into this at some pint
