### ISSUE TITLE
Tezzeret the Schemers first ability crashes Cockatrize?

### ISSUE THREAD

**Issue by mpalmujoki** [Cockatrice/Cockatrice#2598]
<b>OS:</b>
*Mac OS 10.12.4*

<b>Cockatrice version:</b>
*a8a4557 (2017-03-16*

__________

I've now thrice in a row crashed Cockatrice on my Mac by using the first ability of Tezzeret the Schemer, +1: Create a colorless artifact token named Etherium Cell with "{T}, Sacrifice this artifact: Add one mana of any color to your mana pool."

It seems to be very easily replicatable, just start a local game, open your deck, and put the planeswalker on the battlefield, right click the planeswalker and select the ability, and then boom, Cockatrice crashes. 

And on Windows the abilities don't even appear in the right click context menu. Wonder why.

**Comment by skwerlman** [comment]
This is a known (and fixed) issue.

Update your client to the latest version: https://github.com/Cockatrice/Cockatrice/releases/tag/2017-04-15-Release-2.3.16

**Comment by mpalmujoki** [comment]
Yes, should've checked first. Thanks for your quick reply!
