### ISSUE TITLE
Display card names on cards not having a picture bug

### ISSUE THREAD

**Issue by backendr** [Cockatrice/Cockatrice#2600]
If you have the setting mentioned in the title disabled and try to create a numbered token, it doesnt show the card name.

A time when you dod this is during EDH, you create a token with a number to show what you rolled.

It shows an image of a card back with nothing on it. I presume that its seeing the card back as an image and not showing the token name. I think this should be fixed.

**Comment by tritoch** [comment]
Which version of Cockatrice are you running?

**Comment by backendr** [comment]
master branch.

**Comment by backendr** [comment]
Example: Who plays first?

<img width="254" alt="screen shot 2017-04-20 at 12 22 03" src="https://cloud.githubusercontent.com/assets/26419373/25226128/1049f934-25c4-11e7-95f8-4cd291ec0dbe.png">

**Comment by Daenyth** [comment]
I think this ticket might be a dupe

**Comment by Daenyth** [comment]
Maybe not dupe but same root cause as #2023 I think - names not in the card db get card back now instead of the token color gradient

**Comment by ShrewMaster** [comment]
Yep, I've been having the same problem and it's annoying.
