### ISSUE TITLE
Add compile instructions for linux mint to wiki

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#2601]

**Comment by skwerlman** [comment]
these should be more or less the same as the ubuntu ones, ye?

**Comment by Daenyth** [comment]
I think mint has different packages. Someone needed help because he didn't
have websockets installed and I'm not sure what package has it

**Comment by Nightfirecat** [comment]
Based on #2607, this might not be unique to Mint.

**Comment by ctrlaltca** [comment]
Mint shares the package base of Ubuntu. The problem related to websockets was due to the old version of Qt available on the distro at that moment.
