### ISSUE TITLE
Spec mode chat

### ISSUE THREAD

**Issue by ZeldaZach** [Cockatrice/Cockatrice#2602]
Spectator mode should never disengage from chat

**Comment by tooomm** [comment]
We should in general never disengage from chat, no?
To make any in game communication as easy and fast as possible...

Just in case a modulator key like ctrl, alt, or shift is pressed move focus away to make keyboard shortcuts work? And move back right after...
Only thing that brakes is mostly ctrl+c and ctrl+v for copy and paste I guess? F-Shortcuts should also still work. There could be an exception for basic os shortcuts I guess.
