### ISSUE TITLE
Crashes when updating

### ISSUE THREAD

**Issue by DerMeisterXZ** [Cockatrice/Cockatrice#2603]
<b>macOS 10.12.3</b>

<b>dab7316 (2017-01-19)</b>

__________

I'm trying to update Cockatrice to prepare for the release of Amonkhet, but my client crashes every time I try to update. Does anyone have any solutions?

**Comment by ZeldaZach** [comment]
By "crash" do you mean when it says downloading and it finishes downloading the program closes, or do you get a crashlog? The program _should_ close and a new DMG file should be downloaded and begin opening in /tmp on your computer.

**Comment by DerMeisterXZ** [comment]
It never even get to the download screen. A blue bar fills up really quickly (like, less than a second, faster than I can even see what it is), then it just closes and then brings up a window that says "Cockatrice closed unexpectedly" and brings up a window with "ignore," "report," and "reopen" options.

**Comment by ZeldaZach** [comment]
Can you "report" and then copy/paste what you see on that screen here?

**Comment by DerMeisterXZ** [comment]
Manual update worked. Thanks for the assistance.
