### ISSUE TITLE
Travis: add qt5-websocket library

### ISSUE THREAD

**Issue by ctrlaltca** [Cockatrice/Cockatrice#2607]
Compilation under ubuntu is working, but servatrice is not able to use websockets:

https://travis-ci.org/Cockatrice/Cockatrice/jobs/222674938#L685

**Comment by ctrlaltca** [comment]
This can't be fixed at the moment. 
The most recent version of Ubuntu supported by Travis is 14.04 that ships Qt 5.2.1, but Qt introduced websocket support only since Qt 5.3.

**Comment by tooomm** [comment]
Can't we update/load/install the qt library manually instead using the bundled one with ubuntu?

**Comment by ctrlaltca** [comment]
By now we have a working package missing the websockets feature;
We could replace the Qt library bundled with ubuntu with another version, but we'll end up with a package including the websockets feature but unusable by most people, since they'll need to uninstall the "normal" qt version (and all the other software using it) and instal the exact Qt version we used when compiling.

**Comment by Daenyth** [comment]
I'm OK with not shipping servatrice on outdated distros

**Comment by ctrlaltca** [comment]
Servatrice will work, it's only the websocket bridge that won't be compiled in, so web clients won't be able to connect. No big deal.

**Comment by tooomm** [comment]
I was just speaking about the travis version. Tell travis to include it for our hosted files/releases.
We don't have to include it in our actual code... as you lined out it might even be actually better to not do so.

**Comment by ctrlaltca** [comment]
If we compile cockatrice based on a qt version on travis, the .deb package created by travis and uploaded to the release will have an hard dependency on the specific version of Qt that we compiled against.
We can't bundle the whole Qt inside our cockatrice package (the same way we do on osx), because that would most likely cause problems to all the other software using Qt and picking up library files from mixed qt versions.

**Comment by ctrlaltca** [comment]
Well, we could create packages like snaps: https://www.ubuntu.com/desktop/snappy
But that's probably a lot of work for a gui app.

**Comment by Daenyth** [comment]
> Servatrice will work, it's only the websocket bridge that won't be compiled in, so web clients won't be able to connect. No big deal.

That's what I meant. Do we have a cmake flag for this?

**Comment by ctrlaltca** [comment]
No cmake flag, the code is `#ifdef`ed out

**Comment by tooomm** [comment]
It's really a minor thing... don't worry. 👍
