### ISSUE TITLE
Using phase buttons removes focus from the chat

### ISSUE THREAD

**Issue by backendr** [Cockatrice/Cockatrice#2610]
#2604 removes focus from the text edit whenever changing a phases.
Players continually have to click on the text edit to regain focus to chat.

**Comment by tooomm** [comment]
Yep, either way... broken shortcuts on mac after sideboading (https://github.com/Cockatrice/Cockatrice/issues/2490) or annoying all players with focus stealing all the time... we have to find a proper solution here.

What about my proposal the other day? https://github.com/Cockatrice/Cockatrice/issues/2602#issuecomment-295459273

**Comment by Daenyth** [comment]
For now why don't we hide the "remove focus" action under an `#ifdef` for OSX just to reduce impact on other people until we figure out the right way to approach this

**Comment by tooomm** [comment]
Fixed in https://github.com/Cockatrice/Cockatrice/pull/2619

Happy chatting @backendr !
