### ISSUE TITLE
Disable join button if room is full

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2611]
Like mentioned here: https://github.com/Cockatrice/Cockatrice/pull/2605#issuecomment-295613868 (and connected to https://github.com/Cockatrice/Cockatrice/issues/2599)

Expand the "disable button" functionality regarding to the room status to the `Join` button as well.

cc: @ZeldaZach

**Comment by Daenyth** [comment]
@tooomm label your tickets :P

**Comment by skwerlman** [comment]
afaict, he's not a member of the repo (just a contributor), so he wouldn't have permission to do that

**Comment by Daenyth** [comment]
![screen shot 2017-04-21 at 8 35 57 am](https://cloud.githubusercontent.com/assets/14644/25277650/90edcf3a-266d-11e7-9f60-a482a7c1e97a.png)

Nope :P

**Comment by skwerlman** [comment]
Huh.
![2017-04-21-084503_711x60_scrot](https://cloud.githubusercontent.com/assets/6954107/25278025/15bd8236-266f-11e7-977b-6ede6b9f01fd.png)
