### ISSUE TITLE
prevent negative power from displaying

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2615]
All power values <0 should be displayed as 0.
But it's still important to know the real value, just don't display it.

There are many temporary and permanent effects (including -1/-1 counter now) around which adjust the power value. Also rules wise a creature can't deal negative damage etc.

For toughness I'm not sure though. Displaying a negative number catches your attention and reminds you that it might be dead. :)

**Comment by Nightfirecat** [comment]
If there's a good framework in place to apply this for Magic specifically, I wouldn't mind having it clamp negative values to 0 for display. (or just clamp the actual value itself), but if not, I'd rather leave it as-is. Given the table-top nature of Cockatrice, it seems to fit the style of players needing to understand that negative power values is equivalent to 0.

**Comment by tooomm** [comment]
I don't feel to strongly about this, just added it while I was writing another one anyway to hear about your opinions.

And yes... might interfere with other games. :/

**Comment by ZeldaZach** [comment]
There are MTG creatures with power -1, hence forth I'd rather not change this and leave it up to the people.

**Comment by Nightfirecat** [comment]
Now that you mention it, you're right. There's only a few, but you're right nonetheless: http://magiccards.info/query?q=pow%3C0&v=card&s=cname

**Comment by Daenyth** [comment]
I'd like to leave this as-is because it's not hard for people to know that -power = 0 damage, and it makes things easier to just use +1/+1 or -1/-1 actions, and do math based on them.

Cards *are* able to have negative power, so therefore we should display it
