### ISSUE TITLE
Set issue

### ISSUE THREAD

**Issue by lordbovine** [Cockatrice/Cockatrice#2616]
<b>OS: Win 10</b>

<b>Cockatrice version: dc6c375 (2017-04-15)</b>

__________
Cockatrice tells me it is currently up to date and stable, however I can not see cards from Commander 2016 to recent.

**Comment by Daenyth** [comment]
Have you run Oracle?

**Comment by tooomm** [comment]
The program itself (Cockatrice) and the Card Database are two different things.
If you update Cockatrice that won't change your card data, you have to run Oracle to get updates for the later...

**Comment by lordbovine** [comment]
Turns out my Oracle was corrupted so I had to fix that.

**Comment by tooomm** [comment]
How did that happen? And what happened exactly or how did the corruption show? How did you fix it?
