### ISSUE TITLE
Crashes when game replaying

### ISSUE THREAD

**Issue by fbroma** [Cockatrice/Cockatrice#2617]
<b>OS:</b>
10.11.6

<b>Cockatrice version:</b>
Version dc6c375 (2017-04-15)

__________

Crashes every time I try to watch a replay. This is a known issue with previous versions. I created tickets for the same issue. Why is this happening again?

**Comment by tooomm** [comment]
This is fixed already. See https://github.com/Cockatrice/Cockatrice/issues/2593
It will be in the next main release.

There is no development version available with that fix yet. @ZeldaZach ?

**Comment by Daenyth** [comment]
We can put out a development snapshot today
