### ISSUE TITLE
resize problem at replay load

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2621]
<b>OS:</b>
Windows 10 on 1366x786

<b>Cockatrice version:</b>
Version 2.3.17-custom_f24105b (2017-04-21)

----

Normal full screen view of `Main chat`, before going to the `Game replays` tab
![before-replaywatch](https://cloud.githubusercontent.com/assets/9874850/25289720/203086d0-26cb-11e7-83a5-175f1f9029c6.png)

Once you load a replay with double click or the watch button it gets loaded and opens.
But it changes the former full screen of the app and makes it expand more to the bottom which actually hides some UI information - here the `Replay Timeline`:
![replaywatch](https://cloud.githubusercontent.com/assets/9874850/25289730/284923b8-26cb-11e7-83f7-0d7e83db20d7.png)

But all app is now resized as well, so if you go back to `Main chat` you'll get this:
![after_replaywatch](https://cloud.githubusercontent.com/assets/9874850/25289734/29da7006-26cb-11e7-9517-ff32897cd971.png)

All the dark lines you see on the bottom of the pictures is part of my taskbar which I didn't include into the screenshot.

**Comment by ebbit1q** [comment]
I merged these tickets into https://github.com/Cockatrice/Cockatrice/issues/4114
