### ISSUE TITLE
Create new sub-repo for spoiler

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2622]
To host @tritoch 's spoiler code and the resulting .xml for easy distribution.

I suggest using `Magic-Spoiler`, based on "Magic-Token"!

**Comment by ZeldaZach** [comment]
`Cocker-Spoiler` (Play on Cocker Spaniel) 😛

**Comment by Daenyth** [comment]
Please no

**Comment by tritoch** [comment]
Did a bunch of cleanup on https://github.com/tritoch/SpoilerSeason and have Travis-CI generating the files to the files branch https://github.com/tritoch/SpoilerSeason/tree/files

**Comment by Daenyth** [comment]
I don't think you mean to store the generated files in the repo - those are usually better as a release download. Can you adjust that?

**Comment by tritoch** [comment]
>  Can you adjust that so the autogenerated files are on releases

Yes.  But I think I also like the branch files as it shows a nice diff and generates automatically without intervention.

**Comment by tooomm** [comment]
It should also work automatically for gh releases.
But the problem is that we found no easy solution to see the actual changes made in the output file in comparison to a former run - for example a change could be because new cards are spoiled or there was a code change in the script. You somehow need to automatically keep track of the output result, or at least visualize it that you can check it manually (like with a diff).

In general i like gh releases approach... if we find a way to deal with that problem.

Do you have an idea here @Daenyth ?

**Comment by tritoch** [comment]
It's now configured to do both Releases and write files to branch. I don't see any real advantage to using releases other than some API functionality.  Tokens repo doesn't use releases.

**Comment by skwerlman** [comment]
The main advantage to releases is that it is possible to enumerate the files in the release via the api, which is useful here since the names of the files to be downloaded will change over time.

**Comment by Daenyth** [comment]
It's also useful if anyone wants to make an installable package out of the repo

**Comment by Psithief** [comment]
> Tokens repo doesn't use releases.

Well, we do now. For full releases though, not spoiler season.

**Comment by tooomm** [comment]
--> https://github.com/Cockatrice/Magic-Spoiler/
