### ISSUE TITLE
Remove whitespace from filenames

### ISSUE THREAD

**Issue by backendr** [Cockatrice/Cockatrice#2623]
It is currently possible to save a deck name as `xxxx .cod`.

How to reproduce:
+ In deck tab enter a deck name with some whitespace at the end
+ Save deck to finder window or the OS equivalent.
+ Save deck

Saved deck will contain the whitespace.

**Comment by ZeldaZach** [comment]
Any reason this is a problem? Maybe change whitespace to underscores.

**Comment by Daenyth** [comment]
Trimming the ends makes sense. I don't see a problem with having them in the middle of the file though

**Comment by tooomm** [comment]
On windows, I can create any kind of file with whitespaces everywhere (except at the start).

**Comment by ctrlaltca** [comment]
When i create a new deck and save it, the save file dialog will propose the filename "<deck name>.cod", where <deck name> is the text i wrote in the "deck name" field in the deck editor.
If i get this correctly, the idea is to propose by default "<trimmed deck name>.cod" instead, this is a trivial change that somewhat makes the client better by providing a more sane default behavior.
Of course the user must still be in control of the filename, eg. if he want to put a trailing space or a U+1F4A9 character, i see no point in blocking him.

**Comment by backendr** [comment]
If you set the deck name to "xyz     " and save, the save dlg will use the same "xyz     ".
My idea is to remove trailing and proceeding whitspace in the dlg.

**Comment by Nightfirecat** [comment]
Why though? That behavior is consistent with every other program&mdash;if you add a space to the filename, the file would be saved with a space.
