### ISSUE TITLE
'Aftermath' cards not being combined by Oracle

### ISSUE THREAD

**Issue by tritoch** [Cockatrice/Cockatrice#2625]
The new card type in Amonkhet 'Aftermath' ([Start // Finish](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=426917&part=Start)) is not combined by Oracle.  MTGJSON has given them the layout type `aftermath`.

**Comment by tooomm** [comment]
for your example link:
http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=426917&part=Start
removing the last part returns the same:
http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=426917
<br>

>MTGJSON has given them the layout type aftermath.

Are you sure? There is a new special type?
I just found out that they are implemented as single cards (unlike former split cards!) and have a <related> tag in cards.xml... but the second "part" isn't relate-linked back to the first..

       <card>
            <name>Heaven</name>
            <set rarity="Rare" muId="426926" num="224a">AKH</set>
            <color>G</color>
            <related>Earth</related>
            <manacost>XG</manacost>
            <cmc>1</cmc>
            <type>Instant</type>
            <tablerow>3</tablerow>
            <text>Heaven deals X damage to each creature with flying.</text>
        </card>

        <card>
            <name>Earth</name>
            <set rarity="Rare" muId="426926" num="224b">AKH</set>
            <color>R</color>
            <related></related>
            <manacost>XRR</manacost>
            <cmc>2</cmc>
            <type>Sorcery</type>
            <tablerow>3</tablerow>
            <text>Aftermath (Cast this spell only from your graveyard. Then exile it.)
             Earth deals X damage to each creature without flying.</text>
         </card>

**Comment by tritoch** [comment]
>removing the last part returns the same:

Same as traditional `split` cards.

>Are you sure? There is a new special type?

http://mtgjson.com/json/AKH.json

```{"artist":"Magali Villeneuve","cmc":3,"colorIdentity":["W"],"colors":["White"],"id":"f25b27b0d1a4dee219143e95be041088f1faabe5","imageName":"start","layout":"aftermath","manaCost":"{2}{W}","multiverseid":426917,"name":"Start","names":["Start","Finish"],"number":"215a","rarity":"Uncommon","text":"Create two 1/1 white Warrior creature tokens with vigilance.","type":"Instant","types":["Instant"]},{"artist":"Magali Villeneuve","cmc":3,"colorIdentity":["B"],"colors":["Black"],"id":"cc499752c22f6f64bbeda03342d94ce9ebdfc5ad","imageName":"finish","layout":"aftermath","manaCost":"{2}{B}","multiverseid":426917,"name":"Finish","names":["Start","Finish"],"number":"215b","rarity":"Uncommon","text":"Aftermath (Cast this spell only from your graveyard. Then exile it.)\nAs an additional cost to cast Finish, sacrifice a creature.\nDestroy target creature.","type":"Sorcery","types":["Sorcery"]}```

>I just found out that they are implemented as single cards (unlike former split cards!) and have a tag in cards.xml... but the second "part" isn't relate-linked back to the first..

Because Oracle isn't handling them currently.

**Comment by tooomm** [comment]
>http://mtgjson.com/json/AKH.json

Oh cool, I looked at http://mtgjson.com/sets.html but it's not yet linked there!

>Because Oracle isn't handling them currently.

Yeah sure, hence your ticket... nobody teached Oracle yet how to do it. 👍 
I just showed the current result as example.

**Comment by Daenyth** [comment]
Fixed now?

**Comment by tooomm** [comment]
Yes. Working for me!

> 
     <card>
            <name>Heaven // Earth</name>
            <set rarity="" muId="426926" num="224a">AKH</set>
            <color>G</color>
            <color>R</color>
            <manacost>XG // XRR</manacost>
            <cmc>1 // 2</cmc>
            <type>Instant // Sorcery</type>
            <tablerow>3</tablerow>
            <text>Heaven deals X damage to each creature with flying.



             Aftermath (Cast this spell only from your graveyard. Then exile it.)
             Earth deals X damage to each creature without flying.</text>
      </card>
