### ISSUE TITLE
rework contributing.md - should be more useful to normal users and issue creators

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2628]
Regarding to @backendr we should rework our contributing.md file to provide more info to new developers about used practices, style and conventions.

Positive examples:
https://docs.docker.com/opensource/workflow/make-a-contribution/
https://github.com/moby/moby/blob/master/CONTRIBUTING.md#quick-contribution-tips-and-guidelines

**Comment by tooomm** [comment]
I want to add that the contributing guidelines are also automatically linked when you create an issue.

But they are not useful for the ordinary user at the moment and confuse them instead.
I suggest to also add a "User" related part on the top, above the "Developer" related things.

**Comment by ZeldaZach** [comment]
Our friend @ebbit1q just did this :)
