### ISSUE TITLE
Ctrl + left-click on a card should make its name appear in the chat

### ISSUE THREAD

**Issue by ShrewMaster** [Cockatrice/Cockatrice#2629]
This was a feature previously present on Magic Workstation, an old software in which I used to play Magic, and it was very useful for targeting and naming cards. I think this even worked for players (you clicked on the avatar of a player and its name appeared in the chat). Where I believe this feature would be mostly useful is when targeting multiple cards (instead of having to drag an arrow several times) and searching an opponent's library. Because we can no longer drag cards from an opponent's library to the field like we used to, if we need to choose several cards because of an effect, it gets both easier and faster for us to tell that opponent what cards we are choosing.

**Comment by tooomm** [comment]
We have `[[cardname]]`. Just type it in chat.
But I agree that it's not great and your suggestion would be a very sweet addition! 👍 

>Because we can no longer drag cards from an opponent's library to the field like we used to

This was a feature once? When? First time I hear about that. :)

**Comment by ShrewMaster** [comment]
Yes, we could do that back in the primordial days of Cockatrice when Brukie was still developing Cockatrice. But it appears to have been lost between development along the way.

**Comment by tooomm** [comment]
Didn't know that... but sounds not bad.
Clicking cards might even be better and easier!

**Comment by ShrewMaster** [comment]
That's what I figured exactly :) I don't understand programming language, but I would guess this suggestion would be easier to implement while still being very useful.

**Comment by Daenyth** [comment]
Yes, it's a known regression. The problem was that the steal from library feature also allowed you to see every card your opponent drew by keeping the window open.
#625
I have a plan for how to fix it but no time for it since it's rather involved

**Comment by ZeldaZach** [comment]
@Daenyth Write up a proposal maybe?

**Comment by Daenyth** [comment]
Already did https://github.com/Cockatrice/Cockatrice/issues/625#issuecomment-206470099

**Comment by tooomm** [comment]
Note that @ShrewMaster also said that you could drag cards to the chat to send their names!
