### ISSUE TITLE
Watching replays crashes the program in the most recent version

### ISSUE THREAD

**Issue by ShrewMaster** [Cockatrice/Cockatrice#2631]
<b>OS:</b>
*Windows 7 Home Premium*

<b>Cockatrice version:</b>
*Cockatrice Thopter Pie Revision 2*

__________

*Replays are crashing the program shortly after being opened.*

**Comment by tooomm** [comment]
Check https://github.com/Cockatrice/Cockatrice/issues/2617 for information and https://github.com/Cockatrice/Cockatrice/releases for the download mentioned in 2617.

Enjoy! :)
