### ISSUE TITLE
Missing possibility to quickly clear the card search field

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2632]
I like to see a little button within the search bar (or right next to it) which clears the search immediately on hit.
![clearsearch](https://cloud.githubusercontent.com/assets/9874850/25334863/ce4a4090-28f0-11e7-85d7-fd44ad0d19cc.png)

Hitting the delete key should also do the same!

**Comment by Daenyth** [comment]
Delete or backspace definitely shouldn't clear the entire search. A button is reasonable though

**Comment by tooomm** [comment]
>Delete or backspace definitely shouldn't clear the entire search. A button is reasonable though

Good point about `Delete`. I forgot that you could want to erase characters to the right...
