### ISSUE TITLE
Turns ending/someone going to end step stops chatting

### ISSUE THREAD

**Issue by LethalPigeon7** [Cockatrice/Cockatrice#2637]
<b>OS:</b>W7 SP1
<b>Cockatrice version:</b>dc6c375 (2017-04-15)

Whenever the end step is entered, or the turn is passed, the game "clicks away" from chat, so anything I type isn't input. This makes using cockatrice a massive pain, I have to reclick and retype half of what I was typing before proceeding, slowing things down to a halt. Using tab doesn't really help, because it cuts me off in the middle of typing a word so there's always something to fix.

**Comment by ctrlaltca** [comment]
Known problem, we already reverted the problematic code and the latest version is not affected.
