### ISSUE TITLE
grey out not useful options in right click menu

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2640]
Same like `Create another token`...
If there are no single Token cards in your Deck, grey out the `Create predefined token` entry, since it won't show anything anyway.
![predef_token](https://cloud.githubusercontent.com/assets/9874850/25349536/7b2d8480-2922-11e7-8d78-181f18a499c7.png)

Same for `Say` by the way. If there are no macros set up --> grey out.

**Comment by ZeldaZach** [comment]
Also, notice that "Card" thing? It appears everywhere in a long list, especially if you look at Game -> Name

**Comment by ZeldaZach** [comment]
Also, notice that "Card" thing? It appears everywhere in a long list, especially if you look at Game -> Name

**Comment by tooomm** [comment]
>Also, notice that "Card" thing? It appears everywhere in a long list, especially if you look at Game -> Name

Hahaha. Just asked in gitter the same... 😆

**Comment by ZeldaZach** [comment]
Not sure why I closed the fix for this... We'll reimpl
