### ISSUE TITLE
Missing game filter options

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2642]
- Show available games
- Show games which do not allow spectators

In case you are looking to just spectate games the last one would be pretty handy.
The first one though, in combination with "Show unavailable games" would allow to just show unavailable games solely because you could disable available games.

Default should be to show available games and non-spectator games for sure.

**Comment by Daenyth** [comment]
I'm thinking maybe we should kill unavailable and just have toggles for the
options it represents

**Comment by tooomm** [comment]
Can you explain a bit more?

But yes, I need to think about the wording twice to make exactly sure all needed/wanted cases are working. Combining things under toggles might be easier to understand and use since you just have less check boxes to deal with.

**Comment by Daenyth** [comment]
- Show full games
- Show games with passwords
- Show games for registered users only
- Show buddy only games

**Comment by tooomm** [comment]
Your comment confuses me a bit @Daenyth. :)

While it would be nice to have the `registered user` option, this issue is about having filters to
- find `games for spectators` and
- to show `unavailable games` (or full games) only

Right now you can just decide of you want to display full games additionally, but you can't hide available games. Something which you want in case you want to spectate a running match and you don't need to see all this games which are waiting for players to join.

**Comment by ZeldaZach** [comment]
Show full games
    Show games with passwords
    Show games for registered users only
    Show buddy only games

I can probably look into those changes @Daenyth 
Seems straight forward to me. Will also add  `Show games that allow spectators`

**Comment by Daenyth** [comment]
@tooomm I didn't explain myself clearly, I was talking about removing the "Show unavailable games" option because it is confusing and instead replacing it with a switch for everything it does.

**Comment by tooomm** [comment]
Oh right, so you extended my idea.

So we have something like this in the end? (wording could need some work)

```
not full games --> "Show games with places left"
full games --> "Show full games"
with pw --> "Show games with password protection"
reg only --> "Show games for registered users only"
buddy only --> "Show buddy only games"
allow spec --> "Show games that allow spectators"
```

**Comment by tooomm** [comment]
https://github.com/Cockatrice/Cockatrice/issues/628 also requests a switch to separate and show reg/unreg games individually.

So it needs to be:
games for reg only --> "Show games for registered users only"
games for unreg only --> "Show games for unregistered users"
(otherwise you can't only display reg games... because unreg games would always show up)

I hope I got it right... this is quite confusing. 😕

**Comment by ZeldaZach** [comment]
Dupe #2431
