### ISSUE TITLE
Card on top of deck now appears blank instead of showing card back

### ISSUE THREAD

**Issue by ShrewMaster** [Cockatrice/Cockatrice#2643]
<b>OS:</b>
*Windows 7 Home Premium*

<b>Cockatrice version:</b>
*2017-04-25-Development-2.3.17-beta002*

__________

*So I've tested the most recent developmental release. All seems well, but arising from resolving issues #2600 / #2638 , now the top card of everyone's decks appears blank instead of showing the determined image for card back. I tested this in other situations, such as tokens and putting cards face-down on the table, but it appears to only have affected the top card of players' decks.*

**Comment by skwerlman** [comment]
Probably related to #2638

**Comment by tooomm** [comment]
Jep, run into the same regression. I guess it's related to https://github.com/Cockatrice/Cockatrice/pull/2638

cc: @ctrlaltca
