### ISSUE TITLE
Changing phases interrupts typing in the room chat

### ISSUE THREAD

**Issue by Varsav** [Cockatrice/Cockatrice#2644]
<b>Windows</b>
*Windows 10*

<b>Version dc6c375 (2017-04-15)</b>

__________

*When in a game if I am typing in the room chat box and the phase changes for any reason my typing is interrupted.  I then have to click on the chat box again to continue typing. repeatable issue 100% of the time.

**Comment by ctrlaltca** [comment]
Known problem, we already reverted the problematic code and the latest version is not affected: https://github.com/Cockatrice/Cockatrice/releases/tag/2017-04-25-Development-2.3.17-beta002

**Comment by tooomm** [comment]
Sorry for that, we changed it already... until there is a new main release available you might want to switch your client to download `Development snapshots` in the settings!

Happy updating
