### ISSUE TITLE
Osx: investigate usability of Qt versions after 5.7

### ISSUE THREAD

**Issue by ctrlaltca** [Cockatrice/Cockatrice#2647]
<b>OS:</b>
macOS

<b>Cockatrice version:</b>
Any

Some new issues arose when our macOS packages started bundling Qt5.8.
This happened quite transparently to us, since out packages are built on Travis and install Qt from homebrew. When homebrew updated to Qt5.7, we started using it.
When we noticed that Qt5.8 was the cause of such problems, we forced the use of the last known working Qt5.7 (see commits 7f057612bf575422c55d050ea88bd49c71c37f16 and 38ad71b06a55fd8915c589bf07bf498cc71767a9)

This issue is a collector for all issues related to macOS and Qt5.8 that needs to be checked before trying to update the Qt version we use in the future:

 * #2527 Crashes on QNetworkManager
 * #2490 Keybinds disabled after sideboard

**Comment by skwerlman** [comment]
Weirdly, I don't experience any of those issues on Arch Linux with Qt5.8... Maybe its an issue with brew's specific build of Qt5.8?

**Comment by ctrlaltca** [comment]
@skwerlman: MacOS only

**Comment by ctrlaltca** [comment]
Just tested Qt 5.9.1 for bug #2490 (keyboards shortcuts after sideboard), and it's still broken :(
I'km afraid we'll have to workaround it

**Comment by ZeldaZach** [comment]
Sounds like we'll be sticking with 5.7.1 for a while...

**Comment by tooomm** [comment]
Did somebody retest with the recent Qt 5.10 yet?
Too bad that Qt 5.9 LTS has the same issues still according to @ctrlaltca.

**Comment by tooomm** [comment]
Is there an issue at Qt for this? Are they aware of the problem?

**Comment by tooomm** [comment]
`qt@5.7` is discontinued at homebrew: https://github.com/Homebrew/homebrew-core/pull/23165#issuecomment-362270835

We have to either use `qt@5.5` for now as a temporary solution, or look into Qt 5.10 with this issues.

**Comment by NickBeeuwsaert** [comment]
For #2490, it looks like the problem isn't caused by side-boarding, but just opening a dialog will cause all sub-menu item shortcuts in the game menu to stop working (but shortcuts like for Next Turn will still be available). I can put together a minimum working example if anyone wants to look at it / see if they can find a workaround

**Comment by Daenyth** [comment]
That would be helpful

**Comment by NickBeeuwsaert** [comment]
Alright here you go:

```
#include <QtWidgets/QApplication>
#include <QtWidgets/QLCDNumber>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QMessageBox>

int main(int argc, char* argv[]) {
    QApplication app(argc, argv);

    QMainWindow window;
    QLCDNumber counter;
    window.setCentralWidget(&counter);

    auto menuBar = window.menuBar();
    QMenu menu("Menu", menuBar), submenu("SubMenu", &menu);

    QAction incrementMenuItem("Increment counter", &menu), incrementSubMenuItem("Increment counter (From Submenu)", &submenu),
        showDialog("Show Dialog", &menu);

    incrementMenuItem.setShortcut(QKeySequence(Qt::CTRL + Qt::Key_A));
    incrementSubMenuItem.setShortcut(QKeySequence(Qt::CTRL + Qt::Key_S));
    showDialog.setShortcut(QKeySequence(Qt::CTRL + Qt::Key_D));

    QObject::connect(&showDialog, &QAction::triggered, [&]() {
        QMessageBox::information(&window, "Hello, world!", "Increment counter from submenu will no longer work");
    });
    auto increment = [&]() { counter.display(counter.intValue() + 1); };
    QObject::connect(&incrementMenuItem, &QAction::triggered, increment);
    QObject::connect(&incrementSubMenuItem, &QAction::triggered, increment);
    
    submenu.addAction(&incrementSubMenuItem);
    menu.addActions(QList<QAction*>() << &incrementMenuItem << &showDialog << submenu.menuAction());
    menuBar->addAction(menu.menuAction());

    // Potential work-around: add actions to widget as well as menu
    // counter.addActions(QList<QAction*>() << &incrementMenuItem << &incrementSubMenuItem);

    window.show();
    return app.exec();
}

```

**Comment by ctrlaltca** [comment]
Confirmed working on the homebrew version.
Btw the homebrew version is affected some of the bugs fixed in #3216, and is somewhat wrongly marked as depending on the qt formula, even if libraries are bundled inside the applications.

**Comment by tooomm** [comment]
>Btw the homebrew version (...) is somewhat wrongly marked as depending on the qt formula, even if libraries are bundled inside the applications.

Hmm, no idea. Could you possible provide a patch for the formula file [here](https://github.com/Homebrew/homebrew-core/blob/master/Formula/cockatrice.rb) then?

**Comment by ctrlaltca** [comment]
The last time i saw an app formula proposed, it was discarded since homebrew didn't accept GUI apps (i think they created caskroom for those apps). I don't get why a formula is there at all, but i dont' want to be the bad guy that points out the problems and gets the formula removed, so... 🙈 🙉 🙊

**Comment by tooomm** [comment]
That sounds weird... but I've no idea to be honest.
Cockatrice was added as a game by some guy in 2015: https://github.com/Homebrew/homebrew-core/pull/23117#issuecomment-359250694
And games without gui are not too common. :)

([homebrew-games](https://github.com/Homebrew/homebrew-games) is deprecated and got merged into core)

**Comment by ctrlaltca** [comment]
> (homebrew-games is deprecated and got merged into core)

Ok, i missed that step, thank you 👍

**Comment by tooomm** [comment]
Can this issue be closed btw @ctrlaltca?
We should be using 5.10.1 from homebrew by now.
[qt@homebrew](http://formulae.brew.sh/formula/qt) --> [brew install qt](https://github.com/Cockatrice/Cockatrice/blob/master/.ci/travis-dependencies.sh#L5)

**Comment by ctrlaltca** [comment]
Yep!
