### ISSUE TITLE
Issue with ' Create tokend' dialog changes in #2646

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2651]
- If there are no tokens in your deck hitting `Show tokens from this deck` just shows you all tokens that exist within Cockatrice (mirrors first option), maybe falsely introduced in https://github.com/Cockatrice/Cockatrice/pull/2646
**--> option should be grayed out at all, if there are no token in your deck**

- The column state isn't saved and always reverting to default
So you end up with a truncated list every time you open create token. If you try to adjust that and make the columns wider (especially when you resize the window as well - which is saved) that's not helping. :)
![untitled](https://cloud.githubusercontent.com/assets/9874850/25403393/7705579a-29fc-11e7-812a-9e6c48f5c6fe.png)

- The token preview window always shows a card back as long as there is no art loaded or available.
But if you want to create a custom token and you use the colored backgrounds or an annotation and name that should be previewed correctly, too!
<br>

By the way: #2044 didn't request to change the initial behaviour of `Show all tokens`. I don't like that new version, but I guess it was the easier approach to change the other one? ;)

cc: @ctrlaltca

**Comment by ZeldaZach** [comment]
So i have a question on this: If I have Lingering Souls in my deck, for example, should the "Show tokens from deck" auto-populate with "1/1 Spirit" OR should we rely on the user to add the token in the Deck Editor themselves and only show it if they added it.

**Comment by tooomm** [comment]
Interesting idea to auto-populate. But that might trigger some errors or introduce other problems.
So I would leave it as is. Generally you don't need to add tokens to your deck at all because the simplest way to create them is with a right click... but it's an option if somebody prefers that or wants to use the create predefined token option.

**Comment by ZeldaZach** [comment]
Sounds good to me, I"ll go forward with the change I planned then.

**Comment by Daenyth** [comment]
We should auto populate - that's a really good idea and it would make the feature *actually useful*

**Comment by tooomm** [comment]
But we still want the opportunity to manually add them to decks?
- support old decks with tokens as people are used to
- let people easily fix tokens if they are not auto populated for whatever reason

**Comment by ZeldaZach** [comment]
Dupe of #3909
