### ISSUE TITLE
Chat input element in game constantly looses focus when step/phase changes

### ISSUE THREAD

**Issue by MopDa** [Cockatrice/Cockatrice#2653]
<b>OS:</b>
Windows Server 2008 R2 Enterprise

<b>Cockatrice version:</b>
dc6c375(2017-04-15)

__________

Since I believe last update every time phase/step changes, chat input element in game loses focus. Not critical, but annoying as hell. Slows the game down, as I then prefer to type messages during my turn, instead of making my game actions or got to check if focus is still there during opponents' turn instead of keeping an eye on a game state while typing

**Comment by ctrlaltca** [comment]
Known problem, we already reverted the problematic code and the latest version is not affected: https://github.com/Cockatrice/Cockatrice/releases/tag/2017-04-25-Development-2.3.17-beta003

**Comment by tooomm** [comment]
You can also change the `Release channel` in your ingame settings.
Cockatrice is then able to download these development releases right from within the client if you check for updates! (help --> check for updates)
