### ISSUE TITLE
deleting card problem if attached

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2658]
<b>OS:</b>
Win 10

<b>Cockatrice version:</b>
Version 2.3.17-beta003 (2017-04-25)

__________

If you attach a card to another there are some bad interactions with deleting cards.
While the host card which your other card is attached to is destroyed, exiled, blinked... (manually moved to another zone) the attached card is unattached and placed in card row 2. So far so good.

But if you select both cards (host+attached card) and want to delete them or drag both of them simultaneously to the graveyard for example just the host is properly moved and the attached card isn't! Even if you selected them as well.
While this is helpful for equipments for example - it's bad for creature enchantments.

So just make this work as intended and apply all actions to all selected cards, no matter of their attached state. Cleans and speeds things up. 👍 

**It actually looks that you can't interact with attached cards! You can't move them at all.
For example your land enchantment gets exiled. You have to unattach it first to move it to exile!**

**Comment by ZeldaZach** [comment]
This is intended design imo
