### ISSUE TITLE
no first level entry for basic card action "destroy" (--> move to gy)

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2660]
If you right click on a card you should be easily able to select "destroy" since it's the most default action with removing a card. Maybe next to `Clone` ?
Should do the same as "move to graveyard", also shares the same keyboard shortcut.

Not sure we need the same for exile. Might be to specific and it isn't used as often.

**Comment by ZeldaZach** [comment]
I agree, no need for a second option

**Comment by tooomm** [comment]
Yes, that was actually the idea. :)

>I don't see a purpose for having two menu entries named differently that do the same thing.

I realized that playing on a laptop can be a pain with the touchpad, so dragging things around isn't easy at all and leads to some weird misplays and moving around of things that you don't want to move. 

What is the most used interation with a card?
Yes, it's double clicking it to play it and tap it once in the game.
What else do you do with cards?
You destroy them...
Everything else might happen, but don't have to. Like counters etc. More or less every card is going to be destroyed at one point.

So we have like the second most used interaction with cards hidden into a sub menu of the right click menu. Remember how much people complained when we hide the counters into a sub-menu? It's the same here basically.

Why I suggest to duplicate it?
I don't want to replace the structured sub menu to leave it consistent with menus for other zones.
Also the different name is short and maybe of some help for players.

My cents. :)

**Comment by tritoch** [comment]
>Why I suggest to duplicate it?
I don't want to replace the structured sub menu to leave it consistent with menus for other zones.
Also the different name is short and maybe of some help for players.

To further this point, `Move to` is available in zones that do not involve destruction (stack, hand, library, graveyard), so `Destroy` would be a battlefield-only option.

**Comment by Daenyth** [comment]
I think you should set a keybind for this action. If you can't, please ticket making it bindable.

**Comment by tooomm** [comment]
It's possible, sure and it helps. Still... hotkeys, besides the very basic ones, are not very well known and not used all the time.
Also not everybody likes them. Especially more casual player might prefer to use the mouse. On a laptop they have the same problem again. 

Maybe you can't comprehend because you have a great mac touchpad? :P
But hey, I'm also struggeling with a Thinkpad trackpoint here. ;D

**Comment by tritoch** [comment]
>I think you should set a keybind for this action.

Keybinds exist for creating tokens, adding counters, and other options that have been added/re-worked in the card menu.

**Comment by tooomm** [comment]
@tritoch it also exists for this one. You need to look for "move to --> graveyard" though.
Default is Ctrl+Delete
