### ISSUE TITLE
right click into nowhere shows menu options of selected card

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2662]
<b>OS:</b>
Win 10

<b>Cockatrice version:</b>
Cockatrice-2.3.17-custom_9e5ca1b-x86_64_qt5.exe

__________

I don't think this is any helpful. Is this really intentional or can be called a feature!? :)
![card option in rightclick](https://cloud.githubusercontent.com/assets/9874850/25437054/6c82235e-2a95-11e7-8808-1449fbc6818d.png)

Hard to imagine people use that or get not confused by it. All computer users are used to a right click menu related to the item they click on. Not what they select in a different spot....

Since we have some problems with that on mac too, see: https://github.com/Cockatrice/Cockatrice/pull/2655#issuecomment-297513934
Just remove the `Card` entry from the right click and `Game --> Player` menu? Maybe there is some use for it on the player menu, but for the right click I doubt that.

**Comment by Daenyth** [comment]
I think that right click menu is actually the exact same thing as the global menu - it's one thing being displayed in two places.

I'd prefer to keep it, just maybe rename "Card" to "Selected card"

**Comment by tooomm** [comment]
A rename helps understand what it's actually about. 👍 

May I ask why you prefer to keep it? It would be surprising if *anyone* uses the right click option... serious.
In the end it just clutters the client and the UI/UX imo.

**Comment by Daenyth** [comment]
If keeping it costs us little and lets us be more consistent I like it.

I really like that I can tell new people "Everything you can do in the app
you can do from the Game menu"

**Comment by ZeldaZach** [comment]
Super easy. Just rename "Card" to "Selected Cards" and we're good!
