### ISSUE TITLE
Putting cards X from the top of the library shortcut

### ISSUE THREAD

**Issue by ForPsionics** [Cockatrice/Cockatrice#2665]
<b>OS:</b>
macOS 10.12.3

<b>Cockatrice version:</b>
Version dab7316

__________

I would like there to be a shortcut in a game to put a card X cards from the top of the library. Due to the new cards Commit // Memory and Approach of the second sun, along with older cards like Unexpectedly Absent, it is very tedious to put facedown the cards from the top of the library one at a time. I would like to request an option where the card can be placed X cards from the top of the deck.

**Comment by ZeldaZach** [comment]
Seems like this is really wanted, so I'll probably try figuring this out soon
