### ISSUE TITLE
Changing phases stops selecting text box in game

### ISSUE THREAD

**Issue by UnwiseDragon** [Cockatrice/Cockatrice#2667]
<b>OS:</b>
Windows 10

<b>Cockatrice version:</b>
Version dc6c375 (2017-04-15)

__________

In game trying to type in chat, the chat box becomes de-selected every time a phase changes or a player clicks pass even if I am in the process of typing. This is true regardless of which player changes phase. I was playing 1v1. If this is a feature it's a pretty annoying feature.

**Comment by ctrlaltca** [comment]
Known problem, we already reverted the problematic code and the latest development version is not affected: https://github.com/Cockatrice/Cockatrice/releases/tag/2017-04-27-Development-2.3.17-beta004

**Comment by tooomm** [comment]
Thanks for reporting.

You can also change the release channel in your ingame settings.
Cockatrice is then able to download these development releases right from within the client if you check for updates! (help --> check for updates)
