### ISSUE TITLE
Pictures not loading (fixed by restart)

### ISSUE THREAD

**Issue by LethalPigeon7** [Cockatrice/Cockatrice#2669]
<b>OS:</b> W7 SP1
<b>Cockatrice version:</b> dc6c375 (2017-04-15)
More importantly the debug log was [interesting](https://imgur.com/a/MQIbD).

**Comment by ctrlaltca** [comment]
Hopefully the problem in the log is already fixed by #2659. Can you please try to test development version https://github.com/Cockatrice/Cockatrice/releases/tag/2017-04-27-Development-2.3.17-beta004 ?

**Comment by LethalPigeon7** [comment]
Well it wasn't an ongoing problem even on the stable version, just an occasional occurrence, so I can't tell right away. I'll reopen this if the problem returns, I made the ticket just so this was acknowledged, most likely fixed by linked fix.

**Comment by ZeldaZach** [comment]
If this is still a problem, let us know
