### ISSUE TITLE
Document "messages" functionality

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#267]
It allows users to create chat message shortcuts for use inside a game.

**Comment by leematos** [comment]
This is pretty easy to do, but I'm concerned with preference pane height? Is there a max that we consider?

**Comment by Daenyth** [comment]
We can always add scroll areas and extra tabs.

**Comment by tooomm** [comment]
In combination with #1380, a good improvement of the macro functionality :+1:
