### ISSUE TITLE
change the updater to prepare for a file name fix

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2671]
As discussed here: https://github.com/Cockatrice/Cockatrice/pull/2661#issuecomment-297784132

Right now we automatically create and upload these file names on appveyor:
`Cockatrice-2.3.17-beta003-x86_64_qt5.exe`
`Cockatrice-2.3.17-beta003-x86_qt5.exe` 
Nonetheless we manually upload the same files to our main releases with these names:
`Cockatrice_Thopter_Pie_Network_Revision2_win64.exe`
`Cockatrice_Thopter_Pie_Network_Revision2_win32.exe`

The issues with this are:
- We use different names for the same architecture
In order to fix this we need to change the file name pattern created from appveyor.
It should also be in sync with what we upload manually to our releases!
- The `qt5` tag is no longer needed and should be removed

But since our updater checks for exactly this string (including qt5), we need to teach him that first to avoid incompatibility.

**So the questions is:** Which way do we go? `win64` or `x86_64`...

I like the first one more since it includes "win" as well and is generally less technical/confusing for all users.

---
Change needs to get reflected here as well: https://github.com/Cockatrice/cockatrice.github.io/commit/ac83be40673acc1acf7bce4251475b22e94aba0d

**Comment by ZeldaZach** [comment]
I'm fine with making a backwards-compatible change to the updater if you'd like, but I believe we determined the names of the uploads already somewhere

**Comment by Daenyth** [comment]
We should definitely do this

**Comment by tooomm** [comment]
Like I realized again here (https://github.com/Cockatrice/Cockatrice/pull/2888), we still have different patterns for the binaries for releases and betas, and are also still dependent on the redundant qt5 extension.

Missing consistency is leading to confusion for the user. There needs to be a simple and reliable pattern.

>We should definitely do this

What are you exactly agreeing on? :D

<br>

I'm highly looking forward to get things a bit moved around this issue.

**Comment by tooomm** [comment]
Solved in https://github.com/Cockatrice/Cockatrice/pull/3079#pullrequestreview-94168718
