### ISSUE TITLE
Issues With Downloading

### ISSUE THREAD

**Issue by tbrad3399** [Cockatrice/Cockatrice#2675]
<b>OS:</b>
Windows 7

<b>Cockatrice version:</b>

__________

I attempted to download cockatrice tonight and an issue came up when I attempted to launch it. 
"The program can't start because MSVCP120.dll is missing from your computer. Try reinstalling the program to fix this problem."
I reinstalled and the same error occurred.

**Comment by ZeldaZach** [comment]
https://github.com/Cockatrice/Cockatrice/wiki/Troubleshooting#failed-start-because-msvcpxxxdll-was-not-found
