### ISSUE TITLE
Program updater should recommend card database update

### ISSUE THREAD

**Issue by dev-id** [Cockatrice/Cockatrice#2676]
There is often confusion about the difference between 'Check for Card Updates' (Cockatrice menu) and 'Check for Updates' (Help menu).  Users often say things like "I ran the update and it says I'm on the current version, but I don't have `newest set`"

When `Check for Updates` is run, there should be a link asking if the user wants to 'Check for Card Updates' instead of or in addition to.  Especially if they're on the current version.  

>A new version is available [...] You may also want to update your card database(is Oracle link).

>You are on the current version. Do you want to update your card database(is Oracle link)?

**Comment by tooomm** [comment]
We started with renaming the update menu to `Check for Client Updates` to make things a bit better.

We could also think about moving the card updater menu to the same `Help` menu or even to the `Card Database` menu. I've no idea why it's placed in the cockatrice/file menu out of context...

But yeah, the updating process is still not clear and people don't understand the concept of the app+database as two parts.

**Comment by Daenyth** [comment]
We should prompt on first run of a new version to launch Oracle.

We can store the program version in a config setting we read on startup and
if it differs from running version do the prompt

**Comment by ZeldaZach** [comment]
@Daenyth So in settingsCache we store "oracleLastBuildVersion" or something similar and if the dates don't match, prompt? Or do we want it to be a thing where it promps for a re-run every X days, or do we want Oracle to (like I suggested in the past) be more of a daemon of the Cockatrice program and run in the background automatically

**Comment by tooomm** [comment]
I also found this old Cockatrice installer:
![cockatrice installer old](https://cloud.githubusercontent.com/assets/9874850/25596633/7095d1dc-2eca-11e7-82f0-a86969f7d92b.png)

We can just add this option again. It's the most basic and simple, but also the most reliable.
After each install - run Oracle.
We have some kind of promt in Cockatrice already if there is no db found or first rum I guess.

The concept of two separate apps is not easy for the user, that's for sure.

**Comment by tritoch** [comment]
> We started with renaming the update menu to Check for Client Updates to make things a bit better.
We could also think about moving the card updater menu to the same Help menu or even to the Card Database menu. I've no idea why it's placed in the cockatrice/file menu out of context...

Calling the card updater / Oracle a 'Check' when all it does is run no matter if there's an update or not is disingenuous.

**Comment by tooomm** [comment]
Right, I hope we can improve this "stupid" Oracle behaviour at one point. :)

If we rename the menu now and have to change it back later again it confuses users even more... I think we don't have to change it, let's hope for a sooner than later Oracle update.

**Comment by tooomm** [comment]
The former "Run Oracle" option after install, as shown [here](https://github.com/Cockatrice/Cockatrice/issues/2676#issuecomment-298445061) was removed here: https://github.com/Cockatrice/Cockatrice/pull/1859

There is also an explanation why. Not so sure the plan/idea worked out perfectly though, and it is the best way to deal with things. There keep popping up issues regarding the confusion with two types of updates, and why people don't get card updates with installing a new version etc.
Let's reevaluate/rethink this problem again.

**Comment by ctrlaltca** [comment]
> We should prompt on first run of a new version to launch Oracle.

This has already been implemented.
