### ISSUE TITLE
Disable "Remove counter" context item when not useful

### ISSUE THREAD

**Issue by backendr** [Cockatrice/Cockatrice#2677]
I feel that the counters menu can be more context based and only present options based on the current card state.

For example; disable, or even remove, the `Remove Counter(Colour)` if that counter is not on the card. 

<img width="346" alt="screen shot 2017-05-01 at 09 50 53" src="https://cloud.githubusercontent.com/assets/26419373/25577240/ee26bb36-2e64-11e7-81c5-c93ac30d3230.png">

**Comment by tooomm** [comment]
I'm always in for a cleaner and easier to use interface!

**Comment by Daenyth** [comment]
This should be pretty easy. @backendr I can point out where in the code this change would happen if you'd like to submit a PR

**Comment by ZeldaZach** [comment]
Good suggestion, Since it's an easy change I'll leave this one up to you :smile:
