### ISSUE TITLE
cards/tokens.xml should have information about their source data

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2679]
It's an important information in general, but especially for troubleshooting with this files.
Would be helpful to know where they fetched their data on creation from.

For example was somebody providing a local file? Or did he use @tritoch's allsets.json with spoiler info for example.

It's nice to have this kind of comprehensive information in general!

I suggest that Oracle put's the source download link of it's data into the files. (or the file location + name when a local file is provided)
Date+time of oracle run/xml creacion might also be useful.

Same for the Oracle  version (just use the one we have in Cockatrice `about` window) to quickly troubleshoot errors like with aftermath splitcards for example!

**Comment by tooomm** [comment]
@Psithief what are you confused about here? :)

An example could look like this for cards.xml:
```
<?xml version="1.0" encoding="UTF-8"?>
<cockatrice_carddatabase version="3">
    <info>
        <app_version>2.3.17 (2017-05-05)</app_version>
        <xml_create_date>2017-05-20</xml_create_date>
        <xml_data_source>https://mtgjson.com/json/AllSets.json.zip</xml_data_source>
    </info>
    <sets>
    <sets>
        <set>
        ...
        </set>
    </sets>
    <cards>
        <card>
        ...
        </card>
    </cards>
</cockatrice_carddatabase>
```

<br>

or tokens.xml:
```
<?xml version="1.0" encoding="UTF-8"?>
<cockatrice_carddatabase version="3">
    <info>
        <app_version>2.3.18-custom_f0a561d (2017-05-20)</app_version>
        <xml_create_date>2017-05-20</xml_create_date>
        <xml_data_source>https://raw.githubusercontent.com/Cockatrice/Magic-Token/master/tokens.xml</xml_data_source>
    </info>
    <cards>
        <card>
        ...
        </card>
    </cards>
</cockatrice_carddatabase>
```

**Comment by Psithief** [comment]
Oracle gives users an interface to download these files without a user needing to worry about finding XML files in their filesystem. If the debug information is only available from opening the files, there's a gap between the levels of computer literacy required to give us that information.

To address this, I think this information should also be output as lines in the About window.

**Comment by tooomm** [comment]
That's just a matter of reading and displaying the information in Cockatrice as well - should be easy once the additional info is available in the first place! 👍 

We can also think about storing the version of our source (if available).
This would allow to compare the version of the existing file and the latest release with a github api call to determine if there are updates available from within Cockatrice and trigger a new Oracle run for example.
```
<?xml version="1.0" encoding="UTF-8"?>
<cockatrice_carddatabase version="3">
    <info>
        <app_version>2.3.18-custom_f0a561d (2017-05-20)</app_version>
        <xml_create_date>2017-05-20</xml_create_date>
        <xml_data_source>https://raw.githubusercontent.com/Cockatrice/Magic-Token/master/tokens.xml</xml_data_source>
        <xml_data_source_version>1.19.1</xml_data_source_version>
    </info>
    <cards>
        <card>
        ...
        </card>
    </cards>
</cockatrice_carddatabase>
```

<br>
Displaying the current version number (+ create date) in the "About" window for files Cockatrice actually loaded seems fine, and maybe link to the file location from there so the user can easily provide more details if needed, e.g.:<br><br>

Loaded Card Databases:
- cards.xml (2017-05-22)
- tokens.xml (1.19.1 2017-05-22)
- somecustom.xml

Alternatively the printed info on db loads in the debug log could be expanded.
