### ISSUE TITLE
Add "Put Cards on Bottom of Library in Random Order"

### ISSUE THREAD

**Issue by Rendroc** [Cockatrice/Cockatrice#2681]
<b>OS:</b>
*OSX El Capitan 10.11.6
<b>Cockatrice version:</b>
Version dab7316 (2017-01-19)

__________

For Cascade cards there is no feature to put cards on the bottom of the library in a random order. Adding this feature would improve gameplay, make it more similar to paper magic and MTGO and prevent cheating.

**Comment by Daenyth** [comment]
Duplicate of #673
