### ISSUE TITLE
QDEBUG file is unreadable

### ISSUE THREAD

**Issue by backendr** [Cockatrice/Cockatrice#2682]
When you have `--debug-output` enabled, the output is unreadable.
Output can be found in `cockatrice/build/cockatrice/qdebug.txt`
Its full of hex 
```
\x00\x00\x00\xED\b\x01\x1A\xE8\x01\x8A?\xE4\x01\nV\x10
```

**Comment by ctrlaltca** [comment]
I noticed this one, too.
It seems like part of binary protobuf messages received from the network.
Probably due to debug introduced here: https://github.com/Cockatrice/Cockatrice/commit/0da2bdd7aab5005efe9a7801fac4e9bd59a0bf75#diff-27cc8777cc84eeab15dc3940b46e569fR286
