### ISSUE TITLE
Oracle should present it's version number

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2693]
You have no glue what version oracle has. It should just show the "Cockatrice version" on the first screen.
![oracle missing version number](https://cloud.githubusercontent.com/assets/9874850/25774899/cb0acf56-3298-11e7-9a9c-65e3241b1d1d.png)

Helps with troubleshooting.

**Comment by ZeldaZach** [comment]
Not a bad idea!
