### ISSUE TITLE
Request ability to create multiple (attached) tokens

### ISSUE THREAD

**Issue by Qriist** [Cockatrice/Cockatrice#2700]
I touched base with ZeldaZach before posting this.

I would like ability to create multiple tokens at once, with the 2nd+ tokens ending up attached to the first token, kind of like a macro. 

Example of current process: let's say you want to create a creature with an equip attached. Cat with Shuko, since cats need more claws. As is, you would have to create 2 tokens, manually, and then attach Shuko to Cat, manually. Not terribly hard, but tedious, especially over and over. 

Example of solution: Allow the token name box allow for multiple inputs by looking for a delimiter in the typed text, most likely a semi-colon. In the above, instead of creating "Cat" and "Shuko" you put in "Cat;Shuko". Before creating any tokens the game looks for semi-colons and creates an array (TokenArray). It then counts the array (TokenArray0) and creates a token from each input name (TokenArray1 becomes the token card Cat, TokenArray2 becomes the token card Shuko, TokenArray3 and further become any additional inputs). Once all tokens have been created the cards at TokenArray2 and up are attached to the primary card at TokenArray1. Then void the array to free memory and prevent other possible problems.

This would be wonderful to have in formats like MoJhoSto, or even commander where crazy stuff like this sometimes comes up.

Random additional thought, you should have the game clean the array items of leading and trailing whitespace before creating the tokens. "Cat;Shuko;Bone Saw" is likely to be written as "Cat; Shuko ; Bone Saw" simply because of how people type.

**Comment by ZeldaZach** [comment]
I feel the input would have to be type-specific as tokens are named "Cat&nbsp;" and "Cat&nbsp;&nbsp;" So we couldn't really trim on them. Otherwise, I'd be fine easter egging this feature in for now. @Daenyth

**Comment by Qriist** [comment]
Oh, fair point, didn't realize the tokens were named with trailing spaces. That's actually really clever! In that case, perhaps just trim leading whitespace to help mitigate such errors (it's also the most likely to appear). Either way, just implementing the multi-create/attach would be amazing. Thanks!

**Comment by Nightfirecat** [comment]
I'm of the personal opinion that this is a really narrow feature for a rare use case, so maybe would be better to prioritize other efforts first.

**Comment by tooomm** [comment]
If we are working on token creation, I highly prefer to see other way more basic and beneficial features for all users first --> https://github.com/Cockatrice/Cockatrice/issues/2262

**Comment by ZeldaZach** [comment]
This is a complicated game command, trying to interact with game commands. This isn't something that happens _often_ and is not really worth our time imo.
