### ISSUE TITLE
Suggestion: remove case-sensitivity in "Import from Clipboard" in Deck Editor

### ISSUE THREAD

**Issue by aeschenkarnos** [Cockatrice/Cockatrice#2701]
OS and version irrelevant.

__________

The idea should be obvious. Case sensitivity doesn't help at all, and creates a lot of unnecessary retyping. Also would fix the "AEther" "Aether" issue.

**Comment by ZeldaZach** [comment]
I've noticed this myself and wanted to fix it, but I couldn't pintpoint it at my first glance. Will look again.
