### ISSUE TITLE
Suggestion: add clone and create tokens to context menus for cards in graveyard and exile zones

### ISSUE THREAD

**Issue by aeschenkarnos** [Cockatrice/Cockatrice#2702]
OS and version number irrelevant.

__________

Currently a card has to be *on the battlefield* to bring up the "Clone" and "create token" right-click context menu items. This is not currently possible from the graveyard, library, exile, stack or hand zones. I suggest that there are occasional uses for this functionality and it should not be difficult to add it in.

- [x] Add "clone" to other zones
- [x] Add "create token" to other zones

**Comment by tooomm** [comment]
Token creation also works on the stack... so in case for embalm for example you should pull the card out of your gy anyway to show what you are doing and hat your opponent can follow you. Technically you are casting it from the gy, so it should go over the stay anyway. From there you create the token and exile the original spell.

What else do you want/need to create tokens for from the gy? Or what do you want to clone from the exile?

**Comment by tritoch** [comment]
You don't want to drag your `Bridge from Below` out of the graveyard every time it triggers.

**Comment by tooomm** [comment]
Ok, so there is indeed a usecase. Sounds very helpful then! 👍
If we have it on gy, it should be the same for exile. Stack has tokens already - so we are just missing clone there

**Comment by Daenyth** [comment]
Yes, this is totally reasonable. And should be an easy change too.

**Comment by Nightfirecat** [comment]
While we're at it, would it be too complex to just add this context menu to cards in all zones? Another use case would be using Create Related for instants and sorceries which produce tokens, such as `Raise the Alarm`, et. al.

**Comment by ZeldaZach** [comment]
@Nightfirecat I'll check this out

**Comment by tooomm** [comment]
@Nightfirecat you can create tokens from instants and sorceries (all type of cards actually) from the stack already? :)
Right click --> `Token: 1/1 Soldier` for Raise the alarm

**Comment by Nightfirecat** [comment]
> @Nightfirecat you can create tokens from instants and sorceries (all type of cards actually) from the stack already? :)
> Right click --> `Token: 1/1 Soldier` for Raise the alarm

Ah, right you are! If we could get this to be more generic, applying to cards in any zone, that might be helpful.

**Comment by tooomm** [comment]
Other missing right click options related to zones: https://github.com/Cockatrice/Cockatrice/issues/2068

**Comment by tooomm** [comment]
Actually, the missing token creation option should not be named `Create`, it should show the 
`Token: 2x 1/1 Soldier` option directly at the bottom of the right click options like it's done on the stack:
![token from stack](https://user-images.githubusercontent.com/9874850/40871435-f8ee7a4e-663b-11e8-8462-ea01eb4ec9db.png)
