### ISSUE TITLE
Bad moderation

### ISSUE THREAD

**Issue by Jinxstands4Jinx** [Cockatrice/Cockatrice#2703]
This is probably not the place to post for this but I do know the place. I just got banned for insulting a player. I do not recall insulting Anyone without being 1st insulted and i know the mod who did the banning he needs to lose his banning privileges because he looks for reasons to ban and is a Bad moderator.  Also i would like to see this post, because i am pretty sure the person i supposedly insulted needs to be banned Also

**Comment by Nightfirecat** [comment]
This is where the source code for the Cockatrice software is hosted... Please take up issues of server issues&mdash;(moderation, management, etc.&mdash;with the server administrators. (Assuming this is the common Woogerworks server, [website contact form](http://www.woogerworks.com/contact-us.html) or [Twitter](https://twitter.com/woogerworks))

**Comment by Jinxstands4Jinx** [comment]
yeah so where to go for that?

**Comment by Nightfirecat** [comment]
> (Assuming this is the common Woogerworks server, _**[website contact form](http://www.woogerworks.com/contact-us.html)**_ or _**[Twitter](https://twitter.com/woogerworks)**_)
