### ISSUE TITLE
Duplicate logSetActivePlayer in local play

### ISSUE THREAD

**Issue by backendr** [Cockatrice/Cockatrice#2704]
<b>OS:</b>
Irrelevant

<b>Cockatrice version:</b>
Master branch
__________

When playing locally the `logSetActivePlayer` is called once per player:
<img width="322" alt="screen shot 2017-05-08 at 22 14 36" src="https://cloud.githubusercontent.com/assets/26419373/25823384/403a084c-343c-11e7-82ea-16a1707827bd.png">

**Comment by ZeldaZach** [comment]
Pretty much irrelevant nowadays, and too minor to focus in on at this time :(
