### ISSUE TITLE
Maximized game window does not fully conform to available window space

### ISSUE THREAD

**Issue by Nightfirecat** [Cockatrice/Cockatrice#2708]
<b>OS:</b>
Win7 SP2

<b>Cockatrice version:</b>
Latest release (2.3.17)

__________

[A picture is worth a thousand words.](https://cloud.githubusercontent.com/assets/2199511/25840389/7a9f9c86-3450-11e7-836c-238025288c96.png)
You'll see that the very top pixel or two of this screenshot [is a cropped version of the Great Wave off Kanagawa](https://en.wikipedia.org/wiki/The_Great_Wave_off_Kanagawa), with the black pixels toward the left and center being the Kanji in the box and the crest of the large wave. On top of that, the bottom of the window is tucked under the menu bar at the bottom of my screen&mdash;this is most notable in the bottom-right corner where the chat bar is actually halfway covered by it.

**Comment by tooomm** [comment]
Similar but different to https://github.com/Cockatrice/Cockatrice/issues/1904

Btw, why don't you include the picture into the text?

**Comment by Nightfirecat** [comment]
Being a full-screen screenshot, it wouldn't have displayed large enough to really show the issue when displayed inline. If you want it, here you go:

![](https://cloud.githubusercontent.com/assets/2199511/25840389/7a9f9c86-3450-11e7-836c-238025288c96.png)

**Comment by tooomm** [comment]
Oh no offence, I really just wondered! :)
If you click it, you see the full screen version too.

Sometimes it's enough to get de idea though. That there is something wrong with the chat for example.^^

**Comment by ebbit1q** [comment]
I merged these tickets into https://github.com/Cockatrice/Cockatrice/issues/4114
