### ISSUE TITLE
Pm messages

### ISSUE THREAD

**Issue by Thunderbeliever** [Cockatrice/Cockatrice#2717]
<b>OS:</b>
Windows. 8 (i think) 

<b>Cockatrice version:</b>
newest
Version
2.3.17-beta004
(2017-04-27)

__________

I hope I did the above correctly,  sorry not very computer savvy so if I messed it up I apologize. Anyways onward to the issue. When people pm me yesterday I got a sound notification and if I was on another site a window opened and I was able to read a part of the message. I got PMed today and the window did not appear.. is this me?

**Comment by tooomm** [comment]
By the way your version isn't the newest... how can you assume so?
Run the application updater and you'll see. :P

Maybe you turned off windows notification? Like quiet hours or something...

**Comment by Thunderbeliever** [comment]
well, it seemed like the newest, as I said I am not very savvy in that knowledge thank you for correcting me. also, thank you for the help.

**Comment by tooomm** [comment]
Great that it worked out for you, feel free to come back for any other doubts or questions!

Enjoy playing
