### ISSUE TITLE
Occasional crash upon room exit

### ISSUE THREAD

**Issue by LethalPigeon7** [Cockatrice/Cockatrice#2720]
<b>OS:</b> Win 7 SP1
<b>Cockatrice version:</b> 2.3.17 (2017-05-05)
Has been reoccurring for a couple months at least.

**Comment by Daenyth** [comment]
Any debug info?

**Comment by LethalPigeon7** [comment]
Debug logs clear up often, like when I close the app, if I'm not mistaken.

**Comment by Daenyth** [comment]
I mean like a crash report from the OS, stack trace info, etc

**Comment by LethalPigeon7** [comment]
Oh. Sorry, can I get anything relevant retroactively?

**Comment by Daenyth** [comment]
Not really. Keep an eye out for any "details" option in future crashes

**Comment by ZeldaZach** [comment]
I've seen this happen myself, will be investigating further.

**Comment by ZeldaZach** [comment]
_MIGHT_ be fixed in #2749 Not 100% sure yet though

**Comment by ctrlaltca** [comment]
Closing this issue. A lot of new Cockatrice versions has been released since 2017, and this issue doens't contain a lot of informations on the possible caus of this bug. Thank you for the original report, and fell free to reopen if it still crashes for you in the last version.
