### ISSUE TITLE
Unable to start correctly (0xc00000ba)

### ISSUE THREAD

**Issue by notherguy** [Cockatrice/Cockatrice#2721]
<b>OS:</b>
Win 7 SP2

<b>Cockatrice version:</b>
Cockatrice-Trials_of_the_Gods-2.3.17-x86_64_qt5.exe
__________

New user here. Came from untap.in. Installed but doesn't run. "The application was unable to start correctly (0xc00000ba). Click OK to close the application."

I didn't see any similar errors with a quick search so apologies if this's come up before.

**Comment by ZeldaZach** [comment]
Try installing the 32 bit version, see if that helps!

**Comment by tooomm** [comment]
I asked google and it looks like it might be something with direct x?
https://techfaqs.net/computer/error-0xc00000ba/

**Comment by notherguy** [comment]
Here's what Google found:

directx/windows system files corrupted - techfaqs.net
registry errors or conflicts - wikifixes.com
file is a directory - error-toolkit.com
virus that won't be easily removed - computing.net

When the internet doesn't offer consensus, I pretty much ignore it. I'm running a 64 bit machine, but the 32 bit version didn't seem to work either. Other ideas?

**Comment by woogerboy21** [comment]
This sounds very suspicious of either some type of anti-virus or anti-malware type application preventing execution.  Do you have either of those type of applications running and if so could you investigate that they are not preventing the application execution by either taking a look at logs or temporarily try stopping/disabling the services for such apps and executing the cockatrice application.  I know at one  point malware bytes was falsely reporting the oracle app as being a virus due to the 7zip dll's included in it.

**Comment by notherguy** [comment]
I'm not running any anti- type software on my machine because of false positives and the like. I even shut down Window's Defender for much the same reason.

As far as untap goes, I still frequent the site, esp since cockatrice doesn't work. It's a great place to test decks and play against more casual players, but it's not a very competitive scene.

**Comment by tooomm** [comment]
Sorry, no ideas here. @ctrlaltca maybe?

**Comment by tooomm** [comment]
Do you still experience the same issue with the latest release @notherguy?
I saw that you are running an very outdated Windows version, so I highly suggest you to update that too!
Some Cockatrice issues are related to missing libraries on outdated PC's!

For Windows XP (if you really have to stick with that insecure and ancient system...) there is SP3 and a lot of other updates and security fixes available! I'm not sure if the internal Windows Updater still works on XP at all, you might have to download it from other tech or download sites still hosting it...

Also
>I'm running a 64 bit machine

That is *pretty* rare in combination with Windows XP... I guess your computer hardware supports 64bit, but your Windows XP is 32bit? In that case you have to use the 32bit version of Cockatrice too!

**Comment by tooomm** [comment]
No news are good news
