### ISSUE TITLE
date missmatch on latest beta (pre-)release

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2722]
![untitled](https://cloud.githubusercontent.com/assets/9874850/26258775/70b5fb1a-3cc6-11e7-883b-11d475d727fd.png)

`may 18th` in release tag vs.
`may 14th` in release date

It also shows up with a time offset in releases. Picture is from today, may 19th.
Should show 1 day, not 5. But 5 days is the difference to 14th again..
![untitled](https://cloud.githubusercontent.com/assets/9874850/26259033/7ea24c00-3cc7-11e7-9b55-eeb421af54fa.png)

cc: @ZeldaZach

**Comment by ctrlaltca** [comment]
From: https://api.github.com/repos/Cockatrice/Cockatrice/releases
```
    "created_at": "2017-05-14T13:16:03Z",
    "published_at": "2017-05-18T21:18:09Z"
```
About trice: we are currently using "created_at" in cockatrice to extract the date show in the popup: https://github.com/Cockatrice/Cockatrice/blob/d7e5b29d414c96b551b9ed78abd6f537dc0faadf/cockatrice/src/releasechannel.cpp#L264
Change all occurrences of created_at to published_at and it should be ok.

About the release pages on github: i suppose that shows the date of the tagged commit: https://github.com/Cockatrice/Cockatrice/tags .. not a big deal anyway.

**Comment by tooomm** [comment]
Opened a pr. Thanks for pointing! 👍
