### ISSUE TITLE
"grey out" over "hide" for menu options

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2724]
As talked about here with @Daenyth after the original PR got merged: https://github.com/Cockatrice/Cockatrice/pull/2714#issuecomment-301323538
> Yeah, I do think greying out would be better than removing entirely.

My argumentation:
>I also prefer that because the right click menu wouldn't change in size and position of options, which players are used to. Makes it easier and more uniform to find the wanted options.

It also stays in line with the approach in https://github.com/Cockatrice/Cockatrice/pull/2655.

https://github.com/Cockatrice/Cockatrice/pull/2719 addressed a bug in the initial PR, but left out on this.

**Comment by ZeldaZach** [comment]
Not enough information in this ticket to do anything.

**Comment by tooomm** [comment]
Ticket simply picked up an improvement call from a PR, and particularly asks for this:

**When right clicking on a card, the "remove counters" options used to show, even when no counters were on the card and they would do nothing. They get hidden now in that case, but should only be greyed out instead.**
