### ISSUE TITLE
capitalization of files in install directory

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2726]
<b>OS:</b>
*Win 10*

<b>Cockatrice version:</b>
*Version 2.3.18-custom_f0a561d (2017-05-20)*

__________

Referring to #2412, the exe binaries on win aren't properly capitalized.
Same problem with mac: https://github.com/Cockatrice/Cockatrice/issues/3235#issuecomment-388072892

![naming](https://cloud.githubusercontent.com/assets/9874850/26287302/21cd4800-3e79-11e7-972a-2ee2221f4faa.png)
(also leads to lower case shortcuts if you right click and create one)
<br>

Also, our folders in the installation directory are not treated uniformly. `Plugins` is capitalized, while all others are lower case...
In the user directory we have all folders in lower case as well - so `plugins`?

**Comment by Viomi** [comment]
Changing Plugins to plugins would be nice, as lowercase is always better especially for certain linux systems.

> I assume it's the same on other operating systems
In linux/unix executables are always lowercase. So yes, this is the case. Do the windows executables need to be capitalized for something in particular?

**Comment by Daenyth** [comment]
It's typical for windows and osx to have them capitalized. It looks out of place and weird. And it doesn't hurt anything to fix them.

**Comment by Viomi** [comment]
Ah, I never use windows or osx so I wouldn't have known.

This would just be a difference in the build of the program, at least for the executables, right? The only thing in the actual source would be the folder.

**Comment by Daenyth** [comment]
That sounds about right, yes. It's mostly going to be cmake config changes.

**Comment by ZeldaZach** [comment]
This would break existing installs, not worth imo
