### ISSUE TITLE
Cockatrice Crashing When Trying To Save Deck. Everything in FAQ not working.

### ISSUE THREAD

**Issue by spiffyFox** [Cockatrice/Cockatrice#2729]
<b>OS:</b>
Windows 10

<b>Cockatrice version:</b>
Version 2.3.17 (2017-05-05)
__________

I just downloaded Cockatrice for the first time, and attempted to import a decklist of mine. Upon clicking the "save" button, cockatrice crashes when opening file explorer. I have looked into the FAQ and have tried everything... uninstalling certain other programs, messing around with the cockatrice file names. Nothing works, please help.

**Comment by Daenyth** [comment]
Can you attach the deck you were trying to import? Was there any crash message, or details?

**Comment by spiffyFox** [comment]
The deck I tried was the guided by nature edh, and there is no error
message. The file explorer would open up and would stop working after...
Thank you for getting back to me so quickly.

**Comment by ctrlaltca** [comment]
I've just tried pasting and saving that deck and it works here. I suppose any deck would make it crash.

**Comment by spiffyFox** [comment]
Ive now tried everything in the FAQ, ive also tried different types of decks. IE from clipboard, etc.

**Comment by ctrlaltca** [comment]
Closing this issue. A lot of new Cockatrice versions has been released since 2017, and we didn't receive more reports of this crash. Thank you for the original report, and fell free to reopen if it still crashes for you in the last version.
