### ISSUE TITLE
Failure to Download

### ISSUE THREAD

**Issue by jtpickard** [Cockatrice/Cockatrice#2730]
<b>Win 10 64b</b>

<b>Unknown. As of 10/23/17</b>
__________

I am attempting to download Cockatrice to my laptop, but it fails midway through the download. The error always comes back with "Network Error" but there is no issue with my network that I am aware of.  I have tried with Chrome, Edge and Explorer. Any help you could provide would be greatly appreciated. 

Respectfully,
jtpickard

**Comment by Nightfirecat** [comment]
Are you downloading it directly through your browser? It's hard for us to do much about that, since it's downloaded from GitHub's servers.

**Comment by jtpickard** [comment]
Is there another way to go about this, other than through the browser?

**Comment by skwerlman** [comment]
Do you have an antivirus on your laptop? If you do, try checking its logs to see if it's blocking the download.

**Comment by ZeldaZach** [comment]
If you can't download through browser, an anti-virus is stopping it. That's the only way to accomplish the goal of getting the newest client unfortunately.
