### ISSUE TITLE
Mac client - fails to load decks, create games

### ISSUE THREAD

**Issue by anoda9** [Cockatrice/Cockatrice#2731]
<b>OS:</b>
Mac OS 10.11.6

<b>Cockatrice version:</b>
Version 2.3.17

__________

1. Load a deck, then try to load another local deck. Sometimes the 2nd deck is not loaded, the screen just stays the same.

2. Create a game. Sometimes the game is not created. Closing the client and then coming back will then cause the game to appear.

3. The client will very often lag/freeze while playing.

**Comment by tooomm** [comment]
Can you provide a debug log after each of the occurrences, please?
`Help --> Show Debug Log`

**Comment by Daenyth** [comment]
What kind of connection are you on? I'm wondering if you're getting a lot of packet loss or something. This could happen if your commands to the server are being dropped on the network, or delayed. The client doesn't update what it shows you until the server says the action was done

**Comment by ctrlaltca** [comment]
Closing as "long time unsolved mystery with no feedback"
