### ISSUE TITLE
playing cards face down isn't shown in chat log

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2738]
<b>OS:</b>
*Win 10*

<b>Cockatrice version:</b>
*Version 2.3.18-custom_5306314 (2017-05-27)*

__________

For convenience it should say
`... into play from their hand face down.` instead printing only the normal message like for every other normal play.

**Comment by ShrewMaster** [comment]
Why don't you tie this to the chat log reform that you guys were interested in doing?

You could, instead, substitute that for a sentence like:

[[Squire]] : hand -> field (face down)

**Comment by tooomm** [comment]
I just linked it to the other issue. Yeah makes sense!

Still we can't handle everything in just one change, so it's ok to have a separate issue with discussions and ideas regarding other parts.

**Comment by ZeldaZach** [comment]
Seems like a simple change. I'm fine with this.
