### ISSUE TITLE
possibility to search in sets

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2740]
With the crowing and crowing number of sets in `Manage sets..` it would be very helpful to have a search possibility there to show only sets matching a "text filter".

Same like in deck editor with the search bar!

**Comment by LethalPigeon7** [comment]
You can just click a set and start typing to jump to a set. Seems pointless to add a search bar, if anything I'd make it so it registers multiple letters, right now it just notices the first letter you type, and jumps to the first set beginning with that.

**Comment by tooomm** [comment]
I'm speaking about a real search, yes. Not the workaround that let's you jump in lists...

Have fun looking for the zendikar/eldrazi dual deck with your technique. :)
![setlist](https://cloud.githubusercontent.com/assets/9874850/26753666/8d7150aa-486b-11e7-8f82-9d477927161a.png)

Or any other set which happen to share the first letter with several others like M as well...

**Comment by LethalPigeon7** [comment]
Oh hah that's the first time I've seen someone with duel decks enabled, yeah I guess if you have all sets on it'd get pretty nasty, my bad.

**Comment by tooomm** [comment]
You don't need to have them all enabled. Maybe you just want to introduce your friend to magic and rebuild the duel decks...
Or maybe you don't even remember correctly if that one set was called "kings of tarkir" or "clans of tarkir", but what you know is the setcode for sure, so you can search for that and realize it was "khans..." instead.
Or you want the card arts from that older modern masters set to show up, so you need to search for that particular set to bring it to the front... so many possibilities.

**Comment by tooomm** [comment]
This would also help with #2845
