### ISSUE TITLE
Draw arrow from Card to Self

### ISSUE THREAD

**Issue by dev-id** [Cockatrice/Cockatrice#2741]
It should be possible to draw an arrow from a card to itself. This would be most beneficial for explaining in replay/logs where mana that is pooled is going or why a certain effect is happening.

**Comment by Nightfirecat** [comment]
Generally I've seen people point arrows from cards to themselves in cases where they're activating something that doesn't have a target. I'm not sure it's a common enough use case to warrant adding such functionality for now.

**Comment by ShrewMaster** [comment]
This is another example why #2629 would be such a useful feature for the program. Rather than "targeting" the card, you can more easily reference it in the chat and maybe explain what you're doing to it.

**Comment by ZeldaZach** [comment]
We implemented #2629 so I call this a moot point now
