### ISSUE TITLE
gitignore file in themes folder

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2755]
<b>OS:</b>
Win 10 64bit

<b>Cockatrice version:</b>
Client Version: 2.3.18-beta003 (2017-06-04)

__________

This shouldn't be there I guess:
![gitignore](https://cloud.githubusercontent.com/assets/9874850/26787434/426dea6e-4a0a-11e7-8fba-90e8a93f970b.png)

Realized after using the internal updater to jump to the newest beta.

Does this only happen on windows?

**Comment by ctrlaltca** [comment]
Git doesn't track empty directories.
That file is needed to ensure git doesn't wipe the folder.
