### ISSUE TITLE
Can't open cockatrice

### ISSUE THREAD

**Issue by philipcliang** [Cockatrice/Cockatrice#2756]
<b>OS:</b>
Windows 10 home

I get the "The application was unable to start correctly (0xc000007b). Click OK to close the application" error, I had already tried reinstalling.

**Comment by Nightfirecat** [comment]
https://github.com/Cockatrice/Cockatrice/wiki/Troubleshooting#not-a-valid-win32-application-0xc000007b
You should download the correct version (64-bit or 32-bit) for your operating system.

**Comment by philipcliang** [comment]
I'm on a 64-bit system and I downloaded the 64-bit version.

**Comment by ZeldaZach** [comment]
Is your issue solved?

**Comment by ctrlaltca** [comment]
See https://github.com/Cockatrice/Cockatrice/issues/2734#issuecomment-304388527

**Comment by ctrlaltca** [comment]
No news is good news.
