### ISSUE TITLE
Error 0x000007b

### ISSUE THREAD

**Issue by kingriaz** [Cockatrice/Cockatrice#2758]
<b>OS:</b>
Win 10 64 bit

<b>Cockatrice version:</b>
Dont know (latest?)

__________

Downloaded the latest version of cockatrice from the home page but when i start the application i get the error, "The application was unable to start correctly (0xc000007b)." Tried installing c++ 64bit 2017 and getting some dlls i seemed to be missing but nothing has worked yet.

**Comment by ctrlaltca** [comment]
> Tried installing c++ 64bit 2017

Cockatrice currently uses the 2013 c++ libs, you can find the link here: https://github.com/Cockatrice/Cockatrice/wiki/Troubleshooting#not-a-valid-win32-application-0xc000007b

**Comment by tooomm** [comment]
Seems like the old `Failed start because MSVCP{XXX}.dll was not found` message changed to
`The application was unable to start correctly (0xc000007b)` on win 10?

**Comment by kingriaz** [comment]
@ctrlaltca It worked, thanks!

**Comment by ctrlaltca** [comment]
Thank you @kingriaz for the feedback

**Comment by tooomm** [comment]
So we need to change the wiki here to adopt for the changed message in win10?
