### ISSUE TITLE
Unable to play local games while connected

### ISSUE THREAD

**Issue by demern** [Cockatrice/Cockatrice#2761]
<b>OS:</b>
Windows 10 Home

<b>Cockatrice version:</b>
Version dab7316 (2017-01-19)

__________

I noticed that it's impossible to start a local game while connected to a server. This is a bit inconvenient since I connect automatically when starting the client, and oftentimes I want to play a 1-person local game to quickly test initial draws of a deck or whatever. It looks like this behavior was changed in the past [here](https://github.com/Cockatrice/Cockatrice/pull/1018).

However, looking at the files modified in that commit, the code in master today has been reverted to its prior state and local games while connected are still impossible. I couldn't find another issue covering this reversion...is this a regression, or is there a reason this behavior was disabled again? Again, not really a big annoyance, but I'm curious.

**Comment by skwerlman** [comment]
The PR you linked was never merged because it had some unforeseen effects, and was left abandoned for a while.

I agree that local games should be possible when playing on a server.

**Comment by ZeldaZach** [comment]
This is a dupe, just not sure which is the proper ticket.

**Comment by Daenyth** [comment]
This is unlikely to be fixed any time soon due to the way local mode works. We'd need pretty extensive rewrites of the client.

**Comment by ZeldaZach** [comment]
This won't be addressed anytime soon (still), so I'm gonna close it.
