### ISSUE TITLE
change widget behavior regarding sizing

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2762]
There are size problems when showing/hiding widgets.

Taken from here:
https://github.com/Cockatrice/Cockatrice/pull/2745#pullrequestreview-41772920 + following answer from @ctrlaltca: https://github.com/Cockatrice/Cockatrice/pull/2745#issuecomment-307750598

**Comment by ZeldaZach** [comment]
Tech debt, but I don't think we're gonna do anything about it anytime soon.
