### ISSUE TITLE
Activation email

### ISSUE THREAD

**Issue by MasterQuestMaster** [Cockatrice/Cockatrice#2765]
<b>OS: Windows 10 x64</b>

<b>Cockatrice version: Version 2.3.17 (2017-05-05)</b>

__________

I'm asking this for a friend. He doesn't receive the registration e-mail for the cockatrice.woogerworks.com server. He tried it with multiple accounts, and he didn't get an e-mail. Now when he tries to register another account to try it again, it says there are too many accounts and he can't make another.

I got the 2 user names for his accounts, maybe someone can help him by resending the e-mail or help in another way. E-Mail wasn't in his spam folder or anything according to him.

Username 1: Cedrano
Username 2: Cedric4543

Thanks in advance!

**Comment by Daenyth** [comment]
For server-specific issues please contact the server admin through their website.
