### ISSUE TITLE
No activation email received

### ISSUE THREAD

**Issue by EBaucher** [Cockatrice/Cockatrice#2766]
<b>OS:</b>
Windows 10

<b>Cockatrice version:</b>
2.3.17 (2017-05-05)

__________

I have tried to register with 2 different email addresses but not received an activation email. How can I activate my account?

**Comment by Daenyth** [comment]
For server specific issues contact the server admin

**Comment by tooomm** [comment]
In the new connect/register remake we should have the ability to set contact details by the admin/owner in the config, so that people can click a link in that dialog to open the server webpage or mail them directly!
(if a server wants to provide that information for sure)
