### ISSUE TITLE
Missing Sets

### ISSUE THREAD

**Issue by ShovelRight** [Cockatrice/Cockatrice#2767]
<b>OS:Windows 8.1</b>

<b>Cockatrice version:2.3.17 (2017-05-05</b>

__________

When Aether Revolt first came out I had tried to update to get the cards but when I edited the sets, it wasn't there. No matter how many times I tried uninstalling and reinstalling, nothing seemed to work. I then took a break from it. Now that I want to play with cards I don't have, I want cards from both Aether and Amonkhet. Please Help! Thanks

**Comment by Daenyth** [comment]
Run oracle.

**Comment by tooomm** [comment]
>Run oracle.

You can do so by going to `Cockatrice --> Check for Card Updates` for example!
