### ISSUE TITLE
hide hands zone of opponent

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2769]
If you can't interact with it - hide that zone completely to gain space and have a cleaner game layout and UI.

E.g. hide your opponents hands zones always.
Show hand zones of all players if you are allowed to see hands during spectating.

Only information you get there is card count in hand. And we have a big special icon showing that on the player area beneath library already.

**Comment by Daenyth** [comment]
Isn't there a "play with revealed hand" setting?

I agree it's not useful to have much more than a count.

**Comment by tooomm** [comment]
>Isn't there a "play with revealed hand" setting?

Actually I can't recall for sure. If there is we should account for that!

<br>
Was just watching a mtgo stream and realized that they only show your own hand. So I thought it would be an improvement for us as well.

**Comment by ZeldaZach** [comment]
What are you getting at here?

**Comment by tooomm** [comment]
>What are you getting at here?

Improve the user experience with a cleaner and less cluttered interface through hiding things that don't provide value and are of no use? That was the idea at least. :)

**Comment by tooomm** [comment]
Just realized that this interferes with the `Display hand horizontally (wastes space)` option: 
![hands horizontally](https://user-images.githubusercontent.com/9874850/27169524-8344ae5e-51aa-11e7-8b30-7c974b72561a.png)
![hands vertically](https://user-images.githubusercontent.com/9874850/27169528-8564a220-51aa-11e7-9111-9fed17a3cf11.png)

I assume it's the same in a normal game!

**Comment by ZeldaZach** [comment]
We've decided it's fine enough as-is, and we haven't heard this as a complaint from anyone else
