### ISSUE TITLE
Cards dragged to graveyard don't go to top with tokens

### ISSUE THREAD

**Issue by Psithief** [Cockatrice/Cockatrice#2771]
If I make a selection group consisting of one normal object, and one object that is destroyed as soon as it leaves the play area,, and drag that selection to the discard pile (graveyard), the normal object will not go on top of the pile as expected.

Instead, it will be second from the top.

(Note the order: `{card object, token}`)

----

Presumably the drop action is assuming that the graveyard increases by 2, not 1 and inserts the card using indexes based on this assumption.

**Comment by tooomm** [comment]
I guess it's the same for exile?
Maybe stack as well if you drag in between other cards already there?
Hand?

**Comment by ZeldaZach** [comment]
Sounds like an issue with all zones. I'll check this out in the near future

**Comment by jjcard** [comment]
Checked, yes looks like it also happens for exile

**Comment by ZeldaZach** [comment]
Confirmed to still be an issue. Graveyard consists of CardA CardB. I drag CardC and TokenD to graveyard. New Graveyard order is CardA CardC CardB.
