### ISSUE TITLE
add "shields.io" to github applications

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2774]
As reminder for @Daenyth after talking to him:
<br>

![](https://files.gitter.im/tooomm/wS6P/badge-errors.png)
Some badges are erroring from time to time. I realized that earlier as well. If you refresh the page some others might error instead or you just see the alternative link because the graphic is not loading.

The documentation on www.shields.io sais (if you click on one of the github badge links):
>If your GitHub badge errors, it might be because you hit GitHub's rate limits.
>You can increase Shields.io's rate limit by going to [this page](https://img.shields.io/github-auth) to add Shields as a GitHub application on your GitHub account.

We use several of their badges. so maybe we hit that limits sometimes.^^
Please check and add them. :)

**Comment by mitchellkrogza** [comment]
Thanks @tooomm for reporting this, also running into the issue of badges not loading some times. Also saw their page saying add it your repo as an authorized application but visiting their page gives `GitHub OAuth authentication failed to provide a code.`

**Comment by tooomm** [comment]
@mitchellkrogza that's something we have to do on our end, not every user.

But you are right, there is a known problem with their service regarding authorization: https://github.com/badges/shields/issues/1038

**Comment by Daenyth** [comment]
I clicked the button
