### ISSUE TITLE
Suggestion: "xxd00dxx has left the game" should read "xxd00dxx has been kicked by LOLingbrah" if appropriate

### ISSUE THREAD

**Issue by aeschenkarnos** [Cockatrice/Cockatrice#2775]
In the interests of fairness and transparency, the chat should indicate whether a player _left_ the game of his/her own accord, or was _kicked_ from the game (perhaps unfairly) by another player. Currently there is no difference.

It would also be good if the server could tell the difference between a voluntary disconnect (eg alt-F4) and a  timeout-based disconnect, and report that to the chat as well.

**Comment by tooomm** [comment]
In more recent versions of Cockatrice there is something like that.
Since you didn't report your version as stated we can't tell why it isn't working for you.

**Comment by ZeldaZach** [comment]
This has been implemented, as @tooomm has stated. Please update your client :)
