### ISSUE TITLE
remaining improvements to token handling (manifest, unattach+destroy)

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2777]
As requested by @ZeldaZach, here are some extracted issues from https://github.com/Cockatrice/Cockatrice/pull/2773:

- [ ] https://github.com/Cockatrice/Cockatrice/pull/2773#pullrequestreview-44724163
>One thing I'd like to mention is that if a card is dragged from the library and placed face down, it should have a Token: Manifest option for it. This can be a blanket thing for all cards. Great job and I hope you keep contributing!!

<br>

- [ ] https://github.com/Cockatrice/Cockatrice/pull/2773#issuecomment-309287885
>Also, if I flip a creature that has a morph token attached, the token should be unattached & deleted

Same for re-flipping flip/double faced cards like werewolves.
Cockatrice messes around with them quite a bit at the moment. :)

**Comment by Psithief** [comment]
Having a built in rule for a `<card>` element that may not even exist seems icky. Will it still read `manifest` if Cockatrice gets multiple card language support?

I somewhat expected one issue for each item raised in that pull request.

**Comment by Daenyth** [comment]
I think that both of those options really specialize for certain behaviors at the cost of general gameplay. The former interferes with stuff like vampiric tutor as well

**Comment by ZeldaZach** [comment]
This falls under the #1740 ticket
