### ISSUE TITLE
Replay system client crash

### ISSUE THREAD

**Issue by MishraAnkh** [Cockatrice/Cockatrice#2779]
<b>OS: Win 10</b>

<b>Cockatrice version: Version f7c8651d (2016-12-30)</b>

Right clicking the playback wave bar during a replay causes a crash. Sometimes you need to be in fastforward mode. Sometimes not. Was an issue on two systems as well as being reproducible. Clicking a few times or just right clicking in general. Not sure if theres just not a right click menu available thus causing the crash or just something in general.

**Comment by tooomm** [comment]
Your client is very very old. You should download a more recent version here and check if the crash is gone: cockatrice.github.io

We fixed some crashs regarding replays. Once you have the new release you can also check for updates and download new versions right from within Cockatrice. `Help --> Check for Client Updates`

**Comment by tooomm** [comment]
Any news? Did you try the new version? Did it work?
