### ISSUE TITLE
New spoilers

### ISSUE THREAD

**Issue by Thunderbeliever** [Cockatrice/Cockatrice#2780]
<b>OS:</b>
Windows 8

<b>Cockatrice version:</b>
2.3.17 5-5-2017

__________

For the Xml for Hours of devastation is there a xml with ONLY hours?  I was told it included the Ixalan and the commander 17 stuff, why not break these up? what is the point of Ixalan cards now they are not legal for another 6 months roughly

**Comment by ZeldaZach** [comment]
Please can you reopen on https://github.com/cockatrice/Magic-Spoiler/issues as this is a Spoiler issue not a Cockatrice issue
