### ISSUE TITLE
Issues for deckbuilding

### ISSUE THREAD

**Issue by gaara91300** [Cockatrice/Cockatrice#2782]
<b>OS:</b>
Windows 10

<b>Cockatrice version:</b>
Version 2.3.17 (2017-05-05)

__________

Hi,

I'm new to cockatrice since yesterday. The problem i encountered is for deckbuilding. I added 3 decks for the moment and for 2 of those i can't see the picture of a lot of cards in the list to the right and i also can't double-click on cards to sideboard them. (i used text files to create my decks).

I tried to update my database cards and also Cockatrice version but everything is up to date.

Could you please help me ? 

Thanks a lot !

**Comment by skwerlman** [comment]
can you upload the decks which are causing problems to https://gist.github.com and link them here?

**Comment by gaara91300** [comment]
There is it : 
https://gist.github.com/gaara91300/791cf2d53dfe00070f6e93354b037369

I hope it won't make the same problem on my future decks too..

**Comment by tooomm** [comment]
>list to the right

So you mean the list of cards **in** your deck?

Do you find the problematic cards in your list on the left?
(that's the actual list of all cards of your database, you have to enable corresponding sets first for sure to make them show up)

Maybe you can also post a screenshot? You just have to drag&drop an image to the text field to upload it!

**Comment by gaara91300** [comment]
I'm at my work for the moment so i can't for the moment but later tonight i'll give you some screens to show you the issue properly or i can skype to show my screen too if you want.

**Comment by gaara91300** [comment]
And yes i mean the list in MY deck ( on the right ) and there is also the problematic on list on my left. 
I tried both , to make my deck by copy/paste text file AND by the list on the left cards per cards but the problem persists.

**Comment by gaara91300** [comment]
So there is 2 screenshots and this happen on almost all cards in the left's list.
![screen1](https://user-images.githubusercontent.com/29753056/27663712-fb88ba9a-5c63-11e7-9c3a-c826365bff14.png)
![screen2](https://user-images.githubusercontent.com/29753056/27663714-fe767030-5c63-11e7-841d-8c7d032571cd.png)

**Comment by gaara91300** [comment]
Finally it works now. I just uninstall and intall the game and it's fine now !

**Comment by tooomm** [comment]
The pictures somehow started to load or you happen to download corrupted files. Weird.
Happy to hear you fixed it all for yourself with a simple reinstall!

Next time you can also include the error log from `Help --> Debug log`. It has a lot of useful information about the ongoing details in the background like which files are loaded - is there an error etc.

Enjoy gaming (and come back with any other problems).
