### ISSUE TITLE
Issues with Cmake in Arch Linux Manjaro

### ISSUE THREAD

**Issue by fjsaezm** [Cockatrice/Cockatrice#2783]
<b>OS: Arch Linux, Manjaro</b>

<b>Cockatrice version: Latest</b>
_________
I am trying to install it in my new manjaro system and i get this error:

[fjsaezm@fjsaezm build]$ cmake ..
-- Commit is not a release or prerelease (no git tag found)
-- Project version: 2.3.18-custom_03bb02f
-- Friendly project version: 2.3.18-custom_03bb02f (2017-06-26)
-- Project version filename: Cockatrice-2.3.18-custom_03bb02f
-- Performing Test CXX_HAS_WARNING_-Wno-error=extra
-- Performing Test CXX_HAS_WARNING_-Wno-error=extra - Success
-- Performing Test CXX_HAS_WARNING_-Wno-error=delete-non-virtual-dtor
-- Performing Test CXX_HAS_WARNING_-Wno-error=delete-non-virtual-dtor - Success
-- Performing Test CXX_HAS_WARNING_-Wno-error=sign-compare
-- Performing Test CXX_HAS_WARNING_-Wno-error=sign-compare - Success
-- Performing Test CXX_HAS_WARNING_-Wno-error=missing-declarations
-- Performing Test CXX_HAS_WARNING_-Wno-error=missing-declarations - Success
-- UPDATE TRANSLATIONS: OFF
-- Found Qt ..
CMake Error at /usr/share/cmake-3.8/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Protobuf (missing: Protobuf_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.8/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.8/Modules/FindProtobuf.cmake:393 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:153 (FIND_PACKAGE)

-- Configuring incomplete, errors occurred!
See also "/home/fjsaezm/Escritorio/Cockatrice/build/CMakeFiles/CMakeOutput.log".
See also "/home/fjsaezm/Escritorio/Cockatrice/build/CMakeFiles/CMakeError.log".

Any help?

**Comment by fjsaezm** [comment]
I only had to instal "protobuf" package to solve it. Sorry

**Comment by Daenyth** [comment]
Check out the arch AUR package to use as a baseline - that might help
