### ISSUE TITLE
Everything wants to go on the wrong drive

### ISSUE THREAD

**Issue by houselyrander** [Cockatrice/Cockatrice#2789]
<b>OS: Windows 10</b>

<b>Cockatrice version: 2.3.17 (2017-05-05)</b>

__________

I'm trying to install Cockatrice on Drive D since that's my hard drive but even setting the install path there, creating a custom folder for it, and then doing the same for the card database, it still creates a database folder on my solid state Drive C and it STILL insists I need to update. How do I fix this?

**Comment by Daenyth** [comment]
@ctrlaltca any ideas?

**Comment by ctrlaltca** [comment]
By default Cockatrice installs local user data in %LOCALAPPDATA%, that usually is something like `C:\Users\<your name here>\AppData\Local\Cockatrice`, where `c:` is the drive where your user profiles folder is located.
I think you may want us to provide a portable version of Cockatrice that is self contained in a single directory. We already support this in Cockatrice, but we don't provide a precompiled portable Windows build yet. That's a nice thing to add to our Appveyor ToDo.

**Comment by tooomm** [comment]
>I think you may want us to provide a portable version of Cockatrice that is self contained in a single directory. We already support this in Cockatrice, but we don't provide a precompiled portable Windows build yet. That's a nice thing to add to our Appveyor ToDo.

--> https://github.com/Cockatrice/Cockatrice/issues/1616
I think to combine the two possibilities into one installer and let the user choose is even better.

**Comment by houselyrander** [comment]
So, ctrlaltca, you said, "We already support this in Cockatrice, but we don't provide a precompiled portable Windows build yet." What does that mean?

**Comment by skwerlman** [comment]
It means that a portable version (one that keeps its configs/pictures/decks/etc with the program itself) is already possible, but to get one you'd need to compile it yourself since Appveyor isn't setup to produce one automatically yet.

**Comment by houselyrander** [comment]
Thanks skwerlman. So, how do I do that? Every time I tried doing that Cockatrice kept shunting things in to my AppData

**Comment by ctrlaltca** [comment]
Here's a first attempt at a working portable build for windows: https://ci.appveyor.com/project/ctrlaltca/cockatrice/build/0.0.1-branch-appveyor_update-build-438

**Comment by skwerlman** [comment]
we should probably document portable builds in https://github.com/Cockatrice/Cockatrice/wiki/Compiling-Cockatrice-(Windows)

**Comment by houselyrander** [comment]
Thanks for the build ctrlaltca. Just to be clear, do I download all 3 of the things listed under artifacts? Or do I just download the exe?

**Comment by ctrlaltca** [comment]
Just download the exe and install as normal.

**Comment by tooomm** [comment]
Can you try this new installer as well please @houselyrander?
https://ci.appveyor.com/api/buildjobs/foam4070g0d0nqtf/artifacts/Cockatrice-2.3.18-custom_f0e5db3-x86_64_qt5.exe

It has both options combined and will hopefully be build automatically in the future. So all upcoming releases should have the option to use a portable installation instead build in.
Problem with that file might be that it looks like admin rights are still required to even start the .exe. So you can't install portable without these at the moment @ctrlaltca ?

**Comment by houselyrander** [comment]
Hng. That version sort of works tooomm, but I can't log in to chickatrice.net since usernames are now capped at 12 characters. I already have an account there, but it's 13 characters long

**Comment by Daenyth** [comment]
That's entirely server side anyway - you'd have to talk to the admin

**Comment by tooomm** [comment]
@houselyrander so you can install the portable version at your work PC?
Even without having admin rights?

Anyway, make sure to check for updates on the development channel from time to time to get the proper version in the next weeks! You are using a early development version right now.

**Comment by houselyrander** [comment]
@tooomm Well, I dunno if I can do it without admin rights since I run do almost everything as an admin, but yeah, it installs and runs fine. Thanks for the heads up about updates as well.

**Comment by tooomm** [comment]
Oh sorry, yes... mixed your issue up with somebody else. Never mind about admin rights^^. :)
People can still add as this is closed, it's just a little bit more difficult to find for new people and jump in.

Great that it worked for you!
