### ISSUE TITLE
Game immediately crashes

### ISSUE THREAD

**Issue by Milosz006** [Cockatrice/Cockatrice#2792]
On Windows 7 Ultimate Edition 64-bit

<b>Cockatrice version:</b>
Cockatrice-Trials_of_the_Gods-2.3.17-x86_64_qt5

When I try to launch the game nothing happens and then I get an error message, "cockatrice.exe has stopped working". Tried installing on multiple drives.

**Comment by ZeldaZach** [comment]
Does Windows generate any kind of crash logs for you? If so, can you post them?

**Comment by Milosz006** [comment]
I could, however I got the 32-bit version working so unless that will cause problems on a 64-bit machine I'm good

**Comment by tooomm** [comment]
There should be no need at all to use 32bit there.
Did you check our wiki for help with the error message?

Let us know in case you want to run 64bit and need more help.
