### ISSUE TITLE
Crash on Oracle run from program

### ISSUE THREAD

**Issue by nitrodog96** [Cockatrice/Cockatrice#2795]
<b>OS:</b>
Windows 10 Home v1703, build 15063.413

<b>Cockatrice version:</b>
dab7316

__________

*Explain your issue/request/suggestion in detail here!*

Upon running Oracle and resetting the card database, Hour of Devastation cards do not show up. However, when checking the Card Database, a set with the code HOU, but a blank name, type and release date shows up. The program crashes shortly after.

**Comment by Psithief** [comment]
This is two separate problems. Your crash, and #2712.

_So for the crash:_ 
Opening the Edit Sets window crashes the program?
It won't crash if you don't open that window?

---

Hour of Devastation cards aren't available yet anyway. They are typically only put up in Gatherer the Wednesday after the full spoiler is released. This is already covered in #2712

**Comment by nitrodog96** [comment]
No, it doesn't crash when I open the Edit Sets window, I just worded it poorly. It crashes after updating my card database.

**Comment by tooomm** [comment]
Is this issue still present @nitrodog96?
