### ISSUE TITLE
Oracle Problems

### ISSUE THREAD

**Issue by ScarletWeather** [Cockatrice/Cockatrice#2800]
<b>OS:</b>
Win 7 Pro

<b>Cockatrice version:</b>
2.3.18-beta004 2017-6-28
__________

Was informed today that Oracle has updated with the latest set, Hour of Devastation. After multiple attempts to update and double checking to make sure I had the proper settings, it appears that despite mtg.json updating yesterday, Oracle isn't loading the new set. At all.

**Comment by tooomm** [comment]
>After multiple attempts to update and double checking to make sure I had the proper settings, it appears that despite mtg.json updating yesterday, Oracle isn't loading the new set. At all.

I guess you mean `mtgjson`? They have indeed (tried to) updated to HOU.
Check their homepage https://mtgjson.com/, they also have a changelog there.
It works perfectly fine for me by the way!

**Regarding your problem with the settings:
Which `Download URL` are you using?**

**Comment by ScarletWeather** [comment]
**The download url is pointed at the default link, which is https://mtgjson.com/json/AllSets.json.zip **

I've tried both downloading the file from the site and pointing Oracle at it, and running Oracle after multiple restarts. Nothing. Oracle doesn't even present Hour of Devastation in the list of sets for confirmation.

I know multiple other users have had it work just fine, but I'm not the only person having the issue.

**Comment by tooomm** [comment]
This link is correct and worked for me as well.
Did you try again now? Some people said it wasn't working at first, but now is!

**Comment by ScarletWeather** [comment]
Ran Oracle literally right before and after your last comment. Still nothing.

**Comment by tooomm** [comment]
Well, sry then.
As of know I can just advice you to check the directory where Oracle saves the card database, check the card database path in Cockatrice settings and if they both match.
You can also try to rename your card database (to download a fresh one without overwriting the existing one, but still keep the old (+renamed) one as a backup)... as well as actually restarting your PC before performing the update. :)

**Comment by ScarletWeather** [comment]
All of the above have been performed since i got the same advice in the server chat. I ain't got nothing. ^^;

**Comment by tooomm** [comment]
For now you can use this: https://www.reddit.com/r/Cockatrice/comments/6hzyuh/houxml/

But remember to delete the file once the Oracle update works for you!

**Comment by Daenyth** [comment]
My suspicion here is that oracle and cockatrice are looking at different file paths. Where does Oracle put the cards.xml to and what's in your cockatrice settings?

**Comment by ctrlaltca** [comment]
No news is good news.
