### ISSUE TITLE
The Scarab God and God pharaoh's gift

### ISSUE THREAD

**Issue by Thunderbeliever** [Cockatrice/Cockatrice#2802]
<b>OS:</b>
windows 8*

<b>Cockatrice version:</b>
2.3.18-beta004

__________
My title explains most of my issue, Can We get a Generic Token of a 4/4 Black Zombie with No name? This way when you use the above abilities to make the Eternalize token we can have Correct representation of them? Since it does not retain its original colors or its original p/t it would be easier for people. We could use the token from the Proven combantant even, its just without Correct representation the cards are literally unplayable as a incorrect board state is just bad.

*Explain your issue/request/suggestion in detail here!*

**Comment by ZeldaZach** [comment]
cc @Psithief

**Comment by tooomm** [comment]
In general I like the idea and understand the need, but there is just no "generic token of  a 4/4 black zombie" which could be included by [Magic-Token](https://github.com/Cockatrice/Magic-Token). The token project has no custom tokens or custom art.

You could just put the card itself on the battlefield and quickly adjust the stats or/and add a "T" or "token" annotation to mark it.

**Comment by Psithief** [comment]
Unlike `Embalm` or `Eternalize`, this zombie retains the mana cost of the exiled card.

I'm thinking that we can just add this for now and delete it after it rotates.
https://github.com/Cockatrice/Magic-Token/commit/cf2553c890f7c33cb405b43f1c3e67584f1e09bc

@tooomm It very much has custom art. It has fan-made art for old tokens that were never printed by wizards.
I don't have any place to host an image myself, and don't particularly want to start doing that either.

**Comment by tooomm** [comment]
Oh yes the pre-token era, well...

I'm not too excited about that temporary workaround @Psithief 
Is it really better to have a token with wrong picture, name, cost (and likely types), which you have to annotate to keep track which card it represents to check the original values etc. anyway?
Not even speaking about the hassle to need to remove it from the token file again, people will complain then again etc.
Are these cards going to be a big deal in standard/modern at all? (only reason which would justify to think about such an unclean integration at all in my opinion, but just that it is temporary is weird)
Or is it better to just move the card itself from the graveyard and annotate it with a simple "T", "token" or "zombie token" as suggested before?
In paper magic you would also just unsleeve it most likely or put a paper marker on it for example.

You do the same for Liliana, Death's Majesty (AKH) to indicate the creature is a zombie in addition. Here we would indicate that it is a zombie token instead.
You can even move the original one to exile if you care about game state that much, and just annotate the copy! If I think how we handle other game actions this seems to be the correct way.

**Comment by Psithief** [comment]
Yes. It's only an experiment, but not how I want to deal with this kind of issue in the future.

**Comment by Thunderbeliever** [comment]
I understand putting the dude on the board as a token copy but we do not have the power or ability to change the color. so if you eternalize a Armada wurm its not white or green anymore but JUST black so that would be a pain to keep track of. Thankyou for efforts I hope we can do something, Question if we found or someone Made a Generic token could we put it into the file?

**Comment by Thunderbeliever** [comment]
Recently i Found that there Actually is a token in the Token database for this! link it to the cards please

**Comment by tooomm** [comment]
You should really update your token database. Just run Oracle again! (Cockatrice --> Check for Card Updates)

The experimental temporary solution is like your suggestion (with pic!): https://github.com/Cockatrice/Magic-Token/commit/cf2553c890f7c33cb405b43f1c3e67584f1e09bc

**Comment by Thunderbeliever** [comment]
According to that link though 1 card was forgotton.  Hour of Eternity.

**Comment by Thunderbeliever** [comment]
Also I did as you said and updated but that pic is the Same as the picture for Proven combatant, it even Says so :(

**Comment by tooomm** [comment]
Added the missing `Hour of Eternity` link - thanks for pointing out. And sorry for fixing that late.
<br>

>Also I did as you said and updated but that pic is the Same as the picture for Proven combatant, it even Says so :(

You recommended to use the picture of proven combatant by yourself in the starting post here. :)
--> `We could use the token from the Proven combantant even`

As long as we have no general and good custom token we can't link to one.
But as I stated before I'm not so sure this workaround is the best idea in general. You ended up using a custom picture (in custom folder) anyway? Which one do you use?

**Comment by Thunderbeliever** [comment]
some random picture i found online. thx for all the work
