### ISSUE TITLE
Card art preference failure

### ISSUE THREAD

**Issue by mosew** [Cockatrice/Cockatrice#2806]
<b>OS: Windows 10</b>

<b>Cockatrice version: 6e723b2 (2017-03-14)</b>

__________

Hi all. I have organized my card art preference in ascending order of release date, and unchecked some sets. For most cards, older art is successfully preferred by Cockatrice, but for others, card art from unchecked sets is being used. In particular, I hate the Amonkhet invocations art but it's still being used despite the box being unchecked in "Edit Sets...". I have updated the art database and retried, but to no avail.

**Comment by skwerlman** [comment]
Currently, for the purpose of downloading card art, whether a set is enabled or not is not considered. This is to make it possible to see art for cards from sets that are not enabled. The enabled status only controls whether the cards are available in the deck editor.

The solution to your problem would be to move the disabled sets to the bottom of the "Edit Sets" dialogue so other art is prioritized.

Also note that you need to delete the old cards from the images folder so they can be re-downloaded if they were downloaded previously using the wrong art.

**Comment by Daenyth** [comment]
I think it's an oversight that disabled sets aren't moved to the bottom of the list - we shouldn't try a disabled set before trying all enabled sets

**Comment by Daenyth** [comment]
IIRC this should be relatively easy to fix - but it's possible I'm wrong.

**Comment by mosew** [comment]
Thanks!

**Comment by mosew** [comment]
Update: it magically fixed itself. Thank you for your help!

**Comment by Viomi** [comment]
@Daenyth Making it so that disabling something will automatically send it to the bottom of the list, will pull request from https://github.com/Viomi/Cockatrice when it's ready.

**Comment by Daenyth** [comment]
Thanks for working on that! A fix here will help people out.

However, I don't think that approach is the right way to handle it. It breaks user workflows where you enable/disable sets to do broad filtering in the deck editor - I've done that before, and I would have found it very surprising to have my preference order changed.

Instead, we should change the priority order silently when the downloads are being performed. Could you look at that?

**Comment by Viomi** [comment]
Or just add an option to turn this feature on or off. As a power user, I much prefer choice ;)

**Comment by Viomi** [comment]
As for changing priority order silently during downloads, that probably wouldn't be too difficult to do as well.

**Comment by Daenyth** [comment]
I'd strongly prefer making one reasonable choice and sticking with it - choice is nice, but the majority of users will never change things from defaults, and each configurable item adds maintenance overhead and makes it harder to educate users. It's very easy to move it to bottom manually, but it's hard to restore the order. I think that it makes sense to just consider the enabled/disabled toggle during downloads.

**Comment by Viomi** [comment]
I'm not 100% sure what you mean by each configurable item adding overhead.

And I'm not 100% sure how you want it handled during downloads- Do you want to move disabled things to the bottom of the list when the download starts, or would you just like to go through the enabled ones to download images before the disabled ones?

**Comment by Daenyth** [comment]
By overhead in this case I mean it's more code in the codebase that we need to support, provide ui for, test, and keep running.

> would you just like to go through the enabled ones to download images before the disabled ones?

This is what I meant - this can be done without changing the visual order in config. If someone wants them moved down that's really easy

**Comment by Viomi** [comment]
Gotcha, yeah I can look into doing that instead when I get some more free time.

**Comment by Viomi** [comment]
It seems this is supposed to be already implemented:
https://github.com/Cockatrice/Cockatrice/blob/master/cockatrice/src/pictureloader.cpp

`class PictureToLoad::SetDownloadPriorityComparator` supposedly does this already.

**Comment by Daenyth** [comment]
Hmm, you're right.

@mosew Invocations are listed under a different set. Do you have it enabled?
<img width="622" alt="screen shot 2017-08-04 at 7 40 33 am" src="https://user-images.githubusercontent.com/14644/28967242-4382d31c-78e8-11e7-8dd8-4272d83e5e38.png">

**Comment by tooomm** [comment]
I guess we are done here, otherwise reopen please or comment. :)
