### ISSUE TITLE
Problem with confirmation email 

### ISSUE THREAD

**Issue by PussyWagon** [Cockatrice/Cockatrice#2809]
Operating System windows 10 

Latest version from 2.3.17
__________

Hello first of all
I am really sry if my question sounds dumb or anything and I am really sry if I get on any ones nerfs
but I tried to make an account yesterday and I really want to start playing but I have a problem that I just dont get the confirmation email, with the code in it so I can connect to servers, and I really do not know how long it takes.

With greetings, 

PussyWagon

**Comment by Daenyth** [comment]
Please contact the administrator of the server you're trying to register on - this tracker is for bugs in the software; we don't run a server.
