### ISSUE TITLE
Allow users to see warnings and ban history

### ISSUE THREAD

**Issue by backendr** [Cockatrice/Cockatrice#2811]
Allow users to see their ban and warning history in the `profile` tab.

Can help users who want to appeal or maintain their own behaviour.

Might it be a good idea to allow users to log into a server, though not be allowed to perform certain actions? Different ban levels.

**Comment by ZeldaZach** [comment]
I'd be fine with giving users the power to view warn/ban history via Profile tab, but I think if a user is banned they should just see the latest ban message and should not be allowed entry to the server.

**Comment by Daenyth** [comment]
Yeah, I think that makes sense, especially since it's a smaller change.

**Comment by ZeldaZach** [comment]
I'm gonna close this ticket because we'd rather focus our efforts on our in good standing users. A user can always message a mod/admin with questions on their ban/warning statuses
