### ISSUE TITLE
Eternalize Token for those who do not have one

### ISSUE THREAD

**Issue by Thunderbeliever** [Cockatrice/Cockatrice#2812]
OS:
windows 8*

Cockatrice version:
2.3.18-beta004

-------------------------

I know this is a existing issue, I made the other issue. How does a person add a Token into the Token database and link it to Certain cards? I would like to have God pharaoh's gift, the Scarab god, and Hour of eternity all linked to a token that i have Created and would be willing to distribute so that we may actually have correct board states. 
![1501452030746395](https://user-images.githubusercontent.com/28676939/28757452-86260abc-7551-11e7-9223-757847fe8cf8.png)    i know its Generic.

You can just Annotate it to what ever creature you eternalized.

**Comment by ZeldaZach** [comment]
You'll want to go to the Tokens Repo @ https://github.com/cockatrice/Magic-Token

**Comment by Thunderbeliever** [comment]
rude.

**Comment by Thunderbeliever** [comment]
sheesh could atleast help, instead of just slapping in the face and pushing aside and its a wonder people even post issue anymore

**Comment by ZeldaZach** [comment]
To make a change like this, you'll want to update the XML at the Tokens Repo. This is not a chance to Cockatrice itself, more of a change to the data we choose to parse. As such, I closed this ticket as it is more suited for changes on the Tokens Repo.

**Comment by Thunderbeliever** [comment]
you could have said That instead of just "whap" closed go away

**Comment by skwerlman** [comment]
you posted on the wrong repo's tracker; he pointed you to the correct tracker where you could get help b/c it's important to keep issues/knowledge organized.
