### ISSUE TITLE
Suggestion: allow a player to invite a spectator to take over their position (3+ players)

### ISSUE THREAD

**Issue by aeschenkarnos** [Cockatrice/Cockatrice#2819]
Such unexpected occurrences as dinner, school, work calls, picking one's girlfriend up from the airport, etc etc crop up fairly often on online games. I would like to be able to hand my position over to another player to take over, as I might do in a face-to-face multi-player game under such circumstances.

Obviously people online cheat like little cheating cheaters, so it'd need to be a person who isn't currently involved in the game, and hasn't been looking at the hands of other players. So this would be best implemented in a game where the spectator view of hands is off.

It should be the choice of the giving player, not the room owner. The receiving player should get a temp copy of the deck (and of course be able to save it if they want - don't do this if you don't want people copying your deck). Perhaps the room owner might be given veto power over this (and practically speaking they can always kick the receiving player if they dislike the situation for some reason) but I see no good reason to do so.

This would allow more games to naturally finish, without coming to an unnatural early end. People conceding early in multi-player games upends the balance of power, and can create (presumably unintentionally) kingmaking.

**Comment by Daenyth** [comment]
Neat idea!

**Comment by Thunderbeliever** [comment]
Can we expand on this?
 how about an option to allow the player to be Switched into spectator incase they have an important phone call and come back later during the game, like 15ish minutes but no one wanted to wait that long.  and i do not think the "temp" deck should be save-able at all, it should self delete in a matter of minuutes upon the game ending.

**Comment by Daenyth** [comment]
The deck handling is not difficult, once the game starts, the client doesn't really control it. The client side deck is only used when you're sending the card list to the server

**Comment by ZeldaZach** [comment]
Too hard to implement, not really worth the efforts unfortunately
