### ISSUE TITLE
Cant install Cockatrice on Deepin 15.4

### ISSUE THREAD

**Issue by arguerra** [Cockatrice/Cockatrice#2825]
<b>OS:</b>
Deepin 15.4

__________

I tried to install the Cockatrice on Deepin 15.4 following these instructions:
 https://github.com/Cockatrice/Cockatrice/wiki/Compiling-Cockatrice-(Linux) 

But at "make -j 4" i recieve this error:

Generating moc compilation cockatrice_automoc.cpp
[  1%] Built target cockatrice_automoc
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

What is the problem?
Thanks

**Comment by ctrlaltca** [comment]
> What is the problem?

Can you attach a complete log? the real error message is probably a few lines up in the log

**Comment by arguerra** [comment]
I tried format and reinstall the deepin. Now the error is in "cmake .."

arthur@notebook:~/Cockatrice$ cd build
arthur@notebook:~/Cockatrice/build$ cmake ..
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.11.0") 
-- Commit is not a release or prerelease (no git tag found)
-- Project version: 2.3.18-custom_2557a21
-- Friendly project version: 2.3.18-custom_2557a21 (2017-08-06)
-- Project version filename: Cockatrice-2.3.18-custom_2557a21
-- Performing Test CXX_HAS_WARNING_-Wcast-align
-- Performing Test CXX_HAS_WARNING_-Wcast-align - Success
-- Performing Test CXX_HAS_WARNING_-Wmissing-declarations
-- Performing Test CXX_HAS_WARNING_-Wmissing-declarations - Success
-- Performing Test CXX_HAS_WARNING_-Wno-long-long
-- Performing Test CXX_HAS_WARNING_-Wno-long-long - Success
-- Performing Test CXX_HAS_WARNING_-Wno-error=extra
-- Performing Test CXX_HAS_WARNING_-Wno-error=extra - Success
-- Performing Test CXX_HAS_WARNING_-Wno-error=delete-non-virtual-dtor
-- Performing Test CXX_HAS_WARNING_-Wno-error=delete-non-virtual-dtor - Success
-- Performing Test CXX_HAS_WARNING_-Wno-error=sign-compare
-- Performing Test CXX_HAS_WARNING_-Wno-error=sign-compare - Success
-- Performing Test CXX_HAS_WARNING_-Wno-error=missing-declarations
-- Performing Test CXX_HAS_WARNING_-Wno-error=missing-declarations - Success
-- UPDATE TRANSLATIONS: OFF
-- Found Qt 5.6.1
CMake Warning at CMakeLists.txt:135 (FIND_PACKAGE):
  By not providing "FindQt5LinguistTools.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "Qt5LinguistTools", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5LinguistTools"
  with any of the following names:

    Qt5LinguistToolsConfig.cmake
    qt5linguisttools-config.cmake

  Add the installation prefix of "Qt5LinguistTools" to CMAKE_PREFIX_PATH or
  set "Qt5LinguistTools_DIR" to a directory containing one of the above
  files.  If "Qt5LinguistTools" provides a separate development package or
  SDK, be sure it has been installed.


CMake Warning at CMakeLists.txt:143 (MESSAGE):
  Qt's lrelease not found.


-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so;-lpthread (found version "3.0.0") 
CMake Warning at cockatrice/CMakeLists.txt:168 (find_package):
  By not providing "FindQt5Multimedia.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "Qt5Multimedia", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5Multimedia"
  with any of the following names:

    Qt5MultimediaConfig.cmake
    qt5multimedia-config.cmake

  Add the installation prefix of "Qt5Multimedia" to CMAKE_PREFIX_PATH or set
  "Qt5Multimedia_DIR" to a directory containing one of the above files.  If
  "Qt5Multimedia" provides a separate development package or SDK, be sure it
  has been installed.


CMake Warning at cockatrice/CMakeLists.txt:182 (find_package):
  By not providing "FindQt5Svg.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5Svg", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5Svg" with any
  of the following names:

    Qt5SvgConfig.cmake
    qt5svg-config.cmake

  Add the installation prefix of "Qt5Svg" to CMAKE_PREFIX_PATH or set
  "Qt5Svg_DIR" to a directory containing one of the above files.  If "Qt5Svg"
  provides a separate development package or SDK, be sure it has been
  installed.


CMake Warning at cockatrice/CMakeLists.txt:189 (find_package):
  By not providing "FindQt5LinguistTools.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "Qt5LinguistTools", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5LinguistTools"
  with any of the following names:

    Qt5LinguistToolsConfig.cmake
    qt5linguisttools-config.cmake

  Add the installation prefix of "Qt5LinguistTools" to CMAKE_PREFIX_PATH or
  set "Qt5LinguistTools_DIR" to a directory containing one of the above
  files.  If "Qt5LinguistTools" provides a separate development package or
  SDK, be sure it has been installed.


CMake Error at cockatrice/CMakeLists.txt:200 (QT5_ADD_TRANSLATION):
  Unknown CMake command "QT5_ADD_TRANSLATION".


-- Configuring incomplete, errors occurred!
See also "/home/arthur/Cockatrice/build/CMakeFiles/CMakeOutput.log".
See also "/home/arthur/Cockatrice/build/CMakeFiles/CMakeError.log".

**Comment by ctrlaltca** [comment]
You miss some qt5 packages, at least the multimedia and the svg one.
I don't know Deepin but since it seems to be yet another Ubuntu-derived distro, you could try to follow the [Ubuntu instructions](https://github.com/Cockatrice/Cockatrice/wiki/Compiling-Cockatrice-(Linux)#ubuntu-16xx), that will make you install the needed prerequisites.

**Comment by arguerra** [comment]
the new deepin (15.4) is based on debian now.

**Comment by ctrlaltca** [comment]
Package names should be the same; did it work?

**Comment by arguerra** [comment]
yes. it did work! thanks!

but now i have another problem. the images arent loadind. should i open another issue?

**Comment by ctrlaltca** [comment]
Do you mean card images or any image, like button icons etc..?

**Comment by arguerra** [comment]
both

**Comment by ctrlaltca** [comment]
Please try to have a look if your distro provides a separate package for qt5 image plugins, eg. qt5-image-formats-plugins

**Comment by arguerra** [comment]
how do i do that?

i dont know if it gives you some information, but i installed the qt5-image-formats-plugins after you said.

**Comment by ctrlaltca** [comment]
In Debian and derivatives distro they split the Qt libraries in a lot of subpackages.
A typical cause of missing images in Cockatrice is that support for images in Qt is present, but the plugins needed to load the different image formats (eg. png, jpg, etc..) are missing.
Those plugins are contained in the qt5-image-formats-plugins package, so installing it should fix the problem. If it doesn't, i suggest you to open the "debug log" from the cockatrice menu and see if it contains any hint about the problem.

**Comment by arguerra** [comment]
i found this on debug log:

Client Version: 2.3.18-custom_2557a21 (2017-08-06)
Trying to load picture (set:  "pCEL"  card:  "1996 World Champion" )
Picture NOT found, trying to download (set:  "pCEL"  card:  "1996 World Champion" )
starting picture download: "1996 World Champion" Url: QUrl("http://gatherer.wizards.com/Handlers/Image.ashx?name=1996 World Champion&type=card")
Picture downloaded, but blacklisted, will consider it as not found
Picture NOT found, download failed, no more sets to try: BAILING OUT (oldset:  "pCEL"  card:  "1996 World Champion" )
QPixmap::scaled: Pixmap is a null pixmap

**Comment by Daenyth** [comment]
Isn't that card not on gatherer?

**Comment by Daenyth** [comment]
Try another card

**Comment by ctrlaltca** [comment]
Closing
