### ISSUE TITLE
Login with username and password using MSAL with .netcore webapi by accessing cosmosDB

### ISSUE THREAD

**Issue by riturajpandey** [Cockatrice/Cockatrice#2828]
Hello guys

I was working of the issue of login with local account usign Azure ADB2C with cosmosDB, now finally i did it using .net core web api using resource token. So here is the some description what i have done to get this to work

We had need of login with username and password  or local account using Azure ADB2C with cosmosDB, but we had need of accessing cosmosDB using resource token, without directly using db name and key, because of security reason, we wanted to allow authenticated user to access specific document from cosmosDB which has permission for accessing it, so we created the web api which get the access token to authenticate the user and this token was generated with login with username and password using MSAL and it also return the userid of logged in user and we use this user id to create the permission using the instance of DocumentClient and after creating permission it returns the resource token at client side and then using this resource token we create the new connection with cosmosDB which allows us to perform the all operations in the cosmosDB.

But one thing here which we need to notice is that, when we create the collection, we need to specify the partition key and this partition key need to use in the object which are going to save in the document of cosmosDB, otherwise it will deny authorise resource token to access the cosmosDB.

Here i am attaching some files, which you can check what i have done and in this attachment, you will find two file, so controller file is server side file which is using for webAPI and another one is client side file.

[ClientServerFiles.zip](https://github.com/Cockatrice/Cockatrice/files/1219992/ClientServerFiles.zip)

**Comment by skwerlman** [comment]
To clarify, did you mean to post this in this repo? I'm not 100% certain how this pertains to Cockatrice (an online card game application)
