### ISSUE TITLE
Problems adding custom cards

### ISSUE THREAD

**Issue by monkeeboy3** [Cockatrice/Cockatrice#2831]
<b>OS: Windows 10 ver 1607</b>

<b>Cockatrice version: 2.3.17</b>
__________

I recently tried adding some custom cards, and it worked fine, but when I tried to add a new card to the file, they all disappeared from Cockatrice. I've tried removing the file from the customsets folder and putting it back, I've tried adding it with a different file name and set name, and nothing has worked. But adding a completely new file works totally fine somehow? Can someone shed some light on this?

The first file is the one I initially added, then edited, and no longer works, and the second is the brand new one I made to check if it was just completely broken.

(Importantly, my issue is not with images, as those are all in the CUSTOM folder and loading properly *when the cards show up*, so pay no mind to the lack of a proper image url)

[PokemonCards.txt](https://github.com/Cockatrice/Cockatrice/files/1223381/PokemonCards.txt)
[Custom Cards.txt](https://github.com/Cockatrice/Cockatrice/files/1223439/Custom.Cards.txt)

**Comment by Daenyth** [comment]
>  and it worked fine, but when I tried to add a new card to the file, they all disappeared from Cockatrice

My first instinct is to say that you probably broke the xml format. Can you paste the debug log from the help menu? I believe it should have something about loading set files if they are broken.

Also try using an xml linter on the files.

**Comment by monkeeboy3** [comment]
I don't think that's the case, because removing the card I added didn't fix it (which I thought I said in the initial post, but I guess not). Here's the debug log anyway:

Theme changed: "Default"
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
main(): starting main program
main(): MainWindow constructor finished
CardDatabase::loadCardDatabases start
main(): ui.show() finished
cache fail for "_trice_card_back_226281"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/gstol/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 17353 Sets= 213
[CardDatabase] loadCardDatabase(): Path = "C:/Users/gstol/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 17723 Sets= 213
[CardDatabase] loadCardDatabase(): Path = "C:/Users/gstol/AppData/Local/Cockatrice/Cockatrice/customsets/01.Custom Cards.xml" Status = 0 Cards = 17724 Sets= 214
[CardDatabase] loadCardDatabase(): Path = "C:/Users/gstol/AppData/Local/Cockatrice/Cockatrice/customsets/02.Pokemon.xml" Status = 0 Cards = 17724 Sets= 214
CardDatabase::loadCardDatabases success

**Comment by ZeldaZach** [comment]
Running `xmllint /path/to/PokemonCards.xml --schema /path/to/cards.xsd` returns 

```
/path/to/PokemonCards.xml:20: parser error : Input is not proper UTF-8, indicate encoding !
Bytes: 0x92 0x74 0x20 0x63
Spells and abilities your opponents control can?t cause you to discard cards.
```

There seems to be a bad byte in the file whenever you try to use `'`. Need to fix that  before this file will work on the program.

**Comment by monkeeboy3** [comment]
That's weird, I didn't get any errors when I ran it on my end. Just to be safe though, I went through and retyped all the apostrophes, and it still isn't working (and that also wouldn't explain why it worked the first time but doesn't anymore, which is the main thing I'm confused about)

**Comment by ZeldaZach** [comment]
Wanna re-upload your file and i'll try again? Also, make sure you are using the XSD from /doc/cards.xsd and not anything else!

**Comment by monkeeboy3** [comment]
[PokemonCards.txt](https://github.com/Cockatrice/Cockatrice/files/1227221/PokemonCards.txt)
I used the one from the wiki; didn't have one already for some reason

**Comment by tooomm** [comment]
Where did you get the one in the wiki from? Can you link me the wiki page please?

**Comment by monkeeboy3** [comment]
[This one](https://github.com/Cockatrice/Cockatrice/wiki/Custom-Cards-%26-Sets). It's near the bottom

**Comment by tooomm** [comment]
The link there is to https://raw.githubusercontent.com/Daenyth/Cockatrice/master/doc/cards.xsd, so it's the one @ZeldaZach is referring to. In case you used an up to date copy of that file you're ok.

**Comment by monkeeboy3** [comment]
Well, I downloaded it like 2 days ago, so I should *hope* it's up to date

**Comment by Daenyth** [comment]
I mean, cockatrice is loading the card file:
```
[CardDatabase] loadCardDatabase(): Path = "C:/Users/gstol/AppData/Local/Cockatrice/Cockatrice/customsets/02.Pokemon.xml" Status = 0 Cards = 17724 Sets= 214
```
Status = 0 means success, and it's loading a bunch of cards and sets.

Look in Card Database > Edit Sets. Do you see the pokemon sets?

**Comment by monkeeboy3** [comment]
Nope. And if I move the file somewhere else and copy it back using Card Database > Add custom sets/cards, it'll give the message that the cards/sets were loaded successfully and reload the database, but it won't give the message saying a new set was detected, even after relaunching

**Comment by skwerlman** [comment]
@monkeeboy3 Does your file have `.txt` or `.xml` as the extension? If it's `.txt` try changing it to `.xml`.
When I tested with the file you uploaded unmodified (name and all), it failed to load, but after changing the extension to `.xml` it loaded correctly.

**Comment by monkeeboy3** [comment]
The file I'm using is .xml, I'm just uploading it as .txt because it won't let me upload the .xml

**Comment by Daenyth** [comment]
Do you see the sets/cards from `01.Custom Cards.xml`? What if you take that file out of the customsets folder and restart? Do you see the pokemon stuff then?

**Comment by monkeeboy3** [comment]
Yes, I can see those cards fine, and no, removing it from customsets doesn't make the other one work

**Comment by Daenyth** [comment]
Did you ever get this working?

**Comment by monkeeboy3** [comment]
Nope. But what's especially baffling is that it continues to not work even on a fresh install on a new machine

**Comment by ancestral** [comment]
@monkeeboy3 I think this is a simple fix…

Change the encoding from UTF-8 to ISO-8859-1. (The alternative is convert the encoding to UTF-8… but this is simpler.)

To do this, just change the first line of the file:

`<?xml version="1.0" encoding="iso-8859-1"?>`

**Comment by monkeeboy3** [comment]
Oh, hey, it worked. Thanks!
