### ISSUE TITLE
Mysql collation is inconsistent.

### ISSUE THREAD

**Issue by d5c4b3** [Cockatrice/Cockatrice#2835]
The collation between mysql tables is not consistent. 
cockatrice_sessions uses `utf8_unicode_ci`
while cockatrice_users uses `utf8_general_ci`

This causes errors while trying to run queries like
`SELECT COUNT(s.id) FROM cockatrice_sessions s INNER JOIN cockatrice_users u ON s.user_name = u.name WHERE u.admin != 0 AND s.end_time is NULL and id_server = 1`

quick workaround is to use COLLATE in the query
`SELECT COUNT(s.id) FROM cockatrice_sessions s INNER JOIN cockatrice_users u ON s.user_name = u.name COLLATE utf8_unicode_ci WHERE u.admin != 0 AND s.end_time is NULL and id_server = 1`

The quickest way to repair would be to either drop collate statements from table creation or add them to tables that do not have them.

**Comment by woogerboy21** [comment]
I've noticed this before but haven't really tried any real advance querying.  Interesting way to count the number of non-admin users logged in? (if im reading that correctly).

**Comment by d5c4b3** [comment]
It's better than running an extra query for each logged in person. 

I might end up going through the source and work on database queries. If they are anything like the stuff in the web ui they probably need some work.

**Comment by woogerboy21** [comment]
The web ui?  You mean the admin web ui I wrote way back when?  If so that was originally developed as an internal tool for me when I operated a server of like 20 people and things were thrown at it as it grew rather rapidly.  

If you have any DB query skills please by all means take a look at the db queries in the servatrice source and update them accordingly.  It's an area that is lacking IMO.

**Comment by d5c4b3** [comment]
Yea, I wanted to start advertising my server, but I figured I should have some admin tools made first. I started working on my own version. 

Will do.

**Comment by woogerboy21** [comment]
👍 

Though I would recommend working in the admin functionality to the client/server natively.  I've been trying to do so slowly.

**Comment by d5c4b3** [comment]
I do not know C++ at all, but I know database stuff real well. So I can do that part of it,

**Comment by ZeldaZach** [comment]
Feel free to fix up and clean up how we do our databases @d5c4b3, would be awesome! We really have a need to optimize everything :)

**Comment by skwerlman** [comment]
issues related to db cleanup:
- #2218 
- #865

**Comment by d5c4b3** [comment]
I am definitely going to go through the database queries. I don't write C++ very much so it will take a bit for me to learn it, but I do database stuff for work all the time. I don't know what needs to be tuned up over all. This will be a very general plan that I probably won't need to do all of.

**Database Schema**
- Work on this issue, #2835, and #2218 
- Work on #865 (I've had problems with this one)
- Make sure foreign key constraints are being used
- Potentially build stored procedures for complex queries
- Potentially build views for complex queries
**Queries**
- Work on #2303 
- Verify the speed of queries
- Modify them to work with any schema changes I make
- Verify that common security measures are in place (At a cursory glance they look right)

That's my plan over all. If there is anything else I can do either comment on this issue or contact me some other way.

**Comment by Daenyth** [comment]
@woogerboy21 can probably also provide you with slow queries that need indexing. 

I don't think we have anything complex enough to warrant a stored procedure or view - especially since I'd like to get us moved to postgres eventually, so those would make it a bit harder.

**Comment by d5c4b3** [comment]
That would be nice. 

Okay, I'll try to make any changes I do as portable as possible.

**Comment by tooomm** [comment]
If we can see some improvements regarding our db that would be key!
Thanks for looking into that @d5c4b3 

(https://github.com/Cockatrice/Cockatrice/issues/2803 is the postgres issue by the way)

**Comment by Daenyth** [comment]
That's OK - thank you for the interest! If your situation changes we'd be happy to help you get back to the project :)
