### ISSUE TITLE
Tokens

### ISSUE THREAD

**Issue by Thunderbeliever** [Cockatrice/Cockatrice#2836]
OS:
windows 8*

Cockatrice version:
2.3.18-beta004

after updating orcale for c17 eldrazi tokens are now set to Gold picture.. unsure why. also finding out that the c17 tokens are set the same way some are just wrong.

__________

*Explain your issue/request/suggestion in detail here!*

**Comment by skwerlman** [comment]
This is an issue with the[Magic-Token](https://github.com/Cockatrice/Magic-Token/) repo, not the Cockatrice application. Please reopen your issue there.

**Comment by Thunderbeliever** [comment]
thats not an issue board

**Comment by Thunderbeliever** [comment]
well thankyou but the link did not have a "new issue" place

**Comment by skwerlman** [comment]
Can you close this issue, @Thunderbeliever?

**Comment by Thunderbeliever** [comment]
oh i thought you did sry
