### ISSUE TITLE
Update Card Image

### ISSUE THREAD

**Issue by dev-id** [Cockatrice/Cockatrice#2838]
Each card entry should have the ability to individually update the card image (using current card image source settings)

Deck Editor > Select a Card > Update Card Image (new button below the card's image)

Helps with issues like https://github.com/Cockatrice/Magic-Token/issues/41 and https://github.com/Cockatrice/Cockatrice/issues/2764

**Comment by tooomm** [comment]
Right click on a card image or entry in the card list in deck editor --> `Refresh/Re-Download Card Art`

**Comment by ZeldaZach** [comment]
Seems like an idea; I'll consider looking at this at some point in the near future

**Comment by ZeldaZach** [comment]
Dupe #217
