### ISSUE TITLE
Globes for all users connected

### ISSUE THREAD

**Issue by ZeldaZach** [Cockatrice/Cockatrice#2840]
Idea:

Users in the user list will have the server connected icon color so we can see their status (this may or may not be a mod only feature).

* Have each user have a globe in the list with their current status.
* Have globes only shown if user permissions are acceptable
   * Server.ini configuration 
* Make it a feature that can be enabled/disabled in the user menu
    * Settings configuration

**Comment by Daenyth** [comment]
What does this feature help? Most of the time people are going to be on solid connections. If you're not in a game with them, what does it even matter? This seems like bloat

**Comment by ctrlaltca** [comment]
Do you man the current "connection lag" status or a new chat-like status (eg. available / busy / afk )?

**Comment by ZeldaZach** [comment]
I was thinking the green->red circles that show your status. We could also look into custom status set by users regarding their activity on the server though

**Comment by ZeldaZach** [comment]
This doesn't seem too relevant now that we think about it
