### ISSUE TITLE
Revert order of Set List in Edit Sets

### ISSUE THREAD

**Issue by dev-id** [Cockatrice/Cockatrice#2845]
In Set Editor, my preference is to disable all promo sets. The easiest way to do this is to sort by Set type. However if I have previously re-ordered my sets, sorting will clear this information.

It should be an option to revert/undo a sort after enable/disabling sets.

Desired functionality:

1. Re-order sets. Ex: Default sort, oldest first, but move Limited Edition Beta above Limited Edition Alpha
2. Sort sets by type.
3. Disable promo sets.
4. Revert the sort from step 2 - returns order to order from after step 1 (oldest first, LEB above LEA)

**Comment by tooomm** [comment]
I might want to link one of my other issue here: https://github.com/Cockatrice/Cockatrice/issues/2740

If you have the ability to search within sets, that could just filter the displayed results (without affecting your ordering).
This should help here as well:
You could then search for promo, disable all of them, clear the search and go back to your former sorted list without altering your actual set order.

**Comment by tooomm** [comment]
Done in #3229
