### ISSUE TITLE
[Qt 5.8] Life totals don't show

### ISSUE THREAD

**Issue by jfwharton** [Cockatrice/Cockatrice#2846]
<b>OS:</b>
Ubuntu 16.04

<b>Cockatrice version:</b>
2.3.18-custom_a6d3229 (2017-08-19)

__________

I can't get a version of Cockatrice_Trial_of_the_Gods for Ubuntu, and the version I was able to get does not show life totals next to players names. I got this version by following the instructions here: https://askubuntu.com/questions/605629/how-to-install-cockatrice-in-ubuntu

**Comment by Arc676** [comment]
Can you include a screenshot? I can't check my version right now, but I know that life totals do appear on the version I'm running.

**Comment by jfwharton** [comment]
Sure, there's nothing in the boxes that say Player1 and Player2

![screenshot_2017-09-01_22-13-31](https://user-images.githubusercontent.com/25574073/29992166-1dfdff4a-8f63-11e7-8e7e-f13773d15495.png)

**Comment by Arc676** [comment]
I can confirm that this bug does not exist on version dab7316 (2017-01-19).

**Comment by jfwharton** [comment]
I've now gotten the debug build, using # cmake .. -DWITH_SERVER=1 -DCMAKE_BUILD_TYPE=Debug. 

It still has the same problem, but there are many notepad files I can adjust in the cockatrice folders. I don't know anything about debugging, but is there something you would recommend I can do that could fix this?

**Comment by Arc676** [comment]
The only suggestion I have is downloading an older release. I can still connect to the Woogerworks server, even with my older version.

**Comment by jfwharton** [comment]
Ok, thanks. The June 4th release doesn't have the problem

**Comment by ZeldaZach** [comment]
This issue, I believe, is related to QT5.8. If you self-compiled, I recommend using 5.7.1 or older. There was a font change that broke a lot of stuff in client in 5.8 that we haven't adjusted for yet

**Comment by tooomm** [comment]
If it's that... we should have an issue for the transition to Qt 5.8. For problem awareness and tracking progress

**Comment by Daenyth** [comment]
Can you create that please?

**Comment by tooomm** [comment]
Can we make sure that this is the case before, please?

**Comment by Achilles777t** [comment]
Im experiencing these same issues. I downloaded the 6/4 version but I dont know how to install it or replace the existing version with the 6/4 version.

**Comment by WolfAtNight** [comment]
i have expirienced the same issue on an ubuntu machine but i think it was because i found a way to compile it without having libprotobuf8 so i installed that reinstalled and everything worked fine

**Comment by Achilles777t** [comment]
@jfwharton do you recall the command lines entered to install the 6/4 version?

**Comment by jfwharton** [comment]
I went here https://github.com/Cockatrice/Cockatrice/releases and downloaded **Source code (zip)** for the June 4 version. Then I extracted the zip file, which created a folder. Then I followed the usual instructions:

**cd Cockatrice
mkdir build
cd build
Now, configure the build and create a deb package

# Configure the build
cmake .. -DWITH_SERVER=1
# Alternatively, if you want to create a debug build to troubleshoot issues:
# cmake .. -DWITH_SERVER=1 -DCMAKE_BUILD_TYPE=Debug

# Compile Cockatrice and build a debian package
make package**

but for **cd Cockatrice** I subsituted this folder that was made

**Comment by jfwharton** [comment]
Wow, I don't the font sizes in that message are all over the place

**Comment by tooomm** [comment]
Hope I could fix it for you @jfwharton 
`#` and `*` are used for styling at GitHub (markdown)
If you post code, always wrap it in "```" before and after

**Comment by Achilles777t** [comment]
I was able to get it fixed @jfwharton thanks for your input. Also, thank you @tooomm for correcting the code post
