### ISSUE TITLE
NAN

### ISSUE THREAD

**Issue by gokuSSGpc** [Cockatrice/Cockatrice#2847]
<b>OS:</b>
*Put your operating system here! For example: "Win 7 SP2", "macOS 10.12.3", "Ubuntu 16.10" etc.*

<b>Cockatrice version:</b>
*Put your Cockatrice version number & build date here! For example: "2d53ce9 (2016-02-18)"
You find them inside the app under `Help → About Cockatrice` (Windows & Linux), or `Cockatrice → About Cockatrice` (macOS).*

__________

*Explain your issue/request/suggestion in detail here!*

I have just checked and has appeared banned. Could i know why? The nick of registration is: gokuSSG

**Comment by tooomm** [comment]
This repo is only for Cockatrice software itself, we are not running any server.
You should contact the admin of your server instead.
Hint: https://github.com/Cockatrice/Cockatrice/wiki/Public-Servers

Anyway, mods normally put a reason for the ban which is displayed to you...
