### ISSUE TITLE
Frequent 'Socket Error: Remote Host Closed the Connection'

### ISSUE THREAD

**Issue by Li-Fi** [Cockatrice/Cockatrice#2848]
<b>OS: Win 7 Home Premium SP1</b>
*Put your operating system here! For example: "Win 7 SP2", "macOS 10.12.3", "Ubuntu 16.10" etc.*

<b>Cockatrice version: 2.3.17 (2017-05-05)</b>
*Put your Cockatrice version number & build date here! For example: "2d53ce9 (2016-02-18)"
You find them inside the app under `Help → About Cockatrice` (Windows & Linux), or `Cockatrice → About Cockatrice` (macOS).*

__________

*Explain your issue/request/suggestion in detail here!*
While connected to the Woogerworks Cockatrice server I frequently experience the error "Socket Error: Remote Host Closed the Connection". The error happens typically every 5 minutes or so. Taking more actions (either manipulation of game objects such as tapping, drawing etc, or typing in the chat) seem to accelerate the likelihood of the disconnects occuring. 

Within the Chickatrice server I successfully idled in the main chatroom for at least 10 minutes while sporadically typing test messages and there were no disconnects.

This problem has only been present for me for about the last 7 days. I have used Cockatrice happily without this issue for multiple years.

I reinstalled the latest version of cockatrice and checked my Firewall rules to make sure they allow Cockatrice. I am using internet through university accommodation so it is possible that they have changed some settings recently, but if this was the case I assume the problem would apply equally to the Chickatrice server (which also uses port 4747).

In some cases an 'unstable server' type of situation seems to plague all users when multiple people are complaining about disconnects simultaneously, and my experience is similar to this but doesn't seem to affect anybody else.

Any assistance is appreciated.

**Comment by tooomm** [comment]
Do you have the same problems on the alternative port (443) woogerworks is providing as you can see [in our list of public servers](https://github.com/Cockatrice/Cockatrice/wiki/Public-Servers), also linked to from the official page: https://cockatrice.github.com?

**Comment by Li-Fi** [comment]
Sorry yes that has the same problem, I should have mentioned it

**Comment by woogerboy21** [comment]
Try connecting now and see if you still experience this issue.  We performed some scheduled maintenance this morning which should help with connectivity.  Though it is rather odd that it was working ok for you up till some random day.

**Comment by ctrlaltca** [comment]
No news is good news, closing.
