### ISSUE TITLE
Custom Icons/Phases etc.

### ISSUE THREAD

**Issue by ASFUnReaL** [Cockatrice/Cockatrice#2849]
Hey Cockatrice team,
i have a question about to customize my Icons/Phases. Is it possible to change the design of it or will there be an option in the future? And if there a possibility to change it can u explain it to me? 

Previous experiments:
But the "resources" folder from "Cockatrice-master" into my installed cockatrice folder. Then i have make my one .svg phase icon-desing and replace it with the original. Dont work, still the default phase icon there. 

I dont find the normal "phases.svg" folder in my installed folder. Because in this folder i don't have the "resources" folder.

best regards UnReaL

**Comment by tooomm** [comment]
It's easy as that: https://github.com/Cockatrice/Cockatrice/wiki/Themes#customizing-images

Let us know if it worked!

**Comment by ASFUnReaL** [comment]
Ok i have test this. Make subfolders in a new themes folder and i does not work. 

My operational steps:

Go to my cockatrice folder, into my "themes" folder. Make a new folder named" Liliana". In this folder i make a subfolder named "zones" and but my handzone.png etc. inside. That works fine! Now i make in the "Liliana" folder a new subfolder named "phases" and but all phases inside with the right name, dont work! Why? 

I hope my english is not to bad ^^ 

best regards Roman

**Comment by ASFUnReaL** [comment]
OK i have make it, i forget to restart cockatrice! thank u :)
