### ISSUE TITLE
Buttons with similar texts in Github IU too close 

### ISSUE THREAD

**Issue by tatitati** [Cockatrice/Cockatrice#2851]
I have a problem with the next buttons:
"Close pull request" and "comment"
And
"Close and **comment**" and "**comment**"

The problem is that they are too close and sometimes, going fast, the piece of "comment" made me to close a PR with no intention. 

Please, is it possible to put both buttons with more distant?, maybe even in different corners?. Thanks.

**Comment by Daenyth** [comment]
I think you want to direct this at the github support staff, not us..
