### ISSUE TITLE
Deckstats analysation doesnt work

### ISSUE THREAD

**Issue by WolfAtNight** [Cockatrice/Cockatrice#2853]
hello,
i have a question. am i the only one who is having a problem with Deck Editor -> analyze deck -> deckstats?
i mean tapped out works but deckstats doesnt
can somebody fix this or tell me how to fix it?

**Comment by Daenyth** [comment]
Looking at the deckstats code in cockatrice, it's not very robust - I think we're trying to do something they don't officially support.

The file that needs to be updated is here: https://github.com/Cockatrice/Cockatrice/blob/master/cockatrice/src/deckstats_interface.cpp

**Comment by tooomm** [comment]
@WolfAtNight please fill out issues completely (aka: tell us the version you're using!)

**Comment by WolfAtNight** [comment]
i am using the latest version (reinstalled yasterday) and self compiled for ubuntu 17.04 but i had a big problem installing because it wasnt installing libprotobuf8

also another suggestion for changes would be that when you download your decks from a server deckstorage that the deck keeps its name and does not get renamed to Deck_****.cod
it would be really nice if that got implemented

**Comment by tooomm** [comment]
>i am using the latest version (reinstalled yasterday) 

Well. if everybody tells us that he is running the **latest version** we wouldn't be able to help.
Imagine somebody is checking back on an issue which is two month old. Should he do some research first to find out which version the thread starter might have run? Some delays during master updates and published releases included.
Or somebody had some browser issues or for whatever reason used not our official page to download. So his download from yesterday might actually be 6 month old...
The only reliable way to except any problems is to ask users for their version number. We have the template for a reason. Any kind of more or less experienced computer users come here. ;)
We want to save as much time for everybody involved and be as precise as possible - that results in the best help too.

But yes, I'm seeing a `The reply from the server could not be parsed` response on Windows 10 with Version 2.3.18-custom_83f287b (2017-06-18) too.
Most likely something changed on their end.
<br>
You should open a separate issue for your second suggestion.

**Comment by deckstats** [comment]
I already posted this on reddit, but for completeness' sake:


Is there any chance you could give me a dump of the data that is sent back from DeckStats.net when you submit a deck (plus, ideally, also the request that was sent to us)? 

I just tried this request manually and everything seems to work and return the expected line:

    $ curl -d "deck=1 test of faith&decktitle=test xxx" -X POST http://deckstats.net/index.php 2>/dev/null | grep 'og:url'
    <meta property="og:url" content="https://deckstats.net/deck-14132564-9e0040f3af3e4bc2fe9f9cf7eb8df644.html" />

The only issue I could see in the code was that the deck list should be in UTF-8 encoding (I couldn't tell whether it is). If that is not the case you might get errors when the deck list contains special characters, like Æ and so on. You might also want to switch to https:// instead of http:// for the URL but that shouldn't cause the request to fail either.

**Comment by deckstats** [comment]
Actually, I think I may have found the bug - on this line, the regexp is expecting the og:url tag to end with `"/>` but the actual page has a space character in-between: `" />`: https://github.com/Cockatrice/Cockatrice/blob/master/cockatrice/src/deckstats_interface.cpp#L32

I don't have an easy way of patching this, but I think all you'd need to do is use something like this instead:

    QRegExp rx("<meta property=\"og:url\" content=\"([^\"]+)\"(\s+)/>");

**Comment by Daenyth** [comment]
I think we'd want a non-capturing group there or just not group it at all, but that sounds about right. Should be an easy fix

**Comment by WolfAtNight** [comment]
@tooomm 
changing this one line (regexp...) did not fix it for me and i would send u the dump of information from deckstats if i knew how.

**Comment by tooomm** [comment]
@WolfAtNight I didn't talk about any regexp change at all, I guess you mean what @deckstats suggested?

Just copy and past the dump here? At best you wrap it with ` ``` ` before and at the end in new lines.
Or create a gist and post the link to it here!
