### ISSUE TITLE
no color filter for colorless

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2854]
<b>OS:</b>
Win 10

<b>Cockatrice version:</b>
Version 2.3.18-custom_83f287b (2017-06-18)

__________

Filter for `colorless` color doesn't change anything
Filter for `colourless` color returns no cards!

Both should find fake colorless cards with `Devoid` and real colorless cards like "Scion of Ugin".

Feature should already exist though: https://github.com/Cockatrice/Cockatrice/pull/2737
No idea why it's not working for me right now. But anyway, the term `colourless` with "ou" is missing ;)

**Comment by Daenyth** [comment]
Yes, we should have this. As a workaround you can `AND NOT` all 5 colors

**Comment by tooomm** [comment]
with recent repo version it works. also https://github.com/Cockatrice/Cockatrice/pull/2858
