### ISSUE TITLE
Changes on The Deck storage

### ISSUE THREAD

**Issue by WolfAtNight** [Cockatrice/Cockatrice#2855]
This is **NOT** an issue but a request.
i would like to see a general overhaul of the Deck Storage section like:

- Better sorting abillities
- The abillity to rename Decks
- Fixing the ?BUG? that if u download a deck from the server it gets named to its ID. I mean this would be no problem if we had a way to rename them easely
- And something that isn't really necessary but would be really awesome, is some kind of visual syncing. I mean like u select a local deck and a server deck and then you get shown what the difference between them is like the github red/green collumns.

**Comment by ZeldaZach** [comment]
We've done the relevant bits of this ticket at this point
