### ISSUE TITLE
Forgot Password uses case-sensitive email compare

### ISSUE THREAD

**Issue by MotherofRuins** [Cockatrice/Cockatrice#2857]
<b>OS:</b>
Windows 7 Professional SP1

<b>Cockatrice version:</b>
2.3.17

__________

Had difficulty getting Forgot Password to work.  Turns out it expects email address to be case sensitive.  Suggest cast both to lower case before compare.  I believe email clients and servers do that anyway so that is what people might expect.

**Comment by Nightfirecat** [comment]
Agreed. [Supposedly they're not necessarily case-sensitive](https://stackoverflow.com/a/9808332/540162), but in practice they're effectively implemented that way anyway.
