### ISSUE TITLE
Unjustified and arbitrary permanent (!) ban

### ISSUE THREAD

**Issue by ShawnMichaels** [Cockatrice/Cockatrice#2861]
Hello,

so I have just been banned permanently by some moderator from the woogerworks server for being 'overly toxic'. That's all explanation I get. I would like to make a complain about this moderator's behaviour since I think it is groundless and arbitrary. In this specific case there was no reason at all to take this decision. There was no argument, unpolite behaviour or animosity between me and some user at all. In fact we were having a actually interesting discussion about the games future. I got banned out of nowhere. Just read the chat log from a few minutes ago as I post this for proof. I request someone responsible for this to repeal my permanent ban because I honestly suspect that this is either some misunderstanding or someone is having a grudge against me. Altogether I would like to recommend that you codify or clarify they conditions of bans a bit more clearly because it seems that is quite arbitrary and random from my experience. Now I assume the person who permabanned me considers his action as justified because I have been banned in the past but those bans were based on false denuncations and accusations and weren't particularly justified either.

I hope you understand and will take the the respective measures. My account name is the same as on here.
Thanks in advance.

thanks in

**Comment by ShawnMichaels** [comment]
The reason I care this time is that it's a permanent ban and it really came out of nowhere or totally out of the sky. There was no warning whatsoever and I was really surprised to see the message to pop up. I had no idea that you could get banned for having (civilized) discussions in the chat and it really bothers me. I really suggest to reconsider this decision,

**Comment by ctrlaltca** [comment]
This is the issue tracker for the software itself, not a support forum for a specific server.
Contact the server administrator and appeal their decision there.
