### ISSUE TITLE
Unjustified and arbitrary permanent (!) ban

### ISSUE THREAD

**Issue by ShawnMichaels** [Cockatrice/Cockatrice#2862]
( I had to post this twice since my first thread got taken down without notice?)

Hello,

so I was just banned permanently by some modeator from the woogerworks server. I would like to make a complaint about this decision as it is clearly groundless and arbitrary. It came out of nowhere. I was actually discussing in a civilized manner in the main chat when the message popped up that I got banned permanently for being 'overly' toxic'. I have no idea where this verdict came from and I either suspect that this is a misunderstanding or someone is having a grudge against me. There is no foundation in this case at all to take such a drastic measure and I appeal to you to reconsider this decision as it is totally unfounded. I can't figure out for what reason I got banned in this case as there was not the least trace of banworthy behaviour by anyone at the time of the ban and I also didnt get warned whatsoever. The responsible person to look into this can check it by looking at the chat history from about an hour ago as I post this. Altogether I would recommend you clarify and codify the conditions of bannings more because these have always appeared pretty random to me. 

I hope you understand. My account name is the same as on here.

Thanks in advance.

**Comment by ctrlaltca** [comment]
i suggest you to read the reply to your previous post here: https://github.com/Cockatrice/Cockatrice/issues/2861#issuecomment-331915096
