### ISSUE TITLE
Add a shortcut for "add to sideboard" in deck editor

### ISSUE THREAD

**Issue by badasburnt** [Cockatrice/Cockatrice#2865]
<b>OS: Windows 7</b>
*Put your operating system here! For example: "Win 7 SP2", "macOS 10.12.3", "Ubuntu 16.10" etc.*

<b>Cockatrice version:2.3.17</b>
*Put your Cockatrice version number & build date here! For example: "2d53ce9 (2016-02-18)"
You find them inside the app under `Help → About Cockatrice` (Windows & Linux), or `Cockatrice → About Cockatrice` (macOS).*

__________

Yeah I just feel like having a shortcut to add to the sideboard would be very helpful, currently I only see one to add to main deck.
*Explain your issue/request/suggestion in detail here!*

**Comment by ctrlaltca** [comment]
Pressing "enter" on a card form the list adds it to the main deck.
Pressing "ctrl+enter" (cmd+enter on macs) on a card form the list adds it to the sideboard.

Unfortunately this is not configurable by now.
