### ISSUE TITLE
The game will not let me register or recover my password

### ISSUE THREAD

**Issue by GryffindorGirl2013** [Cockatrice/Cockatrice#2866]
<b>OS:</b>
*Put your operating system here!  "Win 7 SP2"
<b>Cockatrice version:</b>
*Put your Cockatrice version number & build date here! Version 2.3.17 (2017-05-05)

__________

So I tried to connect to the server to play but it was telling me to register which I have done before, but I went ahead and tried to do it.  But then the game said I have tried to many times that I had to contact the system owner.  So then I just tried to recover my password but it wouldn't let me do that either saying I had to still contact you guys.  So what do I do know, I can't get on to play.  I have even tried uninstalling and re-installing and still nothing.

**Comment by ctrlaltca** [comment]
You should contact the administrator of the server you are trying to connect to; we only manage the development of the software here. I suppose you are using @woogerboy21 's server, so browse to http://www.woogerworks.com/ and follow the "contact" link.
