### ISSUE TITLE
Life is missing Continuing from #2867

### ISSUE THREAD

**Issue by vpassapera** [Cockatrice/Cockatrice#2868]
<b>OS: Ubuntu 17.04</b>
<b>Cockatrice version: rc_1610</b>
__________

@skwerlman 

<img src="https://i.imgur.com/ahteoT2.png"/>

**Comment by tooomm** [comment]
Do you compile with Qt 5.8 on your end @skwerlman? --> https://github.com/Cockatrice/Cockatrice/issues/2846

**Comment by vpassapera** [comment]
I tried compiling on 17.04 but got no dice. Most of the deps are not readily available through apt.

**Comment by skwerlman** [comment]
No, it's built against QT 5.6.1. What version of QT do you have installed, @vpassapera?

**Comment by vpassapera** [comment]
Will check it out when I get home.

**Comment by skwerlman** [comment]
Have you had a chance to try out the build yet?

**Comment by vpassapera** [comment]
@skwerlman life total is still not showing :(

**Comment by amarzial** [comment]
Is not a Qt issue, I just solved that.
Making a pull request in few hours

**Comment by vpassapera** [comment]
@skwerlman will there be a new build for 1704?

**Comment by skwerlman** [comment]
The current master is being built right now: https://gitlab.tetrarch.co/cockatrice/cockatrice/pipelines/391

**Comment by vpassapera** [comment]
It works. Looks good.

Thank you guys for your efforts!

**Comment by Daenyth** [comment]
@amarzial Thanks for fixing this!
