### ISSUE TITLE
Paste from clipboard -> save as - does not automatically add extension Continuing from #2867

### ISSUE THREAD

**Issue by vpassapera** [Cockatrice/Cockatrice#2869]
<b>OS: Ubuntu 17.10</b>
<b>Cockatrice version: rc_1610</b>
__________

@skwerlman

Paste from clipboard -> save as - does not automatically add extension

**Comment by tooomm** [comment]
Are this your hosted versions @skwerlman?
Never saw this tag before: `rc_1610`

**Comment by vpassapera** [comment]
So, figured out what was wrong. It's not providing a default extension. if i rename file to .cod it works.

**Comment by vpassapera** [comment]
Ux should probably generate extension if not present, 2 cents.

**Comment by vpassapera** [comment]
@tooomm @skwerlman Cockatrice-2.3.18-custom_ef89104 if that's a better tag to use.

**Comment by tooomm** [comment]
>It's not providing a default extension.

Who or what is not providing the extension?
Where do you get your deck file from?

**Comment by vpassapera** [comment]
Paste from clipboard -> Save / Save As

**Comment by vpassapera** [comment]
Fixed title and body of OP.

**Comment by tooomm** [comment]
So you are saying the "Save / Save As" option inside Cockatrice doesn't use a (default) file extension in your linux environment.

On windows it does save as default in `.cod`.
Even though it displays the confusing standard phrase `Common deck formats (.cod, .dec, .txt, .mwDeck)`.

**Comment by vpassapera** [comment]
@tooomm 

<img src="https://i.imgur.com/aGQuomx.png" />

On linux, where does it display the "confusing" phrase?

**Comment by vpassapera** [comment]
That was the load screen (no formats listed)

This is the save screen (again no formats listed).

<img src="https://i.imgur.com/XsspBnp.png"/>

As a first time user, i did not know that a format would have to be specified....

**Comment by tooomm** [comment]
I was just speaking about my windows experience.

But as you can see in your screenshot it displays `Common deck formats` in the lower right for you.
Just without the examples. (btw you're showing the load screen)

---

Ok, that should be explained or more obvious somehow.

**Comment by vpassapera** [comment]
Clicking on the "Common Deck formats" drop down has two options

Common deck formats
All files

Again, no list for expected deck types.

**Comment by tooomm** [comment]
No idea why win and linux are different there. But thanks for letting us know.
Wondering how mac looks like...

But the bigger problem is that it adds no file extension as default.

**Comment by vpassapera** [comment]
I have osx as well. I can report on that. Give me a sec.

**Comment by vpassapera** [comment]
OSX lists the formats and automatically adds `.cod`.

**Comment by tooomm** [comment]
Thanks for checking! We have all basic information gathered for now.

But please try to not spam people with mail triggers for every new post within short frequency, if you can edit it instead. ;)

**Comment by skwerlman** [comment]
@tooomm the build jobs are named as `build_<build type>_<os>`, hence `rc_1610`, though the in-app version is the same as a self-built copy.

@vpassapera I've gotten a 17.04 build to complete; can you try out the deb and let me know how it goes?
https://gitlab.tetrarch.co/cockatrice/cockatrice/-/jobs/1521

**Comment by vpassapera** [comment]
@skwerlman check out my comment on #2868
