### ISSUE TITLE
Make the user information window resizable

### ISSUE THREAD

**Issue by Grim-the-Reaper** [Cockatrice/Cockatrice#2874]
<b>OS:</b>
Windows 10

<b>Cockatrice version:</b>
Version 2.3.18-beta004 (2017-06-28)
__________
Could the user information window be made resizable? The avatar image inside should zoom with it.
I use a magic card as my avatar, and the text is hard to read with the current window size.

**Comment by Daenyth** [comment]
Using a magic card is never going to work well because the aspect ratio is wrong. Making the window resizable is reasonable though.

**Comment by JineteDV** [comment]
Almost the same as #2325
