### ISSUE TITLE
CTRL+U on ubuntu wont work

### ISSUE THREAD

**Issue by WolfAtNight** [Cockatrice/Cockatrice#2875]
i just wanted to report a bug that i found where the CTRL+U shortcut does not work at least on servers.
i go into a local game works. i connect for example to chickatrice and go into a game there, does not work
now i decided to change the shortcut to CTRL+. and that works. i think its also noteworthy that this problem only occurs on ubuntu. on my windows pc everything works fine. and yes both buttons are working normally i mean the U and the CTRL so its NOT the hardware.

i am using Version 2.3.17 (2017-05-05)
on ubuntu 17.04

**Comment by ctrlaltca** [comment]
I suppose it has something to do with Ubuntu binding the ctrl+(shift+)U key to one if its menu, eg. https://superuser.com/questions/358749/how-to-disable-ctrlshiftu-in-ubuntu-linux

**Comment by Arc676** [comment]
Do all other keyboard shortcuts work? On Ubuntu, in order to get keyboard shortcuts to work (at least on an older version) I had to run it with `dbus-run-session Cockatrice`. This prevented the in-game menu bar from appearing in the Unity menu bar and the keyboard shortcuts worked. I'm not sure if this is still true or if it applies to your situation.

**Comment by WolfAtNight** [comment]
i can just say that it is ubuntu budgie for me(i believe it is running Gnome as graphics programm) and that i tried a couple of other shortcuts but deffenitely not all, what so ever the only combination i found that was not working was CTRL+U and the thing from @ctrlaltca did not fix it for me

**Comment by Daenyth** [comment]
Related #476 ?

**Comment by Q3CPMA** [comment]
Same here (on Gentoo with cockatrice-20170505). All the others keybinds works, and ^U isn't seen by my WM.

**Comment by ebbit1q** [comment]
duplicate: https://github.com/Cockatrice/Cockatrice/issues/2219
