### ISSUE TITLE
Portable Windows version?

### ISSUE THREAD

**Issue by InoroIsha** [Cockatrice/Cockatrice#2879]
<b>OS: Windows 10</b>

<b>Cockatrice version: 2.3.17 (2017-05-05)</b>
__________
I've read on Reddit and in the Issues here that Cockatrice is supposed to be portable, but on Windows it doesn't seem to be. Running the installer doesn't provide an option to install a portable version in the [current Windows version installer](https://github.com/Cockatrice/Cockatrice/releases/download/2017-05-05-Release-2.3.17/Cockatrice-Trials_of_the_Gods-2.3.17-x86_64_qt5.exe) at [cockatrice.github.io](https://cockatrice.github.io/). 

When starting Cockatrice, I can set the location of decks, replays, pictures, cards and tokens to a custom location, but still stores the global settings, card database settings, server info and layout settings in the local AppData folder for Cockatrice. I can't find any option to change the location of these settings files, so the app isn't truly portable at all.

Is this intended behavior, or a bug? If it is intended behavior, are there any plans to make the Windows version portable in the future?

**Comment by ctrlaltca** [comment]
We already developed a portable version, but still have to publish an official release with this feature in. In the meanwhile you can use a development release, links are on the github main page.
More info: https://github.com/Cockatrice/Cockatrice/pull/2794

**Comment by Daenyth** [comment]
@ZeldaZach can you publish an official release with that in?

@ctrlaltca is that automatic for builds off master or is there something we need to set up on appveyor?

**Comment by ctrlaltca** [comment]
The feature is built in in every build off master after https://github.com/Cockatrice/Cockatrice/commit/1366e5970e4f4154a9016b04a890c5f68c58afdc
