### ISSUE TITLE
"-betaX" over "-betaXYZ" tag extension

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2880]
use shorter and simpler:
`2017-06-28-Development-2.3.18-beta4` 
instead adding leading zeros to the beta extension:
`2017-06-28-Development-2.3.18-beta004`

There is no way we need 10 (or any other two, or even three digit number...) betas before we should create a new full release. :)

**Comment by ZeldaZach** [comment]
Sure
