### ISSUE TITLE
p/t sorting in deck editor not correct

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2884]
From Gitter:
>I don't know if this has already been mentioned or fixed but just noticed that when sorting cards by p/t they are ordered alphabetically rather than numerically as-in I believe the p/t for cards are being read as a string rather than an integer. ex. cards with power 10 being placed with cards of power 1 because they both start with a 1

Source:  :point_up: [September 3, 2017 11:24 AM](https://gitter.im/Cockatrice/Cockatrice?at=59abca59614889d475b67513)

<br>

Verified with Version: 2.3.18-custom_a01c515 (2017-09-27) on Win 10.

Some screenshots:
![1](https://user-images.githubusercontent.com/9874850/31184763-9ba36bb6-a92a-11e7-844a-bcb6726cba36.png)
![2](https://user-images.githubusercontent.com/9874850/31184767-9d1b998c-a92a-11e7-89d5-576826715df4.png)

**Comment by jjcard** [comment]
I can look into this, doesn't seem like a hard fix.

**Comment by Nightfirecat** [comment]
It's likely sorting as strings as opposed to trying to compare them as numbers, hence "11" would be earlier than "2".

**Comment by Daenyth** [comment]
Yes, that's almost certainly it, because power and toughness are strings - you have p/t like `*/1` so it can't just be a numeric type. We'll need to write a custom sort function that will inspect if it's a number, and if so sort numerically, and then pick some sorting for the non-numbers

**Comment by jjcard** [comment]
I starting doing that, but then found the 'fun' cases like ".5/.5" and "1+*/1+*", so I guess  I can't just parse as ints before the slash. A workaround shouldn't be too hard, but I'll try and figure out the cleanest solution
