### ISSUE TITLE
MSVCP120 / MSVCR120 missing. Already followed through troubleshooting

### ISSUE THREAD

**Issue by t-jung** [Cockatrice/Cockatrice#2887]
<b>OS:</b>
Win 10 64 bit

<b>Cockatrice version:</b>
Cockatrice-Trials_of_the_Gods-2.3.17-x86_64_qt5

__________

Picture of my installed C++ package(s)
https://gyazo.com/56e1d1df9fa8dbda2622bc62524851bd
Video of it not working:
https://gyazo.com/6698ba64725872e0760fe8bf04520917 

Already tried multiple uninstalls and reinstalls. 
Already tried redownloading the cockatrice clients.

**Comment by JineteDV** [comment]
https://github.com/Cockatrice/Cockatrice/wiki/Troubleshooting#failed-start-because-msvcpxxxdll-was-not-found

**Comment by ctrlaltca** [comment]
From the picture you have:
*  2005 32bit + 2005 64bit
*  2010 64bit
 * 2013 32bit
 * 2017 64bit

What you miss is 2013 64bit. Follow @JineteDV 's link.
