### ISSUE TITLE
Tokens for cards that do not have tokens

### ISSUE THREAD

**Issue by Thunderbeliever** [Cockatrice/Cockatrice#2889]
OS:
windows 8*

Cockatrice version:
2.3.18-beta004
__________

i Made a token for Jace, Cunning Castaway's Other ability you can fine it here

https://i.imgur.com/jUiBBEX.jpg  

I do not know how to link it to the card though could someone help with this? I am working on making all the tokens for the Scarab god.

**Comment by Nightfirecat** [comment]
So you're making a token for every creature in Magic? 😕

**Comment by Thunderbeliever** [comment]
sadly yes. Long process

**Comment by Nightfirecat** [comment]
I don't think there's a realistic way to support that in Cockatrice. Really, making a token copy of a creature and adding a "Token" or "Eternalized Zombie" annotation should be sufficient.

**Comment by Thunderbeliever** [comment]
that may be true, and there is a new token made for that, i just am using
the Scarab tokens for MY own board. but the Jace castaway token seemed like
something everyone could use.

**Comment by ZeldaZach** [comment]
Thanks for your contribution @Thunderbeliever but I don't think we'll be pursuing this with the main branch of Cockatrice. As @Nightfirecat stated, just using the annotation field should be sufficient

**Comment by Daenyth** [comment]
cc @Psithief maybe? Would we want this in the tokens file?

**Comment by Thunderbeliever** [comment]
it would be better use the token, than to just not have jace work at all.
