### ISSUE TITLE
Ubuntu installer on website is for outdated ubuntu

### ISSUE THREAD

**Issue by ted537** [Cockatrice/Cockatrice#2894]
<b>OS:</b>
Ubuntu 17.04

<b>Cockatrice version:</b>
Trial of the gods release (2.3.17)

__________

When trying 

    sudo apt install ./Cockatrice-Trials_of_the_Gods-2.3.17.deb

Get this output:

    The following packages have unmet dependencies:
    cockatrice : Depends: libprotobuf8 but it is not installable
    E: Unable to correct problems, you have held broken packages.

Built the deb myself using the latest libprotobuf library, and it works.

**Comment by ctrlaltca** [comment]
Yep, the deb package is currently build on a very old ubuntu version.
You can still try to use an unofficial package, more info here: https://github.com/Cockatrice/Cockatrice/wiki/Unofficial-Developer-Builds
