### ISSUE TITLE
Set up docker multi-stage container for compilation

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#2898]
See https://docs.docker.com/engine/userguide/eng-image/multistage-build/#before-multi-stage-builds

We can use this for:
- faster travis by using docker instead of legacy launcher
- build modern ubuntu versions even if travis doesn't support them, for release to the website etc.
- build other linux versions (rpm etc) for automatic release

**Comment by Daenyth** [comment]
A nice-to-have would be a ready-to-go docker-compose setup that launches mysql+servatrice(+sendmail?)

**Comment by tooomm** [comment]
Since you use docker for your gitlab builds too @skwerlman... any chance you can help us to realize something with travis here?

https://docs.travis-ci.com/user/docker

Also linking https://github.com/Cockatrice/Cockatrice/issues/1746

**Comment by skwerlman** [comment]
Unfortunately, I don't use docker directly in my builds; gitlab-ci handles everything related to docker in the background for me.

**Comment by tooomm** [comment]
>build modern ubuntu versions even if travis doesn't support them, for release to the website etc.

There might be some good news from travis regarding that:
https://blog.travis-ci.com/2017-12-01-new-update-schedule-for-linux-build-images

They are going to offer two groups of images - stable and latest, they also said:
>On a related note… Xenial is just around the corner! :tada: We’re as excited as can be to bring it in along with this new update schedule.

Let's see how *latest*  they go. :)

**Comment by ctrlaltca** [comment]
Already implemented.
