### ISSUE TITLE
Crash when sideboarding by performing game actions

### ISSUE THREAD

**Issue by cym13** [Cockatrice/Cockatrice#2900]
<b>OS:</b>
Linux 4.9.52

<b>Cockatrice version:</b>
Cockatrice 2.3.17

__________

It is possible when sideboarding to perform game-related actions through keyboard shortcuts. These may lead to a crash.

For example, on the sideboarding panel, pressing Ctrl+t open the token selection window. I get a reliable crash by pressing "Name" to invert the sorting order, then selecting "Zombie horror" as a token. Another way to get a crash is simply to press F3 to try seeing the player's library.

I did not notice any side-effect besides crashes in specific cases but it would be bad if a bug was found that allowed modification of the game to come as that would allow cheating. That's why I think such actions should be disabled altogether when on the sideboarding panel.

**Comment by Nightfirecat** [comment]
Quick-reproduce steps for this crash:

* Start a local game with one player
* Press F3 (or whatever your "View Library" shortcut is)

**Comment by cym13** [comment]
Just wanted to precise that the reason why I specified two different methods is that they produce two different crashes with different stacktraces. There may be more.

**Comment by tooomm** [comment]
>Quick-reproduce steps for this crash:
>
>    Start a local game with one player
>    Press F3 (or whatever your "View Library" shortcut is)

Reproduced on windows. Even without loading a deck, so it crashes before game start too.

@cym13 can you post some of the different traces you're seeing.

**Comment by cym13** [comment]
There are many threads so I won't paste everything, only the stacktrace that seems to lead to a bug.

Using the "reverse sort / create token" bug:

                #0  0x00007face494d423 _ZN25QAbstractItemModelPrivate25removePersistentIndexDataEP25QPersistentModelIndexData (libQt5Core.so.5)
                #1  0x00007face494d73a n/a (libQt5Core.so.5)
                #2  0x00007face58e340d n/a (libQt5Widgets.so.5)
                #3  0x00007face593be2c n/a (libQt5Widgets.so.5)
                #4  0x00007face49e53e6 _ZN7QObjectD2Ev (libQt5Core.so.5)
                #5  0x00007face57075c6 _ZN7QWidgetD2Ev (libQt5Widgets.so.5)
                #6  0x00007face592f76a _ZN11QHeaderViewD0Ev (libQt5Widgets.so.5)
                #7  0x00007face49db75d _ZN14QObjectPrivate14deleteChildrenEv (libQt5Core.so.5)
                #8  0x00007face5707535 _ZN7QWidgetD2Ev (libQt5Widgets.so.5)
                #9  0x00007face5985f2a _ZN9QTreeViewD0Ev (libQt5Widgets.so.5)
                #10 0x00007face49db75d _ZN14QObjectPrivate14deleteChildrenEv (libQt5Core.so.5)
                #11 0x00007face5707535 _ZN7QWidgetD2Ev (libQt5Widgets.so.5)
                #12 0x00007face5804aca _ZN9QGroupBoxD0Ev (libQt5Widgets.so.5)
                #13 0x00007face49db75d _ZN14QObjectPrivate14deleteChildrenEv (libQt5Core.so.5)
                #14 0x00007face5707535 _ZN7QWidgetD2Ev (libQt5Widgets.so.5)
                #15 0x000055bfa5402081 _ZN6Player14actCreateTokenEv (cockatrice)
                #16 0x000055bfa5543134 n/a (cockatrice)
                #17 0x00007face49ddc16 _ZN11QMetaObject8activateEP7QObjectiiPPv (libQt5Core.so.5)
                #18 0x00007face56c5623 _ZN7QAction9triggeredEb (libQt5Widgets.so.5)
                #19 0x00007face56c7e46 _ZN7QAction8activateENS_11ActionEventE (libQt5Widgets.so.5)
                #20 0x00007face56c8726 _ZN7QAction5eventEP6QEvent (libQt5Widgets.so.5)
                #21 0x00007face56cbf2c _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5)
                #22 0x00007face56d3a06 _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5)
                #23 0x00007face49ae060 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5)
                #24 0x00007face4f3c339 _ZN12QShortcutMap13dispatchEventEP9QKeyEvent (libQt5Gui.so.5)
                #25 0x00007face4f3c40e _ZN12QShortcutMap11tryShortcutEP9QKeyEvent (libQt5Gui.so.5)
                #26 0x00007face4ee9f6d _ZN22QWindowSystemInterface19handleShortcutEventEP7QWindowmi6QFlagsIN2Qt16KeyboardModifierEEjjjRK7QStringbt (libQt5Gui.so.5)
                #27 0x00007face4f09da8 _ZN22QGuiApplicationPrivate15processKeyEventEPN29QWindowSystemInterfacePrivate8KeyEventE (libQt5Gui.so.5)
                #28 0x00007face4f0ef16 _ZN22QGuiApplicationPrivate24processWindowSystemEventEPN29QWindowSystemInterfacePrivate17WindowSystemEventE (libQt5Gui.so.5)
                #29 0x00007face4ee648c _ZN22QWindowSystemInterface22sendWindowSystemEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Gui.so.5)
                #30 0x00007facdb7cd4b1 n/a (libQt5XcbQpa.so.5)
                #31 0x00007face11d0270 g_main_context_dispatch (libglib-2.0.so.0)
                #32 0x00007face11d1f69 n/a (libglib-2.0.so.0)
                #33 0x00007face11d1fae g_main_context_iteration (libglib-2.0.so.0)
                #34 0x00007face4a08cd1 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
                #35 0x00007face49ac48b _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
                #36 0x00007face49b54d8 _ZN16QCoreApplication4execEv (libQt5Core.so.5)
                #37 0x000055bfa5395d28 main (cockatrice)
                #38 0x00007face3a9df6a __libc_start_main (libc.so.6)
                #39 0x000055bfa539b6ba _start (cockatrice)

Using the "view library" trick:

                Stack trace of thread 14782:
                #0  0x00007f45a6e8aa79 malloc (libc.so.6)
                #1  0x00007f45a77af0a9 _Znwm (libstdc++.so.6)
                #2  0x00007f45a7d870ac n/a (libQt5Core.so.5)
                #3  0x00007f45a7d7af9e _ZN8QVariantC2EiPKvj (libQt5Core.so.5)
                #4  0x00007f45a8d479e2 _ZN13QGraphicsItem6setPosERK7QPointF (libQt5Widgets.so.5)
                #5  0x000055f3b101f7b4 _ZN14ZoneViewWidget9moveEventEP23QGraphicsSceneMoveEvent (cockatrice)
                #6  0x00007f45a8d9a388 _ZN15QGraphicsWidget5eventEP6QEvent (libQt5Widgets.so.5)
                #7  0x00007f45a8a56f2c _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5)
                #8  0x00007f45a8a5ea06 _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5)
                #9  0x00007f45a7d39060 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5)
                #10 0x00007f45a8d9936a _ZN15QGraphicsWidget11setGeometryERK6QRectF (libQt5Widgets.so.5)
                #11 0x00007f45a8d9e31a n/a (libQt5Widgets.so.5)
                #12 0x00007f45a8d9a1e9 _ZN15QGraphicsWidget10itemChangeEN13QGraphicsItem18GraphicsItemChangeERK8QVariant (libQt5Widgets.so.5)
                #13 0x00007f45a8d47a77 _ZN13QGraphicsItem6setPosERK7QPointF (libQt5Widgets.so.5)
                #14 0x000055f3b101f7b4 _ZN14ZoneViewWidget9moveEventEP23QGraphicsSceneMoveEvent (cockatrice)
                #15 0x00007f45a8d9a388 _ZN15QGraphicsWidget5eventEP6QEvent (libQt5Widgets.so.5)
                #16 0x00007f45a8a56f2c _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5)
                #17 0x00007f45a8a5ea06 _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5)
                #18 0x00007f45a7d39060 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5)
                #19 0x00007f45a8d9936a _ZN15QGraphicsWidget11setGeometryERK6QRectF (libQt5Widgets.so.5)                                                                                                                           
                #20 0x00007f45a8d9e31a n/a (libQt5Widgets.so.5)                                                                                                                                                                   
                #21 0x00007f45a8d9a1e9 _ZN15QGraphicsWidget10itemChangeEN13QGraphicsItem18GraphicsItemChangeERK8QVariant (libQt5Widgets.so.5)                                                                                     
                #22 0x00007f45a8d47a77 _ZN13QGraphicsItem6setPosERK7QPointF (libQt5Widgets.so.5)                                                                                                                                  
                #23 0x000055f3b101f7b4 _ZN14ZoneViewWidget9moveEventEP23QGraphicsSceneMoveEvent (cockatrice)                                                                                                                      
                #24 0x00007f45a8d9a388 _ZN15QGraphicsWidget5eventEP6QEvent (libQt5Widgets.so.5)                                                                                                                                   
                #25 0x00007f45a8a56f2c _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5)                                                                                                             
                #26 0x00007f45a8a5ea06 _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5)                                                                                                                            
                #27 0x00007f45a7d39060 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5)                                                                                                                 
                #28 0x00007f45a8d9936a _ZN15QGraphicsWidget11setGeometryERK6QRectF (libQt5Widgets.so.5)                                                                                                                           
                #29 0x00007f45a8d9e31a n/a (libQt5Widgets.so.5)                                                                                                                                                                   
                #30 0x00007f45a8d9a1e9 _ZN15QGraphicsWidget10itemChangeEN13QGraphicsItem18GraphicsItemChangeERK8QVariant (libQt5Widgets.so.5)                                                                                     
                #31 0x00007f45a8d47a77 _ZN13QGraphicsItem6setPosERK7QPointF (libQt5Widgets.so.5)                                                                                                                                  
                #32 0x000055f3b101f7b4 _ZN14ZoneViewWidget9moveEventEP23QGraphicsSceneMoveEvent (cockatrice)                                                                                                                      
                #33 0x00007f45a8d9a388 _ZN15QGraphicsWidget5eventEP6QEvent (libQt5Widgets.so.5)                                                                                                                                   
                #34 0x00007f45a8a56f2c _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5)                                                                                                             
                #35 0x00007f45a8a5ea06 _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5)                                                                                                                            
                #36 0x00007f45a7d39060 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5)                                                                                                                 
                #37 0x00007f45a8d9936a _ZN15QGraphicsWidget11setGeometryERK6QRectF (libQt5Widgets.so.5)                                                                                                                           
                #38 0x00007f45a8d9e31a n/a (libQt5Widgets.so.5)                                                                                                                                                                   
                #39 0x00007f45a8d9a1e9 _ZN15QGraphicsWidget10itemChangeEN13QGraphicsItem18GraphicsItemChangeERK8QVariant (libQt5Widgets.so.5)                                                                                     
                #40 0x00007f45a8d47a77 _ZN13QGraphicsItem6setPosERK7QPointF (libQt5Widgets.so.5)                                                                                                                                  
                #41 0x000055f3b101f7b4 _ZN14ZoneViewWidget9moveEventEP23QGraphicsSceneMoveEvent (cockatrice)                                                                                                                      
                #42 0x00007f45a8d9a388 _ZN15QGraphicsWidget5eventEP6QEvent (libQt5Widgets.so.5)                                                                                                                                   
                #43 0x00007f45a8a56f2c _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5)                                                                                                             
                #44 0x00007f45a8a5ea06 _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5)                                                                                                                            
                #45 0x00007f45a7d39060 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5)                                                                                                                 
                #46 0x00007f45a8d9936a _ZN15QGraphicsWidget11setGeometryERK6QRectF (libQt5Widgets.so.5)                                                                                                                           
                #47 0x00007f45a8d9e31a n/a (libQt5Widgets.so.5)                                                                                                                                                                   
                #48 0x00007f45a8d9a1e9 _ZN15QGraphicsWidget10itemChangeEN13QGraphicsItem18GraphicsItemChangeERK8QVariant (libQt5Widgets.so.5)                                                                                     
                #49 0x00007f45a8d47a77 _ZN13QGraphicsItem6setPosERK7QPointF (libQt5Widgets.so.5)                                                                                                                                  
                #50 0x000055f3b101f7b4 _ZN14ZoneViewWidget9moveEventEP23QGraphicsSceneMoveEvent (cockatrice)                                                                                                                      
                #51 0x00007f45a8d9a388 _ZN15QGraphicsWidget5eventEP6QEvent (libQt5Widgets.so.5)                                                                                                                                   
                #52 0x00007f45a8a56f2c _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5)                                                                                                             
                #53 0x00007f45a8a5ea06 _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5)                                                                                                                            
                #54 0x00007f45a7d39060 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5)                                                                                                                 
                #55 0x00007f45a8d9936a _ZN15QGraphicsWidget11setGeometryERK6QRectF (libQt5Widgets.so.5)                                                                                                                           
                #56 0x00007f45a8d9e31a n/a (libQt5Widgets.so.5)                                                                                                                                                                   
                #57 0x00007f45a8d9a1e9 _ZN15QGraphicsWidget10itemChangeEN13QGraphicsItem18GraphicsItemChangeERK8QVariant (libQt5Widgets.so.5)                                                                                     
                #58 0x00007f45a8d47a77 _ZN13QGraphicsItem6setPosERK7QPointF (libQt5Widgets.so.5)                                                                                                                                  
                #59 0x000055f3b101f7b4 _ZN14ZoneViewWidget9moveEventEP23QGraphicsSceneMoveEvent (cockatrice)                                                                                                                      
                #60 0x00007f45a8d9a388 _ZN15QGraphicsWidget5eventEP6QEvent (libQt5Widgets.so.5)                                                                                                                                                   #61 0x00007f45a8a56f2c _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5)                                                                                                             
                #62 0x00007f45a8a5ea06 _ZN12QApplication6notifyEP7QObjectP6QEvent (libQt5Widgets.so.5)                                                                                                                            
                #63 0x00007f45a7d39060 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5)                                                                                                                 

I did not try fishing for more ways to make it crash.

**Comment by ZeldaZach** [comment]
dupe and fixed
