### ISSUE TITLE
Activation Email Not Received

### ISSUE THREAD

**Issue by MightyOneT** [Cockatrice/Cockatrice#2902]
For some reason I did not receive an activation email, therefore I also did not receive an activation token. There doesn't appear to be a way to have another email resent. Can you fix this? My account name was Onet

__________

*Explain your issue/request/suggestion in detail here!*

**Comment by Daenyth** [comment]
We don't run a server, this site is for issues with the software itself. Please contact the server admin

**Comment by MightyOneT** [comment]
Hi Gavin,

Thank you for responding so swiftly. Do you have the contact details to do
that? I cant seem to find any.

Regards,
Mathew.

**Comment by Nightfirecat** [comment]
We don't really have a way to relay that to you without knowing what server you played on... I'd recommend checking the website for that server.

Assuming you were playing on the default suggested server (Woogerworks), you can reach them on Twitter (https://twitter.com/woogerworks) or by using the contact form on their website: http://woogerworks.com

**Comment by tooomm** [comment]
We have all servers that we know of listed in our wiki (you find links to their websites and/or twitter and the people responsible for them in the [Public Server list](https://github.com/Cockatrice/Cockatrice/wiki/Public-Servers) there). Check that out @MightyOneT!

**Comment by skwerlman** [comment]
i feel like we answer this enough that a note in the issue template would be helpful

**Comment by tooomm** [comment]
Just found out that you can setup a `Saved Reply` on github to have a helpful answer at hand. I'm doing so right now.

With the planned + new `Connect to Server` dialog this reports should vanish hopefully! :)

With the template, every legit bug reporter or feature requester would need to delete that note to keep his post clean. It should be better to direct them to the correct spot right away from client.

**Comment by tooomm** [comment]
Actually there should be a simple little hint right now too (as a workaround):
![contact](https://user-images.githubusercontent.com/9874850/31954611-59cde448-b8e6-11e7-8aa3-9c08b141535d.png)

A similar hint should be placed in the `Register to server` dialog as well!
