### ISSUE TITLE
Unable to receive activation code via email for cockatrice @ woogerworks

### ISSUE THREAD

**Issue by agreenspan** [Cockatrice/Cockatrice#2903]
Never received an email with my code. Can't connect to server. Help?

**Comment by skwerlman** [comment]
This repo is for the Cockatrice software itself, not any of the servers.

Please contact your server's administrator. You can find the contact info for several server admins here: https://github.com/Cockatrice/Cockatrice/wiki/Public-Servers

**Comment by tooomm** [comment]
In your case for woogerworks, you find a link to his webpage (http://woogerworks.com/) in the Public Server list linked above. He has a contact formular there, or reach out to him on his twitter!

He should be able to help you. But first, make sure to check your spam folder, too. ;)
