### ISSUE TITLE
tablerow parsing error

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2904]
>Doubling clicking on treasure map puts it in the land row instead of the noncreature and nonland row.

Looking at my `cards.xml` file I get this:
```
     <card>
            <name>Treasure Map</name>
            <set rarity="Rare" muId="435410" num="250a">XLN</set>
            <related attach="attach">Treasure Cove</related>
            <manacost>2</manacost>
            <cmc>2</cmc>
            <type>Artifact</type>
            <tablerow>0</tablerow>
            <text>{1}, {T}: Scry 1. Put a landmark counter on Treasure Map. Then if there are three or more landmark counters on it, remove those counters, transform Treasure Map, and create three colorless Treasure artifact tokens with &quot;{T}, Sacrifice this artifact: Add one mana of any color to your mana pool.&quot;</text>
      </card>
```

Which is a mistake in Oracle parsing of mtgjson I guess. Tablerow needs to be `1`.

**Comment by Psithief** [comment]
(Speculation ahead.)
It's the "add … to your mana pool" part. The current parser has no understanding of granted abilities, I imagine.

Alternatively, _it does_ but expects quotes to be normalised, not `&quot;`.

**Comment by ctrlaltca** [comment]
> (Speculation ahead.)
> It's the "add … to your mana pool" part. The current parser has no understanding of granted abilities, I imagine.

You are right, the check is implemented here: https://github.com/Cockatrice/Cockatrice/blob/master/oracle/src/oracleimporter.cpp#L91

Artifacts that contains a "tap" symbol and the sentence "to your mana pool" are treated as lands, and end up on tablerow 0.

If anyone has an idea on how to make this check better without breaking all the other cards, i'll be glad to implement it

**Comment by Nightfirecat** [comment]
Perhaps a regex of this sort, utilizing a negative lookahead? `/to your mana pool.(?>&quot;)/`

Example with a few test cases: https://regexr.com/3h33n

**Comment by Psithief** [comment]
No, such a regex definitely cannot end with a period. That would break mana batteries.
I don't think this can be done with just a simple regex. What we want is the ability to remove any text between a **pair** of `&quot;`, and then check for the match on whatever's left.

Then the criteria for a regex would be something more along the lines of:  
`{T}`, any text that's not a line break, `to your mana pool`

Currently affected cards:

- Paradise Mantle
- Prying Blade
- Treasure Map
