### ISSUE TITLE
Contact hint in connect dialog - prevent recurring server issue reports

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2906]
Help the user better in finding support with
- Problems connecting to their server of choice
- Problems with registering
- Problems with bans etc.

A very quick and helpful solution for now would be a little "hint" area in the `Connect` and `Register` dialog.

![contact](https://user-images.githubusercontent.com/9874850/31954611-59cde448-b8e6-11e7-8aa3-9c08b141535d.png)
Mockup from https://github.com/Cockatrice/Cockatrice/issues/2902#issuecomment-339044240

**Comment by Daenyth** [comment]
Once we get the server status stuff in this will be easier

**Comment by Daenyth** [comment]
Oh but a static link is a good first step - I was thinking to show link to the person's site and email

**Comment by tooomm** [comment]
It's just to get people covered for now and link to the specific wiki page, yes. Hopefully we don't need it later. :)

But the rewrite will take time, and this is something the users (and we) benefit from immediately since it's a small change with no big effort. That's why I opened the issue and hope for a earlier consideration. 👍 
The sooner the new login/register dialog is done, the better. But realistically it could be 6-12 month easily, haha.

**Comment by Vafthrudnir** [comment]
With the [JSON](https://cockatrice.github.io/public-servers.json) file up we could display the site linked for the selected server.

**Comment by tooomm** [comment]
@Vafthrudnir see also https://github.com/Cockatrice/Cockatrice/issues/742

**Comment by Daenyth** [comment]
That's of course the one I meant to link to... 742 being the general concept / ui mockup, and 2474 being a spec for a protocol enhancement that would support the desired behavior of 742
