### ISSUE TITLE
Cockatrice Archenemy Database is Incomplete

### ISSUE THREAD

**Issue by Zenthelm** [Cockatrice/Cockatrice#2907]
Win 10
Cockatrice version 2.3.17

__________

I noticed that the card database that Cockatrice uses does not include the promotional Archenemy Schemes:
Perhaps you have met my Cohort
Plot that spans Centuries
Your inescapable Doom
Imprision this Insolent Witch
Drench the Soil in their Blood

I have tried enabling all sets and cards and searching for them with no success. Hope this helps complete database and isn't too much trouble to update!

**Comment by tooomm** [comment]
We pull our card data from [`mtgjson` project](https://github.com/mtgjson/mtgjson). Can you open the issue there, please?

Thank you! 💓
