### ISSUE TITLE
There are new bad thing for me,which is use cockatric by mac

### ISSUE THREAD

**Issue by my9281** [Cockatrice/Cockatrice#2908]
I start a windows computer and this IMac connet my chcoatric service machine. the connet of Imac is droped when the windows is connetting as normal.
I bougth an IMac mini to write code on Xcode in work.Ususally I write some thing on windows or some other operating system. I no good at use MacOS.
So， Is it by Mac setting wrong?

**Comment by my9281** [comment]
In client on mac,It show a messagebox for me  'XXX...is error'……I don't know what XXX means. the XXX not only can means 'interface', but also can means 'port'.

**Comment by tooomm** [comment]
>I start a windows computer and this IMac connet my chcoatric service machine. the connet of Imac is droped when the windows is connetting as normal.

Do you try to login from windows and mac at the same time with the same account?

>In client on mac,It show a messagebox for me 'XXX...is error'……I don't know what XXX means. the XXX not only can means 'interface', but also can means 'port'.

Please post a picture of the error you are seeing!

**Comment by ctrlaltca** [comment]
Feel free to reopen when you have the following informations:
 * cockatrice version (from about "cockatrice menu")
 * macOS version
 * a screenshot of the error, or the exact message you see.
