### ISSUE TITLE
Problem using User Provisioning API 

### ISSUE THREAD

**Issue by LuisEulacioUCAB** [Cockatrice/Cockatrice#2911]
Hi this is my first post I’m new using nextcloud and I have an inconvenient one when creating user from my script.

This is my script:

```php
require (‘vendor/autoload.php’);
$client = new \GuzzleHttp\Client();
$res = $client->request(‘POST’, ‘http://admin:adminpass@localhost/ocs/v1.php/cloud/users -d userid=“Frank” -d password=“frankspassword”’ -H “Content-Type: application/x-www-form-urlencoded” -H “OCS-APIRequest:true”’ );

echo $res->getBody();

```

and he always gives me this mistake:

failure 998 Invalid query, please check the syntax. API specifications are here: http://www.freedesktop.org/wiki/Specifications/open-collaboration-services. DEBUG OUTPUT:

Why this is happening?

**Comment by skwerlman** [comment]
Are you sure you posted this in the correct repo? This repo is for Cockatrice, a TCG emulator.
