### ISSUE TITLE
32-bit version

### ISSUE THREAD

**Issue by SilverHawk1015** [Cockatrice/Cockatrice#2913]
<b>OS:</b>
Win 7 32-bit

<b>Cockatrice version:</b>
N/A

__________

Is there a 32-bit version for Windows 7?

**Comment by Nightfirecat** [comment]
Yes. Don't know why it doesn't list it as an option on the github.io page, but it's listed on the actual release: https://github.com/Cockatrice/Cockatrice/releases/tag/2017-05-05-Release-2.3.17

**Comment by tooomm** [comment]
If you have any trouble installing the 32 version from the link above let us know! @SilverHawk1015 

It's quite unusual to still be dependent on that "outdated" architecture only. That's why we don't have a direct link on the main page anymore. We still provide it, but don't advertise it there.
