### ISSUE TITLE
cards

### ISSUE THREAD

**Issue by AlexandersHamilton** [Cockatrice/Cockatrice#2914]
<b>OS:</b>
*Put your operating system here! For example: "Win 7 SP2", "macOS 10.12.3", "Ubuntu 16.10" etc.*

<b>Cockatrice version:</b>
*Put your Cockatrice version number & build date here! For example: "2d53ce9 (2016-02-18)"
You find them inside the app under `Help → About Cockatrice` (Windows & Linux), or `Cockatrice → About Cockatrice` (macOS).*

__________
i cannot see the cards picture nor its effect all i can see is its name and its place on the field from the new expansion 

*Explain your issue/request/suggestion in detail here!*

**Comment by ZeldaZach** [comment]
Please re-run Oracle. That should solve this issue
