### ISSUE TITLE
database schema and queries optimization

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2916]
As written down by @d5c4b3 here: https://github.com/Cockatrice/Cockatrice/issues/2835#issuecomment-323081180

>**Database Schema**
>    - ~~Work on this issue, #2835, and #2218~~ / done in https://github.com/Cockatrice/Cockatrice/pull/2915
>    - Work on #865 (I've had problems with this one)
>    - Make sure foreign key constraints are being used
>    - Potentially build stored procedures for complex queries
>    - Potentially build views for complex queries
>
>**Queries**
>    - Work on #2303
>    - Verify the speed of queries
>    - Modify them to work with any schema changes I make
>    - Verify that common security measures are in place (At a cursory glance they look right)

Keeping in mind that we would like to move to postgres too.

**Comment by ctrlaltca** [comment]
This is basically a metabug for #2835, #2218, #865 and #2303.
Closing in favor of the more specific issues.
