### ISSUE TITLE
deployment from ci is tagging all relases as prerelease

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2921]
Either appveyor or travis (both?) are resetting the release notes while updating the beforehand published release (uploading their release artifacts).

If you can provide more details I could have a look @ZeldaZach 
- Is all text purged? Is it replaced with some other text (like `Dev build of Cockatrice`)?
- Do you fully release the draft first? Or do you publish it as pre-release?

**Comment by ZeldaZach** [comment]
All text is purged and replaced w/ Dev build phrase. I publish as a full release and it moves it to pre-release. After it's done with the uploads I re-upload the release notes and publish as full.

**Comment by tooomm** [comment]
Ok, we can improve that.
Parts of it are still based on older release handling... I guess it was used for development snapshots as well regarding the phrase.
Also, travis and appveyor handle things a bit different. There might always be little conflicts because both have to deal with the same release on GitHub.

>All text is purged and replaced w/ Dev build phrase.

Shouldn't happen anymore with https://github.com/Cockatrice/Cockatrice/pull/2976
Let's test it with the next `-beta1` you're going to release sooner than later! ;)

>I publish as a full release and it moves it to pre-release. 

Right now it needs to be a bit generic because it has to work for stable and beta releases, they use the same deploy config. Therefore it's better to move both to `Pre-release` and manually correct stable releases than having all beta releases going to stable automatically.

<br>

To get it right, and have proper configuration options for both release types - `Beta` and `Stable` - we need to setup a second deploy provider and run specific commands based on different conditions.
I hope we can use the git tag, check if it contains `beta` for example and use the second deploy provider with its own config on that condition.
Name info for the git tag is already there with `APPVEYOR_REPO_TAG_NAME` and `TRAVIS_TAG`.
I'll try to check that.
