### ISSUE TITLE
host closes connection dialog improvements

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2926]
![host_closed_conn](https://user-images.githubusercontent.com/9874850/33099162-405cd20e-cf10-11e7-91bb-610c30781f6d.png)

This message should have two buttons for a better user experience and more logical workflows!
- `Reconnect`: Opens connect dialog (like it does now if you hit the single available `Ok` button)
- `Ok`: Closes the dialog

<br>

What do you want to do after you idled for a while and get back to your pc?
- stop playing:
    - click `Ok`
    - click `Cancel`
    - click `Ok` for a second time because of https://github.com/Cockatrice/Cockatrice/issues/2925
- go on playing:
    - click `Ok`
    - type credentials
    - click `Connect`

Scenario 1 would be shortened to clicking `Ok` only once.
Scenario 2 wouldn't change - you just click the more obvious `Reconnect` instead.

**Comment by woogerboy21** [comment]
Im confused on this.  If you click ok this screen you can simply reconnect by using the connect dialogue.  Which I believe is the behavior your looking for is it not?

**Comment by tooomm** [comment]
>Im confused on this. If you click ok this screen you can simply reconnect by using the connect dialogue. Which I believe is the behavior your looking for is it not?

@woogerboy21 As stated above, "Scenario 2 (which is the one you describe) **wouldn't change** - you just click the more obvious `Reconnect` (re-labeled button) instead (Ok)."

But many times you come back to the PC after a longer period of time, because live needed your attention. Maybe you just come back to work on other things or shut the computer down for example. Or sometimes you even forgot that Cockatrice was still running in the background...
So you don't want or can't continue to play. (Scenario 1)
The workflow for this would be improved and simplified with my suggestion.

**Comment by ZeldaZach** [comment]
I'm fine with it as-is.
