### ISSUE TITLE
Double click to play isn't always recognized

### ISSUE THREAD

**Issue by JineteDV** [Cockatrice/Cockatrice#2928]
<b>OS: macOS 10.12.6</b>

<b>Cockatrice version: 2.4.0 (2017-11-19)</b>
__________

Has been something I've noticed when trying to double click on a card to play it. For now it seems to be random and this has happened multiple times in games over different days, none of which I felt like I was lagging. For now it happens 2-3 times in a game, it'll just stay in my hand after being double clicked on.

**Comment by woogerboy21** [comment]
Im thinking some one angrily hulked there mouse one to many times ....

**Comment by JineteDV** [comment]
I hadn't adjusted my mouse settings for several months before this. After trying to adjust the settings from more to less sensitive the same nonregistering of the double click persists.

**Comment by woogerboy21** [comment]
I was just jokingly making a comment, honestly it could be many things that could cause this but I doubt it to be code related (been wrong before and probably will be again).  For example, I have a mouse that doesnt register double clicks every time.  Happens inside just about any application I use it on.  Ive had similar behavior happen with mice that are wireless when the batteries are running low, or if the device (being wireless) has interruption by other frequency related issues such as to many bluetooth connections overwhelming the bluetooth adaptor being used.

**Comment by JineteDV** [comment]
Wired mouse. I haven't felt it dropping double clicks in any other program though no other program I use often requires double clicking as often as cockatrice.
