### ISSUE TITLE
Flipping creature face-up doesn't show power / toughness

### ISSUE THREAD

**Issue by JoshuaLamusga** [Cockatrice/Cockatrice#2929]
<b>OS: Windows 10 Home</b>
<b>Cockatrice version: 2.3.17 (2017-05-05)</b>
__________

Playing a creature card face down during gameplay, then flipping it face up will not display the power and toughness of that creature. To be clear, you have to play it from your hand face down; the bug does not occur if you play a creature and then flip it face-down.

**Comment by skwerlman** [comment]
That sounds like a bug in MTGJSON, which is what cockatrice uses to get card data. You can file an issue with them here: https://github.com/mtgjson/mtgjson/issues

**Comment by tooomm** [comment]
Does the p/t value display in the deck editor for you?

**Comment by JoshuaLamusga** [comment]
A second test did not repeat the results I thought I was getting, so I found one that does. Playing a creature face-down and flipping it will not show its power/toughness. I think I was toying with the interface and did this in the first place. I've modified the question.

**Comment by tooomm** [comment]
Ok, thanks for letting us know.

That is a bit similar to https://github.com/Cockatrice/Cockatrice/issues/1882, so I link that here.
