### ISSUE TITLE
Add card from list in deck editor directly to sideboard

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2930]
There is a button for that. That's being said...
But unlike you can switch a card between main deck and sideboard in your
decklist with <kbd>shift</kbd>+<kbd>double click</kbd>.
You can't directly add a card from the card list in deck editor with <kbd>shift</kbd>+<kbd>double click</kbd> to your sideboard.

Since you can use double click to add a card to your main deck, it would be cool to use shift+double click to add cards to your sideboard. Especially since users are used to it from card handling in the decklist.

**Comment by ZeldaZach** [comment]
This exists already. On mac it's Command + Click. I forget the win/lin combo, but they exist.

**Comment by tooomm** [comment]
You are right! Must have missed that... :D
It's `Ctrl + Click` on Windows!
