### ISSUE TITLE
Better way of dealing with repeating tokens

### ISSUE THREAD

**Issue by joshudson** [Cockatrice/Cockatrice#2934]
OS: Debian

Cockatrice version: Version 2.4.0 (2017-11-19) 4d641eb0e

Stack tokens deeper than 3?
![screenshot_20171201_203144](https://user-images.githubusercontent.com/16249210/33511801-4f3c2292-d6d7-11e7-9bca-22fa4d701835.png)

I have 3 Verdant Force (!) tokens and way too many Saproling tokens. The UI is having problems.

**Comment by tooomm** [comment]
Linking https://github.com/Cockatrice/Cockatrice/issues/2224

**Comment by Daenyth** [comment]
At that point I start using counters on top of 1 or 2 tokens personally,
the same way I would in person.

**Comment by ZeldaZach** [comment]
I agree w/ Dae's solution. There's nothing really wrong with the way things are done w/ tokens at this point.

If someone has a better solution, please feel free to re-open!
