### ISSUE TITLE
Export replays to videos

### ISSUE THREAD

**Issue by danyfire** [Cockatrice/Cockatrice#2936]
My Issue is not really an issue.
I was wondering if it was possible in the future to export the replays into videos as a feature ?

Thx

**Comment by ZeldaZach** [comment]
Replays are a move-by-move recreation of the game state. You can use a screen recording software to create a video, at least for now. I don't think this is something we'd be looking into in the near future though

**Comment by Daenyth** [comment]
This is a good suggestion but I think it's not worth it to implement because of the cost in code vs utility - a screen recorder would be able to do a lot better than we could, and we have too few developers able to contribute as is

**Comment by danyfire** [comment]
Could there be a way to manually move to a moment in the replay, instead of activating the fast play option and wait for the moment we want to watch ?

**Comment by Daenyth** [comment]
In theory yes. In practice this will be difficult for us to implement. This has been asked for before I'm fairly sure.

In the short time, speed control would be easier to implement than anything else. Right now it's a hardcoded speed of X time between each game event IIRC

**Comment by tooomm** [comment]
There could be an even quicker speed maybe, let's say `1x`, `2x` and `4x`.

Check this issue for jump marks which should help with speeding forward to a certain moment @danyfire: https://github.com/Cockatrice/Cockatrice/issues/2933
