### ISSUE TITLE
send deck to tappedout.net: aftermath cards not displayed correclty

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2942]
<b>OS:</b>
Win 10

<b>Cockatrice version:</b>
Client Version: 2.4.1-custom_c8e843d (2017-12-05)

__________

Looking at this deck (http://tappedout.net/mtg-deckpaste/05-12-17-akh-pre-release-deck/) you see that `Mouth // Feed` is displayed as `Mouth / Feed` and is correctly linked.
It looks like tappedout uses this naming convention for all aftermath cards: http://tappedout.net/mtg-card/mouth-feed/ instead the double slash "//" to separate both halves.

If you send a deck with a aftermath card to them though, it will show up only with the first half's name!
I had to manually edit the list on their page to find out about their naming convention.
If you check for the card `Start // Finish` in the same decklist, you'll see and understand. It only shows as `Start` and links to only that part of the card (the picture is correct though).
In the edit mode it also only shows `Start`.

**So for tappedout.net we need to send aftermath cards with a slighlty different name. `/` instead `//`**
Or maybe we just send the first name at all?

This might be an general split card issue. Did not test with former ones.

**Comment by KBGrammer** [comment]
I've been using cockatrice for a while and haven't contributed in here yet and wanted to give it a shot with something simple.

This issue looks like it affects every split card. TappedOut is a little inconsistent with whether it appears as "Side1/Side2" or "Side1 / Side2", but it ends up not causing a problem if you feed it "Side1 / Side2" for everything.

I have a fix ready that works for all black bordered split cards. If I try to run it with Who // What // When // Where // Why, then I get an "Unable to analyze the deck" error, and I'm not sure why.

**Comment by tooomm** [comment]
Hey @KBGrammer, cool! Welcome :)

Do you know about our [Gitter channel](https://github.com/Cockatrice/Cockatrice#get-involved-)? Check it out and join us there! Makes life easier... :)

Otherwise it's generally helpful if you open a PR with what you have working. It gets tested on our CI then and people can easily see the changes + give it a run. Troubleshooting isn't really possible without that.
