### ISSUE TITLE
remove all &-type shortcuts

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2943]
- @ZeldaZach doesn't like them. :)
- Translators don't like them and can easily mess them up
- They are of not too much use in terms of accessability
- They are not used consistently or have repeated values within a menu
- They got somehow replaced with the new customizable shortcuts. No doubled features needed

Objections?

**Comment by Daenyth** [comment]
No.

- Translate correctly
- They are not used a ton, but they also are about no effort to add
- Repeated values should be fixed, but that's a very easy fix.
- They don't serve the same purpose as shortcuts - they let you quick select an option from a context menu, not fire off a specific action from outside menus

**Comment by tooomm** [comment]
So you have to add them back in while https://github.com/Cockatrice/Cockatrice/pull/2938 is hot @jrobe ;)
[Zach's opinion](https://gitter.im/Cockatrice/Cockatrice?at=5a274468ba39a53f1a258bf7) overruled.

**Comment by Daenyth** [comment]
It's fine, we don't *need* them - use your judgement and add as needed. There's just no need to go removing them. @jrobe's PR is fine as is. Let's not dick around new contributors on stuff that's not very important please.

**Comment by jrobe** [comment]
The other two online services didn't have them, so I'll keep them out :) - no worries.
