### ISSUE TITLE
split card from UNH has wrong name in cards.xml database

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2947]
This got spotted in a recent PR (https://github.com/Cockatrice/Cockatrice/pull/2944) by @KBGrammer:

Oracle assembles the card [`Who/What/When/Where/Why`](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=74358) from its several pieces/sides out of mtgjson.
But it uses the same schema as for all other split cards, that's why it ends up in the *cards.xml* database as
`Who // What // When // Where // Why`:

```
<card>
            <name>Who // What // When // Where // Why</name>
            <set rarity="" muId="74358" num="120a">UNH</set>
            <color>W</color>
            <color>R</color>
            <color>U</color>
            <color>B</color>
            <color>G</color>
            <manacost>XW // 2R // 2U // 3B // 1G</manacost>
            <cmc>1 // 3 // 3 // 4 // 2</cmc>
            <type>Instant // Instant // Instant // Instant // Instant</type>
            <tablerow>3</tablerow>
            <text>Target player gains X life.

---

Destroy target artifact.

---

Counter target creature spell.

---

Destroy target land.

---

Destroy target enchantment.</text>
        </card>
```

This leads to follow up problems like the `Send to online service --> Analyze deck (tappedout.net)` not recognizing the card and simply returning an error for all request for example.
Every other service you use to copy your deck list to, most likely has the same problem if they use the cards real name.

**Comment by KBGrammer** [comment]
I will take a stab at this one this evening. I think the correct way to do it is to just make a single card exception and edit this specific card name after it's generated, since no other card works this way.

**Comment by tooomm** [comment]
To avoid having the card name in the code, and potentially catch more of these cards in future fun sets...
Would it be reasonable to check for the amount of card sides (`names`) that are going to be combined and use a different scheme for cards with more than 2?
(for layout `split`, because layout `melt` will have 3 `names` there already)

I can't imagine wizards will always print cards which consist out of ~4 parts in a normal set.
Maybe they want to print `Rock/Paper/Scissors` for the next UN set, haha. ;D

**Comment by KBGrammer** [comment]
Sure, I'll make it something more general so that there's no card name in the code.

Whatever the fix is, it'll probably have to be revisited when they print transform instants/sorceries with fuse in un-set 4 anyway.
