### ISSUE TITLE
no easy way to check if installed version is 32 or 64bit

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2948]
In the client updater we also check already for which architecture the package was compiled for I guess.
It would be nice to expose that information in the `About` window next to the version number, too.

Very helpful for troubleshooting instead trying to find other indicators to make sure.

**Comment by Daenyth** [comment]
Yes this should be in the about screen

**Comment by KBGrammer** [comment]
I have something that works in linux for this and it uses QT defines, so I expect it would work in Windows. I'll make a PR.

**Comment by tooomm** [comment]
@KBGrammer Nice! 👍 
For the updater we use something from here to detect the compiled version, would have to look at to code to tell exactly which one... http://doc.qt.io/qt-5/qsysinfo.html

**Comment by KBGrammer** [comment]
Alright, I'll make it consistent with that and make a PR later today.
