### ISSUE TITLE
Pasting deck from clipboard doesn't merge duplicate cards in the deck

### ISSUE THREAD

**Issue by JoshuaLamusga** [Cockatrice/Cockatrice#2951]
**1.** When pasting a deck from the clipboard (Ctrl + Shift + V), if the clipboard contains multiple copies of a card, those are added as independent entries to the deck, rather than being merged. For example,
`1x Abbey Gargoyles`
`1x Abbey Gargoyles`
is not merged into `2x Abbey Gargoyles`. Instead, an entry in the deck is created for each one as if they were different cards.

**Comment by JoshuaLamusga** [comment]
When I first used Cockatrice, there appeared to be an issue with lowercased card names, however I have not seen this issue reappear and I'm staring at the code and I don't think it will re-appear.

**Comment by tooomm** [comment]
This is also true when loading an altered ,cod or .txt deck files.
As long as a card shows up in separate lines in main or sideboard, that get's replicated and not merged.

**Comment by Daenyth** [comment]
@JoshuaLamusga Sounds right. The card name must be an exact character-for-character match, but we added a "simplified" name property in the code that normalizes the name to lowercase and strips punctuation etc that we use in some places like `[[cardname]]` so users can be less specific

**Comment by Daenyth** [comment]
Also I believe the deck hash code should not be affected by this because each card is expanded to one copy per line before performing the hashing

**Comment by tooomm** [comment]
Good call with the deck hash! Something we need to check, yes. 👍

**Comment by ZeldaZach** [comment]
Dupe of #4019 ( I know this is older, but we're tracking new to old)
