### ISSUE TITLE
rarity filter improvements

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2952]
The **rarity filter** right now only works if you type the full rarity name without misspelling to make it find cards:
`common`, `uncommon` , ` rare`, `mythic rare` (or `special`)

Same like with color filter, where you can [type <kbd>c</kbd> to search for colorless](https://github.com/Cockatrice/Cockatrice/pull/2737), it should allow to search rarity with only `c`, `u`, `r`, `m`/ `mr` (and `s`)!

---

Something similar could apply to the card type filter as well maybe (not subtypes, only main):
`a`rtifact, `i`nstant, `c`reature, `s`orcery, `l`and, `e`nchantment, `p`lanswalker ...

**Comment by ZeldaZach** [comment]
Will look into this!

**Comment by JoshuaLamusga** [comment]
Well, what we really need is a suggestions box to pop up as you start typing for a lot of things, the way Gatherer does it.

**Comment by tooomm** [comment]
@JoshuaLamusga that would be a even better solution, hehe. 👍 

Same as when you type a shortcut into the rarity filter (e.g. `u`), it should show `uncommon` in the list of applied filters for a better overview...
Otherwise you see a lot of letters in your applied filter list and it's a bit more difficult to manage them.
