### ISSUE TITLE
clear filters button resets card list even if there is a search entered

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2953]
Confusing and problematic part is that the search isn't resetted or reapplied.

So it should either:
- a) apply the same entered search to the changed card list (because filters changed)
- b) or clear the search bar as well to make clear that there is no search applied any longer

**Comment by ZeldaZach** [comment]
I consider the search bar a "shortcut" filter, so I'll fix this and just flush that bar
