### ISSUE TITLE
Cannot sideboard unrecognized cards

### ISSUE THREAD

**Issue by JoshuaLamusga** [Cockatrice/Cockatrice#2954]
Loading a deck from the clipboard can create invalid cards like `2x Example`, which is useful so you know which cards failed to import. I don't know if it's relevant for custom cards, but trying to put an unknown card like `Example` in the sideboard will cause it to cease to exist instead.

To reproduce:
1. Copy a deck with bogus card names to the clipboard.
2. Open a deck builder tab and press Ctrl + Shift + V to make a deck from it.
3. Try to sideboard one of the cards (double-clicking it or by selecting it and pressing S).

**Comment by JoshuaLamusga** [comment]
I don't know if there's any compatibility-related reasons for preserving unknown cards, so I submitted this issue to be sure. If pasted decks only preserve invalid cards to show the user which cards failed to import, then the behavior of those cards is irrelevant.

**Comment by Daenyth** [comment]
It's really useful during spoiler season, at least historically. Also it
makes it easier to use non magic stuff. We should keep it.

I'm not sure why they'd get removed if it's not main deck though
