### ISSUE TITLE
Photobucket ransom message instead of counter images

### ISSUE THREAD

**Issue by MaxPleaner** [Cockatrice/Cockatrice#2955]
There's some articles about how photobucket recently revoked the free hotlinking they'd offered for a long time. It seems Cockatrice has suffered some functionality loss as a consequence. Specifically, the default counter images repository seems doesn't work any more. There are just images like this:

![ransom](https://user-images.githubusercontent.com/5035719/33977603-85b0a730-e050-11e7-9960-061c628af47e.PNG)

**Comment by ZeldaZach** [comment]
The defaults used in client should be bundled with the service. If you changed them with custom themes or maybe the card download URL, that could be the reason

**Comment by tooomm** [comment]
It's most likely some tokens that are hosted on photobucket.
Problem is, that once you download the shown dummy image it's saved next to your other card pictures.
So even if you fix the download link or the database is updated you'll see it unless you manually delete the broken picture locally.

**Comment by Daenyth** [comment]
cc @Psithief - looks like some token urls need to be removed.

**Comment by tooomm** [comment]
@Daenyth he's on it already! https://github.com/Cockatrice/Magic-Token/pull/51
