### ISSUE TITLE
Hi my aws credentials are not working.Need to reset the credentials for the same.My Username is ajessy.

### ISSUE THREAD

**Issue by Jessy6** [Cockatrice/Cockatrice#2956]
<b>OS:</b>
*Put your operating system here! For example: "Win 7 SP2", "macOS 10.12.3", "Ubuntu 16.10" etc.*

<b>Cockatrice version:</b>
*Put your Cockatrice version number & build date here! For example: "2d53ce9 (2016-02-18)"
You find them inside the app under `Help → About Cockatrice` (Windows & Linux), or `Cockatrice → About Cockatrice` (macOS).*

__________

*Explain your issue/request/suggestion in detail here!*

**Comment by ZeldaZach** [comment]
I think you’re in the wrong place. We’re not AWS, try checking Amazons website?
