### ISSUE TITLE
App name wrong in win installer (NSIS)

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2957]
Spotted in our builds done by AppVeyor CI, downloaded from GitHub releases.
This could be a CMake issue related to parsing the GitHub tag.

64bit:
![64](https://user-images.githubusercontent.com/9874850/33989131-b0d0acaa-e0c6-11e7-9d3a-c575141a03ac.png)

32bit:
![32](https://user-images.githubusercontent.com/9874850/33989137-b40991fc-e0c6-11e7-8d96-56180fdc904c.png)

**Comment by tooomm** [comment]
This is still the case with the 32bit binaries for 2.6.0!

**Comment by tooomm** [comment]
Cockatrice 2.6.1 (32bit) has the same issue:
![version-name-nsis2](https://user-images.githubusercontent.com/9874850/52234256-8237b980-28c1-11e9-85e0-d41244ae5720.png)

64bit is ok:
![version-name-nsis3](https://user-images.githubusercontent.com/9874850/52234457-01c58880-28c2-11e9-991c-11f53599bfe0.png)


For 2.6.3-beta.4 (32bit) it worked fine. The problem could be the release names.
![version-name-nsis1](https://user-images.githubusercontent.com/9874850/52234261-86fc6d80-28c1-11e9-8cb6-d9250d9e5bff.png)

<br><br>

**To test with final 2.6.3 release (probably renamed to 2.7.0) again!**

**Comment by tooomm** [comment]
Jep, for both the name is not correct. Funny enough the results are different:

- 2.7.0 (64bit)
![install64](https://user-images.githubusercontent.com/9874850/53899599-da85e680-403a-11e9-84ef-a4391866fd90.png)

- 2.7.0 (32bit)
![install32](https://user-images.githubusercontent.com/9874850/53899616-e40f4e80-403a-11e9-9a09-04067a7f7163.png)

**Comment by ctrlaltca** [comment]
This has been fixed in release 2.7.4. Both installers show:
![Schermata 2020-03-26 alle 19 08 40](https://user-images.githubusercontent.com/1631111/77681178-4b28d980-6f95-11ea-8c7f-36b1b83dac5a.png)
