### ISSUE TITLE
Migration Failures

### ISSUE THREAD

**Issue by Lachee** [Cockatrice/Cockatrice#2970]
<b>OS:</b>
 Ubuntu 16.04.3 LTS

<b>Cockatrice version:</b>
#2962

__________

While migrating chickatrice.net from database schema 14 to schema 23, the following errors occur:
```
migrate.py:

Migrating from schema version 14...

Migrating: servatrice_0016_to_0017.sql
ERROR 1067 (42000) at line 5: Invalid default value for 'timest'

Migrating: servatrice_0019_to_0020.sql
ERROR 1292 (22007) at line 3: Incorrect datetime value: '0000-00-00 00:00:00' for column 'privlevelStartDate' at row 1

Migrating: servatrice_0020_to_0021.sql
ERROR 1067 (42000) at line 3: Invalid default value for 'requestDate'

Migrating: servatrice_0021_to_0022.sql
ERROR 1067 (42000) at line 2: Invalid default value for 'incidentDate'

Migrating: servatrice_0022_to_0023.sql
ERROR 1265 (01000) at line 3: Data truncated for column 'permissionlevel' at row 1

Finished Migrating. Completed 14 to 23
```

Everything in between were successful. The database has the new schema listed as 16.

**Comment by ctrlaltca** [comment]
I suppose this is related to https://github.com/Cockatrice/Cockatrice/issues/865
If mysql is running in strict mode, is requiring default values for some fields that are not present in the actual servatrice schema.

**Comment by Lachee** [comment]
hmm, most certainly. Its a fresh DB install.

**Comment by Daenyth** [comment]
Cockatrice doesn't work with strict mode right now. You need to set
non-strict

**Comment by Lachee** [comment]
Database has been set to NON_STRICT and migration had no issues.
