### ISSUE TITLE
NSIS: check for vcredist, propose to download and install it

### ISSUE THREAD

**Issue by ctrlaltca** [Cockatrice/Cockatrice#2973]
One of the most recurring problems are users unable to run cockatrice because they miss the correct visual studio runtime.

Before installing Cockatrice, NSIS could:
* detect if cockatrice needs 32-bit or 64-bit runtime;
* check if the needed runtime version + arch is installed: [hint](https://stackoverflow.com/questions/34177547/detect-if-visual-c-redistributable-for-visual-studio-2013-is-installed)
 * ask the user if he wants to download and install it [hint](https://gist.github.com/Gravecorp/2400855)

**Comment by ctrlaltca** [comment]
I'll close this by now since the root issue has been resolved by #3020.

**Comment by tooomm** [comment]
Just leaving a note.

#3020 bundles the vs2017 vcredist.exe file in the same "bit-ness" as the cockatrice installer itself.

While it works, there are several downsides to this:
- install package size doubles and is 30mb now
- install process takes ~5-10x longer (!!) as before, when the app installer has to install vcredist at the end
- this only happens as long as that file isn't installed yet 👍,
but during every install the vcredist gets extracted weather it's used or not, that eats up some time, too.

Maybe there is room for improvement, or the initial idea with checking+freshly downloading the file instead packaging it can be picked up at one point.
