### ISSUE TITLE
reveal to spectators

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2983]
Is it possible to reveal card zones to spectators as well? (e.g. deck and sideboard)
Since this is a bit more difficult to test, I'm putting the question here.

I'm asking because that would allow for a very simple deck check option for tournament organizers.
There are the deck hashes for sure, but it's not a real deck check and the operator needs to assemble all participants decks to generate the hash and check card counting etc.

I'm not talking about well organized tournament operators like magic-league which have scripts and a hp with submission forms or deck uploads with auto-checks, but any simple tournament done by individuals. For only fewer people or which happen rarely...

In the end it wouldn't hurt to have it, and as long as the log covers it there is no room for cheating.

**Comment by Daenyth** [comment]
I don't think this would be easy to implement, nor do I really think we'd want to.

An easy deck check is to upload your .cod file to the TO, who can then verify the hash themselves

**Comment by tooomm** [comment]
Actually, `Reveal to all players` works for the library at least. Spectators will see the library popup, too!
So maybe it's not that difficult to implement? If spectators are recognized as "players" already...

<br>

>An easy deck check is to upload your .cod file to the TO, who can then verify the hash themselves

That requires a setup, a good organization and preparation etc.
The most natural, intuitive and easiest to accomplish that for everybody would be a simple in-game check I think.

**Comment by Thunderbeliever** [comment]
This is a Horrible idea and should not be implemented.

**Comment by ZeldaZach** [comment]
We've decided this isn't really worth anyone's time. It's a really hard protocol change that's just not feasible right now.
