### ISSUE TITLE
raise the_exception\npandevice.errors.PanURLError: URLError: reason: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)\n",

### ISSUE THREAD

**Issue by arkaraung1993** [Cockatrice/Cockatrice#2984]
# Issue Type:

 SSL: CERTIFICATE_VERIFY_FAILED

[root@ansible ansible]# ansible --version
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/my_modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]

Panos PAN-OS 8.0
Python 2.7.5

OS-RedHat 7

-----------------------------------------------
# SUMMARY

This is my playbook for paloalto firewall.

fw_object_update.yml

- name: Update some objects on the firewall
  hosts: pafw2
  connection: local
  gather_facts: False

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

- name: Update an object on the firewall
    panos_object:
      ip_address: '{{ ansible_ssh_host }}'
      username: '{{ ansible_ssh_user }}'
      password: '{{ ansible_ssh_pass }}'
      addressobject: 'test-address'
      address: '192.168.99.89/25'
      address_type: 'ip-netmask'
      description: 'This is a test address object'
      operation: 'update'

------------------------------------------------

This is "vars" file and path

/etc/ansible/host_vars/pafw2.yml

pafw2.yml
---
ansible_ssh_host: pafw2
ansible_ssh_user: admin
ansible_ssh_pass: admin

-------------------------------------------------

Ans I run the Playbook "fw_object_update.yml" and found error.

[root@ansible ansible]# ansible-playbook fw_objects_update.yml
/usr/lib/python2.7/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.22) or chardet (2.2.1) doesn't match a supported version!
  RequestsDependencyWarning)

PLAY [Update some objects on the firewall] ****************************************************************************************************

TASK [PaloAltoNetworks.paloaltonetworks : pip] ************************************************************************************************
ok: [pafw2]

TASK [PaloAltoNetworks.paloaltonetworks : pip] ************************************************************************************************
ok: [pafw2]

TASK [PaloAltoNetworks.paloaltonetworks : pip] ************************************************************************************************
ok: [pafw2]

TASK [search for shared address object] *******************************************************************************************************
task path: /etc/ansible/fw_objects_update.yml:11
Using module file /root/.ansible/roles/PaloAltoNetworks.paloaltonetworks/library/panos_object.py
<pafw2> ESTABLISH LOCAL CONNECTION FOR USER: root
<pafw2> EXEC /bin/sh -c 'echo ~ && sleep 0'
<pafw2> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1514882075.34-245105337284232 `" && echo ansible-tmp-1514882075.34-245105337284232="` echo /root/.ansible/tmp/ansible-tmp-1514882075.34-245105337284232 `" ) && sleep 0'
<pafw2> PUT /tmp/tmpIhgbur TO /root/.ansible/tmp/ansible-tmp-1514882075.34-245105337284232/panos_object.py
<pafw2> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1514882075.34-245105337284232/ /root/.ansible/tmp/ansible-tmp-1514882075.34-245105337284232/panos_object.py && sleep 0'
<pafw2> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1514882075.34-245105337284232/panos_object.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1514882075.34-245105337284232/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_7SP2lM/ansible_module_panos_object.py", line 457, in <module>
    main()
  File "/tmp/ansible_7SP2lM/ansible_module_panos_object.py", line 337, in main
    device = base.PanDevice.create_from_device(ip_address, username, password, api_key=api_key)
  File "/usr/lib/python2.7/site-packages/pandevice-0.5.2-py2.7.egg/pandevice/base.py", line 2974, in create_from_device
    system_info = device.refresh_system_info()
  File "/usr/lib/python2.7/site-packages/pandevice-0.5.2-py2.7.egg/pandevice/base.py", line 3383, in refresh_system_info
    system_info = self.show_system_info()
  File "/usr/lib/python2.7/site-packages/pandevice-0.5.2-py2.7.egg/pandevice/base.py", line 3340, in show_system_info
    root = self.xapi.op(cmd="show system info", cmd_xml=True)
  File "/usr/lib/python2.7/site-packages/pandevice-0.5.2-py2.7.egg/pandevice/base.py", line 3205, in xapi
    self._xapi_private = self.generate_xapi()
  File "/usr/lib/python2.7/site-packages/pandevice-0.5.2-py2.7.egg/pandevice/base.py", line 3247, in generate_xapi
    kwargs = {'api_key': self.api_key,
  File "/usr/lib/python2.7/site-packages/pandevice-0.5.2-py2.7.egg/pandevice/base.py", line 3199, in api_key
    self._api_key = self._retrieve_api_key()
  File "/usr/lib/python2.7/site-packages/pandevice-0.5.2-py2.7.egg/pandevice/base.py", line 3333, in _retrieve_api_key
    xapi.keygen(retry_on_peer=False)
  File "/usr/lib/python2.7/site-packages/pandevice-0.5.2-py2.7.egg/pandevice/base.py", line 3100, in method
    raise the_exception
pandevice.errors.PanURLError: URLError: reason: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)

fatal: [pafw2]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_7SP2lM/ansible_module_panos_object.py\", line 457, in <module>\n    main()\n  File \"/tmp/ansible_7SP2lM/ansible_module_panos_object.py\", line 337, in main\n    device = base.PanDevice.create_from_device(ip_address, username, password, api_key=api_key)\n  File \"/usr/lib/python2.7/site-packages/pandevice-0.5.2-py2.7.egg/pandevice/base.py\", line 2974, in create_from_device\n    system_info = device.refresh_system_info()\n  File \"/usr/lib/python2.7/site-packages/pandevice-0.5.2-py2.7.egg/pandevice/base.py\", line 3383, in refresh_system_info\n    system_info = self.show_system_info()\n  File \"/usr/lib/python2.7/site-packages/pandevice-0.5.2-py2.7.egg/pandevice/base.py\", line 3340, in show_system_info\n    root = self.xapi.op(cmd=\"show system info\", cmd_xml=True)\n  File \"/usr/lib/python2.7/site-packages/pandevice-0.5.2-py2.7.egg/pandevice/base.py\", line 3205, in xapi\n    self._xapi_private = self.generate_xapi()\n  File \"/usr/lib/python2.7/site-packages/pandevice-0.5.2-py2.7.egg/pandevice/base.py\", line 3247, in generate_xapi\n    kwargs = {'api_key': self.api_key,\n  File \"/usr/lib/python2.7/site-packages/pandevice-0.5.2-py2.7.egg/pandevice/base.py\", line 3199, in api_key\n    self._api_key = self._retrieve_api_key()\n  File \"/usr/lib/python2.7/site-packages/pandevice-0.5.2-py2.7.egg/pandevice/base.py\", line 3333, in _retrieve_api_key\n    xapi.keygen(retry_on_peer=False)\n  File \"/usr/lib/python2.7/site-packages/pandevice-0.5.2-py2.7.egg/pandevice/base.py\", line 3100, in method\n    raise the_exception\**npandevice.errors.PanURLError: URLError: reason: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)\n",**
    "module_stdout": **"",**
    "msg": "MODULE FAILURE",
    "rc": 0
}
        to retry, use: --limit @/etc/ansible/fw_objects_update.retry

PLAY RECAP ************************************************************************************************************************************
pafw2                      : ok=3    changed=0    unreachable=0    failed=1

I am not sure it is SSL Certificate error, Please help me on it.

**Comment by Daenyth** [comment]
I have no idea what you're trying to do but it has nothing to do with this project
