### ISSUE TITLE
Very blurry card pictures on 1080p display

### ISSUE THREAD

**Issue by Sandyclaws6** [Cockatrice/Cockatrice#2985]
<b>OS:</b>
Windows 10 Pro

<b>Cockatrice version:</b>
cockatrice 2.4.0

__________

This issue has been happening for a long time. When i have cockatrice open on my 1080p display, the card pictures look super grainy/blurry and almost unreadable(picture provided). When on my smaller 720p display though, they show up just fine. What can i do to fix this?
<img width="197" alt="untitled" src="https://user-images.githubusercontent.com/35045467/34501337-4cf56908-efc3-11e7-8e3f-83888d944795.png">

**Comment by Daenyth** [comment]
Find custom images. Gatherer (from the wizards site) only provides
low-quality card images, and that's what we download by default because
it's the only reliable source we have at the moment

**Comment by tooomm** [comment]
The quality is not always as bad @Sandyclaws6, but for the one you posted they don't have a better one for themselves: http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=184585 :)

Custom images or alternative images sources on the web are the only way to fix that for yourself.
