### ISSUE TITLE
card filter: keywords are not translatable

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2986]
The keywords such as `cmc`, `type` or `text` in the card filter are not translatable right now.

I guess it's only about the missing `tr()` wrappings here?
https://github.com/Cockatrice/Cockatrice/blob/master/cockatrice/src/cardfilter.cpp#L22-L43

Same is true for the logical connectors like `and` and `or not` etc.

**Comment by ZeldaZach** [comment]
They are actively translated at https://github.com/Cockatrice/Cockatrice/blob/master/cockatrice/src/filterbuilder.cpp#L17

**Comment by tooomm** [comment]
So the problem is somewhere else, because there is no possibility to translate them...
Search [our translations source strings](https://github.com/Cockatrice/Cockatrice/blob/master/cockatrice/translations/cockatrice_en.ts) for yourself or check at [transifex](https://www.transifex.com/cockatrice/cockatrice/translate/#de/cockatrice?q=cmc).
There are no translatable strings for e.g. `cmc` available!

Maybe we have to rebuild translations? Or could the way of implementing the `tr()` be an issue here?

**Comment by ZeldaZach** [comment]
Move the tr() to the return value and remove the tr from the filterbuilder. That'll work.

**Comment by tooomm** [comment]
>Move the tr() to the return value and remove the tr from the filterbuilder. That'll work.

Nope, that's not doing it.
Hopefully there is another way to enable translations for that part of the app!  @ctrlaltca?

**Comment by ZeldaZach** [comment]
How'd you check that they "didn't work"?

**Comment by tooomm** [comment]
All CI fails, check the logs. 😢

**Comment by tooomm** [comment]
Any idea what could be wrong here @ctrlaltca ?

**Comment by ctrlaltca** [comment]
From a quick view it seems like those strings are translated dynamically, i.e. there's no explicit call to `tr("string")`.
The "extract string from code" procedure is not able to extract these strings, so we need to explicitly declare them as translatable strings using [QT_TRANSLATE_NOOP](http://doc.qt.io/archives/qt-4.8/qtglobal.html#QT_TRANSLATE_NOOP), eg:
```foo = QT_TRANSLATE_NOOP("QMenuBar", "Services");```
We already use this trick in some parts of the code.

**Comment by tooomm** [comment]
Fixed in https://github.com/Cockatrice/Cockatrice/pull/3490, thanks @ctrlaltca !
