### ISSUE TITLE
card filter: bigger/smaller etc. not supported ("<3" or ">=7")

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#2988]
<b>OS:</b>
Win 10 64bit

<b>Cockatrice version:</b>
Version 2.4.1-custom(8fd634d) (2017-12-29)

__________

`<`, `>` and `=` (more so the sequence `<=`, `=<`, `>=` and `=>`) should be treated in a special way for the *converted mana cost* filter. All others don't need it I think.

For people who are working on the curves of their decks and need special costing cards or like anybody building a [Tiny Leader](https://magic.wizards.com/en/articles/archive/reconstructed/tiny-leaders-big-fun-2015-02-17) deck this is a blessing... because brewing can be quite difficult with all that disallowed cards costing more than 3 mana.
Or just anybody looking for a card which he knows only a few details about.

For `<3` you can do 3 AND filter for cmc=0, cmc=1 and cmc=2 as a workaround... sure.
But for `>=7` one would unlikely want to create filters for cmc=7 up to 16 or whatever the most expensive card actually is - I've no idea. :)

**Comment by ZeldaZach** [comment]
I fully agree with something like this, but our filters would need an overhaul. Maybe i'll find time for this soon.

**Comment by tooomm** [comment]
Closing in favor of https://github.com/Cockatrice/Cockatrice/issues/2205
