### ISSUE TITLE
[Request]Cockatrice bigger picture view ingame

### ISSUE THREAD

**Issue by satsukiyatoshi** [Cockatrice/Cockatrice#299]
Hello.
I use big scans for cards with a lot of text.
The ingame card view is too small for that (the windows witch is used with the center click of the mouse)

So a cool option would be to fullscreen this card preview (and chosse if it can display text + card or only card)

Thanks for your works and feel free to delete this request if it's not the right place to ask it for.

**Comment by ctrlaltca** [comment]
Implemented in late 2015, now the ingame picture can be resized or even detached and fullscreened on a second monitor
