### ISSUE TITLE
Oracle can't download token database with SSL

### ISSUE THREAD

**Issue by Zombiekwest** [Cockatrice/Cockatrice#2994]
<b>Windows 10 x64</b>

<b>Version 2.4.0 (2017-11-19)
</b>

__________

![error](https://user-images.githubusercontent.com/35150063/34626626-1dc2a940-f223-11e7-8d35-f574d5bd48cc.jpg)

Trying to reinstall Cockatrice on a new computer. Every time I try to load Oracle I keep getting this error. I was able to load the card sets by deleting the S in HTTPS, but now I can't seem to get the tokens to want to load by doing the same trick. Any idea on how to best work around this? THANKS!

**Comment by tooomm** [comment]
I assume that github automatically redirects to https and there is no way to use unsecure http anymore.


>Any idea on how to best work around this?

You can manually download the tokens file and replace the old token file at your pc:
https://raw.githubusercontent.com/Cockatrice/Magic-Token/master/tokens.xml

**Comment by woogerboy21** [comment]
Pretty sure the solution for this is described in #2031
