### ISSUE TITLE
"api-ms-win-crt-runtime-l1-1-0.dll" missing => can't launch program

### ISSUE THREAD

**Issue by ShawnMichaels** [Cockatrice/Cockatrice#2995]
So I recently dusted off my old PC which runs on Windows Vista SP2. I get continously get that famous error called "api-ms-win-crt-runtime-l1-1-0.dll" missing and therefore I can't start the program. I've followed all advice I could find on this issue, that is installing every available update for Vista and furthermore to install those "Visual C++" packs from MS. However, all this didn't help and the error still keeps showing up.

What else can i do?

Thanks in advance.

**Comment by tooomm** [comment]
You checked this, right?
https://github.com/Cockatrice/Cockatrice/wiki/Troubleshooting#api-ms-win-crt-runtime-l1-1-0dll-missing

If you provide all the asked questions in our template when creating an issue, we might be able to help you... 
Which version of Cockatrice do you try to run?
Do you use 32bit Vista? 64bit?

Which vcredist package did you install?

**Comment by ShawnMichaels** [comment]
Hello, thanks for your answers. I forgot to tell my specs specifically. It is a "32bit" Vista. I installed the x86-package because that's the one I need right?

After I removed a old Cockatrice version from ~2013 I both tried it with the versions 2.4.0 and 2.3.17.

**Comment by ShawnMichaels** [comment]
Yes I did read the advice you linked. And I did use the x86-cockatrice-versions.

**Comment by ZeldaZach** [comment]
We no longer support Windows Vista nor Windows XP. Unfortunately there's not much more we can do for you.

**Comment by luizhalen** [comment]
I have Windows 7 and I'm facing the same problem...

**Comment by seeyousakura** [comment]
I have Windows 7 SP1 too and I'm facing the same problem...

**Comment by tooomm** [comment]
You would need to provide more details and information.

But as a note upfront, Win 7 is a very old and outdated operating system no longer supported by Microsoft. Only paying enterprise customers get security updates at least as far as I'm aware. 
I would not be surprised to see issues on that old systems.
