### ISSUE TITLE
Socket Error: Connection timed out.

### ISSUE THREAD

**Issue by PantherII** [Cockatrice/Cockatrice#2996]
<b>OS: 64bit</b>
*Windows 8.1*

<b>2.4.0:</b>
Version 2.4.0 (2017-11-19)

__________

I cannot connecto to the woogerworks server anymore. Everytime I try to connect I get the message 'Socket error: conncetion timed out'. This didn't happen when I tried it yesterday. Did something get changed on the server which might cause this issue?

My cockatrice account name is 'SdKfz251D'.

**Comment by tooomm** [comment]
The server is having issues recently: https://status.woogerworks.com/776936898

Important information and links like that, as well as alternative servers can always be found here:
https://github.com/Cockatrice/Cockatrice/wiki/Public-Servers

Keep in mind that this place is for issues with the software, not servers that individuals run.
For any problems with a server or your account, only the server operator can help you best.
