### ISSUE TITLE
Card Images for RIX.xml not loading (SSL)

### ISSUE THREAD

**Issue by Monikar1** [Cockatrice/Cockatrice#2997]
<b>OS:</b>
windows 10

<b>Cockatrice version:</b>
version 2.4.0 (2017-11-19)

__________

My main problem is none of the RIX art appears after installing the RIX.xml, including the basic lands. I looked at the debug log and found this

"Picture NOT found, trying to download (set:  "RIX"  card:  "Forest" )
starting picture download: "Forest" Url: QUrl("https://img.scryfall.com/cards/large/en/rix/196.jpg?1515151204")
QSslSocket: cannot call unresolved function SSLv23_client_method
QSslSocket: cannot call unresolved function SSL_CTX_new
QSslSocket: cannot call unresolved function SSL_library_init
QSslSocket: cannot call unresolved function ERR_get_error
QSslSocket: cannot call unresolved function ERR_get_error
Download failed: "Error creating SSL context ()"
Picture NOT found, download failed, no more sets to try: BAILING OUT (oldset:  "RIX"  card:  "Forest" )"

When I check for updates with cockatrice I get this message "Cockatrice was not built with SSL support , therefore you cannot download updates automatically! please visit download page to update manually"

I don't know anything about coding but I thought it might be connected since it mentions SSL in both the debug log and the auto update message

**Comment by tooomm** [comment]
Where did you download Cockatrice?

https://github.com/Cockatrice/Cockatrice/issues/2031 is a currently known SSL issue for some users on Windows. I assume it's also the reason for your problem.

**Comment by Monikar1** [comment]
https://cockatrice.github.io

From this website


On Jan 7, 2018 10:10 AM, "tooomm" <notifications@github.com> wrote:

Where did you download Cockatrice?

#2031 <https://github.com/Cockatrice/Cockatrice/issues/2031> is a currently
known SSL issue for some users on Windows. I assume it's also the reason
for your problem.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Cockatrice/Cockatrice/issues/2997#issuecomment-355840950>,
or mute the thread

**Comment by tooomm** [comment]
That's the right place to download the installers, yes.
So you are using the correct version at least. Unfortunately you run into the linked issue.

But you can download the art manually if you really need them right now, and place them in your pictures folder. See the wiki for more info.

**Comment by ZeldaZach** [comment]
Dupe #2994
