### ISSUE TITLE
Cards from clipboard in deck builder without quantity given have first word replaced by quantity

### ISSUE THREAD

**Issue by JoshuaLamusga** [Cockatrice/Cockatrice#2998]
<b>OS: Win 10 Home 64-bit</b>
<b>Cockatrice version: 2.4.1</b>

Open Cockatrice and try to add a card or list of cards from the clipboard in deck builder (Ctrl + Shift + V) without quantities specified. Like _Notion Thief_ instead of _1x Notion Thief_. They're supposed to become _1x Notion Thief_ but become _1x  Thief_ instead. The first word is eaten by the quantity prepended to the card name. This affects every card I tested; length of the first word in the card name doesn't matter.

**Comment by ZeldaZach** [comment]
Tested 
```
Quicksilver Elemental
3x Craterhoof Behemoth
2 Elvish Mystic
Progenitus
2x Abrade
1x Absorb
```

Returns all correct except for Quicksilver Elemental, which becomes Elemental

**Comment by tooomm** [comment]
So single worded cards without quantity works fine, just cards with several words don't?

**Comment by ZeldaZach** [comment]
Seems so. I'll check this out soon.
