### ISSUE TITLE
Program crashes when opponent concedes

### ISSUE THREAD

**Issue by jfwharton** [Cockatrice/Cockatrice#3001]
<b>Ubuntu 16.04:</b>

<b>2.4.1-custom_3af2be4 (2017-12-19), also witnessed problem with previous versions:</b>

__________

Often right as the opponent concedes, the program crashes. My opponent reports it as seeing "Opponent has left the game"

What I see is the game first closes, then the entire program closes, in quick succession

**Comment by ZeldaZach** [comment]
I've seen this issue myself a few times. Can you possibly include a crash log so I can look into why _you_ specifically crashed?

**Comment by jfwharton** [comment]
Do I use View debug log under Help?

**Comment by ZeldaZach** [comment]
@jfreake You can do that, yes. If the program crashes it should generate a crash log in /var/log probably.

**Comment by jfwharton** [comment]
It may be a while before it happens again, it happens maybe once out of ever 20-30 games

**Comment by ZeldaZach** [comment]
@jfreake When/if it happens again, please update this ticket :)

**Comment by jfwharton** [comment]
I'll update, when it happens
