### ISSUE TITLE
Cockatrice unable to find the MSVCP140.dll in the most recent download.

### ISSUE THREAD

**Issue by viperfang4** [Cockatrice/Cockatrice#3010]
My operating system is the most up to date version of windows 10 as of 1/11/2018

I tried the 3 most recent versions

__________

Once the downloader finishes, and I try to boot cockatrice, I get an error saying that the program is unable to find MSVCP140.dll file. I am not sure if it downloaded or not. I have had cockatrice on this computer, but it was wiped as I had to reinstall windows after the latest patch crash my computer. It is working now, but I can't get cockatrice to work. I don't know if cockatrice has had any known issues with avast as an antivirus in the past as it is checking the download.

**Comment by ZeldaZach** [comment]
https://github.com/Cockatrice/Cockatrice/wiki/Troubleshooting#failed-start-because-msvcpxxxdll-was-not-found
