### ISSUE TITLE
Store time stamp when password reset is performed 

### ISSUE THREAD

**Issue by woogerboy21** [Cockatrice/Cockatrice#3015]
This is simply a request to create a column some were (maybe in the users table) that when the user resets there password the date/time stamp of when the transaction happened is stored. 

Why is there not a request label?

**Comment by ZeldaZach** [comment]
Any reason why you think something like this could be useful? No objections to the creation, just not certain of the purpose rn

**Comment by woogerboy21** [comment]
It would be nice to have to help identify if some one was attempting to high jack an account.  There has been a few occasions that I’ve been contacted about passwords no longer working and all I can say is “sorry” and reset the password for them to regain access to the account.

Chances are it’s just something they forgot but it would be nice to know when the account password was changed last.

Thanks

**Comment by kopcion** [comment]
Hi
I would like to contribute to this issue. If that's possible could you give me some advice as where to look in the code?
Thanks

**Comment by ebbit1q** [comment]
@kopcion in a quick search I found that the forgot password mails are sent here https://github.com/Cockatrice/Cockatrice/blob/master/servatrice/src/servatrice.cpp#L640

**Comment by kopcion** [comment]
Thanks a lot, could you assign this issue to me if it's not a problem?
