### ISSUE TITLE
Cards with split mana have their mana cost wrong

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#3017]
It looks like all split mana cards with more than 1cmc like the ones below have their mana cost wrong:
![split mana cards](https://user-images.githubusercontent.com/9874850/34964561-7f8646cc-fa4e-11e7-8ede-0fc3ff72d1d9.png)

It should be `GG/GW/WW` (or `GG/WG/WW`) for the selected Guildmage.
But it only wrongly shows `G/WG/W`.

In cards.xml the data is also wrong: `<manacost>G/WG/W</manacost>`
In AllSets.json all occurrences of the card have correct data: `"manaCost": "{G/W}{G/W}",`

**Comment by Arc676** [comment]
Isn't that just the representation? `G/WG/W` is the same as `{G/W}{G/W}`, just without the braces. It's just indicating what can be spent to cast the spell without separating the symbols.

**Comment by tooomm** [comment]
I don't think so @Arc676.
The values in brackets {}, each represent one circled mana symbol. Here it's a split mana symbol.
So each value for each mana symbol can be G or W, so it's represented by `{G or W}` per partial cost, of which there are two.

Cockatrice doesn't use the {} brackets and doesn't represent mana symbols as `Mana Cost`, it shows possible cost combinations in total. `G/WG/W` therefore represent a cost of `G or WG or W`, which is wrong. It should be `GG or WG (GW) or WW`.

I realized it when testing #3008. Because you would expect the mentioned card to show up if you search for `Mana Cost = WW`, as well as GG (not only WG or GW)

**If you look closer, it seems that only the brackets and spaces are striped by Oracle when creating the card database, and it's `G/W G/W` actually, it only looks different when combined to `G/WG/W`. That also explains why it's WG and not GW. Have never thought of that before, thanks @Arc676 for opening my eyes! :D
So maybe the mistake is that.** 👍
I don't care if it should be `G/W G/W` or `GG/GW/WW`. If it's the first, then the search need further changes to find such cards on GG or WW. Otherwise Oracle parsing needs to be adjusted.

**Comment by ZeldaZach** [comment]
Since there are cards that have many hybrid costs, I'm not sure about an appropriate fix at the moment

**Comment by Daenyth** [comment]
@Arc676 is right, it's `{G/W} {G/W}`. We could adjust the formatting to make it more clear
