### ISSUE TITLE
more additions to contributing.md?

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#3029]
I run trough a bunch of recent PR's and tried to gather all style related feedback:

Here is what shouldn't be covered in https://github.com/Cockatrice/Cockatrice/blob/master/.github/CONTRIBUTING.md yet:
- Add info about not using master branch when creating changes
https://github.com/Cockatrice/Cockatrice/pull/2944#issuecomment-350814698
- nullptr > implicit style
https://github.com/Cockatrice/Cockatrice/pull/2991#discussion_r160399573
- cpp style cast
https://github.com/Cockatrice/Cockatrice/pull/3013#discussion_r161927765
- spaces after if etc.
https://github.com/Cockatrice/Cockatrice/pull/3028#discussion_r162698552
- use auto
https://github.com/Cockatrice/Cockatrice/pull/2991#discussion_r160400394
- general QDebug stuff
https://github.com/Cockatrice/Cockatrice/pull/2991#discussion_r160402217
- don't use hungarian notation
https://github.com/Cockatrice/Cockatrice/pull/2960#discussion_r157624279
- no same-line declarations
https://github.com/Cockatrice/Cockatrice/pull/2706#discussion_r116356241
- document peer review process
https://github.com/Cockatrice/Cockatrice/issues/2608#issuecomment-295644737
- no code convention for naming actions yet
https://github.com/Cockatrice/Cockatrice/pull/2605#discussion_r112387652
- no c-style pointer casts
https://github.com/Cockatrice/Cockatrice/issues/2558
- static vs. dynamic casts
https://github.com/Cockatrice/Cockatrice/pull/3036#discussion_r162806888

Not all might be needed, just check, quote and leave a comment please! 👍

**Comment by ZeldaZach** [comment]
I'll look into another update this weekend

**Comment by tooomm** [comment]
>Hint that contributors should avoid changes to existing protobuf `.proto` files wherever possible, since they are the backbone of client/server communication and render the app incompatible with others.
Also servers might need to update as well.

Related, interesting link: https://github.com/Cockatrice/Cockatrice/wiki/Client-server-protocol

**Comment by ZeldaZach** [comment]
The proto is necessary to edit to make server sided changes

**Comment by tooomm** [comment]
Sure, it is there for a reason and very much needed, hence I stated `wherever possible`.
I only want to raise awareness and let new contributors know that they should think twice and check back with us if they want to change something as important as the proto files.
Not everybody capable of c++ might know in detail about the communication concept we rely on.

**Comment by tooomm** [comment]
We should explain our label system there as well (+put a link in readme?), and provide some example links with reasonable combinations of filter patterns, like [Important bugs in the Cockatrice main app (most recent activity on top)](https://github.com/Cockatrice/Cockatrice/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22App+-+Cockatrice%22+label%3A%22Bug%22).
