### ISSUE TITLE
Wrong format when loading .mwDeck

### ISSUE THREAD

**Issue by dino572** [Cockatrice/Cockatrice#3038]
<b>OS:</b>
Win 7 SP2

<b>Cockatrice version:</b>
Version 2.4.0 (2017-11-19)
__________

This is what the .mwDeck original file looks like:
![3](https://user-images.githubusercontent.com/35634225/35185777-98172a8a-fe09-11e7-930a-1f576193e95d.png)
It is an old deck I saved in Magic Workstation.

When I load a deck of type .mwDeck, each card entry is loaded with an extra blank space in front of it and each card has only lower-case letters:
![1](https://user-images.githubusercontent.com/35634225/35185761-7752bcba-fe09-11e7-8838-0bb3ebbbe3fa.png)

This means that Cockatrice doesn't recognize the card correctly. No image or rules text is displayed.

When I save the deck as a .cod file, each card gets a blank space in front of its name and it is saved in lower-case only:
![2](https://user-images.githubusercontent.com/35634225/35185766-7ac30378-fe09-11e7-84b1-abc637b9a241.png)

**Comment by Daenyth** [comment]
I think this is a regression. We're supposed to be able to load mws decks. @ZeldaZach do you recall if the deck parsing code changed lately?

**Comment by Daenyth** [comment]
Regardless this should be really easy to fix. @dino572 can you please attach the mwDeck file?

**Comment by dino572** [comment]
Thanks for taking a look at this. I can't upload mwDeck files here but here's a dropbox link: https://www.dropbox.com/s/77kurck39fon8t4/Bears.mwDeck?dl=1

**Comment by dino572** [comment]
If I "Save deck to clipboard" and then "Load deck from clipboard", it loads as it should.

**Comment by dino572** [comment]
decklist.cpp line 564:
`        // Filter out MWS edition symbols and basic land extras
        QRegExp rx("\\[.*\\]");
        line.remove(rx);
        rx.setPattern("\\(.*\\)");
        line.remove(rx);`

Is that the problem? Not removing one space after the  brackets ?

**Comment by Daenyth** [comment]
Good call. That looks like like it could be the issue. Want to send a pull request changing that regex to `\\[.*\\]\s?` ? We can get a test build up for you

**Comment by dino572** [comment]
I think I sent a pull request now.
The changes are:
QRegExp rx("\\[.*\\]\s?");
rx.setPattern("\\\s(.*\\)");

I added an \s in the second regex too because otherwise I think a line like this:
1 [XLN] Island (2)
Would end up with a space at the end.

**Comment by ctrlaltca** [comment]
You created a pull request, but against your fork of the repo and not the main cockatrice repo.
Don't worry, just follow this link https://github.com/Cockatrice/Cockatrice/compare/master...dino572:dino572-patch-1 to create the PR on the correct repo

**Comment by Daenyth** [comment]
I created the PR from that link - #3056

**Comment by Nightfirecat** [comment]
For future reference, there's no need to make new pull requests for fixing issues; just add another commit to the branch you opened the pull request from, and it'll be included in the PR.

**Comment by dino572** [comment]
I think it's fixed. The final changes were:
`QRegExp rx("\\[.*\\]\\s?");
line.remove(rx);
rx.setPattern("\\s?\\(.*\\)");
line.remove(rx); 
`
