### ISSUE TITLE
"Edit tokens..." dialog needs update

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#3045]
- The dialog shouldn't contain any tokens from `tokens.xml` file since we don't want people to edit them. (Errors should get fixed in the repo for everybody, and custom tokens belong into `TK.xml`)
Confusingly they can't even get edited there... you can actually change values of provided tokens, they get picked up in the UI and suggest that you changed them for real.
But after a restarting the client everything is gone again...
![edittokens](https://user-images.githubusercontent.com/9874850/35231925-6ae31b04-ff9a-11e7-8d61-3d9dada15371.png)

- Instead, rename the dialog to `Edit custom tokens...` and show what it is about:
Creating and editing of custom tokens that go to the `TK.xml` file in `/customsets`

**Comment by ZeldaZach** [comment]
I can understand your reasoning... just it'll be difficult since users won't have a way to view their tokens otherwise. What do you think about that?
