### ISSUE TITLE
Ravager of the Fells crashes my Cockatrice

### ISSUE THREAD

**Issue by TheAller** [Cockatrice/Cockatrice#3054]
<b>OS X El Capitan 10.11.6:</b>

<b>Version 6e723b2 (2017-03-14):</b>

__________

Hi,

Whenever I try to create the token "Ravager of the Fells" (flipped version of Huntmaster of the Fells), my Cockatrice crashes. This doesn't happen with any other token, or at least, not with any other token I tried to create (and I created dozens of different flip cards/tokens/emblems etc). 

I've been having this issue for a long time (certainly months, possibly even years) but I never cared to solve it 'cause I don't usually play decks with this particular card. But now I'd like to try and solve this problem once and for all.

Any idea on why this happens and how to solve it?

P.S. I update my card database at the release of every new set, but this problem remains.

**Comment by ZeldaZach** [comment]
I fixed this many months ago... had something to do with the DFC change in our token repo. Update your client (as you're almost 1 year out of date) and you should be good!

**Comment by TheAller** [comment]
Hi,

I actually have troubles updating my client as well.

I get this message:

A new version is available:
Cockatrice 2.4.0: Unwrapped
published on 20 novembre 2017 .
More informations are available on the release changelog
Unfortunately there are no packages available for your operating system. You may have to use a developer build or build from source yourself. Please visit the download page.

When I try to visit the download page, the binray link doesn't seem to work:

Page not found (404)

**Comment by ctrlaltca** [comment]
We dropped bintray since it's no more friendly to open source projects.
You can download a new version manually (this time) from the main page: https://github.com/Cockatrice/Cockatrice

**Comment by TheAller** [comment]
So what am I supposed to download manually exactly?

I went "clone/download -> download zip", got a folder full of things I've no idea what they are. 

Sorry, I know, I'm not very good at this...am I just trying to download a new version of Cockatrice and re-install it, or am I trying to download something else?

**Comment by skwerlman** [comment]
@ctrlaltca provided the wrong link by accident, it seems. Go here: https://cockatrice.github.io/

**Comment by ctrlaltca** [comment]
Also the main page i linked contains a "Downloads" section with a download link, but i admit that https://cockatrice.github.io/ is more user friendly :)
![schermata 2018-01-29 alle 14 45 34](https://user-images.githubusercontent.com/1631111/35513406-35499d92-0503-11e8-806f-c3f31ee4ef7c.png)

**Comment by Daenyth** [comment]
@TheAller btw from here the auto update should work again.
