### ISSUE TITLE
Expand clang-format for proto and js

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#3060]
While #3028 covered `Language: Cpp`

@Daenyth also suggested in https://github.com/Cockatrice/Cockatrice/issues/2183#issuecomment-249416472 to include a style for proto.
Clang-format could also be expanded to cover the webclient written in Javascript!

Interesting link with help/description regarding the different options availabel: https://clangformat.com
Official clang-format documentation: https://clang.llvm.org/docs/ClangFormat.html

**Comment by Daenyth** [comment]
If someone wants to add that go for it 👍

**Comment by tooomm** [comment]
Is there a possibility to cut trailing whitespace too?
Like fixed [here](https://github.com/Cockatrice/Cockatrice/pull/3081/files#diff-da8ac605d3f53acc09143643ce7ae010R54) for example?


Also this could be a nice link to test clang settings: https://zed0.co.uk/clang-format-configurator/

**Comment by ebbit1q** [comment]
we don't have a complete js client, until then it's not needed.
