### ISSUE TITLE
Add "Get Started" guide (widget) to the default UI

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#3063]
The idea is to have a new, additional widget which is displayed on default for clean installs.
On later runs the user could just close the widget because he most likely never needs it again. But if there is more help required one could display it again like all other widgets: `View` --> `Get Started` --> `visible`
This way veteran players are not annoyed at all while we can provide a better user experience to new players.

It should contain several most basic information and hints to guide a new, tech-unsavy person with no background knowledge about such programs to a pleasurable first run experience and a not complicated and intuitive setup until they can play their very first game connected to a server.

This ticket is about discussions on the idea itself, which information is needed/requiered and in which form it should be presented.

Suggestions and thoughts are highly welcome!
If you are a user, let us know which problems you run into at your first start of the app. What are your experiences?
If you are a moderator/server admin, which issues did new users report to you, or constantly ask questions about?
*It could be reasonable to open a thread at reddit as well to gather more feedback!*

---

I created a mockup how it could look like:
![first_start_view_with_help_widget_shown](https://user-images.githubusercontent.com/9874850/35627242-98de0adc-0698-11e8-8007-6e4be7b124de.png)

A first simple version could be text only with links to our wiki maybe.
And a later one can provide buttons that open `Oracle` or the `Register` dialog etc.

**Comment by Daenyth** [comment]
I actually would put the "get started" guide on the otherwise-blank pre-connect screen. 

One of the reason I've been so on the idea of #652 is because it's low work for us and non-intrusive for folks who don't want it.

This is a good idea though!

**Comment by tooomm** [comment]
>the otherwise-blank pre-connect screen

What's do you mean exactly?

**Comment by ZeldaZach** [comment]
@Daenyth Maybe i'll think of something to build on TOTH

**Comment by Daenyth** [comment]
By pre-connect screen I mean when you install cockatrice and open the app we just have a big grey empty window. You need to go to the menu and select "connect".

**Comment by tooomm** [comment]
>By pre-connect screen I mean when you install cockatrice and open the app we just have a big grey empty window. 

I guess things changed in between, I get this very clumsy view on a clean first run with a popup as a first attempt to help new players getting the cards:
![first-run](https://user-images.githubusercontent.com/9874850/35650493-90d5dd08-06dc-11e8-92f7-0b30c1b0af68.png)


It won't even start in full screen... it looks randomly placed at the left.
To be precise, it shows in ~4:3 screen ratio on my 16:9 monitor and only covers 2/3 of it.
A very good first impression... 😕

**Comment by Daenyth** [comment]
Yes, we also have a hardcoded launch size

**Comment by ZeldaZach** [comment]
I'd rather link back to the wiki on the tip of the day menu.

**Comment by tooomm** [comment]
>I'd rather link back to the wiki on the tip of the day menu.

It would need to be the first tip, then it might work that way as well. (I can't even tell if tips show up for new users on first run by default so they see it for sure?)
