### ISSUE TITLE
Add simple clang-format instructions to CONTRIBUTING

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#3065]
#3028 introduced `clang-format` usage.

>We need a paragraph with explanations about how to install+apply clang-format in the CONTRIBUTING file, too!

Some hints: https://github.com/Cockatrice/Cockatrice/pull/3053#issuecomment-361534883

@Daenyth Do you recall if `clang-format cockatrice/ oracle/ servatrice/` worked for you?
That looks to be the easiest and most general to me.

**Comment by Nightfirecat** [comment]
Seems like you could even remove the trailing slashes to simplify it further: `clang-format cockatrice oracle servatrice` (haven't tested myself, but that's how most CLI utilities work)

**Comment by ZeldaZach** [comment]
Quickest way to do this is probably `clang-format -i **/*.cpp **/*.h` as it will hit every cpp/h file in the entire repo

**Comment by Nightfirecat** [comment]
That wouldn't work, as `**` does not expand to "all recursive directories" in shells. Something like `clang-format $(find . -name '*.cpp' -o -name '*.h')` should work though.

**Comment by ZeldaZach** [comment]
@Nightfirecat Yeah I realized that. I updated my comment and now have
`clang-format-all ./common/ ./oracle/ ./tests/ ./webclient/ ./cockatrice/ ./servatrice/`

**Comment by tooomm** [comment]
Other important notes that should make it to such an explanation:

https://github.com/Cockatrice/Cockatrice/pull/3083#issuecomment-363406749
https://github.com/Cockatrice/Cockatrice/pull/3083#issuecomment-363407307
