### ISSUE TITLE
Add text hint that filter are applied to the game list

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#3068]
Taken from https://github.com/Cockatrice/Cockatrice/issues/3067#issuecomment-362619646
The idea is to clarify to the user that the game list doesn't show all available games right now.

>There could be a simple little hint text **only showing** when filters are active:
![filter hint](https://user-images.githubusercontent.com/9874850/35741295-bed30cc4-0837-11e8-9fc0-10680937615d.png)
>
>I totally see people adding filters to find a suitable game, then close trice and come back a week later to wonder why there are just a few games shown. (Cockatrice remembers used filters, which is a nice feature!)

**Comment by ZeldaZach** [comment]
Seems like a good idea to me, would give me an opportunity to fix up the filters anyway

**Comment by knitknit** [comment]
I'd be happy to take a look at this one to get started. I'll poke around but if anyone has suggestions for files to start with, that would be great!

**Comment by ctrlaltca** [comment]
You may proably want to have a look at https://github.com/Cockatrice/Cockatrice/blob/master/cockatrice/src/gameselector.cpp first

**Comment by tooomm** [comment]
What do you think about my comment @knitknit? https://github.com/Cockatrice/Cockatrice/pull/3973#issuecomment-624912757

I proposed to
- Also disable the `Clear filter` button if filters set by hand do match default values.
Currently, it only disables when you manually hit the button.
- Move the game count to the headline above the game list (similar than the player count on the server is shown)
- Show a simple text hint next to the filter buttons once default is altered in any way.
Maybe such a hint can completely be skipped as long as the clear button is consistently disabled on default filter setting! Also, the current location to show the game count is not necessarily worse - I just like the headline more for consistency reasons.

**Comment by ebbit1q** [comment]
with https://github.com/Cockatrice/Cockatrice/pull/4088 you can now see the enabled button when filters are not at default
