### ISSUE TITLE
Mac Style Issues with Qt >= 5.8.0

### ISSUE THREAD

**Issue by ZeldaZach** [Cockatrice/Cockatrice#3070]
With recent changes to QT5, they have updated several style components. These changes make our tabs appear wonky and have extra space on them (See Deck, Server, Magic). We'll need to see how we can be more compatible with newer QT versions so we can advance the Mac builds. In addition, Qt5.7 was dropped by Homebrew so we'll have to start looking into being compatible with head (5.10) asap.

QT 5.7.1:
<img width="730" alt="screenshot 2018-02-04 02 52 53" src="https://user-images.githubusercontent.com/7460172/35775465-fb924d58-0956-11e8-85dd-054cfbefe2e8.png">

QT 5.10.0:
<img width="827" alt="screenshot 2018-02-04 02 54 09" src="https://user-images.githubusercontent.com/7460172/35775466-fba694c0-0956-11e8-8fd3-b7ebbf6d07c3.png">

**Comment by ZeldaZach** [comment]
QT 5.7.1:
<img width="730" alt="screenshot 2018-02-04 02 52 53" src="https://user-images.githubusercontent.com/7460172/35775465-fb924d58-0956-11e8-85dd-054cfbefe2e8.png">

QT 5.10.0:
<img width="827" alt="screenshot 2018-02-04 02 54 09" src="https://user-images.githubusercontent.com/7460172/35775466-fba694c0-0956-11e8-8fd3-b7ebbf6d07c3.png">

**Comment by Daenyth** [comment]
Looks like perhaps the default CSS changed. Ugh

**Comment by tooomm** [comment]
Are the other Qt issues solved with Qt5.10 by the way? -->https://github.com/Cockatrice/Cockatrice/issues/2647

**Comment by NickBeeuwsaert** [comment]
would it be an acceptable fix to turn documentMode on for the tab widget, so the tabs look more like the tabs in apps like safari or finder?

**Comment by ZeldaZach** [comment]
@NickBeeuwsaert I looked that up quickly and it seems like it would probably be a fine fix. I tried implementing it myself but didn't seem to get very far. If you'd like to take a crack at it, please feel free to! :)

**Comment by NickBeeuwsaert** [comment]
I've got a fix for this issue working, which doesn't need to use documentMode, and I can create a PR for it in a bit here. Should I include the documentMode changes in the PR (since, IMO it makes the app look better), or should i reserve that for its own PR?

I also noticed a second issue where changing cockatrices theme to a theme with a style.css will stop the close buttons from being drawn in qt 5.10, even if the stylesheet is empty

**Comment by ZeldaZach** [comment]
If you think they're related you're free to do one PR. If not, then two is acceptable.

Themes have always been hacky to be honest, so I'm not too surprised it's buggy
