### ISSUE TITLE
cmc filter for split/aftermath cards not working

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#3071]
<b>Info:</b>
Client Version: 2.5.0-custom(3372007) (2018-01-31)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.9.3

__________

The filter for cmc in the deck editor isn't working for split and aftermath cards.
No matter if you filter for `4`, `6` or `10` cmc... [Commit // Memory](https://scryfall.com/card/akh/211) isn't found.

**Comment by Daenyth** [comment]
I think they will also need support for `>=` etc now as well

**Comment by Vafthrudnir** [comment]
In the cards.xml these cards' CMCs are stored as `<cmc>4 // 6</cmc>`.
It should be easy enough to use either of these values, or their sum for filtering. Or any combination of the three.
Which would you prefer?

**Comment by ZeldaZach** [comment]
All 3 imo. Parse as singletons and as a combined

**Comment by Daenyth** [comment]
Yes, all 3
