### ISSUE TITLE
App crash on creating token

### ISSUE THREAD

**Issue by iecya** [Cockatrice/Cockatrice#3073]
<b>OS:</b>
MacOS Hight Sierra 
Version 10.13.1

<b>Cockatrice version:</b>
Version 2.4.0 (2017-11-19)

__________

Every time I create a token the app crashes completely. This happens with any token.
To create the token I right-click on the game board, select "Create token" (or use CMD+T as shortcut), then I select the token from the list and click on "Create". Then the app crashes and I have to restart it.
This started happening after a couple of days I installed the application. I don't recall doing anything particular in the settings other than saving new decks and changing the set order to have specific images for lands.
Also, this was happening before the OS updated to the version listed above.

Let me know if you need more info.

Thanks

**Comment by tooomm** [comment]
Does right clicking on a card and creating "related tokens" work without crashing?

Can you provide a crash log, please?

**Comment by iecya** [comment]
I've just tried on a local game, and it crashed on specific types of token (energy reserve and merfolk), while not on different tokens (I made a 4/2 beast and nth happened).
Sorry for the slight misunderstanding, but given that I only made the above two type of tokens, I though the issue was overall.
Also, when I re-open the app after crashing and re-connect to the game, the token is there :S
Before you answered me I tried to re-install the application, these are the logs I got (taken from Help > Debug Logs)

```
Client Version: 2.4.0 (2017-11-19)
Theme changed: "Default"
SoundEngine: enabling sound
Sound theme changed: "Default"
SoundEngine: enabling sound
main(): starting main program
main(): MainWindow constructor finished
CardDatabase::loadCardDatabases start
cache fail for "_trice_card_back_220291"
main(): ui.show() finished
cache fail for "_trice_card_back_298525"
[CardDatabase] loadCardDatabase(): Path = "/Users/supremadomina/Library/Application Support/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 18094 Sets= 221
[CardDatabase] loadCardDatabase(): Path = "/Users/supremadomina/Library/Application Support/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 18479 Sets= 221
CardDatabase::loadCardDatabases success
```

Let me know if this works for you or you need anything else from me

**Comment by tooomm** [comment]
It looks like the  `Create token` dialog is broken... on windows it doesn't crash, but I basically can't create the tokens I want.

Question still stands:
>Does right clicking on a card and creating "related tokens" work without crashing?

![related-token](https://user-images.githubusercontent.com/9874850/35809278-6d229126-0a88-11e8-870c-77eac2060b8f.png)

**Comment by iecya** [comment]
@tooomm yes that works, sorry I forgot to mention it.
I can create tokens that way until it gets fixed (not sure if the new merge from @ZeldaZach actually fix this) or until i figure how to give you the logs you need =) thanks for your help

**Comment by tooomm** [comment]
Hopefully @ZeldaZach found the issue. Thanks a lot for your report! ❤️ 
For me on windows it works with his fix again. 👍 

If you can't compile Cockatrice for yourself, you have to wait a bit for the next beta or stable release.
But there will be a release of a new version soon!
