### ISSUE TITLE
Disabling full screen mode doesn't work in some circumstances

### ISSUE THREAD

**Issue by Vafthrudnir** [Cockatrice/Cockatrice#3076]
<b>OS:</b>
*Win 10 v1709*

<b>Cockatrice version:</b>
*Version 2.4.0 (2017-11-19)*

__________

If you exit the program while full screen mode is enabled, on next running it can't be disabled on the first try.

**Comment by tooomm** [comment]
I can't follow you. Can you explain in some steps what you do and what's not working exactly?

**Comment by Vafthrudnir** [comment]
Go to full screen mode with either the keyboard shortcut or through the menu.
Exit the Cockatrice through the menu.
Start it again. You'll need to toggle full screen mode three times to disable it.

**Comment by tooomm** [comment]
>You'll need to toggle full screen mode three times to disable it.

Hmm, if I follow your instructions I only need to disable it once in the menu and it'll switch to normal maximized window mode directly.

I'm running this version:
>Client Version: 2.5.0-custom(3372007) (2018-01-31)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.9.3

**Comment by Vafthrudnir** [comment]
The issue seems to be solved in the beta, sorry for reporting it without checking first!

**Comment by tooomm** [comment]
Nothing wrong with that. 😉  

We didn't fix something like that particularly recently, so it must have been a side effect of some other change... 👍

**Comment by Vafthrudnir** [comment]
Thanks for the tip, I haven't knew that!
