### ISSUE TITLE
Rarity filter doesn't work on split cards

### ISSUE THREAD

**Issue by Vafthrudnir** [Cockatrice/Cockatrice#3092]
Filtering for rarity in the card filter hides all split cards (e.g. farm//market).
This is probably caused by not having the rarity information of these cards in the `cards.xml` file, even though they appear in the `.json` file correctly.

**Comment by tooomm** [comment]
>It looks like this right now:
>```
><card>
>            <name>Commit // Memory</name>
>            <set rarity="" muId="426913" num="211a">AKH</set>
>            <color>U</color>
>            <manacost>3U // 4UU</manacost>
>            <cmc>4 // 6</cmc>
>            <type>Instant // Sorcery</type>
>            <tablerow>3</tablerow>
>            <text>Put target spell or nonland permanent into its owner's library second from the top.
>
>---
>
>Aftermath (Cast this spell only from your graveyard. Then exile it.)
>Each player shuffles his or her hand and graveyard into his or her library, then draws seven cards.</text>
>        </card>
>```
>
>The `set rarity=""` value is empty.
