### ISSUE TITLE
Name change for Unhinged cards (special case for split card removed)

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#3093]
Wizards gave UNH cards an update (and oracle text).

`Who/What/When/Where/Why` is now [`Who // What // When // Where // Why`](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=74358), the same as all other split cards.

In mtgjson they are all listed as individual cards, our Oracle tool takes care of combining them for our own `cards.xml` database.
I assume we have a special rule baked in there, we most likely can remove that.

**Comment by Daenyth** [comment]
https://github.com/Cockatrice/Cockatrice/blob/a0d6a342d3b64db3b51d28baf6ae682a5d3b6972/cockatrice/src/carddatabase.cpp#L337-L338

**Comment by tooomm** [comment]
Are you sure that is the correct part in the code?
Isn't that more for some lookup instead the card database writing itself? (which should happens at oracle)

But maybe the last part `.replace('/', ' ')` isn't needed then any longer, too!

Could the needed change be located here?
https://github.com/Cockatrice/Cockatrice/blob/a0d6a342d3b64db3b51d28baf6ae682a5d3b6972/oracle/src/oracleimporter.cpp#L249

**Comment by ZeldaZach** [comment]
This doesn't seem to be an issue anymore
