### ISSUE TITLE
codacy: add/improve custom linting

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#3096]
- Avoid `foreach`
See https://github.com/Cockatrice/Cockatrice/pull/3090#discussion_r166672082

- Consistent naming conventions (lowerCamelCase) etc.
See https://github.com/Cockatrice/Cockatrice/issues/2183#issuecomment-358994979

- ...

**Comment by Daenyth** [comment]
I glanced and I'm not sure you can do this
