### ISSUE TITLE
Running 2 WLS instance on a same server

### ISSUE THREAD

**Issue by dkay703** [Cockatrice/Cockatrice#3107]
<b>OS:</b>
CentOS

<b>Cockatrice version:</b>
*Put your Cockatrice version number & build date here! For example: "2d53ce9 (2016-02-18)"
You find them inside the app under `Help → About Cockatrice` (Windows & Linux), or `Cockatrice → About Cockatrice` (macOS).*

__________

Hi,

I have a WLS 12.1.3 running on an instance.

I was working to spin up WLS 12.2.1.3 on the same machine on a different port.

After the 12.2 installation i confirmed that ./startWeblogic.sh and ./startNodeManager runs fine.

but when I try to start the ManagedServer in WLS console, i get an error 

**For server ManagedServer, the Node Manager associated with machine Machine-1 is not reachable.
Message icon - Warning All of the servers selected are currently in a state which is incompatible with this operation or are not associated with a running Node Manager or you are not authorized to perform the action requested. No action will be performed.

In WLS console, under environment>machine>machine_1>monitoring I see an error even tho Keystore/SSL tab is configured correctly (configured same as 12.1.3 which has no problem starting managed server) 

**Status: | Inactive | Current status of this Node Manager.More Info...
Problem description: | javax.net.ssl.SSLHandshakeException | Exception encountered while communicating with this node manager.More Info...
Version: | (not available)

To add a little more context, nodemanager.properties is pointing to port 5557 same as nodemanager in WLS console.

when i upgraded one of our training environment from 12.1.3. to 12.2.1.3, it had no issue. Is it not feasible to run parallel WLS on a same machine?

Any feedback will be appreciated and please let me know if more information is needed.

**Comment by Nightfirecat** [comment]
@dkay703 I think you've commented on the wrong repository.

**Comment by dkay703** [comment]
@Nightfirecat I'm sorry i'm new to github. Can you help me find where/how i can change it to the correct repo?

**Comment by Nightfirecat** [comment]
You won't be able to move this issue, you can only close it. I don't know what software you're working with, or whether they host a public GitHub repository, so I can't help you with finding the correct place to post your issue.
