### ISSUE TITLE
Segmentation fault in Archlinux

### ISSUE THREAD

**Issue by kbmaster** [Cockatrice/Cockatrice#3110]
<b>OS:</b>
*Archlinux *

<b>Cockatrice version:</b>
*2018-02-14*
__________

*
After successful compiling/installing the program crash when i try to run it

This is my output from cmake > https://paste.pound-python.org/show/UQUDZ4pNrdbgbNsU40gR/
This is my output from make > https://paste.pound-python.org/show/BTIUlMrgcq7ydCnT3iK2/
This is my output from make install > https://paste.pound-python.org/show/rIP04HLtysOR49wWtmdO/

This is the GDB output > https://paste.pound-python.org/show/v5wOfMuSoYVGOLaRS0cO/
*

**Comment by skwerlman** [comment]
after it crashes in gdb, can you type `bt` to get the full trace?

**Comment by ctrlaltca** [comment]
Looks like cockatrice is not even starting, Qt is crashing while loading the X11 platform integration plugin. You are using Qt 5.10.0, i'd try to give it a run with the recently-released 5.10.1 or the more stable 5.9.4.

**Comment by skwerlman** [comment]
qt5 version is likely not the issue, as i have version 5.10.0 working on my end without issues

the only thing that jumps out to me in terms of differences between systems is gcc version; you're on 6.3.1, while i'm on 7.3.0

**Comment by Daenyth** [comment]
If I'm reading that stack trace right it's literally crashing on the very first line of code in the application.

https://github.com/Cockatrice/Cockatrice/blob/master/cockatrice/src/main.cpp#L85-L87

**Comment by skwerlman** [comment]
are all of your qt* at the same version? if they aren't that could be the cause of the crash

**Comment by Daenyth** [comment]
Yes, try running a `pacman -Syu` and recompile

**Comment by Daenyth** [comment]
If this is still an issue let us know

**Comment by kbmaster** [comment]
Hi guys! It was a weird issue from my old archlinux installation. I tried reinstall my archlinux again and i compiled cockatrice from sources without problem. Thanks from your help. See you in coka!
