### ISSUE TITLE
Add an <alias> tag

### ISSUE THREAD

**Issue by Qriist** [Cockatrice/Cockatrice#3111]
I already spoke with Zach a little bit about this, but I hadn't yet made the request here.
Many games have extra wonky symbols in the names, or accented characters that make it a nightmare to [[link]] to even if you know the basic (non-accented) spelling. This would also allow users to [[link]] common nicknames

I suggest an unbounded <alias> tag in the XML, just under the <name> tag. 

Some examples:
(MTG)
```
<name>Márton Stromgald</name>
<alias>Marton Stromgald</alias>
```

```
<name>El-Hajjâj</name>
<alias>El-Hajjaj</alias>
```

```
<name>Dark Confidant</name>
<alias>Bob</alias>
```
_This would allow users to say, for example, "What about [[Bob]]?" and have the card linked be Dark Confidant._

(Pokemon)
```
<name>Lunala ◇</name>
<alias>Lunala *</alias>
<alias>Lunala*</alias>
<alias>Lunala Prism</alias>
<alias>Lunala Prism Star</alias>
```
_These are all ways I have seen this type of card referenced._

(YuGiOh)
```
<name>Summon Reactor・SK</name>
<alias>Summon Reactor.SK</alias>
<alias>Summon Reactor . SK</alias>
<alias>Summon Reactor*SK</alias>
<alias>Summon Reactor * SK</alias>
```
_Side note: this card name has a unicode Japanese bullet. The bullet itself and the whitespace around it is, in fact, all one character. I imagine this would elude most people in normal usage - it certainly made me scratch my head as I attempted to code the custom xml!_

As far as I can see, this would have 3 major locations where it would be useful:
-In the various chats
-deck loading (from manually edited decks)
-Manually creating a token

thanks!

**Comment by Daenyth** [comment]
We already have some lookup that helps with accented stuff. Can be
expanded. Simple name property in the code iirc

**Comment by Qriist** [comment]
Would you mind elaborating on this, or pointing me towards the documentation?

**Comment by Daenyth** [comment]
It looks like we cover some unicode->ascii normalization but not all https://github.com/Cockatrice/Cockatrice/blob/master/cockatrice/src/carddatabase.cpp#L366-L385

**Comment by Daenyth** [comment]
There's no simple off the shelf solution but we should basically be able to enumerate any common ligatures used in mtg (like Æ), along with the basic accents+graves+caron+umlaut+circle. Pain in the ass tedious code but it would work.

**Comment by Qriist** [comment]
To clarify before I workup any code, you are suggesting that, for any accented character we "round down" to the nearest non-accented equivalent?

This doesn't quite do what I had in mind but it is reasonably close that I'm willing to write up the character transformations. Just want to confirm before I execute.

**Comment by Daenyth** [comment]
Yes, that's a reasonable description of what I meant.

**Comment by ctrlaltca** [comment]
This is actually working now, card lookups are made n the normalized version of the card name, ignoring accents etc..
