### ISSUE TITLE
Add basic bold/italic to card text

### ISSUE THREAD

**Issue by Qriist** [Cockatrice/Cockatrice#3112]
Gentle request to add `<b>` and `<i> `tags to card text fields in the xml. 

Currently, attempts to add the tags break cockatrice's interpreting of the xml and.. that's it, no more loading. If you don't want to rewrite the xml parser to account for <> in the field (which I image would be a little bit of a pain) then some other symbol or tag could be used, such as :bold:**bolded text**:bold: that would switch the bold/italics on and off as it renders that text.

Example:
```
<text>♥  :bold:HP:bold: 80

☣ :bold:Evolves from::bold: Dratini

:bold:Attacks:bold:
⚔ :italic::Healing Light:italic: ⚔ 
{Colorless, Colorless}
Remove 1 damage counter from each of your Pokémon that has any damage counters on it.

⚔ :italic:Protective Wave:italic: ⚔ 
{Colorless, Colorless, Colorless}
Flip a coin. If heads, during your opponent's next turn, prevent all effects of attacks, including damage, done to Light Dragonair.

☯ :bold:Resistance & Weakness:bold:
Resistant to Psychic: -30

↯ :bold:Retreat Cost::bold: {Colorless, Colorless}</text>
```

Rendered example:
♥  **HP** 80

☣ **Evolves From:** Dratini

**Attacks**
⚔ _Healing Light_ ⚔ 
{Colorless, Colorless}
Remove 1 damage counter from each of your Pokémon that has any damage counters on it.

⚔ _Protective Wave_ ⚔ 
{Colorless, Colorless, Colorless}
Flip a coin. If heads, during your opponent's next turn, prevent all effects of attacks, including damage, done to Light Dragonair.

☯ **Resistance & Weakness**
Resistant to Psychic: -30

↯ **Retreat Cost** {Colorless, Colorless}

**Comment by Qriist** [comment]
Oh, and maybe some basic colors while we are at it.

:red:
:blue:
:green:
etc

**Comment by ctrlaltca** [comment]
You can already insert html code inside a card text.
You just need to properly escape it as needed by xml (hint: https://www.freeformatter.com/xml-escape.html)
Example:
```
<text>&lt;b&gt;Defender&lt;/b&gt;
Formidable — {G}: Glade Watcher can attack this turn as though it didn't have defender. Activate this ability only if creatures you control have total power 8 or greater.</text>

```
Result:
![schermata 2018-02-14 alle 17 49 41](https://user-images.githubusercontent.com/1631111/36216584-82328ba6-11af-11e8-80ec-6ae636f4113d.png)

**Comment by Qriist** [comment]
Oh, I didn't know that. That would be useful!


...My parser replaces the various symbols with the unicode pointer, so it renders the actual character. Lawl.

**Comment by ancestral** [comment]
This is not actual markup support, which XML certainly allows for.
