### ISSUE TITLE
Some possible features for multi-game support

### ISSUE THREAD

**Issue by DeadeyeN** [Cockatrice/Cockatrice#3114]
<b>OS:</b>
Win 10

<b>Cockatrice version:</b>
2.4

__________

A few features that I'd like to see for multi-game support:

- [ ] Ability to rotate cards 180 degrees (for Casters)
- [ ] Modify the "peek at facedown card" command to show the opponent which card was peeked at (referenced by the number displayed on the back of the card)
- [ ] Perhaps a command for "Place top X cards facedown on field"
- [ ] Might take a lot of work, but lots of games use multiple deck areas, such as Force of Will and Yu-Gi-Oh!
- [x] Ability to only display a singular power number on the bottom right of creature-like cards

**Comment by tooomm** [comment]
The last one should be possible with your recent p/t pr? @ebbit1q

**Comment by ZeldaZach** [comment]
Too many things on a single ticket, hard to track. The relevant components are all already open on different tickets.
