### ISSUE TITLE
Shortcuts regularly disabled on macOS

### ISSUE THREAD

**Issue by MrYann** [Cockatrice/Cockatrice#3117]
<b>OS:</b>
MacOS High Sierra

<b>Cockatrice version:</b>
 ef7670a (2017-03-31)

__________

Regularly, shortcuts are disabled : I am playing, with shortcuts, and then they do not work anymore. I have not been able to isolate a cause. It happens seemingly randomly; sometimes I can pay a whole game with shortcuts; sometimes they "disappear" 20 times in the same game.

To restore shortcuts, I have to fold the window (yellow "-" button) to the dock and then unfold it. Selecting a card on the board (resulting in a red border) does not restore shortcuts. Clicking on that chat window, even back and forth with some permanents on the board, does not resolve the issue either. The rest of the game is functioning as normal. Even though it looks like that, it is not simply a problem of chat window focus stealing.

Please feel free to ask for any detail if I was not precise enough.

**Comment by ctrlaltca** [comment]
I guess you are experiencing https://github.com/Cockatrice/Cockatrice/issues/2490, you may want to try updating.

**Comment by MrYann** [comment]
And now I feel silly having wasted your time. I am so used auto-update that I didn't even try that first...
Thank you anyway for your excellent ant fast answer :)

**Comment by ctrlaltca** [comment]
No worries, thank you for reporting back!

**Comment by Daenyth** [comment]
Opening a well described report doesn't waste our time. As long as you give
us info to figure out what's up it's easy for us and you should go ahead
