### ISSUE TITLE
Ansible: How to read the local variables in a role

### ISSUE THREAD

**Issue by sivana84** [Cockatrice/Cockatrice#3123]
Linux Version: Centos 6.7
Ansible  Version: 2.1

__________

Hi community,

I am trying to use local variables on the roles I have created, but once the var file is created. I don't know how and from where call those. At the moment it is not reading those local vars the role that i have created.

In that role , I am calling those vars following these steps:

    vars_files:
       - /vars/main.yml

Let me know if there is a possible way to do it or somebody has been working on this before with success, perhaps calling those from the main playbook which contains the call to the hosts and roles? ;)

Thanks,
Best Regards.
Sivana

**Comment by ctrlaltca** [comment]
Dear Silvana, this repository is about a program for playing tabletop card games. I suppose you opened the issue on the wrong repository. If you followed a link somewhere that lead you here, please tell us the page where you found this link so that we can fix it. Thank you.

**Comment by sivana84** [comment]
Hi ctrlaltca,

github doesn't resolve questions about ansible? If there is another section do you know which one it is?
Not sure, how I ended on this link if it is not related ;/

Kind regards,
Guillermo

**Comment by ctrlaltca** [comment]
You may want to open your issue on the ansible repo: https://github.com/ansible/ansible/issues

**Comment by Daenyth** [comment]
@sivana84 github is a website somewhat like facebook for software. We are just one page on here, ansible is another. I'm not sure what link you followed that brought you to us specifically

**Comment by sivana84** [comment]
This link was the root cause ;)

https://github.com/Cockatrice/Cockatrice/wiki/How-to-Create-a-GitHub-Ticket

I didn't know that, thanks for  your help

Regards,
Guillermo

**Comment by tooomm** [comment]
Haha. Looks like our help page for users might show up highly in google searches or gets linked from other projects? :D

Thanks for letting us know @sivana84 
And good luck with your issue!

**Comment by sivana84** [comment]
thanks tooomm :)

Kind regards
Sivana

**Comment by skwerlman** [comment]
I've changed the title of that page (and updated the links pointing to it) to hopefully reduce the confusion in future.
