### ISSUE TITLE
vc_redist_64.exe did not complete automatically during installation

### ISSUE THREAD

**Issue by Nightfirecat** [Cockatrice/Cockatrice#3125]
<b>OS: Win 7 SP1</b>
<b>Cockatrice version: 2.5.0 (2018-03-02)</b>

__________

During installation using the usual Help -> Check for Updates method, the `Executing vc_redist_64.exe /quiet /norestart` step did not complete automatically, and the installation did not proceed until I killed the vc_redist_64.exe task from the command prompt.

**Comment by ctrlaltca** [comment]
> , the Executing vc_redist_64.exe /quiet /norestart step did not complete automatically

Did you mean that you waited a few minutes, and after seeing it was not going anywhere assumed it was stuck?

Can you please try to run it manually (without the /quiet parameter) and see if it causes the same problem?

I'm afraid we can't really fix the vc_redist installation if it doesn't work.. but let's try to better understand what's broken before.

**Comment by Nightfirecat** [comment]
As soon as I invoked it from a command prompt, it spawned a "Microsoft Visual C++ 2017 Redistributable (x64)" window, which didn't happen during installation of Cockatrice.

**Comment by ctrlaltca** [comment]
Yep, that's because of the `/quiet` parameter.
Did it work installing after all?

**Comment by Nightfirecat** [comment]
It did install successfully when following through the visual installation.

**Comment by tooomm** [comment]
@Nightfirecat check #3175 and the related comments following https://github.com/Cockatrice/Cockatrice/issues/3169#issuecomment-379282254. 👍
