### ISSUE TITLE
Register to Server not working 

### ISSUE THREAD

**Issue by DiabolicDropBear** [Cockatrice/Cockatrice#3126]
HI there,

I"m trying to Register to server but i keep coming across a really frustrating error that says I'm a registered user, which i know i am, problem is i don't see anyway to Login to it. My username is the same as my current GitHub username and it's incredibly frustrating.

Thoughts?

<b>OS:</b>
WIndows 10, 32gb RAM, 4gb video 970M

<b>Cockatrice version:</b>
Cockatrice (64-bit)
Version 2.5.0 (2018-03-02)

__________

*Explain your issue/request/suggestion in detail here!*

**Comment by Vafthrudnir** [comment]
You should be able to log in to a server with the "Connect" option instead of "Register to server" in the "Cockatrice" menu, do you get the same error with that one?

**Comment by DiabolicDropBear** [comment]
Hi there,

Yes it works, but i was previously a registered user but i can't seem to
find my Username/Password or do anything of the sort to login to Cockatrice.

Ideas?

**Comment by Vafthrudnir** [comment]
Hi,
In the connect window there's a "Forgot password" button that should email you a new password.

**Comment by DiabolicDropBear** [comment]
Hi there,

I tried that, problem is I forgot my username... the only thing i can
remember is that it's most likely DiabolicDropBear. there is also this
error message.

**Comment by Vafthrudnir** [comment]
If you also forgot your username, If you insist on getting your account back, I think the only solution would be contacting the server administrators with the problem. Otherwise just register as a new user.

**Comment by DiabolicDropBear** [comment]
Oh, i thought you were the server administrators.

**Comment by Vafthrudnir** [comment]
No, we are the developers. Which server are you trying to connect?
E.g for woogerworks you can find the contact information over at http://woogerworks.com/

**Comment by DiabolicDropBear** [comment]
Trying to connect to Chickatrice so i suppose i should ask them then.

Thank you for your help in this.

regards
