### ISSUE TITLE
Inability to save card files

### ISSUE THREAD

**Issue by raidereric2** [Cockatrice/Cockatrice#3130]
<b>OS:</b>
*Put your operating system here! For example: "Win 7 SP2", "macOS 10.12.3", "Ubuntu 16.10" etc.*
Windows 8 64-bit
<b>Cockatrice version:</b>
Cockatrice Version 2.5.0
*Put your Cockatrice version number & build date here! For example: "2d53ce9 (2016-02-18)"
Version 2.5.0 (2018-03-02)
You find them inside the app under `Help → About Cockatrice` (Windows & Linux), or `Cockatrice → About Cockatrice` (macOS).*

__________

*Explain your issue/request/suggestion in detail here!*

Hello, I had recently redownloaded Cockatrice after resetting my PC back to factory settings. After downloading the program, it seems I cannot save cards, or card images at all.  It seems that I'm not able save cards, tokens, or card images at all. When I go to Cockatrice --> Check for Card Updates and click through I end up with the error "The file could not be saved to C:/Program Files (x86)/Cockatrice.cockatrice.exe"

**Comment by Daenyth** [comment]
It sounds like your image location settings are wrong. Try changing the card image path in settings to be a location your user can write to

**Comment by tooomm** [comment]
It sounds more like he can't download the card database in the first place.

>When I go to Cockatrice --> **Check for Card Updates** and click through I end up with the error "The file could not be saved to C:/Program Files (x86)/Cockatrice.cockatrice.exe"

Do you see any cards in the deck editor list at all when you open the program @raidereric2?

**Comment by raidereric2** [comment]
I factory reset my pc again, updated my 32-bit settings from windows, and changed the location to save cards to a notepad file. For reasons I can't explain it worked this time. I thank you all for your time, I hope it continues to work!
