### ISSUE TITLE
Automatic updating of custom XMLs

### ISSUE THREAD

**Issue by Qriist** [Cockatrice/Cockatrice#3131]
Very simply, I want to add a tag at the top of a custom set XML that includes a link that can be checked for updating the XML. Something in the vein of:

`<UpdateURL Date="2018-03-10" Frequency="7">http://web.site/to.xml</UpdateURL>`

Date being the Year-Month-Day that the XML is published, Frequency being how many days from that date to redownload (based on the creator's expected push dates). In this example, every day between 2018-03-10 and 2018-03-16 (inclusive) the prog would load normally, while dates from 2018-03-17 onward the prog will download and replace the XML as part of the startup.

Alternative schemes could be to have an embedded version number that is read and checked against on each startup, or to have an attribute that refers to an external text that holds the date of the last updated XML and compares: `<UpdateURL Date="2018-03-10" UpdateCheck="http://web.site/to.txt">`

Whatever method is used, this would really help the maintainers ensure that the users are up to date.

**Comment by Daenyth** [comment]
If we do this we should probably put some energy into fuzzing the xml parsing to make sure it can't become an attack vector.

**Comment by ZeldaZach** [comment]
I'm looking at the "Frequency" component and I'd want to put a hard set in place that they can ENUM from (daily, bi-weekly, monthly, etc)

For the "UpdateCheck" component, I'd still want a frequency status in place; Pinging tons of websites every reload is almost like a DOS method.

**Comment by Qriist** [comment]
Sure, just what sort of conditions are you looking for?

**Comment by ZeldaZach** [comment]
This is a great step towards moving to an Oracle-less service. Gonna call this essentially part 1 of #4109
