### ISSUE TITLE
Token creation bug

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#3137]
If you open the `Create token` dialog and type/select a token you get that token.
If you type "hi" a blank token with the color of your choice is created.

But if you leave the field blank it creates a nameless token with [this card image from UNH](https://scryfall.com/card/unh/23):
![token_creation_wrong](https://user-images.githubusercontent.com/9874850/37481677-a496d2bc-2882-11e8-91ac-1a089bdbc815.png)

Our card image look up might be wrong here.

**Comment by ZeldaZach** [comment]
I don't know if this is necessarily a bug as the unhinged card technically has no name. You have never been able to make a token w/o a name afaik

**Comment by Nightfirecat** [comment]
This card has a name: `"_____"`. It sounds like the empty string is matching that in error.

**Comment by ctrlaltca** [comment]
Currently when creating a token the card name is looked up on the card database using its "simplified" name. Since the simplified name of the`"_____"` card is just an empty string, that one is returned.
We could checking the exact card name instead and fix this corner case, but we will lose the ability to find any card using its simplified name.

**Comment by Nightfirecat** [comment]
Is the simplified name part of MTGJSON or do we compute that? Perhaps this card needs to be considered and _not_ simplified that way.

**Comment by ctrlaltca** [comment]
We compute that: https://github.com/Cockatrice/Cockatrice/blob/master/cockatrice/src/carddatabase.cpp#L366
I'd avoid adding exceptions for specific cards, but we could just add "_" to the list of characters that are not removed from the card name.

**Comment by ctrlaltca** [comment]
This was "fixed", even if not properly or intentionally.
The create token dialog now proposes a default "Token" name, and you can't create a token with an empty name anymore.
