### ISSUE TITLE
Issues with "Tips of the Day"

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#3139]
- **Tips loop!**
There is no way to only make them appear once there are new tips available (after you saw them all). The dialog will pop up again and again without providing benefit.
This leads to annoyed users and *everybody* will disable it. So nobody will see newly added tips in the future and the feature is not helpful at all. :)

Too bad nobody realized that in the PR...
Now it's in a release (with no former beta test period) and most users disabled it by now for sure!

- **There is no way to open the tips dialog other than (re)starting the app.**
There should be a menu entry somewhere.
I also miss a option in settings to enable/disable the tips (Maybe open from there instead the menu? Didn't put any thoughts in which might be better)

**Comment by Daenyth** [comment]
ping @Vafthrudnir

**Comment by ZeldaZach** [comment]
(We can always override the user settings with new tips at some point, so them disabling it is not the end of the world)

**Comment by Vafthrudnir** [comment]
Yes, that's a good idea - once all of the tips were seen, the window shouldn't pop up again. I think this feature should be implemented before new tips are added, so we only have to override the user settings once to show tips again.
Regarding the other topic, I suppose we can add a Tips of the Day button to the Help menu. I don't really see it as vital, but it's easy enough to add - so why not.
And I think there's an option in settings, in the General tab to enable or disable it.

**Comment by tooomm** [comment]
>And I think there's an option in settings, in the General tab to enable or disable it.

You are absolutely right. I totally missed it because it blends in with the rest.
Actually, it's misplaced between all the picture settings. :)

It should be below the reset picture button and see it's own line
(instead being displayed next to the unrelated "how to customize pictures" link):
![settings-tips](https://user-images.githubusercontent.com/9874850/37495389-4b84652e-28ad-11e8-8c12-11aba365440d.png)

**Comment by Vafthrudnir** [comment]
OK, so this issue boils down to three tasks:

- [ ] Move the "Show tips on startup" option to a better suited place in the settings tab. What about here: 
![image](https://user-images.githubusercontent.com/9273978/37517089-a03b3576-2910-11e8-9f32-b64828430b71.png)
- [ ] Store the "date added" property of the last seen tip in the user config file, and don't show the window again if no newer tips exist. If a new tip is added, show that first. Additionally, override the user settings to show tips again when this feature gets implemented.
- [ ] Add a "Tip of the Day" button to the Help menu.

Is there anything else?

**Comment by tooomm** [comment]
Wouldn't storing the date lead to confusions if tips have the same "date added" value?
Can we use a unique index number per tip instead?
Save the "tip id" for the last seen one and open with the next bigger one on next start.
This same "opening rules" should apply for opening tips from the menu.

How are tips added by the way?

About the settings change.
Your suggested location is also fine. 👍 
All picture stuff could see its own group even (like paths), and the cache size settings would fit there too.

**Comment by ZeldaZach** [comment]
@tooomm That's how tips are done... it starts at old+1 where old was the last tip you viewed. Did you have time to fully test this feature before this ticket? 😛 

Tips are added by editing the XML file in the resources folder and adding images there too.

**Comment by Vafthrudnir** [comment]
@tooomm Yeah, tips with the same date would probably confuse it, that didn't occure to me.

My first idea was also to store the index of the tip, but indexing is easy to mess up if some tips are removed or added to the wrong place in the xml. Though this could work if we only add new tips to the end, and don't remove any.

By the way, to add a tip you need to modify the xml in the resources/tipoftheday folder.

**Comment by tooomm** [comment]
@ZeldaZach I realized that, yes 😉 

<br>

>My first idea was also to store the index of the tip, but indexing is easy to mess up if some tips are removed or added to the wrong place in the xml. 
>Though this could work if we only add new tips to the end, and don't remove any.

For removing tips, id's could stay in the xml but with an empty tip and empty tips are skipped? Or have a boolean `display` value for each tip and keep all of them but flip the value?

Also, id's could be 10,20,30 instead 1,2,3. That way you can add in 11 in between later on. That's a common practice for position numbers in part lists (engineering) for example.
That would lead to everybody who passed id20 already to not see the id11 tip of course, but gives us the possibility to reorder or add a follow up tip to another related one if needed.

**Comment by Daenyth** [comment]
I'm OK with a file-order based solution for "seen" awareness. We can just
add new ones at the bottom.

**Comment by tooomm** [comment]
Fixed with #3152
