### ISSUE TITLE
Register to woogerworks not working.

### ISSUE THREAD

**Issue by markjitsu** [Cockatrice/Cockatrice#3142]
<b>OS:</b>
*Windows 10 Pro 64 bit*

<b>Cockatrice version:</b>
*Cockatrice (64-bit)
Version 2.5.0 (2018-03-02)
.*

__________

*I successfully registered to woogerworks with my email.  I played a couple games of magic with a friend.  

Closed program, shut down computer and rebooted next day to try it out again.  When I click connect to server, its asking me to register again.  I already typed in the code sent to my email once.

When I try to register with the same email it says an email already exists that is registered.  My username is markjitsu
*

**Comment by Daenyth** [comment]
Please contact the server admin via their website.
