### ISSUE TITLE
Card Database won't update

### ISSUE THREAD

**Issue by damballah666** [Cockatrice/Cockatrice#3143]
Hey all, just downloaded, and it's giving me an error upon doing the card database update. 

It says "Unable to run the card database updater: /Applications/oracle"

After the app launches, I can go click on update card databse, and it says one is already running.

Thanks!

S

<b>OS: mac os 10.13</b>
*Put your operating system here! For example: "Win 7 SP2", "macOS 10.12.3", "Ubuntu 16.10" etc.*

<b>Cockatrice version:2.5</b>
*Put your Cockatrice version number & build date here! For example: "2d53ce9 (2016-02-18)"
You find them inside the app under `Help → About Cockatrice` (Windows & Linux), or `Cockatrice → About Cockatrice` (macOS).*

__________

*Explain your issue/request/suggestion in detail here!*

**Comment by Daenyth** [comment]
Try opening oracle manually from Applications. I wonder if this is the "are you sure you want to run this unsigned app" thing

**Comment by damballah666** [comment]
I dont have an application called oracle at all. Ive been looking and it's definitely not here.

**Comment by damballah666** [comment]
Got it! I had to drag the oracle icon to applications along with cockatrice on install. 

Thanks!

**Comment by Daenyth** [comment]
It's also probable that we could add a check explicitly to warn the user about this on launch
