### ISSUE TITLE
 Notification for a buddy coming online

### ISSUE THREAD

**Issue by akirhonn** [Cockatrice/Cockatrice#3144]
Hi,
It's not an issue but a proposition for a new feature.

I think it could be really cool to have a notification when a buddy connects to Cockatrice.

Thank you.
Kind regards.

**Comment by tooomm** [comment]
related https://github.com/Cockatrice/Cockatrice/issues/2552#issuecomment-291779905

**Comment by akirhonn** [comment]
I'm agree to say it can be an option you can enable/disable.
