### ISSUE TITLE
Check for card updates broken

### ISSUE THREAD

**Issue by nikisix** [Cockatrice/Cockatrice#3148]
<b>OS:</b>
macOS Sierra 10.12.6

<b>Cockatrice version:</b>
Version 2.5.0 (2018-03-02)
__________

Clicking
*Actions* > *Check for card updates*
yields:

Unable to run the card database updater: /private/var/folders/kf/kpqzhjld3073h3z4zhs264900000gn/T/AppTranslocation/C2444B55-916C-40ED-8A38-63DEEF662E43/d/oracle

**Comment by ctrlaltca** [comment]
Where are you running cockatrice from? Maybe you did not copy both Cockatrice and Oracle to the "Application" folder?

**Comment by ZeldaZach** [comment]
This looks like you're running it from the DMG download and not from the applications folder

**Comment by nikisix** [comment]
Nope, definitely running from the applications folder

**Comment by ctrlaltca** [comment]
The `/private/var/folders/kf/kpqzhjld3073h3z4zhs264900000gn/T/AppTranslocation/C2444B55-916C-40ED-8A38-63DEEF662E43/d/` folder name is suggesting that macOS is triggering app translocation when running Cockatrice.
This is a "security" feature that macOS uses when an application is started from a "unsecure" folder (eg. "Downloads") or for applications that has not been installed (copied) correctly by Finder (i saw some reports of "PathFinder" users complaining about this).

I suggest you to try removing the current cockatrice/oracle from Applications and copy them again using Finder from a fred downloaded copy of the dmg.

Soma background informations: https://lapcatsoftware.com/articles/app-translocation.html

**Comment by nikisix** [comment]
The reinstall worked. Thanks for the info/help
