### ISSUE TITLE
"Show related cards" naming is missleading

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#3154]
In #3113 a right-click menu got added to the list of cards in the deck editor.
There you can display back sides of cards (transform and melt).

But due to the term "related" and other features in the client which use this terminology (in-game --> create related card) one expect it to find/link tokens, emblems etc. too. Which is not the case.

I would like to be able to show these cards too, or rename the menu entry in the deck editor.
`Show backside` or `Show card back` could be an option.

**Comment by Vafthrudnir** [comment]
Anything with `backside` wouldn't be exact, because it works with Kamigawa flip cards as well. Maybe the rest of the cards you listed (tokens, emblems, etc.) should be added to the menu, and then the "related cards" name would be okay.

**Comment by tooomm** [comment]
Also, the in-game option (#3115) is named `View related cards`, but the option in the deck editor is `Show related cards` (#3113). That should be uniform.

**Comment by tooomm** [comment]
This is fixed for me now when trying the 2.7.6-beta.2 release.
I could find emblems **and** tokens next to back sides.
