### ISSUE TITLE
arrow keys not functioning

### ISSUE THREAD

**Issue by Rendroc** [Cockatrice/Cockatrice#3160]
<b>System Information:</b>
   
MacBook Air (Early 2014) Intel Core i7

MacOS High Sierra 10.13.2
_________________________________________________________________________________

   
The arrow keys are unresponsive after upgrade to the newest version. So I can't edit my deck in the deck editor!

**Comment by tooomm** [comment]
You should copy the client version you are running here too... that's the most important information.

I think you run into https://github.com/Cockatrice/Cockatrice/pull/3116 if you are running 2.5.0, you now have to use Shift key in combination with the arrow keys.
Feel free to reopen if you still have problems! 👍
