### ISSUE TITLE
Removing counters

### ISSUE THREAD

**Issue by scpsc** [Cockatrice/Cockatrice#3161]
<b>System Information:</b>
   Client Version: 2.5.0 (2018-03-02)

_________________________________________________________________________________

Hi,

This might be related to #3049, but as my problem does not involve updating shortcuts, I thought it was better to open a new case.

So here is the issue: using shortcuts, when I add counters on a permanent, I cannot remove any before I right-clicked on the card (no need to choose an option). Once it is done, then I can use shortcuts to add or remove counters. For some reason I cannot determine, reducing counters sometimes becomes locked again on some cards and I need to right-click on it again.

Thank you for your time.

**Comment by skwerlman** [comment]
you can only use shortcuts on a selected card. are you able to use shortcuts on a card after simply left-clicking on it?

**Comment by scpsc** [comment]
Yes, but by selecting with left-click, I can only add counters, not removing some. To do so, I have to right-click first, then it is behaving normally for this specific card (but sometimes it gets blocked again at some point). This behavior is true for each card on the battlefield.
