### ISSUE TITLE
Invalid Username for an account I've had for years

### ISSUE THREAD

**Issue by magnumforce2006** [Cockatrice/Cockatrice#3162]
<b>System Information:</b>
   

_________________________________________________________________________________

   
Today when trying to log in I was told I have an invalid username. It's magnumforce2006.

The new requirements say my username can only be a max of 12 characters. Is there a way to fix this without completely registering a new account? I had a large list of friends and blocked users that I'd rather not lose.

**Comment by skwerlman** [comment]
contact the admin of your server directly. they will be able to manually edit your username for you.

a list of servers and their points-of-contact can be found here: https://github.com/Cockatrice/Cockatrice/wiki/Public-Servers

**Comment by CavalryWolfPack** [comment]
HOw exactly do we do that? I'm on the woogerworks server and having the same issue

**Comment by magnumforce2006** [comment]
Yeah I don't see any direct contacts to the server admin.... Their twitter account?

**Comment by CavalryWolfPack** [comment]
There's gotta be another way.

**Comment by magnumforce2006** [comment]
Paging @woogerboy21 . What are we supposed to do if our usernames (which we've had for years) are now too long. can you change them manually?

**Comment by skwerlman** [comment]
This is not a contact form for server admins. Please use the contact info found on the wiki page, or the contact info found on your server's website (also linked on the wiki page) to contact the admin directly.

**Comment by magnumforce2006** [comment]
@skwerlman where is the Woogerworks wiki? Not trying to be daft, but google reveals nothing here. I would love to contact the admin, but I simply don't know how, and the link you've provided reveals nothing.

**Comment by skwerlman** [comment]
the page i linked above is the wiki page i'm referring to

**Comment by magnumforce2006** [comment]
The only links listed there are the Woogerworks Twitter and Github, neither of which seem to be proper methods to directly reach the administrator.

**Comment by skwerlman** [comment]
in the first column, the website is linked

**Comment by magnumforce2006** [comment]
Found an email address on the Xmage site. For anyone wanting to contact the admin for a potential fix to their username it's:

cockatrice-inquiry@woogerworks.com

**Comment by woogerboy21** [comment]
There is contact information off the woogerworks website.

**Comment by magnumforce2006** [comment]
I send an email to cockatrice-inquiry@woogerworks.com

I believe this is the correct method?

**Comment by woogerboy21** [comment]
And also to answer this issue, the existing woogerworks main server has had issues and the original configuration for the server was lost.  The current temp server is running with a default configuration that needs the name limitations adjusted.  It will be this way for a while as I have family things to take care of.  Once corrected users with longer names will be able to login again.  I attempted to update it remotely so it may be fixed for users that have 16 characters or less but my connectivity is spotty at best right now and of the change didn’t take the users with names longer than 12 characters will have trouble logging in till the configuration update is applied.

Users are more than welcome (and encouraged) to try using other cockatrice servers operated by other operators.

Also as mentioned in a quick previous message, contact information for woogerworks is off the website .  Using the contact link will take you to the details.  

Thanks

**Comment by magnumforce2006** [comment]
Ok, thanks for the info!
