### ISSUE TITLE
game crashes when leaving a game; game crashes when attempting to update cockatrice

### ISSUE THREAD

**Issue by DaisyRedRyder** [Cockatrice/Cockatrice#3166]
<b>System Information:</b>
   

Theme changed: "Default"
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
main(): starting main program
main(): MainWindow constructor finished
CardDatabase::loadCardDatabases start
cache fail for "_trice_card_back_220291"
main(): ui.show() finished
cache fail for "_trice_card_back_238359"
_________________________________________________________________________________

   
As title suggests,
When an opponent leaves the game, the client crashes;
The client will crash on occasion when either opponent or I concede a game
When I attempt to update cockatrice, the dialogue box appears and the client crashes;
Using the Macbook pro 2017, 13"

**Comment by ZeldaZach** [comment]
This is a known issue #3001 

We appreciate your help and hope you continue to help find bugs!

**Comment by DaisyRedRyder** [comment]
this known issue is only for when the opponent concedes,
The client is also crashing when I attempt to update the program.
As of now, I can not connect to the server and play online

**Comment by tooomm** [comment]
Your client is probably out of date and too old to update itself. Try updating from our webpage: https://cockatrice.github.io/

**Comment by Vafthrudnir** [comment]
Which cockatrice version are you using?

**Comment by DaisyRedRyder** [comment]
Thanks,
This is what I did last night. It seems to have done the trick, but I won't
be able to test it until I recover my password with woogerworks.
Unfortunately, I am not sure what version of Cockatrice I was running
before this. Is there a way to check if I recover the original file from
the recycling bin?

**Comment by DaisyRedRyder** [comment]
I just realized woogerworks has ended cockatrice support, I redirected my
password reset inquiry to cockatrice as per woogerworks' website.

**Comment by tooomm** [comment]
I assume this is solved.
