### ISSUE TITLE
Problem for connect my account

### ISSUE THREAD

**Issue by SimoneTR** [Cockatrice/Cockatrice#3170]
<b>System Information:</b>
   
Hi to all, when i open cocka and click on connect for enter to play, 
I see a window that tells me that: your client seems to be missing features this server requires for connection. 
how can I solve this problem?
thanks to those who will answer
_________________________________________________________________________________

**Comment by ctrlaltca** [comment]
You need to update Cockatrice. Download from https://cockatrice.github.io/ or https://github.com/Cockatrice/Cockatrice/releases
