### ISSUE TITLE
Cant verify my email

### ISSUE THREAD

**Issue by chancemullen96** [Cockatrice/Cockatrice#3176]
<b>System Information:</b>
   

   
__________________________________________________________________________________

**Comment by ZeldaZach** [comment]
This is the development server. If you have any issue, you can reach out to the appropriate server operator

**Comment by chancemullen96** [comment]
what do you mean, I looked up an old request to fix an email and made a new issue in the same spot, wheres the right spot

**Comment by Nightfirecat** [comment]
> reach out to the appropriate server operator

We don't know what server you're connecting to--go to the website for that server and that will have contact information for your account issue.
