### ISSUE TITLE
non funziona cockatrice

### ISSUE THREAD

**Issue by Darioscala** [Cockatrice/Cockatrice#3179]
non funziona cockatrice, non mi fa stappare o tappare le terre, non mi permette di giocare.Spesso è molto lento e quando io cerco di entrare nella stanza non mi fa entrare
_____
it does not work cockatrice, it does not make me uncork or plug the lands, it does not allow me to play. It's often very slow and when I try to enter the room it does not let me in

**Comment by ZeldaZach** [comment]
I recommend you update at http://cockatrice.github.io/ and see what happens

**Comment by Daenyth** [comment]
What version of Cockatrice is installed, and what operating system are you on?
