### ISSUE TITLE
crash if you try to connect without a pw entered

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#3182]
<b>System Information:</b>
Client Version: 2.5.0-custom(4589d0e) (2018-04-09)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.9.4
__________________________________________________________________________________

I experienced a weird behavior:
When you try to connect to a server only with a user name entered you get an error message.
But when you start typing a pw, and delete it then again completely... connecting crashes the app.

That's the content of my `servers.ini`:
```
[server]
auto_connect=0
server_details\totalServers=43
save_password=0
previoushostName=Rooster Ranges
server_details\saveName40=Chickatrice
server_details\server40=chickatrice.net
server_details\port40=4747
server_details\username40=
server_details\savePassword40=false
server_details\password40=
server_details\isCustom40=false
server_details\saveName41=Dr4ft Cockatrice
server_details\server41=cockatrice.dr4ft.com
server_details\port41=4747
server_details\username41=
server_details\savePassword41=false
server_details\password41=
server_details\isCustom41=false
server_details\saveName42=Tetrarch
server_details\server42=mtg.tetrarch.co
server_details\port42=4747
server_details\username42=
server_details\savePassword42=false
server_details\password42=
server_details\isCustom42=false
server_details\saveName43=Rooster Ranges
server_details\server43=server.cockatrice.us
server_details\port43=4747
server_details\username43=*myusername*
server_details\savePassword43=false
server_details\password43=
server_details\isCustom43=false

```

The `totalServers=43` value looks very suspicious. 😄 
It looks to be somehow related to #3165 because once you refresh your list it'll increment the values.

Also, with 2.5.0 I can't reproduce the crash...

**Comment by ZeldaZach** [comment]
Fixed. Had a racetime
