### ISSUE TITLE
!!! pw leak on every connect

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#3183]
<b>System Information:</b>
Client Version: 2.5.0 (2018-03-02)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.9.3
__________________________________________________________________________________

The pw is saved to the `servers.ini` on every connect, even if you don't have the `save password` option checked.

**Comment by ZeldaZach** [comment]
Fixed with my PR
