### ISSUE TITLE
"You are flooding the game. Please wait a couple of seconds." when loading a deck

### ISSUE THREAD

**Issue by MisterMeowgi** [Cockatrice/Cockatrice#3191]
Hi, when I try to play (after I load a deck) I get continuous messages in the chat saying "You are flooding the game. Please wait a couple of seconds."

I have tried this on multiple accounts on multiple servers, using multiple decks, and am continuing to get the same error. Does anyone have any information on this? The debug log doesn't change when this occurs, and I haven't found anything online about it. Any help would greatly be appreciated.

![image](https://user-images.githubusercontent.com/38267915/38590763-43c48e14-3d01-11e8-98eb-4618e026cc80.png)

**Comment by skwerlman** [comment]
what version of cockatrice are you running? you can get the version info from the top of the debug log

**Comment by ZeldaZach** [comment]
Take a look at what Homebrew does with checkboxes and such

**Comment by Daenyth** [comment]
This is weird. Looks like @ZeldaZach's server. The config shouldn't be doing this on a deck load, but I'd also expect it to affect all users equally

**Comment by ZeldaZach** [comment]
He’s probably breaking the 10 actions per second limit that’s set by default. Loading a deck is one action, but if you’re spamming before it may not work

**Comment by Daenyth** [comment]
If you can record a screen capture of this happening it would be helpful

**Comment by MisterMeowgi** [comment]
Hey guys, I figured it out. My push-to-talk for voip is set to F9, which also happens to be a hotkey for moving to MP2. I removed the hotkey and it is working now. Thank you for all for looking into this for me
