### ISSUE TITLE
Moving cards in the Decklist

### ISSUE THREAD

**Issue by Steackfreet** [Cockatrice/Cockatrice#3195]
<b>System Information:</b>
   
Client Version: 2.5.0 (2018-03-02)
Client Operating System: Windows 7 SP 1 (6.1)
Build Architecture: 64-bit
Qt Version: 5.9.3
Trying to load picture (set:  "DD3_DVD"  card:  "Demonic Tutor" )
Picture found on disk (set:  "DD3_DVD"  file:  "Demonic Tutor" )

   
________________________________________________________________________________________

   
In the decklist double clicking on a card no longer moves it from main deck to sideboard.... but still work from sideboard to main deck.

**Comment by Vafthrudnir** [comment]
This is a confirmed bug in non-English versions of the program, the next release will fix the issue. In the meanwhile changing the language to English should solve the problem.

**Comment by Steackfreet** [comment]
Thx for the info
