### ISSUE TITLE
Card template change: "to your mana pool" no longer part of template.

### ISSUE THREAD

**Issue by Psithief** [Cockatrice/Cockatrice#3196]
All old cards are ***probably*** going to receive non-functional errata that will remove any references to the mana pool for abilities that add mana, as of Dominaria.

Suggest replacing:
```
if (cardTextRows[i].contains("{T}") && cardTextRows[i].contains("to your mana pool"))
```

with
```
if (cardTextRows[i].contains("{T}") && (cardTextRows[i].contains("Add ") || cardTextRows[i].contains(", add ")))
```
Is `contains` case-sensitive?

We don't yet know if there will be additional templating changes for complicated cards, so this may not work. (See `Charmed Pendant`)

---

## Related

#2904 tablerow parsing error
#3178 non-lands skip stack

**Comment by Daenyth** [comment]
`contains` is definitely case sensitive. See also https://magic.wizards.com/en/articles/archive/news/dominaria-frame-template-and-rules-changes-2018-03-21

**Comment by ZeldaZach** [comment]
This should be caught via Oracle, and is very important

**Comment by ZeldaZach** [comment]
Note: Only give Row 0 for Land types
