### ISSUE TITLE
Cockatrice Crashes on Update - Access Violation

### ISSUE THREAD

**Issue by kylerkinnear1** [Cockatrice/Cockatrice#3197]
<b>System Information:</b>
dab7316
Windows 7 Home Premium
Service Pack 1

Theme changed: "Default"
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
main(): starting main program
main(): MainWindow constructor finished
CardDatabase::loadCardDatabases start
main(): ui.show() finished
QWindowsWindow::setGeometry: Unable to set geometry 1280x741+0+20 on QWidgetWindow/'MainWindowClassWindow'. Resulting geometry:  1280x738+0+22 (frame: 8, 30, 8, 8, custom margin: 0, 0, 0, 0, minimum size: 857x741, maximum size: 16777215x16777215).
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Kyle/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 18119 Sets= 222
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Kyle/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 18512 Sets= 223
CardDatabase::loadCardDatabases success
________________________________________________________________________________________

Whenever I attempt to run Help -> Update Cockatrice, the application crashes. I used the JIT debugger in Visual Studio and it appears it is caused by a memory access violation (referencing memory location 0x0000000). It is consistent and happens every time.

I have a crash dump, but the file is too large to upload on GitHub. If you'd like the crash dump, let me know and I can try and get it to you.

I've also uploaded the Windows Event Log.
[crash (2).zip](https://github.com/Cockatrice/Cockatrice/files/1910701/crash.2.zip)

**Comment by ZeldaZach** [comment]
Known issue, solution is to update manually from our website. We changed hosts rapidly and didn't have time to put in a redirection link

**Comment by tooomm** [comment]
Yes, your client is too old to use the build in updater anymore to download recent versions.
After manually updating once, it'll work again. 👍
