### ISSUE TITLE
Closing main Cockatrice window with "Tip of the Day" open does not close the app

### ISSUE THREAD

**Issue by Nightfirecat** [Cockatrice/Cockatrice#3199]
<b>System Information:</b>
```
Client Version: 2.5.0 (2018-03-02)
Client Operating System: Windows 7 SP 1 (6.1)
Build Architecture: 64-bit
Qt Version: 5.9.3
```
________________________________________________________________________________________

See title. When the Tip of the Day window is open, closing the main window does not close the app.

**Comment by tooomm** [comment]
On Windows 10 I can't close the main window as long as `Tip of the Day` is open?

**Comment by Daenyth** [comment]
cc @Vafthrudnir ?
