### ISSUE TITLE
Card database: multiple parser engines

### ISSUE THREAD

**Issue by ctrlaltca** [Cockatrice/Cockatrice#3201]
It would be nice to take the "xml file loader and parser" logic out of the card database.
Creating a generic interface with a few methods that a card parser should implement, we could add support for multiple parser engines.
We currently support only xml files in the `cockatrice_carddatabase version="3"` format, but supporting multiple parser engines we could easily add support for other formats like eg. json, a different xml format, a folder with one card per file etc..

A parser engine should implement at least these methods:
  * "can i parse this file?": a method  that receives the full file path and detects if the parser is able to load that file (checking file extension, cockatrice_carddatabase version, etc..). The card database would just poll each parser until it founds one capable of loading the file;
 * "parse this file": a method that actually parses the file

A few things that needs to be sorted out while developing this:
 * how to handle conflicts (duplicated card names?)
 * wether to make the parser directly call `cardDatabase->addCard()`, use some sort of generic callback, or let the card database fetch cards form the engine at the end of the parse step

**Comment by Daenyth** [comment]
I'd rather have it accept bytes instead of a file path; I can imagine shipping it over the network via protobuf or something instead, so bytes is more generic. You can always read the file anyway

**Comment by ZeldaZach** [comment]
@Vafthrudnir If you'd like to edit the top level comment and put implementation ideas below, feel free to

**Comment by tooomm** [comment]
We still don't have multiple/other parser engines yet. Do we want to keep this open to collect requests/requirements?
@ctrlaltca's post contains some useful general information for additional parsers.
