### ISSUE TITLE
Arrow keys can't be assigned to deck editor keyboard shortcuts

### ISSUE THREAD

**Issue by MisterMomotaro** [Cockatrice/Cockatrice#3206]
<b>System Information:</b>
   
Client Version: 2.5.1 (2018-04-16)
Client Operating System: OS X 10.13
Build Architecture: 64-bit
Qt Version: 5.5.1
QLayout: Attempting to add QLayout "" to ShortcutsTab "shortcutsTab", which already has a layout
Card Database load status:  0
   
________________________________________________________________________________________

Arrow keys can't be assigned to deck editor or main window keyboard shortcuts.  Says 'Invalid key'.  Cmd-Left (Ctrl-Left), Alt-Left, and Meta-Left work fine, however.

**Comment by skwerlman** [comment]
This is intentional. Arrow keys are used for navigation in the deck editor, and can't be rebound because of this.
See #2937 and #3116 for more info.
