### ISSUE TITLE
Cockatriec wont let me go online and not update the game

### ISSUE THREAD

**Issue by Dervanon** [Cockatrice/Cockatrice#3210]
<b>System Information:</b>
   
Theme changed: "Default"
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
main(): starting main program
main(): MainWindow constructor finished
CardDatabase::loadCardDatabases start
main(): ui.show() finished
QWindowsWindow::setGeometry: Unable to set geometry 1920x1021+8+31 on QWidgetWindow/'MainWindowClassWindow'. Resulting geometry:  1920x1017+0+23 (frame: 8, 31, 8, 8, custom margin: 0, 0, 0, 0, minimum size: 1103x1021, maximum size: 16777215x16777215).
cache fail for "_trice_card_back_225537"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Chris/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 18350 Sets= 224
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Chris/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 18743 Sets= 224
CardDatabase::loadCardDatabases success
cache fail for "_trice_card_back_225537"

   

My OS is Windows 10 , Cockatriece version dab7316 (19-04-2018)
________________________________________________________________________________________

   
When i try to join the server i get the following message:
"Your client seems to be missing features this server requires for connection.
Missing features:
- forgot_password"

When i go to -> Help -> Update Cockatriece the game freezes in less than a second and doesnt react anymore. Please help :(

**Comment by Daenyth** [comment]
There's no way your cockatrice version is from yesterday and you get that error - forgot password was added months ago. Double check that you are running the version you expect

**Comment by Vafthrudnir** [comment]
Your version seems to be too old for automatic update, please try download a new version from the website manually.
