### ISSUE TITLE
Aggiornamento non riuscito a Dominaria

### ISSUE THREAD

**Issue by Gibidinp** [Cockatrice/Cockatrice#3218]
<b>System Information:</b>
   

   
________________________________________________________________________________________

**Comment by Gibidinp** [comment]
Ho l'ultima versione di Cockatrice, ho aggiornato l'Oracle (e Dominaria è presente nell'elenco di carte importato), ma nulla funziona. Ho anche disistallato e reistallato, ma ancora niente.
Nemmeno con l'importazione automatica degli spoiler funziona.
Cosa devo fare?

**Comment by ctrlaltca** [comment]
1. This is an english-only bugtracker
2. Please be more precise than "nothing works". There's no way we can help with such a generic question.
---
1. In questo butracker si parla solo inglese
2. Devi essere più preciso di "nulla funziona". Non possiamo aiutarti se non ci fornisci informazioni sul problema.

**Comment by Gibidinp** [comment]
(Sorry for my english)
I wrote all in a comment

Il mer 2 mag 2018, 15:30 ctrlaltca <notifications@github.com> ha scritto:

**Comment by ctrlaltca** [comment]
@Gibidinp in your comment you only wrote "nothing works", we can't help if you don't state your problem clearly.

---
Nel commento hai scritto solo che "nulla funziona", non possiamo aiutarci se prima non ci spieghi esattamente cosa non funziona.

**Comment by Gibidinp** [comment]
(sorry for my english)
I have the last version of Cockatrice.
I uploaded Oracle and in the list there is also Dominaria, but when I run
Cockatrice Dominaria isn't in.
I also tryed to download the spoilers, but also this doesn't run.

2018-05-02 16:49 GMT+02:00 ctrlaltca <notifications@github.com>:

**Comment by ctrlaltca** [comment]
in the "database delle carte -> organizza set" menu, do you see the dominaria set? is it enabled (checked)?

![schermata 2018-05-02 alle 22 13 26](https://user-images.githubusercontent.com/1631111/39546884-23e1b570-4e56-11e8-87d5-61c892f8f10d.png)

**Comment by Gibidinp** [comment]
Oh, It was only this, wow, thx, now It runs

Il mer 2 mag 2018, 22:14 ctrlaltca <notifications@github.com> ha scritto:
