### ISSUE TITLE
Bug phantom cards

### ISSUE THREAD

**Issue by JineteDV** [Cockatrice/Cockatrice#3221]
Version 2.5.1 Already closed the client so lost the debug log.
__________________________________________________________________________________________
I caused this by trying to move the stack of islands around. I couldn't interact with the phantom islands and I could otherwise put cards in that spot, but the image was still under the phantom islands. Disconnecting and reconnecting fixed it.

![screen shot 2018-05-03 at 9 57 04 am](https://user-images.githubusercontent.com/6514656/39587450-85cf9cea-4ec7-11e8-9503-5420bf8865d3.png)

**Comment by tooomm** [comment]
Can you still reproduce this in recent versions like 2.7.0?

**Comment by ZeldaZach** [comment]
This user is no longer active, so no way to address this further. NoFix.
