### ISSUE TITLE
Suggestion: Change the ctrl+m shortcut default

### ISSUE THREAD

**Issue by JineteDV** [Cockatrice/Cockatrice#3222]
No other 2 key shortcut can destroy a game state like an accidental mulligan. Generally I'm against getting in the way of people and stupid, but I also feel like changing the mulligan shortcut to ctrl+shift+m or ctrl+alt+m is a simple precaution that'll help against the most detrimental misclick. 

Most players won't ever change their shortcuts or even know where they are, or that there are even multiple tabs in their settings.

**Comment by Daenyth** [comment]
Reasonable. We should expect to get bug reports about it not working
anymore, but seems fine

**Comment by ZeldaZach** [comment]
I personally changed it to `CTRL+SHIFT+M` and I feel this would be an appropriate default if we were to change it

**Comment by ancestral** [comment]
This is a shortcut I use quite often. I would be sad if it got more difficult to press.

**Comment by tooomm** [comment]
You can change it in setting/shortcuts anyway @ancestral 
The idea here is to make it less likely somebody mulligans on error, because you can't "repair" that.

**Comment by tooomm** [comment]
Idea: With the new London mulligan rule which draws the starting hand size again, there could be a check if current hand size /= starting hand size and prevent ctrl+m from working in that szenario at least or requests an additional confirmation.
