### ISSUE TITLE
"Forgot password" window makes all connect dialog close when you hit cancel

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#3224]
<b>System Information:</b>
  

Client Version: 2.5.1 (2018-04-16)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.9.4

  
__________________________________________________________________________________________

  

  

There is a little bug with the `Forgot password` window within the `Connect...` dialog.
When you hit "Cancel" or "X" you expect the forgot pw window you interacted with to close, but all `Connect` dialog gets closed instead.

**Comment by ZeldaZach** [comment]
This seems to be a wrong parent situation with the dialogs. Very simple fix.

**Comment by tooomm** [comment]
https://github.com/Cockatrice/Cockatrice/pull/2458 probably introduced this while trying to fix another issue (https://github.com/Cockatrice/Cockatrice/issues/2445).
