### ISSUE TITLE
Building Servatrice only, causes dependency on Qt5LinguistTools

### ISSUE THREAD

**Issue by seanbruno** [Cockatrice/Cockatrice#3225]
https://github.com/Cockatrice/Cockatrice/blob/4e10ce7473b925b24bce81d53c63cd5ad4644ce5/CMakeLists.txt#L146

I'm not a cmake expert, so I'm not clear on how to fix this issue.  However, if one *only* builds servatrice, then we don't need to check/build/install Qt5LinguistTools AFAIK.

I found this while modding the FreeBSD Port version to install dependencies based on user options of "Cockatrice + Oracle" or "Servatrice".

**Comment by ZeldaZach** [comment]
From what I recall, the Linguist tools is apart of the system used to build the languages packs. It's not really apart of any of the packages, but I guess we can call it apart of the stuff for C+O. Maybe @ctrlaltca can chime in

**Comment by ctrlaltca** [comment]
What is the problem exactly? That package is not marked as mandatory, so cmake should complete anyway. Do you receive an error?

**Comment by seanbruno** [comment]
There is no build error, just a CMake Warning that there is no LinguistTools installed when cmake invokes FIND_PACKAGE().  I noted this and scratched my head for a while when I was porting this to FreeBSD, thinking that servatrice required it.

```
-- Project version: 2.5.1-custom(unknown)
-- Friendly project version: 2.5.1-custom(unknown) (unknown)
-- Project version filename: Cockatrice-2.5.1-custom(unknown)
-- UPDATE TRANSLATIONS: OFF
-- Found Qt 5.9.4
CMake Warning at CMakeLists.txt:146 (FIND_PACKAGE):
  By not providing "FindQt5LinguistTools.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "Qt5LinguistTools", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5LinguistTools"
  with any of the following names:

    Qt5LinguistToolsConfig.cmake
    qt5linguisttools-config.cmake

  Add the installation prefix of "Qt5LinguistTools" to CMAKE_PREFIX_PATH or
  set "Qt5LinguistTools_DIR" to a directory containing one of the above
  files.  If "Qt5LinguistTools" provides a separate development package or
  SDK, be sure it has been installed.


CMake Warning at CMakeLists.txt:154 (MESSAGE):
  Qt's lrelease not found.
```

**Comment by ctrlaltca** [comment]
I see, there's no blocking error but the cmake warning is somewhat confusing. We'll rework the CMaklists.txt script to avoid triggering such warnings when the missing packages are not needed.

**Comment by seanbruno** [comment]
Awesome. Thanks!
