### ISSUE TITLE
Can't remove counters by shortcut

### ISSUE THREAD

**Issue by RodrigoPG2209** [Cockatrice/Cockatrice#3226]
<b>System Information:</b>
Client Version: 2.5.1 (2018-04-16)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.9.4
Trying to load picture (set:  "UST"  card:  "Plains" )
QPainter::end: Painter ended with 2 saved states
Picture found on disk (set:  "UST"  file:  "Plains" )
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
Server_AbstractUserInterface::playerRemovedFromGame(): gameId = 1
Server_CardZone destructor: "deck"
Server_CardZone destructor: "grave"
Server_CardZone destructor: "hand"
Server_CardZone destructor: "rfg"
Server_CardZone destructor: "sb"
Server_CardZone destructor: "stack"
Server_CardZone destructor: "table"
Server_CardZone destructor: "deck"
Server_CardZone destructor: "grave"
Server_CardZone destructor: "hand"
Server_CardZone destructor: "rfg"
Server_CardZone destructor: "sb"
Server_CardZone destructor: "stack"
Server_CardZone destructor: "table"
Trying to load picture (set:  "M15"  card:  "Chord of Calling" )
Picture found on disk (set:  "M15"  file:  "Chord of Calling" )
Trying to load picture (set:  "DDU"  card:  "Elvish Archdruid" )
Picture found on disk (set:  "DDU"  file:  "Elvish Archdruid" )
Trying to load picture (set:  "DDU"  card:  "Ezuri, Renegade Leader" )
Picture found on disk (set:  "DDU"  file:  "Ezuri, Renegade Leader" )
Trying to load picture (set:  "DPA"  card:  "Elvish Champion" )
Picture found on disk (set:  "DPA"  file:  "Elvish Champion" )
Trying to load picture (set:  "UST"  card:  "Forest" )
Picture found on disk (set:  "UST"  file:  "Forest" )
Trying to load picture (set:  "THS"  card:  "Nykthos, Shrine to Nyx" )
Picture found on disk (set:  "THS"  file:  "Nykthos, Shrine to Nyx" )
Trying to load picture (set:  "A25"  card:  "Nettle Sentinel" )
Picture found on disk (set:  "A25"  file:  "Nettle Sentinel" )
Trying to load picture (set:  "DD3_EVG"  card:  "Wren's Run Vanquisher" )
Picture found on disk (set:  "DD3_EVG"  file:  "Wren's Run Vanquisher" )
Trying to load picture (set:  "MM2"  card:  "Wilt-Leaf Liege" )
Picture found on disk (set:  "MM2"  file:  "Wilt-Leaf Liege" )
Trying to load picture (set:  "DDU"  card:  "Talara's Battalion" )
Picture found on disk (set:  "DDU"  file:  "Talara's Battalion" )
Trying to load picture (set:  "MM3"  card:  "Craterhoof Behemoth" )
Picture found on disk (set:  "MM3"  file:  "Craterhoof Behemoth" )
Trying to load picture (set:  "PCA"  card:  "Beast Within" )
Picture found on disk (set:  "PCA"  file:  "Beast Within" )
Trying to load picture (set:  "M14"  card:  "Mutavault" )
Picture found on disk (set:  "M14"  file:  "Mutavault" )
Trying to load picture (set:  "DTK"  card:  "Collected Company" )
Picture found on disk (set:  "DTK"  file:  "Collected Company" )
Trying to load picture (set:  "CNS"  card:  "Wrap in Vigor" )
Picture found on disk (set:  "CNS"  file:  "Wrap in Vigor" )
Trying to load picture (set:  "CMA"  card:  "Reclamation Sage" )
Picture found on disk (set:  "CMA"  file:  "Reclamation Sage" )
Trying to load picture (set:  "SHM"  card:  "Mercy Killing" )
Picture found on disk (set:  "SHM"  file:  "Mercy Killing" )
Trying to load picture (set:  "EMA"  card:  "Heritage Druid" )
Picture found on disk (set:  "EMA"  file:  "Heritage Druid" )
Trying to load picture (set:  "DOM"  card:  "Steel Leaf Champion" )
Picture found on disk (set:  "DOM"  file:  "Steel Leaf Champion" )
Trying to load picture (set:  "DDU"  card:  "Dwynen's Elite" )
Picture found on disk (set:  "DDU"  file:  "Dwynen's Elite" )
Trying to load picture (set:  "DOM"  card:  "Llanowar Elves" )
Picture found on disk (set:  "DOM"  file:  "Llanowar Elves" )
Trying to load picture (set:  "A25"  card:  "Nettle Sentinel" )
Picture found on disk (set:  "A25"  file:  "Nettle Sentinel" )
Trying to load picture (set:  "DDU"  card:  "Elvish Archdruid" )
Picture found on disk (set:  "DDU"  file:  "Elvish Archdruid" )
Trying to load picture (set:  "DPA"  card:  "Elvish Champion" )
Picture found on disk (set:  "DPA"  file:  "Elvish Champion" )
Trying to load picture (set:  "DDU"  card:  "Ezuri, Renegade Leader" )
Picture found on disk (set:  "DDU"  file:  "Ezuri, Renegade Leader" )
Trying to load picture (set:  "M15"  card:  "Chord of Calling" )
Picture found on disk (set:  "M15"  file:  "Chord of Calling" )
Trying to load picture (set:  "DD3_EVG"  card:  "Wren's Run Vanquisher" )
Player destructor: "Player 1"
GameScene::removePlayer name= "Player 1"
CardZone destructor:  "deck"
Picture found on disk (set:  "DD3_EVG"  file:  "Wren's Run Vanquisher" )
Trying to load picture (set:  "DDU"  card:  "Talara's Battalion" )
CardZone destructor:  "grave"
CardZone destructor:  "hand"
CardZone destructor:  "rfg"
CardZone destructor:  "sb"
CardZone destructor:  "stack"
CardZone destructor:  "table"
Player destructor: "Player 2"
GameScene::removePlayer name= "Player 2"
CardZone destructor:  "deck"
CardZone destructor:  "grave"
CardZone destructor:  "hand"
CardZone destructor:  "rfg"
CardZone destructor:  "sb"
CardZone destructor:  "stack"
CardZone destructor:  "table"
Picture found on disk (set:  "DDU"  file:  "Talara's Battalion" )
Trying to load picture (set:  "MM3"  card:  "Craterhoof Behemoth" )
Server::removeClient: name= "Player 1"
closed session id: 0
Server::removeClient: removed 0x2738d385a80 ; 1 clients;  1 users left
Server_AbstractUserInterface::playerRemovedFromGame(): gameId = 1
Server::removeClient: name= "Player 2"
closed session id: 0
Server::removeClient: removed 0x2738d387c40 ; 0 clients;  0 users left
Server_Room destructor
Server_Game destructor: gameId= 1
Picture found on disk (set:  "MM3"  file:  "Craterhoof Behemoth" )
Trying to load picture (set:  "THS"  card:  "Nykthos, Shrine to Nyx" )
Picture found on disk (set:  "THS"  file:  "Nykthos, Shrine to Nyx" )
Trying to load picture (set:  "UST"  card:  "Forest" )
Picture found on disk (set:  "UST"  file:  "Forest" )
Trying to load picture (set:  "M14"  card:  "Mutavault" )
Picture found on disk (set:  "M14"  file:  "Mutavault" )
Trying to load picture (set:  "PCA"  card:  "Beast Within" )
Picture found on disk (set:  "PCA"  file:  "Beast Within" )
Trying to load picture (set:  "MM2"  card:  "Wilt-Leaf Liege" )
Picture found on disk (set:  "MM2"  file:  "Wilt-Leaf Liege" )
Trying to load picture (set:  "CNS"  card:  "Wrap in Vigor" )
Picture found on disk (set:  "CNS"  file:  "Wrap in Vigor" )
Trying to load picture (set:  "A25"  card:  "Zombify" )
Picture found on disk (set:  "A25"  file:  "Zombify" )
Trying to load picture (set:  "ARC"  card:  "Makeshift Mannequin" )
Picture found on disk (set:  "ARC"  file:  "Makeshift Mannequin" )
Trying to load picture (set:  "IMA"  card:  "Elesh Norn, Grand Cenobite" )
Picture found on disk (set:  "IMA"  file:  "Elesh Norn, Grand Cenobite" )
Trying to load picture (set:  "MPS"  card:  "Platinum Angel" )
Picture found on disk (set:  "MPS"  file:  "Platinum Angel" )
Trying to load picture (set:  "ZEN"  card:  "Iona, Shield of Emeria" )
Picture found on disk (set:  "ZEN"  file:  "Iona, Shield of Emeria" )
Trying to load picture (set:  "ARB"  card:  "Nemesis of Reason" )
Picture found on disk (set:  "ARB"  file:  "Nemesis of Reason" )
Trying to load picture (set:  "C17"  card:  "Steel Hellkite" )
Picture found on disk (set:  "C17"  file:  "Steel Hellkite" )
Trying to load picture (set:  "RTR"  card:  "Archon of the Triumvirate" )
Picture found on disk (set:  "RTR"  file:  "Archon of the Triumvirate" )
Trying to load picture (set:  "MPS"  card:  "Wurmcoil Engine" )
cache fail for "_trice_card_back_226451"
Picture found on disk (set:  "MPS"  file:  "Wurmcoil Engine" )
Trying to load picture (set:  "SHM"  card:  "Godhead of Awe" )
Picture found on disk (set:  "SHM"  file:  "Godhead of Awe" )
Trying to load picture (set:  "DD3_GVL"  card:  "Liliana Vess" )
Picture found on disk (set:  "DD3_GVL"  file:  "Liliana Vess" )
Trying to load picture (set:  "FUT"  card:  "Bonded Fetch" )
Picture found on disk (set:  "FUT"  file:  "Bonded Fetch" )
Trying to load picture (set:  "E02"  card:  "Path to Exile" )
Picture found on disk (set:  "E02"  file:  "Path to Exile" )
Trying to load picture (set:  "RTR"  card:  "Supreme Verdict" )
Picture found on disk (set:  "RTR"  file:  "Supreme Verdict" )
Trying to load picture (set:  "KTK"  card:  "Flooded Strand" )
libpng warning: iCCP: known incorrect sRGB profile
Picture found on disk (set:  "KTK"  file:  "Flooded Strand" )
Trying to load picture (set:  "ZEN"  card:  "Marsh Flats" )
Picture found on disk (set:  "ZEN"  file:  "Marsh Flats" )
Trying to load picture (set:  "RTR"  card:  "Hallowed Fountain" )
Picture found on disk (set:  "RTR"  file:  "Hallowed Fountain" )
Trying to load picture (set:  "XLN"  card:  "Drowned Catacomb" )
Picture found on disk (set:  "XLN"  file:  "Drowned Catacomb" )
Trying to load picture (set:  "UST"  card:  "Swamp" )
Picture found on disk (set:  "UST"  file:  "Swamp" )
Trying to load picture (set:  "UST"  card:  "Island" )
Picture found on disk (set:  "UST"  file:  "Island" )
Trying to load picture (set:  "C17"  card:  "Lightning Greaves" )
Picture found on disk (set:  "C17"  file:  "Lightning Greaves" )
Trying to load picture (set:  "RTR"  card:  "Pithing Needle" )
Picture found on disk (set:  "RTR"  file:  "Pithing Needle" )
Trying to load picture (set:  "RIX"  card:  "Negate" )
Picture found on disk (set:  "RIX"  file:  "Negate" )
Trying to load picture (set:  "RTR"  card:  "Detention Sphere" )
Picture found on disk (set:  "RTR"  file:  "Detention Sphere" )
Trying to load picture (set:  "MM3"  card:  "Inquisition of Kozilek" )
Picture found on disk (set:  "MM3"  file:  "Inquisition of Kozilek" )
Trying to load picture (set:  "IMA"  card:  "Duress" )
Picture found on disk (set:  "IMA"  file:  "Duress" )
Trying to load picture (set:  "BNG"  card:  "Revoke Existence" )
Picture found on disk (set:  "BNG"  file:  "Revoke Existence" )

Windows 10 Pro 64bits
Intel Core i7 4790
16Gb RAM
__________________________________________________________________________________________

I can't remove counters on cards at the battlefield by using the shortcuts, and I only can put counters after exit the focus of the cursor in the chat;

**Comment by Vafthrudnir** [comment]
This is probably the same issue as #3161 , and also relates to #3049.
