### ISSUE TITLE
[request] add a simple text-to-speech announcer for platforms that support one

### ISSUE THREAD

**Issue by alexchandel** [Cockatrice/Cockatrice#3228]
In addition to the basic sound effects, it would be neat to have a simple announcer that spoke certain game actions. Packaging sound effects would be a pain, especially for the myriad cards, so this could be accomplished with text-to-speech for now for major game actions, & limited to platforms that have OS support for TTS for simplicity.

For example, it could read, "Top untap," "Tap tropical island," "play tundra," "tap tundra," "play Jace the mind Sculpter," "bottom untap," "tap two island," "play brainstorm," "discard brainstorm," "lost 2 life"… probably coalescing counter changes over ≈1 second & dropping announcements if more than ≈5 queue.

**Comment by ZeldaZach** [comment]
Sounds simple, but in reality this is a really difficult thing to accomplish...

**Comment by ancestral** [comment]
Isn’t this usually done by on-screen readers and accessibility support in most operating systems?

**Comment by ZeldaZach** [comment]
I _think_ so but I've never dealt with something like this before, maybe @ctrlaltca has some insight?

**Comment by ctrlaltca** [comment]
Yep, Qt supports text to speech on almost all platforms (with some library dependency on linux).
See https://doc.qt.io/qt-5/qtspeech-index.html , there's also a simple helloworld.

**Comment by ancestral** [comment]
I think you should really let the operating system take control of this. Services like VoiceOver and Narrator are going to do a much better job with this. The log is in text mode, so it shouldn’t be difficult for the system do this.

An alternative is wire it into the speak text in Speech in the various major OS’s. For example, macOS has Speech menu commands, and I’m sure Windows does too.

**Comment by alexchandel** [comment]
macOS's Speech service is available via `NSSpeechSynthesizer`. Using it is trivial:

```swift
import Foundation
import AppKit
let synth = NSSpeechSynthesizer()
let didStart = synth.startSpeaking("Hello, world!")

// block in 0.1s increments until finished speaking, to avoid exiting early.
// Don't do this in a real app!!!
if didStart {
	let loop = RunLoop.current
	let mode = loop.currentMode ?? RunLoopMode.defaultRunLoopMode
	while loop.run(mode: mode, before: Date(timeIntervalSinceNow: 0.1)) &&
		synth.isSpeaking { }
} else {
	print("Failed to start speaking.")
}
```

Qt Speech's documentation indicates that `<QTextToSpeech>` uses the OS's APIs, so I imagine it does something similar under the hood. Using it appears to be as simple as:
```C++
/* in class declaration of MainWindow/some QMainWindow/whatever */
QTextToSpeech *m_speech;

/* in constructor: */
m_speech = new QTextToSpeech(this);

/* in method:  */
// m_speech->setRate(1.25); // some say macOS's default rate is too slow, idk.
m_speech->say(QString("Hello, world!"));
```

So the actual speech synthesis is simple to code.

Presumably, you'd maintain a circular buffer of the last ~10 or so speakable game events, and respond to the `stateChanged(QTextToSpeech::State state)` signals from `m_speech` by popping the next item and speaking it until the buffer was empty.

On what constitutes "speakable game events" and how they're formed, I'd limit it to "(Top|Bottom) untap", "tap {name}", "play {name}", "discard {name}", "(Top|Bottom) conceded", and maybe a few other simple ones, where "{name}" is just the card name stripped of commas. Let the speech engine figure out how to pronounce (or butcher) the name.

For example, if the top player plays "Jace, the Mind Sculptor," it should result in `QString("play Jace the Mind Sculptor")` pushed to the circular buffer, and spoken immediately if `m_speech->state() == QTextToSpeech::Ready` (or alternatively if a `stateChanged(QTextToSpeech::Ready)` occurred previously when the buffer was empty, and was cached).

**Comment by ZeldaZach** [comment]
I like the idea, @alexchandel! If you'd like to possibly work on a PR for this feature, your plan seems reasonable.

**Comment by ancestral** [comment]
Does anyone know blind players on Cockatrice? This may be utilized more by people with visual impairments.

**Comment by Daenyth** [comment]
I'm skeptical that cockatrice is even 10% usable for blind users. Vision impaired I know we have at least one and it's not good for them.

**Comment by alexchandel** [comment]
Is there any page about or diagram of Cockatrice's structure? Where are the classes for the game tab and game state, and the logic that prints game information in the tab's chat box?

**Comment by tooomm** [comment]
@alexchandel That is something you should open a new issue for and not use a unrelated ticket for your question, or at best come and chat with us in our Gitter channel. You find more info in our README on the main repo page.

**Comment by Daenyth** [comment]
@alexchandel `tab_game` and iirc `messagelogwidget` are two of the points of interest. I forget the class that holds game state but if you start from tab_game you should get there

**Comment by ZeldaZach** [comment]
There are programs for computers that do this already, and Qt should expose the string set for easy usage. We have done a pretty good job at maintaining a11y imo. If there are deficiencies, please open separate tickets for each one so we can address them.
