### ISSUE TITLE
Reminder: Transition to travis.com, use travis github app + checks api

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#3233]
https://blog.github.com/2018-05-07-introducing-checks-api/
https://blog.travis-ci.com/2018-05-07-announcing-support-for-github-checks-api-on-travis-ci-com
https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps?utm_source=Broadcast&utm_campaign=2may_release

https://docs.travis-ci.com/user/open-source-on-travis-ci-com/#Existing-Open-Source-Repositories-on-travis-ci.org
https://docs.travis-ci.com/user/migrate/open-source-repository-migration#migrating-a-repository

https://developer.github.com/changes/2018-05-07-new-checks-api-public-beta/
https://developer.github.com/v3/checks/

**Update:
https://docs.travis-ci.com/user/migrate/open-source-on-travis-ci-com/#existing-open-source-repositories-on-travis-ciorg**

**Comment by ctrlaltca** [comment]
Tried to have a look, it seems that open source projects currently active on the travis-ci.org infrastrucure can't be migrated right now.

**Comment by tooomm** [comment]
From https://docs.travis-ci.com/user/open-source-on-travis-ci-com/#Existing-Open-Source-Repositories-on-travis-ci.org:

>However, open source repositories will be migrated to travis-ci.com gradually, beginning at the end of Q2 2018. You will receive an email when the migration for a repository is complete. **This is an opt-in process: to have a repository migrated over, it must first be activated on travis-ci.com.**

So maybe @Daenyth can sign us up there?

**Comment by ZeldaZach** [comment]
This never seemed to come to fruition. Not a big deal.

**Comment by tooomm** [comment]
You should really transfer the Projekt over to travis.com as they’ll shut down .org

By now it should be a click of a button only. I saw it the other week again in the interface but you have to do it.
Can point you on the weekend. @ZeldaZach

**Comment by tooomm** [comment]
As seen yesterday:
![travis](https://user-images.githubusercontent.com/9874850/97599909-cb6e5c00-1a08-11eb-920e-40b1296dc92b.png)

From the [linked page](https://docs.travis-ci.com/user/migrate/open-source-repository-migration#frequently-asked-questions), very first information:

>**Q.** When will the migration from travis-ci.org to travis-ci.com be completed? #
>
>**A.** In an effort to ensure that all of our users - whether you build open-source, public or private repositories - receive regular feature updates, security patches and UX/UI enhancements, we are announcing that **travis-ci.org will be officially closed down completely no later than December 31st, 2020**, allowing us to focus all our efforts on bringing new features and fixes to travis-ci.com and all of our awesome users like yourself on the travis-ci.com domain.

**Comment by ZeldaZach** [comment]
Since this is now an end of life ticket, we'll need to handle this when it comes about.
