### ISSUE TITLE
Reminder: Use several templates for e.g. issues

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#3234]
https://blog.github.com/2018-05-02-issue-template-improvements/

https://help.github.com/articles/about-issue-and-pull-request-templates/
https://help.github.com/articles/creating-issue-templates-for-your-repository/

<br>

Example from [Templarian/MaterialDesign](https://github.com/Templarian/MaterialDesign/issues/new/choose):
![example](https://user-images.githubusercontent.com/9874850/40409439-3ac024d2-5e6b-11e8-8473-7954cce44315.png)

---

GitHub allows to automatically tag issues as well, see:
https://github.com/sindresorhus/refined-github/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
https://github.com/sindresorhus/refined-github/blob/master/.github/ISSUE_TEMPLATE/feature_request.md

Have a hint on how to auto-close issues with a PR:
https://github.com/sindresorhus/refined-github/blob/master/.github/pull_request_template.md

**Comment by ZeldaZach** [comment]
Done already
