### ISSUE TITLE
Mac app missing a bundle version number

### ISSUE THREAD

**Issue by ancestral** [Cockatrice/Cockatrice#3235]
The Mac app bundle is missing a version number, so it’s hard to tell which version is installed without opening the app. When you choose “Get Info” in the Finder, it just says “Cockatrice”.

The `GetInfo` string listed in Info.plist has “Cockatrice”, and nothing is written for `CFBundleShortVersionString` or `CFBundleVersion`. (I’m guessing there must be something missing during the packaging process.)

Thanks.

**Comment by tooomm** [comment]
> The Mac app bundle is missing a version number, so it’s hard to tell which version is installed without opening the app. When you choose “Get Info” in the Finder, it just says “Cockatrice”.

Just to make sure:
Are you speaking about the `Cockatrice-Decked_Out_Revision_1-2.5.1.dmg` file we provide for our releases, e.g. [here](https://github.com/Cockatrice/Cockatrice/releases/tag/2018-04-16-Release-2.5.1) or on our website?

**Comment by ancestral** [comment]
>Just to make sure:
Are you speaking about the Cockatrice-Decked_Out_Revision_1-2.5.1.dmg file we provide for our releases, e.g. here or on our website?

Yes.

>I assume there is also no version shown for Oracle, too?

Yes, and Servatrice also.

Also, the app file names are not capitalized, as is convention in macOS.

**Comment by tooomm** [comment]
>Also, the app file names are not capitalized, as is convention in macOS.

Related https://github.com/Cockatrice/Cockatrice/issues/2726
