### ISSUE TITLE
Parser aborts without error when adding set files

### ISSUE THREAD

**Issue by ancestral** [Cockatrice/Cockatrice#3236]
<b>System Information:</b>
  
Client Version: 2.5.1 (2018-04-16)
Client Operating System: OS X 10.13
Build Architecture: 64-bit
Qt Version: 5.5.1
Theme changed: "Default"
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
main(): starting main program
Spoilers Disabled
main(): MainWindow constructor finished
CardDatabase::loadCardDatabases start
main(): ui.show() finished
[CardDatabase] loadCardDatabase(): Path = "/Users/user/Library/Application Support/Cockatrice/cards.xml" Status = 0 Cards = 18094 Sets= 221
[CardDatabase] loadCardDatabase(): Path = "/Users/user/Library/Application Support/Cockatrice/tokens.xml" Status = 0 Cards = 18479 Sets= 221
[CardDatabase] loadCardDatabase(): Path = "/Users/user/Library/Application Support/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 18479 Sets= 221
[CardDatabase] loadCardDatabase(): Path = "/Users/user/Library/Application Support/Cockatrice/Cockatrice/customsets/02.ExpandedKingdoms.xml" Status = 0 Cards = 18509 Sets= 222
[CardDatabase] loadCardDatabase(): Path = "/Users/user/Library/Application Support/Cockatrice/Cockatrice/customsets/03.DAD.xml" Status = 0 Cards = 18516 Sets= 223
[CardDatabase] loadCardDatabase(): Path = "/Users/user/Library/Application Support/Cockatrice/Cockatrice/customsets/Aenyr cockatrice final version.xml" Status = 0 Cards = 18760 Sets= 224
[CardDatabase] loadCardDatabase(): Path = "/Users/user/Library/Application Support/Cockatrice/Cockatrice/customsets/ANK_cards_v2.3.xml" Status = 0 Cards = 18988 Sets= 225
[CardDatabase] loadCardDatabase(): Path = "/Users/user/Library/Application Support/Cockatrice/Cockatrice/customsets/ANK_tokens_v2.3.xml" Status = 0 Cards = 18993 Sets= 225
[CardDatabase] loadCardDatabase(): Path = "/Users/user/Library/Application Support/Cockatrice/Cockatrice/customsets/CC18_0.7.3.xml" Status = 0 Cards = 19120 Sets= 226
[CardDatabase] loadCardDatabase(): Path = "/Users/user/Library/Application Support/Cockatrice/Cockatrice/customsets/CC18_Tokens_0.7.3.xml" Status = 0 Cards = 19122 Sets= 226
[CardDatabase] loadCardDatabase(): Path = "/Users/user/Library/Application Support/Cockatrice/Cockatrice/customsets/dms_cards_v2.50.xml" Status = 0 Cards = 19364 Sets= 227
[CardDatabase] loadCardDatabase(): Path = "/Users/user/Library/Application Support/Cockatrice/Cockatrice/customsets/Grimm 0.2.0.xml" Status = 0 Cards = 19412 Sets= 228
[CardDatabase] loadCardDatabase(): Path = "/Users/user/Library/Application Support/Cockatrice/Cockatrice/customsets/HLW.xml" Status = 0 Cards = 19655 Sets= 229
[CardDatabase] loadCardDatabase(): Path = "/Users/user/Library/Application Support/Cockatrice/Cockatrice/customsets/hollows of lordran tokens.xml" Status = 0 Cards = 19659 Sets= 229
[CardDatabase] loadCardDatabase(): Path = "/Users/user/Library/Application Support/Cockatrice/Cockatrice/customsets/Jannada.xml" Status = 0 Cards = 19888 Sets= 230
[CardDatabase] loadCardDatabase(): Path = "/Users/user/Library/Application Support/Cockatrice/Cockatrice/customsets/lorado.xml" Status = 0 Cards = 20127 Sets= 231
[CardDatabase] loadCardDatabase(): Path = "/Users/user/Library/Application Support/Cockatrice/Cockatrice/customsets/netropolis.xml" Status = 0 Cards = 20384 Sets= 232
[CardDatabase] loadCardDatabase(): Path = "/Users/user/Library/Application Support/Cockatrice/Cockatrice/customsets/tesla_v0.99.xml" Status = 0 Cards = 20640 Sets= 233
[CardDatabase] loadCardDatabase(): Path = "/Users/user/Library/Application Support/Cockatrice/Cockatrice/customsets/villains-v34.xml" Status = 0 Cards = 20907 Sets= 234
CardDatabase::loadCardDatabases success
  
__________________________________________________________________________________________

  
In 2.5.0, if you are importing a set file with an unknown element, Cockatrice ignores it, and moves on to the next element (hopefully as intended?) In 2.5.1, the parser fails on the unknown element, and aborts the rest of the import.

I would hope 2.5.1 would ignore the invalid elements if possible, as it did in 2.5.0. Seeing that the code just looks for specific elements to capture anyway (name, type, text, etc.) I can’t imagine a specific issue there. However, I guess if you are after a stricter importing, then it may be acceptable to skip the card and simply continue? But at the very least, displaying an error message indicating there actually was a problem would be very helpful. (I recently made a Cockatrice set file for folks to use, and I assumed it worked correctly as I saw a bunch of cards in the database. It was only after people told me they were missing cards did I even realize anything bad actually happened.)

**Comment by ZeldaZach** [comment]
The PR #3223 did the refactor. It was supposed to be a seam-less transition, but I seemed to have missed testing with files that have such tags. @ctrlaltca

**Comment by ctrlaltca** [comment]
He's running version 2.5.1 dated 2018-04-16, a few weeks before my PR #3223, so i'm quite sure that is not the cause. I'll try to bisect the bug using the user-provided file from https://github.com/Cockatrice/Cockatrice/issues/3227#issuecomment-387917702

**Comment by ctrlaltca** [comment]
Results with [03.DAD.xml.txt](https://github.com/Cockatrice/Cockatrice/files/1989945/03.DAD.xml.txt)
 * version 2018-03-02-Release-2.5.0: Status = 0 Cards = 86 Sets= 1
 * version 2018-04-16-Release-2.5.1: Status = 0 Cards = 86 Sets= 1

Do you have a file that works with 2.5.0 and is broken with 2.5.1?

**Comment by ancestral** [comment]
Well, 2.5.0 now seems to fail for me too. Perhaps I had an older version, or my working copy had unsaved commits.
