### ISSUE TITLE
Bug: other users tokens appear in your token list

### ISSUE THREAD

**Issue by anoda9** [Cockatrice/Cockatrice#324]
If your opponent (or a player in a game you're watching) creates a token, it gets permanently added to your token list.

**Comment by ZeldaZach** [comment]
Looking further into this, the term "permanently" is inaccurate as the `tokens.xml` file is not written to.

When an opponent/player makes a token that's not defined in your tokens file, it will be added to your temporary cache and will appear as a valid token option for you until you close your client.

I personally find this a nice feature, as it will allow you to work out extra tokens if necessary, which doesn't overwrite your tokens file. Therefore, this is fine as is.

**Comment by anoda9** [comment]
>Looking further into this, the term "permanently" is inaccurate as the tokens.xml file is not written to. 

This is incorrect. The tokens.xml file does get edited, and the changes persist between closing and reopening the client. 

> I personally find this a nice feature, as it will allow you to work out extra tokens if necessary

Ughhhh. Any other opinions on this? To me, this is one of the more annoying bugs in the program. I don't really know what you mean by "work out extra tokens". If a user wants a certain token, they will add it to their token list themselves. The client adding a bunch of junk tokens the user didn't ask for (and that then have to be removed later) does not seem helpful to me.

**Comment by ZeldaZach** [comment]
When I tested the file didn't seem to be overwritten. I did my tests on OS X, which could possibly react differently from Windows and Linux, but, for me, it seemed to be a temporary rewrite for the tokens to appear on the list and disappear when I restart the client.

**Comment by anoda9** [comment]
That's strange, I'm on OS X also (10.6.8), latest cockatrice version (a16f8e0), and the xml does get overwritten for me.

**Comment by ZeldaZach** [comment]
I understand your frustration and we'll look further into this. 

I believe my tokens file may be on read-only mode, which explains why the edits are only temporary.

**Comment by ctrlaltca** [comment]
Fixed in #1859
