### ISSUE TITLE
Compilation on Archlinux fails because of missing break statements

### ISSUE THREAD

**Issue by berserkingyadis** [Cockatrice/Cockatrice#3240]
## Problem
Compiling the newest Cockatrice fails under Archlinux. These are the cmake options I have used:

`-DCMAKE_BUILD_TYPE=Debug -DWITH_SERVER=1`

If I DONT set the Build Type to "Debug" cockatrice and servatrice compile just fine. Also, using
the Debug Build Type is working on Ubuntu 16.04 (GCC 5), it may have to do with the brand new GCC Archlinux is using (GCC 8)

This is the error: https://hastebin.com/ajahasacow.rb , somehow the switch statements without breaks are not liked anymore. ([-Werror=implicit-fallthrough=], warning treated as error)

## System Info
OS: Archlinux x64 Kernel: 4.16.8-1
Cockatrice: Newest
cmake: 3.11.1
GCC: 8.1.0
Qt: 5.10.1
Protobuf: 3.5.1
Zlib: 1.2.11

**Comment by berserkingyadis** [comment]
After ignoring that Warning (Error) with setting the flag `-Wno-error=implicit-fallthrough` in this line [HERE](https://github.com/Cockatrice/Cockatrice/blob/73fb9ee03e0b5d8f901da4b8f1f12a47ab47500c/CMakeLists.txt#L109) another Error from warning emerged:

https://hastebin.com/esigarajun.vbs

That error would be "resolved" by setting another flag: `-Wno-error=ignored-qualifiers`

Other 2 options would be to not treat warnings as errors anymore or fix the warnings.

**Comment by Daenyth** [comment]
We should add `-Wno-error=implicit-fallthrough` to the build; break-less switches are used intentionally for us. Not sure on the other one

**Comment by berserkingyadis** [comment]
Is there another opinion on this? I have to change the Cmakelists.txt very often when checking out other branches to ignore the issues :grimacing:

**Comment by ctrlaltca** [comment]
If you already know what needs to be modified on CMakeLists.txt, please open a PR so that we can evaluate it on other common configurations and merge it.

**Comment by berserkingyadis** [comment]
I wrote the (IMO) possible solutions above and was hoping we could reach a consensus in this issue.

Either:
1. Adding warning-error exceptions ```-Wno-error=implicit-fallthrough``` and ```-Wno-error=ignored-qualifiers```
2. Not treat warnings as errors
3. Fix the warnings.

Ill prepare a PR with Solution Nr. 1 but seeing that @Daenyth wasnt sure about the "ignored-qualifiers" warning, more input is welcomed.

**Comment by Daenyth** [comment]
I say we should `-Wno-error=implicit-fallthrough` and then fix the ignored-qualifiers lint.
