### ISSUE TITLE
Use more modern and uniform icons

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#3248]
This is more of a reminder for myself to look into this at one point.

In the meantime, feel free to gather ideas or suggestions here. (Or tackle it yourself of course.)

The new icons need to be:
- free
- have a appropriate license
- modern style
- clean look and feel

Put any resources or improvements you can think of regarding our used icons here, please.

(linking https://github.com/Cockatrice/Cockatrice/issues/3244)

**Comment by tooomm** [comment]
I'm not speaking about ingame pictures or "theme" stuff. That can users change on their own.
I'm speaking about all other areas in the client, e.g. the icons used in settings.

But sure, somebody should look into a new/better default theme at some point, too.
Like the phase icons or color scheme for the battlefield could easily see some polish.

**Comment by ZeldaZach** [comment]
Dupe #3256
