### ISSUE TITLE
Appveyor builds fail every few months

### ISSUE THREAD

**Issue by Vafthrudnir** [Cockatrice/Cockatrice#3252]
Since `vcredist` is included in the compiled Cockatrice package from a [fix path](https://github.com/Cockatrice/Cockatrice/blob/master/CMakeLists.txt#L211) which contains Visual Studio's current version number, appveyor builds will regularly fail with every VS update - which happens every few months nowadays. 

Furthermore, this could cause building issues for developers with Windows environment, since they might not have the same VS version as set in the `CMakeLists` file.

By adding the `vcredist` files to the repo these paths could be changed to them, solving this issue.

**Comment by Vafthrudnir** [comment]
This path got included in PR #3020, and since then had to be updated in PR #3151 and #3251.

**Comment by ctrlaltca** [comment]
By adding the vcredist files to the repo you would build cockatrice with a version of the c++ libraries and distribute the package with a different version.

**Comment by Vafthrudnir** [comment]
So if that's not a viable option, is there any good way to solve this issue?

**Comment by ctrlaltca** [comment]
In the past there was a way to determine the current folder where the vcredist package was installed.
Recently the m$ guys decided it was nice to move the vcredist around on different paths at almost every new release, so currently I'm not aware of a future-proof solution.

**Comment by tooomm** [comment]
>Would it be possible to set the Appveyor environment to only update versions when we want to?

There are previous images available just like with travis: https://www.appveyor.com/updates/
But since it's not a explicit version it'll update with every release as well I assume. :)

<br>

What about my globes idea from https://github.com/Cockatrice/Cockatrice/pull/3251#issuecomment-390394093?
>Is there support for `*` globes in the file path? If only the version number is increasing...
>
>I've no idea how recent changes looked like.
But I remember @ctrlaltca said they changed the pattern once.

**Comment by Vafthrudnir** [comment]
> https://github.com/cockatrice/Cockatrice/blob/master/CMakeLists.txt#L213
--> "C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/redist/MSVC/*/vc_redist.x86.exe"

Tried it in a few different ways, but none seemed to work :(
