### ISSUE TITLE
Include Brawl as a list of the default formats for games

### ISSUE THREAD

**Issue by ShrewMaster** [Cockatrice/Cockatrice#3254]
Now that Brawl has become a supported format by Wizards, it would be important for players to start playing and testing their Brawl decks on Cockatrice. Adding it as a default format in the "Game type" tab when creating games would make this easier for players to find and play games of Brawl.

**Comment by ZeldaZach** [comment]
This is a server operator option, not a Cockatrice develompental issue.

I recommend you reach out to the server operator(s) via the [Public Server List](https://github.com/Cockatrice/Cockatrice/wiki/Public-Servers) and ask them to include it
