### ISSUE TITLE
Share deck via deck storage

### ISSUE THREAD

**Issue by skwerlman** [Cockatrice/Cockatrice#3260]
Currently if you want to share a deck, you have to use a third party tool to either share the deck list or share the .cod. My idea is to allow direct sharing of decks saved using deck storage.

Sharing would work like this:

1. User 1 uploads their deck to deck storage
2. User 1 presses a 'share deck' button, and enters 'User 2' into the field
3. User 2 checks their deck storage tab, and can see user 1's deck

The shared deck would be user 1's real copy of the deck, so any changes user 1 makes would carry over, but user 2 wouldn't be allowed to make any changes to that copy of the deck.

Related: #400

**Comment by tooomm** [comment]
This sounds very interesting!

**Comment by Daenyth** [comment]
Dupe #2555

**Comment by skwerlman** [comment]
ah, i missed that one in my search. whoops
