### ISSUE TITLE
Can't create related tokens

### ISSUE THREAD

**Issue by skwerlman** [Cockatrice/Cockatrice#3262]
<b>System Information:</b>
  
Client Version: 2.5.2-custom(81803e2) (2018-05-25)
Client Operating System: Arch Linux
Build Architecture: 64-bit
Qt Version: 5.11.0
System Locale: en_US

  
__________________________________________________________________________________________

  

  

The "create related card" option does not appear for any card, although the tokens are in my card database.

**Comment by Daenyth** [comment]
> cockatrice to lose the card database and go into first-time setup mode when building a new commit

That's absolutely not intended

**Comment by skwerlman** [comment]
> Definitely a bug

I'll open a new issue for it once i figure out how to repro. its happened at least twice now, but i can't cause it intentionally...

**Comment by tooomm** [comment]
You know that there is no sub menu any longer and the option is presented on the first layer in the right click menu? It looks like this `Token: 2x 1/1 Soldier`

I'm curious because it works for me:
```
Client Version: 2.5.2-custom(a647dce) (2018-06-14)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.9.5
System Locale: de_DE
```
![token](https://user-images.githubusercontent.com/9874850/41441736-2f54052a-7034-11e8-939b-e3e390d221b0.png)

**Comment by skwerlman** [comment]
The option simply does not show up for me.

(as a note: my dark theme is not the issue, as i've tested without the theme just to make sure)

![2018-06-14-200248_1898x1028_scrot](https://user-images.githubusercontent.com/6954107/41443972-f5854fd2-700d-11e8-968f-94f5f0b8d010.png)
![2018-06-14-200402_1898x1028_scrot](https://user-images.githubusercontent.com/6954107/41444001-1cadc6ca-700e-11e8-8837-66a68fffa085.png)

**Comment by skwerlman** [comment]
This issue does not affect cards that transform.

Also, it seems there are other people experiencing this; I saw a message in the discord yesterday, and there's a post on the reddit about it

https://www.reddit.com/r/Cockatrice/comments/8rxp9b/token_creation_bug/

**Comment by tooomm** [comment]
Do you know the last working version for you?

**Comment by skwerlman** [comment]
the 2.5.2 release is known good; i don't remember what commit i was on prior to hitting this issue though.

the earliest known commit with this issue is 494dfc2

**Comment by tooomm** [comment]
Can anybody check if this is a linux only problem since it seems to work on winfor me?
On reddit several people confirmed the problem but no talks about version or os: https://www.reddit.com/r/Cockatrice/comments/8rxp9b/token_creation_bug/

What about mac?

**Comment by skwerlman** [comment]
it's definitely not linux only; everyone in my playgroup has the bug, and they're mostly windows users, along with a mac user

**Comment by Daenyth** [comment]
Can someone affected by this issue please attach your cards.xml and *all* customsets + spoiler files you have loaded? Also include the debug log output for the whole session

**Comment by ZeldaZach** [comment]
I'm running a default build of Cockatrice on Win10 and this is an issue. Will look into it

**Comment by ZeldaZach** [comment]
Default build on Ubuntu 18 does not have this issue. That's really bizzare!

**Comment by ZeldaZach** [comment]
Blamed it back to a7f4aace9c5704d97fce77ab5c2f37badb5ef77c. Worked with the build prior to that one, but failed with that one and going forward. 

This commit was the refactoring of the card parser. Probably missing something to load in tokens correctly. cc: @ctrlaltca

**Comment by ctrlaltca** [comment]
I made a few tests, but was unfortunately unable to reproduce the problem.

**Comment by ZeldaZach** [comment]
Did you try only on Mac? I had the issue on Linux and windows but didn’t get to test Mac

**Comment by ctrlaltca** [comment]
I tested on mac and windows, current master, clean install + run oracle

**Comment by ZeldaZach** [comment]
Ok, so once you do that close the trice program, and reopen it. It will now fail to show tokens
