### ISSUE TITLE
Spoiler XMLs prevent card preferred card art from downloading

### ISSUE THREAD

**Issue by skwerlman** [Cockatrice/Cockatrice#3263]
<b>System Information:</b>
  
Client Version: 2.5.2-custom(494dfc2) (2018-05-25)
Client Operating System: Arch Linux
Build Architecture: 64-bit
Qt Version: 5.11.0
System Locale: en_US
  
__________________________________________________________________________________________

  

  
When a spoiler XML is loaded, it prevents the preferred art for reprinted cards from downloading. Instead, the art from the spoiler file is always used.

**Comment by Daenyth** [comment]
ah this is really awkward, because the database only has one entry per card, so if the spoiler file declares a picUrl for the card, then that will become part of the card's single definition regardless of whether or not it's the one for that set (I think), and picUrl is the highest priority always

**Comment by skwerlman** [comment]
tested again today, this does not appear to be an issue in the current version
