### ISSUE TITLE
Sort by Creature Type

### ISSUE THREAD

**Issue by TemporalMadness** [Cockatrice/Cockatrice#3267]
<b>System Information:</b>
Client Version: 2.5.1 (2018-04-16)
Client Operating System: Windows 8.1 (6.3)
Build Architecture: 64-bit
Qt Version: 5.9.4

Can it be made so we can Sort by Creature Type in the Deck editor? Like if i am building a Tribal Edh Knight deck i would love to just type "knight and sort the card list by Creatures typed "knight"  Because scrolling Through all the creatures to find the Human knights, the Vampire, knights, the Goblin knights is Painstakingly long process

**Comment by tooomm** [comment]
Try the filter! ;)

![untitled](https://user-images.githubusercontent.com/9874850/40702931-eb5f7946-63e3-11e8-8f86-d215f268d4ec.png)

**Comment by TemporalMadness** [comment]
I do Not see type in the Filter i have used the filter dozens of times

**Comment by tooomm** [comment]
Did you try to scroll down in the list? It's the last entry in the alphabetical list.

**Comment by TemporalMadness** [comment]
Wait there is a Scroll bar???!? um ok I never saw that. that brings me 2
question

1)Can you make the box a lil bigger?
2) why do we need "Loyalty" if we can just do Type Walkers?

Also could we do This with Formats? without having to do set x-times

**Comment by tooomm** [comment]
>1)Can you make the box a lil bigger?

It's not ideal as is, I agree.
Can you open a new issue for that, please?

>2) why do we need "Loyalty" if we can just do Type Walkers?

Because one might just want to filter for Planeswalkers which come into play with 4 Loyalty counters for example. This filter is not for has loyalty yes or no.
