### ISSUE TITLE
Can't make tokens from the grave

### ISSUE THREAD

**Issue by JineteDV** [Cockatrice/Cockatrice#3271]
Version 2.5.1 (2018-04-16) I tried this on macOS and Windows. At some point the ability to right click on a token maker card in the graveyard and make a token from that menu was removed.

![ffffr](https://user-images.githubusercontent.com/6514656/40868832-54d7e316-65df-11e8-894c-6b69689b85a8.png)

**Comment by tooomm** [comment]
Only `Clone` was added yet, token creation is still tracked in https://github.com/Cockatrice/Cockatrice/issues/2702
