### ISSUE TITLE
Issue with playing with top card revealed and face down cards played from library

### ISSUE THREAD

**Issue by Xelsia** [Cockatrice/Cockatrice#3276]
A little bit of a tricky bug to explain, and I haven't tried to reproduce it sorry. 
When playing with the top card of your library revealed, then look at top X cards of your library and then place one of them onto the battlefield face down, Cockatrice will tell other players that whatever card was on top of the library is the one put face down, regardless of whether it was that card or not. When that card is turned face up later, it will have the same name and card art as the card Cockatrice displayed previously to the opponents, but with the correct P/T of what the creature should be

> [top card revealed due to Oracle of Mul Daya]
> [plays Mosswort Bridge from top of library with Oracle]
> [17:24:29] Opponent reveals Ancient Tomb from the top of their library.
> [17:24:29] Opponent puts Mosswort Bridge into play from the top of their library.
> [17:24:31] Opponent taps Mosswort Bridge.
> [17:24:34] Opponent is looking at the top 4 card(s) of their library.
> [17:24:37] Opponent puts Ancient Tomb into play from their library.
> [17:24:40] Opponent reveals Nissa, Vital Force from the top of their library.
> [17:24:40] Opponent puts a card from their library on bottom of their library.
> [17:24:40] Opponent puts a card from their library into their library 78 cards from the top.
> [17:24:40] Opponent puts a card from their library into their library 77 cards from the top.
> [17:24:41] Opponent stops looking at their library.
> [17:24:42] Opponent points from their Nissa, Vastwood Seer to themselves.
> [17:24:45] Opponent creates token: Nissa, Sage Animist.
> [17:24:45] Opponent attaches Nissa, Vastwood Seer to Opponent's Nissa, Sage Animist.
> [17:24:47] Opponent attaches Ancient Tomb to Opponent's Mosswort Bridge.
> 
> [Natural Order on top of library]
> 
> [17:34:05] ￼ Xelsia: In response to the mind's eye trigger
> [17:34:16] Xelsia plays Chaos Warp from their hand.
> [17:34:16] Xelsia points from their Chaos Warp to Opponent's Mosswort Bridge.
> [17:34:17] Xelsia taps Snow-Covered Mountain.
> [17:34:18] Xelsia taps Snow-Covered Mountain.
> [17:34:21] Opponent taps Cinder Glade.
> [17:34:22] Opponent taps Mosswort Bridge.
> [17:34:28] Opponent unattaches Ancient Tomb.
> [17:34:30] Opponent flips Ancient Tomb face-up.
> [17:34:30] Opponent sets PT of Ancient Tomb to 12/12.
> [17:34:32] Opponent plays Kozilek, Butcher of Truth from play.
> [the card in question is displaying Ancient Tomb for me until Opponent moves it to the stack]
> [17:34:33] Opponent points from their Kozilek, Butcher of Truth to themselves.
> [17:34:43] Opponent puts Kozilek, Butcher of Truth into play from the stack.
>

**Comment by Daenyth** [comment]
Definitely a bug. Can you attach the replay file from this game?

**Comment by Xelsia** [comment]
Hmm, it shows the right card on the replay. It's around turn 5-7
[replay_825470.zip](https://github.com/Cockatrice/Cockatrice/files/2088430/replay_825470.zip)

**Comment by Daenyth** [comment]
That's relatively good news. This is either going to be a bug in the client alone, or in the private information reveal to the controller. Should be fixable without forcing an upgrade on everyone

**Comment by ebbit1q** [comment]
this is annoying to reproduce because it requires two clients but it sounds like a real problem, this should get fixed.

**Comment by ebbit1q** [comment]
it's just a client side bug so it shouldn't be too hard, like 3 lines, just pinning it down'd be hard.

**Comment by ebbit1q** [comment]
dupe #1983
