### ISSUE TITLE
allow manipulation of bottom cards of library through actions

### ISSUE THREAD

**Issue by sbheinric** [Cockatrice/Cockatrice#3279]
This is a seldom needed operation, but I ran into a situation once where it was necessary to look at the bottom card of the library and move it without revealing it.  The only way to access the bottom card of the library is by "Put bottom card in graveyard."  

I would recommend changing or replacing that with an option to "View bottom card(s) of library" which would open the same window as "View top cards of library" which would give more general flexibility to do different operations.

**Comment by ZeldaZach** [comment]
You can hold alt to drag from the bottom, shift+alt to drag and facedown from the bottom

**Comment by sbheinric** [comment]
I just tested it and holding "alt" does not make a difference for me, it still takes the top card (Version 2.5.1 (2018-04-16)

Even if holding Alt does work, it's not listed in the UI, so players wouldn't know that it existed, and it wouldn't be as flexible or consistent with the mechanism for interacting with the top of the library, as a "View bottom cards of library" option would be

**Comment by Daenyth** [comment]
I'm pretty sure this exists but isn't well documented

**Comment by ZeldaZach** [comment]
I forget what the command is then... but it exists

**Comment by Daenyth** [comment]
related #1373 and #125

**Comment by sbheinric** [comment]
Ok, so Ctrl or Ctrl+Shift does work -- but since it's not in the right click menu, the feature might as well not exist, because nobody knows it's there, aside from you and me.

This is also a much jankier and less general purpose interface than exists for interacting with the top of the deck, so I still think that a "view bottom cards" right click option would be widely appreciated...and since it would reuse the same window that is already made for accessing top cards of library, I'd think it would be pretty trivial to implement..no?

**Comment by Daenyth** [comment]
I agree we should add proper menu support and parity with "top of deck" actions

**Comment by ZeldaZach** [comment]
This seems relatively easy since we know the data is exposed already. Adding a menu isn't too hard.

**Comment by ltsimeon** [comment]
Notably there is now a card that requires this action to be known by all players to be resolveable: Arvinox the Mind Flail.
