### ISSUE TITLE
Feature: disconnect from games when client closed

### ISSUE THREAD

**Issue by sbheinric** [Cockatrice/Cockatrice#3280]
It's common for rage quitters to close the client without exiting a game.  This causes them to go to disconnected state without leaving the game, and nobody knows for sure if they are a rage quitter or simply having connection issues.

I recommend putting a hook into the client "quit" function (ie, when you click the big X to close it out) that will also send a disconnect message to all games you may currently be joined in.  This would help reduce the majority of the confusion regarding rage quitters.

**Comment by ZeldaZach** [comment]
Quitting is a weird thing, and I'm honestly not sure we should change it. One advantage of accounts is the ability to reconnect to a game if it's still open and you lose connection. If they're not back within 20-30 seconds, assume they're done and simply kick

**Comment by sbheinric** [comment]
I'm NOT suggesting that players who disconnect should be removed from the game...many players have sporadic connections and do regain connection after losing it.

I am suggesting that when a player manually closes the client, there is no reason that the client shouldn't disconnect from any open games in the background...

**Comment by Daenyth** [comment]
Is there a problem with kicking them? I know I've personally used close+reconnect to game when testing the application behavior for certain things.

**Comment by sbheinric** [comment]
The problem is that rage quitting is so common, that players who have sporadic connection issues may be mistaken for rage quitting, which leads to them being kicked and sometimes permanently blocked, on the assumption that they were being a poor sport, when in fact they just had a poorly timed connection issue.

The second problem is that everyone in the game, at the very least, has to wait around for some unspecified period of time trying to figure out if they were a rage quitter or not, to know if they should wait for them to come back.  

I think that sometimes rage quitters intentionally use this as a mechanism to troll the existing players, instead of legitimately quitting, because they know it will slow the game down and create confusion after they leave, instead of just legitimately quitting the game.

why enable them with an abusive tool, that is so easy to fix?

**Comment by Daenyth** [comment]
That's a convincing argument.

This would be pretty easy to implement - in the shutdown handler, send a leave game command to any open games

**Comment by skwerlman** [comment]
this should be the default, but imo a setting should be exposed somewhere (maybe just in the INI, since its not a common need)

**Comment by ebbit1q** [comment]
I think it's not worth looking if someone ragequit or not when they disconnect. if someone quit and you don't like them you can kick them. I think regular users would every now and then have a reason to reopen the client (it's currently the only way to refresh card arts if you change them)
