### ISSUE TITLE
Feature: shortcut to enter battlefield tapped

### ISSUE THREAD

**Issue by sbheinric** [Cockatrice/Cockatrice#3281]
This feature is totally unnecessary, it would just appeal to my OCD if I had a way to play cards and have them ETB tapped instead of having to play them, and then tap them.

**Comment by ZeldaZach** [comment]
Use the `<cipt>` flag for card database

**Comment by sbheinric** [comment]
Nifty, but doesn't help with cards like [[Kismet]]

**Comment by Daenyth** [comment]
I'm not sure how valuable this is

**Comment by tooomm** [comment]
I guess this is ok to close for now then...
