### ISSUE TITLE
Cockatrice ignores saved "Show buddies only games" setting

### ISSUE THREAD

**Issue by skwerlman** [Cockatrice/Cockatrice#3282]
<b>System Information:</b>
  

  

Client Version: 2.5.2-beta (2018-06-10)
Client Operating System: Arch Linux
Build Architecture: 64-bit
Qt Version: 5.11.0
System Locale: en_US
__________________________________________________________________________________________

  

  

Regardless of what filter I used previously, the saved setting for filtering buddies only games (`filter_games/show_buddies_only_games` in `gamefilters.ini`) is completely ignored, and instead is always false when i launch trice.

Additionally, trice does not save my preference at all when i close the app.

This was last fixed in #2434, but it seems to have been broken since.

**Comment by tooomm** [comment]
#4088 should address this, @skwerlman!

**Comment by knitknit** [comment]
We're actually also not storing or reading creator name filter. ("Show buddies only" is stored, but not loaded.) I can have a fix ready for this soon.
