### ISSUE TITLE
Cards animations are occasionally incorrect

### ISSUE THREAD

**Issue by skwerlman** [Cockatrice/Cockatrice#3285]
<b>System Information:</b>
  

  

Version 2.5.0 (64-bit)
(other system info unknown; reported by a friend of mine)
__________________________________________________________________________________________

  

  

Sometimes cards become "over-untapped" when they are untapped.

![download](https://user-images.githubusercontent.com/6954107/41449137-44286e7a-702d-11e8-9c5a-80607bcd6d87.png)

**Comment by ZeldaZach** [comment]
I've never seen this before...

**Comment by ctrlaltca** [comment]
I never saw this before, too, but it' a quite interesting bug.
Do you have tap/untap animations enabled (Settings->User interface->tap/untap animation)?
The animation is run by a timer that rotates the card of 10 degrees every 10 msecs, stopping when it reaches (or surpasses) a predetermined amount (0 or 90 degrees). 
In your case, the card seems to be rotated of about 100 degrees, so the calculation is not working correctly:
![rotateme](https://user-images.githubusercontent.com/1631111/41609208-8ca32a26-73ea-11e8-9702-958126a82d28.png)

We should clamp the value to its min/max value here: https://github.com/Cockatrice/Cockatrice/blob/master/cockatrice/src/carditem.cpp#L408
