### ISSUE TITLE
Options at the top not showing up

### ISSUE THREAD

**Issue by K00lDudE1** [Cockatrice/Cockatrice#3286]
I'm using a macbook air, and have just downloaded cockatrice on it, but the options at the top aren't showing up (like connect to a server, file etc.)

Anything I have done wrong when setting up? Worked fine on my old laptop

**Comment by ZeldaZach** [comment]
Did you go to Actions? Make sure the program is the main one open (on the top of your screen with nothing blocking it)

**Comment by K00lDudE1** [comment]
Where is actions? and I have checked that the program is at the top, but still nothing

**Comment by Daenyth** [comment]
Cockatrice on OSX uses the operating system menu bar at the top of the screen, rather than the in-window linux/windows style. Is that the issue?

**Comment by K00lDudE1** [comment]
Yes, thanks, didn't notice that it used the menu bar
