### ISSUE TITLE
Delete "vc_redist" file after install?

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#3288]
It looks like `vc_redist.x64.exe` persists in the install directory of Cockatrice after both got correctly installed.
If there is a problem with that file or the installation of the vc tools the users are better off reinstaling or redownloading all Cockatrice setup to avoid other problems.

Do we want to delete this file at the end of NSIS setup? I mean, it's 15MB and never used again.

**Comment by ctrlaltca** [comment]
The actual "delete" command has been introduced in #3300, but it seems like that even when the vc_redist file has finished executing, sometimes it's still locked and can't be deleted.
It's a minor issue but it still deserves to be documented here.

**Comment by tooomm** [comment]
What do you think about my solution with adding a little sleep time? @ctrlaltca 
http://nsis.sourceforge.net/Reference/Sleep

In my tests waiting for ~10s before closing the installer did the trick, waiting only ~3s wasn't enough.
So I started testing with 5s, check it out: https://github.com/Cockatrice/Cockatrice/compare/master...tooomm-nsis_test

**Comment by ctrlaltca** [comment]
That sounds empirical, i'm not sure it will work on every pc, but it's better than nothing. Please open a PR
