### ISSUE TITLE
[Servatrice] Pointer needed for mysql db schema updating

### ISSUE THREAD

**Issue by seanbruno** [Cockatrice/Cockatrice#3303]
<b>System Information:</b>
```
root@nmm:/ # uname -a
FreeBSD nmm.ignoranthack.me 12.0-CURRENT FreeBSD 12.0-CURRENT #12 r335376: Tue Jun 19 12:55:43 EDT 2018     sbruno@box.ignoranthack.me:/usr/obj/usr/src/amd64.amd64/sys/GENERIC-NODEBUG  amd64
root@nmm:/ # /usr/local/bin/servatrice --config /usr/local/etc/servatrice.ini
Using configuration file:  "/usr/local/etc/servatrice.ini"
Servatrice 2.6.0-custom(unknown) (unknown) starting.
-------------------------
Authenticating method: none
Store Replays:  true
Client ID Required:  false
Maximum user limit enabled:  false
Accept registered users only:  false
Registration enabled:  false
Forgot password enabled:  false
Auditing enabled:  true
Audit registration attempts enabled:  true
Audit forgot password attepts enabled:  true
"[main] Opening database..."
"[main] Error opening database: the database schema version is too old, you need to run the migrations to update it from version 24 to version 26"
Failed to open database
```

__________________________________________________________________________________________

I'm pretty sure I'm just ignorant on the workings of updates here.  What is the recommended way of updating the database schema and tracking changes here?

**Comment by ctrlaltca** [comment]
Database migrations are available in the "servatrice/migrations/" folder (copy here: https://github.com/Cockatrice/Cockatrice/tree/master/servatrice/migrations)

You need to apply them to the mysql database, one by one, until you get to the required version.
In your case you need to update from version 24 to version 26, so you'll need to apply the `servatrice_0024_to_0025.sql` and `servatrice_0025_to_0026.sql` files.

How? The same way you used to initially create the database, eg:

_CLI mode_
```
mysql -u servatrice -pfoobar servatrice < servatrice_0024_to_0025.sql
mysql -u servatrice -pfoobar servatrice < servatrice_0025_to_0026.sql
```

_mysql mode_
```
# mysql -uservatrice -p
Enter password: ***
Welcome to the MariaDB monitor.  Commands end with ; or \g.
...

MariaDB [(none)]> use servatrice
...
Database changed
MariaDB [servatrice]> \. servatrice_0024_to_0025.sql
...
MariaDB [servatrice]> \. servatrice_0025_to_0026.sql
...
MariaDB [servatrice]> exit
Bye
```
This is probably a good entry to put something into this wiki page: https://github.com/Cockatrice/Cockatrice/wiki/Servatrice-Server-Maintenance

**Comment by seanbruno** [comment]
Ah, Thank you.  I'll look harder next time.
