### ISSUE TITLE
Problems with Server Woogerworks

### ISSUE THREAD

**Issue by Zabur123** [Cockatrice/Cockatrice#3306]
Hei Guys

I have Problem since i updated my Cockatrice. Every time i try to connect to the Server of cockatrice.woogerworks.com the connections doesn't work. I found out in the knowing server list if i go to Woogerworks that the .com is not behind the cockatrice.woogerworks at the server field. This is the reason why i cannot connect. I can do it manually but i have to put every time and its really annoying because it doesn't save anything... So can help me someone or actualize cockatrice to change that? 
Also as a Mac User i get a lot of that the Program closed by itself. Is it a Problem of my Mac or is this all a Bug?

Thanks for helping

Zauber

**Comment by ctrlaltca** [comment]
The woogerworks server is unavailable since april; Have a look at https://github.com/Cockatrice/Cockatrice/wiki/Public-Servers for an alternative.

**Comment by Zabur123** [comment]
But he's avaible i'm in right now..

**Comment by ctrlaltca** [comment]
From http://woogerworks.com/ :
> Cockatrice Details
> As of 4/2/2018 we have ended our support for the cockatrice application.  We wish the best to the development team of the application.
> Our current cockatrice server has been taken offline and the user base information has been transferred to the application development team that has stood up a server.  Feel free to reach out to the new owner/maintainers of the server by visiting there site at https://cockatrice.us/
> We will be redirecting the cockatrice.woogerworks.com name to the new server offered by the development team over at cockatrice.us up till 5/1/2018.  Existing players should update there cockatrice server connections from with-in the client.
