### ISSUE TITLE
Pop out windows aren't named.

### ISSUE THREAD

**Issue by JineteDV** [Cockatrice/Cockatrice#3308]
<b>System Information:</b>
Client Version: 2.6.1-beta (2018-06-24)
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
reorganizeCards: rows= 9 cols= 4
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
Player destructor: "EL_KUN"
GameScene::removePlayer name= "EL_KUN"
CardZone destructor:  "deck"
CardZone destructor:  "grave"
CardZone destructor:  "hand"
CardZone destructor:  "rfg"
CardZone destructor:  "sb"
CardZone destructor:  "stack"
CardZone destructor:  "table"
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
reorganizeCards: rows= 10 cols= 4
unhandled spectator game event 1007
reorganizeCards: rows= 10 cols= 4
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
reorganizeCards: rows= 10 cols= 4
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
ArrowItem constructor: startItem= QGraphicsItem(0x6000025fef10, parent=0x604000156d20, pos=127,10, z=1.12128e+07, flags=(ItemIsSelectable))
unhandled spectator game event 1007
ArrowItem constructor: startItem= QGraphicsItem(0x6000025f5c10, parent=0x604000156d20, pos=20,10, z=1.12021e+07, flags=(ItemIsSelectable))
ArrowItem destructor
ArrowItem destructor
unhandled spectator game event 1007
unhandled spectator game event 1007
ArrowItem constructor: startItem= QGraphicsItem(0x6040021f9710, parent=0x604006ee2310, pos=5,152, flags=(ItemIsSelectable))
unhandled spectator game event 1007
unhandled spectator game event 1007
ArrowItem destructor
unhandled spectator game event 1007
reorganizeCards: rows= 7 cols= 3
unhandled spectator game event 1007
unhandled spectator game event 1007
reorganizeCards: rows= 8 cols= 3
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
ArrowItem constructor: startItem= QGraphicsItem(0x600001bf8010, parent=0x60400014ae00, pos=20,142, z=2.44021e+07, flags=(ItemIsSelectable))
unhandled spectator game event 1007
unhandled spectator game event 1007
reorganizeCards: rows= 10 cols= 4
reorganizeCards: rows= 10 cols= 4
unhandled spectator game event 1007
reorganizeCards: rows= 10 cols= 4
reorganizeCards: rows= 5 cols= 2
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
reorganizeCards: rows= 10 cols= 4
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
reorganizeCards: rows= 7 cols= 3
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
reorganizeCards: rows= 10 cols= 4
unhandled spectator game event 1007
reorganizeCards: rows= 5 cols= 2
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
ArrowItem destructor
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
Player destructor: "SergitoColombia"
GameScene::removePlayer name= "SergitoColombia"
CardZone destructor:  "deck"
CardZone destructor:  "grave"
CardZone destructor:  "hand"
CardZone destructor:  "rfg"
CardZone destructor:  "sb"
CardZone destructor:  "stack"
CardZone destructor:  "table"
unhandled spectator game event 1007
ZoneViewZone destructor
CardZone destructor:  "grave"
ZoneViewZone destructor
CardZone destructor:  "rfg"
ZoneViewZone destructor
CardZone destructor:  "rfg"
ZoneViewZone destructor
CardZone destructor:  "grave"
ZoneViewZone destructor
CardZone destructor:  "deck"
Player destructor: "Comuz"
GameScene::removePlayer name= "Comuz"
CardZone destructor:  "deck"
CardZone destructor:  "grave"
CardZone destructor:  "hand"
CardZone destructor:  "rfg"
CardZone destructor:  "sb"
CardZone destructor:  "stack"
CardZone destructor:  "table"
Player destructor: "lollyx"
GameScene::removePlayer name= "lollyx"
CardZone destructor:  "deck"
CardZone destructor:  "grave"
CardZone destructor:  "hand"
CardZone destructor:  "rfg"
CardZone destructor:  "sb"
CardZone destructor:  "stack"
CardZone destructor:  "table"
__________________________________________________________________________________________

  Pop out windows for zones don't have names.
![screen shot 2018-06-25 at 9 20 32 am](https://user-images.githubusercontent.com/6514656/41852817-35619260-785a-11e8-97b3-34797943ce66.png)

**Comment by JineteDV** [comment]
macOS 10.13.3
I didn't leave anything out of the debug log, I copy/pasted all of it.

**Comment by tooomm** [comment]
Is this still a problem for you?

---

Starting with version ~2.5.0 your log should have this additional info right on the top:


```
Client Version: 2.6.0-custom(0c41b03) (2018-07-18)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.9.5
System Locale: de_DE
---------------------------------------------------------------------------
Theme changed: "Magic The Gathering"
SoundEngine: disabling sound
Sound theme changed: "Default"
...
```

**Comment by JineteDV** [comment]
![screen shot 2018-07-19 at 1 43 43 pm](https://user-images.githubusercontent.com/6514656/42960444-d5d12208-8b59-11e8-9dcb-6a11b96c535c.png)
What I'm using right now.

**Comment by tooomm** [comment]
Do you get the same content right after starting the app?

**Comment by JineteDV** [comment]
What do you mean by 'content'?

**Comment by tooomm** [comment]
Content of the debug log, but it looks like sometimes the os info is not completely displayed.
You completely posted your details in https://github.com/Cockatrice/Cockatrice/issues/3326#issue-341194307 already, so nevermind. It looks like sometimes not everything is shown.

Since this issues doesn't show up on windows for me, I assume it's mac only.
@ZeldaZach same problem for you on mac?

**Comment by ctrlaltca** [comment]
Looks like this is a feature implemented by Qt to follow the macOS guidelines (https://bugreports.qt.io/browse/QTBUG-40679) stating that windows titlebars are not supposed to contain an icon.
