### ISSUE TITLE
Shift-clicking to play a card face down reveals information about the card's type

### ISSUE THREAD

**Issue by anoda9** [Cockatrice/Cockatrice#331]
When you use shift+click to play a card face down, the client automatically places it in its appropriate row on the battlefield, which reveals information about the card's type. (lands get placed in the back row, creatures in the front, instants and sorceries get played to the stack.) Given that you usually play things face down to hide the identity of the card, this is a bit of a problem. It would be best if shift-clicking on a card had a consistent result no matter the card type: playing the card to the front row face down. 

Specific examples of where this reveals information: hideaway lands, liliana discards, show and tell choices, and non-creature morphs (the placement of zoetic cavern and lumithread field reveals their types).

The current workaround is to shift+drag the card into play, but it would be nice if this were fixed.

**Comment by anoda9** [comment]
Another problem is the client automatically stacks cards with the same name, even if they are face down. So if you have a face up snowhorn rider and you cast another one as a morph, it will go down on top of the face up one, making it obvious what the morph is. You can drag it into play as a workaround, but it's a little ridiculous that users have to tiptoe around the issue to prevent the client from leaking information to their opponent. Given that morph is a mainstay in the current limited format, this would be a great thing to fix.

**Comment by Daenyth** [comment]
I agree that's pretty severe. @poixen could you look at this? Shouldn't be hard to just make it always go to the front row with no stacking

**Comment by tooomm** [comment]
To complete this...
Cards that come into play tapped, also get tapped when played face down.

**Comment by anoda9** [comment]
>Another problem is the client automatically stacks cards with the same name, even if they are face down. 

This defect doesn't seem to be fixed.

**Comment by tooomm** [comment]
@anoda9 I tested it with islands and mountains and they got placed next to each other. So it seems to be fixed for me. I'm using b1736c7

**Comment by anoda9** [comment]
Hmm, I'm on version b1736c7 (mac) as well, tested it with basic lands, and they stacked on top of each other.

**Comment by tooomm** [comment]
![islands](https://cloud.githubusercontent.com/assets/9874850/6654310/f2ceac30-caba-11e4-9484-b46cf5303ff3.png)

I used the right click --> play face down and the shift+click option to play them.
(windows - local single player game for this test)

**Comment by ZeldaZach** [comment]
@tooomm Can you open a new issue relating to the stacking of face down cards please?

**Comment by tooomm** [comment]
@ZeldaZach I don't have an issue with it. @anoda9 seems to have one... you should read all new comments. ;P

**Comment by anoda9** [comment]
Update - the cards do stack separately when tested using a local single player game. But when you actually connect to the server, it does not work. (I was testing using a single player game while connected to the main server.)
