### ISSUE TITLE
Untap all - difficult to undo

### ISSUE THREAD

**Issue by sbheinric** [Cockatrice/Cockatrice#3310]
After playing a spell that prevents players from untapping (Tangle Wire, Stasis, etc) it is VERY common for players to accidentally do Ctrl+U out of habit.

This shows "Player untaps all permanents" in the chat log, but there is no record of which permanent(s) were untapped, which makes it difficult to undo in a way that other players can verify is accurate, if not everyone remembers what was tapped.

I recommend that Ctrl+U chat log entry by changed to list all the permanents that were untapped.

Alternatively, adding a general history with "Undo"/"Redo" operations would solve issues like this (and eliminate the need for "Undo last draw" as a special case).  There are a lot of various special cases that would be made easier with a general Undo button which I won't get into.

**Comment by Porkepix** [comment]
It could also be a toggle to lock untap of this permanent from automatic full untap?

**Comment by skwerlman** [comment]
dupe #3404
