### ISSUE TITLE
NSIS: win installer+uninstaller have no publisher set

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#3313]
Maybe we can't fix this because some kind of certificate/registration is needed?

**Comment by ctrlaltca** [comment]
What do you mean by "have no publisher set"? where do you see the information is missing?

**Comment by tooomm** [comment]
Right after you start the exe to install, or when you are about to uninstall via the apps & features dialog in windows for example... the user account control opens and shows `Publisher: Unknown`

**Comment by ctrlaltca** [comment]
I get what you mean. Unfortunately that field is fetched from a digital certificate that we should buy and use to sign our binaries (source: https://stackoverflow.com/questions/10581570/setting-the-uac-publisher-field-for-a-nsis-installer#10587106), so i see it as a no-go.
