### ISSUE TITLE
Regression in Manage Set Dialog

### ISSUE THREAD

**Issue by pilgrimsleet** [Cockatrice/Cockatrice#3314]
<b>System Information:</b>
  
Client Version: 2.6.0 (2018-06-17)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.9.5
System Locale: en_US
  
__________________________________________________________________________________________

  
In the "Manage sets" dialog, you have the options to "Enable all sets" and "Disable all sets."  When you have multiple sets selected, these options change to "Enable selected sets" and "Disable selected sets."  This used to be true whether the sets were in default order or sorted by one of the columns.

However, with this release when you have the sets sorted by any of the columns, for example "Set Type," the buttons will no longer toggle between "all" and "selected" depending on whether you have sets highlighted.  Instead, if you had no sets highlighted before sorting by column it will stay at "Enable all sets" and "Disable all sets" even when you subsequently highlight one or more sets, and if you have one or more sets highlighted before sorting the opposite happens.

**Comment by tooomm** [comment]
Very nice catch! 👍 

Probably caused by https://github.com/Cockatrice/Cockatrice/pull/3229
CC: @Vafthrudnir
