### ISSUE TITLE
Offline Images?

### ISSUE THREAD

**Issue by karbecker** [Cockatrice/Cockatrice#3315]
Is there an option to batch-download all images (in order to use Cockatrice offline for deckbuilding)?

**Comment by Daenyth** [comment]
There's not but you can go into the deck builder and scroll through cards. Every time you select a card on the left it will trigger a download. You can use the arrow key to go through a bunch at once, though I don't think the app will behave well if you try to download thousands at once, so maybe do it in chunks

**Comment by ctrlaltca** [comment]
Closing. There are sources to get the whole imagesets out on the web, but providing them for a specific game is outside the target of cockatrice.
