### ISSUE TITLE
cockatrice crashes when using search

### ISSUE THREAD

**Issue by syi666** [Cockatrice/Cockatrice#3317]
<b>System Information:Theme changed: "Default"
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
Language changed: ""
main(): starting main program
main(): MainWindow constructor finished
CardDatabase::loadCardDatabases start
[CockatriceXml3Parser] Trying to parse:  "C:/Users/Syi/AppData/Local/Cockatrice/Cockatrice/cards.xml"
main(): ui.show() finished
cache fail for "_trice_card_back_226450"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Syi/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 12093 Sets= 228
[CockatriceXml3Parser] Trying to parse:  "C:/Users/Syi/AppData/Local/Cockatrice/Cockatrice/tokens.xml"
Spoiler Service Online
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Syi/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 12351 Sets= 228
[CockatriceXml3Parser] Trying to parse:  "C:/Users/Syi/AppData/Local/Cockatrice/Cockatrice/spoiler.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Syi/AppData/Local/Cockatrice/Cockatrice/spoiler.xml" Status = 0 Cards = 12353 Sets= 228
[CockatriceXml3Parser] Trying to parse:  "C:/Users/Syi/AppData/Local/Cockatrice/Cockatrice/customsets/TK.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Syi/AppData/Local/Cockatrice/Cockatrice/customsets/TK.xml" Status = 0 Cards = 12359 Sets= 228
CardDatabase::loadCardDatabases success
Data Hash = "\xEDvf\xEA\xDD\xC9.o\x9Ag\x1C\x07""a8\xDD<"
File Hash = "\xEDvf\xEA\xDD\xC9.o\x9Ag\x1C\x07""a8\xDD<"
Spoilers Up to Date
Searching for updates on the channel:  "https://api.github.com/repos/Cockatrice/Cockatrice/releases/latest"
Current hash= "c7072cd" update hash= ""
Got reply from release server, size= 11345 name= "Cockatrice 2.6.0: Father of Ruins" desc= "https://github.com/Cockatrice/Cockatrice/releases/tag/2018-06-17-Release-2.6.0" date= QDate("2018-06-17") url= "https://github.com/Cockatrice/Cockatrice/releases/download/2018-06-17-Release-2.6.0/Cockatrice-Father_of_Ruins-2.6.0-win64.exe"
Searching for commit hash corresponding to stable channel tag:  "2018-06-17-Release-2.6.0"
Got reply from tag server, size= 395 commit= "c7072cd543fd2972433bd1f8cf4f5023b8d157c1"
Current hash= "c7072cd" update hash= "c7072cd"
cache fail for "_trice_card_back_226450"</b>
  

  
__________________________________________________________________________________________

  
cockatrice randomly crashes when searching for cards. sometimes I get 2 letters in right after start up, sometimes I can build a whole commander deck before starting a new one and crashing

**Comment by ZeldaZach** [comment]
What version are you on? It looks like it's trying to download the newest release and then crashing

**Comment by syi666** [comment]
2.6.0(2018-06-17)

**Comment by Daenyth** [comment]
I doubt that log output is related because a crash won't generate debug log output, so that must have come from a session pre-crash. No?

**Comment by syi666** [comment]
That's the log after the crash. Opened it up and that's all it says

**Comment by Daenyth** [comment]
Just to be clear, this is a "this application stopped working" crash?

**Comment by syi666** [comment]
Ya. I type in the card search and it'll hang for a second or 2 and just
close without an error from windows

**Comment by Daenyth** [comment]
Possible dupe #2287

**Comment by tooomm** [comment]
For completeness, can you please append the upper part/first lines of the debug log about your system config, too @syi666?
