### ISSUE TITLE
Can't connect because of password, update

### ISSUE THREAD

**Issue by liama482** [Cockatrice/Cockatrice#3319]
<b>System Information:</b>
  
Theme changed: "Default"
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
main(): starting main program
main(): MainWindow constructor finished
CardDatabase::loadCardDatabases start
main(): ui.show() finished
QWindowsWindow::setGeometry: Unable to set geometry 1366x748+0+20 on QWidgetWindow/'MainWindowClassWindow'. Resulting geometry:  1366x745+0+23 (frame: 8, 31, 8, 8, custom margin: 0, 0, 0, 0, minimum size: 861x748, maximum size: 16777215x16777215).
cache fail for "_trice_card_back_226300"
cache fail for "_trice_card_back_226298"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/lp2ab/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 17899 Sets= 219
[CardDatabase] loadCardDatabase(): Path = "C:/Users/lp2ab/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 18269 Sets= 219
[CardDatabase] loadCardDatabase(): Path = "C:/Users/lp2ab/AppData/Local/Cockatrice/Cockatrice/customsets/TK.xml" Status = 0 Cards = 18269 Sets= 219
CardDatabase::loadCardDatabases success
  
__________________________________________________________________________________________

  
I haven't played Cockatrice in awhile (my guess is 4-6 months but it may have been a little longer). Today I had some time availible and opened cockatrice but it wouldn't let me connect. I selected previous host (cockatrice.woogerworks.com) and retained my previous username and password which the application retained. Upon pressing "ok", it said "Your client seems to be missing features this server requires for connection". I clicked on show details, and got "Missing features: forgot password" and instructions of how to update my client.

I attempted to update the client and reached a stage looking like:
![capture1cockatrice](https://user-images.githubusercontent.com/21697116/42524875-bcda7a22-843f-11e8-94ed-a811b4fdca5a.PNG)

After reaching that it froze and progressed no further. Alas, I have been unable to update my client and connect to the main server. Searches on the wiki proved unhelpful or inconclusive. I hope to update Cockatrice without deleting any decks I currently have saved locally, although I am not sure whether deleting the whole application would delete all local data.

**Comment by ZeldaZach** [comment]
You’ll want to go download manually from cockatrice.github.io as your client is using the bad updated code. No decks or settings are lost.
