### ISSUE TITLE
Window resizes itself

### ISSUE THREAD

**Issue by JineteDV** [Cockatrice/Cockatrice#3326]
<b>macOS 10.13.3</b>
Client Version: 2.6.1-beta (2018-06-24)
Client Operating System: macOS High Sierra (10.13)
Build Architecture: 64-bit
Qt Version: 5.11.1
System Locale: en_US
---------------------------------------------------------------------------
Theme changed: "Default"
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
Language changed: "en"
main(): starting main program
Spoilers Disabled
main(): MainWindow constructor finished
CardDatabase::loadCardDatabases start
[CockatriceXml3Parser] Trying to parse:  "/Users/azix_zan/Desktop/Cockatrice AM/M191.xml"
main(): ui.show() finished
cache fail for "_trice_card_back_273373"
[CardDatabase] loadCardDatabase(): Path = "/Users/azix_zan/Desktop/Cockatrice AM/M191.xml" Status = 0 Cards = 18621 Sets= 229
[CockatriceXml3Parser] Trying to parse:  "/Users/azix_zan/Desktop/Cockatrice AM/M19TK1.xml"
[CardDatabase] loadCardDatabase(): Path = "/Users/azix_zan/Desktop/Cockatrice AM/M19TK1.xml" Status = 0 Cards = 19016 Sets= 229
[CardDatabase] loadCardDatabase(): Path = "/Users/azix_zan/Library/Application Support/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 19016 Sets= 229
[CockatriceXml3Parser] Trying to parse:  "/Users/azix_zan/Library/Application Support/Cockatrice/Cockatrice/customsets/01.FFTCG Opus 2.xml"
[CardDatabase] loadCardDatabase(): Path = "/Users/azix_zan/Library/Application Support/Cockatrice/Cockatrice/customsets/01.FFTCG Opus 2.xml" Status = 0 Cards = 19165 Sets= 230
[CockatriceXml3Parser] Trying to parse:  "/Users/azix_zan/Library/Application Support/Cockatrice/Cockatrice/customsets/02.FFTCG Opus 3.xml"
[CardDatabase] loadCardDatabase(): Path = "/Users/azix_zan/Library/Application Support/Cockatrice/Cockatrice/customsets/02.FFTCG Opus 3.xml" Status = 0 Cards = 19320 Sets= 231
CardDatabase::loadCardDatabases success
QLayout: Attempting to add QLayout "" to TabLog "", which already has a layout
cache fail for "_trice_card_back_250181"
GameScene::addPlayer name= "getupandgo"
addCounter: "getupandgo" 0 "life"
addCounter: "getupandgo" 1 "w"
addCounter: "getupandgo" 2 "u"
addCounter: "getupandgo" 3 "b"
addCounter: "getupandgo" 4 "r"
addCounter: "getupandgo" 5 "g"
addCounter: "getupandgo" 6 "x"
addCounter: "getupandgo" 7 "storm"
GameScene::addPlayer name= "VivaSkegVegas"
addCounter: "VivaSkegVegas" 0 "life"
addCounter: "VivaSkegVegas" 1 "w"
addCounter: "VivaSkegVegas" 2 "u"
addCounter: "VivaSkegVegas" 3 "b"
addCounter: "VivaSkegVegas" 4 "r"
addCounter: "VivaSkegVegas" 5 "g"
addCounter: "VivaSkegVegas" 6 "x"
addCounter: "VivaSkegVegas" 7 "storm"
Trying to load picture (set:  "M19"  card:  "Forest" )
Picture found on disk (set:  "M19"  file:  "Forest" )
cache fail for "_trice_card_back_5375"
Trying to load picture (set:  "EMA"  card:  "Green Sun's Zenith" )
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPixmap::scaled: Pixmap is a null pixmap
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
Picture found on disk (set:  "EMA"  file:  "Green Sun's Zenith" )
Trying to load picture (set:  "MM2"  card:  "Emrakul, the Aeons Torn" )
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
Picture found on disk (set:  "MM2"  file:  "Emrakul, the Aeons Torn" )
Trying to load picture (set:  "ONS"  card:  "Enchantress's Presence" )
Picture found on disk (set:  "ONS"  file:  "Enchantress's Presence" )
Trying to load picture (set:  "CNS"  card:  "Exploration" )
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
unhandled spectator game event 1007
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
Picture found on disk (set:  "CNS"  file:  "Exploration" )
Trying to load picture (set:  "M19"  card:  "Forest" )
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
Picture found on disk (set:  "M19"  file:  "Forest" )
Trying to load picture (set:  "USG"  card:  "Serra's Sanctum" )
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
Picture found on disk (set:  "USG"  file:  "Serra's Sanctum" )
Trying to load picture (set:  "7ED"  card:  "Wild Growth" )
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
Picture found on disk (set:  "7ED"  file:  "Wild Growth" )
Trying to load picture (set:  "VMA"  card:  "Savannah" )
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
Picture found on disk (set:  "VMA"  file:  "Savannah" )
Trying to load picture (set:  "ME2"  card:  "Helm of Obedience" )
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
Picture found on disk (set:  "ME2"  file:  "Helm of Obedience" )
Trying to load picture (set:  "MM2"  card:  "Oblivion Ring" )
QPainter::end: Painter ended with 2 saved states
Picture found on disk (set:  "MM2"  file:  "Oblivion Ring" )
Trying to load picture (set:  "EXP"  card:  "Windswept Heath" )
QPainter::end: Painter ended with 2 saved states
Picture found on disk (set:  "EXP"  file:  "Windswept Heath" )
Trying to load picture (set:  "A25"  card:  "Living Wish" )
Picture found on disk (set:  "A25"  file:  "Living Wish" )
Trying to load picture (set:  "A25"  card:  "Utopia Sprawl" )
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
Picture found on disk (set:  "A25"  file:  "Utopia Sprawl" )
Trying to load picture (set:  "XLN"  card:  "Ixalan's Binding" )
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
Picture found on disk (set:  "XLN"  file:  "Ixalan's Binding" )
Trying to load picture (set:  "JOU"  card:  "Eidolon of Blossoms" )
QPainter::end: Painter ended with 2 saved states
Picture found on disk (set:  "JOU"  file:  "Eidolon of Blossoms" )
Trying to load picture (set:  "C15"  card:  "Doomwake Giant" )
QPainter::end: Painter ended with 2 saved states
Picture found on disk (set:  "C15"  file:  "Doomwake Giant" )
Trying to load picture (set:  "EMA"  card:  "Argothian Enchantress" )
QPainter::end: Painter ended with 2 saved states
Picture found on disk (set:  "EMA"  file:  "Argothian Enchantress" )
Trying to load picture (set:  "HOU"  card:  "Solemnity" )
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
Picture found on disk (set:  "HOU"  file:  "Solemnity" )
Trying to load picture (set:  "NPH"  card:  "Phyrexian Unlife" )
QPainter::end: Painter ended with 2 saved states
Picture found on disk (set:  "NPH"  file:  "Phyrexian Unlife" )
Trying to load picture (set:  "EMA"  card:  "Green Sun's Zenith" )
QPainter::end: Painter ended with 2 saved states
Picture found on disk (set:  "EMA"  file:  "Green Sun's Zenith" )
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
unhandled spectator game event 1007
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
unhandled spectator game event 1007
QPainter::end: Painter ended with 2 saved states
cache fail for "_trice_card_back_250334"
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
unhandled spectator game event 1007
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
unhandled spectator game event 1007
ArrowItem constructor: startItem= QGraphicsItem(0x604000dfd410, parent=0x60000015d230, pos=330,162, z=2.64331e+07, flags=(ItemIsSelectable))
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
unhandled spectator game event 1007
unhandled spectator game event 1007
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
unhandled spectator game event 1007
ArrowItem constructor: startItem= QGraphicsItem(0x604000dfac10, parent=0x6000038e2a90, pos=5,152, flags=(ItemIsSelectable))
unhandled spectator game event 1007
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
unhandled spectator game event 1007
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
Trying to load picture (set:  "A25"  card:  "Rest in Peace" )
QPainter::end: Painter ended with 2 saved states
Picture found on disk (set:  "A25"  file:  "Rest in Peace" )
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
ArrowItem destructor
unhandled spectator game event 1007
ArrowItem constructor: startItem= QGraphicsItem(0x604000dfac10, parent=0x60000015d230, pos=20,142, z=2.44021e+07, flags=(ItemIsSelectable))
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
ArrowItem destructor
unhandled spectator game event 1007
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
unhandled spectator game event 1007
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
unhandled spectator game event 1007
ArrowItem constructor: startItem= QGraphicsItem(0x604000dfe210, parent=0x60000015d230, pos=330,152, z=2.54331e+07, flags=(ItemIsSelectable))
unhandled spectator game event 1007
unhandled spectator game event 1007
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
unhandled spectator game event 1007
unhandled spectator game event 1007
unhandled spectator game event 1007
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
unhandled spectator game event 1007
unhandled spectator game event 1007
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
unhandled spectator game event 1007
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
Trying to load picture (set:  "TMP"  card:  "Mirri's Guile" )
QPainter::end: Painter ended with 2 saved states
Picture found on disk (set:  "TMP"  file:  "Mirri's Guile" )
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
unhandled spectator game event 1007
unhandled spectator game event 1007
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
QPainter::end: Painter ended with 2 saved states
unhandled spectator game event 1007
__________________________________________________________________________________________

 Almost every game I join ends up resizing the window to be longer than my screen dimensions.

**Comment by JineteDV** [comment]
Version 2.6.1 (2018-07-17)
Still having the same problem. What it gets resized to after joining as a spectator, I think this only happens when joining as a spectator.
![screen shot 2018-09-08 at 9 08 41 pm](https://user-images.githubusercontent.com/6514656/45260098-a42d1e80-b3ab-11e8-8f98-f7ca87656e69.png)

**Comment by tooomm** [comment]
I can confirm this on windows 10 with 2.6.1 👍 
For testing I started trice, connected to a server, joined a game and got this screen:
![resize](https://user-images.githubusercontent.com/9874850/45264219-81e1e200-b439-11e8-871e-e7cc3d0e8c57.png)

It's supposed to be full screen, but cut off at the buttom.
Linking https://github.com/Cockatrice/Cockatrice/issues/1904, https://github.com/Cockatrice/Cockatrice/issues/2708 and https://github.com/Cockatrice/Cockatrice/issues/2621 

<details>

Client Version: 2.6.1-custom(4970653) (2018-09-04)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.9.5
System Locale: de_DE

---------------------------------------------------------------------------
Theme changed: "Magic The Gathering"
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
Language changed: "en"
main(): starting main program
main(): MainWindow constructor finished
CardDatabase::loadCardDatabases start
[CockatriceXml3Parser] Trying to parse:  "C:/.../Cockatrice/Cockatrice/cards.xml"
main(): ui.show() finished
PictureLoader: cache fail for "_trice_card_back_226283"
Spoiler Service Online
Data Hash = "\xEC\xE7\x8B\x97\xD6\x8D""e\x19|6ac\xD4\x1D\xDA\xFA"
File Hash = "\xEC\xE7\x8B\x97\xD6\x8D""e\x19|6ac\xD4\x1D\xDA\xFA"
Spoilers Up to Date
[CardDatabase] loadCardDatabase(): Path = "C:/.../Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 18621 Sets= 229
[CockatriceXml3Parser] Trying to parse:  "C:/.../Cockatrice/Cockatrice/tokens.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/.../Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 19022 Sets= 229
[CockatriceXml3Parser] Trying to parse:  "C:/.../Cockatrice/Cockatrice/spoiler.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/.../Cockatrice/Cockatrice/spoiler.xml" Status = 0 Cards = 19022 Sets= 229
[CockatriceXml3Parser] Trying to parse:  "C:/.../Cockatrice/Cockatrice/customsets/TK.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/.../Cockatrice/Cockatrice/customsets/TK.xml" Status = 0 Cards = 19022 Sets= 229
CardDatabase::loadCardDatabases success
PictureLoader: cache fail for "_trice_card_back_250156"
**QWindowsWindow::setGeometry: Unable to set geometry 1366x719+0+23 on QWidgetWindow/'MainWindowClassWindow'. Resulting geometry:  1366x705+0+23 (frame: 8, 31, 8, 8, custom margin: 0, 0, 0, 0, minimum size: 709x719, maximum size: 16777215x16777215).**
PictureLoader: cache fail for "_trice_card_back_286201"
GameScene::addPlayer name= "x"
GameScene::addPlayer name= "y"
PictureLoader: cache fail for "_trice_card_back_286200"

</details>

**Comment by ebbit1q** [comment]
I merged these tickets into https://github.com/Cockatrice/Cockatrice/issues/4114
