### ISSUE TITLE
Unable to create tokens using their associated cards.

### ISSUE THREAD

**Issue by vengerofthelight** [Cockatrice/Cockatrice#3333]
Couldn't find this issue elsewhere, so I'm making a new one.

I recently updated to v2.6.0 (2018-06-17), Cockatrice 64-bit.  Running Windows 10.  After this update I've found that I'm unable to use the right-click drop-down menu to create tokens associated with the card I've clicked on unless I use the "Create Token" dialogue window; the option to create the token associated with the card from the menu simply isn't there.

I've tried updating Cockatrice (the Client Update function says I have the latest build from Stable Releases), I've tried running Oracle, and I've tried creating new decks with different token-producing cards.  If anyone has any idea why I can't seem to create tokens in this way, I'd appreciate the help.

**Comment by tooomm** [comment]
Thanks for your report.

There will be a new stable release out in the next few days with a fix.
If you can't wait you have to download and switch to the beta version in the meantime. The fix is already included there!
