### ISSUE TITLE
prevent saving of empty decks

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#3339]
<b>System Information:</b>
Client Version: 2.6.0-custom(168cc49) (2018-07-20)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.9.5
System Locale: de_DE
__________________________________________________________________________________________

Currently it's possible to save an empty deck.
The menu entry should be greyed out until there is something to save like an added name, comments or cards...

**Comment by ZeldaZach** [comment]
Seems like a low priority thing, but should be fairly simple

**Comment by berserkingyadis** [comment]
Is implementing a "dirty" flag the right approach? I used this to invalidate caches or to check if something needs to be rewritten to DB because it changed.

**Comment by Daenyth** [comment]
I think we can do a fully correct check rather than a dirty flag. There's
not that much data
