### ISSUE TITLE
Cannot connect with older client

### ISSUE THREAD

**Issue by joshuabengal** [Cockatrice/Cockatrice#3340]
I see a recent change checks for older client versions, and I can no longer connect. Can someone point me to anything I can add to my older client code to be able to connect? 

I have a made a large number of UI changes over the years to the program to accommodate specific disabilities, and it would be a huge hassle to have to start all over from scratch with the new code base.

**Comment by skwerlman** [comment]
context: #2388

**Comment by skwerlman** [comment]
you _might_ be able to get away with just adding the line 
```
featureList.insert("2.6.1_min_version", false);
```
to `FeatureSet::initalizeFeatureList` in `common/featureset.cpp`.

i'm not 100% sure if it'll work, but it's worth a shot

**Comment by ZeldaZach** [comment]
If you've made changes to the client that you found beneficial, maybe consider opening some PRs so others can experience them, @joshuabengal ?

Also, I'd really like to deter from modifying the featureset like that, as there are changes we make, both server and client sided, that can break if not on the proper channels.

**Comment by Daenyth** [comment]
@joshuabengal I'd really appreciate if you can open a public fork with your modifications. It would ease things for everyone if we can get some of them integrated, even if only as compile time switches. Then we could maintain them instead of you needing to.

**Comment by joshuabengal** [comment]
Hey that did it! Thanks!

skwerlman wrote:
