### ISSUE TITLE
Error on 32bit install on windows

### ISSUE THREAD

**Issue by educator23** [Cockatrice/Cockatrice#3343]
<b>System Information:</b>
  

   I have Windows 7 and downloaded the 32-bit version of Father of Ruins.  
__________________________________________________________________________________________

  

  

Upon install it gets almost complete an says "The procedure entry point qsort_s could not be located in the dynamic link library msvcrt.dll"

It claims to complete the install, but won't open.

**Comment by tooomm** [comment]
Did you try the 64bit version?
You can download it from https://cockatrice.github.io
Before, you should make sure that you have all windows updates installed.

Give us an update please, on how it goes!

**Comment by educator23** [comment]
The 64-bit automatically didn't work because it is not 32 bit said the error.

**Comment by educator23** [comment]
I recall a problem like this back on the last update, but cannot recall how I got around or dealt with it.

**Comment by tooomm** [comment]
So you are running an old 32bit version of windows then, ok.
The 32bit installer is correct in that rare situation.

You are trying to install version 2.6.1?

Is your system up to date with all available updates and service packages?

**Comment by educator23** [comment]
I checked for Service Packs. Windows Genuine Advantage was the only one missing.  I installed it.  I still get the error:

vc_redlist.x86.exe Entry Point Not Found

I click ok and it "complete" the installation but won't open.

**Comment by tooomm** [comment]
Ok, so the `Visual C++ Redistributable` installation is a problem for you.
Are there any more details or error messages that the vc_redist pop-up installation shows you?

cc: @ctrlaltca

**Comment by tooomm** [comment]
During installation you can show `More Details`.
If you expand that and send a screenshot once it gets stuck that would be great!

**Comment by educator23** [comment]
It isn't allowing me to attach for some reason. It could be my browser

**Comment by ctrlaltca** [comment]
If the `vc_redist.x86.exe` installer doesn't even start, it's either missing one of its dependencies or some library is severely messed up on the pc.
I'd start with some basic maintenance:
 * running `sfc /scannow` from an administrative command prompt, it should check and fix any error in libraries (more info here: https://support.microsoft.com/en-us/help/929833/use-the-system-file-checker-tool-to-repair-missing-or-corrupted-system )
 * ensuring your system is up to date, running windows update until it shows no more important updates are available.

**Comment by educator23** [comment]
No idea why I can't paste into this from this or any browser.  I can't select the file either.  It seems to hang up after "Created uninstaller: C:\Program Files\Cockatrice\uninstall.exe"

Then...Execute:"C:\ProgramFiles\Cockatrice\vc_redist.x86.exe' /passive /norestart

and it hangs then gives the error.

I uninstalled it prior to installing it this time, and it did the same thing.

**Comment by tooomm** [comment]
Why don't you try what we are suggesting then?

**Comment by educator23** [comment]
I had. I did every update I could find. The repair doesn't have a link for XP, so I am still looking into it.  I work a lot and have small children.

**Comment by tooomm** [comment]
>The repair doesn't have a link for XP, so I am still looking into it.

If you are really still running XP, instead the above stated Windows 7, we can't really help you as we no longer support XP and Cockatrice won't work on such old and unsafe operating systems. Sorry :/

**Comment by Daenyth** [comment]
If you can install a virtual machine on your XP install, then you should be able to run the linux version.
