### ISSUE TITLE
Ignored Rooms

### ISSUE THREAD

**Issue by Brokenlighthouse** [Cockatrice/Cockatrice#3344]
my suggestion is to make it so the rooms of players that have you on the ignore list do not show up in the roomlist, that way you dont have any confusion when trying to join a room, and it can reduce clutter on your list if you have many people who for any reason have ignored you. 

thanks for reading my request, Corners___

**Comment by Daenyth** [comment]
This has been asked before - the core issue is that your client doesn't know who is ignoring you. Related #1950

**Comment by ZeldaZach** [comment]
Dupe #1950
