### ISSUE TITLE
Can I still play Cockatrice on my MAC OSX 10.10.5?

### ISSUE THREAD

**Issue by Dwaynger** [Cockatrice/Cockatrice#3345]
<b>System Information:</b>
  

   10.10.5 and I've been running the Trials of the Gods Cockatrice version.
__________________________________________________________________________________________

   I can't update Cockatrice and I think it's because my computer is too old. Is there any way I can still play Cockatrice? If so, what should I do?

**Comment by tooomm** [comment]
Did you follow the `Compile your own binaries` link on our webpage?
You should try to compile Cockatrice for your own if you feel comfortable doing so.
See here: https://github.com/Cockatrice/Cockatrice/wiki/Compiling-Cockatrice-(macOS)
If you have trouble with the instructions let us know.

On a site note:
You are running a very old version of macOS. You should definitely update your operating system for security reasons as Apple dropped latest of supports for 10.10 already one year ago! If your hardware is not 10+ years old there should be no problem upgrading to 10.11 which we still support!

**Comment by ZeldaZach** [comment]
Note for Tom: _this_ is why I like to stay as compatible as possible 😛

**Comment by Daenyth** [comment]
@Dwaynger If you haven't compiled in the past on your machine, it's likely impossible now because Apple likes to delete the resources you need to do it, once newer versions of OSX come out. Apple really likes to set things up so you either update or become unable to properly use your machine.

**Comment by ctrlaltca** [comment]
Closing. Feel free to reopen if you need guidance on the compiling steps.
