### ISSUE TITLE
app crashes every attempt to save new deck

### ISSUE THREAD

**Issue by saunders22** [Cockatrice/Cockatrice#3348]
<b>System Information:</b>
  

  
__________________________________________________________________________________________

  
Cockatrice has been working fine until i try to save a deck. i try to save and the app crashes. only tells me "a problem has caused the program to stop working correctly" and the only option is to close program.

**Comment by saunders22** [comment]
windows os btw

**Comment by tooomm** [comment]
Please **provide complete information** about your system **from the debug window** as asked for, e.g.

```
Client Version: 2.6.0 (2018-06-17)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.9.5
System Locale: en_US
```

**Comment by ctrlaltca** [comment]
Try to check https://github.com/Cockatrice/Cockatrice/wiki/Troubleshooting#cockatrice-crashes-when-i-try-to-save-or-load-a-deck
Please reopen if this is still an issue for you, but provide the requested informations.
