### ISSUE TITLE
Window resize on gnome3

### ISSUE THREAD

**Issue by kitchenlattice** [Cockatrice/Cockatrice#335]
When I have a game tab open, the window fixes itself to the maximum screen resolution height (width is still adjustable). However, since this is gnome3, there is a status bar across the top of my desktop under which no window can travel, so the bottom of the window is off the desktop and cannot be reached. This is just enough to make it possible to type in the chat dialog (but not see what I'm typing) in the game rooms and not enough to even do that in a direct message tab.

Don't know if the height is hard-coded or pulled from environment, but it should be max window height, not screen height. It makes playing a major pain.

**Comment by ZeldaZach** [comment]
If this is still malfunctioning, @kitchenlattice, feel free to re-open it.
