### ISSUE TITLE
Save game filter on a per-server basis

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#3350]
It makes not too much sense to have the game filter be the same for every server.
People might be playing different games on different server, or one server (Chickatrice) simply doesn't have a game type option e.g. "Limited" the other has (Rooster Ranges) or it's named differently...

**Comment by ebbit1q** [comment]
I don't think this is a big deal, most of the time you'd want to select a different filter anyway, maybe even removing this from the stored settings would be better.
