### ISSUE TITLE
Client Update Install not completing

### ISSUE THREAD

**Issue by Rendroc** [Cockatrice/Cockatrice#3353]
<b>System Information:</b>Clie
MacBook Air (13-inch, Early 2014)
  
Client Version: 2.5.0 (2018-03-02)

  
__________________________________________________________________________________________

   Install won't complete for new client update. Tried installing by downloading dmg from Github, but it won't even start the download.

**Comment by ctrlaltca** [comment]
Try downloading from https://cockatrice.github.io/ or https://github.com/Cockatrice/Cockatrice/releases
I just tried the downloads and they works.

**Comment by Rendroc** [comment]
It may had to do with my connection. I tried on a different WiFi a bit later and it worked.

**Comment by tooomm** [comment]
Probably. Enjoy your games! :)
