### ISSUE TITLE
Cockatrice Development Meeting #2

### ISSUE THREAD

**Issue by ZeldaZach** [Cockatrice/Cockatrice#3354]
Hi everybody!

The 2nd Cockatrice Development meeting will be taking place in the very near future. Please fill out the poll at <OLD_URL>. You will see the poll times in your local timezone. 

Meeting will take place on [Discord](https://discord.gg/3Z9yzmA)

We'll need at least 5 of the 6 below to attend in order for this meeting to take place based on the dates provided in the poll. cc: @zeldazach @Daenyth @ctrlaltca @Psithief @tooomm @Vafthrudnir 

You can refer to last development's meeting via #3188 to see what has/will be accomplished and what we should revise in the schedule.

**Comment by ZeldaZach** [comment]
The planned time of the development meeting will be

**Sunday, August 5th, 2018 from 09:45-11:00 EST (UTC - 4)**

Developers, please plan to join the call promptly at 09:45. We only have around an hour, so I'd like to make the best of it, if possible.

**Comment by Psithief** [comment]
Is the agenda ready?

**Comment by tooomm** [comment]
I liked your timer from last time, hope I got the timezone right as only one location currently uses EST 😄 

https://www.timeanddate.com/countdown/generic?iso=20180805T0945&p0=1183&msg=Cockatrice+Development+Meeting&font=cursive&csz=1

**Comment by ctrlaltca** [comment]
EST is UTC-5, EDT is UTC-4. Which one is correct?

**Comment by skwerlman** [comment]
Most of what is normally EST is EDT right now, so i'd assume EDT

**Comment by ZeldaZach** [comment]
A baseline agenda (as well as serving as our meeting minutes page): https://docs.google.com/document/d/1hfTKdUv8h0ofqHJV_ZwHny2lxSnfwSCVN-FYgMLkixs/

**Comment by ctrlaltca** [comment]
I guess this can be closed now?

**Comment by tooomm** [comment]
It could be handy to have a tag for meetings so that we can easily find and filter for them!

**Comment by ctrlaltca** [comment]
@tooomm nice idea, added
