### ISSUE TITLE
long idle times cause client/server lethargy.

### ISSUE THREAD

**Issue by Gartral** [Cockatrice/Cockatrice#3357]
<b>System Information:</b>
Various.
__________________________________________________________________________________________

this is a preliminary write-up of an edge-case bug... first the backstory: I run a cockatrice server for a small-ish community of about 50 players, give or take. They asked, since it's a semi-private server if I could remove the forced kick of idle players. Sure.

well that uncovered a bug that's proving difficult to track down, many users, myself included have noticed that after about 18-20 hours of idling that the server is ignoring some commands... these being so far as I've tested: 

Start watching a game replay. 
deck managment.
And sending to chat.

 And for the admins and mods: we can't search the games part of the logs. everything else works, including resuming watching a game replay if you left one open overnight.  

the kicker? (heh) if you submit a command that WORKS such as start a new game, all the other commands start working again. combine this with the fact that re-logging isn't that hard nor annoying and there's a way to work around it on cockatrice without a relog, I'm not too worried about it, but some of my other users are annoyed.

**Comment by Daenyth** [comment]
off hand I wonder if there's a timer that causes the user's connection thread to be scheduled to run which isn't firing due to the idle setting.

**Comment by Gartral** [comment]
that's quite likely, I've discovered that even though I've disabled the idle kick timer for players in a game, a timer fires and disconnects the client altogether.

**Comment by Daenyth** [comment]
@ZeldaZach I think you worked on the idle timer? Anything ringing a bell here?

**Comment by ZeldaZach** [comment]
This feels like a corner case honestly. I'm not sure how we can track this down easily
