### ISSUE TITLE
Can't sort sets by columns anymore

### ISSUE THREAD

**Issue by Cerxi** [Cockatrice/Cockatrice#3359]
I assume, given the "While set list is sorted by columns, custom setting is disabled" message, that this is intended behavior, but I'd like to ask you to reconsider, or at least add a toggle for this behavior. Up until now, I've sorted my sets by *oldest* first, so I can see the original art for every card, by sorting by release date and saving, but now I can't do that. And since the new default order is *newest* first, that means I have to hand-reverse every single set. Please, let me just save after sorting by column again.

**Comment by Daenyth** [comment]
What you mention should be supported - I don't think we intended to remove that

**Comment by ZeldaZach** [comment]
I believe @Vafthrudnir introduced this feature

**Comment by Vafthrudnir** [comment]
Yes, this is a "feature" that was introduced with the implementation of filtering. It's certeainly possible to add a button that makes the sorted list the image priority order, it could replace the warning label.

Sorry for the inconvenience, I'll fix it as soon as I can (probably two weeks from now).

**Comment by kvesel** [comment]
This is being fixed yet? I am having same problem with Fedora 29.

**Comment by Daenyth** [comment]
@Vafthrudnir did you ever get a chance to look at this?

**Comment by archetypalsxe** [comment]
Would like to see this get resolved as well!

**Comment by ebbit1q** [comment]
I've added a simple ignore button to the warning: #3463 
@archetypalsxe @k5t77 @kvesel @Cerxi Is this good enough for a fix for your issue?

**Comment by archetypalsxe** [comment]
@ebbit1q Sounds good to me, thanks!

**Comment by ebbit1q** [comment]
Cool

**Comment by Cerxi** [comment]
I'll have to give it a look to be sure, but it sounds like it works for me.
Though I wonder if, for people unfamiliar with the issue, "Ignore" might be a confusing word, implying you're sending the warning away rather than overwriting it. You might consider something more explicative like "Save Anyway"?

**Comment by kvesel** [comment]
Why does this not saving sort order when selecting columns in Fedora 29? It is only giving warning and not settings are saving.

**Comment by ebbit1q** [comment]
Please check out the changes I made to the warning here: #3463

**Comment by kvesel** [comment]
This is will be released for Fedora 29 or will only compiling with source?

**Comment by Cerxi** [comment]
The change was just made, it's not released for *anything* yet. Patience.

**Comment by ebbit1q** [comment]
This will be released in the next beta, soon, ish. If you are that impatient you still have the option to compile from source. The next release will include Fedora, Ubuntu 18.04, osx Sierra, and windows.

**Comment by tooomm** [comment]
@Daenyth Well, the PR isn't merged yet and deployment only works from master.
Also, starting with the docker builds we have an issue with deploying packages correctly which we need to fix first. Only windows deploys fine since nothing changed at appveyor. :)

**Comment by ebbit1q** [comment]
This is why I said soon ish, I have no clue why this happens and I can't test deploying.

**Comment by tooomm** [comment]
Once your naming fix is in we can try a new test beta release @ebbit1q  👍
