### ISSUE TITLE
Custom Pics doesn't work with Chinese

### ISSUE THREAD

**Issue by Fifholz** [Cockatrice/Cockatrice#3360]
<b>System Information:</b>
  
```
Client Version: 2.6.1 (2018-07-17)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.9.5
System Locale: zh_CN
---------------------------------------------------------------------------
Portable mode enabled
Theme changed: "Default"
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
Language changed: "zh-Hans"
main(): starting main program
Spoilers Disabled
CardDatabase::loadCardDatabases start
[CockatriceXml3Parser] Trying to parse:  "D:/Cockatrice/data/cards.xml"
main(): MainWindow constructor finished
main(): ui.show() finished
cache fail for "_trice_card_back_240455"
[CardDatabase] loadCardDatabase(): Path = "D:/Cockatrice/data/cards.xml" Status = 0 Cards = 18621 Sets= 229
[CockatriceXml3Parser] Trying to parse:  "D:/Cockatrice/data/tokens.xml"
[CardDatabase] loadCardDatabase(): Path = "D:/Cockatrice/data/tokens.xml" Status = 0 Cards = 19026 Sets= 230
[CardDatabase] loadCardDatabase(): Path = "D:/Cockatrice/data/spoiler.xml" Status = 4 Cards = 19026 Sets= 230
[CockatriceXml3Parser] Trying to parse:  "D:/Cockatrice/data/customsets/01.BD1.xml"
[CardDatabase] loadCardDatabase(): Path = "D:/Cockatrice/data/customsets/01.BD1.xml" Status = 0 Cards = 19031 Sets= 231
CardDatabase::loadCardDatabases success
Trying to load picture (set:  "BD1"  card:  "累積" )
Picture found on disk (set:  "BD1"  file:  "累積" )
Trying to load picture (set:  "BD1"  card:  "3" )
Picture found on disk (set:  "BD1"  file:  "3" )
Trying to load picture (set:  "BD1"  card:  "2" )
Picture found on disk (set:  "BD1"  file:  "2" )
Trying to load picture (set:  "BD1"  card:  "1" )
Picture found on disk (set:  "BD1"  file:  "1" )
```

  
__________________________________________________________________________________________

  

I put the images with Chinese file name into the pics\CUSTOM, and the xml into the customsets. Then I found Cockatrice just loaded the image of the last card of the xml. I tried to change some of these cards' name into English and the images displayed perfectly. I doubt that Cockatrice cannot load the images with Simplified Chinese name.

> Some tests:

Well, I can't repeat this again. These tests might be wrong.

Update:

The version dab7316 (2017-1-19) don't have this problem. The image of card with Chinese name is perfectly showed. However, there is another problem. The image of token with Chinese name can't be loaded, just like the card's image can't be loaded now.

**Comment by Daenyth** [comment]
can you include the help > debug log output from a session that loads these images?

**Comment by Fifholz** [comment]
updated.

**Comment by Daenyth** [comment]
Can you also upload the customset xml to gist.github.com and link here?

**Comment by Fifholz** [comment]
[https://gist.github.com/Fifholz/08751eda9e32705c1681b7f2692b6b59](url)

**Comment by Daenyth** [comment]
weird... I'm not sure what's wrong there.

Can you also include the not-working cards?

**Comment by Fifholz** [comment]
Not-Working card means? 
The "名字" card don't work on my pc. Its image is belong to "累積".

**Comment by Fifholz** [comment]
simpleName = simpleName.replace("-", " ");  

    **simpleName.remove(QRegExp("[^a-zA-Z0-9 ]"));**  
    simpleName = simpleName.toLower();  
    return simpleName;  

I think here the problem is.

**Comment by Daenyth** [comment]
Does that get used during card image resolution? If so that would do it. I don't think anyone considered non-western writing when doing `simpleName`.

**Comment by ebbit1q** [comment]
Why would we even have simplenames as a separate list next to the original list of cardnames?
This would require some overhauling to fix.
Anyway until then you should be able to add different amounts of spaces to the names to differentiate them.

**Comment by Daenyth** [comment]
> Why would we even have simplenames as a separate list next to the original list of cardnames?


That's why I'm not sure that's what's actually happening. I thought that was only used for `[[cardname]]` etc, not for selecting image on disk. The `[[cardname]]` thing should really only be used to locate the card entry, it shouldn't be going to disk like that...

**Comment by ebbit1q** [comment]
Currently the card image loader uses the simplename, let's see what I can do here.

**Comment by ebbit1q** [comment]
I really hope it wasn't this simple.

**Comment by Fifholz** [comment]
I just changed this line into `simpleName.remove(QRegExp("[^a-zA-Z0-9\u0800-\u9fa5 ]"));` and compiled a worked version for myself. We have used it for a week and it seems no problem now. 
I hope this could be fixed one day.

**Comment by ZeldaZach** [comment]
See #4106 for tracking
