### ISSUE TITLE
Cannot connect to servers and i get timed out 

### ISSUE THREAD

**Issue by AGreenMoose** [Cockatrice/Cockatrice#3361]
<b>System Information:</b>
  Client Version: 2.6.1 (2018-07-17)
Picture found on disk (set:  "C17"  file:  "Blossoming Sands" )
Trying to load picture (set:  "CNS"  card:  "Unquestioned Authority" )
Picture found on disk (set:  "CNS"  file:  "Unquestioned Authority" )
Trying to load picture (set:  "RTR"  card:  "Ethereal Armor" )
Picture found on disk (set:  "RTR"  file:  "Ethereal Armor" )
Trying to load picture (set:  "E01"  card:  "Grand Abolisher" )
Picture found on disk (set:  "E01"  file:  "Grand Abolisher" )
Trying to load picture (set:  "UDS"  card:  "Academy Rector" )
Picture found on disk (set:  "UDS"  file:  "Academy Rector" )
Trying to load picture (set:  "SOI"  card:  "Open the Armory" )
Picture found on disk (set:  "SOI"  file:  "Open the Armory" )
Trying to load picture (set:  "A25"  card:  "Rancor" )
Picture found on disk (set:  "A25"  file:  "Rancor" )
Trying to load picture (set:  "DDU"  card:  "Elvish Mystic" )
Picture found on disk (set:  "DDU"  file:  "Elvish Mystic" )
Trying to load picture (set:  "CMA"  card:  "Flickerform" )
Picture found on disk (set:  "CMA"  file:  "Flickerform" )
Trying to load picture (set:  "M15"  card:  "Heliod's Pilgrim" )
Picture found on disk (set:  "M15"  file:  "Heliod's Pilgrim" )
Trying to load picture (set:  "C16"  card:  "Reliquary Tower" )
Picture found on disk (set:  "C16"  file:  "Reliquary Tower" )
cache fail for "_trice_card_back_226901"
QAbstractSocket::connectToHost() called when already looking up or connecting/connected to "mtg.tetrarch.co"
Error: Spoiler.xml not found or not deleted
QLayout: Attempting to add QLayout "" to ShortcutsTab "shortcutsTab", which already has a layout
Card Database load status:  0
Adding room: ID= 0 name= ""
Server::loginUser: LocalServerInterface(0x15b5a2f2d50) name= "Player 1"
session id: 0
gameEvent: invalid gameId
Server_AbstractUserInterface::playerAddedToGame(): gameId = 1
GameScene::addPlayer name= "Player 1"
cache fail for "_trice_card_back_250255"
QWindowsWindow::setGeometry: Unable to set geometry 1920x1020+0+23 on QWidgetWindow/'MainWindowClassWindow'. Resulting geometry:  1920x1017+0+23 (frame: 8, 31, 8, 8, custom margin: 0, 0, 0, 0, minimum size: 565x1020, maximum size: 16777215x16777215).
cache fail for "_trice_card_back_274306"
cache fail for "_trice_card_back_274303"
Server_AbstractUserInterface::playerRemovedFromGame(): gameId = 1
Server_Game destructor: gameId= 1
Player destructor: "Player 1"
GameScene::removePlayer name= "Player 1"
CardZone destructor:  "deck"
CardZone destructor:  "grave"
CardZone destructor:  "hand"
CardZone destructor:  "rfg"
CardZone destructor:  "sb"
CardZone destructor:  "stack"
CardZone destructor:  "table"
Server::removeClient: name= "Player 1"
closed session id: 0
Server::removeClient: removed 0x15b5a2f2d50 ; 0 clients;  0 users left
Server_Room destructor
cache fail for "_trice_card_back_226904"
getPort() index =  3  port.val =  "4747"
getPlayerName() index =  3  name.val =  "REEEEE"
link path774 hasn't been detected!
link path774 hasn't been detected!
link path774 hasn't been detected!
link lion hasn't been detected!
link path1214 hasn't been detected!
link path1563 hasn't been detected!
link path1563 hasn't been detected!
Trying to load picture (set:  "C17"  card:  "Blossoming Sands" )
Picture found on disk (set:  "C17"  file:  "Blossoming Sands" )
Trying to load picture (set:  "IMA"  card:  "Boros Garrison" )
Picture found on disk (set:  "IMA"  file:  "Boros Garrison" )
Trying to load picture (set:  "BFZ"  card:  "Canopy Vista" )
Picture found on disk (set:  "BFZ"  file:  "Canopy Vista" )
Trying to load picture (set:  "BFZ"  card:  "Cinder Glade" )
Picture found on disk (set:  "BFZ"  file:  "Cinder Glade" )
Trying to load picture (set:  "C17"  card:  "Command Tower" )
Picture found on disk (set:  "C17"  file:  "Command Tower" )
Trying to load picture (set:  "C13"  card:  "Contested Cliffs" )
Picture found on disk (set:  "C13"  file:  "Contested Cliffs" )
Trying to load picture (set:  "RIX"  card:  "Evolving Wilds" )
Picture found on disk (set:  "RIX"  file:  "Evolving Wilds" )
Trying to load picture (set:  "DOM"  card:  "Forest" )
Picture found on disk (set:  "DOM"  file:  "Forest" )
Trying to load picture (set:  "IMA"  card:  "Gruul Turf" )
Picture found on disk (set:  "IMA"  file:  "Gruul Turf" )
Trying to load picture (set:  "E02"  card:  "Jungle Shrine" )
Picture found on disk (set:  "E02"  file:  "Jungle Shrine" )
Trying to load picture (set:  "V13"  card:  "Kessig Wolf Run" )
Picture found on disk (set:  "V13"  file:  "Kessig Wolf Run" )
Trying to load picture (set:  "DOM"  card:  "Mountain" )
Picture found on disk (set:  "DOM"  file:  "Mountain" )
Trying to load picture (set:  "C13"  card:  "Naya Panorama" )
Picture found on disk (set:  "C13"  file:  "Naya Panorama" )
Trying to load picture (set:  "DOM"  card:  "Plains" )
Picture found on disk (set:  "DOM"  file:  "Plains" )
Trying to load picture (set:  "CNS"  card:  "Reflecting Pool" )
Picture found on disk (set:  "CNS"  file:  "Reflecting Pool" )
Trying to load picture (set:  "EXP"  card:  "Windswept Heath" )
Picture found on disk (set:  "EXP"  file:  "Windswept Heath" )
Trying to load picture (set:  "EXP"  card:  "Wooded Foothills" )
Picture found on disk (set:  "EXP"  file:  "Wooded Foothills" )
Trying to load picture (set:  "C17"  card:  "Wind-Scarred Crag" )
Picture found on disk (set:  "C17"  file:  "Wind-Scarred Crag" )
Trying to load picture (set:  "C17"  card:  "Terramorphic Expanse" )
Picture found on disk (set:  "C17"  file:  "Terramorphic Expanse" )
Trying to load picture (set:  "THS"  card:  "Temple of Triumph" )
Picture found on disk (set:  "THS"  file:  "Temple of Triumph" )
Trying to load picture (set:  "C17"  card:  "Temple of the False God" )
Picture found on disk (set:  "C17"  file:  "Temple of the False God" )
Trying to load picture (set:  "BNG"  card:  "Temple of Plenty" )
Picture found on disk (set:  "BNG"  file:  "Temple of Plenty" )
Trying to load picture (set:  "THS"  card:  "Temple of Abandon" )
Picture found on disk (set:  "THS"  file:  "Temple of Abandon" )
Trying to load picture (set:  "EXP"  card:  "Temple Garden" )
Picture found on disk (set:  "EXP"  file:  "Temple Garden" )
Trying to load picture (set:  "XLN"  card:  "Sunpetal Grove" )
Picture found on disk (set:  "XLN"  file:  "Sunpetal Grove" )
Trying to load picture (set:  "A25"  card:  "Cultivate" )
Picture found on disk (set:  "A25"  file:  "Cultivate" )
Trying to load picture (set:  "SOI"  card:  "Open the Armory" )
Picture found on disk (set:  "SOI"  file:  "Open the Armory" )
Trying to load picture (set:  "PLC"  card:  "Retether" )
Picture found on disk (set:  "PLC"  file:  "Retether" )
Trying to load picture (set:  "TPR"  card:  "Winds of Rath" )
Picture found on disk (set:  "TPR"  file:  "Winds of Rath" )
Trying to load picture (set:  "PCA"  card:  "Three Dreams" )
Picture found on disk (set:  "PCA"  file:  "Three Dreams" )
Trying to load picture (set:  "C17"  card:  "Sol Ring" )
Picture found on disk (set:  "C17"  file:  "Sol Ring" )
Trying to load picture (set:  "C16"  card:  "Chromatic Lantern" )
Picture found on disk (set:  "C16"  file:  "Chromatic Lantern" )
Trying to load picture (set:  "C17"  card:  "Fellwar Stone" )
Picture found on disk (set:  "C17"  file:  "Fellwar Stone" )

  
__________________________________________________________________________________________

  i go to login to a server and i get timed out from connecting

**Comment by tooomm** [comment]
Are you behind a firewall or trying to connect from a school/university/work/... network?

**Comment by ctrlaltca** [comment]
This is definitely a network problem, or the connection you are using is explicitly blocking games and other unknown protocols. Please reopen if this is still an issue

**Comment by AGreenMoose** [comment]
who do i reopen this
