### ISSUE TITLE
Players on Cockatrice side by side not across from each other.

### ISSUE THREAD

**Issue by IzzetFanatic** [Cockatrice/Cockatrice#3365]
<b>System Information:</b>
 
 Link to image of layout problem: https://imgur.com/a/h1kkrhg
I can't find any way to adjust appearance settings to change the orientation to one that reflects how a game would be played, across from one another as opposed to sitting next to eachother. Changing the layout of horizontal vs vertical hands doesnt work either.
__________________________________________________________________________________________

**Comment by Daenyth** [comment]
Can you add any more detail? I don't understand what you're asking

**Comment by IzzetFanatic** [comment]
Sorry I left a link to a screenshot and left a bunch of info including bug
logs. Will try putting it on again. Sorry it didn't show up.

**Comment by IzzetFanatic** [comment]
Ok I adjusted it

**Comment by skwerlman** [comment]
what do you have for the setting "minimum player count for multi-column layout" under appearance?

**Comment by IzzetFanatic** [comment]
Set to 2

**Comment by IzzetFanatic** [comment]
will try 1

**Comment by skwerlman** [comment]
try setting it higher; thats the number of players in a game needed to switch to multi-column view (side-by-side) instead of single-column view (all players above one another)

the default setting is 5, although i personally have mine set to 4 because i play a lot of edh

**Comment by IzzetFanatic** [comment]
thanks thats it.
