### ISSUE TITLE
look into using readthedocs over github wiki

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#3366]
Maybe https://readthedocs.org/ is the better alternative over GitHub Wiki.

Example: http://docs.godotengine.org/en/latest/

**Comment by Daenyth** [comment]
What would it do for us that GH wiki doesn't do, or what problem with GH would be solved?

**Comment by tooomm** [comment]
I put this up for discussion here because it seems to be more flexible and better looking.

It also supports translations and uses a repo behind, so changes are more visible because a PR is created. Therefore updates can get talked about before they are approved.
That way it could be a compromise between the "free-for-all" wiki and the "restrict-to-org-members" wiki.

Never used it though and one need to look into the details.

If we need that? I don't know...
