### ISSUE TITLE
Update strategy: How to get through to users

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#3369]
We always keep talking about updating.
Why people don't do it, why it's difficult for users to understand the concept of databases and the app itself... and so on and so forth.
It's an always recurring topic and there is no real solution yet. The situation improved a lot with the in-client software updater, but there are still many users which doesn't know about it. Or forget to use it. :)
Also, in some cases stuff still brakes because the card database gets updated in order to deal with dfc's or the parsing got tweaked... and without a matching Cockatrice software update some card issues appeared as a result.

~~That's why I came up with the idea to make `Oracle` a central updater and our place for all kind of update checks and update processes.
People are used to run Oracle because of the card database updates they always (have to) do, they are not used to run the client updater manually from a totally different location in the app.
This could be combined so that Oracle also does some software update checks and recommends an update if available (not force).~~
In general a lot more people would use more recent versions because they simply know about them and don't have to actively search for one in a separate step.

<br>

Alternative ideas for update improvements:
 - Same as with spoiler, include a way for automatic update checks:
Instead calling an URL, downloading data and compare them to a local file (spoiler).
Cockatrice can send a API request to GitHub and check the running version against the current release. If newer versions are available, show os notification and open in-client updater when clicking on it.

Maybe that's even the better way to go... an option in settings and automatic version checks on startup. 👍

**Comment by Daenyth** [comment]
I'm 👎 on oracle being a central updater - it should remain magic-specific.

Why not automatically check for updates once on app launch? I think that's pretty harmless

**Comment by ZeldaZach** [comment]
I agree with Gavin. We can do auto update pop ups

**Comment by tooomm** [comment]
@Daenyth 

>(...) oracle (...) should remain magic-specific.

How do you want to be/get game agnostic then?
Or want to handle support for different games better if not through Oracle itself?

<br>

>Why not automatically check for updates once on app launch? 

That's basically my second suggestion from above: 😉 
>>Alternative ideas for update improvements:
>>
>>Same as with spoiler, include a way for automatic update checks:
Instead calling an URL, downloading data and compare them to a local file (spoiler).
Cockatrice can send a API request to GitHub and check the running version against the current release. If newer versions are available, show os notification and open in-client updater when clicking on it.
>>
>>Maybe that's even the better way to go... an option in settings and automatic version checks on startup. 👍

**Comment by Daenyth** [comment]
Separate games can have separate updaters.

That doesn't mean Oracle needs to be its own standalone app forever - I think that design isn't super for us.

**Comment by tooomm** [comment]
Kk, got it!

**Comment by ZeldaZach** [comment]
Just have the Help > Check for Updates run on startup. Not a hard impl at all.

**Comment by Fenrirthviti** [comment]
For OBS, we check for updates silently in the background with every launch. There is a option in the first page in `General` settings to disable this update check if it is not desired, and the `Help -> Check for updates` still functions properly. However, we do also have our own updater (on Windows).

IMO, if the check is quick and painless, there is no real reason to need to inform the user every time. Perhaps a one-time message when updating from a version without automatic updates to a version with explaining that automatic updates can be enabled in `Settings`, but leaving it off to not change expectations. New installations would have this option enabled by default.

**Comment by RickyRister** [comment]
Added checking for updates on startup on #5359
