### ISSUE TITLE
Can't use directional keys/mouse to select/add cards in Deck Editor

### ISSUE THREAD

**Issue by OhNoTypo** [Cockatrice/Cockatrice#3371]
<b>System Information:</b>
  

  
__________________________________________________________________________________________

**Comment by ZeldaZach** [comment]
Use “shift” plus the keys. It was changed in latest release

**Comment by tooomm** [comment]
If that's not doing the trick and you need further assistance, reopen the issue please and let us know! @OhNoTypo
