### ISSUE TITLE
Cockatrice wont open after closing.

### ISSUE THREAD

**Issue by JLphoton** [Cockatrice/Cockatrice#3374]
<b>System Information:</b>
  

   I am using the Windows 7+ version of the program and i am running it on Windows 10.
__________________________________________________________________________________________

  Whenever i try to open cockatrice i get the error message, "This application has failed to start because it could not find or load the Qt platform plugin 'windows' in ''. Reinstalling the application may fix the problem." . Interestingly enough if i reinstall the program i can open it, but i can not open it again if i close it for whatever reason.

**Comment by Daenyth** [comment]
When you open it after reinstalling, are you launching it from the installer?

I wonder if you're actually launching a bad version from your menu and a good version from the installer.

**Comment by JLphoton** [comment]
I launch it from the installer after reinstalling. It is the only way I can currently open the program.

**Comment by tooomm** [comment]
Can you make sure all former instances of old Cockatrice installations or portable versions are gone?
Check `C:\Program Files` **and** `C:\Program Files (x86)`, please. Or any other location in case you altered the default installation folder and properly uninstall them.

Then try to install **v2.6.1** again.

**Comment by ctrlaltca** [comment]
Closing. Feel free to reopen if you still experience this problem and are willing to share more information on it.
