### ISSUE TITLE
Appveyor: 32bit build fails

### ISSUE THREAD

**Issue by ctrlaltca** [Cockatrice/Cockatrice#3378]
Error signature:
```
c:\qt\5.9\msvc2015\include\qtcore\qalgorithms.h(847): error C3615: constexpr function 'qCountLeadingZeroBits' cannot result in a constant expression [C:\projects\cockatrice\build\oracle\oracle.vcxproj]
  c:\qt\5.9\msvc2015\include\qtcore\qalgorithms.h(858): note: failure was caused by call of undefined function or one not declared 'constexpr'
  c:\qt\5.9\msvc2015\include\qtcore\qalgorithms.h(858): note: see usage of 'qPopulationCount'
```

This is due to the recent update of Visual Studio 2017 15.8.
Qt already knows the problem: https://bugreports.qt.io/browse/QTBUG-67259, a patch in Qt is needed to fix it: https://codereview.qt-project.org/#/c/236948/
We should hope in a quick release of the patched Qt version 5.9.7.

**Comment by tooomm** [comment]
Once https://github.com/appveyor/ci/issues/2645 is deployed, this should finally be solved.

**Comment by tooomm** [comment]
@ctrlaltca with the new update at appveyor Qt might be fixed, but we are seeing different errors now: https://ci.appveyor.com/project/Daenyth/cockatrice-8k7y5/builds/20209818

**Comment by ctrlaltca** [comment]
The new errors are due to some other modifications that Apvveyor made to the build images.
I've already reported these problems [here](https://github.com/appveyor/ci/issues/2737), and [here](https://github.com/Cockatrice/Cockatrice/pull/3434)'s a PR to workaround them and restore wroking builds.

**Comment by tooomm** [comment]
Thank for taking a look! Also for the upstream report and workaround PR. 👍
