### ISSUE TITLE
Peek what users are in the room

### ISSUE THREAD

**Issue by TemporalMadness** [Cockatrice/Cockatrice#3379]
Client Version: 2.6.1 (2018-07-17)
__________________________________________________________________________________________

Can we get a tool that tells us all users in a room before we click the room?  Would be helpful for those who actively use the ignore list and it would allow them to not be rude by entering the room and then just leaving for no reason and when asked why they left drama starts. I think this feature would help people not fight so much.

**Comment by Daenyth** [comment]
Related to #3344 perhaps and #1950, just in the other direction.

**Comment by ZeldaZach** [comment]
You can always join as a spectator first, if you need.
