### ISSUE TITLE
"Play the top card [of library] face down." keyboard command

### ISSUE THREAD

**Issue by TyrantofDiscord** [Cockatrice/Cockatrice#3381]
______________________________________________________________________________________

 It would be really useful if there were a keyboard command for "Play the top card face down
" to make playing cards like Necropotence or Bomat Courier easier and cleaner. I and many people I play with have wanted this feature in some form. I'm not sure what the command would be exactly, anything would do really. Needing to right click the library and then hit "Play the top card face down." several times, often more than once a turn, is very tedious.
![image](https://user-images.githubusercontent.com/42899665/44950167-0ff11380-ae0f-11e8-8140-8b3a2bf0079d.png)

**Comment by leestran1995** [comment]
You can shift-click and drag from the library to play the card face down on the battlefield from your library

**Comment by Daenyth** [comment]
That's true, but we should add a menu entry.
