### ISSUE TITLE
Account registration token entry

### ISSUE THREAD

**Issue by Baljortar** [Cockatrice/Cockatrice#3382]
<b>System Information:</b>
  

  
__________________________________________________________________________________________

  <Hello. I just registered into Cockatrice and the token key took a while until it got into my email. So i wanted to register my new account but I cannot see any place to put the token key and also when I connect, the account seems like it is an unregistered one.
I want to know where do I have to put the token key so I can successfully register my account.>

**Comment by tooomm** [comment]
I saw this question being asked before in chats... Maybe we can make this clearer?

(I can't remember how to solve things once people close the registering dialog which asks for the token in the signup process. Mails are mostly delayed for a bit and users may not keep the window/app open all the time.)
