### ISSUE TITLE
fail to uninstall client

### ISSUE THREAD

**Issue by angusju** [Cockatrice/Cockatrice#3383]
Client Version: 2.6.1 (2018-07-17)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.9.5
System Locale: fr_FR

__________________________________________________________________________________________

 Hello

I litterally can't uninstall Cockatrice from my computer. 
With the unsinstall.exe it says that I don't have enough rights and to contact my admin, but in Admin mode it says exactly the same thing. Via the windows uninstaller it says the same, or Fail to start.

**Comment by ZeldaZach** [comment]
Did you try restarting your system, then attempting to un-install again? I've seen that bug appear with several windows apps and I think it's an OS problem

**Comment by tooomm** [comment]
Did you find a workaround for this problem, or does it work in the meantime with newer versions?

**Comment by ctrlaltca** [comment]
Closing. Please reopen if you're willing to share more information on the problem, eg. the specific errors.
