### ISSUE TITLE
Insecure Random Number Generation

### ISSUE THREAD

**Issue by altf4** [Cockatrice/Cockatrice#3385]
Hey,

I see that Cockatrice uses the Mersenne Twister to do random number generation for things like deck shuffling. (sfmt_genrand_uint64) This is not a secure PRNG when used in an adversarial context, and the output of the random number generator can be predicted by a clever attacker. 

I even made a little tool that can be used to break Mersenne Twister seeds / internal states. (https://github.com/altf4/untwister) Once broken, the attacker can 100% predict every past and future output from the RNG for that server. A cheater could abuse this by knowing exactly how a deck will be shuffled before it is done and invisibly stack their deck. 

Instead, I'd recommend using the operating system's native source of secure random numbers. This is supported across all OS's, though in different forms. (/dev/urandom, CryptGenRandom, etc...)

**Comment by Daenyth** [comment]
I'd be very surprised if this can actually be abused in practice. Even if you can predict the sequence of number generation, the random seed is IIRC shared among all threads (correct me if I'm wrong), meaning that every single player in every game can mutate it - in practice this should be totally unpredictable even if you knew the sequence.

**Comment by altf4** [comment]
True, but the attacker can start a second game by their self and launch a timing attack. In this second dummy game, the cheater can ask the server for a bunch of random numbers quickly in a row and then immediately perform the shuffle in the target game after. This way, the attacker can essentially calibrate the random numbers and more reliably guarantee that the shuffle will occur according to plan.

So suppose the attacker is expecting the PRNG to output the following sequence: (single digit numbers for simplicity)

`1, 3, 2, 5, 7, 8, 1, 9, 3`

The attacker could rapidly request 5 random numbers, suppose the following sequence is observed:

`1, 2, 5, 7, 1`

This sort of behavior would occur when other users are around on the same server, "eating" numbers from the PNRG sequence on us. (the 3 and the 8) The attacker would then expect the next number in the sequence to be either 9 or 3, depending on if another number gets "eaten" by another user on the server. The faster that an attacker is able to send these packets makes the likelihood of someone else eating a number smaller, and thus the attack more reliable.

**Comment by ctrlaltca** [comment]
The RNG is used for these methods:
```
Server_CardZone::shuffle()
Server_Player::cmdRollDie()
Server_Player::cmdRevealCards()
PasswordHasher::generateRandomSalt()
```
While i see a theoretical way of using these methods to create a replay attack, i hope no one would really put such an effort just to win a table card game.
Anyway, just to support your point, have a look at how the prng is seeded: https://github.com/Cockatrice/Cockatrice/blob/master/common/rng_sfmt.cpp#L16

So, what should we use instead? Qt ships with a [QRandomGenerator](https://doc.qt.io/archives/qt-5.10/qrandomgenerator.html) class since 5.10, that is basically a mt19937 seeded with a cpu or os-specific ransom source (rdrand, /dev/urandom, getentropy, etc..).
Imho we can't require 5.10 right now, as it would cut out most linux distros.
Alternatives? Find c++ library implementing a cross-os random source and use it, or reinvent the wheel and write our library (please, no).

**Comment by altf4** [comment]
It's not a matter of seeding, unfortunately. The Mersenne Twister itself as an algorithm leaks information about it's internal state every time it produces a random number. A clever attacker can use that information to derive the internal state. I agree with the sentiment about cheaters, but you'd be surprised, and this attack isn't actually as difficult as it may look at first.

Also unfortunately, the literature around this subject is often misleading and/or completely wrong. What you need is a cryptographically secure pseudorandom number generator (CSPRNG), which Qt does seem to provide. (Built-in CSPRNGs are a staple of modern programming languages, but C++ has suitable libraries)

The "system" generator in Qt looks like it's the right thing: https://doc.qt.io/qt-5/qrandomgenerator.html#system

But then it has an utterly nonsensical and completely wrong warning to follow that up:

> They are also possibly backed by a true hardware random number generator. For that reason, the QRandomGenerator returned by this function should not be used for bulk data generation. Instead, use it to seed QRandomGenerator or a random engine from the <random> header.

/dev/urandom cannot run out of entropy, that's not how that works. And simply seeding another PRNG or using <random> is just using a Mersenne Twister all over again, undermining the whole reason you'd use that function in the first place. Definitely don't follow that advice. 

Alternatively, there are other libraries made specifically for this purpose, in particular I'd recommend libsodium:

https://download.libsodium.org/doc/generating_random_data

**Comment by altf4** [comment]
It will surely be worse, objectively. But I don't know offhand how much worse. Almost surely not meaningfully worse. Cockatrice doesn't do a ton of random number generation. Using a PRNG is at worst a syscall worth of overhead. And a single syscall per user-request is not going to break the CPU.

**Comment by ZeldaZach** [comment]
Based on the comments, I'm not too concerned with how things are currently done. If I'm blatantly wrong, please let me know.
