### ISSUE TITLE
Playing replay file displays nothing

### ISSUE THREAD

**Issue by Kirtar89** [Cockatrice/Cockatrice#3389]
Client Version: 2.6.1 (2018-07-17)
Client Operating System: Windows 7 SP 1 (6.1)
Build Architecture: 64-bit
Qt Version: 5.9.5
System Locale: it_IT
______________________________________________________________________________________
Hello. 
My problem is this, I can't see the replay

**Comment by tooomm** [comment]
When does it "error"? Can you provide us the steps you perform?
Is there any kind of message?
What does the debug log say in the help menu?

**Comment by Kirtar89** [comment]
I choose the replay and there isn't nothing in the menu, there isn't a message of an error
![img_20180909_105523](https://user-images.githubusercontent.com/42557901/45262925-9ebdeb80-b420-11e8-8184-d2bf3965af34.jpg)

**Comment by Kirtar89** [comment]
Theme changed: "Default"
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
Language changed: "it"
main(): starting main program
main(): MainWindow constructor finished
CardDatabase::loadCardDatabases start
[CockatriceXml3Parser] Trying to parse:  "C:/Users/Carlo/AppData/Local/Cockatrice/Cockatrice/cards.xml"
main(): ui.show() finished
Attempting auto-connect...
Spoiler Service Online
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Carlo/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 18681 Sets= 230
[CockatriceXml3Parser] Trying to parse:  "C:/Users/Carlo/AppData/Local/Cockatrice/Cockatrice/tokens.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Carlo/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 19086 Sets= 230
[CockatriceXml3Parser] Trying to parse:  "C:/Users/Carlo/AppData/Local/Cockatrice/Cockatrice/spoiler.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Carlo/AppData/Local/Cockatrice/Cockatrice/spoiler.xml" Status = 0 Cards = 19119 Sets= 231
[CockatriceXml3Parser] Trying to parse:  "C:/Users/Carlo/AppData/Local/Cockatrice/Cockatrice/customsets/TK.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Carlo/AppData/Local/Cockatrice/Cockatrice/customsets/TK.xml" Status = 0 Cards = 19119 Sets= 231
CardDatabase::loadCardDatabases success
Data Hash = "\xA0[\xFC\xB7v\x14\xF2'\xD1\"Y:\xF8\x8B\xF7\xC2"
File Hash = "\xA0[\xFC\xB7v\x14\xF2'\xD1\"Y:\xF8\x8B\xF7\xC2"
Spoilers Up to Date

**Comment by Kirtar89** [comment]
Theme changed: "Default"
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
Language changed: "it"
main(): starting main program
main(): MainWindow constructor finished
CardDatabase::loadCardDatabases start
[CockatriceXml3Parser] Trying to parse:  "C:/Users/Carlo/AppData/Local/Cockatrice/Cockatrice/cards.xml"
main(): ui.show() finished
Attempting auto-connect...
Spoiler Service Online
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Carlo/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 18681 Sets= 230
[CockatriceXml3Parser] Trying to parse:  "C:/Users/Carlo/AppData/Local/Cockatrice/Cockatrice/tokens.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Carlo/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 19086 Sets= 230
[CockatriceXml3Parser] Trying to parse:  "C:/Users/Carlo/AppData/Local/Cockatrice/Cockatrice/spoiler.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Carlo/AppData/Local/Cockatrice/Cockatrice/spoiler.xml" Status = 0 Cards = 19119 Sets= 231
[CockatriceXml3Parser] Trying to parse:  "C:/Users/Carlo/AppData/Local/Cockatrice/Cockatrice/customsets/TK.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Carlo/AppData/Local/Cockatrice/Cockatrice/customsets/TK.xml" Status = 0 Cards = 19119 Sets= 231
CardDatabase::loadCardDatabases success
Data Hash = "\xA0[\xFC\xB7v\x14\xF2'\xD1\"Y:\xF8\x8B\xF7\xC2"
File Hash = "\xA0[\xFC\xB7v\x14\xF2'\xD1\"Y:\xF8\x8B\xF7\xC2"
Spoilers Up to Date
link path1214 hasn't been detected!
link path1563 hasn't been detected!
link path1563 hasn't been detected!

**Comment by Daenyth** [comment]
Can you please upload the replay file and add a link to it here
