### ISSUE TITLE
Please have the spoilers enabled by default

### ISSUE THREAD

**Issue by Qriist** [Cockatrice/Cockatrice#3391]
Title really says it all. Spoilers enabled by default would ensure that new people cease asking the same question regarding spoilers. 

Thanks!

**Comment by tooomm** [comment]
I assume if we do this we get the same request the other way around.
There are a lot of people who not only use Cockatrice to brew and don't want updates each and every day before a set release. That can easily be annoying if you're not interested in upcoming card information.

**Comment by Qriist** [comment]
Considering the spoiler update process is virtually invisible, I don't see that being an issue. Perhaps a check box on install?

**Comment by ZeldaZach** [comment]
We've decided against this. Spoilers aren't stable, and are an advanced feature. Instead, we're looking at having databases download automatically in the future. #4109
