### ISSUE TITLE
Wiki: Document project setup with QtCreator

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#3393]
Should cover things like:
- import the project
- get it to compile
- debugging etc.

CC: @berserkingyadis

**Comment by berserkingyadis** [comment]
For Windows and Linux both? I was under the impression it needed to be done for Linux.

**Comment by ctrlaltca** [comment]
QtCreator is bale to open and use cockatrice's cmake problem without problem.
I guess the other points are more related to QtCreator's documentation than to cockatrice's.
Anyway, why not?

**Comment by tooomm** [comment]
I just pinned it here because I thought it might get lost in Gitter.
I also only assumed we are talking about windows because @Daenyth mentioned that only Visual Studio is in our wiki yet.

**Comment by Daenyth** [comment]
QtC is cross platform

**Comment by ctrlaltca** [comment]
Reading again at this issue, I think that it would be overkill for us trying to keep up to date a guide on how to use an external software that we have no control upon.
Referring to the original [QtCreator documentation](https://doc.qt.io/qtcreator/) would still be needed for a new developer to get his hands dirty on QtCreator.
