### ISSUE TITLE
Disable delete/clear filter buttons as long as no filters are created

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#3394]
**System Information:**
Client Version: 2.6.0-custom(168cc49) (2018-07-20)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.9.5
System Locale: de_DE

---

Until one creates a card filter to alter the displayed cards / search results in the deck editor, the
`Delete selected` and `Clear all filters` buttons and menu entries (Deck Editor) should be disabled/greyed out.

Similar to #3339.

**Comment by ZeldaZach** [comment]
Solved.
