### ISSUE TITLE
Treat different apostrophes similarly ' ’

### ISSUE THREAD

**Issue by ancestral** [Cockatrice/Cockatrice#3395]
When searching for cards, some resources treat card titles with curly quotes `’` which can’t be searched with straight quotes `'`.

Could we implement support in the search bars for straight and curly quotes interchangeably? i.e. searching for `'` or `’` returns both.

**Comment by Daenyth** [comment]
This should be easy to do

**Comment by tooomm** [comment]
Which do we use / convert to btw? I hope we only have one... :)

**Comment by Daenyth** [comment]
Convert everything to ASCII apostrophe
