### ISSUE TITLE
Info won't save to server list

### ISSUE THREAD

**Issue by JineteDV** [Cockatrice/Cockatrice#3397]
Had 2 Windows users today complain about when they click on new host and name a new connection, it doesn't save to the server list.

**Comment by Daenyth** [comment]
I believe the issue is that if you already have a server in the list with the same address, we don't save it.

**Comment by tooomm** [comment]
Which is probably ok, just that the user doesn't know what's up.

**Comment by JineteDV** [comment]
Though it does save on OSX (allowing me to have a duplicate of the RR connection with a different name).

**Comment by tooomm** [comment]
One of the users reported yesterday to use in Gitter and GitHub (https://github.com/Cockatrice/Cockatrice/issues/3398).
He then later said that everything works suddenly again, so I assume there was some other problem.

**Comment by Daenyth** [comment]
I think he just selected RR as his autoconnect server and then that
satisfied him
