### ISSUE TITLE
Sprouting Renewal image is french (or something)

### ISSUE THREAD

**Issue by aculver** [Cockatrice/Cockatrice#3400]
<b>System Information:</b>
  

  
__________________________________________________________________________________________

**Comment by Daenyth** [comment]
This might just be a gatherer bug. @ZeldaZach ?

**Comment by aculver** [comment]
The image was English a couple days ago.

**Comment by skwerlman** [comment]
this might be a dupe of #3263 since it got reprinted in GRN

**Comment by Daenyth** [comment]
Specifically the debug output from the session where you downloaded the image

**Comment by ctrlaltca** [comment]
Looks like it's working correctly now.
