### ISSUE TITLE
Activiating account

### ISSUE THREAD

**Issue by kevponce4** [Cockatrice/Cockatrice#3405]
So I waiting to activate my account and thought I entered something wrong on my email since it was taking a long time to receive it and so I exited off the verification button then a few minutes later it sent me the code and now I can't verify my account is there any way that I might still be able to verify the account?

**Comment by ZeldaZach** [comment]
Please reach out to a moderator or admin on the specific server. This is not a development issue. You can reach out (probably) via https://cockatrice.us

**Comment by tooomm** [comment]
The complete list of public servers we know of can be found [here](https://github.com/Cockatrice/Cockatrice/wiki/Public-Servers).
