### ISSUE TITLE
Can not close

### ISSUE THREAD

**Issue by Optissimum** [Cockatrice/Cockatrice#3408]
<b>System Information:</b>
  
Client Version: 2.6.1 (2018-07-17)
Client Operating System: Ubuntu 18.04.1 LTS
Build Architecture: 64-bit
Qt Version: 5.5.1
System Locale: en_US
Theme changed: "Clean"
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
Language changed: ""
main(): starting main program
Spoilers Disabled
CardDatabase::loadCardDatabases start
[CockatriceXml3Parser] Trying to parse:  "/home/sebastian/.local/share/Cockatrice/Cockatrice/cards.xml"
main(): MainWindow constructor finished
main(): ui.show() finished
cache fail for "_trice_card_back_226893"
Attempting auto-connect...
cache fail for "_trice_card_back_226896"
[CardDatabase] loadCardDatabase(): Path = "/home/sebastian/.local/share/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 18925 Sets= 231
[CockatriceXml3Parser] Trying to parse:  "/home/sebastian/.local/share/Cockatrice/Cockatrice/tokens.xml"
[CardDatabase] loadCardDatabase(): Path = "/home/sebastian/.local/share/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 19336 Sets= 231
[CardDatabase] loadCardDatabase(): Path = "/home/sebastian/.local/share/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 19336 Sets= 231
CardDatabase::loadCardDatabases success

  
__________________________________________________________________________________________

  
Cockatrice will not close when exiting, choosing _File_>_Exit_, or choosing the _Exit_ option in the notification bar. I have been able to reproduce this on 2 separate PCs (both are running Kubuntu with `plasmashell 5.12.6`. It will close the window, but will not end the process, and does not add anything to the debug log either.

**Comment by Daenyth** [comment]
This must be related to something we added recently, this used to work

**Comment by Optissimum** [comment]
Just built the latest version, no longer has this problem.

**Comment by tooomm** [comment]
Do you mean master?

**Comment by Daenyth** [comment]
Almost certainly your problem was fixed by #3329
