### ISSUE TITLE
Mining Replays

### ISSUE THREAD

**Issue by ssnow5516** [Cockatrice/Cockatrice#3411]
<b>System Information:</b>
  

  
__________________________________________________________________________________________

 Just wondering if anyone has given thought or considered developing an API or package that allows someone to mine cockatrice replays. This would be beneficial for knowledgeable content creators using data to guide gameplay guides, pilot guides, deck construction guides etc. 

An example, mining 1000 replays for non-land cards played could identify the top 20 cards played in winning decks. And cross-checking these cards against a decklist database could then produce a list of cards that appear frequently in winning decks but aren't as highly played overall. 

If this isn't a thing, I would like to look into this. I am decent at writing Python and Java. Anyone have any pointers to get me started?

**Comment by ZeldaZach** [comment]
I like the idea you have, snow! Would be really cool to get some more aggregate data from the program. 

Our program is written in C++, so I'm not sure if anything in PY3/J8 could be incorporated in the program, but maybe you can decipher the output replays into a more machine-readable format. Let me know if you come up with something or have any breakthroughs!

**Comment by ctrlaltca** [comment]
Hi, a cockatrice replay is a file containing a [protobuf](https://github.com/protocolbuffers/protobuf) data structure that contains all the "events" sent by players to the game.
The data structure is defined in [these definition files](https://github.com/Cockatrice/Cockatrice/tree/master/common/pb), `game_replay.proto` is probably the one you want to start looking at.

If you decide on using python, in the servatrice's [scripts](https://github.com/Cockatrice/Cockatrice/tree/master/servatrice/scripts) directory you can find a `mk_pypb.sh` script used to compile the "proto" definition files into python-compatible classes, and an example python script `register.py
` that is using these classes.

**Comment by berserkingyadis** [comment]
Ive done this for Warcraft 3 replay files to determine unusual heroes or towerrushes, its interesting work!

**Comment by Daenyth** [comment]
The replay files are binary dumps of protobuf data. Any language with protobuf bindings can be used

**Comment by ZeldaZach** [comment]
This feels like an external issue, and no something we're doing.
