### ISSUE TITLE
Archenemy Scheme Decks

### ISSUE THREAD

**Issue by wakarimasensei** [Cockatrice/Cockatrice#3416]
Is there any way to easily use extra decks, and if not, is there a plan to implement it? An extra deck zone would be difficult to implement, but is there any possibility of being able to shuffle cards on the battlefield so that an extra deck could be kept in the sideboard and brought in? Or is there another way (potential or currently-available) that a Scheme deck or the like could be used?

Thank you in advance for the help.

**Comment by Daenyth** [comment]
Related #478

Easily: no. You have a workaround where you connect on an extra account, and that player in the game is responsible for handing out cards from the shared deck.

Plan: sort of. We've sketched out a design but no work has happened toward implementing the required card engine changes. Unfortunately it's kind of a massive one.

Shuffling cards on the field - not really possible right now :(

Unfortunately this just stinks at the moment.

**Comment by ebbit1q** [comment]
this should be addressed by this instead https://github.com/Cockatrice/Cockatrice/issues/1740
