### ISSUE TITLE
REGISTER MY ACCOUNT, GOT ACTIVATION KEY LATER AND I DONT KNOW WHERE TO ENTER IT TO REGISTER

### ISSUE THREAD

**Issue by DianaCastilloP** [Cockatrice/Cockatrice#3418]
<b>System Information:</b>
   Client Version: 2.6.1 (2018-07-17)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.9.5
System Locale: en_US
---------------------------------------------------------------------------
Theme changed: "Default"
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
Language changed: ""
main(): starting main program
Spoilers Disabled
CardDatabase::loadCardDatabases start
main(): MainWindow constructor finished
main(): ui.show() finished
[CockatriceXml3Parser] Trying to parse:  "C:/Users/Diana Castillo/AppData/Local/Cockatrice/Cockatrice/cards.xml"
cache fail for "_trice_card_back_226455"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Diana Castillo/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 18925 Sets= 231
[CockatriceXml3Parser] Trying to parse:  "C:/Users/Diana Castillo/AppData/Local/Cockatrice/Cockatrice/tokens.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Diana Castillo/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 19335 Sets= 231
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Diana Castillo/AppData/Local/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 19335 Sets= 231
CardDatabase::loadCardDatabases success
getPort() index =  1  port.val =  "4747"
getPlayerName() index =  1  name.val =  "DianaC"
link path774 hasn't been detected!
link path774 hasn't been detected!
link path774 hasn't been detected!
link lion hasn't been detected!
link path1214 hasn't been detected!
link path1563 hasn't been detected!
link path1563 hasn't been detected!
getPort() index =  1  port.val =  "4747"
getPlayerName() index =  1  name.val =  "DianaC"
Searching for updates on the channel:  "https://api.github.com/repos/Cockatrice/Cockatrice/releases/latest"
Current hash= "aa30871" update hash= ""
Got reply from release server, size= 11590 name= "Cockatrice 2.6.1: Father of Ruins, Revision 1" desc= "https://github.com/Cockatrice/Cockatrice/releases/tag/2018-07-17-Release-2.6.1" date= QDate("2018-07-18") url= "https://github.com/Cockatrice/Cockatrice/releases/download/2018-07-17-Release-2.6.1/Cockatrice-Father_of_Ruins_Revision_1-2.6.1-win64.exe"
Searching for commit hash corresponding to stable channel tag:  "2018-07-17-Release-2.6.1"
Got reply from tag server, size= 395 commit= "aa308717dee96a5be601cfbcf86eff2b16abcea3"
Current hash= "aa30871" update hash= "aa30871"
Error: Spoiler.xml not found or not deleted
QLayout: Attempting to add QLayout "" to ShortcutsTab "shortcutsTab", which already has a layout
cache fail for "_trice_card_back_226455"

  
__________________________________________________________________________________________

   I want to register my account, when it ask the activation code I didnt get the code and close the log in, then i have tried to find where to put the activation key, but i cant find it to regiter my account

DianaC is my user name

**Comment by tooomm** [comment]
I came up with a simple FAQ entry since we get this question **a lot**.
https://github.com/Cockatrice/Cockatrice/wiki/Frequently-Asked-Questions#where-to-enter-my-account-activation-token

@Daenyth @ZeldaZach Please edit the text there and provide a "right" solution for the future.

**Comment by ctrlaltca** [comment]
Connect to the server using the username and password you used when registering.
Upon connection, you will be asked he activation token.
If it tells you that's something wrong about your credentials, than you are using the wrong password.
If it tells you that's something wrong about your registration, than you are using the wrong username.

**Comment by tooomm** [comment]
If you still have problems, feel free to reopen this ticket.

For other people with the same issue I put it into the wiki/FAQ as well:
https://github.com/Cockatrice/Cockatrice/wiki/Frequently-Asked-Questions#where-to-enter-my-account-activation-token
