### ISSUE TITLE
Bump min Qt version to 5.9 LTS

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#3428]
Currently, we have to stick with Qt 5.5 because our CI builds and tests (and therefore also our .dmg file that we offer for download) run on Xenial (16.04) with Qt 5.5.
After https://github.com/Cockatrice/Cockatrice/issues/3294 is solved we moved to 18.04 LTS with Qt 5.9 LTS. (see also https://github.com/Cockatrice/Cockatrice/issues/2898)

Version guards like `#if QT_VERSION < 0x050600` can then be removed. (linking https://github.com/Cockatrice/Cockatrice/issues/3005)

@ZeldaZach mentioned that some server operators might still use the older Ubuntu 16.04 LTS (bundled with Qt 5.5 per default). Is that an issue or show stopper to consider?

**Comment by ebbit1q** [comment]
Now #3433 has been merged this will be a possibility. Do remember that even though you are encouraged to upgrade from Xenial to Bionic, Xenial will still recieve updates for a [while](https://www.ubuntu.com/about/release-cycle).
It should be possible to simply provide multiple packages: see #3438.

**Comment by tooomm** [comment]
If the target group for our install files is the ordinary end user... I think it's totally fine to only have them available for the latest Ubuntu LTS.
Every experienced user or server operator with special requirements that doesn't update for a specific reason can easily use our compile instructions if they don't know anyway.
Normal users would basically always update within a reasonable time frame.

**Comment by ebbit1q** [comment]
Removing the version guards would cause those compile instructions to no longer work as they'll need to upgrade their qt version separately.

**Comment by tooomm** [comment]
What do you suggest? @ebbit1q 
Update the instructions to tell users on older linux versions that they need to install a newer Qt first?
I think cmake will tell them already? But sure the wiki could be updated as well.

**Comment by tooomm** [comment]
Yes, exactly. It's only xenial still using 5.5. That's why we have to keep the min requirements down to that instead moving to 5.9 LTS. (5.5. isn't even LTS)

The appveyor builds could use up to 5.11 as well.

**Comment by ebbit1q** [comment]
Ok, we should definitely stop using that then, I can check what the best way to get 5.9 on the old ubuntu version is, easiest is to just say "use 18.04" or install qt 5.9 from their website.

**Comment by tooomm** [comment]
Jep, that sounds not too bad. :)
We don't need to provide 5.9 inside xenial.

As we just talked about in gitter... we are probably releasing a new version with mtgjson v4 support at the end of this year. (xenial & bionic deb + fedora rpm)

We can then drop xenial, bump the requirements and look forward to the next releases.

**Comment by ebbit1q** [comment]
Cool, we currently don't build for 16.04 in releases though, is easily implemented however.

**Comment by tooomm** [comment]
Oh true, you are right. 🙈 
Do we have to provide that @Daenyth ?
Or can we skip it already then?

We only use xenial for clang-format check and running our tests currently (all in debug mode only).
I think the tests could easily be moved to docker with newer ubuntu as well.
clang-format could stay with what travis offers as default basis to get quicker results maybe...

**Comment by tooomm** [comment]
Next step:
- move tests to docker build (bionic)

We can then bump the requirements already as we no longer depend on xenial to build in order to run our tests.

**Comment by ebbit1q** [comment]
We are still using Xenial. on 5.5. nothing has changed.

**Comment by tooomm** [comment]
We only use xenial to run our tests, we don't deploy any binaries for xenial

**Comment by ebbit1q** [comment]
We compile on xenial, we want people on xenial to be able to compile.

**Comment by ebbit1q** [comment]
version guards work fine and hurt noone, there is no rush to move away from xenial.

**Comment by ZeldaZach** [comment]
If it stops working, we'll drop support

**Comment by tooomm** [comment]
Status update on our current builds:

- Windows builds use 5.12, but could be updated to 5.15.

- macOS builds run with Qt 5.15 already.

- Linux builds are based on 20.04 Focal LTS with Qt 5.12 since a while now.
    - Via our Docker setup on-top we use a range from the old 18.04 Bionic LTS with Qt 5.9 as base to the current non-LTS 21.04 Hirsute with Qt 5.15 for Ubuntu.
    - Docket setup for Debian 10 uses Qt 5.11
    - All other Linux versions (Fedora 33+34 and Arch) use Qt 5.15 already in the build setup via Docker.
