### ISSUE TITLE
Migrate project to GitHub Apps integration (AppVeyor)

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#3436]
https://www.appveyor.com/blog/2018/10/02/github-apps-integration/
Section "Migrating existing projects to GitHub Apps" has a guide.

*Reminder for @Daenyth*

This is required to be able to use the new GitHub Checks API.

**Comment by ZeldaZach** [comment]
@tooomm If you'd like to pick this up and play around with the settings, feel free to. I'm fine with how things are setup currently.

**Comment by ZeldaZach** [comment]
I followed the steps Tom outlined. Should be good for this repo.

**Comment by tooomm** [comment]
Thanks!
