### ISSUE TITLE
Shortcut settings menu has too many entries per tab

### ISSUE THREAD

**Issue by ebbit1q** [Cockatrice/Cockatrice#3448]
Currently a lot of tabs in the shortcut settings menu are very crowded, prohibiting addition of additional shortcuts.
This can be improved by simply splitting the grouped tabs into separate tabs, with less entries per tab.

See my pr that adds 4 shortcuts while there isn't any space for them: #3439 
And @tooomm 's comment about the lack of space there: https://github.com/Cockatrice/Cockatrice/pull/3439#issuecomment-439696856
Quote:
> Just tested in client. Works for me +1
> 
> Maybe we should have more taps and don't group too many things together.
> I think it's easier to use with more tabs than all that things combined in a few:
> ![shortcuts](https://user-images.githubusercontent.com/9874850/48673831-e611d800-eb45-11e8-9adc-48727319f4d4.png)
> 
> We are really running low on space within each tab, which affects usability and we could come up with better grouping to make it even better for the user and use improve naming since there is more available space.

**Comment by ctrlaltca** [comment]
What about a table instead?
One row per action, grouped by sections (main windows, deck editor, ...).
Each row id readonly, and shows the action name and the associated shortcut.
When you select an action in the row, under the table you get the selected action name and the widget used to change it.
Additionally, a reset selected shortcuts / reset all shortcuts could be added.

**Comment by tooomm** [comment]
I like the table idea 👍 

I think it was @basicer or @ebbit1q, who posted example shortcut tables in gitter some time ago:
![table1](https://user-images.githubusercontent.com/9874850/53887970-a8b55580-4023-11e9-837f-cbbdcf4911df.png)
![table2](https://user-images.githubusercontent.com/9874850/53887972-a8b55580-4023-11e9-942e-7237b7e73ed8.png)
