### ISSUE TITLE
Travis builds on osx take disproportionally longer

### ISSUE THREAD

**Issue by ebbit1q** [Cockatrice/Cockatrice#3450]
![image](https://user-images.githubusercontent.com/36401181/48896594-42c40a00-ee48-11e8-952e-cf328cce99af.png)
As you can see in the logs it's mostly installing dependencies that takes so long, the actual compile takes about the same time as other builds.
The current Ubuntu Xenial build takes 2 mins, while the Ubuntu Bionic build (on docker) takes 3 mins, the osx build take about 13 mins.

**Comment by ZeldaZach** [comment]
They have fewer boxes for mac from what I recall

**Comment by ebbit1q** [comment]
Yeah you notice this in the slower startup time, the osx build starts no more than a minute later, but this is not calculated into the build time for osx.
This should not impact the time it spends installing, no?

**Comment by tooomm** [comment]
Fewer boxes, but fewer demand as well. And they shouldn't be slower cpu wise...
They need more start-up time though.

But the deal breaker is the installation of the dependencies via homebrew.

**Comment by ebbit1q** [comment]
![image](https://user-images.githubusercontent.com/36401181/48982964-52ae4900-f0e9-11e8-9dce-284b9fbf01ea.png)
:cry:

**Comment by tooomm** [comment]
That's some other issue I assume. :D

**Comment by ebbit1q** [comment]
y-yes, m-maybe

**Comment by ebbit1q** [comment]
Merged and fixed :)
