### ISSUE TITLE
travis format checking breaks on project branches

### ISSUE THREAD

**Issue by ebbit1q** [Cockatrice/Cockatrice#3457]
Currently travis uses the clangify.sh script when checking for formatting, this script will by default use `git diff origin/master` to find changed files and only check those files.

This works fine for pull requests but causes issues when on the origin remote itself. When on origin/master this wouldn't cause any errors but it doesn't check anything.

Now when on any other origin branch this will cause an error and exit the script because it can't find origin/master, I assume this is because travis simply doesn't pull it.

There are two ways to fix this: either we force it to fetch the master branch or we have clangify.sh (using `--branch ""`) check every single file which would be time consuming.

**Comment by Daenyth** [comment]
Hmm, tricky. We could try adding in a `git remote update` in there

**Comment by ebbit1q** [comment]
Well I can't test this so someone else would have to make a test branch on origin for this.

**Comment by ebbit1q** [comment]
Alternatively we could simply limit `--format` to prs only.

**Comment by Daenyth** [comment]
I'm ok with that

**Comment by ZeldaZach** [comment]
Would still like to find a fix, but it's not a huge problem

**Comment by tooomm** [comment]
With the Clangify workflow now on GitHub Actions, this should be solved.
