### ISSUE TITLE
Game crashing at random times during play

### ISSUE THREAD

**Issue by zachbarber** [Cockatrice/Cockatrice#3459]
<b>Client Version: 2.6.1 (2018-07-17)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.9.5
System Locale: en_US</b>

__________________________________________________________________________________________

game crashing at random times during play, here's the most recent debug log after re-opening. This time it crashed when I attempted to drag a Liliana, The Last Hope from my hand to my battlefield: 

Theme changed: "Default"
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
Language changed: ""
main(): starting main program
Spoilers Disabled
CardDatabase::loadCardDatabases start
[CockatriceXml3Parser] Trying to parse:  "C:/Users/Zach/AppData/Local/Cockatrice/Cockatrice/cards.xml"
main(): MainWindow constructor finished
main(): ui.show() finished
QWindowsWindow::setGeometry: Unable to set geometry 1920x1024+0+23 on QWidgetWindow/'MainWindowClassWindow'. Resulting geometry:  1920x1017+0+23 (frame: 8, 31, 8, 8, custom margin: 0, 0, 0, 0, minimum size: 879x1024, maximum size: 16777215x16777215).
cache fail for "_trice_card_back_290471"
cache fail for "_trice_card_back_290469"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Zach/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 18925 Sets= 231
[CockatriceXml3Parser] Trying to parse:  "C:/Users/Zach/AppData/Local/Cockatrice/Cockatrice/tokens.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Zach/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 19336 Sets= 231
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Zach/AppData/Local/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 19336 Sets= 231
CardDatabase::loadCardDatabases success

**Comment by Daenyth** [comment]
I don't suppose you could download the replay file of the game where you crashed, and upload it somewhere for us?

**Comment by Daenyth** [comment]
Does it always happen after you drag a card?

**Comment by tooomm** [comment]
Replays are normally saved on the server automatically (if enabled by the admin) for a certain time (different for each server) and one would need to manually download and save them locally to preserve them for a longer time.

So watch out for future crashes! ;)

**Comment by Zachbarber321** [comment]
Thanks!

**Comment by ZeldaZach** [comment]
If this issue is still happening let us know
