### ISSUE TITLE
Clicking "next" on Tip of the Day doesn't remove previous page's image unless "next" page also has an image

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#3464]
Version 2.6.1 (2018-07-17)

Probably we only overwrite previous image, we don't clear it when the new tip doesn't have one.

**Comment by ctrlaltca** [comment]
Just tested, but it seems that the image label gets correctly cleared.

**Comment by tooomm** [comment]
Same here, images are not preserved on following pages (even when there is no follow-up image).
The only tip without picture was the shortcut one though. Tested with

>Client Version: 2.6.2-custom(7670860) (2019-01-21)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.9.7
System Locale: de_DE
