### ISSUE TITLE
Problem connection to servver  

### ISSUE THREAD

**Issue by Bigdogdch** [Cockatrice/Cockatrice#3466]
<b>System Information:</b>
  

  
__________________________________________________________________________________________

**Comment by Bigdogdch** [comment]
When trying to connect it says I have to register.  I try that but it responds with the error message that registration is currently disabled on this server
Please advise

**Comment by ZeldaZach** [comment]
Assuming this is Chickatrice, you need to register on their website: http://chickatrice.net/
