### ISSUE TITLE
Banned Indefinitely

### ISSUE THREAD

**Issue by Rendroc** [Cockatrice/Cockatrice#3467]
I know this is probably not the place to put this, but I don't think anyone checks the Reddit r/cockatrice. I was banned indefinitely  from Rooster Ranges a while back for no good reason (I think I know which Mod, but they didn't message me or anything so I have no way to know for sure which Mod it was and that should NOT be allowed), and I'm a longtime Cockatrice user that contributes to the community. I'd appreciate an unban. Thank you.

**Comment by ZeldaZach** [comment]
You'll have to email the server operator(s) who are responsible for the specific server you were banned on. The development team can do nothing to help.

**Comment by Rendroc** [comment]
How do I contact them if I'm not allowed on the server?

**Comment by ZeldaZach** [comment]
Rooster Ranges: http://cockatrice.us/contact.php
Chickatrice: https://chickatrice.net/

**Comment by Rendroc** [comment]
I get a 404 when I clicked the cockatrice link

Not Found
The requested URL /contact.php was not found on this server.

**Comment by ctrlaltca** [comment]
I can confirm it's not working at least from Italy:

![schermata 2018-12-05 alle 12 35 50](https://user-images.githubusercontent.com/1631111/49511062-5e88d080-f88a-11e8-8863-e4a8aac12895.png)

```
fab$ curl -v http://cockatrice.us/contact.php
*   Trying 167.99.10.1...
* TCP_NODELAY set
* Connected to cockatrice.us (167.99.10.1) port 80 (#0)
> GET /contact.php HTTP/1.1
> Host: cockatrice.us
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Date: Wed, 05 Dec 2018 11:36:54 GMT
< Server: Apache
< Content-Length: 209
< Content-Type: text/html; charset=iso-8859-1
< 
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /contact.php was not found on this server.</p>
</body></html>
```

**Comment by ZeldaZach** [comment]
Should auto https redirect. Weird.

**Comment by ctrlaltca** [comment]
I can confirm it works using https

**Comment by Rendroc** [comment]
Yeah, works with https, no auto redirect

**Comment by tooomm** [comment]
For me the redirect works (Windows 10 / Firefox).
