### ISSUE TITLE
Several server crashes

### ISSUE THREAD

**Issue by ZeldaZach** [Cockatrice/Cockatrice#3473]
https://pastebin.com/SJrMVih5

The server has crashed 4 times in the past 2 days. I gdb outputted the latest one.

cc: @ctrlaltca

**Comment by ctrlaltca** [comment]
(Un)fortunately it looks like a crash internal in the protobuf library.
By any chance did you update / recompile servatrice recently?

**Comment by ZeldaZach** [comment]
No crashes currently, seems to be going well with the rebuild
