### ISSUE TITLE
Colors won't appear

### ISSUE THREAD

**Issue by Romanovskii** [Cockatrice/Cockatrice#3476]
When opening Cockatrice or looking for cards, their associated color won't appear on the database except for tokens.

![123](https://user-images.githubusercontent.com/46036469/50317263-9b6fdc80-04b2-11e9-9d13-251653d1bb6d.jpg)

**Comment by ZeldaZach** [comment]
Fixed in the newest release. Just give it a few hours to build and publish :)

**Comment by Romanovskii** [comment]
Thank you! :+1:
