### ISSUE TITLE
Improve the process of installing custom sets

### ISSUE THREAD

**Issue by KyleGChapman76** [Cockatrice/Cockatrice#3478]
Installing custom cards (as packaged by custom set designers, for example [this one of my set Rakoa](https://drive.google.com/file/d/1M_b9kHv9DboLrpBWzEUBREg6Q3JJbATt/view)) is difficult.. Playtesters frequently can't find or take too long to find the locations for customSets and pics/CUSTOM in the Cockatrice appdata, even with the shortcuts present in the Cockatrice UI. And placing the files given by designers into this location is an annoying multistep process even when the locations are found. Explaining and troubleshooting this process takes a lot of time and frustration that makes play testing custom sets more difficult.

An example of something that would be better would be for example the ability to drag and drop a .zip file into the Cockatrice window to install the custom set XML(s) and image folders present in that archive into Cockatrice, and restart Cockatrice and enable the set automatically.

I talked about this issue with @ZeldaZach in Discord DMs previously and he has asked me to tag him directly.

**Comment by ZeldaZach** [comment]
`Card Database > Add Custom Sets/Cards` does this now

**Comment by ebbit1q** [comment]
this is just a documentation issue, the process is pretty simple
