### ISSUE TITLE
Card arts won't change

### ISSUE THREAD

**Issue by Omega0zero** [Cockatrice/Cockatrice#3479]
<b>System Information:</b>
  Client Version: 2.6.2 (2018-12-20)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.9.7
System Locale: en_US
---------------------------------------------------------------------------
Theme changed: "Default"
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
Language changed: ""
main(): starting main program
Spoilers Disabled
CardDatabase::loadCardDatabases start
[CockatriceXml3Parser] Trying to parse:  "C:/Users/omega/AppData/Local/Cockatrice/Cockatrice/cards.xml"
main(): MainWindow constructor finished
main(): ui.show() finished
QWindowsWindow::setGeometry: Unable to set geometry 1920x1037+0+23 on QWidgetWindow/'MainWindowClassWindow'. Resulting geometry:  1920x1027+0+23 (frame: 8, 31, 8, 8, custom margin: 0, 0, 0, 0, minimum size: 879x1037, maximum size: 16777215x16777215).
PictureLoader: cache fail for "_trice_card_back_290493"
PictureLoader: cache fail for "_trice_card_back_290491"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/omega/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 18992 Sets= 432
[CockatriceXml3Parser] Trying to parse:  "C:/Users/omega/AppData/Local/Cockatrice/Cockatrice/tokens.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/omega/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 19402 Sets= 553
[CardDatabase] loadCardDatabase(): Path = "C:/Users/omega/AppData/Local/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 19402 Sets= 553
[CockatriceXml3Parser] Trying to parse:  "C:/Users/omega/AppData/Local/Cockatrice/Cockatrice/customsets/TK.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/omega/AppData/Local/Cockatrice/Cockatrice/customsets/TK.xml" Status = 0 Cards = 19402 Sets= 553
CardDatabase::loadCardDatabases success
__________________________________________________________________________________________

Issue I'm having is with card arts. According to the sets manager, anything put to the top will be loaded before other sets. Moving a set to the top, for example the Guru lands set, will not make my basics the Guru art. This even goes for sets like beta, Eventide and so forth. I have tried a ton of different things besides making a custom art folder as I have had this work before with no problems up until I got back on Cockatrice. Any suggestions/fixes? (besides a custom art folder)

**Comment by ebbit1q** [comment]
If you are still having this issue on the latest release feel free to reopen this issue. @Omega0zero
