### ISSUE TITLE
Database missing Guilds of Ravnica

### ISSUE THREAD

**Issue by D20Chris** [Cockatrice/Cockatrice#3483]
<b>System Information:</b>
  

  
__________________________________________________________________________________________

  Just like the title says, y'all are missing Guilds of Ravnica. That's all :)

**Comment by ZeldaZach** [comment]
Update to 2.6.2 and run the new oracle. Old oracle no longe works.

**Comment by D20Chris** [comment]
I just figured it out so I closed the issue feeling like a jerk. Sorry man
