### ISSUE TITLE
All cards showing as colorless

### ISSUE THREAD

**Issue by IamAlphaGeek** [Cockatrice/Cockatrice#3486]
So all cards are showing as colorless, making color filtering very difficult (have to use costs).  i've tried updating the database again and nothing is changed.

**Comment by ZeldaZach** [comment]
Make sure you're on 2.6.2 and run Oracle 2.6.2.

**Comment by IamAlphaGeek** [comment]
Thank you!  I'd recently updated and didn't realize there was a new version.
