### ISSUE TITLE
Strings missing in ts files

### ISSUE THREAD

**Issue by Caledor** [Cockatrice/Cockatrice#3488]
Need to manually add the strings returned by CardFilter::attrName (at https://github.com/Cockatrice/Cockatrice/blob/master/cockatrice/src/cardfilter.cpp) in the ts file, context FilterBuilder.

The corresponding tr() is already called at https://github.com/Cockatrice/Cockatrice/blob/master/cockatrice/src/filterbuilder.cpp#L15

**Comment by ebbit1q** [comment]
Could you give more details about the problem?

**Comment by Caledor** [comment]
"Name", "Type" etc up to "Loyalty" are the fields used for filtering the card database. Those strings can be translated since the tr is called at filterbuilder.cpp#L15 but the corresponding messages can't be found in the cockatrice_XX.ts files, cause we're using tr() on the result of a function instead of using it on the strings in cardfilter.cpp (the ts file generator will skip that tr()).

So to fix that we either change all the 
`return "Name"` to `return tr("Name")` (for each return in the switch)
and we remove the tr() at filterbuilder.cpp#L15 so the next time we generate the source .ts files for translations those strings will appear

OR we add the following to the ts file
```
    <message>
        <location filename="../src/filterbuilder.cpp" line="15"/>
        <source>Name</source>
        <translation></translation>
    </message>
```

for each returned string, under 

```
<context>
    <name>FilterBuilder</name>
```

**Comment by ctrlaltca** [comment]
I'd go with the first solution: add the `tr()`s in `cardfilter.cpp` and remove the one from `filterbuilder.cpp`.
As a last resort another solution exists, better than manually adding strings to the ts file (that could possibly get overwritten by lupdate): [QT_TRANSLATE_NOOP](http://doc.qt.io/qt-5/qtglobal.html#QT_TRANSLATE_NOOP) eg. we use it in [window_main.cpp#L709](https://github.com/Cockatrice/Cockatrice/blob/master/cockatrice/src/window_main.cpp#L709)

**Comment by ebbit1q** [comment]
:( that bit of code looks very, erm, not clean.
