### ISSUE TITLE
Resetting the p/t of flipped cards reveals their stats

### ISSUE THREAD

**Issue by ebbit1q** [Cockatrice/Cockatrice#3493]
If a player resets the p/t of a flipped card, that player will fetch the info of that card regardless, revealing information about the flipped card to other players.
We should instead either skip flipped cards or reset them to -1, hiding them in the way they are by default.

**Comment by Daenyth** [comment]
Thanks, good call.

**Comment by ebbit1q** [comment]
So skip or reset to -1?

**Comment by ZeldaZach** [comment]
By flipped card, i assume you mean we see the back of the card. If that's the case, reset it to 2/2

**Comment by ebbit1q** [comment]
We can't assume it's a morph, and either way if it is a morph you should instead just use the morph token and attach the card, way easier.

**Comment by ebbit1q** [comment]
Flipped cards are now called turned over, or played face down.

**Comment by ebbit1q** [comment]
So skip or reset to -1?
