### ISSUE TITLE
Reintroduce "download hq images" setting

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#3496]
With the new card download URL system, we can keep a boolean with the url that says whether the url gives HQ images or not. Then the downloader can check for an "allow downloading HQ images" configuration setting to skip over urls. We can populate the default URL list with HQ scryfall as higher priority above the `?version=small` scryfall url.

The primary goal of this is to allow for saving bandwidth for players with poor or metered internet connections

**Comment by ZeldaZach** [comment]
I think this should just be done manually in card sources as you can specify the component in the URL yourself. A button wouldn't be as intuitive, since you can now directly control the full order of downloads.
