### ISSUE TITLE
Translations missing for counter and game filter

### ISSUE THREAD

**Issue by Caledor** [Cockatrice/Cockatrice#3499]
See issue #887

Allow translation for counter names (life, storm and mana symbols) in the message log.
Allow translation for game types (game filter and list)

~~Change counter name for colorless from x to c as per Oath of the Gatewatch rule update (colorless mana symbol introduced)~~

**Comment by tooomm** [comment]
Note: There was PR trying to fix parts of this, but it got closed due to some issues: #952

**Comment by tooomm** [comment]
Game types are set by each server operator, I doubt we can properly offer to translate them.

Counters are translatable in between!

**Comment by ebbit1q** [comment]
counters have been made translatable here: https://github.com/Cockatrice/Cockatrice/pull/3997

game types are not defined inside cockatrice and could only be provided in different languages if the server would provide them in different languages

**Comment by tooomm** [comment]
Closing as one part is fixed and the other part can not easily be fixed as we are dependent on the server operators there.
