### ISSUE TITLE
Fix "reveal top cards" message in the log

### ISSUE THREAD

**Issue by Caledor** [Cockatrice/Cockatrice#3500]
When using "reveal top cards", the message shown in the log is always "reveals the top card" cause logRevealCards doesn't take the number of cards revealed `cardList.size()` as a parameter

https://github.com/Cockatrice/Cockatrice/blob/273d5d89b74afd2ad5cb88e7a14a6f0edf276fdb/cockatrice/src/player.cpp#L1870

**Comment by Daenyth** [comment]
Thanks, this is a severe one.

**Comment by Caledor** [comment]
Bug: Just tested in a local 2 player game.
If you reveal any number of cards to a specific player the message log always reads "X reveals 0 card(s) from the top of their library to Y".

If you reveal 1 card to everyone the game shows the card and the log mentions its name so that's fine.
Works as intended for 2+ cards revealed to everyone.

**Comment by ebbit1q** [comment]
Ok, this is only true for all the people that don't see the cards, naturally as they don't recieve a list of cards to display.
