### ISSUE TITLE
Card color affiliations not showing up.

### ISSUE THREAD

**Issue by PaulUParadox** [Cockatrice/Cockatrice#3501]
<b>System information:</b> Windows 7 home premium 
  
Client Version: 2.6.1 (2018-07-17)
Client Operating System: Windows 7 SP 1 (6.1)
Build Architecture: 64-bit
Qt Version: 5.9.5
System Locale: en_US

  
__________________________________________________________________________________________

  
Well over 90% of the cards that should have a color identification (WBGUR or any combination thereof) instead have no color identity. This makes it impossible to sort by, search for, or exclude cards using color identity as an option.

![image](https://user-images.githubusercontent.com/46572471/50985806-d1f5b180-14ca-11e9-9749-175207c577df.png)

**Comment by tooomm** [comment]
Can you update your card database please?

**Comment by skwerlman** [comment]
update to 2.6.2 and rerun oracle. oracle is broken in 2.6.1

**Comment by PaulUParadox** [comment]
> Can you update your card database please?

I've done that a few times

**Comment by tooomm** [comment]
> update to 2.6.2 and rerun oracle. oracle is broken in 2.6.1

**Comment by PaulUParadox** [comment]
> update to 2.6.2 and rerun oracle. oracle is broken in 2.6.1

That fixed it, thank you.

**Comment by tooomm** [comment]
Enjoy!

(Thanks @skwerlman)
