### ISSUE TITLE
Deprecate 32bit version for windows

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#3502]
>I don't think there are too many people that really depend on 32bit for windows anymore,
but with the next release we should cover them again to have a last working version with mtgjson v4 support for them, too.
After that, i feel we can deprecate that version... since **no single user reported/requested it since ~1 month now**.
>
>Appveyor builds would then report results in half of the time, hehe :smile: :thumbsup:

Background: With the current release (2.6.2), there is no 32bit version deployed because there was an issue with appveyor at deploy time and nobody realized it at first.

**Comment by ebbit1q** [comment]
I had a total of 1 complaints.

**Comment by tooomm** [comment]
Hmm? In the Server Chat? I saw nothing at Reddit and Gitter...

**Comment by ebbit1q** [comment]
Discord

**Comment by ebbit1q** [comment]
Discord

**Comment by tooomm** [comment]
Probably it would be good to adjust the in-client updater to not only look for `-win64.exe`, but also `win.exe` file endings in general.

Why? It makes sense to drop the "bit"-extension at one point too and keep things as simple as possible for the user. To avoid potential conflicts with updating we should have the client check for both for a while in advance once we make the switch later and change the filename as well.

**Comment by ZeldaZach** [comment]
It works still, I see no reason to prematurely kill it. Windows 10 still ships some 32 bit versions. If at some point it stops working, I'll consider it.
