### ISSUE TITLE
Bug: Ixalan land-transform cards incorrect land picture

### ISSUE THREAD

**Issue by aeschenkarnos** [Cockatrice/Cockatrice#3503]
Ixalan land-transform cards (eg Journey to Eternity / Atzal, Cave of Eternity or Legion's Landing / Adanto, the First Fort) are not showing up properly. The transformed card is showing up graphically as a second copy of the non-land permanent, although the Description field is correct.

**Comment by ZeldaZach** [comment]
So this is a URL thing that I intend to fix. I'm not sure if I have a tracking ticket, but yeah thanks for making this.

Note to self: !back! is needed, and we need to add it to Oracle. cc: @ctrlaltca

**Comment by ctrlaltca** [comment]
Fixed. Will be available in next version.
