### ISSUE TITLE
Bug: in "Create n token creatures" (eg Hunted Troll) the "n" is a weird character

### ISSUE THREAD

**Issue by aeschenkarnos** [Cockatrice/Cockatrice#3504]
Bug: in the right-click context menu to create tokens (typically creatures although Prosperous Pirates is affected and that creates Treasures), the number of such tokens is showing as a non-alphanumeric character, although the actual quantity created is correct.

**Comment by tooomm** [comment]
So nothing changed in the tokens.xml file? @Psithief 

Also, we don't use tokens from mtgjson yet, correct? @ctrlaltca

**Comment by Psithief** [comment]
A behaviour change in the latest versions of QT? Perhaps it converted the int to the string representation before, but now it's using it as an ASCII offset?

**Comment by ctrlaltca** [comment]
Fixed, will be available in the next release.

**Comment by tooomm** [comment]
I missed that in your pr, too @ctrlaltca.
Thanks for closing this.

The fixing commit is https://github.com/Cockatrice/Cockatrice/pull/3511/commits/8a57a1216613fcde02b07a5f32bee79d820f889c by the way.

**Comment by Psithief** [comment]
What was the actual cause?

**Comment by ctrlaltca** [comment]
Here's the oneliner fix: https://github.com/Cockatrice/Cockatrice/commit/8a57a1216613fcde02b07a5f32bee79d820f889c#diff-703dd4a6053aed459e325a18a5998d77L2978
A string was being created from an integer value.

**Comment by Psithief** [comment]
Oh, someone replaced my monstrous switch and ternary logic. :sweat_smile:
