### ISSUE TITLE
Deck Build Filtering

### ISSUE THREAD

**Issue by TheVette777** [Cockatrice/Cockatrice#3505]
<b>System Information:</b>
  

  
__________________________________________________________________________________________

  

As of 1/14/19 I have updated the card database and Cockatrice program (unknown if it is related), after which when I perform a filter of the card database by color i.e.

Add Filter

AND BLACK

only tokens appear as all cards are now listed as colorless...

**Comment by ZeldaZach** [comment]
Please update to 2.6.2, and run Oracle. This was addressed in that release
