### ISSUE TITLE
increase power (+1/+0) hotkey broken

### ISSUE THREAD

**Issue by Dreadhound** [Cockatrice/Cockatrice#3506]
<b>System Information:</b>
  
Client Version: 2.6.2 (2018-12-20)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.9.7
System Locale: nl_NL
  
__________________________________________________________________________________________

  

  
When going to settings, to the hotkey tab, the entrybox for increase power (+1/+0) is empty. When trying to manually input "Ctrl++" it says the shortcut is already in use (even though it isn't, I checked) The shortcut also doesnt function in-game. Restoring the shortcut to default and restoring all shortcuts to default have no effect.

**Comment by ebbit1q** [comment]
This is odd, I noticed this myself but didn't look into it yet. I'll see what's going on.

**Comment by ebbit1q** [comment]
Thanks for reporting! This issue will be fixed in the next build.
