### ISSUE TITLE
Split cards not showing up

### ISSUE THREAD

**Issue by callmemrshank** [Cockatrice/Cockatrice#3507]
<b>System Information:</b>
  

  
__________________________________________________________________________________________

**Comment by callmemrshank** [comment]
So after oracle updated the ravnica allegiance cards, split cards disappeared

**Comment by ZeldaZach** [comment]
You didn't fill out the System Information, so we can't do much to help other than say:

Update to 2.6.2 and run the 2.6.2 Oracle.

**Comment by callmemrshank** [comment]
I did that. Sorry. Unfamilliar with how this thing works. I just want my cards to work

**Comment by tooomm** [comment]
As you can see for yourself, your starting post contains no information at all... @callmemrshank 

>Go to "Help → View Debug Log" and copy all lines above the separation here!
