### ISSUE TITLE
Custom cards in enabled sets not showing up in deck editor

### ISSUE THREAD

**Issue by FallenPrime826** [Cockatrice/Cockatrice#3514]
<b>System Information:</b>
  
Client Version: 2.6.2 (2018-12-20)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.9.7
System Locale: en_US
  
__________________________________________________________________________________________

  
Okay, I was asked on the subreddit to come here with my issue.

I had the Yu-Gi-Oh .xml file from the custom sets page on this site still active in my custom sets folder when I performed a card database update (I'd previously had the Pokemon one too, but I removed it to my Downloads folder to just do YGO stuff). The database updated with all the RNA content, just like I wanted, and it re-activated all the MTG sets I'd disabled, but all the YGO cards disappeared. The sets were all still there and enabled, and the .xml still had the card information in it; they just all vanished from the deck editor's list, and the decks I made with them read them as nonexistent.

All attempts to remove and re-add the .xml file for the YGO sets (and there were _several_ attempts) changed absolutely nothing. The sets are all there, all enabled, but the cards just don't exist. Meanwhile, I put the Pokemon file back in the custom sets folder, and I had no problems with it at all.

This is what I'm getting in the debug log when both are active (as a quote because I don't know how to do the dropdown thing I've seen in other posts). The YGO file inflates the set number, but NOT the card number.

> [CardDatabase] loadCardDatabase(): Path = "C:/Users/GiveM/AppData/Local/Cockatrice/Cockatrice/customsets/XML Creator - Pokemon.xml" Status = 0 Cards = 27739 Sets= 629
[CockatriceXml3Parser] Trying to parse:  "C:/Users/GiveM/AppData/Local/Cockatrice/Cockatrice/customsets/XML Creator - YuGiOh.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/GiveM/AppData/Local/Cockatrice/Cockatrice/customsets/XML Creator - YuGiOh.xml" Status = 0 Cards = 27739 Sets= 1417
CardDatabase::loadCardDatabases success

**Comment by ebbit1q** [comment]
Can you upload the defective xml file to a paste site and link it here, so we can take a look if it might be incorrectly formatted?

**Comment by ZeldaZach** [comment]
Dropbox or meganz?

**Comment by ebbit1q** [comment]
If it's difficult, just posting the first entry in the file would suffice.

**Comment by FallenPrime826** [comment]
I've linked a Dropbox upload. Thanks, ZeldaZach, I didn't even think to try that.

[https://www.dropbox.com/s/2hu3bxgmburw7xe/XML%20Creator%20-%20YuGiOh.xml?dl=0](url)
