### ISSUE TITLE
Card shortcuts already enabled while the game hasn't started

### ISSUE THREAD

**Issue by ebbit1q** [Cockatrice/Cockatrice#3517]
You can use keyboard shortcuts like draw cards before the game has started, crashing the game even for some of them.

**Comment by ebbit1q** [comment]
I'm unable to reproduce the crash in recent versions, yet you still get the popup for drawing cards when pressing ctrl+e while in the sideboarding screen. It just does nothing.

**Comment by ZeldaZach** [comment]
Cool!

**Comment by ebbit1q** [comment]
This issue is not resolved, you shouldn't get the popups while the game didn't start yet.

**Comment by ebbit1q** [comment]
Actually, I managed to reproduce the crash, it happens sometimes when trying to view the top cards of the library (ctrl+w), I would like to test this on some other oses as well.

**Comment by ebbit1q** [comment]
Duplicate of #3155
