### ISSUE TITLE
Card Images and In-Game Buttons Distorted on Beta Release for OS X

### ISSUE THREAD

**Issue by SeanSpartacus** [Cockatrice/Cockatrice#3522]
<b>System Information:</b>

MacOS Mojave
10.14.2
MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports)
Graphics Intel Iris Plus Graphics 655 1536 MB
Built-In Display 13.3-inch (2560 x 1600)

Cockatrice (64-bit)
Version 2.6.3-beta.2 (2019-01-19)

Debug Log : See Attached File

__________________________________________________________________________________________

First of all, thank you to Zelda for the new beta test for Mac users! Unfortunately, I've run into a new issue, which is that all card images and buttons seem to be distorted in-game. I've attached the debug log as well as a screenshot of what I'm seeing. Basically, you only see a quarter of what you would normally see with cards, turn buttons, avatars, and mana/storm counters. This problem only appears to be present in the beta version. 

<img width="1426" alt="cockatrice image distortion" src="https://user-images.githubusercontent.com/9616347/51780223-6585cf80-20d2-11e9-8487-5fff6297d789.png">

[Debug Log from Cockatrice Jan 25 2019.txt](https://github.com/Cockatrice/Cockatrice/files/2798388/Debug.Log.from.Cockatrice.Jan.25.2019.txt)

**Comment by SeanSpartacus** [comment]
Updated the original post with info, also here:

MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports)
Graphics Intel Iris Plus Graphics 655 1536 MB
Built-In Display 13.3-inch (2560 x 1600)

**Comment by skwerlman** [comment]
OT: it'd be good to collect more info about the environment at the top of the log, like DPI, screen res, etc
