### ISSUE TITLE
Split Cards Not Showing Up

### ISSUE THREAD

**Issue by PySean** [Cockatrice/Cockatrice#3523]
<b>System Information:</b>
  
Client Version: 2.6.2-custom(37f9f62) (2019-01-25)
Client Operating System: Debian GNU/Linux buster/sid
Build Architecture: 64-bit
Qt Version: 5.11.3
System Locale: en_US
  
__________________________________________________________________________________________

  
Hello everyone,

After getting the latest card database update for RNA, I can no longer use (or find) split cards. They come up under "Unknown" in the deck builder (when loading a pre-existing deck file with a split card) and have no card art loaded.

I updated to 2.6.2 *after* getting the new set, and the problem persisted. I re-downloaded and re-updated the card database a couple of times after this, each time the problem persisted.

If it helps any, grepping about in the ~/.local/share/Cockatrice/Cockatrice/cards.xml file, I was *not* able to find *any* split cards, even from previous expansions like Amonkhet. I am still able to find these split cards in the AllCards.json file from the URL https://mtgjson.com/json/AllSets.json.zip . I found their names are in the "names" field, which is a two-element list containing both portions of the split card name.

I am guessing something is being lost in translation from the json to xml.

Sincerely,

PySean

**Comment by tooomm** [comment]
Does the most recent beta works for you?
Or can you try to build from master yourself as we don't offer a native Debian build?

Check here maybe: https://github.com/Cockatrice/Cockatrice/wiki/Compiling-Cockatrice-(Linux)#debian-linux

**Comment by tooomm** [comment]
CC: @ctrlaltca

**Comment by ctrlaltca** [comment]
The xml 4 parser is not included in any stable or beta release yet as far as i know.
I assume the version reported in OP 2.6.2-custom(37f9f62) is the broken one, aka current git master.
Btw, how the heck we released a 2.6.3 beta version when the codebase is still versioned at 2.6.2?

**Comment by ctrlaltca** [comment]
Thank you @PySean for catching this issue! If you want to test again the current git master, it should be solved.
