### ISSUE TITLE
Add hint to "draws 0 cards" message in log

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#3530]
Drawing from an empty library leads to a `... draws 0 card(s).` message in the game log:
![library empty](https://user-images.githubusercontent.com/9874850/51806082-ba158000-2275-11e9-87b4-184aefe7f3f8.png)

Having a hint/reason there could be helpful.
`... draws 0 card(s). Library is empty.` or
`... draws 0 card(s). No cards left.` for example.

**Comment by tooomm** [comment]
That still gives no reason why it fails, but the wording is nicer for the 0 cards case for sure.

Do we need/want to give a reason in the log?
Imagine somebody just knowing the log. On the other Hand an empty library is the only reason possible to trigger it?

To me, as a non-native speaker, ‘fails’ sounds a bit like there could be a problem in the app preventing a draw for example...
What about ‘... wasn’t able to draw a card’ or something along the lines?

**Comment by skwerlman** [comment]
maybe `... had no cards to draw.`?

**Comment by tooomm** [comment]
It still doesn't sound perfectly intuitive to me. But that could just be my poor sense of language.
`... had no cards left to draw.`?

I guess that's up to you guys to find the best wording here.

**Comment by skwerlman** [comment]
`... had no cards to draw.` and `... had no cards left to draw.` sound roughly the same to me, and either one is probably fine.

**Comment by ZeldaZach** [comment]
Seems like a visual only issue. Easy enough for new folks to help out with

**Comment by Tobyclark** [comment]
I ran into this and it was a bit confusing for me so I'd like to work on this issue. If someone could tell me what file I would make the changes in I'd appreciate it.

**Comment by ebbit1q** [comment]
that would be cockatrice/src/messagelogwidget.cpp MessageLogWidget::logDrawCards
