### ISSUE TITLE
Two little bugs in face down cards and reset p/t

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#3543]
Realized a second bug, too:

- From a single player game:
```
[15:30:31] Player 1 sets PT of to 3/4.
[15:30:36] Player 1 sets PT of to 5/5.
```
Grammatically wrong when card unknown.
Should use the card number for reference? `Player 1 sets PT of card # 74 to 5/5`

- Reset only works when the card is known

_Originally posted by @tooomm in https://github.com/Cockatrice/Cockatrice/pull/3542#issuecomment-459366160_

**Comment by ebbit1q** [comment]
The first issue isn't related to resetting at all.

**Comment by tooomm** [comment]
Yep, that's why I titled it "face down" and "p/t".
Since you said you are likely to fix both in the open PR, I didn't create separate issues.

**Comment by ebbit1q** [comment]
You let this excellent opportunity to create even more issues go to waste? Fine by me.

**Comment by tooomm** [comment]
It's just easier to move a comment to a new issue via menu, instead creating two manually. 😄

**Comment by tooomm** [comment]
I moved parts of this to a new issue, since I found another one to accompany it: #3544

This issue is now completely addressed in https://github.com/Cockatrice/Cockatrice/pull/3542. 👍
