### ISSUE TITLE
Issues with P/T setting for face down cards

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#3544]
<b>System Information:</b>
Client Version: 2.6.3-custom(cf8c920) (2019-01-31)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.9.7
System Locale: de_DE
__________________________________________________________________________________________

- Once you play a card face down (unknown card) and set a P/T value, the numbers are shown in white even though modified values should always be orange.
Another thing is, that when you peak at such an card (unknown --> known card) the number changes to orange.
If you play a card face down from your hand (known card) and adjust the numbers, the P/T values are orange too.

<br>

- When adjusting power or toughness values for the first time, the resulting value is completely weird:
    - increasing power: 0/0
    - increasing toughness: -1/1
    - increasing power AND toughness: 0/1

This only happens when no value has been set before (e.g. creatures enter the battlefield with their correct P/T when played, or a morph card has been set to 2/2 etc.)

**Comment by ebbit1q** [comment]
Are you kidding me? Please tell me what the problem is...

**Comment by tooomm** [comment]
@ebbit1q Just came back, sorry. Didn't manage to finish the text before, but wanted to link it already to send the other comment. 🙈

**Comment by ebbit1q** [comment]
Is that a problem? What would the preferred behavior be?

**Comment by tooomm** [comment]
>When adjusting power or toughness values of an unknown card for the first time, the resulting value is completely weird:
>
>    * increasing power: 0/0
>    * increasing toughness: -1/1
>    * increasing power AND toughness: 0/1


* increasing **power**: result should be **1/0**
* increasing **toughness**: result should be **0/1**
* increasing **power AND toughness**: result should be **1/1**

**Comment by ebbit1q** [comment]
Every card without p/t starts at -1/0, this "issue" extends further than just facedown cards.
