### ISSUE TITLE
[NSIS] uninstall of old version hint doesn't vanish

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#3552]
<b>System Information:</b>
Client Version: 2.6.3-beta.4 (2019-02-03)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.9.7
System Locale: de_DE
__________________________________________________________________________________________

I realized that in recent versions when installing on windows, the "you have to uninstall an existing old version" hint sticks around after the uninstall already finished and you go back to the initial install steps. When you then click ok, it simply goes away.
Maybe it gets opened twice?

It should close with opening the uninstall procedure already?

**Comment by ZeldaZach** [comment]
Is this still an issue?

**Comment by tooomm** [comment]
I couldn't replicate any longer.
