### ISSUE TITLE
OSX: Keybind Issue Continued (#3482 , #2647)

### ISSUE THREAD

**Issue by bukowskii87** [Cockatrice/Cockatrice#3557]
Hello,

My first git post, hopefully doing this properly. I recently updated to 2.6.2 and am immediatley losing the ability to use shortcut keys, draw, shuffle, etc. after the first few commands I enter. Usually it looks like this:

-Join Game
-Roll dice (command works)
-Mulligan (command works)
-Scry 1 (fail)
-All other commands fail

Anyway we can re open this issue?

<b>System Information:</b>
  

  
__________________________________________________________________________________________

**Comment by ZeldaZach** [comment]
Hi @bukowskii87 this is a known issue with the 2.6.2 Mac Build as we built against a bad version of Qt. This is fixed in the betas if you'd like to test those out. We'll be doing a full release in the very near future, so hang tight on that!
