### ISSUE TITLE
Doubled oracle db update message on fresh installs

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#3559]
<b>System Information:</b>
Client Version: 2.6.3-beta.4 (2019-02-03)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.9.7
System Locale: de_DE
__________________________________________________________________________________________

When doing a fresh install you get two messages that tell you to update your card database:

![msg1](https://user-images.githubusercontent.com/9874850/52277266-924ca900-2954-11e9-9a67-b362b653f52e.png)

![msg2](https://user-images.githubusercontent.com/9874850/52277269-937dd600-2954-11e9-97b5-272698c2118f.png)

**Comment by ZeldaZach** [comment]
When i added this feature, it was not combined with the below card database check. These are two separate checks that happen to be firing at the same time. What should be expected behavior here?

**Comment by ctrlaltca** [comment]
Fixed by #3740
