### ISSUE TITLE
Could not update cards database under Linux

### ISSUE THREAD

**Issue by joeved** [Cockatrice/Cockatrice#3564]
Hi all,

Since some weeks, I cannot update my cadrs database. The download seems to be correct but just after the 100%, I have this popup message "The card database updater exited with an error: crashed".
I try to download the file but this is the same problem.

My OS is Raspbian (Debian) and my computer is a Raspberry.
I compile Cockatrice. The version shown is: 2.6.3 (a719e3b).

Have you any idea to solve my problem ?
Thanks a lot.
Joe.

**Comment by skwerlman** [comment]
do you have a coredump or stack trace for oracle?

**Comment by joeved** [comment]
Yes probably. Where can I find it ?
If you want some version products, tell me ?

For example: CMake is 3.13

**Comment by joeved** [comment]
... and I don't have oracle directory into /var/opt. Is it important ?

**Comment by ctrlaltca** [comment]
I'm afraid that could mean that your Raspberry doesn't have enough memory to run oracle.
Recently oracle has been updated to switch from mtgjson (the card database source) v2 to v4.
While the v2 file was about 31 MB, the v4 file is more that 200 MB i size, and probably loading that file into memory, unzipping and parsing it fills up all the available RAM on the Raspberry.
A possible workaround is to add a swap file/partition to your Raspberry and see if it works.
Here's a thread i found about how to do it on raspbian: https://raspberrypi.stackexchange.com/questions/70/how-to-set-up-swap-space , the defaults seems to be 100MB, try to add a few hundred MBs to that and run oracle again.

**Comment by joeved** [comment]
Great idea, thanks. I will try that tomorow and I'll let you know.

**Comment by joeved** [comment]
It works !! Thanks you. No as easy as I thought.

In /etc/dphys-swapfile:
1- Uncomment CONF_SWAPFILE=/var/swap
2- Uncomment CONF_SWAPFACTOR=2 to have dynamic swap file.
3- Check that CONF_SWAPSIZE=100 is commented
4- Restart the swapfile process: /etc/init.d/dphys-swapfile restart

After that, all is possible !!

Thanks again.

**Comment by tooomm** [comment]
Happy to see it working for you. 👍

**Comment by joeved** [comment]
Yep, hope it will help someone else.

**Comment by tooomm** [comment]
You could add it to the wiki maybe, but not sure where...

**Comment by ctrlaltca** [comment]
To the Raspberry Pi documentation maybe :)

**Comment by tooomm** [comment]
The pi compilation instructions?

https://github.com/Cockatrice/Cockatrice/wiki/Compiling-Cockatrice-(Linux)#raspberry-pi

**Comment by ctrlaltca** [comment]
We have that? nice :)

**Comment by tooomm** [comment]
Do you mind explaining your solution and add it as a hint there? @joeved

**Comment by joeved** [comment]
Yes, if you want. I will try but how can I edit this page (https://github.com/Cockatrice/Cockatrice/wiki/Compiling-Cockatrice-(Linux)#raspberry-pi) ?

**Comment by joeved** [comment]
I see an Edit button on the top, will try a small modif and do more of this is good !!

**Comment by joeved** [comment]
That's it. Check and tell me if it is ok for you. Thanks.

**Comment by tooomm** [comment]
Awesome, thank you!

**Comment by joeved** [comment]
;) thanks you for your help too.
