### ISSUE TITLE
Commander decks being saved incredibly small. Only 32/100 cards show up.

### ISSUE THREAD

**Issue by CerebralHarlot** [Cockatrice/Cockatrice#3568]
<b>System Information:</b>
  

  
__________________________________________________________________________________________

**Comment by ZeldaZach** [comment]
No details. No support available.

**Comment by tooomm** [comment]
See https://github.com/Cockatrice/Cockatrice/issues/3569#issuecomment-461693928

His initial (hidden in html tags) issue report from here:
>Hi there, I hope I am in the right place. I am having an issue in cockatrice where all of my edh decks are being saved as incredibly small (4-5KB) sizes and when I load them up in a game I often get only about 1/3rd or 1/4th of the total cards I put in the deck! Ive done numerous restarts and reinstalls but I am not sure how to solve the problem.
