### ISSUE TITLE
Commander decks being saved incredibly small. Only 32/100 cards show up. (More info?)

### ISSUE THREAD

**Issue by CerebralHarlot** [Cockatrice/Cockatrice#3569]
<b>System Information:</b>
  

  
__________________________________________________________________________________________

My particular issue is with the latest version of cockatrice. 
          In loading an edh deck there is an improper loading and only 32/100 show up
          The deck lists are preserved but will not load once in the lobby room
          Unusually low file size (4-5kb)
         (There was not enough detail in my last post, I hope this is better?)

**Comment by ZeldaZach** [comment]
(Just realized he used HTML comment... still can't say much, but it's not a bogus ticket itself.

Please upload the "deck" you're trying at a minimum :)

**Comment by CerebralHarlot** [comment]
Sorry, about that, I am really new to this and wasn't sure what I needed.
[New Compressed (zipped) Folder.zip](https://github.com/Cockatrice/Cockatrice/files/2845668/New.Compressed.zipped.Folder.zip)

**Comment by ctrlaltca** [comment]
I just tried loading your deck and it looks fine both in the deck editor, game lobby and game library:
![schermata 2019-02-08 alle 16 46 22](https://user-images.githubusercontent.com/1631111/52488945-51a59780-2bc1-11e9-8bdd-5e16b18928cc.png)
![schermata 2019-02-08 alle 16 46 41](https://user-images.githubusercontent.com/1631111/52488946-523e2e00-2bc1-11e9-920b-20b33b3209b4.png)
![schermata 2019-02-08 alle 16 47 03](https://user-images.githubusercontent.com/1631111/52488947-523e2e00-2bc1-11e9-9720-f2d5356edfbf.png)

I'm not sure what the problem could be here..
What version of cockatrice are you running? You can find that info in the "about cockatrice" menu.

**Comment by CerebralHarlot** [comment]
2.6.2 

Here is what I end up seeing  

![screenshot 2](https://user-images.githubusercontent.com/47435965/52489866-581c1b00-2b91-11e9-9ca8-db5265b08b3f.png)

**Comment by ebbit1q** [comment]
@CerebralHarlot are you still having this issue?

**Comment by ebbit1q** [comment]
If you are still having this issue on the latest release feel free to reopen this issue. @CerebralHarlot
