### ISSUE TITLE
My cockatrice is super enlarged and I cannot make it normal size

### ISSUE THREAD

**Issue by kellysandall** [Cockatrice/Cockatrice#3592]
Hey I just got a new computer and my cockatrice text and everything is super enlarged and I cannot fix it. Please help!

![image](https://user-images.githubusercontent.com/48073091/53530688-81034200-3aa5-11e9-8407-c7345842a30b.png)

**Comment by ebbit1q** [comment]
Please give us your logs like the ticket asks you to.

**Comment by kellysandall** [comment]
Client Version: 2.6.2 (2018-12-20)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.9.7
System Locale: en_US
---------------------------------------------------------------------------
Theme changed: "Default"
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
Language changed: ""
main(): starting main program
Spoilers Disabled
CardDatabase::loadCardDatabases start
[CockatriceXml3Parser] Trying to parse:  "C:/Users/kmsan/AppData/Local/Cockatrice/Cockatrice/cards.xml"
main(): MainWindow constructor finished
main(): ui.show() finished
QWindowsWindow::setGeometry: Unable to set geometry 4251x2724+-1398+471 on QWidgetWindow/'MainWindowClassWindow'. Resulting geometry:  4251x2454+-1398+471 (frame: 18, 85, 18, 18, custom margin: 0, 0, 0, 0, minimum size: 1417x818, maximum size: 16777215x16777215).
Attempting auto-connect...
[CardDatabase] loadCardDatabase(): Path = "C:/Users/kmsan/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 19297 Sets= 442
[CockatriceXml3Parser] Trying to parse:  "C:/Users/kmsan/AppData/Local/Cockatrice/Cockatrice/tokens.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/kmsan/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 19712 Sets= 443
[CardDatabase] loadCardDatabase(): Path = "C:/Users/kmsan/AppData/Local/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 19712 Sets= 443
CardDatabase::loadCardDatabases success
QObject::connect: No such signal ShortcutsSettings::shortCutchanged()

**Comment by tooomm** [comment]
Whats your Display Resolution?

**Comment by ebbit1q** [comment]
we already asked him to on gitter....

**Comment by tooomm** [comment]
What was the result? Can this be closed then?

**Comment by ebbit1q** [comment]
Scroll up?

**Comment by ebbit1q** [comment]
If this iss ue was not resolved by the latest release feel free to reopen this issue. @kellysandall
