### ISSUE TITLE
Global Authentication - Brainstorming

### ISSUE THREAD

**Issue by ZeldaZach** [Cockatrice/Cockatrice#3593]
As time has progressed, the public servers have factioned off into different services. These services all struggle with consistency in moderation and user base. 

One of my long terms goals as maintainer is to design and implement a global authentication system. This system would be available to all public servers, and allow for more uniformity in account management.

By having one global database, and only allowing a user to login to one Cockatrice instance at a time (very doable with current implementations), we can maintain consistency in a global database and give users a better overall experience.

Users will be able to retain all of their account information across different servers, logging into the one that's most convenient for them at the current time. This will (hopefully) allow the management debt of servers to decrease as we can unionize together to limit toxic behavior and allow other server's to manage users at the same time.

Looking to have some discussions in the comments below 😄 
____

My implementation ideas:
- Have a global registration based on the official Cockatrice development and in-client.
    - If a user registers in client, if it's for an official public server, it will be equivalent to registering on the development site.
- The global registration server / database will be manged by the development team and have an API network that public servers can call (with appropriate API keys) to maintain the same data state.
- Official public servers can make a local copy of the global registration database and push back changes to it on the fly and/or on a per-determined schedule.

**Comment by ZeldaZach** [comment]
cc: @ctrlaltca @basicer @tooomm @ebbit1q

**Comment by ancestral** [comment]
The important thing here is to adopt a proven form of authentication. Homebrewing some kind of new authentication scheme is probably a bad idea since it wouldn’t have been battle-tested.

You should assume any service you set up could be hacked and compromised. If so, how will you prevent passwords from being unleashed into the wild? This means things like salted and hashed passwords (and/or possibly some system based on public keys) are probably going to be the right way about things.

I would consider looking at existing, robust authentication libraries or built-in authentication methods in popular web frameworks as a baseline.

**Comment by basicer** [comment]
The simplest solution as I see it is:

- NodeJS Auth server.  PassportJS for authentication / integration with social login.
- JWT with JTI and ES512 signature.

**Comment by ZeldaZach** [comment]
@basicer What kinds of logins should we support? How would it work? You don't have a "Cockatrice" password anymore, but have a login using Google/Fb/whatever?

**Comment by basicer** [comment]
You could have both.

**Comment by tooomm** [comment]
Linking https://github.com/Cockatrice/Cockatrice/issues/46

**Comment by ctrlaltca** [comment]
Qt >= 5.8 supports authentication using oauth:  https://doc.qt.io/qt-5/qtnetworkauth-index.html

**Comment by skwerlman** [comment]
i'm not sure we need a global auth registry.

we can treat other servers as "authorities", and each user would be thought of as belonging to an authority (like "alex@tetrarch.co" or "bart@cockatrice.us")

each server can specify which authorities they trust, and what they trust the users from that authority to do (like have avatars of a certain size, or be judges or mods or admins in cross-server games, or send dms, or whatever)

**Comment by ZeldaZach** [comment]
Servers will just be independent, for the time being.
