### ISSUE TITLE
[Replays] Seeking causes progress bar to move unsmoothly

### ISSUE THREAD

**Issue by ImmortalFabio** [Cockatrice/Cockatrice#3598]
<b>System Information:</b>
  
Client Version: 2.7.0 (2019-03-03)
Client Operating System: Windows 7 SP 1 (6.1)
Build Architecture: 64-bit
Qt Version: 5.9.7
System Locale: en_NZ
Install Mode: Standard
  
__________________________________________________________________________________________
Version 2.7.0 (64 bit)

When watching replays, clicking on the progress bar to jump to a specific spot then resuming playback causes the progress bar to no longer move smoothly. Prior to this event progress bar flows smoothly.

Issue is limited to that specific instance/room of replay. Watching other replays, or the same replay in a different viewing room (even if the now-bugged replay is still playing), will be fine, until/unless the action of seeking is taken.

**Comment by ebbit1q** [comment]
can you give us your system information?

**Comment by ImmortalFabio** [comment]
Client Version: 2.7.0 (2019-03-03)
PictureLoader: [card:  "Vendilion Clique"  set:  "A25" ]: Picture found on disk.
reorganizeCards: rows= 1 cols= 2
reorganizeCards: rows= 1 cols= 2
reorganizeCards: rows= 4 cols= 2
PictureLoader: [card:  "Thoughtseize"  set:  "THS" ]: Trying to load picture
PictureLoader: [card:  "Thoughtseize"  set:  "THS" ]: Picture found on disk.
ArrowItem constructor: startItem= QGraphicsItem(0x105a1d30, parent=0x132c4e00, pos=5,152, flags=(ItemIsSelectable))
ArrowItem constructor: startItem= QGraphicsItem(0x764f200, parent=0x17123ec0, pos=234,274, z=3.76235e+07, flags=(ItemIsSelectable))
ArrowItem destructor
ArrowItem destructor
reorganizeCards: rows= 1 cols= 2
reorganizeCards: rows= 1 cols= 2
reorganizeCards: rows= 4 cols= 2
ArrowItem constructor: startItem= QGraphicsItem(0x13426650, parent=0x17123ec0, pos=365,274, z=3.76366e+07, flags=(ItemIsSelectable))
ArrowItem destructor
reorganizeCards: rows= 1 cols= 2
reorganizeCards: rows= 1 cols= 2
reorganizeCards: rows= 5 cols= 2
ArrowItem constructor: startItem= QGraphicsItem(0x1048e880, parent=0x197dd6d0, pos=5,152, flags=(ItemIsSelectable))
PictureLoader: [card:  "Plains"  set:  "UNH" ]: Trying to load picture
PictureLoader: [card:  "Plains"  set:  "UNH" ]: Picture found on disk.
ArrowItem destructor
ZoneViewZone destructor
CardZone destructor:  "hand"
ZoneViewZone destructor
CardZone destructor:  "hand"
ZoneViewZone destructor
CardZone destructor:  "hand"
PictureLoader: [card:  "Jace, the Mind Sculptor"  set:  "A25" ]: Trying to load picture
PictureLoader: [card:  "Jace, the Mind Sculptor"  set:  "A25" ]: Picture found on disk.
PictureLoader: [card:  "Temur Battle Rage"  set:  "FRF" ]: Trying to load picture
PictureLoader: [card:  "Temur Battle Rage"  set:  "FRF" ]: Picture found on disk.
reorganizeCards: rows= 1 cols= 2
reorganizeCards: rows= 1 cols= 2
reorganizeCards: rows= 4 cols= 2
ArrowItem constructor: startItem= QGraphicsItem(0xd18da00, parent=0x17125180, pos=234,274, z=3.76235e+07, flags=(ItemIsSelectable))
ArrowItem destructor
ArrowItem constructor: startItem= QGraphicsItem(0xd18db00, parent=0x17125180, pos=365,274, z=3.76366e+07, flags=(ItemIsSelectable))
ArrowItem destructor
ArrowItem constructor: startItem= QGraphicsItem(0x13798390, parent=0x132c5880, pos=5,152, flags=(ItemIsSelectable))
ArrowItem destructor
ZoneViewZone destructor
CardZone destructor:  "hand"
ZoneViewZone destructor
CardZone destructor:  "hand"
ZoneViewZone destructor
CardZone destructor:  "hand"
addCounter: "Pyroswiftspear" 0 "life"
addCounter: "Pyroswiftspear" 1 "w"
addCounter: "Pyroswiftspear" 2 "u"
addCounter: "Pyroswiftspear" 3 "b"
addCounter: "Pyroswiftspear" 4 "r"
addCounter: "Pyroswiftspear" 5 "g"
addCounter: "Pyroswiftspear" 6 "x"
addCounter: "Pyroswiftspear" 7 "storm"
addCounter: "Acronox" 0 "life"
addCounter: "Acronox" 1 "w"
addCounter: "Acronox" 2 "u"
addCounter: "Acronox" 3 "b"
addCounter: "Acronox" 4 "r"
addCounter: "Acronox" 5 "g"
addCounter: "Acronox" 6 "x"
addCounter: "Acronox" 7 "storm"
ArrowItem constructor: startItem= QGraphicsItem(0x14424b00, parent=0x171253c0, pos=20,142, z=2.44021e+07, flags=(ItemIsSelectable))
ArrowItem destructor
ArrowItem constructor: startItem= QGraphicsItem(0xfec2dd0, parent=0x132c4e00, pos=5,152, flags=(ItemIsSelectable))
ArrowItem destructor
reorganizeCards: rows= 1 cols= 2
reorganizeCards: rows= 1 cols= 2
reorganizeCards: rows= 4 cols= 2
reorganizeCards: rows= 1 cols= 2
reorganizeCards: rows= 1 cols= 2
reorganizeCards: rows= 5 cols= 2
reorganizeCards: rows= 1 cols= 2
reorganizeCards: rows= 1 cols= 2
reorganizeCards: rows= 4 cols= 2
ArrowItem constructor: startItem= QGraphicsItem(0xfad6930, parent=0x17125180, pos=234,274, z=3.76235e+07, flags=(ItemIsSelectable))
ArrowItem destructor
ArrowItem constructor: startItem= QGraphicsItem(0xfad6a30, parent=0x17125180, pos=365,274, z=3.76366e+07, flags=(ItemIsSelectable))
ArrowItem destructor
ArrowItem constructor: startItem= QGraphicsItem(0x14423e00, parent=0x132c5880, pos=5,152, flags=(ItemIsSelectable))
ArrowItem destructor
ZoneViewZone destructor
CardZone destructor:  "hand"
ZoneViewZone destructor
CardZone destructor:  "hand"
ZoneViewZone destructor
CardZone destructor:  "hand"
Player destructor: "Pyroswiftspear"
GameScene::removePlayer name= "Pyroswiftspear"
CardZone destructor:  "deck"
CardZone destructor:  "grave"
CardZone destructor:  "hand"
CardZone destructor:  "rfg"
CardZone destructor:  "sb"
CardZone destructor:  "stack"
CardZone destructor:  "table"
Player destructor: "Acronox"
GameScene::removePlayer name= "Acronox"
CardZone destructor:  "deck"
CardZone destructor:  "grave"
CardZone destructor:  "hand"
CardZone destructor:  "rfg"
CardZone destructor:  "sb"
CardZone destructor:  "stack"
CardZone destructor:  "table"
Player destructor: "Pyroswiftspear"
GameScene::removePlayer name= "Pyroswiftspear"
CardZone destructor:  "deck"
CardZone destructor:  "grave"
CardZone destructor:  "hand"
CardZone destructor:  "rfg"
CardZone destructor:  "sb"
CardZone destructor:  "stack"
CardZone destructor:  "table"
Player destructor: "Acronox"
GameScene::removePlayer name= "Acronox"
CardZone destructor:  "deck"
CardZone destructor:  "grave"
CardZone destructor:  "hand"
CardZone destructor:  "rfg"
CardZone destructor:  "sb"
CardZone destructor:  "stack"
CardZone destructor:  "table"
PictureLoader: cache fail for "_trice_card_back_211300"
PictureLoader: [card:  "Fire // Ice"  set:  "DDJ" ]: Trying to load picture
PictureLoader: [card:  "FireIce"  set:  "DDJ" ]: Picture found on disk.

**Comment by ZeldaZach** [comment]
@ImmortalFabio Mac? Windows? That's what we'd like please :)

**Comment by ebbit1q** [comment]
They just told me that's all they see in the debug log

**Comment by ebbit1q** [comment]
he's on win7
