### ISSUE TITLE
Moving a card with a custom P/T forgets the P/T

### ISSUE THREAD

**Issue by skwerlman** [Cockatrice/Cockatrice#3600]
<b>System Information:</b>
  
Client Version: 2.7.0-custom(unknown) (unknown)
Client Operating System: NixOS 19.03pre169779.b75eab88bde (Koi)
Build Architecture: 64-bit
Qt Version: 5.12.0
System Locale: en_US
Install Mode: Standard
  
__________________________________________________________________________________________

  

  
Moving a card with a custom P/T will cause the card to lose its P/T entirely.

**Comment by ebbit1q** [comment]
THANKS
