### ISSUE TITLE
Reverse-related not working

### ISSUE THREAD

**Issue by skwerlman** [Cockatrice/Cockatrice#3603]
<b>System Information:</b>
  
Client Version: 2.7.0-custom(unknown) (unknown)
Client Operating System: NixOS 19.03pre169779.b75eab88bde (Koi)
Build Architecture: 64-bit
Qt Version: 5.12.0
System Locale: en_US
Install Mode: Standard
  
__________________________________________________________________________________________

  

  
Cards with the `reverse-related` or `related` attrs in the XML don't have the associated menu options in game

**Comment by ebbit1q** [comment]
Can't reproduce.

**Comment by ebbit1q** [comment]
Got it.
