### ISSUE TITLE
Deck editor description box resizes instead of wrapping

### ISSUE THREAD

**Issue by skwerlman** [Cockatrice/Cockatrice#3605]
<b>System Information:</b>
  
Client Version: 2.7.0-custom(unknown) (unknown)
Client Operating System: NixOS 19.03pre169779.b75eab88bde (Koi)
Build Architecture: 64-bit
Qt Version: 5.12.0
System Locale: en_US
Install Mode: Standard
  
__________________________________________________________________________________________

  

  
In the deck editor, when switching to a card with longer attributes (such as name or card type) the description widget will grow to fit the attribute rather than wrapping it.

**Comment by ZeldaZach** [comment]
<img width="504" alt="screenshot 2019-03-03 22 07 26" src="https://user-images.githubusercontent.com/7460172/53708286-c0f95a80-3e00-11e9-9e82-a3727a8b1e32.png">
<img width="450" alt="screenshot 2019-03-03 22 07 13" src="https://user-images.githubusercontent.com/7460172/53708287-c0f95a80-3e00-11e9-836e-f7f91c2b2bd1.png">

**Comment by ebbit1q** [comment]
![image](https://user-images.githubusercontent.com/36401181/53708269-f880fa80-3e32-11e9-8abd-d00438d04b81.png)
![image](https://user-images.githubusercontent.com/36401181/53708285-0afb3400-3e33-11e9-9309-6f7f36b65795.png)

**Comment by ebbit1q** [comment]
ninjas...
