### ISSUE TITLE
Deck Sorting Bug

### ISSUE THREAD

**Issue by JakeChaimowitz** [Cockatrice/Cockatrice#3608]
<b>System Information:</b>
  
Dont have it anymore
   Windows 10
__________________________________________________________________________________________

  
When i view my library in game it sorts enchantment and artifact creatures as enchantments and artifacts rather than as creatures
  
![image](https://user-images.githubusercontent.com/42967457/53709291-77f7d500-3e05-11e9-97e8-aca81a1c45d1.png)

**Comment by ebbit1q** [comment]
The sorting is actually nicely integrated, changing this behavior would mean changing it everywhere else as well.

**Comment by ancestral** [comment]
I would agree that, as players, we want these to be seen under creatures. Creatures that happen to be other card types should probably always still show up under the creatures column.

**Comment by ebbit1q** [comment]
Already fixed it.
