### ISSUE TITLE
Server Dropdown is always Rooster Ranges

### ISSUE THREAD

**Issue by Lachee** [Cockatrice/Cockatrice#3617]
<b>System Information:</b>
Client Version: 2.7.0 (2019-03-04)
Client Operating System: Windows 7 SP 1 (6.1)
Build Architecture: 64-bit
Qt Version: 5.9.7
System Locale: en_AU
Install Mode: Standard
---------------------------------------------------------------------------
Theme changed: "Default"
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
Language changed: ""
main(): starting main program
Spoilers Disabled
CardDatabase::loadCardDatabases start
[CockatriceXml3Parser] Trying to parse:  "C:/Users/Lachee/AppData/Local/Cockatrice/Cockatrice/cards.xml"
main(): MainWindow constructor finished
main(): ui.show() finished
PictureLoader: cache fail for "_trice_card_back_226304"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Lachee/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 16642 Sets= 200
[CockatriceXml3Parser] Trying to parse:  "C:/Users/Lachee/AppData/Local/Cockatrice/Cockatrice/tokens.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Lachee/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 16971 Sets= 200
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Lachee/AppData/Local/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 16971 Sets= 200
[CockatriceXml3Parser] Trying to parse:  "C:/Users/Lachee/AppData/Local/Cockatrice/Cockatrice/customsets/TK.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Lachee/AppData/Local/Cockatrice/Cockatrice/customsets/TK.xml" Status = 0 Cards = 16973 Sets= 200
CardDatabase::loadCardDatabases success
QLayout: Attempting to add QLayout "" to TabLog "", which already has a layout
CardDatabase::loadCardDatabases start
[CockatriceXml3Parser] Trying to parse:  "C:/Users/Lachee/AppData/Local/Cockatrice/Cockatrice/cards.xml"
[CockatriceXml3Parser] Parsing failed: wrong version 4
[CockatriceXml4Parser] Trying to parse:  "C:/Users/Lachee/AppData/Local/Cockatrice/Cockatrice/cards.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Lachee/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 19300 Sets= 443
[CockatriceXml3Parser] Trying to parse:  "C:/Users/Lachee/AppData/Local/Cockatrice/Cockatrice/tokens.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Lachee/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 19715 Sets= 444
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Lachee/AppData/Local/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 19715 Sets= 444
[CockatriceXml3Parser] Trying to parse:  "C:/Users/Lachee/AppData/Local/Cockatrice/Cockatrice/customsets/TK.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Lachee/AppData/Local/Cockatrice/Cockatrice/customsets/TK.xml" Status = 0 Cards = 19717 Sets= 444
CardDatabase::loadCardDatabases success
CardDatabase::loadCardDatabases start
[CockatriceXml3Parser] Trying to parse:  "C:/Users/Lachee/AppData/Local/Cockatrice/Cockatrice/cards.xml"
[CockatriceXml3Parser] Parsing failed: wrong version 4
[CockatriceXml4Parser] Trying to parse:  "C:/Users/Lachee/AppData/Local/Cockatrice/Cockatrice/cards.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Lachee/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 19300 Sets= 443
[CockatriceXml3Parser] Trying to parse:  "C:/Users/Lachee/AppData/Local/Cockatrice/Cockatrice/tokens.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Lachee/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 19715 Sets= 444
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Lachee/AppData/Local/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 19715 Sets= 444
[CockatriceXml3Parser] Trying to parse:  "C:/Users/Lachee/AppData/Local/Cockatrice/Cockatrice/customsets/TK.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Lachee/AppData/Local/Cockatrice/Cockatrice/customsets/TK.xml" Status = 0 Cards = 19717 Sets= 444
CardDatabase::loadCardDatabases success
PictureLoader: cache fail for "_trice_card_back_226304"
getPort() index =  6  port.val =  "4748"
getPlayerName() index =  6  name.val =  "lachee"
link path774 hasn't been detected!
link path774 hasn't been detected!
link path774 hasn't been detected!
link lion hasn't been detected!
link path1214 hasn't been detected!
link path1563 hasn't been detected!
link path1563 hasn't been detected!
QLayout: Attempting to add QLayout "" to TabLog "", which already has a layout
QLayout: Attempting to add QLayout "" to TabLog "", which already has a layout
PictureLoader: cache fail for "_trice_card_back_226304"
PictureLoader: cache fail for "_trice_card_back_226632"
QLayout: Attempting to add QLayout "" to TabLog "", which already has a layout

__________________________________________________________________________________________

Rooster Ranges is always the default server in the listing. When you start the game, disconnect from the server, or even just refresh the server listing, it will automatically select Rooster Ranges. 

I spoken to @ZeldaZach and he suggested that "auto connect" will fix that, but the auto connect box is disabled when you are connecting to a known server from the dropdown. 

Ideally, the dropdown menu should just remember the last one you attempted to connect to. If you want to ensure usability, you could limit it to successful connections.

**Comment by ZeldaZach** [comment]
So the issue at hand here is your "auto connect" checkbox wasn't selectable. It should be enabled when you're using any host in the dropdown menu box. I tested on Windows10 and Mac, but had no luck reproducing.

If someone with a Win7 box can test this, that would be helpful!

**Comment by Lachee** [comment]
I still think the dropdown should remember the last server that was selected as a userbility thing. It can be very confusing for users when they try different accounts names (if they have forgotten) or are trying to reconnect (if they lost internet) without having to explicitly auto connect to only 1 server.

**Comment by Leechcraft** [comment]
I have the same issue of it always defaulting to Rooster Ranges. My "Auto connect" box is available, but it resets every time, even after checking the auto connect.

**Comment by tooomm** [comment]
This behaviour is very bad and should change, yes!

There are also people out there which doesn't want to store their passwords or use auto-connect.

**Comment by ebbit1q** [comment]
this is still an issue, it should use the setting that it stores but it instead always overrides it :(

**Comment by tooomm** [comment]
Exactly, `previoushostName` is correctly stored in `servers.ini`

**Comment by skwerlman** [comment]
ye, i get complaints from my users about this a lot
