### ISSUE TITLE
Arrow keys for life total

### ISSUE THREAD

**Issue by theonekami** [Cockatrice/Cockatrice#3618]
<b>System Information:</b>
  
Client Version: 2.7.0 (2019-03-04)

  
ok so like ctrl L-> life total pop up
the prev version had the option to change it by pressing the upper and down button. 
That is missing now, can we have that back?

**Comment by ZeldaZach** [comment]
CTRL+L in the past did have an up/down arrow to allow for changing of the value one-by-one. I agree this functionality should return.

**Comment by ShrewMaster** [comment]
Came here to speak precisely about this issue. Glad to see I was not the only one to notice.
