### ISSUE TITLE
Commas and Hyphens

### ISSUE THREAD

**Issue by Moonlight-Cockatrice** [Cockatrice/Cockatrice#3620]
<b>System Information:</b>
  

  
__________________________________________________________________________________________

  
Using commas and hyphens in the deck editor's search feature results in the cards whose names include those characters not being displayed.
I can understand frustration with some users not knowing when to use commas, but while it would be one thing to allow omission of the punctuation to still display the associated card, making those cards /only/ visible by /not/ using the correct punctuation is highly unintuitive.

**Comment by ZeldaZach** [comment]
cc: @basicer
