### ISSUE TITLE
Main Card Type

### ISSUE THREAD

**Issue by Moonlight-Cockatrice** [Cockatrice/Cockatrice#3621]
<b>System Information:</b>
  

  
__________________________________________________________________________________________

  
Main Card Type is incorrectly displaying Artifact Lands and Artifact Creatures as having the main card type of Artifact, which is causing artifact lands to go to the stack, which they don't use. 

Additionally, as more of a general suggestion, I feel that both main card type and layout could be hidden information in the description window, as there's generally no reason to search for main card type where one could just search by card type, and it's largely redundant in the description window and takes up vertical space, making the window more cluttered, especially given the word wrap. As for layout, the information is largely unimportant in the description section where the type of card is self evident in the art/typeline.

**Comment by skwerlman** [comment]
dupe #3608
already fixed by #3611

**Comment by ZeldaZach** [comment]
Fixed in 2.7.0_1 (Look for version date of March 4th)

**Comment by Moonlight-Cockatrice** [comment]
@ZeldaZach when checking for client updates, my client tells me that I'm currently up to date on version 2.7.0, march 4th. 
If that's the newest version I'm still having this issue.

**Comment by Moonlight-Cockatrice** [comment]
It seems my issue was not read in full before being closed. The linked issue refers to artifact creatures, which has been fixed, however artifact **lands** are still being displayed as artifacts and going to the stack, which they don't use.
