### ISSUE TITLE
Mac Card Menu Regression

### ISSUE THREAD

**Issue by ZeldaZach** [Cockatrice/Cockatrice#3622]
In the past, a user could `control` + click on a card to get the "right click" menu. This is no longer the case.

A user could, and still can, use two fingers on the trackpad to right click to get the card menu open.

We should look into why this regression came about.

**Comment by ancestral** [comment]
A secondary click can be done different ways, but each person has their personal preference. Certainly affects people who are like using or are just otherwise so familiar with ctrl+click.

**Comment by ctrlaltca** [comment]
Tested old versions, working up to 2.6.2 (qt 5.9.3), broken on 2.7.0 (qt 5.12.1).
Tried building old, known working trice versions using Qt 5.12.1, and the bug is there.
I'm afraid this is a qt bug we can't really fix it, but only add workarounds.

**Comment by tooomm** [comment]
Too bad homebrew dropped the attempt to add qt@5.9 as they run into an issue with it: https://github.com/Homebrew/homebrew-core/pull/36114

**Comment by tooomm** [comment]
Is this still present with 5.12.3?

I couldn't find a report in the Qt tracker when I had a quick look...
Are they aware at all?

**Comment by ctrlaltca** [comment]
This seems to work fine on the last release 2.7.4, based on Qt 5.14.1.

**Comment by tooomm** [comment]
@ebbit Said on Gitter it’s still an issue?

**Comment by ebbit1q** [comment]
I never said that, I have no way to verify that either.

**Comment by tooomm** [comment]
>tooomm @tooomm Mar 25 10:21
Is Cockatrice/Cockatrice#3622 still an issue?
btw flatpak released and website news updated
>>ebbit1q:
>>how many people downloaded the .deb package?
>>
>@ebbit1q 2 372(Ubuntu) (out of 73 108) for 2.7.2, and 172(Debian) + 332(Ubuntu) (out of 8 908) for 2.7.4...
>
> <br>
>
>tooomm @tooomm Mar 25 10:51
What's mtgjson v5 about btw?
>
>ebbit1q @ebbit1q Mar 25 11:34
yes

My bad then. Thought you answered the question. :)

**Comment by ebbit1q** [comment]
No.
