### ISSUE TITLE
Ixalan Flip Lands and Deck Editor Search Functions

### ISSUE THREAD

**Issue by Leechcraft** [Cockatrice/Cockatrice#3624]
<b>System Information:</b>
Client Version: 2.7.0 (2019-03-04)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.9.7
System Locale: en_US
Install Mode: Standard
__________________________________________________________________________________________
Apologies if I'm going about this wrong or this is the wrong place to bring this up. First time posting here. There was just a couple things I wanted to bring to your attention.

1st Issue
The majority of flip cards (dowsing dagger, journey to eternity, thaumatic compass, other ixalan legendary flip lands, etc) do not show the correct picture for me in either the deck builder or in-game when creating the attached token. Instead, both show their image as a copy of the unflipped card (e.g. lost vale appears as an image of dowsing dagger in the deck editor, and the token for it in-game does as well).

I am aware this was being addressed at one point, due to this thread: https://github.com/Cockatrice/Cockatrice/issues/3503 but it says the fix would be going out in the next version. As you can see, that was in January, but I am still having the issue. I'm looking for confirmation as to if this should have been fixed and there's something I need to do on my end to fix it, or if it's still being worked on.

-- Edited by Zach to remove issues split into different tickets --

**Comment by ebbit1q** [comment]
This is not how our system works, please make separate issues for separate issues.
Except for 3, that's not actually a problem as it simply tells us that you forgot to update your card database. Causing issue 1 most likely. Please update your card database by running oracle and see if it still happens.

**Comment by Leechcraft** [comment]
Apologies; I didn't know they needed to be posted separately. Should I go ahead and create separate issues for each despite the current post then?

**Comment by skwerlman** [comment]
> Should I go ahead and create separate issues for each

Yes, please.

> When looking at the debug log, I noticed it's saying a few things were failing

Aside from you needing to rerun oracle, all of the messages in that particular log are totally normal.

**Comment by ctrlaltca** [comment]
About 1st Issue; try to reset the URL download list at Preferences -> Card sources -> Reset Download URLs. You should see that the first url in the list ends with `&face=!prop:side!`, that is the little bit indicating the face of the card that need to be shown.

**Comment by ZeldaZach** [comment]
Ctrlalt is correct here, this issue came about if you were using the beta before we added the new URL scheme.  If you're still having issues with this, please don't hesitate to reopen :)
