### ISSUE TITLE
Mac v2.7.0: Unable to create tokens from associated cards 

### ISSUE THREAD

**Issue by gwantan** [Cockatrice/Cockatrice#3626]
<b>System Information:</b>
Client Version: 2.7.0 (2019-03-03)
Client Operating System: macOS Mojave (10.14)
Build Architecture: 64-bit
Qt Version: 5.12.1
Server_CardZone destructor: "deck"
Server_CardZone destructor: "grave"
Server_CardZone destructor: "hand"
Server_CardZone destructor: "rfg"
Server_CardZone destructor: "sb"
Server_CardZone destructor: "stack"
Server_CardZone destructor: "table"
QPixmap::scaled: Pixmap is a null pixmap
Loaded from "/Users/kyle/Library/Application Support/Cockatrice/Cockatrice/decks/Legacy/zExperimental/Atarka Ramp.cod" - true
Deck was loaded - true
PictureLoader: [card:  "Birds of Paradise"  set:  "LEB" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Kozilek's Return"  set:  "OGW" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Birds of Paradise"  set:  "LEB" ]: Trying to load picture
PictureLoader: [card:  "Life from the Loam"  set:  "RAV" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Sejiri Steppe"  set:  "WWK" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Sylvan Library"  set:  "LEG" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Dryad Arbor"  set:  "FUT" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Dragonlord Atarka"  set:  "DTK" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Titania, Protector of Argoth"  set:  "CMA" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Choke"  set:  "TMP" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Scavenging Ooze"  set:  "CM2" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Knight of the Reliquary"  set:  "CON_" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Green Sun's Zenith"  set:  "MBS" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Swords to Plowshares"  set:  "LEB" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Bojuka Bog"  set:  "WWK" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Ancient Grudge"  set:  "TSP" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Sylvan Safekeeper"  set:  "JUD" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Pyroblast"  set:  "ICE" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Red Elemental Blast"  set:  "LEB" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Gaddock Teeg"  set:  "LRW" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Dark Depths"  set:  "CSP" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Karakas"  set:  "LEG" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Natural Order"  set:  "VIS" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Orcish Lumberjack"  set:  "ICE" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Thalia, Guardian of Thraben"  set:  "DKA" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Thespian's Stage"  set:  "GTC" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Crop Rotation"  set:  "ULG" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Pithing Needle"  set:  "SOK" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Scattered Groves"  set:  "PAKH" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Mox Diamond"  set:  "STH" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Savannah"  set:  "LEB" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Punishing Fire"  set:  "ZEN" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Plains"  set:  "UST" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Reclamation Sage"  set:  "C18" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Taiga"  set:  "LEB" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Windswept Heath"  set:  "ONS" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Forest"  set:  "UST" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Primeval Titan"  set:  "IMA" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Grove of the Burnwillows"  set:  "FUT" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Birds of Paradise"  set:  "LEB" ]: Picture found on disk.
PictureLoader: [card:  "Kozilek's Return"  set:  "OGW" ]: Trying to load picture
PictureLoader: [card:  "Kozilek's Return"  set:  "OGW" ]: Picture found on disk.
PictureLoader: [card:  "Life from the Loam"  set:  "RAV" ]: Trying to load picture
PictureLoader: [card:  "Life from the Loam"  set:  "RAV" ]: Picture found on disk.
PictureLoader: [card:  "Sejiri Steppe"  set:  "WWK" ]: Trying to load picture
PictureLoader: [card:  "Sejiri Steppe"  set:  "WWK" ]: Picture found on disk.
PictureLoader: [card:  "Sylvan Library"  set:  "LEG" ]: Trying to load picture
PictureLoader: [card:  "Birds of Paradise"  set:  "LEB" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Life from the Loam"  set:  "RAV" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Sylvan Library"  set:  "LEG" ]: Picture found on disk.
PictureLoader: [card:  "Dryad Arbor"  set:  "FUT" ]: Trying to load picture
PictureLoader: [card:  "Sylvan Library"  set:  "LEG" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Sejiri Steppe"  set:  "WWK" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Dryad Arbor"  set:  "FUT" ]: Picture found on disk.
PictureLoader: [card:  "Dragonlord Atarka"  set:  "DTK" ]: Trying to load picture
PictureLoader: [card:  "Kozilek's Return"  set:  "OGW" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Dragonlord Atarka"  set:  "DTK" ]: Picture found on disk.
PictureLoader: [card:  "Titania, Protector of Argoth"  set:  "CMA" ]: Trying to load picture
PictureLoader: [card:  "Titania, Protector of Argoth"  set:  "CMA" ]: Picture found on disk.
PictureLoader: [card:  "Choke"  set:  "TMP" ]: Trying to load picture
PictureLoader: [card:  "Choke"  set:  "TMP" ]: Picture found on disk.
PictureLoader: [card:  "Scavenging Ooze"  set:  "CM2" ]: Trying to load picture
PictureLoader: [card:  "Scavenging Ooze"  set:  "CM2" ]: Picture found on disk.
PictureLoader: [card:  "Knight of the Reliquary"  set:  "CON_" ]: Trying to load picture
PictureLoader: [card:  "Knight of the Reliquary"  set:  "CON_" ]: Picture found on disk.
PictureLoader: [card:  "Green Sun's Zenith"  set:  "MBS" ]: Trying to load picture
PictureLoader: [card:  "Green Sun's Zenith"  set:  "MBS" ]: Picture found on disk.
PictureLoader: [card:  "Swords to Plowshares"  set:  "LEB" ]: Trying to load picture
PictureLoader: [card:  "Swords to Plowshares"  set:  "LEB" ]: Picture found on disk.
PictureLoader: [card:  "Bojuka Bog"  set:  "WWK" ]: Trying to load picture
PictureLoader: [card:  "Bojuka Bog"  set:  "WWK" ]: Picture found on disk.
PictureLoader: [card:  "Ancient Grudge"  set:  "TSP" ]: Trying to load picture
PictureLoader: [card:  "Ancient Grudge"  set:  "TSP" ]: Picture found on disk.
PictureLoader: [card:  "Sylvan Safekeeper"  set:  "JUD" ]: Trying to load picture
PictureLoader: [card:  "Sylvan Safekeeper"  set:  "JUD" ]: Picture found on disk.
PictureLoader: [card:  "Pyroblast"  set:  "ICE" ]: Trying to load picture
PictureLoader: [card:  "Pyroblast"  set:  "ICE" ]: Picture found on disk.
PictureLoader: [card:  "Red Elemental Blast"  set:  "LEB" ]: Trying to load picture
PictureLoader: [card:  "Red Elemental Blast"  set:  "LEB" ]: Picture found on disk.
PictureLoader: [card:  "Gaddock Teeg"  set:  "LRW" ]: Trying to load picture
PictureLoader: [card:  "Gaddock Teeg"  set:  "LRW" ]: Picture found on disk.
PictureLoader: [card:  "Dark Depths"  set:  "CSP" ]: Trying to load picture
PictureLoader: [card:  "Dark Depths"  set:  "CSP" ]: Picture found on disk.
PictureLoader: [card:  "Karakas"  set:  "LEG" ]: Trying to load picture
PictureLoader: [card:  "Karakas"  set:  "LEG" ]: Picture found on disk.
PictureLoader: [card:  "Natural Order"  set:  "VIS" ]: Trying to load picture
PictureLoader: [card:  "Natural Order"  set:  "VIS" ]: Picture found on disk.
PictureLoader: [card:  "Orcish Lumberjack"  set:  "ICE" ]: Trying to load picture
PictureLoader: [card:  "Orcish Lumberjack"  set:  "ICE" ]: Picture found on disk.
PictureLoader: [card:  "Thalia, Guardian of Thraben"  set:  "DKA" ]: Trying to load picture
PictureLoader: [card:  "Thalia, Guardian of Thraben"  set:  "DKA" ]: Picture found on disk.
PictureLoader: [card:  "Thespian's Stage"  set:  "GTC" ]: Trying to load picture
PictureLoader: [card:  "Thespian's Stage"  set:  "GTC" ]: Picture found on disk.
PictureLoader: [card:  "Crop Rotation"  set:  "ULG" ]: Trying to load picture
PictureLoader: [card:  "Crop Rotation"  set:  "ULG" ]: Picture found on disk.
PictureLoader: [card:  "Pithing Needle"  set:  "SOK" ]: Trying to load picture
PictureLoader: [card:  "Pithing Needle"  set:  "SOK" ]: Picture found on disk.
PictureLoader: [card:  "Scattered Groves"  set:  "PAKH" ]: Trying to load picture
PictureLoader: [card:  "Scattered Groves"  set:  "PAKH" ]: Picture found on disk.
PictureLoader: [card:  "Mox Diamond"  set:  "STH" ]: Trying to load picture
PictureLoader: [card:  "Mox Diamond"  set:  "STH" ]: Picture found on disk.
PictureLoader: [card:  "Savannah"  set:  "LEB" ]: Trying to load picture
PictureLoader: [card:  "Savannah"  set:  "LEB" ]: Picture found on disk.
PictureLoader: [card:  "Punishing Fire"  set:  "ZEN" ]: Trying to load picture
PictureLoader: [card:  "Punishing Fire"  set:  "ZEN" ]: Picture found on disk.
PictureLoader: [card:  "Plains"  set:  "UST" ]: Trying to load picture
PictureLoader: [card:  "Plains"  set:  "UST" ]: Picture found on disk.
PictureLoader: [card:  "Reclamation Sage"  set:  "C18" ]: Trying to load picture
PictureLoader: [card:  "Reclamation Sage"  set:  "C18" ]: Picture found on disk.
PictureLoader: [card:  "Taiga"  set:  "LEB" ]: Trying to load picture
PictureLoader: [card:  "Taiga"  set:  "LEB" ]: Picture found on disk.
PictureLoader: [card:  "Windswept Heath"  set:  "ONS" ]: Trying to load picture
PictureLoader: [card:  "Windswept Heath"  set:  "ONS" ]: Picture found on disk.
PictureLoader: [card:  "Forest"  set:  "UST" ]: Trying to load picture
PictureLoader: [card:  "Forest"  set:  "UST" ]: Picture found on disk.
PictureLoader: [card:  "Primeval Titan"  set:  "IMA" ]: Trying to load picture
PictureLoader: [card:  "Primeval Titan"  set:  "IMA" ]: Picture found on disk.
PictureLoader: [card:  "Grove of the Burnwillows"  set:  "FUT" ]: Trying to load picture
PictureLoader: [card:  "Grove of the Burnwillows"  set:  "FUT" ]: Picture found on disk.
PictureLoader: [card:  "Birds of Paradise"  set:  "LEB" ]: Trying to load picture
PictureLoader: [card:  "Birds of Paradise"  set:  "LEB" ]: Picture found on disk.
PictureLoader: [card:  "Life from the Loam"  set:  "RAV" ]: Trying to load picture
PictureLoader: [card:  "Life from the Loam"  set:  "RAV" ]: Picture found on disk.
PictureLoader: [card:  "Sylvan Library"  set:  "LEG" ]: Trying to load picture
PictureLoader: [card:  "Sylvan Library"  set:  "LEG" ]: Picture found on disk.
PictureLoader: [card:  "Sejiri Steppe"  set:  "WWK" ]: Trying to load picture
PictureLoader: [card:  "Sejiri Steppe"  set:  "WWK" ]: Picture found on disk.
PictureLoader: [card:  "Kozilek's Return"  set:  "OGW" ]: Trying to load picture
PictureLoader: [card:  "Kozilek's Return"  set:  "OGW" ]: Picture found on disk.
addCounter: "Player 1" 0 "life"
addCounter: "Player 1" 1 "w"
addCounter: "Player 1" 2 "u"
addCounter: "Player 1" 3 "b"
addCounter: "Player 1" 4 "r"
addCounter: "Player 1" 5 "g"
addCounter: "Player 1" 6 "x"
addCounter: "Player 1" 7 "storm"
CardDragItem destructor
__________________________________________________________________________________________

Right-click (Control-click) to bring up context menu works fine. However, when right-clicking on a card that has associated tokens (e.g. Young Pyromancer, Monastery Mentor, Titania, Protector of Argoth) the option to create tokens does not appear.

Please see [this screenshot](https://xocall.com/debug-images/tokens-no-work.png) demonstrating this issue. Thank you.

**Comment by skwerlman** [comment]
Please update to 2.7.0_1. this is already fixed there.

**Comment by ZeldaZach** [comment]
Please make sure you ran `Oracle 2.7.0_1` (that's included inside the DMG. If you ran `Oracle 2.6.2`, you will have this issue since we changed how databases are formatted.

You can verify your database is correct by checking the 2nd line of your `cards.xml` file and seeing it says `cockatricedatabase_version="4"` in it. If you see =3, that means you ran the wrong Oracle.

**Comment by ZeldaZach** [comment]
Note: You're on 2.7.0, not 2.7.0_1 (which had a lot of major fixes released the same day). Please update and ensure your Oracle is updated too. Re-open if you have problems :)

**Comment by gwantan** [comment]
Nifty, thank you.
