### ISSUE TITLE
Artifact Lands

### ISSUE THREAD

**Issue by Moonlight-Cockatrice** [Cockatrice/Cockatrice#3627]
<b>System Information:</b>
  

  
__________________________________________________________________________________________

  
It seems my issue was not read in full before being closed. The linked issue referred to artifact creatures, which has been fixed, however artifact lands are still being displayed as artifacts and going to the stack, which they don't use.

**Comment by Moonlight-Cockatrice** [comment]
If I'm mistaken and this has been fixed in the newest client version, then the in-client update checker isn't notifying of the newest version, as it tells me I'm up to date.

**Comment by ctrlaltca** [comment]
Sorry, i reopened your previous ticket #3621 while you were creating this new one.. I'll keep the older one open, and close this one, since #3621 already contains some possibly useful informations for other people with the same problem.
