### ISSUE TITLE
Ixalan Flip Lands Using Wrong Image

### ISSUE THREAD

**Issue by Leechcraft** [Cockatrice/Cockatrice#3629]
<b>System Information:</b>
Client Version: 2.7.0 (2019-03-04)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.9.7
System Locale: en_US
Install Mode: Standard
__________________________________________________________________________________________
The majority of flip cards (dowsing dagger, journey to eternity, thaumatic compass, other ixalan legendary flip lands, etc) do not show the correct picture for me in either the deck builder or in-game when creating the attached token. Instead, both show their image as a copy of the unflipped card (e.g. lost vale appears as an image of dowsing dagger in the deck editor, and the token attachment for it in-game does as well).

I am aware this was being addressed at one point, due to this thread: #3503 but it says the fix would be going out in the next version. As you can see, that was in January, but I am still having the issue. I'm looking for confirmation as to if this should have been fixed and there's something more I need to do on my own end to fix it, or if it's still being worked on.

I have attempted running the oracle, resetting the download list, and completely reinstalling Cockatrice; all to no effect.

**Comment by ctrlaltca** [comment]
> I have attempted running the oracle, resetting the download list,

A debug log would be nice, i suppose it would show that cockatrice is loading cached images from the disk. When Cockatrice downloads a card picture, it saves the downloaded image to disk to avoid having to download it over and over again.

These images are saved inside you user's Cockatrice profile directory. An easy way to get to that directory is opening a deck editor and clicking on the "Card database menu", then "open custom image folder".
An explorer/finder window will open in the "CUSTOM" folder, just go up one directory and enter the "downloadedPics" folder instead.

Try to locate the image file for a broken card (eg. "Lost Vale" for "dowsing dagger") and delete it.
Restart cockatrice to ensure it doesn't use a copy of the picture from memory, and try to see if the card has the correct image now.
If it does, you can delete the wrong images one by one or, if you don't mind about having to download them all, all at once. To delete all the images just delete the whole contents of the "downloadedPics" folder or use the "Delete Downloaded Images" from Preferences -> Card sources

**Comment by ctrlaltca** [comment]
Almost forgot: if it still doesn't work, please click on the menu Help -> "view debug log" and copypaste the contents of the dialog in a comment here.

**Comment by Leechcraft** [comment]
Deleting them from the downloadedPics folder worked. Thank you!
