### ISSUE TITLE
More Shortcut Options?

### ISSUE THREAD

**Issue by Aureth96** [Cockatrice/Cockatrice#3636]
<b>System Information:</b>
Client Version: 2.6.2 (2018-12-20)
Windows 10
  
__________________________________________________________________________________________
I would like to be able to use more complicated shortcuts. For instance, when choosing the shortcut for Set White Counter I'd like to be able to use [Ins+W], or maybe [F1+W]. Also, I don't know if it's reasonable, but the only time that I would ever hold down two letters at the same time would be to execute a shortcut so, I would also appreciate it if a shortcut could use a combination of letters such as, [M+I+L] for move top card to graveyard once or [M+I+P] for more than one. I understand if the multiple letters hotkey is too easy to trigger at two letters when typing in chat, so maybe only three or more, or possibly a non-letter key must be a part of the hotkey.

**Comment by ctrlaltca** [comment]
As far as i know you can't have key shortcuts where more than a key is pressed at the same time.
Only one key is supported with one or more "modificators" keys: Shift, Ctrl, Alt, Meta (Win)

Al an alternative, you can use a sequence of keys, eg. pressing M, then pressing I, then pressing P, but currently the preference pane doesn't permit you to add an hotkey with this syntax.

You can try to open shortcuts.ini in you cockatrice's profile and add something like:
```
[Custom]
TabDeckEditor\aExportDeckDecklist="S, H, I, T"
```
Pressing the 4 keys in sequence, one at a time, will trigger the associated action (in this example, "export the deck list").

**Comment by ebbit1q** [comment]
There is no reasonable way for us to implement this, this isn't a limitation on our side.
If you really wanted this you'd have to modify your keyboard or use special automation software like autohotkey.
I'm closing this as a won't fix.
