### ISSUE TITLE
Custom Cards No Longer Work (empty card relations)

### ISSUE THREAD

**Issue by Shaldares** [Cockatrice/Cockatrice#3637]
<b>System Information:</b>
Client Version: 2.7.0 (2019-03-04)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.9.7
System Locale: en_US
Install Mode: Standard
---------------------------------------------------------------------------
Theme changed: "Plasma"
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
Language changed: ""
main(): starting main program
Spoilers Disabled
CardDatabase::loadCardDatabases start
[CockatriceXml3Parser] Trying to parse:  "C:/Users/Shald/AppData/Local/Cockatrice/Cockatrice/cards.xml"
[CockatriceXml3Parser] Parsing failed: wrong version 4
[CockatriceXml4Parser] Trying to parse:  "C:/Users/Shald/AppData/Local/Cockatrice/Cockatrice/cards.xml"
main(): MainWindow constructor finished
main(): ui.show() finished
PictureLoader: cache fail for "_trice_card_back_226471"
PictureLoader: [card:  "Zzzyxas's Abyss"  set:  "UNH" ]: Trying to load picture
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Shald/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 19298 Sets= 442
[CockatriceXml3Parser] Trying to parse:  "C:/Users/Shald/AppData/Local/Cockatrice/Cockatrice/tokens.xml"
PictureLoader: [card:  "Zzzyxas's Abyss"  set:  "UNH" ]: Picture found on disk.
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Shald/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 19713 Sets= 443
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Shald/AppData/Local/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 19713 Sets= 443
[CockatriceXml3Parser] Trying to parse:  "C:/Users/Shald/AppData/Local/Cockatrice/Cockatrice/customsets/Aye.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Shald/AppData/Local/Cockatrice/Cockatrice/customsets/Aye.xml" Status = 0 Cards = 19735 Sets= 444
[CockatriceXml3Parser] Trying to parse:  "C:/Users/Shald/AppData/Local/Cockatrice/Cockatrice/customsets/TK.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Shald/AppData/Local/Cockatrice/Cockatrice/customsets/TK.xml" Status = 0 Cards = 19735 Sets= 444
CardDatabase::loadCardDatabases success
PictureLoader: [card:  "Godly Grime"  set:  "AYE" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Godly Grime"  set:  "AYE" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Godly Grime"  set:  "AYE" ]: Requested set property ( "muid" ) for Url template ( "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Godly Grime"  set:  "AYE" ]: Trying to load picture
PictureLoader: [card:  "Godly Grime"  set:  "AYE" ]: Picture found on disk.
__________________________________________________________________________________________

I have some custom cards in a set that I use on cockatrice. Prior to version 2.7.0, these cards worked fine. However, now, whenever I try to put a custom card onto the battlefield, the client freezes up and then crashes.

**Comment by ebbit1q** [comment]
Can you please give us the xml of the custom cards? This is a very serious issue and should never have happened.

**Comment by Shaldares** [comment]
`<cockatrice_carddatabase version="3">
 <cards>
	<card>
	 <name>Ayeli, Scurvy Pilgrim</name>
	 <set picURL="https://mtgcardsmith.com/view/complete/full/2019/2/7/1549520753113516.png">AYE</set>
	 <manacost>WB</manacost>
	 <cmc>2</cmc>
	 <type>Legendary Creature</type>
	 <pt>2/3</pt>
	 <tablerow>2</tablerow>
	 <text></text>
	</card>

	<card>
	 <name>Anthraxos, God of Passion</name>
	 <set picURL="https://mtgcardsmith.com/view/complete/full/2019/2/7/1549522239710762.png">AYE</set>
	 <related></related>
	 <color></color>
	 <manacost>1WB</manacost>
	 <cmc>3</cmc>
	 <type>Creature</type>
	 <pt>5/4</pt>
	 <tablerow>2</tablerow>
	 <text></text>
	</card>

	<card>
	 <name>Mortyfy</name>
	 <set picURL="https://mtgcardsmith.com/view/complete/full/2019/2/7/1549523981434211.png">AYE</set>
	 <related></related>
	 <color></color>
	 <manacost>1WB</manacost>
	 <cmc>3</cmc>
	 <type>Instant</type>
	 <tablerow>3</tablerow>
	 <text></text>
	</card>

	<card>
	 <name>Ajani's Welcome Party</name>
	 <set picURL="https://mtgcardsmith.com/view/complete/full/2019/2/7/1549525251958326.png">AYE</set>
	 <related></related>
	 <color></color>
	 <manacost>W</manacost>
	 <cmc>1</cmc>
	 <type>Enchantment</type>
	 <pt></pt>
	 <loyalty></loyalty>
	 <tablerow>1</tablerow>
	 <text></text>
	 <token></token>
	 <cipt></cipt>
	</card>

	<card>
	 <name>Swamp1</name>
	 <set picURL="https://mtgcardsmith.com/view/complete/full/2018/8/5/1533530091502007.png">AYE</set>
	 <related></related>
	 <color></color>
	 <manacost></manacost>
	 <cmc></cmc>
	 <type>Land</type>
	 <pt></pt>
	 <loyalty></loyalty>
	 <tablerow>0</tablerow>
	 <text></text>
	 <token></token>
	 <cipt></cipt>
	</card>

	<card>
	 <name>Swamp2</name>
	 <set picURL="https://mtgcardsmith.com/view/complete/full/2018/7/28/1532798777118234.png">AYE</set>
	 <related></related>
	 <color></color>
	 <manacost></manacost>
	 <cmc></cmc>
	 <type>Land</type>
	 <pt></pt>
	 <loyalty></loyalty>
	 <tablerow>0</tablerow>
	 <text></text>
	 <token></token>
	 <cipt></cipt>
	</card>

	<card>
	 <name>Swamp3</name>
	 <set picURL="https://mtgcardsmith.com/view/complete/full/2018/12/4/1543908970664583.png">AYE</set>
	 <related></related>
	 <color></color>
	 <manacost></manacost>
	 <cmc></cmc>
	 <type>Land</type>
	 <pt></pt>
	 <loyalty></loyalty>
	 <tablerow>0</tablerow>
	 <text></text>
	 <token></token>
	 <cipt></cipt>
	</card>

	<card>
	 <name>Plains1</name>
	 <set picURL="https://mtgcardsmith.com/view/complete/full/2018/8/5/1533525679987034.png">AYE</set>
	 <related></related>
	 <color></color>
	 <manacost></manacost>
	 <cmc></cmc>
	 <type>Land</type>
	 <pt></pt>
	 <loyalty></loyalty>
	 <tablerow>0</tablerow>
	 <text></text>
	 <token></token>
	 <cipt></cipt>
	</card>

	<card>
	 <name>Plains2</name>
	 <set picURL="https://mtgcardsmith.com/view/complete/full/2018/6/5/1528254999405141.png">AYE</set>
	 <related></related>
	 <color></color>
	 <manacost></manacost>
	 <cmc></cmc>
	 <type>Land</type>
	 <pt></pt>
	 <loyalty></loyalty>
	 <tablerow>0</tablerow>
	 <text></text>
	 <token></token>
	 <cipt></cipt>
	</card>

	<card>
	 <name>Plains3</name>
	 <set picURL="https://mtgcardsmith.com/view/complete/full/2018/5/23/1527122401219769.png">AYE</set>
	 <related></related>
	 <color></color>
	 <manacost></manacost>
	 <cmc></cmc>
	 <type>Land</type>
	 <pt></pt>
	 <loyalty></loyalty>
	 <tablerow>0</tablerow>
	 <text></text>
	 <token></token>
	 <cipt></cipt>
	</card>

	<card>
	 <name>Godly Grime</name>
	 <set picURL="https://mtgcardsmith.com/view/complete/full/2019/2/7/1549590589652722.png">AYE</set>
	 <related></related>
	 <color></color>
	 <manacost></manacost>
	 <cmc></cmc>
	 <type>Land</type>
	 <pt></pt>
	 <loyalty></loyalty>
	 <tablerow>0</tablerow>
	 <text></text>
	 <token></token>
	 <cipt></cipt>
	</card>

	<card>
	 <name>Isolinear Chipple</name>
	 <set picURL="https://mtgcardsmith.com/view/complete/full/2019/2/7/1549593349811729.png">AYE</set>
	 <related></related>
	 <color></color>
	 <manacost></manacost>
	 <cmc></cmc>
	 <type>Land</type>
	 <pt></pt>
	 <loyalty></loyalty>
	 <tablerow>0</tablerow>
	 <text></text>
	 <token></token>
	 <cipt></cipt>
	</card>

	<card>
	 <name>Marshall's Flat</name>
	 <set picURL="https://mtgcardsmith.com/view/complete/full/2019/2/7/1549594544646347.png">AYE</set>
	 <related>CFD Ghost Gen.</related>
	 <color></color>
	 <manacost></manacost>
	 <cmc></cmc>
	 <type>Land</type>
	 <pt></pt>
	 <loyalty></loyalty>
	 <tablerow>0</tablerow>
	 <text></text>
	 <token></token>
	 <cipt></cipt>
	</card>

	<card>
	 <name>CFD Ghost Gen.</name>
	 <set picURL="https://mtgcardsmith.com/view/complete/full/2019/2/7/1549595181724653.png">AYE</set>
	 <related></related>
	 <color></color>
	 <manacost></manacost>
	 <cmc></cmc>
	 <type>Token</type>
	 <pt></pt>
	 <loyalty></loyalty>
	 <tablerow>3</tablerow>
	 <text></text>
	 <token>1</token>
	 <cipt></cipt>
	</card>

	<card>
	 <name>Catheter Membrane</name>
	 <set picURL="https://mtgcardsmith.com/view/complete/full/2019/2/7/1549598218407371.png">AYE</set>
	 <related></related>
	 <color></color>
	 <manacost></manacost>
	 <cmc></cmc>
	 <type>Creature</type>
	 <pt>0/3</pt>
	 <loyalty></loyalty>
	 <tablerow>2</tablerow>
	 <text></text>
	 <token></token>
	 <cipt></cipt>
	</card>

	<card>
	 <name>Verndercehrt</name>
	 <set picURL="https://mtgcardsmith.com/view/complete/full/2019/2/7/1549602103925613.png">AYE</set>
	 <related></related>
	 <color></color>
	 <manacost></manacost>
	 <cmc></cmc>
	 <type>Sorcery</type>
	 <pt></pt>
	 <loyalty></loyalty>
	 <tablerow>3</tablerow>
	 <text></text>
	 <token></token>
	 <cipt></cipt>
	</card>

	<card>
	 <name>Hidden Crocpile</name>
	 <set picURL="https://mtgcardsmith.com/view/complete/full/2019/2/7/1549601801988440.png">AYE</set>
	 <related>Servo</related>
	 <color></color>
	 <manacost></manacost>
	 <cmc></cmc>
	 <type>Enchantment</type>
	 <pt></pt>
	 <loyalty></loyalty>
	 <tablerow>1</tablerow>
	 <text></text>
	 <token></token>
	 <cipt></cipt>
	</card>

	<card>
	 <name>Brave The Man</name>
	 <set picURL="https://mtgcardsmith.com/view/complete/full/2019/2/8/1549609282055424.png">AYE</set>
	 <related></related>
	 <color></color>
	 <manacost></manacost>
	 <cmc></cmc>
	 <type>Enchantment</type>
	 <pt></pt>
	 <loyalty></loyalty>
	 <tablerow>1</tablerow>
	 <text></text>
	 <token></token>
	 <cipt></cipt>
	</card>

	<card>
	 <name>Twilight Grover</name>
	 <set picURL="https://mtgcardsmith.com/view/complete/full/2019/2/8/1549610489955005.png">AYE</set>
	 <related>Spirit</related>
	 <color></color>
	 <manacost></manacost>
	 <cmc></cmc>
	 <type>Creature</type>
	 <pt>1/1</pt>
	 <loyalty></loyalty>
	 <tablerow>3</tablerow>
	 <text></text>
	 <token>2</token>
	 <cipt></cipt>
	</card>

	<card>
	 <name>Hero of Hilthold</name>
	 <set picURL="https://mtgcardsmith.com/view/complete/full/2019/2/8/1549614531515428.png">AYE</set>
	 <related>Soldier</related>
	 <color></color>
	 <manacost></manacost>
	 <cmc></cmc>
	 <type>Creature</type>
	 <pt>3/4</pt>
	 <loyalty></loyalty>
	 <tablerow>2</tablerow>
	 <text></text>
	 <token>2</token>
	 <cipt></cipt>
	</card>

	<card>
	 <name>Zealot Persecution</name>
	 <set picURL="https://mtgcardsmith.com/view/complete/full/2019/2/8/1549611766827979.png">AYE</set>
	 <related></related>
	 <color></color>
	 <manacost></manacost>
	 <cmc></cmc>
	 <type>Instant</type>
	 <pt></pt>
	 <loyalty></loyalty>
	 <tablerow>3</tablerow>
	 <text></text>
	 <token></token>
	 <cipt></cipt>
	</card>

	<card>
	 <name>Ghost-Honed Monk</name>
	 <set picURL="https://mtgcardsmith.com/view/complete/full/2019/2/8/1549613135390815.png">AYE</set>
	 <related>Spirit</related>
	 <color></color>
	 <manacost></manacost>
	 <cmc></cmc>
	 <type>Creature</type>
	 <pt>1/1</pt>
	 <loyalty></loyalty>
	 <tablerow>2</tablerow>
	 <text></text>
	 <token>2</token>
	 <cipt></cipt>
	</card>

 </cards>
</cockatrice_carddatabase>

`

I know that some of the tags are missing, but in the tutorial I read, it said that you can omit unneeded lines. I've never had issues with it before.

**Comment by ebbit1q** [comment]
This issue is fixed and will be in a beta release soon.
