### ISSUE TITLE
Some cards no longer in English

### ISSUE THREAD

**Issue by NotTooSharp** [Cockatrice/Cockatrice#3642]
<b>System Information:</b>
 Client Version: 2.7.0 (2019-03-04)
PictureLoader: [card:  "Secluded Steppe"  set:  "WC04" ]: Requested set property ( "muid" ) for Url template ( "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Secluded Steppe"  set:  "WC04" ]: Trying to load picture
PictureLoader: [card:  "Secluded Steppe"  set:  "WC04" ]: Picture found on disk.
PictureLoader: [card:  "Wall of Fire"  set:  "FBB" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Wall of Fire"  set:  "FBB" ]: Requested set property ( "muid" ) for Url template ( "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Wall of Fire"  set:  "FBB" ]: Trying to load picture
PictureLoader: [card:  "Wall of Fire"  set:  "FBB" ]: Picture found on disk.
PictureLoader: [card:  "Battlefield Forge"  set:  "ORI" ]: Trying to load picture
PictureLoader: [card:  "Battlefield Forge"  set:  "ORI" ]: Picture found on disk.
PictureLoader: [card:  "Field of Ruin"  set:  "XLN" ]: Trying to load picture
PictureLoader: [card:  "Field of Ruin"  set:  "XLN" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Field of Ruin"  set:  "XLN" ]: Trying to download picture from url: "https://api.scryfall.com/cards/d72afb21-7bb0-4fd8-a529-ada92a654f61?format=image&face=front"
PictureLoader: [card:  "Field of Ruin"  set:  "XLN" ]: following redirect: "https://img.scryfall.com/cards/large/en/xln/254.jpg?1527431443"
PictureLoader: [card:  "Field of Ruin"  set:  "XLN" ]: Image successfully downloaded from  "https://img.scryfall.com/cards/large/en/xln/254.jpg?1527431443"
PictureLoader: [card:  "Nevinyrral's Disk"  set:  "FBB" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Nevinyrral's Disk"  set:  "FBB" ]: Requested set property ( "muid" ) for Url template ( "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Nevinyrral's Disk"  set:  "FBB" ]: Trying to load picture
PictureLoader: [card:  "Nevinyrral's Disk"  set:  "FBB" ]: Picture found on disk.
PictureLoader: [card:  "Nykthos, Shrine to Nyx"  set:  "THS" ]: Trying to load picture
PictureLoader: [card:  "Nykthos, Shrine to Nyx"  set:  "THS" ]: Picture found on disk.
PictureLoader: [card:  "Dancing Scimitar"  set:  "SUM" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Dancing Scimitar"  set:  "SUM" ]: Requested set property ( "muid" ) for Url template ( "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Dancing Scimitar"  set:  "SUM" ]: Trying to load picture
PictureLoader: [card:  "Dancing Scimitar"  set:  "SUM" ]: Picture found on disk.
PictureLoader: [card:  "Ancient Silverback"  set:  "M15" ]: Trying to load picture
PictureLoader: [card:  "Ancient Silverback"  set:  "M15" ]: Picture found on disk.
PictureLoader: [card:  "Where Ancients Tread"  set:  "C13" ]: Trying to load picture
PictureLoader: [card:  "Where Ancients Tread"  set:  "C13" ]: Picture found on disk.
PictureLoader: [card:  "Opaline Bracers"  set:  "5DN" ]: Trying to load picture
PictureLoader: [card:  "Opaline Bracers"  set:  "5DN" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Opaline Bracers"  set:  "5DN" ]: Trying to download picture from url: "https://api.scryfall.com/cards/3ae84edd-1294-4722-89d1-84d9f336871c?format=image&face=front"
PictureLoader: [card:  "Opaline Bracers"  set:  "5DN" ]: following redirect: "https://img.scryfall.com/cards/large/en/5dn/141.jpg?1517813031"
PictureLoader: [card:  "Opaline Bracers"  set:  "5DN" ]: Image successfully downloaded from  "https://img.scryfall.com/cards/large/en/5dn/141.jpg?1517813031"
PictureLoader: [card:  "Opal Palace"  set:  "CM2" ]: Trying to load picture
PictureLoader: [card:  "Opal Palace"  set:  "CM2" ]: Picture found on disk.
PictureLoader: [card:  "Kor Chant"  set:  "TPR" ]: Trying to load picture
PictureLoader: [card:  "Kor Chant"  set:  "TPR" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Kor Chant"  set:  "TPR" ]: Trying to download picture from url: "https://api.scryfall.com/cards/27e20ee1-ab61-463b-b516-0a883d9c7c39?format=image&face=front"
PictureLoader: [card:  "Kor Chant"  set:  "TPR" ]: following redirect: "https://img.scryfall.com/cards/large/en/tpr/17.jpg?1517813031"
PictureLoader: [card:  "Kor Chant"  set:  "TPR" ]: Image successfully downloaded from  "https://img.scryfall.com/cards/large/en/tpr/17.jpg?1517813031"
PictureLoader: [card:  "Colossus of Sardia"  set:  "RIN" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Colossus of Sardia"  set:  "RIN" ]: Requested set property ( "muid" ) for Url template ( "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Colossus of Sardia"  set:  "RIN" ]: Trying to load picture
PictureLoader: [card:  "Colossus of Sardia"  set:  "RIN" ]: Picture found on disk.
PictureLoader: [card:  "Commune with Nature"  set:  "MM2" ]: Trying to load picture
PictureLoader: [card:  "Commune with Nature"  set:  "MM2" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Commune with Nature"  set:  "MM2" ]: Trying to download picture from url: "https://api.scryfall.com/cards/a59eafb3-3ce6-4056-a7f7-8d0a8fc12294?format=image&face=front"
PictureLoader: [card:  "Commune with Nature"  set:  "MM2" ]: following redirect: "https://img.scryfall.com/cards/large/en/mm2/142.jpg?1517813031"
PictureLoader: [card:  "Siege-Gang Commander"  set:  "PDOM" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Siege-Gang Commander"  set:  "PDOM" ]: Requested set property ( "muid" ) for Url template ( "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Commune with Nature"  set:  "MM2" ]: Image successfully downloaded from  "https://img.scryfall.com/cards/large/en/mm2/142.jpg?1517813031"
PictureLoader: [card:  "Siege-Gang Commander"  set:  "PDOM" ]: Trying to load picture
PictureLoader: [card:  "Siege-Gang Commander"  set:  "PDOM" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Siege-Gang Commander"  set:  "PDOM" ]: Trying to download picture from url: "https://api.scryfall.com/cards/31633ee1-d13d-4abf-bff4-20baa26f3b89?format=image&face=front"
PictureLoader: [card:  "Siege-Gang Commander"  set:  "PDOM" ]: following redirect: "https://img.scryfall.com/cards/large/en/pdom/143s.jpg?1525116032"
PictureLoader: [card:  "Siege-Gang Commander"  set:  "PDOM" ]: Image successfully downloaded from  "https://img.scryfall.com/cards/large/en/pdom/143s.jpg?1525116032"
PictureLoader: [card:  "Rushblade Commander"  set:  "BBD" ]: Trying to load picture
PictureLoader: [card:  "Rushblade Commander"  set:  "BBD" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Rushblade Commander"  set:  "BBD" ]: Trying to download picture from url: "https://api.scryfall.com/cards/f654a0de-50aa-448d-9bad-0870b32a0a49?format=image&face=front"
PictureLoader: [card:  "Rushblade Commander"  set:  "BBD" ]: following redirect: "https://img.scryfall.com/cards/large/en/bbd/77.jpg?1529061600"
PictureLoader: [card:  "Command Beacon"  set:  "PZ1" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Command Beacon"  set:  "PZ1" ]: Requested set property ( "muid" ) for Url template ( "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Rushblade Commander"  set:  "BBD" ]: Image successfully downloaded from  "https://img.scryfall.com/cards/large/en/bbd/77.jpg?1529061600"
PictureLoader: [card:  "Command Beacon"  set:  "PZ1" ]: Trying to load picture
PictureLoader: [card:  "Command Beacon"  set:  "PZ1" ]: Picture found on disk.
PictureLoader: [card:  "Izzet Chemister"  set:  "PZ2" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Izzet Chemister"  set:  "PZ2" ]: Requested set property ( "muid" ) for Url template ( "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Izzet Chemister"  set:  "PZ2" ]: Trying to load picture
PictureLoader: [card:  "Izzet Chemister"  set:  "PZ2" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Izzet Chemister"  set:  "PZ2" ]: Trying to download picture from url: "https://api.scryfall.com/cards/881a3ee1-a559-44c8-ae0e-656a2710d040?format=image&face=front"
PictureLoader: [card:  "Izzet Chemister"  set:  "PZ2" ]: following redirect: "https://img.scryfall.com/cards/large/en/pz2/65741.jpg?1517813031"
PictureLoader: [card:  "Izzet Chemister"  set:  "PZ2" ]: Image successfully downloaded from  "https://img.scryfall.com/cards/large/en/pz2/65741.jpg?1517813031"
PictureLoader: [card:  "Cathedral Sanctifier"  set:  "DDQ" ]: Trying to load picture
PictureLoader: [card:  "Cathedral Sanctifier"  set:  "DDQ" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Cathedral Sanctifier"  set:  "DDQ" ]: Trying to download picture from url: "https://api.scryfall.com/cards/de3d0a45-3b3a-4718-9cb8-ff0c2464d634?format=image&face=front"
PictureLoader: [card:  "Cathedral Sanctifier"  set:  "DDQ" ]: following redirect: "https://img.scryfall.com/cards/large/en/ddq/3.jpg?1517813031"
PictureLoader: [card:  "Cathedral Sanctifier"  set:  "DDQ" ]: Image successfully downloaded from  "https://img.scryfall.com/cards/large/en/ddq/3.jpg?1517813031"
PictureLoader: [card:  "Cathedral of Serra"  set:  "LEG" ]: Trying to load picture
PictureLoader: [card:  "Cathedral of Serra"  set:  "LEG" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Cathedral of Serra"  set:  "LEG" ]: Trying to download picture from url: "https://api.scryfall.com/cards/e65356e6-0ead-49fd-b069-be1ea9b1c105?format=image&face=front"
PictureLoader: [card:  "Cathedral of Serra"  set:  "LEG" ]: following redirect: "https://img.scryfall.com/cards/large/en/leg/301.jpg?1517813031"
PictureLoader: [card:  "Cathedral of Serra"  set:  "LEG" ]: Image successfully downloaded from  "https://img.scryfall.com/cards/large/en/leg/301.jpg?1517813031"
PictureLoader: [card:  "Cathedral of War"  set:  "PRM" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Cathedral of War"  set:  "PRM" ]: Requested set property ( "muid" ) for Url template ( "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Cathedral of War"  set:  "PRM" ]: Trying to load picture
PictureLoader: [card:  "Cathedral of War"  set:  "PRM" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Cathedral of War"  set:  "PRM" ]: Trying to download picture from url: "https://api.scryfall.com/cards/f940fd28-86b7-49d9-8f2c-a324c9f7ddc6?format=image&face=front"
PictureLoader: [card:  "Cathedral of War"  set:  "PRM" ]: following redirect: "https://img.scryfall.com/cards/large/en/prm/45215.jpg?1517813031"
PictureLoader: [card:  "Cathedral of War"  set:  "PRM" ]: Image successfully downloaded from  "https://img.scryfall.com/cards/large/en/prm/45215.jpg?1517813031"
PictureLoader: [card:  "Plague Wind"  set:  "A25" ]: Trying to load picture
PictureLoader: [card:  "Plague Wind"  set:  "A25" ]: Picture found on disk.
PictureLoader: [card:  "Windborn Muse"  set:  "C16" ]: Trying to load picture
PictureLoader: [card:  "Windborn Muse"  set:  "C16" ]: Picture found on disk.
PictureLoader: [card:  "Windbrisk Heights"  set:  "C16" ]: Trying to load picture
PictureLoader: [card:  "Windbrisk Heights"  set:  "C16" ]: Picture found on disk.
PictureLoader: [card:  "Plains"  set:  "PSS2" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Plains"  set:  "PSS2" ]: Requested set property ( "muid" ) for Url template ( "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Plains"  set:  "PSS2" ]: Trying to load picture
PictureLoader: [card:  "Plains"  set:  "PSS2" ]: Picture found on disk.
CardDatabase::loadCardDatabases start
[CockatriceXml3Parser] Trying to parse:  "C:/Users/Admin/AppData/Local/Cockatrice/Cockatrice/cards.xml"
[CockatriceXml3Parser] Parsing failed: wrong version 4
[CockatriceXml4Parser] Trying to parse:  "C:/Users/Admin/AppData/Local/Cockatrice/Cockatrice/cards.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Admin/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 19300 Sets= 443
[CockatriceXml3Parser] Trying to parse:  "C:/Users/Admin/AppData/Local/Cockatrice/Cockatrice/tokens.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Admin/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 19715 Sets= 444
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Admin/AppData/Local/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 19715 Sets= 444
CardDatabase::loadCardDatabases success
PictureLoader: [card:  "_____"  set:  "UNH" ]: Trying to load picture
PictureLoader: [card:  "_____"  set:  "UNH" ]: Picture found on disk.
PictureLoader: [card:  "Wasp"  set:  "10E" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Wasp"  set:  "10E" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Wasp"  set:  "10E" ]: Requested set property ( "muid" ) for Url template ( "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Wasp"  set:  "10E" ]: Trying to load picture
PictureLoader: [card:  "Wasp"  set:  "10E" ]: Picture found on disk.
PictureLoader: [card:  "Goblin King"  set:  "SUM" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Goblin King"  set:  "SUM" ]: Requested set property ( "muid" ) for Url template ( "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Goblin King"  set:  "SUM" ]: Trying to load picture
PictureLoader: [card:  "Goblin King"  set:  "SUM" ]: Picture found on disk.
PictureLoader: [card:  "Lightning Elemental"  set:  "PS11" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Lightning Elemental"  set:  "PS11" ]: Requested set property ( "muid" ) for Url template ( "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Lightning Elemental"  set:  "PS11" ]: Trying to load picture
PictureLoader: [card:  "Lightning Elemental"  set:  "PS11" ]: Picture found on disk.
PictureLoader: [card:  "Lightning Greaves"  set:  "PSAL" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Lightning Greaves"  set:  "PSAL" ]: Requested set property ( "muid" ) for Url template ( "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Lightning Greaves"  set:  "PSAL" ]: Trying to load picture
PictureLoader: [card:  "Lightning Greaves"  set:  "PSAL" ]: Picture found on disk.
Searching for updates on the channel:  "https://api.github.com/repos/Cockatrice/Cockatrice/releases/latest"
Current hash= "55c4207" update hash= ""
Got reply from release server, name= "Cockatrice 2.7.0: Marchesa's Revenge" desc= "https://github.com/Cockatrice/Cockatrice/releases/tag/2019-03-04-Release-2.7.0" date= QDate("2019-03-04") url= "https://github.com/Cockatrice/Cockatrice/releases/download/2019-03-04-Release-2.7.0/Cockatrice-Marchesas-Revenge-2.7.0_1-win64.exe"
Searching for commit hash corresponding to stable channel tag:  "2019-03-04-Release-2.7.0"
Got reply from tag server, commit= "55c4207182a2a99965f22b4df4ee5d45dc163175"
Current hash= "55c4207" update hash= "55c4207"
Error: Spoiler.xml not found or not deleted
QLayout: Attempting to add QLayout "" to ShortcutsTab "shortcutsTab", which already has a layout
Card Database load status:  0
__________________________________________________________________________________________

  Some of the cards in the database are no longer in English. For example, "Lightning Greaves" are now "Schinieri del Fulmini". They still come up when searching for Lightning Greaves but the card is no longer in English despite retrieving the English card database. Other cards have been affected as well, such as "Leonin Shikari". I'm sure there are others but these are just the two I remember from the last deck I built.

**Comment by ctrlaltca** [comment]
About "Lightning Greaves", the card image with the wrong language is currently being loaded from your disk:
```
PictureLoader: [card: "Lightning Greaves" set: "PSAL" ]: Trying to load picture
PictureLoader: [card: "Lightning Greaves" set: "PSAL" ]: Picture found on disk.
```
In fact it looks like the image source only has the italian cad image for the set PSAL:
https://scryfall.com/search?q=%22Lightning+Greaves%22+set%3Apsal+lang%3Aany&unique=prints&as=grid&order=name
You may want to disable or lower the priority of that set.

**Comment by ebbit1q** [comment]
We have added more sets to cockatrice, unfortunately to some this includes a few non english sets which take precedence in the image fetching process.

For now you'll have to manually disable them:
![image](https://user-images.githubusercontent.com/36401181/54084892-52078e80-4337-11e9-9f62-e2a09a0d6173.png)
Under the menu "Card database" select "Manage sets"
![image](https://user-images.githubusercontent.com/36401181/54084903-8b3ffe80-4337-11e9-9095-9103164e8e23.png)
A window will open, type PSAL into the search bar.
![image](https://user-images.githubusercontent.com/36401181/54084911-b1659e80-4337-11e9-8e4d-9dc458490488.png)
Uncheck the checkbox in front of it.

You can do the same for the sets PS11. FBB and REN
![image](https://user-images.githubusercontent.com/36401181/54084929-ed006880-4337-11e9-8bcf-4c06fb615b22.png)
When you're done simply click the OK button.

**Comment by ebbit1q** [comment]
Linking #3623

**Comment by ctrlaltca** [comment]
Didn't see a ticket was already in place for this problem. Closing, please follow #3623 for updates.

**Comment by tooomm** [comment]
@ctrlaltca As long as there is at least no (pre)release we could keep this important/recurring issues pinned to help users find them. Even if they are fixed already 👍

**Comment by ctrlaltca** [comment]
wait, pinned issues are repo-wide and not per user? boring way to lose screen space.. but sorry for having removed them.

**Comment by tooomm** [comment]
No problem at all, we should have a beta up soon.
But still, not everybody uses them. So it keeps users from reopening the same stuff again.
