### ISSUE TITLE
HTR17 set is missing two cards

### ISSUE THREAD

**Issue by Sunlance** [Cockatrice/Cockatrice#3643]
Hi, 

I recently was making a M'odo, the Gnarled Oracle deck, and noticed that HTR17 actually has three cards as shown via https://scryfall.com/sets/htr17 . However, it seems like Diabolical Salvation and Inzerva, Master of Insights aren't in the deck editor. Would it be possible to 'officially' add these two cards into the corresponding Cockatrice set? Thanks.

**Comment by ZeldaZach** [comment]
MTGJSON issue. You’ll have to wait until 4.3.2 releases. Might be a week or two :(
