### ISSUE TITLE
Application Crash - Token editing

### ISSUE THREAD

**Issue by stern718** [Cockatrice/Cockatrice#3644]
<b>System Information:</b>
Client Version: 2.7.0 (2019-03-04)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.9.7
System Locale: fr_FR
Install Mode: Standard
__________________________________________________________________________________________

Hello,

I'm having an issue concerning token editing. When i try to create a new token, in this case "Serra the Benevolent" after i enter the name  and submit it the application crashes, i saw that this issue is probably known due to a similar issue that got declared in 2017 : https://github.com/Cockatrice/Cockatrice/issues/2548 but still occurs on the latest update.

**Comment by ebbit1q** [comment]
I'm unable to replicate your issue, can you try updating your card database and see if the issue still occurs?

**Comment by stern718** [comment]
Problème résolu merci

**Comment by ebbit1q** [comment]
:ok_hand:

**Comment by stern718** [comment]
Problem solved thank you
