### ISSUE TITLE
My custom editions stopped working

### ISSUE THREAD

**Issue by monoloco666** [Cockatrice/Cockatrice#3645]
355/5000
Hi all

A long time ago (Years to be exact) I used this program to design cards with my friends and everything worked fine.

But yesterday I installed the new update and my custom cards made the game close for me and my other friends.

I'm really desperate about it, it's been years of work invested. I need your help!

**Comment by ebbit1q** [comment]
Can you send us your debug logs? They are available though help->debug log

**Comment by ebbit1q** [comment]
actually can you send us a custom card xml file?

**Comment by monoloco666** [comment]
_Client Version: 2.7.0 (2019-03-04)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.9.7
System Locale: es_CL
Install Mode: Standard
---------------------------------------------------------------------------
Theme changed: "Default"
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
Language changed: "en"
main(): starting main program
Spoilers Disabled
CardDatabase::loadCardDatabases start
[CockatriceXml3Parser] Trying to parse:  "C:/Users/MonoLoco/AppData/Local/Cockatrice/Cockatrice/cards.xml"
main(): MainWindow constructor finished
main(): ui.show() finished
PictureLoader: cache fail for "_trice_card_back_226283"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/MonoLoco/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 19297 Sets= 442
[CockatriceXml3Parser] Trying to parse:  "C:/Users/MonoLoco/AppData/Local/Cockatrice/Cockatrice/tokens.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/MonoLoco/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 19712 Sets= 443
[CardDatabase] loadCardDatabase(): Path = "C:/Users/MonoLoco/AppData/Local/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 19712 Sets= 443
[CockatriceXml3Parser] Trying to parse:  "C:/Users/MonoLoco/AppData/Local/Cockatrice/Cockatrice/customsets/01.FVN.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/MonoLoco/AppData/Local/Cockatrice/Cockatrice/customsets/01.FVN.xml" Status = 0 Cards = 19814 Sets= 447
[CockatriceXml3Parser] Trying to parse:  "C:/Users/MonoLoco/AppData/Local/Cockatrice/Cockatrice/customsets/02.ETG.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/MonoLoco/AppData/Local/Cockatrice/Cockatrice/customsets/02.ETG.xml" Status = 0 Cards = 20163 Sets= 450
[CockatriceXml3Parser] Trying to parse:  "C:/Users/MonoLoco/AppData/Local/Cockatrice/Cockatrice/customsets/04.SWTG.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/MonoLoco/AppData/Local/Cockatrice/Cockatrice/customsets/04.SWTG.xml" Status = 0 Cards = 20467 Sets= 454
[CockatriceXml3Parser] Trying to parse:  "C:/Users/MonoLoco/AppData/Local/Cockatrice/Cockatrice/customsets/05.Anime.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/MonoLoco/AppData/Local/Cockatrice/Cockatrice/customsets/05.Anime.xml" Status = 0 Cards = 20807 Sets= 457
[CockatriceXml3Parser] Trying to parse:  "C:/Users/MonoLoco/AppData/Local/Cockatrice/Cockatrice/customsets/Anime.xml"
[CockatriceXml3Parser] Unknown item "set" , trying to continue anyway
[CardDatabase] loadCardDatabase(): Path = "C:/Users/MonoLoco/AppData/Local/Cockatrice/Cockatrice/customsets/Anime.xml" Status = 0 Cards = 20821 Sets= 458
[CockatriceXml3Parser] Trying to parse:  "C:/Users/MonoLoco/AppData/Local/Cockatrice/Cockatrice/customsets/FTV.xml"
[CockatriceXml3Parser] Parsing failed: wrong version 2
[CockatriceXml4Parser] Trying to parse:  "C:/Users/MonoLoco/AppData/Local/Cockatrice/Cockatrice/customsets/FTV.xml"
[CockatriceXml4Parser] Parsing failed: wrong version 2
[CardDatabase] loadCardDatabase(): Path = "C:/Users/MonoLoco/AppData/Local/Cockatrice/Cockatrice/customsets/FTV.xml" Status = 2 Cards = 20821 Sets= 458
[CockatriceXml3Parser] Trying to parse:  "C:/Users/MonoLoco/AppData/Local/Cockatrice/Cockatrice/customsets/SetsFTV.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/MonoLoco/AppData/Local/Cockatrice/Cockatrice/customsets/SetsFTV.xml" Status = 0 Cards = 20923 Sets= 461
[CockatriceXml3Parser] Trying to parse:  "C:/Users/MonoLoco/AppData/Local/Cockatrice/Cockatrice/customsets/Shadow.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/MonoLoco/AppData/Local/Cockatrice/Cockatrice/customsets/Shadow.xml" Status = 0 Cards = 20931 Sets= 463
CardDatabase::loadCardDatabases success_

**Comment by ebbit1q** [comment]
At what point does the game close?
Is it when playing a card?

**Comment by monoloco666** [comment]
If the game closes when I play a custom card in online mode

[XML.zip](https://github.com/Cockatrice/Cockatrice/files/2949508/XML.zip)

**Comment by ebbit1q** [comment]
Ok we are already aware of this issue and a fix is already in place but not released: #3640 
To avoid this bug you could also remove all empty <related></related> lines in your xmls.

**Comment by tooomm** [comment]
Thanks for the report @monoloco666 
I assume there will be a beta release soon, set your client to look for those releases in settings and check ever few days! (Help --> Check for Client Updates)
