### ISSUE TITLE
Dialogs created from play have improper modality on linux

### ISSUE THREAD

**Issue by ebbit1q** [Cockatrice/Cockatrice#3651]
All dialogs you create from play, like set counter and draw cards, behave differently from other modal dialogs, like settings and about.

These dialogs will, instead of blocking access to the main window, rapidly switch focus back to the dialog when focus is moved.

This problem is fixed by changing the dialog's parent to the main window instead of null-ing it.

Client Operating System: Ubuntu 18.04.2 LTS
DE: GNOME 3.28.3

I found this while testing #3646, it does not occur on windows or osx.

**Comment by ebbit1q** [comment]
![image](https://user-images.githubusercontent.com/36401181/54093094-1b139600-4394-11e9-9bb5-3de66ef3e502.png)
Weird dialog, centered on screen instead of mainwindow, no gray background on mainwindow, mainwindow is draggable in the background, has separate entry in window overview, flickers when focus tries to switch
![image](https://user-images.githubusercontent.com/36401181/54093150-b86eca00-4394-11e9-9a88-cc0eb487d3ee.png)
Normal dialog, dragging the dialog drags the mainwindow with it.

**Comment by tooomm** [comment]
As @ebbit1q brought up, this is maybe connected to https://github.com/Cockatrice/Cockatrice/issues/998
