### ISSUE TITLE
Feature Request: Draft deck hash code

### ISSUE THREAD

**Issue by v-kaivan** [Cockatrice/Cockatrice#3653]
I imagine this would be a decent bit work since draft sites would have to support it as well, but I'd like to request support for a draft deck hash code:
 - hash does not differentiate between cards in the main and sideboard
 - hash is not affected by basic lands

This way users could create decks from a draft pool without changing their deck hash, so other users can verify their hash code when playing games against each other.

**Comment by ZeldaZach** [comment]
Simply put, we can't do this for a variety of reasons. If the group you're playing with doesn't trust you to play fairly and vice versa, you shouldn't be playing with that group any longer.

Deck hashes are a _signature_ of what a deck is. A deck is the mainboard and sideboard. If you use a site like [dr4ft.info](https://dr4ft.info) you can redownload the same pool multiple times and it will update the hash codes.

**Comment by forrely** [comment]
Regarding trust, I run drafts on my discord server where many people have never even met each other before, and I think having the hash work would reduce concerns over that.

As for re-downloading, the dr4ft rooms don't seem to stay open forever, and we run our events over multiple days to allow for time differences between players :(
