### ISSUE TITLE
Setting P/T

### ISSUE THREAD

**Issue by Moonlight-Cockatrice** [Cockatrice/Cockatrice#3656]
<b>System Information:</b>
  

  
__________________________________________________________________________________________

  
Prior to the newest client version, players could set the P/T of creatures with equal P/T (5/5, 2/2, etc) by simply typing a single number (5, 2, etc) now this results in a single number being displayed. Loss of convenience.

**Comment by ebbit1q** [comment]
The convenience gained is you actually being able to set a single number as a pt, this was a conscious decision.
Planeswalkers for example have a single stat at their bottom right. While it doesn't set it automatically yet you can now use the pt field for loyalty. Just use the normal keybind for increasing or decreasing power.

**Comment by Moonlight-Cockatrice** [comment]
In comparison with the colored counters, the P/T numbers representing loyalty on planeswalkers looks terrible to me, but to each their own. The keybind as mentioned is fair enough workaround.

**Comment by ebbit1q** [comment]
Well, at least the option is there now, there is other games than magic that might use this feature more.

**Comment by Moonlight-Cockatrice** [comment]
A fair point I'm too quick to forget
