### ISSUE TITLE
Recent Update Removed/Messed Up Most of My Card Images

### ISSUE THREAD

**Issue by Jayjayrod** [Cockatrice/Cockatrice#3657]
<b>OS:</b> Win 10
<b>Cockatrice Version</b> Version 2.7.0 (2019-03-04)
__________________________________________________________________________________________

So I recently updated Cockatrice and a lot of the images are either missing or messed up in some way. It feels like half of the cards are blank and a decent number of them aren't in English even though I set the language to that when updating the database (even the basic lands are in a different language).

I tried uninstalling and reinstalling the client, deleting the card database file and reinstalling that, but I'm still having the same issue. A friend of mine updated his client like I did at around the same time and he doesn't have the same issues. I've never had an issue like this before and the troubleshooting page for "I'm missing images for some cards" just has "information here was outdated. new entry needed!"
Any ideas? This issue is happening across cards from multiple different sets.

**Comment by tooomm** [comment]
See https://github.com/Cockatrice/Cockatrice/issues/3642#issuecomment-471283390

We try to improve that in the next release, sorry!

I hope that solves it for you?

**Comment by ebbit1q** [comment]
Can you please please please include your full debug log like the ticket asks you to?
While we are aware of the non english cards issue, card images should never be missing.

**Comment by tooomm** [comment]
If you still have this issue when using our beta release, don't hesitate to reopen this ticket and provide more debug information!
