### ISSUE TITLE
Display and export decks in traditional card type order

### ISSUE THREAD

**Issue by asherstuhlman** [Cockatrice/Cockatrice#3660]
Currently, when you edit a deck or export a deck to text, it's shown with card types in alphabetical order: 
Artifact -> Creature -> Enchantment -> Instant -> Land -> Planeswalker -> Sorcery.

However, when decklists are shared on websites, the traditional order is:
Creatures -> Noncreature spells (in some order, keeping instants and sorceries together and permanents together) -> Land
or sometimes:
Land -> Creatures -> Noncreature spells (in some order)

Would it be possible to have decks default to one of those two card type display orders?

**Comment by ZeldaZach** [comment]
I feel like this is a personal preference more than a strict rule. When you submit decks to other websites, they (almost) always convert it to whatever format they'd like (ex: TappedOut, MTGGoldfish, DeckStats)

**Comment by ebbit1q** [comment]
There is absolutely no rule for the order in which you list these, I think alphabetical makes perfect sense. Certainly if you take into account that these types are arbitrary names and any game can make their own.
