### ISSUE TITLE
Dark Mode Option for the new Updated Cockatrice

### ISSUE THREAD

**Issue by AetherCrow** [Cockatrice/Cockatrice#3664]
Since the Update for Cockatrice it had reverted to a white theme with default theme setting and my custom dark theme is not on it and wonder if it would break the new cockatrice to put that back on or not?
 If it'd be possible for Cockatrice Programmer team to incorporate a new dark theme or mode for the interface for people with sensitive eyes? I know I'm not the only one who'd appreciate a dark mode for the interface.

I have looked through a few github issues to see if I could find an answer to my question but could not.

**Comment by ebbit1q** [comment]
We are working on darkmode, with the most recent version you'll notice some improvements.

**Comment by tooomm** [comment]
Please **provide complete information** about your system and Cockatrice **from the debug window** as asked for.
>Go to `Help → View Debug Log` and copy everything *above the separation line* here!
>
>If you can't install Cockatrice to access that information, make
sure to include your OS and the app version from the setup file here

For example:
```
Client Version: 2.6.0 (2018-06-17)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.9.5
System Locale: en_US
```

**Comment by ebbit1q** [comment]
This is not an error report @tooomm 
It's a feature request and most likely a duplicate.

**Comment by tooomm** [comment]
The fixes you added for dark mode should only apply on mac. So I want to know at least which system he is running.

Since the user used a dark **theme** before, and not os native dark **mode** there could be a misunderstanding here because of mixed up terms.

**Comment by ebbit1q** [comment]
There are other ways to have qt use darkmode than just mac. For me it's simply declaring an environment variable `QT_QPA_PLATFORMTHEME=gtk2`

**Comment by ZeldaZach** [comment]
QT is a bit painful with darkmode. We need to do better with themes for the userbase so they can load in the dark theme. #4087 

Will call it a dupe.
