### ISSUE TITLE
Cockatrice failed to load the card database

### ISSUE THREAD

**Issue by Zwappa** [Cockatrice/Cockatrice#3666]
<b>System Information:</b>
Client Version: 2.7.0 (2019-03-04)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.9.7
System Locale: en_NL
Install Mode: Portable
---------------------------------------------------------------------------
Portable mode enabled
Theme changed: "Default"
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
Language changed: ""
main(): starting main program
Spoilers Disabled
CardDatabase::loadCardDatabases start
[CardDatabase] loadCardDatabase(): Path = "I:/Magic the Gathering/data/cards.xml" Status = 4 Cards = 0 Sets= 0
[CardDatabase] loadCardDatabase(): Path = "I:/Magic the Gathering/data/tokens.xml" Status = 4 Cards = 0 Sets= 0
[CardDatabase] loadCardDatabase(): Path = "I:/Magic the Gathering/data/spoiler.xml" Status = 4 Cards = 0 Sets= 0
CardDatabase::loadCardDatabases failed
main(): MainWindow constructor finished
main(): ui.show() finished
PictureLoader: cache fail for "_trice_card_back_302432"
__________________________________________________________________________________________

Dear people,

I installed cockatrice and started playing it. All worked fine. Then one day (2 days ago) all of the sudden cockatrice couldn't load the card database. 

I get this error: 
"Cockatrice is unable to load the card database. Do you want to update your card database now? If unsure or first time user, choose "yes""

When I say yes, it downloads the cards (I see the file cards.xml) but then immediately after it finishes downloading and says it succeeded it pops up the same error. Restarting didn't work. Reinstalling didn't work. Installing it in standard folders didn't work. The non-portable version didn't work.. I'm out of ideas. The already existing threads didn't help either :(

Besides this, it also erased all decks I build. It all just happened from one day to another after I used it without trouble. 

Thank you in advance for your help!

Please tell me if more info is required. 

Kind regards,

**Comment by ebbit1q** [comment]
I assume your portable installation is on the drive labeled `I` if so can you please check if the file at `I:\Magic the Gathering\data\cards.xml` exists? It's possible that the cards are placed in the default location instead of the local drive. You can pick a different location by unchecking the checkbox `save to default location` and then when you click save select the location on your additional drive.

**Comment by Zwappa** [comment]
Thank you for your response ebbit1q,

Unfortunately yes, I did that and I can see the files (cards.xml etc) in the custom (right) folder. It doesn't work :(

**Comment by Zwappa** [comment]
I also tried to not install/safe it all on that drive but leave everything at recommended. That also didn't work.

**Comment by ebbit1q** [comment]
So you're saying that even after you completely reinstalled cockatrice in non portable mode and updated your cards database after it still didn't work?
The last thing I can think of is that something happened to your machine, maybe a magical windows update popped in to ruin your day without even telling you.
Can you maybe give me a debug log of your non portable install? I'm sort of at an end here...

**Comment by Zwappa** [comment]
I will, give me a sec, thank you

**Comment by Zwappa** [comment]
It worked! :D I think it missed an update or something, cause it said thank you for updating to versing XXXXX. (dont know the numbers) thakn you for helping me mate!

**Comment by ebbit1q** [comment]
your debug log said you were on the latest version already, that shouldn't happen, happy to know your issue is resolved anyway.
