### ISSUE TITLE
Disable unconcede in local games

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#3669]
Unconcede (added in https://github.com/Cockatrice/Cockatrice/pull/3515) doesn't work in local games. While this makes perfectly sense, the concede option shouldn't be available in the menu while not in a game.
Currently you can hit concede in the game lobby and you get the non-functional `You already conceded - do you want to unconcede?` dialog box.

**Comment by ZeldaZach** [comment]
Most people don't play local, and why would they unconcede? I really don't see this as relevant honestly... @ebbit1q doesn't either
