### ISSUE TITLE
NSIS Error Launching Installer

### ISSUE THREAD

**Issue by OrphanStomper** [Cockatrice/Cockatrice#3671]
<b>System Information:</b>
Windows 10 Business
Cockatrice-Marchesas_Revenge-2.7.0_1-win64
__________________________________________________________________________________________
Trying to install on my work laptop has been somewhat uneventful. I'm on 64 bit. Neither the 64 nor the 32 installers worked. Have installed quite a few different things, haven't encountered another problem yet.
![image](https://user-images.githubusercontent.com/29932680/55078709-05dc7e00-509b-11e9-8ea2-e8b4c26bd69f.png)
![image](https://user-images.githubusercontent.com/29932680/55078732-17be2100-509b-11e9-9ab0-906efb561ec7.png)

**Comment by ebbit1q** [comment]
Please allow me to ask a couple of questions:
Do you have administrator rights to the computer?
Are you able to install other applications?
At what exact point in the install process does the error occur?
Did you have the opportunity to try the portable install method instead and if so was it successful?
Did you try rebooting your computer and installing again?
Did you try removing and redownloading the package and installing again?
Did you try an older or a beta release? (note that old releases might not be compatible with online play)
Did you try installing a portable install on a removable drive using another computer and running that?
Did you try installing while your antivirus is turned off?
Have you done any research online for this apparently not uncommon error?

**Comment by skwerlman** [comment]
this was discussed in the #support channel on the discord a while back; here's a transcript:
```
OrphanStomper 03/20/2019
Hey, I'm trying to install on my work laptop and I get an NSIS Error launching the installer.  Is there a way to fix this? League of Legends ran just dandy, so I hope it isn't restriction.
Only info on this error I found was an archived reddit thread with no answers

[Tetrarch] skwerlman 03/20/2019
what specific error do you get?

OrphanStomper 03/20/2019
https://cdn.discordapp.com/attachments/431200098978889728/557955515968389217/unknown.png

[Tetrarch] skwerlman 03/20/2019
huh. gotta love windows' famously specific error messages

ForPsionics 03/20/2019
"You have a wombat in your modem"

OrphanStomper 03/20/2019
lol
google (outside the specific context of cockatrice) recommended changing system language, running it as admin, or running it through command line, none of which worked

[Tetrarch] skwerlman 03/20/2019
did the cli offer any additional info?

OrphanStomper 03/20/2019
cli?

[Tetrarch] skwerlman 03/20/2019
command line

OrphanStomper 03/20/2019
dont think so
I open the file, get a "do you want to allow app from foreign source to install" or such
click yes
then get an error
exact same through command line

[Tetrarch] skwerlman 03/20/2019
i guess its possible the download is messed up. have you tried redownloading it?

OrphanStomper 03/20/2019
yuup
tried 32 instead of 64 too

[Tetrarch] skwerlman 03/20/2019
what windows ver?

OrphanStomper 03/20/2019
https://cdn.discordapp.com/attachments/431200098978889728/557959717922799617/unknown.png

[Tetrarch] skwerlman 03/20/2019
win 10 business? odd but it shouldnt break nsis
```

**Comment by OrphanStomper** [comment]
> Please allow me to ask a couple of questions:
> Do you have administrator rights to the computer?
**Yes**
> Are you able to install other applications?
**Yes, even games**
> At what exact point in the install process does the error occur?
**Double click installer > first screen shot > press ok > second screenshot aka error**
> Did you have the opportunity to try the portable install method instead and if so was it successful?
**Afaik that is an option within the installation process, which I can not access**
> Did you try rebooting your computer and installing again?
**Yes.**
> Did you try removing and redownloading the package and installing again?
**Yes.**
> Did you try an older or a beta release? (note that old releases might not be compatible with online play)
**The program has no use to me for offline play.**
> Have you done any research online for this apparently not uncommon error?
**Haven't found much.**
> Did you try installing while your antivirus is turned off?
**Yes.**
> Did you try installing a portable install on a removable drive using another computer and running that?
**Will try tonight.**

**Comment by ebbit1q** [comment]
Thanks, I'm unsure what the issue is but maybe the steps outlined in some of these search results might help: https://duckduckgo.com/?q=nsis+error+launching+installer

The portable install will most definitely work for you, after installing on the portable drive you could simply copy the entire installation to a directory on your work machine and add a shortcut to the executable. This will only work temporarily however as you still wouldn't be able to update.
