### ISSUE TITLE
"Enable all sets" should only effect stuff that is being searched/filtered for

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#3674]
See https://www.reddit.com/r/Cockatrice/comments/b7hau0/would_it_be_possible_to_make_it_so_enable_all/

Maybe the button should switch between `Enable all sets` and `Enable all displayed sets` when a search is applied.

Same for `Disable all sets`.

**Comment by Phantato** [comment]
This could be done by `ctrl`+`a` after searching.

**Comment by ZeldaZach** [comment]
I like Phanto's solution here honestly.

**Comment by ebbit1q** [comment]
maybe adding ctrl a select all as a right mouse menu option would be nice?
