### ISSUE TITLE
Rarity Filter, No Mythic

### ISSUE THREAD

**Issue by Thor-Odenson** [Cockatrice/Cockatrice#3675]
When trying to use the filters to sort by rarity, while you can add common, uncommon, and rare, when you try and add Mythic it does not work. Nothing comes up, I tried Mythic, Mythic Rare, MythicRare, and MR. None worked, when doing the search by card name filter and using r:mythic it works.

Is it another word for mythic rare in the filters or did I find a bug?

**Comment by ctrlaltca** [comment]
You found a bug in the filters.
The good news is that by now you can still type "r:mythic" in the search field to see only mythic-rare cards.
