### ISSUE TITLE
meta data in cards.xml

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#3677]
Have some basic meta data in our Oracle created files.
Like `oracle_version` and a `creation_date` would be very helpful.
Also some information about the data source can be handy like `mtgjson_version`.

Based on that, problems like https://www.reddit.com/r/Cockatrice/comments/b7nva9/problem_when_trying_to_find_some_cards_in_the/ could be spotted more easily and the user gets better support.

In a next step, Cockatrice could show a warning when the cards.xml database got created with a different/older oracle version than Cockatrice itself to prevent compatibility issues or occurrences of already fixed issues for example.

**Comment by ctrlaltca** [comment]
Dup #3647?
