### ISSUE TITLE
Tokens with costom cards

### ISSUE THREAD

**Issue by qchap** [Cockatrice/Cockatrice#3681]
<b>System Information:</b>
Client Version: Version 2.6.2 (2018-12-20)
Client Operating System: Windows 7 Home Premium SP1
Build Architecture: 64-bit
__________________________________________________________________________________________
Hello, it's my first time adding costom cards to cockatrice. I've read this: https://github.com/Cockatrice/Cockatrice/wiki/Custom-Cards-%26-Sets
I have one question left. There are costom cards, that would create tokens (both standard and costom ones). The only word about tokens there, is that you should put "1" in the <token> tag to make the token card. But how should connect the token with a card which makes it? Is it the same thing with standard and costom tokens, or different?
Sorry if my english is bad. Thank you!

**Comment by ctrlaltca** [comment]
Sorry if the documentation is not clear enough on this.
You want to add `<related>` or `<reverse-related>` properties to your cards, with a value of the other card's name.
`<related>Goblin</related>` will add a "Goblin" entry in the card's menu.
`<reverse-related>Angel</reverse-related>` works the opposite, so it will add this card to `Angel`'s card menu.
You can find some examples in the tokens file: https://github.com/Cockatrice/Magic-Token/blob/master/tokens.xml
In that file only tokens are present, so they all use the `<reverse-related>` relation to add themselves to the main card's menu.

**Comment by qchap** [comment]
> 
> 
> Sorry if the documentation is not clear enough on this.
> You want to add `<related>` or `<reverse-related>` properties to your cards, with a value of the other card's name.
> `<related>Goblin</related>` will add a "Goblin" entry in the card's menu.
> `<reverse-related>Angel</reverse-related>` works the inverse, so it will add this card to `Angel`'s card menu.
> You can find some examples in the tokens file: https://github.com/Cockatrice/Magic-Token/blob/master/tokens.xml
> In that file only tokens are present, so they all use the `<reverse-related>` relation to add themselves to the main cards' menu.

Oh, now it's clear, thanks!
