### ISSUE TITLE
Card backs

### ISSUE THREAD

**Issue by qchap** [Cockatrice/Cockatrice#3684]
System Information: 
Client Version: Version 2.6.2 (2018-12-20) 
Client Operating System: Windows 7 Home Premium SP1 
Build Architecture: 64-bit
_______________________________________________________________________________________

 I have one more question now. Can I create a card with a different back? Or maybe I can create a deck with different backs?
Thank you!

**Comment by tooomm** [comment]
You can change the card back for all cards which cockatrice displays as that information is part of the theme.
You can not change it for single cards or particular decks.

This is the relevant section, but make sure to read all:
https://github.com/Cockatrice/Cockatrice/wiki/Themes#the-long-list-of-all-image
