### ISSUE TITLE
Card database issue

### ISSUE THREAD

**Issue by kaeporah** [Cockatrice/Cockatrice#3685]
<b>Card database issues</b>
  

  
_______________________________________________________________________________________

    Alot of my cards are in different languages, not sure what to do about it.

**Comment by tooomm** [comment]
Please **provide complete information** about your system and Cockatrice **from the debug window** as asked for.
>Go to `Help → View Debug Log` and copy everything *above the separation line* here!
>
>If you can't install Cockatrice to access that information, make
sure to include your OS and the app version from the setup file here

For example:
```
Client Version: 2.6.0 (2018-06-17)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.9.5
System Locale: en_US
```

---

>Alot of my cards are in different languages, not sure what to do about it. 

i guess you are talking about the card pictures? In which languages are they? And is it the same for all of them?
Are all these cards from the same set?

**Comment by Moonlight-Cockatrice** [comment]
@kaeporah @tooomm I imagine your cards are in Italian and French. You need to go to manage sets and disable some promo sets that are in foreign languages, most likely Rinascimenti and Renaissance.

**Comment by tooomm** [comment]
If you still continue to have this issue, make sure to read https://github.com/Cockatrice/Cockatrice/issues/3642 and come back to us if that doesn't help you! @kaeporah
