### ISSUE TITLE
Suggestion: avoid arrow removal during combat

### ISSUE THREAD

**Issue by ShrewMaster** [Cockatrice/Cockatrice#3686]
In Magic WorkStation there was a special type of arrow (yellow arrows) that didn't disappear during the combat phase. The advantage of this feature was to keep the information of who was blocking who when players changed from one step to another in the combat phase (for example from the declare blockers step to the combat damage step). In multiplayer, this can additionally track which creature is attacking which player. It's easier to keep.

I was wondering if such a feature could be added to Cockatrice with one of the arrow colors, as this would make tracking combat math easier during games.

**Comment by ebbit1q** [comment]
So if we'd add a new arrow, at what point should it be removed? end of turn, end of combat, start of 2nd main, any non combat step, maybe user configurable?

**Comment by skwerlman** [comment]
If its user-configurable, which user's settings apply to which arrows?

**Comment by ShrewMaster** [comment]
In WorkStation, as far as I remember, the arrows were removed if you changed to a non-combat phase (or step). So, answering ebbit1q's question, these arrows should be removed when passing to the second main phase.

**Comment by ebbit1q** [comment]
I think it's fine right now, it's not like you get this indication on tabletop games unless you were to group them on the table which is something that makes perfect sense to do on cockatrice as well.
