### ISSUE TITLE
osx 10.11

### ISSUE THREAD

**Issue by krisk2** [Cockatrice/Cockatrice#3687]
is there no longer a version that works on os 10.11?
<b>System Information:</b>
  

  
_______________________________________________________________________________________

**Comment by ZeldaZach** [comment]
You can self-compile on OSX10.11 via [wiki instructions](https://github.com/Cockatrice/Cockatrice/wiki/Compiling-Cockatrice-(macOS)) We no longer support it as a pre-compiled build since our build tools were updated
