### ISSUE TITLE
Cockatrice Development Meeting #3 - Spring 2019

### ISSUE THREAD

**Issue by ZeldaZach** [Cockatrice/Cockatrice#3688]
Hi Everyone, please fill out this [Doodle Poll](https://doodle.com/poll/hhih8tn3wg9n2wzd) as soon as you can so we can consider the date/time of our next meeting. The goal is to have as many of the active staff in attendance as possible. **Please pay attention to the time zone listed. You can change it on the site to make it fit your local time zone**

Meeting will take place on [Discord](https://discord.gg/3Z9yzmA) as usual.

cc: @ZeldaZach @ctrlaltca  @tooomm @ebbit1q @basicer 

You can refer to last development's meeting via #3354 to see what has/will be accomplished and what we should revise in the schedule.

**Comment by ZeldaZach** [comment]
@ctrlaltca @tooomm @ebbit1q @basicer New poll for this weekend: ﻿

**Comment by ZeldaZach** [comment]
https://doodle.com/poll/tseq7dy38veqrbyk

**Comment by ZeldaZach** [comment]
@ctrlaltca @tooomm @ebbit1q @basicer New poll for this weekend: ﻿ @ctrlaltca @tooomm @ebbit1q @basicer New poll for this weekend: ﻿

**Comment by ZeldaZach** [comment]
@ctrlaltca @tooomm @ebbit1q @basicer New poll for this weekend: https://doodle.com/poll/tseq7dy38veqrbyk

**Comment by ZeldaZach** [comment]
Cockatrice meeting will take place in approximately **6hours and 30minutes** on Discord. Link on the RR website.

**Comment by ebbit1q** [comment]
6 hours is a way too short notice!

**Comment by ZeldaZach** [comment]
@ZeldaZach @ctrlaltca @tooomm @ebbit1q @basicer New options for this weekend/nextweek https://doodle.com/poll/rbnvfinaxgsggb5r

**Comment by ZeldaZach** [comment]
Meeting time confirmed for Sunday, May 12, 3am EST. [**Countdown timer found here**](https://www.timeanddate.com/countdown/generic?iso=20190512T03&p0=179&msg=Cockatrice+Dev+Meeting&font=cursive).

**Comment by tooomm** [comment]
Meeting notes:
https://docs.google.com/document/d/10Egrb14DEpM44Pb0h5xnVKH2QA5WuSKMdjicETa9m2o/edit?ts=5cd7b8c5

**Comment by ctrlaltca** [comment]
I guess this can be closed now.
