### ISSUE TITLE
"Spoiler Updated" notification no longer appearing

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#3689]
<b>System Information:</b>
Client Version: 2.7.1-custom(be7eaa6) (2019-04-05)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.9.7
System Locale: de_DE
Install Mode: Standard
_______________________________________________________________________________________

There used to be a notification when new data entered the spoiler.xml file.
It doesn't display any longer for me.
So currently, I know there is new data when no notification is shown on start. :)

The `No Updates Available` notification works and gets displayed on app start correctly.

<br>

Can others confirm this? Is it a windows only problem?

**Comment by ebbit1q** [comment]
I wouldn't know I don't think I ever had a notification for that.

**Comment by tooomm** [comment]
It's this one:
https://github.com/Cockatrice/Cockatrice/blob/dc727cb6206436060c46ae336d8528bf31bef12b/cockatrice/src/spoilerbackgroundupdater.cpp#L178

I can't tell when the behaviour changed...

**Comment by ZeldaZach** [comment]
Still works on Mac

**Comment by ZeldaZach** [comment]
Is this still an issue @tooomm

**Comment by tooomm** [comment]
Yes. I only receive a system notification if spoilers are already up to date and there are no updates. If there is nothing shown on startup instead, I know it found a newer version and updated the spoiler...
It used to show a “new spoilers available” message - but that stopped suddenly a long time ago.
