### ISSUE TITLE
Wiki Updates

### ISSUE THREAD

**Issue by ZeldaZach** [Cockatrice/Cockatrice#3690]
Re-add wiki support for MSVC140/etc files. Seems to be coming up again a lot.

https://github.com/Cockatrice/Cockatrice/wiki/Troubleshooting/_compare/6b42344a31514136c7d8682619ec061faa619fa9...5b9b6f19ea2f5444dc5fa0ddd1be33dc3d762391

cc: @tooomm

**Comment by tooomm** [comment]
That shouldn't happen as we deliver the right msvc file with our installer to prevent any issues.
Maybe something changed or got updated at appveyor?

CC: @ctrlaltca

**Comment by ctrlaltca** [comment]
> Seems to be coming up again a lot.

Plz, do you have any report on that so that I can investigate?

**Comment by Psithief** [comment]
Is there a 32-bit version vs. a 64-bit version?

**Comment by tooomm** [comment]
>Is there a 32-bit version vs. a 64-bit version?

What do you mean? @Psithief 

You can download both from the GitHub Releases page:
https://github.com/Cockatrice/Cockatrice/releases/tag/2019-03-04-Release-2.7.0

At Appveyor we use different msvc files for 32/64bit as well:
https://github.com/Cockatrice/Cockatrice/blob/master/.appveyor.yml#L31-L41
More info in the docs: https://www.appveyor.com/docs/windows-images-software/#qt

**Comment by tooomm** [comment]
I think that's not relevant anymore?
