### ISSUE TITLE
Card selector doesn't work - I only get _____ [UNH]

### ISSUE THREAD

**Issue by michaelrfarcasin** [Cockatrice/Cockatrice#3691]
<b>System Information:</b>
Client Version: 2.7.0 (2019-03-04)
Client Operating System: Windows 7 SP 1 (6.1)
Build Architecture: 64-bit
Qt Version: 5.9.7
System Locale: en_US
Install Mode: Standard
---------------------------------------------------------------------------
Theme changed: "Default"
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
Language changed: ""
main(): starting main program
Spoilers Disabled
CardDatabase::loadCardDatabases start
[CockatriceXml3Parser] Trying to parse:  "somepath/AppData/Local/Cockatrice/Cockatrice/cards.xml"
[CardDatabase] loadCardDatabase(): Path = "somepath/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 17664 Sets= 215
[CockatriceXml3Parser] Trying to parse:  "somepath/AppData/Local/Cockatrice/Cockatrice/tokens.xml"
[CardDatabase] loadCardDatabase(): Path = "somepath/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 18045 Sets= 215
[CardDatabase] loadCardDatabase(): Path = "somepathel/AppData/Local/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 18045 Sets= 215
CardDatabase::loadCardDatabases success
main(): MainWindow constructor finished
main(): ui.show() finished
CardDatabase::loadCardDatabases start
[CockatriceXml3Parser] Trying to parse:  "somepath/AppData/Local/Cockatrice/Cockatrice/cards.xml"
[CockatriceXml3Parser] Parsing failed: wrong version 4
[CockatriceXml4Parser] Trying to parse:  "somepath/AppData/Local/Cockatrice/Cockatrice/cards.xml"
[CardDatabase] loadCardDatabase(): Path = "somepath/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 19460 Sets= 446
[CockatriceXml3Parser] Trying to parse:  "somepath/AppData/Local/Cockatrice/Cockatrice/tokens.xml"
[CardDatabase] loadCardDatabase(): Path = "somepath/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 19875 Sets= 446
[CardDatabase] loadCardDatabase(): Path = "somepath/AppData/Local/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 19875 Sets= 446
CardDatabase::loadCardDatabases success
CardDatabase::loadCardDatabases start
[CockatriceXml3Parser] Trying to parse:  "somepath/AppData/Local/Cockatrice/Cockatrice/cards.xml"
[CockatriceXml3Parser] Parsing failed: wrong version 4
[CockatriceXml4Parser] Trying to parse:  "somepath/AppData/Local/Cockatrice/Cockatrice/cards.xml"
[CardDatabase] loadCardDatabase(): Path = "somepath/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 19460 Sets= 446
[CockatriceXml3Parser] Trying to parse:  "somepath/AppData/Local/Cockatrice/Cockatrice/tokens.xml"
[CardDatabase] loadCardDatabase(): Path = "somepath/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 19875 Sets= 446
[CardDatabase] loadCardDatabase(): Path = "somepath/AppData/Local/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 19875 Sets= 446
CardDatabase::loadCardDatabases success
QWindowsXPStylePrivate::buffer(1048575x577), CreateDIBSection() failed. (The parameter is incorrect.)
QWindowsXPStylePrivate::buffer(1048575x561), CreateDIBSection() failed. (The parameter is incorrect.)
QWindowsXPStylePrivate::buffer(1048575x561), CreateDIBSection() failed. (The parameter is incorrect.)
PictureLoader: [card:  "_____"  set:  "UNH" ]: Trying to load picture
PictureLoader: [card:  "_____"  set:  "UNH" ]: Picture found on disk.
PictureLoader: [card:  "Arc Lightning"  set:  "WC00" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Arc Lightning"  set:  "WC00" ]: Requested set property ( "muid" ) for Url template ( "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Arc Lightning"  set:  "WC00" ]: Trying to load picture
PictureLoader: [card:  "Arc Lightning"  set:  "WC00" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Arc Lightning"  set:  "WC00" ]: Trying to download picture from url: "https://api.scryfall.com/cards/b158aa08-3612-47d5-ae43-3d0cc4d3d5e3?format=image&face=front"
PictureLoader: [card:  "Arc Lightning"  set:  "WC00" ]: following redirect: "https://img.scryfall.com/cards/large/en/wc00/jk174.jpg?1524576329"
PictureLoader: [card:  "Arc Lightning"  set:  "WC00" ]: Image successfully downloaded from  "https://img.scryfall.com/cards/large/en/wc00/jk174.jpg?1524576329"
PictureLoader: [card:  "Absolute Grace"  set:  "USG" ]: Trying to load picture
PictureLoader: [card:  "Absolute Grace"  set:  "USG" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Absolute Grace"  set:  "USG" ]: Trying to download picture from url: "https://api.scryfall.com/cards/fe7d1839-7180-4b4c-8ddb-7df24573f740?format=image&face=front"
PictureLoader: [card:  "Nighteyes the Desecrator"  set:  "PSAL" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Nighteyes the Desecrator"  set:  "PSAL" ]: Requested set property ( "muid" ) for Url template ( "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Nighteyes the Desecrator"  set:  "PSAL" ]: Trying to load picture
PictureLoader: [card:  "Nighteyes the Desecrator"  set:  "PSAL" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Absolute Grace"  set:  "USG" ]: following redirect: "https://img.scryfall.com/cards/large/en/usg/1.jpg?1517813031"
PictureLoader: [card:  "Absolute Grace"  set:  "USG" ]: Image successfully downloaded from  "https://img.scryfall.com/cards/large/en/usg/1.jpg?1517813031"
PictureLoader: [card:  "Nighteyes the Desecrator"  set:  "PSAL" ]: Trying to download picture from url: "https://api.scryfall.com/cards/8f047a8b-6c94-4b99-bcaa-10680400ee25?format=image&face=front"
PictureLoader: [card:  "Nighteyes the Desecrator"  set:  "PSAL" ]: following redirect: "https://img.scryfall.com/cards/large/es/psal/A39a.jpg?1536535172"
PictureLoader: [card:  "_____"  set:  "UNH" ]: Trying to load picture
PictureLoader: [card:  "_____"  set:  "UNH" ]: Picture found on disk.
PictureLoader: [card:  "Nighteyes the Desecrator"  set:  "PSAL" ]: Image successfully downloaded from  "https://img.scryfall.com/cards/large/es/psal/A39a.jpg?1536535172"
  

  
_______________________________________________________________________________________

  
Pressing any directional key or selecting any card causes the card _____ [UNH] to appear in the Card Info box. I can't add that card to my deck though, or select any other card.

If I do a search, I can work with the first card that comes up normally (add/remove it from deck, etc). But then pressing any directional key or selecting any other card makes _____ show up again.

I first noticed the problem when I tried searching for Teyo (as in Teyo, the Shieldmage [WAR]).

  

Closing and reopening the application fixed the problem.

**Comment by ctrlaltca** [comment]
I suppose somehow the application (or a key) got stuck, but i never saw any other report about this problem.
If it only happened once, i suppose we can close this as "mystery"
