### ISSUE TITLE
wont load full war of spark sets  

### ISSUE THREAD

**Issue by the-wampyre** [Cockatrice/Cockatrice#3692]
<b>System Information:</b>
 Client Version: 2.7.0 (2019-03-04)
Client Operating System: Windows 8.1 (6.3)
Build Architecture: 64-bit
Qt Version: 5.9.7
System Locale: en_US
Install Mode: Standard
---------------------------------------------------------------------------
Theme name not set, setting default value
Theme changed: "Default"
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
Language changed: ""
main(): starting main program
Spoilers Disabled
CardDatabase::loadCardDatabases start
[CockatriceXml3Parser] Trying to parse:  "C:/Users/Soulless1/AppData/Local/Cockatrice/Cockatrice/cards.xml"
[CockatriceXml3Parser] Parsing failed: wrong version 4
[CockatriceXml4Parser] Trying to parse:  "C:/Users/Soulless1/AppData/Local/Cockatrice/Cockatrice/cards.xml"
main(): MainWindow constructor finished
main(): ui.show() finished
PictureLoader: cache fail for "_trice_card_back_226283"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Soulless1/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 19460 Sets= 446
[CockatriceXml3Parser] Trying to parse:  "C:/Users/Soulless1/AppData/Local/Cockatrice/Cockatrice/tokens.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Soulless1/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 19875 Sets= 446
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Soulless1/AppData/Local/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 19875 Sets= 446
CardDatabase::loadCardDatabases success
PictureLoader: cache fail for "_trice_card_back_226283"
PictureLoader: cache fail for "_trice_card_back_226283"
CardDatabase::loadCardDatabases start
[CockatriceXml3Parser] Trying to parse:  "C:/Users/Soulless1/AppData/Local/Cockatrice/Cockatrice/cards.xml"
[CockatriceXml3Parser] Parsing failed: wrong version 4
[CockatriceXml4Parser] Trying to parse:  "C:/Users/Soulless1/AppData/Local/Cockatrice/Cockatrice/cards.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Soulless1/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 19460 Sets= 446
[CockatriceXml3Parser] Trying to parse:  "C:/Users/Soulless1/AppData/Local/Cockatrice/Cockatrice/tokens.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Soulless1/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 19875 Sets= 446
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Soulless1/AppData/Local/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 19875 Sets= 446
CardDatabase::loadCardDatabases success
PictureLoader: cache fail for "_trice_card_back_226283"
PictureLoader: cache fail for "_trice_card_back_226283"
CardDatabase::loadCardDatabases start
[CockatriceXml3Parser] Trying to parse:  "C:/Users/Soulless1/AppData/Local/Cockatrice/Cockatrice/cards.xml"
[CockatriceXml3Parser] Parsing failed: wrong version 4
[CockatriceXml4Parser] Trying to parse:  "C:/Users/Soulless1/AppData/Local/Cockatrice/Cockatrice/cards.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Soulless1/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 19460 Sets= 446
[CockatriceXml3Parser] Trying to parse:  "C:/Users/Soulless1/AppData/Local/Cockatrice/Cockatrice/tokens.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Soulless1/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 19875 Sets= 446
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Soulless1/AppData/Local/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 19875 Sets= 446
CardDatabase::loadCardDatabases success
CardDatabase::loadCardDatabases start
[CockatriceXml3Parser] Trying to parse:  "C:/Users/Soulless1/AppData/Local/Cockatrice/Cockatrice/cards.xml"
[CockatriceXml3Parser] Parsing failed: wrong version 4
[CockatriceXml4Parser] Trying to parse:  "C:/Users/Soulless1/AppData/Local/Cockatrice/Cockatrice/cards.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Soulless1/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 19460 Sets= 446
[CockatriceXml3Parser] Trying to parse:  "C:/Users/Soulless1/AppData/Local/Cockatrice/Cockatrice/tokens.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Soulless1/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 19875 Sets= 446
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Soulless1/AppData/Local/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 19875 Sets= 446
CardDatabase::loadCardDatabases success
PictureLoader: cache fail for "_trice_card_back_226283"
CardDatabase::loadCardDatabases start
[CockatriceXml3Parser] Trying to parse:  "C:/Users/Soulless1/AppData/Local/Cockatrice/Cockatrice/cards.xml"
[CockatriceXml3Parser] Parsing failed: wrong version 4
[CockatriceXml4Parser] Trying to parse:  "C:/Users/Soulless1/AppData/Local/Cockatrice/Cockatrice/cards.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Soulless1/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 0 Sets= 2
[CockatriceXml3Parser] Trying to parse:  "C:/Users/Soulless1/AppData/Local/Cockatrice/Cockatrice/tokens.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Soulless1/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 415 Sets= 124
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Soulless1/AppData/Local/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 415 Sets= 124
CardDatabase::loadCardDatabases success
CardDatabase::loadCardDatabases start
[CockatriceXml3Parser] Trying to parse:  "C:/Users/Soulless1/AppData/Local/Cockatrice/Cockatrice/cards.xml"
[CockatriceXml3Parser] Parsing failed: wrong version 4
[CockatriceXml4Parser] Trying to parse:  "C:/Users/Soulless1/AppData/Local/Cockatrice/Cockatrice/cards.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Soulless1/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 0 Sets= 2
[CockatriceXml3Parser] Trying to parse:  "C:/Users/Soulless1/AppData/Local/Cockatrice/Cockatrice/tokens.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Soulless1/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 415 Sets= 124
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Soulless1/AppData/Local/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 415 Sets= 124
CardDatabase::loadCardDatabases success
CardDatabase::loadCardDatabases start
[CockatriceXml3Parser] Trying to parse:  "C:/Users/Soulless1/AppData/Local/Cockatrice/Cockatrice/cards.xml"
[CockatriceXml3Parser] Parsing failed: wrong version 4
[CockatriceXml4Parser] Trying to parse:  "C:/Users/Soulless1/AppData/Local/Cockatrice/Cockatrice/cards.xml"
PictureLoader: cache fail for "_trice_card_back_226283"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Soulless1/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 19460 Sets= 446
[CockatriceXml3Parser] Trying to parse:  "C:/Users/Soulless1/AppData/Local/Cockatrice/Cockatrice/tokens.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Soulless1/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 19875 Sets= 446
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Soulless1/AppData/Local/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 19875 Sets= 446
CardDatabase::loadCardDatabases success
PictureLoader: cache fail for "_trice_card_back_226283"
CardDatabase::loadCardDatabases start
[CockatriceXml3Parser] Trying to parse:  "C:/Users/Soulless1/AppData/Local/Cockatrice/Cockatrice/cards.xml"
[CockatriceXml3Parser] Parsing failed: wrong version 4
[CockatriceXml4Parser] Trying to parse:  "C:/Users/Soulless1/AppData/Local/Cockatrice/Cockatrice/cards.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Soulless1/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 19460 Sets= 446
[CockatriceXml3Parser] Trying to parse:  "C:/Users/Soulless1/AppData/Local/Cockatrice/Cockatrice/tokens.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Soulless1/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 19875 Sets= 446
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Soulless1/AppData/Local/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 19875 Sets= 446
CardDatabase::loadCardDatabases success
PictureLoader: cache fail for "_trice_card_back_226283"
CardDatabase::loadCardDatabases start
[CockatriceXml3Parser] Trying to parse:  "C:/Users/Soulless1/AppData/Local/Cockatrice/Cockatrice/cards.xml"
[CockatriceXml3Parser] Parsing failed: wrong version 4
[CockatriceXml4Parser] Trying to parse:  "C:/Users/Soulless1/AppData/Local/Cockatrice/Cockatrice/cards.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Soulless1/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 19460 Sets= 446
[CockatriceXml3Parser] Trying to parse:  "C:/Users/Soulless1/AppData/Local/Cockatrice/Cockatrice/tokens.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Soulless1/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 19875 Sets= 446
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Soulless1/AppData/Local/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 19875 Sets= 446
CardDatabase::loadCardDatabases success
PictureLoader: cache fail for "_trice_card_back_226283"

  
_______________________________________________________________________________________

**Comment by ctrlaltca** [comment]
Did you run oracle to get the new set?

**Comment by ctrlaltca** [comment]
No news is good news, closing.
Feel free to reopen if you have more info to add to your issue.

**Comment by bridemenezes** [comment]
Use o Oracle que vem instalado junto do Cockatrice. Ele atualiza todas edições do game automaticamente. ;)
