### ISSUE TITLE
New xsd for card database version 4

### ISSUE THREAD

**Issue by Psithief** [Cockatrice/Cockatrice#3696]
The current doc/cards.xsd is for card database version 3.

There should be one for card database version 4 that reflects the actual minimum required elements and attributes for any card database xml file that, if not adhered to, will cause a complete parse failure for that file.

Should it be a new file, or just overwrite? 
Should a link to https://github.com/Cockatrice/Cockatrice/wiki/Custom-Cards-&-Sets be included in a comment?

Related issues: 
#2545
#3458

**Comment by ctrlaltca** [comment]
I'd go for a new file
