### ISSUE TITLE
Card image display goes blank when mouse crosses the library

### ISSUE THREAD

**Issue by MotherofRuins** [Cockatrice/Cockatrice#3698]
The card image in the upper right goes blank when your mouse crosses the library or an opponent's morph.  Strongly prefer it remain on the last card front face it was displaying.

**Comment by tooomm** [comment]
>The card image in the upper right goes blank

It should not go blank, but used to show the cards back?

<br>

There are several cases where I want to interact with such cards:
- If I cross a library and there is a revealed card (or a known card) on top it should display.
- If I cross an opponents morph token it should display.
- If I cross a face down card it should display as it might be a card that I already know - in that case it used to display that card instead the card back.

**Comment by ebbit1q** [comment]
This was changed when empty cardinfos where added in the latest release, the box at the top right will show the card info for a card, as instead of the card info not existing it now just being empty it'll show nothing.
