### ISSUE TITLE
Two tokens without card types

### ISSUE THREAD

**Issue by Moonlight-Cockatrice** [Cockatrice/Cockatrice#3702]
<b>System Information:</b>
  

  
_______________________________________________________________________________________

  
Ragavan and Ajani, Adversary of Tyrants Emblem somehow ended up without card types recently.

**Comment by tooomm** [comment]
@Moonlight-Cockatrice issues with tokens go to a different repo.
Can you please open the ticket in https://github.com/Cockatrice/Magic-Token (as I can't move it there).

Looking at the file, I think the issue could be the transition to v4 database schema.
cc @Psithief
