### ISSUE TITLE
War of the Spark (WAR) planeswalkers only load the Japanese alternative art image 

### ISSUE THREAD

**Issue by thanatosiris** [Cockatrice/Cockatrice#3703]
<b>System Information:</b>
Client Version: 2.7.0 (2019-03-04)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.9.7
PictureLoader: [card:  "Kasmina, Enigmatic Mentor"  set:  "WAR" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Kasmina, Enigmatic Mentor"  set:  "WAR" ]: Requested set property ( "muid" ) for Url template ( "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Kasmina, Enigmatic Mentor"  set:  "WAR" ]: Trying to load picture
PictureLoader: [card:  "Kasmina, Enigmatic Mentor"  set:  "WAR" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Kasmina, Enigmatic Mentor"  set:  "WAR" ]: Trying to download picture from url: "https://api.scryfall.com/cards/9eac128e-5784-467c-85ed-e46c6ab25547?format=image&face=front"
PictureLoader: [card:  "Kasmina, Enigmatic Mentor"  set:  "WAR" ]: following redirect: "https://img.scryfall.com/cards/large/front/9/e/9eac128e-5784-467c-85ed-e46c6ab25547.jpg?1555974912"
PictureLoader: [card:  "Kasmina, Enigmatic Mentor"  set:  "WAR" ]: Image successfully downloaded from  "https://img.scryfall.com/cards/large/front/9/e/9eac128e-5784-467c-85ed-e46c6ab25547.jpg?1555974912"
_______________________________________________________________________________________

 All the New War of the Spark (WAR) planeswalkers only load the Japanese alternative art image and the other translations are not available (presumably due to duplicate entry in MTGJSON database?).

For example, from MTGJSON:

This record is ignored and not loaded:
"name": "Kasmina, Enigmatic Mentor",
"number": "56",
"scryfallId": "c77d9454-a78c-4063-ad66-46b2f5a030aa",

Alternate art details that is loaded:
"name": "Kasmina, Enigmatic Mentor",
"number": "56★",
"scryfallId": "9eac128e-5784-467c-85ed-e46c6ab25547"

**Comment by tooomm** [comment]
Are there the same two entries in the Cockatrice Card Database `cards.xml`?
While mtgjson is our source, that doesn't mean the parser carries everything (correctly) over.

**Comment by ctrlaltca** [comment]
Every set contains multiple cards with the same name but different printings.
While this is not usually a problem for other sets since the cards are exactly the same (eg. basic lands), in the WAR set this is problematic because some of these cards are only printed in a specific language.
So, i see a few possible solutions:
- keep everything as it is, and add a specific workaround to skip cards that we know are problematic
- make the card database able to load and display separately two card with the same name in the same set
