### ISSUE TITLE
Hotkeys for switching tabs

### ISSUE THREAD

**Issue by mcandre** [Cockatrice/Cockatrice#371]
Could there be hotkeys for switching tabs, e.g. between the deck builder, chat rooms, and active games?

* Windows/Linux uses the convention `Control + Tab / Control + Shift + Tab`
* Mac OS X uses the convention `Command + Option + (Left | Right Hard Bracket)`

**Comment by ZeldaZach** [comment]
I know if you have a wheel on your mouse, you can use it to interact with the tabs.
Scroll down => go to the left by one tab
Scroll up => go to the right by one tab
