### ISSUE TITLE
Card Images Not Downloading

### ISSUE THREAD

**Issue by Dandicoot** [Cockatrice/Cockatrice#3718]
<b>System Information:</b>
Client Version: 2.7.0 (2019-03-04)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.9.7
System Locale: en_US
Install Mode: Standard
_______________________________________________________________________________________

 I am having an issue with loading card images on my computer.  I have attempted a ton of fixes in conjunction with the support on the Discord server, and nothing has worked yet.  If I do not have a card image saved locally, the picture will successfully download if it is being pulled from gatherer.wizards.com.  If gatherer.wizards.com fails with a "Picture downloaded, but blacklisted" error, it will attempt api.scryfall.com, but it will not fail or succeed.  It is almost like it gets hung up on this request because after that, it will not pull any other card until I restart the program.  But, if I get this error again, I have to restart Cockatrice once again.  The issue is, I have not yet been able to figure out a commonality between the cards that cause the error.

I have attempted the following:
Reinstalling Cockatrice (after every troubleshooting step I have attempted, so we're up to like 7 or 8 reinstalls at this point, uninstalled configurations too)
Navigating to URLs that PictureLoader is trying to pull from (they pull up successfully in IE and Chrome)
Set up inbound/outbound rules in Windows Defender for Cockatrice and the IP addresses of gatherer/scryfall
Checked if IP was blocked on scryfall's servers (it's not)
Upgraded Windows 10 from build 1803 to 1809 (still same issue)
Changed DNS settings to Google's public DNS addresses instead of automatically obtaining
Attempted using Cockatrice on a computer on my network, other computer was wired (same as my computer), and the other computer downloaded images with no issues

Debug Log:
PictureLoader: [card:  "1996 World Champion"  set:  "PCEL" ]: Requested set property ( "muid" ) for Url template ( "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "1996 World Champion"  set:  "PCEL" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "1996 World Champion"  set:  "PCEL" ]: Trying to load picture
PictureLoader: [card:  "1996 World Champion"  set:  "PCEL" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "1996 World Champion"  set:  "PCEL" ]: Trying to download picture from url: "http://gatherer.wizards.com/Handlers/Image.ashx?name=1996 World Champion&type=card"
PictureLoader: [card:  "1996 World Champion"  set:  "PCEL" ]: following redirect: "https://gatherer.wizards.com/Handlers/Image.ashx?name=1996 World Champion&type=card"
PictureLoader: [card:  "1996 World Champion"  set:  "PCEL" ]:Picture downloaded, but blacklisted, will consider it as not found
PictureLoader: [card:  "1996 World Champion"  set:  "PCEL" ]: Trying to load picture
PictureLoader: [card:  "1996 World Champion"  set:  "PCEL" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "1996 World Champion"  set:  "PCEL" ]: Trying to download picture from url: "https://api.scryfall.com/cards/d3f10f07-7cfe-4a6f-8de6-373e367a731b?format=image&face=front"
(end of debug log)

Command Prompt:
Pinged api.scryfall.com, successful pings
Pinged gatherer.wizards.com, received one of two messages from each packet:
Request timed out
Reply from 69.8.221.74: Destination net unreachable

What I find strange about the CMD errors is that Cockatrice can pull from gatherer.wizards.com on some cards successfully.  Cockatrice shouldn't be able to download these images from gatherer if my computer cannot reach the site.  Also, it is not a network issue because I tried plugging my computer into the same port the other computer I tested things on, and my computer is still having the same issue.  I have tried messing with firewall settings and nothing has worked yet.  I'm at a loss of what to try next, so any help would be greatly appreciated!  Thank you!

**Comment by ebbit1q** [comment]
Have you tried the beta?

**Comment by Dandicoot** [comment]
I have not yet, what is the link to it?

**Comment by Dandicoot** [comment]
Never mind, found the link.  Same issue on the beta version.

**Comment by ZeldaZach** [comment]
If this is still an issue, let us know
