### ISSUE TITLE
When dragging cards to play onto a full pile of 3, overflow cards should stack like tokens do

### ISSUE THREAD

**Issue by Insertcleverphrasehere** [Cockatrice/Cockatrice#3721]
When Dragging cards from another game zone into play (such as when flipping cards from the top of the deck for a possibility-storm trigger, ad nauseum, or cascade trigger), you can drag them to an empty spot and pile the cards up to three high. When you try to drag a 4th card onto that pile, it will create a new pile at the next empty space (this is fine). 

The issue arises when another 5th card is dragged onto the pile of three. Instead of putting this 5th card onto the second pile, it creates ANOTHER new pile of 1. Tokens, when created via the clone functionality, do not do this, they neatly pile in groups of three. 

This creates an issue when you need to flip a LOT of cards (like half a commander deck, because you have to manually drag the cards to each new pile to make piles of three, instead of simply being able to drag them onto a pile right near the library and have them pile out automatically (it sounds nitpicky but is a very annoying issue in reality),

Proposed fix: When dragging cards onto a full pile of three, instead of going to the next empty pile, simply make that card drop into the next empty slot on the next available pile that isn't maxed out at 3.

**Comment by ebbit1q** [comment]
Hmmm, I don't really like this, wouldn't you rather have dump top card into play function?

**Comment by Insertcleverphrasehere** [comment]
> Hmmm, I don't really like this, wouldn't you rather have dump top card into play function?

I mean, yeah! But also this would still need to be fixed, but dump card from top into play with a shortcut would be AWESOME.

**Comment by ZeldaZach** [comment]
For those type of effects, you should be using the stack, which has an infinitely growing pile.

**Comment by ebbit1q** [comment]
(shortcut ctrl y)
