### ISSUE TITLE
War of the Spark Planeswalkers incorrectly displayed as Japanese Hobby Promos

### ISSUE THREAD

**Issue by Insertcleverphrasehere** [Cockatrice/Cockatrice#3723]
Even if you disable the 'Hobby Japan Promos' set, planeswalkers such as Narset, Parter of Veils will still show up with the Japanese art and text. 

In the WAR pic folder, the art is the Japanese anime version, rather than the standard english version, so something has been done incorrectly.

**Comment by ZeldaZach** [comment]
Fixed in beta already.
