### ISSUE TITLE
Disable Non-English Sets by default

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#3724]
*Follow up issue on [last dev meeting](https://github.com/Cockatrice/Cockatrice/issues/3688).*

<br>

>Program should have a pre-made list

@ZeldaZach I think you wanted that for next release even?

**Comment by ebbit1q** [comment]
this was fixed just fine in https://github.com/Cockatrice/Cockatrice/pull/3652
having a rework of the oracle system like https://github.com/Cockatrice/Cockatrice/issues/4109 would put this out of scope entirely
