### ISSUE TITLE
Scryfall Sending Busted Localization for Card Art

### ISSUE THREAD

**Issue by PoTaToMaN2141** [Cockatrice/Cockatrice#3726]
<b>System Information:</b>
  
Client Version: 2.7.0 (2019-03-04)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.9.7
System Locale: en_US
Install Mode: Standard
  
_______________________________________________________________________________________

  
Howdy, I was building a deck around new Urza when I encountered a bug for downloading card art. I looked at the other bug threads with similar issues, however this seems to be unique as scryfall seems to be sending the wrong localization for the art to cockatrice. I've included the debug information for one of the affected cards below (Ornithopter), as well as a picture of the art here: https://imgur.com/ehw6kW1 . So far I've attempted deleting the card art from the Card Sources tab in settings, as well as straight up reinstalling cockatrice, both with no change

First:

PictureLoader: [card:  "Ornithopter"  set:  "4BB" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Ornithopter"  set:  "4BB" ]: Requested set property ( "muid" ) for Url template ( "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Ornithopter"  set:  "4BB" ]: Trying to load picture
PictureLoader: [card:  "Ornithopter"  set:  "4BB" ]: Picture not found on disk, trying to download

Then Later:

PictureLoader: [card:  "Ornithopter"  set:  "4BB" ]: Trying to download picture from url: "https://api.scryfall.com/cards/c964c4a8-41fb-4df0-902d-de4c92ce7cc7?format=image&face=front"
PictureLoader: [card:  "Ornithopter"  set:  "4BB" ]: following redirect: "https://img.scryfall.com/cards/large/front/c/9/c964c4a8-41fb-4df0-902d-de4c92ce7cc7.jpg?1557433190"
PictureLoader: [card:  "Ornithopter"  set:  "4BB" ]: Image successfully downloaded from  "https://img.scryfall.com/cards/large/front/c/9/c964c4a8-41fb-4df0-902d-de4c92ce7cc7.jpg?1557433190"

I also keep getting this in the debug log, if that means anything:
libpng warning: iCCP: known incorrect sRGB profile

**Comment by PoTaToMaN2141** [comment]
I figured it out, it was the inclusion of the Foreign Black Border 4 set

**Comment by tooomm** [comment]
We try to improve that with the next versions. 👍
