### ISSUE TITLE
Chat log shrinks to font size 1pt

### ISSUE THREAD

**Issue by mcandre** [Cockatrice/Cockatrice#373]
Somehow the chat text shrunk to font size 1pt, impossible to read. I was no longer able to effectively communicate with other players in the game I hosted.

I tried conceding the game, but the font size stayed at 1pt.

Only by quitting the game I was hosting, and creating a new game did the chat log finally return to its original size.

Mac OS X 10.9.5 Mavericks.

**Comment by brianfeister** [comment]
On OSX, CMD + 0 doesn't work for me.  However, CMD + Scrollwheel (Trackpad) scaled the fonts.

**Comment by ZeldaZach** [comment]
You'll have to use the scroll wheel to change chat size, as I've noticed. The command (0, +, and -) don't seem to affect anything.
