### ISSUE TITLE
searching r:common returns uncommon cards

### ISSUE THREAD

**Issue by skwerlman** [Cockatrice/Cockatrice#3730]
<b>System Information:</b>
  Client Version: 2.7.0 (2019-03-04)
Client Operating System: Arch Linux
Build Architecture: 64-bit
Qt Version: 5.12.1
System Locale: en_US
Install Mode: Standard
  
_______________________________________________________________________________________

  

  

Searching for `r:common` in the deck editor returns cards with uncommon rarity.
A workaround is to search `r:common -r:uncommon`, but this is not immediately clear to new users, and isn't very intuitive.

**Comment by ZeldaZach** [comment]
cc: @basicer

**Comment by ZeldaZach** [comment]
@basicer This feels like a major oversight of the parser
