### ISSUE TITLE
split cards show up as two separate cards rather than as one card

### ISSUE THREAD

**Issue by Derya** [Cockatrice/Cockatrice#3736]
<b>System Information:</b>
  
Client Version: 2.7.0 (2019-03-04)
Client Operating System: macOS High Sierra (10.13)
Build Architecture: 64-bit
Qt Version: 5.12.1
System Locale: en_CA
Install Mode: Standard
  
_______________________________________________________________________________________

  
Split cards like Dusk // Dawn appear as two separate cards instead of one. I was running cockatrice and oracle both on verison 2.6.something, don't remember exactly, and I was rebuilding my `cards.xml` without this issue occurring, until today. Then I updated both cockatrice and oracle to 2.7.0 and rebuilt my `cards.xml`, but the behaviour did not change.
[cards.xml.zip](https://github.com/Cockatrice/Cockatrice/files/3242743/cards.xml.zip)

**Comment by tooomm** [comment]
I can confirm the issue, ran a fresh card DB update with this version:

```
Client Version: 2.7.1-custom(f5c10d3) (2019-05-31)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.9.7
System Locale: de_DE
Install Mode: Standard
```

**Comment by ZeldaZach** [comment]
Observed on my end too. I'm honestly not sure what's up... @ctrlaltca I didn't change much with MTGJSON so I'm not sure why Oracle is struggling with the current format

**Comment by tooomm** [comment]
>I didn't change much with MTGJSON so I'm not sure why Oracle is struggling with the current format

From most recent mtgjson changelog 4.4.0: `aftermath added as layout option`

--> https://github.com/Cockatrice/Cockatrice/pull/3742
