### ISSUE TITLE
cannot connect to the server Roosted Rangers throws an error (remote host closed the connection)

### ISSUE THREAD

**Issue by Enzein035** [Cockatrice/Cockatrice#3737]
<b>System Information:</b>
  

  
_______________________________________________________________________________________

**Comment by tooomm** [comment]
Please **provide complete information** about your system and Cockatrice **from the debug window** as asked for.
>Go to `Help → View Debug Log` and copy everything *above the separation line* here!
>
>If you can't install Cockatrice to access that information, make
sure to include your OS and the app version from the setup file here

For example:
```
Client Version: 2.6.0 (2018-06-17)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.9.5
System Locale: en_US
```

**Comment by ctrlaltca** [comment]
Closing. If you still experience this problem, please provide a debug log.
