### ISSUE TITLE
Decide on what to do with hidden, unused spoiler code in oracle importer

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#3743]
Issue as `Reminder` and place for discussions.

How do we want to bring updates to the users in the future. What's the best approach?

**Comment by ctrlaltca** [comment]
What do you mean by `hidden, unused spoiler code in oracle importer`?
You can start oracle with `-s` or directly from inside trice

**Comment by tooomm** [comment]
If you start oracle normally (or from within trice) you‘ll never see a page where you can import spoiler.
Zach only added it as an Easter egg for maybe later use I think. 
Does the -s actually works?

We check&update spoiler with the internal updater in Cockatrice on startup currently. 

Maybe it’s enough to put a hint in the code (or keep this issue) until we decide one way.

**Comment by ZeldaZach** [comment]
Kinda sorta tech debt, but it's not really worth addressing.

**Comment by tooomm** [comment]
Sure, I assume the unused "Easter Egg" code in Oracle (See initial PR https://github.com/Cockatrice/Cockatrice/pull/2991) doesn't matter and will simply be removed with the Oracle tool itself as you plan on integrating that into the main application. (https://github.com/Cockatrice/Cockatrice/issues/4109)
