### ISSUE TITLE
Big regression: custom shortcuts not saved by default

### ISSUE THREAD

**Issue by ShrewMaster** [Cockatrice/Cockatrice#3755]
So here I was all happy trying out the new update to Cockatrice (version 2.7.1). Oracle has been fixed, counters are working again...

And then I discover that all my custom shortcuts no longer work. Whenever I set custom shortcuts and close the software, the custom shortcuts go back to the default ones. This probably won't affect most users, but for me, who had shortcuts for everything you can imagine to facilitate and speed up the game's progression, it's a big problem. Now I have to go back a lot of months to remember all the default shortcuts of the software because there's no way I'm customizing all of them every time I open Cockatrice. This is such a big issue for me that I'm considering installing the previous version of the software.

Could you possibly fix this and attach it to the current version (2.7.1) for players to download? Or maybe add it to a Beta release?

**Comment by tooomm** [comment]
Which OS do you run? Did you compile for yourself?

**Comment by ShrewMaster** [comment]
Windows 10. I updated the software using the "Check for client updates" under the Help tab.

**Comment by tooomm** [comment]
32bit? 64bit? ...

Please, just provide the information we ask you for when you open an issue.
Otherwise we can't help you.

**Comment by ShrewMaster** [comment]
My apologies, I only realized now what you mean. I think this is what you are asking for, directly copied from the debug log in the help tab.

<b>System Information:</b>
  Client Version: 2.7.1 (2019-06-08)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.12.2
System Locale: pt_PT
Install Mode: Standard
---------------------------------------------------------------------------
Theme changed: "VelvetMarble"
SoundEngine: enabling sound
Sound theme changed: "Legacy"
SoundEngine: enabling sound
Language changed: ""
main(): starting main program
main(): MainWindow constructor finished
Spoilers Disabled
main(): ui.show() finished
Startup: old client version "2.7.0 (2019-03-04)" differs, assuming first start after update
CardDatabase::loadCardDatabases start
[CockatriceXml4Parser] Trying to parse:  "C:/Program Files/Cockatrice/cards.xml"
Attempting auto-connect...
QWindowsWindow::setGeometry: Unable to set geometry 1920x1006+0+34 on QWidgetWindow/'MainWindowClassWindow'. Resulting geometry:  1920x986+0+34 (frame: 11, 45, 11, 11, custom margin: 0, 0, 0, 0, minimum size: 971x1006, maximum size: 16777215x16777215).
PictureLoader: cache fail for "_trice_card_back_308311"
PictureLoader: cache fail for "_trice_card_back_308308"
[CardDatabase] loadCardDatabase(): Path = "C:/Program Files/Cockatrice/cards.xml" Status = 0 Cards = 19668 Sets= 450
[CockatriceXml4Parser] Trying to parse:  "C:/Program Files/Cockatrice/tokens.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Program Files/Cockatrice/tokens.xml" Status = 0 Cards = 20096 Sets= 450
[CardDatabase] loadCardDatabase(): Path = "C:/Users/FOliveira/AppData/Local/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 20096 Sets= 450
[CockatriceXml4Parser] Trying to parse:  "C:/Users/FOliveira/AppData/Local/Cockatrice/Cockatrice/customsets/TK.xml"
[CockatriceXml4Parser] Parsing failed: wrong version 3
[CockatriceXml3Parser] Trying to parse:  "C:/Users/FOliveira/AppData/Local/Cockatrice/Cockatrice/customsets/TK.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/FOliveira/AppData/Local/Cockatrice/Cockatrice/customsets/TK.xml" Status = 0 Cards = 20096 Sets= 450
CardDatabase::loadCardDatabases success

**Comment by ctrlaltca** [comment]
Thank you for the informations @ShrewMaster.
I've been able to reproduce the issue and produce a fix for it.
If you are willing to test the fixed version, you'll be able to find an automated built package containing the fix at https://ci.appveyor.com/project/ZeldaZach/cockatrice/builds/25224324/job/0n6j6lo3cm5bnvqc/artifacts in about 20 minutes.

**Comment by ShrewMaster** [comment]
Yes!! I just tested it and it works!
Thank you for providing a solution so fast, I am very happy to be able to use my custom shortcuts again ^_^
