### ISSUE TITLE
Is GitHub Sponsors a (future) option for us?

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#3757]
I've seen people in our Gitter channel talk about that recently.

https://github.blog/2019-05-23-announcing-github-sponsors-a-new-way-to-contribute-to-open-source/
https://help.github.com/en/articles/about-github-sponsors
https://help.github.com/en/articles/displaying-a-sponsor-button-in-your-repository
**https://help.github.com/en/articles/creating-a-default-community-health-file-for-your-organization**
https://github.com/sponsors
https://help.github.com/en/articles/sponsoring-a-developer

https://www.theverge.com/2019/5/23/18637344/github-sponsors-patreon-style-crowdfunding-open-source

**Comment by ZeldaZach** [comment]
I applied for it weeks ago. We'll see what happens.

**Comment by tooomm** [comment]
Working example: https://github.com/sindresorhus/refined-github
