### ISSUE TITLE
Friend is having a problem with registration

### ISSUE THREAD

**Issue by the-pieman** [Cockatrice/Cockatrice#3758]
A friend of mine is encountering an error when she tries to register to chickatrice or RoosterRanges. She says she's giving a good password, a username, an email and all that jazz, but she gets an error message reading "registration is currently disabled on this server"

What can I tell her to do to fix this? I have no idea, I registered with no problems at all.

**Comment by ZeldaZach** [comment]
Sounds like she's trying to register to Chickatrice. Make sure your friend uses the correct server for RR: `server.cockatrice.us`.

This reminds me _again_ to look into improved registration menu. cc: @ctrlaltca

**Comment by the-pieman** [comment]
I mentioned she tried the same with Rooster Ranges, read the whole message, please

**Comment by ZeldaZach** [comment]
I did read the entire message. Sorry if it came off that I ignored you.
That error only appears when a user registers to Chickatrice, as they have in-client registration disabled. I have a feeling your friend accidentally didn't change the URL of the site she was trying to register to. In either case, if she closes the program and tries to login to RR with a username/password, the registration dialog _should_ popup

**Comment by the-pieman** [comment]
I screenshared with her and she did change it to what RoosterRanges said was its location. She still got an error message

**Comment by the-pieman** [comment]
It should be "https://cockatrice.us/" right? Yeah, that still doesn't work

**Comment by ZeldaZach** [comment]
It should be `server.cockatrice.us` in the URL field

<img width="458" alt="Screenshot 2019-06-14 01 08 01" src="https://user-images.githubusercontent.com/7460172/59484700-de4ab580-8e40-11e9-85f7-bfe584cb275c.png">

**Comment by the-pieman** [comment]
Okay, well she had to log off for the night, so we'll try that tomorrow. I'll post whether it worked or not

**Comment by the-pieman** [comment]
Well, she got it working. She just tried a different email. One for gmail instead of yahoo. Didn't know that would make a difference but apparently it does.

**Comment by tooomm** [comment]
Thanks for reporting back @the-pieman
