### ISSUE TITLE
Custom Cards Are Merged instead of Added

### ISSUE THREAD

**Issue by knittely** [Cockatrice/Cockatrice#3761]
When you import custom sets of cards, which have the same name as cards as an official magic card, they will be merged together and the card will have the data from the official magic card.
This will also be the case, even when you disable all official card sets (only leaving your custom sets enabled).
- Cards which have the same name as in a official set, did not show up in the decklist, also the set containing my custom cards was enabled.
- When opening a deck with cards which have the same name as in a official set, were still shown as being the type of the original set in the deck list.

I tried it with a version=3 and version=4 custom set, also trying to use the uuid and muid attribute of \<set\>, but the cards were always merged.

IMO, A seperate card should be created.

P.S. This issue arised, when I updated from cockatrice 2.5 to cockatrice 2.7.

**Comment by ctrlaltca** [comment]
I doubt this was working on 2.5: in Cockatrice cards are identified by name, so you can't have 2 different cards with the same name.
The workaround used to distinguish different tokens with the same name is adding a variable amount of spaces at the end of the card name (see #473); that should work for your custom set, too.

**Comment by ZeldaZach** [comment]
#473 should say can't distinguish ANY card with the same name. This is a dupe, in some regard.
