### ISSUE TITLE
Travis now supports building snaps

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#3762]
See https://blog.travis-ci.com/2019-06-21-snaps-support-travis-ci

This could be an option for us instead offering an Ubuntu 18 LTS only build.
I think newer Ubuntu versions have default support for snaps anyway + others Linux users could install it too.

**Comment by ebbit1q** [comment]
While I see no reason to replace the .deb package, this would be a nice add for those that use snaps. I prefer flatpak though :)

**Comment by tooomm** [comment]
Sure, it could always be an addition.

I would link to the snaps package form the website though, as it's more vesatile - as long as we don't have flatpak support :P

**Comment by ebbit1q** [comment]
it'd be nice to include the flathub one maybe? yet, apparently subpop isn't paying attention to it

**Comment by tooomm** [comment]
I've write access to the flathub store repo too.

But does flatpak work the same way? Can you build and offer a file for yourself that people can use for installation?
Or do you have to go via a hosted "store" like flathub? To support that there is no way around interacting with their repo I guess.

**Comment by subpop** [comment]
You have to host a Flatpak repository yourself (which is technically an OStree repository). Flathub offers infrastructure that builds and hosts Flatpak repositories for you, but there is nothing stopping anyone from building and hosting Flatpak repositories themselves. An example is https://sdk.gnome.org/; the GNOME development community hosts nightly builds of their application suite.

The last time I looked at Travis and Flatpak, I remember their Ubuntu base platform was 14.04, which did not include Flatpak. If they've updated to a newer Ubuntu (like, say 18.04), maybe Travis could be configured to build a Flatpak directly and publish it to a server to host the OSTree repository.

**Comment by ebbit1q** [comment]
Travis base is still 14.04 but they offer 16.04 now.

**Comment by tooomm** [comment]
We also have 18.04 running from inside docker to build our bionic binary.

To summarize the conversation on gitter:
- snaps are not that easy to support for ourselves
- most practical option would be to use and setup the official "snapcraft" store
- flatpak is generally prefered and there is a working store already setup ([Cockatrice @ flathub](https://flathub.org/apps/details/io.github.Cockatrice.cockatrice))

 --> only the automatic update part is missing. Travis would need to update 2 files in the [flathub repo](https://github.com/flathub/io.github.Cockatrice.cockatrice).
Which could be done with a new deployment part (of type "script").

**Comment by tooomm** [comment]
Superseded by https://github.com/Cockatrice/Cockatrice/issues/3792 for now.
