### ISSUE TITLE
Hello, I want to join to the project

### ISSUE THREAD

**Issue by emjvp** [Cockatrice/Cockatrice#3765]
<b>System Information:</b>
  

  
_______________________________________________________________________________________

  what is the work flow, i just create a branch or what can i do?

**Comment by tooomm** [comment]
You fork the project and create a new branch there for every feature you woke on. When you are done you create a pull request from a branch with your changes against our master branch here.
We then review, test and discuss your changes before merging.

If you have any questions before or during the process join us on Gitter!

Hi :)

**Comment by ebbit1q** [comment]
here are github's own tutorials: https://help.github.com/en#dotcom
I think they're pretty good

**Comment by tooomm** [comment]
Do you need any further help with getting started?

**Comment by JoshuaLamusga** [comment]
10 days without response, should this be closed @tooomm?
