### ISSUE TITLE
set types are not displayed perfectly

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#3766]
Oracle imports `duel_deck` as `Dual_deck` etc.
So we capitalize the first letter as they are all lowercase in mtgjson (see https://mtgjson.com/structures/set/).

But what we should really do is to convert to `Dual Deck`, with a space as separator and capitalize all words.

![Untitled](https://user-images.githubusercontent.com/9874850/60250078-416b2c00-98c6-11e9-9510-b92b030ad9f2.png)

**Comment by ZeldaZach** [comment]
`set_type.replace("_", " ").title()`

**Comment by tooomm** [comment]
>set_type.replace("_", " ").title()

That's exactly what we would need. Just found out that this works in python. :)
Sadly, that doesn't work for Qt, `toTitleCase` only exists for QChar, not QString.

What about splitting into a list of strings, use `toUpper()` for the first char of each string (same as we do now), and join the list of strings again with spaces as separation?
Is there some smarter way?
