### ISSUE TITLE
Modern Horizons not complete

### ISSUE THREAD

**Issue by TheLordCamel** [Cockatrice/Cockatrice#3767]
<b>System Information:</b>
  

  
_______________________________________________________________________________________

  
Modern Horizons hasn't been added to the default website, so it will not add correctly to cockatrice. Are there any alternative websites or ways to get the sets?

**Comment by ZeldaZach** [comment]
What seems to be missing from the set?

**Comment by TheLordCamel** [comment]
Hey, thanks for replying so quickly.

The only cards which I seem to be able to get are Serra and the Cabal, the
first 2 cards which were spoiled, the entire rest of the set is missing.

Kind regards,
Michael.

**Comment by ZeldaZach** [comment]
Please try updating your client and running Oracle again. I just did and have all the cards

**Comment by TheLordCamel** [comment]
I can try that, I will let you know if it works, I can't do it right now, I
will do it in the morning.
Thank you very much for your help.

**Comment by TheLordCamel** [comment]
Hey Zach,

Many thanks, that appears to have worked. I'm not sure why it didn't work
the first time I tried it, I assume I must have done something wrong at
some point or another.

Kind regards and have a nice day,
Michael.
