### ISSUE TITLE
Oracle crashing when parsing

### ISSUE THREAD

**Issue by S1NE4T3R** [Cockatrice/Cockatrice#3768]
<b>System Information:</b>
  Win 7 SP1 32bit
_______________________________________________________________________________________
Tried to update Oracle yesterday to check if M20 was out (last time I updated was when MH1 came out and that worked fine) and Oracle just crashed while parsing the .json file it downloads. Every single time after that it just crashes and can't update. I updated Cockatrice, same result. Fresh installed Cockatrice, same. Tried dling the .json file manually and do the local file update, same. I'm using the correct version of Cockatrice for my OS, all the files are trusted on my antivirus (even with it off, crashes all the same), firewall has exception for Cockatrice, I don't know what's up, especially since it was working perfectly fine not that long ago, and since I did a fresh install, now I have no card database on it and can't use it. Help?

![error1](https://user-images.githubusercontent.com/52361033/60389873-e3a33380-9ac1-11e9-97c4-a9fe7c15f45a.jpg)
![error2](https://user-images.githubusercontent.com/52361033/60389874-ea31ab00-9ac1-11e9-8871-5fe8922da303.jpg)

**Comment by tooomm** [comment]
Please **provide complete information** about your system and Cockatrice **from the debug window** as asked for.
>Go to `Help → View Debug Log` and copy everything *above the separation line* here!
>
>If you can't install Cockatrice to access that information, make
sure to include your OS and the app version from the setup file here

For example:
```
Client Version: 2.6.0 (2018-06-17)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.9.5
System Locale: en_US
```

In your case, you can also check the version that Oracle displays on the first screen when you run it.

**Comment by S1NE4T3R** [comment]
Client Version: 2.7.2-beta (2019-06-12)
Client Operating System: Windows 7 SP 1 (6.1)
Build Architecture: 32-bit
Qt Version: 5.12.2
System Locale: pt_PT
Install Mode: Standard

Oracle displays "2.7.2-beta (2019-06-12)" as well.

**Comment by ctrlaltca** [comment]
Thank you for the report, I can confirm the bug and it seems to happen only on windows, on 32bit builds.

**Comment by tooomm** [comment]
@S1NE4T3R can you maybe try the 64Bit install for now? It’s very very unlikely that you have to use the old 32bit version...

Wondering why nobody else complained yet. There are at least some people still downloading 32bit 🙈

**Comment by ebbit1q** [comment]
There are people running cockatrice on older hardware that is not compatible with 64-bit. Removing support would mean they can't use cockatrice anymore.

**Comment by tooomm** [comment]
>older hardware that is not compatible with 64-bit

I think the hardware is probably less of an issue. But the operating systems could be a problem for some (Windows 7 installations in 32bit in particular).

**Comment by ebbit1q** [comment]
If you installed a 32-bit os on a 64-bit system, don't.

**Comment by S1NE4T3R** [comment]
> 
> @S1NE4T3R can you maybe try the 64Bit install for now? It’s very very unlikely that you have to use the old 32bit version...

You mean try the 64bit version of Cockatrice? My system is all 32bit, it is older hardware, so I don't think that'll work. Even if I could put a 64bit version of the OS on this puppy, going through the lengthy, tedious installation and backups/updates process on my machine just for a CCG app to work seems like a massive overkill.

I've heard of other people having the same crashing Oracle bug before on reddit, I just never really had it happen to me, for some reason the 32bit version of the app always worked pristine for me till now. Glad to know it's an acknowledged bug though.

**Comment by ZeldaZach** [comment]
I can look into smaller MTGJSON builds for legacy Cockatrice support... might be necessary

**Comment by DoomOfFools** [comment]
Hello to everyone.
I'm here for a friend of mine. He has the same exact problem of S1NE4T3R. He has a 32-bit system on Windows7

Client Version: 2.7.2-beta (2019-06-12)
Client Operating System: Windows 7 SP 1 (6.1)
Build Architecture: 32-bit
Qt Version: 5.12.2
System Locale: it
System Locale: standard

He has this problem since Modern Horizon. I try to give to him my database, my pictures and my token, but still crash and no new cards are found.
How may I help him?

**Comment by tooomm** [comment]
To summarize the problem as it was only said on gitter:
The issue is that our data source for cards, MTGJSON, grew in size over a limit the 32bit version can process.

We are aware and try to look into a solution.

**Comment by ebbit1q** [comment]
There is a workaround though, you should be able to get the cards.xml file from another user and replace your own with it.

**Comment by S1NE4T3R** [comment]
Don't really know anyone personally that uses Cockatrice, I mostly like to build decks on it every once in a while or use it as a catalog tool for the ones I build irl. So I'll still wait for a proper fix. The thought of nagging someone random for a cards.xml file everytime the database is updated doesn't sit well with me. Unless that xml file becomes available as an official download somewhere (assuming it works).

**Comment by ZeldaZach** [comment]
For the time being, here you go.
[cards.xml.txt](https://github.com/Cockatrice/Cockatrice/files/3366084/cards.xml.txt)

**Comment by DoomOfFools** [comment]
Ok, but how can I use it? I have to put in the settings ---> paths ---> cards database ... ?

**Comment by ebbit1q** [comment]
just replace the file at the location in the cards database field.

**Comment by tooomm** [comment]
That should work. Yes

But at best you don’t mess with the directory given there and simply put the file Zach linked in that directory.
Of course you have to rename the file to .xml and remove the .txt
In case you don‘t see the TXT file extension your Windows settings are hiding them. Check your explorer options.

**Comment by DoomOfFools** [comment]
I tryed in any way. Cockatrice doesn't like this way even I change the extension and made all the correct passage.

Can someone upload a version without .txt?

**Comment by ebbit1q** [comment]
The extension does not change the file contents, you should simply name it cards.xml and place it in the correct location.

**Comment by DoomOfFools** [comment]
Yeah, ok, done, but the cockatrice app can't load the database anyway. In two hours I will show a screenshot about it

**Comment by ebbit1q** [comment]
You can get your logfile through help>view debug log, there you'll find this useful message:
```[CockatriceXml4Parser] Trying to parse:  "C:/Program Files (x86)/Cockatrice/cards.xml.txt"
[CockatriceXml4Parser] Parsing failed: wrong extension```
rename this file to cards.xml instead

**Comment by tooomm** [comment]
MTGJSON changed to minified JSON as standard and the file should be a bit smaller... but I barely belive that's enough. https://github.com/mtgjson/mtgjson-website/issues/264#issuecomment-523270368
Can you guys retry again? Does Oracle still crashes on 32bit for you? @S1NE4T3R @DoomOfFools

**Comment by S1NE4T3R** [comment]
Sorry for the absence, didn't have time for MTG for a while. Just fresh installed 2.7.2, Oracle downloaded everything and it's working fine. At least for now it is.

Is this a permanent fix, or is it something that'll eventually have issues in the future as more and more sets come out into Oracle? Since it's a filesize issue and all.

**Comment by tooomm** [comment]
Yes. This could be a potential issue as more and more new sets get released and the file grows in size again. But that will happen more slowly now. 

Thanks for reporting back!
