### ISSUE TITLE
Oracle is attached to Cockatrice when run from inside the app

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#3769]
When you run Oracle from inside Cockatrice via `Check for Card Updates...` both executables are somehow linked as if it were one application.
If you close Cockatrice in that case Oracle will abort and close as well.

If you open both apps separately from their binaries that won't happen.

**Comment by ctrlaltca** [comment]
And the problem is?

**Comment by tooomm** [comment]
>If you close Cockatrice in that case **Oracle will abort** and close as well.

That's unexpected and there is no warning or confirmation.
The user could think that everything finishes and he has new data now for example.

**Comment by ZeldaZach** [comment]
I don't see this as an issue
