### ISSUE TITLE
Feature Request: right-click "reload card image"

### ISSUE THREAD

**Issue by aeschenkarnos** [Cockatrice/Cockatrice#3774]
Occasionally a card will partially load, just a few rows at the top and the rest will be a grey box. This is probably due to problems between the Cockatrice client and the source of images.

I suggest that a "reload this card image" right-click menu option which goes progressively through the image source list, would provide a workaround.

**Comment by ebbit1q** [comment]
Can you give us some pictures and your logs?

**Comment by ZeldaZach** [comment]
I haven't seen or heard about this issue happening outside of this super old ticket. I'm gonna close for now, but if this is still an issue, please let us know
