### ISSUE TITLE
Question: Card art trying to fetch in Spanish, no way to change?

### ISSUE THREAD

**Issue by JoshuaLamusga** [Cockatrice/Cockatrice#3782]
I'm not sure if this is a bug, or if there's some hidden preference somewhere. The card art is fetched in Spanish when possible; I never touched any settings to cause that, and I have no idea where to change this behavior. Here's an image:

![image](https://user-images.githubusercontent.com/30244654/61258457-a201c200-a72a-11e9-94d8-15e6bef77ea8.png)

Quite a few cards are in Spanish and it's difficult to use Cockatrice to construct & test decks as I tend to.

<b>System Information (Windows 10 64-bit):</b>
> Client Version: 2.7.0 (2019-03-04)
> PictureLoader: [card:  "Hunter Sliver"  set:  "PSAL" ]: Trying to load picture
> PictureLoader: [card:  "Hunter Sliver"  set:  "PSAL" ]: Picture found on disk.
> PictureLoader: [card:  "Lancer Sliver"  set:  "MH1" ]: Trying to load picture
> PictureLoader: [card:  "Lancer Sliver"  set:  "MH1" ]: Picture found on disk.
> PictureLoader: [card:  "Sliver Legion"  set:  "J19" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
> PictureLoader: [card:  "Sliver Legion"  set:  "J19" ]: Requested set property ( "muid" ) for Url template ( "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
> PictureLoader: [card:  "Sliver Legion"  set:  "J19" ]: Trying to load picture
> PictureLoader: [card:  "Sliver Legion"  set:  "J19" ]: Picture not found on disk, trying to download
> PictureLoader: [card:  "Sliver Legion"  set:  "J19" ]: Trying to download picture from url: "https://api.scryfall.com/cards/3511ae86-9c49-4628-b61b-f25466b1b1d2?format=image&face=front"
> PictureLoader: [card:  "Sliver Legion"  set:  "J19" ]: following redirect: "https://img.scryfall.com/cards/large/front/3/5/3511ae86-9c49-4628-b61b-f25466b1b1d2.jpg?1562172514"
> PictureLoader: [card:  "Sliver Legion"  set:  "J19" ]: Image successfully downloaded from  "https://img.scryfall.com/cards/large/front/3/5/3511ae86-9c49-4628-b61b-f25466b1b1d2.jpg?1562172514"
> PictureLoader: [card:  "Diffusion Sliver"  set:  "M15" ]: Trying to load picture
> PictureLoader: [card:  "Diffusion Sliver"  set:  "M15" ]: Picture found on disk.
> PictureLoader: [card:  "Swords to Plowshares"  set:  "4BB" ]: Trying to load picture
> PictureLoader: [card:  "Swords to Plowshares"  set:  "4BB" ]: Picture found on disk.
> Error: Spoiler.xml not found or not deleted
> QLayout: Attempting to add QLayout "" to ShortcutsTab "shortcutsTab", which already has a layout
> Card Database load status:  0
> PictureLoader: [card:  "Swords to Plowshares"  set:  "4BB" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
> PictureLoader: [card:  "Swords to Plowshares"  set:  "4BB" ]: Requested set property ( "muid" ) for Url template ( "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
> PictureLoader: [card:  "Swords to Plowshares"  set:  "4BB" ]: Trying to load picture
> PictureLoader: [card:  "Swords to Plowshares"  set:  "4BB" ]: Picture found on disk.

**Comment by ctrlaltca** [comment]
I see 2 things in the log you provided: 
 * the image for "Sliver Legion" has been downloaded correctly, english version
 * the image for "Swords to Plowshares" has been loaded from the disk

So, the problem is that some images are saved on your disk.
You can try to locate them manually and delete them, or just wipe them all using the "Delete Downloaded Images" button in preferences.

Also, check the entries in "card sources" and, if needed, reset the urls to the default ones.

**Comment by JoshuaLamusga** [comment]
Nah, that's not the issue. The art for Swords to Plowshares is in the correct language. Cockatrice just wants it to be in Spanish. Some are in Spanish. Deleting the whole cache did nothing. For example, I still get Blade Sliver in Spanish. Here are my card sources, untouched:
![image](https://user-images.githubusercontent.com/30244654/61351124-a1e2ee80-a81e-11e9-858a-c8544c34d9bd.png)

**Comment by tooomm** [comment]
Do you refer to the text on the picture telling you that the image is not available in Spanish (es)?

The is part of the picture and not displayed by Cockatrice. :)
If you look at the picture in your card art folder you can verify that. Some pictures on scryfall have that. But when and why I don’t know. Or why Cockatrice loads it. Is there the correct picture available on scryfall?

Could be an issue at their side.
Or a unusual set that is high on your list for cart art priority (in manage set dialog) in Cockatrice?

**Comment by ctrlaltca** [comment]
Please

1. Close cockatrice
2. Delete that card image from the cache in `c:\users\<your name>\AppData\Local\Cockatrice\Cockatrice\pics\downloadedPics\`. Note that that the card can be present in multiple sets with different images.
3. Start cockatrice and choose that card, the image should be missing and appear after a few seconds (once it has been downloaded again)
4. Get the debug log and paste it here in a comment

**Comment by ebbit1q** [comment]
The logs are already provided above. The client tries to load arts from the 4BB or the "fourth edition foreign black border" set. This set can be disabled in the manage sets dialog, simply search for 4BB in the search field and click the checkmark to uncheck it.

**Comment by JoshuaLamusga** [comment]
It's one of the [39 prints](https://scryfall.com/search?as=grid&order=released&q=%21%E2%80%9CSwords+to+Plowshares%E2%80%9D&unique=prints) on Scryfall.

Didn't know 4BB and PSAL are reprint sets. Probably all pure reprint sets can be ignored.

I already cleared cache (see my last message), just never posted logs. It follows a redirect like with others.

> PictureLoader: [card:  "Swords to Plowshares"  set:  "4BB" ]: Trying to load picture
PictureLoader: [card:  "Swords to Plowshares"  set:  "4BB" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Swords to Plowshares"  set:  "4BB" ]: Trying to download picture from url: "https://api.scryfall.com/cards/c80d1df6-247d-4ceb-8493-226a2a4a8f75?format=image&face=front"
PictureLoader: [card:  "Swords to Plowshares"  set:  "4BB" ]: following redirect: "https://img.scryfall.com/cards/large/front/c/8/c80d1df6-247d-4ceb-8493-226a2a4a8f75.jpg?1557431099"
PictureLoader: [card:  "Swords to Plowshares"  set:  "4BB" ]: Image successfully downloaded from  "https://img.scryfall.com/cards/large/front/c/8/c80d1df6-247d-4ceb-8493-226a2a4a8f75.jpg?1557431099"

**Comment by ebbit1q** [comment]
See my earlier comment with more depth here https://github.com/Cockatrice/Cockatrice/issues/3642#issuecomment-471283390

**Comment by ebbit1q** [comment]
Issue has already been resolved: https://github.com/Cockatrice/Cockatrice/pull/3652

**Comment by ebbit1q** [comment]
Apparently 4BB hasn't been added before, now it is, thanks!

**Comment by ctrlaltca** [comment]
Thank you @ebbit1q, I didn't notice it was loading the image from a foreign set.

**Comment by ebbit1q** [comment]
Yeah I had to search the set shorthand, it seemed unfamiliar, I also opened a pull request to add it.
