### ISSUE TITLE
startup mode not correctly detected

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#3783]
<b>System Information:</b>
Client Version: 2.7.2-custom(b467cf4) (2019-07-11)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.12.2
System Locale: de_DE
Install Mode: Standard
_______________________________________________________________________________________

 When I start my client several times in a row (same version), I always get this line in the log:
`Startup: old client version "2.7.1-custom(ac20551) (2019-06-08)" differs, assuming first start after update`

I should get it only once, and then cockatrice should know that it's the same version.

Looking at the implementing pr (~~https://github.com/Cockatrice/Cockatrice/pull/3748~~  #3740), it should be case 3 `subsequent runs`.

CC: @ctrlaltca

**Comment by ctrlaltca** [comment]
The PR implementing that is #3740
Anyway, it looks like  `settingsCache->getClientVersion()` is reporting that the configuration contains the client version "2.7.1-custom(ac20551) (2019-06-08)".
Can you please check if this is really the value contained at `C:\USERS\tooom\AppData\Local\Cockatrice\Cockatrice\settings\global.ini`? You should see a section like this:
```
[personal]
clientid=xxx
clientversion=2.6.3-custom(6b26409) (2019-02-12)
```

I guess I missed to add a `settingsCache->setClientVersion(VERSION_STRING);` somewhere.

**Comment by tooomm** [comment]
Yes, it has the old value in global.ini:
```
[personal]
...
clientversion=2.7.1-custom(ac20551) (2019-06-08)
...
```
