### ISSUE TITLE
Card missing in Cards Database

### ISSUE THREAD

**Issue by fmotadesa** [Cockatrice/Cockatrice#3784]
Creature (not the Token) "Ajani's Pridemate" is missng in the cards database.

**Comment by ctrlaltca** [comment]
Looks like this is caused by the token and the card having the same name; I've opened a new issue on the token, once it's fixed you'll need to re-run oracle to get the new tokens data.
Follow the issue here: https://github.com/Cockatrice/Magic-Token/issues/66
