### ISSUE TITLE
Some Cards from my Custom Cards are Missing also other cards from the same file are their 

### ISSUE THREAD

**Issue by MagicSharky** [Cockatrice/Cockatrice#3788]
I just finished my Custom Cube about 9 Years of Developping...now i would like to load it on Cockatrice. 

a) First i tried to load it as a big file, it worked but  a lot of cards where missing. 

[SYN big original.txt](https://github.com/Cockatrice/Cockatrice/files/3422683/SYN.big.original.txt)

b) so i tried to split it in parts...but again where some cards missing...intrestingly if i added a deck, from planesculptor, it marks the missing cards as unknown but then when i play a game...it shows the missing cards normaly.

![Screenshot](https://user-images.githubusercontent.com/53227634/61724030-68a20580-ad6d-11e9-9741-53cab77cd00c.jpg)

also intresting is that in the file 
[04.SYN4.txt](https://github.com/Cockatrice/Cockatrice/files/3422666/04.SYN4.txt)

27 Transsylvanian Guild Leader is there
40 Undead Augur is missing
71 Unholy Altar is there again

Do you have any clue, what i made wrong? I exportet the file from MSE (MagicSetEditor) and allready corrected some Issues?

I would really appreciate your help. The debug file shows no entries.

P.S Sorry for my bad english i'm from switzerland

**Comment by ctrlaltca** [comment]
The file seems to be valid xml in UTF8 format, but there are some problems in cards description.
Loading up 04.SYN4.txt, i can see 17 cards, from the first up to "Zombie Guru".
If i check "Zombie Guru"'s description, i can see it's truncated:

![Schermata 2019-07-23 alle 18 36 44](https://user-images.githubusercontent.com/1631111/61730044-d7d12700-ad78-11e9-83c2-74bfa328e911.png)

While the original description is: 
```xml
 <text>
Infect, Boost
Nonsoul Cast > Target creature gets infect.
XXB, Channel: Rise any target creature
with power X*Lor (with power < your Zombies).</text>
```
As you can see the description is truncated at the `<` character. That character is used to delimit tags in xml, so you need to escape it to avoid the xml parser to choke on it thinking it's an invalid token.

These are the characters that you need to escape to ensure xml is correctly parsed:
 * `<` is replaced with `&lt;`
 * `>` is replaced with `&gt;`
 * `&` is replaced with `&amp;`

So, in the previous example, the correct description would be:
```xml
 <text>
Infect, Boost
Nonsoul Cast > Target creature gets infect.
XXB, Channel: Rise any target creature
with power X*Lor (with power &lt; your Zombies).</text>
```

**Comment by MagicSharky** [comment]
many thanks for your explanation ctrlaltca, that make sense
Two more questions.
1. sublime text...doesn't show the truncation...witch program can i use, that shows me it?
2. Is there a limit with the file size...or can i correct the big one 740 kB

**Comment by ctrlaltca** [comment]
Sublime text won't show the truncation since it doesn't really parse the file, but it will show there's something wrong at that place:

![Schermata 2019-07-23 alle 18 57 08](https://user-images.githubusercontent.com/1631111/61731408-b32a7e80-ad7b-11e9-9a44-ce48019c15f0.png)

You can check if an xml file is valid using these instructions: https://github.com/Cockatrice/Cockatrice/wiki/Custom-Cards-&-Sets#i-modified-my-cardsxml-and-it-isnt-working-properly
Running it on your file, this is the output:
```
# xmllint --schema ./Cockatrice/doc/carddatabase_v3/cards.xsd 04.SYN4.txt 
04.SYN4.txt:260: parser error : StartTag: invalid element name
with power X*Lor (with power < your Zombies).</text>
```

There's no limit on file size, currently the normal MtG card database is about 24 MB.

**Comment by MagicSharky** [comment]
sorry i tried no for an hour and didn't get it 

i put in my c: 
cards.xsd 
syn.xml =mein card file
xmllint.exe

than tried 

C:\ xmllint --schema ./cards.xsd ./syn.xml

but it didn't worked...so  I see two possible problems

i didn't get the right cards.xsd (didn't found it either in my cockatrice subdirectory nor with the link: https://raw.githubusercontent.com/Cockatrice/Cockatrice/master/doc/cards.xsd

i wrote the wrong cmd prompt order

can you please give mi a valuate link to the cards.xsd and say mi if my cmd prompt order is correct

sorry my programming skills are so bad

**Comment by ctrlaltca** [comment]
The correct xsd is this: https://raw.githubusercontent.com/Cockatrice/Cockatrice/master/doc/carddatabase_v3/cards.xsd

Installing xmllint under windows is a bit of a pity, but you can use an online xsd validator instead like this one: http://xmlvalidator.new-studio.org/

![Schermata 2019-07-24 alle 08 14 01](https://user-images.githubusercontent.com/1631111/61769601-19021f00-adeb-11e9-95e0-4b9edf4dc303.png)
Result:
![Schermata 2019-07-24 alle 08 14 49](https://user-images.githubusercontent.com/1631111/61769618-261f0e00-adeb-11e9-917f-119038708ef6.png)

**Comment by MagicSharky** [comment]
thanks a lot for your help
