### ISSUE TITLE
Make Android App for Deck Editor

### ISSUE THREAD

**Issue by xChikyx** [Cockatrice/Cockatrice#3789]
I would love to see an Android App which can open the Deck files and be able to edit them. I don't think being able to play would be necesary, but deck editor would be great.
Instead of the images, it could link to Scryfall's result to make it easier. I'm not exactly sure if I Cockatrice downloads the pictures in the PC tho, so... If it normally downloads pictures and they are not too heavyz it could just download them normally...
It would be nice if it was able to open the decks online, as well as storing locally, just as the PC version, and maybe even sync with an the PC if sharing the same server.
It would make life much easier. For example, i right now need to check one of my deck lists to see if I need to buy a card, but I have no access to my PC where my decks are. If there was an Android App, I'd love it because that'd make me able to look at my lists anywhere.

**Comment by ctrlaltca** [comment]
A lot of deck builders apps already exists for Android, and most of them can import/export decks, but as far as i know none can access decks saved on a Cockatrice server.
This could be an easy feature to add to the web client.

**Comment by ctrlaltca** [comment]
Closing this issue. While it would be nice to have a deck editor for android, this is no way related to the current development of Cockatrice itself.
