### ISSUE TITLE
Feature Request: Make changed P/T scores and Annotations visible in Card Info

### ISSUE THREAD

**Issue by NeomerArcana** [Cockatrice/Cockatrice#3791]
The font-size of the updated P/T scores and annotations on cards in play is like font-size for ants. I have difficulty reading these. If they could be displayed in the Card Info or in a larger font on mouse-over, it would be a great help.

**Comment by ZeldaZach** [comment]
Settings -> Appearance -> Table grid layout. Change the size of the font rendering on the cards :)

**Comment by NeomerArcana** [comment]
Whelp, there you go.
