### ISSUE TITLE
Cannot connect to chickatrice

### ISSUE THREAD

**Issue by Dreadhound** [Cockatrice/Cockatrice#3793]
<b>System Information:</b>
  
Client Version: 2.7.1 (2019-06-08)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.12.2
System Locale: nl_NL
Install Mode: Standard
  
_______________________________________________________________________________________

  
Hello folks, when trying to connect to the chickatrice server it shows "Connecting to chickatrice.net..." in perpetuity. I don't get an error message just an overall failure to connect. It is not related to my wifi, probably not to my firewall and unlikely to the server, as it's status suggests nothing is wrong with it. The friend I wanted to play with (also based in the netherlands) struggled with the same issue.

With regards,
Dreadhound

**Comment by ZeldaZach** [comment]
Please reach out directly to the Chickatrice Staff. The development team has no oversight on private servers.
