### ISSUE TITLE
card missing in the card's database

### ISSUE THREAD

**Issue by fmotadesa** [Cockatrice/Cockatrice#3796]
The card named "Champion of the Dusk" is missing in the card's database.

**Comment by tooomm** [comment]
@ZeldaZach mtgjson issue?
I can’t check that on mobile.

**Comment by ebbit1q** [comment]
there is a very good reason why it's not there, the card doesn't exist, maybe you are looking for the card champion of dusk?
![image](https://user-images.githubusercontent.com/36401181/63422649-16571180-c40b-11e9-9d11-337e62eee1ef.png)
