### ISSUE TITLE
Custom shortcut not saved 

### ISSUE THREAD

**Issue by dlucca1986** [Cockatrice/Cockatrice#3797]
Dear all , with the new update Version 2.7.1 (2019-06-08) my custom shortcuts are lost when i close the program.
I use manjaro linux Kde plasma with kernel 4.19.66-1.

**Comment by ebbit1q** [comment]
Which install method did you use? Have you tried updating?

**Comment by dlucca1986** [comment]
Hi, i installed it by Octopi package manager, and updated on monday.

**Comment by ebbit1q** [comment]
Does the octopi package manager use flatpak or some other source? We don't actually provide those.

**Comment by dlucca1986** [comment]
Mhh, good question , how can I verify That ??.
I Think flatpak but I'm not sure .

**Comment by ebbit1q** [comment]
What would have helped is if you'd include your debug log on startup as the ticket actually asks you to do when you make it. It's very difficult if we need to ask for every piece of information like this.

**Comment by dlucca1986** [comment]
I'm sorry , you are completely right .
This is the debug info : 

Client Version: 2.7.1 (2019-06-08)
Client Operating System: Manjaro Linux
Build Architecture: 64-bit
Qt Version: 5.12.3
System Locale: it_IT
Install Mode: Standard
---------------------------------------------------------------------------
Theme changed: "VelvetMarble"
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
Language changed: "it"
main(): starting main program
main(): MainWindow constructor finished
Spoilers Disabled
main(): ui.show() finished
Startup: found config with current version
CardDatabase::loadCardDatabases start
[CockatriceXml4Parser] Trying to parse:  "/home/daniele/.local/share/Cockatrice/Cockatrice/cards.xml"
PictureLoader: cache fail for "_trice_card_back_274281"
[CardDatabase] loadCardDatabase(): Path = "/home/daniele/.local/share/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 19899 Sets= 456
[CockatriceXml4Parser] Trying to parse:  "/home/daniele/.local/share/Cockatrice/Cockatrice/tokens.xml"
[CardDatabase] loadCardDatabase(): Path = "/home/daniele/.local/share/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 20333 Sets= 456
[CardDatabase] loadCardDatabase(): Path = "/home/daniele/.local/share/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 20333 Sets= 456
[CockatriceXml4Parser] Trying to parse:  "/home/daniele/.local/share/Cockatrice/Cockatrice/customsets/TK.xml"
[CardDatabase] loadCardDatabase(): Path = "/home/daniele/.local/share/Cockatrice/Cockatrice/customsets/TK.xml" Status = 0 Cards = 20333 Sets= 456
CardDatabase::loadCardDatabases success

**Comment by ebbit1q** [comment]
This does not look like it was installed from flatpak, can you try that version or maybe a version that's built from git head? (your bug has occurred in an old version and has been fixed already)

**Comment by ebbit1q** [comment]
If you have flathub set up this should be the most straightforward install method: https://flathub.org/apps/details/io.github.Cockatrice.cockatrice

**Comment by dlucca1986** [comment]
Hi , following your instructions I installed the version you linked to me everythings work's fine and shortcuts are now stored !!!.
Thank you very much you were very kind.
Best regards.

**Comment by ebbit1q** [comment]
You're welcome
