### ISSUE TITLE
Custom set and cards not load

### ISSUE THREAD

**Issue by SkFaust** [Cockatrice/Cockatrice#3803]
Hello, I try to add set and 5 custom cards but it's not work.

My log:
[CockatriceXml4Parser] Unknown item "set" , trying to continue anyway
[CockatriceXml4Parser] Unknown item "card" , trying to continue anyway
[CockatriceXml4Parser] Unknown item "card" , trying to continue anyway
[CockatriceXml4Parser] Unknown item "card" , trying to continue anyway
[CockatriceXml4Parser] Unknown item "card" , trying to continue anyway
[CockatriceXml4Parser] Unknown item "card" , trying to continue anyway

My file (I send it .txt because I can't send a .xml file)
[01.customcards.txt](https://github.com/Cockatrice/Cockatrice/files/3560604/01.customcards.txt)

**Comment by ebbit1q** [comment]
Please restart cockatrice and give us the entire log.

**Comment by ebbit1q** [comment]
Actually, you can just see that your file is incorrectly formatted, your sets and cards aren't inside the appropriate <sets> and <cards> tags.

**Comment by ebbit1q** [comment]
See step 3 here https://github.com/Cockatrice/Cockatrice/wiki/Custom-Cards-&-Sets#to-add-your-own-custom-cards-follow-these-steps

**Comment by SkFaust** [comment]
My log:
Client Version: 2.7.2-beta (2019-06-12)
Client Operating System: Windows 7 SP 1 (6.1)
Build Architecture: 64-bit
Qt Version: 5.12.2
System Locale: fr_FR
Install Mode: Standard
---------------------------------------------------------------------------
Theme changed: "Default"
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
Language changed: "fr"
main(): starting main program
main(): MainWindow constructor finished
Spoilers Disabled
main(): ui.show() finished
Startup: found config with current version
CardDatabase::loadCardDatabases start
[CockatriceXml4Parser] Trying to parse:  "C:\\Users\\Faust\\AppData\\Local\\Cockatrice\\cards.xml"
QWindowsWindow::setGeometry: Unable to set geometry 1360x707+1920+22 on QWidgetWindow/'MainWindowClassWindow'. Resulting geometry:  1360x706+1920+22 (frame: 8, 30, 8, 8, custom margin: 0, 0, 0, 0, minimum size: 845x707, maximum size: 16777215x16777215).
PictureLoader: cache fail for "_trice_card_back_269292"
PictureLoader: cache fail for "_trice_card_back_269290"
[CardDatabase] loadCardDatabase(): Path = "C:\\Users\\Faust\\AppData\\Local\\Cockatrice\\cards.xml" Status = 0 Cards = 19899 Sets= 456
[CockatriceXml4Parser] Trying to parse:  "C:\\Users\\Faust\\AppData\\Local\\Cockatrice\\tokens.xml"
[CardDatabase] loadCardDatabase(): Path = "C:\\Users\\Faust\\AppData\\Local\\Cockatrice\\tokens.xml" Status = 0 Cards = 20333 Sets= 456
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Faust/AppData/Local/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 20333 Sets= 456
[CockatriceXml4Parser] Trying to parse:  "C:/Users/Faust/AppData/Local/Cockatrice/Cockatrice/customsets/01.customcards.xml"
[CockatriceXml4Parser] Unknown item "set" , trying to continue anyway
[CockatriceXml4Parser] Unknown item "card" , trying to continue anyway
[CockatriceXml4Parser] Unknown item "card" , trying to continue anyway
[CockatriceXml4Parser] Unknown item "card" , trying to continue anyway
[CockatriceXml4Parser] Unknown item "card" , trying to continue anyway
[CockatriceXml4Parser] Unknown item "card" , trying to continue anyway
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Faust/AppData/Local/Cockatrice/Cockatrice/customsets/01.customcards.xml" Status = 0 Cards = 20333 Sets= 456
CardDatabase::loadCardDatabases success

I use notepad++

**Comment by SkFaust** [comment]
Oooooooooooooooooooooooooh I see. Sorry, it work. <cards> and <card>.
