### ISSUE TITLE
Pixelated icons and card images

### ISSUE THREAD

**Issue by malachyshields** [Cockatrice/Cockatrice#3807]
<b>System Information:</b>
Client Version: 2.7.2 (2019-08-31)
Client Operating System: Windows 7 SP 1 (6.1)
Build Architecture: 64-bit
Qt Version: 5.12.3
System Locale: en_GB
Install Mode: Standard
---------------------------------------------------------------------------
Theme changed: "Default"
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
Language changed: ""
main(): starting main program
main(): MainWindow constructor finished
Spoilers Disabled
main(): ui.show() finished
Startup: found config with current version
CardDatabase::loadCardDatabases start
[CockatriceXml4Parser] Trying to parse:  "C:/Users/Dorchadas/AppData/Local/Cockatrice/Cockatrice/cards.xml"
Attempting auto-connect...
QWindowsWindow::setGeometry: Unable to set geometry 1920x1286+0+28 on QWidgetWindow/'MainWindowClassWindow'. Resulting geometry:  1920x1005+0+27 (frame: 9, 36, 9, 9, custom margin: 0, 0, 0, 0, minimum size: 858x1029, maximum size: 16777215x16777215).
PictureLoader: cache fail for "_trice_card_back_256143"
PictureLoader: cache fail for "_trice_card_back_256142"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Dorchadas/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 19899 Sets= 456
[CockatriceXml4Parser] Trying to parse:  "C:/Users/Dorchadas/AppData/Local/Cockatrice/Cockatrice/tokens.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Dorchadas/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 20333 Sets= 456
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Dorchadas/AppData/Local/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 20333 Sets= 456
[CockatriceXml4Parser] Trying to parse:  "C:/Users/Dorchadas/AppData/Local/Cockatrice/Cockatrice/customsets/TK.xml"
[CockatriceXml4Parser] Parsing failed: wrong version 3
[CockatriceXml3Parser] Trying to parse:  "C:/Users/Dorchadas/AppData/Local/Cockatrice/Cockatrice/customsets/TK.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Dorchadas/AppData/Local/Cockatrice/Cockatrice/customsets/TK.xml" Status = 0 Cards = 20333 Sets= 456
CardDatabase::loadCardDatabases success
CardDatabase::loadCardDatabases start
[CockatriceXml4Parser] Trying to parse:  "C:/Users/Dorchadas/AppData/Local/Cockatrice/Cockatrice/cards.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Dorchadas/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 19899 Sets= 456
[CockatriceXml4Parser] Trying to parse:  "C:/Users/Dorchadas/AppData/Local/Cockatrice/Cockatrice/tokens.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Dorchadas/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 20333 Sets= 456
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Dorchadas/AppData/Local/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 20333 Sets= 456
[CockatriceXml4Parser] Trying to parse:  "C:/Users/Dorchadas/AppData/Local/Cockatrice/Cockatrice/customsets/TK.xml"
[CockatriceXml4Parser] Parsing failed: wrong version 3
[CockatriceXml3Parser] Trying to parse:  "C:/Users/Dorchadas/AppData/Local/Cockatrice/Cockatrice/customsets/TK.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Dorchadas/AppData/Local/Cockatrice/Cockatrice/customsets/TK.xml" Status = 0 Cards = 20333 Sets= 456
CardDatabase::loadCardDatabases success
  

  
_______________________________________________________________________________________

**Comment by ctrlaltca** [comment]
Can we get some more information please, like a screenshot or the screen dpi you are using?
You see pixelated images, that could be due to the actual card pictures being low resolution. Please try to open the pictures directory (you can find it in the settings dialog) and check the images quality form there.
About icons, do you see them all pixelatet or some are ok?

**Comment by malachyshields** [comment]
Hi there, 

I no longer have the problem. I did not update or refresh the cards or client just a restart of the machine. 

Many thanks, 

Malachy

On 8 September 2019 16:40:27 GMT+01:00, ctrlaltca <notifications@github.com> wrote:
>Can we get some more information please, like a screenshot or the
>screen dpi you are using?
>You see pixelated images, that could be due to the actual card pictures
>being low resolution. Please try to open the pictures directory (you
>can find it in the settings dialog) and check the images quality form
>there.
>About icons, do you see them all pixelatet or some are ok?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Cockatrice/Cockatrice/issues/3807#issuecomment-529214424

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by tooomm** [comment]
It helps us a lot when you report back. Thank you!

Glad it's working again.
