### ISSUE TITLE
Japanese card image Karn, the Great Creator in english set WAR

### ISSUE THREAD

**Issue by Dreadhound** [Cockatrice/Cockatrice#3812]
<b>System Information:</b>
  
Client Version: 2.7.1 (2019-06-08)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.12.2
System Locale: nl_NL
Install Mode: Standard
  
_______________________________________________________________________________________

  
Hello, not sure if this is the right place for this, but in the War of the Spark set, the Karn, The Great Creator card image is japanese. The rest of the cards are normal and I have disabled all promo sets and stuff. Hope this can be easily resolved.

Cheers and thanks for your work!

**Comment by tooomm** [comment]
There was an issue with war planeswalkers at one point.
You should try to updating your Cockatrice client and run the card updater Oracle again. 

Also, images are cached locally on your harddrive. So you have to manually delete the wrong Japanese picture to redownload the correct one.
You can open the picture folder from the nenu

**Comment by ebbit1q** [comment]
if this issue isn't resolved, feel free to reopen
