### ISSUE TITLE
Feature Request: Always reveal top card to me.

### ISSUE THREAD

**Issue by chrisjuchem** [Cockatrice/Cockatrice#3813]
Newer cards like Experimental Frenzy and Mystic Forge allow you to look at the top card of your library at any time, essentially meaning it is always revealed to you. The only way to handle this in the client currently is to do `Library > View top cards of library... > 1` every time the top card changes.

It would be nice for players to have an option to enable always revealing the top card to just themselves.

**Comment by jfida** [comment]
I second this. There should be a way of keeping the top card revealed to the player.

**Comment by propagated** [comment]
+1

**Comment by ZeldaZach** [comment]
This is still in the works, but I fully agree this is a needed feature
