### ISSUE TITLE
No language showing up in Oracle

### ISSUE THREAD

**Issue by curieos** [Cockatrice/Cockatrice#3817]
<b>System Information:</b>
Client Version: 2.7.2 (2019-08-31)
Client Operating System: Linux 5.2.11-200.fc30.x86_64
Build Architecture: 64-bit
Qt Version: 5.12.4
System Locale: en_US
Install Mode: Standard 
(this is the Flatpak version running on Fedora 30)
_______________________________________________________________________________________

  Whenever I run oracle there is no language option. The dropdown is there, but there aren't any items to select. I think this is resulting in oracle crashing anytime I try to download the card database. I checked the logs and all that's there is `CardDatabase::loadCardDatabases failed`

**Comment by ctrlaltca** [comment]
Hi, the missing languages in Oracle probably means that the flatpak is not including correctly translation files, or that Oracle is not able to find them where they are supposed to be.
These are about 2 dozen files named after the language, eg `cockatrice_it.qm` for Italian, and they should be in `<oracle path>/../share/cockatrice/translations/`, so usually `/usr/share/cockatrice/translations/`. I'm not sure how flatpak handles these, anyway.

The crash you are experiencing is probably due to another cause, that we just discovered today: https://github.com/Cockatrice/Cockatrice/issues/3815
The comment https://github.com/Cockatrice/Cockatrice/issues/3815#issuecomment-532261621 contains a pregenerated card database file that you can use until we fix oracle.

**Comment by curieos** [comment]
Okay, I saw that issue right after I posted and I was wondering about it. Thank you, I copied that database and it's working well now. I also tried the version built natively for Fedora and it had the same issue, no languages showing up.

**Comment by ebbit1q** [comment]
Now on locally built versions that aren't installed no languages show up, but for the rest it should work.

Flatpak works just fine for me and if you do a make install from git it'll work as well. We no longer provide packages for fedora so you shouldn't use those if you found them wherever you did.

**Comment by tooomm** [comment]
@curieos Do you have the language files in the directory ctrlaltca pointed you to?

**Comment by avDuma** [comment]
Same issue here.

On opening oracle, can't select any languages.

```bash
$ ls -l /usr/share/cockatrice/translations/
-rw-r--r-- 1 root root  51026 11 dic 22.24 cockatrice_cs.qm
-rw-r--r-- 1 root root 161110 11 dic 22.24 cockatrice_de.qm
-rw-r--r-- 1 root root  33263 11 dic 22.24 cockatrice_el.qm
-rw-r--r-- 1 root root  19937 11 dic 22.24 cockatrice_en@pirate.qm
-rw-r--r-- 1 root root     23 11 dic 22.24 cockatrice_en.qm
-rw-r--r-- 1 root root 161274 11 dic 22.24 cockatrice_es.qm
-rw-r--r-- 1 root root  25629 11 dic 22.24 cockatrice_et.qm
-rw-r--r-- 1 root root  54018 11 dic 22.24 cockatrice_fi.qm
-rw-r--r-- 1 root root 163424 11 dic 22.24 cockatrice_fr.qm
-rw-r--r-- 1 root root   1883 11 dic 22.24 cockatrice_hu.qm
-rw-r--r-- 1 root root 157306 11 dic 22.24 cockatrice_it.qm
-rw-r--r-- 1 root root 101472 11 dic 22.24 cockatrice_ja.qm
-rw-r--r-- 1 root root  71324 11 dic 22.24 cockatrice_ko.qm
-rw-r--r-- 1 root root   9661 11 dic 22.24 cockatrice_nb.qm
-rw-r--r-- 1 root root 156362 11 dic 22.24 cockatrice_nl.qm
-rw-r--r-- 1 root root 127624 11 dic 22.24 cockatrice_pl.qm
-rw-r--r-- 1 root root 156679 11 dic 22.24 cockatrice_pt_BR.qm
-rw-r--r-- 1 root root 101319 11 dic 22.24 cockatrice_pt.qm
-rw-r--r-- 1 root root 116757 11 dic 22.24 cockatrice_ru.qm
-rw-r--r-- 1 root root  22791 11 dic 22.24 cockatrice_sr.qm
-rw-r--r-- 1 root root  71248 11 dic 22.24 cockatrice_sv.qm
-rw-r--r-- 1 root root   5083 11 dic 22.24 cockatrice_tr.qm
-rw-r--r-- 1 root root 101625 11 dic 22.24 cockatrice_zh-Hans.qm
```

Thank you in advance for your replies about this issue!

- OS: Arch Linux
- Version installed: cockatrice 2.7.2 from [community packages](https://security.archlinux.org/package/cockatrice)
- Flatpak: installed 1.6.2-1 from [extra packages](https://security.archlinux.org/package/flatpak)
- System Locale: Italian (it_IT)

**Comment by tooomm** [comment]
Why do you install flatpak if you don't install the [flatpak version of Cockatrice](https://flathub.org/apps/details/io.github.Cockatrice.cockatrice), but a community package for arch linux instead? @avDuma 

Can you try if the issue persists with an installation via flatpak?

**Comment by avDuma** [comment]
Hi @tooomm ,
Thank you for your reply.

I've removed Arch package and install it via flatpak.

```
$ flatpak install flathub io.github.Cockatrice.cockatrice

Note that the directories 

'/var/lib/flatpak/exports/share'
'/home/albi/.local/share/flatpak/exports/share'

are not in the search path set by the XDG_DATA_DIRS environment variable, so
applications installed by Flatpak may not appear on your desktop until the
session is restarted.

Looking for matches…
Required runtime for io.github.Cockatrice.cockatrice/x86_64/stable (runtime/org.kde.Platform/x86_64/5.12) found in remote flathub
Do you want to install it? [Y/n]: y

io.github.Cockatrice.cockatrice permissions:
    ipc                   network               wayland       x11
    file access [1]       dbus access [2]

    [1] home, xdg-config/kdeglobals:ro, xdg-run/dconf, ~/.config/dconf:ro
    [2] com.canonical.AppMenu.Registrar

        ID                                               Branch       Op       Remote        Download
 1. [✓] org.freedesktop.Platform.GL.nvidia-440-59        1.4          i        flathub       102,7 MB / 102,7 MB
 2. [✓] org.freedesktop.Platform.VAAPI.Intel             18.08        i        flathub         1,8 MB / 1,8 MB
 3. [✓] org.freedesktop.Platform.html5-codecs            18.08        i        flathub         3,3 MB / 3,3 MB
 4. [✓] org.kde.KStyle.Adwaita                           5.12         i        flathub         5,6 MB / 5,6 MB
 5. [✓] org.kde.Platform.Locale                          5.12         i        flathub         3,2 MB / 334,3 MB
 6. [✓] org.kde.Platform                                 5.12         i        flathub       413,0 MB / 430,1 MB
 7. [✓] io.github.Cockatrice.cockatrice                  stable       i        flathub        11,1 MB / 11,7 MB

Installation complete.
```
By the way, why I have to install kde platform (430 Mb) in my Arch Linux + Mate Desktop system?

After that, I've run Cockatrice as posted in the link you provide me.
```
$ flatpak run io.github.Cockatrice.cockatrice

Note that the directories 

'/var/lib/flatpak/exports/share'
'/home/albi/.local/share/flatpak/exports/share'

are not in the search path set by the XDG_DATA_DIRS environment variable, so
applications installed by Flatpak may not appear on your desktop until the
session is restarted.

Qt: Session management error: Authentication Rejected, reason : MIT-MAGIC-COOKIE-1 authentication rejected
Client Version: 2.7.2 (2019-08-31)
Client Operating System: Linux 5.5.2-arch1-1
Build Architecture: 64-bit
Qt Version: 5.12.4
System Locale: it_IT
Install Mode: Standard
Theme name not set, setting default value
Theme changed: "Default"
Sounds theme name not set, setting default value
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
Language changed: ""
main(): starting main program
main(): MainWindow constructor finished
Spoilers Disabled
main(): ui.show() finished
Startup: old client version empty, assuming first start after clean install
PictureLoader: cache fail for "_trice_card_back_316571"
QXcbConnection: XCB error: 3 (BadWindow), sequence: 712, resource id: 9743251, major code: 40 (TranslateCoords), minor code: 0
CardDatabase::loadCardDatabases start
[CockatriceXml4Parser] Trying to parse:  "/home/albi/.var/app/io.github.Cockatrice.cockatrice/data/Cockatrice/Cockatrice/cards.xml"
[CardDatabase] loadCardDatabase(): Path = "/home/albi/.var/app/io.github.Cockatrice.cockatrice/data/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 20594 Sets= 472
[CockatriceXml4Parser] Trying to parse:  "/home/albi/.var/app/io.github.Cockatrice.cockatrice/data/Cockatrice/Cockatrice/tokens.xml"
[CardDatabase] loadCardDatabase(): Path = "/home/albi/.var/app/io.github.Cockatrice.cockatrice/data/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 21047 Sets= 472
[CardDatabase] loadCardDatabase(): Path = "/home/albi/.var/app/io.github.Cockatrice.cockatrice/data/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 21047 Sets= 472
CardDatabase::loadCardDatabases success
```

But the error persists.
I'm not able to select languages on Oracle.

For what is worth, I've understood that AUR packages on Arch are something similar to PPA's for Ubuntu system: they are users repositories shared for everyone.
Once a package becomes more popular, it can be moved to community repository.

**Comment by tooomm** [comment]
>I've still have .qm files in the flatpak directory

If you are missing language options in Oracle, you have to check for `oracle_XX.qm` files in that same directory.
Just realized that you looked for the wrong ones, sorry...

**Comment by avDuma** [comment]
Hi @tooomm , thank for your replies.
Still have .qm files also for oracle:
```
$ ls -l /var/lib/flatpak/app/io.github.Cockatrice.cockatrice/current/active/files/share/oracle/translations/
-rw-r--r--  2 root root   215 17 feb 20.59 oracle_cs.qm
-rw-r--r--  2 root root 13873 17 feb 21.00 oracle_de.qm
-rw-r--r--  2 root root  8001 17 feb 21.00 oracle_el.qm
-rw-r--r--  2 root root  1038 17 feb 21.00 oracle_en@pirate.qm
-rw-r--r-- 13 root root    23 17 feb 20.56 oracle_en.qm
-rw-r--r--  2 root root 13751 17 feb 21.00 oracle_es.qm
-rw-r--r--  2 root root 12805 17 feb 21.00 oracle_et.qm
-rw-r--r--  2 root root  7447 17 feb 21.00 oracle_fi.qm
-rw-r--r--  2 root root 14221 17 feb 21.00 oracle_fr.qm
-rw-r--r--  2 root root   102 17 feb 21.00 oracle_hu.qm
-rw-r--r--  2 root root 13271 17 feb 21.00 oracle_it.qm
-rw-r--r--  2 root root  6293 17 feb 21.00 oracle_ja.qm
-rw-r--r--  2 root root  5714 17 feb 21.00 oracle_ko.qm
-rw-r--r--  2 root root  6923 17 feb 21.00 oracle_nb.qm
-rw-r--r--  2 root root 13267 17 feb 21.00 oracle_nl.qm
-rw-r--r--  2 root root  7325 17 feb 21.00 oracle_pl.qm
-rw-r--r--  2 root root  8856 17 feb 21.00 oracle_pt_BR.qm
-rw-r--r--  2 root root  7509 17 feb 21.00 oracle_pt.qm
-rw-r--r--  2 root root  7795 17 feb 21.00 oracle_ru.qm
-rw-r--r--  2 root root  2908 17 feb 21.00 oracle_sr.qm
-rw-r--r--  2 root root   228 17 feb 21.00 oracle_sv.qm
-rw-r--r--  2 root root  1204 17 feb 20.59 oracle_tr.qm
-rw-r--r--  2 root root  5705 17 feb 21.00 oracle_zh-Hans.qm
```

What I can't see is the language for cards in oracle, in the first dropdown list in dialog window:
![Screenshot](http://avduma.mooo.com/oracle.png)
As you can see I've changed language in Cockatrice interface, Oracle dialog windows are still in english (but this is not the issue). The issue is that **there's no language listed on dropdown for picking a language for cards**.

I'm still with flatpak version of cockatrice.

Thank you in advance!

**Comment by tooomm** [comment]
>there's no language listed on dropdown for picking a **language for cards**.

The setting for oracle only changes the ui language of the oracle tool itself, not the downloaded cards!
We currently don't support other languages for the card database yet. There is an issue about that already.

Is the dropdown all empty? Or are there entries which don't show a label and clicking them changes the interface language for Oracle?

**Comment by avDuma** [comment]
> The setting for oracle only changes the UI language of the oracle tool itself, not the downloaded cards!
We currently don't support other languages for the card database yet. There is an issue about that already.

Good to know. I've seen that windows version allows to picking languages on that dropdown list.

>Is the dropdown all empty? Or are there entries which don't show a label and clicking them changes the interface language for Oracle?

The first you said. Dropdown is empty, seems disabled.

**Comment by tooomm** [comment]
>Good to know.

We might need to better clarify that in the interface... hmm.

**Comment by ctrlaltca** [comment]
I guess i found the bug, it was linux specific and the fix is trivial: https://github.com/Cockatrice/Cockatrice/pull/3896
