### ISSUE TITLE
Travis: update yml to account for updated release tool (dpl v2)

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#3818]
See https://blog.travis-ci.com/2019-08-27-deployment-tooling-dpl-v2-preview-release

Documentation can already be found here: https://docs.travis-ci.com/user/deployment-v2

For checking our yml: http://config.travis-ci.org/

>[warn] on deploy: deprecated key: "skip_cleanup" (not supported in dpl v2, use cleanup)
[warn] on deploy: deprecated key: "skip_cleanup" (not supported in dpl v2, use cleanup)
[info] on deploy: api_key is an alias for token, using token (key)
[info] on deploy: body is an alias for release_notes, using release_notes (key)
[info] on deploy: api_key is an alias for token, using token (key)
[info] on os: missing os, using the default "linux"

**Comment by tooomm** [comment]
dpl v2 is still in beta and not properly released hence we had to partly revert #3853

**Comment by ZeldaZach** [comment]
Is this still an issue? Travis works fine for us still?

**Comment by tooomm** [comment]
Travis works still fine for us as dpl v2 is still in beta as seen in their docs page:
https://docs.travis-ci.com/user/deployment-v2

>This page documents deployments using the next major version dpl v2, which currently is in a beta release phase. Please see our blog post for details. The current default version is dpl v1. Check dpl v1 documentation here. 

I prefer to keep this open to find the references quickly until they fully release.

**Comment by ZeldaZach** [comment]
I don't expect V2 to drop anytime soon, and it's not relevant for us as we don't really need to upgrade in any case. You can always search closed tickets, and this is just a bloat one imo.
