### ISSUE TITLE
UI problems

### ISSUE THREAD

**Issue by Dactyl49** [Cockatrice/Cockatrice#3823]
<b>System Information:</b>
  

  
_______________________________________________________________________________________

  
Ever since Rooster Ranch took over the main server, none of the text lines up correctly anymore (like the usernames in match show up way offscreen and has to be moved over everytime when this didn't used to be an issue) and has an obscene amount of unused space. font sizes are also 0.1 and completely illegible. 

 If I have cockatrice open on my 4K monitor, when I try to open an in game menu like the graveyard or library and move it to a more convenient location on screen it'll try to snap to every edge very quickly and can't actually be moved reasonably.

**Comment by ebbit1q** [comment]
Thank you for reporting.

Please include your system information in the way the ticket template asks for.

The issue to pull request system works on a per problem basis, we can't address all the problems listed at once so it's preferable to place them in separate tickets.

Most of these problems are visual and could use some further details such as screenshots, also these things can be related to your operating system and screen density (pixels per screen surface).

**Comment by tooomm** [comment]
Please follow the issue in https://github.com/Cockatrice/Cockatrice/issues/1937 to keep track of updates regarding to high res screen issues.
