### ISSUE TITLE
Cascade QOL improvement suggestion

### ISSUE THREAD

**Issue by Jace1234567** [Cockatrice/Cockatrice#3824]
Would it be possible to create  a command for Cascade? Like click on a card -> Command : Cascade -> Action : Puts cards on the stack from the top of the library until a lower cmc card is revealed?

**Comment by ZeldaZach** [comment]
My initial thought is no as the server has no indication of what a card is and only passes around relevant attributes (name, PT, etc). 

Maybe the local client can do this by comparing to custom database and report back? Hmm...

**Comment by Jace1234567** [comment]
Don't the cards have a cmc value? When you go to descriptions there is normally a number for their cmc.

**Comment by ebbit1q** [comment]
Yes, but the server doesn't have this information.
