### ISSUE TITLE
Allow room creator to change player order in multiplayer games.

### ISSUE THREAD

**Issue by Insertcleverphrasehere** [Cockatrice/Cockatrice#3825]
Currently there is no way to change player order after a game has started, or to change it beforehand without a complicated manuever leaving and re-entering the game (which also doesn't work because unless the game has a password other people might join in the meantime). 

The reason for this is that it would be much better to have the option of determining player order by highest to lowest dice roll, rather than just having the highest roll start and being locked into whatever the current player order is. 

In competitive multiplayer, games are often decided by turn order, so multiple games in a row with the same turn order can get tiresome, but there is currently no good solution. 
What would be great is to give the room creators and mods the power to drag-and-drop players in the player list to change the turn order.

**Comment by skwerlman** [comment]
dupe #3795, see also #3062, #3802

**Comment by ZeldaZach** [comment]
I too want this, but it's not as easy as I'd like. Maybe I'll give it another shot. But yeah, dupe.

**Comment by videogreg93** [comment]
Why was this closed? Is this not in the works anymore?
