### ISSUE TITLE
Replay Controls issues

### ISSUE THREAD

**Issue by dstinct** [Cockatrice/Cockatrice#383]
Stop and Pause basically do the same thing, so they seem rather redundant. Fast-forward is really slow, so I would speed it up. Track forward and back do nothing, and there is no way to rewind, which is a huge pain. You have to stop and restart. It would also be handy if you could click on the timeline to go to a specific part of the video. It would also be great if you could some how leave notes or annotations on the line for videos you've downloaded.

I don't think it's possible, but is there any way to convert the replays to a video file for casting? Or do we have to replay it and then screen record the replay? If that is the case, it would be great if you could make the video controls dockable so you can get them out of the way while you are recording.

**Comment by danyfire** [comment]
Hello, just wondering if there as been any advancement on the replay control / video converting subject ? :-).

**Comment by ZeldaZach** [comment]
Dupe #3941

**Comment by tooomm** [comment]
Not exactly a dupe, but "fixed" anyway...

Mentioned issues:
>Stop and Pause basically do the same thing, so they seem rather redundant.
>Fast-forward is really slow, so I would speed it up.
>Track forward and back do nothing
>and there is no way to rewind, which is a huge pain. 

The first is solved as there is no stop button anymore.
The second is still an issue, but has its own ticket: https://github.com/Cockatrice/Cockatrice/issues/1171
The third is sovled as those buttons got removed, maybe they come back with functionality at one point (https://github.com/Cockatrice/Cockatrice/issues/2933).
The forth didn't change, but one can just click the timeline to jump back in time.
