### ISSUE TITLE
Tokens in decks arent grouped

### ISSUE THREAD

**Issue by skwerlman** [Cockatrice/Cockatrice#3835]
<b>System Information:</b>
  
Client Version: 2.7.2-custom(8879fc2) (2019-10-02)
Client Operating System: Arch Linux
Build Architecture: 64-bit
Qt Version: 5.13.1
System Locale: en_US
Install Mode: Standard
  
_______________________________________________________________________________________

  

  

in the deck editor, all tokens are placed in the "tokens" zone, which make sense. however, they are not sorted by type, and are instead all placed in a blank group:
![Screenshot_20191007_192142](https://user-images.githubusercontent.com/6954107/66356076-bb846580-e937-11e9-9385-8a8a54bb0a85.png)
The above tokens should be in the "creatures", "enchantments", and "artifacts" groups, respectively.

this issue also occurs for tokens in the "maindeck" and "sideboard" zones. additionally, there doesnt seem to be a way to move tokens from either of these zones back into the "tokens" zone.

**Comment by kopcion** [comment]
I have started working on it, but I have a question: Let's say I have card TukTuk The Returned which type is "Token Legendary Artifact Creature - Goblin Golem". Should it lay under "Token Legendary Artifact Creature" category or the whole "Token Legendary Artifact Creature - Goblin Golem" thing? In other words should the prefix after "-" be truncated or not?

**Comment by skwerlman** [comment]
No; that should go under "creature" in the "tokens" zone, similar to how a normal artifact creature goes under "creature" in the "maindeck" zone

in general, cards are sorted by their "primary" supertype, which (if im not misreading the code) is in the `maintype` property of the card

**Comment by kopcion** [comment]
The main problem with this solution is that for tokens (getIsToken() == true) getMainCardType is empty string ("").

**Comment by kopcion** [comment]
And when you add Token Creature into Maindeck should it be put together with non-token creatures or separate,  say in 'Token Creature' tab?

**Comment by skwerlman** [comment]
that bit about maintype made me realize something: this is a bug in the tokens xml, not in cockatrice. the tokens xml isnt supplying the `maintype` prop. if you add it in manually, the card is sorted as expected. will open a new issue in the correct place and link back

for putting token/maindeck/sideboard interaction, the only change i can think of needing is moving them tokens->maindeck->sideboard->tokens, rather than tokens->maindeck->sideboard->maindeck. i dont think having their own categories in the maindeck is very useful

**Comment by ebbit1q** [comment]
Why do people add tokens to decks?

**Comment by Psithief** [comment]
It's a legacy feature, but still used for debugging and/or custom sets, I'd imagine.

**Comment by tooomm** [comment]
> Why do people add tokens to decks?

To use the right click, "Create predefined token" option.
Why they still do that (or don't update their decks) with the related cards feature in place... I don't know. :)

**Comment by ZeldaZach** [comment]
We plan on removing tokens from decks, as we'll be automating those in the future. Linking #3909
