### ISSUE TITLE
Cockatrice for Chromebook?

### ISSUE THREAD

**Issue by StrawberriShark** [Cockatrice/Cockatrice#3839]
<b>System Information:</b>
  

  
_______________________________________________________________________________________

HI! I have no clue how to get Cockatrice from my new Chromebook. I loved to play Cockatrice on my old laptop but when it crashed I replaced it with a Chromebook. Well this happened a week ago and I have tried other online MTG platforms and I really miss Cockatrice. Please send help.
-Sincerely, 
 StrawberriShark

**Comment by ctrlaltca** [comment]
Chromebook should be able to run Linux apps, but i have no experience in running Cockatrice on them.
If you want to try, you can follow these [instructions](https://www.androidcentral.com/how-install-linux-apps-your-chromebook) and then install the ".deb" package from here: https://github.com/Cockatrice/Cockatrice/releases/tag/2019-08-31-Release-2.7.2
If it doesn't work, please report back with the error, maybe it's something we can workaround.

**Comment by ZeldaZach** [comment]
Seems like a dead ticket at this point. We also don't have the man power to get into Chrome App development.
