### ISSUE TITLE
Cockatrice locks up on unknown tokens

### ISSUE THREAD

**Issue by dstinct** [Cockatrice/Cockatrice#384]
I was recently watching some gameplay on the server. A player had a young pyromancer in play and was creating elemental tokens. They called it something else, and spit out blank red 1/1 token. I middle mouse clicked the tokens to see if it was just a translation error, but upon releasing the middle mouse button the pop up stayed visible. There was no way to close it. I had to go into task manager and manually kill it, whereupon it threw an error. Luckily the error doesn't appear to cause the program to crash.

**Comment by tooomm** [comment]
fixed in #508
