### ISSUE TITLE
Cockatrice has stopped functionning

### ISSUE THREAD

**Issue by Tentacules** [Cockatrice/Cockatrice#3841]
<b>System Information:</b>
  
Client Version: 2.7.2 (2019-08-31)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.12.3
System Locale: fr_FR
Install Mode: Standard
  
_______________________________________________________________________________________

  

After a few seconds, or directly when I try to load a deck, Cockatrice stop functionning, the page is still open, but nothing function, I can't click anywhere, like a sort of a freeze. I can only close the app via Windows Task Manager. I don't have Dell Backup Recovery, Dropbox or Git. I had already try to change .exe name on the folder and open Oracle again but It didn't work neither.

What can I do ?

**Comment by tooomm** [comment]
Please **provide complete information** about your system and Cockatrice **from the debug window** as asked for.
>Go to `Help → View Debug Log` and copy everything *above the separation line* here!
>
>If you can't install Cockatrice to access that information, make
sure to include your OS and the app version from the setup file here

For example:
```
Client Version: 2.6.0 (2018-06-17)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.9.5
System Locale: en_US
```

**Comment by Tentacules** [comment]
Is this the correct way to provide complete information ? I'm a little bit clumsy.

**Comment by tooomm** [comment]
Yes, thanks you for editing your starting post!

**Comment by ebbit1q** [comment]
Could you provide a full log from startup to freeze?

**Comment by Tentacules** [comment]
I can give you debug log from startup:

"Theme changed: "Default"
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
Language changed: "fr"
main(): starting main program
main(): MainWindow constructor finished
Spoilers Disabled
main(): ui.show() finished
Startup: found config with current version
CardDatabase::loadCardDatabases start
[CockatriceXml4Parser] Trying to parse:  "C:/Users/Clément/AppData/Local/Cockatrice/Cockatrice/cards.xml"
PictureLoader: cache fail for "_trice_card_back_269293"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Clément/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 20200 Sets= 459
[CockatriceXml4Parser] Trying to parse:  "C:/Users/Clément/AppData/Local/Cockatrice/Cockatrice/tokens.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Clément/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 20645 Sets= 459
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Clément/AppData/Local/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 20645 Sets= 459
CardDatabase::loadCardDatabases success"

Otherwise I guess I can only describe you what happens when the app is frozen

**Comment by ebbit1q** [comment]
Does anyone know if it's possible to run an application in a terminal on windows?

**Comment by Tentacules** [comment]
Is there a way to open the debug log outside of the app to see If It says something about what happens ?

**Comment by ebbit1q** [comment]
Well if you'd run it in a terminal it should give the log there.

**Comment by Tentacules** [comment]
I've found a way to open cockatrice.exe via windows terminal. But I don't know If It's possible to navigate inside the app. Because when I try to load a deck with my mouse nothing is written on windows terminal's log.

**Comment by ebbit1q** [comment]
does it give any output at all?

**Comment by Tentacules** [comment]
Nope. I mean, I used prompt DOS, I guess It's the English name for It. And use "CD" command to navigate throughout folders and execute cockatrice.exe but inside the app I can't use prompt DOS to load a deck. I suppose so when I use my mousse to do It nothing get written. Maybe I didn't understand something ?

**Comment by Tentacules** [comment]
Any ideas to help me...?

**Comment by ebbit1q** [comment]
The cause of this is likely some library that is broken on your system, we could either try to see if there is a way to get more information or you could try fixing it.

**Comment by Tentacules** [comment]
I found somewhere a .wer file called "Critical_cockatrice.exe blablablabla"
Will It help If I copy/paste the content ?

**Comment by Tentacules** [comment]
Up ?

**Comment by ebbit1q** [comment]
Up.

**Comment by Tentacules** [comment]
Well... I updated my Cockatrice client to the new one and the problem seems to be solved.
