### ISSUE TITLE
Modern Horizons not working

### ISSUE THREAD

**Issue by jaymgray** [Cockatrice/Cockatrice#3843]
The card database in Oracle is showing that Modern Horizons is one of the sets that is being added to the card database. However, the deck editor isn't allowing me to add cards from Modern Horizons to any deck. 
Ex: When I type "Wrenn and SIx" or "Force of Negation", it's not showing the card in the database.

Any way around this? Thank you.

**Comment by tooomm** [comment]
Is the set enabled in the „manage sets“ dialog in the card database menu?

**Comment by jaymgray** [comment]
that did work! Thank you so much!
