### ISSUE TITLE
libqt5core missing

### ISSUE THREAD

**Issue by LeoFC97** [Cockatrice/Cockatrice#3844]
<b>System Information: Linux Mint</b>
_______________________________________________________________________________________

Everytime i try to install on a Mint i get this error. 
![image](https://user-images.githubusercontent.com/33994116/67402902-9cb4de80-f587-11e9-8918-9372cf57ec66.png)

**Comment by ebbit1q** [comment]
Could you please include more system information than just linux mint?
What version of mint? Have you tried updating it? Have you tried using the flathub image instead?
Our provided .deb package is targeted at Ubuntu 18.04, this means that as long as your distro uses the 18.04 repositories as a base you can use it. If you are using any other version or base the package simply won't install.
Try the flathub image here instead, any up to date version of mint should be able to use the one click install button: https://flathub.org/apps/details/io.github.Cockatrice.cockatrice

**Comment by LeoFC97** [comment]
Ops, forgot to put version. Using 18.1 now, i will try to update and test again

**Comment by ebbit1q** [comment]
To use the .deb we provide you need to use linux mint 19, to use the flatpak you need to use linux mint 18.3.

**Comment by LeoFC97** [comment]
I will update my system thx mate

**Comment by ebbit1q** [comment]
You're welcome
