### ISSUE TITLE
Idea: rework documentation with e.g. GitBook

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#3848]
As an idea, we could start having a new clean and more user friendly documentation.
While reworking the wiki and transform it to GitBooks for example we can update the content, throw old stuff out and finally finish those beginner guides etc.

Example: https://developer.thunderbird.net/ (or https://samypesse.gitbook.io/how-to-create-an-operating-system/)
GitBook: https://www.gitbook.com (free for open source)
There might be other services and possibilities, let us know if you heard about an interesting service!

We could keep the GitHub Wiki for dev notes, and use GitBook for user facing tipps and guides if we think it's better to separate those or want to keep the dev stuff close to the repo.

GitBook has more features and possibilities than the GitHub wiki and one can easily embed videos. Also, there is for example a search which the wiki is strongly missing!
Everything looks very beautiful, too.
Docs could be in their own repo, or sourced from e.g. the `/docs` folder in the main repo. Both is supported in GitBook.

There is also [readthedocs](https://github.com/Cockatrice/Cockatrice/issues/3366), [mkdocs](https://www.mkdocs.org/) and [archbee.io](https://archbee.io) etc.
GitHub pages support to deploy from a `/docs` folder on master, now too. [Read](https://github.blog/2016-08-22-publish-your-project-documentation-with-github-pages/) [Read more](https://help.github.com/en/github/working-with-github-pages/about-github-pages)

Others: [GIT Playbook](https://itnext.io/create-compelling-documentation-with-github-pages-16e4149efe9e), [Docusaurus](https://docusaurus.io/), [ReadMe](https://readme.com/), [Docsify](https://docsify.js.org/), [DocFX](https://dotnet.github.io/docfx/)
Others2: [Hugo](https://gohugo.io/), [Sphinx](https://www.sphinx-doc.org/en/master/#)

Tutorial on how auto-deploy via CI could look like when we are building the docs on ourselves without help of a service like GitBook. [Read](https://circleci.com/blog/deploying-documentation-to-github-pages-with-continuous-integration/) [Read2](https://coderbook.com/@marcus/automatically-publish-your-documentation-to-github-pages-with-your-cicd-pipeline/)

**Comment by ZeldaZach** [comment]
If you want to look into this @tooomm you're more than welcomed to. I don't have the time unfortunately.

**Comment by tooomm** [comment]
I don't have the time either.

Also, the wiki - while not as fancy - is good enough in my opinion.
Cockatrice would benefit more from any contributions towards improving and updating the documentation in the wiki than a new look and more complex setup for the same.
