### ISSUE TITLE
Pull the svg icons out of the dlls to make them customizable

### ISSUE THREAD

**Issue by dstinct** [Cockatrice/Cockatrice#385]
Instead of compiling the svgs into the program, have them point to a directory so that users can change them to their preferred style. This would also help with reskinning for different games. This would also likely require separate icons for the storm count and colorless, that way they can be changed separately if needed. If you want to set it up for reskinning, I would equally distribute the turn phases, in particular the combat ones, so that it doesn't look strange when reskinned.

As for customization, how do you determine the optimal size for the play area images? is it just best to have it scalable?

**Comment by woogerboy21** [comment]
Would this issue be fixed with the recent theme(s)?

**Comment by woogerboy21** [comment]
@ctrlaltca @dstinct

**Comment by ctrlaltca** [comment]
Yes; still there's an hardcoded version of the svgs inside the .exe to be used as a fallback, but every image is customizable using themes.
