### ISSUE TITLE
Feature Suggestion : Customized Friend/Ignore list

### ISSUE THREAD

**Issue by SlomoSapien** [Cockatrice/Cockatrice#3850]
<b>System Information:</b>
  

  
_______________________________________________________________________________________

  
I have added people onto friend/ignore list for different reasons or to play in different formats.  I don't always remember which one I could invite to which type of game.
It would be helpful to have a space where you could add a small note beside the name on the list.

**Comment by tooomm** [comment]
We already maintain such a request in #1957. Please follow there.
