### ISSUE TITLE
Add pioneer to format filters.

### ISSUE THREAD

**Issue by Xatrith** [Cockatrice/Cockatrice#3855]
Hi !

All is in the tittle. I'dd like to know if there is a plan to add the pioneer filter to the deck building tool.

Thx a lot for your work,

Xatrith

<b>System Information:</b>
  

  
_______________________________________________________________________________________

**Comment by ebbit1q** [comment]
Done, now wait until release I guess?

**Comment by Xatrith** [comment]
Ok , thx =)

**Comment by tooomm** [comment]
If you use windows, feel free to test the development version from #3856 already as a release (even beta) might take a while!

--> [Windows 64bit Installer (development version)](https://ci.appveyor.com/api/buildjobs/u5ktq2487wj48c5k/artifacts/Cockatrice-2.7.2-custom(89a6129)-win64.exe)
