### ISSUE TITLE
Multiple issue templates and template chooser config

### ISSUE THREAD

**Issue by skwerlman** [Cockatrice/Cockatrice#3861]
Github now supports having several issue templates, using a table at the top to specify a title and description, as well as automatically assigning some tags.
In addition we can supply custom contact links, which will be helpful to avoid password change requests and the like being opened on the tracker

See https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository

**Comment by tooomm** [comment]
Note: There is even the option to have several links to external pages...
https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser

Documentation/Wiki, FAQ, Gitter would be further options for example.
