### ISSUE TITLE
Error opening file for writing during client update

### ISSUE THREAD

**Issue by chewkahmeng** [Cockatrice/Cockatrice#3864]
<b>System Information:</b>
  

  
_______________________________________________________________________________________

  
![image](https://user-images.githubusercontent.com/35601900/68486855-f6522400-027c-11ea-8542-8c825abb1f3c.png)
Image says it all, I can't seem to update the client to Faerie Tales

**Comment by skwerlman** [comment]
is this issue resolved?

**Comment by chewkahmeng** [comment]
Yup it is!

**Comment by tooomm** [comment]
To help others with the same problem:
How did you solve it? @chewkahmeng

**Comment by chewkahmeng** [comment]
I removed everything (cards, tokens etc...) by checking the second box when uninstalling the previous version of Cockatrice.
