### ISSUE TITLE
Look into GitHub Actions

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#3866]
https://github.com/features/actions
https://help.github.com/en/actions/automating-your-workflow-with-github-actions
https://github.blog/2019-08-08-github-actions-now-supports-ci-cd/
https://github.blog/2019-11-14-powering-community-led-innovation-with-github-actions/

https://github.com/actions

Could be a nice, integrated alternative for simple checks that benefit from having a separate result easily viewable right in the RP! (like linting for example)

**Comment by ZeldaZach** [comment]
We use TravisCI and Appveyor already. I'd  rather not spend more time re configuring system resources.
