### ISSUE TITLE
Uncontrollable Scrolling

### ISSUE THREAD

**Issue by Johan3232323232** [Cockatrice/Cockatrice#3872]
Recently, when opening Cockatrice, I have been unable to effectively use it because it will automatically scroll up unexpectedly. This includes scrolling to the first tab (between deck, server, account, and game tabs), scrolling to the top of file menus, and scrolling to the top of the card database. It mostly only seems to happen when the mouse cursor is hovering over the scroll bar (or tab line). This persisted after restarting my computer and updating cockatrice to the most recent stable build.
My first instinct is I have some kind of phantom inputs, which isn't a cockatrice problem, but I don't seem to have this issue in other applications. Possibly there is some kind of shortcut key in cockatrice I'm unaware of? Regardless, I reached the end of my troubleshooting ideas, so I thought I would post here.

**Comment by tooomm** [comment]
I don’t think there is no shortcut.
Did you try using a different mouse/keyboard?

**Comment by Johan3232323232** [comment]
The problem appears to have resolved itself. I use a laptop, so I hadn't tried an alternative to my keyboard and trackpad, but it's gone.

**Comment by ctrlaltca** [comment]
Thank you for reporting back.
