### ISSUE TITLE
Broken Importing Split Cards

### ISSUE THREAD

**Issue by JakeChaimowitz** [Cockatrice/Cockatrice#3873]
when i try to import decklists from clipboard my export formats it with Commit // Memory which doesnt import and gives unknown when i removed the // memory it also spits out unknown

**Comment by ctrlaltca** [comment]
I've just tried and it seems to work for me.
I don't know your cockatrice and OS version because you didn't fill those information on the form as requested, so I can't help you more than that.
Feel free to reopen if you have more information on the issue.
