### ISSUE TITLE
j14 doesn't show in game

### ISSUE THREAD

**Issue by F34therz** [Cockatrice/Cockatrice#3876]
<b>System Information:</b>
  

  
_______________________________________________________________________________________

  hello, i'm really new to this ,

I just wanted to note that if u go to manage sets and u put J14 on top u don't get to see them in game

**Comment by tooomm** [comment]
What does your log say about loading the picture?

As asked when opening the ticket, please copy the output after selecting some j14 cards in the deck editor.

Probably it finds other pictures of the same cards from a different set that you formerly downloaded. You would have to remove those individually or wipe all picture cache on your disk (look at settings).

**Comment by ebbit1q** [comment]
it won't show images from a different set unless they are not in your database, run the oracle tool to update your card database. If the issue still happens, please include your log file.

**Comment by ZeldaZach** [comment]
This seems to work as intended now
