### ISSUE TITLE
Add shortcuts next to the menu items

### ISSUE THREAD

**Issue by Twainza** [Cockatrice/Cockatrice#3878]
Is it possible to also add shortcuts next to the right click menu items
Same as in the top menus
That way it is easy to learn them
Thanks

**Comment by ZeldaZach** [comment]
This seems very reasonable! Not sure how we haven't done this before... Would love to see these be customizable in our shortcut interface already.

**Comment by ebbit1q** [comment]
this is a mac only issue afaik
