### ISSUE TITLE
Summoning Sickness symbol for cards

### ISSUE THREAD

**Issue by Twainza** [Cockatrice/Cockatrice#3879]
Is it possible to make a function to put a summoning sickness symbol on creature cards
Maybe it can be placed there automatically by casting the creature
and be removed automatically at the upkeep
That way it will be much more easy to see what creatures have summoning sickness 
Sometimes it it difficult to see when there are a lot of creatures and multiple creatures are cast
Thanks

**Comment by ZeldaZach** [comment]
This is a game specific action, and you can always look through the log for what entered. Game specific rules aren't in the plans of the program at this time, so I'm gonna close as a no-fix. This could be related to the #3885 ticket
