### ISSUE TITLE
additional filters for "filter games"

### ISSUE THREAD

**Issue by dstinct** [Cockatrice/Cockatrice#388]
I really like watching games of other players. I usually run it in the background on my tv while I work on my laptop. What's kind of frustrating is that there are games listed that I cannot watch.

When a user turns on "show unavailable games", there should be a tick box that hides games that do not allow spectators.

There should also be the option to hide games of people that are not on your buddy list. This can be used to easily filter out people you cannot watch because it is buddy list only, or filter out players you don't want to play against because they aren't on your buddy list.

I also have a question about the buddy list lock. If there is a game being played that is "buddies only", do you have to be a buddy of the creator, or can you view it if you are buddies with the joining party?

**Comment by tooomm** [comment]
additional request to filter for "spectators allowed" games:
https://www.reddit.com/r/Cockatrice/comments/4vek30/sugestion_for_developers/

**Comment by knitknit** [comment]
I mentioned on #2431 I'm happy to tinker with this, feel free to assign to me.
