### ISSUE TITLE
Add button to copy the deck's security code

### ISSUE THREAD

**Issue by YvesHenri** [Cockatrice/Cockatrice#3880]
I'm probably going to create a discord bot for organizing championships, on which you'll need to register yourself by entering your deck's security code and it'll be available for opponents to check the deck's legality when both players are paired.

For better usability, I'd suggest to add a "compare button" right beside the deck's security code when in a match and another "copy button" right beside the deck's "hash" (security code) when in the deck editor view.

**Comment by ebbit1q** [comment]
and by security code you mean the hash?

**Comment by YvesHenri** [comment]
Exactly
