### ISSUE TITLE
"Error Transferring Card Database"

### ISSUE THREAD

**Issue by Rendroc** [Cockatrice/Cockatrice#3881]
<b>System Information:</b>
Client Version: 2.7.2 (2019-08-31)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.12.3
System Locale: en_US
Install Mode: Standard
---------------------------------------------------------------------------
Theme changed: "Default"
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
Language changed: ""
main(): starting main program
main(): MainWindow constructor finished
Spoilers Disabled
main(): ui.show() finished
Startup: found config with current version
CardDatabase::loadCardDatabases start
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Administrator/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 4 Cards = 0 Sets= 0
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Administrator/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 4 Cards = 0 Sets= 0
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Administrator/AppData/Local/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 0 Sets= 0
CardDatabase::loadCardDatabases failed
QWindowsWindow::setGeometry: Unable to set geometry 1920x1018+0+23 on QWidgetWindow/'MainWindowClassWindow'. Resulting geometry:  1920x1017+0+23 (frame: 8, 31, 8, 8, custom margin: 0, 0, 0, 0, minimum size: 848x1018, maximum size: 16777215x16777215).
PictureLoader: cache fail for "_trice_card_back_243452"
PictureLoader: cache fail for "_trice_card_back_243450"
CardDatabase::loadCardDatabases start
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Administrator/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 4 Cards = 0 Sets= 0
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Administrator/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 4 Cards = 0 Sets= 0
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Administrator/AppData/Local/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 0 Sets= 0
CardDatabase::loadCardDatabases failed
CardDatabase::loadCardDatabases start
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Administrator/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 4 Cards = 0 Sets= 0
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Administrator/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 4 Cards = 0 Sets= 0
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Administrator/AppData/Local/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 0 Sets= 0
CardDatabase::loadCardDatabases failed
CardDatabase::loadCardDatabases start
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Administrator/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 4 Cards = 0 Sets= 0
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Administrator/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 4 Cards = 0 Sets= 0
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Administrator/AppData/Local/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 0 Sets= 0
CardDatabase::loadCardDatabases failed
Error: Spoiler.xml not found or not deleted
External WM_DESTROY received for  QWidgetWindow(0x1139ffb8f00, name="DlgSettingsClassWindow") , parent:  QWindow(0x0) , transient parent:  QWidgetWindow(0x1139d294b80, name="MainWindowClassWindow")
Card Database load status:  4
CardDatabase::loadCardDatabases start
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Administrator/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 4 Cards = 0 Sets= 0
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Administrator/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 4 Cards = 0 Sets= 0
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Administrator/AppData/Local/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 0 Sets= 0
CardDatabase::loadCardDatabases failed

  
_______________________________________________________________________________________

Trying to intall Cockatrice on a Public windows computer, that I've installed it on many times before. When I try to download the card database I get an error message saying it cannot transfer the .json.xz file. Forbidden. When I click the link to the database that I found, it also says the page is Forbidden. What's going on?

**Comment by Rendroc** [comment]
I think it has to do with the admin setting at this gaming lounge. In the meantime, is there a link to the card database other than from the mtgjson website?

**Comment by ebbit1q** [comment]
This was a temporary failure of our card data provider mtgjson, functionality has been restored by now.
Those that are curious can track if this intermittent problem is permanently resolved at their repo https://github.com/mtgjson/mtgjson
