### ISSUE TITLE
More UI reccomendations

### ISSUE THREAD

**Issue by dstinct** [Cockatrice/Cockatrice#389]
1) increase zone view controls/navigation

Is it possible to unlock the scalability of the zones (library, graveyard, exile, etc)? If you are playing a deck like dredge that ends up having a large graveyard, it would be nice to be able to make it a user controlled width/height with a scrollbar. This stops it from covering up too much of the play area when things get out of hand.

It would also be nice to have a tick box that allows you to open your zones as exterior windows, instead of locking them into the viewport. Once again, for decks like dredge or burning wish decks that rely on the sideboard a lot, it would be nice to keep them open without having to find space in the viewport. You would want this togglable though because if you are watching a bunch of games, or leaving it running like I have on occasion, you could end up with a bunch of windows open.

2) quick relauch or update save settings

I've noticed that when a lot of settings are changed, you are required to relaunch in order for the settings to take effect. If I'm in the middle of a game and notice that an image appears that I don't want (say its an older card that has outdated text), there is no way for me to change set order in the settings and have it take effect without relaunching. Would there be a way to make a button that forces a reevaluation of the settings? This could temp purge the images in game and force a reload from the files.

I hope you don't mind me making all these separate issues. When I've done QA for work, they always ask me to log each point separately so nothing gets missed.

3) make it easier to hide fields on the right

I rarely care about the middle field that dictates viewers and players, I usually drag it all the way up to make it disappear. I then have to drag it back down to maximize the size of the card preview. If I drag that too far down, dragging it back up again makes the middle field appear again. Perhaps a check box at the top that says "Show: preview, users" would be beneficial. If you don't want the card preview either, you could just show the game timer and chat dialog, being able to maximize the size to see more information. I can't think of any reason why you would want to hide the chat, but you could make that an option too.

**Comment by ctrlaltca** [comment]
This has been already implemented quite some time ago.
