### ISSUE TITLE
multiple cards won't show up in custom set

### ISSUE THREAD

**Issue by IrdunWindseeker** [Cockatrice/Cockatrice#3890]
I'm trying to create a custom set but any card in the cards section after the first won't show up in cockatrice even after I restart it multiple times. I have the same code for each card so I don't know why it's not showing up in the system.

**Comment by ebbit1q** [comment]
Can you please include the xml so we can see what's wrong with it? are there symbols in it that need to be substituted with xml escapes?

**Comment by IrdunWindseeker** [comment]
Here is the XML.
[01.yugioh.xml.zip](https://github.com/Cockatrice/Cockatrice/files/4120487/01.yugioh.xml.zip)

**Comment by skwerlman** [comment]
in each card, you have a `</prop>` tag, but no `<prop>` tag before it

**Comment by tooomm** [comment]
@IrdunWindseeker Also, there are other yugioh sets from the community already: https://github.com/Cockatrice/Cockatrice/wiki/Custom-Cards-&-Sets#custom-card-databases-by-the-community
