### ISSUE TITLE
Legacy Images

### ISSUE THREAD

**Issue by Moorningstaar** [Cockatrice/Cockatrice#3891]
A couple of friends of mine and I have started a sort of MTG Redux, where we're starting magic over, as if Alpha had just been released.  In a couple of months we'll add Beta and so on and so on.

This has, unfortunately, revealed a slight problem in the area of erratas.  In short, many of the cards in Alpha have been modified in later sets.  These modifications are not shown in the original artwork, which leads to confusion.  I imagine this is a big problem with many early sets.

As near as I can tell, the only way to force the program to show newer images with the sets those images come from being disabled is to manually import each image.  What we need is a way to change the hierarchy that is being created so that people can play only with the old cards, but with the new images.

This could be accomplished by allowing us to change the image prioritization hierarchy to read disabled sets before enabled sets, or by simply offering us a check box to use the newest art.

Without going over the code I can't be sure, but I imagine you've created an object ('card' probably) that contains links to all the images for that card.  It shouldn't be hard to have the database retrieve the newest card regardless of which sets one is playing with.

Thanks for your time.

**Comment by skwerlman** [comment]
one easy possibility (though maybe not optimal) would be to just filter the deck editor when making decks using something like `set:lea or set:leb or ...`

also note that the modern (oracled) text is always available regardless what sets are enabled by going to the `description` or `both` tabs of the card info widget

**Comment by Moorningstaar** [comment]
Skwerlman, thank you.  Ironically, I was coming back here to delete this because I finally found the filter that was staring directly at me the whole time.  Cheers.
