### ISSUE TITLE
Custom Cards crashing Game

### ISSUE THREAD

**Issue by IrdunWindseeker** [Cockatrice/Cockatrice#3892]
<b>System Information:</b>
Client Version: 2.7.0 (2019-03-04)
[CockatriceXml4Parser] Unknown card property "format-standard" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "format-commander" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "format-modern" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "format-pauper" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "layout" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "side" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "type" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "maintype" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "manacost" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "cmc" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "colors" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "coloridentity" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "pt" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "loyalty" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "format-standard" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "format-commander" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "format-modern" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "format-pauper" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "layout" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "side" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "type" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "maintype" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "manacost" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "cmc" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "colors" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "coloridentity" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "pt" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "loyalty" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "format-standard" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "format-commander" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "format-modern" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "format-pauper" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "layout" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "side" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "type" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "maintype" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "manacost" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "cmc" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "colors" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "coloridentity" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "pt" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "loyalty" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "format-standard" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "format-commander" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "format-modern" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "format-pauper" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "layout" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "side" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "type" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "maintype" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "manacost" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "cmc" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "colors" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "coloridentity" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "pt" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "loyalty" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "format-standard" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "format-commander" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "format-modern" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "format-pauper" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "layout" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "side" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "type" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "maintype" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "manacost" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "cmc" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "colors" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "coloridentity" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "pt" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "loyalty" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "format-standard" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "format-commander" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "format-modern" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "format-pauper" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "layout" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "side" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "type" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "maintype" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "manacost" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "cmc" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "colors" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "coloridentity" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "pt" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "loyalty" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "format-standard" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "format-commander" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "format-modern" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "format-pauper" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "layout" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "side" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "type" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "maintype" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "manacost" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "cmc" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "colors" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "coloridentity" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "pt" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "loyalty" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "format-standard" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "format-commander" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "format-modern" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "format-pauper" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "layout" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "side" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "type" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "maintype" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "manacost" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "cmc" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "colors" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "coloridentity" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "pt" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "loyalty" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "format-standard" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "format-commander" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "format-modern" , trying to continue anyway
[CockatriceXml4Parser] Unknown card property "format-pauper" , trying to continue anyway
[CardDatabase] loadCardDatabase(): Path = "/Users/bradentraw/Library/Application Support/Cockatrice/Cockatrice/customsets/01.yugioh.xml" Status = 0 Cards = 21067 Sets= 472
[CockatriceXml3Parser] Trying to parse:  "/Users/bradentraw/Library/Application Support/Cockatrice/Cockatrice/customsets/02.01.customcards.xml"
[CockatriceXml3Parser] Parsing failed: wrong element tag "wordDocument"
[CockatriceXml4Parser] Trying to parse:  "/Users/bradentraw/Library/Application Support/Cockatrice/Cockatrice/customsets/02.01.customcards.xml"
[CockatriceXml4Parser] Parsing failed: wrong element tag "wordDocument"
[CardDatabase] loadCardDatabase(): Path = "/Users/bradentraw/Library/Application Support/Cockatrice/Cockatrice/customsets/02.01.customcards.xml" Status = 2 Cards = 21067 Sets= 472
[CockatriceXml3Parser] Trying to parse:  "/Users/bradentraw/Library/Application Support/Cockatrice/Cockatrice/customsets/DOM.xml"
[CardDatabase] loadCardDatabase(): Path = "/Users/bradentraw/Library/Application Support/Cockatrice/Cockatrice/customsets/DOM.xml" Status = 0 Cards = 21067 Sets= 472
[CockatriceXml3Parser] Trying to parse:  "/Users/bradentraw/Library/Application Support/Cockatrice/Cockatrice/customsets/TK.xml"
[CardDatabase] loadCardDatabase(): Path = "/Users/bradentraw/Library/Application Support/Cockatrice/Cockatrice/customsets/TK.xml" Status = 0 Cards = 21068 Sets= 472
CardDatabase::loadCardDatabases success!

  
_______________________________________________________________________________________

Hello again. As soon as I drag my custom cards from the hand onto the field, the game crashes. I think I may have coded them wrong, but I have no idea what's wrong with them. I have included some examples from the .xml here, as Github is not letting me upload the full .xml:

```
<card>
  <name>Torrential Tribute</name>
  <text></text>
  <token></token>
  <cipt></cipt>
  <upsidedown></upsidedown>
  <tablerow>3</tablerow>
  <set rarity="common" uuid="DBS-050" num="50" muid="000050" picurl="https://i.ibb.co/fxps3VG/Torrential-Tribute.png">DBS</set>
  <related>Another card name</related>
    <layout>normal</layout>
    <side>front</side>
    <type>Instant</type>
    <maintype>Instant</maintype>
    <manacost>R</manacost>
    <cmc>1</cmc>
    <colors>R</colors>
    <coloridentity>R</coloridentity>
    <pt>0/2</pt>
    <loyalty>4</loyalty>
    <format-standard>legal</format-standard>
    <format-commander>legal</format-commander>
    <format-modern>legal</format-modern>
    <format-pauper>legal</format-pauper>
  <prop></prop>
</card>
<card>
  <name>Trap Hole</name>
  <text></text>
  <token></token>
  <cipt></cipt>
  <upsidedown></upsidedown>
  <tablerow>3</tablerow>
  <set rarity="common" uuid="DBS-050" num="50" muid="000050" picurl="https://i.ibb.co/8Xf6Dbf/Trap-Hole.png">DBS</set>
  <related>Another card name</related>
    <layout>normal</layout>
    <side>front</side>
    <type>Instant</type>
    <maintype>Instant</maintype>
    <manacost>R</manacost>
    <cmc>1</cmc>
    <colors>R</colors>
    <coloridentity>R</coloridentity>
    <pt>0/2</pt>
    <loyalty>4</loyalty>
    <format-standard>legal</format-standard>
    <format-commander>legal</format-commander>
    <format-modern>legal</format-modern>
    <format-pauper>legal</format-pauper>
  <prop></prop>
</card>
<card>
  <name>Wall of Thorns</name>
  <text></text>
  <token></token>
  <cipt></cipt>
  <upsidedown></upsidedown>
  <tablerow>3</tablerow>
  <set rarity="common" uuid="DBS-050" num="50" muid="000050" picurl="https://i.ibb.co/PGM5rtW/Wall-of-Thorns.png">DBS</set>
  <related>Another card name</related>
    <layout>normal</layout>
    <side>front</side>
    <type>Instant</type>
    <maintype>Instant</maintype>
    <manacost>R</manacost>
    <cmc>1</cmc>
    <colors>R</colors>
    <coloridentity>R</coloridentity>
    <pt>0/2</pt>
    <loyalty>4</loyalty>
    <format-standard>legal</format-standard>
    <format-commander>legal</format-commander>
    <format-modern>legal</format-modern>
    <format-pauper>legal</format-pauper>
  <prop></prop>
</card>
<card>
  <name>Zero Gravity</name>
  <text></text>
  <token></token>
  <cipt></cipt>
  <upsidedown></upsidedown>
  <tablerow>3</tablerow>
  <set rarity="common" uuid="DBS-050" num="50" muid="000050" picurl="https://i.ibb.co/s6TjDS2/Zero-Gravity.png">DBS</set>
  <related>Another card name</related>
    <layout>normal</layout>
    <side>front</side>
    <type>Instant</type>
    <maintype>Instant</maintype>
    <manacost>R</manacost>
    <cmc>1</cmc>
    <colors>R</colors>
    <coloridentity>R</coloridentity>
    <pt>0/2</pt>
    <loyalty>4</loyalty>
    <format-standard>legal</format-standard>
    <format-commander>legal</format-commander>
    <format-modern>legal</format-modern>
    <format-pauper>legal</format-pauper>
  <prop></prop>
</card>
<card>
  <name>Enemy Controller</name>
  <text></text>
  <token></token>
  <cipt></cipt>
  <upsidedown></upsidedown>
  <tablerow>3</tablerow>
  <set rarity="common" uuid="DBS-050" num="50" muid="000050" picurl="https://i.ibb.co/fr20Qkf/image.png">DBS</set>
  <related>Another card name</related>
    <layout>normal</layout>
    <side>front</side>
    <type>Instant</type>
    <maintype>Instant</maintype>
    <manacost>R</manacost>
    <cmc>1</cmc>
    <colors>R</colors>
    <coloridentity>R</coloridentity>
    <pt>0/2</pt>
    <loyalty>4</loyalty>
    <format-standard>legal</format-standard>
    <format-commander>legal</format-commander>
    <format-modern>legal</format-modern>
    <format-pauper>legal</format-pauper>
  <prop></prop>
</card>
```

**Comment by IrdunWindseeker** [comment]
Nevermind, I got it to zip.
[01.yugioh.xml.zip](https://github.com/Cockatrice/Cockatrice/files/4162407/01.yugioh.xml.zip)

**Comment by ebbit1q** [comment]
The client shouldn't crash no matter what you put into that xml, could you please give us some steps for reproducing this crash?

**Comment by IrdunWindseeker** [comment]
I actually got it fixed by myself by deleting a lot of the tags for the card for some reason? It works for me now. You might want to see if downloading that xml and using the custom cards in a game crashes it for you. Regardless, I got it fixed for myself.

**Comment by ebbit1q** [comment]
I used the xml you gave and made a deck with every card and played them all at once without crashing.

**Comment by tooomm** [comment]
He is still on 2.7.0. Maybe there changed something in between?
