### ISSUE TITLE
Custom Cards not displaying images/displaying alternate images

### ISSUE THREAD

**Issue by IrdunWindseeker** [Cockatrice/Cockatrice#3893]
<b>System Information:</b>
  

  
_______________________________________________________________________________________

 Ok, hopefully this is the last time I have to post here. I'm having this strange issue with my custom cards where the image either won't load or it will display the image of... a different custom card. I can't figure out why. I've repasted the image links multiple times, rewritten the code multiple times, and there are 0 visible differences in the code between the non-visible images and the visible ones. Plus, there are about 3 cards that display an entirely different custom card image even though the image link isn't even remotely the same. What is going on? Attached is the xml file.
Here are some screenshots of what I'm talking about
![image](https://user-images.githubusercontent.com/26135995/74065895-e8b75200-49c3-11ea-965d-adefc6066aef.png)
![image](https://user-images.githubusercontent.com/26135995/74065906-f240ba00-49c3-11ea-8110-7eaf8e8cf3a0.png)
![image](https://user-images.githubusercontent.com/26135995/74065972-1d2b0e00-49c4-11ea-8276-5d23cc4c8f89.png)
![image](https://user-images.githubusercontent.com/26135995/74065992-2916d000-49c4-11ea-95b3-b2b123ed9877.png)

[02.yugioh.xml.zip](https://github.com/Cockatrice/Cockatrice/files/4172934/02.yugioh.xml.zip)

**Comment by IrdunWindseeker** [comment]
Also I should note, whenever I add a new card to the xml file now, the image just won't load. At all. The card will show up in the database, but no image, no matter what I do.

**Comment by skwerlman** [comment]
try going into settings and clearing downloaded images

**Comment by IrdunWindseeker** [comment]
Just tried it, no dice :(

**Comment by IrdunWindseeker** [comment]
Wait... Now NONE of the images are loading

**Comment by tooomm** [comment]
Can you post the output of the debut log?

**Comment by IrdunWindseeker** [comment]
Client Version: 2.7.0 (2019-03-04)
Client Operating System: macOS Mojave (10.14)
Build Architecture: 64-bit
Qt Version: 5.12.1
System Locale: en_US
Install Mode: Standard
---------------------------------------------------------------------------
Theme changed: "Default"
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
Language changed: ""
main(): starting main program
main(): MainWindow constructor finished
CardDatabase::loadCardDatabases start
[CockatriceXml3Parser] Trying to parse:  "/Users/bradentraw/Library/Application Support/Cockatrice/Cockatrice/cards.xml"
[CockatriceXml3Parser] Parsing failed: wrong version 4
[CockatriceXml4Parser] Trying to parse:  "/Users/bradentraw/Library/Application Support/Cockatrice/Cockatrice/cards.xml"
main(): ui.show() finished
PictureLoader: cache fail for "_trice_card_back_232291"
Spoiler Service Online
File Hash = "\xAB\xFF\xD4\xB0\xD1""3W}\xCF\xC3\xB1""6\xAAP\xF9\xB5"
Data Hash = "\xAB\xFF\xD4\xB0\xD1""3W}\xCF\xC3\xB1""6\xAAP\xF9\xB5"
Spoilers Up to Date
[CardDatabase] loadCardDatabase(): Path = "/Users/bradentraw/Library/Application Support/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 20594 Sets= 472
[CockatriceXml3Parser] Trying to parse:  "/Users/bradentraw/Library/Application Support/Cockatrice/Cockatrice/tokens.xml"
[CockatriceXml3Parser] Parsing failed: wrong version 4
[CockatriceXml4Parser] Trying to parse:  "/Users/bradentraw/Library/Application Support/Cockatrice/Cockatrice/tokens.xml"
[CardDatabase] loadCardDatabase(): Path = "/Users/bradentraw/Library/Application Support/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 21047 Sets= 472
[CockatriceXml3Parser] Trying to parse:  "/Users/bradentraw/Library/Application Support/Cockatrice/Cockatrice/spoiler.xml"
[CardDatabase] loadCardDatabase(): Path = "/Users/bradentraw/Library/Application Support/Cockatrice/Cockatrice/spoiler.xml" Status = 0 Cards = 21047 Sets= 472
[CockatriceXml3Parser] Trying to parse:  "/Users/bradentraw/Library/Application Support/Cockatrice/Cockatrice/customsets/02.yugioh.xml"
[CardDatabase] loadCardDatabase(): Path = "/Users/bradentraw/Library/Application Support/Cockatrice/Cockatrice/customsets/02.yugioh.xml" Status = 0 Cards = 21289 Sets= 473
[CockatriceXml3Parser] Trying to parse:  "/Users/bradentraw/Library/Application Support/Cockatrice/Cockatrice/customsets/TK.xml"
[CardDatabase] loadCardDatabase(): Path = "/Users/bradentraw/Library/Application Support/Cockatrice/Cockatrice/customsets/TK.xml" Status = 0 Cards = 21290 Sets= 473
CardDatabase::loadCardDatabases success
PictureLoader: [card:  "Alpha the Magnet Warrior"  set:  "DBS" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Alpha the Magnet Warrior"  set:  "DBS" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Alpha the Magnet Warrior"  set:  "DBS" ]: Requested set property ( "muid" ) for Url template ( "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Alpha the Magnet Warrior"  set:  "DBS" ]: Trying to load picture
PictureLoader: [card:  "Alpha the Magnet Warrior"  set:  "DBS" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Alpha the Magnet Warrior"  set:  "DBS" ]: Trying to download picture from url: "http://gatherer.wizards.com/Handlers/Image.ashx?name=Alpha the Magnet Warrior&type=card"
PictureLoader: [card:  "Alpha the Magnet Warrior"  set:  "DBS" ]: following redirect: "https://gatherer.wizards.com/Handlers/Image.ashx?name=Alpha the Magnet Warrior&type=card"
PictureLoader: [card:  "Alpha the Magnet Warrior"  set:  "DBS" ]:Picture downloaded, but blacklisted, will consider it as not found
PictureLoader: [card:  "Alpha the Magnet Warrior"  set:  "" ]:  Picture NOT found, download failed, no more url combinations to try: BAILING OUT
QPixmap::scaled: Pixmap is a null pixmap
PictureLoader: [card:  "Amphibious Bugroth MK-3"  set:  "DBS" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Amphibious Bugroth MK-3"  set:  "DBS" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Amphibious Bugroth MK-3"  set:  "DBS" ]: Requested set property ( "muid" ) for Url template ( "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Amphibious Bugroth MK-3"  set:  "DBS" ]: Trying to load picture
PictureLoader: [card:  "Amphibious Bugroth MK-3"  set:  "DBS" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Amphibious Bugroth MK-3"  set:  "DBS" ]: Trying to download picture from url: "http://gatherer.wizards.com/Handlers/Image.ashx?name=Amphibious Bugroth MK-3&type=card"
PictureLoader: [card:  "Amphibious Bugroth MK-3"  set:  "DBS" ]: following redirect: "https://gatherer.wizards.com/Handlers/Image.ashx?name=Amphibious Bugroth MK-3&type=card"
PictureLoader: [card:  "Amphibious Bugroth MK-3"  set:  "DBS" ]:Picture downloaded, but blacklisted, will consider it as not found
PictureLoader: [card:  "Amphibious Bugroth MK-3"  set:  "" ]:  Picture NOT found, download failed, no more url combinations to try: BAILING OUT
QPixmap::scaled: Pixmap is a null pixmap

**Comment by IrdunWindseeker** [comment]
So, none of the images are loading now. Like none.

**Comment by IrdunWindseeker** [comment]
Yep, that fixed it. But now I have a new problem: the cards won't have their types loaded into the system, so they aren't categorized at all :(

**Comment by ebbit1q** [comment]
[02.yugioh.xml.zip](https://github.com/Cockatrice/Cockatrice/files/4173597/02.yugioh.xml.zip)
You're welcome

**Comment by Andr255** [comment]
As imagens das cartas de Yu-Gi-Oh não aparecem no meu cockatrice, alguém poderia me dar um suporte tbm?

**Comment by ebbit1q** [comment]
could you ask your question in english?
