### ISSUE TITLE
Noninteractive installer

### ISSUE THREAD

**Issue by fenhl** [Cockatrice/Cockatrice#3894]
**Description of New Feature**

It would be nice if the installer could accept command-line options to automate the installation process (or if a separate noninteractive installer could be added). Ideally I'd like to be able to run something like `Cockatrice-Faerie_Tales-2.7.2-win64.exe --noninteractive --portable --install-path=.\foo\trice` and have that command install Cockatrice Portable at that location and exit without any user interaction other than the Windows UAC prompt.

**Additional Context**

This would allow me to further automate a maintenance chore that includes bundling a portable Cockatrice with custom cards.

# Solution

See https://github.com/Cockatrice/Cockatrice/issues/3894#issuecomment-583789401.

**Comment by ebbit1q** [comment]
Our NSIS installer should support these commandline arguments https://nsis.sourceforge.io/Docs/Chapter3.html#installerusage

I'm not sure how difficult it would be to change these, our installer is generated from the script here https://github.com/Cockatrice/Cockatrice/blob/master/cmake/NSIS.template.in

**Comment by ebbit1q** [comment]
I found another alternative: you can extract the executables using 7zip and do with them as you'd like.

I tested this using p7zip and did a testrun of cockatrice with wine, it should work on a windows box too.

**Comment by fenhl** [comment]
The NSIS command line arguments are exactly what I was looking for, thanks! For future reference, the arguments are:

* `/S` to enable noninteractive mode
* `/PORTABLE` to select the portable install
* `/D=C:\Users\Fenhl\foo\trice` to set the install location

**Comment by skwerlman** [comment]
@fenhl It'd be cool if you could add this info to the wiki so its a bit more discoverable

**Comment by tooomm** [comment]
Where would that go? @skwerlman

**Comment by skwerlman** [comment]
i was gonna say somewhere in the install guide, but i guess we dont have one?

**Comment by ctrlaltca** [comment]
Closing this issue. The feature already exists, but it's probably overkill for us tring to document in our wiki all the features available on other software that we sue or ship with Cockatrice (in this case, NSIS). A user looking for the same answer will still find the closed issue with the solution.
