### ISSUE TITLE
Deck Builder won't sort card types with custom cards

### ISSUE THREAD

**Issue by IrdunWindseeker** [Cockatrice/Cockatrice#3895]
<b>System Information:</b>
  

  
_______________________________________________________________________________________

Ok, last time I promise. The types that I put for my cards show up in the left side, in the card searcher, but the deck builder in the right won't make any distinction, making it impossible to sort between different types. Attached is the XML was well as a screenshot. 

[02.yugioh.xml 2.zip](https://github.com/Cockatrice/Cockatrice/files/4173609/02.yugioh.xml.2.zip)

![image](https://user-images.githubusercontent.com/26135995/74077086-d8ff3400-49ea-11ea-9c66-edddfe0d9dcf.png)

**Comment by ebbit1q** [comment]
Add <maintype> tags in your <prop> tags in your <card> tags, see the wiki: https://github.com/Cockatrice/Cockatrice/wiki/Custom-Cards-&-Sets#to-add-your-own-custom-cards-follow-these-steps
