### ISSUE TITLE
fails to install on Debian

### ISSUE THREAD

**Issue by jcdc404** [Cockatrice/Cockatrice#3899]
The following packages have unmet dependencies:
 cockatrice : Depends: libqt5multimedia5-plugins but it is not installed
              Depends: libprotobuf10 but it is not installable

**Comment by ctrlaltca** [comment]
In the new debian buster libprotobuf was upgraded from 3.0 to 3.6, and the library version changed from libprotobuf10 to libprotobuf17.
I'm afraid you'll need to compile Cockatrice yourself by now, here's some instructions:
https://github.com/Cockatrice/Cockatrice/wiki/Compiling-Cockatrice-(Linux)#debian
You'll need to adapt the version numbers in the instructions.

**Comment by vindicate7** [comment]
This is absolutely correct, and using this knowledge I was able to compile Cockatrice onto Debian 10 running in a Termux shell on Android.  Thats right, Cockatrice on Android!   Check out the wiki for the post!

**Comment by ebbit1q** [comment]
Absolutely do check this guide, even if only for it's infinite entertainment value. Here it is specifically https://github.com/Cockatrice/Cockatrice/wiki/Cockatrice-on-Android-(phone-tablet)

**Comment by ctrlaltca** [comment]
A package for Debian Buster is now available.
