### ISSUE TITLE
Document Servatrice password hashing and provide reference implementations

### ISSUE THREAD

**Issue by Lachee** [Cockatrice/Cockatrice#390]
How do one use the database for the users? I have managed to figure out most parameters except token and password_sha512. 

password_sha512 is fairly self explanatory, however the DB states its 120 long, where sha512 encrypts 128 long.

What is the token?

Some documentation on the database would be nice.

**Comment by woogerboy21** [comment]
One thing to mention, with the more recent updates the token field is now used.

**Comment by ctrlaltca** [comment]
The needed information and an example implementation is available at https://github.com/Cockatrice/Cockatrice/wiki/Setting-up-Servatrice
