### ISSUE TITLE
Crashing When Trying to Load Deck

### ISSUE THREAD

**Issue by D0nV170** [Cockatrice/Cockatrice#3903]
<b>System Information:</b>
  
Client Version: 2.7.2-custom(c1f4b74) (2019-08-31)
Client Operating System: macOS Mojave (10.14)
Build Architecture: 64-bit
Qt Version: 5.13.0
System Locale: en_US
Install Mode: Standard

  
_______________________________________________________________________________________

  
I had a user report the deck that has been attached crashes their client any time they try to load it into their deck editor. I was able to load the deck just fine and they said that they were able to manually edit it and after experimenting with several cards, they found if they removed Karmic Guide, the deck would load fine. I have attached their error log as well. I don't know if this is just specific to them or something that is an actual issue, so I figured I'd at least make y'all aware of it. Thank you.

[AlesharistocratsCRASHWARNINGDONOTOPEN.zip](https://github.com/Cockatrice/Cockatrice/files/4271099/AlesharistocratsCRASHWARNINGDONOTOPEN.zip)
[cockatriceerrorlog.txt](https://github.com/Cockatrice/Cockatrice/files/4271100/cockatriceerrorlog.txt)

**Comment by ebbit1q** [comment]
We need a specific way to replicate this otherwise we really can't do anything.
