### ISSUE TITLE
Websockets

### ISSUE THREAD

**Issue by SirZach** [Cockatrice/Cockatrice#391]
Hi, me and some of my buddies are building a cockatrice web app! I've been in touch with Woogerworks on twitter making sure he'd be okay with it and he didn't object. We're now at a point where we need to start integrating with the server. Right now, because the server speaks via protocol buffers, the app cannot talk to it. We've come up with two options:

1) Build a dumb translation layer that will take JSON and turn it into the appropriate protocol buffer. This is proving to be more challenging than expected and also poses a problem with the number of clients that the server allows considering all the web clients would have to go through it.

2) Add websocket support to servatrice in order to allow the web clients direct access to the server, much like how the thick clients work today. This is our preferred solution.

In order to make 2 work, we would have to submit some PRs for servatrice to open itself to websocket connections and we want to make sure that's something you would be on board with. 

If you want to see how the web client has turned out so far, you clone it from https://github.com/thomasjmwb/bbbbbbbbbbbbbbb and run it locally. We hope to have this stood up on heroku in the very near future. Thanks so much for your time!

**Comment by galaxiecruzin** [comment]
@SirZach I'd be interested in helping out. Let me know what you need to push this forward

**Comment by woogerboy21** [comment]
I actually started to tinker with the idea of integrating websockets into servatrice.  You can see an example of a server with both tcp and websocket listeners at https://github.com/woogerboy21/CCGTableTop 

The thing that would need to get done if we added things to servatrice is to forward all the binary communication from the websocket listener into the functions that handle the binary translations of the protobuf content and of course vice versa.  Ive just been focused on other areas in the app that could use some improvement (like moderation tools).

**Comment by galaxiecruzin** [comment]
Right on @woogerboy21 . I found SirZach's github projects and took a peek at the web interface he linked to on heroku. I'm not very good with javascript and front end ui, but the websocket translation is something up my alley

**Comment by SirZach** [comment]
@galaxiecruzin thanks for checking it out! I ended up using my own server to handle the web-socket connections and does not use Servatrice. At this point, Webatrice has gone too far to be able to be used for Cockatrice and Servatrice but I think it's still an awesome idea to allow Servatrice to use web-socket connections for a different web interface.

**Comment by woogerboy21** [comment]
@SirZach so what did you end up using the interface for if its not talking to servatrice?
And I still like the idea of having web sockets available. Maybe if I get some extra time I'll roll in the web socket server into a real servatrice instance but would need someone to build the protocol handler layer as I am more focused on getting other area's of the app up and functionally sound.

**Comment by SirZach** [comment]
@woogerboy21 we opted to go with https://www.firebase.com/ as a means for a database and live updates. It's pretty neat in that you don't write any server code, all of it is handled within the web app.

**Comment by woogerboy21** [comment]
Are your just using it for deck construction then?  Or is it some how relaying the data to servatrice for other area's of the client (like game data).

**Comment by SirZach** [comment]
You can do deck construction and game play with some chat room functionality built in as well. It doesn't interact with Servatrice.

**Comment by galaxiecruzin** [comment]
I've been searching around for more information on this topic. Did some reading on Google's protobuf docs. I'm finding quite a bit of information for implementing protocol buffers in javascript. Could you explain your thought process @woogerboy21 with doing the translation to a websocket data stream? If SirZach has already diverged from this path and a new UI would need to be created, then a more elegant solution may present itself in another way. I'm going to try to hit up the local Meteor js meetup crew to see get their thoughts on this topic.

**Comment by woogerboy21** [comment]
If your using PB as the protocol to serialize the data being sent then all that should be needed is the binary data passed to the existing protocol handler functions and I believe everything should just work.  When I mention a translation layer I was thinking more of adding a layer in that would allow for other protocols to be used since in the original post json was mentioned.

**Comment by Daenyth** [comment]
I don't think we should expand the data layer - it would create a high maintenance burden. Protobuf is widely supported across many platforms, so I don't think we need to offer other things. As for the binary packing, here's an example in python to refer to: https://github.com/Cockatrice/Cockatrice/blob/master/servatrice/scripts/register.py

**Comment by ctrlaltca** [comment]
For your interest, here's a branch i'm working on: https://github.com/ctrlaltca/Cockatrice/tree/websockets
It that adds websocket support on servatrice and contains a sample javascript webclient that's able to login by now.

**Comment by TMiguelT** [comment]
@ctrlaltca have there been any issues with the servitrice patch? Do you plan to open a PR to have it integrated?

**Comment by ctrlaltca** [comment]
I'd like to get at least the main room chat working before attempting to merge it. If you want to help or pick up the task, i can get the code in good shape and make a PR.

**Comment by TMiguelT** [comment]
I'm definitely interested in helping. I'll see what I can do when I get home in a few days

**Comment by TMiguelT** [comment]
Any pointers about where to start with the chat?

**Comment by Daenyth** [comment]
Can it get a connection and keep it open by replying to pings yet?

**Comment by ctrlaltca** [comment]
What's implemented by now in servatrice:
 * servatrice listens on port 4748 for websockets (confgurable in the .ini)
 * websockets connections are handled in a special pool (qt's websockets can not be moved to different threads, so no multi-pool, sorry)
 * servatrice: the old xml handshake and "messageInProgress" handling used for TCP sockets are not used: websockets messages are hardwired to protobuf

What's implemented by now in the webclient:
 * simple tabbed UI using jqueryUI + worker javascript object
 * websockets and protobuf handling (https://github.com/dcodeIO/protobuf.js) using the very same .proto files from ```common/pb```
 * Commands: Command_Login, Command_ListRooms, Command_JoinRoom
 * Reponses: Response_Login, Event_ServerMessage, Event_ListRooms, Response_JoinRoom
 * Parse the responses and provides useful error messages
 * Autojoin for rooms

The next step is to implement the commands and events used to send/receive room messages, and then the simple "main room chat" app will be working.

**Comment by ctrlaltca** [comment]
> Any pointers about where to start with the chat?

 1. Check out my branch from https://github.com/ctrlaltca/Cockatrice/tree/websockets
 2. recompile servatrice, configure it a start it up
 3. get a webserver working on your development box
 3. ```ln -s``` the "webclient" folder inside your webserver's document root
 4. browse to http://127.0.0.1/webclient or wherever you linked the webclient folder to

Some basic idea on the structure:
 * ```js/``` contains js libraries: jQuery, jQueryUI, protobuf.js and dependencies (bytebuffer.js, long.js);
 * ```webclient.js``` contains the "WebClient" object that implements the cockatrice network protocol;
 * ```index.html``` contains the html structure and some js code to bring up the UI and react to callbacks fired by WebClient
 * ```style.css``` should be self-explanatory

**Comment by TMiguelT** [comment]
Thanks, I understand the basic stuff like that. What I needed was what you said that 

>The next step is to implement the commands and events used to send/receive room messages

Which file will this implementation go in?

**Comment by TMiguelT** [comment]
Also the webclient should be in a separate repository, no? Actually servatrice and cockatrice should be separated as well right? Because this way we can't update the server without the clients thinking they're out or date. 

Because I was thinking of making a webclient as well with a more framework approach (rather than jQuery), so I think the client should be a separate thing

**Comment by TMiguelT** [comment]
Although perhaps there should be one official webclient. Maybe it would eventually be hosted on GitHub somewhere? It would be static so it would work on GitHub pages I think.

**Comment by ctrlaltca** [comment]
> Which file will this implementation go in?

In webclient.js the network  and message parsing implementation; in index.html the "add the text to the UI" part.

> Also the webclient should be in a separate repository, no?
> Actually servatrice and cockatrice should be separated as well right?

I agree with the idea, but servatrice and cockatrice share a lot of code (in common/), since cockatrice's "local game" mode is basically an embedded server.

> Because I was thinking of making a webclient as well with a more framework approach (rather than jQuery)

I agree on this one, too; by now the webclient object is not using jQuery at all (no $ in the file), jQuery is used only in index.html to update the UI.

> Maybe it would eventually be hosted on GitHub somewhere? It would be static so it would work on GitHub pages I think.

Yep, there's no server-side code needed, so GitHub hosting will suffice.

**Comment by Daenyth** [comment]
> Also the webclient should be in a separate repository

Yes, please.

**Comment by TMiguelT** [comment]
>In webclient.js the network and message parsing implementation; in index.html the "add the text to the UI" part.

So you're saying that the websocket implementation in servatrice is done and all that's needed is the client? Can't we just merge the servatrice changes and then start on the new repo for the client then? 

As I understand, you're writing a UI independent client object that we can listen to and update the UI with? That sounds very flux like, and I'd love to write a react app for the UI. 

If that's the case, and you just need help with JavaScript then that should be easy and I'll give it a try later today. I'm a lot more comfortable with JavaScript than C++

**Comment by TMiguelT** [comment]
@Daenyth would you like to make a Cockatrice/WebClient repo then?

**Comment by Daenyth** [comment]
re: ui/client logic separation - as I mentioned in the updater stuff, you'll get the most flexibility if they are totally separate and the ui just instantiates and invokes the client.

I can make the repo, yes.

**Comment by TMiguelT** [comment]
@Daenyth I suppose you should set @ctrlaltca as a contributor?

**Comment by TMiguelT** [comment]
Also I'm not getting a servatrice executable when I build cockatrice. Am I missing something? I just followed the usual steps on https://github.com/Cockatrice/Cockatrice#building--

**Comment by skwerlman** [comment]
You're using `-DWITH_SERVER=1`, ye?

**Comment by TMiguelT** [comment]
Heh, nope. Thanks for pointing that out

**Comment by TMiguelT** [comment]
@ctrlaltca Is the server patch indeed complete? Because then I'll start on a PR for the webclient

**Comment by ctrlaltca** [comment]
The server patch is working, but has not been tested on any server with a real user load > 2 users.
I've just updated the webclient adding ping and room messages support, so now it's possible to chat on rooms.
