### ISSUE TITLE
Deleting Messages in Main Chat

### ISSUE THREAD

**Issue by D0nV170** [Cockatrice/Cockatrice#3917]
**Similar Requests**
There was one suggested about a mass clear of Main chat which led into users being able to edit their own messages for a certain amount of time but that was deemed to much work. 

**Description of New Feature**
Mods should be able to delete messages in Main chat.

**Additional Context**

**Comment by ZeldaZach** [comment]
Maybe expand this to "clear main chat for all users"

cc: @ctrlaltca

**Comment by ZeldaZach** [comment]
I like this ticket. Having the ability to nuke chat and/or remove specific messages would be useful.

**Comment by D0nV170** [comment]
This would still be super useful.
