### ISSUE TITLE
Muting Users from Main Chat

### ISSUE THREAD

**Issue by D0nV170** [Cockatrice/Cockatrice#3918]
**Similar Requests**
None surprisingly.

**Description of New Feature**
Mods should be able to prevent a user from typing in the Main chat for a certain amount of time.

**Additional Context**

**Comment by ZeldaZach** [comment]
cc: @ctrlaltca

**Comment by ZeldaZach** [comment]
This isn't gonna happen most likely, so we're gonna close it. But #3917 looks very promising
