### ISSUE TITLE
Library's "Always reveal top card" option does not reset between games

### ISSUE THREAD

**Issue by Nightfirecat** [Cockatrice/Cockatrice#392]
When ending a game while the "Always reveal top card" option is enabled, the option will remain enabled, but will cease to reveal the top card. (top card is not visible, is not announced in chat, but the checkbox is checked)

Steps to reproduce:

1. Cockatrice > Start Local Game; any number of players
2. Load any deck, start game
3. Right-click library > click "Always reveal top card"
4. Concede the game
5. Start game
6. Right-click library; "Always reveal top card" option is still selected, but not functioning

**Comment by Daenyth** [comment]
Fixed in #520
