### ISSUE TITLE
Fullscreen mode

### ISSUE THREAD

**Issue by CTimmerman** [Cockatrice/Cockatrice#3923]
Related to #140, #2708, and #1936 (does MacOS have fullscreen or is that also merely maximized?).

A "Fullscreen (Alt+Enter)" item in the View menu that would hide the task bar, window decoration, menu bar, and tab bar.

![image](https://user-images.githubusercontent.com/9662163/77230236-239bd080-6b93-11ea-8d07-9cfff3435b86.png)

**Comment by ZeldaZach** [comment]
On Windows you can press CTRL + F (Cockatrice > Full Screen) to get full screen mode.
