### ISSUE TITLE
Card info as tooltip

### ISSUE THREAD

**Issue by CTimmerman** [Cockatrice/Cockatrice#3924]
Related to #140 (seems more like mousewheel zoom as in Duels and Arena).

Only showing the card info as a tooltip instead of a permanent window would be nice.

![image](https://user-images.githubusercontent.com/9662163/77230470-aec99600-6b94-11ea-922c-35ae123c09ff.png)

**Comment by ZeldaZach** [comment]
This exists as middle mouse button press down already. This might not be well documented, so we'll need to do a better job at that.
