### ISSUE TITLE
A Way to See the In-Game Log

### ISSUE THREAD

**Issue by D0nV170** [Cockatrice/Cockatrice#3925]
**Similar Requests**

**Description of New Feature**
Mods being able to view the in-game log, as in the game actions, not just chat of a current game without having to wait for the game to end. 

**Additional Context**
I had a report of a player kicking players out of a game but the game was only 5 minutes old and it was in progress so I wanted to be able to see if a first game did start or if the player was kicked prior to the game start. I wasn't able to verify that until an hour later when the game ended and I was able to pull the replay.

**Comment by ZeldaZach** [comment]
I'm gonna call this a dupe of #1953 as we want a way to give mods access to replays in-client, and quicker.
