### ISSUE TITLE
Mac 10.12.6 (Download)

### ISSUE THREAD

**Issue by Jasonic-gif** [Cockatrice/Cockatrice#3926]
<b>System Information:</b>
  

   Mac 10.12.6 working fine until last night... (must be the new update/version). Downloads fine but won’t open (incompatible)
_______________________________________________________________________________________

  
As of last night won’t work with Mac 10.12.6

**Comment by ctrlaltca** [comment]
Can you please state the exact error that you get, or a screenshot of what's blocking you from using Cockatrice?
Also, a pointer to the exact file you have downloaded could be useful in trying to help you.
Thank you.

**Comment by Jasonic-gif** [comment]
“You can’t use this version of the application “cockatrice” with this
version of macOS”

“You have macOS 10.12.16. The application requires macOS 10.13 or later.”

I’ve tried downloading and running both macOS options from the cockatrice
download page (10.14 and newer, and the 10.12 & 10.13)

**Comment by tooomm** [comment]
We removed Sierra support over 6 month ago... #3837
The binary even tells you that it requires 10.13:
`Cockatrice-Dawn_of_Hope_Revision_1-2.7.4-macos10.13.dmg`

Looks like Zach wasn't aware in recent changes. I try to clean some stuff up today.

Can't you upgrade your OS? It should be free of charge and the 10.13 is even supported on older devices... 10.12 should also no longer be supported by Apple itself and you don't even get security fixes.

**Comment by Jasonic-gif** [comment]
There are no available updates as far as I can tell on my macOS. It is kind
of old (12 years I think). It had been working great for the past couple of
years, until the new cockatrice version came out a couple days ago.

**Comment by ctrlaltca** [comment]
Unfortunately the service we use to build the mac packages doesn't support anymore Sierra.
You can either:
 * try to download and install High Sierra from the App Store;
 * continue using the old Cockatrice version;
 * try to build a package for the new Cockatrice version yourself: https://github.com/Cockatrice/Cockatrice/wiki/Compiling-Cockatrice-(macOS)

**Comment by tooomm** [comment]
Let us know if you need further help - just ask here.
