### ISSUE TITLE
Issue Oracle Importer "does not contain any sets data"

### ISSUE THREAD

**Issue by Gcarva** [Cockatrice/Cockatrice#3928]
<b>System Information:</b>
  The file was retrieved successfully, but it does not contain any sets data.

 Ubuntu 18.04.4
Cockatrice 64 bit Version 2.7.4 (2020-03-20)
_______________________________________________________________________________________

Compiled Cockatrice successfully using instructions. Run Cockatrice, on start up it prompts Oracle loader. Continue with English. Default website ending in .xz does not exist so try both downloading AllPrintings.JSON from https://www.mtgjson.com/files/AllPrintings.json and downloading file and using it locally. In both cases I get error message: 

"The file was retrieved successfully, but it does not contain any sets data."

Possibly related: I am unable to open the JSON file, I get this error:
"The file you opened has some invalid characters. If you continue editing this file you could corrupt this document.
You can also choose another character encoding and try again."
I tried downloading the file again but no success.

**Comment by skwerlman** [comment]
This appears to be caused by the server sending down a bzip-compressed file instead of the uncompressed file oracle was expecting. This is a bug in MTGJSON, not in oracle. See mtgjson/mtgjson#537

**Comment by ZeldaZach** [comment]
Fixed upstream
