### ISSUE TITLE
Default sets priority for images downloading

### ISSUE THREAD

**Issue by Elitesparkle** [Cockatrice/Cockatrice#393]
Hi.

Since Cockatrice is getting the images from an external site and some of them are missing there, people keep asking about how to fix that problem.

I want to suggest to have a default sets priority that avoids this problem having promo sets on the bottom of the list. It should be easy to implement. You just need to set key values.
I could provide the order I'm currently using, if needed.

When a new set is released, it will be added on top of the list.
You could also let the user decide where to add it.
Some people like to have Zendikar on top to load the lands from there so, if you let the user decide to put the new sets in the position "x from the top" (the user will insert the x value), they could keep Zendikar on top and have the new set after it and before the others.

This way the problem about the images not loading will be solved.

Thanks for reading.

**Comment by ctrlaltca** [comment]
I think this is not relevant anymore.
Sets order management has been reworked and it should be easier to order sets by date now.
Then, even if you're using a "broken" set ordering with promo sets on top and the download fails, cockatrice will try to load the card image from the following sets.

**Comment by ctrlaltca** [comment]
Closing after #985 and #1039 changes.
