### ISSUE TITLE
Supporting Gif images 

### ISSUE THREAD

**Issue by Karpulza** [Cockatrice/Cockatrice#3930]
**Similar Requests**
https://www.reddit.com/r/Cockatrice/comments/3n0a12/gif_format_to_suport_for_foil_animation_on_cards/ 

Hi, I'm just creating a custom set in MSE and in doing so, came across some really cool animated cards in GIF format. I tried swapping a gif out for the same png in my deck in Cockatrice, and while the application still sees the image and uses it, there is no animation. Anyway, from the above reddit post, it looks like I'm not the only one to think of this and having an animated foil effect on cards would be awesome too. 

Love the App, keep up the great work! Thank you!

**Additional Context**

**Comment by ZeldaZach** [comment]
Hey mate, thanks for the suggestion! Unfortunately I don't think supporting GIF images enhances the play ability of the game and might lead to frustration from others. I appreciate your request, and hope to see more in the future!
