### ISSUE TITLE
XSD Validation v4 doesn't validate example

### ISSUE THREAD

**Issue by celphy** [Cockatrice/Cockatrice#3932]
[test.txt](https://github.com/Cockatrice/Cockatrice/files/4396987/test.txt)

<b>System Information:</b>
  
Client Version: 2.7.4 (2020-03-20)
Client Operating System: Fedora 31 (Workstation Edition)
Build Architecture: 64-bit
Qt Version: 5.13.2
System Locale: en_US
Install Mode: Standard
---------------------------------------------------------------------------
  
_______________________________________________________________________________________

  

I'm currently trying to validate an example set with the v4 XSD validator from https://github.com/Cockatrice/Cockatrice/blob/master/doc/carddatabase_v4/cards.xsd.

`<cockatrice_carddatabase version="4">
<sets>
<set>
<name>TEST</name>
<longname>Testset for validator</longname>
<settype>Custom</settype>
<releasedate>28-03-2020</releasedate>
</set>
</sets>
<cards>
<card>
<name>Card name</name>
<text>
Card description and oracle text, including actions, effects, etc..
</text>
<token>1</token>
<cipt>1</cipt>
<upsidedown>1</upsidedown>
<tablerow>3</tablerow>
<set rarity="common" uuid="12345678-abcd-1234-abcd-1234567890ab" num="42" muid="123456" picurl="http://.../image.jpg">XXX</set>
<related>Another card name</related>
<reverse-related>Another card name</reverse-related>
<prop>
<layout>normal</layout>
<side>front</side>
<type>Instant</type>
<maintype>Instant</maintype>
<manacost>R</manacost>
<cmc>1</cmc>
<colors>R</colors>
<coloridentity>R</coloridentity>
<pt>0/2</pt>
<loyalty>4</loyalty>
<format-standard>legal</format-standard>
<format-commander>legal</format-commander>
<format-modern>legal</format-modern>
<format-pauper>legal</format-pauper>
</prop>
</card>
</cards>
</cockatrice_carddatabase>`

The card information is copied from the [Documentation](https://github.com/Cockatrice/Cockatrice/wiki/Custom-Cards-&-Sets). Also the link [in the documentation](https://github.com/Cockatrice/Cockatrice/wiki/Custom-Cards-&-Sets#i-modified-my-cardsxml-and-it-isnt-working-properly) to the [updated copy](https://raw.githubusercontent.com/Cockatrice/Cockatrice/master/doc/cards.xsd) seems to be broken.

The output is:

_./test.xml:15: element token: Schemas validity error : Element 'token': This element is not expected. Expected is one of ( prop, set ).
./test.xml fails to validate_

After removing token, cipt, upsidedown, tablerow the output is:

_./test.xml:18: element prop: Schemas validity error : Element 'prop': This element is not expected. Expected is one of ( token, tablerow, cipt, upsidedown ).
./test.xml fails to validate_

I hope I haven't missed something obvious, thanks for taking the time.

€: I attached the file at the top as .txt. Github doesn't accept .xml files.

**Comment by ctrlaltca** [comment]
Your example xml is fine, and it will work correctly when used with Cockatrice.
The problem here is due to a limitation to the schema language (xsd) used to validate the xml.
Due to this limitation, for the file to validate correctly the elements must be in a specific order.
I've reworked the xml you posted by moving some elements around (prop and tablerow), and it now validates fine:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<cockatrice_carddatabase version="4">
	<sets>
		<set>	
			<name>TEST</name>
			<longname>Testset for validator</longname>
			<settype>Custom</settype>
			<releasedate>28-03-2020</releasedate>
		</set>
	</sets>
	<cards>
		<card>
  			<name>Card name</name>
			<text>Card description and oracle text, including actions, effects, etc..</text>
  			<prop>
    				<layout>normal</layout>
    				<side>front</side>
    				<type>Instant</type>
    				<maintype>Instant</maintype>
    				<manacost>R</manacost>
    				<cmc>1</cmc>
    				<colors>R</colors>
    				<coloridentity>R</coloridentity>
    				<pt>0/2</pt>
    				<loyalty>4</loyalty>
    				<format-standard>legal</format-standard>
    				<format-commander>legal</format-commander>
    				<format-modern>legal</format-modern>
    				<format-pauper>legal</format-pauper>
  			</prop>
  			<set rarity="common" uuid="12345678-abcd-1234-abcd-1234567890ab" num="42" muid="123456" picurl="http://.../image.jpg">XXX</set>
  			<related>Another card name</related>
  			<reverse-related>Another card name</reverse-related>
			<token>1</token>
  			<tablerow>3</tablerow>
			<cipt>1</cipt>
  			<upsidedown>1</upsidedown>
		</card>
	</cards>
</cockatrice_carddatabase>
```

**Comment by celphy** [comment]
Thanks for the help. Should I edit the wiki with the changes for the example and fix the dead link?

**Comment by ctrlaltca** [comment]
Contributions are welcome so yes, thank you!
