### ISSUE TITLE
Right-click on library, then click on play area, top card gets moved to play area

### ISSUE THREAD

**Issue by n21lv** [Cockatrice/Cockatrice#3935]
<b>System Information:</b>
  
Client Version: 2.7.4 (2020-03-20)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.12.6
  
_______________________________________________________________________________________

  
**Description:**
If you have at least one card anywhere on the play area except your hand, when you right-click the Library and then click anywhere on the play area, the top card of your library will be moved to that area. E.g. if you right-click the library and then click on the red area, the card will be moved to the battlefield. If, instead, you click the green area, the card will be placed into your hand. Even if you click on the light-grey area (the one with counters, library etc), the card back will flash briefly at the top-left corner of the screen.
___
**Debug log:**
Adding room: ID= 0 name= ""
Server::loginUser: LocalServerInterface(0x21f54c1c0b0) name= "Player 1"
session id: 0
gameEvent: invalid gameId
Server_AbstractUserInterface::playerAddedToGame(): gameId = 1
GameScene::addPlayer name= "Player 1"
PictureLoader: cache fail for "_trice_card_back_278320"
QWindowsWindow::setGeometry: Unable to set geometry 1920x1007+0+29 (frame: 1938x1054-9-9) on QWidgetWindow/"MainWindowClassWindow" on "\\.\DISPLAY1". Resulting geometry: 1920x1001+0+29 (frame: 1938x1048-9-9) margins: 9, 38, 9, 9 minimum size: 674x1007 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=692,1054 maxtrack=0,0)
PictureLoader: cache fail for "_trice_card_back_334430"
Loaded from "C:/Users/anki/AppData/Local/Cockatrice/Cockatrice/decks/[PIO] WUG Defenders.cod" - true
Deck was loaded - true
PictureLoader: [card:  "Plains"  set:  "THB" ]: Trying to load picture
PictureLoader: [card:  "Sorcerous Spyglass"  set:  "ELD" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Sorcerous Spyglass"  set:  "ELD" ]: Requested set property ( "muid" ) for Url template ( "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Plains"  set:  "THB" ]: Picture found on disk.
PictureLoader: [card:  "Prairie Stream"  set:  "C19" ]: Trying to load picture
PictureLoader: [card:  "Prairie Stream"  set:  "C19" ]: Picture found on disk.
PictureLoader: [card:  "Wall of Runes"  set:  "WAR" ]: Trying to load picture
PictureLoader: [card:  "Wall of Runes"  set:  "WAR" ]: Picture found on disk.
PictureLoader: [card:  "Mystical Dispute"  set:  "ELD" ]: Trying to load picture
PictureLoader: [card:  "Mystical Dispute"  set:  "ELD" ]: Picture found on disk.
PictureLoader: [card:  "Canopy Vista"  set:  "BFZ" ]: Trying to load picture
PictureLoader: [card:  "Canopy Vista"  set:  "BFZ" ]: Picture found on disk.
PictureLoader: [card:  "Orator of Ojutai"  set:  "C17" ]: Trying to load picture
PictureLoader: [card:  "Orator of Ojutai"  set:  "C17" ]: Picture found on disk.
PictureLoader: [card:  "Hinterland Harbor"  set:  "DOM" ]: Trying to load picture
PictureLoader: [card:  "Hinterland Harbor"  set:  "DOM" ]: Picture found on disk.
PictureLoader: [card:  "Island"  set:  "THB" ]: Trying to load picture
PictureLoader: [card:  "Island"  set:  "THB" ]: Picture found on disk.
PictureLoader: [card:  "Banefire"  set:  "M19" ]: Trying to load picture
PictureLoader: [card:  "Banefire"  set:  "M19" ]: Picture found on disk.
PictureLoader: [card:  "Irrigated Farmland"  set:  "AKH" ]: Trying to load picture
PictureLoader: [card:  "Irrigated Farmland"  set:  "AKH" ]: Picture found on disk.
PictureLoader: [card:  "Fae of Wishes // Granted"  set:  "ELD" ]: Trying to load picture
PictureLoader: [card:  "Fae of WishesGranted"  set:  "ELD" ]: Picture found on disk.
PictureLoader: [card:  "Forest"  set:  "THB" ]: Trying to load picture
PictureLoader: [card:  "Forest"  set:  "THB" ]: Picture found on disk.
PictureLoader: [card:  "Arcades, the Strategist"  set:  "M19" ]: Trying to load picture
PictureLoader: [card:  "Arcades, the Strategist"  set:  "M19" ]: Picture found on disk.
PictureLoader: [card:  "High Alert"  set:  "RNA" ]: Trying to load picture
PictureLoader: [card:  "High Alert"  set:  "RNA" ]: Picture found on disk.
PictureLoader: [card:  "Axebane Guardian"  set:  "RTR" ]: Trying to load picture
PictureLoader: [card:  "Axebane Guardian"  set:  "RTR" ]: Picture found on disk.
PictureLoader: [card:  "Sorcerous Spyglass"  set:  "ELD" ]: Trying to load picture
PictureLoader: [card:  "Sorcerous Spyglass"  set:  "ELD" ]: Picture found on disk.
PictureLoader: [card:  "Tetsuko Umezawa, Fugitive"  set:  "DOM" ]: Trying to load picture
PictureLoader: [card:  "Tetsuko Umezawa, Fugitive"  set:  "DOM" ]: Picture found on disk.
PictureLoader: [card:  "Tower Defense"  set:  "RNA" ]: Trying to load picture
PictureLoader: [card:  "Tower Defense"  set:  "RNA" ]: Picture found on disk.
PictureLoader: [card:  "Tormod's Crypt"  set:  "C14" ]: Trying to load picture
PictureLoader: [card:  "Tormod's Crypt"  set:  "C14" ]: Picture found on disk.
PictureLoader: [card:  "Anticipate"  set:  "M20" ]: Trying to load picture
PictureLoader: [card:  "Anticipate"  set:  "M20" ]: Picture found on disk.
PictureLoader: [card:  "Wall of Frost"  set:  "M15" ]: Trying to load picture
PictureLoader: [card:  "Wall of Frost"  set:  "M15" ]: Picture found on disk.
PictureLoader: [card:  "Settle the Wreckage"  set:  "XLN" ]: Trying to load picture
PictureLoader: [card:  "Settle the Wreckage"  set:  "XLN" ]: Picture found on disk.
PictureLoader: [card:  "Geist of the Archives"  set:  "EMN" ]: Trying to load picture
PictureLoader: [card:  "Geist of the Archives"  set:  "EMN" ]: Picture found on disk.
PictureLoader: [card:  "Caustic Caterpillar"  set:  "ORI" ]: Trying to load picture
PictureLoader: [card:  "Caustic Caterpillar"  set:  "ORI" ]: Picture found on disk.
PictureLoader: [card:  "Teyo, the Shieldmage"  set:  "WAR" ]: Trying to load picture
PictureLoader: [card:  "Teyo, the Shieldmage"  set:  "WAR" ]: Picture found on disk.
PictureLoader: [card:  "Glacial Fortress"  set:  "XLN" ]: Trying to load picture
PictureLoader: [card:  "Glacial Fortress"  set:  "XLN" ]: Picture found on disk.
PictureLoader: [card:  "Plains"  set:  "THB" ]: Trying to load picture
PictureLoader: [card:  "Plains"  set:  "THB" ]: Picture found on disk.
PictureLoader: [card:  "Prairie Stream"  set:  "C19" ]: Trying to load picture
PictureLoader: [card:  "Prairie Stream"  set:  "C19" ]: Picture found on disk.
PictureLoader: [card:  "Wall of Runes"  set:  "WAR" ]: Trying to load picture
PictureLoader: [card:  "Wall of Runes"  set:  "WAR" ]: Picture found on disk.
addCounter: "Player 1" 0 "life"
addCounter: "Player 1" 1 "w"
addCounter: "Player 1" 2 "u"
addCounter: "Player 1" 3 "b"
addCounter: "Player 1" 4 "r"
addCounter: "Player 1" 5 "g"
addCounter: "Player 1" 6 "x"
addCounter: "Player 1" 7 "storm"
CardDragItem: coordinate overflow: x = 9.53291 , y = -59.6102
CardDragItem: coordinate overflow: x = 404.357 , y = 102.608

**Comment by ebbit1q** [comment]
I can not reproduce this issue.

**Comment by tooomm** [comment]
I can reproduce it, also Client Version: 2.7.4 (2020-03-20) on Windows 10 (64bit).

Also, if you keep right clicking to the board or the stack after the first right click on the library, the right click menu from the library is still shown there instead the one from the section you are actually clicking.

**Comment by n21lv** [comment]
> I can not reproduce this issue.

@ebbit1q do you have at least one card anywhere on the play area except your hand? It doesn't happen to me when I have no cards on the battlefield/stack.

**Comment by ebbit1q** [comment]
I'm flagging this as a windows specific issue then.

**Comment by skwerlman** [comment]
i cant repro the card moving, but i was able to occasionally repro the second issue @tooomm mentioned regarding the right click menu, tho thats probably worth a separate issue.
Client Version: 2.7.3-custom(27b7ebe) (2020-03-30) on Arch Linux

**Comment by mingomongo** [comment]
I can consistently replicate on windows, I have a macbook too and the issue isn't present. Won't work at the start of the game, but moving a card off the deck slightly and putting it back will make the right click glitch happen consistently and exactly as described by n21lv.

```
Client Version: 2.7.4 (2020-03-20)
Client Operating System: Windows 7 SP 1 (6.1)
Build Architecture: 64-bit
Qt Version: 5.12.6
System Locale: en_GB
```

**Comment by JoeRLDuncan** [comment]
I have a player on a mac who complains about this repeatedly, I'll ask for his deets.

**Comment by JoeRLDuncan** [comment]
Nope, not mac, Windows 10.

**Comment by MotherofRuins** [comment]
Confirming this on Windows 7 SP1

**Comment by leestran1995-daugherty** [comment]
Confirming on Windows 10, and also confirming that the problem doesn't seem to exist on Ubuntu.

**Comment by leestran1995-daugherty** [comment]
Additional detail: If you right click your library, and then right click any other zone (any number of times) and **then** left click, the issue still happens.

**Comment by NMS127** [comment]
This happens consistently for me. Also, right-clicking the library, then left-clicking and holding outside the menu begins dragging the top card (face down).

System Information:
Client Version: 2.7.4 (2020-03-20)
Client Operating System: Windows 8.1 (6.3)
Build Architecture: 64-bit
Qt Version: 5.12.6
System Locale: en_US
Install Mode: Standard

**Comment by ZeldaZach** [comment]
Sounds like a windows specific thing still, based on what people have been commenting. This is probably QT based, but diagnosing it is proving difficult. Maybe @ctrlaltca can lend a hand?

**Comment by rafuwu** [comment]
I can confirm this is still present in **Cockatrice version 2.8.0 (2021-01-26)** (stable release) and **Windows 10** 64-bit.

Bellow is a screen recording of the issue happening in Animated PNG format.

![2022-03-12_23-20-11_cockatrice_1](https://user-images.githubusercontent.com/73766909/158076944-e7ac5602-aa39-4660-baf1-cdb8435e7085.png)

You can use the URL bellow to download the original video. It doesn't play in the browser because it uses RGB color space.
`https://user-images.githubusercontent.com/73766909/158077011-48874a30-d011-4c70-8aec-da3a94f9b320.mp4`

**Comment by ebbit1q** [comment]
the video works just fine

**Comment by ZeldaZach** [comment]
Can't reproduce on Win11

**Comment by ebbit1q** [comment]
someone told me this is still and issue, could it be exclusive to win10?

**Comment by NMS127** [comment]
This bug is still present for me on Windows 10 (22H2), with Cockatrice 2.10.2. It was also present on Windows 8.1.

Currently it doesn't seem to happen if I click very briefly outside the menu, but if I hold for even a moment, it begins dragging the top card of my deck and moves it to wherever I release the button.

**Comment by ebbit1q** [comment]
more investigation is needed into this issue, it's very annoying and can greatly disrupt games for uninitiated players
