### ISSUE TITLE
Seeking During Replays

### ISSUE THREAD

**Issue by D0nV170** [Cockatrice/Cockatrice#3940]
<b>System Information:</b>
  

  
_______________________________________________________________________________________

  
When trying to view a game replay, I am unable to seek it any further than about 25% and then it either goes directly to the very end or goes back to the beginning.

**Comment by ctrlaltca** [comment]
Please insert the version information as request in the issue template.
Also, if you are experiencing this on some specific replays, please attach an example to this ticket.
Fell free to reopen this bug once you dd the missing info.
