### ISSUE TITLE
Not a computer person sorry need help

### ISSUE THREAD

**Issue by andrew475** [Cockatrice/Cockatrice#3942]
<b>System Information:</b>
MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports) 
2.3 GHz Dual-Core Intel Core i5
8 GB 2133 MHz LPDDR3
Macintosh HD
Intel Iris Plus Graphics 640 1536 MB
C02V4856HV29
Go to "Help → View Debug Log" and copy all lines above the separation here! -->
Client Version: 2.7.4 (2020-03-20)
Client Operating System: macOS 10.15
Build Architecture: 64-bit
Qt Version: 5.14.1
System Locale: en_US
Install Mode: Standard
---------------------------------------------------------------------------
Theme name not set, setting default value
Theme changed: "Default"
Sounds theme name not set, setting default value
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
Language changed: ""
main(): starting main program
main(): MainWindow constructor finished
Spoilers Disabled
main(): ui.show() finished
Startup: old client version empty, assuming first start after clean install
PictureLoader: cache fail for "_trice_card_back_220431"
PictureLoader: cache fail for "_trice_card_back_317430"
PictureLoader: cache fail for "_trice_card_back_317430"
PictureLoader: cache fail for "_trice_card_back_317430"
PictureLoader: cache fail for "_trice_card_back_317430" 
newest macOS and the newest Mac download for cocktrice
_______________________________________________________________________________________

  
i keep getting this message it won't download the cards /private/var/folders/gt/0qr4nq4j44z8ers_ss9tjn_480000gn/T/apptranslocation/CE64D36A-5B56-42B7-8618-F371FD163F30/d/oracle

**Comment by ctrlaltca** [comment]
This is due to a security measure in macOS preventing downloaded applications to run other applications (in this case, Cockatrice is trying to run the card updated called Oracle).
A quick workaorund is to mark the "Cockatrice" application as safe opening a terminal and writing this command:
```sh
sudo xattr -r -d com.apple.quarantine /Applications/cockatrice.app/
```
We are working on a ore transparent solution.
