### ISSUE TITLE
verify my sccount

### ISSUE THREAD

**Issue by ajschremp** [Cockatrice/Cockatrice#3943]
<b>System Information:</b>
  

  
_______________________________________________________________________________________

the email to verify my account still hasnt sent

**Comment by tooomm** [comment]
You are talking to the developers of the application - we don't run a server.
This is the issue tracker for the software itself, we can't give you support for a specific server or help with bans etc.
Please contact the admin staff of whatever server you're using.

Check the [Public Server List](https://github.com/Cockatrice/Cockatrice/wiki/Public-Servers) with all available servers that we know of.
There you find links to webpages and contact details of the respective owners!

<br>

To give you a few general solutions to **common problems**:
- **Registering**
    - If you're missing your *Activation Token*, you should check your mails `SPAM` folder as well!
- **Connecting**
    - If you are seeing a `Socket Error`, check [this](https://github.com/Cockatrice/Cockatrice/wiki/Troubleshooting#socket-error-xxx-error-messages-explained)
    - If you are seeing a `Unknown Error: -1`, read [here](https://github.com/Cockatrice/Cockatrice/wiki/Troubleshooting#unknown-error--1-message-upon-login)
    - Make sure your network doesn't block connections on the port your server uses, work or university networks might be problematic
