### ISSUE TITLE
page up/page down in "Deck" tab/window / search results for faster browsing

### ISSUE THREAD

**Issue by ZombiePlayground** [Cockatrice/Cockatrice#3945]
**Similar Requests**

**Description of New Feature**

**Additional Context**

**Comment by ebbit1q** [comment]
Please describe your request in further detail.

**Comment by ZombiePlayground** [comment]
![2020-04-08 22_27_24-Window](https://user-images.githubusercontent.com/63249815/78851732-8c36da00-79e8-11ea-8c47-413662d4b58a.png) 

Deck Editor > New Deck > "Search by card name" --if left blank, and you want to just browse, there is no PgUp/PgDn functionality for scrolling up/down through cards. Enable PgUp/PgDn to scroll one whole "page" of search results (the cards).

**Comment by ZeldaZach** [comment]
I like the idea. Should be easy enough

**Comment by tooomm** [comment]
Linking https://github.com/Cockatrice/Cockatrice/issues/2801 as it would be nice to have `Pos1` and `End` as well to navigate in the list of cards in deck editor.
