### ISSUE TITLE
Multiple settings windows able to be open on Mac

### ISSUE THREAD

**Issue by mingomongo** [Cockatrice/Cockatrice#3949]
```
Client Version: 2.7.2 (2019-08-31)
Client Operating System: macOS Sierra (10.12)
Build Architecture: 64-bit
Qt Version: 5.13.0
System Locale: en_GB
Install Mode: Standard
```

```
MacBook Air (13-inch, Late 2010)
1.86 GHz Intel Core 2 Duo
4 GB 1067 MHz DDR3
NVIDIA GeForce 320M 256 MB
```
_______________________________________________________________________________________

I haven't explored this in detail, but multiple settings windows can be opened on my macbook by going to the Preferences menu option, or using the shortcut. Opening 'Settings' blocks all menu options except for the ones under "Cockatrice", though Preferences might be the only one that might cause issues. Settings can be different between windows, the most recent changes takes effect when all Settings windows are closed I believe.

Might not cause issues but is confusing and doesn't seem on purpose. Opening multiple 'Settings' windows is not possible on my copy of Windows (same Cockatrice version, Win7 64bit)

![Screen Shot 2020-04-08 at 22 54 29](https://user-images.githubusercontent.com/33768220/78837558-3e23d580-79ec-11ea-90d6-c220efbde2d8.png)

**Comment by tooomm** [comment]
>Opening multiple 'Settings' windows is not possible on my copy of Windows (same Cockatrice version, Win7 64bit)

I can agree here. Though I assume that's because the settings window forces focus on windows and is always in the foreground of the Cockatrice app, therefore it's just not possible to open the menu again and initiate a second copy of settings. :)

**Comment by ZeldaZach** [comment]
This really doesn't feel like a problem, as there's no racetime conditions you can hit within settings afaik. This is an OS implementation compared to a Cockatrice issue.
