### ISSUE TITLE
The card Pack Hunt is missing from the deck editor.

### ISSUE THREAD

**Issue by atomlab7** [Cockatrice/Cockatrice#3952]
<b>System Information:</b>
  

  
_______________________________________________________________________________________

  
The card Pack Hunt is missing from the deck editor.

**Comment by skwerlman** [comment]
It is not missing for me. Do you have NEM enabled in the set manager?

**Comment by tooomm** [comment]
It also shows for me.

If you still have an issue reopen the issue and come back with more details, please.
