### ISSUE TITLE
Crashes on Creating Tokens

### ISSUE THREAD

**Issue by yesennes** [Cockatrice/Cockatrice#3953]
<b>System Information:</b>
  
System Locale: en_US
Install Mode: Standard
---------------------------------------------------------------------------
Theme changed: "Default"
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
Language changed: "en"
main(): starting main program
main(): MainWindow constructor finished
Spoilers Disabled
main(): ui.show() finished
Startup: found config with current version
CardDatabase::loadCardDatabases start
[CockatriceXml4Parser] Trying to parse:  "/home/yesennes/.local/share/Cockatrice/Cockatrice/cards.xml"
PictureLoader: cache fail for "_trice_card_back_282456"
[CardDatabase] loadCardDatabase(): Path = "/home/yesennes/.local/share/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 20810 Sets= 478
[CockatriceXml4Parser] Trying to parse:  "/home/yesennes/.local/share/Cockatrice/Cockatrice/tokens.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
[CardDatabase] loadCardDatabase(): Path = "/home/yesennes/.local/share/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 21263 Sets= 478
[CardDatabase] loadCardDatabase(): Path = "/home/yesennes/.local/share/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 21263 Sets= 478
CardDatabase::loadCardDatabases success
  
_______________________________________________________________________________________
For reference I'm running on Ubuntu 18.04.4 LTS
  
Sometimes when I create a token the game hangs or crashes. It's repeatable, but a handful of relatively unrelated things will avoid the issue, so I am going to be detailed in the steps to repeat:

1. Start Cockatrice
2. Start a local game with one player
3. Load an empty deck
4. Rightclick -> Create token
5. Sort the tokens by name
6. Double click the first angel
7. The game will always crash

I have noticed some decks will cause it to work. I don't understand why the ones do work. Not sorting by name will also cause it to work. The other players deck may cause it to work.

It doesn't seem to matter if it's a local game or server, you double click the token or select okay, or have other players in the game. The token selected also doesn't seem to matter. It doesn't seem to matter if its a fresh start of Cockatrice, or you have been done other things first.

Github won't seem to let me upload the crash log, it's too big. Let me know with any directions to upload it.

**Comment by ebbit1q** [comment]
I cannot replicate this issue, you also haven't included your client version in your log, are you running the most recent version?

**Comment by Psithief** [comment]
@yesennes If you open the tokens.xml file and delete the `<info>` element, does it still crash?

**Comment by MotherofRuins** [comment]
Can't reproduce on Windows 7 SP1 Cockatrice 2.7.4

**Comment by tooomm** [comment]
@yesennes 
How do you "Load an empty deck"? What do you mean?

I tried it with a normal deck and it did not crash on Windows 10 with Cockatrice 2.7.5-beta (2020-04-08)

Try updating to the newest client version, run the Oracle card updater (get newest token file there too!) and reopen this issue with complete information if the problem persists, please.
Also report back on the suggestions made and questions asked if you need further help.
