### ISSUE TITLE
Issue: I can't kick people from rooms I create

### ISSUE THREAD

**Issue by doggymien4o** [Cockatrice/Cockatrice#3958]
Hello,

I have had an issue on Cockatrice ever since I registered more than 2 years ago. For some reason, I cannot kick people from my rooms regardless of what I try.
I am using Cockatrice on Windows 10, always up to date.

**Comment by tooomm** [comment]
Can you please provide exact version information as asked?
Where have you downloaded Cockatrice?
Which server are you connecting to?

Please describe what you try when you want to kick somebody from a game you created for yourself (you are the host).

**Comment by doggymien4o** [comment]
I have downloaded cockatrice from here https://cockatrice.github.io/
And I am playing on Rooster Ranges.
When I right click on a person and select "Kick" nothing happens.

**Comment by ebbit1q** [comment]
When you created your ticket it asked you for your system information as provided in cockatrice's log, please, provide said information.

**Comment by doggymien4o** [comment]
> When you created your ticket it asked you for your system information as provided in cockatrice's log, please, provide said information.

Where do I get the log from?

**Comment by tooomm** [comment]
This is displayed when you open your issue:
`Go to "Help → View Debug Log" and copy all lines above the separation here!` :)

**Comment by doggymien4o** [comment]
> This is displayed when you open your issue:
> `Go to "Help → View Debug Log" and copy all lines above the separation here!` :)

Here's what my Log has:

Client Version: 2.7.0 (2019-03-04)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.9.7
System Locale: en_US
Install Mode: Standard
---------------------------------------------------------------------------
Theme changed: "Fabric"
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
Language changed: "en"
main(): starting main program
Spoilers Disabled
CardDatabase::loadCardDatabases start
[CockatriceXml3Parser] Trying to parse:  "C:/Users/yasop/AppData/Local/Cockatrice/Cockatrice/cards.xml"
[CockatriceXml3Parser] Parsing failed: wrong version 4
[CockatriceXml4Parser] Trying to parse:  "C:/Users/yasop/AppData/Local/Cockatrice/Cockatrice/cards.xml"
main(): MainWindow constructor finished
main(): ui.show() finished
Attempting auto-connect...
QWindowsWindow::setGeometry: Unable to set geometry 1920x1018+0+23 on QWidgetWindow/'MainWindowClassWindow'. Resulting geometry:  1920x1017+0+23 (frame: 8, 31, 8, 8, custom margin: 0, 0, 0, 0, minimum size: 861x1018, maximum size: 16777215x16777215).
PictureLoader: cache fail for "_trice_card_back_226186"
PictureLoader: cache fail for "_trice_card_back_226185"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/yasop/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 20983 Sets= 478
[CockatriceXml3Parser] Trying to parse:  "C:/Users/yasop/AppData/Local/Cockatrice/Cockatrice/tokens.xml"
[CockatriceXml3Parser] Parsing failed: wrong version 4
[CockatriceXml4Parser] Trying to parse:  "C:/Users/yasop/AppData/Local/Cockatrice/Cockatrice/tokens.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
[CardDatabase] loadCardDatabase(): Path = "C:/Users/yasop/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 21446 Sets= 478
[CardDatabase] loadCardDatabase(): Path = "C:/Users/yasop/AppData/Local/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 21446 Sets= 478
[CockatriceXml3Parser] Trying to parse:  "C:/Users/yasop/AppData/Local/Cockatrice/Cockatrice/customsets/01.POK.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/yasop/AppData/Local/Cockatrice/Cockatrice/customsets/01.POK.xml" Status = 0 Cards = 21466 Sets= 479
[CockatriceXml3Parser] Trying to parse:  "C:/Users/yasop/AppData/Local/Cockatrice/Cockatrice/customsets/02.ExpandedKingdomsClassic3.1_Release.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/yasop/AppData/Local/Cockatrice/Cockatrice/customsets/02.ExpandedKingdomsClassic3.1_Release.xml" Status = 0 Cards = 21505 Sets= 480
[CockatriceXml3Parser] Trying to parse:  "C:/Users/yasop/AppData/Local/Cockatrice/Cockatrice/customsets/POK.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/yasop/AppData/Local/Cockatrice/Cockatrice/customsets/POK.xml" Status = 0 Cards = 21505 Sets= 480
[CockatriceXml3Parser] Trying to parse:  "C:/Users/yasop/AppData/Local/Cockatrice/Cockatrice/customsets/STW.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/yasop/AppData/Local/Cockatrice/Cockatrice/customsets/STW.xml" Status = 0 Cards = 21520 Sets= 481
[CockatriceXml3Parser] Trying to parse:  "C:/Users/yasop/AppData/Local/Cockatrice/Cockatrice/customsets/TK.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/yasop/AppData/Local/Cockatrice/Cockatrice/customsets/TK.xml" Status = 0 Cards = 21520 Sets= 481
CardDatabase::loadCardDatabases success
link path1214 hasn't been detected!
link path1563 hasn't been detected!
link path1563 hasn't been detected!

**Comment by tooomm** [comment]
@doggymien4o we had over 100 changes since version 2.7.0
Can you try to update your client and tell us if the problem persists?

Go to `Help --> Check for Client Updates`, and don't forget to update your card database after doing so!
You find that in `Cockatrice --> Check for card updates...`

**Comment by doggymien4o** [comment]
I updated and still cant kick people

Client Version: 2.7.4 (2020-03-20)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.12.6
System Locale: en_US
Install Mode: Standard
---------------------------------------------------------------------------
Theme changed: "Fabric"
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
Language changed: "en"
main(): starting main program
main(): MainWindow constructor finished
Spoilers Disabled
main(): ui.show() finished
Startup: old client version "2.7.0 (2019-03-04)" differs, assuming first start after update
Attempting auto-connect...
PictureLoader: cache fail for "_trice_card_back_226292"
CardDatabase::loadCardDatabases start
[CockatriceXml4Parser] Trying to parse:  "C:/Users/yasop/AppData/Local/Cockatrice/Cockatrice/cards.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/yasop/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 20927 Sets= 478
[CockatriceXml4Parser] Trying to parse:  "C:/Users/yasop/AppData/Local/Cockatrice/Cockatrice/tokens.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
[CardDatabase] loadCardDatabase(): Path = "C:/Users/yasop/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 21390 Sets= 478
[CardDatabase] loadCardDatabase(): Path = "C:/Users/yasop/AppData/Local/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 21390 Sets= 478
[CockatriceXml4Parser] Trying to parse:  "C:/Users/yasop/AppData/Local/Cockatrice/Cockatrice/customsets/01.POK.xml"
[CockatriceXml4Parser] Parsing failed: wrong version 3
[CockatriceXml3Parser] Trying to parse:  "C:/Users/yasop/AppData/Local/Cockatrice/Cockatrice/customsets/01.POK.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/yasop/AppData/Local/Cockatrice/Cockatrice/customsets/01.POK.xml" Status = 0 Cards = 21410 Sets= 479
[CockatriceXml4Parser] Trying to parse:  "C:/Users/yasop/AppData/Local/Cockatrice/Cockatrice/customsets/02.ExpandedKingdomsClassic3.1_Release.xml"
[CockatriceXml4Parser] Parsing failed: wrong version 3
[CockatriceXml3Parser] Trying to parse:  "C:/Users/yasop/AppData/Local/Cockatrice/Cockatrice/customsets/02.ExpandedKingdomsClassic3.1_Release.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/yasop/AppData/Local/Cockatrice/Cockatrice/customsets/02.ExpandedKingdomsClassic3.1_Release.xml" Status = 0 Cards = 21449 Sets= 480
[CockatriceXml4Parser] Trying to parse:  "C:/Users/yasop/AppData/Local/Cockatrice/Cockatrice/customsets/POK.xml"
[CockatriceXml4Parser] Parsing failed: wrong version 3
[CockatriceXml3Parser] Trying to parse:  "C:/Users/yasop/AppData/Local/Cockatrice/Cockatrice/customsets/POK.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/yasop/AppData/Local/Cockatrice/Cockatrice/customsets/POK.xml" Status = 0 Cards = 21449 Sets= 480
[CockatriceXml4Parser] Trying to parse:  "C:/Users/yasop/AppData/Local/Cockatrice/Cockatrice/customsets/STW.xml"
[CockatriceXml4Parser] Parsing failed: wrong version 3
[CockatriceXml3Parser] Trying to parse:  "C:/Users/yasop/AppData/Local/Cockatrice/Cockatrice/customsets/STW.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/yasop/AppData/Local/Cockatrice/Cockatrice/customsets/STW.xml" Status = 0 Cards = 21464 Sets= 481
[CockatriceXml4Parser] Trying to parse:  "C:/Users/yasop/AppData/Local/Cockatrice/Cockatrice/customsets/TK.xml"
[CockatriceXml4Parser] Parsing failed: wrong version 3
[CockatriceXml3Parser] Trying to parse:  "C:/Users/yasop/AppData/Local/Cockatrice/Cockatrice/customsets/TK.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/yasop/AppData/Local/Cockatrice/Cockatrice/customsets/TK.xml" Status = 0 Cards = 21464 Sets= 481
CardDatabase::loadCardDatabases success
gameEvent: invalid gameId
PictureLoader: cache fail for "_trice_card_back_274308"
QWindowsWindow::setGeometry: Unable to set geometry 1920x1022+0+23 (frame: 1936x1061-8-8) on QWidgetWindow/"MainWindowClassWindow" on "\\.\DISPLAY1". Resulting geometry: 1920x1017+0+23 (frame: 1936x1056-8-8) margins: 8, 31, 8, 8 minimum size: 645x1022 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=661,1061 maxtrack=0,0)
PictureLoader: cache fail for "_trice_card_back_290398"
GameScene::addPlayer name= "doggymien4o"
PictureLoader: cache fail for "_trice_card_back_290396"
PictureLoader: cache fail for "_trice_card_back_290259"
PictureLoader: cache fail for "_trice_card_back_290394"
PictureLoader: cache fail for "_trice_card_back_290395"
PictureLoader: cache fail for "_trice_card_back_290397"
PictureLoader: cache fail for "_trice_card_back_290399"
PictureLoader: cache fail for "_trice_card_back_290400"
PictureLoader: cache fail for "_trice_card_back_290401"
PictureLoader: cache fail for "_trice_card_back_290402"
PictureLoader: cache fail for "_trice_card_back_290403"
PictureLoader: cache fail for "_trice_card_back_290404"
PictureLoader: cache fail for "_trice_card_back_290405"
PictureLoader: cache fail for "_trice_card_back_290406"
PictureLoader: cache fail for "_trice_card_back_290407"
PictureLoader: cache fail for "_trice_card_back_290408"
PictureLoader: cache fail for "_trice_card_back_290409"
PictureLoader: cache fail for "_trice_card_back_290410"
PictureLoader: cache fail for "_trice_card_back_290411"
PictureLoader: cache fail for "_trice_card_back_290412"
PictureLoader: cache fail for "_trice_card_back_290413"
PictureLoader: cache fail for "_trice_card_back_290414"
GameScene::addPlayer name= "TessoGonff"
GameScene::addPlayer name= "Made_my_day"

**Comment by ZeldaZach** [comment]
Unfortunately nobody on the team can reproduce this issue. If you continue to experience it, please reach out to us directly on Discord and we'll walk through it for better understanding of the process.
