### ISSUE TITLE
"Put to graveyard, bottom, exile" buttons in crtl-W window

### ISSUE THREAD

**Issue by anoda9** [Cockatrice/Cockatrice#396]
These features might be useful:
- A "put cards to graveyard" button in the crtl-W window. Milling a certain number of cards is a fairly common action, especially in this standard with Sidisi and Nyx Weaver. 
- A "Put cards to bottom" button in the crtl-W window. This would make it easier to use scrylands and Dig Through Time. 
- A "put cards to exile" button in the graveyard window, to make delving easier. 

In all of these, the action would affect only the the cards the player selected (by dragging/highlighting), except if the number of cards selected was 0, in which case it would effect all the cards in the window. 

The buttons could be titled "Mill", "Bottom", and "Exile" for brevity.

**Comment by ZeldaZach** [comment]
I believe this was added

**Comment by Daenyth** [comment]
I don't think so

**Comment by ZeldaZach** [comment]
Isn't `CTRL + W` == Scry?

**Comment by ZeldaZach** [comment]
This was added.
<img width="418" alt="screenshot 2015-07-08 00 27 52" src="https://cloud.githubusercontent.com/assets/7460172/8563055/31948032-2508-11e5-8477-3b5aef4004a4.png">
