### ISSUE TITLE
Alternate art selection at the card-by-card level via an override list

### ISSUE THREAD

**Issue by aeschenkarnos** [Cockatrice/Cockatrice#3960]
**Similar Requests**
#3485 

**Description of New Feature**
Change the art selection mechanism to allow for the player to register individual cards as overriding the general order of the Card Database. My preference would be an item in the right-click menu to allow for selection of which printing/set the card art is to be taken from, with the default top set (as per the Card Database order) highlighted.

Note that some cards in particular basic lands appear in a LOT of sets so the dialogue will need to account for that, perhaps present the set abbreviations in a small grid of maximum 10 rows?

This would allow for simple fixing of partially-loaded images, barely-readable black planeswalkers, Godzilla promos, textless cards, occasional wrong-language priority art, and various other issues.

It need not be implemented for spoiler cards, if that would cause issues.

**Comment by tooomm** [comment]
Looks like my message went not trough on mobile when closing this. Sorry for that 🙈 
Remembered this one when searching for other card art issues right now. :)

I guess this is related and connected to https://github.com/Cockatrice/Cockatrice/issues/486, which also asks for managing/usage of the various arts available for a certain card.

I like your right click proposal and detailed description here!

Thanks for bringing this up, your proposal should now be visible and linked to the other issue. 👍
