### ISSUE TITLE
Want to create a TCG card game called Battle Spirits

### ISSUE THREAD

**Issue by ryze12138** [Cockatrice/Cockatrice#3962]
Hello everyone, my original intention was to create a Japanese TCG game called Battle Spirits in Cockatrice. I think this game is good and interesting enough. I want everyone to have the opportunity to recognize and enjoy this excellent game. I actually operated the Cockatrice platform, I think it is enough to play Battle Spirits. I just need to create a custom database for Battle Spirits. But I don't know how to do it. Can you tell me where to look for the production tutorial or help me? Thank you very much and look forward to your guidance!

**Comment by ZeldaZach** [comment]
Hey @ryze12138 You can find more information about creating custom sets on our wiki at https://github.com/Cockatrice/Cockatrice/wiki/Custom-Cards-&-Sets. Let us know if you have other questions over on Discord or Gitter!
