### ISSUE TITLE
How do I set the card back image and the image with card effects on both sides?

### ISSUE THREAD

**Issue by ryze12138** [Cockatrice/Cockatrice#3963]
I checked the user guide, I only saw how to change the front image, but now I want to achieve two effects:
1. I want to set the picture on the back of the card at will, not limited to Magic
2. I want to create a card with pictures and effects on both sides, and I can give a detailed explanation in the description column for the effect of each side
How can I accomplish the above two points?
thank you all

**Comment by ebbit1q** [comment]
Currently the effect of double sided cards is produced through the "related card" you simply make a separate card for both sides and have them be linked in the card database.

**Comment by ryze12138** [comment]
Okay, thank you for your answers. How can I replace the card back? Also, will I add a function to move the counter directly from one card to another in the future? Instead of subtracting the counter on one card and adding the same counter on the other card. I think this operation is too cumbersome.

**Comment by ebbit1q** [comment]
The card back is part of the application's theme, see here: https://github.com/Cockatrice/Cockatrice/wiki/Themes

Please open separate tickets for different feature requests.

**Comment by tooomm** [comment]
If you have further questions please reopen this (if it's related), or open a new issue.
