### ISSUE TITLE
[Ikoria] Wrong picture for many cards

### ISSUE THREAD

**Issue by danyfire** [Cockatrice/Cockatrice#3964]
Hello,

Many pictures downloaded with oracle for the “Ikoria” extension are not the default one.
There is even one in Japanese: Mysterious Egg
Many other cards are getting alternate art instead of the original one’s example: auspicious Starrix; Brokkos, Apex of Forever; cloudpiercer; glowstone recluse; ....
I have not check them all. Can you help us fixing this automatically instead of manually through the custom images?

Sincerely,

Danyfire

**Comment by ebbit1q** [comment]
Mtgjson now puts these cards in the same set but with a new field called flavorName, also the isPromo field is set.

**Comment by danyfire** [comment]
> Mtgjson now puts these cards in the same set next to the normal version but with a new field called flavorName, also the isPromo field is set.

So how can we fix this ? When I asked in the Mtgjson discord their programmers explained me that the problem wasn't on there side that Cockatrice had to fix this on this side.

**Comment by tooomm** [comment]
@danyfire There is a proposed fix already #3965

**Comment by ebbit1q** [comment]
I already opened a code change ticket that would fix this issue.
