### ISSUE TITLE
Double click instants/sorceries from stack to graveyard

### ISSUE THREAD

**Issue by mosew** [Cockatrice/Cockatrice#3972]
**Similar Requests**

**Description of New Feature**
After double clicking an instant or sorcery, it goes to the stack. Double clicking it again, it goes to play. It should probably go to the graveyard?

**Additional Context**

**Comment by skwerlman** [comment]
Normally, instants and sorceries do go to the graveyard from the stack, so this sounds like a bug.
Which cards are affected by this for you?
Please also post the top few lines of the debug log as well (the lines above the `------`; the log is available in the help menu)

**Comment by tooomm** [comment]
Can reproduce for some cards. Debug log shows nothing.

While normal Sorceries and Instants seem to work for me. I have the same issue with `Start // Finish`. But another spit (aftermath) card worked just fine: `Mouth // Feed`

**Comment by ebbit1q** [comment]
nice catch on the split cards, it only occurs on split cards that have two types, say Instant // Sorcery, the default is it going to the row for non creatures.
