### ISSUE TITLE
Some windows won't X closed

### ISSUE THREAD

**Issue by MotherofRuins** [Cockatrice/Cockatrice#3976]
Client Version: 2.7.4 (2020-03-20)
Client Operating System: Windows 7 SP 1 (6.1)
Build Architecture: 64-bit
Qt Version: 5.12.6
System Locale: en_US
Install Mode: Standard
_______________________________________________________________________________________

Two windows I've found won't close when you click the window's X close button:

Help-> About
Game -> Game Information

They will still close if you click the OK buttons or do Alt-F4

Pretty low priority but may be easy to fix.

**Comment by ebbit1q** [comment]
I can't replicate this.

**Comment by tooomm** [comment]
>Help-> About
Game -> Game Information

I can close them both on `X` click.

Running:
Client Version: 2.7.5-beta (2020-04-08)
Client Operating System: Windows 10 (10.0)

Can you try the newest beta @MotherofRuins ?

Can somebody else confirm this on Windows 7?

**Comment by ctrlaltca** [comment]
Just testet Windows 7 x32 and x64, works in both.

**Comment by ZeldaZach** [comment]
Gonna close as as a no fix as nobody can reproduce this
