### ISSUE TITLE
Show notifiaction when player joins your game

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#3977]
**Description of New Feature**
Don't miss out when a player joins your room while you are waiting for opponents and Cockatrice might be in the background. There would also be a sound.
Would make it easier for hosts to manage their games and react quickly & appropriately for a better experience for all users.

Example text: `A player joined your game` or `X joined your game`

Currently, the Cockatrice icon flashes. But that also happens for chat message in the game room.

**Comment by ZeldaZach** [comment]
Seems like a fine first issue to me. Good idea!
