### ISSUE TITLE
Cockatrice segfaults when viewing another user's games

### ISSUE THREAD

**Issue by ebbit1q** [Cockatrice/Cockatrice#3979]
Client Version: 2.7.5-beta.2 (2020-04-23)
Client Operating System: Pop!_OS 19.10
Build Architecture: 64-bit
Qt Version: 5.11.3
System Locale: en_GB
Install Mode: Standard
_______________________________________________________________________________________

Cockatrice segfaults when you click show this user's games:

1. connect to a server
2. go to account tab
3. right click an online buddy
4. click show this user's games
5. segfault

Stack trace:
```
#0  0x00005555557d2e80 in GamesProxyModel::getNumberOfAlteredFilters() const ()
#1  0x0000555555808682 in GameSelector::retranslateUi() ()
#2  0x0000555555809af0 in GameSelector::GameSelector(AbstractClient*, TabSupervisor const*, TabRoom*, QMap<int, QString> const&, QMap<int, QMap<int, QString> > const&, bool, bool, QWidget*) ()
#3  0x000055555589e723 in UserContextMenu::gamesOfUserReceived(Response const&, CommandContainer const&) ()
#4  0x00007ffff69b1e4a in QObject::event(QEvent*) ()
   from /lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007ffff787da86 in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    () from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#6  0x00007ffff7886e00 in QApplication::notify(QObject*, QEvent*) ()
   from /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#7  0x00007ffff6985a2a in QCoreApplication::notifyInternal2(QObject*, QEvent*)
    () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007ffff69886a8 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00007ffff69de037 in ?? () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x00007ffff595e8bd in g_main_context_dispatch ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#11 0x00007ffff595eb40 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#12 0x00007ffff595ebe3 in g_main_context_iteration ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#13 0x00007ffff69dd635 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#14 0x00007ffff69845cb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib/x86_64-linux-gnu/libQt5Core.so.5
#15 0x00007ffff698c336 in QCoreApplication::exec() ()
   from /lib/x86_64-linux-gnu/libQt5Core.so.5
#16 0x000055555577583d in main ()
```

**Comment by ebbit1q** [comment]
This also happens on master, see #3946

**Comment by knitknit** [comment]
Will revert change, we're altering the filter text anyway in https://github.com/Cockatrice/Cockatrice/pull/3973. Sorry for the bug!

**Comment by ebbit1q** [comment]
Note that you don't have to have a buddy online, you can just view any user's games.

**Comment by knitknit** [comment]
Interesting - I'm on a Mac, and I don't have the option to view an offline user's games (it's grayed out when I right-click). I can work around it by adding a random online user as a buddy, but I wonder if that's related?

**Comment by ebbit1q** [comment]
No, ehh, that always was like that. You can't see offline player's games because they can't have games open in the first place....

**Comment by tooomm** [comment]
>Note that you don't have to have a buddy online, you can just view any user's games.

@knitknit I assume ebbit just wanted to note, that you can check any online user on the server for their games. It doesn’t have to be a buddy to make it crash.

**Comment by knitknit** [comment]
Oh duh, I misread it - thanks!
