### ISSUE TITLE
Only first 57 cards from custom set are loaded

### ISSUE THREAD

**Issue by asherstuhlman** [Cockatrice/Cockatrice#3981]
I've been using Cockatrice to playtest a card game and I've implemented it in the form of a custom set. I've been running into a wall, though, as for some reason Cockatrice only loads 57 or so cards from my custom set into the deckbuilder. I assumed at first I was breaking the XML somehow, so I checked it by deleting individual cards - and I found that, no matter which cards they were, Cockatrice would stop loading them into the deckbuilder at a certain point. For instance, the 58th card in this file right now is called "Rogue (2)" and it doesn't fully load; cards after that don't load at all. If you go into the XML and delete 10 cards, the next 10 will load. What's going on with this behavior?

The xml file I'm using is here: http://stuhlman.net/TDH/TopdeckHeroes017.xml (right-click and save as, your browser will try to open it as a web page)

**Comment by tooomm** [comment]
Please provide client and debug log information when loading such a set as asked for.

**Comment by asherstuhlman** [comment]
Client Version: 2.7.0 (2019-03-04)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.9.7
System Locale: en_US
Install Mode: Standard
---------------------------------------------------------------------------
Theme changed: "Default"
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
Language changed: ""
main(): starting main program
Spoilers Disabled
CardDatabase::loadCardDatabases start
[CockatriceXml3Parser] Trying to parse:  "C:/Users/Asher/AppData/Local/Cockatrice/Cockatrice/cards.xml"
[CockatriceXml3Parser] Parsing failed: wrong version 4
[CockatriceXml4Parser] Trying to parse:  "C:/Users/Asher/AppData/Local/Cockatrice/Cockatrice/cards.xml"
main(): MainWindow constructor finished
main(): ui.show() finished
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Asher/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 20684 Sets= 472
[CockatriceXml3Parser] Trying to parse:  "C:/Users/Asher/AppData/Local/Cockatrice/Cockatrice/tokens.xml"
[CockatriceXml3Parser] Parsing failed: wrong version 4
[CockatriceXml4Parser] Trying to parse:  "C:/Users/Asher/AppData/Local/Cockatrice/Cockatrice/tokens.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Asher/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 21137 Sets= 472
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Asher/AppData/Local/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 21137 Sets= 472
CardDatabase::loadCardDatabases success
PictureLoader: cache fail for "_trice_card_back_308269"
PictureLoader: cache fail for "_trice_card_back_308269"
CardDatabase::loadCardDatabases start
[CockatriceXml3Parser] Trying to parse:  "C:/Users/Asher/AppData/Local/Cockatrice/Cockatrice/cards.xml"
[CockatriceXml3Parser] Parsing failed: wrong version 4
[CockatriceXml4Parser] Trying to parse:  "C:/Users/Asher/AppData/Local/Cockatrice/Cockatrice/cards.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Asher/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 20684 Sets= 472
[CockatriceXml3Parser] Trying to parse:  "C:/Users/Asher/AppData/Local/Cockatrice/Cockatrice/tokens.xml"
[CockatriceXml3Parser] Parsing failed: wrong version 4
[CockatriceXml4Parser] Trying to parse:  "C:/Users/Asher/AppData/Local/Cockatrice/Cockatrice/tokens.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Asher/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 21137 Sets= 472
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Asher/AppData/Local/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 21137 Sets= 472
[CockatriceXml3Parser] Trying to parse:  "C:/Users/Asher/AppData/Local/Cockatrice/Cockatrice/customsets/01.TopdeckHeroes017.xml"
[CockatriceXml3Parser] Parsing failed: wrong version 4
[CockatriceXml4Parser] Trying to parse:  "C:/Users/Asher/AppData/Local/Cockatrice/Cockatrice/customsets/01.TopdeckHeroes017.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Asher/AppData/Local/Cockatrice/Cockatrice/customsets/01.TopdeckHeroes017.xml" Status = 0 Cards = 21194 Sets= 474
CardDatabase::loadCardDatabases success
PictureLoader: [card:  "Beholder"  set:  "TDH" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Beholder"  set:  "TDH" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Beholder"  set:  "TDH" ]: Requested set property ( "muid" ) for Url template ( "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Beholder"  set:  "TDH" ]: Trying to load picture
PictureLoader: [card:  "Beholder"  set:  "TDH" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Beholder"  set:  "TDH" ]: Trying to download picture from url: "http://stuhlman.net/TDH/topdeck_heroes_17_053.gif"
PictureLoader: [card:  "Beholder"  set:  "TDH" ]: Image successfully downloaded from  "http://stuhlman.net/TDH/topdeck_heroes_17_053.gif"
PictureLoader: [card:  "Eye Beam"  set:  "TDH" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Eye Beam"  set:  "TDH" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Eye Beam"  set:  "TDH" ]: Requested set property ( "muid" ) for Url template ( "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Eye Beam"  set:  "TDH" ]: Trying to load picture
PictureLoader: [card:  "Disintegrate!"  set:  "TDH" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Disintegrate!"  set:  "TDH" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Eye Beam"  set:  "TDH" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Disintegrate!"  set:  "TDH" ]: Requested set property ( "muid" ) for Url template ( "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Eye Beam"  set:  "TDH" ]: Trying to download picture from url: "http://stuhlman.net/TDH/topdeck_heroes_17_054.gif"
PictureLoader: [card:  "Disintegrate!"  set:  "TDH" ]: Trying to load picture
PictureLoader: [card:  "Disintegrate!"  set:  "TDH" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Disintegrate! (2)"  set:  "TDH" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Disintegrate! (2)"  set:  "TDH" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Disintegrate! (2)"  set:  "TDH" ]: Requested set property ( "muid" ) for Url template ( "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Disintegrate! (2)"  set:  "TDH" ]: Trying to load picture
PictureLoader: [card:  "Disintegrate! (2)"  set:  "TDH" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Rogue"  set:  "TDH" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Rogue"  set:  "TDH" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Rogue"  set:  "TDH" ]: Requested set property ( "muid" ) for Url template ( "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Rogue"  set:  "TDH" ]: Trying to load picture
PictureLoader: [card:  "Rogue"  set:  "TDH" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Rogue (2)"  set:  "" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Rogue (2)"  set:  "" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Rogue (2)"  set:  "" ]: Requested set property ( "muid" ) for Url template ( "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Rogue (2)"  set:  "" ]: Trying to load picture
PictureLoader: [card:  "Rogue (2)"  set:  "" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Eye Beam"  set:  "TDH" ]: Image successfully downloaded from  "http://stuhlman.net/TDH/topdeck_heroes_17_054.gif"
PictureLoader: [card:  "Disintegrate!"  set:  "TDH" ]: Trying to download picture from url: "http://stuhlman.net/TDH/topdeck_heroes_17_055.gif"
PictureLoader: [card:  "Disintegrate!"  set:  "TDH" ]: Image successfully downloaded from  "http://stuhlman.net/TDH/topdeck_heroes_17_055.gif"
PictureLoader: [card:  "Disintegrate! (2)"  set:  "TDH" ]: Trying to download picture from url: "http://stuhlman.net/TDH/topdeck_heroes_17_056.gif"
PictureLoader: [card:  "Disintegrate! (2)"  set:  "TDH" ]: Image successfully downloaded from  "http://stuhlman.net/TDH/topdeck_heroes_17_056.gif"
PictureLoader: [card:  "Rogue"  set:  "TDH" ]: Trying to download picture from url: "http://stuhlman.net/TDH/topdeck_heroes_17_057.gif"
PictureLoader: [card:  "Rogue"  set:  "TDH" ]: Image successfully downloaded from  "http://stuhlman.net/TDH/topdeck_heroes_17_057.gif"
PictureLoader: [card:  "Rogue (2)"  set:  "" ]: Trying to download picture from url: "http://gatherer.wizards.com/Handlers/Image.ashx?name=Rogue %282%29&type=card"
PictureLoader: [card:  "Rogue (2)"  set:  "" ]: following redirect: "https://gatherer.wizards.com/Handlers/Image.ashx?name=Rogue %282%29&type=card"
PictureLoader: [card:  "Rogue (2)"  set:  "" ]:Picture downloaded, but blacklisted, will consider it as not found
PictureLoader: [card:  "Rogue (2)"  set:  "" ]:  Picture NOT found, download failed, no more url combinations to try: BAILING OUT
PictureLoader: [card:  "Fortune"  set:  "TDH" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Fortune"  set:  "TDH" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Fortune"  set:  "TDH" ]: Requested set property ( "muid" ) for Url template ( "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Fortune"  set:  "TDH" ]: Trying to load picture
PictureLoader: [card:  "Fortune"  set:  "TDH" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Fortune"  set:  "TDH" ]: Trying to download picture from url: "http://stuhlman.net/TDH/topdeck_heroes_17_004.gif"
PictureLoader: [card:  "Knowledge"  set:  "TDH" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Knowledge"  set:  "TDH" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Knowledge"  set:  "TDH" ]: Requested set property ( "muid" ) for Url template ( "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Fortune"  set:  "TDH" ]: Image successfully downloaded from  "http://stuhlman.net/TDH/topdeck_heroes_17_004.gif"
PictureLoader: [card:  "Knowledge"  set:  "TDH" ]: Trying to load picture
PictureLoader: [card:  "Knowledge"  set:  "TDH" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Knowledge"  set:  "TDH" ]: Trying to download picture from url: "http://stuhlman.net/TDH/topdeck_heroes_17_003.gif"
PictureLoader: [card:  "Deftness"  set:  "TDH" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Deftness"  set:  "TDH" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Deftness"  set:  "TDH" ]: Requested set property ( "muid" ) for Url template ( "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Deftness"  set:  "TDH" ]: Trying to load picture
PictureLoader: [card:  "Deftness"  set:  "TDH" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Knowledge"  set:  "TDH" ]: Image successfully downloaded from  "http://stuhlman.net/TDH/topdeck_heroes_17_003.gif"
PictureLoader: [card:  "Deftness"  set:  "TDH" ]: Trying to download picture from url: "http://stuhlman.net/TDH/topdeck_heroes_17_002.gif"
PictureLoader: [card:  "Deftness"  set:  "TDH" ]: Image successfully downloaded from  "http://stuhlman.net/TDH/topdeck_heroes_17_002.gif"
PictureLoader: [card:  "Power"  set:  "TDH" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Power"  set:  "TDH" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Power"  set:  "TDH" ]: Requested set property ( "muid" ) for Url template ( "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Power"  set:  "TDH" ]: Trying to load picture
PictureLoader: [card:  "Power"  set:  "TDH" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Power"  set:  "TDH" ]: Trying to download picture from url: "http://stuhlman.net/TDH/topdeck_heroes_17_001.gif"
PictureLoader: [card:  "Power"  set:  "TDH" ]: Image successfully downloaded from  "http://stuhlman.net/TDH/topdeck_heroes_17_001.gif"
PictureLoader: [card:  "Beholder"  set:  "TDH" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Beholder"  set:  "TDH" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Beholder"  set:  "TDH" ]: Requested set property ( "muid" ) for Url template ( "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Rogue"  set:  "TDH" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Rogue"  set:  "TDH" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Rogue"  set:  "TDH" ]: Requested set property ( "muid" ) for Url template ( "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Beholder"  set:  "TDH" ]: Trying to load picture
PictureLoader: [card:  "Beholder"  set:  "TDH" ]: Picture found on disk.
PictureLoader: [card:  "Rogue"  set:  "TDH" ]: Trying to load picture
PictureLoader: [card:  "Rogue"  set:  "TDH" ]: Picture found on disk.
PictureLoader: cache fail for "_trice_card_back_308269"
PictureLoader: cache fail for "_trice_card_back_308269"

**Comment by ctrlaltca** [comment]
The card "It's coming" is not encoded correctly:
```
 <name>It�s Coming...</name>
```
If you try to open the file eg. in Mozilla Firefox you'll see the error:

![Schermata 2020-04-29 alle 15 36 35](https://user-images.githubusercontent.com/1631111/80602331-44c3cc80-8a2f-11ea-9f4a-9c9584c912ff.png)

**Comment by asherstuhlman** [comment]
Thank you, that fixed it! I'm not sure why it broke at a separate card, instead of that one, but it works now.

**Comment by tooomm** [comment]
Also, your client version is one year outdated, you might want to run the most recent version with new features and fixes.
