### ISSUE TITLE
Automatically exile Companions on game start

### ISSUE THREAD

**Issue by YvesHenri** [Cockatrice/Cockatrice#3982]
Companions could be revealed on the begining each game (despite their companion rule), if the following pattern matches:

- it's the beginning of the game
- there's only one Companion card in the sideboard

Simply enough, they could be automatically sent to exile zone, making it much more user-friendly.

**Comment by ZeldaZach** [comment]
While indeed this would be a nifty feature, which could even be expanded to commanders, I am hesitant to go forward with such a change.

The server is card agnostic. It has no idea what a "companion" is, or what any card is. The server simply stores an object (name, player-side, x-coord, y-coord) and lets the clients decipher the rest. Adding any kind of checking logic would require a major overhaul of the servatrice object, which I don't find worth the time.

**Comment by ZeldaZach** [comment]
Falls under #282 imo. Closing as dupe.
