### ISSUE TITLE
Cockatrice requesting full disk access, access to calendar and contacts

### ISSUE THREAD

**Issue by kc711** [Cockatrice/Cockatrice#3984]
<b>System Information:</b>
  

  

macOS catalina, 10.15.4, cockatrice version 2.7.4
_______________________________________________________________________________________

  

Logged in to rooster ranges and then cockatrice prompted me for access to my calendars and contacts. In security and privacy system settings cockatrice was also listed as requesting full disk access. Never encountered that before with older versions/os. Any help appreciated, thanks.

**Comment by ctrlaltca** [comment]
From macOS Mojave, apple introduced these prompts the same way they are implementes in iOS.
Cockatrice can open files from your mac (eg. decks), so macOS tells you if you want it to be able to access also the directories containing calendars, contacts, or any directory (full disk access).
Cockatrice doesn't need these permissions.

Please have a read here: https://discuss.atom.io/t/why-does-macos-say-that-atom-wants-to-access-my-calendar-contacts-photos-etc/59291

**Comment by kc711** [comment]
Ah, great. Thanks very much for the response.
