### ISSUE TITLE
Cutomzing Appearance - Load two different tablezone.jpg

### ISSUE THREAD

**Issue by Assassinsquid** [Cockatrice/Cockatrice#3985]
When it comes to customzing the appearance of Cockatrice, You can only load one image for each zone (tablezone, stackzone...). So as a result, you see each zone twice (for you and your opponent), and it is not very beautiful. Is it possible to load two different images for each zone (one for you and one for your opponent) ? It would be a very great add. Thanks.

**Comment by fdipilla** [comment]
If the approach I'm using looks ok, I would like to make similar changes for all the zones and up to 4 players.

**Comment by ZeldaZach** [comment]
Fixed in the linked issues

**Comment by tooomm** [comment]
@fdipilla do you still want to apply your approach to the other zones as well?? That would be awesome! 🚀

**Comment by fdipilla** [comment]
Heck yeah!
