### ISSUE TITLE
Capitalize player counters

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#3992]
Player counters should be `W`, `U`, `B`, `R`, `G` and `C` (See https://github.com/Cockatrice/Cockatrice/issues/3991), as well as `Life` and `Storm`:

![counter_cap](https://user-images.githubusercontent.com/9874850/81398259-2d6c9980-9129-11ea-8ad3-0c04fbe9159a.png)

**Comment by awlangham** [comment]
Hi, is it alright if I submit a PR for this? I've capitalized the counter names where they are created in Server_Player::setupZones().

**Comment by ebbit1q** [comment]
We'd like to see your pr but note that if you change them on the server side you'll break backwards compatibility in server communication, it'd be preferable to keep these strings client side where they can also be translated.

**Comment by tooomm** [comment]
@awlangham Some other new contributor was a bit faster :)
Let us know if you want to help with something else!

**Comment by awlangham** [comment]
@tooomm Not a problem :) Is it alright if I help with #2874?

**Comment by tooomm** [comment]
Of course! Just check the open PR‘s or if somebody claimed the issue already - both is negative here :)

In case you want to chat or need help check Gitter or join our discord at best!
