### ISSUE TITLE
Can't compile debug build on ubuntu 20.04

### ISSUE THREAD

**Issue by ebbit1q** [Cockatrice/Cockatrice#3993]
As seen in this pr:
https://github.com/Cockatrice/Cockatrice/pull/3989

Ubuntu 20.04 uses qt 5.12 which has a bug that triggers a warning inside the qt headers, because debug builds do not allow warnings they fail.
Debug builds use the flag -CMAKE_BUILD_TYPE=Debug which sets different options for gcc (-Wall, -Wextra, -Werror)

The log here shows the full output: https://travis-ci.org/github/Cockatrice/Cockatrice/jobs/682556888

**Comment by ebbit1q** [comment]
This is an upstream bug, see ticket https://codereview.qt-project.org/c/qt/qtbase/+/272258

Note that this doesn't affect normal builds and you can still compile without -Werror

**Comment by tooomm** [comment]
Note: Due to this, we currently only use Ubuntu 20.04 LTS as `Release` build (running in Docker) and kept 18.04 for the `Debug` build and our tests at Travis.

**Comment by ebbit1q** [comment]
workaround until 2022 I guess add flag ` -DCMAKE_CXX_FLAGS="-w"` to disable warnings
