### ISSUE TITLE
macOS thinks cockatrice.app is possibly malware

### ISSUE THREAD

**Issue by jessegavin** [Cockatrice/Cockatrice#3994]
<b>System Information:</b>
  macOS Catalina 10.15.3 (19D76)
_______________________________________________________________________________________

I get the following error when launching the app. macOS gives me no options to resolve it except "Move to Trash"

    "cockatrice.app" cannot be opened because the developer cannot be verified.
    macOS cannot verify that this app is free from malware.

![image](https://user-images.githubusercontent.com/78791/81867549-8035bf00-9536-11ea-99e2-cbad6dc76a71.png)

**Comment by ZeldaZach** [comment]
If you right click > open on the program, you'll be able to open it. We don't have a signing key, and that's a default mac action for 10.15.X

**Comment by tooomm** [comment]
I added this to our FAQ as well:
https://github.com/Cockatrice/Cockatrice/wiki/Frequently-Asked-Questions-(FAQs)#developer-cannot-be-verified-pop-up-message-macos

**Comment by ebbit1q** [comment]
via right click? maybe a full description or a picture?

**Comment by tooomm** [comment]
I used the only available information from Zach's reply.
Maybe a macOS user can come up with a better explanation on how to easily deal with such a situation. 👍

**Comment by ebbit1q** [comment]
that's why I didn't specifically ask you to do so :)

**Comment by ctrlaltca** [comment]
Official documentation: https://support.apple.com/guide/mac-help/mh40616/mac

Long explanatory article with screenshots: https://www.howtogeek.com/205393/gatekeeper-101-why-your-mac-only-allows-apple-approved-software-by-default/

**Comment by tooomm** [comment]
Thanks @ctrlaltca!
The howtogeek article might be a bit too long and detailed. I linked the official support article from Apple instead. It automatically switches to your local language as well.
