### ISSUE TITLE
 the default tablezone tablezone.jpg, all players is not being honored in multiplayer (spectating)

### ISSUE THREAD

**Issue by jonschoning** [Cockatrice/Cockatrice#3998]
existing themes broken https://github.com/Cockatrice/Cockatrice/pull/3990
according to the PR i think the behavior should be
tablezone.jpg | default, all players
tablezone0.jpg | ignored
tablezone1.jpg | Player 1
tablezone2.jpg | Player 2
tablezone3.jpg | Player 3
?

## * Edit - the screenshots below are while spectating games

1.
However the default tablezone  `tablezone.jpg | default, all players` is not being honored.
the existing themes at https://github.com/Cockatrice/Cockatrice/wiki/Themes are broken in multiplayer Kitchen Table - by Yami | Screenshots
![image](https://user-images.githubusercontent.com/137183/82130228-211eb700-978f-11ea-9558-bec38223f092.png)

---
2. 
Aalso, i created a grey bg and made the following copies:
```
tablezone.png
tablezone0.png  
tablezone1.png  
tablezone2.png 
tablezone3.png  
tablezone4.png  
```
And in a 3-player game the grey bg is not used for one of the tablezones and it purple when it should be grey.
![image](https://user-images.githubusercontent.com/137183/82130327-131d6600-9790-11ea-8137-b4dbdff73534.png)

**Comment by fdipilla** [comment]
Well, this is awkward. When testing I always replaced the default tablezone for a purple one so the change will be more obvious to me when in fact in doing so I was screwing up my tests. I'm so sorry for that, I feel like an idiot.

I think I got number 1 fixed now.
I'll be trying to replicate number 2.

**Comment by ZeldaZach** [comment]
Heh things happen, and that's why we beta test. Don't worry about it, @fdipilla :)

When you have a fix ready, feel free to open another PR!

**Comment by tooomm** [comment]
No worries @fdipilla :)

----

>according to the PR i think the behavior should be
tablezone.jpg | default, all players
tablezone0.jpg | ignored
tablezone1.jpg | Player 1
tablezone2.jpg | Player 2
tablezone3.jpg | Player 3

@jonschoning this should not be how it currently works, this provided table by @fdipilla was a suggestion for a potential ideal behavior, which is not yet implemented.
