### ISSUE TITLE
Share deck

### ISSUE THREAD

**Issue by ctrlaltca** [Cockatrice/Cockatrice#400]
Basically a shortcut to:

(sender)
1. open deck editor
2. deck -> copy to clipboard
3. paste deck to a chat

(recipient)
1. (copy deck from chat)
2. open deck editor
3. deck -> paste from clipboard
4. ok
5. save as  (unsure about this one)

The recipient could get a dialog like: "%user shared with you a deck named %name. Do you want to open it in a new deck editor?"

**Comment by Daenyth** [comment]
closing in favor of #2555
