### ISSUE TITLE
Use an english translation file for better pluralization

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#4003]
**Description of New Feature**

@ebbit1q pointed this out in the discord:
>what I'm talking about is translating the source strings to english similarly as we do all the others to have: to quote the help article here: "To handle plural forms in the native language, you need to load a translation file for this language, too. The lupdate tool has the -pluralonly command line option, which allows the creation of TS files containing only entries with plural forms."

Linking #2029

**Comment by ebbit1q** [comment]
So zach delegated this to be by assigning me maintainership on transifex.
I want to move the source translation file to cockatrice_en@source.ts as painlessly as possible, without losing the existing translations on transifex.
Changing the file in the build scripts is a piece of cake but I don't want transifex to break :grimacing:

**Comment by ebbit1q** [comment]
I err added the new en_US language on transifex, it's complaining that noone translates it? I guess I hsould try searching for (s) and replace them

**Comment by ebbit1q** [comment]
![image](https://user-images.githubusercontent.com/36401181/94848906-f626be00-0424-11eb-97dc-215ab907faf6.png)
this warning is idiotic, can we disable it? I can see it preventing our translators from properly translating our project.

**Comment by tooomm** [comment]
I can hopp on discord and we can have a look. But I’m busy until Sunday for sure. 😔

Thanks for looking into that @ebbit1q.
Curious how transifex handles this and everything works out in the end. Several questions come to my mind...
