### ISSUE TITLE
Servatrice maintenance timed routines

### ISSUE THREAD

**Issue by woogerboy21** [Cockatrice/Cockatrice#402]
Currently there is no implementation for the servatrice application to perform any type of health check type routines resulting in things like replays to grow out of control.  Implementing a timed routine that performs maintenance tasks would be nice.  Replay cleanup is the first that comes to mind but doing other things like checking for configuration changes (maybe reg only required settings) may be another one.

Kind of brainstorming the idea right now...

**Comment by ZeldaZach** [comment]
While I think this might be a nice to have, cronjobs do the purpose and are more customizable. We need better docs on suggested cleanups for the wiki. @tooomm reach out i'll give you more details.

**Comment by tooomm** [comment]
I couldn't reach you, let me know on discord.

So far, there is only a placeholder page on the wiki (plus suggested content): https://github.com/Cockatrice/Cockatrice/wiki/Servatrice-Server-Maintenance
