### ISSUE TITLE
Deck Editor makes the Application crash.

### ISSUE THREAD

**Issue by redhead4444** [Cockatrice/Cockatrice#4020]
<b>System Information:
MacBook Pro (13inch - Mid 2012)
2,5 GHz intel Core i5
16 GB 1600 MHz DDR3
Intel HD Graphics 4000 1536 MB</b>
  
Client Version: 2.7.4 (2020-03-20)
Client Operating System: macOS High Sierra (10.13)
Build Architecture: 64-bit
Qt Version: 5.14.1
System Locale: es_ES
Install Mode: Standard
---------------------------------------------------------------------------
Theme changed: "Default"
SoundEngine: enabling sound
Sound theme changed: "Default"
SoundEngine: enabling sound
Language changed: ""
main(): starting main program
main(): MainWindow constructor finished
Spoilers Disabled
main(): ui.show() finished
Startup: found config with current version
CardDatabase::loadCardDatabases start
[CockatriceXml4Parser] Trying to parse:  "/Users/Antonio/Library/Application Support/Cockatrice/Cockatrice/cards.xml"
PictureLoader: cache fail for "_trice_card_back_232372"
[CardDatabase] loadCardDatabase(): Path = "/Users/Antonio/Library/Application Support/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 20927 Sets= 483
[CockatriceXml4Parser] Trying to parse:  "/Users/Antonio/Library/Application Support/Cockatrice/Cockatrice/tokens.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
[CardDatabase] loadCardDatabase(): Path = "/Users/Antonio/Library/Application Support/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 21390 Sets= 483
[CardDatabase] loadCardDatabase(): Path = "/Users/Antonio/Library/Application Support/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 21390 Sets= 483
CardDatabase::loadCardDatabases success

_______________________________________________________________________________________

**Comment by tooomm** [comment]
Double entry
