### ISSUE TITLE
A box for describing your game lobby stop being cancerous cunts

### ISSUE THREAD

**Issue by 100cardcombo** [Cockatrice/Cockatrice#4022]
I feel it might be interesting/wise/prudent to add a box in the lobby creation screen where you can put additional information. As a EDH player I am getting sick of people disregarding my lobby title and bringing decks that they think are casual and you think aren't. Given more room to describe your lobbies, I think that you can more cleanly separate players who want to play by your rules from those who don't. 

If no textbox is possible or wanted, perhaps you could add a system where you can select key phrases to indicate the same. Phrases like "friendly", "competetive", "no mld", "no combo", "italiano" and what have you.

**Comment by ebbit1q** [comment]
Where in the interface would we place this "longer description"? The current description box allows 61 characters and is displayed on only single line in order to fit in the list. A possibility would be a tooltip but those are easily ignored.

**Comment by 100cardcombo** [comment]
Input can be in the lobby creation screen, output can be the log when everything is starting up.
