### ISSUE TITLE
Batch download all the card gallery at once

### ISSUE THREAD

**Issue by onepunchmanu** [Cockatrice/Cockatrice#4025]
**Similar Requests**
There have been similar requests like this, but they didn't include a solution to the problem

 Downloading all the images of the cards at the same time
**Description of New Feature**
A way to download the whole gallery of the card images to be able to build new decks offline and for other purposes.

My internet connection is pretty bad, and some new cards take up to minutes before they show up. This would fix it completely, and I don't see why it couldn't be made.
**Additional Context**

**Comment by tooomm** [comment]
I'm not comfortable with hitting other services for gigabytes of data and 22k requests.
Probably you would get rate limited anyway and the download wouldn't complete.

If you are on such a bad connection, the download would take ages which leads to further problems.

To try to help you:
- Which settings do you use to download picture data? Maybe try to change the picture provider or go with a special low quality option if your connection is that bad and speed loading up?
You should find some information about that in the wiki.

- There should be other sources providing picture downloads for all cards. You can download them and use the custom picture folder to use them.

- Also, may I suggest that you can still build decks offline? Just switch to the text option of the card

**Comment by onepunchmanu** [comment]
Thanks @tooomm , didn't know I could change the quality of the picture. For now I think it is the best I can do while I search for a single download with all the pictures of the cards. Yes, it would take ages, but at least I wouldn't have that those problems again.

**Comment by ZeldaZach** [comment]
Thanks for the suggestion @onepunchmanu, but unfortunately I don't feel comfortable with such a change. We rely on upstream providers to give us data, and hammering their services with the force of 1000+ users at anytime is a quick way to get yourself blocked by the networks. There are services out there that have ZIP files you can download and put into the card loader directory so you don't have to waste time downloading cards on the fly.
