### ISSUE TITLE
Compilation error: aggregate 'QPainterPath path' has incomplete type and cannot be defined

### ISSUE THREAD

**Issue by safuya** [Cockatrice/Cockatrice#4028]
<b>System Information:</b>
  

  
Git hash version:
0f0e0193c11219cd56d07ffff1969f37f8e8d256

Arch Linux: Linux desktop 5.7.2-arch1-1 #1 SMP PREEMPT Wed, 10 Jun 2020 20:36:24 +0000 x86_64 GNU/Linux
cmake 3.17.3-1
protobuf 3.12.0-1
qt5-base 5.15.0-3
qt5-multimedia 5.15.0-1
qt5-svg 5.15.0-1
qt5-tools 5.15.0-2
qt5-websockets 5.15.0-1
_______________________________________________________________________________________

  
Failing to make with error:

```
[ 84%] Building CXX object cockatrice/CMakeFiles/cockatrice.dir/src/replay_timeline_widget.cpp.o
/home/safuya/Cockatrice/cockatrice/src/replay_timeline_widget.cpp: In member function 'virtual void ReplayTimelineWidget::paintEvent(QPaintEvent*)':
/home/safuya/Cockatrice/cockatrice/src/replay_timeline_widget.cpp:53:18: error: aggregate 'QPainterPath path' has incomplete type and cannot be defined
   53 |     QPainterPath path;
      |                  ^~~~
make[2]: *** [cockatrice/CMakeFiles/cockatrice.dir/build.make:1545: cockatrice/CMakeFiles/cockatrice.dir/src/replay_timeline_widget.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:354: cockatrice/CMakeFiles/cockatrice.dir/all] Error 2
make: *** [Makefile:172: all] Error 2
```

**Comment by ebbit1q** [comment]
I already submitted a pr for this here: https://github.com/Cockatrice/Cockatrice/pull/4027

**Comment by ebbit1q** [comment]
You'll already be able to build that branch while I work out the remaining warnings.
