### ISSUE TITLE
Deck Editor: add a "force-add card name" red arrow button beside blue and green arrows

### ISSUE THREAD

**Issue by aeschenkarnos** [Cockatrice/Cockatrice#4031]
Often a spoiler appears somewhere (eg reddit discussions) and I would like to add that card to a deck immediately, before I forget about it. Cockatrice's deck format is a text file with card names, and if a deck file contains unknown cards it's capable of importing those cards in under the "unknown card" subsection.

It would be useful to be able to manually add in a card name that has no associated card in the database, for this purpose. Once the spoilers are updated, it will appear in the proper place in the decklist, with associated art and description.

**Comment by ZeldaZach** [comment]
Trying to add a card not found in your database feels like a problem waiting to happen. If you don't have the card, and nobody else has it, it could be annoying when playing games. We update spoilers once a day, which only leaves a little lag time in between when a card is spoiled and when you can actually use it in client. In the future, we could look into updating spoilers twice a day to reduce this gap, but I don't like the idea of force adding "junk" to a deck.

**Comment by ebbit1q** [comment]
note that you're currently able to add "junk" to your deck using the load deck from clipboard feature
