### ISSUE TITLE
Cockatrice Lost all of ikoria for me?

### ISSUE THREAD

**Issue by Jaystorm5050** [Cockatrice/Cockatrice#4034]
I just tried to update my game and instead of just adding cards it deleted ikoria and reverted the cards that spoiled in ikoria into the joke names they had in the beginning, Like Deadly Rollick was "No Capes" but yesterday everything was perfectly fine. I have everything else but for some reason Ikoria just disappeared for the most part and with it so did most of the decks I built. What can i do to fix this problem

**Comment by ebbit1q** [comment]
This is an issue with our card data provider https://mtgjson.com/ you should be able to update again soon enough, just give them some time.

**Comment by ZeldaZach** [comment]
We have this fixed up now!
