### ISSUE TITLE
cards.xml folder missing on install (no card database ): )

### ISSUE THREAD

**Issue by Tr1cycle** [Cockatrice/Cockatrice#4035]
I'm using debian and am a linux noob so I could be doing something wrong but when I got Cockatrice there was no cards.xml folder. same for tokens. thanks

**Comment by tooomm** [comment]
Did you run the Oracle tool to download them as asked on first run?
Check the first menu in the bar and select “Check for card updates...”.

**Comment by ebbit1q** [comment]
cards.xml should be a file, not a folder/directory, on linux it's located at ~/.local/share/Cockatrice/Cockatrice

**Comment by Tr1cycle** [comment]
ebbit1q typo by me. The file isn't there though.

**Comment by ebbit1q** [comment]
Did you run oracle as prompted on first startup?

**Comment by tooomm** [comment]
@Tr1cycle See https://github.com/Cockatrice/Cockatrice/wiki/Frequently-Asked-Questions-%28FAQs%29#how-do-i-update-my-card-database-to-have-the-latest-cards

**Comment by ZeldaZach** [comment]
If this is still an issue @Tr1cycle please let us know!
