### ISSUE TITLE
Search for cmc not possible

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#4036]
**Description of New Feature**
- Allow to search for cards with a certain converted mana cost:
`cmc:2` should show cards with converted mana cost of two

**Comment by skwerlman** [comment]
this is already implemented.

from https://github.com/Cockatrice/Cockatrice/blob/master/cockatrice/resources/help/search.md
```
Power, Toughness, Converted Mana Cost:
tou:1 (Any card with a toughness of 1)
pow>=8 (Any card with a power greater than or equal to 8)
cmc=7 (Any card with a converted mana cost equal to 7) 
```

**Comment by ebbit1q** [comment]
cmc:2 works just fine, if you continue having this problem open it as a troubleshooting ticket.

**Comment by tooomm** [comment]
Interesting. Both do not work for me (`cmc:2` and `cmc=2`).
I was sure such a basic query must work...

I only have M21 enabled, for IKO it works. So I assume it's a card db issue - in this case the spoiler file as M21 is not yet in MTGJSON.
The M21 spoiler file has cmc information... weird. https://github.com/Cockatrice/Magic-Spoiler/blob/df1db2db416fdfcaa7eb3131b8ef241ec2cdf05e/M21.xml

<br>

Lol, just before hitting the `Comment` button I switched back to M21 from my IKO test and now it works?!
