### ISSUE TITLE
Deck Editor: Allow Copy Card Name from card Database

### ISSUE THREAD

**Issue by MotherofRuins** [Cockatrice/Cockatrice#4041]
When highlighting a card in my deck, I can Ctrl-C to copy the card name to the clipboard.  Very helpful!

I would also like to be able to Ctrl-C to copy the card name to the clipboard when highlighting a card name in the card database.  That would save me from having to add it to a deck, then copy from the deck.

**Comment by ZeldaZach** [comment]
This seems like a great first issue for newer developers, so I've labeled it as such
