### ISSUE TITLE
Ctrl+T breaks the game

### ISSUE THREAD

**Issue by CtrlTBroken** [Cockatrice/Cockatrice#4042]
Client Version: 2.7.4 (2020-03-20)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.12.6
System Locale: pt_PT
Install Mode: Standard
_______________________________________________________________________________________

My issue is the following, whenever i make a token if it's the first time i open the token menu in that match the game freezes for very long time, up to 1m or sometimes even more, during that time I can't do anything. After that the software either completely breaks with cockatrice being closed, or it unfreezes and then it works as intended for the remaining of the match. This happens every time i first make a token in a match. The problem has been going on for about 2 weeks for me now, I don't know if other have the same issue, but decided to report and hope for a solution, I believe I've everything updated, dunno what's wrong here. Thanks in advance.

**Comment by tooomm** [comment]
Try updating your card (and token) database, please. You have to run the oracle tool for that (Cockatrice --> Check for card updates).
You did not change the path to your card and token database in settings?

If that doesn't work, please try the newest beta release. I'm using that with the newest cards on Windows 10 without problems. Ctrl+T works flawlessly.

**Comment by ebbit1q** [comment]
This issue was present on an older version of cockatrice, are you sure you are using the most recent version?

**Comment by ZeldaZach** [comment]
Known issue on older versions of Cockatrice. Please update to 2.7.5 (or whatever is the latest release) for a solution.
