### ISSUE TITLE
Switch to MTGJSON v5 (v4 deprecated in 2020)

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#4043]
**Description of New Feature**
MTGJSON v5 got released: https://mtgjson.com/changelog/version-5/

Switch over to the new release for downloading and processing card data for our database.

Also, the version file/information is integrated right into the card data download now. There is still a separate version file (called meta now) available. Relevant for https://github.com/Cockatrice/Cockatrice/issues/3647.
<br>

**v4 is deprecated and only works until the end of 2020!** See https://mtgjson.com/changelog/version-4/

---

Linking #4097

**Comment by aeschenkarnos** [comment]
Is this also an opportunity to update .dec format to allow for support of player-chosen card versions?

**Comment by ebbit1q** [comment]
Changing the database to allow a different key than the card name would encompass a lot more. Changing to mtgjson v5 doesn't change that situation, consider that mtgjson v4 also contains all different versions of a card but we just choose to keep one. The protocol is based on the assumption that all the identifying information is contained in the card's name a well. See https://github.com/Cockatrice/Cockatrice/issues/486
