### ISSUE TITLE
Issues with player information widget after resizable change

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#4051]
<b>System Information:</b>
Client Version: 2.7.4-custom(880ed8c) (2020-07-23)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.12.6
System Locale: de_DE
Install Mode: Standard
_______________________________________________________________________________________

  

#4009 introduced a problem to the Player Information widget.
The values for coutnry and account age are right aligned to the player picture. That way the reference to their label is lost and everything looks off.
You realize at best when there is a rectangular avatar and you increase the width further.

![user-info](https://user-images.githubusercontent.com/9874850/88388388-b56f5080-cdb4-11ea-8bbd-bc5b64728b97.png)

Those values should not move on window size changes at all.

CC: @awlangham

**Comment by ebbit1q** [comment]
Ah, that's why I was doubtful about this change here: https://github.com/Cockatrice/Cockatrice/commit/fe63dfa76260c4baee339ca3f08e3a1ab340a408#diff-0315bae3665ab5e87457406874ba4b3aR46

Just undoing that would fix this.

**Comment by ebbit1q** [comment]
Actually no, scratch that, it's this here https://github.com/Cockatrice/Cockatrice/commit/fe63dfa76260c4baee339ca3f08e3a1ab340a408#diff-0315bae3665ab5e87457406874ba4b3aR34

**Comment by awlangham** [comment]
Seems like undoing both of those lines mentioned fixes this problem, but then there's nothing centering the player icon. Removing the Qt::AlignCenter flag was necessary to allow the label to expand. Undoing both of these would allow it to expand while not affecting column 2 or 3's widths, but then the avatar label won't be centered horizontally anymore. I'll investigate further.

**Comment by ebbit1q** [comment]
If necessary, use a second layout nested in the first one to separate the label and the text, this trick makes them independent of each other.

**Comment by awlangham** [comment]
That's a good idea. I'll look into it. Apologies for causing another issue with my code.

**Comment by ebbit1q** [comment]
You have nothing to apologize for. :)

**Comment by tooomm** [comment]
Did you check column span and alignment options? https://doc.qt.io/qt-5/qgridlayout.html

**Comment by ebbit1q** [comment]
We already set the column span option, you can also set the row span, but it's generally a pain. In my own projects I generally go the lazy way and simply use nested layouts and spacers, it's less efficient but it's less of a hassle than tweaking with qt's layout options.

**Comment by tooomm** [comment]
>We already set the column span option

Yes, but it's set to 1. So it spans over 1 column, I think we want it to span over all columns (correct value would be 3, no?). There is also the -1 option.

I don't think we need row span.
