### ISSUE TITLE
Artifact Lands are being grouped with Artifacts instead of Lands

### ISSUE THREAD

**Issue by ArtifactLands** [Cockatrice/Cockatrice#4053]
<b>System Information:</b>
  

  
_______________________________________________________________________________________

**Comment by ebbit1q** [comment]
Please include your system information from your log in your bug report, this issue happened on an old version of cockatrice, please make sure your version is up to date.

**Comment by ebbit1q** [comment]
See #3621 more than a year ago. The most recent version is 2.7.4 now. I'm unable to reproduce the issue with the current version.
