### ISSUE TITLE
Appveyor failing

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#4054]
Appveyor currently fails due to a timing cap at 1h.
Compilation of protobuf seems to take to long and the cached version can't be used.

**Comment by ebbit1q** [comment]
This will likely require us to update the image we use on appveyor again, see https://github.com/Cockatrice/Cockatrice/pull/3020

**Comment by olegshtch** [comment]
Looks like keyring should be updated: https://www.msys2.org/news/#2020-06-29-new-packagers

**Comment by ctrlaltca** [comment]
Maybe appveyor fixed the images? the last PR builded fine

**Comment by olegshtch** [comment]
Looks like it was fixed in https://github.com/microsoft/vcpkg/pull/12467
