### ISSUE TITLE
Can there be a way to interact with other players' boards?

### ISSUE THREAD

**Issue by swalters37** [Cockatrice/Cockatrice#4060]
**Similar Requests**
Owned/Controlled card manipulation #104

**Description of New Feature**
A setting that could be toggled, probably upon creating a room, that would allow players to interact with cards that are visible on other boards. Specifically moving them between boards to exchange control.

**Additional Context**
I began to use Cockatrice to host another card game called Ramen Fury, that relies on players drawing cards from a group of face up cards. We currently have it set up so that one player is the "dealer" and has to pay close attention to what people ask for, but if we continue to play this game (and maybe other imported games) then it would be really useful for there to be a way for any player to move cards around.

**Comment by ZeldaZach** [comment]
Feels like an addendum to #104 (as you stated), so I'm gonna close it as such. However, this would still be a nifty thing to have!
