### ISSUE TITLE
"Location is not available" (unable to browse network drive) in ver 2.5 or greater

### ISSUE THREAD

**Issue by crimson30** [Cockatrice/Cockatrice#4061]
<b>System Information:</b>
Client Version: 2.7.4 (2020-03-20)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.12.6
System Locale: en_US
Install Mode: Standard
---------------------------------------------------------------------------
Theme changed: "Default"
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
Language changed: ""
main(): starting main program
main(): MainWindow constructor finished
Spoilers Disabled
main(): ui.show() finished
Startup: found config with current version
CardDatabase::loadCardDatabases start
[CockatriceXml4Parser] Trying to parse:  "C:/Users/crimson30/AppData/Local/Cockatrice/Cockatrice/cards.xml"
[CockatriceXml4Parser] Parsing failed: wrong version 3
[CockatriceXml3Parser] Trying to parse:  "C:/Users/crimson30/AppData/Local/Cockatrice/Cockatrice/cards.xml"
QWindowsWindow::setGeometry: Unable to set geometry 2048x1059+0+34 (frame: 2070x1115-11-11) on QWidgetWindow/"MainWindowClassWindow" on "\\.\DISPLAY1". Resulting geometry: 2048x1058+0+34 (frame: 2070x1114-11-11) margins: 11, 45, 11, 11 minimum size: 908x1059 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=930,1115 maxtrack=0,0)
PictureLoader: cache fail for "_trice_card_back_308469"
PictureLoader: cache fail for "_trice_card_back_308466"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/crimson30/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 21254 Sets= 492
[CockatriceXml4Parser] Trying to parse:  "C:/Users/crimson30/AppData/Local/Cockatrice/Cockatrice/tokens.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
[CardDatabase] loadCardDatabase(): Path = "C:/Users/crimson30/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 21724 Sets= 492
[CardDatabase] loadCardDatabase(): Path = "C:/Users/crimson30/AppData/Local/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 21724 Sets= 492
CardDatabase::loadCardDatabases success

  
When I try to load a deck in 2.5 or above, I get:
![2 7 4](https://user-images.githubusercontent.com/13973790/89694003-81744f00-d8cd-11ea-83d4-1263e4a4dd7f.jpg)

If I try using d55e44e (2015-09-23), it works fine:
![d55e44e (2015-09-23)](https://user-images.githubusercontent.com/13973790/89693822-df546700-d8cc-11ea-9ad1-a7390c0a0269.jpg)

If I uninstall d55e44e and reinstall 2.5 or greater, I get the error again, and if I reinstall d55e44e again, I am able to load decks just fine.  I hopped around versions several times and can accurately reproduce and fix the error each time by uninstalling and reinstalling different versions.

**Comment by skwerlman** [comment]
is `Y:` a network drive, and if so, what kind of share is it? samba? nfs?

**Comment by crimson30** [comment]
smb on a CentOS 8 box

**Comment by ebbit1q** [comment]
That's a version from 2015, it might be any change in qt version in between those years.

**Comment by crimson30** [comment]
I hadn't noticed the "Next" link at the bottom of the release downloads page.  I reproduced the problem with the May 8, 2016 release (The Shadows) and the Feb 3, 2016 release (Gatewatchers) works fine.

**Comment by ebbit1q** [comment]
That it got released then, doesn't mean it's immediately in use, it will tell you in the log which version is used.

**Comment by crimson30** [comment]
I was able to get it to work by installing the May 8, 2016 release (The Shadows) and copying the old Qt5Network.dll into the cockatrice directory.  Looks like qt is indeed the culprit.

**Comment by ZeldaZach** [comment]
This is a QT issue, so an upstream alert might be needed. Unfortunately, this is out of our control and I'm terribly sorry for the bad user experience. We can't easily diagnose this on our end, but if you'd like to ping QT they might be able to help!
