### ISSUE TITLE
Manage Sets set order not respected

### ISSUE THREAD

**Issue by MotherofRuins** [Cockatrice/Cockatrice#4062]
I am getting the 2XM mana vault and similar cards even though I have 2xm unchecked.
Also, I get M21 promo versions of images even though M21 Promos is unchecked.
ELD showcases are displayed instead of regular adventure frames.  PELD is unchecked.
V12 (unchecked) Dryad Arbor is shown instead of FUT (checked).
Spacegodzilla is shown instead of Brokkos even though PIKO is unchecked.
Dryad of the Ilysian Grove and Nyxbloom Ancient and Tectonic Giant frameless are shown (PTHB is unchecked)

Many other examples can be found.

**Comment by ebbit1q** [comment]
Is this problem still present on the beta branch?

**Comment by skwerlman** [comment]
couldnt repro this issue when i checked a couple days ago but maybe i missed something: #3263

**Comment by ebbit1q** [comment]
well, 2xm is in the main database now, right? the spoiler.xml should be gone and be unable to conflict with cards.

**Comment by MotherofRuins** [comment]
Client Version: 2.7.4 (2020-03-20)
Client Operating System: Windows 7 SP 1 (6.1)
Build Architecture: 64-bit
Qt Version: 5.12.6
System Locale: en_US
Install Mode: Standard

**Comment by MotherofRuins** [comment]
Apologies, the 2XM card is Mana Crypt, not vault.  The other observations stand though.

**Comment by skwerlman** [comment]
can you try to replicate this on the beta channel?

**Comment by MotherofRuins** [comment]
Okay after some more digging, these are due to a variety of reasons:

1.  Dryad Arbor somehow I had the V12 image in my FUT folder.
2.  Mana Crypt I had all set sit exists in unchecked, so it did not show up in Deck Editor.  In game, it decided to just use the topmost version I believe.
3.  Showcase and frameless card versions, and Godzilla cards, are parts of their basic sets, not the promo sets.  In cards.xml, for each set, there is only one listing, usually the highest set number for that card.  

Maybe the cards in each group after the base set should get their own distinguishing set codes.  Looking at scryfall for THB, for example, [https://scryfall.com/sets/thb?as=grid&order=set](url) you see the following categories:

IN BOOSTERS • 254 CARDS
BORDERLESS PLANESWALKERS • 3 CARDS
SHOWCASE CARDS • 11 CARDS
BUY-A-BOX • 1 CARD
PLANESWALKER DECKS • 18 CARDS
THEME BOOSTER CARDS • 10 CARD
EXTENDED ART CARDS • 55 CARDS
PROMOS • 6 CARDS

So someone decided that cards.xml for Dryad of the Ilysian Grove for THB would use card 326 instead of 169.  Personally, I prefer the standard frames.  Not sure how you would want to handle this, so I'm closing this issue.

**Comment by ebbit1q** [comment]
this is precisely what removing duplicate promos did

**Comment by ebbit1q** [comment]
https://github.com/Cockatrice/Cockatrice/pull/3965 from april 23th, now finally in a release
