### ISSUE TITLE
Database Missing Cards

### ISSUE THREAD

**Issue by jonidcrushfire** [Cockatrice/Cockatrice#4065]
<b>System Information:</b>
  

  
_______________________________________________________________________________________

  Recently updated Cockatrice via Oracle to get newest card database. It is missing many, many cards. From the previous update to now, I would hazard a guess and say roughly 3000 cards, if I'm going by the total number downloaded in the message. How can I get a proper update?

**Comment by ChrisGz95** [comment]
I have noticed that Ixalan and Zendikar are missing, coincidentally they are at the bottom of the list of sets, maybe cockatrice has a limit to the number of sets it can import?

I was able to manually paste in the <sets></sets> and <cards></cards> section of the XML into cards.xml to "trick" cockatrice into accepting the sets into the database.

**Comment by tooomm** [comment]
Please let us know which version of Cockatrice you are using...

Also, paste the complete debug log after you start cockatrice. It tells you how many cards are imported and from which source.

**Comment by ChrisGz95** [comment]
Cockatrice (64-bit)
Version 2.7.4 (2020-03-20)

Client Version: 2.7.4 (2020-03-20)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.12.6
System Locale: en_US
Install Mode: Portable
---------------------------------------------------------------------------
Portable mode enabled
Theme changed: "Default"
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
Language changed: ""
main(): starting main program
main(): MainWindow constructor finished
Spoilers Disabled
main(): ui.show() finished
Startup: found config with current version
CardDatabase::loadCardDatabases start
[CockatriceXml4Parser] Trying to parse:  "C:/Users/someguy/Desktop/CockatricePortable/data/cards.xml"
QWindowsWindow::setGeometry: Unable to set geometry 1920x1074+0+23 (frame: 1936x1113-8-8) on QWidgetWindow/"MainWindowClassWindow" on "\\.\DISPLAY1". Resulting geometry: 1920x1057+0+23 (frame: 1936x1096-8-8) margins: 8, 31, 8, 8 minimum size: 806x1074 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=822,1113 maxtrack=0,0)
PictureLoader: cache fail for "_trice_card_back_226286"
PictureLoader: cache fail for "_trice_card_back_226285"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/someguy/Desktop/CockatricePortable/data/cards.xml" Status = 0 Cards = 17540 Sets= 411
[CockatriceXml4Parser] Trying to parse:  "C:/Users/someguy/Desktop/CockatricePortable/data/tokens.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
[CardDatabase] loadCardDatabase(): Path = "C:/Users/someguy/Desktop/CockatricePortable/data/tokens.xml" Status = 0 Cards = 18012 Sets= 433
[CardDatabase] loadCardDatabase(): Path = "C:/Users/someguy/Desktop/CockatricePortable/data/spoiler.xml" Status = 4 Cards = 18012 Sets= 433
CardDatabase::loadCardDatabases success
PictureLoader: [card:  "1996 World Champion"  set:  "PCEL" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "1996 World Champion"  set:  "PCEL" ]: Requested set property ( "muid" ) for Url template ( "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "1996 World Champion"  set:  "PCEL" ]: Trying to load picture
PictureLoader: [card:  "1996 World Champion"  set:  "PCEL" ]: Picture found on disk.

**Comment by florenceboettger** [comment]
I'm having the same problem, here's the log for running the import after a fresh install:

```Client Version: 2.7.4 (2020-03-20)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.12.6
System Locale: de_DE
Install Mode: Standard
---------------------------------------------------------------------------
Theme name not set, setting default value
Theme changed: "Default"
Sounds theme name not set, setting default value
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
Language changed: ""
main(): starting main program
main(): MainWindow constructor finished
Spoilers Disabled
main(): ui.show() finished
Startup: old client version empty, assuming first start after clean install
PictureLoader: cache fail for "_trice_card_back_272595"
CardDatabase::loadCardDatabases start
[CockatriceXml4Parser] Trying to parse:  "C:/Users/Flori/AppData/Local/Cockatrice/Cockatrice/cards.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Flori/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 17540 Sets= 411
[CockatriceXml4Parser] Trying to parse:  "C:/Users/Flori/AppData/Local/Cockatrice/Cockatrice/tokens.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Flori/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 18012 Sets= 433
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Flori/AppData/Local/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 18012 Sets= 433
CardDatabase::loadCardDatabases success
PictureLoader: cache fail for "_trice_card_back_272595"
```

Notably, the issues here stem from the cards.xml file. For instance, it doesn't have an entry for Theros Beyond Death or original Theros (only the promos for those sets). The only results for "Theros" in the file are the TBD promos, the original Theros Promos and 2 entries for Soul of Theros from M15. However, the .json from [https://www.mtgjson.com/files/AllPrintings.json.xz](https://www.mtgjson.com/files/AllPrintings.json.xz) does contain those sets, so it seems to be an issue in parsing that file to the xml. Cards that were only in a missing set, such as Battlewise Valor from original Theros, also do not appear in the cards.xml.

**Comment by tooomm** [comment]
Thanks for the reports.

Jep, there are many many cards missing, there should be >21.000 cards. Probably an issue with our card source.

**Comment by florenceboettger** [comment]
> @florenceboettger we still use the old v4 version of MTGJSON. Can you confirm that the cards are missing there as well?

@tooomm I tried deliberately using the v4 version by using [https://mtgjson.com/api/v4/AllPrintings.json.xz](https://mtgjson.com/api/v4/AllPrintings.json.xz) as the source, but the sets and cards are still missing.

**Comment by tooomm** [comment]
That is no surprise as that is the exact same file oracle uses by default. Just another link if their forwarding works.

I meant to manually look into the v4 mtgjson file and check if the cards are missing there, too. You did that with v5 already.

**Comment by florenceboettger** [comment]
@tooomm I checked the json again and realized I messed up in my assessment last time - searching Scars of Mirrodin brings up a lot of results, but most of them are from the other sets in SOM block and SOM promos. The actual SOM set isn't in there. Individual cards such as Battlewise Valor are also missing from the json. My bad for not checking properly last time.

**Comment by tooomm** [comment]
Ok, thanks for investigating!
That should be enough information... It’s a mtgjson problem with v4 then I guess. @zeldazach

**Comment by jonidcrushfire** [comment]
Client Version: 2.7.4 (2020-03-20)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.12.6
System Locale: en_US
Install Mode: Portable
---------------------------------------------------------------------------
Portable mode enabled
Theme changed: "Default"
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
Language changed: ""
main(): starting main program
main(): MainWindow constructor finished
Spoilers Disabled
main(): ui.show() finished
Startup: found config with current version
CardDatabase::loadCardDatabases start
[CockatriceXml4Parser] Trying to parse:  "C:/Users/username/Desktop/Game Stuff/MTG/Cockatrice/data/cards.xml"
PictureLoader: cache fail for "_trice_card_back_226293"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/username/Desktop/Game Stuff/MTG/Cockatrice/data/cards.xml" Status = 0 Cards = 17540 Sets= 411
[CockatriceXml4Parser] Trying to parse:  "C:/Users/username/Desktop/Game Stuff/MTG/Cockatrice/data/tokens.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
[CardDatabase] loadCardDatabase(): Path = "C:/Users/username/Desktop/Game Stuff/MTG/Cockatrice/data/tokens.xml" Status = 0 Cards = 18012 Sets= 433
[CardDatabase] loadCardDatabase(): Path = "C:/Users/username/Desktop/Game Stuff/MTG/Cockatrice/data/spoiler.xml" Status = 4 Cards = 18012 Sets= 433
[CockatriceXml4Parser] Trying to parse:  "C:/Users/username/Desktop/Game Stuff/MTG/Cockatrice/data/customsets/TK.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/username/Desktop/Game Stuff/MTG/Cockatrice/data/customsets/TK.xml" Status = 0 Cards = 18012 Sets= 433
CardDatabase::loadCardDatabases success



If this helps, here it is. I tried again today. What I have noticed in my sets is in the pics. Mostly, a bunch of sets with "returns" such as Ravnica, Theros, etc are missing some of their iterations.
![Cockatrice Bug](https://user-images.githubusercontent.com/69694379/90320414-37afe800-df0f-11ea-9a84-ef089285fede.png)

**Comment by flomerboy** [comment]
Just wanted to comment that I have also experienced this issue - it does seem to be a problem with the data source. Is there any way to be notified when there's a fix?

**Comment by ZeldaZach** [comment]
Known issue with MTGJSON. See https://github.com/mtgjson/mtgjson/issues/654 for tracking details. I rolled back the changes from yesterday, so this should be temporarily addressed. Fix is in the works, ETA of 6 hours or so.

**Comment by flomerboy** [comment]
@ZeldaZach That bug says it's only a v4 issue, but here it seems like folks (myself included) are experiencing it with v5.

**Comment by ZeldaZach** [comment]
@flomerboy Really? That's super weird. Will investigate v5. It's also full building. ETA on that is about 2 hours.

**Comment by flomerboy** [comment]
@ZeldaZach yeah if you look at the last screenshot, that's consistent with what I'm seeing after loading from v5 through oracle. I tried closing and reopening cockatrice, and loading from other URLs and reloading from v5. Nothing fixed it so far.

**Comment by ZeldaZach** [comment]
v5 isn't compatible with Oracle yet as far as I recall... Might be silently failing? In any case, I just looked at v5's contents that are publicly available and all sets were there as expected.

**Comment by flomerboy** [comment]
Just tried loading from default URL and it works, I can see ixalan and 2021 in there. 
Ah, I didn't realize v5 was not compatible with Oracle yet, that explains it.
Thanks for shipping a fast fix!

**Comment by jonidcrushfire** [comment]
Ok, I see that it is at least functional until a proper fix can be done, so I am closing this as completed for the issue while awaiting the changes.

Thank you for the speedy responses and work, guys!
