### ISSUE TITLE
Cards not in database

### ISSUE THREAD

**Issue by Aragotheplaneswalker** [Cockatrice/Cockatrice#4067]
<b>System Information:</b>
  

  
_______________________________________________________________________________________
Certain cards are not showing up in the database for me. In my pre-existing decks they are classified as "unknown" instead of the proper card types and images won't load
Cards I can't find include: Nim Deathmantle, Rhythm of the Wild, Necromancy, Cruel Celebrant, Anax, Hardened in the Forge, Heartwarming Redemption, Captain Lannery Storm, Tainted Peak, Prismatic Omen, Settle the Wreckage, Krosan Restorer, Pitiless Plunderer and much more. I think the entire Ixalan block, and Theros Beyond Death are completely missing
![Screenshot (24)](https://user-images.githubusercontent.com/69767724/90341939-f8969b00-dfd1-11ea-8522-6dba4116b5f3.png)
![Screenshot (25)](https://user-images.githubusercontent.com/69767724/90341951-12d07900-dfd2-11ea-8ebe-0672457075cb.png)
![Screenshot (26)](https://user-images.githubusercontent.com/69767724/90341957-2da2ed80-dfd2-11ea-8950-61f16b6baf73.png)
![Screenshot (27)](https://user-images.githubusercontent.com/69767724/90341973-4f9c7000-dfd2-11ea-9287-46f295a41b2d.png)

**Comment by ZeldaZach** [comment]
Please try running Oracle. Cockatrice > Check for Card Updates should refresh it. If not, please reopen and we'll dig further into this.
