### ISSUE TITLE
Bump CMakeLists.txt VERSION to 2.7.5

### ISSUE THREAD

**Issue by seanbruno** [Cockatrice/Cockatrice#4075]
Thank you for your work on the new release!  While working on the FreeBSD port update, I noticed the version string didn't get updated.

With the release of 2.7.5, the VERSION information should be bumped:

```
--- CMakeLists.txt.orig	2020-08-24 13:29:55 UTC
+++ CMakeLists.txt
@@ -37,7 +37,7 @@ endif()
 
 # A project name is needed for CPack
 # Version can be overriden by git tags, see cmake/getversion.cmake
-PROJECT("Cockatrice" VERSION 2.7.4)
+PROJECT("Cockatrice" VERSION 2.7.5)
 
 # Use c++11 for all targets
 set(CMAKE_CXX_STANDARD 11 CACHE STRING "C++ ISO Standard")

```

**Comment by tooomm** [comment]
That's often overlooked when the project is having releases... :(

Now with 2.7.5 released, it should even be bumped to the next version (probably 2.7.6) right away according to the contributing guidelines.
