### ISSUE TITLE
Move revealed card to bottom of library

### ISSUE THREAD

**Issue by smallonion1** [Cockatrice/Cockatrice#4079]
Playing Atla Palani EDH deck proves difficult in Cockatrice when her reveal until creature card ability is triggered. When you reveal top card, it seems the only way to move to the bottom of the library if it is not a creatures is to pull on to battle field and then move to bottom of the library. Is there a way to skip that middle step of dragging off of library pile? It would make these triggers a lot easier to pull off. 

**Similar Requests**

**Description of New Feature**

**Additional Context**

**Comment by ebbit1q** [comment]
Yes, simply use the play top card command, this is also useful for cascade and similar.
It is not possible to automate this process based off a certain parameter right now but this could be implemented client side or server side if needed. The default keybind for play top card is ctrl y, it moves the card to the stack, after which you can opt to keep going or use that card.

**Comment by ZeldaZach** [comment]
It seems you're trying to resolve the ability of Atla Palani a bit wrong. You should reveal the cards onto the stack, similar to Cascade, and then put them to the bottom. With Cascade, you put the cards onto the stack (CTRL + Y shortcut) and then move them all to the bottom in a random order. Hopefully this helps you resolve your gameplay issue!
