### ISSUE TITLE
Cockatrice crashes randomly during matches

### ISSUE THREAD

**Issue by programming-wolf** [Cockatrice/Cockatrice#4080]
<b>System Information:</b>
Device 1:
Client Version: 2.7.4 (2020-03-20)
Client Operating System: macOS 10.15
Build Architecture: 64-bit
Qt Version: 5.14.1
System Locale: en_DE
Install Mode: Standard

Device 2:
Client Version: 2.7.5 (2020-08-23)
Client Operating System: macOS 10.15
Build Architecture: 64-bit
Qt Version: 5.15.0
System Locale: en_DE
Install Mode: Standard
_______________________________________________________________________________________

Hi. We were simply playing matches against each other, when Cockatrice (apparently) randomly crashed. We didn't do anything specific, just clicking in the UI for regular game moves (drawing cards, drawing arrows, etc.). 

I have attached crash logs from the two devices that we used to play. 

[cockatrice_2020-09-03-212420_MetalBookPro.crash.txt](https://github.com/Cockatrice/Cockatrice/files/5170814/cockatrice_2020-09-03-212420_MetalBookPro.crash.txt)
[cockatrice_2020-09-03-213815_Tobiass-MacBook-Pro.crash.txt](https://github.com/Cockatrice/Cockatrice/files/5170817/cockatrice_2020-09-03-213815_Tobiass-MacBook-Pro.crash.txt)
[cockatrice_2020-09-03-210021_Tobiass-MacBook-Pro.crash.txt](https://github.com/Cockatrice/Cockatrice/files/5170818/cockatrice_2020-09-03-210021_Tobiass-MacBook-Pro.crash.txt)

If there is anything else that you need or that could help, let me know.

**Comment by ebbit1q** [comment]
The first crash and the other ones seem unrelated, but both are happening somewhere inside of qt itself, I'm not sure if we can do something about this without a way to reproduce it.

**Comment by programming-wolf** [comment]
Is there a way to upgrade QT on my machine? Or is it compiled into the software? I haven't programmed Qt myself yet, so I don't really know. One is a retain on a null reference, the other two are segmentation faults (I think). :-/ we weren't even able to reproduce them ourselves.

**Comment by ebbit1q** [comment]
QT will be packaged in the installer for mac and windows builds, you'd have to compile it yourself with the instructions from our wiki. Though if it no longer happens and it's not reproducible I'll have to close this ticket.

**Comment by programming-wolf** [comment]
Well, it's not reproducible, but it happened randomly the whole evening. :-/ haven't played since, but will keep an eye on it if it happens more often.

**Comment by ebbit1q** [comment]
If you get it to happen more often be sure to reopen the ticket! :slightly_smiling_face:
