### ISSUE TITLE
Running 2.7.0 or above on 10.11 El Capitan

### ISSUE THREAD

**Issue by jgiacobbi** [Cockatrice/Cockatrice#4082]
Hello,

I have an old macbook, running an old version of cockatrice. I can't connect to the host with the following issue:

```
Missing Features: 
     • 2.7.0_min_version
     • websocket
```

It looks like 2.7.0 is only available for 10.12 and above, but that version of OSX is not available to me. Is it possible to compile a 2.7.0 that will run under 10.11, or can I get a functional older version working by faking feature flags? Are there OS features that are required that are not available on 10.11?

**Comment by ctrlaltca** [comment]
Cockatrice doesn't require any feature that is missing in osx 10.11.
It's just hard for our limited team to be able to develop and provide packages for all the different os version.
We currently provide a package for 10.13 (the last non-metal osx) and a package for 10.15 (the latest).
You could build a package yourself for your os version using these instructions: https://github.com/Cockatrice/Cockatrice/wiki/Compiling-Cockatrice-(macOS)
We'll be glad to help if you experience any problem

**Comment by ZeldaZach** [comment]
Please feel free to reach out if you are still having problems!
