### ISSUE TITLE
Card preview window gets stuck and can't be removed

### ISSUE THREAD

**Issue by mikethebos** [Cockatrice/Cockatrice#409]
I have an issue on the latest Cockatrice build (OS X 10.10). Take a look at this screenshot: http://imgur.com/hBust2m

The window (highlighted in red) will not close without having to close Cockatrice itself. There is no close button on this window.

I am looking for help with this issue. I have contacted WoogerWorks about this issue. They told me to post my issue here. 

Thanks

**Comment by ZeldaZach** [comment]
This was fixed in #508 :)
