### ISSUE TITLE
Don't allow empty game titles/descriptions

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#4096]

**Comment by ebbit1q** [comment]
This is not possible to enforce, nor does it makes sense considering there are plenty of hard to see characters you can replace them with.
Why would empty descriptions be a problem anyway?

**Comment by tooomm** [comment]
>Why would empty descriptions be a problem anyway?

I think about it as reminder to not forget to put something up there and not wonder why nobody joins your game because you might not realize it right away. And in the end you waste time and recreate the game anyway because people come in and bring wrong decks or ask about the draft set because they only see modern or limited.

The idea was that it might help to improve the environment for both - hosts looking for players and users looking for games. Empty description games don't help either of them.
And if somebody really needs to, he can put a dot in there for whatever reason and it's ok.

**Comment by ebbit1q** [comment]
I often make private lobbies without title, it doesn't matter in that case

**Comment by ZeldaZach** [comment]
I find this to be moot honestly. I see no reason for this change.

**Comment by tooomm** [comment]
You're probably right. Convinced :)
