### ISSUE TITLE
ZNR Flip lands don't work from deck.

### ISSUE THREAD

**Issue by esotericantonym** [Cockatrice/Cockatrice#4098]
<b>System Information:</b>
  

  
_______________________________________________________________________________________

  
ZNR Flip lands from your deck don't have an option to attach to flip side, but ones created as a token do.
![bla](https://user-images.githubusercontent.com/71231135/93026672-c9c21380-f5d5-11ea-8c53-c3157225ce65.png)
Cockatrice Ver. 2.7.5 Oracle Ver. 2.7.5

**Comment by ebbit1q** [comment]
I'm unable to replicate this issue, could you please include your full system information and log by copying and pasting the entry in help>view debug log in the way the ticket template asks you to, please?

**Comment by ebbit1q** [comment]
I noticed in your chat window the card is called clearwater pathway // murkwater pathway, the card in cockatrice is just called clearwater pathway. You should replace it to solve the issue.

**Comment by ZeldaZach** [comment]
This is a known issue with the spoiler options for Zendikar. Spoilers aren't always perfect, and this was one of the bugs we encountered this time around. If you update using Oracle, they should work the same as any other flip card.
