### ISSUE TITLE
Error 0xc000007b

### ISSUE THREAD

**Issue by seska588** [Cockatrice/Cockatrice#4100]
<b>System Information:</b>
  

   
_______________________________________________________________________________________

   

Hello, I have had Cockatrice installed on my computer for years now. When i tried using it a few weeks ago, it gave me this error, right away as I tried to open it. I have tried everything I could, including installing and reinstalling, numerous times. I am using windows 10 home, 64 bit.

**Comment by tooomm** [comment]
Some more infos can be found starting in https://github.com/Cockatrice/Cockatrice/issues/2389#issuecomment-686906059.

**Comment by seska588** [comment]
I legit have no idea what happened, but the issue fixed itself.

**Comment by ebbit1q** [comment]
would it be fine to close this issue then?

**Comment by seska588** [comment]
yes
