### ISSUE TITLE
Remove secret card from opponent's deck

### ISSUE THREAD

**Issue by sbheinric** [Cockatrice/Cockatrice#4104]
Cards like Praetor's Grasp require removing a facedown card from opponent's deck.  This would be easy to do if you could offer the ability to reveal a modifiable deck to opponent so they can remove a card facedwon as if you were doing a tutor. It's a popular card in commander but nobody has time to play entire deck facedown.

**Comment by ebbit1q** [comment]
duplicate of https://github.com/Cockatrice/Cockatrice/issues/625 please comment on existing tickets instead of making a new one
