### ISSUE TITLE
Is the search bar compatible with non-English characters?

### ISSUE THREAD

**Issue by Ranshen** [Cockatrice/Cockatrice#4106]
When i try to make a localized card database for mtg, everything is all right except the search bar. I cant search for cards with non-English characters such as Chinese. 
I have attached the screenshots.

![Snipaste_2020-09-25_02-55-50](https://user-images.githubusercontent.com/20995471/94187542-a9019400-feda-11ea-883e-af1cd606c52c.png)

**Comment by ebbit1q** [comment]
unfortunately the card database itself is only ascii characters meaning that it doesn't distinguish between cards that are only using nonlatin characters. see https://github.com/Cockatrice/Cockatrice/issues/2330 https://github.com/Cockatrice/Cockatrice/issues/3360
better support for cards in other languages would require the id system mentioned here
for now you should consider only translating the card arts using the `https://api.scryfall.com/cards/!setcode_lower!/!set:num!/!sflang!?format=image&face=!prop:side!` template from here https://github.com/Cockatrice/Cockatrice/wiki/Custom-Picture-Download-URLs#example-urls

**Comment by ebbit1q** [comment]
would be fixed by https://github.com/Cockatrice/Cockatrice/issues/2545
