### ISSUE TITLE
server welcome message gets scrolled up by backlog messages

### ISSUE THREAD

**Issue by ebbit1q** [Cockatrice/Cockatrice#4110]
the server leaves a first message to welcome players to the server in the chat, unfortunately this will be obscured by the backlog of "missed messages" that are placed in the chat afterwards.
it'd be preferable to simply place the welcome message after the backlog so it's more visible

**Comment by Yashs911** [comment]
Hi @ebbit1q  I would like to work on this. If you provide a detailed explanation then it would be great.

**Comment by ebbit1q** [comment]
here is a picture of the current look, as you can see the message in green on the top would be obscured if you didn't make the widget bigger
![image](https://user-images.githubusercontent.com/36401181/94430912-ea24cd00-0194-11eb-94e7-b414afbe0778.png)
the code that manages this tab is here https://github.com/Cockatrice/Cockatrice/blob/master/cockatrice/src/tab_room.cpp

**Comment by Yashs911** [comment]
@ebbit1q Thanks for assigning this issue. But I am new to open source and I don't think I would be able to solve this issue.

**Comment by ebbit1q** [comment]
in what way would we be able to help you get more acquainted with open source development?

**Comment by ebbit1q** [comment]
if you have a few simple questions you can ask them directly through our discord or gitter

**Comment by ZeldaZach** [comment]
Hey @Yashs911 if you're looking for some suggestions on how to solve this, consider looking at pushing the server messages to the end of the stack. It might just be simply moving https://github.com/Cockatrice/Cockatrice/blob/master/common/server_protocolhandler.cpp#L666 to after the for loop. Feel free to experiment around, though! Let us know if you have any Qs on [Discord](https://cockatrice.us/discord) :)

**Comment by Yashs911** [comment]
@ZeldaZach I am using windows so how to check the changes in windows?

**Comment by ebbit1q** [comment]
You'd have to set up the development environment of your choice to clone our git repository, make the changes, test them, then open a pull request.
Github provides excellent resources on how to make pull requests, the way you make the changes themselves is specific to the tools you use but any IDE will provide you a guide on how to use it with github.

**Comment by ebbit1q** [comment]
check our contributing guidelines https://github.com/Cockatrice/Cockatrice/blob/master/.github/CONTRIBUTING.md our compile instructions https://github.com/Cockatrice/Cockatrice/wiki/Compiling-Cockatrice and github's introduction course https://lab.github.com/
