### ISSUE TITLE
[Raspberry Pi] Cockatrice app loses focus on some game events

### ISSUE THREAD

**Issue by knitknit** [Cockatrice/Cockatrice#4119]
Client Version: 2.7.6-custom(45cbdad) (2020-08-24)
Client Operating System: Raspbian GNU/Linux 10 (buster)
Build Architecture: ARM
Qt Version: 5.11.3
System Locale: en_US
Install Mode: Standard
_______________________________________________________________________________________

This has been happening for a little while now, just getting around to filing a bug for it. Whenever I start a game, for some events (turn change, card played, etc.) the Cockatrice window flashes in the top bar and then loses focus - meaning the keyboard shortcuts no longer work, since Cockatrice isn't "selected" essentially. It's easy enough to click in with the mouse but mildly annoying.

Will pay closer attention next time on what specific events cause this to happen and will update with more info.

**Comment by ebbit1q** [comment]
which window manager are you using? I suspect it's causing this on certain notifications

**Comment by knitknit** [comment]
Thanks @ebbit1q ! It's LXDE.

Non-exhaustive list of events that caused problems:
- Set life (self) with shortcut - sometimes
- Rolling die (self) - sometimes
- Setting annotation on card (self)
- Setting counter on card (self)

Did not cause problems:
- Opponent clicks "ready to start", game starts
- Rolling die (self or opponent)
- Setting life (opponent)
- Adding or removing a single counter from right-click menu

The only pattern I've seen so far is any event for which a dialog box needs to come up (setting life, rolling die, setting annotation, setting counters all have this attribute - you need to enter text).
- Drawing card (opponent)

**Comment by ebbit1q** [comment]
this isn't a problem with cockatrice but with lxde in that case, you should figure out which window gets focus after closing one and if it properly implements window hints like modal windows, I suspect you're using an older version of lxde and this'd be fixed in a more recent version. closing this issue as not our bug.
