### ISSUE TITLE
Right clicking library can place top card on battlefield.

### ISSUE THREAD

**Issue by rickclops** [Cockatrice/Cockatrice#4128]
<b>System Information:</b>
Client Version: 2.7.5 (2020-08-23)
PictureLoader: [card:  "Reliquary Tower"  set:  "C20" ]: Picture found on disk.
PictureLoader: [card:  "Pyromancer's Swath"  set:  "MMA" ]: Trying to load picture
PictureLoader: [card:  "Pyromancer's Swath"  set:  "MMA" ]: Picture found on disk.
PictureLoader: [card:  "Fog Bank"  set:  "MB1" ]: Trying to load picture
PictureLoader: [card:  "Fog Bank"  set:  "MB1" ]: Picture found on disk.
PictureLoader: [card:  "Goldnight Castigator"  set:  "SOI" ]: Trying to load picture
PictureLoader: [card:  "Goldnight Castigator"  set:  "SOI" ]: Picture found on disk.
PictureLoader: [card:  "Form of the Dragon"  set:  "FMB1" ]: Trying to load picture
PictureLoader: [card:  "Form of the Dragon"  set:  "FMB1" ]: Picture found on disk.
PictureLoader: [card:  "Homeward Path"  set:  "J17" ]: Trying to load picture
PictureLoader: [card:  "Homeward Path"  set:  "J17" ]: Picture found on disk.
PictureLoader: [card:  "Jinxed Idol"  set:  "TPR" ]: Trying to load picture
PictureLoader: [card:  "Jinxed Idol"  set:  "TPR" ]: Picture found on disk.
PictureLoader: [card:  "Thriving Isle"  set:  "JMP" ]: Trying to load picture
PictureLoader: [card:  "Thriving Isle"  set:  "JMP" ]: Picture found on disk.
PictureLoader: [card:  "Leyline of Anticipation"  set:  "M20" ]: Trying to load picture
PictureLoader: [card:  "Leyline of Anticipation"  set:  "M20" ]: Picture found on disk.
PictureLoader: [card:  "Felidar Sovereign"  set:  "MB1" ]: Trying to load picture
PictureLoader: [card:  "Felidar Sovereign"  set:  "MB1" ]: Picture found on disk.
PictureLoader: [card:  "Plains"  set:  "JMP" ]: Trying to load picture
PictureLoader: [card:  "Plains"  set:  "JMP" ]: Picture found on disk.
PictureLoader: [card:  "Idyllic Tutor"  set:  "PTHB" ]: Trying to load picture
PictureLoader: [card:  "Idyllic Tutor"  set:  "PTHB" ]: Picture found on disk.
PictureLoader: [card:  "Ponder"  set:  "C18" ]: Trying to load picture
PictureLoader: [card:  "Ponder"  set:  "C18" ]: Picture found on disk.
PictureLoader: [card:  "Transcendence"  set:  "TOR" ]: Trying to load picture
PictureLoader: [card:  "Transcendence"  set:  "TOR" ]: Picture found on disk.
PictureLoader: [card:  "Rugged Prairie"  set:  "2XM" ]: Trying to load picture
PictureLoader: [card:  "Rugged Prairie"  set:  "2XM" ]: Picture found on disk.
PictureLoader: [card:  "Fabled Passage"  set:  "M21" ]: Trying to load picture
PictureLoader: [card:  "Fabled Passage"  set:  "M21" ]: Picture found on disk.
addCounter: "Player 1" 0 "life"
addCounter: "Player 1" 1 "w"
addCounter: "Player 1" 2 "u"
addCounter: "Player 1" 3 "b"
addCounter: "Player 1" 4 "r"
addCounter: "Player 1" 5 "g"
addCounter: "Player 1" 6 "x"
addCounter: "Player 1" 7 "storm"
PictureLoader: cache fail for "_trice_card_back_137195"
QPixmap::scaled: Pixmap is a null pixmap
Server_AbstractUserInterface::playerRemovedFromGame(): gameId = 1
Server_CardZone destructor: "deck"
Server_CardZone destructor: "grave"
Server_CardZone destructor: "hand"
Server_CardZone destructor: "rfg"
Server_CardZone destructor: "sb"
Server_CardZone destructor: "stack"
Server_CardZone destructor: "table"
Server_Game destructor: gameId= 1
Player destructor: "Player 1"
GameScene::removePlayer name= "Player 1"
CardZone destructor:  "deck"
CardZone destructor:  "grave"
CardZone destructor:  "hand"
CardZone destructor:  "rfg"
CardZone destructor:  "sb"
CardZone destructor:  "stack"
CardZone destructor:  "table"
Server::removeClient: name= "Player 1"
closed session id: 0
Server::removeClient: removed 0x29837bdda20 ; 0 clients;  0 users left
Server_Room destructor
PictureLoader: cache fail for "_trice_card_back_222917"
GameScene::addPlayer name= "Kelderan"
GameScene::addPlayer name= "Clawps"
PictureLoader: cache fail for "_trice_card_back_278339"
QWindowsWindow::setGeometry: Unable to set geometry 1920x1054+0+29 (frame: 1938x1101-9-9) on QWidgetWindow/"MainWindowClassWindow" on "\\.\DISPLAY1". Resulting geometry: 1920x1051+0+29 (frame: 1938x1098-9-9) margins: 9, 38, 9, 9 minimum size: 852x1054 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=870,1101 maxtrack=0,0)
PictureLoader: cache fail for "_trice_card_back_278306"
Loaded from "C:/Users/Clops/AppData/Local/Cockatrice/Cockatrice/decks/Commander/rick zedruu commander.cod" - true
Deck was loaded - true
addCounter: "Kelderan" 0 "life"
addCounter: "Kelderan" 1 "w"
addCounter: "Kelderan" 2 "u"
addCounter: "Kelderan" 3 "b"
addCounter: "Kelderan" 4 "r"
addCounter: "Kelderan" 5 "g"
addCounter: "Kelderan" 6 "x"
addCounter: "Kelderan" 7 "storm"
addCounter: "Clawps" 0 "life"
addCounter: "Clawps" 1 "w"
addCounter: "Clawps" 2 "u"
addCounter: "Clawps" 3 "b"
addCounter: "Clawps" 4 "r"
addCounter: "Clawps" 5 "g"
addCounter: "Clawps" 6 "x"
addCounter: "Clawps" 7 "storm"
PictureLoader: cache fail for "_trice_card_back_77109"
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
CardDragItem: coordinate overflow: x = 101.78 , y = -453.743
CardDragItem: coordinate overflow: x = -17.5157 , y = -525.132
CardDragItem: coordinate overflow: x = 86.7503 , y = -331.629
PictureLoader: cache fail for "_trice_card_back_5071"
QPixmap::scaled: Pixmap is a null pixmap
PictureLoader: [card:  "Reclamation Sage"  set:  "2XM" ]: Trying to load picture
PictureLoader: [card:  "Reclamation Sage"  set:  "2XM" ]: Picture found on disk.
PictureLoader: cache fail for "_trice_card_back_4969"
PictureLoader: [card:  "Jarad's Orders"  set:  "RTR" ]: Trying to load picture
PictureLoader: [card:  "Jarad's Orders"  set:  "RTR" ]: Picture found on disk.
PictureLoader: cache fail for "_trice_card_back_4462"
PictureLoader: [card:  "Acidic Slime"  set:  "C20" ]: Trying to load picture
QPixmap::scaled: Pixmap is a null pixmap
PictureLoader: [card:  "Acidic Slime"  set:  "C20" ]: Picture found on disk.
PictureLoader: cache fail for "_trice_card_back_4360"
PictureLoader: [card:  "Hardened Scales"  set:  "CM2" ]: Trying to load picture
QPixmap::scaled: Pixmap is a null pixmap
PictureLoader: [card:  "Hardened Scales"  set:  "CM2" ]: Picture found on disk.
PictureLoader: cache fail for "_trice_card_back_4259"
PictureLoader: [card:  "Inscription of Abundance"  set:  "PZNR" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Inscription of Abundance"  set:  "PZNR" ]: Requested set property ( "muid" ) for Url template ( "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Inscription of Abundance"  set:  "PZNR" ]: Trying to load picture
PictureLoader: [card:  "Inscription of Abundance"  set:  "PZNR" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Inscription of Abundance"  set:  "PZNR" ]: Trying to download picture from url: "https://api.scryfall.com/cards/dd282787-3fc5-472d-b0fd-7c83720eccc9?format=image&face=front"
PictureLoader: [card:  "Inscription of Abundance"  set:  "PZNR" ]: following redirect: "https://c1.scryfall.com/file/scryfall-cards/large/front/d/d/dd282787-3fc5-472d-b0fd-7c83720eccc9.jpg?1601002674"
PictureLoader: [card:  "Inscription of Abundance"  set:  "PZNR" ]: Image successfully downloaded from  "https://c1.scryfall.com/file/scryfall-cards/large/front/d/d/dd282787-3fc5-472d-b0fd-7c83720eccc9.jpg?1601002674"
PictureLoader: [card:  "Satyr Wayfinder"  set:  "C20" ]: Trying to load picture
PictureLoader: [card:  "Satyr Wayfinder"  set:  "C20" ]: Picture found on disk.
QPixmap::scaled: Pixmap is a null pixmap
PictureLoader: [card:  "Swamp"  set:  "JMP" ]: Trying to load picture
PictureLoader: [card:  "Swamp"  set:  "JMP" ]: Picture found on disk.
PictureLoader: cache fail for "_trice_card_back_76108"
PictureLoader: cache fail for "_trice_card_back_278304"
CardDragItem: coordinate overflow: x = 103.58 , y = -692.345
CardDragItem: coordinate overflow: x = -18.9047 , y = -363.52
PictureLoader: cache fail for "_trice_card_back_4057"
QPixmap::scaled: Pixmap is a null pixmap
  

  
_______________________________________________________________________________________

  
If I'm in a 2 player game and I right click the library, then left click in the battlefield, stack zone or hand zone, it moves a card from the top of my library to that zone.

It shouldn't move anything when I right click the library and bring up the library menu then click somewhere that isn't on the menu.

**Comment by rickclops** [comment]
guess this has already been reported

**Comment by ebbit1q** [comment]
duplicate of https://github.com/Cockatrice/Cockatrice/issues/3935 please add your comments or reports on that ticket instead
