### ISSUE TITLE
Ability to specify local card image filename in custom sets

### ISSUE THREAD

**Issue by 8bitbanana** [Cockatrice/Cockatrice#4135]
**Similar Requests**
Couldn't find any similar requests.

**Description of New Feature**
There currently isn't the ability to specify a custom filename for Cockatrice to search for when grabbing a card's image from disk. 

**Additional Context**
Designers like Magic Set Editor often trim punctuation from card image names, meaning commas and slashes get trimmed.

One current workaround is to rename the images to match the card names, adding commas and stuff back in, but this is clunky and doesn't work for slashes and other invalid filename characters. Another is to use "file://" links in picUrl, but these have to be absolute paths, unsuitable for sharing.

It's small, but it seems amiss to have no control over Cockatrice searching for card images on disk. I might also be missing something obvious. Thanks for any help!

**Comment by ebbit1q** [comment]
Cockatrice of course removes any illegal characters from image file names, to be specific it removes the following from the full card name: ` // ` `:` `"` `?` and then it replaces `/` with a space ` `

You should simply follow the same pattern and it'll work just fine, note that everything else including capitalization must match.

You can see where it does this in the function here: https://github.com/Cockatrice/Cockatrice/blob/master/cockatrice/src/carddatabase.cpp#L269

**Comment by tooomm** [comment]
Maybe also something to consider in combination with https://github.com/Cockatrice/Cockatrice/issues/1740
