### ISSUE TITLE
User Timer

### ISSUE THREAD

**Issue by andreacosta** [Cockatrice/Cockatrice#4145]
**Description of New Feature**
Add a timer for each player like MTGO, this could be very helpful for tournaments.

**Additional Context**
Each time a player pass the turn the other player timer start.

**Comment by tooomm** [comment]
What about actions that other players perform within your turn?
Any complex interaction or thinking time how to react would still be all on your count as long as it happens in your turn.  

Cockatrice doesn’t know about priority, that’s why I’m not sure if this would be helpful. It would never be accurate. 
In paper magic there is just a total timer for the round in a tournament.

**Comment by ebbit1q** [comment]
In games of magic where you are allowed to interact a lot and perform many actions on other player's turns this doesn't make a lot of sense, maybe in other games a timer for your turn would work but enforcing a turn switch at the end of the timer sounds like a bad idea in general for a digital tabletop. I'm going to close this until we see a need for it after implementing #1740
