### ISSUE TITLE
Resizing filter widget behaves weirdly

### ISSUE THREAD

**Issue by ebbit1q** [Cockatrice/Cockatrice#4148]
> the dialog is now a lot wider, also considering the list of formats is arbitrary it could actually be longer
> ![image](https://user-images.githubusercontent.com/36401181/96749941-bd4a8b00-13cb-11eb-8e65-491f380fce3d.png)
> this shows some inconsistency with resizing the dialog, the left column has a spacer added while the right one does not.
> ![image](https://user-images.githubusercontent.com/36401181/96750302-17e3e700-13cc-11eb-822b-a7cd05f5537b.png)

**Comment by knitknit** [comment]
Sorry I didn't get around to this before the original PR was merged in - thanks @tooomm !
