### ISSUE TITLE
Choose a number or a name in secret

### ISSUE THREAD

**Issue by ShrewMaster** [Cockatrice/Cockatrice#4151]
When adding a note to a card, have an option to make that note public (to your opponents) or private. The card's owner should be able to switch between these modes.

There are currently four cards that require players to either secretly choose a player or a number. Wizards is about to print a fifth card with a similar effect in Commander Legends (Wheel of Misfortune). These cards require clunky methods to work in Cockatrice (e.g. tell the secret to a spectator). Since these kinds of effects will probably become more common in the future with the increase of casual and multiplayer play, I think it is important that Cockatrice addresses this gap. Adding the abovementioned feature to Cockatrice would fill this gap and allow these cards to be played as intended. Additionally, with this feature, players can add personal notes to their permanents without burdening or confusing their opponents with irrelevant details of the game state.

**Comment by ZeldaZach** [comment]
Hey @ShrewMaster this is a great feature idea, and we already have it ticketed over at #3278. You can follow the tracking over there.
