### ISSUE TITLE
Let specific tokens default to not being destroyed off-battlefield

### ISSUE THREAD

**Issue by CajunAvenger** [Cockatrice/Cockatrice#4161]
**Similar Requests**

**Description of New Feature**
Have specific tokens have "Destroy token when it leaves the battlefield" unchecked without needing to make them one at a time. This could key off either a property in tokens.xml (ex. `<permanent>1</permanent>`) or off the particular reverse-related script (ex `<reverse-related count="x" permanent="true">`).

**Additional Context**
This got brought up on Discord [here](https://cdn.discordapp.com/attachments/352634063980593153/775062469206868018/unknown.png) and this is the ticket for it.

**Comment by PhilippeSaner** [comment]
I'll second this suggestion; it would be very helpful for the custom set I'm working on.

**Comment by Tvpattack** [comment]
I will bump this, as this is something that would be greatly beneficial for the same reason PilippeSaner is mentioning
