### ISSUE TITLE
Cannot send to deckstats

### ISSUE THREAD

**Issue by edight** [Cockatrice/Cockatrice#4163]
<b>System Information:</b>
  

  
_______________________________________________________________________________________

   Trying to send decklist to deckstats and receiving error message "response from server cannot be parsed".  Updated to the latest cockatrice and am running windows.

**Comment by tooomm** [comment]
I can confirm the problem. The other external services still work.

```
Client Version: 2.7.5 (2020-08-23)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.12.6
```

CC: @deckstats

**Comment by deckstats** [comment]
Hi, this may be related to some changes we recently made to our deck pages. If you can point me to the relevant code I'd be happy to have a quick look.

**Comment by tooomm** [comment]
Thanks for your fast response and help @deckstats. Highly appreciated!
The relevant file is this one: https://github.com/Cockatrice/Cockatrice/blob/master/cockatrice/src/deckstats_interface.cpp

**Comment by deckstats** [comment]
Alright, I made some changes on our end so this should be working again now!

**Comment by ebbit1q** [comment]
thanks! it works again!
