### ISSUE TITLE
Use [Ctrl+Shift+S] as a Shortcut to "Save deck as..."

### ISSUE THREAD

**Issue by Glitchy-Tozier** [Cockatrice/Cockatrice#4174]
**Description of New Feature**
Use Ctrl+Shift+S as a Shortcut to "Save deck as..."

**Additional Context**
Ctrl+S already is used for "Save deck"
We could also implement the other established saving-Shortcut. A lot of software uses [Ctrl+Shift+S] as a Shortcut to "Save as...". A few examples: Libreoffice, most other text-editors, Blender, a lot of video-editing software, etc.
- Most applications use this shortcut.
- It doesn't seem to be used for something else in the deck-editor

So why not use it?

**Comment by ZeldaZach** [comment]
Seems very reasonable

**Comment by Fenrirthviti** [comment]
PR submitted for this, #4188
