### ISSUE TITLE
Linux&Flatpak: Saving a deck doesn't add the file-extention.

### ISSUE THREAD

**Issue by Glitchy-Tozier** [Cockatrice/Cockatrice#4176]
<b>System Information:</b>

Client Version: 2.7.5 (2020-08-23)
Client Operating System: KDE Flatpak runtime
Build Architecture: 64-bit
Qt Version: 5.15.1
System Locale: en_GB
Install Mode: Standard

Theme changed: "Default"
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
Language changed: ""
main(): starting main program
main(): MainWindow constructor finished
Spoilers Disabled
main(): ui.show() finished
Startup: found config with current version
CardDatabase::loadCardDatabases start
[CockatriceXml4Parser] Trying to parse:  "/home/florian/.var/app/io.github.Cockatrice.cockatrice/data/Cockatrice/Cockatrice/cards.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
[CardDatabase] loadCardDatabase(): Path = "/home/florian/.var/app/io.github.Cockatrice.cockatrice/data/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 21696 Sets= 506
[CockatriceXml4Parser] Trying to parse:  "/home/florian/.var/app/io.github.Cockatrice.cockatrice/data/Cockatrice/Cockatrice/tokens.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
[CardDatabase] loadCardDatabase(): Path = "/home/florian/.var/app/io.github.Cockatrice.cockatrice/data/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 22179 Sets= 506
[CardDatabase] loadCardDatabase(): Path = "/home/florian/.var/app/io.github.Cockatrice.cockatrice/data/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 22179 Sets= 506
CardDatabase::loadCardDatabases success
_______________________________________________________________________________________

  
<b>Bug:</b>
The Title is pretty self-explanatory.
This might not be caused by Cockatrice but rather Flatpak itself.
Here's the Flatpak-issue that's targeting the bug: https://github.com/flatpak/xdg-desktop-portal-gtk/issues/191 , I just thought maybe I should inform you guys about this.
_______________________________________________________________________________________
This is especially annoying in software like this (Cockatrice, I love this client btw.), because here more uncommon file-types are used. If this bug happens in telegram for example, I know that I can rename the file to add ".jpg".
But for Cockatrice, I had to **look up** what file-extension it uses, just so I could re-open my (extention-less) file.

**Comment by tooomm** [comment]
Done
