### ISSUE TITLE
Cockatrice Stops Responding Mac Big Sur OS

### ISSUE THREAD

**Issue by MarcusTrevino** [Cockatrice/Cockatrice#4186]
<b>System Information:</b>

MacOS Big Sur 11.0.1
_______________________________________________________________________________________

I installed MacOS Big SUr 11.0.1 this evening.
After installing, cockatrice application would stop responding when I attempted to open the app.

I installed the latest MacOS version and when I attempt to deploy it, MacOS rejects because it cannot confirm that malware does not exist on the file.

My other applications are working fine.  As far as I can tell, only Cockatrice is having an issue.

**Comment by tooomm** [comment]
Hallo @MarcusTrevino! Thanks for opening this.

I've some questions for you:
- Which mac do you use? The super new models with Apples own M1 chip? Or the older ones with Intel processors?
- Can you give us the exact file name of the dmg binary you used for installation?
And where did you download it from?

**Comment by ebbit1q** [comment]
did you try the beta? https://github.com/Cockatrice/Cockatrice/releases
are you able to run the file anyway using the steps described here? https://github.com/Cockatrice/Cockatrice/wiki/Frequently-Asked-Questions#developer-cannot-be-verified-pop-up-message-macos

**Comment by MarcusTrevino** [comment]
Hi.  I was able to make it work by bypassing the security feature.  So Cockatrice is back to working now.  Thank you

**Comment by MarcusTrevino** [comment]
For clarification, after installing a new OS on my macbook pro 17, the old installation stopped responding and froze when I attempted to start it.   I installed the latest version for MacOS and I encountered a pop up window that prevented cockatrice from starting.

To remedy the problem, I followed the steps to start the application and bypass the security protocol.  Cockatrice then worked as normal.

**Comment by ebbit1q** [comment]
Thanks for clarifying

**Comment by tooomm** [comment]
Which version of Cockatrice did you exactly install in the end? @MarcusTrevino 
Can you copy the first lines of the debug log (in the help menu) here, please?

**Comment by MarcusTrevino** [comment]
Client Version: 2.7.5 (2020-08-23)
