### ISSUE TITLE
Running on beta channel gives you an update loop

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#4187]
If you are using the most recent beta release (2.7.6-beta.2) and search for new updates, it finds the same version you are already running and tells you a new version is available nonetheless.

If you run the latest stable (2.7.5), the same process gives you a "no newer versions found" message.

Confirmed on Windows and Linux.

**Comment by ebbit1q** [comment]
works as intended now
![image](https://user-images.githubusercontent.com/36401181/106422575-20ce6500-645f-11eb-82c0-def9b8f9db59.png)
