### ISSUE TITLE
Kamigawa Flip Cards Upside Down

### ISSUE THREAD

**Issue by D0nV170** [Cockatrice/Cockatrice#4198]
<b>System Information:</b>
  
Client Version: 2.7.6-beta.2 (2020-11-23)
  
_______________________________________________________________________________________

  
The art for the Kamigawa flip cards is upside down. Rune-Tail, Kitsune Ascendant's art shows it as Rune-Tails Essence as well as all of the others. I double checked. I have recently updated the client, updated card database and then deleted downloaded images and it still shows the cards as their flipped version, for both names.

**Comment by ebbit1q** [comment]
Seems like something I missed in my changes to this pr https://github.com/Cockatrice/Cockatrice/pull/4162
