### ISSUE TITLE
Mac OS 11.0.1 (Big Sur) open issue

### ISSUE THREAD

**Issue by Cthielking** [Cockatrice/Cockatrice#4205]
With the most recent version of Cockatrice installed it will not open on my Mac which I recently updated to OS 11.0.1 (Big Sur).

**Comment by ebbit1q** [comment]
have you seen this faq entry? https://github.com/Cockatrice/Cockatrice/wiki/Frequently-Asked-Questions#developer-cannot-be-verified-pop-up-message-macos

**Comment by Cthielking** [comment]
I have been annoyed by that stupid feature of Mac OS for years, but this problem is not related to it.  I've been using Cockatrice for about a year on my Mac, and after updating to the new OS it freezes during start up and wont open.

**Comment by tooomm** [comment]
Can you please provide complete information for a better understanding? @Cthielking 

May I wrap up what I understand so far:
You had Cockatrice running without issues, you then updated your Mac to Big Sur and the old Cockatrice installation suddenly did not open anymore. You did not update Cockatrice and did not do any other changes to your system. Everything else works as expected.

1. Which *exact* version of Cockatrice have you been using?
2. Which version of Mac did you use before upgrading?
3. Do you get any error or hint displayed when you try to open Cockatrice?
4. I'm sure you tried to uninstall and reinstall with a fresh download of version 2.7.5 (or even 2.7.6-beta.2)?

**Comment by tooomm** [comment]
@Cthielking how did you solve your issue?

We love to hear what went wrong or how you dealt with it.

**Comment by Cthielking** [comment]
Hi sorry, in pandemic times I only sporadically check my emails...

I solved my issue by completely uninstalling and reinstalling Cockatrice.
But to more fully answer your questions from before

1) I was using the most recent release of Cockatrice which I believe was
the same then as no, 64-bit Version 2.7.5 (2020-08-23)
2) I had been on the most recent update of Mac OS X before updating to OS 11
3) No it just stalled out.  It wouldn't freeze my computer, it was almost
as if my computer thought the program was operating correctly, but when I
clicked on the Cockatrice app icon in my dock it would blink, then nothing
would appear.
4) Yes, ultimately this is what worked.  I had been worried that doing this
would cause me to loose all of my decks saved on the platform, but in the
end they all made it through to the new install.

Cheers,
Chris Thielking
He/Him/His
www.ChrisThielking.com
Chris.Thielking@Gmail.com
585 . 749 . 2939

**Comment by tooomm** [comment]
Thanks for coming back to us. I happily close this issue then.
Sometimes it's as easy as a fresh install and nobody can explain what went wrong. :)

<br>

Uninstalling the Cockatrice client will never change any data saved on a server.
