### ISSUE TITLE
Shortkeys not working on Mac

### ISSUE THREAD

**Issue by fbroma** [Cockatrice/Cockatrice#4208]
Hi guys, I am running cockatrice ver.2.7.3 beta on OSX Catalina 10.15.4 and am having problems getting my preselected shortkeys to work in player vs. player mode. I initially went into a one-player mode and changed the shortkeys to functions like add/remove a green counter and increase/decrease power/toughness to suit my needs. I then tested them out in one-player mode where they worked fine. The problem arises when I go into player-vs-player when they no longer work, meaning nothing happens when I press the keys. Thanks.

**Comment by ebbit1q** [comment]
Have you checked if the chat is focused? The chat bar uses some of the keybinds, you can unfocus it by pressing esc.

Also 2.7.3 was released last march and had a few bugs, you can check for the most recent version here https://github.com/Cockatrice/Cockatrice/releases

**Comment by fbroma** [comment]
That fixed it. Thank you!


Sent from Yahoo Mail for iPhone


On Tuesday, December 8, 2020, 3:12 PM, ebbit1q <notifications@github.com> wrote:




Have you checked if the chat is focused? The chat bar uses some of the keybinds, you can unfocus it by pressing esc.

Also 2.7.3 was released last march and had a few bugs, you can check for the most recent version here https://github.com/Cockatrice/Cockatrice/releases

**Comment by tooomm** [comment]
What fixes it? The new version or unfocusing the chat? :)

**Comment by fbroma** [comment]
Not sure. I updated the client and changed shift to control key as the former was selecting the chat without highlighting it.


Sent from Yahoo Mail for iPhone


On Tuesday, December 8, 2020, 5:54 PM, tooomm <notifications@github.com> wrote:




What fixes it? The new version or unfocusing the chat? :)
