### ISSUE TITLE
Wrong Image for [[Wheel of Fortune]]

### ISSUE THREAD

**Issue by SmashPortal** [Cockatrice/Cockatrice#4212]
<b>System Information:</b>
Log not applicable
  
Windows 10 Education Edition 64x
Client Version: 2.7.5 (2020-08-23)
  
_______________________________________________________________________________________
The image for [[Wheel of Fortune|G10]] has been replaced with the image for [[Wheel of Fortune|VMA]].
I noticed this because I have all MTGO sets disabled, but Cockatrice was still loading the Vintage Masters printing.
I checked my images folder for G10 and the image for Wheel of Fortune was the Vintage Masters version.

**Comment by ebbit1q** [comment]
can you please include your log where it downloads the image in your issue?

**Comment by SmashPortal** [comment]
> can you please include your log where it downloads the image in your issue?

The reason I said the log wasn't applicable is because I don't have the log from when it downloaded. I tried multiple things to fix it before I realized it was saved as that image. This meant that the log from when I downloaded the card was overwritten (as far as I'm aware).

When I download card updates, this is the download URL: https://www.mtgjson.com/files/AllPrintings.json.xz

**Comment by ebbit1q** [comment]
you'll need to delete the saved card image in order to download it again, you can either delete all images in settings>card sources or navigate to your image directory and then delete downloadedPics/[setcode]/Wheel of Fortune.jpg.

**Comment by SmashPortal** [comment]
That fixed it.

**Comment by ebbit1q** [comment]
you're welcome
