### ISSUE TITLE
Quick and easy response system

### ISSUE THREAD

**Issue by TheRealJoci** [Cockatrice/Cockatrice#4217]
The reason behind this request is that I have been playing a lot of EDH but without voice chat, and only by playing and typing. There really isn't a quick and fluid way to communicate with an opponent if you have anything in response or that you're thinking or that you're fine with the resolving the stack. Let's be real, the chat is not a suitable way of interacting for such a basic need, it's simply too slow and too clunky. A much more suitable system would be to implement something like a version of "Smart Ping" that League of Legends has. For example you could set it to trigger while not on an object, or for example only on a free place on the battlefield, on a right click and drag to emote that would maybe be "RESOLVE", "RESOLVE WHOLE STACK", "THINKING", "IN RESPONSE" or really any variation.
In my opinion that would greatly improve the fluidity of the playing experience and quality of life for people without a way to communicate through voice chat.

**Comment by tooomm** [comment]
A not so elegant looking version of a "chat wheel with shortcuts" are chat macros in Cockatrice.
You configure them in settings and access them with a simple right click on the battlefield and selecting `Say`.

They are even accessible via hotkeys (`CTRL+1`,`CTRL+2` etc.).

I guess that's what you are looking for.

**Comment by TheRealJoci** [comment]
I wouldn't say "not so elegant" but rather not in any way faster that clicking on chat and writing "k". I don't think that the way chat macros are implemented right now is fluid enough or quick to access, but it brings an interesting possibility. Without complicating too much, the same way that the "ping wheel" would function, why not just let the user have a possibility of modifying the drop down menu that right click opens with personalized chat macros?
![Artboard – 1](https://user-images.githubusercontent.com/52679614/103458192-fd03ec00-4d05-11eb-952d-f65494272372.png)
It's not a professional prototype, but you can see what I mean.

**Comment by ebbit1q** [comment]
this menu exists, it's called "say" and is visible in your mockup

**Comment by TheRealJoci** [comment]
Yeah it is, I know how to use it, but it is too far down the drop-down menu to be used quickly and easily. The thing is it should be the first thing there or at least that's my opinion...

**Comment by tooomm** [comment]
Any objections in reordering the menu when right clicking on the battlefield?

**Comment by ZeldaZach** [comment]
It would have to be a really good reason to reorder, as the menu has remained the same for quite a long time, and negative backlash is something I'd like to avoid.

**Comment by ZeldaZach** [comment]
I'm gonna close this as a "works as expected"
