### ISSUE TITLE
Having a hard time adding custom "sets" like issue #3019

### ISSUE THREAD

**Issue by MSGTNP** [Cockatrice/Cockatrice#4218]
Don't know If this is the right place but I've been trying to add a custom set I've made for myself and my friend to use but after making it with only one card for now, I tried adding it to Cockatrice and gotten the quote "the new sets/cards have been added successfully. Cockatrice will now reload the card database." yet when I looked for it, I could not find it for the life of me so I can only assume I messed up somewhere. With that said, can someone look at it for me and tell me what's wrong? Normally I'd just look up a custom card/deck but I can't find any.
![Screenshot 2021-01-04 23 51 25](https://user-images.githubusercontent.com/76962790/103559061-e1146c00-4ef8-11eb-97f0-b6a782b7214e.png)

download link for my XML file
[https://mega.nz/file/gGhAyBLZ#VSo17Piax6aZMFJnDeQRP-pt8xnnEextR960ctU4iH0](url)

**Comment by ebbit1q** [comment]
did you follow the steps outlined here to find problems in your xml file? https://github.com/Cockatrice/Cockatrice/wiki/Custom-Cards-&-Sets#diagnosing-problems-in-your-xml-file
I noticed your file contains an unescaped &, is missing the <sets> tags and has the wrong set for the card, here is the corrected file: 
[SOTSPR1.xml.txt](https://github.com/Cockatrice/Cockatrice/files/5766432/SOTSPR1.xml.txt)

**Comment by MSGTNP** [comment]
> did you follow the steps outlined here to find problems in your xml file? https://github.com/Cockatrice/Cockatrice/wiki/Custom-Cards-&-Sets#diagnosing-problems-in-your-xml-file
> I noticed your file contains an unescaped &, is missing the `<sets>` tags and has the wrong set for the card, here is the corrected file:
> [SOTSPR1.xml.txt](https://github.com/Cockatrice/Cockatrice/files/5766432/SOTSPR1.xml.txt)

I followed it to the best of my ability but I clearly missed something. Thank you though for fixing it for me! If It's not too much trouble, do you I mind if I bother you a little for help if I need it?

**Comment by ebbit1q** [comment]
what part of these steps do you think needs additional clarification?

**Comment by MSGTNP** [comment]
> what part of these steps do you think needs additional clarification?

Exactly how do you do split cards correctly? And........how do you fix images? For some reason, even though they have their own direct PNG url, two of my cards keep sharing the same image. My only guess is that they share a same word and the program is getting confused.

Also, why isn't there a warning in the wiki regarding <text></text> ? You apparently break the code If you type in too much between the  <text></text> .

**Comment by ebbit1q** [comment]
there is no difference between normal cards and split cards, just fill in the properties, mtg cards use a `//` for splitting the mana cost of both halves for example, but it's entirely arbitrary.

if an image somehow got switched and has been downloaded you'll have to remove it before your changes to the image url are noticed. you can do so by deleting all downloaded images in settings>card sources or finding it in your images location at downloadedPics/[setcode]/[imagename]. however it is possible that two cards will share the same name and thus load the same image from disk if you use a name that is the same if you remove all signs and other stuff that isn't a number, letter or space. also on certain file systems they will not be case sensitive.

no such limitation exists regarding the text tags, but note that some characters have to be escaped in html/xml files, here is a full list:
-   " is replaced with &quot;
-   & is replaced with &amp;
-   < is replaced with &lt;
-   > is replaced with &gt;
