### ISSUE TITLE
No Mac Download

### ISSUE THREAD

**Issue by nickbucchia123** [Cockatrice/Cockatrice#4234]
<b>System Information:</b>
  

  
_______________________________________________________________________________________

When I click on the Mac download on Cockatrice's homepage, nothing is downloaded. I just updated my computer to work with the new update, what should I do?

**Comment by ebbit1q** [comment]
get the latest version from our release page here https://github.com/Cockatrice/Cockatrice/releases/latest

**Comment by tooomm** [comment]
@nickbucchia123 you can now go to our webpage (https://cockatrice.github.io/) again to download macOS versions right away. I fixed it.
Let us know if it works for you.

Thanks for the report! ❤️
