### ISSUE TITLE
tokens are moved one slot to the left when moved

### ISSUE THREAD

**Issue by adrienrapper** [Cockatrice/Cockatrice#4235]
<b>System Information:</b>
  

  
_______________________________________________________________________________________

  

each token move to the left a little bit

**Comment by tooomm** [comment]
We are sorry, but you have to elaborate a bit more about your issue.
When does it happen? How can we reproduce it? Probably a screenshot is helpful as well.

Important: Please provide the details about your Cockatrice version and your operating system as asked.

**Comment by omegaula** [comment]
Version 2.8.0, windows, 64-bit

Steps to repro:
- create a names token eg. "cmd dmg"
- put it into battlefield right to the right of another card

Expected:
- token ends up to the right of said card

Actual:
- token is put on top of said card

**Comment by ebbit1q** [comment]
perplexing, never noticed this before. is this a regression?

**Comment by ZeldaZach** [comment]
Sounds like a regression to me, but in any case we need to address it

**Comment by jonschoning** [comment]
I've never seen it before either until i got latest main

**Comment by ebbit1q** [comment]
I think this commit is a likely source https://github.com/Cockatrice/Cockatrice/commit/a0deb73df652b3cd76ee521761624e4869976402

**Comment by ebbit1q** [comment]
compared build from this commit to the one before it, can confirm it introduced the issue

**Comment by adrienrapper** [comment]
> We are sorry, but you have to elaborate a bit more about your issue.
> When does it happen? How can we reproduce it? Probably a screenshot is helpful as well.
> 
> Important: Please provide the details about your Cockatrice version and your operating system as asked.

i use version 2.8.0 64 bit
i am on Windows 10 Professionnel ver 20H2 19042.746

u can reproduce while use "start local game" then try making an token and put it in the middle, u will see that he move a slot to the left

**Comment by tooomm** [comment]
Thanks for coming back to this @adrienrapper.
In the meantime we found the causing regression already and fixed it. Though, there is no new release with the changes included yet. I suggest you switch to `Beta Releases` in settings and check for Cockatrice updates from time to time. It will be there first!

**Comment by ebbit1q** [comment]
sure, I'll make a beta

**Comment by adrienrapper** [comment]
> Thanks for coming back to this and reporting the issue in the first place, @adrienrapper.
> In the meantime we found the causing regression already and fixed it. Though, there is no new release with the changes included yet. I suggest you switch to `Beta Releases` in settings and check for Cockatrice updates from time to time. It will be there first!

you're welcome!
and thanks you too for fix it!!
regards
