### ISSUE TITLE
update not on the aur

### ISSUE THREAD

**Issue by djpiper28** [Cockatrice/Cockatrice#4239]
<b>System Information:</b>
  
manjaro linux
  
_______________________________________________________________________________________

**Comment by ebbit1q** [comment]
we don't manage the aur, please message their maintainers instead.

**Comment by skwerlman** [comment]
assuming you are talking about the -git package. i just updated it

**Comment by tooomm** [comment]
CC: @FFY00

**Comment by FFY00** [comment]
Thanks for the ping! The new release notification got lost in my sea of github notifications :sweat_smile:

**Comment by djpiper28** [comment]
Thanks @FFY00 and @skwerlman
