### ISSUE TITLE
Installation stops at qtaudio_wasapi.dll

### ISSUE THREAD

**Issue by GiampaJP** [Cockatrice/Cockatrice#4240]
While installing new Cockatrice update, installation stops at this file.
![Immagine](https://user-images.githubusercontent.com/78563696/106946391-53ab7e00-6729-11eb-810f-b32b853391b7.png)

**Comment by ebbit1q** [comment]
Which os are you using?
Which download are you using?
What does it show if you click show details?

**Comment by GiampaJP** [comment]
Right :-) I'm using Windows 10, the download is the "Cockatrice v2.8.0". Below the details. If I "ignore" the fact is not able to install this .dll file, during the installation it shows the same message for each file related to qt...

![image](https://user-images.githubusercontent.com/78563696/107140668-f0d20680-6923-11eb-9e33-486ece7bb44d.png)

**Comment by ebbit1q** [comment]
it is unable to write the first file, are you sure you have enough disk space?

**Comment by GiampaJP** [comment]
Several GB of free space... I also tried to reinstall older versions of Cockatrice but installation stops at the same file.

**Comment by ZeldaZach** [comment]
Sounds like your computer doesn't have enough free space, if you're running into the same issue on an older build.

**Comment by GiampaJP** [comment]
The point is that there is enough space 
![image](https://user-images.githubusercontent.com/78563696/107324134-d032b980-6aa7-11eb-9008-e6d34ccf6ce7.png)

**Comment by GiampaJP** [comment]
If I try to ignore the message and I try to open Cockatrice I find this issue:

![image](https://user-images.githubusercontent.com/78563696/107608996-ea9e9b80-6c3d-11eb-8cf6-c71485a23464.png)

**Comment by ebbit1q** [comment]
Are you sure you are giving the installer the correct permissions to install system wide files?

**Comment by ZeldaZach** [comment]
If this is still an issue, please let us know.
