### ISSUE TITLE
Adventure cards not registering as creatures

### ISSUE THREAD

**Issue by PurpleFruitNewt** [Cockatrice/Cockatrice#4241]
About 1/3 of creatures with an adventure are registering as having instant or sorcery as their primary card type, rather than creature. This isn't a huge issue in practice, but there are a few minor, odd things this does--if on the stack, clicking them again sends them to the graveyard, rather than the battlefield; the power & toughness entry while on the battlefield is listed as, for example, " // 5/5", rather than just "5/5", which in turn means that adding or subtracting toughness treats this score as being base 0/0. This is also a bit of a nuisance in the Deck Builder, where these cards aren't listed as creatures.
The following, at least in my client, are running into this issue:
Embereth Shieldbreaker
Giant Killer
Lovestruck Beast
Merchant of the Vale
Oakhame Ranger
Order of Midnight
Realm-Cloaked Giant
Reaper of Night
Rimrock Knight
Silverflame Squire
Smitten Swordmaster
Tuinvale Treefolk

**Comment by ebbit1q** [comment]
this happens for every adventure that sorts alphabetically after it's adventure half.
