### ISSUE TITLE
War of the Spark Promos Planeswalkers

### ISSUE THREAD

**Issue by BatmenzDW** [Cockatrice/Cockatrice#4242]
**Description of New Feature**
War of the Spark Promos set should have Japanese alternate arts instead of the regular art with prerelease stamp. Example attached.

![image](https://user-images.githubusercontent.com/64180735/107093067-a2612280-67d2-11eb-843f-1ce9a6abeb43.png)

**Comment by ebbit1q** [comment]
No, they "should" not? you seem to be confused, here are some tips:
1. the card you've linked is not a promo, [it's an alternative version released in the same set](https://scryfall.com/card/war/169%E2%98%85/ja/%E4%B8%96%E7%95%8C%E3%82%92%E6%8F%BA%E3%82%8B%E3%81%8C%E3%81%99%E8%80%85%E3%80%81%E3%83%8B%E3%83%83%E3%82%B5)
2. we have specifically removed these as they previously took precedence over the normal print #3706
3. the set PRM contains this card with the same art but is only available in english, you can prioritize PRM to take precedence in your sets editor like normal
4. if you specifically want this print you can simply drop the art with the exact same name `Nissa, Who Shakes the World` into your CUSTOM image dir, see our [wiki](https://github.com/Cockatrice/Cockatrice/wiki/Custom-Cards-&-Sets#to-add-custom-art-for-cards-the-easiest-way-is-to-use-the-custom-folder)

I hope this helps you, I'll be closing this feature request but you can still comment.
