### ISSUE TITLE
"The card database updater exited with an error: crashed"

### ISSUE THREAD

**Issue by SakimikaS** [Cockatrice/Cockatrice#4243]
<b>System Information:</b>

Client Version: 2.8.0 (2021-01-26)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.12.9
System Locale: en_US
Install Mode: Standard

CardDatabase::loadCardDatabases start
[CardDatabase] loadCardDatabase(): Path = "C:/Users/mikas/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 4 Cards = 0 Sets= 0
[CardDatabase] loadCardDatabase(): Path = "C:/Users/mikas/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 4 Cards = 0 Sets= 0
[CardDatabase] loadCardDatabase(): Path = "C:/Users/mikas/AppData/Local/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 0 Sets= 0
CardDatabase::loadCardDatabases failed
PictureLoader: cache fail for "_trice_card_back_226183"

_______________________________________________________________________________________

Hello! I can't seem to update the card list. It keeps giving me the "The card database updater exited with an error: crashed" error. Reinstalling doesn't seem to help the problem either. Any thoughts? Thank you.

- S

**Comment by ZeldaZach** [comment]
We have no information to go on here, so I can't act. If you have more details for us, please do comment them!
