### ISSUE TITLE
App freezes on every occasion since update

### ISSUE THREAD

**Issue by pujok** [Cockatrice/Cockatrice#4245]
Today, I've updated to 2.8.0 on my Windows 10 machine.
Sometimes Cockatrice freezes indefinitely on launch, disallowing me to do anything.
In the case it doesn't and lets me connect to a server, attempting to open any of the server related tabs results in another infinite freeze.
Same case with trying to start a local game.
I've opened the debug log while trying to replicate this but predictably it crashes with the rest of the app before outputting anything.
Is there another persistent log file that perhaps tells us what happened?

**Comment by ebbit1q** [comment]
32 or 64 bit?
are you using the portable version?
have you tried reinstalling?

**Comment by pujok** [comment]
My system is 64-bit, I'm using the full install. 
I had a few problems during the initial installation but I've reinstalled three times without hiccups afterward and nothing changed.

**Comment by ebbit1q** [comment]
Does the oracle card updater work? Does it show the correct version on the first page?

**Comment by pujok** [comment]
Yes, `Help > Check for card updates` enters the Oracle Importer. Shows 2.8.0 in the window that pops up. The further card update also proceeds without problems.

**Comment by pujok** [comment]
Well, I don't know if it was the card update or me turning the computer on and off inbetween now and then, but the problem vanished, thank you for your cooperation.

**Comment by tooomm** [comment]
Thanks for letting us know @pujok. Sometimes you can not explain...
