### ISSUE TITLE
Support MTGO xml formatted .dek files

### ISSUE THREAD

**Issue by ebbit1q** [Cockatrice/Cockatrice#4247]
**Similar Requests**
see addition of mtgo plaintext .dek file loading #3889

**Description of New Feature**
Cockatrice could use the ability to load decks in MTGO's xml format.

**Additional Context**
MTGO uses a different format with the same extension but internally it's xml just like cockatrice's own format so it tries to load the file normally and simply ends up doing nothing (not even an error message).

The format looks like this:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Deck xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <NetDeckID>0</NetDeckID>
  <PreconstructedDeckID>0</PreconstructedDeckID>
  <Cards CatID="[card muid]" Quantity="2" Sideboard="false" Name="[card name]" Annotation="0" />
  <Cards CatID="[card muid]" Quantity="1" Sideboard="true" Name="[card name]" Annotation="0" />
  ...
</Deck>
```
where [card muid] is the muid property as stored in cockatrice's card database and [card name] is the card's name.

Cockatrice's database is indexed by card name so the muid might as well just be ignored.

**Comment by tooomm** [comment]
You confused me now @ebbit1q :D 

I think you mean MTG Online deck files (.dek)?
But then again, I though they are plain text form as stated by @skwerlman in his PR (#3889).

I don't know of any MTG Arena deck files.
The MTGA client only allows me to `Export` decks as far as I know 🤔 ... which will copy a list of cards to the clipboard like this:
```
Deck
2 Riddlemaster Sphinx (ANB) 31
2 Soulblade Djinn (ANB) 34
3 Warden of Evos Isle (ANB) 38
2 Wall of Runes (ANB) 37
2 Sworn Guardian (ANB) 35
3 Waterkin Shaman (ANB) 39
3 Cloudkin Seer (ANB) 25
2 Octoprophet (ANB) 29
2 Windstorm Drake (ANB) 42
3 Unsummon (ANB) 36
2 Glint (ANB) 28
2 Winged Words (ANB) 43
3 Waterknot (ANB) 40
1 Sleep (ANB) 33
25 Island (ANB) 113
1 Overflowing Insight (ANB) 30
1 Windreader Sphinx (ANB) 41
1 Frilled Sea Serpent (ANB) 27

Sideboard
4 Zephyr Gull (ANB) 44
3 Armored Whirl Turtle (ANB) 24
2 River's Favor (ANB) 32

```

Cockatrice can import those, the only issue is the `Deck` headline at the beginning as Cockatrice tries to find a card with that name. It still imports the deck, but includes that one unknown card. I did not check special cards.

**Comment by ebbit1q** [comment]
I just saw dr4ft adding this format and thought we should at least support every format that they export...

**Comment by mixmix** [comment]
I don't think it's needed for dr4ft as that exports Cockatrice `cod` just fine.

But cool to support mtgo > Cockatrice

(mtgo is dek, mtga doesn't have a file format i don't think?)

**Comment by ebbit1q** [comment]
Right, but the format exists so for other tools that export it we could support them.

**Comment by tooomm** [comment]
Ok, thanks for clarifying in the starting post and changing the title. MTGO then, that's what I though. 👍 

What I'm still not sure about is the content of the .dek files...
In the [dr4ft issue](https://github.com/dr4fters/dr4ft/issues/1016) and in [skwerlman's PR](#3889) people said MTGO uses a plain text format, not xml.

Can you explain why you used the xml format in the end when creating the dr4ft export for MTGO @mixmix?
If it works that's good - it's still unclear to me if plain text would work as well and if the .dek files can have either of them? Or is the plain text info outdated or wrong?
I don't use MTGO, so I can not test here.

**Comment by mixmix** [comment]
I think mtgo can take..txt files too?
I made dek because it was unique to mtgo

One thing to note is the CatId - this if the unique card identifier in mtgo. Turns out it's not needed, and I'm fact might be safer not to include because not all sets are supported by mtgo (groan).

See my tests in dr4ft if you're intetested

**Comment by tooomm** [comment]
Reading the PR conversation at dr4ft again, I assume the .dek file LotusWalker send you in private contained xml, unlike the several times mentioned "MTGO is plain text" statement, and you based it off of that. That makes sense. 👍 

>I think mtgo can take..txt files too?

I guess so, those contain simply text then most likely.

**Comment by mixmix** [comment]
Here's what the xml looks like :

https://github.com/dr4fters/dr4ft/blob/88e653e9208b556b831162a3168b694151ba0838/frontend/src/export/mtgo.spec.js#L21

Note that example shows how you don't necessarily need CatId.

Note that particular xml with that last unset card won't work because that card does not exist in mtgo (eg unsets and a bunch of promo sets)

**Comment by ebbit1q** [comment]
seems like this isn't a good idea https://github.com/dr4fters/dr4ft/pull/1457
