### ISSUE TITLE
Support importing decks from MTGA

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#4249]
The MTG Arena client allows me to `Export` decks, which will copy a list of cards to the clipboard like this:
```
Deck
2 Riddlemaster Sphinx (ANB) 31
2 Soulblade Djinn (ANB) 34
3 Warden of Evos Isle (ANB) 38
2 Wall of Runes (ANB) 37
2 Sworn Guardian (ANB) 35
3 Waterkin Shaman (ANB) 39
3 Cloudkin Seer (ANB) 25
2 Octoprophet (ANB) 29
2 Windstorm Drake (ANB) 42
3 Unsummon (ANB) 36
2 Glint (ANB) 28
2 Winged Words (ANB) 43
3 Waterknot (ANB) 40
1 Sleep (ANB) 33
25 Island (ANB) 113
1 Overflowing Insight (ANB) 30
1 Windreader Sphinx (ANB) 41
1 Frilled Sea Serpent (ANB) 27

Sideboard
4 Zephyr Gull (ANB) 44
3 Armored Whirl Turtle (ANB) 24
2 River's Favor (ANB) 32

```

Cockatrice can import those via the "Import deck from clipboard" option, the only issue is the `Deck` headline at the beginning as Cockatrice tries to find a card with that name. It still imports the deck, but includes that one unknown card. I did not check special cards.

_Originally posted by @tooomm in https://github.com/Cockatrice/Cockatrice/issues/4247#issuecomment-776238883_

**Comment by ebbit1q** [comment]
so it works, no problem, why would you open a ticket for something that's already in the client?

**Comment by tooomm** [comment]
I think we have a different definition of "working" then.

If importing a deck from MTG Arena to Cockatrice via the clipboard (which is the only possible way) does not result in the exact same deck in our app... I don't think we "have proper support in the client" yet.

**Comment by ZeldaZach** [comment]
Spoke with Ebbit, we agree this should filter out Deck as Mainboard. Will have a PR up soon.
