### ISSUE TITLE
Kaldheim Cards Are not loaded After downloading latest version

### ISSUE THREAD

**Issue by MarcusTrevino** [Cockatrice/Cockatrice#4252]
Prior to re-installing cockatrice with the latest version for MacOS Big Sur, cockatrice version 2.08, I could see all of the cards from Kaldheim.

After the install, I am unable to see any cards from Kaldheim.

The set does not show up in my card set list.
When I click on "check for card updates" in the Help Menu, nothing happens.

Please advise.

**Comment by mixmix** [comment]
Think I saw a friend with this problem. try Uninstall and reinstall.
Then open and update cards again

**Comment by lcorvini** [comment]
It's the same situation with me. I've tried to uninstall and reinstall it, and there's no change.

**Comment by tooomm** [comment]
>When I click on "check for card updates" in the Help Menu, nothing happens.

That makes me thing that Oracle is not working/installed... if it's not even opening.
Can you check the logs please when you try to update your card database? `Help --> View Debug Log`

On macOS you need to manually install the card database tool as well:
![install](https://user-images.githubusercontent.com/9874850/107851025-f093a880-6e06-11eb-80d5-e770f2dceb32.png)

**Comment by lcorvini** [comment]
Nice. After doing this, and updating the cards via Oracle, the list appeared on Cockatrice. Thanks!

**Comment by tooomm** [comment]
It looks like - for Mac users at least - https://github.com/Cockatrice/Cockatrice/issues/4109 would be even more helpful and has extra value. :)

**Comment by MarcusTrevino** [comment]
I corrected the problem following these steps:

1.  Uninstalled Cockatrice and Oracle
2.  Installed latest version of cockatrice using the dmg file.
3. Opened Oracle and stepped through new update.

Once this was completed, my cockatrice was working as expected.

**Comment by ebbit1q** [comment]
Thanks! closing as resolved.
