### ISSUE TITLE
Only allow front sides of cards to be added to decks

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#4253]
**Description of New Feature**

In order to better find cards and review all sides etc. it makes sense to have them all as individual cards in the database and accessible in the deck editor.

However, a deck itself should only have real cards and their official names (=front halves) for clarity and avoiding issues.
E.g it's possible to have [`Brisela, Voice of Nightmares`](https://scryfall.com/card/emn/15b/brisela-voice-of-nightmares) or [`It That Rides as One`](https://scryfall.com/card/emn/33/lone-rider-it-that-rides-as-one?back) in your deck, as well as [`Tidechannel Pathway`](https://scryfall.com/card/khm/251/barkchannel-pathway-tidechannel-pathway?back) or [`Azcanta, The Sunken Ruin`](https://scryfall.com/card/xln/74/search-for-azcanta-azcanta-the-sunken-ruin?back) for example.

**Comment by ebbit1q** [comment]
you can also add tokens to your deck, why this distinction?

**Comment by tooomm** [comment]
One important difference is e.g. that tokens end up in a dedicated `Token` area in your deck, not your real main deck or sideboard.

We have another issue open that asks for removal of that behavior btw.
The intention to allow tokens in decks (it *was* actually useful) was that people could manually add all kind of tokens they might need during gameplay to create them a bit easier via `Right click to the battlefield --> Create predefined token`.
Our integrated related cards feature superseded that. It's now easier and quicker.

**Comment by ZeldaZach** [comment]
Ebbit and I both agree this is a non-issue, as you can add tokens to the deck as-is. A user should know what side of a card they're adding to the deck, and if they mess up then in game they can always "transform" it and the correct half will appear.
