### ISSUE TITLE
Related cards not shown for meld in card info

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#4254]
**System Information:**
Client Version: 2.8.1-custom(efc3f98) (2021-02-09)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.12.9

_______________________________________________________________________________________

Meld cards in Cockatrice deck editor
	a) have an empty `Related cards` field
	b) don't contain a `Related cards` field at all

For every meld card - which is combined out of two different cards - its two individual front faces have always both cases. One falls into a, the other into b. The meld part misses the `Related cards` field as well.

Both main parts should always have the `Related cards` field and link to the meld part, and vice versa:
https://scryfall.com/card/emn/28/gisela-the-broken-blade
https://scryfall.com/card/emn/15a/bruna-the-fading-light
https://scryfall.com/card/emn/15b/brisela-voice-of-nightmares

Note, that ones that create tokens have the `Related cards` field and correctly link to those:
https://scryfall.com/card/emn/130a/hanweir-garrison

_______________________________________________________________________________________

**Steps to reproduce:**
 - Search for any meld card and check all 2 other connected cards (2x front faces --> combining to 1x meld back face)

**Comment by tooomm** [comment]
Running Client Version: 2.8.1-custom(2b0a997) (2021-02-24) and with an updated card database, the issue still partly persists:

- ❌ Bruna has no related cards field and no links, should link to Brisela (Maybe to Gisela as well?)
- ✔️ Gisela has a related cards field and links to Brisela (Maybe to Bruna as well?)
- ❌ Brisela has no related cards field and no links, should link to Bruna and Gisela

**Comment by ebbit1q** [comment]
This is intentional, only gisela has the meld ability.
