### ISSUE TITLE
View library with large decks

### ISSUE THREAD

**Issue by MotherofRuins** [Cockatrice/Cockatrice#4259]
When someone views their library, if the library is very large (eg, 4000 cards), it can take a couple minutes to display.  This action is blocking.  Generally with these decks we try to avoid F3 and just make a token with the  name of the card we would search for, but sometimes we hit F3 without thinking, and then Cockatrice freezes up for a while.  In a local game it's inconvenient but in an online game it annoys the other players.  One wants a way to break out.  ESC would be a typical abort key.

**Comment by Daenyth** [comment]
Likely area of interest: [ZoneViewWidget](https://github.com/Cockatrice/Cockatrice/blob/master/cockatrice/src/zoneviewwidget.cpp)

I'm betting it has something to do with sorting the view

**Comment by ebbit1q** [comment]
making 4000 card deck I guess...

**Comment by Daenyth** [comment]
Would be good to check on number of cards vs number of *distinct* cards, and how that impacts it

**Comment by ebbit1q** [comment]
I err, had a way to automate this and now spent more time to find it than it would to make again...

**Comment by ebbit1q** [comment]
here
```bash
cards="$HOME/.local/share/Cockatrice/Cockatrice/cards.xml"
pre='<?xml version="1.0" encoding="UTF-8"?>
<cockatrice_deck version="1">
    <deckname>big deck</deckname>
    <comments></comments>
    <zone name="main">'
end='    </zone>
</cockatrice_deck>'
linepre='        <card number="1" name="'
lineend='"/>'
first="<cards>"
regex='<name>(.*)<\/name>'

echo "$pre"
{
  while read "line" && [[ ! $line =~ $first ]]; do
    :
  done
  while read "line"; do
    [[ $line =~ $regex ]] && echo "$linepre${BASH_REMATCH[1]}$lineend"
  done
}<"$cards"
echo "$end"
```

**Comment by MotherofRuins** [comment]
I can send you a 4000 card deck if you like.  Also it's singleton.

**Comment by ebbit1q** [comment]
> I can send you a 4000 card deck if you like. Also it's singleton.

no need, the script up there automatically generates a 20.000 card list

**Comment by MotherofRuins** [comment]
The big deck displays with F3 instantly, thank you.

**Comment by ebbit1q** [comment]
please don't close the issue until this pull request is merged
