### ISSUE TITLE
Swamp and Plains missing (b) variation

### ISSUE THREAD

**Issue by fn4twn** [Cockatrice/Cockatrice#4265]
**System Information:**

MacOS 11.2.1
_______________________________________________________________________________________

There are (b) variations of the basic lands for Island, Forest, and Mountain, but not Swamp or Plains

<img width="419" alt="Screen Shot 2021-02-20 at 6 38 30 PM" src="https://user-images.githubusercontent.com/64651989/108611316-8ac99280-73ab-11eb-9457-4e0a83a7dae4.png">

_______________________________________________________________________________________

**Steps to reproduce:**
 - Search t:basic in deck editor

**Comment by ebbit1q** [comment]
this isn't a bug, there simply aren't any sets with three variations on those land types. if there were, please open a report at our data provider github.com/mtgjson/mtgjson instead.
