### ISSUE TITLE
Accidental mulligan ruins games

### ISSUE THREAD

**Issue by MotherofRuins** [Cockatrice/Cockatrice#4274]
Accidentally hitting C-m during a game ruins the game and is not easily recovered from.  In a tournament I suppose it's a game loss.  A mulligan undo function would solve the problem but it's probably a lot of work to implement.  Also there are game variants, like pack wars, where you shouldn't be seeing any cards from your library, so even Undo isn't perfect.

I suggest the code look at the board state before resolving.  If there are any permanents on the battlefield, or any cards in graveyard or exile, pop up a dialog first "Are you sure?  Y/N".  Otherwise proceed as usual.

**Comment by ebbit1q** [comment]
https://github.com/Cockatrice/Cockatrice/pull/3773 added a dialog more than a year ago that was also intended to require a user to confirm they wanted to do a mulligan while picking the amount of cards, defaulting to 7. This is exactly like the mechanic you suggest except it is always present. I what way do you think this is insufficient and how would adding a second dialog resolve this?

**Comment by MotherofRuins** [comment]
I could swear I accidentally mull'd yesterday without confirmation, but I must have reflexively hit Enter as well.
