### ISSUE TITLE
MacOS Catalina (macbook pro 7,1 mid 2010) - Cockatrice closed immediately / can't start

### ISSUE THREAD

**Issue by superm57** [Cockatrice/Cockatrice#4275]
Hello, when i start cockatrice it immediately closed itself...
I'm on Mac OS X Catalina. Here the computer  :

Model: MacBookPro7,1, BootROM 68.0.0.0.0, 2 processors, Intel Core 2 Duo, 2,4 GHz, 8 GB, SMC 1.62f7
Graphics: kHW_NVidiaGeForce320MItem, NVIDIA GeForce 320M, 256 MB
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1067 MHz, 0x859B, 0x435434473353313036374D2E433136464B44
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1067 MHz, 0x859B, 0x435434473353313036374D2E433136464B44
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x8D), Broadcom BCM43xx 1.0 (5.106.98.102.31)
Bluetooth: Version 7.0.6f7, 3 services, 18 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: CT500MX500SSD1, 500,11 GB
Serial ATA Device: MATSHITADVD-R   UJ-898
USB Device: USB Bus
USB Device: BRCM2046 Hub
USB Device: Bluetooth USB Host Controller
USB Device: IR Receiver
USB Device: Apple Internal Keyboard / Trackpad
USB Device: USB Bus
USB Device: USB 2.0 Bus
USB Device: Internal Memory Card Reader
USB Device: USB 2.0 Bus
USB Device: Built-in iSight
Thunderbolt Bus: 

What can i do ? Thanks in advance

**Comment by ebbit1q** [comment]
Have you tried uninstalling and then reinstallling from our release page? https://github.com/Cockatrice/Cockatrice/releases

**Comment by superm57** [comment]
> 
> 
> Have you tried uninstalling and then reinstallling from our release page? https://github.com/Cockatrice/Cockatrice/releases

Yeah, i did it many time and also the new beta...

**Comment by ZeldaZach** [comment]
I'm not sure what to do with this as we don't have enough information to go on. When you say it crashes, can you provide an Apple crash log on the situation?
