### ISSUE TITLE
add option to throw multiple dice

### ISSUE THREAD

**Issue by ebbit1q** [Cockatrice/Cockatrice#4276]
**Description of New Feature**
Sometimes you'd like to throw multiple dice at the same time, without being ratelimited etc.
I propose an additional value to the roll die command and event that simply specifies an amount of them, this should then be interpreted either server or clientside to translate a single rand to multiple values. note that the maximum random number currently geneneratable is half an int64. see https://github.com/Cockatrice/Cockatrice/blob/master/common/rng_sfmt.cpp

**Additional Context**
While a rare effect in magic it certainly is possible to have many die or coin related abilities trigger at the same time, other games could benefit as well.
This would be a small addition to the protocol and maintain backwards compatibility.

**Comment by Heroj04** [comment]
Just adding my thoughts,
It would be really cool to implement an actual dice rolling expressions solver.
Something similar to the PyHedrals Library https://github.com/StarlitGhost/pyhedrals
I think this would require sending a string to the server instead though and I wasnt able to find a c++ library to do this already from my quick searching.

**Comment by ebbit1q** [comment]
that would be nice and I'm sure there would be a good way to send them to the server (preferably just an array of rolls rather than a string that needs parsing) though just adding how many of the same die you'd like to roll would already serve almost every occasion, especially in card games (how many people play ttrpgs on cockatrice, inquiring minds need to know)
