### ISSUE TITLE
Can't Install Cockatrice

### ISSUE THREAD

**Issue by Bugejoah** [Cockatrice/Cockatrice#4277]
**System Information:**
Windows 10 Client Version 2.7.4

_______________________________________________________________________________________

I was attempting to reinstall Cockatrice, but when I try, I keep getting this message: 

![Untitled](https://user-images.githubusercontent.com/80181889/110225601-bd47b500-7eac-11eb-8db8-61992754619d.png)

_______________________________________________________________________________________

**Comment by mainman879** [comment]
This seems to be a copy of this issue, perhaps you can find the solution in here. https://github.com/Cockatrice/Cockatrice/issues/1574

**Comment by ZeldaZach** [comment]
Can you try rebooting and reinstalling? Reopen if still an issue
