### ISSUE TITLE
Dryad Arbor Using Stack

### ISSUE THREAD

**Issue by jonidcrushfire** [Cockatrice/Cockatrice#4282]
When playing a Dryad Arbor, it goes to the stack, and then to the field next to creatures when it "resolves."

The location it goes to is fine, and generally preferred, but this card should not use the stack at all. It is not a spell.

I tried to search if this issue has come up before, but I was unable to find it in the open issues, so I am not sure if it is only my end or not.

Please advise.

**Comment by ebbit1q** [comment]
this is a concession in the way card actions are handled, all cards that are not placed in the bottom row will use the stack.
there isn't much we can do about this unless we were to implement card specific behavior in the client which would reduce the flexibility we want in cockatrice

**Comment by ZeldaZach** [comment]
I agree w/ Ebbit here, that we'd rather have Dryad Arbor on the creature line. It's a super limited edge case, and most people tend to drag it into play anyway. As such, I will be closing this ticket for now.
