### ISSUE TITLE
improve performance on large decks

### ISSUE THREAD

**Issue by ebbit1q** [Cockatrice/Cockatrice#4284]
**Similar Requests**
https://github.com/Cockatrice/Cockatrice/issues/4259
https://github.com/Cockatrice/Cockatrice/issues/67

**Description of New Feature**
there is an opportunity to improve the performance of loading decks in the player by delaying or optimizing how card menus are generated.

**Additional Context**
by my estimate of just stopping the client to see what it is doing while loading decks and noticing the improvement when disabled in the code, card menus are responsible for more than 90% of the time spent when loading the deck.
this time is spent on allocating QAction objects and initializing them as each card has its own menu with a unique set of actions that the card can take.
this menu should instead be either shared between multiple cards or simply generated when the card is interacted with.
this isn't limited to loading the deck either, a new card object with a new set of qactions is created for each card in every cardview as well.
this issue isn't very noticeable until you load about a thousand cards but any improvement here could lead normal sized decks to load in a bit snappier as well, not to mention the fact this is basically just wasting a lot of cpu cycles.

for testing it does not matter if the cards are unique, simply making a deck of 1000 of the same card should suffice.
relevant code is found here https://github.com/Cockatrice/Cockatrice/blob/master/cockatrice/src/player.cpp#L3026

**Comment by MotherofRuins** [comment]
Anything you can do in this regard would be very welcome by me and our playgroup.  We have a bunch of different 1000 card singleton decks we use to mimic cube experience without actually drafting.

**Comment by tooomm** [comment]
>card menus are responsible for more than 90% of the time spent when loading the deck
this time is spent on allocating QAction objects and initializing them as each card has its own menu with a unique set of actions that the card can take.
this menu should instead be either shared between multiple cards or **simply generated when the card is interacted with.**
this isn't limited to loading the deck either, a new card object with a new set of qactions is created for each card in every cardview as well.

+1 that sounds reasonable. I can't imagine any drawback here?
