### ISSUE TITLE
Reference Point Collector Number with filling zeros

### ISSUE THREAD

**Issue by Carlosjrlu** [Cockatrice/Cockatrice#4286]
I would like to be able to use a reference point for [Custom Picture Download URLs](https://github.com/Cockatrice/Cockatrice/wiki/Custom-Picture-Download-URLs) that fill up zeros when a number is low.

Like:
5     -> 005
55   -> 055
355 -> 355

**Comment by ebbit1q** [comment]
so this would be an addition to the current notation for custom urls? what notation do you propose? would it need to apply to all url fields or would something like `!zfill_num!` be sufficient?

**Comment by Carlosjrlu** [comment]
!set:zfill_num! would be sufficient so I can use it in custom URLs

**Comment by ebbit1q** [comment]
I have opened a pull request, test binaries are automatically generated and will be available here https://github.com/Cockatrice/Cockatrice/actions/runs/665684821
if you'd be able to test them it'd be appreciated, please leave your comments on them on the pull request.
