### ISSUE TITLE
Prefill forgot password dialog with info from selected server

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#4294]
**Description of New Feature**
The `Forgot Password` dialog should know which server is currently selected and populate the related+stored server and user information to its dialog when opened to request a new password.
Currently, it's always pre-filled with the last successfully connected server, not the actual selection.

Join server A
Disconnect
Open Connect dialog
Server A will be preselected
Select server B
Join server B
Disconnect
Open Connect dialog
Server B will be preselected
Select server A
Click Forgot Password
It will be prefilled with the details from server B (last connected one) + your user name from server B

It should have all info from server A instead as that is your selection.
Users can not even copy and paste the server data from the connect dialog, one has to type them which is annoying and an easy source for errors.

This is probably a leftover when the connect dialog got changed ~2 years ago. Before, the `Forgot Password` button was more general and not as connected to the login fields which are now tied to the server selection as well.

**Comment by ebbit1q** [comment]
it already does this but instead takes the most recent server you clicked connect on.
