### ISSUE TITLE
Getting mixed results from URL download priority in Cockatrice

### ISSUE THREAD

**Issue by rnaranjo** [Cockatrice/Cockatrice#4304]
**System Information:**
Client Version: 2.8.0 (2021-01-26)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.12.9
System Locale: es_CL
Install Mode: Standard

_______________________________________________________________________________________

I'm getting mixed results when trying to download card images in spanish, with card images sometimes being downloaded in english and sometimes in spanish.

I wanted to check if I could configure Cockatrice to download the card images in spanish, so I went on the documentation and carried out the following steps:

_______________________________________________________________________________________

1. I added the following url on the Download URL list: https://api.scryfall.com/cards/!setcode_lower!/!set:num!/es?format=image&face=!prop:side!
2. I hovered over some cards, however all images were still in english, so I tried to delete the images from the Pictures directory.
3. I restarted Cockatrice and tried to see if this worked. The cards were still being downloaded in english, so I decided to eliminate all the other Download URLs, except for the one I just added.
4. Deleted all images from the Pictures directory again.
5. This time the cards were finally downloaded in spanish. Hooray!
6. I started searching for some cards, but eventually noticed some card images were missing and would never load. In particular, this happened with all the Kaldheim god cards (Birgi, Esika, etc.).
7. I figured this happened because it couldn't find these cards on the URL, so I decided to reset the download URL list using the button at the top of the list. I added the spanish cards URL to the list on top.
8. I went on to search for more cards, however now I'm getting mixed results, were some cards are downloaded in Spanish and some in English.

I made sure that the cards I was testing this with were available in spanish by leaving only the spanish URL in the configuration, however when adding all the default URLs and deleting all files from the pictures folder and I kept getting different results when downloading the images, with cards appearing either in spanish or english seemingly at random.

**Comment by ebbit1q** [comment]
this is an issue at scryfall, their esika is not available in other languages for whatever reason: https://scryfall.com/card/khm/168/esika-god-of-the-tree-the-prismatic-bridge

spanish esika obviously exists though: https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=504383

cockatrice can't fix this, I'd recommend reporting the issue to scryfall.

as a workaround you're able to replace any card art with the art of your liking by using custom images: https://github.com/Cockatrice/Cockatrice/wiki/Custom-Cards-&-Sets#to-add-custom-art-for-cards-the-easiest-way-is-to-use-the-custom-folder

**Comment by Carlosjrlu** [comment]
Is there any way to have a Download URL from gatherer.wizards.com with a specific language?

I know the multiverseid from english is different to the spanish one for example, but the data for the multiverseid in spanish is in mtgjson.

It would be awesome if we can change what multiverseid cockatrice uses by changing the program's language.

**Comment by ebbit1q** [comment]
no, just download their image and put it into CUSTOM

we have this and it works fine for any exception to the rules, I don't see this as a priority as its a different way to do the same thing.

**Comment by ebbit1q** [comment]
closed as upstream issue (scryfall)
