### ISSUE TITLE
Search for strings with umlaut characters

### ISSUE THREAD

**Issue by jroed** [Cockatrice/Cockatrice#4305]
**System Information:**
Client Version: 2.8.0 (2021-01-26)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.12.9
_______________________________________________________________________________________

When searching for strings with umlaut characters (such as 'Jötun Grunt') Cockatrice returns no results.

_______________________________________________________________________________________

**Steps to reproduce:**
 - Optional: Go to Jötun Grunt's Scryfall page (https://scryfall.com/card/cmd/16/j%C3%B6tun-grunt) and copy the card name into your clipboard.
 - Open Cockatrice and enter 'Jötun Grunt' into the Cockatrice search bar.

**Comment by ebbit1q** [comment]
I can't reproduce this issue, searching for an o umlaut gives me the expected jötun grunt, jötun owl keeper, bösium strip cards

**Comment by jroed** [comment]
Hi @ebbit1q, thank you for checking. I attach a screenshot to show my experience with this issue.

![cockatrice_umlaut_example](https://user-images.githubusercontent.com/1543873/114268513-bfe47f80-9a01-11eb-9c2d-b1515328fa6a.jpg)

**Comment by ebbit1q** [comment]
![image](https://user-images.githubusercontent.com/36401181/114271036-c548c680-9a0f-11eb-8dfd-43c0f55875f0.png)
Client Version: 2.8.0 (2021-01-26)
Client Operating System: Pop!_OS 20.10
Build Architecture: 64-bit
Qt Version: 5.14.2
System Locale: en_US
Install Mode: Standard

@jroed are you able to find jötun grunt when searching for just grunt?
![image](https://user-images.githubusercontent.com/36401181/114271124-1bb60500-9a10-11eb-91ff-ea75118d9379.png)

**Comment by jroed** [comment]
Yes, searching for 'grunt' shows the correct results including 'jötun grunt'. Also searching only for 'ö' doesn't show any results. System locale is non-English and install mode is standard. Could this be an encoding problem?

**Comment by ebbit1q** [comment]
sounds likely, I'm going to tag this as windows only.

**Comment by tooomm** [comment]
Can confirm on Windows with 2.8.0.

**Comment by skwerlman** [comment]
does the composition of the o umlaut matter here? like U+00F6 (`ö`) or U+006f U+0308 (`ö`)

**Comment by ebbit1q** [comment]
me typing the first one does work, the combined o + separate diacritic does not.

this makes sense as the database only includes the normal u+f6 character.

**Comment by ebbit1q** [comment]
> Can confirm the issue on Windows with 2.8.0.

could you please test if the character composition matters on windows for us?

**Comment by tooomm** [comment]
It seems to not matter. I tried to use (copy) both umlaut variants mentioned by skwerlman.
Copying the name from scryfall directly shows no result as well with `CMD` set enabled.
