### ISSUE TITLE
Can't download new sets

### ISSUE THREAD

**Issue by fedeb95** [Cockatrice/Cockatrice#4306]
I get an error trying to download cards, and even downloading the file from mtgjson doesn't import any card.

This is the error I get with default URL:

Network error: Error transferring https://mtgjson.com/json/AllPrintings.json.xz - server replied: Not Found.

This happens with the updated client for Debian Buster

**Comment by tooomm** [comment]
Update your client first, please. See the help menu. 
You are probably using an outdated version.

**Comment by ebbit1q** [comment]
The first page of the oracle wizard has a version number, the latest version is 2.8.0 right now, if it's not up to date you should get the most recent version from our release page https://github.com/Cockatrice/Cockatrice/releases/latest

If your version is up to date and it didn't correct to the updated url that would be a bug and you should try the "restore default download url" button on the second page of the wizard.

If you have installed cockatrice in the past from a compiled version by downloading from git and using `make install` you will first need to remove this version's installed files from `/usr/local`, cmake will make a manifest of all installed files in the build directory `install_manifest.txt` see https://stackoverflow.com/questions/19921017/cleaning-cmake-installed-files .

**Comment by fedeb95** [comment]
I installed from the debian binary, but forgot that last time I used a custom build so I couldn't use the up to date version. Now everything is working, thanks and sorry for the trouble.

**Comment by ebbit1q** [comment]
I'd recommend to, instead of directly installing, make a package using cmake and then installing the package if you want to build from source yourself.

`make package` will by default make a debian package, you can install the package the same way you'd install the downloaded package.

our build system will also make a package for every commit.
