### ISSUE TITLE
Can't update client with MacOS Mojave

### ISSUE THREAD

**Issue by salmonofdoubt12** [Cockatrice/Cockatrice#4312]
I opened up Cockatrice for the first time in a while today, navigated to "Help" -> "Check for Client Updates," and got an error message saying that "Unfortunately there are no download packages available for your operating system." When I checked Github, it appears as though Mojave should be a compatible operating system for download packages. Any idea what the issue is?
![Screen Shot 2021-04-14 at 1 05 30 PM](https://user-images.githubusercontent.com/8680625/114772355-8c1b9980-9d22-11eb-807c-86be2b1d6c92.png)

**Comment by ebbit1q** [comment]
what is your original version?

have you tried simply downloading from the website and updating that way (this is all the updater does)

**Comment by salmonofdoubt12** [comment]
Thanks, I tried downloading directly and it worked!
