### ISSUE TITLE
Wording change: CMC --> MV

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#4316]
**Description of New Feature**
STX will introduce a rule change regarding terminology.
`Converted Mana Cost (CMC)` will be named `Mana Value (MV?)` starting in one week.

We use it in several places in the UI, as well as the card databases.

@ZeldaZach Will MTGJSON change as well? Scryfall API?
Do we want to change the Spoiler and Token files as well?

**Comment by ebbit1q** [comment]
it's unlikely any internal apis will change, changing the ui is easy though:
```
cockatrice/src/game_specific_terms.h
31:        return QCoreApplication::translate("Mtg", "Converted Mana Cost");

cockatrice/resources/help/search.md
36:<dd>[cmc=7](#cmc=7) <small>(Any card with a converted mana cost equal to 7)</small></dd>
```

also consider this should get added to the filter widget with mv=[n], I think this should not replace the existing cmc, we can have both.
