### ISSUE TITLE
Card images refreshing+redownloading (even when available on HDD)

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#4319]
**System Information:**
Client Version: 2.8.1-custom(4c624ff) (2021-04-18)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.12.9

_______________________________________________________________________________________

Card images keep disappearing and refreshing/reloading for no obvious reason after the client has not been active for a while.

I remember that we talked about this (or a very similar) phenomenon in another issue before. I hope I can add more information to it.
It looks like card pics get lost and are not found on disk again? The log shows the repeated process, even though the image file is there.
![reload](https://user-images.githubusercontent.com/9874850/115146843-9c03e800-a058-11eb-831b-0debfe043eb7.png)
As you can see in the screen the file is there, got created 2 years ago and got very recently accessed. Bot for whatever reason it is not found and looks like the client re-requests and re-downloads it again in order to redisplay the art after inactivity...

This does not happen in the deck editor as far as I can tell.

<details>
<summary>Complete Debug Log</summary>

Client Version: 2.8.1-custom(4c624ff) (2021-04-18)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.12.9
PictureLoader: cache fail for "_trice_card_back_134190"
PictureLoader: [card:  "Greenwood Sentinel"  set:  "" ]: Requested set property ( "uuid" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Greenwood Sentinel"  set:  "" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Greenwood Sentinel"  set:  "" ]: Requested set property ( "muid" ) for Url template ( "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Greenwood Sentinel"  set:  "" ]: Trying to load picture
PictureLoader: [card:  "Greenwood Sentinel"  set:  "" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Greenwood Sentinel"  set:  "" ]: Trying to download picture from url: "http://gatherer.wizards.com/Handlers/Image.ashx?name=Greenwood Sentinel&type=card"
PictureLoader: [card:  "Siegebreaker Giant"  set:  "" ]: Requested set property ( "uuid" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Siegebreaker Giant"  set:  "" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Siegebreaker Giant"  set:  "" ]: Requested set property ( "muid" ) for Url template ( "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Siegebreaker Giant"  set:  "" ]: Trying to load picture
PictureLoader: [card:  "Siegebreaker Giant"  set:  "" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Greenwood Sentinel"  set:  "" ]: following redirect: "https://gatherer.wizards.com/Handlers/Image.ashx?name=Greenwood Sentinel&type=card"
PictureLoader: [card:  "Greenwood Sentinel"  set:  "" ]: Image successfully downloaded from  "https://gatherer.wizards.com/Handlers/Image.ashx?name=Greenwood Sentinel&type=card"
PictureLoader: [card:  "Siegebreaker Giant"  set:  "" ]: Trying to download picture from url: "http://gatherer.wizards.com/Handlers/Image.ashx?name=Siegebreaker Giant&type=card"
PictureLoader: [card:  "Siegebreaker Giant"  set:  "" ]: following redirect: "https://gatherer.wizards.com/Handlers/Image.ashx?name=Siegebreaker Giant&type=card"
PictureLoader: [card:  "Siegebreaker Giant"  set:  "" ]: Image successfully downloaded from  "https://gatherer.wizards.com/Handlers/Image.ashx?name=Siegebreaker Giant&type=card"
PictureLoader: cache fail for "_trice_card_back_134190"
PictureLoader: [card:  "Greenwood Sentinel"  set:  "" ]: Requested set property ( "uuid" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Greenwood Sentinel"  set:  "" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Greenwood Sentinel"  set:  "" ]: Requested set property ( "muid" ) for Url template ( "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Greenwood Sentinel"  set:  "" ]: Trying to load picture
PictureLoader: [card:  "Greenwood Sentinel"  set:  "" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Greenwood Sentinel"  set:  "" ]: Trying to download picture from url: "http://gatherer.wizards.com/Handlers/Image.ashx?name=Greenwood Sentinel&type=card"
PictureLoader: [card:  "Siegebreaker Giant"  set:  "" ]: Requested set property ( "uuid" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Siegebreaker Giant"  set:  "" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Siegebreaker Giant"  set:  "" ]: Requested set property ( "muid" ) for Url template ( "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Siegebreaker Giant"  set:  "" ]: Trying to load picture
PictureLoader: [card:  "Siegebreaker Giant"  set:  "" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Greenwood Sentinel"  set:  "" ]: following redirect: "https://gatherer.wizards.com/Handlers/Image.ashx?name=Greenwood Sentinel&type=card"
PictureLoader: [card:  "Greenwood Sentinel"  set:  "" ]: Image successfully downloaded from  "https://gatherer.wizards.com/Handlers/Image.ashx?name=Greenwood Sentinel&type=card"
PictureLoader: [card:  "Siegebreaker Giant"  set:  "" ]: Trying to download picture from url: "http://gatherer.wizards.com/Handlers/Image.ashx?name=Siegebreaker Giant&type=card"
PictureLoader: [card:  "Siegebreaker Giant"  set:  "" ]: following redirect: "https://gatherer.wizards.com/Handlers/Image.ashx?name=Siegebreaker Giant&type=card"
PictureLoader: [card:  "Siegebreaker Giant"  set:  "" ]: Image successfully downloaded from  "https://gatherer.wizards.com/Handlers/Image.ashx?name=Siegebreaker Giant&type=card"

</details>

_______________________________________________________________________________________

**Steps to reproduce:**
 - Start a local game
 - Put a few cards to the battlefield
 - Open the Debug log, clear it, reopen it
 - Minimize Cockatrice and wait some time (e.g. 15min, I don't know if there is a breaking time frame)
 - Maximize Cockatrice (pics will disappear and get reloaded - but not from disk)
 - Minimize Cockatrice and wait some time again
 - Maximize Cockatrice (same will happen, another fresh copy is requested from various online sources)
 - ...

**Comment by ebbit1q** [comment]
I can't reproduce this issue

**Comment by n21lv** [comment]
Could it be that the application saves some sort of image index file somewhere in a protected folder where it doesn't have write access? 
Another cause could be that the drive where these are stored is simply living through its last days. I'd recommend running a full HD Tune check on that drive to rule this out.

**Comment by tooomm** [comment]
> Another cause could be that the drive where these are stored is simply living through its last days. I'd recommend running a full HD Tune check on that drive to rule this out.

CrystalDiskInfo reports no SMART issues and a good health status of my SSD.
Windows error checking passes flawlessly on all partitions of the drive as well.

**Comment by n21lv** [comment]
Could be the picture cache issue. What's the size of %localappdata%\Cockatrice\Cockatrice\pics\downloadedPics folder compared to value in the settings?
You can also try using [Diskmon](https://docs.microsoft.com/en-us/sysinternals/downloads/diskmon) to monitor the folder to see what is constantly deleting card pictures there.

**Comment by tooomm** [comment]
Picture cache size is set to 2047 MB in settings (unchanged max value, default).

The size of the `downlaodedPics` folder in the `Pictures directory path` is: 399 MB.

**Comment by tooomm** [comment]
I have the feeling this could be related to the `Manage sets` dialog and whether one has all sets enabled or only very few.
Since this view also influences image loading, there might be an issue with loading cards from sets that are disabled.

When all sets are enabled and I open a Cockatrice instance from the background, all images shortly flash but show correctly.
The log contains this then instead:
```
PictureLoader: [card:  "Faithless Looting"  set:  "C21" ]: Trying to load picture
PictureLoader: [card:  "Faithless Looting"  set:  "C21" ]: Picture found on disk.
PictureLoader: [card:  "Blackcleave Cliffs"  set:  "ZNE" ]: Trying to load picture
PictureLoader: [card:  "Blackcleave Cliffs"  set:  "ZNE" ]: Picture found on disk.
PictureLoader: [card:  "Bloodstained Mire"  set:  "ZNE" ]: Trying to load picture
PictureLoader: [card:  "Bloodstained Mire"  set:  "ZNE" ]: Picture found on disk.
PictureLoader: [card:  "Inquisition of Kozilek"  set:  "STA" ]: Trying to load picture
PictureLoader: [card:  "Inquisition of Kozilek"  set:  "STA" ]: Picture found on disk.
PictureLoader: [card:  "Blood Crypt"  set:  "SLD" ]: Trying to load picture
PictureLoader: [card:  "Blood Crypt"  set:  "SLD" ]: Picture found on disk.
PictureLoader: [card:  "Lightning Bolt"  set:  "STA" ]: Trying to load picture
PictureLoader: [card:  "Lightning Bolt"  set:  "STA" ]: Picture found on disk.
PictureLoader: [card:  "Bedlam Reveler"  set:  "TSR" ]: Trying to load picture
PictureLoader: [card:  "Bedlam Reveler"  set:  "TSR" ]: Picture found on disk.
```


Going back to "Draft" mode with only the latest regular set used for limited play being enabled and loading the same Modern deck loads fine at first. (New images being downloaded)
But when leaving it minimized in the background for a while and opening it again, all cards are colored rectangles and fresh reloads from scratch are triggered instead using the prior downlaoded images:
```
PictureLoader: [card:  "Faithless Looting"  set:  "" ]: Trying to download picture from url: "https://gatherer.wizards.com/Handlers/Image.ashx?name=Faithless Looting&type=card"
PictureLoader: [card:  "Faithless Looting"  set:  "" ]: Image successfully downloaded from  "https://gatherer.wizards.com/Handlers/Image.ashx?name=Faithless Looting&type=card"
PictureLoader: [card:  "Lingering Souls"  set:  "" ]: Trying to download picture from url: "https://gatherer.wizards.com/Handlers/Image.ashx?name=Lingering Souls&type=card"
PictureLoader: [card:  "Lingering Souls"  set:  "" ]: Image successfully downloaded from  "https://gatherer.wizards.com/Handlers/Image.ashx?name=Lingering Souls&type=card"
PictureLoader: [card:  "Kolaghan's Command"  set:  "" ]: Trying to download picture from url: "https://gatherer.wizards.com/Handlers/Image.ashx?name=Kolaghan%27s Command&type=card"
PictureLoader: [card:  "Kolaghan's Command"  set:  "" ]: Image successfully downloaded from  "https://gatherer.wizards.com/Handlers/Image.ashx?name=Kolaghan%27s Command&type=card"
PictureLoader: [card:  "Terminate"  set:  "" ]: Trying to download picture from url: "https://gatherer.wizards.com/Handlers/Image.ashx?name=Terminate&type=card"
PictureLoader: [card:  "Terminate"  set:  "" ]: Image successfully downloaded from  "https://gatherer.wizards.com/Handlers/Image.ashx?name=Terminate&type=card"
```

**Comment by ebbit1q** [comment]
that perfectly explains your issue, you have the sets disabled so the cards are not found in the database, instead the card downloader tries to look up an image for it online but will not save it to disk. (from https://github.com/Cockatrice/Cockatrice/pull/3589)
when later the card cache in ram is refreshed these images have to be redownloaded, taking some time and having the cards be empty for a bit in between.
nothing special is happening here, if you have no further questions I will be closing this issue.

**Comment by tooomm** [comment]
At least there is some light in the dark now.
