### ISSUE TITLE
Have to reinstall the latest update every time I open Cockatrice

### ISSUE THREAD

**Issue by narkboy42** [Cockatrice/Cockatrice#4320]
**System Information:**

Client Version: 2.8.0 (2021-01-26)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.12.9
System Locale: en_US
Install Mode: Standard
_______________________________________________________________________________________

I have to reinstall the 2.8.0 update every time I launch Cockatrice. Somehow it always reverts back to the old version after I close it. 

_______________________________________________________________________________________

**Steps to reproduce:**
 - Open Cockatrice
 - Install update
 - Close it when I'm done
 - Repeat

**Comment by ebbit1q** [comment]
this probably means you have installed cockatrice twice, maybe a portable version, you should copy your data from that version, back it up and uninstall both versions then reinstall
