### ISSUE TITLE
Game creator should be able to start game, even if not full

### ISSUE THREAD

**Issue by ZeldaZach** [Cockatrice/Cockatrice#434]
This mainly applies to EDH players; if a group sets up for 4 and only has 3 and wants to start, the game creator should have the option to launch the game at any point

**Comment by ZeldaZach** [comment]
I haven't seen a duplicate and I think we should really consider this feature.

**Comment by Daenyth** [comment]
I've meant to do this for a while

**Comment by ZeldaZach** [comment]
If possible, can somebody try and look into this? It's been quiet for a long time and it's something a lot of people seem to want

**Comment by MotherofRuins** [comment]
Would also like to increase number of players, not just start with fewer.
