### ISSUE TITLE
Add a preference to use regular card images instead of boosterfun stuff

### ISSUE THREAD

**Issue by n21lv** [Cockatrice/Cockatrice#4342]
**Similar Requests**
#4062 

**Description of New Feature**
Some players prefer having regular card images of cards instead of any borderless, alternative or extended art versions. The latter can be an issue when card uses white text on a light-gray background, which makes it hard to read.

**Proposed solution**
A checkbox that changes the preference of card images that are downloaded can be added to the "Manage sets" window. This can be implemented by only downloading card images of those JSON objects where `booster` is `true`. 

**Acceptance criteria**
When checkbox is checked, if a set contains multiple versions of the same card, the game SHOULD use the standard version of card art instead of any borderless, alternative or extended art versions.

**Comment by n21lv** [comment]
> if you still have the old images you should update your card database and clear your image cache.

Thanks, this is exactly what I needed!

**Comment by ebbit1q** [comment]
you're welcome
