### ISSUE TITLE
Can't uncheck "notify in taskbar when users in buddy list connect" box

### ISSUE THREAD

**Issue by Zandercat** [Cockatrice/Cockatrice#4355]
**System Information:** Mac OS X Big Sur

_______________________________________________________________________________________

When attempting to disable these notifications, I found that the notification checkbox was greyed out.

![image](https://user-images.githubusercontent.com/42007489/118371279-e5712580-b579-11eb-8714-dc9417d02b0d.png)

Checking the other two boxes did not cause it to become checkable. I did manage to resolve the issue by checking both of the other two boxes, then restarting the application, at which point the third option ceased to be greyed out and I was able to uncheck it normally.

_______________________________________________________________________________________

**Steps to reproduce:**
 - Do A
 - Do B
 - Do C ...

Unfortunately, I do not know how to reproduce this bug.

**Comment by ebbit1q** [comment]
as I read it reproducing this should be relatively easy:
- check notify in taskbar
- uncheck enable notifications
- relaunch cockatrice

**Comment by Zandercat** [comment]
Ah, yep, that did it. I unchecked "enable notifications" with the other two
boxes checked, then relaunched trice. When I opened preferences again,
"enable notifications" was unchecked and the other two were checked and
greyed out. Checking "enable notifications" un-greyed "notify while
spectating", but not "notify for buddies."

**Comment by ebbit1q** [comment]
thanks for your bug report, you will find this change in a future release
