### ISSUE TITLE
Double "New sets are available" pop ups.

### ISSUE THREAD

**Issue by mainman879** [Cockatrice/Cockatrice#4385]
Client Version: 2.8.0 (2021-01-26)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.12.9
System Locale: en_US
Install Mode: Standard
_______________________________________________________________________________________

Whenever I get the "New Sets are Available" pop-up when starting the client, it creates two pop-ups. Both will prevent interaction with the rest of the client until they are both cleared away. Selecting "yes" to enable the set seems to work with both to top and bottom pop-up, but it seems weird for the client to create two of them.
_______________________________________________________________________________________

Steps: 
1. Wait for a new set. (Today it happened for AAFR~)
2. Get 2 pop-ups after updating card database or starting the client and it finds a new set automatically.

**Comment by ebbit1q** [comment]
can you show me a screenshot? I can't reproduce this issue

**Comment by tooomm** [comment]
Yes, very annoying issue for years: https://github.com/Cockatrice/Cockatrice/issues/3764

**Comment by ebbit1q** [comment]
it's a duplicate then

**Comment by tooomm** [comment]
I still give you your screenshot :P
![Untitled](https://user-images.githubusercontent.com/9874850/123491764-cef9c780-d617-11eb-85dd-a562a6ffa58d.png)

**Comment by mainman879** [comment]
Didn't realize it was a duplicate, thanks tooomm.

**Comment by ebbit1q** [comment]
if you want me to reopen this ticket and close the other I can, otherwise, comment on the original ticket please
