### ISSUE TITLE
PM attentiveness issue. 

### ISSUE THREAD

**Issue by smorgenstern73** [Cockatrice/Cockatrice#439]
Some backstory. I play and spec a lot of duel commander on cockatrice. It is one of the premier places to do so. That being said, when I am spectating, one of the most frustrating things is seeing play errors take place. Naturally the specs will have an easier time noticing these sorts of things than those in game, because we have less to think about.

For example: About 20 minutes ago, I was spec a 1v1 game with the spec chat not enabled. Player A casts Harmonize with a forest, 3 islands and a Mountain in play. Myself and another spec both PMed both players in an attempt to try to get their attention that an error had occurred. No success. After that, player N, Hymn to Tourached player A, followed by player A playing a mountain and casting SylvanPrime.

My request is that the client make it easier for spectators to alert participants in the game when a play error takes place. One method would be taking away the option to mute spectators in game. The other that I thought of after critique from u/woogerboy21 was that a PM would have an alert tone the first time that a player messages another (thereby opening a chat window) It might be possible to code an alert or Jump to the chat window itself. u/woogerboy21 brought up the discussion of abuse, but because it is possible to simply add a user to the ignore list, would it also not be possible to mute this feature after a spec messages you once?

**Comment by ZeldaZach** [comment]
Have you had a chance to look into this @poixen ?

**Comment by poixen** [comment]
The only way to edit the color of the tab is to apply CSS to it. Once you do that you lose ALL of the current tab formatting. It would be a **lot** of work to get it looking the same. 

Re-reading this issue:
+ The room was created to allow you to watch, not comment. This is the room creators decision.
+ Given that the room owner did not want you to message in-game, I think it would be wrong for us to overrule this with pings/alerts.
+ Its up to the players to spot mistakes.
+ Users can PM other users, if they need to. Maybe we need somthing more stand-out than the '!'. Maybe something more like the Green ball seen on the Server tab.
