### ISSUE TITLE
Somehow Blossoming Calm is not part of MH2 set

### ISSUE THREAD

**Issue by ziqueiros** [Cockatrice/Cockatrice#4392]
**System Information:**

_______________________________________________________________________________________

Blossoming Calm card doesn't appear on the cards list.

_______________________________________________________________________________________

**Steps to reproduce:**
 - Do a search for Blossoming Calm on text search

_______________________________________________________________________________________

PictureLoader: [card:  "Blossoming Sands"  set:  "M21" ]: Trying to load picture
PictureLoader: [card:  "Blossoming Sands"  set:  "M21" ]: Picture found on disk.
PictureLoader: [card:  "Blossoming Defense"  set:  "KLR" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Blossoming Defense"  set:  "KLR" ]: Requested set property ( "muid" ) for Url template ( "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Blossoming Defense"  set:  "KLR" ]: Trying to load picture
PictureLoader: [card:  "Blossoming Defense"  set:  "KLR" ]: Picture found on disk.

**Comment by mainman879** [comment]
It certainly does show for me. You need to update your cards at Help->Check for Card Updates.

**Comment by ebbit1q** [comment]
I'll assume this issue has been resolved in the mean time
