### ISSUE TITLE
Both CI builds for windows are failing

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#4401]
I spotted this after the most recent merge to master happened (https://github.com/Cockatrice/Cockatrice/pull/4398).

64-bit and 32-bit builds are failing in the `Restore or setup vcpkg` step:
https://github.com/Cockatrice/Cockatrice/runs/3157059370

It looks like the issue was already visible in the PR itself: https://github.com/Cockatrice/Cockatrice/actions/runs/1061233135

**Comment by ebbit1q** [comment]
vcpkg has to be updated most likely
