### ISSUE TITLE
Add the ability to pick a secret number

### ISSUE THREAD

**Issue by Jdrawer** [Cockatrice/Cockatrice#4412]
Wheel of Misfortune requires players to simultaneously choose secret numbers. I am requesting some sort of in-app feature that makes resolving this spell easier. Many thanks for looking at this ticket.

**Comment by mainman879** [comment]
Duplicate of https://github.com/Cockatrice/Cockatrice/issues/3278

**Comment by ebbit1q** [comment]
please leave a comment on existing tickets before opening new ones

**Comment by Daenyth** [comment]
> please leave a comment on existing tickets before opening new ones

I suggested they open it, didn't think to check first. Oops
