### ISSUE TITLE
Undo Mulligan

### ISSUE THREAD

**Issue by MotherofRuins** [Cockatrice/Cockatrice#4429]
It would be great to have an undo for mulligans.  I'd guess anytime you would mulligans the game saves the old state briefly in case Undo Mulligan is the very next command.

**Comment by ZeldaZach** [comment]
Before you can mulligan, a popup appears asking how many cards to draw. This popup can be dismissed, thus canceling the mulligan. I don't feel adding another layer of popups or server memory saving the state is worth it as we'd have to store the deck order and hand before a mulligan takes place. We also don't know when we could safely discard this data, and it can lead to some wonky states. 

Unfortunately, I think this is one we're going to have to pass on at this time. I just see too many complications coming about and we already have a baseline protection in place thanks to your prior ticket
