### ISSUE TITLE
Mac Do Not Disturb

### ISSUE THREAD

**Issue by ZeldaZach** [Cockatrice/Cockatrice#443]
On a Mac, the cockatrice icon bounces every time an action occurs (a game move takes place, a private chat, etc.)

I was thinking that this could be edited in the settings so we could determine when it would bounce. I'm not a fan of it bouncing every second when I'm spectating a game and change tabs to go on Facebook for something.

Another alternate solution is for it to have the mac red circle with a number in it to indicate "notification"

**Comment by Daenyth** [comment]
http://stackoverflow.com/questions/25365387/how-to-set-badge-notification-for-qt-on-mac

**Comment by ZeldaZach** [comment]
This was partially fixed in #712 

Would still like badge notifications, but this issue is solved as is.
