### ISSUE TITLE
Line Breaks in Annotations

### ISSUE THREAD

**Issue by MotherofRuins** [Cockatrice/Cockatrice#4430]
Would love to be able to type Shift-Enter or some such to put line breaks in annotations.

**Comment by ZeldaZach** [comment]
Bounty established

**Comment by MotherofRuins** [comment]
Thank you for this, but if I may request a slight change.  I'd prefer Enter is bound to the OK button and use Shift-Enter for newlines in the annotation.  The dialog can alert people to the Shift-Enter behavior.
