### ISSUE TITLE
Problem handling a card named as a token

### ISSUE THREAD

**Issue by ctrlaltca** [Cockatrice/Cockatrice#445]
There's an old card from "Legends" named "Kobolds of Kher Keep".
Unfortunately a token by the same exact name exists, too (The card named "Kher Keep" from Commander 2013 is an example of a card generating such a token).
It seems that having this card present both in the card database and in the token database makes cockatrice unable to correctly show the sets the card exists in; only a set with an empty name is shown, while i suppose "LEG, TK" would be more desirable

**Comment by ZeldaZach** [comment]
Due to the diff name of the token version, this isn't an issue.
