### ISSUE TITLE
Can't Drag Cards from Hand to Top of Library

### ISSUE THREAD

**Issue by dmmyccnt** [Cockatrice/Cockatrice#4463]
**System Information:**

Client Version: 2.8.1-beta.4 (2021-11-04)
Client Operating System: Windows 10 Version 2009
Build Architecture: 64-bit
Qt Version: 5.15.2
System Locale: en_US
Install Mode: Standard
_______________________________________________________________________________________

When playing a local game with 2 players, if either player tries to drag several cards from their hand back onto the top of their library in sequence, the game will gradually stop allowing any cards to be dragged out of the hand.

When dragging the first four or five cards from the hand onto the top of the library, it works fine. After the first five, it seems that some cards are still able to be dragged onto the top of the library (more often land cards and cards that are on the left side of the hand box, closer to the library), while others (usually spells and cards farther to the right, farther away from the library) seem not to be able to be dragged onto the library, although, in general, the distribution of which cards can be dragged and which can't appears totally random.

It also seems that, the larger the number of cards in hand at the time that you start to drag them back, the more consistently cards aren't allowed to be dragged out of the hand.

A hand with fewer cards in it seems to be able to drag a larger number of them out onto the library.

If the cards are dragged onto the battlefield first, then dragged onto the top of the library, there doesn't seem to be a problem. Directly dragging a large number of cards from the hand onto the top of the library, one-by-one (not simultaneously) causes the game to slowly prevent them from being dragged out of the hand.

If a very large number of cards are still in the hand after finding nine or ten cards that can be dragged onto the top of the library, Cockatrice consistently crashes for me.

This happens to both player 1 and player 2 when they perform this sequence of events.

_______________________________________________________________________________________

**Steps to reproduce:**
 - Draw a large number of cards (try 14 as an example)
 - Start to drag cards one by one from your hand back on top of your library
 - The app will stop allowing all cards to be dragged
 - If a large number of cards are still in hand, eventually the app will crash

**Extra Debug Log Information**

Theme changed: "VelvetMarble"
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
Language changed: ""
main(): starting main program
Unable to enumerate family ' "Noto Sans Inscriptional Parthian" '
main(): MainWindow constructor finished
Spoilers Disabled
main(): ui.show() finished
Startup: found config with current version
CardDatabase::loadCardDatabases start
[CockatriceXml4Parser] Trying to parse:  "C:/Users/dmmyc/AppData/Local/Cockatrice/Cockatrice/cards.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
QWindowsWindow::setGeometry: Unable to set geometry 1920x1065+0+29 (frame: 1938x1112-9-9) on QWidgetWindow/"MainWindowClassWindow" on "\\.\DISPLAY1". Resulting geometry: 1920x1051+0+29 (frame: 1938x1098-9-9) margins: 9, 38, 9, 9 minimum size: 879x1065 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=897,1112 maxtrack=0,0)
PictureLoader: cache fail for "_trice_card_back_256239"
PictureLoader: cache fail for "_trice_card_back_256237"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/dmmyc/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 23810 Sets = 590 "1064ms"
[CockatriceXml4Parser] Trying to parse:  "C:/Users/dmmyc/AppData/Local/Cockatrice/Cockatrice/tokens.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
[CardDatabase] loadCardDatabase(): Path = "C:/Users/dmmyc/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 24356 Sets = 590 "29ms"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/dmmyc/AppData/Local/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 24356 Sets = 590 "0ms"
CardDatabase::loadCardDatabases success

Adding room: ID= 0 name= ""
Server::loginUser: LocalServerInterface(0x1e5fea55df0) name= "Player 1"
session id: 0
Server::loginUser: LocalServerInterface(0x1e5fea57b30) name= "Player 2"
session id: 0
gameEvent: invalid gameId
Server_AbstractUserInterface::playerAddedToGame(): gameId = 1
GameScene::addPlayer name= "Player 2"
Server_AbstractUserInterface::playerAddedToGame(): gameId = 1
GameScene::addPlayer name= "Player 1"
PictureLoader: cache fail for "_trice_card_back_250100"
PictureLoader: cache fail for "_trice_card_back_566632"
PictureLoader: cache fail for "_trice_card_back_566633"
Deck was loaded - true
PictureLoader: [card:  "Island"  set:  "VOW" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Island"  set:  "VOW" ]: Requested set property ( "muid" ) for Url template ( "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Mistmoon Griffin"  set:  "VMA" ]: Trying to load picture
PictureLoader: [card:  "Man-o'-War"  set:  "J21" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Man-o'-War"  set:  "J21" ]: Requested set property ( "muid" ) for Url template ( "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Impulse"  set:  "MB1" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Impulse"  set:  "MB1" ]: Requested set property ( "muid" ) for Url template ( "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Vodalian Illusionist"  set:  "PLIST" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Vodalian Illusionist"  set:  "PLIST" ]: Requested set property ( "muid" ) for Url template ( "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Disrupt"  set:  "WC02" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Disrupt"  set:  "WC02" ]: Requested set property ( "muid" ) for Url template ( "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Empyrial Armor"  set:  "MB1" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Empyrial Armor"  set:  "MB1" ]: Requested set property ( "muid" ) for Url template ( "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Plains"  set:  "VOW" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Plains"  set:  "VOW" ]: Requested set property ( "muid" ) for Url template ( "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Pacifism"  set:  "ANB" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Pacifism"  set:  "ANB" ]: Requested set property ( "muid" ) for Url template ( "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Mistmoon Griffin"  set:  "VMA" ]: Picture found on disk.
PictureLoader: [card:  "Heavy Ballista"  set:  "7ED" ]: Trying to load picture
PictureLoader: [card:  "Heavy Ballista"  set:  "7ED" ]: Picture found on disk.
PictureLoader: [card:  "Serrated Biskelion"  set:  "DDF" ]: Trying to load picture
PictureLoader: [card:  "Serrated Biskelion"  set:  "DDF" ]: Picture found on disk.
PictureLoader: [card:  "Alabaster Dragon"  set:  "WTH" ]: Trying to load picture
PictureLoader: [card:  "Alabaster Dragon"  set:  "WTH" ]: Picture found on disk.
PictureLoader: [card:  "Memory Lapse"  set:  "STA" ]: Trying to load picture
PictureLoader: [card:  "Memory Lapse"  set:  "STA" ]: Picture found on disk.
PictureLoader: [card:  "Waterspout Djinn"  set:  "JVC" ]: Trying to load picture
PictureLoader: [card:  "Waterspout Djinn"  set:  "JVC" ]: Picture found on disk.
PictureLoader: [card:  "Island"  set:  "VOW" ]: Trying to load picture
PictureLoader: [card:  "Island"  set:  "VOW" ]: Picture found on disk.
PictureLoader: [card:  "Man-o'-War"  set:  "J21" ]: Trying to load picture
PictureLoader: [card:  "Man-o'-War"  set:  "J21" ]: Picture found on disk.
PictureLoader: [card:  "Debt of Loyalty"  set:  "WTH" ]: Trying to load picture
PictureLoader: [card:  "Debt of Loyalty"  set:  "WTH" ]: Picture found on disk.
PictureLoader: [card:  "Cloud Djinn"  set:  "VMA" ]: Trying to load picture
PictureLoader: [card:  "Cloud Djinn"  set:  "VMA" ]: Picture found on disk.
PictureLoader: [card:  "Power Sink"  set:  "VMA" ]: Trying to load picture
PictureLoader: [card:  "Power Sink"  set:  "VMA" ]: Picture found on disk.
PictureLoader: [card:  "Impulse"  set:  "MB1" ]: Trying to load picture
PictureLoader: [card:  "Impulse"  set:  "MB1" ]: Picture found on disk.
PictureLoader: [card:  "Sage Owl"  set:  "M10" ]: Trying to load picture
PictureLoader: [card:  "Sage Owl"  set:  "M10" ]: Picture found on disk.
PictureLoader: [card:  "Vodalian Illusionist"  set:  "PLIST" ]: Trying to load picture
PictureLoader: [card:  "Vodalian Illusionist"  set:  "PLIST" ]: Picture found on disk.
PictureLoader: [card:  "Abduction"  set:  "6ED" ]: Trying to load picture
PictureLoader: [card:  "Abduction"  set:  "6ED" ]: Picture found on disk.
PictureLoader: [card:  "Disrupt"  set:  "WC02" ]: Trying to load picture
PictureLoader: [card:  "Disrupt"  set:  "WC02" ]: Picture found on disk.
PictureLoader: [card:  "Empyrial Armor"  set:  "MB1" ]: Trying to load picture
PictureLoader: [card:  "Empyrial Armor"  set:  "MB1" ]: Picture found on disk.
PictureLoader: [card:  "Benalish Knight"  set:  "10E" ]: Trying to load picture
PictureLoader: [card:  "Benalish Knight"  set:  "10E" ]: Picture found on disk.
PictureLoader: [card:  "Fog Elemental"  set:  "10E" ]: Trying to load picture
PictureLoader: [card:  "Fog Elemental"  set:  "10E" ]: Picture found on disk.
PictureLoader: [card:  "Plains"  set:  "VOW" ]: Trying to load picture
PictureLoader: [card:  "Plains"  set:  "VOW" ]: Picture found on disk.
PictureLoader: [card:  "Pacifism"  set:  "ANB" ]: Trying to load picture
PictureLoader: [card:  "Pacifism"  set:  "ANB" ]: Picture found on disk.
PictureLoader: [card:  "Dissipate"  set:  "MID" ]: Trying to load picture
PictureLoader: [card:  "Dissipate"  set:  "MID" ]: Picture found on disk.
PictureLoader: [card:  "Ophidian"  set:  "JVC" ]: Trying to load picture
PictureLoader: [card:  "Ophidian"  set:  "JVC" ]: Picture found on disk.
PictureLoader: [card:  "Suq'Ata Firewalker"  set:  "MIR" ]: Trying to load picture
PictureLoader: [card:  "Suq'Ata Firewalker"  set:  "MIR" ]: Picture found on disk.
Unable to enumerate family ' "Noto Sans Inscriptional Parthian" '
PictureLoader: [card:  "Island"  set:  "VOW" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Island"  set:  "VOW" ]: Requested set property ( "muid" ) for Url template ( "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Island"  set:  "VOW" ]: Trying to load picture
PictureLoader: [card:  "Island"  set:  "VOW" ]: Picture found on disk.
PictureLoader: [card:  "Plains"  set:  "VOW" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Plains"  set:  "VOW" ]: Requested set property ( "muid" ) for Url template ( "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Plains"  set:  "VOW" ]: Trying to load picture
PictureLoader: [card:  "Man-o'-War"  set:  "J21" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Man-o'-War"  set:  "J21" ]: Requested set property ( "muid" ) for Url template ( "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Plains"  set:  "VOW" ]: Picture found on disk.
PictureLoader: [card:  "Alabaster Dragon"  set:  "WTH" ]: Trying to load picture
PictureLoader: [card:  "Vodalian Illusionist"  set:  "PLIST" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Vodalian Illusionist"  set:  "PLIST" ]: Requested set property ( "muid" ) for Url template ( "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Empyrial Armor"  set:  "MB1" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Empyrial Armor"  set:  "MB1" ]: Requested set property ( "muid" ) for Url template ( "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Pacifism"  set:  "ANB" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Pacifism"  set:  "ANB" ]: Requested set property ( "muid" ) for Url template ( "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Disrupt"  set:  "WC02" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Disrupt"  set:  "WC02" ]: Requested set property ( "muid" ) for Url template ( "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Impulse"  set:  "MB1" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Impulse"  set:  "MB1" ]: Requested set property ( "muid" ) for Url template ( "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Alabaster Dragon"  set:  "WTH" ]: Picture found on disk.
PictureLoader: [card:  "Benalish Knight"  set:  "10E" ]: Trying to load picture
PictureLoader: [card:  "Benalish Knight"  set:  "10E" ]: Picture found on disk.
PictureLoader: [card:  "Cloud Djinn"  set:  "VMA" ]: Trying to load picture
PictureLoader: [card:  "Cloud Djinn"  set:  "VMA" ]: Picture found on disk.
PictureLoader: [card:  "Fog Elemental"  set:  "10E" ]: Trying to load picture
PictureLoader: [card:  "Fog Elemental"  set:  "10E" ]: Picture found on disk.
PictureLoader: [card:  "Heavy Ballista"  set:  "7ED" ]: Trying to load picture
PictureLoader: [card:  "Heavy Ballista"  set:  "7ED" ]: Picture found on disk.
PictureLoader: [card:  "Man-o'-War"  set:  "J21" ]: Trying to load picture
PictureLoader: [card:  "Man-o'-War"  set:  "J21" ]: Picture found on disk.
PictureLoader: [card:  "Mistmoon Griffin"  set:  "VMA" ]: Trying to load picture
PictureLoader: [card:  "Mistmoon Griffin"  set:  "VMA" ]: Picture found on disk.
PictureLoader: [card:  "Ophidian"  set:  "JVC" ]: Trying to load picture
PictureLoader: [card:  "Ophidian"  set:  "JVC" ]: Picture found on disk.
PictureLoader: [card:  "Sage Owl"  set:  "M10" ]: Trying to load picture
PictureLoader: [card:  "Sage Owl"  set:  "M10" ]: Picture found on disk.
PictureLoader: [card:  "Serrated Biskelion"  set:  "DDF" ]: Trying to load picture
PictureLoader: [card:  "Serrated Biskelion"  set:  "DDF" ]: Picture found on disk.
PictureLoader: [card:  "Suq'Ata Firewalker"  set:  "MIR" ]: Trying to load picture
PictureLoader: [card:  "Suq'Ata Firewalker"  set:  "MIR" ]: Picture found on disk.
PictureLoader: [card:  "Vodalian Illusionist"  set:  "PLIST" ]: Trying to load picture
PictureLoader: [card:  "Vodalian Illusionist"  set:  "PLIST" ]: Picture found on disk.
PictureLoader: [card:  "Waterspout Djinn"  set:  "JVC" ]: Trying to load picture
PictureLoader: [card:  "Waterspout Djinn"  set:  "JVC" ]: Picture found on disk.
PictureLoader: [card:  "Abduction"  set:  "6ED" ]: Trying to load picture
PictureLoader: [card:  "Abduction"  set:  "6ED" ]: Picture found on disk.
PictureLoader: [card:  "Empyrial Armor"  set:  "MB1" ]: Trying to load picture
PictureLoader: [card:  "Empyrial Armor"  set:  "MB1" ]: Picture found on disk.
PictureLoader: [card:  "Pacifism"  set:  "ANB" ]: Trying to load picture
PictureLoader: [card:  "Pacifism"  set:  "ANB" ]: Picture found on disk.
PictureLoader: [card:  "Debt of Loyalty"  set:  "WTH" ]: Trying to load picture
PictureLoader: [card:  "Debt of Loyalty"  set:  "WTH" ]: Picture found on disk.
PictureLoader: [card:  "Disrupt"  set:  "WC02" ]: Trying to load picture
PictureLoader: [card:  "Disrupt"  set:  "WC02" ]: Picture found on disk.
PictureLoader: [card:  "Dissipate"  set:  "MID" ]: Trying to load picture
PictureLoader: [card:  "Dissipate"  set:  "MID" ]: Picture found on disk.
PictureLoader: [card:  "Impulse"  set:  "MB1" ]: Trying to load picture
PictureLoader: [card:  "Impulse"  set:  "MB1" ]: Picture found on disk.
PictureLoader: [card:  "Memory Lapse"  set:  "STA" ]: Trying to load picture
PictureLoader: [card:  "Memory Lapse"  set:  "STA" ]: Picture found on disk.
PictureLoader: [card:  "Power Sink"  set:  "VMA" ]: Trying to load picture
PictureLoader: [card:  "Power Sink"  set:  "VMA" ]: Picture found on disk.
Deck was loaded - true
PictureLoader: [card:  "Compulsion"  set:  "WC03" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Compulsion"  set:  "WC03" ]: Requested set property ( "muid" ) for Url template ( "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Concentrate"  set:  "MB1" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Concentrate"  set:  "MB1" ]: Requested set property ( "muid" ) for Url template ( "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Compulsion"  set:  "WC03" ]: Trying to load picture
PictureLoader: [card:  "Wonder"  set:  "J21" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Wonder"  set:  "J21" ]: Requested set property ( "muid" ) for Url template ( "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Fiery Temper"  set:  "J21" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Fiery Temper"  set:  "J21" ]: Requested set property ( "muid" ) for Url template ( "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Mountain"  set:  "VOW" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Mountain"  set:  "VOW" ]: Requested set property ( "muid" ) for Url template ( "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Compulsion"  set:  "WC03" ]: Picture found on disk.
PictureLoader: [card:  "Churning Eddy"  set:  "TOR" ]: Trying to load picture
PictureLoader: [card:  "Compulsion"  set:  "WC03" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Compulsion"  set:  "WC03" ]: Requested set property ( "muid" ) for Url template ( "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Churning Eddy"  set:  "TOR" ]: Picture found on disk.
PictureLoader: [card:  "Concentrate"  set:  "MB1" ]: Trying to load picture
PictureLoader: [card:  "Concentrate"  set:  "MB1" ]: Picture found on disk.
PictureLoader: [card:  "Barbarian Lunatic"  set:  "ODY" ]: Trying to load picture
PictureLoader: [card:  "Barbarian Lunatic"  set:  "ODY" ]: Picture found on disk.
PictureLoader: [card:  "Shower of Coals"  set:  "ODY" ]: Trying to load picture
PictureLoader: [card:  "Shower of Coals"  set:  "ODY" ]: Picture found on disk.
PictureLoader: [card:  "Aven Windreader"  set:  "10E" ]: Trying to load picture
PictureLoader: [card:  "Aven Windreader"  set:  "10E" ]: Picture found on disk.
PictureLoader: [card:  "Violent Eruption"  set:  "C19" ]: Trying to load picture
PictureLoader: [card:  "Violent Eruption"  set:  "C19" ]: Picture found on disk.
PictureLoader: [card:  "Hapless Researcher"  set:  "JUD" ]: Trying to load picture
PictureLoader: [card:  "Hapless Researcher"  set:  "JUD" ]: Picture found on disk.
PictureLoader: [card:  "Lava Dart"  set:  "MH1" ]: Trying to load picture
PictureLoader: [card:  "Lava Dart"  set:  "MH1" ]: Picture found on disk.
PictureLoader: [card:  "Flash of Insight"  set:  "JUD" ]: Trying to load picture
PictureLoader: [card:  "Flash of Insight"  set:  "JUD" ]: Picture found on disk.
PictureLoader: [card:  "Worldgorger Dragon"  set:  "EMA" ]: Trying to load picture
PictureLoader: [card:  "Worldgorger Dragon"  set:  "EMA" ]: Picture found on disk.
PictureLoader: [card:  "Scalpelexis"  set:  "10E" ]: Trying to load picture
PictureLoader: [card:  "Scalpelexis"  set:  "10E" ]: Picture found on disk.
PictureLoader: [card:  "Wonder"  set:  "J21" ]: Trying to load picture
PictureLoader: [card:  "Wonder"  set:  "J21" ]: Picture found on disk.
PictureLoader: [card:  "Barbarian Bully"  set:  "JUD" ]: Trying to load picture
PictureLoader: [card:  "Barbarian Bully"  set:  "JUD" ]: Picture found on disk.
PictureLoader: [card:  "Swelter"  set:  "JUD" ]: Trying to load picture
PictureLoader: [card:  "Swelter"  set:  "JUD" ]: Picture found on disk.
PictureLoader: [card:  "Dwarven Scorcher"  set:  "JUD" ]: Trying to load picture
PictureLoader: [card:  "Dwarven Scorcher"  set:  "JUD" ]: Picture found on disk.
PictureLoader: [card:  "Wormfang Turtle"  set:  "JUD" ]: Trying to load picture
PictureLoader: [card:  "Wormfang Turtle"  set:  "JUD" ]: Picture found on disk.
PictureLoader: [card:  "Aven Fisher"  set:  "10E" ]: Trying to load picture
PictureLoader: [card:  "Aven Fisher"  set:  "10E" ]: Picture found on disk.
PictureLoader: [card:  "Fiery Temper"  set:  "J21" ]: Trying to load picture
PictureLoader: [card:  "Fiery Temper"  set:  "J21" ]: Picture found on disk.
PictureLoader: [card:  "Mountain"  set:  "VOW" ]: Trying to load picture
PictureLoader: [card:  "Mountain"  set:  "VOW" ]: Picture found on disk.
PictureLoader: [card:  "Chainflinger"  set:  "ODY" ]: Trying to load picture
PictureLoader: [card:  "Chainflinger"  set:  "ODY" ]: Picture found on disk.
PictureLoader: [card:  "Skywing Aven"  set:  "UMA" ]: Trying to load picture
PictureLoader: [card:  "Skywing Aven"  set:  "UMA" ]: Picture found on disk.
PictureLoader: [card:  "Compulsion"  set:  "WC03" ]: Trying to load picture
PictureLoader: [card:  "Compulsion"  set:  "WC03" ]: Picture found on disk.

addCounter: "Player 1" 0 "life"
addCounter: "Player 1" 1 "w"
addCounter: "Player 1" 2 "u"
addCounter: "Player 1" 3 "b"
addCounter: "Player 1" 4 "r"
addCounter: "Player 1" 5 "g"
addCounter: "Player 1" 6 "x"
addCounter: "Player 1" 7 "storm"
addCounter: "Player 2" 0 "life"
addCounter: "Player 2" 1 "w"
addCounter: "Player 2" 2 "u"
addCounter: "Player 2" 3 "b"
addCounter: "Player 2" 4 "r"
addCounter: "Player 2" 5 "g"
addCounter: "Player 2" 6 "x"
addCounter: "Player 2" 7 "storm"
addCounter: "Player 1" 0 "life"
addCounter: "Player 1" 1 "w"
addCounter: "Player 1" 2 "u"
addCounter: "Player 1" 3 "b"
addCounter: "Player 1" 4 "r"
addCounter: "Player 1" 5 "g"
addCounter: "Player 1" 6 "x"
addCounter: "Player 1" 7 "storm"
addCounter: "Player 2" 0 "life"
addCounter: "Player 2" 1 "w"
addCounter: "Player 2" 2 "u"
addCounter: "Player 2" 3 "b"
addCounter: "Player 2" 4 "r"
addCounter: "Player 2" 5 "g"
addCounter: "Player 2" 6 "x"
addCounter: "Player 2" 7 "storm"
PictureLoader: cache fail for "_trice_card_back_6998"
QPixmap::scaled: Pixmap is a null pixmap
PictureLoader: cache fail for "_trice_card_back_566633"

**Comment by madmox** [comment]
This bug is not random at all and very easy to reproduce. It also doen't involve the number of cards in your hand, and it makes this software version almost unusable for me.

Steps to reproduce:
* start a new 2-players local game ;
* draw initial hand of 7 cards ;
* drag any set of cards from your hand **not including the first one** (which is the top card when you use vertical hand display) on top of your library.

It looks like the card index in the hand is not handled properly. If you drag card n°3 from your hand on top of your library, then card n°2 is actually moved on top when you release the mouse. Card n°3 stays in your hand and becomes unmovable (you can no longer perform any action involving the card, it's just stuck in your hand), while **also** being on top of the library. While card n°2 has simply disappeared from your deck...

Fun side-effect: if you repeatedly move card n°7 from your hand on top of your library and draw it back, you can actually build yourself a hand of 7 unmovable copies of the same card.

**Comment by ebbit1q** [comment]
thanks for the detailed reproduction steps, this makes fixing this issue much easier
