### ISSUE TITLE
Crash when right-click context menu is open on card in graveyard or exile and that card changes zone

### ISSUE THREAD

**Issue by a-gorman** [Cockatrice/Cockatrice#4465]
If you have a right-click context menu open on a card in either a graveyard or in exile, the client will crash when that card changes zone.

Steps to reproduce:
1. Put a card in User 1's graveyard.
2. Have User 2 open the graveyard/exile and then open the right-click context menu on that card.
3. Have User 1 move that card to the battlefield while the menu is still open.
4. Observe User 2's client crash to desktop

Cockatrice version 2.8.0
Reproduced on Windows 10.

**Comment by ebbit1q** [comment]
does this issue happen online or locally? does it still occur when using the latest beta?

**Comment by madmox** [comment]
> does this issue happen online or locally?

You cannot move a card while also having the right-click context menu open (any click or keystroke by a user having this menu open will close it), so the bug can only happen online. I don't play online so I cannot tell you if the beta is still bugged, but it shouldn't be hard to reproduce, the OP's bug description is clear enough.
