### ISSUE TITLE
Pasting card name from Excel into search bar includes linefeed character

### ISSUE THREAD

**Issue by MotherofRuins** [Cockatrice/Cockatrice#4494]
When I copy a card name from an Excel cell and paste into the deck editor search bar, for some reason there is what appears to be a space character at the end.  It's actually a linefeed (ASCII 10).  That prevents the card from turning up in search results until I manually delete it.  Pasting into emacs adds the linefeed as well.  Pasting into TCGPlayer search works fine, they must strip the non-printing characters.  Request that CR, LF, and possibly other ascii control characters be stripped when pasted into deck editor search bar.

Reproduce:  Highlight and copy the following two lines.  Paste into search bar.  Text appears correct but search fails.

Abominable
Treefolk

**Comment by ZeldaZach** [comment]
Bounty established
