### ISSUE TITLE
Card missing in database

### ISSUE THREAD

**Issue by Ryuu-Haku** [Cockatrice/Cockatrice#4495]
Hello,
I don't know if it's the good place to speak about this, but since few month, I need a card that is not in the database which is "Unexpected Windfall" from D&D edition.
I tried to put the same message in the mtgjson discord but they are saying that is a Cockatrice problem...
I update the card database every time with the link https://www.mtgjson.com/api/v5/AllPrintings.json.xz but every time, the card is missing.
Thank you to help me on this.

**Comment by ebbit1q** [comment]
go to the set manager and make sure that afr is enabled

**Comment by Ryuu-Haku** [comment]
It was simply that... sorry for the inconvenience !!
Thank you very much for the help !

**Comment by ebbit1q** [comment]
you're welcome
