### ISSUE TITLE
Inevitable Betrayal missing?

### ISSUE THREAD

**Issue by cerietke** [Cockatrice/Cockatrice#4498]
I've opened all sets and I've opened MH2, in both cases I am unable to find the card Inevitable Betrayal.

**Comment by ebbit1q** [comment]
have you tried updating your card database? it's at help>check for card updates...
also make sure that the set mh2 is enabled in your sets manager

**Comment by cerietke** [comment]
No updates available. I tried both all sets and MH2, it was not there.

**Comment by ebbit1q** [comment]
it is, there is no prompt that says no updates available in the card updater, it always overwrites no matter what. go to help>check for card updates
if the option is not there for you you most likely are not using the most recent version, try reinstalling from our downloads.

**Comment by cerietke** [comment]
Forcing the update indeed solved it, thanks.

**Comment by ebbit1q** [comment]
you're welcome
