### ISSUE TITLE
Moving Cards from Hand to Library Doesn't Work in Local Game

### ISSUE THREAD

**Issue by dmmyccnt** [Cockatrice/Cockatrice#4502]
**System Information:**

Client Version: 2.8.1-beta.4 (2021-11-04)
Client Operating System: Windows 10 Version 2009
Build Architecture: 64-bit
Qt Version: 5.15.2
System Locale: en_US
Install Mode: Standard
_______________________________________________________________________________________

If you open a local game, draw more than 1 card, then try to move any card other than the left-most or top-most card of your hand back onto the top of your library, that card does not leave your hand. Instead, the left-most or the top-most card goes back onto the top of your library and the card that you tried to move becomes locked in your hand. That card can no longer leave your hand or be put into any other zone by any means.

This happens for both dragging the cards from the hand onto the library with the mouse, or selecting "Move to -> Top of Library" in the right click menu. It happens to any player who attempts it and it will happen with any number of cards in-hand greater than 1.

_______________________________________________________________________________________

**Steps to reproduce:**
 - Load a local game
 - Draw two or more cards
 - Try to move cards from hand back onto the top of the library

**Comment by ebbit1q** [comment]
please try again but using the new beta https://github.com/Cockatrice/Cockatrice/releases/tag/2021-12-20-Development-2.8.1-beta.5

**Comment by dmmyccnt** [comment]
Thanks! Sorry about that! I filed that report like 30 minutes before the
new beta was uploaded.

The new beta is great! Worlds like a charm and I played a Pharaoh game with
it tonight!

Thank you for all your hard work and amazing gift to the Gathering.
