### ISSUE TITLE
Unable to scale

### ISSUE THREAD

**Issue by DrAwkward33** [Cockatrice/Cockatrice#451]
I running cockatrice on a yoga pro with the native resolution at 3200 x 1800 and i can barely read card text and the UI is rather cramped. Any way to maybe fix this?

**Comment by Daenyth** [comment]
Related to #143 I think

**Comment by ZeldaZach** [comment]
Any new information on this @ctrlaltca ?

**Comment by ctrlaltca** [comment]
I have no such high resolution monitor to test recent builds on. @DrAwkward33 Can you give it a run?

**Comment by ctrlaltca** [comment]
Closing for #1937
