### ISSUE TITLE
Constant disconnect

### ISSUE THREAD

**Issue by jbozelli92** [Cockatrice/Cockatrice#4536]
**System Information:**

Windows 10
Logs attached in the ticket
_______________________________________________________________________________________

After a certain amount of minutes, even if I am active, I keep getting timeouts. Error is:

Player destructor: "TheArchitectXX"
GameScene::removePlayer name= "TheArchitectXX"
_______________________________________________________________________________________

**Steps to reproduce:**
After opening the client and starting a game, in 5 to 7 minutes time I will get a timeout

**Comment by jbozelli92** [comment]
![SS](https://user-images.githubusercontent.com/64626694/150290567-16d03181-647c-4c73-9255-a0b6bea8bd8e.PNG)
[logs.txt](https://github.com/Cockatrice/Cockatrice/files/7903020/logs.txt)

**Comment by ebbit1q** [comment]
this is a know issue with specifically the Rooster Ranges server, it is related to your isp's ipv6 connection, disabling ipv6 on your system will avoid the issue
