### ISSUE TITLE
Password too short error even though is not

### ISSUE THREAD

**Issue by the-glima** [Cockatrice/Cockatrice#4538]
**System Information:**
Client Version: 2.8.1-beta.6 (2022-01-16)
Client Operating System: macOS 12.0
Build Architecture: 64-bit
Qt Version: 5.15.2
System Locale: en_US
Install Mode: Standard
_______________________________________________________________________________________

Just installed, trying to register an account and it keep saying that my password is too short.
I've tried with 15|18|30|82 characters, same thing. Tried with different email, different name, same error, nothing on the debug log.

![Screen Shot 2022-01-20 at 17 49 15](https://user-images.githubusercontent.com/1394578/150420787-55915698-87b8-4659-b58f-fd83ea7b0a91.png)

![Screen Shot 2022-01-20 at 17 49 23](https://user-images.githubusercontent.com/1394578/150420809-f1690b47-d468-45da-b59e-da80d7f0e345.png)

![image](https://user-images.githubusercontent.com/1394578/150420992-6e23fd2e-8fa7-4486-8dc1-5c6d9809d086.png)

_______________________________________________________________________________________

**Steps to reproduce:**
 - Open Cockatrice
 - Click on Actions > Register to Server
 - Fill the form and click ok

**Comment by ebbit1q** [comment]
that's because Rooster Ranges is not updated with the latest version and is actually using an intermediate version that supports the new login structure but not the new registration messages, you'll be able to register using an older version of cockatrice

**Comment by ebbit1q** [comment]
we've updated rooster ranges to the latest version now
