### ISSUE TITLE
Emrakul, the promised end art is missing.

### ISSUE THREAD

**Issue by Pezblaster** [Cockatrice/Cockatrice#4545]
**System Information:**

Windows 10
_____________________________________________________________________________________

Emrakul the promised end is missing its art in-game. It appears as a white rectangle with the black highlighted white letters "Emrakul The Promised End"

put Emurakul the promised end into a deck in deck editor.
join a game and enjoy the pain.

**Comment by tooomm** [comment]
It's probably an issue on your end, but since you did not provide an log output or further details I can not really help.

The card is correctly downloaded and displayed for me with all sets enabled:
```
PictureLoader: [card:  "Emrakul, the Promised End"  set:  "PEMN" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Emrakul, the Promised End"  set:  "PEMN" ]: Requested set property ( "muid" ) for Url template ( "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Emrakul, the Promised End"  set:  "PEMN" ]: Trying to load picture
PictureLoader: [card:  "Emrakul, the Promised End"  set:  "PEMN" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Emrakul, the Promised End"  set:  "PEMN" ]: Trying to download picture from url: "https://api.scryfall.com/cards/df768328-6215-4653-9793-1e53384a9f45?format=image&face=front"
PictureLoader: [card:  "Emrakul, the Promised End"  set:  "PEMN" ]: following redirect: "https://c1.scryfall.com/file/scryfall-cards/large/front/d/f/df768328-6215-4653-9793-1e53384a9f45.jpg?1562942134"
PictureLoader: [card:  "Emrakul, the Promised End"  set:  "PEMN" ]: Image successfully downloaded from  "https://c1.scryfall.com/file/scryfall-cards/large/front/d/f/df768328-6215-4653-9793-1e53384a9f45.jpg?1562942134"
```

**Comment by ebbit1q** [comment]
please make sure you are using the most recent version of cockatrice and oracle, then update your card database using oracle or clicking help>check for card updates, then replicate the issue by searching for your missing card and send us the entire log from help>show debug log

**Comment by Pezblaster** [comment]
Everything is fine but thank you for the reply

**Comment by ebbit1q** [comment]
everything is fine now? did that fix your issue?

**Comment by tooomm** [comment]
Looks like the issue is solved. 👍 

Please come back to us with more details otherwise!
