### ISSUE TITLE
video tutorials on how to place cards and custom sets on cockatiel

### ISSUE THREAD

**Issue by Umbipolar** [Cockatrice/Cockatrice#4550]
**Similar Requests**

**Description of New Feature**

**Additional Context**

**Comment by Umbipolar** [comment]
please do video tutorials on how to place cards and custom sets on cockatiel. I tried reading the wiki but I couldn't.

**Comment by tooomm** [comment]
>how to place cards and custom sets on cockatiel. I tried reading the wiki but I couldn't.

Can you be more specific about your issues with the wiki?

How to construct the file:
https://github.com/Cockatrice/Cockatrice/wiki/Custom-Cards-&-Sets#to-add-your-own-custom-cards-follow-these-steps

How to add the file and use it in Cockatrice:
https://github.com/Cockatrice/Cockatrice/wiki/Custom-Cards-&-Sets#to-add-custom-sets-follow-these-steps
