### ISSUE TITLE
Issue with account creation

### ISSUE THREAD

**Issue by AphidBurthday** [Cockatrice/Cockatrice#4575]
Nkt sure if this is the right place to talk about this but I was told to post here through discord so I'm just gonna copy and paste my message cause I spent awhile trying to write it in a clear and intentional way. 

Hi there, I just downloaded cockatrice and was super excited to play with friends. unfortunately, when I made an account I came across something that upset me deeply. When I made my account name, the prompt told me that these words weren't allowed "adolf, hitler, *, *, *, *" I get that its important to moderate usernames, but when I saw those words listed so nonchalantly I felt disgusted. Listing off all the words that you hope to prevent users from seeing has had the opposite effect of what you're trying to achieve. Therefore I want to suggest that rather than listing these really awful words, just say that "names with racist, fascist, queerphobic, xenophobic, ableist, and mysoginist terms will not be permitted" and leave it at that. 

I appreciate you hearing me out and thank you for maintaining a rad resource that I can use to play with online friends.
-Aphid

**Comment by ebbit1q** [comment]
there are two possible approaches to this:
- we change the code on the client to only show the list when you click on an extra button
- we change the code on the server to add a field with a description of the list to the configuration file that replaces it

**Comment by AphidBurthday** [comment]
Does the second one mean the words arent shown at all? I personally feel
like those words dont need to be mentioned in writing besides in the coding
itsself, like the words should not be public facing in any form.

**Comment by ebbit1q** [comment]
to elaborate, cockatrice has two main components, the server and the client, the server is what the client connects to and is the one that sets the requirements for usernames, when a user enters a name that the server does not consider acceptable the server sends the client a message that contains which requirements are needed, the list of requirements is kept on the server and currently the client does not interpret the message sent by the server, it only displays it when the server sends it and does not use it to decide if the username is correct on its own

**Comment by AphidBurthday** [comment]
All right yeah that seems better, thanks for putting in the work ♡
