### ISSUE TITLE
Add configurable chat highlighting

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#458]
Users should be able to configure a list of highlight keywords. By default it should contain their username. When a line of chat comes in containing any of the keywords, all keywords should have a "highlight-word" css class applied and then the line should have a "highlight-line" css class applied.

We should provide a default css string, probably background color on the line, and bold/color on the word. The css string should be exposed in the user's configuration panel.

**Comment by tooomm** [comment]
is this finished?

**Comment by ZeldaZach** [comment]
I believe so :)
