### ISSUE TITLE
Manaform Hellkite

### ISSUE THREAD

**Issue by byoungfaminz** [Cockatrice/Cockatrice#4581]
**System Information:**

_______________________________________________________________________________________

Creating a new deck. searched for manafrom Hellkite in Innistrad:crimson vow set.
Not found. Is there a missing card?

_______________________________________________________________________________________

**Steps to reproduce:**
 - Do A
 - Do B
 - Do C ...

**Comment by ebbit1q** [comment]
please run the card updater whenever new cards release, you can run the card updater through help>check for card updates...
