### ISSUE TITLE
Server Connectivity issues for all users 

### ISSUE THREAD

**Issue by Lavanda25** [Cockatrice/Cockatrice#4588]
**System Information:**

Client Version: 2.8.0 (2021-01-26)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.12.9
System Locale: en_US
Install Mode: Standard
_______________________________________________________________________________________

Using Cockatrice to play a game of magic in the rooster servers the game started becoming unresponsive and eventually kicked us out of our game. We could see in the chat other players were noticing this too. I tried the old "turn it off and on" to see if closing the cockatrice program and logging back in would work and now I cannot access the server now. 
Midway through typing, it seems to be letting people back into the rooster ranges again and the connection seems to be stable again
EDIT:
NVM  it seems like the connection is going haywire when you try to open a new room now. It starts to lag and the connection drops off before picking up again.

_______________________________________________________________________________________

**Steps to reproduce:**
 - log into cockatrice
 - log into the server
 - enter rooster ranges
 - create new room
 - that's where the lagging and freezing starts to happen

**Comment by ZeldaZach** [comment]
The Rooster Ranges server was under attack from a rogue agent. We've been working on mitigation steps. Thanks for the report!
