### ISSUE TITLE
Servatrice Logs still contain login passwords

### ISSUE THREAD

**Issue by Lachee** [Cockatrice/Cockatrice#4594]
**System Information:**
Ubuntu 18
Servatrice Build #4591 
( https://github.com/Cockatrice/Cockatrice/actions/runs/1977061539 )

_______________________________________________________________________________________

When `writelog` is enabled, the server will log Command events directly to the file. This results in the password of anyone logging in being written to the log file. 

While log files are server-side only, having them in plain text is a security risk that makes sharing logs much more
difficult.

_______________________________________________________________________________________

**Steps to reproduce:**
 - Install the Bionic package in the build generated by #4591 
 - Configure to use accounts and enable writelog
 - Login with your account
 - Scan the logs for `[Command_Login.ext]`
 - Note the password is listed in plain text

Tagging @ebbit1q as per Discord discussion.

**Comment by ZeldaZach** [comment]
`Servatrice 2.8.1-custom(f5b973e) (2022-03-02)` is functioning as expected with writelog=1, so I'm not sure what's going on here

Raising priority

**Comment by ebbit1q** [comment]
I see, I changed the debug mode logging but not the file created by writelog

**Comment by tooomm** [comment]
Is this resolved and login information no longer leak this way? @Lachee
