### ISSUE TITLE
Alt+Right Click and Drag Causes a Crash

### ISSUE THREAD

**Issue by dmmyccnt** [Cockatrice/Cockatrice#4616]
**System Information:**
Client Version: 2.8.1-beta.7 (2022-05-06)
Client Operating System: Windows 10 Version 2009
Build Architecture: 64-bit
Qt Version: 6.3.0
System Locale: en_US
Install Mode: Standard

_______________________________________________________________________________________

Whenever I start a game, then hold Alt+Right Click and Drag or Shift+Right Click and Drag to create a blue arrow or a green arrow more than once, the game immediately crashes on me. 

It doesn't seem to have the same problem when using Ctrl+Right Click and Drag, with which I can make many different yellow arrows. Perhaps this can help narrow down what's causing this crash.

_______________________________________________________________________________________

**Steps to reproduce:**
 - Put any permanents on both players' battlefields.
 - Hold down either Alt+ or Shift+Right Click and Drag multiple times to try to create several arrows between permanents on opposite battlefields.
 - The game crashes.

**Comment by ZeldaZach** [comment]
Confirmed on Windows 10
