### ISSUE TITLE
Sound Do Not Overlap

### ISSUE THREAD

**Issue by Entitale** [Cockatrice/Cockatrice#4619]
**System Information:**

Client Version: 2.8.0 (2021-01-26)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.12.9
System Locale: en_US
Install Mode: Standard
_______________________________________________________________________________________
I have Uploaded a custom sound pack, but I've noticed that after I have one sound play, I need to wait until that sound file ends completely before any other sound plays instead of overlapping the sounds.
_______________________________________________________________________________________
**Steps to reproduce:**

 - Do any action that produces a sound
 - Do a second action that should produce a sound while the previous sound is still playing

**Comment by ebbit1q** [comment]
have you tried if the latest beta also has this issue?

**Comment by Entitale** [comment]
> have you tried if the latest beta also has this issue?

Yes, I am having the same issues in the latest beta.

**Comment by ebbit1q** [comment]
does this pr result in the behavior that you expect? see here for how to install the test version: https://github.com/Cockatrice/Cockatrice/wiki/How-to-use-unreleased-versions-created-by-pull-requests

**Comment by ebbit1q** [comment]
I guess zach already merged it, if the new behavior isn't actually what you mean feel free to reopen the ticket
