### ISSUE TITLE
Please Separate Secret Lairs!

### ISSUE THREAD

**Issue by Unclefester90** [Cockatrice/Cockatrice#4626]
Hey everyone! I was just wondering is\f the s\Secret Lairs can be sorted by their Lair Name and not just tossed into the same category. It makes making the deck just how you want it that much easier. A lot of art just gets buried away in it. Thank you for everything you all do!

**Comment by ebbit1q** [comment]
we simply use the data in the way that it is provided by mtgjson.com, cockatrice provides a much more powerful option for customization anyway, you can simply set the art of any card to whatever you'd like using the custom art folder: https://github.com/Cockatrice/Cockatrice/wiki/Custom-Cards-&-Sets#to-add-custom-art-for-cards-the-easiest-way-is-to-use-the-custom-folder

**Comment by ebbit1q** [comment]
also, for reference: https://github.com/Cockatrice/Cockatrice/issues/486 is about removing the restriction of cockatrice only allowing one art at a time

**Comment by SlightlyCircuitous** [comment]
A little late to this issue, but I actually made custom sets for (most of) the individual Secret Lair Drops, if you want to use the ones you like or just pull the individual art you like out into the custom art folder. https://github.com/SlightlyCircuitous/Custom-Sets-for-Cockatrice
