### ISSUE TITLE
64 bit builds no longer work on windows 7 because of qt6

### ISSUE THREAD

**Issue by MotherofRuins** [Cockatrice/Cockatrice#4631]
Client Version: 2.8.1-beta.6 (2022-01-16)
Client Operating System: Windows 7 Version 6.1 (Build 7601: SP 1)
Build Architecture: 64-bit
Qt Version: 5.15.2
System Locale: en_US
Install Mode: Standard
_______________________________________________________________________________________

Install beta.7.  When I run cockatrice I get Windows Application Error "The application was unable to start correctly (0xc0000005)"
Try install beta.8.  Same thing.
Try install beta.9.  Same thing.
Restore beta.6.  Everything is fine again.

**Comment by ebbit1q** [comment]
this is caused by the new qt6 builds no longer supporting windows 7, as a workaround the 32 bit builds still use qt5.15 and should still work for you (they will show you a warning message that is safe to ignore)

**Comment by ZeldaZach** [comment]
@ebbit1q I'm pretty sure we spoke about this and how we can offer a Win7_64_qt5  and Win10_64_qt6 to solve this

**Comment by MotherofRuins** [comment]
I seem to recall a similar thing happening going from qt4 to qt5.

**Comment by MotherofRuins** [comment]
Here is the old issue https://github.com/Cockatrice/Cockatrice/issues/1895

**Comment by ebbit1q** [comment]
this issue is likely unrelated, qt5 has always supported windows 7, with the introduction of qt6 there is no support for windows 7 or 8: https://doc.qt.io/qt-6.2/supported-platforms.html#windows

**Comment by MotherofRuins** [comment]
I appreciate that you aren't leaving Windows 7 behind.  It's the last OS that still lets me own my own machine.

**Comment by ebbit1q** [comment]
you mean it is the last windows os that does?

**Comment by tooomm** [comment]
> I appreciate that you aren't leaving Windows 7 behind. It's the last OS that still lets me own my own machine.

You are aware though that it's generally out of support and not secure to use? @MotherofRuins 
They even show full screen warnings from time to time.

I suggest you look into Linux if you want to "own your own machine" without being exposed to unpatched security issues.
(Or have to pay $$$ yearly to get ESU patches for enterprises.)

**Comment by MotherofRuins** [comment]
Agree on both points.  Linux will be my offramp from Windows.  But not for a couple of years.
