### ISSUE TITLE
Selected Token Art Missing -- Possible Broken Links

### ISSUE THREAD

**Issue by SlightlyCircuitous** [Cockatrice/Cockatrice#4634]
**System Information:**
Client Version: 2.8.1-beta.9 (2022-05-12)
Client Operating System: Ubuntu 22.04 LTS
Build Architecture: 64-bit
Qt Version: 6.2.4
System Locale: en_US
Install Mode: Standard
_______________________________________________________________________________________

I've noticed that there are several tokens missing art in (at least) my install of Cockatrice. I have made a list of the 124 affected tokens and have attached it. It's a tab-separated file with columns: name, set, distinguishing feature (if needed for tokens with the same name and set).

[Cockatrice Missing Art Tokens.txt](https://github.com/Cockatrice/Cockatrice/files/8808177/Cockatrice.Missing.Art.Tokens.txt)

Looking into the problem further, it seems like the issue is with broken Scryfall links. I looked at the entries for several of the artless tokens in tokens.xml and they all have "https://img.scryfall.com/cards..." style links that don't work when copied into the browser. Further, I made a custom set of some of the artless tokens by copying their entries from tokens.xml and replacing the "https://img.scryfall.com/cards..." style links with working "https://c1.scryfall.com/file/scryfall-cards..." style links from the appropriate Scryfall json. That fixed the issue for those tokens for me. I have included screenshots below of the difference in display between the two kinds of links in case that is helpful.

Adorned Pouncer using the "https://img.scryfall.com/cards..." style link in tokens.xml:

![Adorned Pouncer no image](https://user-images.githubusercontent.com/71394296/171269122-2deb4817-988f-478b-ad7e-872863af8992.png)

Adorned Pouncer using "https://c1.scryfall.com/file/scryfall-cards..." style link from Scryfall json in custom set:

![Adorned Pouncer image](https://user-images.githubusercontent.com/71394296/171269155-a2abf678-d158-4632-b2cc-088576530dc8.png)

Thank you.
_______________________________________________________________________________________

**Steps to reproduce:**
 - Open Cockatrice
 - Look at a token on the above list (e.g. Adorned Pouncer (Token), Anointer Priest (Token), Avatar Token [M19])

**Comment by tooomm** [comment]
Thanks for your detailed report and the work you put in to track it down further! You are absolutely right and your findings are correct. We are aware of the issue and I proposed a fix already, it's awaiting a review from others in the team.

https://github.com/Cockatrice/Magic-Token/pull/148

**Comment by tooomm** [comment]
@SlightlyCircuitous You can try to update your card database now. In the last step it will update your token file as well.

Feel free to reopen this request in case!

**Comment by SlightlyCircuitous** [comment]
Tokens load perfectly now, Thank you for the fix!

**Comment by ebbit1q** [comment]
also, for future reference, issues with tokens should be tracked in https://github.com/Cockatrice/Magic-Token

**Comment by SlightlyCircuitous** [comment]
OK, I will track it over there in the future. Didn't realize all the separate pieces had separate bug report zones. Do you want me to open up an issue over there with the debug logs or are you good as per ebbit1q's comment?

**Comment by tooomm** [comment]
I just merged @ebbit1q's fix. It should work now (after updating to the newest version of token data of course).

Sure, feel free to come over and report issues with the token file or help with improving its content!

**Comment by SlightlyCircuitous** [comment]
Great! Works for me now! Thanks so much for your help, both of you!
