### ISSUE TITLE
Update initial server chat message

### ISSUE THREAD

**Issue by poixen** [Cockatrice/Cockatrice#464]
+ Add [url][/url] tags to the http links
+ update the magic online link to https://accounts.onlinegaming.wizards.com/accountsignup.aspx

**Comment by ZeldaZach** [comment]
What's the current purpose of this ticket? I'm not certain anymore...

**Comment by woogerboy21** [comment]
@poixen : i think this issue is resolved correct?

**Comment by poixen** [comment]
Yea. Seems like everything has been moved to the server tab now.
