### ISSUE TITLE
Playing in a local game with certain decks crashes everything

### ISSUE THREAD

**Issue by jazzthejazzyjazz** [Cockatrice/Cockatrice#4645]
**System Information:**
Client Version: 2.8.0 (2021-01-26)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.12.9
System Locale: en_US
Install Mode: Standard

_______________________________________________________________________________________

When I try to play local games against myself, with certain decks, it crashes and closes the application entirely. I'm not as computer savvy as most of you are, so pardon me if I'm not using the right verbiage. But I've noticed it specifically on my Yuriko ninja tribal, Marrow Gnawer rat tribal and Rune-Tail Kitsune Ascendent. 

_______________________________________________________________________________________

Start a local game
Choose 2 decks
Set life to 40
Pull commanders from sideboard onto stack area (often crashes at this point)
Go through mulligan process
Usually by the 4th or 5th turn, it freezes up and crags

**Comment by ebbit1q** [comment]
could you please provide your .cod deck file?

**Comment by ebbit1q** [comment]
feel free to reopen with the deck file if the issue persists
