### ISSUE TITLE
Adjusting Format Options

### ISSUE THREAD

**Issue by Bottomfall** [Cockatrice/Cockatrice#4649]
Hey guys! I was wondering if we could consider removing Frontier as an option, as it sees little if no use at all, and adding Historic/Alchemy so people might be encouraged to at least try out decks in a free client alternative. This could be useful for testing purposes for people who both play MTGA and Cockatrice. If not, perhaps removing Highlander and Frontier, and solidifying the Other category for everything not considered the original paper formats might be an option. I do realize Cockatrice was created to emulate the tabletop feel of Magic: the Gathering, but I feel that with the growing popularity of MTGA, giving these new formats visibility might be overall helpful. I thank anyone who happens to read through this.

**Comment by mainman879** [comment]
The format list is something handled by the server admins. It is better to email the appropriate server admin about changes like this. There are also substantial difficulties with emulating certain features of MTGA play like perpetual or random conjuring or seek, and cockatrice is not a good option for things such as these.

**Comment by ebbit1q** [comment]
it's probably better to suggest it directly to the maintainer of the server you're using, the software itself doesn't include such a list by default and is configurable by the server
