### ISSUE TITLE
linker failure on debug mac ci builds

### ISSUE THREAD

**Issue by ebbit1q** [Cockatrice/Cockatrice#4652]
mac builds fail on linking to protobuf, this is likely related to an update of the version of protobuf available in homebrew

see this tag I pushed: https://github.com/Cockatrice/Cockatrice/runs/7379820512?check_suite_focus=true#step:4:822

```

  [100%] Linking CXX executable cockatrice.app/Contents/MacOS/cockatrice
  Undefined symbols for architecture x86_64:
    "google::protobuf::internal::InternalMetadata::~InternalMetadata()", referenced from:
        google::protobuf::Message::~Message() in libcockatrice_protocol.a(admin_commands.pb.cc.o)
        AdminCommand::AdminCommand(google::protobuf::Arena*, bool) in libcockatrice_protocol.a(admin_commands.pb.cc.o)
        AdminCommand::AdminCommand(google::protobuf::Arena*, bool) in libcockatrice_protocol.a(admin_commands.pb.cc.o)
        AdminCommand::AdminCommand(AdminCommand const&) in libcockatrice_protocol.a(admin_commands.pb.cc.o)
        AdminCommand::AdminCommand(AdminCommand const&) in libcockatrice_protocol.a(admin_commands.pb.cc.o)
        AdminCommand::~AdminCommand() in libcockatrice_protocol.a(admin_commands.pb.cc.o)
        Command_ShutdownServer::Command_ShutdownServer(Command_ShutdownServer const&) in libcockatrice_protocol.a(admin_commands.pb.cc.o)
```

until this is fixed we can't release anything for mac

**Comment by tooomm** [comment]
>mac builds fail on linking to protobuf

This seems to have resolved in the meantime and the builds are succeeding again, see https://github.com/Cockatrice/Cockatrice/runs/7741243649?check_suite_focus=true

<br>

But the mac debug build is still throwing (a different) issue: https://github.com/Cockatrice/Cockatrice/runs/7741243559?check_suite_focus=true

(Well, and Impish fails: https://github.com/Cockatrice/Cockatrice/runs/7741244967?check_suite_focus=true)

**Comment by tooomm** [comment]
>that's because impish is eol and should be removed

I updated #4628 to also address this.

**Comment by tooomm** [comment]
https://github.com/Cockatrice/Cockatrice/pull/4662

**Comment by tooomm** [comment]
This should be fixed in between.
There were finally some [upstream fixed](https://github.com/protocolbuffers/protobuf/pull/12445) that superseded #4662.
