### ISSUE TITLE
Streets of New Capenna Cards Unavailable

### ISSUE THREAD

**Issue by ghost-ware** [Cockatrice/Cockatrice#4660]
**System Information:**
Client Version: 2.8.0 (2021-01-26)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.12.9
System Locale: en_US
Install Mode: Standard

_______________________________________________________________________________________

I have the set "Streets of New Capenna" enabled in the Set Manager, but when I search for cards from that set, they cannot be found.
![image](https://user-images.githubusercontent.com/48546042/184523036-e96f31f2-bfc3-42a4-81a9-cab7c5537caa.png)
![image](https://user-images.githubusercontent.com/48546042/184523052-631f99ef-f23a-45d3-ae62-2d67686ade14.png)
![image](https://user-images.githubusercontent.com/48546042/184523068-debc604b-e310-45ff-9305-148b2f2ae14f.png)

_______________________________________________________________________________________

**Steps to reproduce:**
 - Enable "Streets of New Capenna" in "Manage Sets"
 - Search for cards from Streets of New Capenna
 - I'm not sure that this will reproduce the bug on other systems.

**Comment by tooomm** [comment]
Did you try to update the card database again?

**Comment by ghost-ware** [comment]
Yeah, I've tried updating the database a few times and re-installed after a bit. No luck so far.

**Comment by ebbit1q** [comment]
which version of oracle does it show on the first page of the card updater wizard?

**Comment by tooomm** [comment]
Tested again, it works without issues here:
![Untitled](https://user-images.githubusercontent.com/9874850/187851376-10437833-528b-488a-94e1-ed070b6403de.png)
Probably some issue with your database or Oracle.

Can you include all information from the `Debug log` after opening Cockatrice with SNC enabled and searching for a SNC card? @ghost-ware

**Comment by tooomm** [comment]
Feel free to reopen this with more information if the issue persists.

I can add that I had similar issues when freshly installing Cockatrice and on first start it did not load the new database and show any cards. A simple app restart always fixed things.
