### ISSUE TITLE
No sound on Windows with (new) Qt5 build

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#4665]
**System Information:**
Client Version: 2.8.1-beta.10 (2022-06-08)
Client Operating System: Windows 10 Version 2009
Build Architecture: 64-bit
Qt Version: 5.15.2
System Locale: en_GB
Install Mode: Standard

_______________________________________________________________________________________

After testing some 64-bit Qt5 build on Windows 10, I realized that they all have no sounds for me.
I found out, that `2.8.1-beta.6` (which was the last release that was still all Qt5) does play sound.
So with the switch to Qt6 (even though Qt5 was reintroduced later again, #4639) sound is lost now for Qt5 users on Windows it seems.

@motherofruins Do you have sound on your Qt5 build that you run on Windows 7? Which version is it?
Can you also try the new 2.8.1-beta.10/Win7/64bit (Qt5), please?

This issue is not directly related to #4642, I tried a build before that change as well and had no sound either.

Edit: Same issue when running the 32-bit version of 2.8.1-beta.10 (also Qt5) on my 64-bit Windows 10.

**Comment by ebbit1q** [comment]
sound works as normal for me using the linux build, this could be an issue with our build system perhaps?

**Comment by MotherofRuins** [comment]
I have the same problem with version Cockatrice-2.8.1-beta.10-Win7+-64bit.exe
Sound works on Cockatrice-2.8.1-beta.6-win64.exe

**Comment by MotherofRuins** [comment]
@tooomm @ebbit1q 
Any luck finding that regression?

**Comment by ebbit1q** [comment]
with me unable to reproduce the issue I haven't been able to look into it.

**Comment by ZeldaZach** [comment]
I just tested building locally using Windows10 with Qt5.15.2 and Qt6.3.0, and the sound engine appears to be working for both. Unable to reproduce.

Creating a package release and installing them, I don't have sounds on Qt5 build but I do on the Qt6 build. Will continue to investigate.

**Comment by ZeldaZach** [comment]
Figured it out, missing plugin

**Comment by MotherofRuins** [comment]
Sound works on version Cockatrice-2.8.1-custom(a4c7e6d)-Win7+-64bit.exe.

Thank you!
