### ISSUE TITLE
Branchlouft pathway is broken

### ISSUE THREAD

**Issue by LordSnom** [Cockatrice/Cockatrice#4669]
I was playing a game a while ago and played a branchlouft pathway and when I clicked to create a boulderloft pathway it created a card called boulderloft pathway but it's really just the full art for branchlouft pathway.

**Comment by ebbit1q** [comment]
I assume the issue has resolved itself?

**Comment by LordSnom** [comment]
Yes it was I had to pull the set up and set it above the other zendikar rising sets for it to fix itself
