### ISSUE TITLE
Preblem with filtering with CMC of split cards and adventure cards

### ISSUE THREAD

**Issue by liyangwu** [Cockatrice/Cockatrice#4676]
**System Information:**
Client Version: 2.8.0 (2021-01-26)
PictureLoader: [card:  "Noxious Revival"  set:  "PLIST" ]: Trying to load picture
PictureLoader: [card:  "Noxious Revival"  set:  "PLIST" ]: Picture found on disk.
PictureLoader: [card:  "Mutagenic Growth"  set:  "MM2" ]: Trying to load picture
PictureLoader: [card:  "Mutagenic Growth"  set:  "MM2" ]: Picture found on disk.
PictureLoader: [card:  "Slippery Bogle"  set:  "UMA" ]: Trying to load picture
PictureLoader: [card:  "Slippery Bogle"  set:  "UMA" ]: Picture found on disk.
PictureLoader: [card:  "Bioshift"  set:  "GTC" ]: Trying to load picture
PictureLoader: [card:  "Bioshift"  set:  "GTC" ]: Picture found on disk.
PictureLoader: [card:  "Elvish Hexhunter"  set:  "SHM" ]: Trying to load picture
PictureLoader: [card:  "Elvish Hexhunter"  set:  "SHM" ]: Picture found on disk.
PictureLoader: [card:  "Dryad Militant"  set:  "PLIST" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Dryad Militant"  set:  "PLIST" ]: Requested set property ( "muid" ) for Url template ( "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Dryad Militant"  set:  "PLIST" ]: Trying to load picture
PictureLoader: [card:  "Dryad Militant"  set:  "PLIST" ]: Picture found on disk.
PictureLoader: [card:  "Barkshell Blessing"  set:  "SHM" ]: Trying to load picture
PictureLoader: [card:  "Barkshell Blessing"  set:  "SHM" ]: Picture found on disk.
PictureLoader: [card:  "Seedcradle Witch"  set:  "SHM" ]: Trying to load picture
PictureLoader: [card:  "Seedcradle Witch"  set:  "SHM" ]: Picture found on disk.
PictureLoader: [card:  "Safewright Quest"  set:  "SHM" ]: Trying to load picture
PictureLoader: [card:  "Safewright Quest"  set:  "SHM" ]: Picture found on disk.
PictureLoader: [card:  "Rhys the Redeemed"  set:  "2XM" ]: Trying to load picture
PictureLoader: [card:  "Rhys the Redeemed"  set:  "2XM" ]: Picture found on disk.
PictureLoader: [card:  "Wild Cantor"  set:  "GPT" ]: Trying to load picture
PictureLoader: [card:  "Wild Cantor"  set:  "GPT" ]: Picture found on disk.
PictureLoader: [card:  "Tattermunge Maniac"  set:  "SHM" ]: Trying to load picture
PictureLoader: [card:  "Tattermunge Maniac"  set:  "SHM" ]: Picture found on disk.
PictureLoader: [card:  "Guttural Response"  set:  "PLIST" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Guttural Response"  set:  "PLIST" ]: Requested set property ( "muid" ) for Url template ( "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Guttural Response"  set:  "PLIST" ]: Trying to load picture
PictureLoader: [card:  "Guttural Response"  set:  "PLIST" ]: Picture found on disk.
PictureLoader: [card:  "Fossil Find"  set:  "SHM" ]: Trying to load picture
PictureLoader: [card:  "Fossil Find"  set:  "SHM" ]: Picture found on disk.
PictureLoader: [card:  "Scuzzback Scrapper"  set:  "SHM" ]: Trying to load picture
PictureLoader: [card:  "Scuzzback Scrapper"  set:  "SHM" ]: Picture found on disk.
PictureLoader: [card:  "Gut Shot"  set:  "MB1" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Gut Shot"  set:  "MB1" ]: Requested set property ( "muid" ) for Url template ( "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Gut Shot"  set:  "MB1" ]: Trying to load picture
PictureLoader: [card:  "Gut Shot"  set:  "MB1" ]: Picture found on disk.
PictureLoader: [card:  "Make Your Mark"  set:  "STX" ]: Trying to load picture
PictureLoader: [card:  "Make Your Mark"  set:  "STX" ]: Picture found on disk.
PictureLoader: [card:  "Duergar Assailant"  set:  "EVE" ]: Trying to load picture
PictureLoader: [card:  "Duergar Assailant"  set:  "EVE" ]: Picture found on disk.
PictureLoader: [card:  "Figure of Destiny"  set:  "2X2" ]: Trying to load picture
PictureLoader: [card:  "Figure of Destiny"  set:  "2X2" ]: Picture found on disk.
PictureLoader: [card:  "Boros Recruit"  set:  "RAV" ]: Trying to load picture
PictureLoader: [card:  "Boros Recruit"  set:  "RAV" ]: Picture found on disk.
PictureLoader: [card:  "Oona's Gatewarden"  set:  "SHM" ]: Trying to load picture
PictureLoader: [card:  "Oona's Gatewarden"  set:  "SHM" ]: Picture found on disk.
PictureLoader: [card:  "Dream Salvage"  set:  "SHM" ]: Trying to load picture
PictureLoader: [card:  "Dream Salvage"  set:  "SHM" ]: Picture found on disk.
PictureLoader: [card:  "Memory Sluice"  set:  "SHM" ]: Trying to load picture
PictureLoader: [card:  "Memory Sluice"  set:  "SHM" ]: Picture found on disk.
PictureLoader: [card:  "Dream Salvage"  set:  "SHM" ]: Trying to load picture
PictureLoader: [card:  "Dream Salvage"  set:  "SHM" ]: Picture found on disk.
PictureLoader: [card:  "Stream Hopper"  set:  "EVE" ]: Trying to load picture
PictureLoader: [card:  "Stream Hopper"  set:  "EVE" ]: Picture found on disk.
PictureLoader: [card:  "Clout of the Dominus"  set:  "EVE" ]: Trying to load picture
PictureLoader: [card:  "Clout of the Dominus"  set:  "EVE" ]: Picture found on disk.
PictureLoader: [card:  "Nivmagus Elemental"  set:  "RTR" ]: Trying to load picture
PictureLoader: [card:  "Nivmagus Elemental"  set:  "RTR" ]: Picture found on disk.
PictureLoader: [card:  "Blistercoil Weird"  set:  "RTR" ]: Trying to load picture
PictureLoader: [card:  "Blistercoil Weird"  set:  "RTR" ]: Picture found on disk.
PictureLoader: [card:  "Beckon Apparition"  set:  "UMA" ]: Trying to load picture
PictureLoader: [card:  "Beckon Apparition"  set:  "UMA" ]: Picture found on disk.
PictureLoader: [card:  "Edge of the Divinity"  set:  "EVE" ]: Trying to load picture
PictureLoader: [card:  "Edge of the Divinity"  set:  "EVE" ]: Picture found on disk.
PictureLoader: [card:  "Nip Gwyllion"  set:  "EVE" ]: Trying to load picture
PictureLoader: [card:  "Nip Gwyllion"  set:  "EVE" ]: Picture found on disk.
PictureLoader: [card:  "Marrow Shards"  set:  "NPH" ]: Trying to load picture
PictureLoader: [card:  "Marrow Shards"  set:  "NPH" ]: Picture found on disk.
PictureLoader: [card:  "Zealous Guardian"  set:  "SHM" ]: Trying to load picture
PictureLoader: [card:  "Zealous Guardian"  set:  "SHM" ]: Picture found on disk.
PictureLoader: [card:  "Judge's Familiar"  set:  "GK2" ]: Trying to load picture
PictureLoader: [card:  "Judge's Familiar"  set:  "GK2" ]: Picture found on disk.
PictureLoader: [card:  "Runed Stalactite"  set:  "PLIST" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Runed Stalactite"  set:  "PLIST" ]: Requested set property ( "muid" ) for Url template ( "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Runed Stalactite"  set:  "PLIST" ]: Trying to load picture
PictureLoader: [card:  "Runed Stalactite"  set:  "PLIST" ]: Picture found on disk.
PictureLoader: [card:  "Giant Killer // Chop Down"  set:  "ELD" ]: Trying to load picture
PictureLoader: [card:  "Giant KillerChop Down"  set:  "ELD" ]: Picture found on disk.
PictureLoader: [card:  "Flaxen Intruder // Welcome Home"  set:  "ELD" ]: Trying to load picture
PictureLoader: [card:  "Flaxen IntruderWelcome Home"  set:  "ELD" ]: Picture found on disk.
PictureLoader: [card:  "Icehide Golem"  set:  "MH1" ]: Trying to load picture
PictureLoader: [card:  "Icehide Golem"  set:  "MH1" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Icehide Golem"  set:  "MH1" ]: Trying to download picture from url: "https://api.scryfall.com/cards/b2671c36-96fa-49e3-90dc-52820b2c8a62?format=image&face=front"
PictureLoader: [card:  "Icehide Golem"  set:  "MH1" ]: following redirect: "https://c1.scryfall.com/file/scryfall-cards/large/front/b/2/b2671c36-96fa-49e3-90dc-52820b2c8a62.jpg?1562202467"
PictureLoader: [card:  "Icehide Golem"  set:  "MH1" ]: Image successfully downloaded from  "https://c1.scryfall.com/file/scryfall-cards/large/front/b/2/b2671c36-96fa-49e3-90dc-52820b2c8a62.jpg?1562202467"
PictureLoader: [card:  "Faerie Guidemother // Gift of the Fae"  set:  "ELD" ]: Trying to load picture
PictureLoader: [card:  "Faerie GuidemotherGift of the Fae"  set:  "ELD" ]: Picture found on disk.
PictureLoader: [card:  "Postmortem Lunge"  set:  "NPH" ]: Trying to load picture
PictureLoader: [card:  "Postmortem Lunge"  set:  "NPH" ]: Picture found on disk.
PictureLoader: [card:  "Corrosive Gale"  set:  "NPH" ]: Trying to load picture
PictureLoader: [card:  "Corrosive Gale"  set:  "NPH" ]: Picture found on disk.
PictureLoader: [card:  "Dawnglow Infusion"  set:  "SHM" ]: Trying to load picture
PictureLoader: [card:  "Dawnglow Infusion"  set:  "SHM" ]: Picture found on disk.
PictureLoader: [card:  "Flower // Flourish"  set:  "GRN" ]: Trying to load picture
PictureLoader: [card:  "FlowerFlourish"  set:  "GRN" ]: Picture found on disk.
PictureLoader: [card:  "Giant Killer // Chop Down"  set:  "ELD" ]: Trying to load picture
PictureLoader: [card:  "Giant KillerChop Down"  set:  "ELD" ]: Picture found on disk.
PictureLoader: [card:  "Nested Shambler"  set:  "MH2" ]: Trying to load picture
PictureLoader: [card:  "Nested Shambler"  set:  "MH2" ]: Picture found on disk.
PictureLoader: [card:  "Foulmire Knight // Profane Insight"  set:  "ELD" ]: Trying to load picture
PictureLoader: [card:  "Foulmire KnightProfane Insight"  set:  "ELD" ]: Picture found on disk.
PictureLoader: [card:  "Almighty Brushwagg"  set:  "IKO" ]: Trying to load picture
PictureLoader: [card:  "Almighty Brushwagg"  set:  "IKO" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Almighty Brushwagg"  set:  "IKO" ]: Trying to download picture from url: "https://api.scryfall.com/cards/71f2b7ac-8742-468d-b6a3-87881cb522ff?format=image&face=front"
PictureLoader: [card:  "Almighty Brushwagg"  set:  "IKO" ]: following redirect: "https://c1.scryfall.com/file/scryfall-cards/large/front/7/1/71f2b7ac-8742-468d-b6a3-87881cb522ff.jpg?1591227501"
PictureLoader: [card:  "Almighty Brushwagg"  set:  "IKO" ]: Image successfully downloaded from  "https://c1.scryfall.com/file/scryfall-cards/large/front/7/1/71f2b7ac-8742-468d-b6a3-87881cb522ff.jpg?1591227501"
PictureLoader: [card:  "Flaxen Intruder // Welcome Home"  set:  "ELD" ]: Trying to load picture
PictureLoader: [card:  "Flaxen IntruderWelcome Home"  set:  "ELD" ]: Picture found on disk.
PictureLoader: [card:  "Postmortem Lunge"  set:  "NPH" ]: Trying to load picture
PictureLoader: [card:  "Postmortem Lunge"  set:  "NPH" ]: Picture found on disk.
PictureLoader: [card:  "Corrosive Gale"  set:  "NPH" ]: Trying to load picture
PictureLoader: [card:  "Corrosive Gale"  set:  "NPH" ]: Picture found on disk.
PictureLoader: [card:  "Dawnglow Infusion"  set:  "SHM" ]: Trying to load picture
PictureLoader: [card:  "Dawnglow Infusion"  set:  "SHM" ]: Picture found on disk.
PictureLoader: [card:  "Faerie Guidemother // Gift of the Fae"  set:  "ELD" ]: Trying to load picture
PictureLoader: [card:  "Faerie GuidemotherGift of the Fae"  set:  "ELD" ]: Picture found on disk.
PictureLoader: [card:  "Flower // Flourish"  set:  "GRN" ]: Trying to load picture
PictureLoader: [card:  "FlowerFlourish"  set:  "GRN" ]: Picture found on disk.
PictureLoader: [card:  "Beanstalk Giant // Fertile Footsteps"  set:  "PLIST" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Beanstalk Giant // Fertile Footsteps"  set:  "PLIST" ]: Requested set property ( "muid" ) for Url template ( "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Beanstalk Giant // Fertile Footsteps"  set:  "PLIST" ]: Trying to load picture
PictureLoader: [card:  "Beanstalk Giant // Fertile Footsteps"  set:  "PLIST" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Beanstalk GiantFertile Footsteps"  set:  "PLIST" ]: Trying to download picture from url: "https://api.scryfall.com/cards/035975da-7a65-4cef-9bd3-d1e1f6102f38?format=image&face=front"
PictureLoader: [card:  "Beanstalk Giant // Fertile Footsteps"  set:  "PLIST" ]: following redirect: "https://c1.scryfall.com/file/scryfall-cards/large/front/0/3/035975da-7a65-4cef-9bd3-d1e1f6102f38.jpg?1609988082"
PictureLoader: [card:  "Beanstalk Giant // Fertile Footsteps"  set:  "PLIST" ]: Image successfully downloaded from  "https://c1.scryfall.com/file/scryfall-cards/large/front/0/3/035975da-7a65-4cef-9bd3-d1e1f6102f38.jpg?1609988082"

_______________________________________________________________________________________

###  General
Sometimes I want to find cards by filtering with CMC. With the follwing two card types below, I have found a problem.

### Split cards
The CMC of split cards is the sum of both cards instead of having their own CMC respectively.
For example "Flower // Flourish" can't be find with CMC=1 or CMC=6, but CMC=7 instead.
Workaround: Search for all cards with "//" in the card name. Problem: You still have to look through alot of irrelevent cards.

### Adventure cards
Adventure spells of Adventure cards cannot be found with CMC at all.
For example "Giant Killer // Chop Down" can only be found with CMC=1 but not CMC=3.
Same workaround as above.

_______________________________________________________________________________________

none

**Comment by ebbit1q** [comment]
this is following the official rules on what the cmc/mana value of that card is, for adventure cards it's the creature, for split cards both are added together. (see cr 202.3d or 709.4b)

scryfall etc. all only list the official cmc/mana value of the card, not what it could potentially be cast for, this would need a significant amount of extra thought, there is tons of effects that have different costs and we simply don't have a list of them available. (eg phyrexian mana and alternative casting costs, or even certain abilities like morph or foretell)

I currently don't see an alternative other than simply using the official cost and searching for that.

an alternative tag like "mana options" would be a future possibility but I don't think it'd be up to us to map that out, we would prefer to use a data provider like mtgjson and simply using what is provided.

**Comment by liyangwu** [comment]
Hi @ebbit1q , thanks for the insights. I hope that data providers will improve on that. Especially with the json format, you can add more information to specific cards without polluting the "schema" of all other cards. Deck building is the core essence of MtG. I hope data providers agree on that :D
