### ISSUE TITLE
GitHub Actions: `set-output` is deprecated

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#4684]
**Description**
There are several places where we use this.

**Additional Context**
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by ebbit1q** [comment]
their docs don't seem to show any alternative yet? I don't see this deprecation happening very soon.

**Comment by tooomm** [comment]
Probably this one? https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter

**Comment by ebbit1q** [comment]
ah, I see, yeah that looks doable, their blog simply linked a different chapter
