### ISSUE TITLE
Allow moderators to view a user's recent chat messages

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#469]
As a moderator I'd like to be able to query the server for recent chat messages of a user:
 - by ip
 - by user ids
 - by username

I'd like to be able to see
 - Chat messages
 - In game messages
 - Private chat messages

**Comment by Daenyth** [comment]
This is more or less done right?

**Comment by ZeldaZach** [comment]
This ticket can be closed
