### ISSUE TITLE
Sorting options missing/disabled in beta.10

### ISSUE THREAD

**Issue by DoomStrider** [Cockatrice/Cockatrice#4696]
**System Information:**

Client Version: 2.8.1-beta.10 (2022-09-01)
Client Opperating System: Windows 10 Version 2009
Build Architecture: 64-bit
Qt Version: 6.3.1
System Locale: en_US
Install Mode: Standard
_______________________________________________________________________________________

The bar where the colum descriptors (where you can select the sort modes) is blank for me and does not allow me to change the sort settings. 

_______________________________________________________________________________________

N/A, just noticed it today and can't fix it. 
![16668245373258140913892436771194](https://user-images.githubusercontent.com/84279777/198153204-47bad836-c03f-40d8-a4f7-41b33c610796.jpg)

**Comment by ebbit1q** [comment]
the image hasn't completed uploading, please try sending the picture again

**Comment by DoomStrider** [comment]
Resent

**Comment by ebbit1q** [comment]
I can't reproduce this, does this happen on the 2.8.0 or the win7 beta version as well?

**Comment by DoomStrider** [comment]
I can try to downgrade to non beta when I get home later.

**Comment by ZeldaZach** [comment]
I can't seem to reproduce this on Windows 10, Beta 10, 64 bit... Can you try running again?
