### ISSUE TITLE
Need help with compiling cockatrice (can't find Qt files when making package)

### ISSUE THREAD

**Issue by Fherlayt** [Cockatrice/Cockatrice#4701]
Hi,
I try to compile cockatrice. on Windows 10, with visual studio 2019, I set the correct QT path wherever I could, but still, when building "package" I get the following error:

2>Error copying file "Qt5Core.dll" to "D:/Cockatrice2/build/_CPack_Packages/win64/NSIS/Cockatrice-2.8.1-custom(f619ef2)/Qt5Core.dll".
(And the same for all the other Qt5 files)

Can someone help me which file is giving the above error message, unfortunately I don't know from where it tries to copy these files.
Thanks in advance, and sorry if my post is the wrong format / place, this is the first time I try get help here.

**Comment by ebbit1q** [comment]
I don't think our wiki is fully up to date with the latest instructions, but when running cmake it will tell you which location it found qt, for example see this line on our automated builds here https://github.com/Cockatrice/Cockatrice/actions/runs/3365211887/jobs/5580501844#step:6:111

I don't know much about visual studio but we would really appreciate it if someone that is familiar with visual studio could update the wiki page: https://github.com/Cockatrice/Cockatrice/wiki/Compiling-Cockatrice-(Windows)

**Comment by Fherlayt** [comment]
Thanks for the reply! Cmake finds QT, actually I can compile cockatrice.exe, servatrice etc. If I copy these exes and the dlls manually together, cockatrice is able to run without problem. But I cannot generate an install package by "build package" because I get the above error message. So I was wondering, maybe I have to set a QT patch in Visual Studio too? Or what text should I search for in cmake files to figure out which is trying to copy from the wrong place?

**Comment by ZeldaZach** [comment]
I updated the wiki a [few weeks ago](https://github.com/Cockatrice/Cockatrice/wiki/Compiling-Cockatrice-(Windows)#zachs-new-guide-january-2023) on how to get it up and running with Clion/VisualStudio
