### ISSUE TITLE
Card database crashing while updating on Linux

### ISSUE THREAD

**Issue by Yes-Tis-I** [Cockatrice/Cockatrice#4702]
**System Information:**
Client Version: 2.8.0 (2021-01-26)
Client Operating System: KDE Flatpak runtime
Build Architecture: ARM
Qt Version: 5.15.3
System Locale: en_US
Install Mode: Standard
_______________________________________________________________________________________

I just bought a Chromebook and just downloaded Linux, flatpak on Linux, and Cockatrice with flatpak yesterday. The Chromebook has a 32-bit OS. Whenever I open Cockatrice, it'll ask me to update the card database, I click yes, in English, and the default URL for the database. It will download but then it says it crashed. I know very little of coding or exactly what I am doing.

_______________________________________________________________________________________

**Steps to reproduce:**
 - I open Cockatrice.
 - I start updating the default card database URL.
 - It crashes.

**Comment by ebbit1q** [comment]
how much ram does your chromebook have? oracle takes about 2GB to run, you might have to close background applications as the default linux vm the chromebook configures does not include swap space.

**Comment by Yes-Tis-I** [comment]
It has 4GB of RAM (small I know) and the only other thing open is a few google chrome tabs. Is parsing the file a separate process from downloading?

**Comment by ebbit1q** [comment]
no, they happen sequentially in oracle but are part of the same process. close chrome or start oracle after a clean restart, alternatively look up how to configure your vm to use swap space.
