### ISSUE TITLE
Custom image per deck?

### ISSUE THREAD

**Issue by Jdrawer** [Cockatrice/Cockatrice#4703]
**Similar Requests**

**Description of New Feature**

I think being able to have set default for card arts is a great feature and helps in user-side expression, but the fact that whatever default image I set for Swamps in my Jodah deck affects the image that appears in my Greel deck makes me less likely to use the feature. Is there a way (or rather, could we get a way) to choose custom/default images per deck?

**Additional Context**

**Comment by ebbit1q** [comment]
duplicate of the more encompassing #486
