### ISSUE TITLE
meld creatures can't find their art on scryfall

### ISSUE THREAD

**Issue by ebbit1q** [Cockatrice/Cockatrice#4704]
meld creatures (eg. Brisela, voice of Nightmares or Mishra, Lost to Phyrexia) can't download their art from scryfall because oracle assigns them as the back face, which in turn reflects mtgjson saying it is side b, which adds &face="back" to the url which scryfall does not recognize for these cards (even though they technically are the back side of two cards scryfall saves them in their database as a unique object without backside, unlike transform cards etc)

in the default configuration these cards correctly download their art from the fallback link.

to fix this an exception would need to be added to oracle or #4109

**Comment by SlightlyCircuitous** [comment]
In my tests, only the melds in BRO (Mishra, Lost to Phyrexia; Urza, Planeswalker; and Titania, Gaea Incarnate) couldn't find pictures and added "&face=back" to their URLs when searching.

The ones in EMN (Brisela, Voice of Nightmares; Hanweir, Writhing Township; and Chittering Host) all find their pictures correctly and they don't add "&face=back" to their URLs. 

Not sure why this would be, but seemed worth mentioning.

**Comment by SlightlyCircuitous** [comment]
Just deleted all my downloaded pictures and tested getting the art for the 6 meld cards from both EMN and BRO. Cockatrice found and displayed the art for each of them. Running cockatrice in the terminal confirmed that the art was downloaded from Scryfall and oracle did not try to add "&face=back" to any of them. I don't know what changed, but this seems fixed, at least for me.

**Comment by ebbit1q** [comment]
perhaps it was an upstream issue, weems it's resolved so I'll be closing this
