### ISSUE TITLE
"&" is converted to // from text input

### ISSUE THREAD

**Issue by Knepsia** [Cockatrice/Cockatrice#4706]
**System Information:**

Client Version: 2.8.1-beta.6 (2022-01-16)
Client Operating System: Windows 10 Version 2009
Build Architecture: 64-bit
Qt Version: 5.15.2
System Locale: en_GB
Install Mode: Standard
_______________________________________________________________________________________

when a card with "&" in it's name is loaded form a txt file or form clipboard the & is replaced with //
expor the following deck to clipboard: 
![image](https://user-images.githubusercontent.com/22708704/201768160-62f17903-f841-4fcf-b4d9-3dd988974909.png)
paste deck form clipboard window: 
![image](https://user-images.githubusercontent.com/22708704/201768304-25f24313-eb9b-4366-8c71-e921744e7b81.png)
decklist form menu:
```
// 1 Maindeck
// 1 Planeswalker
1 Minsc & Boo, Timeless Heroes
```
resulting decklist: 
![image](https://user-images.githubusercontent.com/22708704/201768524-bcb2d669-8718-4ad9-9409-7387ef9633ce.png)

_______________________________________________________________________________________

step 1: create a deck with minsc & boo, timeless heroes
step 2: export this deck to clipboard/txt file
step 3: reload form txt file or clipboard
**Steps to reproduce:**
 - Do A
 - Do B
 - Do C ...

**Comment by ebbit1q** [comment]
note: as a workaround, simply remove all ampersands from your pasted decklist before clicking ok.
