### ISSUE TITLE
Saved server password is stored in plain text

### ISSUE THREAD

**Issue by SmellyHuffer** [Cockatrice/Cockatrice#4709]
Hi,

I noticed that user login info to connect to servers is stored locally (when I tick Save Password) in plain text in servers.ini. I'm no security expert by any means but that doesn't look right to me. Should this not be encrypted in some way? Just wondering, thought I'd let you guys know.

Kind regards,
Huffy

**Comment by ebbit1q** [comment]
duplicate of #344 to be fixed by #4586
