### ISSUE TITLE
Deckstorage not working

### ISSUE THREAD

**Issue by KidWar75** [Cockatrice/Cockatrice#4711]
**System Information:**
Windows 10
Cockatrice (64-bit) Version 2.8.0 (2021-01-26

_______________________________________________________________________________________

I can't use / create the "Deck storage". I can't create or import deck and I can't save them on the server :(
All the button in the bottom are not working (doesn't do anything) except the "create a folder" button on the right side.
![image](https://user-images.githubusercontent.com/62625228/203602916-b9fd140c-c6fa-4205-bb0c-0b204a4e8085.png)

_______________________________________________________________________________________

**Steps to reproduce:**

N/A

**Comment by ebbit1q** [comment]
before you can move a local deck to the server you first need to save the deck to your decks folder locally
