### ISSUE TITLE
can't install .deb on Ubuntu 22.04

### ISSUE THREAD

**Issue by mixmix** [Cockatrice/Cockatrice#4722]
there were a bunch of dependencies I needed to install, but I got stuck on `libprotobuf17`

```
The following packages have unmet dependencies:
 cockatrice : Depends: libprotobuf17 but it is not installable
```

_______________________________________________________________________________________

```
sudo dpkg -i Cockatrice-Prismatic.Bridge-2.8.0-UbuntuFocal.deb
```

**Comment by mixmix** [comment]
tried

```
apt search libprotobuf17
```
no results. Tried duckduckgo for where to source that dep but couldn't find anything useful

**Comment by ZeldaZach** [comment]
Looks like libprotobuf17 is for 20.04 only, and [libprotobuf23](https://packages.ubuntu.com/jammy/libprotobuf23) is what we'll need

**Comment by ebbit1q** [comment]
we provide different packages for all the different versions of a distro, ubuntu focal is 20.04, ubuntu 22.04 is jammy, we provide a package for 22.04 right here: https://github.com/Cockatrice/Cockatrice/releases/tag/2022-09-01-Development-2.8.1-beta.10
cockatrice 2.8.0 was released before ubuntu jammy, we do not create new packages for older releases, if you don't want to use the beta version you can use the flatpak: https://flathub.org/apps/details/io.github.Cockatrice.cockatrice
you can also compile for any distro from any tag following the instructions here: https://github.com/Cockatrice/Cockatrice/wiki/Compiling-Cockatrice-(Linux)

**Comment by mixmix** [comment]
thanks @ZeldaZach @ebbit1q 

For context here's the path I took (which might be good to clarify for other users)

![image](https://user-images.githubusercontent.com/2665886/208524460-3e9c6adc-7835-49c5-b194-dc4ba5f62e7c.png)

![image](https://user-images.githubusercontent.com/2665886/208524618-6edc28fc-db9c-4cbc-a957-0874754a42fa.png)

**Comment by ebbit1q** [comment]
yeah, the letters saying 20.04 are rather small, if you have suggestions to improve it check out the website's repo https://github.com/Cockatrice/cockatrice.github.io
