### ISSUE TITLE
Add Support for TLS 1.3

### ISSUE THREAD

**Issue by Sacharkin** [Cockatrice/Cockatrice#4723]
**Support for TLS 1.3**

TLS 1.3 is not supported by the current version 2.8 for MAC (Ventura 13.1).
It is not possible to connect to the server.

<img width="401" alt="Screenshot 2022-12-22 at 10 21 56 PM" src="https://user-images.githubusercontent.com/50102954/209229453-bbfbc14a-4d0a-4029-836f-e8c68b3dd4a8.png">

**Comment by ZeldaZach** [comment]
Qt6 should support TLS 1.3. Provided you're not on Windows 7 still, this should work now. If you have a problem, do let us know!
