### ISSUE TITLE
A lot of Card images missing

### ISSUE THREAD

**Issue by TOSHIOOOOOOOOOOO** [Cockatrice/Cockatrice#4725]
(sorry for some possible broken english ahead)
I'm not sure if the problem is my internet or if i have a problem with my client, the card images are taking so long to load.
_______________________________________________________________________________________

Since Monday  for no apparent reason while i was playing the "downloadedPics" file went missing and even reinstalling the whole client (in a portable way or not and without saving the settings) or updating the card database i coundn't retrieve those files.
I asked a friend of mine do send me this file where was supposed to be the images but a lot of cards still missing and some of them are just appearing randomly (as if it were still being downloaded for a week) while in his client all the cards are there.
I even updated the card database again but nothing changed. 

![image](https://user-images.githubusercontent.com/121358965/209449243-68776c25-d71c-439a-8b6d-cf70060a824b.png)

as example the image of "A little chat" wasn't avaiable but appeared a little ago

![image](https://user-images.githubusercontent.com/121358965/209449784-7a8f8b49-6da3-4b26-8064-ef26f4fa914e.png)

The only way i found to load all the images of a deck was opening the whole list on a game and waiting to see if it would loud or not the images, what for some reason is a really slow process even if the cockatrice was the only thing consuming internet.    
_______________________________________________________________________________________

Here is the debug log
[debug log.txt](https://github.com/Cockatrice/Cockatrice/files/10299119/debug.log.txt)

**Comment by ebbit1q** [comment]
seems like it's not downloading pictures from scryfall and falling back to downloading them from gatherer instead, which might take longer. maybe scryfall was having a problem at that time? have you tried if disabling the previews fixes the issue?
