### ISSUE TITLE
Build for Debian Bullseye

### ISSUE THREAD

**Issue by skwerlman** [Cockatrice/Cockatrice#4731]
**Similar Requests**
N/A

**Description of New Feature**
Build releases for Debian Bullseye (11.6) in addition to Debian Buster (10.13)

**Additional Context**
At least one user has asked about Bullseye builds in the support channel on discord.

11.x has been the stable release train for over a year: 11.0 released in Aug 2021

**Comment by ebbit1q** [comment]
fixed by https://github.com/Cockatrice/Cockatrice/pull/4525 you can find these here: https://github.com/Cockatrice/Cockatrice/releases
