### ISSUE TITLE
Deck Editor: I keep finding cards moved to my sideboard.

### ISSUE THREAD

**Issue by Psithief** [Cockatrice/Cockatrice#474]
Perhaps I am trying to save with Ctrl+S and hitting S before Ctrl, or (more likely), I am under the impression that I have the deck editor search focussed and am typing card names. When they start with `S` I start having problems.

Could someone please change the shortcut key to not be an unmodified alphabetic key? Ctrl+something that's not already taken.

Reference commit: #332

**Comment by JoshuaLamusga** [comment]
Same as issue #2937

**Comment by ctrlaltca** [comment]
Fixed in #3116
