### ISSUE TITLE
Investigate alternate shuffling methods

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#475]
http://www.reddit.com/r/magicTCG/comments/2o73b4/incontrovertible_fact_of_the_unfairness_of_the/cmkj0sm

Algorithm P.

There's also mention of using /dev/random, which we should probably do.

**Comment by ZeldaZach** [comment]
No plans to look into this I assume?

**Comment by Daenyth** [comment]
No need

**Comment by tooomm** [comment]
On that reddit post, there are 2 links that I want to extract + archieve here as well:

> Even if you're following a proven shuffling algorithm by the book you can introduce a ton of biases - the most common ones I've personally seen are the ones listed on the wiki - implementation errors and then an insufficient pseudorandom generator. 

http://bost.ocks.org/mike/algorithms/#shuffling
http://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle#Potential_sources_of_bias

If someone wants to look at our implementation in detail that might be helpful.
