### ISSUE TITLE
Column headers appear blank and abiliy to sort is absent in 2.8.1-beta11 on Ubuntu 22.10

### ISSUE THREAD

**Issue by SlightlyCircuitous** [Cockatrice/Cockatrice#4750]
**System Information:**

Debug Log:

Client Version: 2.8.1-beta.11 (2023-02-10)
Client Operating System: Ubuntu 22.10
Build Architecture: 64-bit
Qt Version: 6.3.1
System Locale: en_US
Install Mode: Standard
---------------------------------------------------------------------------
Theme changed: "None "
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
Loaded qt translation "qt_en_US" at "/usr/share/qt6/translations"
Loaded "cockatrice" translation "cockatrice_en_US" at "/usr/bin/../share/cockatrice/translations"
main(): starting main program
main(): MainWindow constructor finished
Spoilers Disabled
main(): ui.show() finished
Startup: found config with current version
CardDatabase::loadCardDatabases start
[CockatriceXml4Parser] Trying to parse:  "/home/[user]/.local/share/Cockatrice/Cockatrice/cards.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
PictureLoader: cache fail for "_trice_card_back_282598"
PictureLoader: cache fail for "_trice_card_back_282599"
[CardDatabase] loadCardDatabase(): Path = "/home/[user]/.local/share/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 26401 Sets = 679 "1260ms"
[CockatriceXml4Parser] Trying to parse:  "/home/[user]/.local/share/Cockatrice/Cockatrice/tokens.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
[CardDatabase] loadCardDatabase(): Path = "/home/[user]/.local/share/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 27069 Sets = 679 "26ms"
[CardDatabase] loadCardDatabase(): Path = "/home/[user]/.local/share/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 27069 Sets = 679 "0ms"
Loading Custom Set 0 ( "/home/[user]/.local/share/Cockatrice/Cockatrice/customsets/TK.xml" )
[CockatriceXml4Parser] Trying to parse:  "/home/[user]/.local/share/Cockatrice/Cockatrice/customsets/TK.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
[CardDatabase] loadCardDatabase(): Path = "/home/[user]/.local/share/Cockatrice/Cockatrice/customsets/TK.xml" Status = 0 Cards = 27069 Sets = 679 "0ms"
--[Removed lines where it loads several custom sets without issues]--
CardDatabase::loadCardDatabases success

_______________________________________________________________________________________

Issue details:

Column headers are blank, as shown below, and I am unable to sort the columns at all. 

![Screenshot from 2023-02-15 11-34-17](https://user-images.githubusercontent.com/71394296/219094089-02c20c47-cf9d-46ea-8f50-4276aa4a33c7.png)

This issue was not present while using the Beta 10 .deb (or any previous Beta .deb) on Ubuntu 22.04.
This issue is present while using Beta 10 (built from source) on Ubuntu 22.10 and also while using the Beta 11 .deb on Ubuntu 22.10.
I have not tested building any other Beta versions or 2.8.0 from source on Ubuntu 22.10.
I am inclined to believe that this is a problem with Ubuntu/Gnome because of this, but I figured I would post this here anyway since I am unsure how else to proceed.

_______________________________________________________________________________________

**Steps to reproduce:**
 - Install Cockatrice beta 10 or beta 11 on Ubuntu 22.10.
 - Open client

**Comment by ebbit1q** [comment]
duplicate of #4696 similarities is the use of qt 6.3.1, possible upstream regression.

**Comment by SlightlyCircuitous** [comment]
Column headers display and sorting works as expected when running 2.8.1-beta12 on the Lunar Lobster (23.04) beta. Lunar is using Qt 6.4.2 so it could very well be that some Qt regression was fixed in a newer version.
