### ISSUE TITLE
Check for Client Updates shows update available on latest beta version

### ISSUE THREAD

**Issue by SlightlyCircuitous** [Cockatrice/Cockatrice#4751]
**System Information:**

Debug Log:

Client Version: 2.8.1-beta.11 (2023-02-10)
Client Operating System: Ubuntu 22.10
Build Architecture: 64-bit
Qt Version: 6.3.1
System Locale: en_US
Install Mode: Standard
---------------------------------------------------------------------------
Theme changed: "None "
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
Loaded qt translation "qt_en_US" at "/usr/share/qt6/translations"
Loaded "cockatrice" translation "cockatrice_en_US" at "/usr/bin/../share/cockatrice/translations"
main(): starting main program
main(): MainWindow constructor finished
Spoilers Disabled
main(): ui.show() finished
Startup: found config with current version
CardDatabase::loadCardDatabases start
[CockatriceXml4Parser] Trying to parse:  "/home/[user]/.local/share/Cockatrice/Cockatrice/cards.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
PictureLoader: cache fail for "_trice_card_back_282598"
PictureLoader: cache fail for "_trice_card_back_282599"
[CardDatabase] loadCardDatabase(): Path = "/home/[user]/.local/share/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 26401 Sets = 679 "1260ms"
[CockatriceXml4Parser] Trying to parse:  "/home/[user]/.local/share/Cockatrice/Cockatrice/tokens.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
[CardDatabase] loadCardDatabase(): Path = "/home/[user]/.local/share/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 27069 Sets = 679 "26ms"
[CardDatabase] loadCardDatabase(): Path = "/home/[user]/.local/share/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 27069 Sets = 679 "0ms"
Loading Custom Set 0 ( "/home/[user]/.local/share/Cockatrice/Cockatrice/customsets/TK.xml" )
[CockatriceXml4Parser] Trying to parse:  "/home/[user]/.local/share/Cockatrice/Cockatrice/customsets/TK.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
[CardDatabase] loadCardDatabase(): Path = "/home/[user]/.local/share/Cockatrice/Cockatrice/customsets/TK.xml" Status = 0 Cards = 27069 Sets = 679 "0ms"
--[Removed lines where it loads several custom sets without issues]--
CardDatabase::loadCardDatabases success

_______________________________________________________________________________________

Checking for client updates on the latest beta displays the following message, incorrectly indicating that there is a new client version available to download. Specifically, it doesn't seem to be able to tell that the current version that I am running and the latest version available for download are the same version. 

![Screenshot from 2023-02-15 19-02-32](https://user-images.githubusercontent.com/71394296/219223869-935707e8-d336-42e9-b700-0567a0407008.png)

I installed this using the provided 2.8.1-beta.11 .deb for Ubuntu 22.10 and have not built it from source.

_______________________________________________________________________________________

**Steps to reproduce:**
 - Run 2.8.1-beta11
 - Help > Check For Client Updates

**Comment by Elarnon** [comment]
Latest beta release has `target_commitish: "master"` (see https://api.github.com/repos/Cockatrice/Cockatrice/releases ) but Cockatrice compares that value with `"787c8d7"` which is the actual commit ID at the time of build.

I would assume [this](https://github.com/Cockatrice/Cockatrice/commit/787c8d740b997c9e432bfbd41c2ff3a2a16faae0#diff-73d26ed8f688bf0bdc3abc2d453358c8f72c00a45c082b2a2ecae0972018a8feR69) is the culprit.

**Comment by ebbit1q** [comment]
hmm, thanks for looking into that, that indeed seems to be the problem, but a bit different than what you'd expect (the names of these variables I just kept, they are arbitrary). I'll pr a fix now.
