### ISSUE TITLE
Searching in the mana cost of cards

### ISSUE THREAD

**Issue by ScorpioneOrzion** [Cockatrice/Cockatrice#4757]
Being able to search in the mana cost of cards.
It would then use the command m or mana

So for example
"mana:4" would search for any card where the mana cost is greater than or equal to {4}
"m:4 -m:5" would search for any card where the mana cost is greater than or equal to {4} and the mana cost is not greater than or equal to {5}

**Comment by skwerlman** [comment]
this is already possible: `mv:4` or `mv=4` finds all cards with a mana value of 4, `mv>=4` finds cards with a mana value greater than 4; theres also `<=`, `<` and `>` for less than or equal, less than, and greater then, respectively

**Comment by ebbit1q** [comment]
it is possible to search for any card property as if it were a string already, use `manacost:4` to search for cards with a 4 in their mana cost

**Comment by skwerlman** [comment]
is `manacost:` documented anywhere? it's not mentioned in the search syntax infobox, and there doesnt seem to be a wiki page on the search syntax

**Comment by ebbit1q** [comment]
it's not explicitly mentioned anywhere but all items inside the `<prop>` tags from the xml can be searched for (see https://github.com/Cockatrice/Cockatrice/wiki/Custom-Cards-&-Sets#to-add-your-own-custom-cards-follow-these-steps), the `<prop>` tags are able to contain anything which will then be searchable this way. while oracle and cockatrice look for this tag sometimes there is no code that explicitly defines `manacost:` in the search.

**Comment by skwerlman** [comment]
would it be feasible to dynamically add entries for each `<prop>` to the infobox based on the loaded xml? ones created by oracle could probably also have descriptions, tho i dont think descriptions are possible in general for custom `<prop>`s without maybe changing the xml format to add a way to include descriptions

**Comment by ebbit1q** [comment]
yes it would be possible to do that, the xml is just a template, maybe we could simply add a section to it that just notes all valid expressions
