### ISSUE TITLE
Unable to Reverse Relate Token to Card

### ISSUE THREAD

**Issue by jonidcrushfire** [Cockatrice/Cockatrice#4760]
Client Version: 2.8.1-beta.11 (2023-02-10)
Client Operating System: Windows 11 Version 2009
Build Architecture: 64-bit
Qt Version: 6.3.2

I am attempting to create a token in my custom set to specifically reverse relate it to Urza, Chief Artificer. I have tried to update the card database to fix a missing token (i.e. Urza is missing its related construct - which I would also like to report).

I am able to create tokens for other cards and related them to their appropriate cards, but for some reason, I cannot get this token to show up in the right-click context menu or the keyboard shortcut to create the token. Here is the way it looks in my notepad++:

	<card>
		<name>Construct Token   </name>
		<text>This creature gets +1/+1 for each artifact you control.</text>
		<prop>
			<layout>normal</layout>
			<side>front</side>
			<type>Token Artifact Creature</type>
			<maintype>Creature</maintype>
			<cmc>0</cmc>
			<pt>0/0</pt>
		</prop>
		<set rarity="common" uuid="MCST-00000006-Construct_Token" num="6" muid="9001" picurl="https://product-images.tcgplayer.com/fit-in/437x437/453476.jpg">MCST</set>
		<reverse-related>Urza, Chief Artificer</reverse-related>
		<token>1</token>
		<tablerow>2</tablerow>
	</card>

I did figure out that the several construct token names are separated by virtue of additional spaces at the end of their names, and this particular one is as seen above. But the main issue is the reverse related is not working for some reason. It *does* show in my list of cards and *does* show the appropriate art, annotations, etc, it just does not seem to let me create the token outside of manually opening the token menu and selecting it there. Can someone clarify if I am doing something wrong?

Please let me know if there is any additional information you require.

**Comment by ebbit1q** [comment]
please report missing tokens here: https://github.com/Cockatrice/Magic-Token

**Comment by ebbit1q** [comment]
at first glance I can already guess this token does not have enough spaces to make it unique compared to the many construct tokens already in the tokens file, this will lead to it not being used as a custom card because it exists already.

please suggest your edits to the Magic-Token repo so other people can use these tokens

**Comment by jonidcrushfire** [comment]
Apologies for asking about the token in the wrong section - I am still somewhat unfamiliar with how to navigate this site.

It looks like I did have to add enough spaces to make it an entirely unique item. I was hoping to simply have it associate the correct token, but all's well that ends well, I suppose.

Thank you for your patience and help!
