### ISSUE TITLE
Banned 

### ISSUE THREAD

**Issue by MoeLiva** [Cockatrice/Cockatrice#4761]
**System Information:**

_______________________________________________________________________________________

Hello I was recently perma banned on my account MoeLiva I took a shower after playing modern with some friends and came upstairs too my brother laughing hysterically and apparently he got me banned  I dont even want too know what he said cause hes done this before. I would like too have this issue resolved if possible because this is my only way of testing new decks without spending 1000s or printing them

_______________________________________________________________________________________

**Steps to reproduce:**
 - Do A
 - Do B
 - Do C ...

**Comment by ebbit1q** [comment]
this board is for reporting issues with the software, not any of the public servers, you should contact your server operator instead.
