### ISSUE TITLE
Custom cards from MSE doesen't show

### ISSUE THREAD

**Issue by ximocm** [Cockatrice/Cockatrice#4768]
**System Information:**
Client Version: 2.8.0 (2021-01-26)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.12.9
System Locale: es_ES
Install Mode: Standard
---------------------------------------------------------------------------
Theme changed: "Default"
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
Language changed: ""
main(): starting main program
main(): MainWindow constructor finished
Spoilers Disabled
main(): ui.show() finished
Startup: found config with current version
CardDatabase::loadCardDatabases start
[CockatriceXml4Parser] Trying to parse:  "C:/Users/ximoc/AppData/Local/Cockatrice/Cockatrice/cards.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
[CardDatabase] loadCardDatabase(): Path = "C:/Users/ximoc/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 26449 Sets= 690
[CockatriceXml4Parser] Trying to parse:  "C:/Users/ximoc/AppData/Local/Cockatrice/Cockatrice/tokens.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
[CardDatabase] loadCardDatabase(): Path = "C:/Users/ximoc/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 27117 Sets= 690
[CardDatabase] loadCardDatabase(): Path = "C:/Users/ximoc/AppData/Local/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 27117 Sets= 690
Loading Custom Set 0 ( "C:/Users/ximoc/AppData/Local/Cockatrice/Cockatrice/customsets/cards.xml" )
[CockatriceXml4Parser] Trying to parse:  "C:/Users/ximoc/AppData/Local/Cockatrice/Cockatrice/customsets/cards.xml"
[CockatriceXml4Parser] Parsing failed: wrong version 3
[CockatriceXml3Parser] Trying to parse:  "C:/Users/ximoc/AppData/Local/Cockatrice/Cockatrice/customsets/cards.xml"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/ximoc/AppData/Local/Cockatrice/Cockatrice/customsets/cards.xml" Status = 0 Cards = 27148 Sets= 691
CardDatabase::loadCardDatabases success

_______________________________________________________________________________________

When i load the custom set, only 31 from 110 cards are shown.

_______________________________________________________________________________________

**Steps to reproduce:**
 - Export xml from magic set editor
 - Move pics to custom pics
 - Move cards to custom cards
 - Execute cockatrice

**Comment by skwerlman** [comment]
Can you validate the generated database against this XSD: https://github.com/Cockatrice/Cockatrice/blob/master/doc/carddatabase_v3/cards.xsd

See here for how: https://github.com/Cockatrice/Cockatrice/wiki/Custom-Cards-&-Sets#diagnosing-problems-in-your-xml-file

**Comment by ebbit1q** [comment]
This is an issue with MSE's exporter, not cockatrice, you can find the most recent version of it here: https://github.com/MagicSetEditorPacks/Full-Magic-Pack

Please try the most recent version of the exporter which will output xml v4 before opening a ticket on there.
