### ISSUE TITLE
Cleanup Step

### ISSUE THREAD

**Issue by Grim-the-Reaper** [Cockatrice/Cockatrice#477]
The phase bar is missing the cleanup step, which is technically part of the game
While it's the least important phase for gameplay purposes, there is little reason not to add it.

Advantages of adding the step:
- Players can indicate they are still in the process of discarding cards..
- The phase bar becomes slightly less wide (due to the icons being vector based, they will resize to smaller squares, hence reducing the width of the bar)

**Comment by ZeldaZach** [comment]
Dupe #1740
