### ISSUE TITLE
unregistered----Solved

### ISSUE THREAD

**Issue by Kirito61745** [Cockatrice/Cockatrice#4775]
**System Information:**
Version: 2.8.0

______________________
_________________________________________________________________

I have an account, but I am unregistered as a status. I want to register, but I can't. I need help on that issue.

_______________________________________________________________________________________

**Steps to reproduce:**
 - Do A
 - Do B
 - Do C ...

**Comment by ebbit1q** [comment]
which server? there are multiple servers. there is currently only one public server that supports unregistered accounts though, if you want to create an account for chickatrice you have to do so on their website. the other two public servers allow you to register by using the register option in the drop down menu, it's right below connect.
