### ISSUE TITLE
Room

### ISSUE THREAD

**Issue by Kirito61745** [Cockatrice/Cockatrice#4776]
**System Information:**
Version: 2.8.0

_______________________________________________________________________________________

I am trying to play with other players, but I don't see a tab for magic at all. I am a registered user now, but the magic tab is still unavailable. I can only see the registered room and public room, no magic room. I remember in the past there was a main room, not sure what happened to it. 

_______________________________________________________________________________________

**Steps to reproduce:**
 - Do A
 - Do B
 - Do C ...

**Comment by SlightlyCircuitous** [comment]
Which server are you connected to?

**Comment by Kirito61745** [comment]
> Which server are you connected to?

I'm not sure, but under the port box it says 4748

**Comment by Kirito61745** [comment]
> Which server are you connected to?

![image](https://user-images.githubusercontent.com/128571830/227384294-6ef59031-a0ff-4c99-9d3d-5921b1036d16.png)

**Comment by ebbit1q** [comment]
chickatrice is a different server, you were probably connected to rooster ranges before, which has a main room, and a lot more users.

**Comment by Kirito61745** [comment]
> chickatrice is a different server, you were probably connected to rooster ranges before, which has a main room, and a lot more users.

can I move over or what should I do when registering for a new account?

**Comment by SlightlyCircuitous** [comment]
If you want to register to Rooster Ranges, you should be able to use `Cockatrice > Register to server...` to pull up the registration box for that server. It should auto-fill the Host field to 'server.cockatrice.us' (which is Rooster Ranges) and the Port field. Fill out the rest, submit it, then verify your email and you should be good to connect. Just make sure when you connect, you are connecting to Rooster Ranges.
