### ISSUE TITLE
Any plans for a new release?

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#4781]
The last release is very old and there have been many changes, fixes and new improvements over the last two years.

What is holding a new release back?
Any blockers, open PRs or pending issues that should make it in?

<br>

Next release should be v2.9.0 imho... not v2.8.1

**Comment by ebbit1q** [comment]
#4736

**Comment by tooomm** [comment]
#4787
#4791
#4785
#4796

#4792
