### ISSUE TITLE
Operations on life

### ISSUE THREAD

**Issue by Ignell** [Cockatrice/Cockatrice#4782]
When setting Life you could accept also operations in order to update the Life Total.

For example: if you have 20 Life and take 5 damage, right now you have 2 possibilità to update the Life:
1) right click the Life 5 times to reduce your life by 1, 5 times (in the chat you see your life ticking away).
2) do the calculation on your own, ask the program to set your life total and type "15" (in the chat you see that your life has gone down by 5).

I suggest that you should add another option:
When you ask the program to set your life total you could tell him "-5", he see that the fist character is an operation and do that operation for you on the Life Total that now is 15 (in the chat you see that your life has gone down by 5)

This could also be beneficial when adding, doubling and halving life.

**Comment by ebbit1q** [comment]
the set counter dialog is prefilled with the current value, is simply adding -5 to the end of this not sufficient?
![image](https://user-images.githubusercontent.com/36401181/229357748-eeefb727-16ce-4f1b-afb5-869991ed8717.png)

to halve it use the division operator: /
![image](https://user-images.githubusercontent.com/36401181/229357788-fb9adeaf-3400-470b-b669-f3f6c99e8a7e.png)

note that this rounds down, if you want it to do proper rounding use the round function
![image](https://user-images.githubusercontent.com/36401181/229357950-6a238d56-99f2-4710-a987-6cb7bc4ce946.png)

**Comment by ebbit1q** [comment]
for reference, the recognized expressions are from [https://github.com/yhirose/cpp-peglib#cpp-peglib](cpp-peglib) they have been in cockatrice since https://github.com/Cockatrice/Cockatrice/pull/3534
