### ISSUE TITLE
Card legality missing on certain cards

### ISSUE THREAD

**Issue by Reanamet** [Cockatrice/Cockatrice#4783]
The issue is extremely simple. Using syntax to filter out cards illegal in EDH (typing in "legal:commander" into the searchbar) also filters out the Lightning Bolt.

![fig1](https://user-images.githubusercontent.com/129909710/229942661-88865853-e96d-49aa-8ce1-835a3aa9cddc.png)
![fig2](https://user-images.githubusercontent.com/129909710/229942667-d64be685-2a57-4f05-9f9e-8743047e27c4.png)

**Comment by ebbit1q** [comment]
it isn't marked "illegal" it is not marked in any way, this is an issue with how oracle interprets mtgjson's data, it'll take the first instance of every card it finds in their data and only take the set it was in from the other printings.

some of the more limited sets on mtgjson do not include format legality in the data, I'm not sure if this is an issue on their end but it results in this information not making it into cockatrice.
