### ISSUE TITLE
Updater doesn't work

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#4792]
**System Information:**
Client Version: 2.8.1-custom(4b3dc2d) (2023-04-20)
Client Operating System: Windows 11 Version 2009
Build Architecture: 64-bit
Qt Version: 6.3.2
System Locale: en_DE
Install Mode: Standard

_______________________________________________________________________________________

Running the updater correctly finds a new stable release, but don't let me install it and reports that there are no suitable packages available.
<img width="380" alt="image" src="https://user-images.githubusercontent.com/9874850/233827883-16018a32-e8aa-4d3c-86a3-11346839d827.png">

These kind of "downgrade" from more recent dev or beta versions back to latest stable used to work.

<br>

Trying to go from 2.8.0 to latest beta has the same result: (also see the difference in window sizing #4793)
<img width="259" alt="image" src="https://user-images.githubusercontent.com/9874850/233828844-abde1e24-e8e6-46fa-a401-8c9316570e6e.png">

**Comment by ebbit1q** [comment]
this is caused by the change in naming scheme

**Comment by tooomm** [comment]
![grafik](https://user-images.githubusercontent.com/9874850/235296769-51853918-d181-4024-9f5f-7d3c548570cb.png)
beta.12 finds beta.13 correctly and allows to install. Starting with beta.11 it should work.

Hmm. Basically all user will have to install a new release manually as the updater is broken, that's bad.

Can we have the old file names as well in the release? But then the installer should check which version of Windows is running and prevent installation on Win7 with a useful hint where to download the right one. That way at least only a few Win7 users are affected.
Looking at the download numbers of the releases with separate Win7 exe. It's downloaded by ~7% of Windows users only.

**Comment by ebbit1q** [comment]
we could change the naming scheme again, as long as it doesn't break we can keep the win7 build but if it stops working we can just remove it.

**Comment by tooomm** [comment]
You want to revert the naming scheme back to `win32` and `win64`? And also have a `win7_64` for example?

Win7 users can not run Qt6 (removed support for Win7 already). So the `win64` installer would still need to check for the running os and show a message that users need to get the old Qt5 (`win7_64` installer), and where to get it.
Similar to the hint that shows on 64bit machines when users try to install a 32bit version.

**Comment by ebbit1q** [comment]
we could also have the win7 one as the default, it works on both

**Comment by tooomm** [comment]
Just tried the Win7, 64bit, Qt5 one again on Windows 10 and Windows 11 to be sure. It works. 👍 
So `win64`, `win10_64` and `win32`? I do not recall the exact updater logic we used to have.

Any issues or things to consider if we put win7 as the temporary default on Win because it will be Qt5 based for example? I remember several issues with sounds - but those got fixed I think.

**Comment by tooomm** [comment]
> we could also have the win7 one as the default, it works on both

The Win7 one does run on newer as well, true. But actually, this would have some drawbacks on newer machines as Qt5 does not deal very well with high resolution screens.

The initial issue is resolved with the new release, and the updater finds the binaries with the changed naming pattern on both channels.
https://github.com/Cockatrice/Cockatrice/blob/master/cockatrice/src/releasechannel.cpp#L44
