### ISSUE TITLE
Win 11: Layout issues

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#4793]
**System Information:**
Client Version: 2.8.1-custom(4b3dc2d) (2023-04-20)
Client Operating System: Windows 11 Version 2009
Build Architecture: 64-bit
Qt Version: 6.3.2
System Locale: en_DE
Install Mode: Standard

_______________________________________________________________________________________

Oracle window is kinda broken:
<img width="392" alt="image" src="https://user-images.githubusercontent.com/9874850/233826771-777efb7e-f83d-4af8-8387-48ff4f00f07c.png">

The title is not fully displayed, and the window icons for e.g. closing are also hidden.

**Comment by tooomm** [comment]
With 2.8.0 on the same machine the result look different:

<img width="266" alt="image" src="https://user-images.githubusercontent.com/9874850/233828665-7c8a86cb-840e-432e-9e58-601bcf404b84.png">
<img width="272" alt="image" src="https://user-images.githubusercontent.com/9874850/233828701-5c48eddc-52e8-445d-b326-a317c64f996b.png">

This is a full hd resolution screen with 150% scaling.

**Comment by ebbit1q** [comment]
that 2.8.0 one also looks wrong, this is a scaling issue: https://github.com/Cockatrice/Cockatrice/issues/1937

**Comment by ebbit1q** [comment]
closing as duplicate
