### ISSUE TITLE
MAT Narset, Enlightened Exile Image Download Prevents Other Images From Loading

### ISSUE THREAD

**Issue by jonidcrushfire** [Cockatrice/Cockatrice#4802]
Client Version: 2.8.1-beta.11 (2023-02-10)
PictureLoader: [card:  "Seer of Stolen Sight"  set:  "MOM" ]: Trying to load picture
PictureLoader: [card:  "Seer of Stolen Sight"  set:  "MOM" ]: Picture found on disk.
PictureLoader: [card:  "Fathom Mage"  set:  "NCC" ]: Trying to load picture
PictureLoader: [card:  "Fathom Mage"  set:  "NCC" ]: Picture found on disk.
PictureLoader: [card:  "Weather the Storm"  set:  "MH1" ]: Trying to load picture
PictureLoader: [card:  "Weather the Storm"  set:  "MH1" ]: Picture found on disk.
PictureLoader: [card:  "Sword of the Animist"  set:  "AFC" ]: Trying to load picture
PictureLoader: [card:  "Sword of the Animist"  set:  "AFC" ]: Picture found on disk.
PictureLoader: [card:  "Tamiyo, Collector of Tales"  set:  "WAR" ]: Trying to load picture
PictureLoader: [card:  "Tamiyo, Collector of Tales"  set:  "WAR" ]: Picture found on disk.
PictureLoader: [card:  "Zimone and Dina"  set:  "MOM" ]: Trying to load picture
PictureLoader: [card:  "Zimone and Dina"  set:  "MOM" ]: Picture found on disk.
PictureLoader: [card:  "Fiend Artisan"  set:  "IKO" ]: Trying to load picture
PictureLoader: [card:  "Fiend Artisan"  set:  "IKO" ]: Picture found on disk.
PictureLoader: [card:  "Protean Hulk"  set:  "DIS" ]: Trying to load picture
PictureLoader: [card:  "Protean Hulk"  set:  "DIS" ]: Picture found on disk.
PictureLoader: [card:  "Teferi's Ageless Insight"  set:  "M21" ]: Trying to load picture
PictureLoader: [card:  "Teferi's Ageless Insight"  set:  "M21" ]: Picture found on disk.
PictureLoader: [card:  "Aetherflux Reservoir"  set:  "KLD" ]: Trying to load picture
PictureLoader: [card:  "Aetherflux Reservoir"  set:  "KLD" ]: Picture found on disk.
PictureLoader: [card:  "Fyndhorn Elder"  set:  "8ED" ]: Trying to load picture
PictureLoader: [card:  "Fyndhorn Elder"  set:  "8ED" ]: Picture found on disk.
PictureLoader: [card:  "Inexorable Tide"  set:  "MM2" ]: Trying to load picture
PictureLoader: [card:  "Inexorable Tide"  set:  "MM2" ]: Picture found on disk.
PictureLoader: [card:  "Emiel the Blessed"  set:  "2X2" ]: Trying to load picture
PictureLoader: [card:  "Emiel the Blessed"  set:  "2X2" ]: Picture found on disk.
PictureLoader: [card:  "Skirge Familiar"  set:  "MH2" ]: Trying to load picture
PictureLoader: [card:  "Skirge Familiar"  set:  "MH2" ]: Picture found on disk.
PictureLoader: [card:  "Displacer Kitten"  set:  "CLB" ]: Trying to load picture
PictureLoader: [card:  "Displacer Kitten"  set:  "CLB" ]: Picture found on disk.
PictureLoader: [card:  "Nissa's Expedition"  set:  "C21" ]: Trying to load picture
PictureLoader: [card:  "Nissa's Expedition"  set:  "C21" ]: Picture found on disk.
PictureLoader: [card:  "Sidisi, Undead Vizier"  set:  "DTK" ]: Trying to load picture
PictureLoader: [card:  "Sidisi, Undead Vizier"  set:  "DTK" ]: Picture found on disk.
PictureLoader: [card:  "Wing Splicer"  set:  "MM3" ]: Trying to load picture
PictureLoader: [card:  "Wing Splicer"  set:  "MM3" ]: Picture found on disk.
PictureLoader: [card:  "Peek"  set:  "10E" ]: Trying to load picture
PictureLoader: [card:  "Peek"  set:  "10E" ]: Picture found on disk.
PictureLoader: [card:  "Empty the Warrens"  set:  "MMA" ]: Trying to load picture
PictureLoader: [card:  "Empty the Warrens"  set:  "MMA" ]: Picture found on disk.
PictureLoader: [card:  "Increasing Ambition"  set:  "DKA" ]: Trying to load picture
PictureLoader: [card:  "Increasing Ambition"  set:  "DKA" ]: Picture found on disk.
PictureLoader: [card:  "Circuitous Route"  set:  "ZNC" ]: Trying to load picture
PictureLoader: [card:  "Circuitous Route"  set:  "ZNC" ]: Picture found on disk.
PictureLoader: [card:  "Rupture Spire"  set:  "C20" ]: Trying to load picture
PictureLoader: [card:  "Rupture Spire"  set:  "C20" ]: Picture found on disk.
PictureLoader: [card:  "Vitalizing Wind"  set:  "PCY" ]: Trying to load picture
PictureLoader: [card:  "Vitalizing Wind"  set:  "PCY" ]: Picture found on disk.
PictureLoader: [card:  "Archaeomancer"  set:  "UMA" ]: Trying to load picture
PictureLoader: [card:  "Archaeomancer"  set:  "UMA" ]: Picture found on disk.
PictureLoader: [card:  "Riku of Two Reflections"  set:  "2XM" ]: Trying to load picture
PictureLoader: [card:  "Riku of Two Reflections"  set:  "2XM" ]: Picture found on disk.
PictureLoader: [card:  "Chulane, Teller of Tales"  set:  "ELD" ]: Trying to load picture
PictureLoader: [card:  "Chulane, Teller of Tales"  set:  "ELD" ]: Picture found on disk.
PictureLoader: [card:  "The Locust God"  set:  "MOC" ]: Trying to load picture
PictureLoader: [card:  "The Locust God"  set:  "MOC" ]: Picture found on disk.
PictureLoader: [card:  "Folio of Fancies"  set:  "ELD" ]: Trying to load picture
PictureLoader: [card:  "Folio of Fancies"  set:  "ELD" ]: Picture found on disk.
PictureLoader: [card:  "The Reaver Cleaver"  set:  "DMC" ]: Trying to load picture
PictureLoader: [card:  "The Reaver Cleaver"  set:  "DMC" ]: Picture found on disk.
PictureLoader: [card:  "Sprout Swarm"  set:  "FUT" ]: Trying to load picture
PictureLoader: [card:  "Sprout Swarm"  set:  "FUT" ]: Picture found on disk.
PictureLoader: [card:  "Taigam, Ojutai Master"  set:  "C17" ]: Trying to load picture
PictureLoader: [card:  "Taigam, Ojutai Master"  set:  "C17" ]: Picture found on disk.
PictureLoader: [card:  "Primeval Titan"  set:  "MM2" ]: Trying to load picture
PictureLoader: [card:  "Primeval Titan"  set:  "MM2" ]: Picture found on disk.
PictureLoader: [card:  "Oona's Grace"  set:  "C19" ]: Trying to load picture
PictureLoader: [card:  "Oona's Grace"  set:  "C19" ]: Picture found on disk.
PictureLoader: [card:  "Klauth, Unrivaled Ancient"  set:  "AFC" ]: Trying to load picture
PictureLoader: [card:  "Klauth, Unrivaled Ancient"  set:  "AFC" ]: Picture found on disk.
PictureLoader: [card:  "Praetor's Counsel"  set:  "C14" ]: Trying to load picture
PictureLoader: [card:  "Praetor's Counsel"  set:  "C14" ]: Picture found on disk.
PictureLoader: [card:  "Tamiyo, the Moon Sage"  set:  "AVR" ]: Trying to load picture
PictureLoader: [card:  "Tamiyo, the Moon Sage"  set:  "AVR" ]: Picture found on disk.
PictureLoader: [card:  "Finale of Devastation"  set:  "WAR" ]: Trying to load picture
PictureLoader: [card:  "Finale of Devastation"  set:  "WAR" ]: Picture found on disk.
PictureLoader: [card:  "Neoform"  set:  "WAR" ]: Trying to load picture
PictureLoader: [card:  "Neoform"  set:  "WAR" ]: Picture found on disk.
PictureLoader: [card:  "Yawgmoth's Bargain"  set:  "UDS" ]: Trying to load picture
PictureLoader: [card:  "Yawgmoth's Bargain"  set:  "UDS" ]: Picture found on disk.
PictureLoader: [card:  "Profane Tutor"  set:  "MH2" ]: Trying to load picture
PictureLoader: [card:  "Profane Tutor"  set:  "MH2" ]: Picture found on disk.
PictureLoader: [card:  "Tribute to the World Tree"  set:  "MOM" ]: Trying to load picture
PictureLoader: [card:  "Tribute to the World Tree"  set:  "MOM" ]: Picture found on disk.
PictureLoader: [card:  "Urborg Scavengers"  set:  "MAT" ]: Trying to load picture
PictureLoader: [card:  "Urborg Scavengers"  set:  "MAT" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Urborg Scavengers"  set:  "MAT" ]: Trying to download picture from url: "https://api.scryfall.com/cards/4dbb4d8f-8ae3-4052-9c6a-e56e96cec832?format=image&face=front"
PictureLoader: [card:  "Urborg Scavengers"  set:  "MAT" ]: Image successfully downloaded from  "https://api.scryfall.com/cards/4dbb4d8f-8ae3-4052-9c6a-e56e96cec832?format=image&face=front"
PictureLoader: [card:  "Undercity Upheaval"  set:  "MAT" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Undercity Upheaval"  set:  "MAT" ]: Requested set property ( "muid" ) for Url template ( "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Undercity Upheaval"  set:  "MAT" ]: Trying to load picture
PictureLoader: [card:  "Undercity Upheaval"  set:  "MAT" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Undercity Upheaval"  set:  "MAT" ]: Trying to download picture from url: "https://api.scryfall.com/cards/acfe6957-d971-413f-b075-01b995f1d7a3?format=image&face=front"
PictureLoader: [card:  "Undercity Upheaval"  set:  "MAT" ]: Image successfully downloaded from  "https://api.scryfall.com/cards/acfe6957-d971-413f-b075-01b995f1d7a3?format=image&face=front"
PictureLoader: [card:  "Tyvar the Bellicose"  set:  "MAT" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Tyvar the Bellicose"  set:  "MAT" ]: Requested set property ( "muid" ) for Url template ( "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Tyvar the Bellicose"  set:  "MAT" ]: Trying to load picture
PictureLoader: [card:  "Tyvar the Bellicose"  set:  "MAT" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Tyvar the Bellicose"  set:  "MAT" ]: Trying to download picture from url: "https://api.scryfall.com/cards/01a543f0-72fe-4a30-a4a0-356971c1c68a?format=image&face=front"
PictureLoader: [card:  "Tyvar the Bellicose"  set:  "MAT" ]: Image successfully downloaded from  "https://api.scryfall.com/cards/01a543f0-72fe-4a30-a4a0-356971c1c68a?format=image&face=front"
PictureLoader: [card:  "Tranquil Frillback"  set:  "MAT" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Tranquil Frillback"  set:  "MAT" ]: Requested set property ( "muid" ) for Url template ( "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Tranquil Frillback"  set:  "MAT" ]: Trying to load picture
PictureLoader: [card:  "Tranquil Frillback"  set:  "MAT" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Tranquil Frillback"  set:  "MAT" ]: Trying to download picture from url: "https://api.scryfall.com/cards/5b647377-d47e-4630-8ccc-933ef6127880?format=image&face=front"
PictureLoader: [card:  "Tranquil Frillback"  set:  "MAT" ]: Image successfully downloaded from  "https://api.scryfall.com/cards/5b647377-d47e-4630-8ccc-933ef6127880?format=image&face=front"
PictureLoader: [card:  "Training Grounds"  set:  "MAT" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Training Grounds"  set:  "MAT" ]: Requested set property ( "muid" ) for Url template ( "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Training Grounds"  set:  "MAT" ]: Trying to load picture
PictureLoader: [card:  "Training Grounds"  set:  "MAT" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Training Grounds"  set:  "MAT" ]: Trying to download picture from url: "https://api.scryfall.com/cards/991c27ed-f53c-48c6-8c12-282f44b8d441?format=image&face=front"
PictureLoader: [card:  "Training Grounds"  set:  "MAT" ]: Image successfully downloaded from  "https://api.scryfall.com/cards/991c27ed-f53c-48c6-8c12-282f44b8d441?format=image&face=front"
PictureLoader: [card:  "Tolarian Contempt"  set:  "MAT" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Tolarian Contempt"  set:  "MAT" ]: Requested set property ( "muid" ) for Url template ( "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Tolarian Contempt"  set:  "MAT" ]: Trying to load picture
PictureLoader: [card:  "Tolarian Contempt"  set:  "MAT" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Tolarian Contempt"  set:  "MAT" ]: Trying to download picture from url: "https://api.scryfall.com/cards/f72a9deb-9329-4930-a906-136c26490d52?format=image&face=front"
PictureLoader: [card:  "Tolarian Contempt"  set:  "MAT" ]: Image successfully downloaded from  "https://api.scryfall.com/cards/f72a9deb-9329-4930-a906-136c26490d52?format=image&face=front"
PictureLoader: [card:  "Narset, Enlightened Exile 10*"  set:  "MAT" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Narset, Enlightened Exile 10*"  set:  "MAT" ]: Requested set property ( "muid" ) for Url template ( "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Narset, Enlightened Exile 10*"  set:  "MAT" ]: Trying to load picture
PictureLoader: [card:  "Narset, Enlightened Exile 10*"  set:  "MAT" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Narset, Enlightened Exile 10*"  set:  "MAT" ]: Trying to download picture from url: "https://api.scryfall.com/cards/827ecc44-0b00-4515-8953-bc91fa03705a?format=image&face=front"
PictureLoader: [card:  "Nissa, Resurgent Animist"  set:  "MAT" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Nissa, Resurgent Animist"  set:  "MAT" ]: Requested set property ( "muid" ) for Url template ( "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Nissa, Resurgent Animist"  set:  "MAT" ]: Trying to load picture
PictureLoader: [card:  "Nissa, Resurgent Animist"  set:  "MAT" ]: Picture not found on disk, trying to download

This is my debug log. I was trying to click each new card in MAT and get its picture to download on my drive. Once I got to Narset, I noticed an issue with the name. It has an asterisk and is failing to load. After starting that download, it fails to attempt to download any other card image until I close the client and restart.

If there is any more information I can provide, please let me know. Thank you.

**Comment by ebbit1q** [comment]
```
PictureLoader: [card: "Narset, Enlightened Exile 10*" set: "MAT"]: Requested "set"property ("muid") for Url template ("https://api.scryfall.com/cards/multiverse/!set:muid!?format=image") is not available
PictureLoader: [card: "Narset, Enlightened Exile 10*" set: "MAT"]: Requested "set"property ("muid") for Url template ("https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card") is not available
PictureLoader: [card: "Narset, Enlightened Exile 10*" set: "MAT"]: Trying to load picture
PictureLoader: [card: "Narset, Enlightened Exile 10*" set: "MAT"]: No custom picture, trying to download
PictureLoader: [card: "Narset of the Ancient Way" set: "IKO"]: Trying to fetch picture from url "https://api.scryfall.com/cards/fa7b28d8-b835-44a0-978d-cadfd392fff5?format=image&face=front"
PictureLoader: [card: "Narset of the Ancient Way" set: "IKO"]: following redirect to "https://cards.scryfall.io/large/front/f/a/fa7b28d8-b835-44a0-978d-cadfd392fff5.jpg?1591228120"
PictureLoader: [card: "Narset of the Ancient Way" set: "IKO"]: Image successfully downloaded from url "https://cards.scryfall.io/large/front/f/a/fa7b28d8-b835-44a0-978d-cadfd392fff5.jpg?1591228120"
PictureLoader: [card: "Narset, Enlightened Exile 10*" set: "MAT"]: Trying to fetch picture from url "https://api.scryfall.com/cards/827ecc44-0b00-4515-8953-bc91fa03705a?format=image&face=front"
PictureLoader: [card: "Narset, Enlightened Exile 10*" set: "MAT"]: following redirect to "https://cards.scryfall.io/large/front/8/2/827ecc44-0b00-4515-8953-bc91fa03705a.jpg?1683093903"
PictureLoader: [card: "Narset, Enlightened Exile 10*" set: "MAT"]: Image successfully downloaded from url "https://cards.scryfall.io/large/front/8/2/827ecc44-0b00-4515-8953-bc91fa03705a.jpg?1683093903"
PictureLoader: [card: "Narset, Enlightened Master" set: "KTK"]: Trying to load picture
PictureLoader: [card: "Narset, Enlightened Master" set: "KTK"]: No custom picture, trying to download
PictureLoader: [card: "Narset, Enlightened Master" set: "KTK"]: Trying to fetch picture from url "https://api.scryfall.com/cards/f210adb7-b389-4672-a3eb-0ced9bfe190c?format=image&face=front"
PictureLoader: [card: "Narset, Enlightened Master" set: "KTK"]: following redirect to "https://cards.scryfall.io/large/front/f/2/f210adb7-b389-4672-a3eb-0ced9bfe190c.jpg?1562795852"
PictureLoader: [card: "Narset, Enlightened Master" set: "KTK"]: Image successfully downloaded from url "https://cards.scryfall.io/large/front/f/2/f210adb7-b389-4672-a3eb-0ced9bfe190c.jpg?1562795852"
```

Can't reproduce, check if you have enough disk space then try if clearing your downloaded images (in the settings) solves the issue.

**Comment by ebbit1q** [comment]
Doing a card update just now I noticed the 10* is no longer in the card name, this probably fixed the issue.

My suspicion is that the main issue is that the asterisk is a special character that isn't allowed in file names on windows (but only windows). I think it might be best to make a separate bug ticket for that and close this one.

**Comment by jonidcrushfire** [comment]
Thank you. I hope that will fix it. I am ok to close this.
