### ISSUE TITLE
Fate Seal Menu Option

### ISSUE THREAD

**Issue by Tittliewinks22** [Cockatrice/Cockatrice#4813]
Is it possible to add "Reveal top card of library to opponents" and "reveal top card of library to all players" to the shortcut options?

**Comment by ebbit1q** [comment]
revealing to all opponents but not to yourself isn't currently an action, how often do you want to do this? is revealing to one person at a time not sufficient?

reveal top card of library to all players is already an action, all actions have the option to add a shortcut, the default for revealing the top card to all players is ctrl+n

**Comment by Tittliewinks22** [comment]
We use reveal to opponents alot.  We dont use cockatruce for mtg

**Comment by Tittliewinks22** [comment]
Primarily alot of fate sealing in what we do.

**Comment by ZeldaZach** [comment]
![image](https://github.com/user-attachments/assets/67571e1d-4fa5-4327-84e2-7fde9f5bcf29)

Was already done. Enjoy!
