### ISSUE TITLE
Unable to Rearrange URLs in Card Sources

### ISSUE THREAD

**Issue by SlightlyCircuitous** [Cockatrice/Cockatrice#4815]
**System Information:**

Client Version: 2.8.1-beta.14 (2023-04-30)
Client Operating System: Ubuntu 23.04
Build Architecture: 64-bit
Qt Version: 6.4.2
System Locale: en_US
Install Mode: Standard
---------------------------------------------------------------------------
Theme changed: "None "
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
Loaded qt translation "qt_en_US" at "/usr/share/qt6/translations"
Loaded "cockatrice" translation "cockatrice_en_US" at "/usr/bin/../share/cockatrice/translations"
main(): starting main program
main(): MainWindow constructor finished
Spoilers Disabled
main(): ui.show() finished
Startup: found config with current version
CardDatabase::loadCardDatabases start
[CockatriceXml4Parser] Trying to parse:  "/home/[username]/.local/share/Cockatrice/Cockatrice/cards.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
PictureLoader: cache fail for "_trice_card_back_289599"
PictureLoader: cache fail for "_trice_card_back_289601"
[CardDatabase] loadCardDatabase(): Path = "/home/[username]/.local/share/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 27262 Sets = 703 "1950ms"
[CockatriceXml4Parser] Trying to parse:  "/home/[username]/.local/share/Cockatrice/Cockatrice/tokens.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
[CardDatabase] loadCardDatabase(): Path = "/home/[username]/.local/share/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 27964 Sets = 703 "39ms"
[CardDatabase] loadCardDatabase(): Path = "/home/[username]/.local/share/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 27964 Sets = 703 "0ms"
[Truncated loading of several custom sets]
CardDatabase::loadCardDatabases success
_______________________________________________________________________________________

In `Settings > Card Sources`, I am unable to drag the URLs in the URL Download Priority Box to rearrange their priority. I can click on a URL and drag a copy of it up or down, but when I release the mouse button, it simply disappears rather than moving to a new position. It is similar to if one clicks and drags a UI element that is not supposed to move: a little copy of the element follows the mouse, but can't actually be moved anywhere.

![Screenshot from 2023-06-12 12-27-26](https://github.com/Cockatrice/Cockatrice/assets/71394296/6bb52d6f-832f-4e81-9782-0f22cdfd4a89)
Picture shows me attempting to drag the top URL to the bottom of the list. Note the crossed out circle on the cursor and the duplication of the highlighted URL. 
_______________________________________________________________________________________
**Steps to reproduce:**
 - Open`Settings > Card Sources`
 - Drag any URL in the URL Download Priority Box

**Comment by ebbit1q** [comment]
I am unable to reproduce this, could be specific to qt 6.4?

**Comment by SlightlyCircuitous** [comment]
I'm not sure as I have never tried to do it on any other version of Ubuntu/Qt. It wouldn't be the first time I found a UI bug that was Qt's fault though.

**Comment by SlightlyCircuitous** [comment]
Was playing around in Pop!_OS 22.04, which uses Qt 6.2.4, and I can rearrange the URLs as normal. This is likely an issue with 6.4 specifically.
