### ISSUE TITLE
I can't register my account

### ISSUE THREAD

**Issue by Keyser7Soze** [Cockatrice/Cockatrice#4824]
Client Version: 2.8.0 (2021-01-26)

**System Information:**

____Windows 10 Pro___________________________________________________________________________________

The issue is simple: I can't register my account because I never received the activation token in my e-mail. There is nothing I can do without the activation token.

**Comment by ebbit1q** [comment]
this github board is for bugs and feature requests, there are three public servers, please contact the support for the server you are registering to by email or discord etc.
