### ISSUE TITLE
Failing to build on arch

### ISSUE THREAD

**Issue by skwerlman** [Cockatrice/Cockatrice#4825]
**System Information:**
Archlinux
Qt 6.5.1
Protobuf 23.3
GCC 13.1.1

_______________________________________________________________________________________

When building on arch, the build fails.

CMake emits this warning:
```
CMake Warning at /usr/share/cmake/Modules/FindProtobuf.cmake:524 (message):
  Protobuf compiler version 23.3 doesn't match library version 4.23.3
Call Stack (most recent call first):
  CMakeLists.txt:219 (find_package)


-- Found Protobuf: /usr/lib/libprotobuf.so (found version "4.23.3") 
```

Then the build fails with this:
```
/usr/bin/ld: /usr/lib/libprotobuf.so: undefined reference to symbol '_ZN4absl12lts_2023012512log_internal17MakeCheckOpStringIllEEPNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEET_T0_PKc'
/usr/bin/ld: /usr/lib/libabsl_log_internal_check_op.so.2301.0.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

full build log: [gist](https://gist.github.com/skwerlman/f83f4b7625a72c1cb475353dba2587db)

edit: this also happens when building normally, so i have updated the issue

_______________________________________________________________________________________

**Steps to reproduce:**
 - git clone and cd in
 - mkdir build
 - cmake ..
 - make -j1

**Comment by ebbit1q** [comment]
this seems like an issue with your system, please `pacman -Syu` clear any ccache entries if used, and clear your build directory before building again

**Comment by skwerlman** [comment]
still failing after:
- `sudo pacman -Syu`
- `sudo pacman -S protobuf` (to reinstall protobuf in case anything was bad on disk)
- `rm -r ~/.cache/ccache/`
- `rm -r build/ && mkdir build`

same warnings/errors as before

**Comment by ebbit1q** [comment]
hmm, strange, could something be wrong with the arch repos?

**Comment by skwerlman** [comment]
i think it might be an issue with cmake and protobuf >= 23.3: https://github.com/protocolbuffers/protobuf/issues/12292

**Comment by skwerlman** [comment]
the warning will be fixed in cmake 3.27; currently trying to figure out whether the other issue is also fixed upstream yet

https://gitlab.kitware.com/cmake/cmake/-/issues/24847

**Comment by skwerlman** [comment]
this does not seem like it will be fixed upstream particularly fast, there's apparently a way to work around it by calling protobuf's own cmake module instead of the one shipped with cmake, though I am not good enough at cmake to make it work. I am unable to build cockatrice at all until this is fixed at either end.

https://github.com/protocolbuffers/protobuf/issues/12292#issuecomment-1529680040
https://gitlab.kitware.com/cmake/cmake/-/issues/24321

**Comment by ebbit1q** [comment]
I've looked into this and got tired, I've downgraded protobuf to v21 to keep it working

**Comment by skwerlman** [comment]
upgrading to cmake 3.27.5, the library version mismatch warning is now fixed, although the linking error remains

**Comment by rdrpenguin04** [comment]
Got it to work with `cmake -GNinja -DCMAKE_FIND_PACKAGE_PREFER_CONFIG=Yes -Dprotobuf_MODULE_COMPATIBLE=ON ..`

This can be fixed in the Cockatrice `CMakeLists.txt` with a couple of changes:
* Include "CONFIG" in the `find_package` line: `find_package(Protobuf CONFIG)`
* Before the `find_package` line, include `set(protobuf_MODULE_COMPATIBLE ON CACHE BOOL "")`. This avoids needing to change the existing code.

**Comment by rdrpenguin04** [comment]
Scratch that, still isn't fixed :(

**Comment by skwerlman** [comment]
> Got it to work with `cmake -GNinja -DCMAKE_FIND_PACKAGE_PREFER_CONFIG=Yes -Dprotobuf_MODULE_COMPATIBLE=ON ..`

This also worked for me, but only in conjunction with #4879
