### ISSUE TITLE
Drawing from the bottom of the deck reveals card

### ISSUE THREAD

**Issue by SlightlyCircuitous** [Cockatrice/Cockatrice#4834]
Client Version: 2.8.1-beta.14 (2023-04-30)
Client Operating System: Ubuntu 23.04
Build Architecture: 64-bit
Qt Version: 6.4.2
Adding room: ID= 0 name= ""
Server::loginUser: LocalServerInterface(0x55e44099d9d0) name= "Player 1"
session id: 0
gameEvent: invalid gameId
Server_AbstractUserInterface::playerAddedToGame(): gameId = 1
GameScene::addPlayer name= "Player 1"
PictureLoader: cache fail for "_trice_card_back_252100"
PictureLoader: cache fail for "_trice_card_back_278267"
PictureLoader: cache fail for "_trice_card_back_278265"
Loaded from "/home/USER/.local/share/Cockatrice/Cockatrice/decks/Exploding Goblins.cod" - true
Deck was loaded - true
PictureLoader: [card: "Goblin Fireslinger" set: "MB1"]: Requested "set"property ("muid") for Url template ("https://api.scryfall.com/cards/multiverse/!set:muid!?format=image") is not available
PictureLoader: [card: "Goblin Fireslinger" set: "MB1"]: Requested "set"property ("muid") for Url template ("https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card") is not available
PictureLoader: [card: "Goblin Chieftain" set: "PLIST"]: Requested "set"property ("muid") for Url template ("https://api.scryfall.com/cards/multiverse/!set:muid!?format=image") is not available
PictureLoader: [card: "Goblin Chieftain" set: "PLIST"]: Requested "set"property ("muid") for Url template ("https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card") is not available
PictureLoader: [card: "Lightning Bolt" set: "30A"]: Requested "set"property ("muid") for Url template ("https://api.scryfall.com/cards/multiverse/!set:muid!?format=image") is not available
PictureLoader: [card: "Lightning Bolt" set: "30A"]: Requested "set"property ("muid") for Url template ("https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card") is not available
PictureLoader: [card: "Goblin War Paint" set: "MB1"]: Requested "set"property ("muid") for Url template ("https://api.scryfall.com/cards/multiverse/!set:muid!?format=image") is not available
PictureLoader: [card: "Goblin War Paint" set: "MB1"]: Requested "set"property ("muid") for Url template ("https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card") is not available
PictureLoader: [card: "Curse of Bloodletting" set: "DKA"]: Trying to load picture
PictureLoader: [card: "Curse of Bloodletting" set: "DKA"]: No custom picture, trying to download
PictureLoader: [card: "Curse of Bloodletting" set: "DKA"]: Trying to fetch picture from url "https://api.scryfall.com/cards/9dc4ac6f-0005-47f8-bee9-10429cc542e4?format=image&face=front"
PictureLoader: [card: "Hissing Iguanar" set: "2X2"]: Trying to load picture
PictureLoader: [card: "Hissing Iguanar" set: "2X2"]: No custom picture, trying to download
PictureLoader: [card: "Goblin Fireslinger" set: "MB1"]: Trying to load picture
PictureLoader: [card: "Goblin Fireslinger" set: "MB1"]: No custom picture, trying to download
PictureLoader: [card: "Mountain" set: "SNID"]: Trying to load picture
PictureLoader: [card: "Mountain" set: "SNID"]: No custom picture, trying to download
PictureLoader: [card: "Goblin Grenade" set: "J22"]: Trying to load picture
PictureLoader: [card: "Goblin Grenade" set: "J22"]: No custom picture, trying to download
PictureLoader: [card: "Goblin Chieftain" set: "PLIST"]: Trying to load picture
PictureLoader: [card: "Goblin Chieftain" set: "PLIST"]: No custom picture, trying to download
PictureLoader: [card: "Reckless One" set: "EVG"]: Trying to load picture
PictureLoader: [card: "Reckless One" set: "EVG"]: No custom picture, trying to download
PictureLoader: [card: "Blisterstick Shaman" set: "J21"]: Trying to load picture
PictureLoader: [card: "Blisterstick Shaman" set: "J21"]: No custom picture, trying to download
PictureLoader: [card: "Lightning Bolt" set: "30A"]: Trying to load picture
PictureLoader: [card: "Lightning Bolt" set: "30A"]: No custom picture, trying to download
PictureLoader: [card: "Goblin Freerunner" set: "OGW"]: Trying to load picture
PictureLoader: [card: "Goblin Freerunner" set: "OGW"]: No custom picture, trying to download
PictureLoader: [card: "Mudbutton Torchrunner" set: "J22"]: Trying to load picture
PictureLoader: [card: "Mudbutton Torchrunner" set: "J22"]: No custom picture, trying to download
PictureLoader: [card: "Boros Recruit" set: "RAV"]: Trying to load picture
PictureLoader: [card: "Boros Recruit" set: "RAV"]: No custom picture, trying to download
PictureLoader: [card: "Siege-Gang Commander" set: "LTC"]: Trying to load picture
PictureLoader: [card: "Siege-Gang Commander" set: "LTC"]: No custom picture, trying to download
PictureLoader: [card: "Raging Goblin" set: "ANB"]: Trying to load picture
PictureLoader: [card: "Raging Goblin" set: "ANB"]: No custom picture, trying to download
PictureLoader: [card: "Krenko, Mob Boss" set: "CMM"]: Trying to load picture
PictureLoader: [card: "Krenko, Mob Boss" set: "CMM"]: No custom picture, trying to download
PictureLoader: [card: "Raid Bombardment" set: "ANB"]: Trying to load picture
PictureLoader: [card: "Raid Bombardment" set: "ANB"]: No custom picture, trying to download
PictureLoader: [card: "Akki Rockspeaker" set: "CHK"]: Trying to load picture
PictureLoader: [card: "Akki Rockspeaker" set: "CHK"]: No custom picture, trying to download
PictureLoader: [card: "Goblin Arsonist" set: "M21"]: Trying to load picture
PictureLoader: [card: "Goblin Arsonist" set: "M21"]: No custom picture, trying to download
PictureLoader: [card: "Goblin Wardriver" set: "DDT"]: Trying to load picture
PictureLoader: [card: "Goblin Wardriver" set: "DDT"]: No custom picture, trying to download
PictureLoader: [card: "Goblin War Paint" set: "MB1"]: Trying to load picture
PictureLoader: [card: "Goblin War Paint" set: "MB1"]: No custom picture, trying to download
PictureLoader: [card: "Furnace Scamp" set: "NPH"]: Trying to load picture
PictureLoader: [card: "Furnace Scamp" set: "NPH"]: No custom picture, trying to download
PictureLoader: [card: "Curse of Bloodletting" set: "DKA"]: following redirect to "https://cards.scryfall.io/large/front/9/d/9dc4ac6f-0005-47f8-bee9-10429cc542e4.jpg?1562932270"
PictureLoader: [card: "Curse of Bloodletting" set: "DKA"]: Image successfully downloaded from url "https://cards.scryfall.io/large/front/9/d/9dc4ac6f-0005-47f8-bee9-10429cc542e4.jpg?1562932270"
PictureLoader: [card: "Hissing Iguanar" set: "2X2"]: Trying to fetch picture from url "https://api.scryfall.com/cards/2268cf4b-de6d-4447-86e8-f8298728a3bd?format=image&face=front"
PictureLoader: [card: "Hissing Iguanar" set: "2X2"]: following redirect to "https://cards.scryfall.io/large/front/2/2/2268cf4b-de6d-4447-86e8-f8298728a3bd.jpg?1673147821"
PictureLoader: [card: "Hissing Iguanar" set: "2X2"]: Image successfully downloaded from url "https://cards.scryfall.io/large/front/2/2/2268cf4b-de6d-4447-86e8-f8298728a3bd.jpg?1673147821"
PictureLoader: [card: "Goblin Fireslinger" set: "MB1"]: Trying to fetch picture from url "https://api.scryfall.com/cards/1c0ebffc-7350-4f04-b13c-20c41563e57e?format=image&face=front"
PictureLoader: [card: "Goblin Fireslinger" set: "MB1"]: following redirect to "https://cards.scryfall.io/large/front/1/c/1c0ebffc-7350-4f04-b13c-20c41563e57e.jpg?1573511819"
PictureLoader: [card: "Goblin Fireslinger" set: "MB1"]: Image successfully downloaded from url "https://cards.scryfall.io/large/front/1/c/1c0ebffc-7350-4f04-b13c-20c41563e57e.jpg?1573511819"
PictureLoader: [card: "Mountain" set: "SNID"]: Trying to fetch picture from url "https://api.scryfall.com/cards/dd8611ec-6db3-4d29-8d3b-01e87bb38a55?format=image&face=front"
PictureLoader: [card: "Mountain" set: "SNID"]: following cached redirect to "https://cards.scryfall.io/large/front/d/d/dd8611ec-6db3-4d29-8d3b-01e87bb38a55.jpg?1648839729"
PictureLoader: [card: "Mountain" set: "SNID"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/d/d/dd8611ec-6db3-4d29-8d3b-01e87bb38a55.jpg?1648839729"
PictureLoader: [card: "Goblin Grenade" set: "J22"]: Trying to fetch picture from url "https://api.scryfall.com/cards/c5dacb5a-68d7-4eb0-b3ba-b1b96a100d3c?format=image&face=front"
PictureLoader: [card: "Goblin Grenade" set: "J22"]: following redirect to "https://cards.scryfall.io/large/front/c/5/c5dacb5a-68d7-4eb0-b3ba-b1b96a100d3c.jpg?1675650480"
PictureLoader: [card: "Goblin Grenade" set: "J22"]: Image successfully downloaded from url "https://cards.scryfall.io/large/front/c/5/c5dacb5a-68d7-4eb0-b3ba-b1b96a100d3c.jpg?1675650480"
PictureLoader: [card: "Goblin Chieftain" set: "PLIST"]: Trying to fetch picture from url "https://api.scryfall.com/cards/35ac943e-8747-40a0-ac2a-8b88cfa32ca8?format=image&face=front"
PictureLoader: [card: "Goblin Chieftain" set: "PLIST"]: following redirect to "https://cards.scryfall.io/large/front/3/5/35ac943e-8747-40a0-ac2a-8b88cfa32ca8.jpg?1599764783"
PictureLoader: [card: "Goblin Chieftain" set: "PLIST"]: Image successfully downloaded from url "https://cards.scryfall.io/large/front/3/5/35ac943e-8747-40a0-ac2a-8b88cfa32ca8.jpg?1599764783"
PictureLoader: [card: "Reckless One" set: "EVG"]: Trying to fetch picture from url "https://api.scryfall.com/cards/e1d31dd2-7b09-487a-b869-eb10dfcc6dcc?format=image&face=front"
PictureLoader: [card: "Reckless One" set: "EVG"]: following redirect to "https://cards.scryfall.io/large/front/e/1/e1d31dd2-7b09-487a-b869-eb10dfcc6dcc.jpg?1562940360"
PictureLoader: [card: "Reckless One" set: "EVG"]: Image successfully downloaded from url "https://cards.scryfall.io/large/front/e/1/e1d31dd2-7b09-487a-b869-eb10dfcc6dcc.jpg?1562940360"
PictureLoader: [card: "Blisterstick Shaman" set: "J21"]: Trying to fetch picture from url "https://api.scryfall.com/cards/40fc422b-53f3-4072-a5f9-60641ffc4410?format=image&face=front"
PictureLoader: [card: "Blisterstick Shaman" set: "J21"]: following redirect to "https://cards.scryfall.io/large/front/4/0/40fc422b-53f3-4072-a5f9-60641ffc4410.jpg?1630248672"
PictureLoader: [card: "Blisterstick Shaman" set: "J21"]: Image successfully downloaded from url "https://cards.scryfall.io/large/front/4/0/40fc422b-53f3-4072-a5f9-60641ffc4410.jpg?1630248672"
PictureLoader: [card: "Lightning Bolt" set: "30A"]: Trying to fetch picture from url "https://api.scryfall.com/cards/54be73dd-cb3b-411b-8f48-d12ca5183dee?format=image&face=front"
PictureLoader: [card: "Lightning Bolt" set: "30A"]: following redirect to "https://cards.scryfall.io/large/front/5/4/54be73dd-cb3b-411b-8f48-d12ca5183dee.jpg?1664925661"
PictureLoader: [card: "Lightning Bolt" set: "30A"]: Image successfully downloaded from url "https://cards.scryfall.io/large/front/5/4/54be73dd-cb3b-411b-8f48-d12ca5183dee.jpg?1664925661"
PictureLoader: [card: "Goblin Freerunner" set: "OGW"]: Trying to fetch picture from url "https://api.scryfall.com/cards/5082e0a1-5c3e-4b8c-ba88-290151564133?format=image&face=front"
PictureLoader: [card: "Goblin Freerunner" set: "OGW"]: following redirect to "https://cards.scryfall.io/large/front/5/0/5082e0a1-5c3e-4b8c-ba88-290151564133.jpg?1562911327"
PictureLoader: [card: "Goblin Freerunner" set: "OGW"]: Image successfully downloaded from url "https://cards.scryfall.io/large/front/5/0/5082e0a1-5c3e-4b8c-ba88-290151564133.jpg?1562911327"
PictureLoader: [card: "Mudbutton Torchrunner" set: "J22"]: Trying to fetch picture from url "https://api.scryfall.com/cards/d696b42b-02c7-4389-bc37-15fa1fa4f01b?format=image&face=front"
PictureLoader: [card: "Mudbutton Torchrunner" set: "J22"]: following redirect to "https://cards.scryfall.io/large/front/d/6/d696b42b-02c7-4389-bc37-15fa1fa4f01b.jpg?1675650761"
PictureLoader: [card: "Mudbutton Torchrunner" set: "J22"]: Image successfully downloaded from url "https://cards.scryfall.io/large/front/d/6/d696b42b-02c7-4389-bc37-15fa1fa4f01b.jpg?1675650761"
PictureLoader: [card: "Boros Recruit" set: "RAV"]: Trying to fetch picture from url "https://api.scryfall.com/cards/5af01330-05c2-4c5b-9830-2886711b2b5d?format=image&face=front"
PictureLoader: [card: "Boros Recruit" set: "RAV"]: following redirect to "https://cards.scryfall.io/large/front/5/a/5af01330-05c2-4c5b-9830-2886711b2b5d.jpg?1598917696"
PictureLoader: [card: "Boros Recruit" set: "RAV"]: Image successfully downloaded from url "https://cards.scryfall.io/large/front/5/a/5af01330-05c2-4c5b-9830-2886711b2b5d.jpg?1598917696"
PictureLoader: [card: "Siege-Gang Commander" set: "LTC"]: Trying to fetch picture from url "https://api.scryfall.com/cards/98b913e1-c26d-4a7d-9671-50d483304ba3?format=image&face=front"
PictureLoader: cache fail for "_trice_card_back_136193"
QPixmap::scaled: Pixmap is a null pixmap
PictureLoader: [card: "Siege-Gang Commander" set: "LTC"]: following redirect to "https://cards.scryfall.io/large/front/9/8/98b913e1-c26d-4a7d-9671-50d483304ba3.jpg?1686965885"
PictureLoader: [card: "Siege-Gang Commander" set: "LTC"]: Image successfully downloaded from url "https://cards.scryfall.io/large/front/9/8/98b913e1-c26d-4a7d-9671-50d483304ba3.jpg?1686965885"
PictureLoader: [card: "Raging Goblin" set: "ANB"]: Trying to fetch picture from url "https://api.scryfall.com/cards/c73ae1f0-60b6-4c4a-975b-13e659a33f50?format=image&face=front"
PictureLoader: [card: "Raging Goblin" set: "ANB"]: following redirect to "https://cards.scryfall.io/large/front/c/7/c73ae1f0-60b6-4c4a-975b-13e659a33f50.jpg?1597377254"
PictureLoader: [card: "Raging Goblin" set: "ANB"]: Image successfully downloaded from url "https://cards.scryfall.io/large/front/c/7/c73ae1f0-60b6-4c4a-975b-13e659a33f50.jpg?1597377254"
PictureLoader: [card: "Krenko, Mob Boss" set: "CMM"]: Trying to fetch picture from url "https://api.scryfall.com/cards/27141cae-3ca1-4a4f-933f-9608bbcf9bd9?format=image&face=front"
PictureLoader: [card: "Krenko, Mob Boss" set: "CMM"]: following redirect to "https://cards.scryfall.io/large/front/2/7/27141cae-3ca1-4a4f-933f-9608bbcf9bd9.jpg?1689997996"
PictureLoader: [card: "Krenko, Mob Boss" set: "CMM"]: Image successfully downloaded from url "https://cards.scryfall.io/large/front/2/7/27141cae-3ca1-4a4f-933f-9608bbcf9bd9.jpg?1689997996"
PictureLoader: [card: "Raid Bombardment" set: "ANB"]: Trying to fetch picture from url "https://api.scryfall.com/cards/ce45801e-2fca-435c-833f-dd1b8f11f308?format=image&face=front"
PictureLoader: cache fail for "_trice_card_back_278130"
PictureLoader: [card: "Raid Bombardment" set: "ANB"]: following redirect to "https://cards.scryfall.io/large/front/c/e/ce45801e-2fca-435c-833f-dd1b8f11f308.jpg?1597377262"
PictureLoader: [card: "Raid Bombardment" set: "ANB"]: Image successfully downloaded from url "https://cards.scryfall.io/large/front/c/e/ce45801e-2fca-435c-833f-dd1b8f11f308.jpg?1597377262"
PictureLoader: [card: "Akki Rockspeaker" set: "CHK"]: Trying to fetch picture from url "https://api.scryfall.com/cards/9c8b6685-2c74-4026-aef0-73ca7bc43306?format=image&face=front"
PictureLoader: [card: "Akki Rockspeaker" set: "CHK"]: following redirect to "https://cards.scryfall.io/large/front/9/c/9c8b6685-2c74-4026-aef0-73ca7bc43306.jpg?1562762984"
PictureLoader: [card: "Akki Rockspeaker" set: "CHK"]: Image successfully downloaded from url "https://cards.scryfall.io/large/front/9/c/9c8b6685-2c74-4026-aef0-73ca7bc43306.jpg?1562762984"
PictureLoader: [card: "Goblin Arsonist" set: "M21"]: Trying to fetch picture from url "https://api.scryfall.com/cards/fa4bf664-3b92-4598-b905-2bc090958c8b?format=image&face=front"
PictureLoader: [card: "Goblin Arsonist" set: "M21"]: following redirect to "https://cards.scryfall.io/large/front/f/a/fa4bf664-3b92-4598-b905-2bc090958c8b.jpg?1594736650"
PictureLoader: [card: "Goblin Arsonist" set: "M21"]: Image successfully downloaded from url "https://cards.scryfall.io/large/front/f/a/fa4bf664-3b92-4598-b905-2bc090958c8b.jpg?1594736650"
PictureLoader: [card: "Goblin Wardriver" set: "DDT"]: Trying to fetch picture from url "https://api.scryfall.com/cards/6fb10750-4037-4630-82d3-bb068c335e48?format=image&face=front"
PictureLoader: [card: "Goblin Wardriver" set: "DDT"]: following redirect to "https://cards.scryfall.io/large/front/6/f/6fb10750-4037-4630-82d3-bb068c335e48.jpg?1592764848"
PictureLoader: [card: "Goblin Wardriver" set: "DDT"]: Image successfully downloaded from url "https://cards.scryfall.io/large/front/6/f/6fb10750-4037-4630-82d3-bb068c335e48.jpg?1592764848"
PictureLoader: [card: "Goblin War Paint" set: "MB1"]: Trying to fetch picture from url "https://api.scryfall.com/cards/adf99238-6d5d-4920-8d56-91d1edeb7759?format=image&face=front"
PictureLoader: [card: "Goblin War Paint" set: "MB1"]: following redirect to "https://cards.scryfall.io/large/front/a/d/adf99238-6d5d-4920-8d56-91d1edeb7759.jpg?1573511882"
PictureLoader: [card: "Goblin War Paint" set: "MB1"]: Image successfully downloaded from url "https://cards.scryfall.io/large/front/a/d/adf99238-6d5d-4920-8d56-91d1edeb7759.jpg?1573511882"
PictureLoader: [card: "Furnace Scamp" set: "NPH"]: Trying to fetch picture from url "https://api.scryfall.com/cards/97538294-058c-47d4-b7a8-4db3753a6628?format=image&face=front"
PictureLoader: [card: "Furnace Scamp" set: "NPH"]: following redirect to "https://cards.scryfall.io/large/front/9/7/97538294-058c-47d4-b7a8-4db3753a6628.jpg?1562879991"
PictureLoader: [card: "Furnace Scamp" set: "NPH"]: Image successfully downloaded from url "https://cards.scryfall.io/large/front/9/7/97538294-058c-47d4-b7a8-4db3753a6628.jpg?1562879991"
PictureLoader: cache fail for "_trice_card_back_278153"
PictureLoader: cache fail for "_trice_card_back_278269"
_______________________________________________________________________________________

When drawing cards from the bottom of the library using  `Bottom of library... > Draw bottom card`, the name of the card is revealed in the chat log message:

![Screenshot from 2023-08-05 12-04-25](https://github.com/Cockatrice/Cockatrice/assets/71394296/613d02d1-4777-4814-989b-52f8613cd88b)

This also occurs when drawing multiple cards using `Bottom of library... > Draw bottom cards...`: 

![Screenshot from 2023-08-05 12-04-57](https://github.com/Cockatrice/Cockatrice/assets/71394296/38ec82bf-4fd8-45fa-baf0-d0d67bf60087)
The last three cards in this screenshot where all drawn using the `Draw bottom cards...` option, putting in '3' in the dialogue box. For whatever reason, 'Lightning Bolt' does not say that its from the bottom of the library.

This does not occur when playing the bottom card face down or moving the bottom card to the top of the library:

![Screenshot from 2023-08-05 12-04-40](https://github.com/Cockatrice/Cockatrice/assets/71394296/1da3c38b-18aa-4d3d-88b7-dd2121aa3afc)

_______________________________________________________________________________________

**Steps to reproduce:**
 - Start Local Game
 - Use the deck context menu `Bottom of library... > Draw bottom card` or `Bottom of library... > Draw bottom cards...` to draw one or more cards.
 - Check chat log for name of card(s) drawn

**Comment by SlightlyCircuitous** [comment]
Looking into this further, I think this might be a bug involving the logic of MessageLogWidget::logMoveCard. In [lines 307-313](https://github.com/Cockatrice/Cockatrice/blob/5b694a55d276ed376b76b87602da97b2937acf5d/cockatrice/src/messagelogwidget.cpp#L307C1-L313C6), the if statement fires when playing the bottom card face down or moving the bottom card to the top of the library, but the else statement fires on drawing one or more cards from the bottom of the library, naming the card instead of using the generic "the bottom card" statement. I would have expected the if statement ("player 1 puts the bottom card from their library into their hand") or maybe the if else statement ("player 1 moves a card from the bottom of their library into their hand") to fire instead. I am not exactly what is going wrong, but I thought I would note this as I keep looking.

**Comment by ebbit1q** [comment]
this is not a bug, this information is not shared with your opponent 
![image](https://github.com/Cockatrice/Cockatrice/assets/36401181/4c642403-5864-4b51-8012-c8d2cc031b94)

**Comment by SlightlyCircuitous** [comment]
oh, wow. that's what I get for testing it in local games only, I guess.
