### ISSUE TITLE
Add card search to the in-game view library window

### ISSUE THREAD

**Issue by gabahulk** [Cockatrice/Cockatrice#4835]
**Similar Requests**
[#4661](https://github.com/Cockatrice/Cockatrice/issues/4661)

**Description of New Feature**
Add a search input field to the in-game view library window to filter a specific card (and maybe eventually search for card types, power/toughness, creature types, etc).

**Additional Context**
Sometimes it might be hard for users to find the specific card they are looking for while searching their library. Magic Online highlights all possible cards that you can get with the search, but a search filter could be more potent than that.

**Comment by tooomm** [comment]
I think you want to follow this old issue: https://github.com/Cockatrice/Cockatrice/issues/2993

Closing as dupe.
