### ISSUE TITLE
Automated game start actions. Set Life, Commander, dice,...

### ISSUE THREAD

**Issue by danyfire** [Cockatrice/Cockatrice#4858]
Hello, 

The feature idea would be some kind of customable start game setup actions, with profils maybe depending of game format.
The goal is to automatically set at the beginning of the game actions.

For exemple if you join a multi player commander game you can click a action bouton that will :

- Set your Life to 40
- Put Commander(s) in command zone
- Roll Dice 20 and create a token with result
- Draw first Hand

For a modern profile 
- Set Life to 20
- Roll Dice 20 and create a token with result
- Draw first Hand

Et cetera.
There could be default templates for known formats and customable ones.

What do you dev think about this feature idea?

Sincerely,
Danyfire

**Comment by ebbit1q** [comment]
this is covered by https://github.com/Cockatrice/Cockatrice/issues/1740 I'll be closing it as a duplicate, please continue discussion on that ticket instead.
