### ISSUE TITLE
Simple: Typo for Hylda's Crown of Winter (WOE)

### ISSUE THREAD

**Issue by Linearwolf** [Cockatrice/Cockatrice#4868]
**System Information:**

_______________________________________________________________________________________

Card in search engine is listed as "Hyldra's ------" rather than "Hylda's"

:)

_______________________________________________________________________________________

**Steps to reproduce:**
 - Do A
 - Do B
 - Do C ...

**Comment by ebbit1q** [comment]
![image](https://github.com/Cockatrice/Cockatrice/assets/36401181/fb4fee36-8979-4511-bcf2-ddc6e6cf4632)
can't reproduce, please run the card updater "oracle" at help>check for card updates, you should update your cards with some regularity in order to have the most current cards.

**Comment by tooomm** [comment]
Also showing correct for me. 👍 

Please reopen the issue and provide more details if it still doesn't work after the card database update via Oracle.
