### ISSUE TITLE
Make cards on the stack slightly overlap to stress order

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#4872]
**Description of New Feature**
Cards on the stack are shown next to each other. There is no way to know if the cards more on the top are the more recent ones or the other way around when just looking at it.

It would help to just slightly overlap the cards to clearly visualize their order.
Any potential information that might be covered up can easily be reviewed with moues over or middle click.

**Comment by ebbit1q** [comment]
there isn't a clear order, when you drag a card to the stack it will always be placed at the top (this is index 0) yet if you use play top card it will place it at the bottom (appends to list, will show as overlapping if enough cards are on the stack)

**Comment by tooomm** [comment]
I was not aware, hmm. Played a bit around and yes, it's exactly as you describe it.
Is there a reason why we do not care for an order on the stack?

You are right, overlapping is shown once the stack tget's crowded:
<img width="118" alt="image" src="https://github.com/Cockatrice/Cockatrice/assets/9874850/e2d5e875-fc8e-4e90-a2c7-b95bc8df30f8">
