### ISSUE TITLE
Unable to update to new version (2.8.0 to 2.8.1)

### ISSUE THREAD

**Issue by CharaIndompt** [Cockatrice/Cockatrice#4874]
**System Information:**
Client Version: 2.8.0 (2021-01-26)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.12.9

_______________________________________________________________________________________

I can't seemingly update to version 2.8.1 or 2.9.0 (both are referred to in the GitHub page, I don't know which one it should be...).

As I click on Help => Check for Client updates, it just throws me an error saying that no packaging is available at the moment for my operating system and that I should compile the sources myself.

_______________________________________________________________________________________

**Steps to reproduce:**
 - Do A
 - Do B
 - Do C ...
 
 - Use Windows 10
 - Use Cockatrice 2.8.0
 - Click on Help => Check for Client Update

**Comment by ebbit1q** [comment]
could you try again? the new update is 2.9.0

**Comment by CharaIndompt** [comment]
![1694859321416733856288849974137](https://github.com/Cockatrice/Cockatrice/assets/111198093/c5121e37-a968-482e-82dd-7a3bab5a138e)

I apparently still am unable to update... same error

**Comment by ebbit1q** [comment]
you can find our downloads here https://github.com/Cockatrice/Cockatrice/releases

**Comment by CharaIndompt** [comment]
Will it keep all my decks and personal settings?

**Comment by madmox** [comment]
Same issue here on Windows 11. Downloading from the release page worked, but the client auto-update from the menu throws the same error ("no download package available for your operating system")..

**Comment by ZeldaZach** [comment]
> Will it keep all my decks and personal settings?

Yes, all settings are retained by default



> Same issue here on Windows 11. Downloading from the release page worked, but the client auto-update from the menu throws the same error ("no download package available for your operating system")..

There seems to be an issue from the updater, so you might have to manually go and download it

**Comment by tooomm** [comment]
Here is the link to always find our newest version:
https://github.com/Cockatrice/Cockatrice/releases/latest

Please feel free to reopen this and provide more information, if you're still having trouble!
