### ISSUE TITLE
Transforming DFC's still attaching

### ISSUE THREAD

**Issue by triggrhappy0** [Cockatrice/Cockatrice#4875]
**System Information:**
Client Version: 2.9.0 (2023-09-14)
[CockatriceXml3Parser] Unknown card property "maintype" , trying to continue anyway
[CockatriceXml3Parser] Unknown card property "maintype" , trying to continue anyway
[CockatriceXml3Parser] Unknown card property "maintype" , trying to continue anyway
[CockatriceXml3Parser] Unknown card property "maintype" , trying to continue anyway
[CockatriceXml3Parser] Unknown card property "maintype" , trying to continue anyway
[CockatriceXml3Parser] Unknown card property "maintype" , trying to continue anyway
[CockatriceXml3Parser] Unknown card property "maintype" , trying to continue anyway
[CockatriceXml3Parser] Unknown card property "maintype" , trying to continue anyway
[CockatriceXml3Parser] Unknown card property "maintype" , trying to continue anyway
[CockatriceXml3Parser] Unknown card property "maintype" , trying to continue anyway
[CockatriceXml3Parser] Unknown card property "maintype" , trying to continue anyway
[CockatriceXml3Parser] Unknown card property "maintype" , trying to continue anyway
[CockatriceXml3Parser] Unknown card property "maintype" , trying to continue anyway
[CockatriceXml3Parser] Unknown card property "maintype" , trying to continue anyway
[CockatriceXml3Parser] Unknown card property "maintype" , trying to continue anyway
[CockatriceXml3Parser] Unknown card property "maintype" , trying to continue anyway
[CockatriceXml3Parser] Unknown card property "maintype" , trying to continue anyway
[CockatriceXml3Parser] Unknown card property "maintype" , trying to continue anyway
[CockatriceXml3Parser] Unknown card property "side" , trying to continue anyway
[CockatriceXml3Parser] Unknown card property "side" , trying to continue anyway
[CockatriceXml3Parser] Unknown card property "side" , trying to continue anyway
[CockatriceXml3Parser] Unknown card property "side" , trying to continue anyway
[CockatriceXml3Parser] Unknown card property "side" , trying to continue anyway
[CockatriceXml3Parser] Unknown card property "side" , trying to continue anyway
[CockatriceXml3Parser] Unknown card property "side" , trying to continue anyway
[CockatriceXml3Parser] Unknown card property "side" , trying to continue anyway
[CockatriceXml3Parser] Unknown card property "side" , trying to continue anyway
[CockatriceXml3Parser] Unknown card property "side" , trying to continue anyway
[CockatriceXml3Parser] Unknown card property "side" , trying to continue anyway
[CockatriceXml3Parser] Unknown card property "side" , trying to continue anyway
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Kevin/AppData/Local/Cockatrice/Cockatrice/customsets/03.pjto_cockatrice.xml" Status = 0 Cards = 29253 Sets = 720 "11ms"
Loading Custom Set 2 ( "C:/Users/Kevin/AppData/Local/Cockatrice/Cockatrice/customsets/TK.xml" )
[CockatriceXml4Parser] Trying to parse:  "C:/Users/Kevin/AppData/Local/Cockatrice/Cockatrice/customsets/TK.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Kevin/AppData/Local/Cockatrice/Cockatrice/customsets/TK.xml" Status = 0 Cards = 29253 Sets = 720 "0ms"
CardDatabase::loadCardDatabases success
gameEvent: invalid gameId
GameScene::addPlayer name= "triggrhappy0"
PictureLoader: cache fail for "_trice_card_back_274170"
QWindowsWindow::setGeometry: Unable to set geometry 1280x664+0+23 (frame: 1296x703-8-8) on QWidgetWindow/"MainWindowClassWindow" on "\\.\DISPLAY1". Resulting geometry: 1280x657+0+23 (frame: 1296x696-8-8) margins: 8, 31, 8, 8 minimum size: 674x664 MINMAXINFO(maxSize=POINT(x=0, y=0), maxpos=POINT(x=0, y=0), maxtrack=POINT(x=0, y=0), mintrack=POINT(x=690, y=703)))
PictureLoader: cache fail for "_trice_card_back_265284"
PictureLoader: cache fail for "_trice_card_back_265282"
Loaded from "C:/Users/Kevin/AppData/Local/Cockatrice/Cockatrice/decks/rakdos mid.cod" - true
Deck was loaded - true
PictureLoader: [card: "Mountain" set: "PKTO"]: Requested "set"property ("uuid") for Url template ("https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!") is not available
PictureLoader: [card: "Mountain" set: "PKTO"]: Requested "set"property ("muid") for Url template ("https://api.scryfall.com/cards/multiverse/!set:muid!?format=image") is not available
PictureLoader: [card: "Mountain" set: "PKTO"]: Requested "set"property ("muid") for Url template ("https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card") is not available
PictureLoader: [card: "Swamp" set: "PKTO"]: Requested "set"property ("uuid") for Url template ("https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!") is not available
PictureLoader: [card: "Swamp" set: "PKTO"]: Requested "set"property ("muid") for Url template ("https://api.scryfall.com/cards/multiverse/!set:muid!?format=image") is not available
PictureLoader: [card: "Swamp" set: "PKTO"]: Requested "set"property ("muid") for Url template ("https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card") is not available
PictureLoader: [card: "Power Word Kill" set: "AFR"]: Trying to load picture
PictureLoader: [card: "Power Word Kill" set: "AFR"]: Picture found on disk.
PictureLoader: [card: "Unlicensed Hearse" set: "SNC"]: Trying to load picture
PictureLoader: [card: "Unlicensed Hearse" set: "SNC"]: Picture found on disk.
PictureLoader: [card: "Blood Crypt" set: "RNA"]: Trying to load picture
PictureLoader: [card: "Blood Crypt" set: "RNA"]: Picture found on disk.
PictureLoader: [card: "Go for the Throat" set: "BRO"]: Trying to load picture
PictureLoader: [card: "Go for the Throat" set: "BRO"]: Picture found on disk.
PictureLoader: [card: "Fatal Push" set: "2XM"]: Trying to load picture
PictureLoader: [card: "Fatal Push" set: "2XM"]: Picture found on disk.
PictureLoader: [card: "Sokenzan, Crucible of Defiance" set: "NEO"]: Trying to load picture
PictureLoader: [card: "Sokenzan, Crucible of Defiance" set: "NEO"]: Picture found on disk.
PictureLoader: [card: "Mountain" set: "PKTO"]: Trying to load picture
PictureLoader: [card: "Mountain" set: "PKTO"]: Picture found on disk.
PictureLoader: [card: "Haunted Ridge" set: "MID"]: Trying to load picture
PictureLoader: [card: "Haunted Ridge" set: "MID"]: Picture found on disk.
PictureLoader: [card: "Kolaghan's Command" set: "2X2"]: Trying to load picture
PictureLoader: [card: "Kolaghan's Command" set: "2X2"]: Picture found on disk.
PictureLoader: [card: "Castle Locthwain" set: "ELD"]: Trying to load picture
PictureLoader: [card: "Castle Locthwain" set: "ELD"]: Picture found on disk.
PictureLoader: [card: "Hive of the Eye Tyrant" set: "AFR"]: Trying to load picture
PictureLoader: [card: "Hive of the Eye Tyrant" set: "AFR"]: Picture found on disk.
PictureLoader: [card: "Graveyard Trespasser" set: "MID"]: Trying to load picture
PictureLoader: [card: "Graveyard Trespasser" set: "MID"]: Picture found on disk.
PictureLoader: [card: "Blackcleave Cliffs" set: "ONE"]: Trying to load picture
PictureLoader: [card: "Blackcleave Cliffs" set: "ONE"]: Picture found on disk.
PictureLoader: [card: "Bloodtithe Harvester" set: "VOW"]: Trying to load picture
PictureLoader: [card: "Bloodtithe Harvester" set: "VOW"]: Picture found on disk.
PictureLoader: [card: "Sheoldred, the Apocalypse" set: "DMU"]: Trying to load picture
PictureLoader: [card: "Sheoldred, the Apocalypse" set: "DMU"]: Picture found on disk.
PictureLoader: [card: "Misery's Shadow" set: "BRO"]: Trying to load picture
PictureLoader: [card: "Misery's Shadow" set: "BRO"]: Picture found on disk.
PictureLoader: [card: "Rending Volley" set: "DTK"]: Trying to load picture
PictureLoader: [card: "Rending Volley" set: "DTK"]: Picture found on disk.
PictureLoader: [card: "Dreadbore" set: "RTR"]: Trying to load picture
PictureLoader: [card: "Dreadbore" set: "RTR"]: Picture found on disk.
PictureLoader: [card: "Pithing Needle" set: "2X2"]: Trying to load picture
PictureLoader: [card: "Pithing Needle" set: "2X2"]: Picture found on disk.
PictureLoader: [card: "Thoughtseize" set: "THS"]: Trying to load picture
PictureLoader: [card: "Thoughtseize" set: "THS"]: Picture found on disk.
PictureLoader: [card: "Takenuma, Abandoned Mire" set: "NEO"]: Trying to load picture
PictureLoader: [card: "Takenuma, Abandoned Mire" set: "NEO"]: Picture found on disk.
PictureLoader: [card: "Swamp" set: "PKTO"]: Trying to load picture
PictureLoader: [card: "Swamp" set: "PKTO"]: Picture found on disk.
PictureLoader: [card: "Fable of the Mirror-Breaker" set: "NEO"]: Trying to load picture
PictureLoader: [card: "Fable of the Mirror-Breaker" set: "NEO"]: Picture found on disk.
PictureLoader: [card: "Den of the Bugbear" set: "AFR"]: Trying to load picture
PictureLoader: [card: "Den of the Bugbear" set: "AFR"]: Picture found on disk.
PictureLoader: [card: "Hidetsugu Consumes All" set: "NEO"]: Trying to load picture
PictureLoader: [card: "Hidetsugu Consumes All" set: "NEO"]: Picture found on disk.
PictureLoader: [card: "Reckoner Bankbuster" set: "NEO"]: Trying to load picture
PictureLoader: [card: "Reckoner Bankbuster" set: "NEO"]: Picture found on disk.
PictureLoader: [card: "Blightstep Pathway" set: "KHM"]: Trying to load picture
PictureLoader: [card: "Blightstep Pathway" set: "KHM"]: Picture found on disk.
PictureLoader: [card: "Extinction Event" set: "IKO"]: Trying to load picture
PictureLoader: [card: "Extinction Event" set: "IKO"]: Picture found on disk.
PictureLoader: [card: "Duress" set: "M21"]: Trying to load picture
PictureLoader: [card: "Duress" set: "M21"]: Picture found on disk.
PictureLoader: [card: "Bonecrusher Giant // Stomp" set: "ELD"]: Trying to load picture
PictureLoader: [card: "Bonecrusher GiantStomp" set: "ELD"]: Picture found on disk.
PictureLoader: [card: "Noxious Grasp" set: "M20"]: Trying to load picture
PictureLoader: [card: "Noxious Grasp" set: "M20"]: Picture found on disk.
PictureLoader: [card: "Kroxa, Titan of Death's Hunger" set: "THB"]: Trying to load picture
PictureLoader: [card: "Kroxa, Titan of Death's Hunger" set: "THB"]: Picture found on disk.
PictureLoader: [card: "Abrade" set: "HOU"]: Trying to load picture
PictureLoader: [card: "Abrade" set: "HOU"]: Picture found on disk.
PictureLoader: [card: "Power Word Kill" set: "AFR"]: Trying to load picture
PictureLoader: [card: "Power Word Kill" set: "AFR"]: Picture found on disk.
PictureLoader: [card: "Unlicensed Hearse" set: "SNC"]: Trying to load picture
PictureLoader: [card: "Unlicensed Hearse" set: "SNC"]: Picture found on disk.
PictureLoader: cache fail for "_trice_card_back_84120"
QPixmap::scaled: Pixmap is a null pixmap
PictureLoader: cache fail for "_trice_card_back_242221"
PictureLoader: [card: "Delver of Secrets" set: "MID"]: Trying to load picture
PictureLoader: [card: "Delver of Secrets" set: "MID"]: Picture found on disk.
PictureLoader: [card: "Insectile Aberration" set: "MID"]: Trying to load picture
PictureLoader: [card: "Insectile Aberration" set: "MID"]: Picture found on disk.

_______________________________________________________________________________________

After updating to 2.9.0, I tested the transforming DFC function with Delver of Secrets, and it worked. I was able to see the backside of the card without the front side attached. That functionality no longer happens. Selecting Token: Transform now attaches Delver to Insectile Aberration as it did in previous versions of Cockatrice.

![image](https://github.com/Cockatrice/Cockatrice/assets/76265453/79a1e1bf-c1d7-4ee1-b30e-898f1cd4118f)

_______________________________________________________________________________________

**Steps to reproduce:**
 - Right click Delver of Secrets
 - Select Token: Transform into "3/2 Insectile Aberration"

**Comment by ebbit1q** [comment]
cannot reproduce, please run oracle to update your card database

**Comment by triggrhappy0** [comment]
Updating it didn't work, but deleting it and downloading it fresh did. Issue is resolved, but it's unclear what caused it in the first place, as the transform function was working and then stopped.

**Comment by triggrhappy0** [comment]
Updating it didn't work, but deleting it and downloading it fresh did. Issue is resolved, but it's unclear what caused it in the first place, as the transform function was working and then stopped.
