### ISSUE TITLE
Transforming DFC's not working in custom set

### ISSUE THREAD

**Issue by triggrhappy0** [Cockatrice/Cockatrice#4876]
**System Information:**

Client Version: 2.9.0 (2023-09-14)
[CockatriceXml3Parser] Unknown card property "maintype" , trying to continue anyway
[CockatriceXml3Parser] Unknown card property "maintype" , trying to continue anyway
[CockatriceXml3Parser] Unknown card property "maintype" , trying to continue anyway
[CockatriceXml3Parser] Unknown card property "maintype" , trying to continue anyway
[CockatriceXml3Parser] Unknown card property "maintype" , trying to continue anyway
[CockatriceXml3Parser] Unknown card property "maintype" , trying to continue anyway
[CockatriceXml3Parser] Unknown card property "maintype" , trying to continue anyway
[CockatriceXml3Parser] Unknown card property "maintype" , trying to continue anyway
[CockatriceXml3Parser] Unknown card property "maintype" , trying to continue anyway
[CockatriceXml3Parser] Unknown card property "maintype" , trying to continue anyway
[CockatriceXml3Parser] Unknown card property "maintype" , trying to continue anyway
[CockatriceXml3Parser] Unknown card property "maintype" , trying to continue anyway
[CockatriceXml3Parser] Unknown card property "side" , trying to continue anyway
[CockatriceXml3Parser] Unknown card property "side" , trying to continue anyway
[CockatriceXml3Parser] Unknown card property "side" , trying to continue anyway
[CockatriceXml3Parser] Unknown card property "side" , trying to continue anyway
[CockatriceXml3Parser] Unknown card property "side" , trying to continue anyway
[CockatriceXml3Parser] Unknown card property "side" , trying to continue anyway
[CockatriceXml3Parser] Unknown card property "side" , trying to continue anyway
[CockatriceXml3Parser] Unknown card property "side" , trying to continue anyway
[CockatriceXml3Parser] Unknown card property "side" , trying to continue anyway
[CockatriceXml3Parser] Unknown card property "side" , trying to continue anyway
[CockatriceXml3Parser] Unknown card property "side" , trying to continue anyway
[CockatriceXml3Parser] Unknown card property "side" , trying to continue anyway
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Kevin/AppData/Local/Cockatrice/Cockatrice/customsets/03.pjto_cockatrice.xml" Status = 0 Cards = 29253 Sets = 720 "20ms"
Loading Custom Set 2 ( "C:/Users/Kevin/AppData/Local/Cockatrice/Cockatrice/customsets/TK.xml" )
[CockatriceXml4Parser] Trying to parse:  "C:/Users/Kevin/AppData/Local/Cockatrice/Cockatrice/customsets/TK.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Kevin/AppData/Local/Cockatrice/Cockatrice/customsets/TK.xml" Status = 0 Cards = 29253 Sets = 720 "0ms"
CardDatabase::loadCardDatabases success
gameEvent: invalid gameId
GameScene::addPlayer name= "triggrhappy0"
PictureLoader: cache fail for "_trice_card_back_274170"
QWindowsWindow::setGeometry: Unable to set geometry 1280x667+0+23 (frame: 1296x706-8-8) on QWidgetWindow/"MainWindowClassWindow" on "\\.\DISPLAY1". Resulting geometry: 1280x657+0+23 (frame: 1296x696-8-8) margins: 8, 31, 8, 8 minimum size: 674x667 MINMAXINFO(maxSize=POINT(x=0, y=0), maxpos=POINT(x=0, y=0), maxtrack=POINT(x=0, y=0), mintrack=POINT(x=690, y=706)))
PictureLoader: cache fail for "_trice_card_back_265278"
PictureLoader: cache fail for "_trice_card_back_265276"
Loaded from "C:/Users/Kevin/AppData/Local/Cockatrice/Cockatrice/decks/murktide.cod" - true
Deck was loaded - true
PictureLoader: [card: "Counterspell" set: "PHED"]: Requested "set"property ("muid") for Url template ("https://api.scryfall.com/cards/multiverse/!set:muid!?format=image") is not available
PictureLoader: [card: "Counterspell" set: "PHED"]: Requested "set"property ("muid") for Url template ("https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card") is not available
PictureLoader: [card: "Murktide Regent" set: "MH2"]: Trying to load picture
PictureLoader: [card: "Murktide Regent" set: "MH2"]: Picture found on disk.
PictureLoader: [card: "Spirebluff Canal" set: "KLD"]: Trying to load picture
PictureLoader: [card: "Spirebluff Canal" set: "KLD"]: Picture found on disk.
PictureLoader: [card: "Ledger Shredder" set: "SNC"]: Trying to load picture
PictureLoader: [card: "Ledger Shredder" set: "SNC"]: Picture found on disk.
PictureLoader: [card: "Abrade" set: "HOU"]: Trying to load picture
PictureLoader: [card: "Abrade" set: "HOU"]: Picture found on disk.
PictureLoader: [card: "Otawara, Soaring City" set: "NEO"]: Trying to load picture
PictureLoader: [card: "Otawara, Soaring City" set: "NEO"]: Picture found on disk.
PictureLoader: [card: "Scalding Tarn" set: "MH2"]: Trying to load picture
PictureLoader: [card: "Scalding Tarn" set: "MH2"]: Picture found on disk.
PictureLoader: [card: "Dress Down" set: "MH2"]: Trying to load picture
PictureLoader: [card: "Dress Down" set: "MH2"]: Picture found on disk.
PictureLoader: [card: "Steam Vents" set: "GRN"]: Trying to load picture
PictureLoader: [card: "Steam Vents" set: "GRN"]: Picture found on disk.
PictureLoader: [card: "Unholy Heat" set: "MH2"]: Trying to load picture
PictureLoader: [card: "Unholy Heat" set: "MH2"]: Picture found on disk.
PictureLoader: [card: "Engineered Explosives" set: "2XM"]: Trying to load picture
PictureLoader: [card: "Engineered Explosives" set: "2XM"]: Picture found on disk.
PictureLoader: [card: "Spell Snare" set: "BBD"]: Trying to load picture
PictureLoader: [card: "Spell Snare" set: "BBD"]: Picture found on disk.
PictureLoader: [card: "Mystical Dispute" set: "ELD"]: Trying to load picture
PictureLoader: [card: "Mystical Dispute" set: "ELD"]: Picture found on disk.
PictureLoader: [card: "Mishra's Bauble" set: "2XM"]: Trying to load picture
PictureLoader: [card: "Mishra's Bauble" set: "2XM"]: Picture found on disk.
PictureLoader: [card: "Brazen Borrower // Petty Theft" set: "ELD"]: Trying to load picture
PictureLoader: [card: "Brazen BorrowerPetty Theft" set: "ELD"]: Picture found on disk.
PictureLoader: [card: "Ragavan, Nimble Pilferer" set: "MH2"]: Trying to load picture
PictureLoader: [card: "Ragavan, Nimble Pilferer" set: "MH2"]: Picture found on disk.
PictureLoader: [card: "Flusterstorm" set: "MH1"]: Trying to load picture
PictureLoader: [card: "Flusterstorm" set: "MH1"]: Picture found on disk.
PictureLoader: [card: "Spell Pierce" set: "NEO"]: Trying to load picture
PictureLoader: [card: "Spell Pierce" set: "NEO"]: Picture found on disk.
PictureLoader: [card: "Polluted Delta" set: "KTK"]: Trying to load picture
PictureLoader: [card: "Polluted Delta" set: "KTK"]: Picture found on disk.
PictureLoader: [card: "Flooded Strand" set: "KTK"]: Trying to load picture
PictureLoader: [card: "Flooded Strand" set: "KTK"]: Picture found on disk.
PictureLoader: [card: "Counterspell" set: "PHED"]: Trying to load picture
PictureLoader: [card: "Counterspell" set: "PHED"]: Picture found on disk.
PictureLoader: [card: "Fiery Islet" set: "MH1"]: Trying to load picture
PictureLoader: [card: "Fiery Islet" set: "MH1"]: Picture found on disk.
PictureLoader: [card: "Expressive Iteration" set: "STX"]: Trying to load picture
PictureLoader: [card: "Expressive Iteration" set: "STX"]: Picture found on disk.
PictureLoader: [card: "Fury" set: "MH2"]: Trying to load picture
PictureLoader: [card: "Fury" set: "MH2"]: Picture found on disk.
PictureLoader: [card: "Consider" set: "MID"]: Trying to load picture
PictureLoader: [card: "Consider" set: "MID"]: Picture found on disk.
PictureLoader: [card: "Unlicensed Hearse" set: "SNC"]: Trying to load picture
PictureLoader: [card: "Unlicensed Hearse" set: "SNC"]: Picture found on disk.
PictureLoader: [card: "Snow-Covered Island" set: "MH1"]: Trying to load picture
PictureLoader: [card: "Snow-Covered Island" set: "MH1"]: Picture found on disk.
PictureLoader: [card: "Subtlety" set: "MH2"]: Trying to load picture
PictureLoader: [card: "Subtlety" set: "MH2"]: Picture found on disk.
PictureLoader: [card: "Misty Rainforest" set: "MH2"]: Trying to load picture
PictureLoader: [card: "Misty Rainforest" set: "MH2"]: Picture found on disk.
PictureLoader: [card: "Dragon's Rage Channeler" set: "MH2"]: Trying to load picture
PictureLoader: [card: "Dragon's Rage Channeler" set: "MH2"]: Picture found on disk.
PictureLoader: [card: "Lightning Bolt" set: "2X2"]: Trying to load picture
PictureLoader: [card: "Lightning Bolt" set: "2X2"]: Picture found on disk.
PictureLoader: [card: "Blood Moon" set: "2XM"]: Trying to load picture
PictureLoader: [card: "Blood Moon" set: "2XM"]: Picture found on disk.
PictureLoader: [card: "Murktide Regent" set: "MH2"]: Trying to load picture
PictureLoader: [card: "Murktide Regent" set: "MH2"]: Picture found on disk.
PictureLoader: [card: "Spirebluff Canal" set: "KLD"]: Trying to load picture
PictureLoader: [card: "Spirebluff Canal" set: "KLD"]: Picture found on disk.
PictureLoader: cache fail for "_trice_card_back_85120"
QPixmap::scaled: Pixmap is a null pixmap
PictureLoader: cache fail for "_trice_card_back_242221"
PictureLoader: [card: "Delver of Secrets" set: "MID"]: Trying to load picture
PictureLoader: [card: "Delver of Secrets" set: "MID"]: Picture found on disk.
PictureLoader: [card: "Insectile Aberration" set: "MID"]: Trying to load picture
PictureLoader: [card: "Insectile Aberration" set: "MID"]: Picture found on disk.
PictureLoader: [card: "Bulbasaur" set: "PKTO"]: Requested "prop"property ("side") for Url template ("https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!") is not available
PictureLoader: [card: "Bulbasaur" set: "PKTO"]: Requested "set"property ("muid") for Url template ("https://api.scryfall.com/cards/multiverse/!set:muid!?format=image") is not available
PictureLoader: [card: "Bulbasaur" set: "PKTO"]: Requested "set"property ("muid") for Url template ("https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card") is not available
PictureLoader: [card: "Bulbasaur" set: "PKTO"]: Trying to load picture
PictureLoader: [card: "Bulbasaur" set: "PKTO"]: No custom picture, trying to download
PictureLoader: [card: "Bulbasaur" set: "PKTO"]: Trying to fetch picture from url "https://brooks42.github.io/pkto/cards/Bulbasaur.png"
PictureLoader: [card: "Bulbasaur" set: "PKTO"]: Image successfully loaded from cached url "https://brooks42.github.io/pkto/cards/Bulbasaur.png"
PictureLoader: [card: "Ivysaur (DFC)" set: "PKTO"]: Requested "prop"property ("side") for Url template ("https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!") is not available
PictureLoader: [card: "Ivysaur (DFC)" set: "PKTO"]: Requested "set"property ("muid") for Url template ("https://api.scryfall.com/cards/multiverse/!set:muid!?format=image") is not available
PictureLoader: [card: "Ivysaur (DFC)" set: "PKTO"]: Requested "set"property ("muid") for Url template ("https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card") is not available
PictureLoader: [card: "Ivysaur (DFC)" set: "PKTO"]: Trying to load picture
PictureLoader: [card: "Ivysaur (DFC)" set: "PKTO"]: No custom picture, trying to download
PictureLoader: [card: "Ivysaur (DFC)" set: "PKTO"]: Trying to fetch picture from url "https://brooks42.github.io/pkto/cards/IvysaurDFC.png"
PictureLoader: [card: "Ivysaur (DFC)" set: "PKTO"]: Image successfully loaded from cached url "https://brooks42.github.io/pkto/cards/IvysaurDFC.png"
_______________________________________________________________________________________

I have a custom set using the v3 database formatting, and I'm unable to get DFC's to transform with the new feature instead of attaching. Existing cards work fine. I have updated to the new DFC templating but there is no change in behavior.

![image](https://github.com/Cockatrice/Cockatrice/assets/76265453/93e6214c-19ab-4d92-a070-f66d6092f6b8)

`<card>
			<name>Bulbasaur</name>
			<set picURL="https://brooks42.github.io/pkto/cards/Bulbasaur.png" rarity="common">PKTO</set>
			<color>G</color>
			<manacost>G</manacost>
			<type>Pokémon - Grass Poison</type>
			<pt>1/1</pt>
			<tablerow>2</tablerow>
			<side>front</side>
			<related attach="transform">Ivysaur (DFC)</related>
			<text>{T}: Add {G}.
{1}{G}: Evolve</text>
		</card>
		<card>
			<name>Ivysaur (DFC)</name>
			<set picURL="https://brooks42.github.io/pkto/cards/IvysaurDFC.png" rarity="common">PKTO</set>
			<color>G</color>
			<type>Pokémon - Grass Poison</type>
			<pt>2/2</pt>
			<tablerow>2</tablerow>
			<text>{T}: Add {G}.</text>
			<side>back</side>
			<related attach="transform">Bulbasaur</related>
		</card>`

_______________________________________________________________________________________

**Steps to reproduce:**
 - Load custom set with the above cards
 - Right click Bulbasaur
 - Select Token: Attach to "2/2 Ivysaur (DFC)"

**Comment by triggrhappy0** [comment]
`<card>
			<name>Bulbasaur</name>
			<set picURL="https://brooks42.github.io/pkto/cards/Bulbasaur.png" rarity="common">PKTO</set>
			<color>G</color>
			<manacost>G</manacost>
			<type>Pokémon - Grass Poison</type>
			<pt>1/1</pt>
			<tablerow>2</tablerow>
			<side>front</side>
			<related attach="transform">Ivysaur (DFC)</related>
			<text>{T}: Add {G}.
{1}{G}: Evolve</text>
		</card>
		<card>
			<name>Ivysaur (DFC)</name>
			<set picURL="https://brooks42.github.io/pkto/cards/IvysaurDFC.png" rarity="common">PKTO</set>
			<color>G</color>
			<type>Pokémon - Grass Poison</type>
			<pt>2/2</pt>
			<tablerow>2</tablerow>
			<text>{T}: Add {G}.</text>
			<side>back</side>
			<related attach="transform">Bulbasaur</related>
		</card>`

**Comment by ebbit1q** [comment]
please use cockatrice xml v4 format

**Comment by triggrhappy0** [comment]
On a whim I switched from <cockatrice_carddatabase version="3"> to <cockatrice_carddatabase version="4"> and now it works. I lose all my card properties, but it seems like there is an arbitrary restriction on this feature not working with older xml formats.

**Comment by ebbit1q** [comment]
you can find the details of the v4 format here:
https://github.com/Cockatrice/Cockatrice/wiki/Custom-Cards-&-Sets#to-add-your-own-custom-cards-follow-these-steps

cockatrice ships with a command line toolcalled dbconverter that will automatically convert your database from v3 to v4, I cannot guarantee it'll work well with your xml though as it looks like it contains some tags that are not part of the v3 format but are from the v4 one.
