### ISSUE TITLE
Can't download Cockatrice

### ISSUE THREAD

**Issue by LieutenantDan1172** [Cockatrice/Cockatrice#4877]
**System Information:**

<img width="644" alt="image" src="https://github.com/Cockatrice/Cockatrice/assets/145247138/6c7e2a1d-064a-4127-9752-58049e981122">

_______________________________________________________________________________________

When I attempt to download cockatrice for windows, I am redirected to the custom binaries page. I checked on reddit and don't seem to be alone in hangs this issue.

_______________________________________________________________________________________

Any attempt to download leads to the same page. rather than giving option to download app, a new tab is opened width he custom binaries page.

**Steps to reproduce:**
 - Do A
 - Do B
 - Do C ...

**Comment by ZeldaZach** [comment]
Windows 11 Download: https://github.com/Cockatrice/Cockatrice/releases/download/2023-09-14-Release-2.9.0/Cockatrice-Rings.of.the.Wild-2.9.0-Win10+-64bit.exe

**Comment by ebbit1q** [comment]
https://github.com/Cockatrice/Cockatrice/releases/download/2023-09-14-Release-2.9.0 isn't for "custom" binaries, it is for all binaries for all systems including windows
