### ISSUE TITLE
Lower rendering quality on Rings of the Wild build

### ISSUE THREAD

**Issue by Pickle-boi** [Cockatrice/Cockatrice#4880]
**Prismatic Bridge:**
Client Version: 2.8.0 (2021-01-26)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.12.9
System Locale: en_US
Install Mode: Portable
---------------------------------------------------------------------------
Portable mode enabled
Theme name not set, setting default value
Theme changed: "Default"
Sounds theme name not set, setting default value
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
Language changed: ""
main(): starting main program
main(): MainWindow constructor finished
Spoilers Disabled
main(): ui.show() finished
Startup: old client version empty, assuming first start after clean install
PictureLoader: cache fail for "_trice_card_back_328421"
CardDatabase::loadCardDatabases start
[CockatriceXml4Parser] Trying to parse:  "C:/Users/noahj/OneDrive/Desktop/CockatricePortable/data/cards.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
[CardDatabase] loadCardDatabase(): Path = "C:/Users/noahj/OneDrive/Desktop/CockatricePortable/data/cards.xml" Status = 0 Cards = 27625 Sets= 717
[CockatriceXml4Parser] Trying to parse:  "C:/Users/noahj/OneDrive/Desktop/CockatricePortable/data/tokens.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
[CardDatabase] loadCardDatabase(): Path = "C:/Users/noahj/OneDrive/Desktop/CockatricePortable/data/tokens.xml" Status = 0 Cards = 28355 Sets= 717
[CardDatabase] loadCardDatabase(): Path = "C:/Users/noahj/OneDrive/Desktop/CockatricePortable/data/spoiler.xml" Status = 4 Cards = 28355 Sets= 717
CardDatabase::loadCardDatabases success
PictureLoader: cache fail for "_trice_card_back_328421"
PictureLoader: [card:  "Acolyte of Affliction"  set:  "THB" ]: Trying to load picture
PictureLoader: [card:  "Acolyte of Affliction"  set:  "THB" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Acolyte of Affliction"  set:  "THB" ]: Trying to download picture from url: "https://api.scryfall.com/cards/a14afed6-ca42-442d-ba86-621179e6957c?format=image&face=front"
PictureLoader: [card:  "Akki Coalflinger"  set:  "PLIST" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Akki Coalflinger"  set:  "PLIST" ]: Requested set property ( "muid" ) for Url template ( "https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Akki Coalflinger"  set:  "PLIST" ]: Trying to load picture
PictureLoader: [card:  "Akki Coalflinger"  set:  "PLIST" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Acolyte of Affliction"  set:  "THB" ]: following redirect: "https://cards.scryfall.io/large/front/a/1/a14afed6-ca42-442d-ba86-621179e6957c.jpg?1581480955"
PictureLoader: [card:  "Acolyte of Affliction"  set:  "THB" ]: Image successfully downloaded from  "https://cards.scryfall.io/large/front/a/1/a14afed6-ca42-442d-ba86-621179e6957c.jpg?1581480955"
PictureLoader: [card:  "Akki Coalflinger"  set:  "PLIST" ]: Trying to download picture from url: "https://api.scryfall.com/cards/1f2b6e79-1822-4f9f-af06-1e4d356d8b76?format=image&face=front"
PictureLoader: [card:  "Akki Coalflinger"  set:  "PLIST" ]: following redirect: "https://cards.scryfall.io/large/front/1/f/1f2b6e79-1822-4f9f-af06-1e4d356d8b76.jpg?1643939737"
PictureLoader: [card:  "Akki Coalflinger"  set:  "PLIST" ]: Image successfully downloaded from  "https://cards.scryfall.io/large/front/1/f/1f2b6e79-1822-4f9f-af06-1e4d356d8b76.jpg?1643939737"
PictureLoader: [card:  "Fling"  set:  "JMP" ]: Trying to load picture
PictureLoader: [card:  "Fling"  set:  "JMP" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Fling"  set:  "JMP" ]: Trying to download picture from url: "https://api.scryfall.com/cards/8f42d773-c742-4465-b6d5-31feaba49146?format=image&face=front"
PictureLoader: [card:  "Fling"  set:  "JMP" ]: following redirect: "https://cards.scryfall.io/large/front/8/f/8f42d773-c742-4465-b6d5-31feaba49146.jpg?1601077681"
PictureLoader: [card:  "Fling"  set:  "JMP" ]: Image successfully downloaded from  "https://cards.scryfall.io/large/front/8/f/8f42d773-c742-4465-b6d5-31feaba49146.jpg?1601077681"
PictureLoader: [card:  "Fling"  set:  "JMP" ]: Trying to load picture
PictureLoader: [card:  "Fling"  set:  "JMP" ]: Picture found on disk.

**Rings of the Wild:**
Client Version: 2.9.0 (2023-09-14)
Client Operating System: Windows 11 Version 2009
Build Architecture: 64-bit
Qt Version: 6.3.2
System Locale: en_US
Install Mode: Portable
---------------------------------------------------------------------------
Portable mode enabled
Theme changed: "None "
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
Unable to load qt translation "qt_" at "C:/Games/CockatricePortable/Resources/translations"
Unable to load "cockatrice" translation "cockatrice_" at "C:/Games/CockatricePortable/translations"
main(): starting main program
main(): MainWindow constructor finished
Spoilers Disabled
PictureLoader: cache fail for "_trice_card_back_257213"
main(): ui.show() finished
Startup: found config with current version
CardDatabase::loadCardDatabases start
[CockatriceXml4Parser] Trying to parse:  "C:/Games/CockatricePortable/data/cards.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
PictureLoader: cache fail for "_trice_card_back_257210"
[CardDatabase] loadCardDatabase(): Path = "C:/Games/CockatricePortable/data/cards.xml" Status = 0 Cards = 27621 Sets = 717 "1981ms"
[CockatriceXml4Parser] Trying to parse:  "C:/Games/CockatricePortable/data/tokens.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
[CardDatabase] loadCardDatabase(): Path = "C:/Games/CockatricePortable/data/tokens.xml" Status = 0 Cards = 28351 Sets = 717 "43ms"
[CardDatabase] loadCardDatabase(): Path = "C:/Games/CockatricePortable/data/spoiler.xml" Status = 4 Cards = 28351 Sets = 717 "1ms"
CardDatabase::loadCardDatabases success
PictureLoader: [card: "\"Ach! Hans, Run!\"" set: "UNH"]: Trying to load picture
PictureLoader: [card: "Ach! Hans, Run!" set: "UNH"]: Picture found on disk.
PictureLoader: [card: "\"Lifetime\" Pass Holder" set: "UNF"]: Trying to load picture
PictureLoader: [card: "\"Lifetime\" Pass Holder" set: "UNF"]: No custom picture, trying to download
PictureLoader: [card: "Lifetime Pass Holder" set: "UNF"]: Trying to fetch picture from url "https://api.scryfall.com/cards/fede7f75-0dff-4f3e-816d-e52b43e8b33b?format=image&face=front"
PictureLoader: [card: "Acolyte of Affliction" set: "THB"]: Trying to load picture
PictureLoader: [card: "Acolyte of Affliction" set: "THB"]: No custom picture, trying to download
PictureLoader: [card: "Akki Coalflinger" set: "PLIST"]: Requested "set"property ("muid") for Url template ("https://api.scryfall.com/cards/multiverse/!set:muid!?format=image") is not available
PictureLoader: [card: "Akki Coalflinger" set: "PLIST"]: Requested "set"property ("muid") for Url template ("https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card") is not available
PictureLoader: [card: "Akki Coalflinger" set: "PLIST"]: Trying to load picture
PictureLoader: [card: "Akki Coalflinger" set: "PLIST"]: No custom picture, trying to download
PictureLoader: [card: "\"Lifetime\" Pass Holder" set: "UNF"]: following redirect to "https://cards.scryfall.io/large/front/f/e/fede7f75-0dff-4f3e-816d-e52b43e8b33b.jpg?1680048203"
PictureLoader: [card: "\"Lifetime\" Pass Holder" set: "UNF"]: Image successfully downloaded from url "https://cards.scryfall.io/large/front/f/e/fede7f75-0dff-4f3e-816d-e52b43e8b33b.jpg?1680048203"
PictureLoader: [card: "Acolyte of Affliction" set: "THB"]: Trying to fetch picture from url "https://api.scryfall.com/cards/a14afed6-ca42-442d-ba86-621179e6957c?format=image&face=front"
PictureLoader: [card: "Acolyte of Affliction" set: "THB"]: following redirect to "https://cards.scryfall.io/large/front/a/1/a14afed6-ca42-442d-ba86-621179e6957c.jpg?1581480955"
PictureLoader: [card: "Acolyte of Affliction" set: "THB"]: Image successfully downloaded from url "https://cards.scryfall.io/large/front/a/1/a14afed6-ca42-442d-ba86-621179e6957c.jpg?1581480955"
PictureLoader: [card: "Akki Coalflinger" set: "PLIST"]: Trying to fetch picture from url "https://api.scryfall.com/cards/1f2b6e79-1822-4f9f-af06-1e4d356d8b76?format=image&face=front"
PictureLoader: [card: "Akki Coalflinger" set: "PLIST"]: following redirect to "https://cards.scryfall.io/large/front/1/f/1f2b6e79-1822-4f9f-af06-1e4d356d8b76.jpg?1643939737"
PictureLoader: [card: "Akki Coalflinger" set: "PLIST"]: Image successfully downloaded from url "https://cards.scryfall.io/large/front/1/f/1f2b6e79-1822-4f9f-af06-1e4d356d8b76.jpg?1643939737"
PictureLoader: [card: "Fling" set: "JMP"]: Trying to load picture
PictureLoader: [card: "Fling" set: "JMP"]: No custom picture, trying to download
PictureLoader: [card: "Fling" set: "JMP"]: Trying to fetch picture from url "https://api.scryfall.com/cards/8f42d773-c742-4465-b6d5-31feaba49146?format=image&face=front"
PictureLoader: [card: "Fling" set: "JMP"]: following redirect to "https://cards.scryfall.io/large/front/8/f/8f42d773-c742-4465-b6d5-31feaba49146.jpg?1601077681"
PictureLoader: [card: "Fling" set: "JMP"]: Image successfully downloaded from url "https://cards.scryfall.io/large/front/8/f/8f42d773-c742-4465-b6d5-31feaba49146.jpg?1601077681"

_______________________________________________________________________________________

I've been playing with the new build for a few days now and I noticed that the quality of the card images on the new build is lower than that of the previous version, Prismatic Bridge. This issue is not urgent, but it is slightly irritating. 

Prismatic Bridge, Fling (JMP):
![image](https://github.com/Cockatrice/Cockatrice/assets/118238362/ca2de72e-0c8a-43d7-91cd-ee31ee18ec5c)

Rings of the Wild, Fling (JMP):
![image](https://github.com/Cockatrice/Cockatrice/assets/118238362/7ea48b2f-3cad-415f-95e0-6cebd8eeb200)

I tried to get the cards to be the same size on my screen, but they may be slightly different sizes.

_______________________________________________________________________________________

**Steps to reproduce:**
 - Open either build and pull up a card image
 - Pull up the same image on the other build
 - Compare

**Comment by Elarnon** [comment]
If I had to guess, I'd say I messed up something related to scaling in #4765, probably in `CardInfoPicture::paintEvent`. I will try to look into it if I find the time (no guarantee though, sorry!) but I can't seem to reproduce the issue on my side. This might be Linux vs Windows diffference (I don't have a Windows machine to test on atm) but just to be sure — @Pickle-boi do you happen to have a 4K display?

**Comment by Pickle-boi** [comment]
@Elarnon I'm not sure about a 4k display, but I have a monitor at home that I can test with. My current display on my laptop is 1920x1200 with a 13.3 inch display (I have no clue what yall need, I never got into the computer specs aspect). I'm not sure what the monitor is.

**Comment by Elarnon** [comment]
Thanks for the reply! Sorry, it was a bit late when I wrote this and I could have been more precise. The actual thing I wanted to check is if your "Display Scaling" setting (I believe it is in Settings > System > Display) is set to 100% or to any other value.

If it is set to something else than 100%, can you set it (temporarily) to 100% and check if the issue still reproduces? If it doesn't that will give a hint as to where to look for the fix (and if it does, that will give a hint as to where *not* to look).

**Comment by Pickle-boi** [comment]
Ok, thanks for the clarification. The display was set at 150% (the recommended setting). Changing the scaling to 100% seems to resolve the issue, but I haven't been able to test on the older version to compare (I can't find the download). 
![Fling 100% scaling RoW](https://github.com/Cockatrice/Cockatrice/assets/118238362/826c2ed0-b5b7-4669-8a26-2cf7f04ad245)

**Comment by Elarnon** [comment]
OK! Thanks for testing, that means that the issue is probably related to scaling (and maybe specifically fractional scaling, because I can't seem to reproduce the issue with 200% scaling on my laptop). I will try to setup an appropriate environment to investigate.

**Comment by Elarnon** [comment]
> The display was set at 150% (the recommended setting). Changing the scaling to 100% seems to resolve the issue

Thank you, this told me exactly where to look and I was able to find a fix quickly #4962 (even though the issue was actually not related to https://github.com/Cockatrice/Cockatrice/pull/4765 ).
