### ISSUE TITLE
Cascading into MDFC cards 

### ISSUE THREAD

**Issue by Malachi046** [Cockatrice/Cockatrice#4881]
Client Version: 2.9.0 (2023-09-14)
PictureLoader: [card: "Bloodthirster" set: "40K"]: Picture found on disk.
PictureLoader: [card: "Talisman of Dominance" set: "WOC"]: Trying to load picture
PictureLoader: [card: "Talisman of Dominance" set: "WOC"]: No custom picture, trying to download
PictureLoader: [card: "Volcanic Torrent" set: "CLB"]: Trying to load picture
PictureLoader: [card: "Volcanic Torrent" set: "CLB"]: Picture found on disk.
PictureLoader: [card: "Wild-Magic Sorcerer" set: "CLB"]: Trying to load picture
PictureLoader: [card: "Wild-Magic Sorcerer" set: "CLB"]: Picture found on disk.
PictureLoader: [card: "Great Unclean One" set: "40K"]: Trying to load picture
PictureLoader: [card: "Great Unclean One" set: "40K"]: Picture found on disk.
PictureLoader: [card: "Silundi Vision" set: "ZNR"]: Trying to load picture
PictureLoader: [card: "Silundi Vision" set: "ZNR"]: Picture found on disk.
PictureLoader: [card: "Sengir, the Dark Baron" set: "CMR"]: Trying to load picture
PictureLoader: [card: "Sengir, the Dark Baron" set: "CMR"]: Picture found on disk.
PictureLoader: [card: "Vandalblast" set: "SCD"]: Trying to load picture
PictureLoader: [card: "Vandalblast" set: "SCD"]: Picture found on disk.
PictureLoader: [card: "Foreboding Ruins" set: "LTC"]: Trying to load picture
PictureLoader: [card: "Foreboding Ruins" set: "LTC"]: Picture found on disk.
PictureLoader: [card: "Inevitable Betrayal" set: "MH2"]: Trying to load picture
PictureLoader: [card: "Inevitable Betrayal" set: "MH2"]: Picture found on disk.
PictureLoader: [card: "Rona, Herald of Invasion" set: "MOM"]: Trying to load picture
PictureLoader: [card: "Rona, Herald of Invasion" set: "MOM"]: No custom picture, trying to download
PictureLoader: [card: "Castle Vantress" set: "CLB"]: Trying to load picture
PictureLoader: [card: "Castle Vantress" set: "CLB"]: Picture found on disk.
PictureLoader: [card: "Burning-Rune Demon" set: "KHM"]: Trying to load picture
PictureLoader: [card: "Burning-Rune Demon" set: "KHM"]: Picture found on disk.
PictureLoader: [card: "Reaper from the Abyss" set: "J22"]: Trying to load picture
PictureLoader: [card: "Reaper from the Abyss" set: "J22"]: Picture found on disk.
PictureLoader: [card: "Suspicious Stowaway" set: "DBL"]: Trying to load picture
PictureLoader: [card: "Suspicious Stowaway" set: "DBL"]: Picture found on disk.
PictureLoader: [card: "Shipwreck Marsh" set: "DBL"]: Trying to load picture
PictureLoader: [card: "Shipwreck Marsh" set: "DBL"]: Picture found on disk.
PictureLoader: [card: "Talisman of Indulgence" set: "SCD"]: Trying to load picture
PictureLoader: [card: "Talisman of Indulgence" set: "SCD"]: Picture found on disk.
PictureLoader: [card: "Commander's Plate" set: "PHED"]: Trying to load picture
PictureLoader: [card: "Commander's Plate" set: "PHED"]: Picture found on disk.
PictureLoader: [card: "Decadent Dragon // Expensive Taste" set: "WOE"]: Trying to load picture
PictureLoader: [card: "Decadent DragonExpensive Taste" set: "WOE"]: Picture found on disk.
PictureLoader: [card: "Keeper of Secrets" set: "40K"]: Trying to load picture
PictureLoader: [card: "Keeper of Secrets" set: "40K"]: Picture found on disk.
PictureLoader: [card: "Bedevil" set: "DMC"]: Trying to load picture
PictureLoader: [card: "Bedevil" set: "DMC"]: Picture found on disk.
PictureLoader: [card: "Path of Ancestry" set: "WOC"]: Trying to load picture
PictureLoader: [card: "Path of Ancestry" set: "WOC"]: No custom picture, trying to download
PictureLoader: [card: "Kill! Maim! Burn!" set: "40K"]: Trying to load picture
PictureLoader: [card: "Kill! Maim! Burn!" set: "40K"]: Picture found on disk.
PictureLoader: [card: "Watery Grave" set: "RVR"]: following redirect to "https://cards.scryfall.io/large/front/6/e/6e86eb36-f4cc-4a75-b43a-4dee463a3b33.jpg?1695422495"
PictureLoader: [card: "Watery Grave" set: "RVR"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/6/e/6e86eb36-f4cc-4a75-b43a-4dee463a3b33.jpg?1695422495"
PictureLoader: [card: "Invisibility" set: "PLIST"]: Trying to fetch picture from url "https://api.scryfall.com/cards/4ad1dc5c-ed9f-44a9-bd39-1d7498d01cd8?format=image&face=front"
PictureLoader: [card: "Invisibility" set: "PLIST"]: following redirect to "https://cards.scryfall.io/large/front/4/a/4ad1dc5c-ed9f-44a9-bd39-1d7498d01cd8.jpg?1626117340"
PictureLoader: [card: "Invisibility" set: "PLIST"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/4/a/4ad1dc5c-ed9f-44a9-bd39-1d7498d01cd8.jpg?1626117340"
PictureLoader: [card: "Orcish Bowmasters" set: "LTR"]: Trying to fetch picture from url "https://api.scryfall.com/cards/7c024bae-5631-4e20-ac69-df392ac9e109?format=image&face=front"
PictureLoader: [card: "Orcish Bowmasters" set: "LTR"]: following redirect to "https://cards.scryfall.io/large/front/7/c/7c024bae-5631-4e20-ac69-df392ac9e109.jpg?1686968669"
PictureLoader: [card: "Orcish Bowmasters" set: "LTR"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/7/c/7c024bae-5631-4e20-ac69-df392ac9e109.jpg?1686968669"
PictureLoader: [card: "Drain Power" set: "ME4"]: Trying to fetch picture from url "https://api.scryfall.com/cards/380a7357-8c07-4ee5-83a0-10672d7e85d4?format=image&face=front"
PictureLoader: [card: "Drain Power" set: "ME4"]: following redirect to "https://cards.scryfall.io/large/front/3/8/380a7357-8c07-4ee5-83a0-10672d7e85d4.jpg?1562908155"
PictureLoader: [card: "Drain Power" set: "ME4"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/3/8/380a7357-8c07-4ee5-83a0-10672d7e85d4.jpg?1562908155"
PictureLoader: [card: "Command Tower" set: "WOC"]: Trying to fetch picture from url "https://api.scryfall.com/cards/aed61bbb-83fd-452b-b940-c8eb1e1ebdac?format=image&face=front"
PictureLoader: [card: "Command Tower" set: "WOC"]: following redirect to "https://cards.scryfall.io/large/front/a/e/aed61bbb-83fd-452b-b940-c8eb1e1ebdac.jpg?1692935942"
PictureLoader: [card: "Command Tower" set: "WOC"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/a/e/aed61bbb-83fd-452b-b940-c8eb1e1ebdac.jpg?1692935942"
PictureLoader: [card: "Rivendell" set: "LTR"]: Trying to fetch picture from url "https://api.scryfall.com/cards/bacd500c-1389-4314-a53e-0ad510d6fb79?format=image&face=front"
PictureLoader: [card: "Rivendell" set: "LTR"]: following redirect to "https://cards.scryfall.io/large/front/b/a/bacd500c-1389-4314-a53e-0ad510d6fb79.jpg?1686970394"
PictureLoader: [card: "Rivendell" set: "LTR"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/b/a/bacd500c-1389-4314-a53e-0ad510d6fb79.jpg?1686970394"
PictureLoader: [card: "Island" set: "LCI"]: Trying to fetch picture from url "https://api.scryfall.com/cards/338e5b63-1fee-4a7c-af9b-483d383f79b7?format=image&face=front"
PictureLoader: [card: "Island" set: "LCI"]: following redirect to "https://cards.scryfall.io/large/front/3/3/338e5b63-1fee-4a7c-af9b-483d383f79b7.jpg?1695408219"
PictureLoader: [card: "Island" set: "LCI"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/3/3/338e5b63-1fee-4a7c-af9b-483d383f79b7.jpg?1695408219"
PictureLoader: [card: "Nalfeshnee" set: "HBG"]: Trying to fetch picture from url "https://api.scryfall.com/cards/5ca10af3-62e9-4b2b-a1a7-967e4a5321fe?format=image&face=front"
PictureLoader: [card: "Nalfeshnee" set: "HBG"]: following redirect to "https://cards.scryfall.io/large/front/5/c/5ca10af3-62e9-4b2b-a1a7-967e4a5321fe.jpg?1681000312"
PictureLoader: [card: "Nalfeshnee" set: "HBG"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/5/c/5ca10af3-62e9-4b2b-a1a7-967e4a5321fe.jpg?1681000312"
PictureLoader: [card: "Evolving Wilds" set: "LTC"]: Trying to fetch picture from url "https://api.scryfall.com/cards/e24ec4c1-5a28-450d-8e37-62a154749ee6?format=image&face=front"
PictureLoader: [card: "Evolving Wilds" set: "LTC"]: following redirect to "https://cards.scryfall.io/large/front/e/2/e24ec4c1-5a28-450d-8e37-62a154749ee6.jpg?1687735596"
PictureLoader: [card: "Evolving Wilds" set: "LTC"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/e/2/e24ec4c1-5a28-450d-8e37-62a154749ee6.jpg?1687735596"
PictureLoader: [card: "Mountain" set: "LCI"]: Trying to fetch picture from url "https://api.scryfall.com/cards/7cb82fdb-5090-45c0-ae67-4846667c8625?format=image&face=front"
PictureLoader: [card: "Mountain" set: "LCI"]: following redirect to "https://cards.scryfall.io/large/front/7/c/7cb82fdb-5090-45c0-ae67-4846667c8625.jpg?1695408268"
PictureLoader: [card: "Mountain" set: "LCI"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/7/c/7cb82fdb-5090-45c0-ae67-4846667c8625.jpg?1695408268"
PictureLoader: [card: "Swiftfoot Boots" set: "PAGL"]: Trying to fetch picture from url "https://api.scryfall.com/cards/a41a16a0-6afc-452d-a18f-94f0d68f1cda?format=image&face=front"
PictureLoader: [card: "Swiftfoot Boots" set: "PAGL"]: following redirect to "https://cards.scryfall.io/large/front/a/4/a41a16a0-6afc-452d-a18f-94f0d68f1cda.jpg?1693264258"
PictureLoader: [card: "Swiftfoot Boots" set: "PAGL"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/a/4/a41a16a0-6afc-452d-a18f-94f0d68f1cda.jpg?1693264258"
PictureLoader: [card: "Swamp" set: "LCI"]: Trying to fetch picture from url "https://api.scryfall.com/cards/a825ac86-d642-42fd-b6aa-94aa804907d9?format=image&face=front"
PictureLoader: [card: "Swamp" set: "LCI"]: following redirect to "https://cards.scryfall.io/large/front/a/8/a825ac86-d642-42fd-b6aa-94aa804907d9.jpg?1695408249"
PictureLoader: [card: "Swamp" set: "LCI"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/a/8/a825ac86-d642-42fd-b6aa-94aa804907d9.jpg?1695408249"
PictureLoader: [card: "Mithril Coat" set: "LTR"]: Trying to fetch picture from url "https://api.scryfall.com/cards/0fd1fc09-a09d-45e6-8a07-3a8a83b4e6ec?format=image&face=front"
PictureLoader: [card: "Mithril Coat" set: "LTR"]: following redirect to "https://cards.scryfall.io/large/front/0/f/0fd1fc09-a09d-45e6-8a07-3a8a83b4e6ec.jpg?1686970224"
PictureLoader: [card: "Mithril Coat" set: "LTR"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/0/f/0fd1fc09-a09d-45e6-8a07-3a8a83b4e6ec.jpg?1686970224"
PictureLoader: [card: "Sunken Hollow" set: "WOC"]: Trying to fetch picture from url "https://api.scryfall.com/cards/4953d020-2173-448c-a8ec-0611e8262d6a?format=image&face=front"
PictureLoader: [card: "Sunken Hollow" set: "WOC"]: following redirect to "https://cards.scryfall.io/large/front/4/9/4953d020-2173-448c-a8ec-0611e8262d6a.jpg?1692936132"
PictureLoader: [card: "Sunken Hollow" set: "WOC"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/4/9/4953d020-2173-448c-a8ec-0611e8262d6a.jpg?1692936132"
PictureLoader: [card: "Prosper, Tome-Bound" set: "HBG"]: Trying to fetch picture from url "https://api.scryfall.com/cards/eecb1a63-26e5-45e9-9b2f-2789d66f12f0?format=image&face=front"
PictureLoader: [card: "Prosper, Tome-Bound" set: "HBG"]: following redirect to "https://cards.scryfall.io/large/front/e/e/eecb1a63-26e5-45e9-9b2f-2789d66f12f0.jpg?1681000768"
PictureLoader: [card: "Prosper, Tome-Bound" set: "HBG"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/e/e/eecb1a63-26e5-45e9-9b2f-2789d66f12f0.jpg?1681000768"
PictureLoader: [card: "Exotic Orchard" set: "WOC"]: Trying to fetch picture from url "https://api.scryfall.com/cards/11ac362c-6ee3-410a-9b59-b94839161dc8?format=image&face=front"
PictureLoader: [card: "Exotic Orchard" set: "WOC"]: following redirect to "https://cards.scryfall.io/large/front/1/1/11ac362c-6ee3-410a-9b59-b94839161dc8.jpg?1692935984"
PictureLoader: [card: "Exotic Orchard" set: "WOC"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/1/1/11ac362c-6ee3-410a-9b59-b94839161dc8.jpg?1692935984"
PictureLoader: [card: "Sol Ring" set: "WOC"]: Trying to fetch picture from url "https://api.scryfall.com/cards/16fbbd8d-bb18-4a8b-95a4-30ad6d548f72?format=image&face=front"
PictureLoader: [card: "Sol Ring" set: "WOC"]: following redirect to "https://cards.scryfall.io/large/front/1/6/16fbbd8d-bb18-4a8b-95a4-30ad6d548f72.jpg?1692935844"
PictureLoader: [card: "Sol Ring" set: "WOC"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/1/6/16fbbd8d-bb18-4a8b-95a4-30ad6d548f72.jpg?1692935844"
PictureLoader: [card: "Archpriest of Shadows" set: "MOM"]: Trying to fetch picture from url "https://api.scryfall.com/cards/f5931746-a55c-4528-9e4a-ee15edab3489?format=image&face=front"
PictureLoader: [card: "Archpriest of Shadows" set: "MOM"]: following redirect to "https://cards.scryfall.io/large/front/f/5/f5931746-a55c-4528-9e4a-ee15edab3489.jpg?1682203557"
PictureLoader: [card: "Archpriest of Shadows" set: "MOM"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/f/5/f5931746-a55c-4528-9e4a-ee15edab3489.jpg?1682203557"
PictureLoader: [card: "Talisman of Dominance" set: "WOC"]: Trying to fetch picture from url "https://api.scryfall.com/cards/5c4f9134-e3be-4520-a53e-2cf572a5758f?format=image&face=front"
PictureLoader: [card: "Talisman of Dominance" set: "WOC"]: following redirect to "https://cards.scryfall.io/large/front/5/c/5c4f9134-e3be-4520-a53e-2cf572a5758f.jpg?1692935857"
PictureLoader: [card: "Talisman of Dominance" set: "WOC"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/5/c/5c4f9134-e3be-4520-a53e-2cf572a5758f.jpg?1692935857"
PictureLoader: [card: "Rona, Herald of Invasion" set: "MOM"]: Trying to fetch picture from url "https://api.scryfall.com/cards/f487b582-e73f-4325-939f-95fc5a9aba49?format=image&face=front"
PictureLoader: [card: "Rona, Herald of Invasion" set: "MOM"]: following redirect to "https://cards.scryfall.io/large/front/f/4/f487b582-e73f-4325-939f-95fc5a9aba49.jpg?1682203390"
PictureLoader: [card: "Rona, Herald of Invasion" set: "MOM"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/f/4/f487b582-e73f-4325-939f-95fc5a9aba49.jpg?1682203390"
PictureLoader: [card: "Path of Ancestry" set: "WOC"]: Trying to fetch picture from url "https://api.scryfall.com/cards/de0f23f6-3720-4d91-9484-7962e1c295c9?format=image&face=front"
PictureLoader: [card: "Path of Ancestry" set: "WOC"]: following redirect to "https://cards.scryfall.io/large/front/d/e/de0f23f6-3720-4d91-9484-7962e1c295c9.jpg?1692936082"
PictureLoader: [card: "Path of Ancestry" set: "WOC"]: Image successfully loaded from cached url "https://cards.scryfall.io/large/front/d/e/de0f23f6-3720-4d91-9484-7962e1c295c9.jpg?1692936082"
gameEvent: invalid gameId
GameScene::addPlayer name= "Malachi046"
PictureLoader: cache fail for "_trice_card_back_274319"
QWindowsWindow::setGeometry: Unable to set geometry 1920x1067+0+23 (frame: 1936x1106-8-8) on QWidgetWindow/"MainWindowClassWindow" on "\\.\DISPLAY2". Resulting geometry: 1920x1057+0+23 (frame: 1936x1096-8-8) margins: 8, 31, 8, 8 minimum size: 674x1067 MINMAXINFO(maxSize=POINT(x=0, y=0), maxpos=POINT(x=0, y=0), maxtrack=POINT(x=0, y=0), mintrack=POINT(x=690, y=1106)))
PictureLoader: cache fail for "_trice_card_back_335421"
PictureLoader: cache fail for "_trice_card_back_335417"
Loaded from "C:/Users/Lynsey Harrington/AppData/Local/Cockatrice/Cockatrice/decks/a new abbadon wishlist 9-23.cod" - true
Deck was loaded - true
PictureLoader: [card: "SIDEBOARD:" set: ""]: Requested "prop"property ("side") for Url template ("https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!") is not available
PictureLoader: [card: "SIDEBOARD:" set: ""]: Requested "set"property ("muid") for Url template ("https://api.scryfall.com/cards/multiverse/!set:muid!?format=image") is not available
PictureLoader: [card: "SIDEBOARD:" set: ""]: Requested "set"property ("muid") for Url template ("https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card") is not available
PictureLoader: [card: "SIDEBOARD:" set: ""]: Trying to load picture
PictureLoader: [card: "SIDEBOARD:" set: ""]: No custom picture, trying to download
PictureLoader: [card: "SIDEBOARD" set: ""]: Trying to fetch picture from url "https://gatherer.wizards.com/Handlers/Image.ashx?name=SIDEBOARD%3A&type=card"
PictureLoader: [card: "SIDEBOARD:" set: ""]: Picture found, but blacklisted, will consider it as not found
PictureLoader: [card: "SIDEBOARD" set: ""]: Picture NOT found, download failed, no more url combinations to try: BAILING OUT
QPixmap::scaled: Pixmap is a null pixmap
PictureLoader: cache fail for "_trice_card_back_226288"
PictureLoader: cache fail for "_trice_card_back_140199"
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap

_______________________________________________________________________________________

I'm no expert at the rules, but the new cascade feature (Right click->top of library->take top card until) seems to behave strange with MDFC cards. While using the constraints (cmc<1 -t:land) to cascade it hit cards like [[Inevitable Betrayal]] like it's supposed to, but it would also hit cards like [[silundi vision]] and [[akoum warrior]] which are cmc 3 and 6 on one side and lands on the other. I figured the land side was causing it to pass the cmc<1 constraint while the other side was causing it to pass the -t:land side, but another card [[Birgi, God of Storytelling]] would pass the constraint despite neither side being cmc<1 (they're cmc 3 and 5). I tested birgi a bit and it seems to identify as a 0 cmc creature. Same with silundi vision, it identifies as a 0 cmc instant.

_______________________________________________________________________________________

have silundi vision and/or birgi in the deck 
ctrl+shift+y 
enter cmc<0 -t:land

**Comment by tooomm** [comment]
Can you please try this version here? @Malachi046 
https://github.com/Cockatrice/Cockatrice/actions/runs/6442745448?pr=4896#artifacts
You also need to run Oracle again to build the card database freshly after installing the new version.

It looks like cmc is not correctly saved for those cards.
Your example - silundi vision - is not showing a cmc value in the deck editor currently.
