### ISSUE TITLE
Ctrl+Enter as shortcut for OK when setting annotation

### ISSUE THREAD

**Issue by RickyRister** [Cockatrice/Cockatrice#4915]
**Description of New Feature**
With the addition of multiline annotations in the latest version, pressing enter will no longer close the annotation window. Instead, you now have to manually mouse over and click OK. This is a step back from the previous version, where you could enter an annotation entirely from the keyboard. It makes setting annotations much less convenient, not to mention slower.

I suggest adding a keyboard shortcut for OK'ing the annotation. Ctrl+Enter is used as a shortcut for "click the OK button" in many other apps and programs, so should be familiar to most people. That way, we can support multiline annotations while retaining the previous ease of entering annotations.

**Comment by ebbit1q** [comment]
this shortcut already exists in a way, the accelerator key for the ok button works while the text field is in focus, you can press alt o to select the ok button

**Comment by MotherofRuins** [comment]
I'd be happy with this or with Alt-Enter to add a newline within the dialog, like Slack and Discord do.
