### ISSUE TITLE
macOS Sonoma Support

### ISSUE THREAD

**Issue by BjoernRave** [Cockatrice/Cockatrice#4936]
**System Information:**
Client Version: 2.9.0 (2023-09-14)
Client Operating System: macOS 14.1
Build Architecture: 64-bit
Qt Version: 6.5.1
System Locale: en_DE
Install Mode: Standard
---------------------------------------------------------------------------
Theme changed: "None "
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
Unable to load qt translation "qt_" at "/Applications/cockatrice.app/Contents/Resources/translations"
Unable to load "cockatrice" translation "cockatrice_" at "/Applications/cockatrice.app/Contents/MacOS/../Resources/translations"
main(): starting main program
main(): MainWindow constructor finished
Spoilers Disabled
main(): ui.show() finished
PictureLoader: cache fail for "_trice_card_back_317428"
Startup: found config with current version
CardDatabase::loadCardDatabases start
[CockatriceXml4Parser] Trying to parse:  "/Users/bjoernrave/Library/Application Support/Cockatrice/Cockatrice/cards.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
[CardDatabase] loadCardDatabase(): Path = "/Users/bjoernrave/Library/Application Support/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 28282 Sets = 725 "1081ms"
[CockatriceXml4Parser] Trying to parse:  "/Users/bjoernrave/Library/Application Support/Cockatrice/Cockatrice/tokens.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
[CardDatabase] loadCardDatabase(): Path = "/Users/bjoernrave/Library/Application Support/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 29057 Sets = 725 "25ms"
[CardDatabase] loadCardDatabase(): Path = "/Users/bjoernrave/Library/Application Support/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 29057 Sets = 725 "0ms"
CardDatabase::loadCardDatabases success

_______________________________________________________________________________________

When I try to connect to a server sometimes it already happens during connecting and sometimes when clicking on the magic area. The UI glitches and is not working anymore as you can see in the screenshot. 

I am not sure if this is connected with MacOS Sonoma or the M2 chip, but I read somewhere that apple silicon should be supported.

<img width="1728" alt="Screenshot 2023-11-09 at 19 54 30" src="https://github.com/Cockatrice/Cockatrice/assets/36173920/4cc69576-8e30-4806-8a0d-e1bd88b232f6">

_______________________________________________________________________________________

Start application
Actions -> Connect -> Magic

**Comment by ebbit1q** [comment]
this looks pretty bad, we can check if making a build on a more recent version of macos solves the problem

**Comment by tooomm** [comment]
@BjoernRave Can you please confirm if this helps or fixes your issue?

**Comment by hottopotatto** [comment]
> @BjoernRave Can you please confirm if this helps or fixes your issue?
> 
> You can download a build for macOS 13 on this page (very bottom): https://github.com/Cockatrice/Cockatrice/actions/runs/7229159667#artifacts We assume that helps with Sonoma as well.

For the sake of feedback: this one worked for me. I had the same issues as TS. MacOS 13 build fixed that for me being on: Sonoma 14.1.1 (intel-bases MacBook).

**Comment by tooomm** [comment]
Thanks for confirming @hottopotatto!

Feel free to reopen if it does not work for you @BjoernRave
