### ISSUE TITLE
Requesting new feature to fix Triumph of Saint Katherine

### ISSUE THREAD

**Issue by morganrwolfe** [Cockatrice/Cockatrice#4938]
Currently on cockatrice, Triumph of Saint Katherines ability is not able to be properly resolved. For context here is the full text: "Praesidium Protectiva — When Triumph of Saint Katherine is put into your graveyard from the battlefield, exile it and the top six cards of your library in a face-down pile. If you do, shuffle that pile and put it back on top of your library."

I have spent some time trying to find a way to resolve this sufficiently randomly but have been unsuccessful. If there a shortcut exists that allows for this please let me know. Otherwise I request a feature to shuffle the top "x" cards of library, which seems like it would be the easiest way to do it.

**Comment by ebbit1q** [comment]
there currently isn't a way to do this directly, yet there is a sinple workaround: simply place the cards on the bottom of the library in a random order (this shuffles them) then place them on top.

Implementing an action in the player would be very straightforward though.

**Comment by morganrwolfe** [comment]
That method hadn't occurred to me. Thanks for the tip.

**Comment by ebbit1q** [comment]
you're welcome
