### ISSUE TITLE
Cascade not working

### ISSUE THREAD

**Issue by AmebaDaKing** [Cockatrice/Cockatrice#4940]
**System Information:**
Client Version: 2.9.0 (2023-09-14)
PictureLoader: [card: "Saruman the White" set: "LTR"]: Trying to fetch picture from url "https://api.scryfall.com/cards/1bfccbab-29fa-4e92-8919-6cd4815fb655?format=image&face=front"
PictureLoader: [card: "Saruman the White" set: "LTR"]: following redirect to "https://cards.scryfall.io/large/front/1/b/1bfccbab-29fa-4e92-8919-6cd4815fb655.jpg?1686968266"
PictureLoader: [card: "Saruman the White" set: "LTR"]: Image successfully downloaded from url "https://cards.scryfall.io/large/front/1/b/1bfccbab-29fa-4e92-8919-6cd4815fb655.jpg?1686968266"
PictureLoader: [card: "Book of Mazarbul" set: "LTR"]: Trying to fetch picture from url "https://api.scryfall.com/cards/04dcef75-6f98-4233-ae32-6fe41724c8e0?format=image&face=front"
PictureLoader: [card: "Book of Mazarbul" set: "LTR"]: following redirect to "https://cards.scryfall.io/large/front/0/4/04dcef75-6f98-4233-ae32-6fe41724c8e0.jpg?1688569131"
PictureLoader: [card: "Book of Mazarbul" set: "LTR"]: Image successfully downloaded from url "https://cards.scryfall.io/large/front/0/4/04dcef75-6f98-4233-ae32-6fe41724c8e0.jpg?1688569131"
PictureLoader: [card: "Dreadhorde Invasion" set: "CMM"]: Trying to fetch picture from url "https://api.scryfall.com/cards/241a6a3b-8809-4d22-bf1e-c4620c609aba?format=image&face=front"
PictureLoader: [card: "Dreadhorde Invasion" set: "CMM"]: following redirect to "https://cards.scryfall.io/large/front/2/4/241a6a3b-8809-4d22-bf1e-c4620c609aba.jpg?1690004550"
PictureLoader: [card: "Dreadhorde Invasion" set: "CMM"]: Image successfully downloaded from url "https://cards.scryfall.io/large/front/2/4/241a6a3b-8809-4d22-bf1e-c4620c609aba.jpg?1690004550"
PictureLoader: [card: "Uglúk of the White Hand" set: "LTR"]: Trying to fetch picture from url "https://api.scryfall.com/cards/e914c7fc-be3c-4346-bf37-6e10f4998204?format=image&face=front"
PictureLoader: [card: "Uglúk of the White Hand" set: "LTR"]: following redirect to "https://cards.scryfall.io/large/front/e/9/e914c7fc-be3c-4346-bf37-6e10f4998204.jpg?1686970114"
PictureLoader: [card: "Uglúk of the White Hand" set: "LTR"]: Image successfully downloaded from url "https://cards.scryfall.io/large/front/e/9/e914c7fc-be3c-4346-bf37-6e10f4998204.jpg?1686970114"
PictureLoader: [card: "Honor the God-Pharaoh" set: "WAR"]: Trying to fetch picture from url "https://api.scryfall.com/cards/75844d13-74f5-4008-9bc6-2f6d04f378aa?format=image&face=front"
PictureLoader: [card: "Honor the God-Pharaoh" set: "WAR"]: following redirect to "https://cards.scryfall.io/large/front/7/5/75844d13-74f5-4008-9bc6-2f6d04f378aa.jpg?1557576722"
PictureLoader: [card: "Honor the God-Pharaoh" set: "WAR"]: Image successfully downloaded from url "https://cards.scryfall.io/large/front/7/5/75844d13-74f5-4008-9bc6-2f6d04f378aa.jpg?1557576722"
PictureLoader: [card: "Stormcarved Coast" set: "WHO"]: Trying to fetch picture from url "https://api.scryfall.com/cards/54fe029f-e173-4a16-bdb4-394847b4e50b?format=image&face=front"
PictureLoader: [card: "Stormcarved Coast" set: "WHO"]: following redirect to "https://cards.scryfall.io/large/front/5/4/54fe029f-e173-4a16-bdb4-394847b4e50b.jpg?1696637120"
PictureLoader: [card: "Stormcarved Coast" set: "WHO"]: Image successfully downloaded from url "https://cards.scryfall.io/large/front/5/4/54fe029f-e173-4a16-bdb4-394847b4e50b.jpg?1696637120"
PictureLoader: [card: "Ioreth of the Healing House" set: "LTR"]: Trying to fetch picture from url "https://api.scryfall.com/cards/03ab74cd-978a-49eb-9d38-bc8b472b3cef?format=image&face=front"
PictureLoader: [card: "Ioreth of the Healing House" set: "LTR"]: following redirect to "https://cards.scryfall.io/large/front/0/3/03ab74cd-978a-49eb-9d38-bc8b472b3cef.jpg?1686968152"
PictureLoader: [card: "Ioreth of the Healing House" set: "LTR"]: Image successfully downloaded from url "https://cards.scryfall.io/large/front/0/3/03ab74cd-978a-49eb-9d38-bc8b472b3cef.jpg?1686968152"
PictureLoader: [card: "Call of the Ring" set: "PLTR"]: Trying to fetch picture from url "https://api.scryfall.com/cards/c492e865-a9db-41a0-ba75-b8de3551357b?format=image&face=front"
PictureLoader: [card: "Call of the Ring" set: "PLTR"]: following redirect to "https://cards.scryfall.io/large/front/c/4/c492e865-a9db-41a0-ba75-b8de3551357b.jpg?1687888002"
PictureLoader: [card: "Call of the Ring" set: "PLTR"]: Image successfully downloaded from url "https://cards.scryfall.io/large/front/c/4/c492e865-a9db-41a0-ba75-b8de3551357b.jpg?1687888002"
PictureLoader: [card: "Smite the Deathless" set: "LTR"]: Trying to fetch picture from url "https://api.scryfall.com/cards/8b716fcc-c4cc-4987-be82-2897a9888d23?format=image&face=front"
PictureLoader: [card: "Smite the Deathless" set: "LTR"]: following redirect to "https://cards.scryfall.io/large/front/8/b/8b716fcc-c4cc-4987-be82-2897a9888d23.jpg?1686969173"
PictureLoader: [card: "Smite the Deathless" set: "LTR"]: Image successfully downloaded from url "https://cards.scryfall.io/large/front/8/b/8b716fcc-c4cc-4987-be82-2897a9888d23.jpg?1686969173"
PictureLoader: [card: "Sauron, Lord of the Rings" set: "LTC"]: Trying to fetch picture from url "https://api.scryfall.com/cards/fc53dec0-79fe-4f6f-9d5b-cf298588e808?format=image&face=front"
PictureLoader: [card: "Sauron, Lord of the Rings" set: "LTC"]: following redirect to "https://cards.scryfall.io/large/front/f/c/fc53dec0-79fe-4f6f-9d5b-cf298588e808.jpg?1686963724"
PictureLoader: [card: "Sauron, Lord of the Rings" set: "LTC"]: Image successfully downloaded from url "https://cards.scryfall.io/large/front/f/c/fc53dec0-79fe-4f6f-9d5b-cf298588e808.jpg?1686963724"
PictureLoader: [card: "Haunted Ridge" set: "WHO"]: Trying to fetch picture from url "https://api.scryfall.com/cards/01b62353-e170-4c29-bda1-7cd8441c01c2?format=image&face=front"
PictureLoader: [card: "Haunted Ridge" set: "WHO"]: following redirect to "https://cards.scryfall.io/large/front/0/1/01b62353-e170-4c29-bda1-7cd8441c01c2.jpg?1696637070"
PictureLoader: [card: "Haunted Ridge" set: "WHO"]: Image successfully downloaded from url "https://cards.scryfall.io/large/front/0/1/01b62353-e170-4c29-bda1-7cd8441c01c2.jpg?1696637070"
PictureLoader: [card: "Toll of the Invasion" set: "WAR"]: Trying to fetch picture from url "https://api.scryfall.com/cards/4471c2a5-aa2c-47e2-8238-1eb366c8adc9?format=image&face=front"
PictureLoader: [card: "Toll of the Invasion" set: "WAR"]: following redirect to "https://cards.scryfall.io/large/front/4/4/4471c2a5-aa2c-47e2-8238-1eb366c8adc9.jpg?1557576575"
PictureLoader: [card: "Toll of the Invasion" set: "WAR"]: Image successfully downloaded from url "https://cards.scryfall.io/large/front/4/4/4471c2a5-aa2c-47e2-8238-1eb366c8adc9.jpg?1557576575"
PictureLoader: [card: "Wasteland" set: "PIP"]: Trying to fetch picture from url "https://api.scryfall.com/cards/e4d51c18-4b7d-4948-96bc-12c8ab3d0bd0?format=image&face=front"
PictureLoader: [card: "Wasteland" set: "PIP"]: following redirect to "https://cards.scryfall.io/large/front/e/4/e4d51c18-4b7d-4948-96bc-12c8ab3d0bd0.jpg?1697729216"
PictureLoader: [card: "Wasteland" set: "PIP"]: Image successfully downloaded from url "https://cards.scryfall.io/large/front/e/4/e4d51c18-4b7d-4948-96bc-12c8ab3d0bd0.jpg?1697729216"
PictureLoader: [card: "Sauron, the Dark Lord" set: "PLTR"]: Trying to fetch picture from url "https://api.scryfall.com/cards/fc8d7f48-6a18-4f18-b4bd-7308390aa340?format=image&face=front"
PictureLoader: [card: "Sauron, the Dark Lord" set: "PLTR"]: following redirect to "https://cards.scryfall.io/large/front/f/c/fc8d7f48-6a18-4f18-b4bd-7308390aa340.jpg?1687887486"
PictureLoader: [card: "Sauron, the Dark Lord" set: "PLTR"]: Image successfully downloaded from url "https://cards.scryfall.io/large/front/f/c/fc8d7f48-6a18-4f18-b4bd-7308390aa340.jpg?1687887486"
PictureLoader: [card: "Enter the God-Eternals" set: "SCD"]: Trying to fetch picture from url "https://api.scryfall.com/cards/d1da08b8-08c2-44e8-874b-eb93b535e90b?format=image&face=front"
PictureLoader: [card: "Enter the God-Eternals" set: "SCD"]: following redirect to "https://cards.scryfall.io/large/front/d/1/d1da08b8-08c2-44e8-874b-eb93b535e90b.jpg?1674675850"
PictureLoader: [card: "Enter the God-Eternals" set: "SCD"]: Image successfully downloaded from url "https://cards.scryfall.io/large/front/d/1/d1da08b8-08c2-44e8-874b-eb93b535e90b.jpg?1674675850"
PictureLoader: [card: "Lazotep Chancellor" set: "J21"]: Trying to fetch picture from url "https://api.scryfall.com/cards/2583c3c4-4238-4136-9020-37d46bff73d0?format=image&face=front"
PictureLoader: [card: "Lazotep Chancellor" set: "J21"]: following redirect to "https://cards.scryfall.io/large/front/2/5/2583c3c4-4238-4136-9020-37d46bff73d0.jpg?1630251778"
PictureLoader: [card: "Lazotep Chancellor" set: "J21"]: Image successfully downloaded from url "https://cards.scryfall.io/large/front/2/5/2583c3c4-4238-4136-9020-37d46bff73d0.jpg?1630251778"
PictureLoader: [card: "Invading Manticore" set: "WAR"]: Trying to fetch picture from url "https://api.scryfall.com/cards/674e408b-f052-451c-9bf9-ac6f98753a9d?format=image&face=front"
PictureLoader: [card: "Invading Manticore" set: "WAR"]: following redirect to "https://cards.scryfall.io/large/front/6/7/674e408b-f052-451c-9bf9-ac6f98753a9d.jpg?1557576743"
PictureLoader: [card: "Invading Manticore" set: "WAR"]: Image successfully downloaded from url "https://cards.scryfall.io/large/front/6/7/674e408b-f052-451c-9bf9-ac6f98753a9d.jpg?1557576743"
PictureLoader: [card: "Herald of the Dreadhorde" set: "WAR"]: Trying to fetch picture from url "https://api.scryfall.com/cards/d7ae9cb7-a3af-4224-89a5-a72f4d09dacf?format=image&face=front"
PictureLoader: [card: "Herald of the Dreadhorde" set: "WAR"]: following redirect to "https://cards.scryfall.io/large/front/d/7/d7ae9cb7-a3af-4224-89a5-a72f4d09dacf.jpg?1557576484"
PictureLoader: [card: "Herald of the Dreadhorde" set: "WAR"]: Image successfully downloaded from url "https://cards.scryfall.io/large/front/d/7/d7ae9cb7-a3af-4224-89a5-a72f4d09dacf.jpg?1557576484"
PictureLoader: [card: "Blood Crypt" set: "RVR"]: Trying to fetch picture from url "https://api.scryfall.com/cards/0994aef4-b341-45f4-8881-523565a5956e?format=image&face=front"
PictureLoader: [card: "Blood Crypt" set: "RVR"]: following redirect to "https://cards.scryfall.io/large/front/0/9/0994aef4-b341-45f4-8881-523565a5956e.jpg?1695422241"
PictureLoader: [card: "Blood Crypt" set: "RVR"]: Image successfully downloaded from url "https://cards.scryfall.io/large/front/0/9/0994aef4-b341-45f4-8881-523565a5956e.jpg?1695422241"
PictureLoader: [card: "Mauhúr, Uruk-hai Captain" set: "LTR"]: Trying to fetch picture from url "https://api.scryfall.com/cards/65e9a757-7ed4-4cc0-bb6f-a59fa69b32a5?format=image&face=front"
PictureLoader: [card: "Mauhúr, Uruk-hai Captain" set: "LTR"]: following redirect to "https://cards.scryfall.io/large/front/6/5/65e9a757-7ed4-4cc0-bb6f-a59fa69b32a5.jpg?1686969884"
PictureLoader: [card: "Mauhúr, Uruk-hai Captain" set: "LTR"]: Image successfully downloaded from url "https://cards.scryfall.io/large/front/6/5/65e9a757-7ed4-4cc0-bb6f-a59fa69b32a5.jpg?1686969884"
PictureLoader: [card: "Island" set: "PIP"]: Trying to fetch picture from url "https://api.scryfall.com/cards/a5b0a88d-7049-4206-8085-4a68ab0bfd81?format=image&face=front"
PictureLoader: [card: "Island" set: "PIP"]: following redirect to "https://cards.scryfall.io/large/front/a/5/a5b0a88d-7049-4206-8085-4a68ab0bfd81.jpg?1697729460"
PictureLoader: [card: "Island" set: "PIP"]: Image successfully downloaded from url "https://cards.scryfall.io/large/front/a/5/a5b0a88d-7049-4206-8085-4a68ab0bfd81.jpg?1697729460"
PictureLoader: [card: "Underground Sea" set: "30A"]: Trying to fetch picture from url "https://api.scryfall.com/cards/cbde3041-fb76-4dc8-9cdf-359ad955fd73?format=image&face=front"
PictureLoader: [card: "Underground Sea" set: "30A"]: following redirect to "https://cards.scryfall.io/large/front/c/b/cbde3041-fb76-4dc8-9cdf-359ad955fd73.jpg?1664926780"
PictureLoader: [card: "Underground Sea" set: "30A"]: Image successfully downloaded from url "https://cards.scryfall.io/large/front/c/b/cbde3041-fb76-4dc8-9cdf-359ad955fd73.jpg?1664926780"
PictureLoader: [card: "Grim Initiate" set: "WAR"]: Trying to fetch picture from url "https://api.scryfall.com/cards/29b6ec9d-3861-48bf-a198-dc7efba5d89c?format=image&face=front"
PictureLoader: [card: "Grim Initiate" set: "WAR"]: following redirect to "https://cards.scryfall.io/large/front/2/9/29b6ec9d-3861-48bf-a198-dc7efba5d89c.jpg?1557576710"
PictureLoader: [card: "Grim Initiate" set: "WAR"]: Image successfully downloaded from url "https://cards.scryfall.io/large/front/2/9/29b6ec9d-3861-48bf-a198-dc7efba5d89c.jpg?1557576710"
PictureLoader: [card: "Easterling Vanguard" set: "LTR"]: Trying to fetch picture from url "https://api.scryfall.com/cards/e860dd40-07c5-47c3-92a8-1ee95a953c2f?format=image&face=front"
PictureLoader: [card: "Easterling Vanguard" set: "LTR"]: following redirect to "https://cards.scryfall.io/large/front/e/8/e860dd40-07c5-47c3-92a8-1ee95a953c2f.jpg?1686968439"
PictureLoader: [card: "Easterling Vanguard" set: "LTR"]: Image successfully downloaded from url "https://cards.scryfall.io/large/front/e/8/e860dd40-07c5-47c3-92a8-1ee95a953c2f.jpg?1686968439"
PictureLoader: [card: "Gollum's Bite" set: "LTR"]: Trying to fetch picture from url "https://api.scryfall.com/cards/1b1e790e-ff82-4888-8aee-9986c646241a?format=image&face=front"
PictureLoader: [card: "Gollum's Bite" set: "LTR"]: following redirect to "https://cards.scryfall.io/large/front/1/b/1b1e790e-ff82-4888-8aee-9986c646241a.jpg?1686968460"
PictureLoader: [card: "Gollum's Bite" set: "LTR"]: Image successfully downloaded from url "https://cards.scryfall.io/large/front/1/b/1b1e790e-ff82-4888-8aee-9986c646241a.jpg?1686968460"
PictureLoader: [card: "Swarming of Moria" set: "LTR"]: Trying to fetch picture from url "https://api.scryfall.com/cards/0a1bd073-4351-4c56-9b07-4430d0d83084?format=image&face=front"
PictureLoader: [card: "Swarming of Moria" set: "LTR"]: following redirect to "https://cards.scryfall.io/large/front/0/a/0a1bd073-4351-4c56-9b07-4430d0d83084.jpg?1686969195"
PictureLoader: [card: "Swarming of Moria" set: "LTR"]: Image successfully downloaded from url "https://cards.scryfall.io/large/front/0/a/0a1bd073-4351-4c56-9b07-4430d0d83084.jpg?1686969195"
PictureLoader: [card: "Exotic Orchard" set: "LCC"]: Trying to fetch picture from url "https://api.scryfall.com/cards/a54b6832-9990-4144-99ef-990a9ad4c081?format=image&face=front"
PictureLoader: [card: "Exotic Orchard" set: "LCC"]: following redirect to "https://cards.scryfall.io/large/front/a/5/a54b6832-9990-4144-99ef-990a9ad4c081.jpg?1698988574"
PictureLoader: [card: "Exotic Orchard" set: "LCC"]: Image successfully downloaded from url "https://cards.scryfall.io/large/front/a/5/a54b6832-9990-4144-99ef-990a9ad4c081.jpg?1698988574"
PictureLoader: [card: "Relentless Advance" set: "WAR"]: Trying to fetch picture from url "https://api.scryfall.com/cards/4258e242-91c6-4b30-86ec-7759705aa97c?format=image&face=front"
PictureLoader: [card: "Relentless Advance" set: "WAR"]: following redirect to "https://cards.scryfall.io/large/front/4/2/4258e242-91c6-4b30-86ec-7759705aa97c.jpg?1557576292"
PictureLoader: [card: "Relentless Advance" set: "WAR"]: Image successfully downloaded from url "https://cards.scryfall.io/large/front/4/2/4258e242-91c6-4b30-86ec-7759705aa97c.jpg?1557576292"
Card Database load status:  0
Server_AbstractUserInterface::playerRemovedFromGame(): gameId = 1
Server_CardZone destructor: "deck"
Server_CardZone destructor: "grave"
Server_CardZone destructor: "hand"
Server_CardZone destructor: "rfg"
Server_CardZone destructor: "sb"
Server_CardZone destructor: "stack"
Server_CardZone destructor: "table"
Server_CardZone destructor: "deck"
Server_CardZone destructor: "grave"
Server_CardZone destructor: "hand"
Server_CardZone destructor: "rfg"
Server_CardZone destructor: "sb"
Server_CardZone destructor: "stack"
Server_CardZone destructor: "table"
Player destructor: "Giocatore 1"
GameScene::removePlayer name= "Giocatore 1"
CardZone destructor:  "deck"
CardZone destructor:  "grave"
CardZone destructor:  "hand"
CardZone destructor:  "rfg"
CardZone destructor:  "sb"
CardZone destructor:  "stack"
CardZone destructor:  "table"
Player destructor: "Giocatore 2"
GameScene::removePlayer name= "Giocatore 2"
CardZone destructor:  "deck"
CardZone destructor:  "grave"
CardZone destructor:  "hand"
CardZone destructor:  "rfg"
CardZone destructor:  "sb"
CardZone destructor:  "stack"
CardZone destructor:  "table"
Server::removeClient: name= "Giocatore 1"
closed session id: 0
Server::removeClient: removed 0x2610bf1f4f0 ; 1 clients;  1 users left
Server_AbstractUserInterface::playerRemovedFromGame(): gameId = 1
Server::removeClient: name= "Giocatore 2"
closed session id: 0
Server::removeClient: removed 0x2610bf1f970 ; 0 clients;  0 users left
Server_Room destructor
Server_Game destructor: gameId= 1

_______________________________________________________________________________________

When using the new function to automatically cascade it doesn't work properly. I did a few tests to see it in action and all were not cascading properly.

_______________________________________________________________________________________

Here is what I did to notice this bug:
1) reveal top cards until "land" is revealed. It revealed two consecutive lands instead of one.
2) reveal top cards until "4 lands" are revealed. It reveald the entire deck.
3) reveal top cards until "creature" is revealed. Same result as #2, all deck revealed
4) take  top cards until "instant" is revealed. For the third time it revealed the entire deck

**Comment by ebbit1q** [comment]
you seem to misunderstand how the reveal until function works, it does not interpret the value entered as a type, it does not take amounts, instead it interprets your entry the same way as the deck editor's search bar does.

to search for a land enter `t:land`, searching for land searches for a card with the text `land` in the name, eg `island` would match. there is no option to search for 4 lands, you'll have to do the action 4 times.
