### ISSUE TITLE
Display issue in log when using translations

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#4943]
**System Information:**
Client Version: 2.9.0-custom(9cbb905) (2023-11-17)
Client Operating System: Windows 11 Version 22H2
Build Architecture: 64-bit
Qt Version: 6.5.3
System Locale: en_DE
Install Mode: Standard

_______________________________________________________________________________________

When not using English language, card names are not always properly separated in the logs. For certain actions, there is no space after the card name and the zone it's going:
<img width="214" alt="image" src="https://github.com/Cockatrice/Cockatrice/assets/9874850/f6782c8a-0037-4618-8952-6968ced3419f"><br>
<img width="215" alt="image" src="https://github.com/Cockatrice/Cockatrice/assets/9874850/56a1e07f-4c20-4ec9-8994-be7952304722">

_______________________________________________________________________________________

**Steps to reproduce:**
 - Select EN
 - Move cards around zones
 - Select GER
 - Move cards around zones

**Comment by ebbit1q** [comment]
this isn't some bug, this is because the translation is not including the space:
```xml
    <message> 
        <location filename="src/messagelogwidget.cpp" line="81"/>
        <source> from their hand</source>
        <translation>von ihrer Hand</translation>
    </message>
```

**Comment by tooomm** [comment]
Smart to also look into the translation files! I did only check Transifex... and indeed, it's barely visible there. That's obviously an issue for translators:
<img width="756" alt="image" src="https://github.com/Cockatrice/Cockatrice/assets/9874850/a84f1eef-89c5-41dc-9f07-35aae87c5c0e">
<br><br>
<img width="755" alt="image" src="https://github.com/Cockatrice/Cockatrice/assets/9874850/41c8c965-3594-4cc4-b075-0260a4736295">

This looks like a problem which requires a fix in the code. We do not want to have leading or trailing blanks in our source strings and make life for translators difficult, or make people complain about the log as a result of somebody not copying the space into the translation as well.

I tried a fix in https://github.com/Cockatrice/Cockatrice/pull/4945. It did not solve the issue for me, but it could be related to the source and translation files now being out of sync.
Would be happy if you can have a look and let me know what you think!
