### ISSUE TITLE
holding the shift key while attempting to join game results in "this game is only open to registered users" error

### ISSUE THREAD

**Issue by unferth** [Cockatrice/Cockatrice#4947]
**System Information:**

windows
cockatrice ver 2.9.0 (2023-9-14)

_______________________________________________________________________________________

minor bug

_______________________________________________________________________________________

**Steps to reproduce:**
login to rooster ranges
select a game to join
hold shift key and click join game

**Comment by ebbit1q** [comment]
this is not a bug, holding shift enters the game in "judge mode" if you are not a judge this will result in an error
