### ISSUE TITLE
Convert decklist to custom set

### ISSUE THREAD

**Issue by MotherofRuins** [Cockatrice/Cockatrice#4954]
Problem: Many people want to use deck editor filters on their decks, say to count how many of a particular creature type are present.  Cockatrice position has been that there are many deck editors available so understandably not willing to add that functionality.

Solution:  Custom sets.  If a player could convert their decklist into a custom set they could load it in deck editor and have all the functionality for what may be comparatively little effort.  

I'm going to look into how to manually convert, but a Menu item Save Deck as Custom Set could be nice.

See also:
https://github.com/Cockatrice/Cockatrice/issues/3741
https://github.com/Cockatrice/Cockatrice/issues/4949
https://github.com/Cockatrice/Cockatrice/issues/4869

**Comment by ebbit1q** [comment]
this sounds like a workaround that is not very intuitive for users, I'd rather commit to rewriting the decklist widget (the way it is written rn is very inflexible)

**Comment by MotherofRuins** [comment]
That'd be fine.
