### ISSUE TITLE
Cards from Jurassic World Collection and Lost Caverns of Ixalan Commander sets not showing in card search results

### ISSUE THREAD

**Issue by danielbrown95** [Cockatrice/Cockatrice#4957]
**System Information:**
Client Version: 2.8.0 (2021-01-26)
---------------------------------------------------------------------------
Theme changed: "DarkMingo-Theme-for-Cockatrice-1.2"
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
Language changed: ""
main(): starting main program
main(): MainWindow constructor finished
main(): ui.show() finished
Startup: old client version "2.9.0 (2023-09-14)" differs, assuming first start after update
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
PictureLoader: cache fail for "_trice_card_back_232286"
libpng warning: iCCP: known incorrect sRGB profile
Spoiler Service Online
Data Hash = "\xB4\xFA\x00\x9C\xFF\xBE\xE4\xF7\x00H\x16\xEE\xF6O\xB7\xA9"
File Hash = "\xB4\xFA\x00\x9C\xFF\xBE\xE4\xF7\x00H\x16\xEE\xF6O\xB7\xA9"
Spoilers Up to Date
CardDatabase::loadCardDatabases start
[CockatriceXml4Parser] Trying to parse:  "C:/Users/Dan/AppData/Local/Cockatrice/Cockatrice/cards.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Dan/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 28345 Sets= 731
[CockatriceXml4Parser] Trying to parse:  "C:/Users/Dan/AppData/Local/Cockatrice/Cockatrice/tokens.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Dan/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 29120 Sets= 731
[CockatriceXml4Parser] Trying to parse:  "C:/Users/Dan/AppData/Local/Cockatrice/Cockatrice/spoiler.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Dan/AppData/Local/Cockatrice/Cockatrice/spoiler.xml" Status = 0 Cards = 29120 Sets= 737
CardDatabase::loadCardDatabases success
PictureLoader: [card:  "\"Ach! Hans, Run!\""  set:  "UNH" ]: Trying to load picture
PictureLoader: [card:  "Ach! Hans, Run!"  set:  "UNH" ]: Picture found on disk.
PictureLoader: [card:  "\"Brims\" Barone, Midway Mobster"  set:  "UNF" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "\"Brims\" Barone, Midway Mobster"  set:  "UNF" ]: Requested set property ( "muid" ) for Url template ( "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "\"Brims\" Barone, Midway Mobster"  set:  "UNF" ]: Trying to load picture
PictureLoader: [card:  "Brims Barone, Midway Mobster"  set:  "UNF" ]: Picture found on disk.
PictureLoader: [card:  "\"Rumors of My Death . . .\""  set:  "UST" ]: Trying to load picture
PictureLoader: [card:  "Rumors of My Death . . ."  set:  "UST" ]: Picture found on disk.
PictureLoader: [card:  "_____ Bird Gets the Worm"  set:  "UNF" ]: Trying to load picture
PictureLoader: [card:  "_____ Bird Gets the Worm"  set:  "UNF" ]: Picture found on disk.
PictureLoader: [card:  "Acolyte of the Inferno"  set:  "ORI" ]: Trying to load picture
PictureLoader: [card:  "Acolyte of the Inferno"  set:  "ORI" ]: Picture found on disk.
PictureLoader: [card:  "Adeliz, the Cinder Wind"  set:  "PLIST" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Adeliz, the Cinder Wind"  set:  "PLIST" ]: Requested set property ( "muid" ) for Url template ( "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Adeliz, the Cinder Wind"  set:  "PLIST" ]: Trying to load picture
PictureLoader: [card:  "Adeliz, the Cinder Wind"  set:  "PLIST" ]: Picture found on disk.
PictureLoader: [card:  "Desert of the Indomitable"  set:  "AKR" ]: Trying to load picture
PictureLoader: [card:  "Desert of the Indomitable"  set:  "AKR" ]: Picture found on disk.
PictureLoader: [card:  "Anthousa, Setessan Hero"  set:  "THS" ]: Trying to load picture
PictureLoader: [card:  "Anthousa, Setessan Hero"  set:  "THS" ]: Picture found on disk.
PictureLoader: [card:  "Command Tower"  set:  "40K" ]: Trying to load picture
PictureLoader: [card:  "Command Tower"  set:  "40K" ]: Picture found on disk.
PictureLoader: [card:  "Dinosaur Token"  set:  "XLN" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Dinosaur Token"  set:  "XLN" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Dinosaur Token"  set:  "XLN" ]: Requested set property ( "muid" ) for Url template ( "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Dinosaur Token"  set:  "XLN" ]: Trying to load picture
PictureLoader: [card:  "Dinosaur Token"  set:  "XLN" ]: Picture found on disk.
PictureLoader: [card:  "Forest"  set:  "J22" ]: Trying to load picture
PictureLoader: [card:  "Forest"  set:  "J22" ]: Picture found on disk.
PictureLoader: [card:  "Island"  set:  "OLEP" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Island"  set:  "OLEP" ]: Requested set property ( "muid" ) for Url template ( "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Island"  set:  "OLEP" ]: Trying to load picture
PictureLoader: [card:  "Island"  set:  "OLEP" ]: Picture found on disk.
PictureLoader: [card:  "Mountain"  set:  "BRO" ]: Trying to load picture
PictureLoader: [card:  "Mountain"  set:  "BRO" ]: Picture not found on disk, trying to download
PictureLoader: [card:  "Mountain"  set:  "BRO" ]: Trying to download picture from url: "https://api.scryfall.com/cards/95083e1d-faf5-40e4-9be5-909cd01cc2b5?format=image&face=front"
PictureLoader: [card:  "Mountain"  set:  "BRO" ]: following redirect: "https://cards.scryfall.io/large/front/9/5/95083e1d-faf5-40e4-9be5-909cd01cc2b5.jpg?1674422289"
PictureLoader: [card:  "Mountain"  set:  "BRO" ]: Image successfully downloaded from  "https://cards.scryfall.io/large/front/9/5/95083e1d-faf5-40e4-9be5-909cd01cc2b5.jpg?1674422289"
PictureLoader: [card:  "Plains"  set:  "BRO" ]: Trying to load picture
PictureLoader: [card:  "Plains"  set:  "BRO" ]: Picture found on disk.
PictureLoader: [card:  "Swamp"  set:  "BRO" ]: Trying to load picture
PictureLoader: [card:  "Swamp"  set:  "BRO" ]: Picture found on disk.
PictureLoader: [card:  "Treasure Token"  set:  "CLB" ]: Requested property ( "side" ) for Url template ( "https://api.scryfall.com/cards/!set:uuid!?format=image&face=!prop:side!" ) is not available
PictureLoader: [card:  "Treasure Token"  set:  "CLB" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Treasure Token"  set:  "CLB" ]: Requested set property ( "muid" ) for Url template ( "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Treasure Token"  set:  "CLB" ]: Trying to load picture
PictureLoader: [card:  "Treasure Token"  set:  "CLB" ]: Picture found on disk.
PictureLoader: [card:  "Abaddon the Despoiler"  set:  "40K" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Abaddon the Despoiler"  set:  "40K" ]: Requested set property ( "muid" ) for Url template ( "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Abaddon the Despoiler"  set:  "40K" ]: Trying to load picture
PictureLoader: [card:  "Abaddon the Despoiler"  set:  "40K" ]: Picture found on disk.
CardDatabase::loadCardDatabases start
[CockatriceXml4Parser] Trying to parse:  "C:/Users/Dan/AppData/Local/Cockatrice/Cockatrice/cards.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Dan/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 28345 Sets= 731
[CockatriceXml4Parser] Trying to parse:  "C:/Users/Dan/AppData/Local/Cockatrice/Cockatrice/tokens.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Dan/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 29120 Sets= 731
[CockatriceXml4Parser] Trying to parse:  "C:/Users/Dan/AppData/Local/Cockatrice/Cockatrice/spoiler.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Dan/AppData/Local/Cockatrice/Cockatrice/spoiler.xml" Status = 0 Cards = 29120 Sets= 737
CardDatabase::loadCardDatabases success
PictureLoader: [card:  "_____"  set:  "UNH" ]: Trying to load picture
PictureLoader: [card:  "_____"  set:  "UNH" ]: Picture found on disk.
PictureLoader: [card:  "\"Ach! Hans, Run!\""  set:  "UNH" ]: Trying to load picture
PictureLoader: [card:  "Ach! Hans, Run!"  set:  "UNH" ]: Picture found on disk.
PictureLoader: [card:  "\"Brims\" Barone, Midway Mobster"  set:  "UNF" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "\"Brims\" Barone, Midway Mobster"  set:  "UNF" ]: Requested set property ( "muid" ) for Url template ( "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "\"Brims\" Barone, Midway Mobster"  set:  "UNF" ]: Trying to load picture
PictureLoader: [card:  "Brims Barone, Midway Mobster"  set:  "UNF" ]: Picture found on disk.
PictureLoader: [card:  "_____ Bird Gets the Worm"  set:  "UNF" ]: Trying to load picture
PictureLoader: [card:  "_____ Bird Gets the Worm"  set:  "UNF" ]: Picture found on disk.
PictureLoader: [card:  "Acolyte of the Inferno"  set:  "ORI" ]: Trying to load picture
PictureLoader: [card:  "Acolyte of the Inferno"  set:  "ORI" ]: Picture found on disk.
PictureLoader: [card:  "Adeliz, the Cinder Wind"  set:  "PLIST" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Adeliz, the Cinder Wind"  set:  "PLIST" ]: Requested set property ( "muid" ) for Url template ( "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Adeliz, the Cinder Wind"  set:  "PLIST" ]: Trying to load picture
PictureLoader: [card:  "Adeliz, the Cinder Wind"  set:  "PLIST" ]: Picture found on disk.
PictureLoader: [card:  "Desert of the Indomitable"  set:  "AKR" ]: Trying to load picture
PictureLoader: [card:  "Desert of the Indomitable"  set:  "AKR" ]: Picture found on disk.
PictureLoader: [card:  "Anthousa, Setessan Hero"  set:  "THS" ]: Trying to load picture
PictureLoader: [card:  "Anthousa, Setessan Hero"  set:  "THS" ]: Picture found on disk.
PictureLoader: [card:  "_____ Bird Gets the Worm"  set:  "UNF" ]: Trying to load picture
PictureLoader: [card:  "_____ Bird Gets the Worm"  set:  "UNF" ]: Picture found on disk.
PictureLoader: [card:  "Acolyte of the Inferno"  set:  "ORI" ]: Trying to load picture
PictureLoader: [card:  "Acolyte of the Inferno"  set:  "ORI" ]: Picture found on disk.
PictureLoader: [card:  "Adeliz, the Cinder Wind"  set:  "PLIST" ]: Requested set property ( "muid" ) for Url template ( "https://api.scryfall.com/cards/multiverse/!set:muid!?format=image" ) is not available
PictureLoader: [card:  "Adeliz, the Cinder Wind"  set:  "PLIST" ]: Requested set property ( "muid" ) for Url template ( "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card" ) is not available
PictureLoader: [card:  "Adeliz, the Cinder Wind"  set:  "PLIST" ]: Trying to load picture
PictureLoader: [card:  "Adeliz, the Cinder Wind"  set:  "PLIST" ]: Picture found on disk.
PictureLoader: [card:  "Desert of the Indomitable"  set:  "AKR" ]: Trying to load picture
PictureLoader: [card:  "Desert of the Indomitable"  set:  "AKR" ]: Picture found on disk.

_______________________________________________________________________________________

When searching for the below cards from the Jurassic World Collection and The Lost Caverns of Ixalan Commander sets the cards do not show in the search results.

 - The Indomitable
 - Indominus Rex, Alpha

Have updated Cockatrice to v2.9.0 and updated card client to the latest versions and the cards still don't show. Have spoken with and screen shared with friends who use Cockatrice who are on version v2.8.0 and latest card update who have both cards show on their search results.

I have uninstalled Cockatrice and reinstalled v.2.8.0 to be on the same version as them and the cards do not show on my search results.

I have also tried searching the sets for these cards and still they do not show the cards in the search results.
_______________________________________________________________________________________

**Steps to reproduce:**
 - On Deck tab, search for the card, The Indomitable - Card does not show in card results
 - On Deck tab, search for the card, Indominus Rex, Alpha - Card does not show in card results

**Comment by ebbit1q** [comment]
after updating your card database you are prompted whether or not you want to enable the new cards, if you select no here the cards will not show up in the deck editor, to enable them again go to card database>set manager and enable all sets or select the sets you'd like enabled. the set manager is the primary way to manage what cards are available and which art they use.
