### ISSUE TITLE
Oracle window glitched and buttons not visible

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#4968]
**System Information:**
Client Version: 2.9.0-custom(1716801) (2023-12-15)
Client Operating System: Windows 11 Version 22H2
Build Architecture: 64-bit
Qt Version: 6.5.3
System Locale: en_DE
Install Mode: Standard

_______________________________________________________________________________________

Buttons in Oracle are no longer visible (Ok, Cancel?), also the dialog window controls only partially:
<img width="399" alt="image" src="https://github.com/Cockatrice/Cockatrice/assets/9874850/7769d1c0-fb5e-4304-8e02-c98ffb88a3c3">
Screenshot is taking on a smaller laptop screen with full HD resolution and 150% scaling.
Changing the scaling to 100% and restarting the app does not change the result.
I do get a different visual result (still broken) on an external monitor (also full HD, 100% scaling).

I'm not having this on the Win 7 (64Bit) build which still uses Qt5, so I'm thinking it could be a Qt6 issue (Windows only?). 
Is this a problem on other operating systems as well?
I'm seeing this for a while now...
Other windows in Cockatrice itself (like Manage Sets, About, Tip of the Day, Debug Log) are fine.

**Comment by ZeldaZach** [comment]
Seems to be an issue between Qt 6.5.3 and 6.6 on Windows and Linux.
