### ISSUE TITLE
Adding a new translation (Korean)

### ISSUE THREAD

**Issue by ideocl4st** [Cockatrice/Cockatrice#497]
While Cockatrice has many languages available, Korean wasn't one of them - So I've been looking at .ts files to see if I can translate it.

But judging from strings, it looks as if available languages are hard-coded into the client.

Will it be difficult to add another language into Cockatrice? Or rather, what would I need to implement Korean translation (Other than having a translated .ts file)?

**Comment by ctrlaltca** [comment]
#500 has been merged, feel free to open your PR

**Comment by ideocl4st** [comment]
@ctrlaltca Thank you. I'll do it as soon as I'm done going over it one last time.

One last thing before I open the pull request : Is it okay if I add my name in About Cockatrice dialog?

**Comment by Daenyth** [comment]
Sure

**Comment by ZeldaZach** [comment]
In all languages it seems like "Chat Room" is never translated :(

**Comment by ideocl4st** [comment]
@ZeldaZach That was because name of "Chat Room" is set by the server. We can't translate what the server decided to name its chat room :P

**Comment by ZeldaZach** [comment]
Seems legit @woogerboy21

**Comment by ctrlaltca** [comment]
committed as 471a690cf04acf3a5a012dc8420253bbd360ba5f
