### ISSUE TITLE
Cockatrice on Linux/Chromebook crash on Startup

### ISSUE THREAD

**Issue by Koobie88** [Cockatrice/Cockatrice#4971]
**System Information:** (Copied from chrome://system, if incorrect or different info is needed, please let me know)
[CHROME VERSION](https://chromium.googlesource.com/chromiumos/platform2/+/HEAD/debugd/docs/log_entries.md#CHROME%20VERSION)
119.0.6045.212
[CHROMEOS_ARC_ANDROID_SDK_VERSION](https://chromium.googlesource.com/chromiumos/platform2/+/HEAD/debugd/docs/log_entries.md#CHROMEOS_ARC_ANDROID_SDK_VERSION)
30
[CHROMEOS_ARC_DPC_VERSION](https://chromium.googlesource.com/chromiumos/platform2/+/HEAD/debugd/docs/log_entries.md#CHROMEOS_ARC_DPC_VERSION)
[CHROMEOS_ARC_POLICY](https://chromium.googlesource.com/chromiumos/platform2/+/HEAD/debugd/docs/log_entries.md#CHROMEOS_ARC_POLICY)
[CHROMEOS_ARC_POLICY_COMPLIANCE_REPORT](https://chromium.googlesource.com/chromiumos/platform2/+/HEAD/debugd/docs/log_entries.md#CHROMEOS_ARC_POLICY_COMPLIANCE_REPORT)
[CHROMEOS_ARC_STATUS](https://chromium.googlesource.com/chromiumos/platform2/+/HEAD/debugd/docs/log_entries.md#CHROMEOS_ARC_STATUS)
enabled
[CHROMEOS_ARC_VERSION](https://chromium.googlesource.com/chromiumos/platform2/+/HEAD/debugd/docs/log_entries.md#CHROMEOS_ARC_VERSION)
11189745
[CHROMEOS_AUSERVER](https://chromium.googlesource.com/chromiumos/platform2/+/HEAD/debugd/docs/log_entries.md#CHROMEOS_AUSERVER)
https://tools.google.com/service/update2
[CHROMEOS_BLUETOOTH_FLOSS](https://chromium.googlesource.com/chromiumos/platform2/+/HEAD/debugd/docs/log_entries.md#CHROMEOS_BLUETOOTH_FLOSS)
disabled
[CHROMEOS_BOARD_APPID](https://chromium.googlesource.com/chromiumos/platform2/+/HEAD/debugd/docs/log_entries.md#CHROMEOS_BOARD_APPID)
{BA7092E6-2B09-4620-BBB0-FAA34397F3F8}
[CHROMEOS_CANARY_APPID](https://chromium.googlesource.com/chromiumos/platform2/+/HEAD/debugd/docs/log_entries.md#CHROMEOS_CANARY_APPID)
{90F229CE-83E2-4FAF-8479-E368A34938B1}
[CHROMEOS_DEVSERVER](https://chromium.googlesource.com/chromiumos/platform2/+/HEAD/debugd/docs/log_entries.md#CHROMEOS_DEVSERVER)
[CHROMEOS_FIRMWARE_VERSION](https://chromium.googlesource.com/chromiumos/platform2/+/HEAD/debugd/docs/log_entries.md#CHROMEOS_FIRMWARE_VERSION)
Google_Fennel.12573.380.0
[CHROMEOS_RELEASE_APPID](https://chromium.googlesource.com/chromiumos/platform2/+/HEAD/debugd/docs/log_entries.md#CHROMEOS_RELEASE_APPID)
{BA7092E6-2B09-4620-BBB0-FAA34397F3F8}
[CHROMEOS_RELEASE_BOARD](https://chromium.googlesource.com/chromiumos/platform2/+/HEAD/debugd/docs/log_entries.md#CHROMEOS_RELEASE_BOARD)
jacuzzi-signed-mp-v13keys
[CHROMEOS_RELEASE_BRANCH_NUMBER](https://chromium.googlesource.com/chromiumos/platform2/+/HEAD/debugd/docs/log_entries.md#CHROMEOS_RELEASE_BRANCH_NUMBER)
69
[CHROMEOS_RELEASE_BUILDER_PATH](https://chromium.googlesource.com/chromiumos/platform2/+/HEAD/debugd/docs/log_entries.md#CHROMEOS_RELEASE_BUILDER_PATH)
jacuzzi-release/R119-15633.69.0
[CHROMEOS_RELEASE_BUILD_NUMBER](https://chromium.googlesource.com/chromiumos/platform2/+/HEAD/debugd/docs/log_entries.md#CHROMEOS_RELEASE_BUILD_NUMBER)
15633
[CHROMEOS_RELEASE_BUILD_TYPE](https://chromium.googlesource.com/chromiumos/platform2/+/HEAD/debugd/docs/log_entries.md#CHROMEOS_RELEASE_BUILD_TYPE)
Official Build
[CHROMEOS_RELEASE_CHROME_MILESTONE](https://chromium.googlesource.com/chromiumos/platform2/+/HEAD/debugd/docs/log_entries.md#CHROMEOS_RELEASE_CHROME_MILESTONE)
119
[CHROMEOS_RELEASE_DESCRIPTION](https://chromium.googlesource.com/chromiumos/platform2/+/HEAD/debugd/docs/log_entries.md#CHROMEOS_RELEASE_DESCRIPTION)
15633.69.0 (Official Build) stable-channel jacuzzi 
[CHROMEOS_RELEASE_KEYSET](https://chromium.googlesource.com/chromiumos/platform2/+/HEAD/debugd/docs/log_entries.md#CHROMEOS_RELEASE_KEYSET)
mp-v13
[CHROMEOS_RELEASE_NAME](https://chromium.googlesource.com/chromiumos/platform2/+/HEAD/debugd/docs/log_entries.md#CHROMEOS_RELEASE_NAME)
Chrome OS
[CHROMEOS_RELEASE_PATCH_NUMBER](https://chromium.googlesource.com/chromiumos/platform2/+/HEAD/debugd/docs/log_entries.md#CHROMEOS_RELEASE_PATCH_NUMBER)
0
[CHROMEOS_RELEASE_TRACK](https://chromium.googlesource.com/chromiumos/platform2/+/HEAD/debugd/docs/log_entries.md#CHROMEOS_RELEASE_TRACK)
stable-channel
[CHROMEOS_RELEASE_UNIBUILD](https://chromium.googlesource.com/chromiumos/platform2/+/HEAD/debugd/docs/log_entries.md#CHROMEOS_RELEASE_UNIBUILD)
1
[CHROMEOS_RELEASE_VERSION](https://chromium.googlesource.com/chromiumos/platform2/+/HEAD/debugd/docs/log_entries.md#CHROMEOS_RELEASE_VERSION)
15633.69.0

_______________________________________________________________________________________

After installing Cockatrice using the flatpak guide on Linux for Chromebook, I have been unable to fully launch the program. The install went successfully, but crashes everytime I launch the program. Opening the program causes the pop-up "Cockatrice is unable to load the card database. Do you want to update your database now?" Clicking yes, no, or Open settings leads to an immediate crash of the program. The guide for updating the database presents fixes, but I am unable to get past this pop-up and get into Cockatrice itself to manually input the database. I'm not super well versed in Linux, but any help would be greatly appreciated. If more info is required, please reach out and let me know.

_______________________________________________________________________________________

**Steps to reproduce:**
A. Launch Cockatrice
B. Answer Card Database Update Prompt
C. Crash

**Comment by ebbit1q** [comment]
the crash while the updater is running is related to a lack of memory, how much ram does your machine have and have you tried closing other applications first? have you tried runninh oracle without starting cockatrice?

**Comment by Koobie88** [comment]
The total RAM says just under 4GB, but even with everything closed the free RAM is under 1GB. How would I go about running oracle? Via the Linux terminal?

**Comment by ebbit1q** [comment]
I think because it's flatpak it only creates a desktop link for the main app and not for oracle, you'd be able to run it from the linux terminal using flatpak run --command=oracle io.github.cockatrice.cockatrice if I recall correctly

**Comment by Koobie88** [comment]
"error: app/io.github.cockatrice.cockatrice/aarch64/master not installed"

This popped up when I entered what you typed.

**Comment by ebbit1q** [comment]
ah maybe try flatpak --user run --command=oracle io.github.cockatrice.cockatrice

**Comment by ZeldaZach** [comment]
If you're still having an issue, please feel free to re-open and let us know!

**Comment by deathboss-gloop** [comment]
so I'm attempting to run the program cockatrice on my chromebook Asus, I'm currently using linex to do so. I've gotten through most of the steps until running into two issues. 
1. flatpak remote-add --if-not-exists flathub https://flathub.org
2. after using that this error populates : Flatpak system operation ConfigureRemote not allowed for user
3. thought well I'll try to go to the next step and attempted doing step 4
4.  flatpak install flathub io.github.cockatrice.cockatrice
5. error  No remote refs found for ‘flathub’
6.  next command was : flatpak run io.github.cockatrice.cockatrice
7. error app/io.github.cockatrice.cockatrice/x86_64/master not installed
8. did an alternate command to the prior :  flatpak --user run --command=oracle io.github.cockatrice.cockatrice
9. error app/io.github.cockatrice.cockatrice/x86_64/master not installed

so I'm lost what to do, I've gone through multiple paths and step by steps and nothing has gotten myself past these errors.

**Comment by ebbit1q** [comment]
please create a new topic for your issue or ask for direct support on our discord

**Comment by lomcharsceynicaecklayanmaiecnay** [comment]
Em qua., 1 de abr. de 2026 10:32, ebbit1q ***@***.***>
escreveu:

**Comment by lomcharsceynicaecklayanmaiecnay** [comment]
Em dom., 15 de mar. de 2026 01:48, Ubiquiti Updates ***@***.***>
escreveu:

> Ubiquiti Updates is an unmonitored inbox. Please visit our website at
> https://ui.com/.
>
>
> For product support, please visit https://account.ui.com/mysupport and
> https://help.ui.com/. Or, visit our Community at
> https://community.ui.com/.
>
>
> For sales, please visit https://design.ui.com/ or, for large
> deployments, https://experts.ui.com/.
>
>
> This is an automatically generated Delivery Status Notification.
> Please do not reply to this e-mail.
>
