### ISSUE TITLE
CI: macOS 10.15 builds failing when installing protobuf dependencies

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#5007]
```
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/2to3-3.11
Target /usr/local/bin/2to3-3.11
already exists. You may want to remove it:
  rm '/usr/local/bin/2to3-3.11'
...
```

More information can be found in #4986 where @candyapplecorn tried to fix this already.

In general this could be related to #4924 and others where we had issues already with protobuf builds no longer being available for older macOS versions on homebrew.

**Comment by njelich** [comment]
When facing this, I fixed it in an ugly way.

https://github.com/njelich/casr/blob/85b12249b5051464328a760318300e311b6c6769/.github/workflows/darwin-i386.yml#L20

**Comment by tooomm** [comment]
Thanks for pointing this out and providing the input, @njelich!
Reopened #4986 and implemented your suggestion. I also needed to remove Python 3.11 in our case.

I guess that's good enough of an workaround for now, hopefully we get rid of such old builds sooner than later. As long as homebrew has support, it's quite convenient.

Result of the workaround:
- `homebrew` step in question completes now
-  But Qt installation after does not...
