### ISSUE TITLE
Power and toughness not automatically set anymore

### ISSUE THREAD

**Issue by Lynn9289** [Cockatrice/Cockatrice#5016]
**System Information:**

_______________________________________________________________________________________

Whenever I play a creature card, the power and toughness of the card are not automatically set. This isn't a big deal, but I'd like for it to be how it used to be, and not have to tick up the counters every single time I play a creature. Tokens that come into play still have power and toughness though. Another issue that I've had is cards that have a backside such as battles. I'm not sure how to access their backside.

_______________________________________________________________________________________

**Steps to reproduce:**
 - Do A
 - Do B
 - Do C ...

**Comment by ebbit1q** [comment]
this would mean your card database is missing or incomplete, run the updater (oracle) at help>check for card updates, make sure it is using the default url and is the current version 2.9.0

**Comment by Lynn9289** [comment]
> this would mean your card database is missing or incomplete, run the updater (oracle) at help>check for card updates, make sure it is using the default url and is the current version 2.9.0

I tried that. It used the default url and said 2.9.0, but it still isn't working.

**Comment by ebbit1q** [comment]
did you change the card database location in cockatrice's settings or in oracle?

**Comment by Lynn9289** [comment]
> did you change the card database location in cockatrice's settings or in oracle?

No I havent messed with any of that stuff

**Comment by ebbit1q** [comment]
please provide the debug log on startup the way the new ticket template instructed

**Comment by Lynn9289** [comment]
> please provide the debug log on startup the way the new ticket template instructed

Client Version: 2.9.0 (2023-09-14)
Client Operating System: Windows 11 Version 2009
Build Architecture: 64-bit
Qt Version: 6.3.2
System Locale: en_US
Install Mode: Standard
---------------------------------------------------------------------------
Theme changed: "Leather"
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
Unable to load qt translation "qt_" at "C:/Program Files/Cockatrice/Resources/translations"
Unable to load "cockatrice" translation "cockatrice_" at "C:/Program Files/Cockatrice/translations"
main(): starting main program
main(): MainWindow constructor finished
Spoilers Disabled
main(): ui.show() finished
Startup: found config with current version
CardDatabase::loadCardDatabases start
[CockatriceXml4Parser] Trying to parse:  "C:/Users/Dahli/AppData/Local/Cockatrice/Cockatrice/cards.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
PictureLoader: cache fail for "_trice_card_back_226278"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Dahli/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 793 Sets = 185 "53ms"
[CockatriceXml4Parser] Trying to parse:  "C:/Users/Dahli/AppData/Local/Cockatrice/Cockatrice/cards.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Dahli/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 793 Sets = 185 "51ms"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Dahli/AppData/Local/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 793 Sets = 185 "0ms"
Loading Custom Set 0 ( "C:/Users/Dahli/AppData/Local/Cockatrice/Cockatrice/customsets/TK.xml" )
[CockatriceXml4Parser] Trying to parse:  "C:/Users/Dahli/AppData/Local/Cockatrice/Cockatrice/customsets/TK.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Dahli/AppData/Local/Cockatrice/Cockatrice/customsets/TK.xml" Status = 0 Cards = 793 Sets = 186 "0ms"
CardDatabase::loadCardDatabases success

**Comment by ebbit1q** [comment]
in your log it shows your cards.xml path is not changed but the tokens.xml path has been misconfigured to overwrite the main cards.xml, to fix this go to the settings in cockatrice and click reset all paths, then run the card updater again and make sure save to a custom path is not checked when downloading tokens

**Comment by Lynn9289** [comment]
> in your log it shows your cards.xml path is not changed but the tokens.xml path has been misconfigured to overwrite the main cards.xml, to fix this go to the settings in cockatrice and click reset all paths, then run the card updater again and make sure save to a custom path is not checked when downloading tokens

This worked like a charm. Thanks so much for the help, I really appreciate it.

**Comment by ebbit1q** [comment]
you're welcome
