### ISSUE TITLE
Servatrice is losing database connection after some time

### ISSUE THREAD

**Issue by janpfischer** [Cockatrice/Cockatrice#5022]
Servatrice build upon master using the Docker file.

_______________________________________________________________________________________

I've running servatrice inside a container inside my kubernetes cluster. This is running fine and I have no issues once the server is running. 
I have a second service running mysql in the cluster. The services communicate via an internal DNS name over network (inside the same VM).
The database connection can be established and is working without issues. However after about 1 day I can't login anymore. When I try to login with Cockatrice I get the message that I would have to register an user (which I already have). When I just try to register the same user again I get an error message that the communication with the server is faulty. 

Servatrice is logging this: 

```
	2024-04-23 19:15:59.963	
Tue Apr 23 17:15:59 2024 "[pool 999] Error executing query: MySQL server has gone away QMYSQL: Unable to execute query"
2024-04-23 19:15:59.962	
Tue Apr 23 17:15:59 2024 Failed to insert user:  QSqlError("2006", "QMYSQL: Unable to execute query", "MySQL server has gone away")  sql:  "insert into cockatrice_users (name, realname, password_sha512, email, country, registrationDate, active, token, admin, avatar_bmp, clientid, privlevel, privlevelStartDate, privlevelEndDate) values (:userName, :realName, :password_sha512, :email, :country, UTC_TIMESTAMP(), :active, :token, 0, '', '', 'NONE', UTC_TIMESTAMP(), UTC_TIMESTAMP())"
2024-04-23 19:15:59.962	
Tue Apr 23 17:15:59 2024 "[pool 999] Error executing query: MySQL server has gone away QMYSQL: Unable to execute query"
2024-04-23 19:15:59.962	
Tue Apr 23 17:15:59 2024 Id ban check failed: SQL error. QSqlError("2006", "QMYSQL: Unable to execute query", "MySQL server has gone away")
2024-04-23 19:15:59.962	
Tue Apr 23 17:15:59 2024 "[pool 999] Error executing query: MySQL server has gone away QMYSQL: Unable to execute query"
2024-04-23 19:15:59.962	
Tue Apr 23 17:15:59 2024 Name ban check failed: SQL error QSqlError("2006", "QMYSQL: Unable to execute query", "MySQL server has gone away")
2024-04-23 19:15:59.961	
Tue Apr 23 17:15:59 2024 "[pool 999] Error executing query: MySQL server has gone away QMYSQL: Unable to execute query"
2024-04-23 19:15:59.961	
Tue Apr 23 17:15:59 2024 IP ban check failed: SQL error. QSqlError("2006", "QMYSQL: Unable to execute query", "MySQL server has gone away")
2024-04-23 19:15:59.961	
Tue Apr 23 17:15:59 2024 "[pool 999] Error executing query: MySQL server has gone away QMYSQL: Unable to execute query"
2024-04-23 19:15:59.961	
Tue Apr 23 17:15:59 2024 "[pool 999] Error executing query: MySQL server has gone away QMYSQL: Unable to execute query"
2024-04-23 19:15:59.961	
Tue Apr 23 17:15:59 2024 Got register command for user: "xxx"
```

If I restart servatrice (not mysql) everything is working again. I've tried mysql version 5 and 8. 
Seems like if servatrice is losing the connection to the database it does not re-establish it by it's own. A restart is needed. 
_______________________________________________________________________________________

**Comment by ebbit1q** [comment]
is strict mode off on mysql?

**Comment by janpfischer** [comment]
I did not have disabled strict mode. I've done it now and verified that "STRICT_TRANS_TABLES" is not active anymore. SQL_MODE was initialized empty now. 
After roughly one day the same error happens again.

**Comment by janpfischer** [comment]
I did some more testing. I set the wait_timeout to 120 seconds and exactly after 120 seconds servatrice can't establish a new connection to the database. A restart is needed. 
Seems like that the "checkSql" function is not working as it should with newer MYSQL/MariaDB versions. 
For now I applied the following patch to my build and the connection is re-established and I do not need to restart servatrice. 

```
diff --git a/servatrice/src/servatrice_database_interface.cpp b/servatrice/src/servatrice_database_interface.cpp
index ab90eb97..636fdf66 100644
--- a/servatrice/src/servatrice_database_interface.cpp
+++ b/servatrice/src/servatrice_database_interface.cpp
@@ -46,6 +46,7 @@ bool Servatrice_DatabaseInterface::initDatabase(const QString &type,
     sqlDatabase.setDatabaseName(databaseName);
     sqlDatabase.setUserName(userName);
     sqlDatabase.setPassword(password);
+    sqlDatabase.setConnectOptions("MYSQL_OPT_RECONNECT=1");

     return openDatabase();
 }
```

However the following is logged then. So I think it would need a more sufficient solution.
`WARNING: MYSQL_OPT_RECONNECT is deprecated and will be removed in a future version.` (should be logged with MYSQL >= 8.0.35)

**Comment by ebbit1q** [comment]
I'm not sure what is going on there, I don't see it on my end, maybe @ZeldaZach knows something?

Do you maybe know what could be different breaking the normal setup?

**Comment by janpfischer** [comment]
You should be able to reproduce ist with the current main and the docker-compose file like this. 

1. Change docker-compose file to set the wait_timeout
```
diff --git a/docker-compose.yml b/docker-compose.yml
index 7cef0ffe..f29acb66 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -3,20 +3,22 @@ version: '3'
 services:
   mysql:
     image: mysql
-    command: --sql_mode=
+    command: --sql_mode= --wait_timeout=120
```
2. Use the following minimal servatrice configuration
```
[database]
type=mysql
prefix=cockatrice
hostname=mysql
database=servatrice
user=servatrice
password=password
[registration]
enabled=true
requireemail=false
requireemailactivation=false
[authentication]
method=sql
```
3. Start the containers with `docker compose up`
4. Register a new user to the Database with Cockatrice user registration
5. Login to the user. This should work
6. Logout
7. Wait 120-140 seconds
8. Try to login again
9. A login is not possible anymore. Servatrice is logging error messages like 
```
servatrice-1  | Sat Apr 27 09:43:54 2024 55fd72662db0 12 bytes [Command_RequestPasswordSalt.ext] { user_name: "test123" }
servatrice-1  | Sat Apr 27 09:43:54 2024 "[pool 0] Error executing query: MySQL server has gone away QMYSQL: Unable to execute query"
servatrice-1  | Sat Apr 27 09:43:54 2024 55fd72662db0 235 bytes [Command_Login.ext] { user_name: "test123" clientid: "d03103772833755" clientver: "2.9.0 (2023-09-14)" clientfeatures: "2.7.0_min_version" clientfeatures: "2.8.0_min_version" clientfeatures: "client_id" clientfeatures: "client_ver" clientfeatures: "client_warnings" clientfeatures: "feature_set" clientfeatures: "forgot_password" clientfeatures: "idle_client" clientfeatures: "mod_log_lookup" clientfeatures: "room_chat_history" clientfeatures: "user_ban_history" clientfeatures: "websocket" }
servatrice-1  | Sat Apr 27 09:43:54 2024 "[pool 0] Error executing query: MySQL server has gone away QMYSQL: Unable to execute query"
servatrice-1  | Sat Apr 27 09:43:54 2024 IP ban check failed: SQL error. QSqlError("2006", "QMYSQL: Unable to execute query", "MySQL server has gone away")
servatrice-1  | Sat Apr 27 09:43:54 2024 "[pool 0] Error executing query: MySQL server has gone away QMYSQL: Unable to execute query"
servatrice-1  | Sat Apr 27 09:43:54 2024 Name ban check failed: SQL error QSqlError("2006", "QMYSQL: Unable to execute query", "MySQL server has gone away")
servatrice-1  | Sat Apr 27 09:43:54 2024 "[pool 0] Error executing query: MySQL server has gone away QMYSQL: Unable to execute query"
servatrice-1  | Sat Apr 27 09:43:54 2024 Id ban check failed: SQL error. QSqlError("2006", "QMYSQL: Unable to execute query", "MySQL server has gone away")
servatrice-1  | Sat Apr 27 09:43:54 2024 "[pool 0] Error executing query: MySQL server has gone away QMYSQL: Unable to execute query"
servatrice-1  | Sat Apr 27 09:43:54 2024 Login denied: SQL error
servatrice-1  | Sat Apr 27 09:43:54 2024 Socket error: QAbstractSocket::RemoteHostClosedError
servatrice-1  | Sat Apr 27 09:43:54 2024 Server::removeClient: removed 0x55fd72662db0 ; 0 clients;  0 users left
servatrice-1  | Sat Apr 27 09:43:54 2024 55fd72662db0 TcpServerSocketInterface destructor
servatrice-1  | Sat Apr 27 09:44:03 2024 [main] Opening database...
servatrice-1  | Sat Apr 27 09:44:18 2024 [main] Opening database...
```
10. Restart Servatrice and the login is working again for 120 seconds

**Comment by ZeldaZach** [comment]
This is definitely an interesting report. Rooster Ranges operates on a similar model, except I have dedicated boxes for SQL/Server compared to a K8 cluster. I can report I see a similar set of errors in my logs. I haven't had reports of users having issues logging in (at least, none that have come forward with an email/GH issue), but this is something we should address

cc @ebbit1q -- I'll do a bit more digging on this potential issue

**Comment by janpfischer** [comment]
Thanks for looking into this @ZeldaZach.

This is not only reproduce able in k8s. It is in the docker setup described above, too. 
For now with the workaround mentioned here (https://github.com/Cockatrice/Cockatrice/issues/5022#issuecomment-2079593427) it is working without issues for weeks. 

But what I also noticed: If the database server is restarted when servatrice is running (crash, version update etc.) servatrice will not re-establish a connection. You'll have to basically restart servatrice.

**Comment by janpfischer** [comment]
@ZeldaZach Thanks for the fix! I've build a new docker image and tested it. It seems to work for normal scenario (database is available but connection is idle and have to be re-established). 
However if servatrice is runnig and the mysql server is restarted it can be that the login is not possible anymore and the logs are logging.

```
[main] Error executing query: Lost connection to MySQL server during query QMYSQL: Unable to reset statement"
```

FTR: I did not build a new client from source, I am using the latest stable one but I believe this should not make any difference.
