### ISSUE TITLE
Any chance for split land draw or split decks format?

### ISSUE THREAD

**Issue by leleleSDX** [Cockatrice/Cockatrice#5028]
There's always been this idea floating around to have lands and spells as separate draws. Is this anyway possible in the client? Maybe the side deck can be used as the land deck? Or maybe to keep it simpler just allow two decks and leave it up to the players if they want all lands on one side.

**Comment by ebbit1q** [comment]
this requires some redesign of some of the protocol and ui elements, we put that into this ticket: #1740
