### ISSUE TITLE
Support multiple facedown sideboards 

### ISSUE THREAD

**Issue by Masbirb** [Cockatrice/Cockatrice#5036]
This has to do with the unfinity attraction and sticker decks (and contraptions) that are placed in a separate face down deck.
May add support for other games.

A button on deck creation that allows for creating secondary decks.
A button when the deck is in play to cycle between your extra decks/discards.
Maybe cards played from second decks have a different back color or outline

**Comment by ebbit1q** [comment]
this is a more complex issue that would need a larger redesign, this will be tracked in #1740 instead.

**Comment by Masbirb** [comment]
oh ok
