### ISSUE TITLE
 Can't see all card sets

### ISSUE THREAD

**Issue by 73028736** [Cockatrice/Cockatrice#5039]
**System Information:**

Client Version: 2.9.0 (2023-09-14)
PictureLoader: [card: "Reckless Handling" set: "MAT"]: Trying to load picture
PictureLoader: [card: "Reckless Handling" set: "MAT"]: Picture found on disk.
PictureLoader: [card: "Scheming Symmetry" set: "SLD"]: Requested "set"property ("muid") for Url template ("https://api.scryfall.com/cards/multiverse/!set:muid!?format=image") is not available
PictureLoader: [card: "Scheming Symmetry" set: "SLD"]: Requested "set"property ("muid") for Url template ("https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card") is not available
PictureLoader: [card: "Scheming Symmetry" set: "SLD"]: Trying to load picture
PictureLoader: [card: "Scheming Symmetry" set: "SLD"]: Picture found on disk.
PictureLoader: [card: "Song of Totentanz" set: "PWOE"]: Requested "set"property ("muid") for Url template ("https://api.scryfall.com/cards/multiverse/!set:muid!?format=image") is not available
PictureLoader: [card: "Song of Totentanz" set: "PWOE"]: Requested "set"property ("muid") for Url template ("https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card") is not available
PictureLoader: [card: "Song of Totentanz" set: "PWOE"]: Trying to load picture
PictureLoader: [card: "Song of Totentanz" set: "PWOE"]: Picture found on disk.
PictureLoader: [card: "Toxic Deluge" set: "CC2"]: Requested "set"property ("muid") for Url template ("https://api.scryfall.com/cards/multiverse/!set:muid!?format=image") is not available
PictureLoader: [card: "Toxic Deluge" set: "CC2"]: Requested "set"property ("muid") for Url template ("https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card") is not available
PictureLoader: [card: "Toxic Deluge" set: "CC2"]: Trying to load picture
PictureLoader: [card: "Toxic Deluge" set: "CC2"]: Picture found on disk.
PictureLoader: [card: "Unearth" set: "2X2"]: Trying to load picture
PictureLoader: [card: "Unearth" set: "2X2"]: Picture found on disk.
PictureLoader: [card: "Vandalblast" set: "AFC"]: Trying to load picture
PictureLoader: [card: "Vandalblast" set: "AFC"]: Picture found on disk.
PictureLoader: [card: "Victimize" set: "AFC"]: Trying to load picture
PictureLoader: [card: "Victimize" set: "AFC"]: Picture found on disk.
PictureLoader: [card: "Wheel of Fortune" set: "30A"]: Requested "set"property ("muid") for Url template ("https://api.scryfall.com/cards/multiverse/!set:muid!?format=image") is not available
PictureLoader: [card: "Wheel of Fortune" set: "30A"]: Requested "set"property ("muid") for Url template ("https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card") is not available
PictureLoader: [card: "Wheel of Fortune" set: "30A"]: Trying to load picture
PictureLoader: [card: "Wheel of Fortune" set: "30A"]: Picture found on disk.
PictureLoader: [card: "Combat Celebrant" set: "LTC"]: Trying to load picture
PictureLoader: [card: "Combat Celebrant" set: "LTC"]: Picture found on disk.
PictureLoader: [card: "Filth" set: "JUD"]: Trying to load picture
PictureLoader: [card: "Filth" set: "JUD"]: Picture found on disk.
PictureLoader: [card: "Garna, Bloodfist of Keld" set: "DMU"]: Trying to load picture
PictureLoader: [card: "Garna, Bloodfist of Keld" set: "DMU"]: Picture found on disk.
PictureLoader: [card: "Tilonalli's Summoner" set: "PRIX"]: Requested "set"property ("muid") for Url template ("https://api.scryfall.com/cards/multiverse/!set:muid!?format=image") is not available
PictureLoader: [card: "Tilonalli's Summoner" set: "PRIX"]: Requested "set"property ("muid") for Url template ("https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card") is not available
PictureLoader: [card: "Tilonalli's Summoner" set: "PRIX"]: Trying to load picture
PictureLoader: [card: "Tilonalli's Summoner" set: "PRIX"]: Picture found on disk.
PictureLoader: [card: "Bitterblossom" set: "2X2"]: Trying to load picture
PictureLoader: [card: "Bitterblossom" set: "2X2"]: Picture found on disk.
PictureLoader: [card: "Battle Hymn" set: "AVR"]: Trying to load picture
PictureLoader: [card: "Battle Hymn" set: "AVR"]: Picture found on disk.
PictureLoader: [card: "Blood for the Blood God!" set: "40K"]: Trying to load picture
PictureLoader: [card: "Blood for the Blood God!" set: "40K"]: Picture found on disk.
PictureLoader: [card: "Shellephant" set: "UST"]: Trying to load picture
PictureLoader: [card: "Shellephant" set: "UST"]: Picture found on disk.
PictureLoader: [card: "Psychosis Crawler" set: "BRR"]: Trying to load picture
PictureLoader: [card: "Psychosis Crawler" set: "BRR"]: Picture found on disk.
PictureLoader: [card: "Siege Behemoth" set: "CMA"]: Trying to load picture
PictureLoader: [card: "Siege Behemoth" set: "CMA"]: Picture found on disk.
PictureLoader: [card: "Siege-Gang Commander" set: "DMR"]: Trying to load picture
PictureLoader: [card: "Siege-Gang Commander" set: "DMR"]: Picture found on disk.
Server_AbstractUserInterface::playerRemovedFromGame(): gameId = 1
Server_Game destructor: gameId= 1
Player destructor: "Player 1"
GameScene::removePlayer name= "Player 1"
CardZone destructor:  "deck"
CardZone destructor:  "grave"
CardZone destructor:  "hand"
CardZone destructor:  "rfg"
CardZone destructor:  "sb"
CardZone destructor:  "stack"
CardZone destructor:  "table"
Server::removeClient: name= "Player 1"
closed session id: 0
Server::removeClient: removed 0x28840e939d0 ; 0 clients;  0 users left
Server_Room destructor
CardDatabase::loadCardDatabases start
[CockatriceXml4Parser] Trying to parse:  "C:/Users/Intel/AppData/Local/Cockatrice/Cockatrice/cards.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
PictureLoader: cache fail for "_trice_card_back_275410"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Intel/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 29548 Sets = 753 "1534ms"
[CockatriceXml4Parser] Trying to parse:  "C:/Users/Intel/AppData/Local/Cockatrice/Cockatrice/tokens.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Intel/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 30368 Sets = 753 "42ms"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Intel/AppData/Local/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 30368 Sets = 753 "0ms"
Loading Custom Set 0 ( "C:/Users/Intel/AppData/Local/Cockatrice/Cockatrice/customsets/TK.xml" )
[CockatriceXml4Parser] Trying to parse:  "C:/Users/Intel/AppData/Local/Cockatrice/Cockatrice/customsets/TK.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
[CardDatabase] loadCardDatabase(): Path = "C:/Users/Intel/AppData/Local/Cockatrice/Cockatrice/customsets/TK.xml" Status = 0 Cards = 30368 Sets = 753 "0ms"
CardDatabase::loadCardDatabases success
PictureLoader: [card: "Infinity Elemental" set: "ULST"]: Requested "set"property ("muid") for Url template ("https://api.scryfall.com/cards/multiverse/!set:muid!?format=image") is not available
PictureLoader: [card: "Infinity Elemental" set: "ULST"]: Requested "set"property ("muid") for Url template ("https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card") is not available
PictureLoader: [card: "Infinity Elemental" set: "ULST"]: Trying to load picture
PictureLoader: [card: "Infinity Elemental" set: "ULST"]: Picture found on disk.
PictureLoader: [card: "Molten Sentry" set: "RAV"]: Trying to load picture
PictureLoader: [card: "Molten Sentry" set: "RAV"]: Picture found on disk.
PictureLoader: [card: "Bell Borca, Spectral Sergeant" set: "DMC"]: Trying to load picture
PictureLoader: [card: "Bell Borca, Spectral Sergeant" set: "DMC"]: Picture found on disk.
PictureLoader: [card: "Dire-Strain Demolisher" set: "DBL"]: Requested "set"property ("muid") for Url template ("https://api.scryfall.com/cards/multiverse/!set:muid!?format=image") is not available
PictureLoader: [card: "Dire-Strain Demolisher" set: "DBL"]: Requested "set"property ("muid") for Url template ("https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card") is not available
PictureLoader: [card: "Dire-Strain Demolisher" set: "DBL"]: Trying to load picture
PictureLoader: [card: "Dire-Strain Demolisher" set: "DBL"]: Picture found on disk.
PictureLoader: [card: "Great Train Heist" set: "OTJ"]: Trying to load picture
PictureLoader: [card: "Great Train Heist" set: "OTJ"]: Picture found on disk.
PictureLoader: [card: "Bedevil" set: "AFC"]: Trying to load picture
PictureLoader: [card: "Bedevil" set: "AFC"]: Picture found on disk.
PictureLoader: [card: "Ancient Tomb" set: "LTC"]: Trying to load picture
PictureLoader: [card: "Ancient Tomb" set: "LTC"]: Picture found on disk.
PictureLoader: [card: "Arid Mesa" set: "MH2"]: Trying to load picture
PictureLoader: [card: "Arid Mesa" set: "MH2"]: Picture found on disk.
PictureLoader: [card: "Badlands" set: "30A"]: Requested "set"property ("muid") for Url template ("https://api.scryfall.com/cards/multiverse/!set:muid!?format=image") is not available
PictureLoader: [card: "Badlands" set: "30A"]: Requested "set"property ("muid") for Url template ("https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card") is not available
PictureLoader: [card: "Badlands" set: "30A"]: Trying to load picture
PictureLoader: [card: "Badlands" set: "30A"]: Picture found on disk.
PictureLoader: [card: "Blightstep Pathway" set: "PLST"]: Requested "set"property ("muid") for Url template ("https://api.scryfall.com/cards/multiverse/!set:muid!?format=image") is not available
PictureLoader: [card: "Blightstep Pathway" set: "PLST"]: Requested "set"property ("muid") for Url template ("https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card") is not available
PictureLoader: [card: "Blightstep Pathway" set: "PLST"]: Trying to load picture
PictureLoader: [card: "Blightstep Pathway" set: "PLST"]: Picture found on disk.
PictureLoader: [card: "Blood Crypt" set: "CLU"]: Trying to load picture
PictureLoader: [card: "Blood Crypt" set: "CLU"]: Picture found on disk.
PictureLoader: [card: "Bloodstained Mire" set: "ZNE"]: Trying to load picture
PictureLoader: [card: "Bloodstained Mire" set: "ZNE"]: Picture found on disk.
PictureLoader: [card: "Command Tower" set: "40K"]: Trying to load picture
PictureLoader: [card: "Command Tower" set: "40K"]: Picture found on disk.
PictureLoader: [card: "Dragonskull Summit" set: "DMC"]: Trying to load picture
PictureLoader: [card: "Dragonskull Summit" set: "DMC"]: Picture found on disk.
PictureLoader: [card: "Fabled Passage" set: "PW21"]: Requested "set"property ("muid") for Url template ("https://api.scryfall.com/cards/multiverse/!set:muid!?format=image") is not available
PictureLoader: [card: "Fabled Passage" set: "PW21"]: Requested "set"property ("muid") for Url template ("https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card") is not available
PictureLoader: [card: "Fabled Passage" set: "PW21"]: Trying to load picture
PictureLoader: [card: "Fabled Passage" set: "PW21"]: Picture found on disk.
PictureLoader: [card: "Hanweir Battlements" set: "SIR"]: Trying to load picture
PictureLoader: [card: "Hanweir Battlements" set: "SIR"]: Picture found on disk.
PictureLoader: [card: "Haunted Ridge" set: "DBL"]: Requested "set"property ("muid") for Url template ("https://api.scryfall.com/cards/multiverse/!set:muid!?format=image") is not available
PictureLoader: [card: "Haunted Ridge" set: "DBL"]: Requested "set"property ("muid") for Url template ("https://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=!set:muid!&type=card") is not available
PictureLoader: [card: "Haunted Ridge" set: "DBL"]: Trying to load picture
PictureLoader: [card: "Haunted Ridge" set: "DBL"]: Picture found on disk.
PictureLoader: [card: "Hanweir Battlements" set: "SIR"]: Trying to load picture
PictureLoader: [card: "Hanweir Battlements" set: "SIR"]: Picture found on disk.
PictureLoader: [card: "Ayara, Widow of the Realm" set: "MOM"]: Trying to load picture
PictureLoader: [card: "Ayara, Widow of the Realm" set: "MOM"]: Picture found on disk.++++++++çÇç
_______________________________________________________________________________________

Can't see all card sets (modern horizons III) in my game ... 
but if I see that other players can use that set within my game

______________________________________________________________________________________

all time

**Steps to reproduce:**
 - Do A
 - Do B
 - Do C ...

**Comment by 73028736** [comment]
Thank my friend, its work

**Comment by ebbit1q** [comment]
you're welcome
