### ISSUE TITLE
Draw from bottom of deck option

### ISSUE THREAD

**Issue by DjZekrom** [Cockatrice/Cockatrice#5041]
**Feature Idea:**
Hello! I was hoping Cockatrice could get a "Draw from bottom of deck" option when right-clicking on your deck. Additionally, having an option to toggle this feature on and off when inputting the draw command (ctrl+D) or clicking the draw button would also streamline the process.

**Context:**
I request this because I recently built a Commander deck with River Song. The ability in question is as follows:
_Meet In Reverse_ - You draw cards from the bottom of your library rather than the top.

I didn't realize until I tried it out with a friend that it was impossible to draw from the bottom of your library without looking at your entire library and picking out the last card in the stack. While this appears to be the only card I can find with this kind of ability, making my request very specific, it still would be incredibly helpful if drawing from the bottom of the deck was an option.

Thank you for considering my request!

**Comment by ebbit1q** [comment]
this is already an option, highlighted in the shortcuts menu:
![image](https://github.com/Cockatrice/Cockatrice/assets/36401181/cc094197-cc42-4cf5-8c9a-57c894d6619a)

while playing it's in the right click menu of your library under bottom of library> draw bottom card

**Comment by ebbit1q** [comment]
also as an alternative you can drag while holding ctrl, I am closing this issue as resolved, please reopen it if you need more help.
