### ISSUE TITLE
cant open to download

### ISSUE THREAD

**Issue by jdawg80** [Cockatrice/Cockatrice#5042]
**System Information:**
windows 11

_______________________________________________________________________________________

not sure what is going on but i cant even open up the application to download and play, my bud told me about this

_______________________________________________________________________________________

**Steps to reproduce:**
 - Do A
 - Do B
 - Do C ...

**Comment by ebbit1q** [comment]
not sure what you mean with can't open the application then download, you can download from this page: https://github.com/Cockatrice/Cockatrice/releases/tag/2023-09-14-Release-2.9.0

**Comment by jdawg80** [comment]
like i download it off here, and i go to open it and then the install wizard wont install or even open up

**Comment by Censor-Array** [comment]
What system are you using?
