### ISSUE TITLE
Images not loading in deck builder (solved?)

### ISSUE THREAD

**Issue by Marco-Wolf-original** [Cockatrice/Cockatrice#5048]
**System Information:**

Client version 2.9.0 (2023-09-14)
_______________________________________________________________________________________

The issue was images would not load in deck builder at all or would take ages to load.

_______________________________________________________________________________________

**Steps to reproduce:**
 - Do A be building a deck
 - Do B scrolling through clicking cards
 - Do C it just happens or doesn't

The solution I found works for now is to remove the scryfall links in the card sources and leave download on the fly checked. For some reason it does not like the scryfall links and they will either fail or be very slow according to the debug but since doing this it downloads images from gatherer nearly instantly. First screen shot is near the top of the debug. And second is near the bottom after fix applied. Hope it helps.
![1717838370529762581554912157284](https://github.com/Cockatrice/Cockatrice/assets/52013161/91f83f51-daa8-406a-aeed-0d7ae7deec35)

![17178384120845549935323670727290](https://github.com/Cockatrice/Cockatrice/assets/52013161/1d5348a6-12c5-49d3-bdcc-dd13ccae031f)

**Comment by ebbit1q** [comment]
please don't send screenshots of the logs, you can copy them and paste them into the ticket.

some users report that scryfall doesn't work for a bit sometimes, it usually is fine again the next time you'll use cockatrice, in the mean time it'll be able to get cards from gatherer that are lower quality. changing the urls in the settings makes this backup solution a lot faster.
