### ISSUE TITLE
Revelation

### ISSUE THREAD

**Issue by Marco-Wolf-original** [Cockatrice/Cockatrice#5050]
**System Information:**

_______________________________________________________________________________________

When using cards like revelation the revealed hands don't refresh automatically as if the hands were revealed at all times

_______________________________________________________________________________________

**Steps to reproduce:**
 - Do A
 - Do B
 - Do C ...

**Comment by ebbit1q** [comment]
this is intentional, you will need to show your hand every time it changes or play with your hand on the battlefield instead

**Comment by ebbit1q** [comment]
duplicate of https://github.com/Cockatrice/Cockatrice/issues/3295
