### ISSUE TITLE
Reveal Random Card from Exile, and Battlefield.

### ISSUE THREAD

**Issue by Censor-Array** [Cockatrice/Cockatrice#5054]
**Similar Requests**
The original Graveyard random card selector
https://github.com/Cockatrice/Cockatrice/pull/2652

Face down card in exile request
https://github.com/Cockatrice/Cockatrice/issues/1769

I would like to see the reveal random card from graveyard feature expanded to include exile and the battlefield to streamline the game when a random card must be selected from one of these zones.

I'd also like to see this apply to only face down cards on the battlefield or in exile, turning the face down card over if it is revealed.

**Additional Context**

**Comment by ebbit1q** [comment]
in which situation would you need a random card from exile?
