### ISSUE TITLE
Moderator Feature: Clear Chat

### ISSUE THREAD

**Issue by ZeldaZach** [Cockatrice/Cockatrice#506]
When we have users who do bad things, such as some of the guests who go on racial rampages, there should be a mod function to clear the main chat.

EDIT: Also, maybe a way to turn the chat off temporarily for certain ranks
- [ ] Disable for Guests
- [ ] Disable for Registered

**Comment by Daenyth** [comment]
I don't like the idea of mods being able to affect things going on in other people's clients. What does this get us exactly?

@A4G that's a separate discussion (open another ticket? might be one already..)

**Comment by ZeldaZach** [comment]
@Daenyth My idea is if we have a "nazi hitler ascii" attack, a mod can flush the chat quickly so users aren't pestered by it. It's just an idea, and I know as a former virtual world owner, having a way to clear the chat is important.

**Comment by A4G** [comment]
@Daenyth Zach edited his main comment, which was what I was addressing.

**Comment by woogerboy21** [comment]
Should we consider implementing an id type system in messages sent that could be used to allow users to edit/update there chat messages with-in the last so many seconds/min or allow the moderation staff to be able to delete messages on an individual basis?

**Comment by ZeldaZach** [comment]
Do you mean similar to glitter and how you have 10min to edit? I like the idea

**Comment by woogerboy21** [comment]
@ZeldaZach Yes, that is the idea.  Not sure what it would take to implement though.

**Comment by poixen** [comment]
@woogerboy21 lots of work.

**Comment by Daenyth** [comment]
I think the benefits of editable messages are questionable, and it's a fair amount of work

**Comment by poixen** [comment]
I think now we have tools to deal with this.
Mods can warn and ban, users can ignore and clear the local chat.

Are ignored users visible in the main chat?

**Comment by Daenyth** [comment]
No.
