### ISSUE TITLE
Custom URLs filling values feature don't work as intended

### ISSUE THREAD

**Issue by ThibaultEbroussard** [Cockatrice/Cockatrice#5062]
**System Information:**
Client Version: 2.9.1-beta (2024-06-16)
Client Operating System: Windows 11 Version 23H2
Build Architecture: 64-bit
Qt Version: 6.5.3
System Locale: fr_FR
Install Mode: Standard
---------------------------------------------------------------------------
Theme changed: "Default"
SoundEngine: disabling sound
Sound theme changed: "Default"
SoundEngine: disabling sound
Unable to load qt translation "qt_fr" at "C:/Program Files/Cockatrice/Resources/translations"
Loaded "cockatrice" translation "cockatrice_fr" at "C:/Program Files/Cockatrice/translations"
main(): starting main program
main(): MainWindow constructor finished
Spoilers Disabled
main(): ui.show() finished
Startup: found config with current version
CardDatabase::loadCardDatabases start
[CockatriceXml4Parser] Trying to parse:  "C:/Users/****/AppData/Local/Cockatrice/Cockatrice/cards.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
PictureLoader: cache fail for "_trice_card_back_302533"
PictureLoader: cache fail for "_trice_card_back_302531"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/****/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 29584 Sets = 754 "1275ms"
[CockatriceXml4Parser] Trying to parse:  "C:/Users/****/AppData/Local/Cockatrice/Cockatrice/tokens.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
[CardDatabase] loadCardDatabase(): Path = "C:/Users/****/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 30417 Sets = 754 "33ms"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/****/AppData/Local/Cockatrice/Cockatrice/spoiler.xml" Status = 4 Cards = 30417 Sets = 754 "0ms"
CardDatabase::loadCardDatabases success

_______________________________________________________________________________________

Following the wiki for Custom Picture Download URLs (https://github.com/Cockatrice/Cockatrice/wiki/Custom-Picture-Download-URLs),
!set:num_fill_with_000! is expected to have the following behavior:

- 1 become 001
- 42 become 042
- 101 become 101

Instead, I noticed this behavior:

- 1 become 0001
- 42 become 00042
- 101 become 000101

_______________________________________________________________________________________

1. Add !set:num_fill_with_000!  to an url.
2. Open the debug log.
3. Try to load a picture and check the debug log.

**Comment by ebbit1q** [comment]
this seems to be a regression since https://github.com/Cockatrice/Cockatrice/pull/4287

**Comment by Carlosjrlu** [comment]
Seems to not be working again.
