### ISSUE TITLE
Sorting labels fail

### ISSUE THREAD

**Issue by i-c-a-t** [Cockatrice/Cockatrice#5064]
--------------------------------------------------------------------------
Theme changed: "Leather"
SoundEngine: enabling sound with 0 sounds
Sound theme changed: "Default"
SoundEngine: enabling sound with 7 sounds
Unable to load qt translation "qt_en" at "C:/Program Files/Cockatrice/Resources/translations"
Unable to load "cockatrice" translation "cockatrice_en" at "C:/Program Files/Cockatrice/translations"
main(): starting main program
main(): MainWindow constructor finished
main(): ui.show() finished
Startup: found config with current version
CardDatabase::loadCardDatabases start
[CockatriceXml4Parser] Trying to parse:  "C:/Users/dell/AppData/Local/Cockatrice/Cockatrice/cards.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
PictureLoader: cache fail for "_trice_card_back_275425"
PictureLoader: cache fail for "_trice_card_back_275422"
[CardDatabase] loadCardDatabase(): Path = "C:/Users/dell/AppData/Local/Cockatrice/Cockatrice/cards.xml" Status = 0 Cards = 29583 Sets = 754 "4884ms"
[CockatriceXml4Parser] Trying to parse:  "C:/Users/dell/AppData/Local/Cockatrice/Cockatrice/tokens.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
[CardDatabase] loadCardDatabase(): Path = "C:/Users/dell/AppData/Local/Cockatrice/Cockatrice/tokens.xml" Status = 0 Cards = 30403 Sets = 754 "98ms"
[CockatriceXml4Parser] Trying to parse:  "C:/Users/dell/AppData/Local/Cockatrice/Cockatrice/spoiler.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
[CardDatabase] loadCardDatabase(): Path = "C:/Users/dell/AppData/Local/Cockatrice/Cockatrice/spoiler.xml" Status = 0 Cards = 30403 Sets = 755 "1ms"
Loading Custom Set 0 ( "C:/Users/dell/AppData/Local/Cockatrice/Cockatrice/customsets/TK.xml" )
[CockatriceXml4Parser] Trying to parse:  "C:/Users/dell/AppData/Local/Cockatrice/Cockatrice/customsets/TK.xml"
[CockatriceXml4Parser] Unknown item "info" , trying to continue anyway
[CardDatabase] loadCardDatabase(): Path = "C:/Users/dell/AppData/Local/Cockatrice/Cockatrice/customsets/TK.xml" Status = 0 Cards = 30403 Sets = 755 "1ms"
CardDatabase::loadCardDatabases success

_______________________________________________________________________________________

![bug1](https://github.com/Cockatrice/Cockatrice/assets/53009819/4bbcd256-ec04-4c5e-b053-b4d48ace7e7e)

They just go blank and I can't click on any of them.

**Comment by ebbit1q** [comment]
your logs are missing the top part with the system info and version, this bug was present with a specific version of windows and cockatrice, try updating both. the current version of cockatrice is 2.9.0

**Comment by i-c-a-t** [comment]
Client Version: 2.9.0 (2023-09-14)
Client Operating System: Windows 10 Version 1909
Build Architecture: 64-bit
Qt Version: 6.3.2
System Locale: zh_CN
Install Mode: Standard

missing part added

**Comment by ebbit1q** [comment]
could you check if using the windows 7 version works better for you? alternatively try our latest beta: https://github.com/Cockatrice/Cockatrice/releases

**Comment by i-c-a-t** [comment]
> could you check if using the windows 7 version works better for you? alternatively try our latest beta: https://github.com/Cockatrice/Cockatrice/releases

The latest version works again：） tks

**Comment by ebbit1q** [comment]
you mean the beta fixes it for you?

**Comment by i-c-a-t** [comment]
> you mean the beta fixes it for you?

yes

**Comment by ebbit1q** [comment]
awesome, thank you for your feedback, we'll try to make the beta a full release soon
