### ISSUE TITLE
UI Elements Missing from Card Database Dialogue Box

### ISSUE THREAD

**Issue by irkella** [Cockatrice/Cockatrice#5065]
**System Information:**
Client Version: 2.9.1-beta.2 (2024-06-24)
Client Operating System: Windows 11 Version 23H2
Build Architecture: 64-bit
Qt Version: 6.5.3
System Locale: en_CA
Install Mode: Standard
_______________________________________________________________________________________

**Issue:** 
UI button elements are missing or not within the viewable area on the card database update dialogue box upon opening. It is still able to be operated through keyboard input, and expanding the window makes them appear.

Moving an expanded window causes them to partially disappear again.

Initially:
![Screenshot 2024-06-25 205429](https://github.com/Cockatrice/Cockatrice/assets/149741841/1dab4d1d-864e-4bb5-8e6d-d3763edf4881)

After drag-expanding box:
![Screenshot 2024-06-25 210024](https://github.com/Cockatrice/Cockatrice/assets/149741841/d6241843-1942-482e-8833-cd6b93a3a4d3)

After moving window that has been expanded:
![Screenshot 2024-06-25 210033](https://github.com/Cockatrice/Cockatrice/assets/149741841/49a5bc34-87b1-4534-82a0-b886a3bda31a)

_______________________________________________________________________________________

**Steps to reproduce:**
- Open the "Check for Card Updates..." option under the Help menu.
- UI button elements are missing upon box opening.
- You can expand the window to cause buttons to appear as normal.
- Moving the box using the cursor/mouse causes partial disappearance of buttons.

**Comment by ebbit1q** [comment]
let's close this issue in favor of the older one
