### ISSUE TITLE
Missing Cards: The Fifteenth Doctor

### ISSUE THREAD

**Issue by adupraz** [Cockatrice/Cockatrice#5090]
**System Information:**

_______________________________________________________________________________________

I don't know if it's a bug, but The Fifteenth Doctor is missing from card database

_______________________________________________________________________________________

Type "The Fifteeth Doctor", it do not appears

**Comment by ebbit1q** [comment]
![image](https://github.com/user-attachments/assets/eec01830-7cb3-42ac-be2e-77a90a35905c)
can't reproduce, please update your card database at help>check for card updates before reporting a card missing, if the issue persists please include your debug log from startup as the template for ticket creation instructs you to.
