### ISSUE TITLE
Importing Custom Set Not Working

### ISSUE THREAD

**Issue by Embercleave** [Cockatrice/Cockatrice#5101]
So I have absolutely no idea about how xml works, but I was following the instructions on how to add custom sets and cards and nothing seems to work. The game just never recognizes my set or card. Here is my html file.

        <xml version="1.0" encoding="utf-8">
        <cockatrice_carddatabase version="4">
            <sets>
	            <set>
			        <name>MDU</name>
			        <longname>Might of the Mardu</longname>
			        <settype>Custom</settype>
			        <releasedate>2024-08-29</releasedate>
	            </set>
	        </sets>
            <cards>
	            <card>
		            <name>Kerlia, the Warlord</name>
		            <text>Flying, first strike, lifelink, trample, vigilance
        
				          Creatures you control have wither.
        
				          Whenever you attack, you choose which creatures
				          block this turn and how those creatures block.</text>
		            <prop>
			            <layout>normal</layout>
			            <side>front</side>
			            <type>Legendary Creature - Angel Warrior </type>
			            <maintype>Instant</maintype>
			            <manacost>1WWBBRR</manacost>
			            <cmc>7</cmc>
			            <colors>WBR</colors>
			            <coloridentity>WBR</coloridentity>
			            <pt>7/7</pt>
			            <format-standard>legal</format-standard>
			            <format-commander>legal</format-commander>
			            <format-modern>legal</format-modern>
			            <format-pauper>legal</format-pauper>
		            </prop>
		            <set rarity="mythic rare" muId="0" picurl="https://s3.us-east-1.wasabisys.com/mtgcardsmith-wasabi/mtgcardsmith/view/complete/full/2024/7/28/1722195172553834.png">MDU</set>
		          <tablerow>2</tablerow>
                </card>
            </cards>
        </cockatrice_carddatabase>

Please Help me. I've tried everything I can think of and looked at multiple similar issues to no avail.

**Comment by ebbit1q** [comment]
note that you can use the xsd to validate your xml file, this is described on the wiki https://github.com/Cockatrice/Cockatrice/wiki/Custom-Cards-&-Sets#diagnosing-problems-in-your-xml-file

**Comment by ebbit1q** [comment]
it's useful to leave solutions on tickets in case other people find them
