### ISSUE TITLE
"Enters the battlefield tapped" stopped working

### ISSUE THREAD

**Issue by CTimmerman** [Cockatrice/Cockatrice#5114]
**System Information:**

Client Version: 2.9.0 (2023-09-14)
_______________________________________________________________________________________

Geothermal Bog "enters tapped", but doesn't because the code probably still looks for "enters the battlefield tapped".
_______________________________________________________________________________________

**Steps to reproduce:**
 - Play Geothermal Bog
 - Notice it is not tapped like it used to be before the wording change.

**Comment by ebbit1q** [comment]
duplicate of #5093, fixed by #5094
