### ISSUE TITLE
Can't install on Ubuntu 24.04

### ISSUE THREAD

**Issue by sedated87** [Cockatrice/Cockatrice#5115]
Steps for recreating attempt to install through terminal

# Manually installing to see logs of why it failed
$ sudo dpkg -i Cockatrice-Rings.of.the.Wild-2.9.0-UbuntuJammy.deb 
Selecting previously unselected package cockatrice.
(Reading database ... 160364 files and directories currently installed.)
Preparing to unpack Cockatrice-Rings.of.the.Wild-2.9.0-UbuntuJammy.deb ...
Unpacking cockatrice (2.9.0) ...
dpkg: dependency problems prevent configuration of cockatrice:
 cockatrice depends on libqt6multimedia6; however:
  Package libqt6multimedia6 is not installed.
 cockatrice depends on libqt6svg6; however:
  Package libqt6svg6 is not installed.
 cockatrice depends on qt6-qpa-plugins; however:
  Package qt6-qpa-plugins is not installed.
 cockatrice depends on libprotobuf23 (>= 3.12.4); however:
  Package libprotobuf23 is not installed.
 cockatrice depends on libqt6core6 (>= 6.2.0); however:
  Package libqt6core6 is not installed.
 cockatrice depends on libqt6gui6 (>= 6.1.2); however:
  Package libqt6gui6 is not installed.
 cockatrice depends on libqt6multimedia6 (>= 6.2.1); however:
  Package libqt6multimedia6 is not installed.
 cockatrice depends on libqt6network6 (>= 6.1.2); however:
  Package libqt6network6 is not installed.
 cockatrice depends on libqt6printsupport6 (>= 6.1.2); however:
  Package libqt6printsupport6 is not installed.
 cockatrice depends on libqt6sql6 (>= 6.1.2); however:
  Package libqt6sql6 is not installed.
 cockatrice depends on libqt6websockets6 (>= 6.2.1); however:
  Package libqt6websockets6 is not installed.
 cockatrice depends on libqt6widgets6 (>= 6.1.2); however:
  Package libqt6widgets6 is not installed.

dpkg: error processing package cockatrice (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.36.0-1.1ubuntu3) ...
Processing triggers for desktop-file-utils (0.27-2build1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Errors were encountered while processing:
 cockatrice

# Trying to manually install all the dependencies
$ sudo apt install libqt6multimedia6 libqt6svg6 qt6-qpa-plugins libprotobuf23 libqt6core6 libqt6gui6 libqt6network6 libqt6printsupport6 libqt6sql6 libqt6websockets6 libqt6widgets6
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package libprotobuf23 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libprotobuf23' has no installation candidate

# Refreshing shows cockatrice needs to be removed following the attempt
$ sudo apt-get update && sudo apt-get upgrade
Hit:1 https://downloads.1password.com/linux/debian/amd64 stable InRelease
Hit:2 https://dl.google.com/linux/chrome/deb stable InRelease                                            
Hit:3 http://us.archive.ubuntu.com/ubuntu noble InRelease                                                
Get:4 http://us.archive.ubuntu.com/ubuntu noble-updates InRelease [126 kB]                               
Get:5 http://security.ubuntu.com/ubuntu noble-security InRelease [126 kB]                                
Hit:6 http://archive.ubuntu.com/ubuntu jammy InRelease                                                   
Ign:7 http://linux.dropbox.com/ubuntu noble InRelease                                                    
Hit:8 http://us.archive.ubuntu.com/ubuntu noble-backports InRelease                                      
Hit:9 http://linux.dropbox.com/ubuntu noble Release                                                      
Get:10 http://us.archive.ubuntu.com/ubuntu noble-updates/main amd64 Packages [530 kB]
Get:12 http://us.archive.ubuntu.com/ubuntu noble-updates/universe amd64 Packages [374 kB]              
Get:13 http://us.archive.ubuntu.com/ubuntu noble-updates/universe Translation-en [154 kB]
Get:14 https://esm.ubuntu.com/apps/ubuntu noble-apps-security InRelease [7,532 B]                        
Get:15 https://esm.ubuntu.com/apps/ubuntu noble-apps-updates InRelease [7,468 B]
Get:16 http://security.ubuntu.com/ubuntu noble-security/main Translation-en [81.5 kB]
Get:17 https://esm.ubuntu.com/infra/ubuntu noble-infra-security InRelease [7,462 B]
Get:18 http://security.ubuntu.com/ubuntu noble-security/universe amd64 Packages [270 kB]
Get:19 https://esm.ubuntu.com/infra/ubuntu noble-infra-updates InRelease [7,461 B]
Get:20 http://security.ubuntu.com/ubuntu noble-security/universe Translation-en [113 kB]
Fetched 1,804 kB in 1s (1,361 kB/s)                              
Reading package lists... Done

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 cockatrice : Depends: libqt6multimedia6 but it is not installed
              Depends: libqt6svg6 but it is not installed
              Depends: qt6-qpa-plugins but it is not installed
              Depends: libprotobuf23 (>= 3.12.4) but it is not installable
              Depends: libqt6core6 (>= 6.2.0)
              Depends: libqt6gui6 (>= 6.1.2)
              Depends: libqt6multimedia6 (>= 6.2.1) but it is not installed
              Depends: libqt6network6 (>= 6.1.2)
              Depends: libqt6printsupport6 (>= 6.1.2)
              Depends: libqt6sql6 (>= 6.1.2)
              Depends: libqt6websockets6 (>= 6.2.1) but it is not installed
              Depends: libqt6widgets6 (>= 6.1.2)
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

**System Information:**
OS: Ubuntu 24.04.1 LTS x86_64 
Kernel: 6.8.0-45-generic 
Uptime: 1 day, 6 hours, 31 mins 
Packages: 1792 (dpkg), 13 (snap) 
Shell: bash 5.2.21 
Resolution: 1080x1920, 3840x1080 
DE: GNOME 46.0 
WM: Mutter 
WM Theme: Adwaita 
Theme: Yaru-dark [GTK2/3] 
Icons: Yaru [GTK2/3] 
Terminal: terminator 
CPU: AMD Ryzen 7 3800X (16) @ 4.200GHz 
GPU: NVIDIA GeForce GTX 960 
Memory: 6069MiB / 64207MiB
_______________________________________________________________________________________

**Comment by ebbit1q** [comment]
you've installed the ubuntu jammy version, this version is for ubuntu 22.04, you are using ubuntu noble, 24.04

when we released cockatrice 2.9.0 ubuntu 24.04 did not exist yet, however it is supported through our beta versions, please download them from here: https://github.com/Cockatrice/Cockatrice/releases
