### ISSUE TITLE
Cockatrice does not traverse symlinked directories when loading images in pics/CUSTOM

### ISSUE THREAD

**Issue by RickyRister** [Cockatrice/Cockatrice#5125]
**System Information:**
Client version: Version 2.9.0 (2023-09-14)
OS: macOS 14.1.2
_______________________________________________________________________________________

When cockatrice is trying to find an image in `pics/CUSTOM`, it will not look inside symlinked directories in there.

### Example

Custom card image is located inside a symlinked directory inside `pics/CUSTOM`
<img width="1006" alt="Screenshot 2024-10-09 at 2 12 58 AM" src="https://github.com/user-attachments/assets/904541b7-18e7-4db0-8be1-0c432b6a5f8f">

...but cockatrice fails to load the image for that card
<img width="1028" alt="Screenshot 2024-10-09 at 2 13 45 AM" src="https://github.com/user-attachments/assets/7d119070-7568-41ab-9f2f-9abf44104733">

### Possible Cause?

https://github.com/Cockatrice/Cockatrice/blob/500b694cc6de0e829dc9bc041149c5896fdd8c42/cockatrice/src/pictureloader.cpp#L193

The `QDirIterator` responsible for iterating through the `pics/CUSTOM` folder is missing the [`QDirIterator::FollowSymlinks`](https://doc.qt.io/qt-6/qdiriterator.html#IteratorFlag-enum) flag, meaning it will not recursively traverse symlinked directories.
_______________________________________________________________________________________

**Steps to reproduce:**
 - Create a directory containing a custom image for a card.
 - Create a symlink to that directory in `pics/CUSTOM`.
 - Open cockatrice. It will not load the custom image for that card.

**Comment by ebbit1q** [comment]
sounds like you've also found the solution, should be as simple as QDirIterator it(customPicsPath, QDirIterator::Subdirectories | QDirIterator::FollowSymLinks);
