### ISSUE TITLE
Failure to Download Replays

### ISSUE THREAD

**Issue by ZeldaZach** [Cockatrice/Cockatrice#513]
I've been informed by 3 Windows users that the arrow to download the replays from the server to the local PC is not working.

I haven't had an issue on Mac OS X 10.10.1, but when 3 separate users told me this was a problem, I figured I should open a ticket.

EDIT: All 3 are running Windows7

**Comment by tooomm** [comment]
Win 8.1 here.
The arrow works, bust just if you click on the replay itself (of a single game within a match). If you click on the folder (=match) containing several replays it's not downloading anything. I expected the client to download all replays if you click on the folder (of different games within the same game tab, 2 games if you play 2-0 in a best of 3 e.g.).
You need to make sure to open the folder and click on every single replay.

Marking several replays with the mouse or shortcuts is not working either if you want to download multiple replays at once.

Maybe that's the problem with the windows users who reported this as well? They just marked the folder (which is closed by default) and clicked the button.
