### ISSUE TITLE
Database to Deck shortcut key

### ISSUE THREAD

**Issue by ChibiEcho** [Cockatrice/Cockatrice#5130]
**By hitting a shortcut, you can directly add a card from the card database to your decklist.**

Instead of double clicking or right clicking and pressing add to deck, a quick button press would be nice.
I wanted to press my insert key to insert the card quickly but didn't see a shortcut for that

Also minor thing, the del button is already keybinded to the delete card button but doesn't show up in the shortcuts menu as a keybind. 
If I wanted it to just remove one card instead of all copies of the card I can't rebind the key to remove card because it's function is fixed.
Similar To #4819

**Comment by ebbit1q** [comment]
this key does exist, it is enter, it is not remappable atm.
