### ISSUE TITLE
Urgent! I clicked delete local replay without selecting anything and i'm pretty sure it deleted my entire home folder.

### ISSUE THREAD

**Issue by Shadetheartist** [Cockatrice/Cockatrice#5134]
**System Information:**

OS: Arch Linux x86_64 
Host: MS-7C37 1.0 
Kernel: 6.11.3-arch1-1 
WM: i3 
CPU: AMD Ryzen 9 3900X (24) @ 3.800GHz 
GPU: AMD ATI Radeon RX 7900 XT/7900 XTX/7900 GRE/7900M 
Memory: 32038MiB 

**Cockatrice**
Client Version: 2.9.0 (2023-09-14)
Client Operating System: Arch Linux
Build Architecture: 64-bit
Qt Version: 5.15.15
System Locale: en_CA
Install Mode: Standard

_______________________________________________________________________________________

I just installed a fresh version of cockatrice from the official arch repos, i quickly joined a server and created a lobby, but my buddy couldn't see the lobby so i closed the lobby and was taken to the replay tab. I was a little confused as to where the server rooms tab was (i accidentally closed it earlier) so i clicked the red X's at the bottom. Without having actually done anything in the game at all. And all of a sudden cockatrice was frozen, and then almost immediately i started seeing issues with missing configs on my top-bar. Alarmed, I thought it might be some active malware so i force shut down my computer and after rebooting i found that my entire home directory was completely reset, empty. 

I didn't have a very recent backup and i lost some valuable files. If this issue is really related to that "delete local replay" functionality this could affect others more severely than I, and that could be tragic.

I'm not going to try actively reproducing this right now as i don't want to risk blowing up my home directory every time. I suggest someone more familiar with the source code comment out the actual file deletion part of the code for this button press and check the file name set to be deleted.

**Steps to reproduce:**
DO NOT DO THIS WITHOUT DUE CARE, YOUR HOME DIR IS AT STAKE
- fresh install?
- go into some server (rooster ranges in my case)
- go to game replays tab (there should be nothing listed for local replays)
- press the red X on local replays (or maybe the red X on server replay storage, i clicked both when i had the issue)

**Comment by Shadetheartist** [comment]
Pretty sure it's related to this

https://github.com/Cockatrice/Cockatrice/blob/038ce3dcece00dabebfb1ec59b8d14972445ffc3/cockatrice/src/tab_replays.cpp#L146

**Comment by Shadetheartist** [comment]
Ok I can confirm that the arch linux version on the official repo **does indeed have this issue**. I have backups this time but it absolutely deleted my home dir again. 

However I compiled from source with Qt6 and debugged this issue myself and it's actually not reproducible in that context.

The arch repo is dangerous for users right now. 

https://archlinux.org/packages/extra/x86_64/cockatrice/

Build date is Sept. 23, 2024, 6:44 p.m. UTC, and it uses QT5, perhaps there's a bug in QT5?

**Comment by FFY00** [comment]
(arch packager here)

I have gone ahead and rebuilt the package with Qt 6, as you reported you weren't able to reproduce the issue locally. This is released as **cockatrice 2.9.0-9**.

It's possible this isn't the source of the issue, but I think this is the best option right now. If I were to simply remove the package from the repos, the current package will stay in the user's systems.

**Comment by ebbit1q** [comment]
we recommend using qt6 over 5 anyway, note that when building with qt6 a couple of dependencies were split off the base and need to be added as separate packages: qt6-imageformats qt6-translations. see our automatic test builds for arch: https://github.com/Cockatrice/Cockatrice/blob/master/.ci/ArchLinux/Dockerfile
note that qt 6.8 added some deprecation warnings that we still have to fix before qt 6.9, for now they are safe to ignore.

we still want to continue supporting qt5 though, so I'll mark this ticket with the highest priority, it's likely that only linux is affected (I'd expect us to have heard of this issue much sooner if it affected windows)

**Comment by ebbit1q** [comment]
![image](https://github.com/user-attachments/assets/bcb80b71-fa3f-40e4-86e5-9182c9f17d6b)
this dialog probably shouldn't even appear, and it definitely shouldn't do anything when you press ok, I'll just make sure it never even asks.

**Comment by FFY00** [comment]
@ebbit1q thanks for the quick fix!

I backported it to arch's 2.9.0 package — released as **cockatrice 2.9.0-10**.

**Comment by ebbit1q** [comment]
you're welcome!
@FFY00 could you add the missing dependencies to the package? I tried suggesting them directly on https://gitlab.archlinux.org/archlinux/packaging/packages/cockatrice but I seem to be unable to log in.

**Comment by FFY00** [comment]
Sorry for the delay, released as 2.9.0-11.

**Comment by ebbit1q** [comment]
awesome, thank you
