### ISSUE TITLE
Packaging issue on Debian Sid

### ISSUE THREAD

**Issue by doms3** [Cockatrice/Cockatrice#5149]
**System Information:**

Client Version: 2.9.1-beta.2 (2024-06-24)
Client Operating System: Debian GNU/Linux trixie/sid
Build Architecture: 64-bit
Qt Version: 6.4.2
System Locale: en_CA
Install Mode: Standard

_______________________________________________________________________________________

I was having issues installing the official Debian package of Cockatrice. This is because the package `qt6-websockets-abi` no longer exists in the Debian package repository. It is my understanding that `qt6-websockets-abi` is actually a pseudo-package that was at one point provided by the  `libqt6websockets6` package.

In newer versions of Qt, the `libqt6websockets6` package now provides `qt6-websockets-private-abi` rather than `qt6-websockets-abi`. I was able to successfully install and run Cockatrice by replacing the dependency `qt6-websockets-abi (=6.4.2)` with `qt6-websockets-abi (=6.4.2) | qt6-websockets-private-abi (>=6.4.2)`.

_______________________________________________________________________________________

**Comment by ebbit1q** [comment]
our prebuilt binaries are for debian 11 and 12 only, for sid you'll either have to build from source or use the flatpak

- https://github.com/Cockatrice/Cockatrice/wiki/Compiling-Cockatrice-(Linux)#debian-based-systems-using-apt
- https://flathub.org/apps/io.github.Cockatrice.cockatrice
