### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by mazzespazze** [Cockatrice/Cockatrice#5154]
Hi!

I cannot install Cockatrice on Ubuntu 20.04. 

I tried

# Install through GitHub

Steps I did:
`git clone git@github.com:Cockatrice/Cockatrice.git`
`mkdir build`
`cd build`
`cmake ..`

I end up with:
```
-- Update Translations: OFF
CMake Error at cmake/FindQtRuntime.cmake:72 (message):
  No suitable version of Qt was found
Call Stack (most recent call first):
  CMakeLists.txt:214 (include)


-- Configuring incomplete, errors occurred!

```

# Step 2: download through Ubuntu package

I went here https://cockatrice.github.io/ and downloaded the ubuntu package. When the installer GUI open and I select install I get 
```
dpkg: error processing package cockatrice (--install):
 dependency problems - leaving unconfigured
Processing triggers for desktop-file-utils (0.24-1ubuntu3) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Errors were encountered while processing:
 cockatrice
```

Same for .deb releases.

**Comment by mazzespazze** [comment]
I solved it by running the full command:

`sudo apt-get install -y  build-essential  cmake  git  libprotobuf-dev  libqt5sql5-mysql  libmysqlclient-dev  libqt5websockets5-dev  protobuf-compiler  qt5-default  qtbase5-dev  qttools5-dev-tools  qttools5-dev`

That should be added in the ReadMe installation.

**Comment by ebbit1q** [comment]
which download did you use? we have downloads for 20.04 but they aren't on the main website, you have to click on the button to show all the downloads.
