### ISSUE TITLE
fedora 41 ci errors out during cpack

### ISSUE THREAD

**Issue by ebbit1q** [Cockatrice/Cockatrice#5165]
#5151 added fedora 41 build but probably because of some bug in cmake it does not create an rpm after compile: https://github.com/Cockatrice/Cockatrice/actions/runs/11740491817/job/32707161539#step:7:702

**Comment by tooomm** [comment]
I think Microsoft keeps updating the available tooling in the actions runner images.

If there is a upstream ticket we can link here and track for a foxing version.
Didn't see one on first glimpse though.

**Comment by ebbit1q** [comment]
we don't use the tooling in the actions runner images except for docker, then we make a fresh container with the dependencies from the distro's repos.

**Comment by tooomm** [comment]
You are absolutely right for the Linux builds!

Was thinking Windows & macOS in my mind.

**Comment by tooomm** [comment]
Fixed in #5180
