### ISSUE TITLE
"Lock" Active Games

### ISSUE THREAD

**Issue by ZeldaZach** [Cockatrice/Cockatrice#517]
[09:43] Grey-Bot: i want to give you some ideas on cockatrice. how about you include an option to "close" a game, its annoying to have a draft, after round 1 someone leaves the room and then you have a constant flow of players checking in and out if you could just make it that no new players can join, even if its only 7/8 full that would be nice so you can read actual new messages in the room

---

I believe this may be a duplicate, but I thought I'd post it.

**Comment by tooomm** [comment]
This is related to: #101 , #171 and #222 (all I could find right now)

Still my +1 for this! :)

**Comment by ZeldaZach** [comment]
Dupe of the few listed above ^

**Comment by tooomm** [comment]
maybe better to keep this single one open and close all the others?
the references to them are all in here, it's a good overview.

**Comment by ZeldaZach** [comment]
Sure @tooomm  :)

**Comment by ZeldaZach** [comment]
Dupe #434

**Comment by tooomm** [comment]
Clarification:
`Locking not yet started games` is different to `Start not yet completely filled up games`.
While the later might be important for EDH, the first would help a lot with drafts.

Draft rooms never start, they are just used to group up and share pairings, report results etc.
The problem is that players who drop the draft/tournament also leave the game room... opening it up for new players, even though the event is still ongoing and not looking for players.

**Comment by ebbit1q** [comment]
I argued that this would be fixed by shrinking the player size as per #434 in our discussion of this ticket and we decided to track it there

**Comment by tooomm** [comment]
Thanks for the heads up and explanation @ebbit1q!! 💯 

>this would be fixed by shrinking the player size as per #434 

Looks like I still need some more details here, as important points from your discussion did not transfer over to our issue tracker.

First off, I would not solve #434 by manually shrinking the player count... If that was your approach.
But even then, I don't get how this should solve the issue with e.g. draft rooms? Remember that such rooms never start and are quite different and more dynamic.
Probably I miss something, or do you have different plans with #434? Honestly, I thought it simply requests a "Start game" button.

<br>

Perfect world:
- have a `Edit Room` option to adjust room type, description, player count without recreating the room... (I think that got requested before?)
- have a `Start Game` button to start the game in a room which is not full (#434)
- have a `Lock Room` button to prevent users from joining (this issue)

**Comment by ZeldaZach** [comment]
I'm happy with closing this, as we're not going to be changing the option. Look to #434 for future fixes.
