### ISSUE TITLE
Cockatrice doesn't auto-update when checking client updates

### ISSUE THREAD

**Issue by Gianluca90** [Cockatrice/Cockatrice#5184]
**System Information:**

Client Version: 2.8.0 (2021-01-26)
Client Operating System: Windows 10 (10.0)
Build Architecture: 64-bit
Qt Version: 5.12.9

_______________________________________________________________________________________

I don't know if it's a bug or not, but whenever i go to "Help" -> "Check client updates" , i get this message:

![immagine](https://github.com/user-attachments/assets/2d78ba06-8f0c-4ffb-bfc9-3b6197bf3e11)

This is the log:

![immagine](https://github.com/user-attachments/assets/3b0daa4a-6468-4cd0-a0d5-9ca77cec0baa)

_______________________________________________________________________________________

**Steps to reproduce:**
 - 1. Click "Help" 
 - 2. Click "Check client updates"

**Comment by tooomm** [comment]
Your version is 3 years old. Maybe too old and probably things changed since then. 

I suggest you download v2.9 from our webpage: https://cockatrice.github.io
For next versions the updater should then work again.

**Comment by Gianluca90** [comment]
> Your version is 3 years old. Maybe too old and probably things changed since then.
> 
> I suggest you download v2.9 from our webpage: https://cockatrice.github.io For next versions the updater should then work again.

Do i have to uninstall my old version, or does the v2.9 have a built-in uninstaller when i run it?
Also, can i keep my settings? For exemples, i have various custom themes and decks saved, does the new version delete them if i install it?
Thanks

**Comment by ebbit1q** [comment]
v2.9 will run the uninstaller of previous versions if it finds them, settings will be migrated automatically.

**Comment by Gianluca90** [comment]
> v2.9 will run the uninstaller of previous versions if it finds them, settings will be migrated automatically.

Thank you

**Comment by ebbit1q** [comment]
you're welcome!
