### ISSUE TITLE
Ubuntu upgrade from 24.04 to 24.10 : "Unsatisfied dependencies:  cockatrice : Depends: qt6-websockets-abi (= 6.4.2) but it is not installable"

### ISSUE THREAD

**Issue by TechInTerh** [Cockatrice/Cockatrice#5190]
**System Information:**
Ubuntu 24.10
Gnome Version : 47
libqt6websockets6 v6.6.2-2 installed
_______________________________________________________________________________________

Hi, I have just upgraded my Ubuntu from 24.04 to 24.10, and Cockatrice was removed during the upgrade.

I tried to reinstall from Cockatrice-2.9.1-beta.2-UbuntuNoble.deb and Cockatrice-2.9.1-beta.2-Debian12.deb (latest release),
and I have the following error :

```sh
$sudo apt install ./Cockatrice-2.9.1-beta.2-Debian12.deb
Note, selecting 'cockatrice' instead of './Cockatrice-2.9.1-beta.2-Debian12.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

Unsatisfied dependencies:
 cockatrice : Depends: qt6-websockets-abi (= 6.4.2) but it is not installable
Error: Unable to correct problems, you have held broken packages.
```
Seems like this package is mandatory to run cockatrice, but it is not available.
I tried to install the version of libqt6websockets6 (6.6.2) with apt, but this does not work (same error).
The expected version of this lib is not available in the public repo.
(Note : this is the only things that does not work work after upgrading :)
_______________________________________________________________________________________

**Steps to reproduce:**
 - Upgrade from ubuntu 24.04 to 24.10 (Cockatrice worked well before upgrading) 
 - Cockatrice is removed during the upgrade
 - Download the latest relase (Noble version and Debian 12)
 - Try to install them with apt.
 - Cry (Optional)

**Comment by ebbit1q** [comment]
the package we provide is not compatible with 24.10, nor do we currently make releases for it, you will have to follow these instructions to compile it yourself, start with the dependencies here: https://github.com/Cockatrice/Cockatrice/wiki/Compiling-Cockatrice-(Linux)#debian-based-systems-using-apt and then scroll down the page to the "Compiling" header

**Comment by TechInTerh** [comment]
Thank you very much. This worked!
