### ISSUE TITLE
Deck editor's card search function does no longer work with text after quotation marks

### ISSUE THREAD

**Issue by Bugtracker319** [Cockatrice/Cockatrice#5200]
Client Version: 2.10.0-custom(ac85b36) (2024-11-21)
Client Operating System: Ubuntu 20.04.6 LTS
Build Architecture: 64-bit
Qt Version: 5.12.8
System Locale: en_US
Install Mode: Standard
_______________________________________________________________________________________

**Description:**

Expected Behaviour:
- When using the search function of the deck editor in the Cockatrice client and writing expressions using quotation marks, the correct results show up. This includes searches as e.g.
  `o:"enchantment" o:"artifact"`, `o:"enchantment" or o:"artifact"`, `o:"equip" -o:"arti"`, `f:c -ci:rgb (o:"fly" or o:"skulk") -o:"defender"`
  and so on.
- Results on searching simple terms like `o:"enchantment" o:"artifact"` are the same as the results on searching `o:enchantment o:artifact`

Issues:
- When using quotation marks in a card search of the deck editor, instead of displaying fitting results nothing is shown as if the query was wrong or as if there were no fitting results.
- Searching without quotation marks for the same expressions where possible give correct results, whilst using quotation marks in any capacity does not give any results at all.
- This behaviour was not present in client versions 2.8.1-beta or prior.
![CardEditorSearchQuotationsBug](https://github.com/user-attachments/assets/55a0f9cb-6cfd-4bad-9e7f-aba60eadb991)
_______________________________________________________________________________________

**Steps to reproduce:**
- Have client version 2.9.1-beta or up. (Potentially also 2.9.0 or up.)
- Use the search function of the deck editor with any search expressions involving quotation marks and any other text or epxression after a space after a quotation mark (see examples above).

**Comment by ebbit1q** [comment]
can reproduce, any search with quotes in it anywhere other than the last atom fails
