### ISSUE TITLE
Interface glitches

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#521]
- In the "Deck" tab there is a picture of the selected card.
Around and under this card you can find several lines. Around the card they just shouldn't appear at all I guess? And around the filter field they should be circulating to seperate that area, no?
![card lines under deck](http://oi62.tinypic.com/35ck1np.jpg)

- There is a colored bar between the "Games" and "Chat" field in the Main Server Room ("Chat Room").
It doesn't seem to belong there. It's the only one of its kind in the client. Colored the same as buttons and every other line in game list and chat, too.
![colored bar under chat room](http://oi62.tinypic.com/ick7yc.jpg)

(Win 8.1 - Cockatrice 776d809)

**Comment by ctrlaltca** [comment]
The lines in the first image are frames borders, they are supposed to group different widgets.
The like in the second image is a vertical splitter, if you hover it with your mouse you should be abl to resize the upper and the lower sections.
Hum.. i suppose you're running a qt4-based build, that doesn't play really nice with windows > 7 and their style. A qt5-based build could look nicer.

**Comment by tooomm** [comment]
I'm running the weekly build from wooger, two weeks old I think.

**Comment by tooomm** [comment]
These elements have different width...
Is this also related to qt4?

![game windows](http://fs1.directupload.net/images/150112/x4lgwirm.png)

**Comment by ZeldaZach** [comment]
Glitches came from running QT4. Fixed in QT5 from my understanding.
