### ISSUE TITLE
Clone keyboard shortcut does not work on opponent's cards.

### ISSUE THREAD

**Issue by RickyRister** [Cockatrice/Cockatrice#5231]
**System Information:**

Client version 2.9.0 (2023-09-14)

_______________________________________________________________________________________

The `Clone` keyboard shortcut does nothing if an opponent's card is selected. The `clone` action from the right-click menu still works on opposing cards.
_______________________________________________________________________________________

**Steps to reproduce:**
 - Join a multiplayer game
 - Get your opponent to put a card on the board
 - Confirm that the `clone` keyboard shortcut does not work on their card
 - Confirm that the `clone` action from the right-click menu does work on their card
 - Confirm that the `clone` keyboard shortcut does work on your cards

**Comment by ebbit1q** [comment]
this would be a nice feature, probably not even that complicated
