### ISSUE TITLE
Misleading debug message for FilterString validation error

### ISSUE THREAD

**Issue by RickyRister** [Cockatrice/Cockatrice#5238]
Client version 2.9.0 (2023-09-14)

_______________________________________________________________________________________

Looking at the code, the “put top card on stack until” action is suppose to validate the filter expression, and terminate the action and throw up an error window if invalid. However, currently the validation will always succeed. 

_______________________________________________________________________________________

**Steps to reproduce:**
 - Open Cockatrice with logs enabled
 - Try entering an invalid expression in the deck builder search bar
   - Confirm that cockatrice logs a debug message about invalid expression
 - Open a game and use the `put top card on stack until` action and enter an invalid expression
   - Cockatrice will happily accept that expression and then proceed to flip the entire deck onto the stack

**Comment by RickyRister** [comment]
So turns out the expression validation does work. The problem is that my understanding of what expression validation means is incorrect. 

I incorrectly thought that an expression is invalid if it contains a query that does not exist. However, turns out the validator only validates the grammar of the expression.

Basically, I thought that `asdf:` and `asdf:asdf` are both considered invalid. In actuality, only `asdf:` is considered invalid.

The reason I saw error messages in the deckbuilder was because I was typing the expression in manually. As I was typing in `asdf:asdf` for example, the error was logged on `asdf:` but since the error message doesn't contain the expression itself, I thought it was getting logged at the end.

**Comment by ebbit1q** [comment]
ah, I didn't validate your report and just triaged it according to what you wrote, I just tested and it works in the way I expected, it's a lot of work to do the validation in a way that it compares it to the entire database
![image](https://github.com/user-attachments/assets/cfae48fc-fe13-46d3-8c22-3b5c8924b31b)
would you like to edit this ticket's title to be more reflective? then I'll lower the prio on it to low, otherwise, close the ticket.
