### ISSUE TITLE
"put top card on stack until" should warn if expression does not match any card in card database

### ISSUE THREAD

**Issue by RickyRister** [Cockatrice/Cockatrice#5241]
Follow-up to #5238

**Description of New Feature**
For the "put top card on stack until" action, after the player enters their search expression and click ok, Cockatrice should check if the search expression matches at least one card in the card database. If not, then Cockatrice should pop up a warning, explaining the issue and giving the player the choice of cancelling or proceeding.

**Additional Context**
I just learned that the expression validation for the “put top card on stack until” action only validates the syntax of the expression. It does not validate that that all the filter names are valid. This seems like a good workaround to validate the filter names. It will additionally catch any expressions that have valid filter names but typos in the values (for example, `t:rouge`)

Currently, a search expression with a typo will likely match every card, meaning Cockatrice will flip the entire deck onto the stack, which is quite disruptive to the gamestate when done on accident. This feature will add a layer of safety to typo situations.

**Comment by ebbit1q** [comment]
this sounds like it'd be very computationally expensive for a simple validation

**Comment by RickyRister** [comment]
Nah, it's peanuts compared to what Cockatrice has to deal with normally. Like, I could see it being a concern if it was being run multiple times a second, but realistically, how often will this scan get run? The deckbuilder needs to run a more expensive version of this calculation every time the search bar or filter changes, and it handles it just fine.

**Comment by ebbit1q** [comment]
yeah that's true, the deck editor is really slow imo, but if it just does this when ok is clicked instead of when a new character is added like the deck editor it's fine. greying out the ok button until the thing is valid is an option as well.
