### ISSUE TITLE
Add a search bar to keyboard shortcut config menu

### ISSUE THREAD

**Issue by RickyRister** [Cockatrice/Cockatrice#5261]
**Description of New Feature**

Add a search bar to the keyboard shortcut config menu. 

**Additional Context**

Currently, the keyboard shortcut config menu has a lot of shortcuts, and grouped together in groups. Finding a shortcut is nontrivial, even for experienced users. Adding a search bar would make it much easier.

**Comment by tooomm** [comment]
Looks like we have the same great ideas 😉 #3648

**Comment by ebbit1q** [comment]
closing as duplicate
