### ISSUE TITLE
Make game replays tabs always accessible 

### ISSUE THREAD

**Issue by anoda9** [Cockatrice/Cockatrice#529]
Currently, the deck storage and game replays tabs only appear when you connect to the server, but it would be better if they were accessible even when not connected. Users may still want to browse decks and replays stored on their local file system without being connected to the server.

**Comment by tooomm** [comment]
I could imagine a grayed out right side (server storage) + including an overlay info message.
Maybe a button to connect to server, too

**Comment by ZeldaZach** [comment]
I like the idea

**Comment by Daenyth** [comment]
:+1: this would be nice.

**Comment by ZeldaZach** [comment]
Deck storage doesn't make sense as decks are _stored on a server_. However, viewing downloaded replays seems reasonable. Relabeling ticket.

**Comment by ebbit1q** [comment]
this is already a thing, you can open the replays that are stored on your file system by clicking the top left menu (Cockatrice) then "Watch replay"
