### ISSUE TITLE
Prevent Non-Standard Characters

### ISSUE THREAD

**Issue by ZeldaZach** [Cockatrice/Cockatrice#532]
With the new database and parse system, non-standard characters, like `Ω`, cause the system to throw an error. I'd like to propose only allowing letters, numbers, and accents where appropriate.

**Comment by ctrlaltca** [comment]
Do you mean that database message logging has problems with non-ASCII characters? If this is the case, we can just add a setting to servatrice to ensure the proper charset is used (mysql: SET NAMES utf8)

**Comment by ZeldaZach** [comment]
Correct

**Comment by Daenyth** [comment]
Can you be more specific about what breaks how. Error messages, etc

**Comment by ZeldaZach** [comment]
`htmlspecialchars` converts them to question marks on the log page when parsing the DB... I don't know what's in the db physically, but I'm assuming it's also not parsing from the game correctly either

**Comment by ZeldaZach** [comment]
Fixed myself
