### ISSUE TITLE
Error on connect with the servidor - COOKATRICE

### ISSUE THREAD

**Issue by Thomasffx** [Cockatrice/Cockatrice#533]
Hello, my name is thomas. I'm from Brazil.

I'm trying to connect with the servidor of Coockatrice, since morning but it's not working.

The error says that to connect, i need a register, but the register is offline, right?

So how i do?

I'm using the normal settings.

cockatrice.woogerworks.com
4747

But, when i try to connect appears "This server requires user registration."

I wish someone can help me.

thx all

Thomas

**Comment by Daenyth** [comment]
This is related to the woogerworks server, not cockatrice as software. If the server is down and you're not able to register for the backup server, you'll need to wait until the main server is back up. I suggest registering an account for the future when possible.

**Comment by Thomasffx** [comment]
And have any forecast when it will be available for registration ? maybe tomorrow the server is already back right?

thx

**Comment by woogerboy21** [comment]
I hope to have the main server back online with in 24 hours
