### ISSUE TITLE
Buddy/Ignore Notifications

### ISSUE THREAD

**Issue by ZeldaZach** [Cockatrice/Cockatrice#537]
If a user adds another user, then that user will get a little notification "ZeldaZach added you to his buddy list! Would you like to do the same? 'Add' or 'Ignore'"

Another part to this question could be do we signal "You have been ignored by ZeldaZach" in a notification?
_____

This ticket can also be attributed to having a way to send notifications to users, which can be adapted in the future to being a way for moderators to send a message to a user or users (the entire server?)

**Comment by Daenyth** [comment]
I wouldn't really care to have this enabled myself but I can see how other people might like it. We'd have to do some kind of control on it so that people can't toggle it back and forth for the notifications

**Comment by ZeldaZach** [comment]
Do you mean you want to prevent somebody from adding/deleting rapidly to spam someone or have a toggle to enable or disable these kinds of notifications?

**Comment by anoda9** [comment]
I don't know if this is really necessary; the purpose of the program (imo) is to let people play magic, not to be a MTG facebook/social networking platform (with users exchanging friend requests, "likes", etc.). Personally, all I want from the buddy/ignore list is for it to be strictly functional - to let me keep track of people that I want playtest/draft with, and to stop people that I dislike from messaging me or joining my games.

**Comment by anoda9** [comment]
>Another part to this question could be do we signal "You have been ignored by ZeldaZach" in a notification?   
Given that the only effect such a notification would be to generate negative emotion, I'd say no. (Facebook doesn't inform you when someone de-friends you or blocks you, for example.) But I think the very fact that discussing this issue causes me to reference precedents set by facebook highlights my initial point - this kind of function is more something you'd find on a social networking platform, not on a program dedicated to playing games. 

I'd prefer to see buddy list groups/categories ("draft people", "modern playtesting people", "EDH players") implemented before this, as that actually increases the functionality of the game-playing aspect of the program (making it easier to find people to play a specific format with you.)

**Comment by tooomm** [comment]
What does actually happen if I ban someone?
Anoda9 mentioned that he is not going to be able to join games created by me and that he can't message me anymore... So can he send the messages and they just don't appear for me, or is there some kind of information shown that the message can't be send?
Same for the games. Is there a message popping up? Just for him? Or a log in the games chat that he tried to connect?
