### ISSUE TITLE
Installer does not open correctly with admin rights

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#5382]
The installer does not ask for admin rights when opening.
It errors only later in the install process. The only way to complete the installation correctly is to right click the .exe and force "Open as administrator".

Instead the OS usually asks for an admin password when opening other installers like Firefox, VLC or Dropbox etc. automatically and completes without the workaround to manually open as administrator.

This also results in the integrated updater never completing.

<img width="399" alt="image" src="https://github.com/user-attachments/assets/39e6f433-8752-49a8-b342-9048c7fb6896" />

_______________________________________________________________________________________

**Steps to reproduce:**
 - Open installer .exe with user that does not have admin privileges
 - Installer does not complain and does open/start
 - Only at a later stage it will error out instead prompting for elevated rights and ask for admin login

**Comment by ZeldaZach** [comment]
This is probably due to my change in #5282 where I need to set Reg keys to support crash dump collection

**Comment by tooomm** [comment]
With the new installer from your PR, it correctly prompts to enter an admin password.

I'll also check the internal updater with the next available beta.

Thanks for the quick fix, Zach!
