### ISSUE TITLE
[Servatrice] Sessions not ending

### ISSUE THREAD

**Issue by Lachee** [Cockatrice/Cockatrice#541]
For my site chickatrice.net, I have a "Users Currently Playing Cockatrice" field which works by checking the current sessions and retrieving the ones with null ending time. This appears to be broken. 

For the most part, the sessions do end when they log off, however, every now and again the session end time remains null after they disconnect.

A suggested fix would be for servatrice to poll every few minutes to see if they are still connected or not and ending their sessions if they are still running.

**Comment by woogerboy21** [comment]
The servatrice app and client have a keep alive ping pole that occurs and in the event the pole fails over a set number of times the clients are disconnected and there sessions are destroyed.  I can’t say I have ever seen or experienced what you describe about a user disconnects and there session table information is not updated.  That sounds like there is some type of database connectivity issue going on.


Is there a way you have been able to successfully recreate it so I could test?

Thanks.






From: Lachee
Sent: ‎Sunday‎, ‎January‎ ‎11‎, ‎2015 ‎4‎:‎39‎ ‎PM
To: Cockatrice/Cockatrice





For my site chickatrice.net, I have a "Users Currently Playing Cockatrice" field which works by checking the current sessions and retrieving the ones with null ending time. This appears to be broken. 

For the most part, the sessions do end when they log off, however, every now and again the session end time remains null after they disconnect.

A suggested fix would be for servatrice to poll every few minutes to see if they are still connected or not and ending their sessions if they are still running.

**Comment by ZeldaZach** [comment]
I've experienced this issue myself a number of times. It occurs if my wifi cuts out and the server doesn't have a chance to ping me. I reconnect my wifi and try joining, but it says my account is in use.

After about 5 minutes it lets me login again (which probably means the server finally realized I wasn't online)

**Comment by woogerboy21** [comment]
The only other time I have seen the sessions not get an end time in the sessions table is if the server crashes and is not restarted.  At that point, the sessions table remains in its last state.  How ever if the server is then restarted one of the first steps in the server start up is to make sure the sessions table is in a sane state.

**Comment by Lachee** [comment]
Actually, now that you mention it, my mysql db crashed (2002) which I guess would cause the issue.... I will make sure the reboot script will end all sessions. Sorry for wasting your time.
