### ISSUE TITLE
"Game Created" column in game list does not re-sort when filtering is enabled

### ISSUE THREAD

**Issue by poixen** [Cockatrice/Cockatrice#542]
When you have a filter applied and have the Game Created column selects, a resort does not seem to happen when new games are added. Related to #436 

![untitled](https://cloud.githubusercontent.com/assets/2134793/5713146/301ea2d4-9ab9-11e4-89f2-b1866a1c0a28.png)

**Comment by Daenyth** [comment]
cc @mitchellwrosen

**Comment by mitchellwrosen** [comment]
Hmm... @Daenyth I'm not sure off the top of my head, I could dig around the code once more.

**Comment by ZeldaZach** [comment]
Tested and confirmed error... seems odd.

**Comment by tooomm** [comment]
It is working for me.

My filter settings are:
- Draft/Sealed
- 1-8 players
- Show password protected games

Sorting is set to newest games on top.

Tested with filter set to description "FRF" without problems, too.

All games are displayed in the right order and new created games or these with slots becoming free again, due to leaving players, are sorted in the list at the right position.

I got this wrong maybe? :) (I'm on 8e396ca)

**Comment by poixen** [comment]
@tooomm did you leave the client for a while?

**Comment by tooomm** [comment]
@poixen I waited until like 2 new games showed up again, they got sorted at the top if new (<1min) or got sorted in between other games (in my case a draft room which finished and people start leaving again (~1h))
So no real long-term test. I will keep an eye on it.

**Comment by Daenyth** [comment]
I wonder:

http://qt-project.org/doc/qt-4.8/qsortfilterproxymodel.html#dynamicSortFilter-prop

> Note that you should not update the source model through the proxy model when dynamicSortFilter is true. For instance, if you set the proxy model on a QComboBox, then using functions that update the model, e.g., addItem(), will not work as expected.

**Comment by Daenyth** [comment]
Yes, I think that's the problem. https://github.com/Cockatrice/Cockatrice/blob/master/cockatrice/src/gamesmodel.cpp#L148

We directly modify the gameList object instead of going through the proxy.

**Comment by Daenyth** [comment]
I can't make it fail compiling from f51e558

**Comment by Daenyth** [comment]
Scratch that - I've observed it from 3cc7c3b

**Comment by tooomm** [comment]
Rechecked that today with no filters applied and letting the window stay passive in the background for like 2 hours:
![gameview](http://fs1.directupload.net/images/150203/95egq6pe.png)

When I reapplied my filter settings it worked fine after roughly the same time.
So it might be related to the filters being unchecked?
Someone else test this with filters please.

**Comment by poixen** [comment]
I only use filters. Standard, modern, EDH. Happens all the time.
