### ISSUE TITLE
Deck editor toolbar commands disabled when focus is removed from the deck editor.

### ISSUE THREAD

**Issue by ZeldaZach** [Cockatrice/Cockatrice#547]
On OSX, there's an issue (that you're likely already brutally aware of, but I'll digress and continue just in case.) with the disabling of deck editor toolbar command functions when focus is removed from the deck editor.

Repro steps:
1) open deck editor and import or create a deck
2) start a local game
3) Close the local game
4) Return to deck editor tab
5) Attempt to interact with Deck Editor dropdown toolbar

Example: http://screencast.com/t/rxsnqGMiywy

The fastest way I've been clearing that state is to select Cockatrice - start local game then when the dialog box pops up, I simply close it and the functionality is restored to the deck editor.

<><><><>
In a server hosted game, I pressed cmd+i to roll and the text in the chat window suddenly shrunk to a font size of 2 or 3: http://screencast.com/t/rFBa9HnXXAO

-Woasha

**Comment by woogerboy21** [comment]
Any change you can update your client and try to reproduce?

**Comment by ZeldaZach** [comment]
I'll try it out

**Comment by ZeldaZach** [comment]
I can't replicate this issue on the latest build...

**Comment by Daenyth** [comment]
Pass it to them, close it if it works

**Comment by woasha** [comment]
On latest build the issue still persists in an identical way indicated above. Currently on OS X Yosemite, but issue was congruent on OS X Mavericks also.
