### ISSUE TITLE
Feature Request : Multiple Database Functionality

### ISSUE THREAD

**Issue by woogerboy21** [Cockatrice/Cockatrice#550]
This is a request to eventually work in the ability to define separate database information to store replays and logs.  An example would be to define a db that stores say the user information / session information etc.  Then have a database definition in the ini that tells servatrice what db to store the replay content into.  And possibly a third database definition in the ini that tells servatrice what db to store the log information in.

Allowing this additional functionality will provide operators the ability to store the larger amounts of less used information by servatrice on a slower type of disk keeping the cost down on servers hosted by cloud companies along with increase the servers performance by gaining the ability of database files to be store across multiple disks.

**Comment by ZeldaZach** [comment]
The practicality of this doesn't align with my vision right now. While it would be nice, I don't ever see us picking this up.
