### ISSUE TITLE
Card picture cache is limited to 2047MB

### ISSUE THREAD

**Issue by heevy** [Cockatrice/Cockatrice#555]
I have installed Cockatrice client(version from About window 761d549) and import default set of edition. But currently i cannot see any card images in the client. If i will go to the pictures directory i see that the pictures are correctly fetched but they are only not displayed. 

If i will install and setup same client version into Windows virtual machine, images are displayed correctly.

**Comment by poixen** [comment]
Do you point to the correct cards.xml location in your settings?

**Comment by Daenyth** [comment]
Can you do the following in the OSX client:

- Open Terminal.app
- Enter the command `/Applications/cockatrice.app/Contents/MacOS/cockatrice &> ~/Desktop/Cockatrice.log &`
- Play enough to see the problem
- Upload Cockatrice.log from your Desktop folder onto gist.github.com and put the link here.

**Comment by Akbaillie** [comment]
I'm having the exact same issue. I typed in the above to terminal, and nothing has changed. I just updated to the new client.

**Comment by Akbaillie** [comment]
Ok, I just fixed the issue by adjusting the picture cashe size to 700mb.

**Comment by heevy** [comment]
@poixen Default ones.I use card DB build by Oracle.

**Comment by heevy** [comment]
@Daenyth messsages from log when i click on a card
Picture NOT found, trying to download (set:  "THS"  card:  "Aqueous Form" ) 
starting picture download: "Aqueous Form" Url:  QUrl( "http://mtgimage.com/multiverseid/373715.jpg" )  

Following 2 lines repeat many....may times.
Trying to load picture (set:  "THS"  card:  "Aqueous Form" ) 
Picture found on disk (set:  "THS"  card:  "Aqueous Form" ) 

However the file ~/Library/Application Support/Cockatrice/Cockatrice/pics/downloadedPics/THS/Aqueous Form.jpg exists and it is correct image.

According to Akbaillie i have set picture cache size back to 700 mb (i have put there 8000 mb during initial setup) and it has started to work. 

After few tests i have found out that it works for cache size 999 mb bot not work for 1000 mb and bigger.

**Comment by Daenyth** [comment]
How much RAM memory does your computer have? (Apple menu > About this mac)

**Comment by Daenyth** [comment]
And what is the filesize of the picture?

**Comment by ZeldaZach** [comment]
I set my picture cache to 1GB (1024MB) so I haven't personally seen this issue, but I'll run a debug on it later

**Comment by heevy** [comment]
Sry for wrong info. So after further tests the line of problem (on my mac) is 2047 mb for image cache (2048 mb is not working). 

@Daenyth My macbook is the latest one 15 inch retina with 16gb of ram and 1TB SSD. The picture cache is for disk size of all images or for ingame image buffering into RAM ?

**Comment by ZeldaZach** [comment]
I have the same computer as you, so I don't know why you're having an issue @heevy

**Comment by tooomm** [comment]
@ZeldaZach 
You are using 1GB cache, he was using 8GB cache.
When he goes down to **below** 2GB (so 2047MB or lower) he is fine too.

**Comment by ZeldaZach** [comment]
Let me try putting it up to a higher number of gigs and see what happens

**Comment by ZeldaZach** [comment]
Interesting... 2048MB+ causes an issue. Will classify as issue
cc: @ctrlaltca

**Comment by ctrlaltca** [comment]
Sounds like the max acceptable value is 2047:
```
void QPixmapCache::setCacheLimit ( int n ) [static]
```
A 32bit signed integer accepts value up to (2^32)-1; this value equals to 2047MB.

**Comment by Daenyth** [comment]
That seems low. Is there some way around this?

**Comment by ZeldaZach** [comment]
Can you add a max value to prevent this from being set above 2047?
I also uploaded a gist relating to my test: https://gist.github.com/ZeldaZach/4c70af7230c9e9dd16a9

**Comment by ctrlaltca** [comment]
I'll check if there's a way (maybe subclassing QPixmapCache?) to raise the limit. Anyway 2047MB should be enough to store hundreds of cards in RAM at the same time.. the problem here is that settings 8GB we overflow the int space, setting a negative value to QPixmapCache::setCacheLimit().. i wonder why is that method supposed to accept a negative value anyway..

**Comment by ZeldaZach** [comment]
That's what I told @Daenyth, that it's enough space to store a lot of cards for the biggest EDH Game

**Comment by Daenyth** [comment]
Because people are careless about using signed numbers.

Can this handle a 4+ person EDH game?

**Comment by tooomm** [comment]
It's just the size in RAM? Or the the maximum amount of MB that can be stored in the pictures folder in general?

**Comment by ZeldaZach** [comment]
Why don't we change it from an input field to a select field that way people can't pick above the maximum value(s) at hand? Most users won't care anyway

**Comment by ZeldaZach** [comment]
It's the Maximum RAM @tooomm 
The only limit on the pictures folder is how much storage your computer has (usually hundreds of gigs)

**Comment by tooomm** [comment]
Well I think there was some limit (in windows at least) that 32bit standard applications are not able to adress more than 2gig of ram?
Did that changed? Or am I totally wrong?

:+1:  for Dropdown

**Comment by skwerlman** [comment]
That number is 4gb, @tooomm
