### ISSUE TITLE
Chat Color Regression

### ISSUE THREAD

**Issue by ZeldaZach** [Cockatrice/Cockatrice#557]
![screenshot 2015-01-15 20 17 45](https://cloud.githubusercontent.com/assets/7460172/5770103/aec1b072-9cf3-11e4-9562-98c6357665c9.png)

The "has left" and "has joined" server messages were a different color (green) in the past, but now they're the same color as the chat.

**Comment by ZeldaZach** [comment]
cc: @poixen

**Comment by poixen** [comment]
How did you even enable this feature? I have never seen it. Is it only available to mods?

**Comment by ZeldaZach** [comment]
@poixen This is in a private message, which anybody can use. You never talk to anyone, so that's your problem :P 

I looked in the code and I think the issue is in [chatview.cpp:129-130](https://github.com/Cockatrice/Cockatrice/blob/8fee9c6c4b4995901f3e865760ba76187865cad4/cockatrice/src/chatview.cpp#L129-L130) that hooks into the [tab_message](https://github.com/Cockatrice/Cockatrice/blob/27eca2505794e77a41e2c167f1f7e58cc6997634/cockatrice/src/tab_message.cpp#L107-L118) aspect and the server's welcome message, which used to be in green also
![screenshot 2015-01-16 09 54 56](https://cloud.githubusercontent.com/assets/7460172/5778009/c0dfa76a-9d65-11e4-93de-df8d90dabb59.png)

**Comment by poixen** [comment]
I think the issue is actually here: 
[line182-183](https://github.com/Cockatrice/Cockatrice/blob/8fee9c6c4b4995901f3e865760ba76187865cad4/cockatrice/src/chatview.cpp#L182-L183).

Will look at it later on.

**Comment by ZeldaZach** [comment]
Thanks!!

**Comment by ZeldaZach** [comment]
@poixen Here's what it used to look like (this image is very old, but this change only occurred a few builds ago. I couldn't find pictures cuz people don't take pics of this shit usually...)

![http://www.thecommandzone.com/wp-content/uploads/2012/10/Picture-3.png](http://www.thecommandzone.com/wp-content/uploads/2012/10/Picture-3.png)

**Comment by ZeldaZach** [comment]
This issue has re-emerged

**Comment by Daenyth** [comment]
Zach can you run a git bisect to find what commit broke it again?

**Comment by ZeldaZach** [comment]
Not 100% certain how to...

**Comment by Daenyth** [comment]
This is fixed right?
