### ISSUE TITLE
Oracle not Working/Importing

### ISSUE THREAD

**Issue by Axelrod1** [Cockatrice/Cockatrice#560]
Hello, I am trying to install Cockatrice on my computer, but when it gets to the step where Oracle is supposed to import the cards it gets hung up and just loads indefinitely.  

What do I do?

Thank you.

**Comment by ZeldaZach** [comment]
Can you provide some screenshots on what went wrong? Also, what's your OS?

**Comment by Axelrod1** [comment]
You have to understand I am practically computer illiterate, so screenshots may be beyond my capabilities.  Also I don't know what OS is.  The Oracle Importer is on the screen where it says "Source Selection" and the download url is the one automatically inserted "mtgjson.com/json/AllSets.json"

Then, the bar for "downloading" is just sitting there at 0 MB, with it looking like it's trying to download but not actually doing anything.  

Does that help?

**Comment by ZeldaZach** [comment]
Ok, paste the URL into your browser and download the file. Then, use the 2nd option of Oracle to "load a file from your computer" and select `AllSets.json` that you just downloaded. That should do it.

**Comment by Axelrod1** [comment]
I'm at the MTG Json homepage now.  Which file am I supposed to download?  The one that says "all sets"?  Or the one that says "All Cards"?

**Comment by Axelrod1** [comment]
Wait, I think that worked.

**Comment by Axelrod1** [comment]
Success!

Thank you so much.
