### ISSUE TITLE
As a player I want to see my deck notes in game tab

### ISSUE THREAD

**Issue by poixen** [Cockatrice/Cockatrice#563]
I want to see and edit my deck notes of the currently loaded deck when I am in the lobby of a room.

**Comment by ZeldaZach** [comment]
Using notes not created in the current match are prohibited in game play normally...

**Comment by tooomm** [comment]
Fair point from both of you, but interesting though... Zach is true for competitive play at least.

I thought about rearranging the right panel these days with a tab-structure. You don't need to see the players all the time or their deck hash, but you are more than happy with a bigger chat panel.
One tab for "Chat", one tab for "Players (with counter "5/8") and there might be one as well for "Notes" you can take *during* a match for removal you see etc. :)

**Comment by ZeldaZach** [comment]
I like the idea of temporary notes you can take during a match ^

**Comment by Daenyth** [comment]
You can't enforce the notes thing. A user can just have a text file open in another window. I don't think it's a concern for us.
