### ISSUE TITLE
Add chat option cog to anywhere chat is used

### ISSUE THREAD

**Issue by poixen** [Cockatrice/Cockatrice#564]
+ in game.
+ in direct chat

**Comment by woogerboy21** [comment]
Are you revering to the little cog gear at the lower section of the main chat area?  And if so what is the goal your trying to accomplish by putting it every were?

**Comment by Daenyth** [comment]
Does it show the option to ignore chat from unreg in the private message screen

**Comment by woogerboy21** [comment]
@Daenyth Not that I am aware of.  I started to look into adding the option to ignore unreg users but didnt make it that far as I couldn't decide if (and this was discussed once) we should add the option to ignore unreg users PM's as an extra option or simply make the "ignore unreg users chat" encompass PMs and have it a single option.

**Comment by ZeldaZach** [comment]
@woogerboy21 I'm a fan of it just blocking all contact with unregs. One option to block both main & pms

**Comment by Daenyth** [comment]
I think it should be two options. I can imagine ignoring pm but allowing chat since we have chat mods

**Comment by ZeldaZach** [comment]
are you implying mods should have the option to ignore unregs from messaging them? (jw)

**Comment by poixen** [comment]
@woogerboy21  My reasoning behind this is continuity and convenience. 

When I move the "Ignore unreg users..." chat option to the chat setting menu, it will be renamed to something like "Ignore unregisterd users in chat rooms". Later on we can add more functionality.

**Comment by Daenyth** [comment]
I was speaking from the perspective of a normal user wanting to ignore unreg PM to avoid harassment but keeping public chat visible since that is moderated and people harassing there will be removed.
