### ISSUE TITLE
Feature Request - Vertically Adjustable Comments and Deck Box Sizes In Deck Editor 

### ISSUE THREAD

**Issue by DanielLevesque** [Cockatrice/Cockatrice#566]
Afternoon.
I've been thinking for a while how I wish I was able to adjust the size of my comment box in the deck editor. I don't know how the workflow is of other players, but I use the comments box pretty heavily with an assortment of notes. (combos and interactions, a maybe board for card ideas for the deck, sideboard notes etc) however the box size itself isn't really conducive to expanded note taking.

Without overhauling the deck editor UI to incorporate a more detailed notation area, I'm proposing making the boxes adjustable on a vertical axis. I don't know how difficult it is to adjust the UI with Qt, but since there isn't anything mapping to them (that I can tell), I don't think it's major. Moving a title box, adding a vertical adjust property etc. But I'm not a dev, so what do I know. Maybe I'm way off base.

Here's an (ugly) example of what I'm talking about: http://screencast.com/t/7Ly0sWqbb
Essentially, I think it would not only look cleaner to have the boxes be congruent in width, but it would serve as a practical purpose of creating more usable space for the end user.

**Comment by Daenyth** [comment]
:+1:

**Comment by poixen** [comment]
I can look into this. Seems simple enough to do.

**Comment by ZeldaZach** [comment]
Seems like an easy fix, i'll get to this shortly

**Comment by tooomm** [comment]
Done already, there is a drag-able separator now to adjust the sizing:
![separator](https://user-images.githubusercontent.com/9874850/97453196-cd1b1f80-1935-11eb-978f-d5a570f8a96a.png)

**Comment by ZeldaZach** [comment]
That’s not the issue. It’s the comment box itself. Please don’t close issues I’ve labeled and audited already until they’re done

**Comment by tooomm** [comment]
#3105

**Comment by ebbit1q** [comment]
zach in our discussion of this ticket decided that it does not resize small enough if I remember correctly

**Comment by tooomm** [comment]
Ok, sure. 👍 
The minimum size for comments is currently ~3 rows.

While you are at it. I suggest to rename `Deck name:` to `Name:`, and `Comments:` to `Notes:` in order to make the fields expand more and waste less space.
