### ISSUE TITLE
Remember column adjustments across sessions.

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#569]
> But rearranging the columns (e.g. you want the password column more on the right and the player count way more left) or changing the width of columns isn't saved at all.
I'm using a low resolution display (1280*1024) right now and still have unused space on the right. I could see so much more use of a bigger description or restriction column since people use longer names for there room if its something special or several restrictions.
You need to rearrange that every time you rejoin the chat room or reconnect to server.

**Comment by tooomm** [comment]
Daenyth  = Speedy Gonzales

Saw this for example: "looking for TRON/BG/x or ad nauseam match up", even "FRF KTK KTK draft" is not showing up completely with the current default wideness of the description column.

A more useful predefined width (depending on screensize? with %) or ordering of the columns itself will help, too. Like the saved custom ordering+width most, though. :P

**Comment by ZeldaZach** [comment]
I just like having the width set to "max-width:/current-max-val" based on the filters and how much space each would theoretically take up; ex: 6 words would be 200px

**Comment by ZeldaZach** [comment]
With recent updates, the tabs are more uniformed and have defined widths. I don't see a real issue on this anymore.

**Comment by tooomm** [comment]
this issue is not just about widths. recent updates improved this though.
it's also about **rearranging** and saving customization in general.
