### ISSUE TITLE
Filter for games list in "server room" and in "user's games" share the same save settings

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#576]
I prefer different filters applied/saved to these two completely different features.

In the room with all games listed ("Chat Room" on wooger server) I want to filter for draft games not yet in progress or some other particular thing, in the user's games list (right click on a user --> "Show this user's games") I want to see all games, including the ones in progress for sure!
It always destroys the other settings and automatically saves the "wrong" ones, so its a doom loop if you happen to use both from time to time. :)

I'm not certain if we need the saved feature for the "Show this user's games" dialog at all. Just show all games by default... that's what you want and expect from this option.
Even a high frequent player with 2 ongoing games in parallel, 2 dead drafts room and a game room for chatting with friends is not confusing in this case.
You can still use the filter if you want/need to (without storing changes to the filter!)

**Comment by kaiserfro** [comment]
I was wondering how long it would take for someone to complain about this.

I had submitted a patch to the code to reload the saved filters on startup a while back, and while writing that code, I was thinking to myself that perhaps saving the user name or game name fields may not be a great idea.  Saving the other fields like, game type and player count seemed ok to me.  But at the time, all of the fields were being saved, but not reloaded.  So i just fixed the reloading part.

Perhaps another fix is in order.

**Comment by tooomm** [comment]
;)

BTW:
Is there a reason for the "user's game" dialog window being that narrow?
You barely see any information about the games you opened this window for...
