### ISSUE TITLE
Mentions of other users should check for punctuation

### ISSUE THREAD

**Issue by poixen** [Cockatrice/Cockatrice#586]
@otheruser should be highlighted along with @otheruser! @otheruser? 
ect ect

right now the mention code will check to the end of the current word, including the !?., ect ect

Doesnt effect self mentions, due to checks if the message contains your own username.

**Comment by ZeldaZach** [comment]
Ding :+1:

**Comment by Daenyth** [comment]
The way we do checking might have some level of interaction with #98
