### ISSUE TITLE
unexpectedly absent can't be played

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#596]
We currently can't do this without viewing hidden cards

**Comment by TaZi-loh** [comment]
you could drag cards face down from the lib into play, couldn't you?

**Comment by ZeldaZach** [comment]
Currently just drag the top X cards of the library onto the field in a known order and then place the known card on the library. It's a crude way to do it, but it's what we have atm.

We did add the library feature for grenzo... maybe we can look into this in the future

**Comment by LivingInfinite** [comment]
I think this one is fixed

**Comment by ZeldaZach** [comment]
Yep, agreed!
