### ISSUE TITLE
Missing some flag svg

### ISSUE THREAD

**Issue by poixen** [Cockatrice/Cockatrice#598]
When debugging I see we are missing some flag images:
```
Cannot open file ':/resources/countries/va.svg', because: Unknown error
Cannot open file ':/resources/countries/gb.svg', because: Unknown error
Cannot open file ':/resources/countries/kw.svg', because: Unknown error
Cannot open file ':/resources/countries/bs.svg', because: Unknown error
Cannot open file ':/resources/countries/un.svg', because: Unknown error
Cannot open file ':/resources/countries/cr.svg', because: Unknown error
Cannot open file ':/resources/countries/bo.svg', because: Unknown error
Cannot open file ':/resources/countries/wa.svg', because: Unknown error
```
These images are not in /resources/countries and should be added.

**Comment by ZeldaZach** [comment]
My searches are screwy, so if you can tell me the countries I can try and locate these

**Comment by Nightfirecat** [comment]
According to the all-knowing base of Wikipedia:

* [VA - Holy See (Vatican City State)](http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#VA)
* [GB - United Kingdom](http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#GB)
* [KW - Kuwait](http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#KW)
* [BS - Bahamas](http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#BS)
* **UN - ???**
* [CR - Costa Rica](http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#CR)
* [BO - Bolivia, Plurinational State of](http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#BO)
* **WA - ???**

**Comment by tooomm** [comment]
Don't know about these two either.

Checked out:
http://www.nationsonline.org/oneworld/countrycodes.htm
http://www.worldatlas.com/aatlas/ctycodes.htm

**Comment by ZeldaZach** [comment]
@ideocl4st Can you possibly assist with this, as I know you were able to get the south korea flag working? :)

**Comment by ideocl4st** [comment]
According to https://www.iso.org/obp/ui/#search
WA is 'unassigned'
and UN is 'exceptionally reserved' - I don't think we can find a flag for non-existing countries ;)

I thought the application picks up whatever that's on cockatrice.qrc as I had to add kr.svg in there to make Cockatrice pick up the South Korean flag.

Except none of those files are present in cockatrice.qrc.

**Comment by ZeldaZach** [comment]
I didn't add to `cockatrice.qrc`... whoops. I'll deal with that now. thanks!!

**Comment by ideocl4st** [comment]
Actually, better question would be why it would be looking for files that are NOT in cockatrice.qrc. I can't find any reference of those countries in source codes...

Perhaps some people in wooger's server put down those codes as their country and Cockatrice was confused that it couldn't find flags for those countries?

**Comment by tooomm** [comment]
(@ideocl4st no, they just get notified once with the original text)

**Comment by ideocl4st** [comment]
@tooomm Oh, that's a relief. I know that I should be more careful writing comments so that I don't have to edit afterwards but I can't stop myself from finding out 'better' ways to phrase what I just wrote.
