### ISSUE TITLE
Servatrice password hashing

### ISSUE THREAD

**Issue by VanNostrand** [Cockatrice/Cockatrice#60]
I propose to remove password hashing from the code and use crypto functions instead to store passwords.

Also, the salting procedure looks suspicious, because salts have to be random strings and they shouldn't be too small but the PasswordHasher uses the 16 first characters from the password as salt? Whatever the user uses, it is propably not random.
So this is insecure.

And why is this in PasswordHasher::computeHash()?
const int rounds = 1000;
char hash[hashLen], tmp[hashLen];
for (int i = 1; i < rounds; ++i) {
    memcpy(tmp, hash, hashLen);
    gcry_md_hash_buffer(algo, hash, tmp, hashLen);
}
-> memcpy copies the value from hash to tmp, then the digest is created and overwrites the old one... thousand times all over again?
This won't make it more secure or more random, use a cipher like Blowfish instead and replace this code.
For Qt there is the QCA library: http://delta.affinix.com/docs/qca/ so you can replace libgcrypt easily - and you don't need to convert QStrings to char arrays anymore.
There is a QCA tutorial: http://www.essentialunix.org/index.php?option=com_content&view=article&id=48:qcatutorial&catid=34:qttutorials&Itemid=53

**Comment by Daenyth** [comment]
Now that we have the "required features" ability we could force a full update, though for UX purposes I'd like to not turn it on for a little while

**Comment by Daenyth** [comment]
See http://security.stackexchange.com/questions/211/how-to-securely-hash-passwords

Summing up;

- Use a good hash function (let's pick bcrypt)
- Add a salt column to the user db. Use randomly-generated values
- Client sends hash(password). The work factor has to be static and hardcoded here to avoid the output changing across client upgrades or anything like that.
- Server accepts the hashed password, looks up the salt by username, then does hash(hashedpw+salt), and compares that with the db.
  - This permits a timing attack to determine whether a user exists; I don't think I care about this. You can already enumerate usernames in a variety of ways (for example, brute force add-to-buddy-list calls).

Actually we don't have to do anything to the client here. It can continue sending the current method of hashed password and the server can just start taking that as an input. The awkward part is the transition period. Perhaps we can handle that with a database migration?

**Comment by ctrlaltca** [comment]
Closing this as "nonsense".

> I propose to remove password hashing from the code and use crypto functions instead to store passwords.

Reversible crypto functions should not be used to store data that doesn't need to be decrypted. Hash functions exists exactly to store data like passwords that you only need to check for equality.

> Also, the salting procedure looks suspicious, because salts have to be random strings and they shouldn't be too small but the PasswordHasher uses the 16 first characters from the password as salt? 

No, probably you misread the code. A random 16-char salt gets randomly created.

> And why is this in PasswordHasher::computeHash()?
> const int rounds = 1000;
> char hash[hashLen], tmp[hashLen];
> for (int i = 1; i < rounds; ++i) {
> memcpy(tmp, hash, hashLen);
> gcry_md_hash_buffer(algo, hash, tmp, hashLen);
> }
> -> memcpy copies the value from hash to tmp, then the digest is created and overwrites the old one... thousand times all over again?

Those are called "rounds" in hashing. More info here: https://security.stackexchange.com/questions/149299/rounds-in-a-hashing-function

> This won't make it more secure or more random,

Yes, it does. 

> use a cipher like Blowfish instead and replace this code.

No way a reversible crypto function is more secure that an hash function. We should store the crypt key somewhere to be able to decrypt the user password and compare it, and this would make the encryption useless.

**Comment by arxanas** [comment]
Blowfish backs the bcrypt hash, which is a current "best-practice" hash.
See for example
https://security.stackexchange.com/questions/133239/what-is-the-specific-reason-to-prefer-bcrypt-or-pbkdf2-over-sha256-crypt-in-pass.
It's best not to roll one's own password-hashing code to accomplish the
same thing.
