### ISSUE TITLE
Add Deck Name and Comments to Save to/Load from clipboard functionality

### ISSUE THREAD

**Issue by wildnacatl** [Cockatrice/Cockatrice#601]
Saving the deck to clipboard results in the main deck and the sideboard being copied, however we lose the deck name and comments in this process.

**Comment by ZeldaZach** [comment]
Saving the deck to clipboard only saves the deck list... I don't see an issue

**Comment by wildnacatl** [comment]
In deck editor, if I load a saved deck, the name and comments populate.

**Comment by Daenyth** [comment]
I'm excited this is finally in!
