### ISSUE TITLE
Player text color (temporarily?) resets to black between games

### ISSUE THREAD

**Issue by Nightfirecat** [Cockatrice/Cockatrice#604]
Don't have many details yet - just noticed it while playing on version 776d809 today, and it may not be an issue on the current build. I'll do some more digging tomorrow and update this issue.

**Comment by ZeldaZach** [comment]
Try compiling your own build and see if it's fixed. I recall @poixen fixed this again

**Comment by poixen** [comment]
This. If you are a github user, download the latest version. If not wait for the weekly build.

**Comment by Nightfirecat** [comment]
Alright, I'll take your word for it. My build was pretty old (weekly from about a month ago), so that's likely the cause.
