### ISSUE TITLE
"Connect... (to server)" - Cursor stuck to the first field

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#606]
If you click on "Cockatrice" --> "Connect..." on the main menu to join a server the cursor will always be placed in the first field. Regardless if you already added a server address and all other stuff.
I would like to see the cursor jumping to the first empty field instead. So it will work out for first time users which need to add a server address first and heavy users which just needs to type their password equally.

(I guess most people just use the save password setting and maybe even auto-connect, but not everyone likes that --> especially since #344)

A loop check for an empty field might work here?

**Comment by ZeldaZach** [comment]
If you hit the `tab` key you can change quickly... I don't see a real need, but it's an option for sure :)

**Comment by tooomm** [comment]
Five times tabulator key is a workaround, yes.

Still wanted to point that one out. ;)

**Comment by Daenyth** [comment]
I think it should go to the same field every time. Consider the moment you hit connect with your button: what field will it be in? You can't reliably know. Leaving it as is does have a (very) slight inconvenience but it also allows for muscle memory

**Comment by poixen** [comment]
I agree, it seems like a very minor issue.
