### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by CucumberKimchi** [Cockatrice/Cockatrice#613]
Hey guys I'd like to suggest in making the themes and card backs look and flow better on cockatrice.

First off making an "install theme" section below the sections of manually inputting the images, utilizing a zip with specific names (ie. Tabe.png) and being able to just download and install them. for a more advanced user they can open the zip, assign what they like and don't have to use what they don't like. I can make a few of these themes and work on thread that people upload their themes. or I could design a few basic themes to be applied to the next release as well as basic cockatrice avatars for reg. users.

Here is a basic wood theme I made: 
![kgh8jrc](https://cloud.githubusercontent.com/assets/10725518/5919127/a1711a5c-a5fe-11e4-99eb-a2e711361f64.png)

**Comment by poixen** [comment]
Will be interesting to hear @Daenyth thoughts on this.

**Comment by woogerboy21** [comment]
Personally I dont know if I am a fan of having something that is in client that would connect to some were to pull the them information and then make it available to the client.  Who would maintain the infrastructure required for clients to pull the data?  Who would maintain any listing of said theme's.  Now this does bring up something else in mind, maybe we could have a theme configuration type file the client could understand and input the desired information for all the theme components that are available in the client.  That might be a possibility.  That way users can download theme's from any were and with a single search and load of the configuration file all the relevant theme items would be used.

**Comment by woasha** [comment]
Is there any way that nefarious code could be introduced through a theme if it it's unmoderated and just used as third party upload?

**Comment by ZeldaZach** [comment]
I can add a sidebar link on Reddit to link to a "themes page" where .png and .jpg images could be hosted or something.

I really like the wood layout and think others would rock too!

**Comment by Daenyth** [comment]
I think we can best accommodate themes by enforcing that the filenames always be the same and change settings to select a folder. That way a theme can just be a folder of specific files and sharing them becomes easy

**Comment by ZeldaZach** [comment]
I like the idea @Daenyth 

So we have `zonebg` currently. Maybe we can allow sub-folders within that directory called like `my blue theme` and then within the theme they can have files `hand.png`, `stack.png`, `table.png`, `playercard.png`, and `cardback.png` which will represent all aspects that can be modified.

Also, if you don't include the image then it defaults to whatever @poixen updated the client with a while ago

![screenshot 2015-01-27 15 28 15](https://cloud.githubusercontent.com/assets/7460172/5926463/3328a30e-a639-11e4-8530-ece583091857.png)
![screenshot 2015-01-27 15 28 19](https://cloud.githubusercontent.com/assets/7460172/5926464/332afe6a-a639-11e4-8312-946be53648d9.png)

**Comment by CucumberKimchi** [comment]
I think the subfolders is a great Idea and will work well once its sorted out I'd be happy to make them as long as I know the format.

**Comment by ZeldaZach** [comment]
Awesome @CucumberKimchi :)

**Comment by ZeldaZach** [comment]
Started progress in #792

**Comment by woogerboy21** [comment]
@ZeldaZach Now that @ctrlaltca theme PR is in, can we close this issue?
