### ISSUE TITLE
Card size

### ISSUE THREAD

**Issue by CucumberKimchi** [Cockatrice/Cockatrice#614]
Please have an option as the in-game on battlefield card size is far too small, please have an option to make them larger.

**Comment by poixen** [comment]
Can I ask what resolution your screen is? Also, you can see a preview of the card to the right of the screen, does that not help?

**Comment by CucumberKimchi** [comment]
I run at 1600x900 but comparable to modo you can make the cards much larger. Its nit picky but the only thing I have a problem with. I can use the vertical hand, however making the game 2 sections as opposed to 3 all-together would just be much simpler however break a lot of things

**Comment by woogerboy21** [comment]
It would be kind of nice to have an option to set the default size of the card images on the battlefield.  Though I am not certain how often it would get used on most clients, but those running higher resolutions it probably would come in handy.

**Comment by woasha** [comment]
As someone who's primary machine is a 15" macbook pro, I would ~love~ to be able to manually adjust the size of the cards in my hand and on the board somehow to be larger than they are currently. (Or to turn off the auto-scale when cards extend to a certain point on the grid.)

My typical "workflow" has me stacking lands in a way that I normally wouldn't simply to reduce the amount of scaling the client does when lands extend on the grid for the simple sake of keeping them to an appropriate visible size.

**Comment by ZeldaZach** [comment]
Same thing as @woasha here. I'd love to have cards be a little bit bigger on the screen

**Comment by FFY00** [comment]
Same issue with me.

**Comment by ebbit1q** [comment]
dupe https://github.com/Cockatrice/Cockatrice/issues/2798
