### ISSUE TITLE
[Feature Request] - Right Click Hand Option - Discard Card at Random

### ISSUE THREAD

**Issue by woasha** [Cockatrice/Cockatrice#617]
Unless I missed a basic feature that utilizes something like this already, I'd like to see an option to discard a card at random. Currently, I've seen some players place their cards face down on the table, place tokens on them and assign them values (1,2,3,4 etc) then asked me to chose one to discard. 

This was quite cumbersome. Is there a more appropriate way to facilitate this? If not, could be add a right-click feature on the bottom hand play area for "discard random card" etc? 

http://screencast.com/t/mc5ljStV

Spitballin'...

**Comment by ZeldaZach** [comment]
How I've seen it done is you hit "Reveal random card to all" then discard that one.

**Comment by woasha** [comment]
@ZeldaZach  - That works too. Not as clean, but functionally does the same. I definitely missed that option. Thanks.

**Comment by Daenyth** [comment]
I don't see the harm in adding it

**Comment by ZeldaZach** [comment]
@Daenyth Too many features gets cluttered quickly tho

**Comment by JineteDV** [comment]
What Zach said, people already don't read all the menu options.
