### ISSUE TITLE
Server requires user registration

### ISSUE THREAD

**Issue by tyler13ho** [Cockatrice/Cockatrice#618]
I was connecting just fine for a day or two and now when I go to connect to Cockatrice, it gives me the message:
Server requires user registration

I created an account with Woogerworks however the account registration was disabled. Could this be the reason that I can't connect? Could it be due to server capacity?

**Comment by Daenyth** [comment]
The server was on the backup machine for an upgrade on the main server. Accounts are synced to the backup about daily
