### ISSUE TITLE
Ctrl+Tab doesn't work on OSX

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#621]

**Comment by ctrlaltca** [comment]
I suppose it's mapped to cmd+tab, that is broken since that's the accellerator key for osx's process list (windows' alt+tab).

**Comment by Daenyth** [comment]
Seems likely

**Comment by ZeldaZach** [comment]
Nothing on mac works :(

**Comment by ZeldaZach** [comment]
Can we close this as you can reassign commands?
