### ISSUE TITLE
Allow oracle to download zipped version of sets json

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#624]
With the default json we'd go from 11mb -> 2.5mb on each download.

**Comment by ZeldaZach** [comment]
:+1: for reduced bandwidth usage

**Comment by Sembiance** [comment]
Just to mention, if the HTTP downloading code in Cockatrice supports gzip for "Content-Encoding" then that 11MB goes to 3.4MB. Yes, zip support would get you even further than that :)

**Comment by Psithief** [comment]
:+1: for Sembiance dropping in.

**Comment by ctrlaltca** [comment]
FYI: I'm working on the issue
