### ISSUE TITLE
Issues with online deck storage

### ISSUE THREAD

**Issue by tehboss** [Cockatrice/Cockatrice#626]
Cannot save changes to a deck that resided online.  Also cannot move a deck from local storage to online storage.  It copies with an ID of 0 and isn't actually there.

**Comment by Daenyth** [comment]
Was there any error message?

**Comment by MassCraziness** [comment]
Just tried moving a deck now. It has an ID of 0, cannot be loaded in-game, and cannot be deleted from the server.

**Comment by MassCraziness** [comment]
No error message at all

**Comment by tehboss** [comment]
No errors.

**Comment by ZeldaZach** [comment]
Just tried this out and it seems to work fine now. Might've been fixed elsewhere at some point.
