### ISSUE TITLE
Option of hiding games of unregistered users

### ISSUE THREAD

**Issue by LethalPigeon7** [Cockatrice/Cockatrice#628]
Since there's an "ignore unregistered users in the main chat" I feel like this is the next logical step on the path to a bright unreg-free future.

**Comment by Daenyth** [comment]
This is fairly easy to do

**Comment by Nightfirecat** [comment]
Why close this? Seems like it's still a valid issue.

**Comment by ZeldaZach** [comment]
Maybe it was closed b/c "main" server is reg only. Still valid for not reg servers

**Comment by Daenyth** [comment]
It's a good suggestion. I don't think I want to implement it until we make filter configuration suck less.

**Comment by LethalPigeon7** [comment]
Yeah I was not aware that servers with unregs still existing.

**Comment by tooomm** [comment]
Related to https://github.com/Cockatrice/Cockatrice/issues/1702
This option should only be shown or be usable when the server allows unreg at all AND is not unreg-only.

**Comment by ZeldaZach** [comment]
This is apart of #1702 and is super low priority imo. I'm gonna close and track there.
