### ISSUE TITLE
Create new statistics db table

### ISSUE THREAD

**Issue by woogerboy21** [Cockatrice/Cockatrice#629]
I would like to see a new table added to the DB that keeps track of any number of stat type information.  The first stat to monitor would be the last login date / time of users.  Another row column idea would be the number of times the kick function was used by a user.  

Any other thoughts to this?

**Comment by woogerboy21** [comment]
This may work into/with #170

**Comment by Daenyth** [comment]
I'd rather implement the sdk of some dedicated analytics software
