### ISSUE TITLE
Whitespace isn't properly stripped from game description

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#635]
Not sure how this happened

http://s15.postimg.org/v5gysgbwp/Screen_Shot_2015_01_28_at_8_36_28_PM.png

**Comment by ZeldaZach** [comment]
The hell... no idea

**Comment by Daenyth** [comment]
If you paste a string with `\n` in it into description it will do it.

It also stretches your tab bar.

Client & server should replace `\n` with ` ` (space). Probably `\t` and `\f` too

**Comment by Psithief** [comment]
Would you want to strip every whitespace (`\s`) character that's not space?

**Comment by Daenyth** [comment]
We should do a regex replace `\s+` -> ` `

**Comment by kaiserfro** [comment]
I think in QT is easier than that.  str.simplified() should reduce the whitespace to a single space.
