### ISSUE TITLE
Missing svg files for counters

### ISSUE THREAD

**Issue by poixen** [Cockatrice/Cockatrice#647]
```
Cannot open file ':/resources/counters/x.svg', because: Unknown error
Cannot open file ':/resources/counters/storm.svg', because: Unknown error
```
Same issue as with the flags.

**Comment by Daenyth** [comment]
"Same issue as with the flags" can you clarify?

**Comment by poixen** [comment]
I reported on an issue with missing svg flags. On my phone, can't find the issue number. 

The client tries to load in missing files.

**Comment by Daenyth** [comment]
Those files don't seem to exist, I see now

**Comment by tooomm** [comment]
This one? #598 
@ZeldaZach fixed the flags.

**Comment by skwerlman** [comment]
Also: `Cannot open file ':/resources/counters/storm_highlight.svg', because: Unknown error`

**Comment by ZeldaZach** [comment]
The X and Storm are both using the `general.svg` and `general_highlight.svg` instead of `x.svg`, `x_highlight.svg`, `storm.svg`, and `storm_highlight.svg`.

**Comment by ZeldaZach** [comment]
Fixed
