### ISSUE TITLE
Can't register an account for Cockatrice

### ISSUE THREAD

**Issue by pyrwyrm** [Cockatrice/Cockatrice#650]
How do I register an account for Cockatrice? Whenever I try to register through http://woogerworks.com/index.php/account-registration , this error page appears: http://cockatrice.woogerworks.com:81/registrationpage.php . Can someone help me? Thanks!

**Comment by Daenyth** [comment]
@woogerboy21

**Comment by woogerboy21** [comment]
What error are you seeing and have you tried another browser?  It sounds odd but many times people have lots of plugins in there default browser loaded and when an issue like this happens trying one that isn't usually used that doesn't have all the things loaded works.

I show others registering fine.

**Comment by Hanmac** [comment]
I did register myself on that formular but i didnt get an email ...
i used that contact formular too but also there no email 
even i did check the point that i should get a copy of it
