### ISSUE TITLE
Document translator process

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#651]
@ideocl4st I'm trying to get a wiki page set up with a "How to translate cockatrice" guide. I was hoping you can share a little of your experience on it. What OS are you on?

**Comment by ideocl4st** [comment]
I'm on Mac OS X (Yosemite).

**Comment by Daenyth** [comment]
I'm assuming your workflow is to run `cmake -DUPDATE_TRANSLATIONS=1 && make` and then run QTLinguist against the file?

**Comment by ideocl4st** [comment]
Well...Nowadays I only use Sublime Text.
Since I only need to edit a phrase or two for each update, I just open the translation file in any text editor and look up 'unfinished' to find the new strings that appeared since my last translation.

On my initial translation though, I used Qt Linguist for two reasons:
1. You can see where the strings will be used in terms of source code, which gives you a good idea of what the string is about. (I don't need this anymore as I keep track of new commits and have a pretty good idea of what the new strings would be about)
2. You can easily see how much you have finished translating - Much better than looking up 'unfinished' in a text editor when you have a few hundred unfinished strings is not very efficient.

**Comment by tooomm** [comment]
@ctrlaltca set up a ![project page](https://www.transifex.com/projects/p/cockatrice/) on Transifex to make it possible for every user to easily help with Cockatrice and Oracle translations.

You did some editing and reviewing already... You might want to share your thoughts about the site @ideocl4st ?
How do you like it in comparison to your previous workflow?

For me it felt very intuitive and I think we could lower the barrier for people to help translating...

I also added the requested FAQ on the Cockatrice wiki: ![Translation FAQ](https://github.com/Cockatrice/Cockatrice/wiki/Translation-FAQ)

**Comment by ideocl4st** [comment]
@tooomm 
I love it. I actually wondered whether we couldn't have something like this the other day and BOOM here it is.

A slight concern is keeping the source language's translation file up-to-date with the latest commit on master branch.

Some new strings were added in the latest commit ("can see hands", "see hands", etc. for spectator options), but I don't see the new strings in Transifix's source language file yet.

This means that if I wanted to build a test client with the translation that is done on Transifex, some strings would not be translated (or worse, vanished) on the built client.

Do maintainers have to manually upload the translation file whenever it gets changed? or is there a way to better handle this in Transifex?

**Comment by Daenyth** [comment]
When we modify strings in code we need to run cmake with UPDATE_TRANSLATIONS and commit the ts change along with the code

**Comment by ctrlaltca** [comment]
So, the workflow should be something like this:
 1. An addition / change a of string is made in the source code.
 2. developer runs "cmake -DUPDATE_TRANSLATIONS=ON"; the files for english (cockatrice_en.ts and oracle_en.ts) gets updated.
 3. The change gets committed to github
 4. Transifex picks up automatically the modified files (resources in transifex's own jargon) from github every 24h. Alternative: a team manager (actually: me, @Daenyth, @tooomm, @ZeldaZach) manually uploads the updated file from the web interface or from the "tx" cli.
 5. Translators see there are some new strings that needs translation (and hopefully translates them)
 6. a developer fetches the new translations from transifex and opens a PR on github.

Now, things that needs to be cleared out:
 * step 1: do we want every PR that adds/changes strings to include the updated english resources, or we prefer to do step 2 manually every some time when it's needed?
 * step 5: how to notify translators that they need to translate new strings? need to check transifex docs, i hope there's some form of notification for team members.
 * step 6: i've currently set up the cli: http://docs.transifex.com/developer/client/ to do this operation myself when needed. There's also an automated way to do this: http://docs.transifex.com/developer/integrations/github but it requires a server running a ruby web framework that automatically opens a PR when a translation reaches the 100% mark (i'm a bit skeptical this could work)

**Comment by ideocl4st** [comment]
Step 1: Just to be clear - Does Transifex automatically updates the source language file (cockatrice_en.ts and oracle_en.ts) and updates the strings on its interface? 
If that's the case, as long as it doesn't cause a problem with existing translations I think it would be a necessity for translators to see new strings as soon as possible.

Step 5: 
![screen shot 2015-02-12 at 21 19 37](https://cloud.githubusercontent.com/assets/2484055/6167275/e5771e26-b2fc-11e4-9e2a-658d941f5adb.PNG)
I don't know how and why I got this message, but I think this can be a good enough way to notify people.

Step 6: Doing this whenever we are about to upload a weekly build should be a good time to push all the new translation.

**Comment by ctrlaltca** [comment]
step 1: no, we need to extract the strings from the cpp files and update the *_en.ts files manually using cmake/make. Then transifex will notice that the *_en.ts files have been updated, load them  and update its interface.
step 5: nice, i'll rtfm on how to nofify translation teams.
step 6: i agree

**Comment by ideocl4st** [comment]
Ah, so as long as *_en.ts files are committed to Github it will be automatically picked up by Transifex?
Then If it's not too much of a hassle for developers then it would be nice to update them whenever new strings are created.

**Comment by ctrlaltca** [comment]
yup, if this is the way we'll decide to follow it will be better to update the cmake scripts in order to update only the *_en.ts files and not the files for the other languages, to avoid merge problems when pulling the new translations from transifex.

**Comment by tooomm** [comment]
Step 5: I posted on the team message board / forum. Not sure if translators can do this too and if everyone (including translators) receive the notification you got... (but I'm sure you can disable them...)
@ideocl4st is right about the "see hands" strings changed/included by poix/zach a few days ago.
When are the cmake scripts normally run?

Step 6: Should we just include reviewed translations (aka two-man rule) to get high quality and mostly complete translations (just include 80%+ e.g.)? Or grab and include everything we can get?

**Comment by ctrlaltca** [comment]
cmake scripts can be run manually by anyone in order to update the *_en.ts files; they then ned to open a PR and get the modified files actually added to github.
Following @ideocl4st's proposal we could create a "rule" asking developers opening a PR where strings have been changed to include the updated *_en.ts files, so that they gets merged in cockatrice with the PR itself and picked up automatically by transifex the next day.

**Comment by ctrlaltca** [comment]
@Daenyth is it ok for you to require developers to regenerate the *_en.ts files and add them to their PR if their PR adds/changes some strings?

**Comment by Daenyth** [comment]
I'm ok with putting that in CONTRIBUTORS and nagging people on PRs (nagging
is what I do best).

Remembering to nag on it might not be perfect but I expect that other
reviewers will help me out here ;)
