### ISSUE TITLE
Alt + Number to create special characters in chat also activates token creation.

### ISSUE THREAD

**Issue by Psithief** [Cockatrice/Cockatrice#653]
Can we disable this shortcut when the game chat is in focus so I can use the fancy Alt+### codes to draw symbols like
- Æ
- —
- …
- •

without creating tokens on the board?

**Comment by ZeldaZach** [comment]
You can write "AE" "-" "..." and they are equivalent to what you're trying to do

**Comment by Psithief** [comment]
I wunt da progum to werk gud. :+1:

**Comment by ZeldaZach** [comment]
mmmm... NOHH xD

**Comment by ZeldaZach** [comment]
You can re-assign shortcuts, and it's a Windows issue only

**Comment by ebbit1q** [comment]
also you can unfocus the chat now with a keybind
