### ISSUE TITLE
Prevent some game actions when users disconnect

### ISSUE THREAD

**Issue by poixen** [Cockatrice/Cockatrice#657]
Right now if a user drops due to bad internet for a few seconds, this gives the opponent an oppertunity to cheat. Be it with a shuffle, scry or another form of game state manipulation.

To solve this we should have a server side check to see if any users are in the room, but disconnected. If true, then no actions should be taken, a message should be returned saying actions can resume when the player reconnects. 

If the player does not reconnects, then the room owner may kick the player and then the actions may resume.

**Comment by Daenyth** [comment]
What if the room owner is the one who is disconnected? This seems like it could get in the way of game rejoin functionality.

I like the idea of locking the actions while a user is disconnected in the case of a two player game but I think as long as there's at least two players still in game it should proceed

**Comment by Daenyth** [comment]
For multiplayer*

**Comment by poixen** [comment]
Doesn't ownership of the room transfer at some point?

**Comment by tooomm** [comment]
or they agree on cheating together.. ;)

**Comment by Daenyth** [comment]
I don't think it's worth holding up the game for that.

Ownership of the room never transfers

**Comment by ZeldaZach** [comment]
I can't express myself in words for this, but it should be dealt with somehow

**Comment by Psithief** [comment]
Wouldn't this work better if each room had a log buffer?

**Comment by ZeldaZach** [comment]
I don't see how we can do much about this.
