### ISSUE TITLE
Problem with Card Database Sets

### ISSUE THREAD

**Issue by Redvader8** [Cockatrice/Cockatrice#658]
For some reason, whenever the third time I close cockatrice on my Mac, my sets change without me actually going in and changing them. I like to have the unhinged set as the first on the list so I can use full art for my lands, but when i close out the third time, cockatrice moves my set order and places unhinged as 3rd on the list rather than first, sometimes it goes to 6th or 7th, but most recently its gone to 3rd. Any suggestions as to what is wrong or how to fix this?

**Comment by Daenyth** [comment]
I've never seen this before but honestly I never use the set ordering feature myself...

**Comment by ZeldaZach** [comment]
Please remember you need to hit "Save Set Ordering" otherwise it won't save...

**Comment by Redvader8** [comment]
I have clicked Save Set Ordering, but it still occurs, but it only occurs after the third time opening the cockatrice app

**Comment by ZeldaZach** [comment]
If this still is an issue for you @Redvader8 please feel free to reopen. No other Mac users have reported an issue like this.
