### ISSUE TITLE
Menu entries get rearranged when enabling localization

### ISSUE THREAD

**Issue by ZeldaZach** [Cockatrice/Cockatrice#659]
On my Mac, if you change translations the entire UI layout is changed

***Before:***
![screenshot 2015-02-01 11 24 30](https://cloud.githubusercontent.com/assets/7460172/5992785/95d7a98a-aa05-11e4-8e2f-7ca66454ea26.png)

***After:*** (I went from English -> Spanish -> English)
![screenshot 2015-02-01 11 25 28](https://cloud.githubusercontent.com/assets/7460172/5992788/95d89a16-aa05-11e4-9c75-32037431f6fe.png)
![screenshot 2015-02-01 11 25 41](https://cloud.githubusercontent.com/assets/7460172/5992786/95d7cd2a-aa05-11e4-81df-1330b74c2d8e.png)
![screenshot 2015-02-01 11 26 09](https://cloud.githubusercontent.com/assets/7460172/5992787/95d7e5e4-aa05-11e4-8472-a41c1a77dfa9.png)

You'll notice:
+ The `Help` tab is created on the top
+ `About Cockatrice` is moved to the `Help` tab
+ `Preferences` is moved to the `Cockatrice` tab and is renamed `Settings`

I tried restarting after changing the language (English -> Spanish) and it had the Help tab on it, but if I restarted with it in English (Spanish -> English) then it looked "normal" to me.

I've noticed this bug for months on Mac OSX going all the way back to Snow Leopard (10.6).
Can someone on windows test if this is the case for them as well?

**Comment by Daenyth** [comment]
http://qt-project.org/doc/qt-4.8/qmenubar.html#qmenubar-on-mac-os-x

**Comment by ctrlaltca** [comment]
Yup, some menu options should not be localized under OSX.
Another point is about having two "cockatrice" menus: i suppose that makes it hard to explain to newbies how to do basic stuff, eg:
 * *win support guy*: now, go to the cockatrice menu and press connect
 * *osx newbie*: which cockatrice menu? i have two!
 * *win support guy*: lolwut?
