### ISSUE TITLE
Checkbox issues OSX

### ISSUE THREAD

**Issue by JineteDV** [Cockatrice/Cockatrice#661]
Just the newest update for OSX today. 
-The 'shuffle when closing' box isn't checked by default.
All the sort by type, sort by name, and pile view check boxes between all the zones are all connected. When once is changed, that same box is changed for all the other zones. Would be nice if that wasn't a thing.

**Comment by ZeldaZach** [comment]
Did you build your own client? I experience none of the above on OSX 10.10.2

**Comment by JineteDV** [comment]
I did not

**Comment by ZeldaZach** [comment]
Can you try building your own client on mac?

**Comment by Daenyth** [comment]
I think your issue is already fixed
