### ISSUE TITLE
"Analyze on deckstats.net" needs to be updated for the new deckstats interface

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#662]
osx mavericks - clicking analyze with a loaded deck, nothing happens.

**Comment by ZeldaZach** [comment]
Issue occurs on OSX Yosemite (10.10.2) as well

**Comment by ZeldaZach** [comment]
Occurs on Windows as well

**Comment by ZeldaZach** [comment]
I know this worked in early November, 2014

**Comment by Daenyth** [comment]
I think deckstats changed their site. Looking at http://deckstats.net/upload-deck/en/ though it accepts .cod file upload so we should update the code to use that.

**Comment by tooomm** [comment]
Not working for me on windows as well with build from 29th january.
Used to work ~2 weeks ago.

**Comment by Psithief** [comment]
Really? I'm getting an actual error message from Cockatrice.

```
Error downloading http://deckstats.net/index.php - server replied: Service Temporarily Unavailable
```

Did they change things or are they just down for maintenance?

**Comment by Psithief** [comment]
We should probably check the website before we try fixing Cockatrice:

```
We cannot connect to the deck database right now. This is usually due to a scheduled backup or database maintenance, which should be completed within a few minutes. Please refresh this page in a minute to try again!
In the mean time you can still visit our forums!
```

**Comment by ZeldaZach** [comment]
Deckstats.net was down when I last checked an hour ago. This has nothing to do with the bug we've experienced though as I haven't been able to use the feature in client for a while now.

**Comment by Psithief** [comment]
Good to know — I haven't had a chance to see the new interface.
