### ISSUE TITLE
Settings selectors sometimes get squashed

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#663]
This happens for me on OSX, but not 100% of the time. Has anyone seen this on windows/linux?

![wat](https://camo.githubusercontent.com/e046bb6b74d3ecdc9e9f2c4f415aae4cbb58b66e/687474703a2f2f692e696d6775722e636f6d2f73576d4f5a75462e706e673f31)

**Comment by Psithief** [comment]
Haven't seen on Windows.
(Sorry, not the most useful comment!)

**Comment by ZeldaZach** [comment]
I don't experience this ever on OSX 10.10.2

**Comment by kaiserfro** [comment]
I have not seen this in Xubuntu 14.10 32-bit with QT 5.3.0.

**Comment by ctrlaltca** [comment]
I've finally's been able to reproduce this.
While changing language the different translated strings changes and their width, too. It seems that Qt doesn't handle the repositioning automatically, so we'll need to force e relayout.

**Comment by Daenyth** [comment]
I've experienced it without changing my language settings.

**Comment by ZeldaZach** [comment]
Is this still a known issue?

**Comment by tooomm** [comment]
it happens if you change the language because all strings get exchanged instantly, but not the positions or icons. if you reopen the window it's fine.
maybe that caused the issue?

**Comment by Daenyth** [comment]
I'll try to confirm this as soon as I can
