### ISSUE TITLE
Unregistered users create new PM tabs on every new message

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#664]
I almost certainly introduced this with #660

**Comment by woogerboy21** [comment]
Can you give a bit more detail on this?  Is a new tab being created even when responding to existing PMs?  Is the new tab being created even though ignore is enabled resulting in tabs that are blank (or empty)?

**Comment by Daenyth** [comment]
Ignore disabled. It made new tabs as you say. Z can't repro so maybe it was something else

**Comment by ZeldaZach** [comment]
I'm thinking it was something else.

Here's something that may or may not be relevant. If you double click on a person's name in the main chat room a few times, multiple chat tabs will be opened and only one will "work" for receiving messages. It bugs the system out.

![screenshot 2015-02-02 23 32 54](https://cloud.githubusercontent.com/assets/7460172/6014533/e5677816-ab33-11e4-8990-8ef2b669adc4.png)

**Comment by Daenyth** [comment]
Maybe I did that

**Comment by ZeldaZach** [comment]
Can you check into this again possibly, @Daenyth ?
