### ISSUE TITLE
oracle svg icon not correct?

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#665]
Cockatrice/oracle/resources/oracle.svg

In the preview here on github the "O" is not aligned correctly in front of the card image.
All others seem fine. Can't open appicon.icns though.

**Comment by Daenyth** [comment]
Can you give some screenshots

**Comment by ctrlaltca** [comment]
IIRC the icon has been created with Inkscape and then exported in the other raster formats.
My 2 cents: github's svn preview is not able to use/find the specified font and is using another as a fallback, thus showing an unaligned "O".

**Comment by tooomm** [comment]
Seems to be a render problem within the browser.
Since you asked for screens I tested it with Chrome as well.

Firefox 35 on github site:
![ff35](http://fs1.directupload.net/images/150202/oyp7r2rt.png)

Chrome 32 on github site:
![chrome32](http://fs1.directupload.net/images/150202/d7pqrmk4.png)


I digged deeper and checked the Cockatrice/oracle/resources/oracle.svg file Git Desktop downloads within different browsers offline:
![all3browser](http://fs1.directupload.net/images/150202/nkjg46i8.png)

I don't have vector graphics program to test it there...

**Comment by ZeldaZach** [comment]
@tooomm Does it not look right on the physical application when you run it, or just when you view the SVG?

**Comment by tooomm** [comment]
Its not uniform:

![oracle svgs](http://fs2.directupload.net/images/150204/wwuh78hw.png)
Windows search looks nice, but the application itself has the same little miss-aligned icon with bold font as chrome shows on the github preview.
Oracle.exe icon in explorer looks the same as in windows search.

Just thought the svg is "wrong" and needs to be replaced. Not that big of an issue anyway.

**Comment by Daenyth** [comment]
If it works in the build I'm not inclined to change it
