### ISSUE TITLE
Disconnecting should disable chat & pm windows instead of closing them

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#666]
If you come back to your computer and find that you've timed out, you lose all trace of messages people have sent you in the mean time.

Disconnecting should disable the tabs.
Reconnecting should refresh and reenable them.

Connecting to a new server should clear the old tabs

**Comment by ZeldaZach** [comment]
I like this idea a lot. Maybe messages can have a "hidden" column that only activates when you physically close down the private chat message tab.

Messages where 'hidden = 0' should be all visible

**Comment by woogerboy21** [comment]
Is this resolved by #1474 ?

**Comment by ZeldaZach** [comment]
I would say so
