### ISSUE TITLE
Servatrice should inform mod users of all bans

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#668]
When servatrice handles a ban command, it should send an event message to all connected mods so that we can put something in chat locally.

**Comment by woogerboy21** [comment]
your not referring to some type of chat entry in the main chat room that only a certain user level can see are you?

**Comment by ZeldaZach** [comment]
That's what it seems like he's saying, @woogerboy21

**Comment by Daenyth** [comment]
That's what I'm saying.

**Comment by ZeldaZach** [comment]
Tested and works fully as expected. :shipit:

**Comment by ZeldaZach** [comment]
The groundwork for this is set in #1522 and will be ready to be closed on the next PR for bannings.
