### ISSUE TITLE
Lands have no cmc

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#669]

**Comment by ZeldaZach** [comment]
Is that a "duh" statement? Lands have a CMC of 0

**Comment by Psithief** [comment]
No CMC is not the same as Zero CMC.

It's missing when it should be zero.

**Comment by ZeldaZach** [comment]
Ohhh, meh. Yeah... 
How about something like `if (card->getType().equals("Land")) { setValue->CMC("0") }`

**Comment by Psithief** [comment]
The only game objects without CMC are things that can only exist in the Command Zone, like Emblems, Planes, Schemes, Phenomena, etc.

**Comment by Daenyth** [comment]
Good point on emblems... I was thinking I'd set cmc to "0" if absent

**Comment by ZeldaZach** [comment]
So I'd just like to re-iterate my idea then as stated above then ^^

**Comment by Daenyth** [comment]
Except Evermind

**Comment by ZeldaZach** [comment]
There are some cards, like  Ancestral Vision and Evermind that can't be cast as they don't have an official mana cost... My statement was only implying LANDS would have a default mana cost of 0 set... not every card

**Comment by tooomm** [comment]
some related comprehensive rules:

202.1b Some objects have no mana cost. This normally includes all land cards, any other cards that have no mana symbols where their mana cost would appear, tokens (unless the effect that creates them specifies otherwise), and nontraditional Magic cards.
Having no mana cost represents an unpayable cost (see rule 117.6). Note that lands are played without paying any costs (see rule 305, "Lands").

202.3. The converted mana cost of an object is a number equal to the total amount of mana in its mana cost, regardless of color.

202.3a The converted mana cost of an object with no mana cost is 0.

**Comment by Psithief** [comment]
Instants, sorceries, artifacts without a mana cost still have a converted mana cost. They just can't be cast without an effect that says "cast this without paying its mana cost".

So anything that can exist on the battlefield (permanents), can be cast (spells) or can be in the library/hand/graveyard (cards) must have a CMC.

**Comment by Psithief** [comment]
Is CMC a signed numeric field? What happens if I put 

```xml
<cmc>-1</cmc>
```
for emblem entries? :grinning:

**Comment by ZeldaZach** [comment]
WW3 @Psithief

**Comment by tooomm** [comment]
The one about emblems:
113.3. An emblem has no characteristics other than the abilities defined by the effect that created it. In particular, an emblem has no name, no types, no mana cost, no color, and no expansion symbol. 

(@Psithief: That's also related to my first token issue, Emblem is no card type - but it helps a lot with sorting and searching. So it should stay? Maybe with quotation marks? --> "Emblem"?)

**Comment by Daenyth** [comment]
It's a string field.

**Comment by ctrlaltca** [comment]
We're pulling the "cmc" field value directly from mtgjson's database. When a card has no cmc value in mtgjson, it has no value in our database, too. Mtgjson states about the value:
```
Converted mana cost. Always a number. NOTE: cmc may have a decimal point as cards from unhinged may contain "half mana" (such as 'Little Girl' with a cmc of 0.5). Cards without this field have an implied cmc of zero as per rule 202.3a
```
So, i see 2 possible solutions here:
 1. leave it the way it is,
 2. strictly follow rule 202.3a and set cmc to 0 when missing. If i understand the rules correctly, eg. Evermind has no mana cost, but its converted mana cost is 0.

**Comment by Daenyth** [comment]
You are correct. The current behavior means that it's not possible to use a
cmc 0 filter in deck editor
