### ISSUE TITLE
Enters the battlefield tapped flag needs expanding.

### ISSUE THREAD

**Issue by Psithief** [Cockatrice/Cockatrice#670]
oracleimporter.cpp
```c++
        bool cipt = (cardText.contains(cardName + " enters the battlefield tapped."));
```

This should actually check for any of the following:

* :name: enters the battlefield tapped.
* :name: enters the battlefield tapped with
* :name: enters the battlefield tapped and

Doing so would fix the [following cards](http://gatherer.wizards.com/Pages/Search/Default.aspx?action=advanced&output=spoiler&method=visual&text=+[m/::name::.enters.the.battlefield.tapped\s(with|and)/]) not entering tapped:

* Grimgrin, Corpse-Born
* Vivid Crag, Vivid Creek, Vivid Grove, Vivid Marsh, Vivid Meadow
* Hickory Woodlot, Peat Bog, Remote Farm, Sandstone Needle, Saprazzan Skerry
* Sphere of the Suns
* Leviathan

**Comment by Daenyth** [comment]
If you just remove the period it should work

**Comment by ZeldaZach** [comment]
I think @Daenyth is right...

**Comment by Psithief** [comment]
No good, that would suddenly include all the cards that say 'enters the battlefield tapped **unless**'

**Comment by Daenyth** [comment]
Nice catch
