### ISSUE TITLE
Cascade can't be performed.

### ISSUE THREAD

**Issue by jthemphill** [Cockatrice/Cockatrice#673]
Currently the acceptable way to cascade in Cockatrice is to drag cards from the top of the deck onto the table until you find a card that fits the requirements. The annoying part is dragging each and every card individually to fill the table up with stacks of three cards each, then separating the cards that were originally on the table from the cards that I just revealed while putting those back on the deck.

Here's the alternative I'm proposing:
- Replaces the "view top cards of library..." option and adds a "reveal top cards of library..." option
- Instead of taking you to a menu where you choose the number of cards, then spawning a zone with that number of cards revealed, the option now takes you directly to the zone.
- The zone contains a button and dropdown which allows you to reveal n more cards whenever the button is activated.

I'd be happy to implement if others think the design is sound.

**Comment by ZeldaZach** [comment]
Can you possibly make a crude example in paint or something? I don't think I understand

**Comment by MassCraziness** [comment]
If you get rid of the "view top cards of library", how am I going to Ponder or Sensei's Divining Top or Taigam's Scheming or Scry?

Please, no.

**Comment by ZeldaZach** [comment]
The way I've seen it done / how I do it is by dragging them onto the stack like this:

![screenshot 2015-02-03 18 03 09](https://cloud.githubusercontent.com/assets/7460172/6031906/31583aba-abd1-11e4-9a19-9ed23e6d4d23.png)

The cards change alignment on each new card added and they always list in stack order, so no matter where you drag the next card to on the stack, it will go on the very top of it.

**Comment by jthemphill** [comment]
@ZeldaZach - Thanks, the stack is a much better place to put cards than the table. It still gets pretty crowded, but it's better than what I was doing.

Here's an MSPaint relating to what I proposed. It's literally just the two steps of the "View cards" flow mashed together, in such a way that you can choose whether or not you want to reveal/view more cards based on the cards you've already seen. I don't think it's a very large change (and it definitely wouldn't break scry!), but I think it would make cascade much less painful to play.

![zone](https://cloud.githubusercontent.com/assets/887446/6035267/04f7d6a6-abe5-11e4-8226-d9a5aabe38eb.png)

**Comment by Daenyth** [comment]
The harder part of cascade is randomizing the cards at bottom. I'm not sure
it's exactly possible at this time

**Comment by LethalPigeon7** [comment]
This is purely adressing the convenience of a possible built in system for revealing them I believe, not the random order on bottom, I for one do not mind that not working at all, definitely not as much as the inconvenience of cascading exists, as it is my favourite keyword.

**Comment by MassCraziness** [comment]
The thing about looking at the top X cards before revealing to cascade is that.. Well, you could well end up looking at too many cards (if it is implemented that way).

**Comment by Daenyth** [comment]
You've accurately assessed the situation

**Comment by macraw83** [comment]
Probably the best way to fix would be adding an option to randomize "bottom X" cards from the library, but someone smarter than me would have to implement it

**Comment by tooomm** [comment]
Zach tried something like that already in https://github.com/Cockatrice/Cockatrice/pull/2689, but I don't recall the problem there.
