### ISSUE TITLE
Servatrice fails to create the log file if its folder does not exist

### ISSUE THREAD

**Issue by skwerlman** [Cockatrice/Cockatrice#674]
I've just compiled and installed servatrice from commit b7521ba, and after configuring and starting it, I kept seeing `QIODevice::write: device not open` in the terminal. Eventually, I noticed the server log didn't exist. After I created folder the log was supposed to be written to, the warnings went away.

**Comment by ctrlaltca** [comment]
Your os is? maybe the user running servatrice didn't have the rights to create that file?

**Comment by skwerlman** [comment]
xubuntu 14.04, and I was writing the log to `/home/username/.logs/servatrice.log`. And i meant to say folders, not files. Apologies, it's rather late here. Main issue edited.

**Comment by ctrlaltca** [comment]
Servatrice should "mkdir -p" the folder it's going to write its log to.

**Comment by Daenyth** [comment]
@skwerlman can you try the version from #682 and see if that fixes the problem

**Comment by skwerlman** [comment]
Tested and working, though there were errors when I built:
```
[ 96%] Building CXX object servatrice/CMakeFiles/servatrice.dir/src/server_logger.cpp.o
/home/wheeler/Cockatrice/servatrice/src/server_logger.cpp: In static member function ‘static void ServerLogger::hupSignalHandler(int)’:
/home/wheeler/Cockatrice/servatrice/src/server_logger.cpp:129:40: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
     ::write(sigHupFD[0], &a, sizeof(a));
                                        ^
/home/wheeler/Cockatrice/servatrice/src/server_logger.cpp: In member function ‘void ServerLogger::handleSigHup()’:
/home/wheeler/Cockatrice/servatrice/src/server_logger.cpp:141:43: warning: ignoring return value of ‘ssize_t read(int, void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
     ::read(sigHupFD[1], &tmp, sizeof(tmp));
                                           ^
[ 97%] Building CXX object servatrice/CMakeFiles/servatrice.dir/__/version_string.cpp.o
```
