### ISSUE TITLE
No sound on Xubuntu 14.10 with PulseAudio

### ISSUE THREAD

**Issue by skwerlman** [Cockatrice/Cockatrice#675]
Using cockatrice version b7521ba with QT5 and PulseAudio 1:4.0-0ubuntu22, I see the message `using null output device, none available` whenever cockatrice would normally play a sound.

**Comment by skwerlman** [comment]
This is still an issue with version f733daf18ad870fac616faae527db43975164c32 on Xubuntu 15.04 using QT5.4.1 and PulseAudio 1:6.0-0ubuntu6

**Comment by ctrlaltca** [comment]
Do you have the libqt5multimedia5 and libqt5multimedia5-plugins packages installed?

**Comment by skwerlman** [comment]
I was missing libqt5multimedia5-plugins.
Thanks for the fix, though there's no mention of those libs in the install instructions for Ubuntu.

**Comment by ctrlaltca** [comment]
Thank you for fixing the wiki.
