### ISSUE TITLE
There is no "Reveal top X Cards" feature

### ISSUE THREAD

**Issue by ZeldaZach** [Cockatrice/Cockatrice#678]
The option to "Reveal X cards.." from top of library seems to have gone-a-miss.

**Comment by Daenyth** [comment]
Likely from #597

**Comment by Daenyth** [comment]
Huh actually looking at the code it wasn't that. Did I imagine that we had this feature? I could have sworn you could reveal top x to other players

**Comment by ZeldaZach** [comment]
I made this ticket due to your statement... but I recall to reveal the top X I just flip them onto the stack like such: 
![screenshot 2015-02-03 18 03 09](https://cloud.githubusercontent.com/assets/7460172/6031638/1019ad9a-abcf-11e4-948f-a376d1db6d36.png)

**Comment by Daenyth** [comment]
Right but you can't fateseal like that because you're not supposed to see them yourself

**Comment by ZeldaZach** [comment]
Ahh yes... I think we should look into (re?) adding this feature to the service.

**Comment by ctrlaltca** [comment]
fixed in #1051
