### ISSUE TITLE
Using a macro causes the client to crash

### ISSUE THREAD

**Issue by poixen** [Cockatrice/Cockatrice#684]
Steps to reproduce:

+ version cb50fd0
+ make sure you have a macro mapped
+ start local game
+ use macro

**Comment by tooomm** [comment]
- version a31c15c (weekly from wooger 29th January)
 - working just fine on Win 8.1 (one player local game)

Observation:
If I test with 2 players it doesn't crash, but there is no text send. Maybe that's what you are referring to?

**Comment by woogerboy21** [comment]
Just curious.  Were you seeing the crashes when running a game from the server? Either 1 or 2 players?
