### ISSUE TITLE
Create github website

### ISSUE THREAD

**Issue by VanNostrand** [Cockatrice/Cockatrice#69]
github allows you to create a website for each project (http://pages.github.com/) and as there is still much confusion about where the cockatrice page is now, I suggest that such a site is created here.
It doesn't need to provide binaries if you don't want, but the page should contain information about the development, where public servers are and where to get/how to build binaries, because people use those pesky hosting services for two year old binaries.

**Comment by ZeldaZach** [comment]
Is this still open for discussion?
