### ISSUE TITLE
No Auto-Shuffle After Searching Library

### ISSUE THREAD

**Issue by racky54** [Cockatrice/Cockatrice#690]
I was playing before and I searched my deck for a land with a fetchland, but after I closed my deck it didn't say I shuffled my library, and the card on the top I saw from Courser of Kruphix was still the same. So, I tested it in a single-player game, and no matter how many times I opened and closed my library, the same card (a 1-of) was still on the top. If it matters, I'm on Mac OSX

**Comment by ZeldaZach** [comment]
We fixed this in the past week and should be on the weekly build by friday

**Comment by Daenyth** [comment]
@racky54 make sure you have the "shuffle" check box ticked. One build made it unchecked by default and made it remember the setting. If you check the box it should still work
