### ISSUE TITLE
Change Attach to Card shortcut (Ctrl+A) to something else.

### ISSUE THREAD

**Issue by Psithief** [Cockatrice/Cockatrice#691]
**Platform:** Windows 7 64-bit.
**Version:** Every version.

This is not a regression, I'm sure I've never seen it work in multiplayer.

The shortcut is Ctrl+A, it's probably conflicting with the "Select All text" shortcut common to most Windows applications.

I don't know why it works in Local games only, but even then it won't work if the chat text box has focus. (Related #653)

**Comment by Psithief** [comment]
Also related: 787773e
Sets the chat to have focus on game start.

**Comment by Nightfirecat** [comment]
Can confirm - I've tried on multiple occasions to do this in an active multiplayer game, and never had it actually work. Just checked with a local game, and it worked fine there.

**Comment by ZeldaZach** [comment]
Confirmed on Mac OSX 10.10.2 Yosemite

**Comment by skwerlman** [comment]
Does not seem to happen on Xubuntu 14.10

**Comment by poixen** [comment]
The reason this happens is that the chat has focus. Example:

Join a game.
Load deck.
Click on chat to greet, roll, decide plays.
Try to attach card -- **Wont work due to the chat having focus.**
If you click on the chat log to take the focus away it works.

**Comment by Nightfirecat** [comment]
Perhaps we need to decouple the shortcuts, or fall back on the ctrl+a shortcut if the chat's textbox is empty?

**Comment by Psithief** [comment]
Cockatrice should probably try to avoid using any shortcuts listed in http://en.wikipedia.org/wiki/Table_of_keyboard_shortcuts

**Comment by Daenyth** [comment]
We should also just bite the bullet and set up a ketbind config interface

**Comment by ZeldaZach** [comment]
@Daenyth Can we get another look into a keybind for the cockatrice service to override mac/window default commands?

**Comment by ctrlaltca** [comment]
Issue resurfaced and is being discussed in #1493. We now have configurable hotkeys, so maybe this is the good time to fix this.
