### ISSUE TITLE
Flags Fail

### ISSUE THREAD

**Issue by ZeldaZach** [Cockatrice/Cockatrice#692]
Quotted from @tooomm 

Just tested from build 0c32cfa:
![country code in details](http://fs2.directupload.net/images/150205/alqgt4gg.png)

My suggestions:
 - add a space between flag and "(xx)"
 - if there is no flag set, don't display "()", or make it e.g. "(not set)"

**Comment by ZeldaZach** [comment]
I'll look into this later today if somebody doesn't beat me. Seems pretty simple to me...

**Comment by Daenyth** [comment]
It should only take maybe 15 minutes to finish a fix

**Comment by Daenyth** [comment]
If they have no flag, just don't add the entire location row

**Comment by ZeldaZach** [comment]
I already fixed it. Will push in a few min.
