### ISSUE TITLE
filter by language

### ISSUE THREAD

**Issue by aeosynth** [Cockatrice/Cockatrice#696]
a pc version of this request from reddit: http://www.reddit.com/r/Cockatrice/comments/2usrty/feature_request_ignoreblock_countries/

since games generally require text communication, i would like to filter out users who do not speak my language; i would like to find users who do speak my language

for prior art, see dota2, a game which also depends on communication - users can select their language preferences. i'm sure there are many more examples

**Comment by ZeldaZach** [comment]
So are we going to be judging users based on the "country" they select for their account? Usually the game description explains what language it is, if it's not english (Like many people say "french" in their descriptions if they only speak french)

**Comment by aeosynth** [comment]
> So are we going to be judging users based on the "country" they select for their account?

yes, why not? if you speak only french and not english, good for you, but i'd rather play with someone else. you would be able to select multiple languages ofc.

the game description can describe anything, should we remove filtering entirely?

**Comment by MassCraziness** [comment]
I don't really see a problem with this. If you only speak English, then you should be allowed to play with people who speak English (and, likewise, not with people who can't).

No, I'm not saying we should just add filtering out countries. That's not the same thing. Nor am I saying we should not play with people who can speak the language, just not well.

**Comment by aeosynth** [comment]
there's another perspective to this issue - if you're not a native english speaker, it would be nice to find users who speak your native language

**Comment by Daenyth** [comment]
I already said I don't want this

**Comment by aeosynth** [comment]
you said you didn't want filtering users by country; this is filtering games by language. anyway, i won't push for this.

**Comment by Daenyth** [comment]
Cockatrice has no concept of language

**Comment by aeosynth** [comment]
it's a program, it can gain arbitrary concepts. that's just an implementation detail.
