### ISSUE TITLE
[Possible Regression] Filters for User's Games are no longer saved

### ISSUE THREAD

**Issue by MassCraziness** [Cockatrice/Cockatrice#698]
Before, when I right-clicked a user and hit "show this user's games", I could set a filter to show Unavailable Games and Password-protected Games, and then close the window out and it would save those settings and work for all users. Now, it no longer saves any filter settings, so I have to re-filter every time. It was really nice when it saved it, and now it's just a hassle having to constantly re-filter.

Possible culprit is #582

**Comment by ZeldaZach** [comment]
Experienced this as well

**Comment by ZeldaZach** [comment]
Fixed in #710
