### ISSUE TITLE
Servatrice user active/inactive account functionality oddity

### ISSUE THREAD

**Issue by woogerboy21** [Cockatrice/Cockatrice#70]
When an account is created in the user database for a user to log in.  If the account is set to "active = 0" (effectively inactive).  The user is still able to actually log into the server.  When the account is inactive, the user still needs to know the password to authenticate to the account but when logged in the account shows as "unregistered".  I would expect the behavior to be that if the account is registered and the account is set to inactive that the account not be able to be logged in or used.

**Comment by ctrlaltca** [comment]
Fixed in #1101. Unactive users can't login anymore.
