### ISSUE TITLE
[Suggestion] Tiny Leaders

### ISSUE THREAD

**Issue by LethalPigeon7** [Cockatrice/Cockatrice#701]
TL should be a gamemode, I see about 2-5 rooms/day, and haven't seen 5 ext rooms or block rooms in my life, not to mention "Hearthstone" and "Kaijudo", which I've never even heard of, so if those get to exist, I feel TL deserves to as well.

**Comment by ZeldaZach** [comment]
cc: @woogerboy21 

Also, this is a server configuration, not a development issue. This *should* be on the forum for woogerworks.
