### ISSUE TITLE
Cannot set focus to textbox with Tab.

### ISSUE THREAD

**Issue by Zenijin** [Cockatrice/Cockatrice#718]
In previous versions of the client the chat textbox in games could be focused on by hitting Tab.
Now, however, hitting tab during your own turn changes phases and hitting tab during an opponent's turn does nothing.

It would be nice if Tab were reverted to having standard application functionality (that being as a focus shifting key), or if some other keyboard shortcut were added for setting focus to the textbox.

Barring all of that, it would be REALLY nice if the focus was always just automatically on the textbox.

**Comment by poixen** [comment]
When was the last Time you updated. We now automaticly focus on the chat when you start a game. This makes it easier to communicate quickly and start playing.

**Comment by Zenijin** [comment]
I'm running whatever the latest version is from the Woogerworks client
download page.
I've tried and have not seen the bahaviour you're talking about. Focus is
never automatically set to the chat textbox.

**Comment by tooomm** [comment]
about Tab:
I like when it changes phases in your turn and does nothing at your opponents turn.
Cycling through the open Tabs like in a web browser is nice too. Chrome and Firefox use Ctrl+Tab for this.

The In-game chat textbox is focused after a game started (not created!), you should double check that again.
I would like it even more if the focus is set directly after joining (as spectator and player) or creating a game since I need/want to start chatting immediately.

**Comment by Daenyth** [comment]
I don't like tab. We changed it so that the Ctrl space key doesn't conflict
with Mac but I'm not a fan

**Comment by tooomm** [comment]
I doesn't know about the ctrl+space either. I always use the mouse for phases. 
But when I tried with Tab today it feels intuitive.

**Comment by Daenyth** [comment]
I dislike the idea of using a bare key as an action. What about <kbd>Ctrl+]</kbd> or <kbd>Ctrl+[</kbd> for phases?

**Comment by Daenyth** [comment]
I should just work on #130

**Comment by tooomm** [comment]
Are you talking about the cornered brackets?
I need to hit already two buttons on my keyboard to get those...

What do you think about Ctrl+Tab for phases and Tab for cycling open Tabs?

**Comment by Daenyth** [comment]
Ctrl tab is universally cycle through tabs, we can't change that. If we just make it Ctrl+space everywhere again it would be fine. We just need an exception for Mac because at translates Ctrl to cmd and cmd space is a system shortcut. Ctrl is all reserved for app level

**Comment by ctrlaltca** [comment]
Please note that ctrl+space is the default hotkey for IME (Input Method Editor) under windows and linux. The hotkey changed to WIN+space from windows 8 onwards.

**Comment by tooomm** [comment]
I tried the ctrl+tab before and got confused because it does nothing. Therefore I mentioned it in two of my comments above.
But it is working actually and I like it!

You just need to hit the new created game tab once (just a click in the black field on the left, inside the chat log or in the edit chat line is working!) to get it focused and make ctlr+tab work.
Maybe you ran into the same problem and this is sufficient for you @Zenijin ?

**Comment by Zenijin** [comment]
I'll have to try that when I get a chance, but my point remains.

It doesn't make sense to have the keys behave in a non-standard way. It's counter intuitive. Ctrl+Tab should cycle through open tabs in the client. Just hitting Tab should cycle focus in controls.

As for changing phased, I think it would make more sense to make use of either the Function keys (F1 through F12) or Ctrl+Number for the phase/step number. 

<div>-------- Original message --------</div><div>From: tooomm <notifications@github.com> </div><div>Date:10-02-2015  9:04 AM  (GMT-05:00) </div><div>To: Cockatrice/Cockatrice <Cockatrice@noreply.github.com> </div><div>Cc: Zenijin <bradburyw@gmail.com> </div><div>Subject: Re: [Cockatrice] Cannot set focus to textbox with Tab. (#718) </div><div>
</div>I tried the ctrl+tab before and got confused because it does nothing. Therefore I mentioned it in two of my comments above.
But it is working actually and I like it!

You just need to hit the new created game tab once (just a click in the black field on the left, inside the chat log or in the edit chat line is working!) to get it focused and make ctlr+tab work.
Maybe you ran into the same problem and this is sufficient for you @Zenijin ?

**Comment by Zenijin** [comment]
Alternatively, another idea. Changing phases could be done with Ctrl+Up/Down. I don't think that currently does anything, does it? 

<div>-------- Original message --------</div><div>From: tooomm <notifications@github.com> </div><div>Date:10-02-2015  9:04 AM  (GMT-05:00) </div><div>To: Cockatrice/Cockatrice <Cockatrice@noreply.github.com> </div><div>Cc: Zenijin <bradburyw@gmail.com> </div><div>Subject: Re: [Cockatrice] Cannot set focus to textbox with Tab. (#718) </div><div>
</div>I tried the ctrl+tab before and got confused because it does nothing. Therefore I mentioned it in two of my comments above.
But it is working actually and I like it!

You just need to hit the new created game tab once (just a click in the black field on the left, inside the chat log or in the edit chat line is working!) to get it focused and make ctlr+tab work.
Maybe you ran into the same problem and this is sufficient for you @Zenijin ?

**Comment by tooomm** [comment]
Just stumbled upon this...

We have custom changable shortcuts since a while. There are also shortcuts added to focus and unfocus the chat in a game. Not exactly what you asked for, but should be very helpful.

**Comment by ebbit1q** [comment]
see https://github.com/Cockatrice/Cockatrice/pull/3898
