### ISSUE TITLE
"You have been kicked" modal UX could be better

### ISSUE THREAD

**Issue by Psithief** [Cockatrice/Cockatrice#719]
The new "you have been kicked" modal dialog box (#697) is not restricted to the tab that generates it, so it interrupts whatever other activity the user might have been doing.

Being kicked out of a game is not important enough to interrupt the entire application. If the user has changed the active tab to something to something else, he/she is clearly not interested in the game for the moment.

**Comment by Daenyth** [comment]
What do you think of the workflow I mention in #721?

**Comment by Psithief** [comment]
> Here's my ideal workflow:

> * client receives kick event
* Lay grey transparent mask over entire game tab contents
* On top of the mask show a flat message box with the kick message
  * Not a modal, something more like the card zone displays but not movable - locked to center screen
* Tab gets updated icon
* QApplication::alert

Something that immediately comes to mind:

* Does the mask go away after the user has acknowledged the message box?

**Comment by Daenyth** [comment]
No, I don't think so. There's nothing you can do in a game once you're kicked from it

**Comment by Psithief** [comment]
…except take screenshots of the last state.

Why take that away from people after they have already acknowledged the state change?

**Comment by MassCraziness** [comment]
Why do we need to take a screenshot of a game we've been kicked out of?

"HURR DURR LOOK AT WHAT I HAD WHEN THAT LOSER KICKED ME!" Yeah, no? What's really the point of this. What does that grant anyone? If you want to see that gamestate we should update replays to have timestamp navigation and fast forwarding and other functions.

**Comment by Psithief** [comment]
More than enough Cockatrice users *are* childish pricks, so this is going to remain relevant.
Cockatrice is developed for reality, rather than some unattainable ideal, right? :smirk:

**Comment by MassCraziness** [comment]
That doesn't mean we need to enable people with more ways to *be* childish pricks, does it?

**Comment by catmanjan** [comment]
@MassCraziness why are you trying to be the internet police? If I want to have a chuckle with my friend for getting kicked for having 40 X/X hydras on the field why shouldn't I?

**Comment by Daenyth** [comment]
Making it able to be dismissed would be somewhat annoying since I'd want to make the game controls all locked and disabled so it's clear you cannot interact with them. It would add code to it that I don't really think is useful.

**Comment by anoda9** [comment]
To me, the current (or previous, maybe I'm behind on versions) implementation of being kicked worked just fine. There certainly doesn't need to be a pop-up box that gets in the way of everything to announce you've been kicked. 

There are two improvements for the previous implementation (text message in the chat) that I could see:
- The "you have been kicked" message could be in a different color/bold text so it's easier to notice in the game log.
- The exclamation point that indicates activity in a tab you're not focused on could be a different color when you're kicked - a green exclamation point for normal activity, a red exclamation point for being kicked.
