### ISSUE TITLE
Move card menu does not work in 2 player local game

### ISSUE THREAD

**Issue by grandmasterv** [Cockatrice/Cockatrice#72]
In version `92ff503` of cockatrice on Windows 7 64bit the "Move" context menu does not seem to work on any cards that belong to the non-active player. 

For example, scrying when it is not your turn you cannot move cards to the bottom of your library.

**Comment by ZeldaZach** [comment]
I don't know if the issue is fixed, but I was able to successfully scry for both AP and NAP by right clicking on the respective deck

**Comment by grandmasterv** [comment]
Tested with latest builds and it works for me now.

Thanks!
