### ISSUE TITLE
Feature Request: Save/Load card filters in Deck Editor

### ISSUE THREAD

**Issue by littleaj** [Cockatrice/Cockatrice#722]
In the deck editor, I find myself creating similar filters every time I create or edit a deck. I would like the ability to save the current filter and load it again in a different deck editor instance. The saved filters should be given unique names.

Variations of this Feature:
1. Default filters for decks.
   Use case: When editing standard deck, Jim only wants to see standard legal cards.
2. Default filter for deck editor. If Variation 1 is also implemented, any default filter for a deck would override the editor's default.
   Use case: Jim only plays Modern and wants the deck editor to filter out cards which are not Modern-legal by default.

Implementation suggestions
1. An editable drop-down box for saving loading filters. To save, enter the name of the filter and click save/press enter (the newly saved filter is then selected). To load, click drop-down and select the desired filter.

**Comment by Daenyth** [comment]
This sounds like a nice feature - especially for formats like TL

**Comment by ZeldaZach** [comment]
You are able to copy/paste search requests into the search bar nowadays, so you can use that instead of the widget.
