### ISSUE TITLE
Feature Request: Filter to hide games created/hosted by people you ignore

### ISSUE THREAD

**Issue by DavidHouse369** [Cockatrice/Cockatrice#724]
Hi, I was wondering if it would be at all possible to add a feature to the ignore list that would prevent games created by people on that list from showing in the games list?

Obviously not a high priority as you can simply choose not to join their game. The benefit comes when you ignored someone a while ago and don't recall their specific name, instead of checking your ignore list, their game simply won't show.

As I said, it's not really a necessity, just a simple feature that would fit well I think.

Thanks

**Comment by Daenyth** [comment]
Seems reasonable. I can add a new filter for it.

**Comment by tooomm** [comment]
I like this a lot. Should be as simple as compare the Creator/Host (https://github.com/Cockatrice/Cockatrice/issues/2108) against your individual ignore list.

**Comment by ZeldaZach** [comment]
Sounds like a localized change; I might be able to look into this at some point
