### ISSUE TITLE
Deck Editor "copy to clipboard" should sort and add comments

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#725]
When I ctrl+c from the deck editor, I get my deck file in the order I added cards.

It would be nice if instead it sorted it according to the same rules as the display, adding in the `// Creature` comments and so on.

**Comment by ZeldaZach** [comment]
I tried looking into this, but I wasn't able to find a way to do this yet. Will re-evaluate again in the future.
