### ISSUE TITLE
Feature Request: Account Management Tab

### ISSUE THREAD

**Issue by woogerboy21** [Cockatrice/Cockatrice#730]
Add a tab that when logging in as a registered user the user can manipulate the account information for there account.  Users should be able to update/manipulate the following portions of there account:

```
| realname         | varchar(255)             | NO   |     | NULL    |                |
| gender           | char(1)                  | NO   |     | NULL    |                |
| password_sha512  | char(120)                | NO   |     | NULL    |                |
| email            | varchar(255)             | NO   | MUL | NULL    |                |
| country          | char(2)                  | NO   |     | NULL    |                |
| avatar_bmp       | blob                     | NO   |     | NULL    |                |
```

Also, there should be a tab that allows moderators/admin's manipulate the following aspects of a user account:
```
| name             | varchar(35)              | NO   | UNI | NULL    |                |
| realname         | varchar(255)             | NO   |     | NULL    |                |
| gender           | char(1)                  | NO   |     | NULL    |                |
| password_sha512  | char(120)                | NO   |     | NULL    |                |
| email            | varchar(255)             | NO   | MUL | NULL    |                |
| country          | char(2)                  | NO   |     | NULL    |                |
| avatar_bmp       | blob                     | NO   |     | NULL    |                |
| active           | tinyint(1)               | NO   |     | NULL    |                |
```

I'm welcome to any additional idea's from the current moderation staff on this matter since they would have better insight as to what tasks for account management are done more frequently.  I know for me personally being able to activate an account is the most used task.

**Comment by MassCraziness** [comment]
Activating an account/resending the verification is most used. However, I have had to add avatars for people, and change their country and email as well, as well as resetting a password. Just from personal experience.

**Comment by woogerboy21** [comment]
I have a feeling that if users had an easier way to get to and manipulate there account information in client that they would be more inclined to actually fill in the information themselves.

**Comment by MassCraziness** [comment]
I agree. It would also make it easier to help users out with account problems.

**Comment by tooomm** [comment]
I'm not sure if gender/country/real name should be that easy to edit repeatedly. People might screw around with it if over and over again.
Just allow initial setup and edits over the account link in browser or they need to ask a mod?

I would like to see that tab merged with the user lists tab we have right now (renamed to account).
The friends- and banlist is connected to your account anyway.
The right side (userlist) is a mirrow, so we can free up some room there?

**Comment by Daenyth** [comment]
I was already planning to add this, I just hadn't ticketed it

**Comment by Daenyth** [comment]
@tooomm what do you mean about the user list?

**Comment by woogerboy21** [comment]
@tooomm : users are free to edit that information now.  Why would you want to restrict the ability for users to edit those type of account information components?  All I see as an outcome by doing that is they simply will not fill the information in.

**Comment by tooomm** [comment]
@Daenyth 
That's the "User lists" tab right now:
![user lists - account management tab](http://fs1.directupload.net/images/150211/dhzomkr2.png)
The red part on the right is not needed (just a mirror) and can be used to display more account information + the edit stuff.

@woogerboy21 nvm. Was just throwing ideas... it's not the most reasonable feature, though.

**Comment by Daenyth** [comment]
I'm not sure what you mean by "just a mirror" - The contents are not
available anywhere else in the UI. It contains all users connected to
the server - the room list only has users inside the room. Especially
as we add user rooms they will continue to not be the same

**Comment by tooomm** [comment]
You are right. I should get some sleep. :)

**Comment by woogerboy21** [comment]
He does bring up a good point that there is a lot of wasted space on the tab.  Not saying the account information functionality should be worked into the tab but it may be possible to and recouping wasted space.

**Comment by Daenyth** [comment]
We could move buddy & ignore to one column vertically separated

**Comment by woogerboy21** [comment]
I was thinking more to add the information into the user details box in the upper right and allow for editing of it.  You may have to shrink the user list below but it wouldnt be by much.  Just a thought.

**Comment by tooomm** [comment]
"Users online" (User lists tab) should be renamed to "Users at the server" or "Users connected to the server"... :D
Will avoid confusion and is uniform to "Users in this room" in the "Chat Room" tab.

I'm still a supporter of the possibility to add short notes next to friends (met at gp, L2 judge, always up for tiny leaders...) or people I ignore (left drafts several times, ...) to keep track of them.
It came up once in the main chat I think. This could be considered if the layout gets reordered.

**Comment by Daenyth** [comment]
User notes will happen. A plain text field and an unanchored live search
will work nicely I think

**Comment by poixen** [comment]
If anything we should add some kind of profile tab, and move all the userdata from the userlist tab and put it in there. You should also be able to edit your details there.

**Comment by tooomm** [comment]
is this done now with #1210 btw? :)
