### ISSUE TITLE
FYI: #hearthsim IRC channel for Hearthstone Simulation/development

### ISSUE THREAD

**Issue by jleclanche** [Cockatrice/Cockatrice#734]
Hi guys

This is a quick heads up on a channel I created originally for [Fireplace, my Hearthstone simulator](https://github.com/jleclanche/fireplace): #hearthsim on Freenode. The channel is centered around HS simulation and simulator development and welcomes theorycrafting, reverse engineering, internals talk etc.

We have several devs and contributors from various communities and I figure this may be of interest to anyone here who is into Hearthstone. :)

The channel is fairly quiet but very high SNR. Feel free to ping me (jleclanche) if you swing by. Enjoy!

**Comment by ZeldaZach** [comment]
While it's great knowing about your IRC channel, this ticket unfortunately has nothing to do with Cockatrice's development.

**Comment by Daenyth** [comment]
If there's software support you need to make the game more playable I'd be
happy to figure out what to add
