### ISSUE TITLE
some shortcut makes freeze cockatrice, popup open a lot of random windows

### ISSUE THREAD

**Issue by Marcel-Brouette** [Cockatrice/Cockatrice#739]
Hi, 

I'm currently on Elementary OS which is based on ubuntu. I had absolutly no problem with the previous version. I have update my client 3 day ago. There is a lot of new features, thanks for that ! But I also have a lot of bug on linux : 

- Ctrl + w and Ctrl + I make cockatrice totally freeze, I can only kill the soft and restart.
- Ctrl+'+' and ALT+'+', (to change  P / T) doesn't work anymore.
- custom message with Ctrl+1, Ctrl+2, Ctrl+3, ... doesn't work anymore.
- right click on library make a square in top left of my screen which is stay on top of any other windows ...
- each time a popup appears (like hand or library), a lot of empty windows appears. they disappears way I close the popup.

(the others shortcut seems to be ok.)

[I made a video to illustrate the weird square and the apparition of windows.] (http://mtg-peasant.com/WebService.php?action=video&id=300)

am I the only one to have this issues ?

**Comment by Daenyth** [comment]
What was the previous version you had installed? Last week's weekly build? Summer magic? Some weekly in between? A version before summer magic?

**Comment by Marcel-Brouette** [comment]
My old .local/data/Cockatrice has been created the 1 May 2014. It's possible that I made others install between this date and now, but not more than one. I'm sorry but I don't remenber better than that ...

anyway, on the bug which freeze cockatrice, in fact it doesn't freeze anything but the new windows (to roll a dice, create a token or view top cards) appears behind the main window. So I though cockatrice was just freezing but I had to do an 'ALT'+'TAB'  in order to make the popup window appears.

If you need to confirm any change I can change et rebuild cockatrice on locally. I'm not good at all at C++ but I could search on my own and give you feedback if I find any clue. But in fact I don't have the level needed ^^

Thank for your good work.

**Comment by Daenyth** [comment]
Can you paste the full output of cmake from when you compiled it

**Comment by Marcel-Brouette** [comment]
http://pastebin.com/tSWuiB2s

**Comment by kaiserfro** [comment]
I can get the adding of Power and Toughness working by using CTRL+SHIFT+= and ALT+SHIFT+=.  In other words, the '+' is SHIFT+=.  I cannot get the shortcut of CTRL+ALT+SHIFT+= to work, in order to increase both P/T together.  Instead i get = and - in the "Say:" text box.

This is a bit awkward.  The shortcut probably ought to be CTRL+= and ALT+=.

Additionally, I cannot get the keypad+ or keypad- to work for the same shortcuts.

**Comment by Marcel-Brouette** [comment]
I notice that as a bug because this method doesn't work and I don't have any keypad

**Comment by ctrlaltca** [comment]
Qt 5.0.2? that version is so young it already proved to be prone to problems. If that's the most recent qt5 version you can get on your os, i'd try going for a qt4 based installation.

**Comment by Daenyth** [comment]
Unrelated, but I'd also suggest moving off of Elementary OS. The developers seem to be a little.. weird. I don't think it's going to stay around as a distro. http://liliputing.com/2015/02/elementary-os-devs-say-youre-cheating-dont-pay-free-software.html

**Comment by Daenyth** [comment]
As Ctrlaltca said, try compiling cockatrice with either a newer version of Qt5 or with Qt4.

If you still have issues after doing so, please re-open this ticket.
