### ISSUE TITLE
cmake should prevent compilation using Qt 5.0

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#741]
Qt 5.0 creates obnoxious confusing bugs, the cmake scripts should prevent compiling with that version

**Comment by ZeldaZach** [comment]
Can we just require 5.4.0?

**Comment by Daenyth** [comment]
I think it works OK with 5.2 or 5.3

**Comment by ctrlaltca** [comment]
Requiring 5.4 we will cut out some linux distro. From a quck poll:
 * Debian's oldest supported version is 5.3.2 
 * ubuntu's oldest supported version has 5.2.1
 * rhel/centos have 5.4.0 (epel repo)
 * slackware has 5.4.0 (slackbuilds)

I suppose 5.2 could be a good choice.

**Comment by skwerlman** [comment]
IIRC, the newest version in ubuntu's repos is 5.3.2. (They have a habit of
not updating)

**Comment by ctrlaltca** [comment]
Right, that's correct but only for "vivid". Older ubuntu versions: http://packages.ubuntu.com/search?keywords=qt5-default&searchon=names&suite=all&section=all

**Comment by Daenyth** [comment]
We should mandate whatever version is the lowest that compiles and doesn't
crash rather than base it off what common distros have available.

**Comment by ctrlaltca** [comment]
I agree with @Daenyth , but testing every combination of qt version/distro would take too much time. Since we know that ubuntu's 5.0.2 is problematic, should we just require at least 5.0.3?

**Comment by Daenyth** [comment]
That's what I was suggesting, I just didn't know the lowest working version
