### ISSUE TITLE
Server Deck Storage severely bugged

### ISSUE THREAD

**Issue by MassCraziness** [Cockatrice/Cockatrice#744]
Yesterday, I created 3 folders for decks. Modern, EDH, and Other. I log on today, only Modern is there. I delete this folder. Then, after the server went down for maintenance, the EDH folder was there (still no Other, though).

I deleted the folders because I don't really use server storage anyway, but that's really bugged and doesn't seem good at all.

**Comment by Daenyth** [comment]
Someone reported something similar on the forums
