### ISSUE TITLE
Feature request: Oracle text under card picture in editor

### ISSUE THREAD

**Issue by Asthner** [Cockatrice/Cockatrice#747]
It would be useful if in the editor tab, in the middle column under the selected card’s picture there was a box with the current Oracle wording for the card. It would make it much easier to browse through older cards – and there is a lot of wasted space in that column at the moment anyway.

**Comment by ZeldaZach** [comment]
I think this is a dupe

**Comment by Asthner** [comment]
I thought so too, but couldn’t find any such request among other issues.

**Comment by Daenyth** [comment]
I think it's in #97

**Comment by Asthner** [comment]
It is. Odd, I did a search for “Oracle text” but missed this. :)

**Comment by ZeldaZach** [comment]
Fixed
