### ISSUE TITLE
Deck Editor filter by set is broken

### ISSUE THREAD

**Issue by MassCraziness** [Cockatrice/Cockatrice#749]
![Error](https://cloud.githubusercontent.com/assets/10480542/6207169/c9a9e528-b560-11e4-8e8c-6e82fc1e5f6d.png)

As you can see, it's showing cards that are not in the set I tell it to filter by.

**Comment by ZeldaZach** [comment]
Seems that when I run "DGM" i get both Dragon's Maze and Judgement sets... odd

**Comment by MassCraziness** [comment]
Perhaps it has to do with the set name? Because in the sets filter, I can use the whole name "Judgment" to get Judgment. So perhaps it sees the dgm in Judgment and adds that to the filter.

**Comment by ZeldaZach** [comment]
@MassCraziness Good point... there's a high probability that's what is going on here

**Comment by Daenyth** [comment]
That's exactly what it's doing

**Comment by ctrlaltca** [comment]
From carddatabasemodel.cpp:135
```if (!cardNameSet.contains(info->getName()))```
We could change this to check for an exact match or, even better, an exact wildcard match. Thoughts?

**Comment by MassCraziness** [comment]
@ctrlaltca I think an exact wildcard match would be great. I really think anything would be fine, so long as if I typed in a short name it didn't look into long names.

**Comment by Psithief** [comment]
What about if All-Caps restricts the search to set codes only?
I already can't get a result for `frf` but can for `FRF`. So make it exclude other set names and include only set codes when the search is all captial letters.

**Comment by Daenyth** [comment]
The fact that it's case sensitive is bad already

**Comment by tooomm** [comment]
it can be handled via ordering maybe.
exact matches for the set code on top, followed by other matches. but that might bring up other difficulties we can't think of right now.

generally speaking I think case in-sensitiveness is better and easier to use/explain to the user.
but a way to look just for set codes within set search would be very usefull indeed.
new search item just for searching/filtering for set codes called "set code"?

**Comment by poixen** [comment]
@Daenyth can you decide what the expected behaviour should be? I am working on this at the moment. I have made it so that you can use lowercase to search for sets, "frf", "dgm" and so on, which you cant currently do right now.

Should I add anything else?

**Comment by poixen** [comment]
fixed in #849
