### ISSUE TITLE
Tab memory

### ISSUE THREAD

**Issue by FrozenSlave** [Cockatrice/Cockatrice#752]
The Tabs for game creator and time of creation and such should have a memory of how you set them.  I like to have description and creation next to each other but i really do not care much about creator or players or if specs are allowed and changing the order every time i log in is annoying. Also we should be able to Adjust the length of these tabs. Maybe even take off ones We never look at.

**Comment by Daenyth** [comment]
This is a dupe

**Comment by FrozenSlave** [comment]
dupe?

Fayt is a fickle thing.

**Comment by Daenyth** [comment]
#569
