### ISSUE TITLE
Abuse: Token Generation

### ISSUE THREAD

**Issue by ZeldaZach** [Cockatrice/Cockatrice#753]
Currently, there are multiple users who, when they lose, start swearing and making 1000s of tokens to crash their opponents.

While we can't stop them from swearing, the token issue is something I don't want to be a problem. My idea is to have a `TABLE_MAX_CARDS` option and that option cannot be exceeded (if someone tries to play/make a new card when the table is at max, it will return it to its prior location and/or return false (for creating cards).

Opinions on this?

**Comment by Nightfirecat** [comment]
I agree, but I feel it's hard to pin down the right number here... Should it be 100? 666? 1000? What can we reasonably expect to see on the field?

**Comment by ZeldaZach** [comment]
Maybe it should vary based on the # of players... `115*n` where N = # of players

**Comment by Daenyth** [comment]
I'd like to see what specifically happens when they make tokens. Possibly
we can make it just crash them instead of the other players

**Comment by woogerboy21** [comment]
I agree.  What is the crash caused by?  Does the client run out of memory?  What version of the client is the user using that is crashing?  Could use some more details or even a way to reproduce the results.
