### ISSUE TITLE
Can't close "view deck" dialog anymore

### ISSUE THREAD

**Issue by ctrlaltca** [Cockatrice/Cockatrice#754]
On  small screen (13" mac book pro). Trying to make the window wider, the dialog moves accordingly keeping the "X" button outside the screen.
Maybe an hotkey like "ESC" could help.

![schermata 2015-02-17 alle 23 31 00](https://cloud.githubusercontent.com/assets/1631111/6238658/398efcc8-b6fd-11e4-8b30-07f46ff066a5.png)

**Comment by ZeldaZach** [comment]
I think this has something to do with the changes @poixen made with the pile view

**Comment by MassCraziness** [comment]
If it's just viewing your own deck, the F3 hotkey they opens the library will also close it. However, for opponents' libraries then yeah it'd be a problem (or if you reveal to everyone)

**Comment by ctrlaltca** [comment]
I think the issue predates the addition of pile view, maybe it was less probable to happen before.
A generic fix is surely appreciated.

**Comment by Daenyth** [comment]
We should make ESC work

**Comment by ctrlaltca** [comment]
After some tests on the zoneviewwidget;
 * it appears in a good position when opened, and its width is contrained correctly;
 * its height is contrained to an hardcoded value of 500px+extrasize (scrollbar, titlebar, etc). This is good enough even for a 1280x800 display like the one i was using;
 * you can manually move it, but if you move its titlebar out of the gameview you'll lose the ability to grab it and move it back in;
 * the ESC key already works.

The only "fix" i can imagine here is to clamp the topleft point of the zoneviewwidget inside the gameview, so that the titlebar can never be hidden outside  the gameview. Comments?

**Comment by Daenyth** [comment]
I'd like to see how it behaves with the clamped top when it goes off the
bottom.
