### ISSUE TITLE
Room Generation & Destruction Refresh

### ISSUE THREAD

**Issue by ZeldaZach** [Cockatrice/Cockatrice#756]
Currently, the server has to be restarted to have room and game types changed and updated.

An idea is for there to be a button in the admin console to clear the cache.

**Comment by ZeldaZach** [comment]
cc: @ctrlaltca

**Comment by Daenyth** [comment]
This feature will be irrelevant as soon as the create and destroy commands
are added to the protocol, client, and server

**Comment by ctrlaltca** [comment]
I agree it's a better idea to implement protobuf commands to open and close new rooms, and also a command to tell clients the list of rooms has changed.
