### ISSUE TITLE
Disappearing Card Trick

### ISSUE THREAD

**Issue by Nowwhereman** [Cockatrice/Cockatrice#757]
So I was playing a game of EDH earlier and all of the sudden I noticed that my Dryad Arbor had disappeared. As in, gone. If you count my cards I have 99 cards with my general Karametra, and my opponent has 100 with his general Karrthus included. (ignore the tokens) Not sure what happened, kinda weird. 
![missing dryad arbor](https://cloud.githubusercontent.com/assets/11068392/6260377/ec457d70-b7ab-11e4-9439-459a13f8120f.png)

**Comment by Daenyth** [comment]
Can you upload the replay file somewhere? (maybe dropbox)

Are you sure it's in the deck file? Didn't accidentally hit `-` on it?

**Comment by ZeldaZach** [comment]
Could not reproduce. I feel as if the user deleted the card by accident

**Comment by Nowwhereman** [comment]
How do you want me to do the reply file? Just copy the text into a document, I can do that. Also, I had played Dryad Arbor (or fetched with Karametra) then it just disappeared from the board and game.

**Comment by ZeldaZach** [comment]
You could've hotkey'd it to sideboard possibly

**Comment by ZeldaZach** [comment]
I was following the replay and it does seem to have just disappeared ... 

http://mtgheadquarters.com//zach/replay_ralph.cor

**Comment by Nowwhereman** [comment]
I watched it, too. I think it got stuck under a forest somehow, and I never tapped that forest alone, but tapped the entire stack of 3 so everything tapped at the same time, dryad arbor included. The text confirms this.

**Comment by ZeldaZach** [comment]
I haven't heard anything about this issue from any other user in the past few months. If this occurs again, please feel free to reopen.
