### ISSUE TITLE
no manifest from library (play face down) option

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#762]
@kaiserfro added a right click entry to the hands menu in #726 

The same entry at the library menu would be great and will make playing the current cards easier.

(i know about shift+dragging from library)

**Comment by Daenyth** [comment]
:+1:

**Comment by Daenyth** [comment]
This would be impacted by #331

**Comment by ZeldaZach** [comment]
@ctrlaltca When I press the button, it should assign the face down card a P/T of 2/2. 

Also, do we want it to tell me what card I played or no?
What I see: `ZeldaZach puts the top card of his library into play.`
What my opponents see: `ZeldaZach puts the top card of his library into play.`

What I should see: `ZeldaZach puts the top card of his library (Batterskull) into play.`

**Comment by Daenyth** [comment]
No, you should not see the name - not until you peek at it. Not everything
that comes from top of library should be revealed

**Comment by ZeldaZach** [comment]
Fair enough @Daenyth.

If that's the case then I see no issue merging #1035

**Comment by poixen** [comment]
Pyxis of Pandemonium is an example.

**Comment by ZeldaZach** [comment]
Gotcha poix. It's fine as is then :)
