### ISSUE TITLE
check accounts for wrong/not allowed country codes (e.g. many use NATO)

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#768]
Many users still have this weird white flags.
I think that's because they used to be able to use their own letters inside the country field.

Some messed around with it to get this "special looking white flag", others just don't know their right code and others used codes that are not working with our international norm we start using to pull the flags.

I checked some players during low-server times (just 500 users!) and still found all this different codes:
- un (**many many!**; unknown?)
- uk (**many!**; uk is United Kingdom (Great Britain) within the old NATO country codes);<br>
 to be honest, I think I never ever saw someone with a GB flag
- sw (**several**; sw is Sweden within the old NATO country codes)
- sp (**several**; sp is Spain within the old NATO country codes)
- ja (ja is Japan within the old NATO country codes)
- no (no is Norway within the old NATO country codes)
- en (en is Estonia within the old NATO country codes)
- ct (ct is Central African Republic within the old NATO country codes)
- wa (wa is Namibia within the old NATO country codes)
- rm (rm is Marshall Islands within the old NATO country codes)
- qc
- ti
- ip
- 29, N7 (??? :) )
<br>*(added more to the list in the meantime)*

**Important:**
As described in https://en.wikipedia.org/wiki/List_of_NATO_country_codes the NATO codes got changed to be the same as the ISO ones we use.
The old ones can be found here, e.g.: https://de.wikipedia.org/wiki/Liste_der_NATO-L%C3%A4ndercodes

I suggest checking the database for codes not conform to the ISO-3166-1 norm we use right now and reset these values. Some kind of script can do this? I wouldn't convert old NATO codes automatically.
@woogerboy21 @ZeldaZach @Daenyth your thoughts?

Our reference is the [ALPHA-2 code from ISO-3166-1](http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2).

**Comment by Daenyth** [comment]
I agree that we shouldn't convert.

**Comment by ZeldaZach** [comment]
Maybe we can just upload the same copy of the flag under the "old" NATO names in order to fix the problem?

**Comment by tooomm** [comment]
We could do that @ZeldaZach.
But it's more of a workaround for people who use old and wrong codes we do not longer support within the new country dropdown menu we added a while ago.

I like to see a more general solution, no workaround for lazy people who doesn't want to change their flags again. They realized that their flags are gone/have changed to empty squares and just don't see a reason to change them again. So that shouln't stop us from cleaning up old dusty codes.
That's why I suggest to run a check on the database and remove/empty values outside of the new ISO 3166-1 alpha-2 codes. This will just remove old unsupported flags, which don't get displayed anyway right now. People who don't care about their flag won't complain. People who do are free to re-add their country to their account - now they even get displayed! :)
