### ISSUE TITLE
Oracle import: Flip cards

### ISSUE THREAD

**Issue by Grim-the-Reaper** [Cockatrice/Cockatrice#77]
Flip cards are incorrectly imported if the flipped counterpart comes before the regular one alphabetically. 
As such, the flipped rules text is not added to the regular card, rather, the regular card gets the rules text (and p/t) of the flip side.

I suggest storing flipped versions (the ones with brackets) in memory if the flipped version is encountered and their regular counterpart has not yet been encountered. Once the regular is encountered, it can be created and the flipped version's text can be added to it.

Imo, the import should also create a separate instance of the flipped version of the card, so that a token can be created using the secondary card name, which would have flipped art, making it more easily readable by those who prefer to read the card art instead of text boxes.

Also, because of the way flip cards are currently handled, the un-set Erase is not being imported correctly (because it thinks it's a flip card). The un-set text is added to the regular Erase's text.
(Not sure how to correct this, though)

B.F.M. also loses its bracketed text due to being treated like a flip card.

AErathi Berserker is another card which has problems being imported due to the way it's being handled. In the text spoiler, It uses the misprinted name as the name with the corrected oracle name between brackets.

If a card with brackets is encountered, and there is no card found which refers to what's between those brackets, it should add the card with the brackets as a regular card (at the end of that set's import). This would fix BFM, but not erase, nor the berserker... (which would become 'rathi Berserker (AErathi Berserker)')

Those would need to be handled as exceptions.

**Comment by ZeldaZach** [comment]
I'd like to return to this issue possibly.

I feel that if a card is known by Oracle/Database that it's a double-sided card, an additional option should be shown on the menu in client.
![screenshot 2015-02-03 18 49 57](https://cloud.githubusercontent.com/assets/7460172/6032309/892b2942-abd5-11e4-9420-05c5ae97284e.png)

Potentially after "Flip" it could say "Transform" and it will create the appropriate card to replace it either like this:
![screenshot 2015-02-03 18 51 22](https://cloud.githubusercontent.com/assets/7460172/6032314/aaa0f8c2-abd5-11e4-8125-1a1d01caa163.png)

...or just replacing the physical object for a new one.

**Comment by aeosynth** [comment]
There's not much to discuss here, the specific ui is just a minor detail. I imagine a PR would be welcome.

**Comment by Daenyth** [comment]
I think we can just tie this into making tokens for related cards
