### ISSUE TITLE
Handle Command_Register and write new user to database table

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#777]
Create new user account from register command

Need to check
- ip/client id is banned
- user already exists (sql unique constraint)
- email required but not provided
- server doesn't use auth
- client is sending too many requests (auto ban possibility?)

**Comment by ZeldaZach** [comment]
Too many requests would be determined by...?

**Comment by Daenyth** [comment]
Basically it's an anti-spam measure so that a malicious client can't keep sending reg requests over and over to flood the user database.

**Comment by ZeldaZach** [comment]
Maybe we should look into client ID
