### ISSUE TITLE
Servatrice should send email for new users being registered

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#778]
This needs #777 to be implemented first.

When a new account is registered, servatrice should email the user with the activation link.

**Comment by ZeldaZach** [comment]
Email from a server that's config'd in servatrice? I know @woogerboy21 made it work for a gmail account

**Comment by woogerboy21** [comment]
Is this still needed since in client registration is now functional?  Also is #777 ?

**Comment by Daenyth** [comment]
I think this was implemented?

**Comment by woogerboy21** [comment]
Yes, it does email users with the activation code that gets generated.

**Comment by woogerboy21** [comment]
I also noticed you had #776 that seemed to be associated with in client
registration.
