### ISSUE TITLE
Servatrice should allow users to activate accounts

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#779]
Perhaps the user should copy paste an activation code from their email into cockatrice?

When client gets a RespAccountNotActivated, display a dialog for the user to enter their activation info.

- Add Command_ActivateAccount (usable by mods without a code)
- Add appropriate activation responses
- Activation key needs to be stored in sql and time locked. See how wooger's php handles this

Need to check for client bans as well as some kind of brute force prevention logic so a malicious client can't just use it over and over until it finds a working account.

**Comment by ZeldaZach** [comment]
:+1: but maybe it just links them to a website that the code activates on (like most sites)

**Comment by Daenyth** [comment]
Currently the only code that exists to do that is wooger's php admin UI. While that's nice, I don't want to mandate that all server owners must use it. Cockatrice should primarily be self serve.

**Comment by ZeldaZach** [comment]
I've always plugged them in together as one service tbh

**Comment by Daenyth** [comment]
Nope. I'm not willing to put my/cockatrice's name behind that code. Maybe if I wrote an admin UI from scratch to my standards, but that's the point of it being in the protocol - anyone can perform these actions using the protocol and know there's no mistakes - it becomes "fill in form" -> send a protobuf message to servatrice -> done

**Comment by woogerboy21** [comment]
the stuff i wrote should be hastily retired if at all possible for a much better in client/server solution.

**Comment by ZeldaZach** [comment]
I agree, but we don't have anything currently :disappointed:

**Comment by Daenyth** [comment]
Hence this ticket

**Comment by ctrlaltca** [comment]
Implemented in #1101
