### ISSUE TITLE
Request/Suggestion: Detachable elements for multi-monitor use.

### ISSUE THREAD

**Issue by TechieJunk** [Cockatrice/Cockatrice#78]
Ability to move Art pane, chat pane, etc.. separately from main window

**Comment by TechieJunk** [comment]
Addressed by [#1329](https://github.com/Cockatrice/Cockatrice/issues/1329) and [#1342](https://github.com/Cockatrice/Cockatrice/pull/1342)

**Comment by woogerboy21** [comment]
Should this be closed since its only the deck editor that things have been implemented in?

**Comment by TechieJunk** [comment]
Er, I guess you're right. I didn't realize it was only the deck editor.

**Comment by woogerboy21** [comment]
yeah having it in the game scene would be totally cool, but for that matter every where would be totally cool

**Comment by TechieJunk** [comment]
I had just redownloaded cockatrice today and saw the change and got all excited, hadn't even played a game yet. And I remembered my "issue" I posted here. :+1: :

**Comment by ctrlaltca** [comment]
#1753 implements this.
