### ISSUE TITLE
Provide a cleanup script to delete unactivated user accounts

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#782]
If a user account is registered more than X days ago and not activated, delete it.

**Comment by ZeldaZach** [comment]
:+1:

**Comment by woogerboy21** [comment]
Should be something like this:
```
#!/bin/bash
# SCHEDULE WITH CRONTAB BASED ON TIME PERIOD REPLAYS SHOULD BE SAVED UNTIL (EX: SCHEDULE ONCE A WEEK TO KEEP A WEEKS WORTH OF REPLAYS IN THE DB)
mysql --defaults-file=./mysql.cnf -h localhost -e 'delete * from servatrice.cockatrice_users where active = 0'
```

**Comment by woogerboy21** [comment]
Just checked that code on the backup server and it works. (fyi)

**Comment by Daenyth** [comment]
That will also break activation for users who registered the same day. You
need a where clause on created at tine

**Comment by woogerboy21** [comment]
@Daenyth 
It does have a where statement on the registration date.  I edited the post and you probably don't see the edits through email?

**Comment by Daenyth** [comment]
Edits don't go to email, yeah
