### ISSUE TITLE
Priority Indication feature

### ISSUE THREAD

**Issue by eronsis** [Cockatrice/Cockatrice#786]
As far as I know there isn't a good way other than leaving verbal cues (such as "k?", "does my trigger resolve?", "responses?") in the chat window to indicate who has priority and whether one passes priority to the non-active player. I think a simple feature like a red-light/green-light indicator somewhere that could be toggled between players could simplify this problem.

**Comment by Nightfirecat** [comment]
I think figuring out an intuitive UI/interface for it would be tricky, but I agree that this would be an awfully handy feature.

**Comment by woogerboy21** [comment]
Is what your looking for as simple as some on board notification that the inactive player has a response?

**Comment by tooomm** [comment]
hmm...

There are two options I think:
- a **response indicator** that you hit IF you want to respond (must be fast+simple to use and easy to notice for your opponent)
You then kinda interrupt your opponent and show him that you want to do something in response without the use of the chat or the need to waiting 5s every time just because your opp might do something or maybe is typing right now.
- some kind of a *chess counter* in the way that it **shows who has priority** and players need to actively pass priority. It will show if they are still thinking and going to play stuff after their first spell.
For example your opp finished casting his two spells on the stack and decides to pass priority (-> hit the priority switch and it swaps to show you have priority now and are able to respond). If you doesn't want to cast something in response to his last spell you hit the switch as well and the last spell on the stack resolves. Your opp can then do something again or if he wants his first spell to resolve he hits the switch again.
In some situations (or multiplayer) that might annoy and is just too complex, but that's the only way I can think of doing it right. Not sure if I like it, though.

In a real card game on the kitchen table you solve this generally without having something like a "chess clock"-like switch. But with gestures and words its way easier and faster, though.

**Comment by ZeldaZach** [comment]
I don't know if this is a great idea seeing how people do it currently, but maybe you guys can come up with some good ideas for a simple notification system :)

**Comment by eronsis** [comment]
@woogerboy21 what I had in mind was a visual cue players had the option of toggling back and forth to indicate who had priority to use the stack. Because a lot of players misunderstand the priority during phases (and the stack in general) the lack of a reminder about APNAP enforces misinterpretation of cards, card interactions, etc.

@ZeldaZach I believe a feature that allowed players the option of indicating who has priority not only streamlines Cockatrice but it would also help players understand the game a bit better.

**Comment by Vafthrudnir** [comment]
The area under the exiled cards is unused and large enough to hold a pause button. If a player A would press it, player B could be informed about this via either a messagebox or changing the color of this button (or both).

Messagebox:
![pause_button_2](https://user-images.githubusercontent.com/9273978/36397974-23ec67b4-15c5-11e8-8e87-b03ef1b4cf8b.png)

Color change:
![pause_button_2](https://user-images.githubusercontent.com/9273978/36398059-856837c0-15c5-11e8-899e-89a5317ab087.png)

The button would stay in this state until player A hits the continue button (which would replace this pause button on his side), the phase changes, or player A reacts in any way (draws an arrow or puts down a card) - whichever happens first.
What do you think?

**Comment by ZeldaZach** [comment]
I like the overall concept, but instead of a play/pause button maybe change it to priority? I'm not really sure what I'd like to see for this yet

I'd like to know @Daenyth opinion on this as this would be a really big change to the system (and maybe would require a protocol change)

**Comment by Vafthrudnir** [comment]
I think priority is a bit too magic-specific, while pause (or wait) is more universal. According to my idea, this feature wouldn't add any limitations gameplaywise, it would only be a new way to signal our opponent for a pause - whether the player would like to react or just wants some time to analyze the table before continuing. Although I'm not familiar yet with communication implementation, so a protocol change may indeed be needed.

**Comment by ZeldaZach** [comment]
Sure, we can make this work. 

So if my opponent casts a spell onto the stack, I can press the "wait" button and their button will turn red indicating I'm making a move. Once I'm done, I can press it again and it will turn green. I think in addition, a phase change should reset the wait button to default color.

I'm really not sure how much of an impact this specific issue will be as I don't see the full picture yet.

**Comment by Daenyth** [comment]
Is this actually solving a problem in general? It seems "nice", but what about adding a button to the UI to trigger the already-existing chat message shortcut? We could change the default message to be "wait a moment" or something like that.

I'm reluctant to expand scope given how hard the project has become to maintain

**Comment by ZeldaZach** [comment]
That's what I was thinking myself, but I wanted your opinion. I honestly don't know how needed something like this is, but I don't want to turn away a solution a hard working member of the community provides.

**Comment by Daenyth** [comment]
I agree, but it's a balancing act because they do the initial work of
adding it and then we keep it working for the next 5-10 years after. For
some stuff that's fine but I do hope to someday do a redesign of the
protocol, and having a smaller feature set at that time will help

**Comment by Vafthrudnir** [comment]
I think the problem with the chat macro is that it is not defined by default (you have to create one yourself), and it is only displayed in the chat.
This feature would supply instant, clearly visible feedback about whether the opponent wants to do something or not, which in my opinion would definitely enhance the gaming experience.

**Comment by Daenyth** [comment]
I'm concerned about the segment of the userbase who would be annoyed by
adding in-your-face stuff like that as well as the segment of the user base
who simply won't use it at all.

**Comment by tooomm** [comment]
>I think the problem with the chat macro is that it is not defined by default (you have to create one yourself), and it is only displayed in the chat.

That we could solve anyway to raise awareness of the feature.
There could be pre-configured stuff like `Ok!`, `Wait!`, `Thinking...`, `Good luck, have fun`, `I go first` etc.
At best there would be a "Edit Chat Macros" link in the right click "say" menu as well which brings you to the corresponding page in settings.

**Comment by Daenyth** [comment]
A menu entry would be extremely easy to add.

**Comment by ZeldaZach** [comment]
#1740
