### ISSUE TITLE
Putting cards from opponents library onto the battlefield

### ISSUE THREAD

**Issue by KratosAurion** [Cockatrice/Cockatrice#788]
I can't put the revealed cards of my opponents deck to the battlefield, that's really annoying when I cast spells like Sadistic Sacrament, especially in multiplayer.

**Comment by ZeldaZach** [comment]
I see pros and cons for this idea... pros are that you can play cards with the cons that people can abuse it if you reveal your deck/hand to them for something non-related

**Comment by Daenyth** [comment]
It needs to work

**Comment by KratosAurion** [comment]
Well, it does. Now. But a few minutes before I created this issue, it didn't.

**Comment by ZeldaZach** [comment]
So you're saying you experienced a bug, but it works now?

**Comment by KratosAurion** [comment]
My opponent revealed his library to my, usually I could drag his cards to my board. But it didn't work. I closed his library and asked him to reveal it again. He did and I still couldn't drag the cards to my board. So I just named the cards, he should exile.

**Comment by Fizztastic** [comment]
This bug had already happened to me during a match prior to this ticket but I was able to reproduce the bug.

1. Make a new game with 2 players.
2. Have the active player reveal his library.
3. The non-active player can't move cards from the active player library.

Tested on release E4147E6.

**Comment by ZeldaZach** [comment]
Dupe of #625
