### ISSUE TITLE
Suggestion : Card editor

### ISSUE THREAD

**Issue by stendardo** [Cockatrice/Cockatrice#79]
Hi, I have a little suggestion that would come in in handy for many users. Have an actual GUI editor for editing card data, as well as do partial import/export of cards.xml. This will allow people to both add sets of newly-released "official" cards (not yet on gatherer) as well as create custom sets. People should not have to dig through XML in order to edit cards.

**Comment by ZeldaZach** [comment]
This is done through MTGSalvation's script service usually

**Comment by Daenyth** [comment]
We could still do it at some point

**Comment by ZeldaZach** [comment]
Looking back at this, we're not MSE. We're a different entity. There's no real reason for us to implement this when there's another functional program that just does it better.
