### ISSUE TITLE
HiDPI support on Mac

### ISSUE THREAD

**Issue by leematos** [Cockatrice/Cockatrice#799]
Hey all,

Would it be possible to add HiDPI support on Mac by default? I did it by editing the plist:

```
<key>NSHighResolutionCapable</key>
<string>True</string>
```

(http://apple.stackexchange.com/questions/69038/open-in-low-resolution-checkbox-on-retina-macbook-pro-checked-and-disabled)

but I'm not sure how to get that into the build system.

**Comment by Daenyth** [comment]
Thanks. I'll see what we can do

**Comment by ZeldaZach** [comment]
Tested by adding the string and WOW, this is great. :)

**Comment by Daenyth** [comment]
I'll look at how to get cmake to do this as soon as I can

cc @ctrlaltca

**Comment by tooomm** [comment]
> The application may now allow a **hacked, possibly glitchy** retina mode.

Are you sure you want that into the build by default?

**Comment by leematos** [comment]
@tooomm It's supported by Qt. More information here:

http://blog.qt.io/blog/2013/04/25/retina-display-support-for-mac-os-ios-and-x11/

Section titled "Enabling high-dpi for OS X Applications".

**Comment by ZeldaZach** [comment]
Seems like a glitch came about from this; 
![screenshot 2015-03-05 14 32 36](https://cloud.githubusercontent.com/assets/7460172/6512793/85e79d70-c344-11e4-8c7b-5089fa4c6f87.png)

**Comment by ZeldaZach** [comment]
@Daenyth Can you try and look into this when you get time? Much appreciated :)

**Comment by Daenyth** [comment]
It'll be after I finish reg

**Comment by ZeldaZach** [comment]
After some testing with this, it seems as if life totals don't show in 2 player games
![two_players](https://cloud.githubusercontent.com/assets/7460172/7253426/9ddd7f22-e80a-11e4-990b-354ebce627ae.png)

And when you get into 3+ player games, one or two life totals show, but in a weird location and they flash in and out.
![multi_players](https://cloud.githubusercontent.com/assets/7460172/7253427/9ddfeca8-e80a-11e4-8a59-9f1ace04ac24.png)

I haven't noticed any other bugs at this time, but these seem to be major ones that need to be corrected if this is to be incorporated.
