### ISSUE TITLE
Suggestion: Card description hinting

### ISSUE THREAD

**Issue by stendardo** [Cockatrice/Cockatrice#80]
Often when we play a game with unreleased cards we have the issue that the opponent does not see those cards if he/she did not update its cards.xml, requiring you to explain to him/her in the chat and/or have him/her search the spoiler list. A solution to this would be to have the client without the new cards to request the card information (which includes image url, p/t, cost, loyalty, etc.) of unknown cards that the opponent put in a visible zone to the opponent's client. As soon as that client sees an unknown card created by a player (or anytime afterwards), the client in question sends a request to the other party (potentially through the server). If the opponent has indeed put this card in a visible zone during the game (to avoid allowing fishing for information by a rogue client), if the opponent has checked an appropriate option in his/her settings (to avoid leaking information by default) and if the opponent has not been sollicited for this particular card name more than N times during this game (to avoid denial-of-service), then the information for this card will be sent to the requesting client, which will display it with a yellow (or other color) border, to indicate that the information for this card was sent by another player (and warn the player that the info should not be trusted in absolute as being the valid info for this card).

**Comment by Daenyth** [comment]
I think this doesn't make sense for the direction of the project, at least for now. Maybe in the future we'll get some kind of cross-client card awareness but for now I don't think this will actually help much in practice. I feel like the spoiler season card db sharing has gotten easier and that's taken away some impetus from this
