### ISSUE TITLE
Crash when returning to sideboard

### ISSUE THREAD

**Issue by poixen** [Cockatrice/Cockatrice#802]
Here is an image of the screen when it crashed. I am on win7. I am guessing this has to do with loading/unloading cards.

![crash](https://cloud.githubusercontent.com/assets/2134793/6528776/b328dd18-c424-11e4-828a-6b0dda5468dd.png)

**Comment by Nightfirecat** [comment]
I think I repro'd on 816c01e: [screenshot](http://i.imgur.com/AJGTM0d.png)

**Comment by ZeldaZach** [comment]
I've tested this on 277d7e2 (Latest Release) on Windows 7 and I don't seem to experience this issue. If it's still a problem for you guys, please feel free to reopen.
