### ISSUE TITLE
Room tab title doesn't correctly display ampersand (&)

### ISSUE THREAD

**Issue by Nightfirecat** [Cockatrice/Cockatrice#811]
Screenshots ([1](https://cloud.githubusercontent.com/assets/2199511/6570516/34368784-c6b9-11e4-8f85-c52be8334198.png), [2](https://cloud.githubusercontent.com/assets/2199511/6570515/3434ab9e-c6b9-11e4-95c4-84eb44dd9ffb.png)) of a room titled "Modern T1&2 Only", which displayed as "Modern Tier1_2_ Only". (underscores representing the underlined number)

Appeared on version b0fe2ef.

**Comment by ctrlaltca** [comment]
We need to escape the ampersand; example commit from another project: https://code.wireshark.org/review/#/c/7346/2/ui/qt/module_preferences_scroll_area.cpp

**Comment by poixen** [comment]
Heh. It thinks it's an accelerator key.

**Comment by poixen** [comment]
I can reproduce this on the current master branch. @Nightfirecat are you able to update to the latest weekly build and then see if you still get the same issue? Cheers.

**Comment by ZeldaZach** [comment]
I just tried on Mac OSX 10.10.3 and when I entered "Modern T1&2 Only" it transformed into "Modern T12 Only"
