### ISSUE TITLE
Stacked 4 lands of one type in one pile

### ISSUE THREAD

**Issue by Nightfirecat** [Cockatrice/Cockatrice#812]
After a fairly long game, upon playing a fourth island (after moving some other adjacent lands over to make space), it instead was placed directly on top of the spot the other three already inhabited. I was able to move it off of that spot, but only because I guessed that I had to drag it over.

[Here's a replay showing the incident](https://www.dropbox.com/s/i24s8pxnmtjajrc/4-islands.cor?dl=0), happening [around 55% through this game](https://cloud.githubusercontent.com/assets/2199511/6570607/bcd146b4-c6ba-11e4-8c6d-56c289a29960.png) for the top player.

I experienced this on b0fe2ef.

**Comment by ZeldaZach** [comment]
I think I've experienced this myself in the past.

An idea I have is for lands with the same name to "attach" to a master land
(i.e. I play a forest, and if I play another forest it will auto attach (like equip) to the first forest. Same goes for any other forest I play.)

**Comment by Daenyth** [comment]
Is there another bug about this? This sounds familiar

**Comment by radioactivehazards** [comment]
I do not think this should be "Auto" as some players do not attach their lands

**Comment by ZeldaZach** [comment]
This is not an issue, as we only allow stacking 3 cards

**Comment by ebbit1q** [comment]
if this were meant as a bug instead I tried and it's impossible to do this.
