### ISSUE TITLE
Filter function not functional

### ISSUE THREAD

**Issue by TheAmazingPeanut** [Cockatrice/Cockatrice#813]
Any term I put in the filter doesn't actually do anything. I don't know what else to say about it, really. I've tried restarting the program, my computer, even re-installing the program from scratch and it still seems to have the same problem. I'm not sure what else I can do.

![image](https://cloud.githubusercontent.com/assets/11411875/6581374/c757ebde-c72c-11e4-956b-e9787392036c.png)

![image](https://cloud.githubusercontent.com/assets/11411875/6581388/f02b6248-c72c-11e4-948a-287bee3013a1.png)

**Comment by woogerboy21** [comment]
Did you install the pre-built client or compile your own?  Also what OS specific version information can you provide?  Obviously its windows but....

**Comment by poixen** [comment]
It's been fixed and PR'd. When merged will be in this weeks build.

**Comment by TheAmazingPeanut** [comment]
Thank you for the quick response.
