### ISSUE TITLE
Card Images Not Loading

### ISSUE THREAD

**Issue by ynalak7** [Cockatrice/Cockatrice#814]
Hello,

My card images are not loading in my library/deck builder or in game. I have tried reset/clear downloaded pictures and reordering sets with promo sets at the bottom. I also downloaded the latest client and tried all of this.

This problem just started happening today, was working fine before.

**Comment by woogerboy21** [comment]
This is due to mtgimage.com being shutdown by wizards.
Use LQ images for the time being.

Thanks.

**Comment by woogerboy21** [comment]
Or another option for HQ images is to manually download them from other sources and put them into the required folder locations.

**Comment by ynalak7** [comment]
Oh geez that was a simple fix. Thank you!

**Comment by Nightfirecat** [comment]
MTGImage was shut down?
Today is the saddest day.

**Comment by Psithief** [comment]
*throws hands up in disgust, walks away*

**Comment by ZeldaZach** [comment]
https://www.reddit.com/r/Cockatrice/comments/2ylmpz/solved_hq_card_images_not_loading/
