### ISSUE TITLE
No card images populating in Cockatrice

### ISSUE THREAD

**Issue by jedthehomarid** [Cockatrice/Cockatrice#816]
I noticed that several of my card images were not populating so I downloaded what seems like the latest version of Cockatrice (Version fd4f762) for Mac and redid the Oracle import.  Now none of the card images are visible either in deck editor or in gameplay.  I went through the FAQ steps and have tried importing all the sets, only certain sets and reordering the set priority with no luck.

Any advice would be appreciated.  If you need any additional information from me please let me know.

Cheers,

Ryan

**Comment by Nightfirecat** [comment]
You'll have to disable HQ image downloading, since MTGImage was shut down by Wizards not long ago. See #814.

**Comment by ZeldaZach** [comment]
https://www.reddit.com/r/Cockatrice/comments/2ylmpz/solved_hq_card_images_not_loading/

**Comment by jedthehomarid** [comment]
Thanks.
