### ISSUE TITLE
Absolutely no card art

### ISSUE THREAD

**Issue by CptTrollzor** [Cockatrice/Cockatrice#817]
I've tried refreshing oracle, i've tried getting custom "cards.xml," and i've tried everything i was told on here. I STILL have no card art, even after fully uninstalling and re-installing. Not a single card in the database has art.

**Comment by ctrlaltca** [comment]
Hi, and thank you for reporting your issue. Anyway, you may want to search for similar issues before opening a new one. Specifically, an issue almost identical to yours has been reported and the solution is described in #814, #815, #816. Please test the solution described there an let us know if it worked.

**Comment by CptTrollzor** [comment]
I've followed those steps to no avail, was my point. I'm just trying to avoid downloading 14933 images to keep all my card art.

**Comment by ZeldaZach** [comment]
https://www.reddit.com/r/Cockatrice/comments/2ylmpz/solved_hq_card_images_not_loading/

**Comment by CptTrollzor** [comment]
Hey zach, just like i said to ctrlaltca, that doesn't work, i've tried it and it didn't pull any images. thanks for closing it though...

**Comment by ZeldaZach** [comment]
Have you tried "clearing downloaded pics/cards"

**Comment by CptTrollzor** [comment]
yes, to no avail
