### ISSUE TITLE
Load from clipboard should support .COD

### ISSUE THREAD

**Issue by aeosynth** [Cockatrice/Cockatrice#818]
the only other format i've tried is mtgo's `.txt`, which works, is that the only one supported? would be nice if the supported formats were documented, preferably in the load dialog

**Comment by ZeldaZach** [comment]
Last I checked COD files worked fine. I'll see what's up later today

**Comment by Daenyth** [comment]
Load from clipboard treats it as .txt right now. It supports a few common variations including mws, appretice, mtgo.

Good suggestion though
