### ISSUE TITLE
pictures vanished please help!!!

### ISSUE THREAD

**Issue by djsoltex** [Cockatrice/Cockatrice#819]
everything was working great, then for some reason all pictures vanished from everywhere, the deck editor and even in a game. the pictures just wont pull up 
![screen shot 2015-03-12 at 3 31 54 am](https://cloud.githubusercontent.com/assets/11437463/6614427/04823f32-c868-11e4-9a94-c9f2129345e0.png)

**Comment by ctrlaltca** [comment]
Hi, and thank you for reporting your issue. Anyway, you may want to search for similar issues before opening a new one. Specifically, an issue almost identical to yours has been reported and the solution is described in #814, #815, #816, #817, #820, #821. Please test the solution described there an let us know if it worked.

**Comment by ZeldaZach** [comment]
https://www.reddit.com/r/Cockatrice/comments/2ylmpz/solved_hq_card_images_not_loading/
