### ISSUE TITLE
i have a problem with software cockatice

### ISSUE THREAD

**Issue by yann45** [Cockatrice/Cockatrice#821]
I have no picture on the cards.

**Comment by ctrlaltca** [comment]
Hi, and thank you for reporting your issue. Anyway, you may want to search for similar issues before opening a new one. Specifically, an issue almost identical to yours has been reported and the solution is described in #814, #815, #816, #817, #819, #820. Please test the solution described there an let us know if it worked.

**Comment by ZeldaZach** [comment]
https://www.reddit.com/r/Cockatrice/comments/2ylmpz/solved_hq_card_images_not_loading/

**Comment by yann45** [comment]
Hello Zach
 
thank you for the answer
 
I'im french and my english is bad.

**Comment by yann45** [comment]
Hello Zach
 
thank you for the answer
 
I'im french and my english is bad.
 
What does it do exactly ?
 
Yann

**Comment by ZeldaZach** [comment]
Go to Cockatrice -> Settings -> un-check the "Download High Quality Images".
