### ISSUE TITLE
Right-Click is doing nothing.

### ISSUE THREAD

**Issue by ArcyTheArcanine** [Cockatrice/Cockatrice#822]
When in a game I get no menu when right-clicking a card, and right clicking does nothing when clicking my life total and any of the token under the life for mana/storm.

I've ran it as administrator before talking to ZeldaZach, who prompted me to re-download/re-install Cockatrice and restart my computer. Both didn't work, then was told to submit a ticket here.

**Comment by Daenyth** [comment]
What version of windows do you have? You downloaded it from woogerworks?

**Comment by woogerboy21** [comment]
Is this still an issue?

**Comment by ZeldaZach** [comment]
reopen if still persistant
