### ISSUE TITLE
hardcoded strings

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#824]
![hardcoded strings](https://cloud.githubusercontent.com/assets/9874850/6639999/c37e653c-c994-11e4-8eea-89b33a558ec9.png)
green: german
purple: english hardcoded, no strings within transifex...

to reproduce:
- change language to non-english
- open/join game
- try to close cockarice

I tried to search for them but I just found this:
GitHub\Cockatrice\cockatrice\src\tab_supervisor.cpp (1 hit)
```
Line 137:
if (QMessageBox::question(this, tr("Are you sure?"), tr("There are still open games. Are you sure you want to quit?"), QMessageBox::Yes | QMessageBox::No, QMessageBox::No) == QMessageBox::No) {
```

**Comment by ZeldaZach** [comment]
Hmm, maybe we have to add the direct string to the english translation file? 

cc: @poixen & @ctrlaltca

**Comment by tooomm** [comment]
I just posted the code from cockatrice itself. There is something in the translation files as well:
GitHub\Cockatrice\cockatrice\translations\cockatrice_de.ts (1 hit)
Line 1814:         <source>There are still open games. Are you sure you want to quit?</source>

But you can't find it in transifex...

**Comment by tooomm** [comment]
more research:
If you hit the small x on the game room it will show a window with translated string. A different one, though.
It's just if you close cockatrice itself with the X in the upper corner or use "Cockatrice menu" --> "Exit"

I found a refering string in transifex btw:
Transifex Nr.: 319 
Occurrences: ../src/window_main.cpp:427
Maybe a different one?

**Comment by ctrlaltca** [comment]
The strings are the same, but have been moved to another context, so qt is searching them in the wrong place. These strings needs to be re-extracted, i noticed this accidentally while committing #854. Once that PR is merged, the new string should be available on transifex.

**Comment by ctrlaltca** [comment]
Issue fixed by yesterday's update of translation files.
