### ISSUE TITLE
Cockatrice's Advanced Search Function Does Nothing

### ISSUE THREAD

**Issue by McKendry2** [Cockatrice/Cockatrice#831]
I recently installed Cockatrice on my dektop computer, having used it extensively on my laptop before this. I downloaded the client and used the Oracle to install the cards. Cockatrice opens fine and as far as I can tell, all of the cards are there.

The problem is that utilizing Cockatrice's (and, or, and not, or not) search function does nothing. It's almost as if the advanced search function doesn't even exist. It doesn't filter any of the cards at all.

The version of Cockatrice I'm using is fd4f762

**Comment by ZeldaZach** [comment]
I just re-built my client from the latest github version (20603c7) and this feature seems to be fully functional.

I recall we fixed the filtering functions last week. It's very possible the change wasn't pushed to the weekly build in time. You're free to either compile your own build through github or wait until next weeks build comes out (Friday morning).

Sorry for the issues!!

**Comment by poixen** [comment]
This should be fixed in the new installer on woogerworks.
