### ISSUE TITLE
rename "user lists" tab to something more suitable

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#834]
suggestions:
- Account (details?)
- Profile

If we are going to have more information and details about our account/profile in there and maybe even the possibility to make changes to them it's more intuitive to have it's name changed accordingly.

**Comment by poixen** [comment]
been wanting to rename that tab to profile for a while.

**Comment by ZeldaZach** [comment]
What about "Acquaintances" or "Buddy List"

**Comment by tooomm** [comment]
@ZeldaZach That are good suggestions for the use it has right now. I like that.

If this tab should get extended to be more account related in general its not fitting that well, though.

I think we need to decide here if we want
- one tab for account related lists (buddies, ignored user...) **and a seperate tab** for profile (account management, details and settings) information with the things that can be found & edited [here](http://cockatrice.woogerworks.com:81/loginpage.php) right now
- the two combined into one tab
- just the tab we have right now + a menu entry with a special window (like the cockatrice settings window right now) for account related settings instead of them being in a tab
- ...

**Comment by tooomm** [comment]
This can be closed I think.
