### ISSUE TITLE
issue with #331 (pr #775 not sufficient)

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#835]
As discovered by @anoda9 [here](https://github.com/Cockatrice/Cockatrice/issues/331#issuecomment-79926159):

> Another problem is the client automatically stacks cards with the same name, even if they are face down.

![anoda9](https://cloud.githubusercontent.com/assets/9874850/6657545/e30eaed6-cb4f-11e4-9596-188c8884871f.png)
Fix #775 for #331 is not sufficient. It's working locally, but not on the server.

The server code needs some changes as well?! @Daenyth

**Comment by Daenyth** [comment]
Most likely wooger has not updated the server to run the fixed version.

**Comment by Daenyth** [comment]
@woogerboy21 can you make sure the server is up to date?

**Comment by woogerboy21** [comment]
I plan on upgrading the servers now that the anti flood code is in the code base which can then retesting for this issue can occur.

**Comment by woogerboy21** [comment]
@Daenyth do you know by chance the commit that fixed this?

**Comment by ctrlaltca** [comment]
779a400de4c690597e6ca0186d8eeacbbea38049 and a7b8934a1b43873c15c0856e7688dec3ac3e06a5

**Comment by tooomm** [comment]
@woogerboy21 updates the backup server code, still no change:
![facedownissue](https://cloud.githubusercontent.com/assets/9874850/6783843/5d1c1e52-d17c-11e4-829b-0cc25d372352.png)

**Comment by ZeldaZach** [comment]
I believe it tells you what card you put into play, but the opponent can't tell

**Comment by tooomm** [comment]
The issue is about the cards stacking

**Comment by woogerboy21** [comment]
The updated code should now be working on the backup / main server.

**Comment by tooomm** [comment]
working on main+backup:
![facedownissue](https://cloud.githubusercontent.com/assets/9874850/6785487/136ca164-d186-11e4-810f-ddc746b2e11f.png)

(anti-flood works as well on both - if you're using an older client you just get no message about it, but it kicks in!)

This can be closed.
