### ISSUE TITLE
Random number generator

### ISSUE THREAD

**Issue by JimMcMahon** [Cockatrice/Cockatrice#837]
Hey everyone, 

I randomly took a look at the RNG code and started poking around.  

# Evaluating 3 different cases:  

* 1) **32bit SFMT [0,1]** -- Using the SFMT random number generator, use the function sfmt_genrand_real1() to generate a sample from [0,1), and then map to [min,max]. We use rejection sampling similar to the prior method however we only reject when sfmt_genrand_real() == 1, which has a very low probability. Due to this, i don't  mutex.lock().

* 2) **C++11** -- Using *random*  I generate values similar to above using the std library. This uses MT, not SFMT. 

* 3) **Current 64bit SFMT** -- The current implementation. 

# caveats: 
* sfmt_genrand_real1() uses the 32bit implementation of SFMT. 

# Experiments:

I ran each case 60 times, calculating the chi^2 for k = 1 to 59. The number of samples was n = 500000 * k. I then, for each case k, dropped the 5 highest values and 5 lowest values and took the mean value (to remove outliers).  The attached plot shows the mean chi^2 as a function of k for each implementation along with the corresponding error bars. 

 . | **32bit SFMT [0,1]** | **C++11* | **Current 64bit SFMT** 
 ------------ | ------------- | ------------- | -------------
 mean runtime | 8.9s   | 29.7s | 33.6s

![chi_squared](https://cloud.githubusercontent.com/assets/11464708/6657756/8dd2613e-cb2b-11e4-81b5-46648fa15081.jpg)

# Conclusions:

The randomness of all three implementations were nearly identical, the only differences were in the runtime. The large difference between **1** & **3** are most likely due to the mutex.lock() overhead. I'm not sure if people would be comfortable with getting rid of it when using implementation **1**.  I'm not sure what's making the C++11 implementation so slow, maybe they're also making it thread safe, i'd have to look into that. 

So, in the end, the entropy is good, there just seems to be room for speedup if it's worth having.

**Comment by woogerboy21** [comment]
Just curious, what spurred this testing?  Always interested in hearing about this sort of thing.

**Comment by JimMcMahon** [comment]
My testing group uses cockatrice pretty heavily to practice for GPs and Opens, and i always hear them complain about their "bad draws" or that the shuffling doesn't work well, or something... i also had experienced several instances where while rolling a d20, my opponent and I rolled the same multiple times in a row, which seemed pretty unlikely. 

So i was curious enough to see what was going on. I think the die-rolling may have been a timing thing since the seed is set in the server ( I think ) , if you're hitting the button at the same time you're going to get the same number  (which would be based on more than just the efficiency of the RNG itself). The shuffling i think is just them complaining that they have a truly random deck. Shuffling with actual cards typically yields a set that isn't as efficiently randomized so people are probably more used to less randomization.

**Comment by woogerboy21** [comment]
Yeah, we've tried to explain that to users over and over and most people seem to not understand (or dont like to think) that shuffling IRL isn't efficiently randomized (broken).  I'm also convinced that a good number of players still mana weave and not even realize it.

**Comment by woogerboy21** [comment]
I have found though, that since I started using electronic games to test decks and then build them IRL i get a more consistent play rather than a biased to paper only deck experience.

**Comment by JimMcMahon** [comment]
Oh absolutely!  In fact, if you just pile shuffle your deck and present it at a tournament you can be disqualified for cheating (not randomizing your deck).  You need to riffle or mash shuffle multiple times after pile-shuffling if you don't want a judge called on you, doing anything else is essentially mana-weaving your deck so you can get near optimal draws.

**Comment by poixen** [comment]
Are we going to do anything further with this, or can the issue be closed?

**Comment by ctrlaltca** [comment]
Imho a quick change to #838 could make it mergeable and solve most of this issue.

**Comment by ctrlaltca** [comment]
Closing; related discussion in #838 and #961
