### ISSUE TITLE
allow to define a language for card picture downloads

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#841]
A brazilian guy told me this... he said that this would be a very huge improvement since many people struggle with english in general (true for other languages/countries as well!). If they get the card pictures and/or text in the language of their choice that would help many foreign players and strengthens the international cockatrice community in general.
Everybody sees the pictures and/or text in their preferred languages, even in the same game. For many users this would be much more comfortable.

I found out after a check that magiccards.info and gatherer both provide card pictures (and -text) in different languages!

**Gatherer** (you need to click on languages to see all available (printed) languages)
![Quiet Contemplation (en)](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=386629)
![Quiet Contemplation (de)](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=387436)
![Quiet Contemplation (chinese simplified)](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=386898)
As you see the multiverse id is different for each language, even for the same card.

**magiccards.info**
http://magiccards.info/ktk/en/50.html
http://magiccards.info/ktk/de/50.html
http://magiccards.info/ktk/cn/50.html
The direct link to the images are "magiccards.info/scans/**en**/ktk/50.jpg" etc.

So in theory this should be possible...

---

**Edit:**
In the meantime, mci redirects all requests to **Scryfall**, which has different arts, too as [it's part of scryfall now](https://scryfall.com/blog/scryfall-magiccards-info-190)!
So the above mci links point to this scryfall pages:
https://scryfall.com/card/ktk/50/en/
https://scryfall.com/card/ktk/50/de/
https://scryfall.com/card/ktk/50/zhs/

**Comment by woogerboy21** [comment]
It would need some investigation but the first thing that comes to mind is for us to expose the settings on were to pull the HQ images from and at that point users could put in the site with the needed language and card naming convention for the setting and then the users client could pull whatever language they like with the card images from the site of there choosing.

As for lower quality images from the gatherer that would need some work.

**Comment by tooomm** [comment]
The url pattern from magiccards.info seems fairly easy though:
`/scans/language_code/set_code/card_number.jpg`

In general users who prefer to play non-english cards (for a reason) shouldn't complain too much if they just get low quality images in exchange for cards being in their own language.
There must be a hint in settings about this for sure. (next to a tick-box "Use card text and art in your clients language")
HQ pics can just go with english to make things easier. It can still be a option for later if really needed.

**Comment by ctrlaltca** [comment]
Using magiccards.info is a nice idea, but i think somebody should get in touch with them and ask permission before pointing all cockatrice users on their bandwidth.

**Comment by Daenyth** [comment]
+1 for asking them.

This is a fine feature - we talked about it a long time ago. Now that we're using mtgjson instead of gatherer it's more possible

**Comment by tooomm** [comment]
https://github.com/lsmoura/mtgjson/issues/12 got included in the meantime, so there are unique foreign multiverse ID's since quite some time.

@Daenyth the other thing I pointed you to the other day is about full foreign language support with card text etc., we don't need that to make this work.
So once we use the newer mtgjson v3 we could potentially get this working.

**Comment by ebbit1q** [comment]
this was added in https://github.com/Cockatrice/Cockatrice/pull/3670
