### ISSUE TITLE
no text label on unreadable tabs

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#842]
If you have many tabs open you can't read them anymore.
![tabs](https://cloud.githubusercontent.com/assets/9874850/6671485/bb3c22b0-cc05-11e4-9ee4-fa7027311963.png)

This is especially a problem on lower resolutions. Or languages that need more space because they user longer words.

If you move the mouse over a tab there should appear a text label with the complete name of the tab. For example within firefox:
![text label](https://cloud.githubusercontent.com/assets/9874850/6671802/1b1d5486-cc08-11e4-8a4a-d13467c65baa.png)

**Comment by ctrlaltca** [comment]
I'd suggest to also remove the "Talking to " prefix and start the tab caption with the user name, adding a proper suffix like " - private chat".

**Comment by tooomm** [comment]
That's a good one! :+1: 

Private chat, private message or direct chat etc.
To make it uniform to the right click menu it should be direct chat. But I feel like private chat/message is more commonly used and easier to understand.

**Comment by ZeldaZach** [comment]
@ctrlaltca :+1: I like the idea
