### ISSUE TITLE
no art

### ISSUE THREAD

**Issue by avatonqp** [Cockatrice/Cockatrice#843]
i cant see the art of the cards. none of them :/

**Comment by ctrlaltca** [comment]
We are sorry :(

You should probably check the tickets of other people who reported your same problem in the last few days: #814 #815 #816 #817 #819 #820 #821 #823

**Comment by avatonqp** [comment]
i did, unchecked the hq box, i still have the same problem. Note: i downloaded cockatrice today, and it's my first time trying to use it.

**Comment by avatonqp** [comment]
Needed some time as it seems. now it works, thanks.

**Comment by poixen** [comment]
The reason you couldn't see any art was because gatherer was down while they added DTK.
