### ISSUE TITLE
Error 0xc000007b launching Cockatrice and/or Oracle

### ISSUE THREAD

**Issue by alu0100405200** [Cockatrice/Cockatrice#851]
I've had the same problem with League of Legends and managed to fix it, but it seems that Cockatrice isn't working as intended either.

**Comment by ctrlaltca** [comment]
Please try the solution described at this link:https://github.com/Cockatrice/Cockatrice/wiki/Troubleshooting#failed-start-because-msvcp100dll-was-not-found

**Comment by alu0100405200** [comment]
I've uninstalled and installed Visual C++ 2010 both in 64bits and x86 and still get the same error

**Comment by ctrlaltca** [comment]
That error is the not-really-userfriendly way that windows uses to tell you that something went wrong when loading the dlls needed by a program to start.
If you had the same problem for other software, you were probably missing these dlls, or some software installed an outdated/wrong version of them.

I saw some websites suggesting to manually download some dlls and put them into c:\windows\system32; that could make some software run, but it will force all the other software to use that same dlls, even if they need another version of the dll.

To understand exactly what's going on you should open cockatrice.exe using dependecy walker: http://www.dependencywalker.com/ ; it will report if any dll is missing, and the path where it's being loaded from the disk. By the way cockatrice is a 32bit binary, so the x86 vcredist package is the correct one.

**Comment by woogerboy21** [comment]
As @ctrlaltca mentioned above.  This issue is a problem on your system with the visual c++ runtime libraries being either mismatching in versions, incorrectly registered or just simply corrupted.  Fixing this type of issue can be painful.  Along with @ctrlaltca suggestion I would say to google on how to manually deregister the existing DLL's.  Remove them and then reinstall the redistributable package once the problematic DLLs have been removed and registry information is cleaned up.

**Comment by alu0100405200** [comment]
So I should get these?
![4ko4guy](https://cloud.githubusercontent.com/assets/8983126/6743096/b067f244-ce8d-11e4-8831-1269e3318c1f.png)

**Comment by ctrlaltca** [comment]
No, you should not get missing dlls.

**Comment by tooomm** [comment]
`Error 0xc000007b` is equivalent to [this in wiki](https://github.com/Cockatrice/Cockatrice/wiki/Troubleshooting#failed-start-because-msvcp100dll-was-not-found)?

**Comment by alu0100405200** [comment]
No, tried that solution but didn't work. I went and did a complete reset of the computer, installed windows 8.1 and it's working now. Maybe I screwed the libraries while trying to fix League of Legends.
