### ISSUE TITLE
Solution for card images/database path for Windows 8.x

### ISSUE THREAD

**Issue by theonepb** [Cockatrice/Cockatrice#853]
I've been looking for updated information for about 3 days now - off and on - and I can't find any definitive answer on this issue. 

My new pc runs Windows 8.1. I've loaded and updated cockatrice and the database on several computers, but never one running W8 and above. I've tried several different databases - I've tried checking all, unchecking all, clearing images, running everything as admin, changing the sort order, etc... I even tried updating with only one set... nothing works. 

help?

**Comment by ctrlaltca** [comment]
Sorry sir, but what is the problem? "card images/database path" is a bit too generic.

**Comment by theonepb** [comment]
I know it's kind of vague; not sure how else to describe it. I am only assuming that it is a path issue, because I think I've done all the "muggle" troubleshooting I can do. 

This may help... earlier today, I removed cockatrice from 2 computers - a windows 7 laptop (that it has worked fine on for over a year) and the new windows 8.1 laptop I am having trouble with. Then I re-installed it on both computers and ran the card database update exactly the same way on both machines (as administrator). 

It works perfectly - as in, I can see all the card images/information - on the Windows 7 machine. On the windows 8 machine, I can see only the description (text) of the each card only in the deck editor tab. On the W7 machine, I can connect and play games and see all card images and everything is fine. On the W8 machine, I can connect and start games, but cannot see any images OR text descriptions for cards. 

I have repeated this process as admin, not as admin, and a mixture of each on both machines and I've tried (on both machines) to rearrange the set list, download only a small selection of sets, etc. I have also tried using links to alternative databases, rather than the default database that Oracle provides. No matter what I do, it always works on the W7 machine and never works on the W8 machine. 

I'm not a coder. I would alter scripts and core code when I played UO back in the day, but I don't know really remember anything about it and I do not speak the language. I'm thinking that this is a path issue specific to W8 and that's all I really know. So, I'm sitting here with a brand new HP Omen and I'm unable to get the only game I'm really interested in playing at the moment to function... and I know there must be a simple fix... I mean, unless cockatrice just doesn't work on W8 machines?

**Comment by tooomm** [comment]
- Do both machines have images in their pictures direcotries? (Settings --> General --> Pictures Directory)
- Which version of Cockatrice do you use? The same on both machines?
- Have you **unchecked** "Download high-quality card images" on both machines?

**Comment by theonepb** [comment]
Ugh... see, now I knew that, but I didn't think to check and here's why: On the Windows 7 machine, after I uninstalled/reinstalled it, I didn't have to uncheck HQ images. It installed with all the settings I had before uninstalling (which is great, actually). I guess since I did that one first and didn't have to change it, my brain just skipped that step on the second machine. 

My bad!

**Comment by ZeldaZach** [comment]
Glad this is fixed for ya dude :)

**Comment by tooomm** [comment]
Hmm. But I'm curious why windows keeps the settings **after** uninstalling & reinstalling.
Which version do you use @theonepb? Check the about tab pls.
Maybe it's still the one which checked HQ Images after the install by default.

**Comment by theonepb** [comment]
well, i deleted everything when i deleted it, so i installed the same version on both PCs today. i don't have the old PC with me at the moment, but i can double-check when i get back to it. i'm gonna bet it's the same as this one: fd4f762.

**Comment by tooomm** [comment]
Yep. That should be a build that sets the pictures to hq after installation.

You deleted it? Does this means you uninstalled it using the uninstall.exe inside the cockatrice folder?
Or did you just deleted the cockatrice installation folder on your c drive?

**Comment by poixen** [comment]
If you have hq images set to true and the reinstall, it will be the same. The client settings are not uninstalled. In the latest version I have set hq images to false which fixes this issue.

**Comment by tooomm** [comment]
@poixen he did not just reinstalled the client. He uninstalled it before.
If cockatrice uninstaller leaves settings behind... we don't need it. There is no benefit of having an uninstaller that's not working. :)

**Comment by Daenyth** [comment]
Making the uninstaller delete registry keys would make you lose settings on upgrade I think

**Comment by tooomm** [comment]
what do you mean with upgrade? installing a new client?
well, you want to keep your settings? just install the new client over the current one.
if you use uninstall before, you know that you loose everything. that's what uninstalling is about and always was... :)

**Comment by Daenyth** [comment]
On windows (currently) installing the new one runs the uninstaller of the old one first. That's why people's decks got deleted on upgrades.

**Comment by woogerboy21** [comment]
I thought that was fixed was it not?  ive ran the new installers before and not lost any of my deck files.

**Comment by tooomm** [comment]
I never use uninstall for cockatrice, don't lost my decks too. Now that you mention it.
Would have been bad if they disappeared, because I totally don't expect that to happen. :)

What is fixed exactly @woogerboy21 ?
The decks getting deleted or running the uninstaller before install?

**Comment by Daenyth** [comment]
We fixed it by 1) deleting specific files instead of all of the Cockatrice/ folder and 2) by default store decks in %appdata% instead of program files/cockatrice

**Comment by Daenyth** [comment]
The behavior of "install new client runs uninstaller of old client" remains the same afaik

**Comment by tooomm** [comment]
>We fixed it by 1) deleting specific files instead of all of the Cockatrice/ folder and 2) by default store decks in %appdata% instead of program files/cockatrice

Hmm. I think the uninstaller needs a rework then.
The uninstaller should at least clear+remove the `program files/cockatrice` directory completely. I don't like it leaving something behind at all. I think there are programms out there that ask if you want to delete user data (pics, tokens, card database, decks etc. for us) as well or just the programm files in the app directory + registry + shortcuts etc.

Right now it leaves the zlib file in `program files/cockatrice` behind as well if you use the uninstaller...

**Comment by Daenyth** [comment]
@tooomm please ticket the zlib thing, that's an oversight.
