### ISSUE TITLE
linebreaks for links are buggy

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#855]
![linebreaks for links are buggy](https://cloud.githubusercontent.com/assets/9874850/6741007/aa941644-ce84-11e4-8caa-32f38d8896fe.png)

As you can see the link is `www.magic-league.com`, but it's displayed as `www.magic-ague.com` if there appears a line break.
If you click the link you'll get redirected to the correct site for both cases. So the link works, but is displayed not correctly.

There should be no linebreak for links. :)

**Comment by woogerboy21** [comment]
You dont have your text area zoomed by using the ctrl + scroll wheel do you?

**Comment by tooomm** [comment]
I don't know. Just tested this feature for the first time now...
How can I reset it to be 100% again?

**Comment by Daenyth** [comment]
ctrl+0 I think or maybe close and reopen

**Comment by tooomm** [comment]
ctrl+0 (zero) not working
reopening the particular chat tab (=rejoining that room) did the job

i could reproduce this:
http://screencast-o-matic.com/watch/coerbeeMij
someone can confirm?

**Comment by Daenyth** [comment]
We probably need to explicitly bind Ctrl 0 in the chat view for it to work

**Comment by ZeldaZach** [comment]
This issue seems to be fixed.
