### ISSUE TITLE
Copy Paste in Cockatrice Client.

### ISSUE THREAD

**Issue by ChrisFiore** [Cockatrice/Cockatrice#858]
I have been having a bug were I cannot paste into the client. I have deleted the client and installed the newest one to try and troubleshoot the issue. I am able to copy things from the client and paste them elsewhere however, when i try to copy a decklist and import it into the client the function does not work. Also if i copy a link such as drafts.in url and try to paste it into client it does not work. I am however able to copy the link from cockatrice and post it into the browser. Really strange bug.

**Comment by woogerboy21** [comment]
There is something going on with your machine.  Copy and paste functionality work fine on every client I have tested in the last 10 minutes or so.

**Comment by ChrisFiore** [comment]
It is isolated specifically to cockatrice weird

**Comment by woogerboy21** [comment]
What operating system are you using?

**Comment by ChrisFiore** [comment]
I have windows 8. Some others I've talked to ate experiencing simular
issues with the paste function specifically

**Comment by ZeldaZach** [comment]
You're not the first user to report something like this to me. All have come from Windows 8.1

**Comment by woogerboy21** [comment]
Thats odd.  Works fine on my windows 8.1 lenovo.

**Comment by tooomm** [comment]
I've never had problems with this on Win 8.1. Pasting links all day... just tried a decklist again. 

- You made sure to focus the chat bar ("Say") before pasting your link?
- Have you tried both, Ctrl+V and right click --> paste?

**Comment by ChrisFiore** [comment]
Yes tomm. Ctrl v and right click. When I right click all options are are
unavailable.
On Mar 20, 2015 6:41 AM, "tooomm" <notifications@github.com> wrote:

I've never had problems with this on Win 8.1. Pasting links all day... just
tried a decklist again.

   - You made sure to focus the chat bar ("Say") before pasting your link?
   - Have you tried both, Ctrl+V and right click --> paste?

—
Reply to this email directly or view it on GitHub
<https://github.com/Cockatrice/Cockatrice/issues/858#issuecomment-83983866>.

**Comment by Daenyth** [comment]
Can you take some screenshots? What version of cockatrice from the about menu?

**Comment by ZeldaZach** [comment]
If this issue is still persisting, please feel free to reopen this :)
