### ISSUE TITLE
No art or even text

### ISSUE THREAD

**Issue by Black1reaper** [Cockatrice/Cockatrice#867]
I am not sure how, I had cockatrice on my laptop and works perfectly fine. When I put it on my rig though it seems, that no art or text appears at all for the cards. I get the name of the card, its power/toughness and the cards are colored to represent what color of mana it takes, that is all it show.
![cockatrice](https://cloud.githubusercontent.com/assets/11593714/6768054/62ea2bbe-d02b-11e4-943d-5b18f6f72cf9.jpg)

**Comment by Black1reaper** [comment]
So I resolved it myself, strangely just uninstalling it, and re-installing it three times did the trick. Who the heck knows why that is.

**Comment by Daenyth** [comment]
https://www.reddit.com/r/Cockatrice/comments/2ylmpz/solved_hq_card_images_not_loading/
