### ISSUE TITLE
Servatrice.app crashes on launch

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#868]
Build on osx using `make package`, installed servatrice.app to /Applications, launched it, and then this crash:

https://gist.github.com/Daenyth/7dc1dc25de95cdf9e093

**Comment by ctrlaltca** [comment]
The QObjectPrivate ctor is trying to output a fatal message:
```
// QObjectPrivate::QObjectPrivate(int version)
    if (version != QObjectPrivateVersion)
        qFatal("Cannot mix incompatible Qt libraries");
```
The program then abort().
I see two possibilities here:
 1. the servatrice's application bundle contains mixed libraries/plugins from different qt versions;
 2. the executable or one of the qt libraries has not been "cleaned" correctly by cmake when installing. You can specify default search paths for libraries in executables (think of rpath under linux), and these can be checked running ``` otool -L /Applications/servatrice.app/Contents/MacOS/servatrice ```.

**Comment by ctrlaltca** [comment]
I'm quite confident this was due to mixed versions of qt libraries, please reopen if it's still a problem.
