### ISSUE TITLE
Download high-quality card pictures no longer works

### ISSUE THREAD

**Issue by dak393** [Cockatrice/Cockatrice#869]
I have to disable the option in order to get any card art. I would guess that the source of the images has changed the api call or no longer has the images.

**Comment by ctrlaltca** [comment]
No need to guess, we had a lot of people asking the same question over and over here: #814 #815 #816 #817 #819 #820 #821 #823 #843 #844 #853 #867 and in a dozen reddit threads, even a sticky one: https://www.reddit.com/r/Cockatrice/comments/2ylmpz/solved_hq_card_images_not_loading/
