### ISSUE TITLE
Deck Doesn't Show In-Game

### ISSUE THREAD

**Issue by Rednal** [Cockatrice/Cockatrice#872]
I recently updated Cockatrice, and no new decks I've created can be played. They save properly, and I can edit them - I can even right-click on the deck area in-game (with zero cards), and open the deck to edit from there, but it won't actually let me PLAY the deck. I simply have no cards at all on my side of the field.

I've tried loading the deck both locally and from the server - neither worked. That said, all of my older decks work fine, so I'm guessing it's something to do with the current client. Is there anything you can tell me about what might be causing this and how I can fix it?

**Comment by Daenyth** [comment]
What OS are you on? What version from the about menu? Can you attach a screenshot?

**Comment by Rednal** [comment]
![no deck error](https://cloud.githubusercontent.com/assets/11620237/6792621/1d695dc4-d177-11e4-9a2f-6fd0dc2eab08.png)

As you can see in the screenshot, no deck appears, despite having been selected.. I'm running Windows 7, and Cockatrice version 6065587. Right-clicking the deck-zone and selecting 'Open Deck in Deck Editor', as mentioned before, brings up the correct deck in a new tab.

**Comment by Daenyth** [comment]
Can you try loading the deck in local game mode? Also please upload the deck file to gist.github.com

**Comment by Rednal** [comment]
I can technically "load" the deck, but it does not appear in local game mode either.

The Deck File can be accessed here: https://gist.github.com/Rednal/dff1b0d9c2c82196c89a#file-awaken-the-mountains-cod (At least, I -think- that's the right link... my apologies if it's wrong)

**Comment by woogerboy21** [comment]
umm....  all your cards in that deck are in the sideboard.

**Comment by Daenyth** [comment]
Yeah that would do it.
