### ISSUE TITLE
Unreg users can create temp username with invalid chars

### ISSUE THREAD

**Issue by poixen** [Cockatrice/Cockatrice#874]
We have set rules in place for new registrations that limit the chars to [a-z A-Z 0-9 -_], right now unreg users can use invalid chars, like the username "try a sexy nerd ;D".

Now it might be, depending on how the client registration is working @Daenyth, we wont need to address this server-side, as the server will soon be registration only.

**Comment by Daenyth** [comment]
https://github.com/Cockatrice/Cockatrice/blob/process-registration-request/servatrice/src/servatrice_database_interface.cpp#L100

**Comment by poixen** [comment]
Addressed in #956
