### ISSUE TITLE
wrong login --> return to login window

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#875]
If you enter a wrong password while connecting to a server, Cockatrice displays this message:
![loginmsg](https://cloud.githubusercontent.com/assets/9874850/6802249/2745024a-d22f-11e4-8e06-d00502ffe0c2.png)

If you hit "OK" the message closes and you are at the deck editor tab again.
**Hitting "OK" should bring you back to the login window, that you actually can check what is wrong and try to login again without complications.**

**Comment by ZeldaZach** [comment]
I agree with the idea of having the connect menu popup on failed login

**Comment by Daenyth** [comment]
:+1: we should rework the connect dialog anyway when we do reg. I'd also like to make it remember all your servers in a dropdown instead of only the most recent

**Comment by poixen** [comment]
Same with usernames?

**Comment by tooomm** [comment]
It's just if you enter a wrong password, sry.
If you enter a wrong username (doesn't matter if you don't enter a password at all or if it's a right or wrong one). Cockatrice will connect you to the server as unregistered users with that "wrong" name.
That's even more weird! :D

**Comment by Nightfirecat** [comment]
> This error message just appears if you enter a wrong password for your correct username, sry.  
> If you enter a wrong username (doesn't matter if you don't enter a password at all or if it's a right or wrong one). Cockatrice will connect you to the server as unregistered users with that "wrong" name.

This is actually a tad concerning from a security standpoint, as it gives a direct indication regarding whether a user account exists for a given name. (login fails if it exists, unreg access granted if it doesn't)

Of course, this isn't the easiest fix, as allowing unregistered users to log in while preventing them from clashing with existing usernames doesn't actually work... Maybe it would be better to assign an identifier to unregs and allow them to use a nickname? (that way each user is unique and we don't expose the existence of a given username)

**Comment by tooomm** [comment]
These cases can occur while logging in:
- no username, no password<br>
--> msg: enter complete authentication information (reg) or choose username (unreg)
- no username, "wrong" password<br>
--> msg: enter complete authentication information (reg) or choose username (unreg)
- **non-existent username, no password**<br>
--> connect with username as unreg
- non-existent username, wrong password<br>
--> msg: incorrect username or password
- **correct username, no password**<br>
--> msg: incorrect username or password
- correct username, wrong password<br>
--> msg: incorrect username or password
- correct username, right password<br>
--> connect with username as reg

You would still know then that there is an existant account for this username because of the two bold cases in the list.


But if unreg support is going to get dropped anyway, that's no longer an issue:
- no username, no password<br>
--> msg: enter complete authentication information
- no username, "wrong" password<br>
--> msg: enter complete authentication information
- non-existent username, no password<br>
--> msg: incorrect username or password
- non-existent username, wrong password<br>
--> msg: incorrect username or password
- correct username, no password<br>
--> msg: incorrect username or password
- correct username, wrong password<br>
--> msg: incorrect username or password
- correct username, right password<br>
--> connect with username as reg

**Comment by Daenyth** [comment]
How about if server is in require registration mode, return bad auth instead of "you must register" for unregistered names?

**Comment by poixen** [comment]
Created #879 to address the key issue.

**Comment by ZeldaZach** [comment]
Fixed in #879
