### ISSUE TITLE
uninstaller improvements

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#876]
Right now the uninstaller leaves the zlib file in `program files/cockatrice` behind.
Plus many thousands of pictures and other stuff in `%appdata%` ...without notifying the user or giving him the opportunity to delete them as well while uninstalling. I didn't check the registry.
Not the most user friendly way of handling this.

- [x] uninstaller doesn't delete `zlib1.dll` in `program files/cockatrice/` and leaves the trice folder behind
- [x] ask the user during ***un*installing** if he just wants to delete the main programm files in<br> `program files/cockatrice/` (+registry + shortcuts +...) or also user data (pics, tokens, card database, decks etc.) as well in `%appdata%` **+ message macros** (wherever they are stored)
- [x] ask the user during **installation** setup (if the app is already installed) if he wants to delete old settings
- [x] add `Cockatrice` name label instead of NSIS at the bottom (see VLC e.g.)<br>
http://nsis.sourceforge.net/Removing_%27Nullsoft_Install_System_vX.XX%27_String_from_installer
![cockatrice setup](https://cloud.githubusercontent.com/assets/9874850/7513851/f83c0fce-f4b7-11e4-9602-776cf744726f.png)

<br>
Here are some nice examples from the common app VLC media player:
VLC source: http://www.videolan.org/vlc/download-sources.html

VLC installation setup:
![vlc install](https://cloud.githubusercontent.com/assets/9874850/6826870/83b772b2-d304-11e4-90ed-eca781c057ea.png)

VLC uninstall dialog:
![vlc uninst](https://cloud.githubusercontent.com/assets/9874850/6826646/44222512-d303-11e4-82c7-ce3ebd457544.png)

VLC installation dialog if installing over existing installation:
![vlc install over existing](https://cloud.githubusercontent.com/assets/9874850/6826650/49d02112-d303-11e4-8e17-bbd266cb3a7c.png)

VLC installation dialog if installing over existing installation 2:
![vlc install over existing2](https://cloud.githubusercontent.com/assets/9874850/6826654/4d7819d2-d303-11e4-86ee-88884de8ee8c.png)

**Comment by Daenyth** [comment]
Doing the installer like that would be really nice

**Comment by ctrlaltca** [comment]
about point three: in #1062 i've added uninstall-before-update to the nsis script, so that:
 * old version of cockatrice will be able to clean after them, before installing the new version (no old library versions leftovers)
 * adding the "clean user data" option to uninstall will implement both the second and the third point of this issue

**Comment by ZeldaZach** [comment]
@ctrlaltca I'm just making sure I understand; When you try downloading a newer version of the client, it will auto-uninstall the older version to write the new one.

Or will a user have to manually uninstall before they can run the executable file?

**Comment by ctrlaltca** [comment]
When you run the cockatrice setup, it will detect that an old version is already installed, show you a "A previous version of Cockatrice must be uninstalled before installing the new one." popup, run the uninstaller, then let you proceed with the normal installation.

**Comment by ctrlaltca** [comment]
This has been implemented in #1169
