### ISSUE TITLE
Cockatrice not downloading High Quality Pictures

### ISSUE THREAD

**Issue by BlackMageTribuS** [Cockatrice/Cockatrice#888]
Cockatrice will not download high quality images.  I have tried everything in the post here: https://github.com/Cockatrice/Cockatrice/wiki/Frequently-Asked-Questions#some-of-my-cards-dont-have-art

It will download low quality images.

Any help would be greatly appreciated.

**Comment by woogerboy21** [comment]
The HQ image provider was closed down by wizards and that option is not currently working till a new provider becomes available.  Until then you can either manually download HQ images and place them in the folders accordingly or survive with LQ images.
