### ISSUE TITLE
Cockatrice 0xc000007b - Trying everything

### ISSUE THREAD

**Issue by Incontroll1** [Cockatrice/Cockatrice#913]
I tried everything to work Cockatrice but I always get the error code 0xc000007b.
Installed AIO Runtimes to get all important programs, manually installed all Visual C++ programs, run Dependency Walker, installed windows again, but nothing! Can some1 help me please? Here are some pictures from the walker, my computer system (buying 2*4gb RAM tomorow) and all programs I have on my PC.
Thanks! 
![dwalker](https://cloud.githubusercontent.com/assets/11811655/7006217/be235450-dc7f-11e4-8e2a-2bf2de9cfefe.PNG)
![windows](https://cloud.githubusercontent.com/assets/11811655/7006218/c0d6d08c-dc7f-11e4-848b-efc6eb8238f8.PNG)
![programme](https://cloud.githubusercontent.com/assets/11811655/7006220/c2865164-dc7f-11e4-9683-d145a01dad45.PNG)

**Comment by tooomm** [comment]
does #851 help you?

**Comment by Incontroll1** [comment]
Did everything it said multiple times, no it doesn't unfortunately

**Comment by Incontroll1** [comment]
I FOUND SOMETHING!!!! Guys use this if you have the same problem!
http://freewisdoms.com/download-dll-files-commonly-used-by-games/

**Comment by tooomm** [comment]
which dll was missing?

**Comment by Incontroll1** [comment]
Just copied everything in, really don't know & care at this point :D
