### ISSUE TITLE
Game wrong size for screen 

### ISSUE THREAD

**Issue by FinalFee** [Cockatrice/Cockatrice#914]
![screen shot 2015-04-06 at 16 08 49](https://cloud.githubusercontent.com/assets/11822097/7009151/28ec2824-dc90-11e4-9720-bd8747bf156d.png)

The game is too long for my screen.
I can't resize the window vertically, and when I drag the window it pings back to the top. 

I run Yosemite 10.10.2 on a Late 2011 Macbook Pro

This problem only arises once I have connected. Disconnected the game is the right size:
![screen shot 2015-04-06 at 16 08 31](https://cloud.githubusercontent.com/assets/11822097/7009298/2f62e3a4-dc91-11e4-823b-c198700491ed.png)

**Comment by Daenyth** [comment]
What dimensions does your screen have? Has this worked correctly in any
version?

**Comment by poixen** [comment]
Might be in missing something. I can see an issue with the image.

**Comment by poixen** [comment]
Can't.

**Comment by ZeldaZach** [comment]
@poixen The bottom in the 1st image is cutoff

**Comment by FinalFee** [comment]
@Daenyth As I said in my reddit post that has more detail (link below) this issue only happened once I had re-downloaded cockatrice recently. 
https://www.reddit.com/r/Cockatrice/comments/31mve0

**Comment by Daenyth** [comment]
Do you happen to know what version it worked on?

**Comment by FinalFee** [comment]
@Daenyth I'm sorry but I don't. I downloaded it a while ago though. Definitely months ago.

**Comment by tooomm** [comment]
maybe you still have the old installer in your download folder for example?

**Comment by FinalFee** [comment]
@Daenyth @tooomm Ah yes, thank you. Last time I downloaded Cockatrice was 07/11/2014 (day/month/year)

**Comment by tooomm** [comment]
just to make sure: what's the file name of the installer? it has the version in it ;)

**Comment by FinalFee** [comment]
@tooomm I'm sorry, I'm probably being really stupid, but what I downloaded on that day was a .dmg file just called Cockatrice-MacClient.dmg. Are we talking about different things?

**Comment by FinalFee** [comment]
@tooomm I don't have anything else sorry

**Comment by tooomm** [comment]
oh ok, you downloaded via the static link. nevermind then.
the date you provided should help @Daenyth

**Comment by Daenyth** [comment]
Unfortunately we've probably had over 1000 commits since then so it doesn't
narrow it down much.

How technical are you? Are you able to compile trice from the instructions
in the wiki?

Hopefully we can run through a git bisect and figure out where it broke.

What dimensions do you have on your screen?

**Comment by FinalFee** [comment]
@Daenyth Could I get a link to the instructions please? And this is all the information for my computer should you need to know more:
https://www.apple.com/uk/macbook-pro/specs/

I've never changed the resolution or anything like that.

**Comment by pepi55** [comment]
I have the same issue on a hp mini (1024x512 or something like that). I think it might be due to qt auto managing window space but this is obviously a wild guess.

**Comment by ctrlaltca** [comment]
After some tests on the very same hardware (a 13" mac book pro, non-retina, 1280x800 resolution), the minimum window size for cockatrice is 720x640 when not connected and 820x640 when connected to a server. So, i've been unable to reproduce the problem.
@FinalFee can you try to resize the window to the screen size, double clicking on the window's titlebar (left to "Cockatrice - logged in as ...")?

**Comment by FinalFee** [comment]
@ctrlaltca thank you! That fixes the problem :)
