### ISSUE TITLE
Download tokens.xml on Oracle update

### ISSUE THREAD

**Issue by RASMiranda** [Cockatrice/Cockatrice#915]
Sugestion time, it would be cool if Oracle would download tokens.xml from https://github.com/Psithief/Cockatrice-tokens to the default directory C:\Users\Rui Miranda\AppData\Local\Cockatrice\Cockatrice\tokens.xml

I'll play around to see what I can do, not much experience with c++, but will give it a try. Any tips are welcome!

**Comment by tooomm** [comment]
:+1:

**Comment by Psithief** [comment]
Perhaps Cockatrice should fork the repository and point Oracle to the fork, to guard against the unlikely case of "bad things" happening that require Oracle to be rewritten to fix a broken link.

I'm not actually planning to suddenly die or anything but…

**Comment by Daenyth** [comment]
We could host the repo and add you to the org with wrote access to it

**Comment by ZeldaZach** [comment]
Is hosting it a bad idea b/c of copyrighted things or is that essentially just "a file with words that happen to be magic related"

**Comment by Daenyth** [comment]
Mtgjson would have been shut down with mtgimage if card text was a problem

**Comment by tooomm** [comment]
the token file includes direct image links, if that is considered problematic... 

not sure if we can use the same way to generate picture links from the app as we do right now for cards

**Comment by Psithief** [comment]
> not sure if we can use the same way to generate picture links from the app as we do right now for cards

The tokens file is hand-crafted because there is *no other source*. The actual tokens text is trivial (#590), but no repository of images for these exists, especially considering Wizards hasn't printed official versions of older tokens.
