### ISSUE TITLE
Unable to download any pictures

### ISSUE THREAD

**Issue by gencross** [Cockatrice/Cockatrice#924]
Hi, I've used cockatrice in the past and haven't had any problems, but I just installed it on my new laptop and no card images will download. I followed all of the steps in the FAQ and made sure that "Download Hi Res Images" was unchecked but still, no images will download. I'm running the most recent version of Cockatrice on Windows 8.1, 64 bit. Thanks in advance for any help you can provide.

**Comment by Daenyth** [comment]
Can you try to make sure you have your image cache memory settings high enough? Set that as high as you can. Check your pic storage location settings and see if there's cards in it. Make sure you can write to it

**Comment by ZeldaZach** [comment]
Gatherer is currently offline for maintenance. No cards will download for anything. 

Try again in a few hours :)

**Comment by gencross** [comment]
Thanks!

**Comment by Daenyth** [comment]
Bah, I forgot this even happened at all. Mtgimage was so much better

**Comment by ZeldaZach** [comment]
I agree @Daenyth but what can we do?

**Comment by Daenyth** [comment]
Not much sadly
