### ISSUE TITLE
Supporting all card statuses, attacking/blocking, damage assignment

### ISSUE THREAD

**Issue by Grim-the-Reaper** [Cockatrice/Cockatrice#933]
Some suggested features:

Currently, Cockatrice supports tapped cards, and face-down cards.

It would be nice if it also supported the other card statuses, namely flipped and phased out.
Flipped would rotate the card 180°. 
Phased-out could make the card 50% transparent.
(The statuses don't have to have those names, to remain game-independent)

It would also be nice if dual-faced cards were actually dual faced, so that you don't have to use tokens when it changes sides. (simply right click --> transform)
This would of course require a link between both card faces in the database.
(The Flipped status could perhaps use the same mechanism, the 'night side' would just be the same art, rotated 180°)

As a bonus, cards which are attacking could also be indicated specially (I suggest a red border)
(For attacking creatures, this is useful if they have vigilance)
(I noticed that the card object already has an 'attacking' member, but I don't think it's actually used.)

Blocking cards could be similarly colored with a yellow border. (less important)

It would also be nice if damage could be marked on the cards. (ctrl-left-click would add damage, ctrl-right-click would remove it). Damage would disappear when the turn changes.

**Comment by Daenyth** [comment]
I'm not really sure we need this. It makes an already complex interface
more complex and I think the gains over just using arrows aren't big

**Comment by Grim-the-Reaper** [comment]
I'm wondering, why does the card class have an 'attacking' member? Is this something left over from the Brukie days? Perhaps it should be cleaned up if it's not used and you don't plan to use it.

**Comment by ZeldaZach** [comment]
I'm a fan of the 180* rotation b/c of some cards from Kamigawa, but the phasing thing I don't think is really necessary.

**Comment by poixen** [comment]
Phased cards:
Agree, its not really needed.

Rotate/transform cards:
A rotated card would not work as you would expect. Take Erayo, Soratami Ascendant for example. If you look in the cards.xml you will see Erayo, Soratami Ascendant and Erayo Essence are both separate cards. We would need to apply some linking between these two cards, which I feel is wrong. cards.xml needs to add support for an additional tag like <flip>(for transform cards) or <rotate>  which could link to another card within the file. This would not be added by us though. 
Also, we cant just rotate the card 180 degrees. The card text would then not match the image.

Card damage / blocks / attackers
I can see this causing issues. "Can you apply dmg plz". Real passive agressive stuff. "Learn to use the client". Also for the effort to get it in, I dont feel like anyone would use it as it slows down play.
Attacking/blocking is handled with arrows, I dont think we need to add more states, no one would use it as it adds more clicking to the game. Also, the setting of attackers/blockers and colored boarders would require all users to update to see it. For users who dont have the latest version, it can slow down play as the newer client will be waiting for the older client to active a feature they dont have. There are work arounds for this serverside, but its not woth the effort.

These features would be great in a rules based client, like MTGO or xmage, but in ours, not so much.
