### ISSUE TITLE
Negative power (and toughness)

### ISSUE THREAD

**Issue by Grim-the-Reaper** [Cockatrice/Cockatrice#934]
A minor issue:

Technically, a creature can have negative power and/or toughness.
Negative toughness usually isn't a big deal (since it will die at that point), but negative power can be.

Imagine you have a lot of creatures on the field, some of which are creatures with 0 power (walls)
Some effect changes the p/t of all creatures by -2/-2.

The player selects all cards and presses ctrl alt - twice.
After the effect ends, he wants to restore the p/t to it's original values, so again, he selects them and presses ctrl alt + twice.

After doing this, the walls will have incorrect p/t and will have to be adjusted manually, because cockatrice does not properly support negative p/t.

Negative p/t support would fix this (and should be easy to implement)

**Comment by tooomm** [comment]
rules:

    107.1. The only numbers the game uses are integers.
        107.1a You can't choose a fractional number, deal fractional damage, gain fractional life, and so on. If a spell or ability could generate a fractional number, the spell or ability will tell you whether to round up or down.
        107.1b Most of the time, the game uses only positive numbers and zero. You can't choose a negative number, deal negative damage, gain negative life, and so on. However, it's possible for a game value, such as a creature's power, to be less than zero. If a calculation or comparison needs to use a negative value, it does so. If a calculation that would determine the result of an effect yields a negative number, zero is used instead, unless that effect sets a player's life total to a specific value, doubles a player's life total, sets a creature's power or toughness to a specific value, or otherwise modifies a creature's power or toughness.

            Example: If a 3/4 creature gets -5/-0, it’s a -2/4 creature. It assigns 0 damage in combat. Its total power and toughness is 2. You'd have to give it +3/+0 to raise its power to 1.


<br>
Lowest power number right now is "-1", it won't decrease further.
That's what @Grim-the-Reaper referring to.
If you lower p/t of a 0/5 wall twice with ctrl+alt+"-" (--> -2/-2) it will turn into a `-1/3` creature which is wrong. If you increase p/t twice afterwards with ctrl+alt+"+" (--> +2/+2) it will turn into a `1/5` creature which is wrong as well.

Lowest toughness number right now is "0", it will make both p/t disappear completely if you lower further with alt+"-" or ctrl+alt+"-" for example.
P/t will appear again if you make any change to the p,t or p/t value and updates the changed value (except for decreasing only toughness further - anyway, if you decrease theoretically to -10, a single +1 will bring it back to 0 and p/t appears again).

**Comment by poixen** [comment]
Fixed in #939
