### ISSUE TITLE
Player battlefield area incorrect in multicolumn layout

### ISSUE THREAD

**Issue by Grim-the-Reaper** [Cockatrice/Cockatrice#944]
The player's battlefield area/hand area is incorrectly displayed/calculated in multicolumn layout, but only if the vertical window space is the limiting factor. 

Instead of stretching the area across the screen, the area of the players in the first column is cropped. 

This is not only incorrect visually, but behaves inaccurately if you try to drag a card into, say, the stack of a player in the second column. Apparently the drag drop uses a different calculation to determine where you drag to, that the one that's actually displayed on-screen.

I think this is caused by two problems: 
- When decreasing vertical size, only the right column changes proportion, not the left. They should both be changing proportions.
- The positioning of the right column is slightly off when decreasing size, the further you decrease the vertical size, the more it overlaps with the left column.

Tested off-line, but I've seen it on-line as well.

![untitled](https://cloud.githubusercontent.com/assets/7745100/7086953/b17f6270-df86-11e4-834b-d902e6b82882.png)

**Comment by Grim-the-Reaper** [comment]
Note that it only does this if using horizontal hand display.
In vertical hand display there is no cropping.
Instead, there is wasted space. (a lot of black area)

![untitled](https://cloud.githubusercontent.com/assets/7745100/7087244/879f442c-df89-11e4-8349-65ffb6d457d3.png)

**Comment by Grim-the-Reaper** [comment]
Looking at the code, I think the last line of this method of GameScene.cpp should be conditional.
The hand width should only be set to tablewidth + stackwidth if horizontal hand size is being used. (Not sure if this is related to this problem though)

void Player::processSceneSizeChange(int newPlayerWidth)
{
    qreal tableWidth = newPlayerWidth - CARD_HEIGHT - 15 - counterAreaWidth - stack->boundingRect().width();
    if (!settingsCache->getHorizontalHand())
        tableWidth -= hand->boundingRect().width();
    
    table->setWidth(tableWidth);
    hand->setWidth(tableWidth + stack->boundingRect().width());
}

**Comment by poixen** [comment]
Give it a try :) if it works, PR it.

**Comment by Grim-the-Reaper** [comment]
I think I might be having problems since I'm using Visual Studio 2013 Ultimate instead of Visual Studio 2010 Express (don't really feel like installing a second visual studio...)

Did you get a similar error when you first set it up?

**Comment by poixen** [comment]
What error do you get?

**Comment by Grim-the-Reaper** [comment]
![untitled](https://cloud.githubusercontent.com/assets/7745100/7090435/6a1e9e92-dfa3-11e4-9b11-db5518f1deb3.png)

**Comment by Grim-the-Reaper** [comment]
I think it's expecting to find the dll's in the release folder, but after building, only the executable is there.

**Comment by poixen** [comment]
Copy the dlls from QT5\5.3\msvc2010_opengl\bin to your release folder, if you want to be able to debug, you will need the "d" version of the dlls in the debug folder.

**Comment by Grim-the-Reaper** [comment]
Looking into the code further, I've determined that the problem is caused by the order in which the procedures 'rearrange' and 'ProcessViewSizeChange' are executed.
They both set variables which the other require for drawing the zones correctly.

If reorder is executed last, the left column is incorrectly positioned.
if ProcessViewSizeChange is executed last, the right column is incorrectly positioned.

Both procedures change the layout, so it would probably be best if they are rewritten/merged into a single layout procedure so you have more control over the order in which all resizing and positioning happens.

**Comment by ZeldaZach** [comment]
@Grim-the-Reaper Just in the future please don't delete comments as it makes the thread seem weird with Poixen talking to himself :smile:

**Comment by Grim-the-Reaper** [comment]
I've fixed the issue in the code (the fix is easier than I initially thought), but I'm unsure how to commit the change here... (Not familiar with Git)

**Comment by ZeldaZach** [comment]
@grim-the-reaper Fork the repo (done from the top), check it out locally on a new branch, push to the main repo, and then create a PR

1) Fork the repo
2) In your local terminal or git terminal
```
git clone https://github.com/grim-the-reaper/cockatrice
git checkout -b fix_944
```

do your changes, then
```
git commit -am "changes made"
git push origin fix_944
```

then on github create a PR :)
