### ISSUE TITLE
"You have flooded the server" seems too tight

### ISSUE THREAD

**Issue by camaroman86v6** [Cockatrice/Cockatrice#949]
While I understand the purpose of this message, it seems that it triggers too quickly and punishes fast players. I have received this message for pressing shuffle 4 or 5 times quickly before a game (I know, with an RNG once is enough) and then trying to draw an opening hand. I have also received this warning for the sequence of: pass turn, untap permanents, draw card, play land, tap, play a card. I don't think this functionality should be capturing typical fast plays and forcing players to wait when they aren't actually doing anything nefarious and flooding the server. The natural reaction to "I just pressed draw a card and it didn't draw" is "I'm going to press it again", which could lead to an accidental double draw or mulligan to 6 at the beginning of the game if a confused user presses CTRL+D or CTRL+M twice in their frustration over the game not behaving as they expect.

Perhaps the trigger for a flood warning should observe the recent command history before triggering? For instance, a player who clicked pass, untap, draw, etc. is more likely to be a human actively playing the game quickly than someone flooding the game. That is to say, multiple different commands sent quickly are more likely to be game activity than multiple repeated commands. Obviously, one could flood just by cycling through different commands, but the trigger should at least be relaxed when the command history is a sequence of multiple different commands. It looks like from skimming the thread about this functionality that the trigger is 10 actions in 10 seconds? Perhaps if the actions are different (say at least 3 or 4 different actions) then 20 actions should be allowed in 10 seconds in order to avoid false positives?

**Comment by ZeldaZach** [comment]
We decided, when implementing this, to block every action as a potential flood warning.

Over time, with new tickets coming in, we're slowly "white listing" certain actions (such as shuffling, moving cards when sideboarding, mulliganing, etc) to allow for better game play.

From your request, it seems as if changing phases should be white listed, and I agree.

cc: @poixen

**Comment by camaroman86v6** [comment]
Is mulliganing now white listed? I believe just yesterday or the day before, I got the warning for "shuffle, shuffle, shuffle, draw initial hand (ctrl+m)".

Thanks for your prompt response. The development team here has been great every time I've had a question/comment here.

**Comment by poixen** [comment]
Yes I added mull a week or so ago. 

I can see 10 actions a sec can be a little restrictive for faster users. I am considering raising to 15/s. This will effect server load/performance though. Its not something I can change without consulting the server host. Will get back to you when I know more.

**Comment by poixen** [comment]
Ok, I have updated the code. It will be applied later today.

The new limit has gone from 10 -> 15. #953

It will also require a server restart. Sorry :/
