### ISSUE TITLE
Limit new player names to ~20 chars

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#962]
For unregistered users and new account registrations.

A quick check on the online users list tells me that there are just very few players (1-2?) using names longer than 20 chars. The number could be adjusted, though.

This would help with interface design and readability in chat for example.
Columns are no longer too narrow for some names and stuff... I remember an issue with player names and scroll bars in the games lobby out of the head.

The lists of connected users could get narrowed down to increase the room for the chat/game list as well with this. There is plenty of unused space that we can't use right now:
![player names space](https://cloud.githubusercontent.com/assets/9874850/7120787/0469f834-e210-11e4-9085-3b640dcb7cd6.png)

Opinions?

**Comment by Daenyth** [comment]
I dislike imposing limits that are purely arbitrary.

Why not just shrink the column anyway, and if a user has a long username, we can either truncate with `...` or we can make it horizontal scroll

**Comment by tooomm** [comment]
I wouldn't call it arbitrary. Let's say common sense. ;)
It doesn't need to be that strict, let's say 30 - but there are some benefits of having this in general.
Talked to @woogerboy21, there are 108 users out there with longer names (31 chars and more).
Most of them being very weird and likely not used, a huge amount of them even tried to inject code!

<br>
>Why not just shrink the column anyway, and if a user has a long username, we can either truncate with ... or we can make it horizontal scroll

The user list of connected players is just an example.
But I don't like the idea of punishing all users (and making cockatrice a worse experience) with a horizontal scroll bar just because there is that one user with a (stupid?) 42 character user name for no reason.

I like the idea about truncating with `...`. It will have the same effect as a user name char limit for the interface and columns without limiting freedom of single players.
Chat won't benefit though and it sounds to me as it needs more code and special handling.

**Comment by ZeldaZach** [comment]
I'm a fan of limiting charnames. When I ran my VW, I had a 13 character limit because long names take up a lot of room in game (for us, in client) and it's just lame.

People can make clever & ez usernames usually between 8-10 characters.

Truncation of usernames in the menu list is a nice idea for sure, just I think for future users we should limit them down a bit.

**Comment by tooomm** [comment]
Oh sure, truncation could be done for existent users additionally to avoid running into problems!

**Comment by poixen** [comment]
You can make the user list thinner, though longer names will be truncated throughout the app anyway. Imagine I have the username "hellomynameisbobhowareyou1234567". This will be truncated in the following locations: creator column, user list, in-game user list, in game avatar name. This is inconvenient for all parties. The user cant see their name anywhere unless in chat, the other people cant see who they are playing, the chat will become a jagged mess and maybe more.

Im for limiting to 20 chars or something. 

Just as a side not, if we do change it, I just saw this code in server.cpp line 108 that would also need to be updated: 

```
if (name.size() > 35)
        name = name.left(35);
```

We should maybe also no allow more than 20 chars allowed in the connection dlg.

**Comment by woogerboy21** [comment]
With name restriction settings now being defined in the servatrice configuration file its up to the servers owner / operator to define the requirements.  Can this issue be closed?

**Comment by poixen** [comment]
Seems like it can be.
