### ISSUE TITLE
New Deck Editor needs UI Polish

### ISSUE THREAD

**Issue by Daenyth** [Cockatrice/Cockatrice#97]
- [x] Card movement icons need improvement (keycodes listed, better icons)
- [x] The color filter needs the user to enter "g" for "green", etc. It should handle the color words
- [x] Case handling might not be consistent
- [x] Hitting <kbd>-</kbd> on a filter doesn't remove it
- [x] Oracle text can't be viewed at the same time as image, and the toggle between is hidden in the menu
- [x] There's no "clear all" button for filters except hidden in the menu
- [x] cardname filter box is anchored to beginning of name instead of anywhere in name
- [x] Deck editor needs to do natural sort. Diacritics should come after their unmodified form. Eg `Jö` should come after `Jo` and before `Jw`

**Comment by ZeldaZach** [comment]
I marked some of the boxes as complete. This is making some nice progress :)

**Comment by ZeldaZach** [comment]
Want to look into the last few things on this ticket, @poixen ?

**Comment by ctrlaltca** [comment]
Two more issues has been closed in #1137. The only remaining issue is "Hitting - on a filter doesn't remove it".
Is this desiderable? Since the "add filter" hotkey is "enter", i'd see "delete/backspace" as its appropriate counterpart.

**Comment by ZeldaZach** [comment]
Yeah, I agree with using delete/backspace as a delete method
