### ISSUE TITLE
Can't log into server.

### ISSUE THREAD

**Issue by JineteDV** [Cockatrice/Cockatrice#972]
I'm a registered user with the name 'Jinete del Viento' and every time I try to log into the server it tells me 'invalid username'. What's the problem?

**Comment by ZeldaZach** [comment]
The woogerworks server specifically doesn't allow for usernames with spaces to login any longer.

I'll have another dev look into a workaround shortly. Sorry for the issues.

**Comment by poixen** [comment]
Incase other users come here.

The only chars available for usernames are now a-z, A-Z, 0-9, - and _

We are setting up a rename site, so you change your current login name.

I will post it here when it is ready.

**Comment by Daenyth** [comment]
Hang on, why are we rejecting previously valid usernames? This rule should
only apply to new accounts. We need to change this so we allow the name if
it's already registered

**Comment by ZeldaZach** [comment]
@Daenyth We made a tool to change usernames; http://cockatrice.woogerworks.com/changeusername.php

**Comment by Daenyth** [comment]
No, that's honestly not good enough. We should really let people continue to use the usernames they've been using.

**Comment by Daenyth** [comment]
I'll try to get some time this weekend to fix it

**Comment by poixen** [comment]
Fix what?

**Comment by Daenyth** [comment]
The fact that we've locked out a wide swath of existing users. I thought
the name restriction PR was applying for unregistered names

**Comment by poixen** [comment]
I did too originally, though the transition has been smooth from what I can tell.

We now only permit users with correct usernames to register AND login. The users with out of date names can use the tool to keep their account.

The userlist in the server is now uniform and tidy. Only a small % of users had special chars.

@woogerboy21 , @ZeldaZach and I talked about this when we realized and we all agreed that we liked the change.

**Comment by ZeldaZach** [comment]
I think I'm fine with temporarily re-enabling the login to allow people to know how to change their name, but all-in-all, I'd like to see only names that follow the standard format we have on the server.

**Comment by Daenyth** [comment]
If you all really think it's better than I suppose I'm in the minority here.

We should reach out to the chickatrice operator, I'm not sure they use the wooger management UI for accounts, so this change affects them.

Are there other servers out there?

This definitely needs to have a release note

**Comment by tooomm** [comment]
other server:
https://github.com/woogerboy21/servatriceadminwebui/issues/1#issuecomment-50531155

**Comment by poixen** [comment]
Ideally these would not be hard coded, they would be part of an external file, like the ini. That could be a way to go...
