### ISSUE TITLE
Annoyingly useless shutdown message

### ISSUE THREAD

**Issue by woogerboy21** [Cockatrice/Cockatrice#979]
So currently there is a button in the administration tab that you can schedule a server shutdown.  How ever the announcements for the server shutdown are hard set to popup on players screens every minute.  So if you attempt to schedule a shutdown say for an hour prior to the shutdown everyone playing gets an annoying popup every minute interrupting games etc when the shutdown time is a considerable period of time from happening.  I would like to see the functionality changed to do the following (other suggestions welcome).

When the shutdown button is used to bring down a server, the server should take the shutdown time and / by 2 unless the amount of time till shutdown is less than 5 minutes.  Then a counter should start and once the time / 2 is reached notify the users of the shutdown and start the process over again only using the new remaining time / 2.  So notifications would work as follows.  An admin would issue the shutdown and set the time for say 60min.  The first notification to clients would go out immediately.  The next notification would occur with 30min left before shutdown.  The next notification would happen at 15 min, the following would be 7(or8) min mark.  Then notifications at the 5,4,3,2,and 1 min mark.

Thoughts?

**Comment by tooomm** [comment]
Would be a very nice improvement! :+1: 

Keeping usefulness while dropping annoying popups every single minute.

**Comment by poixen** [comment]
Addressed in #1006

**Comment by tooomm** [comment]
If a new popup shows up it should close an older one before as well.
Otherwise there will be several messages stacked up and you need to click all of them if you are away from the pc and come back.

**Comment by woogerboy21** [comment]
Closing as the behavior is changed and a new issue has been created for further improvements.
