### ISSUE TITLE
no confirmation dialog if you close the client while being connected

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#982]
Closing an open client will disconnect you without warning and all open pm's etc. will be gone.

It just warns you if there are open games as well.

**Comment by Psithief** [comment]
This 'fix' is going to annoy me so much.

**Comment by Psithief** [comment]
@tooomm If the confirmation had a 10 second timeout (where if you don't respond within 10 seconds, the application closes) would this still fulfil the intent of the suggestion?

**Comment by Daenyth** [comment]
Why don't we just add PM history so that messages aren't lost, reopen the client and reconnect and they could come back up
