### ISSUE TITLE
OS X 10.10.3

### ISSUE THREAD

**Issue by emoreno619** [Cockatrice/Cockatrice#992]
I can't see any images. Have fiddled with options like 'download on the fly', 'hi-quality' and 'clear/reset images', even deleted image folder and re-run oracle and cockatrice...but the custom image folder always seems to be empty...

**Comment by woogerboy21** [comment]
The customs image folder will always stay empty.  It is used to place specific card images into that will trump any set url / image on a card by card basis.    So is the issue that your not seeing any images period or that you can't see images that are located in the customs folder?

**Comment by emoreno619** [comment]
Can't see any images period.

and thanks good to know.

**Comment by Daenyth** [comment]
Follow the instructions on debugging on the wiki and see what the console
output says when you try to load a card

**Comment by emoreno619** [comment]
From console:
Download failed: "Error downloading http://mtgimage.com/multiverseid/386626.jpg - server replied: Not Found" 
Picture NOT found, download failed, no more sets to try: BAILING OUT (oldset:  "KTK"  card:  "Plains" )

**Comment by ZeldaZach** [comment]
@emoreno619 That means your high-quality setting is still checked. Please uncheck/untick the "download HQ images" option.
