### ISSUE TITLE
missing 'trice icon for several dialog windows

### ISSUE THREAD

**Issue by tooomm** [Cockatrice/Cockatrice#998]
https://github.com/Cockatrice/Cockatrice/pull/840#issuecomment-81722310

Maybe other dialog windows than the listed ones are affected as well:
- `Show this user's games`
  (as poixen mentioned in his comment, if you open this and close Cockatrice, the user's games window won't close with the app)
- `Load deck from server`
- `Create token`
- `Game information`
- `Manage sets...`
- `Edit tokens...`
- `Reveal top cards of library` the one, where you put the amount of cards you want to reveal
  (maybe other reveal/show dialogs as well or where you get asked about how many (dice e.g.))

no icon:
![dialog window-noicon](https://cloud.githubusercontent.com/assets/9874850/7261257/96c03dea-e870-11e4-8712-8cc1bc385e6f.png)

should be:
![dialog window-withicon](https://cloud.githubusercontent.com/assets/9874850/7261258/9bf84f6e-e870-11e4-80cb-61e89d0170ab.png)

---
- `Die roll` got fixed: #1065

**Comment by poixen** [comment]
The reason that there is no icon is that the window has no attachment to a parent. Usually in the window constructor you can pass a pointer to the parent. Where the code is though, it is hard to determine who the parent is. 

The lack of a parent causes 2 issues:

 + no icon
 + window will not close when parent does (if you open a parent-less window then close the app the window will remain)

**Comment by tooomm** [comment]
Still exists in e50c201 (2016-05-31)
I was able to close the app itself while the `Edit sets...` dialog box was open.
Weird part is that if I enable a new set and hit `OK` I get th confirmation message and everything closes as usual. When Cockatrice gets started again for the next time the newly enabled set is enabled. So while the app itself is closed some components can continue to run and even write changes to files...
